### ISSUE TITLE
Better subtitle opaque box management

### ISSUE THREAD

**Issue by Susexe** [clsid2/mpc-hc#100]
Currently, the opaque boxes of subtitle lines are overlapping each other and cannot be divided. I remember it was possible before by decreasing the value of _Scale (y, %)_, which would, sadly, flatten a font, but still, it could be done. Also, when _Opaque box_ is enabled, shadows and outlines cannot be applied to fonts. PotPlayer has the _2nd outline_ option, but nothing similar for shadows. MPC-HC has none.

TL;DR: Make it so that the opaque boxes can be naturally shrank horizontally/vertically and shifted around, also make the _Shadow_ option functionality equivalent to the one when _Outline_ is enabled. Maybe allow negative values in the _Width_ and _Shadow_ boxes?

Please have a look at the images below.

Wanted result: https://i.imgur.com/G98NQBP.jpg
MPC-HC: https://i.imgur.com/QqLSQdH.png
PotPlayer: https://i.imgur.com/YIDkOTx.png

**Comment by clsid2** [comment]
I am not interested in changing this. Someone else would need to contribute a patch.

**Comment by Susexe** [comment]
Can you at least fix the bug that doesn't allow both XySubFilter and Internal Subtitle Renderer to be used at the same time? Everything's fine with a combination of DirectVobSub + Internal Subtitle Renderer.

**Comment by Susexe** [comment]
Could someone try and improve this? It's literally the only reason I'm still using PotPlayer for subtitled content. See the comparison image [here](https://i.imgur.com/wM3KqQT.png).
