### ISSUE TITLE
Whitelist of hosts for web server.

### ISSUE THREAD

**Issue by CrPO4** [clsid2/mpc-hc#1001]
Currently, there's only 2 security settings for the server: it's either allowed to everyone (which is unsafe) or it's allowed to no one except localhost (rendering it almost useless in most cases). But there are some "remote control" apps for phones that make use of this feature and since phones aren't "localhost" to use those apps you'd need to allow everyone to connect to MPC-HC.

I think such a whitelist will be greatly appreciated by quite a few people.

**Comment by clsid2** [comment]
Wrong. To get access to the web interface the "attacker" needs to have access to your local network first.

I am not interested in implementing this. Someone else would have to submit a patch. For example to add option to allow 192.168.*.*

**Comment by CrPO4** [comment]
Meant it more for privacy on local network than for "external attack", you definitely would need to go out of your way to make it "vulnerable" to public.

But I got your point, thanks for the answer, closing the issue.
