### ISSUE TITLE
[Feature Request/Question] How can I copy video URL that is opened with MPC

### ISSUE THREAD

**Issue by T1mL3arn** [clsid2/mpc-hc#1003]
Let's say I opened youtube video (like this https://www.youtube.com/watch?v=dQw4w9WgXcQ) with MPC and it is playing well and after a couple minutes I completely lost the youtube link to the video and I want to get the link somehow from MPC. My options are:

1. Look at the MPC window header and manually type link
2. or look at the same place for the video title and google it
![image](https://user-images.githubusercontent.com/9349164/111567356-8ba6e600-87ea-11eb-972e-c5bc8ea7220e.png)
3. [**Preferable way**] Copy the url from MPC (I did not find where I can do it)

If there is no such feature at all, would be nice to have it in video properties window somewhere near "Location" property 

![image](https://user-images.githubusercontent.com/9349164/111568581-bdb94780-87ec-11eb-9746-93eea65adaae.png)

As a workaround I can do "File -> Save Image" and get desired url from the image name (that is not convenient, I have to restore escaped slash chars).

**Comment by clsid2** [comment]
There is no way to copy the original URL. Playlist has option to copy location to clipboard in right-click menu, but that uses the processed URL.

I am not interested in adding it. I already have too much other stuff to do.

**Comment by clsid2** [comment]
I have changed it to show the original URL as the title.
