### ISSUE TITLE
[Feature Request/Question] Holding Wheel Right/Left in MPC-HC and making it stick, like holding Left/Right arrow keys

### ISSUE THREAD

**Issue by ionGL** [clsid2/mpc-hc#1004]
Hello.

So i got this logitech mouse with Left and Right moving wheel. I set the Wheel Right to jump forward small and Wheel left for left.

The problem is that once you click the wheel left or right and you hold it, it only jumps once and that's it, you have to click, click, click...

https://i.postimg.cc/jSRcRZf4/wheel-Right-Left.jpg

Holding left or right arrow on the keyboard (as set by me in the example above), continues to jump through the video.

How do i get the mouse command to act just like when i hold the left/right arrow keys on the keyboard, to make the jumps go for as long as i hold the Wheel Right/Left?

Holding left/right on the wheel sticks when used in chrome, youtube, wherever.

**Comment by clsid2** [comment]
Not possible at this moment.

**Comment by ionGL** [comment]
Oh, i see. I thought i was missing something and there might be a hidden setting somewhere.

But this think makes sense, right? Holding the button pressed should give the same behavior as holding the left/arrow keys and continue to jump forward/backwards, as selected.

The command is called left/right scroll in the logitech setpoint software.

I hold the right wheel button, as i smoothly right scroll in the Keys window, thinking "RepCnt" might help :)

Maybe in the future!

**Comment by cw2** [comment]
Hm, could not it be a mouse driver issue? Because I have tried Microsoft Ergonomic and Logitech G502 mice and in both cases mouse wheel left/right button is repeated in MPC-HC while holding and it jumps continously.

**Comment by ionGL** [comment]
It could be the way those mouse buttons are assigned. If they are seen as left/right button presses on the keyboard, they could behave just like the keyboard presses behave.
There is a way to change what the buttons do in the logitech software, but assigning them to Left/Right keystrokes breaks other stuff. As in you have to highlight the window where you use those buttons, plus the jumps are different from the default Left/Right Scroll, commands that work when you just hover the cursor over something that has left/right scroll in them.

[https://i.imgur.com/iZRkBnF.jpeg](url)

**Comment by clsid2** [comment]
Assign a keystroke to test if it really triggers multiple events when holding down the wheel.

If it triggers multiple events, then I see no reason why it shouldn't already be working in MPC-HC.
https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-mousehwheel
Only exception would be if WHEEL_DELTA is 0.

**Comment by ionGL** [comment]
I think cw2 is right. Could be a logitech driver/software issue. After i set the left and right moving wheel to work as left and right keyboard arrows, holding either doesn't stick in any program. It's just like a single left/right arrow press on the keyboard.
https://i.imgur.com/ff8iYdt.jpeg

Having them at default - Left/Right Scroll makes the command stick when holding on youtube for example, it jumps 5 seconds forward/back.

**Comment by clsid2** [comment]
You can also use Ctrl + vertical scroll to seek through a file.

I am closing this because it appears to be a driver issue.
