### ISSUE TITLE
Improve WebVTT markup support

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#1008]
@adipose: Hi, it would be nice if you can improve WebVTT support (at least hide markup) :)

Sample file: [8BIT-001_D_WEBVTT.zip](https://github.com/clsid2/mpc-hc/files/6175104/8BIT-001_D_WEBVTT.zip)

Screenshot: ![screenshot](https://user-images.githubusercontent.com/15793015/111863586-cf216180-895c-11eb-9233-aa11fe1866f8.png)

**Comment by clsid2** [comment]
The unsupported tag filtering is not applied yet. That is currently only done when parsing external file.

**Comment by clsid2** [comment]
I have applied quick hack to filter the tags.

**Comment by ale5000-git** [comment]
Here are explained also other things that may appear: https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#cue_settings

**Comment by ale5000-git** [comment]
I think now it should be mostly fine but what about `Timestamp tags` inside text?
These are the most annoying things to see.

**Comment by clsid2** [comment]
Those are already stripped I think. Otherwise give a sample file.

**Comment by ale5000-git** [comment]
These are the things like `<00:00:23.250>` inside the text in the above sample.

**Comment by clsid2** [comment]
Those are stripped.

**Comment by ale5000-git** [comment]
Good :)
