### ISSUE TITLE
Improve seeking in videos with missing keyframes 

### ISSUE THREAD

**Issue by JorgeR81** [clsid2/mpc-hc#1009]
Hi, 

This is not a very specific request, so feel free to change the title or close it, if you feel it's best.

I have some video files that might be damaged or missing keyframes. 
I noticed different players deal with these situations better than others. I don't know if there is an option that could be enabled, or if that's just the way the player works. 
For instance, in a 20 minutes video I can only seek the first and last 5 minutes, in the timeline. The rest of the video plays fine ( I can even increase the playback speed ), but I can't jump to a specific time between the 5 and 15 minutes time points.

- In **_Potplayer_**, if I try to jump/seek to the  ( e.g. ) 10 minutes time point, I automatically go to the last seekable point ( the 5 minute time point ). This happens instantly, the application does not hang or anything. 
So the user feels conformable with the player, when it's trying to find the seekable sections in the video. 

- In **_mpc-hc_** and **_mpv_**, if I try to seek beyond the seekable range, the video gets paused. It's actually a bit scary because It seems the application is hanging, but if you click in a the seekable section, it starts playing again, after a few seconds.
So it's not very fun to use these players in these situations, especially when you don't know the video it's damaged or which parts are not seekable. 

- In **_VLC_**, after 3 or 4 seconds of buffering ( they show a yellow progress bar, over the timeline ) it actually manages to get to the exact point I want and the video plays normally. So it seems VLC found a way to solve this. 

If it's not possible to do this in mpc-hc, it would be nice, if the Potplayer solution was used. 

Thanks
Jorge Rodrigues

**Comment by JorgeR81** [comment]
I just tried the players keyframe seeking options, with some interesting results: 

- In **_VLC_**, if I enable "_fast seek_'', ( the tool tip reads: "_favor speed over precision while seeking_" ), it behaves like Potplayer.
- In **_Potplayer_**, if I disable "_jump to keyframe_" it behaves like mpc-hc and mpv.
- In **mpc-hc**, the behaviour it's the same with "_fast seek (on keyframe)_" disabled or enabled (for the "_latest keyframe_" and  "_nearest keyframe_" options).

**Comment by clsid2** [comment]
Your file is broken.

Use MkvToolNix to remux it. That will add a proper seek index.

**Comment by JorgeR81** [comment]
OK, thanks for the tip.
