### ISSUE TITLE
compatibility with Minilyric broken

### ISSUE THREAD

**Issue by tswntk** [clsid2/mpc-hc#101]
Minilyric will just stutter at the top of the lyric window. clicking the seek bar on MPC will make the lyric sync correctly for a split second then go back to the top.

Issue can be trace back to 1.7.4. Works fine on 1.7.3

PS. Minilyric has stopped development but I have yet to find an alternative that I like (personal preference).

**Comment by clsid2** [comment]
Sorry, but I am not interested in this. If it doesn't work it is the fault of Minilyric.

**Comment by tswntk** [comment]
Fine, you are not interested is all that matters and I can respect that.

But its not fair to simply state that "If it doesn't work it is the fault of Minilyric"
I would view this in two different angles
1. Minilyric didn't catch up with changes in MPC-HC (development has stopped too)
2. MPH-CH didn't maintain backward compatibly (in this aspect). Everything has bee working up to 1.73 and broken ever since 1.74.
If the fix only involve a few lines of codes, I would hope someone could fix it with a fork.

**Comment by clsid2** [comment]
Well, then first figure out what change 'broke' it. You can't expect me to invest time in testing some third party software that broke 5 years ago.

**Comment by tswntk** [comment]
As I said, it is perfectly fine and I respect the fact that you are not interested in this "issue"
But can you at least kept it open so someone else who is familiar with MPC coding might pick it up and "fix" it? Or you can totally ignore this comment if you really don't want to re-open this "issue"

I am not familiar with the structure of MPC but I guess it have to do with the current playing time.
1. Minilyric can't find the correct playing time so it just stays at the top
2. MPC-HC did present to Minilyric the playing time the old way (like in 1.7.3) momentarily the moment the seek bar is manipulated
3. Minilyric's lyric editor did make MPC-HC jump (seek) to specific positions correctly

**Comment by clsid2** [comment]
There aren't any other active people who are familiar with the code. And those that do contribute code only care about their own issues.
