### ISSUE TITLE
Washed out colors in MPC-HC compared to other players

### ISSUE THREAD

**Issue by MaciejGorczyca** [clsid2/mpc-hc#1010]
Hey.

I started to have washed out colors since a week or two ago. I upgraded to RX 6800 XT around that time so it might be related (I have some other driver/monitor issues).

Basically all the colors are a bit washed and blacks are basically gray. I tried to reset settings to default, updated MPC-HC, tried to play with rendering options and color outputs but there was no change.

I attached screenshot showing the difference between MPC-HC and MPV.

![2021-03-21-00-31-14-454-1055x1074- SubsPlease _Jaku-Chara_Tomozaki-kun_-_03_(1080p)_](https://user-images.githubusercontent.com/26925976/111888492-48f92f80-89dd-11eb-8e9d-7530d1ac1654.jpg)

If there are any logs or info you require please let me know.

**Comment by lifegpc** [comment]
Maybe you can try set your video renderer to MPC-VR or MadVR in Output settings page.

**Comment by clsid2** [comment]
It is not a bug in the player. I can't help you with driver issues.

Remove your driver with DDU and do a fresh installation.

**Comment by clsid2** [comment]
Changing hardware acceleration setting in the video decoder might help bypass the driver bug.

**Comment by MaciejGorczyca** [comment]
Solved by changing default rendered to MPC Video Renderer AND forcing Direct3D 11. It was showing washed out colors without Direct3D 11 too.

Radeon drivers are a mess... Probably upgrading to RX 6800 XT introduced that issue for some reason. Thanks for your suggestions!

Comparison below:

![2021-03-21-01-09-26-025-1920x1080- SubsPlease _Horimiya_-_03_(1080p)_ F7587910 mkv](https://user-images.githubusercontent.com/26925976/111889064-59f86f80-89e2-11eb-8b08-8c666c56daa9.jpg)
![2021-03-21-01-09-17-853-1920x1080- SubsPlease _Horimiya_-_03_(1080p)_ F7587910 mkv](https://user-images.githubusercontent.com/26925976/111889065-5a910600-89e2-11eb-9101-7d06928908d4.jpg)

**Comment by clsid2** [comment]
Please use the AMD Driver Bug Report tool to report his issue:
https://www.amd.com/en/support/kb/faq/amdbrt

DXVA2 decoding + Direct3D9 rendering = washed out video

**Comment by MaciejGorczyca** [comment]
I tried default settings and renderer and LAV Video Decoder (internal) set to none for hardware acceleration but the "display statistics" info still showed my GPU as a device used to display stuff - not sure if it's only used to display frames or to render them too. Not sure if LAV VD is used for decoding/rendering when using default renderer too (don't know MPC-HC structure that well).

Anyway it definitely has some issues with Direct3D9 rendering and I will be reporting it to AMD. Thank you!
