### ISSUE TITLE
The color of the drop-down list in the video decoder properties is wrong in dark mode.

### ISSUE THREAD

**Issue by FX8350** [clsid2/mpc-hc#1014]
Enable dark mode and hover the mouse cursor over the item in the drop-down list of the video decoder, the item colors will be wrong.
![スクリーンショット 2021-03-21 143726](https://user-images.githubusercontent.com/10481430/111894996-f9554b00-8a52-11eb-8003-ce121715c0f7.png)
![スクリーンショット 2021-03-21 143705](https://user-images.githubusercontent.com/10481430/111895006-0bcf8480-8a53-11eb-95d4-028019a27a8d.png)

**Comment by adipose** [comment]
Confirmed.  Page is not totally controlled by MPC-HC, and the theming of that window doesn't seem to be sticking.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1056
