### ISSUE TITLE
ToDo: WebVTT improvements

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#1017]
[1] Alignment tags could be converted into SSA tag `{\anX}` (were X is a position value)

[2] I have seen several files were each line is repeated twice. So identical start/stop times and text. These duplicates should be removed.

[3] Possibly parse style information and convert into SSA

```
WEBVTT
Kind: captions
Language: en
Style:
::cue(c.color000000) { color: rgb(0,0,0);
 }
::cue(c.colorFEFEFE) { color: rgb(254,254,254);
 }
##

00:00:00.174 --> 00:00:00.241 line:85%
<c.colorFEFEFE>example text</c>
```

**Comment by ale5000-git** [comment]
While I agree that repeated lines are annoying they may be intended: For example display the same text 2 times with a little position change to create a custom shadow effect or also display different text at different position but same time.

I think the correct solution to duplicate text is to support the various positioning elements so the second text is just displayed on top of the first.

**Comment by clsid2** [comment]
All the duplicates I saw were exact duplicates. No differences. NONE.

I decide what I implement. I don't have any interested or motivation at all to fully implement the WebVTT standard.

**Comment by ale5000-git** [comment]
In this case it is fine I think, but there should be a bug in the software creating subtitles otherwise it doesn't make sense.

**Comment by ale5000-git** [comment]
The subtitles here: https://github.com/pinterf/xy-VSFilter/issues/18#issuecomment-803512511
can be taken as sample for duplicate (and quadriplicate subtitles).

**Comment by adipose** [comment]
Yeah, it doesn't seem like valid data, but just discarding exact duplicates seems good to me.  I can't see any value.  Even if you wanted to do an effect of the st showing up twice, they would show up at the exact same time anyway.

Does it actually cause any problem today, having duplicates (maybe a flicker)?

**Comment by clsid2** [comment]
It currently shows duplicates as two repeated lines.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1023

This handles 1-2.

**Comment by adipose** [comment]
By the way, the webvtt file mentioned above that has duplicates contains a style block.  But it's not correctly formatted.

```
Style:
::cue(c.color000000) { color: rgb(0,0,0);
 }
::cue(c.colorFEFEFE) { color: rgb(254,254,254);
 }
```

Spec says:

```
You can also define the style directly in the WebVTT file. 
In this case, you insert your CSS rules into the file with 
each rule preceded by the string "STYLE" all by itelf on a 
line of text, as shown below:
```

`Style:` vs `STYLE`

Wouldn't be hard to support the first, too, but maybe this webvtt is just produced with a buggy generator?

**Comment by clsid2** [comment]
Yes, might be invalid. We can have a look at it again in the future. The style stuff is not really important right now.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1026

This handles styles.  It supports background and foreground colors in the style blocks (both rgb and named colors).  Maybe we need to add rgba later.

Looking at webvtt spec, it's pretty ambiguous what kinds of style changes they permit.  Their only examples are foreground color and background *image*.  And the only tag they show being styled is a `<b>` tag.  Taking the linked (buggy) vtt file above, you can see they used "c.colorFEFEFE" as a custom tag, and then coded it with rgb(). It seems like a bad choice for tag name, because it looks a lot like the named color tag names (<c.green>).  But, it currently works fine because the regex I used only checks for lower case (so "green" is valid but "colorFEFEFE" is not).

I'm not sure if we need to restrict the <c.color> tags to only valid named colors...otherwise it's a potential bug if they do <c.colorfefefe> for example.  One solution is to not set "white" as the color when it fails to parse as the SSAColorTag function does today, but to just leave it alone.

**Comment by clsid2** [comment]
Here is example with background color (and alpha channel):
https://developer.mozilla.org/en-US/docs/Web/CSS/::cue

https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#webvtt_body
See example 14.
"colorFEFEFE" is a classname for a CSS style.
I suspect that any name is valid, and that for example <c.green> simply uses a predefined standard style.

**Comment by adipose** [comment]
Thanks for the cue link, I missed that when reading the spec.  I see now that the "class tag" in webvtt is simply `<c>`, which is a convenient way to apply a class style to a cue without introducing additional changes.  Thanks for pointing that out.

But now, I'm wondering where the spec is stating you can just do "<c.red>".  I can't find it anywhere.  So those predefined styles may not be standard at all?  If so, it would be simpler to just handle them all as CSS classes, as you could have conflicts:

::cue(c.red) { color: rgb(128,0,0); }

**Comment by clsid2** [comment]
Defaulting to white if color is unknown is correct:
https://www.w3.org/TR/webvtt1/#applying-css-properties
Also useful:
https://www.w3.org/TR/webvtt1/#css-extensions-introduction
Color list:
https://www.w3.org/TR/css-color-4/#named-colors

CSS styles can be defined externally in the HTML document itself. Those would be unavailable to us when parsing the subtitle file.

Live test:
https://ronallo.com/demos/webvtt-cue-settings/
This seems to indicate that (at least) red/blue/green/yellow are standard colors to use in a class tag (<c>).

**Comment by adipose** [comment]
He defined them here:

view-source:https://ronallo.com/demos/webvtt-cue-settings/webvtt-cue-settings.css

Guess they are non-standard.

**Comment by ale5000-git** [comment]
The default classes are these: https://w3c.github.io/webvtt/#default-text-color
I think others are just defined elsewhere in the subtitle or in the webpage.

And default classes can be overriden.

**Comment by adipose** [comment]
Thanks. That's a pretty short list. I am almost inclined to extend it to the master list of html colors even if they are non standard. It wouldn't surprise me if they expanded it later.

@clsid2 , do you agree?

I will redo the code to parse the class and use the default style, then override style if defined.

Do we want to support a css file with the webvtt? Depending on how the vtt file is acquired, the user may be able to get loaded css files as well. YouTubedl for example could be made to grab it.

**Comment by clsid2** [comment]
Color list can be expanded if there are examples that use it.

If youtubedl does not yet support css, then there is no point in supporting that. Keep things simple.

**Comment by adipose** [comment]
This should be done.  Could use some testing, maybe.  Not implemented:

1. ID selectors like ::cue(#test) { color: lime; }
2. CSS selectors like ::cue(v[voice="Esme"]) { color: cyan }
3. Various formatting elements like "line: 85%"

**Comment by ale5000-git** [comment]
Two things that may be important for Japanese subtitles are vertical cue and ruby position: https://medium.com/google-exoplayer/improved-japanese-subtitle-support-7598fee12cf4
