### ISSUE TITLE
Random BSODs

### ISSUE THREAD

**Issue by akdevservices** [clsid2/mpc-hc#1018]
Random BSODs (memory management) on ver. 1.9.10, I didn't figure out what causes them. Ver. 1.9.8 seems to be working OK.

**Comment by clsid2** [comment]
BSoD => Driver or hardware problem

https://www.nirsoft.net/utils/blue_screen_view.html

**It is not the fault of MPC-HC !!!**

**Comment by akdevservices** [comment]
Guys, treating issues like that is not the right way to success of your software. The point is that the latest version of MPC HC (ver. 1.9.10) crashes the OS with the same video files and the same NVIDIA driver and ver. 1.9.8 and below doesn't. That's the issue you should think about (and what you have changed since 1.9.8 that might cause the problem) and not blindly assign blame.

**Comment by ale5000-git** [comment]
It is possible that an app trigger a crash but the crash is caused by a bug in the OS and/or in drivers.
Example: if you walk on a crumbling bridge and the bridge falls you might think it is your fault but the fault lies in the bridge.

**Comment by ale5000-git** [comment]
BlueScreenView is a good software to discover the driver that caused the crash but most of the time just updating the audio/video driver is enough to fix it (if it happen during video playing).
In other cases it can also be the driver loaded from the antivirus.

**Comment by clsid2** [comment]
The fact that 1.9.8 does not trigger a BSoD does not mean there is a fault in 1.9.10.

Bugs in user-mode applications like MPC-HC cause application crashes.
Bugs in Windows kernel, or drivers that run at kernel level, cause BSoDs.

So start by installing an older version of your graphics driver, and then come back to apologize and admit that you are an idiot.
