### ISSUE TITLE
Audio of video plays but picture does not

### ISSUE THREAD

**Issue by holygamer** [clsid2/mpc-hc#1019]
Version: 1.9.10 x64
I'm also trying version 1.9.7 x86 portably after a friend advised me that later versions are buggy. 

When I double-click on a video file the MPC-HC windows opens and I can hear the audio play but the video has no picture. I need to double-click inside the window for the picture to play. If I then double-click inside the window to play it full-screen, nothing happens. If I close the window and play the video again then it plays properly. 

I've been using MPC-HC for years and I've never had this problem before. I tried using a different portable version and it somehow has the same issues.

Also why are my settings remembered when I use a different Portable version? Shouldn't the settings file be contained in the portable directory?

**Comment by clsid2** [comment]
The ZIP is not strictly portable. It is only portable if you enable the option to store settings in .INI file.

For the black screen problem I can only advice the following:
Disable hardware accelerated decoding in the internal video decoder.
Update your graphics driver.

**Comment by holygamer** [comment]
Thanks. I updated my GeForce GTX 980Ti drivers. I downloaded the 32-bit MPC-HC then enabled .INI file then reset everything to default settings.

I went into Internal Filters > Video Decoder. I set “Hardware Decoder to use” to None. However the problem remains. Is there anything else I can do? Very strange as I've never had this problems in years of using MPC-HC.

**Comment by clsid2** [comment]
If it only happens with a specific file, then I need details about the file.
Menu > File > Properties > MediaInfo

You can try a different video renderer:
Options > Playback > Output
Default one is "Enhanced Video Renderer (Custom Presenter)".

**Comment by holygamer** [comment]
When I click on File the program freezes. I have to end the task in task manager to close it. Also I changed the Exit shortcut to the Escape key and when I press the Escape key the program freezes.

I then reset the settings to default and it didn't make a difference at first then after playing a few videos it started working again where it doesn't crash when I pressed the Escape key. I was then able to click on File to get the info you wanted.

The files are nothing special. Just x264 1080i or 1080p and radio MP3s. 

General
Unique ID                      : 20710274364043691234419943591116175703 (0xF94A75C83DEED1AA01F4FFFF4767957)
Complete name                  : L:\G Drive\To Check Sync\Uploading to Lightspeed\F2 2021 01 Race 1-3 (replays).mkv
Format                         : Matroska
Format version                 : Version 4
File size                      : 28.0 GiB
Duration                       : 3 h 51 min
Overall bit rate mode          : Variable
Overall bit rate               : 17.3 Mb/s
Writing application            : VideoReDo (Lavf56.25.101)
Writing library                : VideoReDo (Lavf56.25.101)

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L4
Format settings                : CABAC / 2 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 2 frames
Format settings, GOP           : M=3, N=12
Codec ID                       : V_MPEG4/ISO/AVC
Duration                       : 3 h 51 min
Bit rate mode                  : Variable
Maximum bit rate               : 30.0 Mb/s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 25.000 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Interlaced
Scan type, store method        : Separated fields
Scan order                     : Top Field First
Default                        : No
Forced                         : No
Color range                    : Limited
Color primaries                : BT.709
Transfer characteristics       : BT.709
Matrix coefficients            : BT.709
Duration_Source                : General_Duration

Audio
ID                             : 2
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Codec ID                       : A_AAC-2
Duration                       : 3 h 51 min
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 46.875 FPS (1024 SPF)
Compression mode               : Lossy
Language                       : English
Default                        : Yes
Forced                         : No
Duration_Source                : General_Duration

**Comment by clsid2** [comment]
For File menu issue:
Options (press O) > Player > Disable open disc menu

For the video issue, please copy filter list during playback:
Menu > Player > Filters

**Comment by holygamer** [comment]
Thanks. The freezing issue when trying to close the program is now fixed. But the files not playing issue remains.

Here's the info you asked for:

Filters currently loaded:
  - Default DirectSound Device
  - Enhanced Video Renderer (custom presenter)
  - Audio Switcher
  - LAV Video Decoder (internal)
  - LAV Audio Decoder (internal)
  - LAV Splitter Source (internal)

**Comment by clsid2** [comment]
The filter list includes a video decoder, so I don't know why you get black video. I need a sample video to test if it also happens on my computer.

Maybe enabling Yadif deinterlacing in the video decoder settings will help.

**Comment by holygamer** [comment]
1080p sample video is [HERE](https://drive.google.com/file/d/1k_6KuYQ2OJcigmlB5r5y23yXvihe_C-z/view?usp=sharing)

The video not playing seems to only happen on progressive videos not interlaced videos. When a video doesn't play but the audio does I have to double-click in the window to make the video play THEN when I exit the program and open another video that video will then play correctly. However the next video will have the problem again.

I enabled Yadif 25p/30p and also tried  50p/60p and neither option fixed the problem.

**Comment by clsid2** [comment]
That sample plays without problems here.

Try with latest development build:
https://github.com/clsid2/mpc-hc/releases/download/1.9.10.16/MPC-HC.1.9.10.80.x64.exe

And reset settings:
Options > Miscellaneous > Reset

The described symptoms indicate an issue with the graphics driver. Use Display Driver Uninstaller (DDU) to remove it and try an old driver from around the time the 980 was released. The recent drivers of NVIDIA are pretty bad.
