### ISSUE TITLE
WebVTT size issue

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#1027]
The subtitle is the same.

Embedded VTT:
![embedded-vtt](https://user-images.githubusercontent.com/15793015/112679343-5fcfd400-8e6c-11eb-9ab4-3d116d500c8e.png)

External VTT:
![external-vtt](https://user-images.githubusercontent.com/15793015/112679381-68280f00-8e6c-11eb-83e8-e42a4e003d83.png)

**Comment by ale5000-git** [comment]
[Test.zip](https://github.com/clsid2/mpc-hc/files/6213784/Test.zip)

**Comment by clsid2** [comment]
Forcing "Default Style" also has issues for embedded sub.

**Comment by ale5000-git** [comment]
I have never changed default style settings.

**Comment by clsid2** [comment]
It is a different issue. I just added it because it may have same cause as yours.

**Comment by 54m4d** [comment]
@ale5000-git How did you open the video file? i get this:

![Capture 15_04_2021_05_45_26](https://user-images.githubusercontent.com/52612348/114811124-cf6f1a00-9dad-11eb-96e0-11ea9e225d7e.png)

**Comment by ale5000-git** [comment]
I install MPC-HC and LAV Filters as part of the K-Lite Codec Pack.
The MPC-HC inside K-Lite Codec Pack is usually updated earlier and LAV Filters inside K-Lite Codec Pack contain additional patches.

Open the file with GraphStudioNext (x64) to see what is the problem on your pc.

**Comment by 54m4d** [comment]
I'm also using the one from codecguide,

I opened the file in GraphStudioNext but unfortunately i don't know how to use this application, i really want to know why i can't play this video file.

![Capture 15_04_2021_22_15_47](https://user-images.githubusercontent.com/52612348/114933181-af386d00-9e38-11eb-908c-0de6a7abb5a5.gif)

**Comment by clsid2** [comment]
Enable "msrle" in LAV Video Decoder. Should be enabled by default already though.

**Comment by 54m4d** [comment]
I want to try, but where should i do that?

![Capture 16_04_2021_01_50_41](https://user-images.githubusercontent.com/52612348/114952339-58da2700-9e56-11eb-9679-cbc4130d68d4.png)

**Comment by Dorno** [comment]
You have to enable it under "Formats" tab inside the LAV Video Decoder options. Though you don't seem to have one. Perhaps you are using the internal filter?

**Comment by 54m4d** [comment]
How can i check if i'm using the internal filter or not?

**Comment by Dorno** [comment]
There should be a setting under options called "internal filters" or "filters". Make sure you uncheck everything. This will require that you have external versions of those filters installed or the videos won't play.

Alternatively add LAV Video Decoder under "External Filters". If you have LAV installed it will show up in the list under external filters/add filters.

**Comment by 54m4d** [comment]
You are right, i found that the internal filters were enabled, i also didn't have any extra external filters installed.

It seems like i have to install the external version of LAV?

Demo:

https://user-images.githubusercontent.com/52612348/162597449-abcbf160-f4ba-4123-920b-e3947c641db9.mp4

**Comment by Dorno** [comment]
Yeah to get LAV filters to show up in the external section you have to install them. You may not even need to add them as external filters once you install them. Once you disable all the internal filters the player will attempt to use any external filters.

**Comment by clsid2** [comment]
Fixed
