### ISSUE TITLE
It seem that all the windows media player haven't nice thumbnails.

### ISSUE THREAD

**Issue by channingbox** [clsid2/mpc-hc#103]
The only software is "Icaros",but it too heavy,it should a part of player. and it hasn't nice thumbnails.the android player "mx player"has nice thumbnails,but i don't know is it possible migrate to the windows platform.

**Comment by clsid2** [comment]
No, a shell extension for Explorer and a player are two totally different things.

This GitHub issue tracker is for bug reports. I am not interested in feature requests.
