### ISSUE TITLE
MPC 1.9.10 crash

### ISSUE THREAD

**Issue by zhenjie1999** [clsid2/mpc-hc#1030]
![QQ截图20210329023733](https://user-images.githubusercontent.com/75268245/112761852-23e96a00-9038-11eb-991f-fcf0125cabb6.png)
[system support utility report.txt](https://github.com/clsid2/mpc-hc/files/6223629/system.support.utility.report.txt)
[DxDiag.txt](https://github.com/clsid2/mpc-hc/files/6223632/DxDiag.txt)
These video when have this crash problem when I play with SVP
[movie sample.zip](https://github.com/clsid2/mpc-hc/files/6223637/movie.sample.zip)
![image](https://user-images.githubusercontent.com/75268245/112879921-c66f1f00-9104-11eb-928d-846b3dc5a1d0.png)
![image](https://user-images.githubusercontent.com/75268245/112879950-d25ae100-9104-11eb-8e77-784069949b62.png)

**Comment by clsid2** [comment]
One of the Avisynth plugins that is used by SVP is probably causing the crash. I can't help you with that. You need to have SVP team reproduce and fix it.
