### ISSUE TITLE
Subtitle does not render properly using internal but does using AssFilter

### ISSUE THREAD

**Issue by Revenent** [clsid2/mpc-hc#1031]
Subtitle does not render properly using internal but does using AssFilter.

Repro:
https://www.erai-raws.info/anime-list/non-non-biyori-nonstop/ -- Episode 12 (1080p)

Sorry, couldn't cut the file in a way that seems to repro other than using the full file.

Start playing at 4:30.  Difference starts at 4:46.
Internal does not show the lines: "The ceremony's over." and "Let's go home."

MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.10 (29a1254b5)
    Compiler:           MSVC v19.26.28806
    Build date:         Feb 25 2021

LAV Filters:
    LAV Splitter:       0.74.1.92
    LAV Video:          0.74.1.92
    LAV Audio:          0.74.1.92
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 10.0 (build 19042)
    Version:            10.0 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    GPU1:               NVIDIA GeForce GTX 1660 SUPER (driver version: 27.21.14.6140)
    GPU2:               NVIDIA GeForce GTX 1660 SUPER (driver version: 27.21.14.6140)
    GPU3:               NVIDIA GeForce GTX 1660 SUPER (driver version: 27.21.14.6140)

**Comment by clsid2** [comment]
Try with latest development build:
https://github.com/clsid2/mpc-hc/releases

Then it should work again.
