### ISSUE TITLE
Ass Subtitle files containing =(equel signs) give syntax errors 

### ISSUE THREAD

**Issue by Rikitik** [clsid2/mpc-hc#1038]
Subtitle lines containing the Equel sign(=) in atleast *.Ass subtitle files give syntax errors
Tested the same files with VLC no issue removing the = sign fixes the error  but is not proper behavior?

**Comment by clsid2** [comment]
I added a = to a dialogue line and it worked just fine.

So I need a sample ass file that triggers this problem.

**Comment by Rikitik** [comment]
https://paste.simplylinux.ch/view/47eaa6f6

**Comment by clsid2** [comment]
Fixed

**Comment by Rikitik** [comment]
What exactly did you find if it was not the "=" that caused it?

**Comment by ale5000-git** [comment]
Probably this: https://github.com/clsid2/mpc-hc/commit/c05a8bec4d87d2f4f6e8e2ca7993e202afb796e2
