### ISSUE TITLE
Please Support for Amiga File Formats !

### ISSUE THREAD

**Issue by TP555** [clsid2/mpc-hc#1039]
Hi

can you please add Support for Play MOD , IT , XM , S3M Files  ?
Also all know from Amiga. !

**Comment by NanaMizukiAnother7** [comment]
I think that Media Player Classic - Home Cinema doesn't support these file formats yet because it is getting too old...

The current developer clsid2 might add these on MPC-HC.

**Comment by clsid2** [comment]
Native support for those formats is not available.

But you can play them if you install this codec:
https://rwijnsma.home.xs4all.nl/dc-bsm/index.htm

Note: this codec is only available as a 32-bit version, so you need to use the x86 version of MPC-HC.

**Comment by ale5000-git** [comment]
Doesn't the codec pack already include this codec?
