### ISSUE TITLE
Play with MPC-HC with Multible Files fail on Windows 7

### ISSUE THREAD

**Issue by username7291** [clsid2/mpc-hc#104]
In Windows 7 many times files missing in the playlist. I select for example 26 avi/h264 Files, and in the list are 10 files. It fails in about 80% of the trys. This happend on WindowsXP before too, but in <1% of trys(i think if the cpu is on high load). If you use "Add to MPC-HC Playlist" it always works but you have to be over the first file while using the context menu to get the correct order.
On Windows 7 the time between Videos is longer(Pause/Gap).
On Windows 7 the Arrow Left key goes to the another Video, but its set to go 1 Frame Backwards. Arrow Right goes 1 Frame forward like it should.

The Windows 7 Hardware is newer&faster.
It makes no difference if you use Software Decoder or Intel Quick Sync.

**Comment by clsid2** [comment]
Are you selecting the files in the Open dialog of the player, or in Explorer? Explorer has a limit of 15 files. But a registry tweak exists to increase that value. If you are selecting in the player, then there might be a bug.

Arrow keys works fine for others. Reset you settings (options > miscellaneous > reset). Default action is 5 second jump, so you need to adjust in options if you want framestepping.

You should not use QuickSync. You should use DXVA2 native.

**Comment by username7291** [comment]
The dialog on Explorer. I know about this strange Windows7 limit. I tweak the registry already(with out the modification there is no mpc-hc entry in the context menu).

The Arrow keys Settings are correct 1 frame back or 1 frame forward, but only forward works on Win7.
It works only if you open just 1 file, on multible it goes to another file. It Works on avi/Mpeg-4/h.263
but not on avi/avc/h264. All work on XP.

None or QuickSync acts same, DXVA2 plays wrong fps(to fast) at end of the video.

**Comment by clsid2** [comment]
Adding files works correctly on my Win7 system. I even tried with super long filenames.

Going to next/previous file is a different keycombo. You must be doing something wrong. Reset your settings! Ctrl+Left/Right is default for framestepping.
Frame stepping backwards is slow on video formats (like H.264) that use references frames. Then decoding a frame can depend on several preceding frames. Decoding in backwards order is very inefficient in that case.

Give a link to a file that has wrong fps.

**Comment by username7291** [comment]
Is it Win7 64 Bit?. Have you tryed about 26 files? Open from Windows Explorer, not "Add to MPC-HC Playlist". Add to MPC-HC Playlist works like it should. If yes have you counted that all 26 files are in the playlist of MPC-HC?
I too tryed with avi/h264 & shorter Filenames, 26 Files are selected, only 18 are in the Playlist.
Its a fresh installed Win7 64 Bit, it shouldnt behave different than other systems. Exept you have
a faster processor, cause it happens too(but very rare) on WinXP on high cpu loads. My is i3 1.7GHZ mobile.

I reset it already and installed another Version(deinstalled with delete all settings).
On XP or Win7 with only 1 File open, it doesnt go to another File, but it cant really show the frame backwards i think cause of duration about of 2 seconds and having only 1 Ref Frames. Means on xp i need more times press Arrow right until the first frame and then go again forward.
With Win7 and avi/h263 and multible files it works likes it should, means its impossible be a problem of the keyboard settings. Possible its a K-Lite codec bug, cause its a new version/64 bit and use LAV for all instead of ffdshow, maybe it produces a exeception and causes MPC-HC to skip to another file.

**Comment by username7291** [comment]
Found it the default setting Video Renderer  "Enhanced Video Renderer (custom presenter)" causes all these Bugs.
I set it to "System Standard" and all bugs are gone, i tryed 5 times, everytime all 26 files was in the list.
Arrow Right works again like on XP. MPC-HC plays fast&without black gap between the videos.

**Comment by clsid2** [comment]
If you select multiple files and use Play/Open in Explorer, then it will actually launch a new instance of the player for each file. The only reason why it can add files to playlist is because of a workaround in the player. It checks how much time has elapsed between launching files. If it is less than 500 milliseconds, file get added to playlist. Otherwise it is opened normally, clearing current playlist. I can consider increasing this to 1 second. But proper way to add files to playlist is to use "Add to MPC-HC Playlist".

Disable hardware decoding in the settings of LAV Video decoder. That should solve the backwards framestepping. System default renderer is very basic and doesn't support (DXVA2 native) hardware acceleration. Hence the reason why it works in that case.

**Comment by username7291** [comment]
I understand, yes increasing to 1 second may help if people require to use another renderer or have
a slow system.

The backwards frame stepping(going to another File instead) is too solved by using System-Standard renderer.
Just with 1 Ref frame Video i cant really go back until the Ref frame is reached, but thats the same with XP, that dont disturb much. It doesnt change with LAV hardware(DXVA2/Cuda/QuickSync)/software decoding.

**Comment by clsid2** [comment]
The video renderer itself has no effect on how seeking or framestepping is performed by the player. Frame stepping works fine with EVR-CP.
