### ISSUE TITLE
Installer build failed.

### ISSUE THREAD

**Issue by ageback** [clsid2/mpc-hc#1041]
**What I did:**
build.bat installer

**What issue I met:**
The main MPC-HC.exe built successfully. But installer built failed: 
`mpc-hc\distrib\custom_messages_translated.iss  Line 37: Unknown language name "bg"`

**What's expected:**
define "bg" in mpc-hc_setup.iss

**PS:**
pt_PT has the same issue.

**Comment by clsid2** [comment]
Will fix that soon.
