### ISSUE TITLE
What im supose to do to use ffdshow

### ISSUE THREAD

**Issue by Ramonlaw** [clsid2/mpc-hc#1042]
Hi i wanna use ffdshow to use an avisynth script... but the ffdshow icon is not showing tray

![image](https://user-images.githubusercontent.com/77369336/113710537-360f7c00-96ba-11eb-9c9a-4c9f156e645a.png)

i aready uncheck all this internal filters

![image](https://user-images.githubusercontent.com/77369336/113710922-b504b480-96ba-11eb-8d60-be73a8bbf50c.png)

**Comment by clsid2** [comment]
1) Enable all internal filters!
2) In External Filters, add "ffdshow raw video filter" and set it as preferred.

**Comment by Ramonlaw** [comment]
ok i  got it but now my audio is crackling i just wanna watch my videos in 60fps with avisynth script

**Comment by clsid2** [comment]
I can't help you with that.

Your system might be too slow. That can result in audio problems.
