### ISSUE TITLE
[FR] finer playback speed control with pitch correction

### ISSUE THREAD

**Issue by mrx23dot** [clsid2/mpc-hc#1043]
Please add youtube like playback speed controls i.e.:
1.25x
1.5x
1.75x

with pitch correction.

Currently it only supports 2x which is too fast for lectures, also sound turns into high pitch.

**Comment by clsid2** [comment]
Already exists!

Menu > View > Playback Rate
Options > playback > Speed step

Options > Playback > Output > Audio Renderer > Internal Audio Renderer
That one has automatic pitch correction

**Comment by mrx23dot** [comment]
Works great!
Might worth decreasing default playback steps to 25% from 200%.

**Comment by ToxicSmurf** [comment]
Looks like "Internal Audio Renderer" is no longer an option, and no audio renderers have automatic pitch correction as far as I can tell.
