### ISSUE TITLE
Add suport for WebVTT embedded in fragmented MP4 streams

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#1045]
As title say.
I'm not sure if it need also some changes in LAV Splitter but it would be nice to support it now that the support of WebVTT is improved a lot.

Sample: http://media.axprod.net/ExoPlayer/Captions/Manifest.mpd
The streaming already works but it completely ignore the subtitle tracks.

Ref: https://github.com/google/ExoPlayer/issues/689

**Comment by clsid2** [comment]
That needs to be implemented in FFmpeg. Its DASH support is still a work in progress.
