### ISSUE TITLE
Seek preview not shown on web streams

### ISSUE THREAD

**Issue by brian6932** [clsid2/mpc-hc#1047]
VODs don't have seek preview, tested for both YouTube and Twitch VODs using Streamlink HLS and youtube-dl

Build information:
    Version:            1.9.10.57 (7496b042e)
    Compiler:           MSVC v19.26.28806
    Build date:         Mar 30 2021

**Comment by lifegpc** [comment]
Preview only enabled for local files which have key frames information.

**Comment by clsid2** [comment]
It is intentionally disabled for online streams.

In the future there might be an option to enable it. But not right now. Some people move their mouse like a maniac over the seekbar and then preview doesn't really work well when data input is slow (online stream / spinning discs). I don't want to deal with "bug" reports for issues that are the result of that.

This decision is final and not debatable.

**Comment by brian6932** [comment]
Ah ok

**Comment by schoerg** [comment]
Pushing this as there seems to be a bug on what is considered remote (or local):

Windows 10, MPC-HC 1.9.13

When using a mounted device (`Z:\example\example.mkv`) the preview is not shown. However when using a UNC path like `\\hostname\example\example.mkv` the preview is shown.

It works fine in remote terms (1 Gbps connection) but that is just a sidenote.

**Comment by clsid2** [comment]
UNC paths and mounted network drives are not considered to be "remote" in this context, only actual URLs. Your problem was caused by something else.

**Comment by ale5000-git** [comment]
@schoerg: Preview on mounted device works perfectly here.
