### ISSUE TITLE
what is the abbreviation of portugues (Brasil) in subtitles section?

### ISSUE THREAD

**Issue by Ramonlaw** [clsid2/mpc-hc#1048]
What is the abbreviation for Portuguese (Brazil)?
because I wrote pt and had as result Portuguese (Portugal)

![image](https://user-images.githubusercontent.com/77369336/113807229-1cae1480-973a-11eb-8a05-7c2b1285faea.png)

**Comment by clsid2** [comment]
It is **pb**.
In places where three letter code is used it is pob.
