### ISSUE TITLE
Feature Suggestion: Finer grain Speed-up slow-down  

### ISSUE THREAD

**Issue by kellytrinh** [clsid2/mpc-hc#1050]
For the speed up/slow down (accessible by control up and control down) - the smallest change is 2x (/0.5x) normal speed.

Please consider 1.25 / 1.5x speeds - this would allow something to be still watchable whereas 2x is just too quick.

**Comment by clsid2** [comment]
Already exists!

Menu > View > Playback Rate
Options > playback > Speed step
