### ISSUE TITLE
MPC-HC x64 portable freezes

### ISSUE THREAD

**Issue by githubbapoopa** [clsid2/mpc-hc#1051]
MPC-HC x64 portable just freezes after a while. I used MPC-HC.1.9.10.80.x64 and MPC-HC.1.9.10.16.x64. Win10P Pro x64 fresh clean install 2021.04.10.

Find the dump files here:

[https://www.sendspace.com/file/0h5kko](url)

[https://www.sendspace.com/file/0h5kko](url)

**Comment by clsid2** [comment]
You need to provide more information.

What are you playing when the freeze happens? I don't see any decoder threads in the dump.
How often does it happen?
What is a while? Is it during playback, or is the player paused?

The current dump is useless. It doesn't indicate any problem in the player itself.

**Comment by githubbapoopa** [comment]
x265
happens every time
after an undefined amout of time
during playback
on different portable versions 
on an "older" and freshly installed Win10

did'nt occur 3 month ago, this is no HW (or driver) problem other players work fine
maybe Winupdate?

**Comment by clsid2** [comment]
Disable hardware acceleration in the video decoder and see if that helps.

**Comment by githubbapoopa** [comment]
With hw acceleration disable it's also freezing. But mpc-hc then uses about 7% cpu so that's not really an option for me on a mulit monitor + multi video setup.

What does that tell? What could be the real culprit? LAV? I'm digging...

How can I assist further?

New dump [https://www.sendspace.com/file/wx2q3h](url)

**Comment by githubbapoopa** [comment]
Update:

Default installation of MPC-HC.1.9.10.x64 and portable version of MPC-HC.1.9.10.x64 (default) freezes with HW acceleration both disabled and enabled.

VLC portable (default) works fine.

**Comment by ale5000-git** [comment]
You should try [MPC-HC 1.9.10.80](https://github.com/clsid2/mpc-hc/releases/tag/1.9.10.16).

**Comment by githubbapoopa** [comment]
I already have (see first post)

https://www.sendspace.com/file/cd631e

Drives me nuts.

How can I assist?

**Comment by ale5000-git** [comment]
1) Does Windows went in standby or hibernation with MPC-HC opened?
2) Are you playing local files or streamings?
3) Does it freeze when you let it play normally without touching any button on MPC-HC or when you do seeking?
4) Does files have subtitles?
5) Is the audio/video driver updated?
Every player may does things in a different way so if there is a bug in the driver it may or may not be triggered.

**Comment by clsid2** [comment]
It still seems to be using DXVA2 in that last dump.

It looks like you paused. Did the freeze happen directly after the pause, or before?

**Comment by clsid2** [comment]
Also try this:
Options > player > uncheck "Show OSD"

**Comment by githubbapoopa** [comment]
1. no
2. local
3. normal play
4. no (not loaded in seperate folder)

....but while we were communicating I was able to narrow it down.
This took a while to be sure. 
I did a fresh win install, again.
Tested different audio drivers (Realtek HD and UAD), different Intel HD grapic drivers.

Then I realized that every time I was searching for the error I had FirefoxPortable open. Well I use a huge!!! amount of tabs as this is my style of work. What I didn't realize is that Firefox was using the GPU heavily. As soon as the GPU use hits a certain limit all my mpc-hc players (I had 4 open to test parallel) froze.

**Firefox fresh start with session restoring of a massive amount of tabs**

![tricky](https://user-images.githubusercontent.com/82314033/114617998-217a4780-9ca9-11eb-9664-089232208613.jpg)

**GPU utilization hits "the spot" > mpc freezes**

![tricky2](https://user-images.githubusercontent.com/82314033/114618173-58e8f400-9ca9-11eb-9c7a-3f9a1f708477.jpg)

**What did I do? I disabled HW (GPU) accelation in Firefox.**

![tricky3](https://user-images.githubusercontent.com/82314033/114618368-8df54680-9ca9-11eb-8988-9ff5070fb635.jpg)

**Result: Firefox 0% GPU utilization > mpc-hc running fine.**

![tricky4](https://user-images.githubusercontent.com/82314033/114618545-c2690280-9ca9-11eb-8fb9-4637f4061fec.jpg)

This was tricky.

Still unclear what really happens with that GPU load balancing and wether it's a Intel driver, Firefox or mpc-hc bug. Or a GPU running out of memory....

Can you dig further?

Cheers

PS. mpc-hc GPU utilization still a little high for DXVA2 (native) on a x265 or x264 don*t you think?

**Comment by clsid2** [comment]
MPC-HC was hanging while waiting for a free memory buffer in the video decoder. So another program using all available GPU memory would indeed be a logical cause for that problem.
It is not a bug in the player, so I can't fix it. If you read release notes for graphics driver releases, then you will discover that this is also a common issue with other applications and games that are used at same time as browsers. Not just with Intel, but also with AMD and NVIDIA.

Can you test if playback eventually resumes in MPC-HC after you close Firefox?

**Comment by githubbapoopa** [comment]
Good explanation.

I enabled HW accelearation in Firefox again but get inconsistent results

![tricky5](https://user-images.githubusercontent.com/82314033/114631236-80958780-9cbc-11eb-81d2-459ffa178356.jpg)

Some instances of MPC-HC simply have no window anymore (the ones with 0% GPU) other fluctuate heavily (up to 71% GPU)

At one point I had a paused instance which I think was playing again after terminating Firefox. But as testing ist quite difficult I'm not 100% sure.

If resuming happens that would conlude that at least the MPC-HC code is fine, right?


PS.. DXVA native ist the correct setting fot Intel 620HD + EGPU Nvidia (not used in this testing setup)?

**Comment by clsid2** [comment]
The problem occurs outside of the player code.

DXVA native is correct choice. Software decoding could give better stability, but at cost of much higher CPU usage.

**Comment by githubbapoopa** [comment]
Maybe the explanation of freezes and player hangs others complain about also.

I'm fine with that and happy not to have to use VLC ;)

Thanks

**Comment by clsid2** [comment]
Disabling hardware acceleration in the browser or in the player is a good workaround for anyone that suffers from this problem.

**Comment by githubbapoopa** [comment]
Do *I* have to close that issue (I'm a newbie)?

**Comment by ale5000-git** [comment]
@clsid2
I'm not sure if it is feasible but isn't possible to put a timeout of 10 seconds for the  waiting for a free memory buffer and after the timeout automatically stop video to prevent player freeze?

**Comment by githubbapoopa** [comment]
If it's not you fault don't fix it :)

People still wouldn't know what stopped mpc-hc and still complain.

Maybe stop and an mpc-hc error message after a timeout for waiting on memory buffer? This would help to realize what is the problem.

But as I said: Not your fault. Just update the FAQ's :)

Sidenote: Firefox without GPU acceleration is muuuuuch snappier.

**Comment by ale5000-git** [comment]
Well, it depends.
For example, I expect apps not crashing even when system RAM is full; I also expect apps recreating systray icon when explorer crash; I also expect players play broken video files :)
But I agree that it is opinable.

But still there are also old video cards with low amount of video memory and they may exhaust it without other applications using it.

Also put the case you open a Youtube playlist with more than 100 files (that may take more than 60 seconds) and then player freeze. You will lose the playlist and the point you have reached.
If the player just stop you just have to press play again.

**Comment by githubbapoopa** [comment]
You're the developer do whatever you want! If mpc-hc improves from it we can all benefit.
It's one of my favourit softwares yet 👍

**Comment by ale5000-git** [comment]
I'm not the developer but just someone that follow the project from years :)

**Comment by MadokaAyukawa** [comment]
Just a newbie question. One of the features of Win 10 20H2 was supposedly that you can selection a GPU to use with an application for those computers with more than one. I've never tried this (the feature is still off), but could one avoid the above issue if one were to leave Firefox with the integrated Intel GPU and assign HC to the secondary nVidia GPU?

**Comment by clsid2** [comment]
You have to try yourself.

You can find this option in the Windows advanced display settings.

**Comment by ale5000-git** [comment]
@MadokaAyukawa: I'm not sure, because I was able to use DXVA (inside MPC-HC) on Intel GPU but it doesn't work on nVidia GPU at least on my notebook.

**Comment by clsid2** [comment]
Try this test build:
[removed]

Instead of freezing it now should drop frames or fail decoding instead. I also increased the amount of buffers. Maybe that will solve the problem. But it is possible buffers are not freed properly due to a bug somewhere. That would require further debugging.

Have you ever been able to reproduce with a single instance of MPC-HC? Next step would be use a debug build and generate a trace log. To make that log understandable it is best done with just one instance.

**Comment by githubbapoopa** [comment]
> 
> 
> @MadokaAyukawa: I'm not sure, because I was able to use DXVA (inside MPC-HC) on Intel GPU but it doesn't work on nVidia GPU at least on my notebook.

You can enable whatever GPU you like for mpc-hc. Choose graphic settings (you may enable hardware eccalerated GPU scheduling wich is a fairly new feature) > then choose desktop app > choose mpc-hc > Options > choose your graphics card

my setup is german :)

![tricky8](https://user-images.githubusercontent.com/82314033/115068545-af953e80-9ef2-11eb-8212-48785a84a611.jpg)

If you disable your nVidia 
(e.g. unplug EGPU or 
via "devcon disable PCI\VEN_10DE^&DEV_1CB1^&SUBSYS_11BC10DE^&REV_A1" in my case)
mpc-hc uses automatically the other GPU.
If you do that *while* mpc-plays a file then of course mpc freezes but sound is played furthermore.
mpc-hc works fine with Intel (+) or nVidia + DXVA native setting

And yes you can assign the GPU use that way and avoid that freeze issue. But as soon as there is only one GPU left Windows chooses that GPU. In my case I want to be able to unplug the EGPU without firefox crashing so I had to disable the hw accelaration in firefox rather than assigning it to a different GPU.

hope this helps

**Comment by githubbapoopa** [comment]
> 
> 
> Try this test build:
> https://www.sendspace.com/file/1rf42p
> 
> Instead of freezing it now should drop frames or fail decoding instead. I also increased the amount of buffers. Maybe that will solve the problem. But it is possible buffers are not freed properly due to a bug somewhere. That would require further debugging.
> 
> Have you ever been able to reproduce with a single instance of MPC-HC? Next step would be use a debug build and generate a trace log. To make that log understandable it is best done with just one instance.

Hah you had to do it :)

First of all this version throws an error

![tricky9](https://user-images.githubusercontent.com/82314033/115072480-f3d70d80-9ef7-11eb-90ec-96c2d9be2d65.jpg)

altthough this is a fresh windows

![tricky10](https://user-images.githubusercontent.com/82314033/115072535-05b8b080-9ef8-11eb-8106-4b2086625e52.jpg)

This version shows no pictures while playing from start. You get a picture only after a while but it's frozen without firefox even running. If you seek you get a picture for about 1 s but then it freezes again. DXVA native.

**Comment by clsid2** [comment]
You need to copy D3DX9_43.dll and D3DCompiler_47.dll from the ZIP version of non-test build.
Those are not part of clean Windows install. You can also get them by installing DirectX End-User Runtime.

Here is a debug build. With the dlls included.
https://www.sendspace.com/file/r07m9e

Run Dbgview.exe to create a log file during playback.

**Comment by githubbapoopa** [comment]
Sorry you have to give me further infos. Do I have to install mpc-hc latest develop build and then copy the files over? Or is it for a portable version and I have to copy the files over? Seems I cannot run this alone... Cannot set any video decoders > error cannot render file...

**Comment by MadokaAyukawa** [comment]
> 
> 
> Try this test build:
> https://www.sendspace.com/file/1rf42p
> 
> Instead of freezing it now should drop frames or fail decoding instead. I also increased the amount of buffers. Maybe that will solve the problem. But it is possible buffers are not freed properly due to a bug somewhere. That would require further debugging.
> 
> Have you ever been able to reproduce with a single instance of MPC-HC? Next step would be use a debug build and generate a trace log. To make that log understandable it is best done with just one instance.

I tried this. I put the contents of this zip into the .80 install folder. But HC's picture hung after like 1 to 2 seconds. It was still responsive as I could Alt-X to kill the program.

**Comment by clsid2** [comment]
It should work as a portable as well if you unzip the archive.

Use the second build and run the included dbgview.exe as well.

**Comment by githubbapoopa** [comment]
I used MPC-HC.1.9.10.80.x64 (zip), copied the files from mpc-hc_x64_Debug over:

[
https://www.sendspace.com/file/m09se4](url)

Cannot render file.

?

**Comment by clsid2** [comment]
It is failing to load the LAVFilters.

You probably needs to install the Microsoft VC++ Runtime:
https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by githubbapoopa** [comment]
Portable (Runtime installed) > files from mpc-hc_x64_Debug copied over

[https://www.sendspace.com/file/linato](url)

Installed instance (Runtime still installed> files from mpc-hc_x64_Debug copied over

[https://www.sendspace.com/file/rco02k](url)

Am I doing anything totally wrong? Really like to help...

**Comment by gitschab** [comment]
I have the same problem. I haven't encountered it during playback, but when I would pause the player and leave it paused for a couple minutes it would freeze. I've NEVER had this issue before with MPC-HC, so I reverted to 1.9.9 and the problem does not occur anymore, which leads me to think it might be a player issue after all. Win10 x64 Enterprise 20H2.

**Comment by clsid2** [comment]
@gitschab
Please try 1.9.10.80 development build.
If it freezes, open Windows Task Manager, right-click on mpc-hc64.exe and create dump.
Zip/rar the dump file and upload it for me.

**Comment by clsid2** [comment]
@gthbububba
Put these two files in the LAVFilters64 folder:
https://www.sendspace.com/file/dj29fj
Then the debug build should hopefully work.

**Comment by githubbapoopa** [comment]
Portable with LAVFilters64 updated

[https://www.sendspace.com/file/wwxs2t](url)

Installed .80 > copied debug files > copied LAV files

[https://www.sendspace.com/file/sb0m7u](url)

**Comment by clsid2** [comment]
Another try now with static build:
https://www.sendspace.com/file/177zh1

**Comment by githubbapoopa** [comment]
Portable .80 with updated/overwritten files from https://www.sendspace.com/file/177zh1

nope

[https://www.sendspace.com/file/lmwzir](url)

**Comment by clsid2** [comment]
I tested this one in a Virtual Machine, so should now finally include all required debug DLLs.
https://www.sendspace.com/file/79syrs

Stupid Microsoft makes our lives difficult by not making an easy to install debug runtime.

**Comment by githubbapoopa** [comment]
Picture for 1s then picture freezes. Audio still playing. On seek picture for 1s then picture freezes again. Audio still playing fine.

[https://www.sendspace.com/file/pn6em3](url)

Same as https://github.com/clsid2/mpc-hc/issues/1051#issuecomment-821456807

**Comment by clsid2** [comment]
New build with lots of logging:
https://www.sendspace.com/file/ntictr

**Comment by gitschab** [comment]
> @gitschab
> Please try 1.9.10.80 development build.
> If it freezes, open Windows Task Manager, right-click on mpc-hc64.exe and create dump.
> Zip/rar the dump file and upload it for me.

1.9.10.80 (downloaded on Apr 18th) seems to do the trick for me, no freezing so far. It has this odd behavior that when I restore a minimized paused player it shows the last frame that I paused on for a split-second and then it turns black (never had that in the past). I can resume the playback normally though.

**Comment by githubbapoopa** [comment]
portable .80 with copied files from https://www.sendspace.com/file/ntictr

Audio if fine but picture stutters (count 1,2 stutter 3). Seeking and stop/start is fine.

[https://www.sendspace.com/file/roe4es](url)

**Comment by clsid2** [comment]
Debug build is slower, so ignore stuttering.

If you are able to get a freeze with this build, then maybe the last part of the log can reveal some clues about what went wrong.

**Comment by gitschab** [comment]
The issue *kinda* returned for me in 1.9.11 - after pausing the player and leaving it paused playback cannot be resumed instantaneously - clicking the player window causes it to freeze for about 5 seconds, then it unfreezes itself and operates normally.

**Comment by clsid2** [comment]
If your harddrive has gone into sleep mode, then it can take several seconds for it to spin up again and be ready when an application tries to read data. During that time the player will be unresponsive.

**Comment by gitschab** [comment]
> If your harddrive has gone into sleep mode, then it can take several seconds for it to spin up again and be ready when an application tries to read data. During that time the player will be unresponsive.

1. this is a SSD machine and it was not put in standby mode or anything of the sort between 
2. if this was common I would've noticed it before and I've been using MPC-HC for ages (10 years for sure). This is something that appeared only in ver. 1.9.10 (permanent freeze) and 1.9.11 (temporary freeze).

**Comment by clsid2** [comment]
Test the development builds in between 1.9.9 and 1.9.10. That might help identify a possible cause. Because I am unable to reproduce any hang problems.

Are you able to reproduce the problem by just pausing the player and doing nothing for a while? Or does it only happen when you do something else while it is paused? Such as using a webbrowser or game?
