### ISSUE TITLE
Casting with chromecast ?

### ISSUE THREAD

**Issue by SoManyGold** [clsid2/mpc-hc#1052]
# <h1>`CASTING WITH CHROMECAST ?`
I don't know if it's in the project but it's an idea.
I put this here make what you want about that
If one day it's be realise, maybe I'll be just :
"Oh ! Nice, that good 😄"
so have a great day, bye 😀
### <h2>
`Follow me :`
>- ![Twitter](https://icons.iconarchive.com/icons/xenatt/the-circle/24/App-Twitter-icon.png) : [@BenjaminA2mains](https://twitter.com/benjaminA2mains)
>- ![Instagram](https://icons.iconarchive.com/icons/designbolts/free-instagram/24/Active-Instagram-3-icon.png) : [BenjaminA2mains](https://www.instagram.com/benjamina2mains/)
>- ![Youtube](https://icons.iconarchive.com/icons/alecive/flatwoken/24/Apps-Youtube-icon.png) : [Bonjour Benjamin](https://www.youtube.com/channel/UCNB_LHeEdgDkMM4949yNX3A?view_as=subscriber)
>- ![Twitch](https://icons.iconarchive.com/icons/papirus-team/papirus-apps/24/gnome-twitch-icon.png) : [Im4g1neOff](https://www.twitch.tv/im4g1neoff)
>- ![Soundcloud](https://icons.iconarchive.com/icons/sicons/basic-round-social/24/soundcloud-icon.png) : [ベンジャミン / Benjamin](https://soundcloud.com/amatanime)
>- ![Xbox](https://icons.iconarchive.com/icons/icons8/windows-8/24/Logos-Xbox-icon.png) : [SoManyGold](https://account.xbox.com/fr-fr/Profile?xr=mebarnav&rtc=1)
>- ![Playstation](https://icons.iconarchive.com/icons/martz90/circle-addon2/24/playstation-icon.png) : [SoManyGold](https://my.playstation.com/profile/SoManyGold)

**Comment by clsid2** [comment]
Such functionality will not be added.

**Comment by Korb** [comment]
@SoManyGold, do you mean something similar to what [is implemented in VLC Media Player](https://www.vlchelp.com/how-to-cast-vlc-media-to-chromecast-devices/)?
