### ISSUE TITLE
Error compiling SubPic in MPC-HC 1.9.10

### ISSUE THREAD

**Issue by sudongg** [clsid2/mpc-hc#1055]
Compiling with VS2019 16.8.4, MPC-HC 1.9.7.0 has been successfully compiled before, but an error occurred when compiling MPC-HC 1.9.10.

SubPic Release Win32 error：

```
1>XySubPicQueueImpl.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\cmath(143,18): error C2039: "llrintf": is not a member of '`global namespace''
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\cmath(143,25): error C3861: “llrintf”:  identifier not found
```

**Comment by clsid2** [comment]
Compiling works fine for me and others.

**Comment by sudongg** [comment]
@clsid2 
I just want to compile Lavfilters, but Lavfilters doesn't provide a compilation document.
If I just compile Lavfilters, how do I compile them?

**Comment by clsid2** [comment]
You can find LAV project inside MPC-HC solution file. Right-click on that to compile only that project.

**Comment by sudongg** [comment]
@clsid2
Before that, I compiled the lavfilters project with error (issue #1053).
According to your answer, compiled zlib, and then encountered this error.
I choose to compile the MPC-HC project, and the same error occurs.

**Comment by clsid2** [comment]
I don't know what is wrong. You need to figure it out yourself.

**Comment by sudongg** [comment]
@clsid2 
I don't know what the problem is, but I compiled MPC-HC 1.9.7.0 successfully.
