### ISSUE TITLE
Subtitles do not show up if 2 or more are shown

### ISSUE THREAD

**Issue by LetsPlayNintendoITA** [clsid2/mpc-hc#1059]
Hi, in the last stable version and also in the nightly, if two or more subs are shown (i.e. in certain anime with signs and dialogue) they only show the one that starts first. it has started happening only recently. can someone help?

**Comment by clsid2** [comment]
Use 1.9.10.80

**Comment by LetsPlayNintendoITA** [comment]
ok thanks!

**Comment by clsid2** [comment]
I assume you used an older nightly before.

**Comment by LetsPlayNintendoITA** [comment]
yes i by mistake used the .16 after the stable one didn't work
