### ISSUE TITLE
Feature Request: Set custom HTTP user-agent in settings

### ISSUE THREAD

**Issue by lucas3F59** [clsid2/mpc-hc#106]
Hi there!

I'm not a programmer, otherwise I would make these changes myself. I know it's in maintenance mode, but it should only take a few minutes to add this for a real programmer.

Thank you!

Lucas.

My suggestions:

**mplayerc.cpp:**
Change
`"User-Agent: MPC-HC\r\n"`
to
`"User-Agent: " + strHTTPUserAgent + "\r\n"`

**AppSettings.cpp:**
Add at the right positions
`, strHTTPUserAgent("MPC-HC")`
`pApp->WriteProfileString(IDS_R_SETTINGS, IDS_RS_HTTPUSERAGENT, strHTTPUserAgent);`
`strHTTPUserAgent = pApp->GetProfileString(IDS_R_SETTINGS, IDS_RS_HTTPUSERAGENT);`

**AppSettings.h:**
Add at the right position
`CString strHTTPUserAgent;`

**Comment by clsid2** [comment]
That UA is not used for playback. LAV Splitter controls that. There already is a feature request for it:
https://github.com/Nevcairiel/LAVFilters/issues/274

**Comment by ale5000-git** [comment]
@clsid2
LAVFilters now support a dedicated interface that allow set User-Agent and Referer, please use it.
Link: https://github.com/Nevcairiel/LAVFilters/commit/9070300a62d3713b6c6352d785f3be902460cc23
