### ISSUE TITLE
Disable Link Select Cursor 

### ISSUE THREAD

**Issue by vuslatx** [clsid2/mpc-hc#1061]
![sda](https://user-images.githubusercontent.com/65629417/115286836-63b9e380-a104-11eb-8599-e56b74034212.jpg)
Hi. Thanks for good media player software. I'm looking for a way to disable the link select cursor in the seekbar.  I want the right cursor instead of the cursor on the left. Is there any way? Thanks.

**Comment by clsid2** [comment]
There is no option for that, and I am not going to add any extra options either.
