### ISSUE TITLE
MPC-HC & the "DX9AllocatorPresenter failed" message have NOTHING to do with system bootloops.

### ISSUE THREAD

**Issue by Disappeaer** [clsid2/mpc-hc#1062]
Hi again, I just wanted to say I found the root cause of my bootloops and as you said, it was definitely **not** connected with MPC-HC. You might think: "Um, of course, I already knew that / I told you that".
I still maintain I chose my words carefully, and I never flat-out accused the program for something that could very well, as it turned out to be, had nothing to do with it. Especially after your explanation, which made perfect sense.
**But,** this doesn't change the fact I initially made the connection, plus I've made you spend some time to read those messages/essays and reply. (Of course, I've spent **much more** time typing all that, but it was my problem to begin with and certainly not your fault).
Therefore, let this be a public apology. I tried to edit my original issue to include it, but you had already closed it and I had no other way to contact you or make things up.
I am sorry you had to read stuff, which as it turns out, given the fact this is your area of expertise, it probably came across as absurd as me having a client recording something in my studio, then complaining it's haunted or there is something fundamentally wrong with the recording, because he is convinced he can hear voices from the other side on it...

I'd be more than happy to install MPC-HC back into my system, your good work of keeping alive this legend between media players is well appreciated. :)

**Comment by clsid2** [comment]
You should still be able to reply in a closed issue. It is probably just edit that doesn't work. But doesn't matter.

Now I am curious what the real cause was ;)

**Comment by Disappeaer** [comment]
I would too. Oh well... Do you remember I've also asked whether running batch files to sort PVR recordings could be the culprit?
Apparently it could... Two days ago, I wanted to sort the recent ones, on my flash drive, once again.
I paused and thought whether that batch file (a variation of it I recalled editing recently...) could cause the problem and while it seemed like it could indeed be a possibility and another bootloop wasn't certainly not welcome,  at the same time, for troubleshooting reasons it kinda was. So I just ran it and while stuff was running with the speed of light on the CMD window, my eye caught paths/files that **were not** a part of the flash drive... Uh oh....
I went to reboot right ahead (without playing a video with MPC-HC  :P ), and sure enough....bootloop galore!
So it was quite obvious something on the batch file was doing things I didn't want it to do. Here it is btw:



```
takeown /f "H:\PVR" /r 
icacls "H:\PVR" /reset /T 
FOR /R "H:\PVR" %%i IN (*.ts *.tsv) DO MOVE "%%i" "H:\PVR" 
CD /D "H:\PVR" 
ren *.tsv *.ts
**for /f "delims=" %%d in ('dir /ad /b') do @rd /q /s "%%d"** 
setlocal EnableDelayedExpansion 
for %%a in (*.ts *.tsv) do ( 
set name=%%~Na 
set num=00!random! 
set newName=!!name:~-17! 
ren "%%a" "!newName!%%~Xa" 
)
```

I've asked around online and people quickly pointed out that if the following line fails:
`CD /D "H:\PVR" `  (and it certainly did because Windows often attach a different letter on flash drives)
then this line: `for /f "delims=" %%d in ('dir /ad /b') do @rd /q /s "%%d`
would delete folders from the source folder of the batch file instead, which can be enough of a problem on its own.
But, to make things worse, I had no idea that since I was also running the batch file as admin, the batch file was actually running from  `\Windows\System32`! *facepalm*
And well, while Windows protect _some_ Microsoft folders/files, apparently lots of other crucial stuff (like drivers!) gets deleted...
Which perfectly explains why although I wasn't getting an instant BSOD, MPC-HC was showing that error and Windows would fail to boot... If you are wondering "how dumb you felt?", the answer is a lot. But I also can't remember ever feeling happier/more relieved to do something so stupid. Because I had found the root cause of my problem and it also signaled my hardware is fine.
I can't believe that after almost 25 years of using computers, I pretty much pulled a "Look mum, I've deleted System 32!"
Guess CMD Land is a more dangerous place  than I thought and Windows do not protect themselves **that** efficiently...
Lesson learnt and hopefully all is well now. :)

**Comment by ale5000-git** [comment]
This is why when I write batch / shell scripts I test exit code of ALL commands (even ones that normally shouldn't fail) and stop the script on error (displaying the error).

**Comment by clsid2** [comment]
Tip; change working dir to .bat location with:
CD /D %~dp0
