### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Dominiquini** [clsid2/mpc-hc#1064]
This last version asks me every time I start the application whether I want to activate the new version of chasing or not, no matter which option I choose!

---
_Do you want to check periodically for MPC-HC updates?
This feature can be disabled later from the Miscellaneous options page._
---

App Version: 1.9.11 (6096e5ea7)
OS: Windows 10 x64

Thanks.

**Comment by clsid2** [comment]
This happens when it it unable to save the settings.

Did you enable the option to store settings in INI file? The settings file must have write access.

**Comment by Dominiquini** [comment]
No, I did not change anything in the settings. I even tried to reset the settings.
I also cannot enable the option to save the settings in an INI file. The option is disabled here!

![mpc-hc64_X4u7KqzFFw](https://user-images.githubusercontent.com/1180808/115893240-57989380-a42e-11eb-9df7-178d2277aaa6.png)

Thanks

**Comment by clsid2** [comment]
Start the Registry editor: regedit.exe
Remove this key: HKEY_CURRENT_USER\Software\MPC-HC

**Comment by Dominiquini** [comment]
I tried this and the problem persists.
As soon as I started the program again, the key "HKEY_CURRENT_USER\Software\MPC-HC" was recreated, but none of the sub-keys appeared. And every time I started the program, the message appeared to activate updates automatically!

When I run the program as an administrator, everything seems to work fine. The sub-keys were created and edited according to the settings I selected. But if I open the program as a normal user, all settings return to the default value.
It appears that the program cannot read or write the settings to the registry. 

Now I found out how to use the INI file to save the settings and everything seems to be working now as a normal user!

Thanks.

**Comment by clsid2** [comment]
Then the access permissions in your Registry might be broken.

Right-click on HKEY_CURRENT_USER\Software and go to Permissions. Your user account should have full control.

**Comment by Dominiquini** [comment]
My registry was really wrong with permission settings! I fixed it here and it seems to be working fine now!
I think that was what was causing some other errors and other applications on my PC.

Sorry to bother you with something that was obviously not caused by this application.

Thank you for your help!

**Comment by ale5000-git** [comment]
In these cases the best (long term) way to fix Windows is create a new user, move data to the new user and then delete the old user.
