### ISSUE TITLE
Strings arent fully displayed - mpc 1.9.11

### ISSUE THREAD

**Issue by Felipefpl** [clsid2/mpc-hc#1065]
No space.gif - the phrase "Aplicar perfil de cores do...." isnt fully shown

No space 2.gif - the same happens with "Tamanho do....." in the properties

It would be nice if all dialog boxes auto-resize themselves to give space for translated words since most of times they are bigger in other languages beside english. ;)

![No space 2](https://user-images.githubusercontent.com/5569804/115870964-56f40300-a416-11eb-9415-8c61ba989111.gif)
![No space](https://user-images.githubusercontent.com/5569804/115870969-578c9980-a416-11eb-8fe7-82fdfe26be60.gif)

**Comment by clsid2** [comment]
Autosize is not possible. That would fuck up the whole layout. I am not going to spend a lot of time facilitating long strings.

I increased size of logo page option. The other one is already max size. And I am not going to move stuff around. You will have to shorten the translation.
