### ISSUE TITLE
Restoring settings from the original project

### ISSUE THREAD

**Issue by vermajai93** [clsid2/mpc-hc#1066]
I was initially using the original MPC-HC project from [here](https://mpc-hc.org/). Before using clsid2's version, I exported key bindings from the original version.

Before I restore the old key binding using the reg file, I want to confirm whether or not it will work. Given that the original project was maintained by someone else.

Any help would be appreciated.

**Comment by clsid2** [comment]
My version is a continuation of the old project. Settings are still the same.
