### ISSUE TITLE
"mpc-hc" as add-on or ActivX for internet browser.

### ISSUE THREAD

**Issue by Arkady23** [clsid2/mpc-hc#1067]
Is it possible to put a video on your site, for example, through the "mpc-hc" add-on? It is not very convenient to use an IP-camera every time to watch videos, download video files. In the suppressed majority of cases, it is enough only to view the camera itself on the http-server. You can always put your own html page on the IP-camera with the ability to view files located on the SD-card.

**Comment by clsid2** [comment]
It is a player, not a plugin.

**Comment by ale5000-git** [comment]
@Arkady23: It isn't clear what you say but you can open the webpage of the webcam directly in MPC-HC (if youtube-dl.exe is present) and it may work (not sure though).

**Comment by Arkady23** [comment]
I didn't find any items in the mpc-hc menu how to open url. 
![image](https://user-images.githubusercontent.com/79393209/115959513-ec46e280-a54f-11eb-824b-246513be0a02.png)

I entered for example the command `mpc-hc64.exe https://www.youtube.com/watch?v=uIlCsOdzAnY` and received:
![image](https://user-images.githubusercontent.com/79393209/115959387-60cd5180-a54f-11eb-96e5-1785d2314124.png)

**Comment by ale5000-git** [comment]
1) First be sure to have the latest version of MPC-HC (1.9.11)
2) Place youtube-dl.exe in the same folder of mpc-hc64.exe or mpc-hc.exe (be sure to have latest version of youtube-dl.exe also)
3) Then go to File => Open File/URL...
4) Inside **Open:** paste the url then press **OK**

**Comment by Arkady23** [comment]
@ale5000-git Thank you so much. I did it all..... It was necessary to install vcredist_x86_2010.exe. Everything worked. This is very cool. I guess there's a way out of this for me. But I note that VLC has an application and a plugin for the site. But the recordings on the SD card of my IP camera VLC does not play, and MPC-HC shows, but without sound and without a slider. The model of the VStarcam camera.
![image](https://user-images.githubusercontent.com/79393209/115961021-e5bc6900-a557-11eb-8fb6-eddeedca900a.png)

**Comment by ale5000-git** [comment]
If you download the video with youtube-dl alone (youtube-dl.exe http://...) and then play it in MPC-HC does audio works?

**Comment by clsid2** [comment]
A .h264 file is a raw video stream. It does not contain audio. It is also not seekable.

If you want a seekable file you need to remux it into a container. For example into a .mkv file. You can do that with MkvToolNix.

**Comment by ale5000-git** [comment]
Maybe the camera have options (although I don't know yours specifically), some create ASF files.

**Comment by Arkady23** [comment]
I'm sorry I didn't answer right away. I had a night out. I bought this camera the other day. I began to search for information on it. A video player is included with this camera Zpleyer.exe for PC and the Eye4 phone app. Only these two apps play sound and allow you to move the slider. I also found information on the internet that records that fit on an SD card can be played by Classic Video Player. No other apps play back these recordings. There are some codecs inside the folder with Eye4/918 H264Decoder.dll and H264Decoder2.dll.
[Eye4.zip](https://github.com/clsid2/mpc-hc/files/6370926/Eye4.zip)

**Comment by Arkady23** [comment]
> Maybe the camera have options (although I don't know yours specifically), some create ASF files.

@ale5000-git In my opinion, the Eye4 application for PC can do the conversion to avi when watching videos. It doesn't make sense. Usually, these videos are not watched more than 1 time.

**Comment by Arkady23** [comment]
> A .h264 file is a raw video stream. It does not contain audio. It is also not seekable.
> 
> If you want a seekable file you need to remux it into a container. For example into a .mkv file. You can do that with MkvToolNix.

If you compare the H264 files and the resulting avi. You're right. The H264 has audio, but this file is much larger in size than the resulting avi.
https://drive.google.com/file/d/1N_SFG12EHHq3EMCDhAbe7FEdFP7iLqZr/view?usp=sharing

**Comment by Arkady23** [comment]
> If you download the video with youtube-dl alone (youtube-dl.exe http://...) and then play it in MPC-HC does audio works?

I checked it right away. No sound.
