### ISSUE TITLE
Lag while speed changes

### ISSUE THREAD

**Issue by vuslatx** [clsid2/mpc-hc#1069]
There is a little lag when video or audio playback speed changes(such as 1.0>1.1). Do you have a suggestion?

**Comment by clsid2** [comment]
A short lag is normal when changing speed.

Try the internal audio renderer. That gives shortest lag here.

**Comment by astroboylrx** [comment]
Do you mind explaining a bit why technically a short lag is normal for changing speed? It seems there is no such lag in other players or in youtube. Thanks a lot in advance.

**Comment by vuslatx** [comment]
> Do you mind explaining a bit why technically a short lag is normal for changing speed? It seems there is no such lag in other players or in youtube. Thanks a lot in advance.

For example, no problem with Potplayer.

**Comment by clsid2** [comment]
Then go use PotPlayer.

Youtube is not a DirectShow player.
