### ISSUE TITLE
Add support for .mks files as subtitle files

### ISSUE THREAD

**Issue by Silver-Fullbuster** [clsid2/mpc-hc#1070]
Adding support would be nice for providing subs with fonts as a .mks file, because .ass files don't have a system of adding fonts (or none that I'm aware of)

**Comment by clsid2** [comment]
Support for .mks will not be added.

You can embed fonts inside a .ass file.
http://www.tcax.org/docs/ass-specs.htm

But preferably you should put the subtitle and fonts directly in the .mkv file.
