### ISSUE TITLE
1.9.11 - Multiple anime subtitles are positioned incorrectly

### ISSUE THREAD

**Issue by Reelix** [clsid2/mpc-hc#1072]
MPC-HC 1.9.11
![MPC-HC 1.9.11](https://i.imgur.com/QzmzdN0.jpg)

VLC
![VLC](https://i.imgur.com/D3kQPjd.jpg)

**Comment by clsid2** [comment]
I need a link to that file.

**Comment by adipose** [comment]
Is it webvtt?

**Comment by Reelix** [comment]
He's a link to a 20 second trimmed version of the original video (The trimming process broke the first 2 seconds of video for some reason, but it still shows the subtitle issue as expected)

Github itself doesn't allow mkv files to be attached (For some reason), so here is a dropbox link to the file. https://dl.dropboxusercontent.com/s/h6o627z3xat5x24/1111.mkv

**Comment by MadokaAyukawa** [comment]
I played that file, both in VLC and 1.9.11, and they look the same. The dialogue font is different—it looks like Arial—but the karaoke works and looks the same as your VLC SS. .11 for me definitely doesn't look like your HC SS. BE looks the same too.

**Comment by clsid2** [comment]
Works ok here as well.

I think you might have enabled the "Default Style" overrride.
Menu > Play > Subtitles > uncheck "Default Style"

**Comment by ale5000-git** [comment]
@Reelix: Aren't just wrong options?

Try to uncheck "Never animate the subtitles" option and change "sub pictures to buffer".

**Comment by Reelix** [comment]
> Menu > Play > Subtitles > uncheck "Default Style"
  
Well - Now I feel sheepish :)

User Error - Marking this as closed - Thanks for the assistance :)
