### ISSUE TITLE
Subtitle "Subresync" adjustments

### ISSUE THREAD

**Issue by roysubs** [clsid2/mpc-hc#1073]
I would greatly appreciate subtitle management to get the same care and attention that so much other of the UI has. Most other tools in MPC-HC have great shortcut keys that really make any adjustments really simple like the options in the View menu. The problem is that maybe 30+% of all subtitles I get do not sync. I can do Ctrl+6 to get into "Subresync" tool, but it's really awkward to use and adjust. I'd really appreciate shortcut keys for the following:

• Subtitle back 2 seconds
• Subtitle forward 2 seconds
• Subtitles speed up 2%
• Subtitles slow down 2%

With this, I think 100% of subtitles will be really to manage. MPC-HC is by far the easiest and best media player that I know of, but the Subresync option is quite frustrating to use - and mostly, I cannot get it to work, as if I sync up a subtitle, I often find that they just slide out of timing again within 1-2 minutes, hence why I think "Subtitle speed up" and "Subtitle slow down" options would be so useful / important to getting clean subtitles (and this would be a ton easier with the above 4x shortcut keys! 👍)

**Comment by clsid2** [comment]
You can adjust subtitle delay with F1/F2 keys.

I am not going to add any extra options to Subresync. That is a part of the code I am not familiar with and I am not going to touch it.

Figure out why your subtitles are out of sync, and what the exact speed difference is. For example video was converted from NTSC to PAL or vice versa. If all of them share something in common then maybe one day there will be an option to compensate for that. But not any time soon, because to be honest I don't really care about this issue.

**Comment by roysubs** [comment]
ok, I'll try playing with those. I get that you don't care about subtitles, that's no problem, I wouldn't care about subtitles much myself except that my girlfriend is partially deaf, so for her (and there really are a lot of people in this position sadly) subtitles kind of become the single-most-important-feature in a media player (she'll happily watch crap quality video all day long - but if there are no subtitles it's just not an option). I can totally appreciate that if you are not familiar with that code that it might be considered lower priority, but hopefully some other folks can jump on board and help you with that aspect of the code! Thanks for the tips though. 👍🙂

**Comment by clsid2** [comment]
I don't care about **incorrect** subtitles.

There are plenty of tools that you can use to sync subtitles.
https://subshifter.bitsnbites.eu/
http://www.uruworks.net/index.html
https://sourceforge.net/projects/subadjuster/

**Comment by ShadyHarbinger** [comment]
F1 and F2 just doont work. It is well know issue with MPC.

**Comment by clsid2** [comment]
Works just fine, so user error on your side, for example by not using the internal subtitle renderer.

**Comment by ShadyHarbinger** [comment]
> Works just fine, so user error on your side, for example by not using the internal subtitle renderer.

Maybe but I have no idea what is the problem. I use MadVR but the internal renderer for subtitles but F1 and F2 do nothing. Only displays a 0 ms delay message. I found many cases on forums regarding this function.

**Comment by clsid2** [comment]
MadVR is a video renderer, not a subtitle renderer.

Options > Playback > Output > Subtitle Renderer > Internal Subtitle Renderer

It does not work with external renderer such as XySubFilter.

**Comment by ShadyHarbinger** [comment]
I know and I use the internal renderer for subtitles. :) It just does not work. I have to use an app for syncing when I need but it is very rare so I can live with it.

**Comment by clsid2** [comment]
Options > Subtitles > Delay Step

If you have set that to 0 then it obviously also fails. That is not the DELAY but the DELAY STEP, meaning that value is added/subtracted for each press of F1/F2.

**Comment by ShadyHarbinger** [comment]
OMG. That was the problem. I use the Hungarian language and the translation is wrong. The translated text means "delay" in English and not "delay step". So I set it 0. Thank You! :D
