### ISSUE TITLE
Blank Screen When Playing Windows Media v8 Video And MPEG-4 Simple Profile Videos

### ISSUE THREAD

**Issue by LuisGuzmanTech** [clsid2/mpc-hc#1077]
Currently MPC-HC Has An Issue With Some Windows Media v8 Videos And MPEG-4 Simple Profile Videos Where It Will Not Show Anything On The Screen. I Have The Files And Screenshots For Troubleshooting

![MPC-HC Issue 555# Issue With Single Profile MPEG4](https://user-images.githubusercontent.com/73855192/116488314-b65b7400-a857-11eb-9220-55f021393451.PNG)

**Comment by LuisGuzmanTech** [comment]
Heres The Files That Have The Issue

https://app.box.com/s/5g7o7c3kbcild2r8ejc72tvx2yvzrflf

https://app.box.com/s/flz9d5ism112zdm75a8qtmw9qqbbg075

**Comment by clsid2** [comment]
Both play fine here.

Copy your filter list for both files:
Menu > Play > Filters

**Comment by LuisGuzmanTech** [comment]
Ill Get That Later Since Im At Work But Your Version Plays Fine? Mine Was 1.98.32

**Comment by clsid2** [comment]
That is an old version. I can only help with problems if they occur with latest version: 1.9.11

**Comment by LuisGuzmanTech** [comment]
ill update to make sure its not a problem. i havent updated in a while since im using an older system for now

**Comment by LuisGuzmanTech** [comment]
Sorry I havent gotten back.  The issue seems to be fixed in the newer builds
