### ISSUE TITLE
Laptop freezes very regularly when using MPC-HC

### ISSUE THREAD

**Issue by Necrolion99** [clsid2/mpc-hc#1079]
I have been getting this very annoying problem very regularly while using MPC-HC. I have a collection of like 1000 videos, mostly movies and random videos I filmed in my trips, and I have noticed that when I open older videos, or watching them continuously, my laptop will freeze completely, and I can't do anything but holding the power button for a restart. I'm using 1.9.11, with madVR, blueskyFRCU and LAV installed. At first, I thought it was because of madVR and the others, but it happened too after I disabled them. So far, I have tried the following: update MPC-HC, update the graphic drivers, put MPC, HC on high graphic performance setting and disable hardware accelerator. They worked for a few days at most, then the problem returned. Sometimes, I have unsaved works opened in the background, so whenever this happens, it become very problematic for me to try and restore lost stuff. I am a bit illiterate in term of these things, so all helps are very appreciated. 

Edit no.1: it has just happened again. 2 times in the span of 15 minutes. It seems like the triggers are watching more than 10 videos in a short period (which makes this event more annoying because I have a lot of short clips), or watch the same video repeatedly (~3-4 times). As mentioned, this happens more with older videos than newly creates pr downloaded ones. Additionally, short videos (1~3 min) are more likely to make the freeze happens.

**Comment by clsid2** [comment]
If your laptop has a traditional spinning harddrive, then I recommend to perform a full disk scan and check for bad sectors on the drive.

A full system freeze means a low level issue, so hardware or driver related. If it only happens after watching several videos, then it is possible there is an overheating issue.

**Comment by Necrolion99** [comment]
I see. I will try a full scan and report the results later. Thank you for the recommendation.

**Comment by Necrolion99** [comment]
> I see. I will try a full scan and report the results later.

Did 2 scans, one with cmd and one through My Computer. No errors were found. So far so good, I guess. It's very late now, so I will make more tests tomorrow to see if the problem is solved and report here again.

**Comment by ale5000-git** [comment]
Just in case you haven't done it in this way I suggest:
1) `chkdsk /F /R c:`
2) Restart the pc
3) `sfc /scannow`

**Comment by clsid2** [comment]
Which GPUs and driver versions do you have installed?

Also look in the Windows Event Viewer to see if it logged any error messages around the time the freeze occurred.

**Comment by Necrolion99** [comment]
> Just in case you haven't done it in this way I suggest:
> 1) `chkdsk /F /R c:`
> 2) Restart the pc
> 3) `sfc /scannow`

Thank you, but I actually tried sfc/scannow before, when the freezing start happenings months ago. No problem founded. I used window 10's playback troubleshoot a few days ago, and it said thaty laptop can't view 4K vids, which doesn't make much sense since I don't have any 4K vids at all.

**Comment by Necrolion99** [comment]
> Which GPUs and driver versions do you have installed?
> 
> Also look in the Windows Event Viewer to see if it logged any error messages around the time the freeze occurred.

I have an ASUS laptop with AMD Radeon (TM) Vega 8 and Radeon RX 560X, driver versions are the latest installed along AMD Radeon Software 21.4.1, released on 13 Apr 2021. 

I has just been able to manually trigger the freeze to happen, by watching a video saved from ~1 month ago, then play the next 2 videos also saved  from the same period. This trigger the error. Event viewer shows the sudden power button reboot as critical error, but refuses to elaborate any further. But I have noticed a few common warnings that was shown. First is "the machine-default permission settings do not grant local activation permission to the COM server application with CLSID and APPID", next is the same one, but "application-specific permission" instead. I am too dumb to know any of these mean, but I don't think it is related to the freezing problem, since it happened in other non-freezing days, too.

**Comment by Necrolion99** [comment]
Also, while my laptop is weaker than most professional gaming laptop, I know it is not related to weak hardwares or anything. I have never experienced overheat, and have handled worse programs running. I was able to run most games at max setting juat fine, and run a video upscaler continously for 12+hrs. The only reason my laptop has ever frozen besides MPC-HC is running the same upscaler at a setting not supported by my laptop's GPU. It makes no sense for a video viewer that doesn't consume much resource to completely freeze my laptop, while every other resource hogging apps don't. As mentioned, I am a bit illiterate in term of technology, and I don't know if any information I probided actually help, so any helpa is very very appreciated, because it has been quite frustrating. Thank you, and very sorry if I sound annoying.

**Comment by clsid2** [comment]
If event viewer logs the power button shutdown, then it doesn't seem to be a full system freeze.

Try pressing Ctrl+Shift+Esc to open Task Manager when player freeze happens. If that works, then right-click on mpc-hc64.exe and create a dump file.

You can also try Winkey+Ctrl+Shift+B to restart the graphics driver.

**Comment by Necrolion99** [comment]
> If event viewer logs the power button shutdown, then it doesn't seem to be a full system freeze.
> 
> Try pressing Ctrl+Shift+Esc to open Task Manager when player freeze happens. If that works, then right-click on mpc-hc64.exe and create a dump file.
> 
> You can also try Winkey+Ctrl+Shift+B to restart the graphics driver.

I can't do anything when it freezes, though. Crtl+Shift+Esc, Ctrl+Alt+Delete. None worked.  Tried the graphic driver restart. Still can manually trigger the freezes. As usual, I tried all button combinations, and nothing worked, so I left the laptop by itself for 30min. When I got back, my laptop has restarted itself, ans for some reason the Vega GPU diasabled itself, too. I also have to re-update the 2 GPU drivers again, despite them showing to be the latest version just yesterday. I guess there is something wrong with the GPUs. Still very strange that it only happens to MPC-HC, and specifically older videos.

**Comment by clsid2** [comment]
Maybe Windows update is messing with the drivers. Disable automatic driver updates, so that it won't install old drivers behind your back.

It might be related to the video playback TDR bug in the AMD driver:
https://community.amd.com/t5/drivers-software/rx-400-amp-rx-500-tdr-after-video-playback-fixed-with-21-4-1/td-p/465699

**Comment by ale5000-git** [comment]
Try to [disable automatic restarts](https://www.stellarinfo.com/blog/how-to-stop-automatic-restart-windows-10-issue/) so you see the real blue screen (with a code) instead of a restart in case of system crash.

PS: Just follow the instruction to disable it, doesn't download the things offered.
