### ISSUE TITLE
GIFs rendering colors incorrectly with a blue color shift

### ISSUE THREAD

**Issue by akaleeroy** [clsid2/mpc-hc#108]
Upgraded from v1.7.1 by previous maintainer, noticed all .gif files are being rendered with a blue color shift, like there's a missing channel or something...?

mpc-hc64 v.1.8.6
![wrong](https://user-images.githubusercontent.com/4068718/59197818-ed103e80-8b9a-11e9-8ae4-3604223013dd.jpg)

correct colors
![correct](https://user-images.githubusercontent.com/4068718/59197842-01ecd200-8b9b-11e9-9ef6-c6be6e61e4bb.jpg)

Will supply more info on request, I don't know what to mention for this issue.

**Comment by clsid2** [comment]
Gifs render correctly here. Provide a sample file.

Bugs in the internal codes can be reported here:
https://github.com/Nevcairiel/LAVFilters/issues

**Comment by akaleeroy** [comment]
This problem occurs with _any_ GIF, that's why I didn't provide a sample.

**Comment by clsid2** [comment]
What is shown in: Menu > Play > Filters

**Comment by akaleeroy** [comment]
Filters currently loaded:
  - Enhanced Video Renderer (custom presenter)
  - LAV Video Decoder
  - LAV Splitter Source (internal)

```
Filter : LAV Splitter Source - CLSID : {B98D13E7-55DB-4385-A33D-09FD1BA26338}

- Connected to:

CLSID: {EE30215D-164F-4A92-A4EB-9D4C13390F9F}
Filter: LAV Video Decoder
Pin: Input

- Connection media type:

Video: GIF  500x206 100fps

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Video {73646976-0000-0010-8000-00AA00389B71}
subtype: Unknown GUID Name {20464947-0000-0010-8000-00AA00389B71}
formattype: FORMAT_VideoInfo {05589F80-C356-11CE-BF01-00AA0055595A}
bFixedSizeSamples: 0
bTemporalCompression: 1
lSampleSize: 1
cbFormat: 88

VIDEOINFOHEADER:
rcSource: (0,0)-(500,206)
rcTarget: (0,0)-(500,206)
dwBitRate: 0
dwBitErrorRate: 0
AvgTimePerFrame: 100000

BITMAPINFOHEADER:
biSize: 40
biWidth: 500
biHeight: 206
biPlanes: 1
biBitCount: 32
biCompression: GIF 
biSizeImage: 412000
biXPelsPerMeter: 0
biYPelsPerMeter: 0
biClrUsed: 0
biClrImportant: 0

pbFormat:
0000: 00 00 00 00 00 00 00 00 f4 01 00 00 ce 00 00 00 ........ô...Î...
0010: 00 00 00 00 00 00 00 00 f4 01 00 00 ce 00 00 00 ........ô...Î...
0020: 00 00 00 00 00 00 00 00 a0 86 01 00 00 00 00 00 ........ ......
0030: 28 00 00 00 f4 01 00 00 ce 00 00 00 01 00 20 00 (...ô...Î..... .
0040: 47 49 46 20 60 49 06 00 00 00 00 00 00 00 00 00 GIF `I..........
0050: 00 00 00 00 00 00 00 00                         ........

- Enumerated media type 0:

Set as the current media type

```
