### ISSUE TITLE
Change in behaviour when adding network streams to playlist

### ISSUE THREAD

**Issue by neodyne** [clsid2/mpc-hc#1080]
Between the stable versions 1.9.10 and 1.9.11, apparently a change occured in how network streams are added to playlist in MPC-HC.

In MPC-HC 1.9.10, when multiple urls of mp3 files are added to playlist with `/add`, only the first one is processed (and played) and the player remains responsive. Each successive url is processed the moment it is about to be played.

In MPC-HC 1.9.11, in the same situation, the player locks up, processing all the links at the same time, and becomes responsive only after all are done. This happens regardless of `youtube-dl` being present or not.

This is highly inconvenient, for multiple reasons:

- the player can lock up for a significant amount of time (up to a minute), depending on how many urls are being added, reporting as `(Not responding)`
- streaming remote resources from the same server (e.g. podcast episodes) often becomes impossible, due to rate limiting. If you add a whole podcast to be played in MPC-HC, and the player wants to process all the episodes at once, the server ends up serving `429 Too Many Requests` (This wasn't a concern when links were processed as played)
- if for whatever reason *any* of the supplied urls do not resolve / error out, the playlist is not played as a whole (`cannot render file`)

I can imagine processing the playlist like this can be useful when dealing with links that end up using the ytdl hook, but surely for the urls that don't need it this isn't the case.

Could this change be reverted (or at least adjusted a bit), or alternatively, is there a setting that can be changed to go back to pre-1.9.11 behaviour?

EDIT: It seems #1032 is the culprit, merged between 1.9.10.56 and 1.9.10.68.

**Comment by clsid2** [comment]
Fixed

**Comment by neodyne** [comment]
@clsid2 Thank you for looking into this, unfortunately the issue is not fixed in its entirety. After testing the new dev build (1.9.11.22), the issue persists with mp3 links that have additional characters after the file extension, for example in [this podcast feed](https://theblacktapes.libsyn.com/rss) (in the XML, note the url in enclosure of any episode).

I see that MPC-HC [skips further processing](https://github.com/clsid2/mpc-hc/blob/develop/src/mpc-hc/mplayerc.cpp#L359) for selected formats now, based on a check of the file extension. Maybe the url should be stripped of additional characters after the extension for this check, but not as an actual url to be played (some resources may not stream without the proper parameters following `?` after the extension).

Another aspect of this issue also became apparent; file urls (without extension) in [this podcast feed](https://spotifeed.timdorr.com/4rOoJ6Egrf8K2IrywzwOMk) cannot be added to playlist with `mpc-hc64.exe /add`, only the first one gets added. They are processed as the same way as they were in 1.9.10 (through `youtube-dl` if present); the difference is that mpc-hc stops after adding the first url.

**Comment by clsid2** [comment]
Fixed both issues.
