### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by greyboxgt** [clsid2/mpc-hc#1081]
Feature request: I would like to be able to directly update MPC-HC without having to go to Github releases page to download and execute the latest new version. Thank you!

**Comment by clsid2** [comment]
Request denied.

**Comment by greyboxgt** [comment]
It would be nice to know why so other people would not put the similar request back.

**Comment by clsid2** [comment]
BECAUSE I DON'T WANT TO SPEND MY VALUABLE FREE TIME DOING THINGS THAT I DON'T WANT TO DO.

AND I AM ACTION LIKE AN ASSHOLE BECAUSE I AM FUCKING SICK AND TIRING OF WHINING LITTLE BITCHES WHO DEMAND EXPLANATIONS FOR EVERY REQUEST THAT I CLOSE.
