### ISSUE TITLE
[Feature request] Command-line option to generate thumbnails image from video file "mpc-hc.exe /thumbnail"

### ISSUE THREAD

**Issue by jbruchon** [clsid2/mpc-hc#1082]
I use MPC-HC to generate thumbnail preview images, but have to do so manually. I would like a way to automate thumbnail preview image generation using the command line, like so: `mpc-hc.exe infile.mp4 /thumbnail outfile.png`

Edit: in support of this request, I am far from the first person to want to do it, as seen here:

* [batch create image contact sheet from videofiles?](https://www.donationcoder.com/forum/index.php?topic=7569.0)
* [Looking For a Thumbnail Maker Similar Like MPC-HC](https://forum.videohelp.com/threads/391687-Looking-For-a-Thumbnail-Maker-Similar-Like-MPC-HC)
* [Batch thumbnails with MPC-HC](https://forum.doom9.org/showthread.php?t=150301)

Most of theser users are using AutoHotkey or similar keystroke scripting tools as a workaround to automate pressing the menu keys. I'd like to just have a CLI option.

**Comment by agatakotecka** [comment]
Is this feature implemented or not Mr @clsid2 ?

**Comment by clsid2** [comment]
menu > help > command line switches
