### ISSUE TITLE
Being asked to upload subtitles for any video without them.

### ISSUE THREAD

**Issue by DurotarHeights** [clsid2/mpc-hc#1084]
When I play an mp4 that has no subtitles a prompts appear to both upload and download subtitles.

![image](https://user-images.githubusercontent.com/68454533/117414318-ff10ce00-aee4-11eb-895d-0ce22a529f21.png)

The options window in the last few builds is sized incorrectly and I can't see the whole Subtitles -> Misc windows. Maybe there's an option to turn off offering me to upload subtitles but I can't see the right end of the window.

![image](https://user-images.githubusercontent.com/68454533/117413958-945f9280-aee4-11eb-87ec-4b1a475e8e6c.png)

I on the latest Windows 10 build 20H2 and tried 1.9.11.14 and the last 3 versions before that on the downloads page and they all showed this behavior. However it didn't start until today. Resetting the settings on the install didn't help.

**Comment by clsid2** [comment]
Options > Miscellaneous > Reset

You should not be getting those screens unless you press the keyboard shortcuts for those functions, which are "D" (download) and "Ctrl+U" (upload).

**Comment by DurotarHeights** [comment]
I was resetting the settings when I installed the different builds. I reset it again to no avail.

And the problem is that I am NOT pressing those shortcuts. And no, my keys are not stuck.

**Comment by clsid2** [comment]
You are the only person with this problem, so I don't know what is wrong. Something else on your computer must be messing with the application.

**Comment by DurotarHeights** [comment]
Well, I wiped the entire install, deleted every file and directory related to MPC, and reinstalled.

Problem is gone.

**Comment by avoroshilov** [comment]
@DurotarHeights do you remember by any chance which folders did you delete? I've tried wiping MPC-HC completely and reinstalling, and still getting the same issue. I think it started appearing after the Win10 update (I now have 20H2 19042.1052), but cannot tell for sure since I do not use MPC often. Now whatever I do, I am getting the same exact issues that you have - both download and upload subtitles windows open each time I open MPC-HC, and when I try to open Options from them, I am getting this same cut off window as your second screenshot. I've managed to restore the size of this window (it goes ok after pressing OK in the options window and then re--opening it through those pop up windows) - but that's just a regular options window and fiddling with it absolutely didn't make the error go away.

**Comment by avoroshilov** [comment]
@clsid2 resetting settings does not help; clearing hotkeys for download and uploading subtitles doesn't help either..

**Comment by clsid2** [comment]
Some who also had this problem told me that in his case it was caused by "Slack" messenger. That application started to unhide hidden/disabled windows from other applications.

**Comment by avoroshilov** [comment]
Hm, that's interesting. Unfortunately I cannot test/verify that since the problem **just went away on its own** today.

¯\_(ツ)_/¯

Will try to check out if Slack has any effect on this situation once I will be able to reproduce. Thanks for the info!

**Comment by DurotarHeights** [comment]
> @DurotarHeights do you remember by any chance which folders did you delete? I've tried wiping MPC-HC completely and reinstalling, and still getting the same issue. I think it started appearing after the Win10 update (I now have 20H2 19042.1052), but cannot tell for sure since I do not use MPC often. Now whatever I do, I am getting the same exact issues that you have - both download and upload subtitles windows open each time I open MPC-HC, and when I try to open Options from them, I am getting this same cut off window as your second screenshot. I've managed to restore the size of this window (it goes ok after pressing OK in the options window and then re--opening it through those pop up windows) - but that's just a regular options window and fiddling with it absolutely didn't make the error go away.

Sorry, no I do not remember. I had the problem re-appear a few days ago, but it went away on it's own without even a re-install.

I do have Slack installed on my computer, which makes some kind of inter-action causing this possible.

**Comment by clsid2** [comment]
It seems pretty clear that Slack is the cause. Everyone who has this issue has it installed. I suggest reporting this bug to them, so they can fix it.

**Comment by southrop** [comment]
Been having this issue with 1.7.13 (the last stable before the project shutdown) and I can confirm that the Slack desktop app was the cause. Killing the Slack app via Task Manager stopped this issue from occurring. The issue didn't occur after restarting the Slack app though, so it might only be an issue that occurs after keeping the app for a while.
