### ISSUE TITLE
Playlist !!!

### ISSUE THREAD

**Issue by Arkady23** [clsid2/mpc-hc#1085]
Please make a playlist. I can download a list of videos from my ip camera. If I have a YouTube module, then your player plays them well over a local network. But it is very inconvenient to watch each record separately.

**Comment by MadokaAyukawa** [comment]
There is a playlist feature. I've use it for years.

**Comment by clsid2** [comment]
Menu > View > Playlist

**Comment by Arkady23** [comment]
> Menu > View > Playlist

Thanks
