### ISSUE TITLE
[Feature Request] Show audio track names like VLC

### ISSUE THREAD

**Issue by aaddaammgg** [clsid2/mpc-hc#1086]
In VLC, it shows all audio track names that I named from OBS.

**MPC-HC**
![image](https://user-images.githubusercontent.com/9024049/117523554-e00a4e80-af6d-11eb-88ad-bc4e038e749b.png)

**VLC**
![image](https://user-images.githubusercontent.com/9024049/117523567-f7493c00-af6d-11eb-94e5-4c568f65e70f.png)

**Comment by Quantummmm** [comment]
> Can u open this video with mediainfo?
> I know MPC-HC use handler_name rather than title metadata of a audio track.

I opened it with mediainfo and it shows all the names for each of the audio tracks

![image](https://user-images.githubusercontent.com/9024049/117523907-b81bea80-af6f-11eb-93d7-e114a38e0c62.png)

**Comment by clsid2** [comment]
This has to be done in LAV Filters.
