### ISSUE TITLE
Symbol in Subtitle doesn't render properly

### ISSUE THREAD

**Issue by pandavova** [clsid2/mpc-hc#1088]
Im on Windows 10, using the standard K-Lite Codec Pack 16.1.5, MPC-HC 1.9.11.14 (4cce4c81f) with madVR. I tried the internal subtitle renderer, the VSFilter / DirectVobSub thing and the XySubFilter.

Everyone of those doesn't render the music note that should be displayed. VLC renders it correctly. 

MPC-HC: 
![mpc-hc64_08 05 2021_23-58-09](https://user-images.githubusercontent.com/9296158/117555606-e1687380-b060-11eb-8c71-e7bcf12c0b89.png)

VLC: 
![vlc_08 05 2021_23-57-34](https://user-images.githubusercontent.com/9296158/117555610-e9c0ae80-b060-11eb-9902-8924d9fe83d0.png)

**Comment by clsid2** [comment]
That happens when the font does not contain that character, and the font also doesn't have a fallback font. Only solution is the change the font in the subtitle. For example Tahoma instead of Arial. So creator of file choose a wrong font.

Font rendering is done differently in VLC. There probably will be an option in the future to use libass in MPC-HC, which will give similar results as VLC. Including bugs that VLC has MPC-HC doesn't have.

**Comment by clsid2** [comment]
Can you give a link to this video?

**Comment by pandavova** [comment]
Here is the nyaa link: https://nyaa.si/view/1383295 
If you need a direct dl, I can reupload it. 

Its about the character "♬" or U+266C. 
The fonts in this .mkv are "Roboto-Medium.ttf" and "Roboto-MediumItalic.tff", so yeah, looks like this font doesn't support the "Miscellaneous Symbols" unicode block and there isn't a fallback font.

**Comment by MadokaAyukawa** [comment]
> Font rendering is done differently in VLC. There probably will be an option in the future to use libass in MPC-HC, which will give similar results as VLC. Including bugs that VLC has MPC-HC doesn't have.

Is this why sometimes the font colors seem a little bit lighter in MPC vs VLC? This is really only noticeable when the typesetter tries to match the colors of on-screen text, and it seems lighter in MPC.

**Comment by clsid2** [comment]
That is unrelated to fonts.
https://github.com/clsid2/mpc-hc/issues/974

**Comment by clsid2** [comment]
Libass actually is not going to solve this problem. At least not with its default settings.

I am closing this because I do not consider this to be a bug. File creators should use a proper font.
