### ISSUE TITLE
fuzzy image on different devices.

### ISSUE THREAD

**Issue by silentvoice84** [clsid2/mpc-hc#1089]
Greetings,

I was watching GoT on my older laptop which is connected to 21" screen through VGA connection, the image is clear as crystal but When I changed to my other laptop the video quality is lower even that i'm using the same version of codecs and MPC

I'm not sure why the "better" laptop gives a worse image, specially in dark areas I'll post an image.

this is from MPC
![game of thrones s02e03 1080p bluray x264-rovers mkv_snapshot_42 53_ 2021 05 09_16 45 14](https://user-images.githubusercontent.com/83912645/117574875-eb818500-b0e7-11eb-914e-1bb984f1f87a.jpg)
 
This is from VLC
![game of thrones s02e03 1080p bluray x264-rovers mkv_snapshot_42 53_ 2021 05 09_16 45 14 vlc](https://user-images.githubusercontent.com/83912645/117575298-dd346880-b0e9-11eb-8a2d-713e540ab195.jpg)

**Comment by clsid2** [comment]
The MPC-HC screenshot looks better to me, and the VLC one is very dark.

If you have an Intel GPU, then go into the driver settings. Disable stuff like "Dynamic Contrast" and "Fleshtone Enhancement".

**Comment by clsid2** [comment]
I can't provide any more help without details about both laptops. Most importantly the GPU they have.

**Comment by hooke007** [comment]
Is the source HDR? The difference is tone mapping from your pictures.

**Comment by clsid2** [comment]
The default renderer does not support HDR tonemapping. For playback of HDR videos you need to install an extra video renderer: [madVR](http://forum.doom9.org/showthread.php?t=146228) or [MPC Video renderer](https://github.com/Aleksoid1978/VideoRenderer).
