### ISSUE TITLE
Online subtitle search failed

### ISSUE THREAD

**Issue by dafuki** [clsid2/mpc-hc#109]
Can't seem to find any subtitles anymore
https://paste.pics/028b4dfd423457e7f1c320e062f65b41
https://paste.pics/5STS1

Tried turning firewall off, no change.
Procmon doesn't show any network activity from mpc-hc64.exe.
This happened before I changed to the clsid builds, I was using the latest official version.
Also I'm on Windows 10 18912.1001, might be related.

**Comment by clsid2** [comment]
Probably an issue with the Windows firewall.

**Comment by dafuki** [comment]
> 
> 
> Probably an issue with the Windows firewall.

The firewall was entirely turned off, plus the app doesn't seem to even generate a request via Procmon.
Do you think it is an internal Insider Build issue?

**Comment by clsid2** [comment]
It works on other systems, so yes, it must be an Insider build issue. There are no debugging options besides compiling it yourself. I am not interested in spending time testing Microsoft's broken builds.
