### ISSUE TITLE
Subtitle for video online

### ISSUE THREAD

**Issue by comproperty247** [clsid2/mpc-hc#1090]
I tried to find over the options or if I'm missing something with the player..
But is not the first time, I saw a video online but can't get any subtitle when I go to "Download subtitles" or by pressing "D".
This works well for local videos! Congrats!
But this a bug or I need to change something over the options?

Any recommendations will be welcome.

Regards.

**Comment by clsid2** [comment]
It has only been tested with local files. I am not interested in supporting this functionality for online videos.
