### ISSUE TITLE
HTML Subtitle formatting

### ISSUE THREAD

**Issue by Revenger** [clsid2/mpc-hc#1092]
Can we get options to ignore or render the html formatting in mpc-hc?
I tried a video file that uses embedded subtitles, but also has formatting codes, as it was hard to find the movie to begin with in VLC the subs render fine in HPC-HC the formatting codes are shown as per screenshot.

So if we can get options to ignore or render the formatting codes that would be great.

![mpc-hc](https://user-images.githubusercontent.com/597280/117946049-82954980-b341-11eb-9bc7-a77e310166a0.PNG)

**Comment by clsid2** [comment]
Fixed
