### ISSUE TITLE
register MPC-HC as available player in Settings > Apps > Default Apps

### ISSUE THREAD

**Issue by freesbee98** [clsid2/mpc-hc#1093]
And before you ask, it is not possible for MPC-HC (or any other app) to force itself as a default.

_Originally posted by @clsid2 in https://github.com/clsid2/mpc-hc/issues/294#issuecomment-593007852_

What is written here corresponds to my experience: the possibility of programs to set them as "default" is something that for some reason Microsoft does not like. It is possible to remove a program association with SetUserFTA, but it is not possible to set a certain program as default.
Nevertheless the real problem is that, even if MPC-HC is installed in the operating system, it is NOT offered as video/audio player among the Settings > Apps > Default Apps.
To my current knowledge one program can be added to the available apps only with elevation, and during installation MPC-HC definitely has elevation.
Would it be possible to add a switch to the installer, in order to add MPC-HC among the available players? Alternatively this could be done by default by the installer, as there is nothing bad in offering MPC-HC among the available players in the system.
The former version that was embedded with CCCP could register itself among the available players. It's a big pity that this one cannot.
(I would gladly contribute since I love this program, but my knowledge of C++ is zero)

**Comment by clsid2** [comment]
You can register it here:
Options > Player > Formats

If you want an advanced installer that does everything for you, then you should use K-Lite Standard. That not only registers all formats but also uses SetUserFTA to directly set it as default player.

I have no plans to improve the installer of MPC-HC.

**Comment by Dragodraki** [comment]
It is possible with SetUserFTA, but you have to define many registry entries before (any app must defined with a specifix label, SetUserFTA can relate on). This is the standard way and would help also to get things like context menue items, icons, redirect and more.

Ready setups create those reg-entries when installing. Here are two examples:
Mozilla Firefox has the label "FirefoxURL-308046B0AF4A39CB", SetUserFTA actually works with them.
And Adobe Reader has the label "AcroExch.Document.DC".

Any app (like MPC) which isn't registered already, SetUserFTA can do nothing. Other than the developer means, it doesn't work with direct paths.

But please don't ask all referred registry-entries now. They are too much to explain all of them now. But here are some pathes
(compare entries with VLC-Media Player):

HKCU\Software\Classes\.mp3...
HKCU\Software\Classes\NAME-OF-YOUR-UNIQUE-LABEL.mp3...
HKCU\Software\Classes\Applications\...
HKCU\Software\Classes\mp3_auto_file\shell\open\command...
HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.mp3\...

HKCR\.mp3...
HKCR\.mp3\shell\open\command...
HKCR\NAME-OF-YOUR-UNIQUE-LABEL.mp3...

HKLM\SOFTWARE\Clients\Media\Media Player Classic\Capabilities...

HKCR\MPC-HC_Special.mp3\shell\NAME-OF-YOUR-UNIQUE-LABEL.enqueue...
HKCR\MPC-HC_Special.mp3\shell\NAME-OF-YOUR-UNIQUE-LABEL.play...
HKCR\SystemFileAssociations\.mp3\shell\NAME-OF-YOUR-UNIQUE-LABEL.enqueue...
HKCR\SystemFileAssociations\.mp3\shell\NAME-OF-YOUR-UNIQUE-LABEL.play...

And that you'll have to do with every extension and both OS architecture EXE's (x86 and x64)

**Comment by hooke007** [comment]
>Nevertheless the real problem is that, even if MPC-HC is installed in the operating system, it is NOT offered as video/audio player among the Settings > Apps > Default Apps.

Hmm...Why I can do this?
![Snipaste_2021-05-13_22-07-49](https://user-images.githubusercontent.com/41094733/118137666-0c274300-b438-11eb-9e4d-04e427b0cfd6.jpg)

**Comment by clsid2** [comment]
As I have already said, all required registry keys for the default app registration are created by MPC-HC through:
Options > Player > Formats

**Comment by freesbee98** [comment]
> Hmm...Why I can do this?

The reason why you can do this is that MPC-HC is already "known" as a player on your OS.
If you make a clean install you will not see the option.

> As I have already said, all required registry keys for the default app registration are created
> by MPC-HC through Options > Player > Formats

This is true, but elevation is needed to be able to access that command (which technically writes registry entries in HKLM and HKCR I presume... which was exactly what I have asked to be done by installing the program).

Nevertheless the suggestion of clsid2 is absolutely fine to my task: I will verify if using the "K-Lite Codec Pack Standard" does the job properly, hoping that it has a switch for silent install. Of course I will report my findings here.

**Comment by clsid2** [comment]
K-Lite supports fully customized silent installs. It's installer is super advanced.

MPC-HC has command line parameters for registration of the file formats. That is something you could manually run after the installer has completed.

**Comment by freesbee98** [comment]
from my perspective the functionality of K-Lite is absolutely ok. I have already tested it, and it satisfies my needs entirely. Nevertheless, knowing MPC-HC command line parameters would be very useful for other tasks

**Comment by clsid2** [comment]
Menu > Help > Command line
