### ISSUE TITLE
Displaying of file extensions in Options - Player - Format

### ISSUE THREAD

**Issue by Rhiannon81** [clsid2/mpc-hc#1094]
In Options - Player - Format, file extensions (between parentheses) for AVI and Other (divx amv etc.) are displayed with a dot, as opposed to all other items which are not.

Each time you toggle a selection and save your settings, an additional dot is added.

Screenshot for clarity.

![immagine](https://user-images.githubusercontent.com/35920225/118162773-ac697180-b410-11eb-86e8-f92c577e95b5.png)

**Comment by clsid2** [comment]
Fixed
