### ISSUE TITLE
Subtitle Freezing Issue

### ISSUE THREAD

**Issue by MadokaAyukawa** [clsid2/mpc-hc#1095]
Just mentioning it here. The buffer was defaulted to 0 from 10 because it caused some anime with heavy overlays to not display all the lines and was changed in 1.9.10.

But a friend was playing [Judas] Kimetsu no Yaiba - S01E23.mkv with the latest stable. At 12:10 when the guy says "Five times" the video will freeze for a few seconds with the audio playing normally. This is due to an overlay in the next scene. Then the video jumps ahead. Setting the buffer to 10 stops the stuttering and shows the overlay.

But in the same episode at 12:47, if the buffer is set to 10, then the original problem of complex subs not appearing shows up so the overlay is not shown. With the buffer set to 0, it stutters like above.

There is not a setting that seems to play this episode without issues. I tried setting the subtitle resolution lower but that didn't help the first issue with buffer at 0. This happens with the latest developmental build as well. VLC with libass plays both scenes ok.

You can get the episode from this torrent: https://nyaa.si/view/1280887

**Comment by clsid2** [comment]
Which CPU do you have?

I get no freeze on an 11 year old CPU and 1920x1200 screen.

Both overlays are working fine here with both buffer 0 and 10.

When there is a performance issue, it either waits (buffer 0) or drops (buffer >0).

**Comment by MadokaAyukawa** [comment]
It happens on an Intel Core i7-8550U. I tried it on an Intel Corei7-870 (Win 7), and it seems to work fine.

My friend has a Core-i5 4690K, GPU is GTX 1060 6 GB, with an SSD.

**Comment by clsid2** [comment]
Single core performance is what matters for subtitle rendering. Laptop CPUs often have low performance in that regard.

Extracted the relevant piece of the sub:
```
Dialogue: 2,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(1057.455,593.707)\fscx26\fscy44\frz328.8\fnsplatter\fs100\b0\bord0\shad0\c&HEAEAEA&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 2,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(1091.233,623.929)\fscx26\fscy44\frz328.8\fnsplatter\fs100\b0\bord0\shad0\c&HEAEAEA&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(1055.232,603.04)\fscx17\fscy47\frz328.8\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(1127.232,640.373)\fscx17\fscy47\frz328.8\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(1093.454,620.818)\fscx17\fscy47\frz328.8\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(1039.232,598.596)\fscx17\fscy47\frz328.8\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 0,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\an7\fnsplatter\b0\c&HDEE1E0&\bord0\shad0\fs100\pos(1102.4,553.2)\blur8\fscx100\fscy100\p1}m -173 -44 l -83 -105 180 50 99 96
Dialogue: 2,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(826.141,769.936)\fscx26\fscy44\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HEAEAEA&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 2,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(849.633,780.729)\fscx26\fscy44\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HEAEAEA&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(813.632,759.84)\fscx17\fscy47\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(885.632,797.173)\fscx17\fscy47\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(851.854,777.618)\fscx17\fscy47\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(797.632,755.396)\fscx17\fscy47\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(885.632,797.173)\fscx17\fscy47\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(851.854,777.618)\fscx17\fscy47\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(797.632,755.396)\fscx17\fscy47\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 2,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(1011.055,723.307)\fscx26\fscy44\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HEAEAEA&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 2,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(1044.833,753.529)\fscx26\fscy44\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HEAEAEA&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(1008.832,732.64)\fscx17\fscy47\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(1080.832,769.973)\fscx17\fscy47\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(1047.054,750.418)\fscx17\fscy47\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(992.832,728.196)\fscx17\fscy47\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(1080.832,769.973)\fscx17\fscy47\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(1047.054,750.418)\fscx17\fscy47\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 1,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(992.832,728.196)\fscx17\fscy47\frz43.09\fnsplatter\fs100\b0\bord0\shad0\c&HD2D4D2&\blur2}SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ
Dialogue: 0,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\an7\fnsplatter\b0\c&HDEE1E0&\bord0\shad0\fs100\blur8\pos(870.4,670)\fscx100\fscy100\p1}m -306 109 l -40 -112 122 0 -129 220
Dialogue: 2,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\pos(1066.047,588.381)\frz-30.41\fax-0.43\fnHand Of Sean\fs55\bord0\shad0\c&H323132&\blur0.9}Medicine
Dialogue: 2,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\fnHand Of Sean\c&H323132&\fs55\bord0\shad0\frz-30.41\fax-0.43\blur.9\an7\pos(877.933,525.067)}For Agatsuma Zenitsu:
Dialogue: 2,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\fnHand Of Sean\c&H323132&\fs55\bord0\shad0\frz-30.41\fax-0.43\blur.9\an7\pos(854.893,574.097)}Take 5 times daily
Dialogue: 2,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\fnHand Of Sean\c&H323132&\fs55\bord0\shad0\frz-30.41\fax-0.43\blur.9\an7\pos(839.213,624.957)}After each meal
Dialogue: 2,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\fnHand Of Sean\c&H323132&\fs55\bord0\shad0\frz-30.41\fax-0.43\blur.9\an7\pos(763.586,702.327)}7 days' worth
Dialogue: 0,0:12:15.71,0:12:18.21,Default,,0,0,0,,{\an7\bord0\shad0\blur4\c&HDCDFDE&\fscx100\fscy100\p1\pos(812,687.6)}m 62 -183 l 227 -97 299 -55 356 -16 366 2 31 283 -96 210 -240 78
```
Analysis is required which of these tag(s) are slow.

**Comment by clsid2** [comment]
The lines with the text "SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ" seem totally useless to me. Does anyone know what their purpose is? They do nothing but draw some bullshit white text behind the white overlay text background. I almost feel like those lines are there just to make things slow...

**Comment by clsid2** [comment]
Does anyone have any videos from a different series that has the same issue?

**Comment by MadokaAyukawa** [comment]
> The lines with the text "SJDKFHSD\NSDFJHRKJHGT\NEJKSHFKJ" seem totally useless to me. Does anyone know what their purpose is? They do nothing but draw some bullshit white text behind the white overlay text background. I almost feel like those lines are there just to make things slow...

They are using it to make the background match the paper's appearance as the white mask they use is totally uniform.

Original Text:
![image](https://user-images.githubusercontent.com/44476321/118369669-1e4cd280-b559-11eb-836a-5f32a20ee018.png)

With Mask Only:
![image](https://user-images.githubusercontent.com/44476321/118369703-40deeb80-b559-11eb-8623-c606e72b5fbc.png)

With Mask and those extra lines:
![image](https://user-images.githubusercontent.com/44476321/118369729-5bb16000-b559-11eb-8fb9-7478a9e301b1.png)

With no mask, but with the extra lines:
![image](https://user-images.githubusercontent.com/44476321/118369823-c5ca0500-b559-11eb-8148-6a7d7c39881b.png)

I played this section in Aegisub with both libass and vsfiltermd_textsub as the subtitle provider and both play fine on the machine that stutters. Not sure that helps but just putting it here.

**Comment by MadokaAyukawa** [comment]
I tired the following. I used mkvtoolnix and extracted the English subtitle into an external file. I then removed all subtitle tracks from the file, making new a raw file. I then inactivated those SJDKFHSD lines out for the first instance at around 12:07 in the subtitle file. Using this subtitle file with the raw resulted in normal play for the first instance of the medicine bag and stuttering for the second instance. Playing the raw resulted in normal play for both. I then changed the \fnsplatter tag in those lines to \fnArial so it uses a locally installed font and reactivated those lines. Playing this latest file resulted in normal play for the first instance with Arial and stuttering with the second instance with splatter. The splatter font is included as an attachment in the video file, but is not installed on my computer. Could the stutter be due to some issue in retrieving the font from the file to use?

**Comment by clsid2** [comment]
Embedded fonts are loaded when opening the file. They don't need to be installed. Embedded fonts are very common for Anime videos and they generally don't have any issues.

But it is interesting that the font has impact on the performance. Maybe the splatter font is more difficult to render. Or something is wrong with this font that causes a delay.

**Comment by clsid2** [comment]
I have tracked down the slowness.

It is caused by the call to CloseFigure() in Rasterizer::EndPath()
This function is a Windows GDI API function, so there is not anything I can do to fix that.

I don't see any solution except replacing this specific font with Arial when parsing the subtitle.

**Comment by MadokaAyukawa** [comment]
I'm just curious, why doesn't this happen with VLC and libass?

**Comment by clsid2** [comment]
Those doesn't use GDI for font rendering but use Harfbuzz instead.

Using libass in MPC-HC is not ready for public use yet. The implementation in MPC-HC is still too buggy at the moment.

Using Arial as an alternative is an easy workaround. Do you have any other files with the same problem, but with other font?

**Comment by MadokaAyukawa** [comment]
I don't, but I've asked my friend if he knows of any other series as he watches more anime.

Although the Arial alternative isn't that easy for the average user. For example, my friend asked me about this issue as he doesn't know about subs or HC. He wouldn't know how to change the font to Arial as that's in an override tag in the script which would be not be editable in the video file. He said that he had to use VLC for the final episodes.

**Comment by clsid2** [comment]
I will modify MPC-HC to automatically adjust the subtitle style during playback. So you don't need to do anything yourself.

That should fix the problem for this series. But a similar issue might exist with other fonts.

**Comment by hooke007** [comment]
Maybe GDI is not the core problem. By testing pfmod's vsfilter, it plays smooth.

**Comment by MadokaAyukawa** [comment]
It also plays ok on my older Win 7 machine, although I wouldn't know if things are different from the Win 10 machine.

**Comment by clsid2** [comment]
I am 100% sure it is the call to GDI CloseFigure() is where the delay happens. The problem is only noticeable if the delay is long enough (on a slower system).

With xy-VSFilter there is indeed much less slowdown with that call. Which is weird, since it uses almost identical code there. I need to investigate more.

**Comment by clsid2** [comment]
1.9.11.53 uses Arial font instead of splatter and should give good performance.

**Comment by astiob** [comment]
I want to point out that this change, obviously, makes subtitles _look wrong_ for _everyone_ to fix a slight stuttering in one file for one person.

**Comment by astiob** [comment]
Not to mention that even in this file and this scene—not even considering any other files that may use the same font—substituting Arial makes for visible grey and white letter shapes that are quite jarring once you notice them (view at full screen):
![Judas  Kimetsu no Yaiba - S01E23 mkv_snapshot_12 17 000](https://user-images.githubusercontent.com/515193/187093909-7ff286ce-feaf-4380-bbae-0bd84d886298.png)

which isn’t the case in mpv, which obediently uses the named font:
![mpv-shot0002](https://user-images.githubusercontent.com/515193/187095051-54df3ef2-3199-4435-b227-31f246c96344.jpg)

On the other hand, to be fair, when I tried XySubFilter, it seemed to _drop_ the splatter lines entirely, rather than render them quickly. Wut?
![Judas  Kimetsu no Yaiba - S01E23 mkv_snapshot_12 17 000_XySubFilter](https://user-images.githubusercontent.com/515193/187094139-5642a447-541f-4751-9597-b0e6dfa90478.png)
Same in xy-VSFilter, even old CCCP xy-VSFilter (so it isn’t pinterf’s bug), although I had to use CCCP’s equally old MPC-HC to test it because current MPC-HC [crashes instead](https://github.com/clsid2/mpc-hc/issues/452). And by the way, it also crashes with pinterf’s latest build of xy-VSFilter, with seemingly random stack traces (now that it launches visible Doctor Dump) and seemingly with a non-100% probability (I’ve had it work a few times some three months ago, although today was a zero success rate), sometimes upon file open and sometimes later—which is why I resorted to trying an older xy-VSFilter in the first place. x64 if it matters.

**Comment by clsid2** [comment]
This subtitle script is one of the most idiotic I have encountered in my life. Using a massive amount of blurry text to create a background. Ugh.

**Comment by astiob** [comment]
No arguing with that :-) But that’s the reality of ASS. Real-world scripts _are_ that idiotic and even more idiotic than that. Subtitle authors just bash a hammer at the keyboard until the output looks just right; they don’t care how nice the resulting code seems to a programmer. And our thankless job as subtitle renderers is to render them correctly (but quickly).
