### ISSUE TITLE
Failed playing DTS Interactive (5.1 Surround) in MPC-HC with internal audio renderer

### ISSUE THREAD

**Issue by Dragodraki** [clsid2/mpc-hc#1096]
Briefly two facts:

1. In Windows I have under "Playback Devices" the default format "DTS Interactive (5.1 Surround)" (Realtek drivers make it possible). 
2. MPC-HC should use "Internal Audio Renderer" as audio renderer (much better quality than the native one)

![MPC-Renderer Problem](https://user-images.githubusercontent.com/76787321/118248845-0ca9f300-b4a5-11eb-818c-76d4da342147.png)

But both together don't work, then no sound comes (for mp3/flac/wav/...). Only when I either limit the format to 2 channels or change the renderer, I get sound. The result is not satisfactory.

Does anyone know a patch that I can use to teach the "Internal Audio Renderer" 5.1 channels?

**Comment by clsid2** [comment]
The internal audio renderer can output 5.1 channels just fine if you configure your sound device as 5.1, so that isn't the problem. The problem is likely in the transcoding functionality in the driver.

I don't have this functionality on my system so I can't test or fix any issues.

Try with the exclusive mode options disabled. Also disable everything on the Enhancements (Verbesserungen) tab.

**Comment by Dragodraki** [comment]
I tried these settings now, but there is still no sound.
If this depends on the driver (Relatek in my case), then it would be very bad, because Realtek became very common as an successfully standard audio driver...

"Default WaveOut" or "DirectSound" (mpc-settings) work with 5.1 but they are no option because quality is lower and volume varies extremely on different media types and computer hardware.

Have you another idea, I could try?

**Comment by clsid2** [comment]
Things to experiment with:
Mixer setting in internal audio decoder
"ignore system channel mixer" option of internal audio renderer

Loudness equalization in the sound enhancements can help with making volume more consistent between sources.

**Comment by clsid2** [comment]
Make a screenshot of this status page:
Menu > Play > Filters > Internal Audio Renderer > Status

**Comment by Dragodraki** [comment]
These changes unfortunately doesn't solve my problem too.

Here is the screenshot you asked for (after apply your recommended changes):
![Bild1](https://user-images.githubusercontent.com/76787321/118536788-6d0e8e00-b74c-11eb-8c7d-a50283ab3cc9.png)

**Comment by clsid2** [comment]
I don't have a solution for you.

**Comment by clsid2** [comment]
Try with [1.9.15.74 development build](https://github.com/clsid2/mpc-hc/releases/tag/1.9.15.4)
In the output options, select "MPC Audio Renderer". That will hopefully work correctly.

Note to self. For SaneAR it might be fixable by adjusting samplerate to system mix rate before checking format support. See [this commit](https://sourceforge.net/p/mpcbe/code/5241/tree//trunk/src/filters/renderer/MpcAudioRenderer/MpcAudioRenderer.cpp?diff=54bb00b7c4d104415b75022c:5240) from MPCAR.

**Comment by Dragodraki** [comment]
Thank you for the solution - it works.
When comparing the renderer (independent of surround or stereo), which one the best for highest quality? Is MPC Audio renderer also as good as the earlier "Internal Audio renderer" (possibly it's the same only with another name) or get SaneAR the better results?

**Comment by ale5000-git** [comment]
"Internal Audio renderer" is the old name of "SaneAR".

**Comment by clsid2** [comment]
There is not really any quality difference. So just use what works best for you.
