### ISSUE TITLE
Youtube-dl subtitles

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#1098]
This is fondamentally wrong: https://github.com/clsid2/mpc-hc/blob/develop/src/mpc-hc/YoutubeDL.cpp#L64
`--write-auto-sub` is correct for automatic captions but instead `--write-sub` is for normal subtitles.

PS: `--all-subs` is probably not needed and not used by youtube-dl for JSON (if I'm not wrong).

**Comment by clsid2** [comment]
It doesn't work without --all-subs

**Comment by ale5000-git** [comment]
If s.bUseAutomaticCaptions is false then it (incorrectly) doesn't add `--write-sub` so if both `--write-sub` and `--all-subs` are missing then it doesn't work but it should work if you add `--write-sub`.

At least when I have tried from command-line it worked like I have explained.

**Comment by clsid2** [comment]
Fixed
