### ISSUE TITLE
Preview aspect ratio wrong

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#1099]
What I suppose it happens:
Preview don't support rotation flag but still it set the rotated aspect ratio so it go wrong.

If you need a sample just tell me.

**Comment by adipose** [comment]
Sure, upload a sample.

**Comment by ale5000-git** [comment]
@adipose
Sample: https://easyupload.io/3vl2ft
Password: 123

Screenshot:
![screenshot](https://user-images.githubusercontent.com/15793015/122370526-68adde80-cf5f-11eb-8a65-477d1a996e3f.png)

**Comment by adipose** [comment]
We are using EVR to display the video, so built-in rotation flags are not sent to the renderer.  Hence, the AR is right, but the video is not rotated properly.

@clsid2, originally you suggested using EVR (and not EVR-CP).  What problems would EVR-CP add, potentially?  EVR-CP would support rotation.

I also think I can fix this by integrating MPCVR code to MPC-HC, a project I was planning to make it a tier-1 renderer.

**Comment by clsid2** [comment]
MPCVR doesn't support multiple simultaneous instances in one process. So that can't be used for preview.

We can maybe add option to use EVR-CP instead of EVR.

**Comment by adipose** [comment]
MPCBE has some code in the preview for an "internal" mpc-vr. I think it may bypass the limitation by having two copies. But I think it is used for MPCBE preview.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1176

This seems to work with the attached video.  I haven't done much else testing, but I assume it's ok for average videos, too.

**Comment by ale5000-git** [comment]
@adipose
Thanks, in the latest build automatic/manual rotation works perfectly on renders where EVR-CP is used in preview, but on renders where normal EVR is used (like VMR9 renderless) the aspect ratio is still wrong like in the first post.
The aspect ratio set in the preview window should respect wheter the render used for preview support rotation or not.

**Comment by ale5000-git** [comment]
An alternative easier way is to check whether width is higher than height and rotate aspect ratio accordingly.

**Comment by adipose** [comment]
> 
> 
> @adipose
> Thanks, in the latest build automatic/manual rotation works perfectly on renders where EVR-CP is used in preview, but on renders where normal EVR is used (like VMR9 renderless) the aspect ratio is still wrong like in the first post.
> The aspect ratio set in the preview window should respect wheter the render used for preview support rotation or not.

I don't understand what you mean by this:

> on renders where normal EVR is used (like VMR9 renderless)

When I fixed the code for EVC-CP rotation in the preview, I noticed a problem with the data returned by EVR-CP for the main window.  It didn't take into account the rotation.  So I made a new method to handle that.  It already worked for madvr and mpcvr.

Maybe VMR9 has a similar issue that isn't handled by that routine.  I'm not sure what is meant by "where normal EVR is used," though.

**Comment by ale5000-git** [comment]
@adipose
Look here: https://github.com/clsid2/mpc-hc/commit/9853c1aba86508eae3cec1e264417ff8519fa3ac (in FGManager.cpp)
When main renderer is EVR-CP, EVR-Sync, madVR, MPC-VR then the preview use EVR-CP
instead if the main renderer is normal EVR, VMR or other then is use normal EVR for preview.

**Comment by ale5000-git** [comment]
Sorry, my fault.
Probably I was trying with an older build.

**Comment by ale5000-git** [comment]
I have reproduced it again here: #1233
