### ISSUE TITLE
Program freeze after opening Options->Subtitles>Misc page

### ISSUE THREAD

**Issue by ahmedtds** [clsid2/mpc-hc#110]
If there is no internet connection and you open Options->Subtitles>Misc page and then close it by pressing OK or Cancel, program just freeze and you have to kill the process.

Fix it please, very annoying bug.

Thanks.

**Comment by clsid2** [comment]
It takes a few seconds for the connection request to timeout. After that the application closes successfully.

**Comment by ahmedtds** [comment]
It doesn't for me, it just freezes and never come back. Waited several minutes every time, more than a few seconds.

**Comment by ahmedtds** [comment]
@clsid2 Is it fixed? Why did you close it?
