### ISSUE TITLE
MPC-HC Seems to Handle Blur Tags Differently

### ISSUE THREAD

**Issue by MadokaAyukawa** [clsid2/mpc-hc#1102]
When played with mpv, I get the following with the \blur tags as indicated in the parentheses.

![image](https://user-images.githubusercontent.com/44476321/118529865-d369c100-b6f8-11eb-81a4-35ff2da8f108.png)

With MPC-HC, I get:

![image](https://user-images.githubusercontent.com/44476321/118529952-f3998000-b6f8-11eb-8d38-6a17989935c4.png)

The blur strength seems much less with HC such that it's not very noticeable the the lower values, and \blur1 is more intense in mpv than \blur1.5 in HC.

**Comment by clsid2** [comment]
The VSFilter/MPC-HC implementation is the de-factor standard ASS implementation, not the implementation from MPV/libass. I am not going to make any changes to it. That would change behavior of many existing subtitles.

**Comment by MadokaAyukawa** [comment]
Thank you for the information. The above has to do with the subtitle texture resolution.
