### ISSUE TITLE
Program freezes when changing playback speed

### ISSUE THREAD

**Issue by harmandmen** [clsid2/mpc-hc#1103]
I just want to report something that may be of some interest to developers.

When I use the _"CTRL+UP/DOWN arrow"_ keyboard shortcut to rise or lower the video playback speed I get erratic behaviours.

Sometimes (rarely) the speed changes instantly, but in most cases the playback stalls for a while before restarting (at the expected speed).
The duration of that "while" seems to vary on a random basis: sometimes a few seconds, other times a minute or even more.

**Comment by clsid2** [comment]
I am unable to reproduce such long freeze. So unless you can provide any details that allows me to reproduce, there is nothing I can do.

**Comment by harmandmen** [comment]
The only details I can add are those related to my system configuration:
Z590 chipset, i9-11900, 32GB DDR4, 1TB SSD, GeForce 9800 GT, Win10 64, updated drivers.
I don't know, however, if they can be useful anyhow.

As I said, I'm not complaining nor asking for anything; I just wanted to report and describe something I'm experimenting with the program.
The causes could lay anywhere, obviously; outside the program or... inside. That's why I decided to report. :]

**Comment by clsid2** [comment]
Try with the internal audio renderer:
Options > Playback > Output > Audio Renderer
