### ISSUE TITLE
Microsoft Store version for easier updates

### ISSUE THREAD

**Issue by Tminus1** [clsid2/mpc-hc#1107]
Updating is kind of a hassle. It would be nice to have MPC-HC on the Microsoft Store if it's possible.

**Comment by clsid2** [comment]
I don't like the Microsoft Store.

**Comment by Tminus1** [comment]
What a dumb reson

**Comment by clsid2** [comment]
Another reason:
I don't want to spend a lot of my precious free time to do things I don't want to do just to make YOUR life easier.
