### ISSUE TITLE
Memory leak with MP3 cover images

### ISSUE THREAD

**Issue by krishty** [clsid2/mpc-hc#111]
I let my MPC play MP3 overnight, and this morning I was surprised to find its working set in the order of gigabytes. After trying around a bit, I was able to reproduce the issue:

1. Play an MP3 file with an embedded cover image.
2. Add another MP3 file with an embedded cover image to the playlist (it can be the same file.)
3. Every time you press "forward" (or when the next file is played automatically, if you’re patient), MPC's working set grows by ~0.5–2 MiB (depending on the specific file).

This does not happen if there are no cover images in the MP3, so I suspect there is a memory leak in the cover handling …

**Comment by adipose** [comment]
Fixed in https://github.com/clsid2/mpc-hc/pull/191
