### ISSUE TITLE
Hello, God, I need your help.

### ISSUE THREAD

**Issue by bindaofq** [clsid2/mpc-hc#1111]
Hello, gods, this is deepl translation 
I have a request, I need a screenshot date timestamp, can this be implemented on MPC-HC?

你好 大神 这是deepl翻译 
我有一个请求，我需要一个截图日期时间戳，这个能够在MPC-HC上实现吗？

mpc-be [JOJO&UHA-WING&Kamigami][JoJo's Bizarre Adventure - Golden Wind][20][BDRIP 1920x1080][x264_DTS-HDMA].mkv_snapshot_00.05_### **[2021.05.27_00.44.19]**.jpg
                                                                        
mpc-hc [JOJO&UHA-WING&Kamigami][JoJo's Bizarre Adventure - Golden Wind][20][BDRIP 1920x1080][x264_DTS-HDMA].mkv_snapshot_00.06.154.jpg

![be](https://user-images.githubusercontent.com/84865963/119699715-05abb900-be85-11eb-9801-81ef9aeb9230.jpg)

![hc](https://user-images.githubusercontent.com/84865963/119699731-0a706d00-be85-11eb-9b98-514b632459ac.jpg)

**Comment by clsid2** [comment]
Options > Advanced > SaveImageCurrentTime
