### ISSUE TITLE
Is there a way to make "scripts" for mpc?

### ISSUE THREAD

**Issue by helpimnotdrowning** [clsid2/mpc-hc#1114]
I use MPC-HC to select frames that get put into a file by copying the video time in the format (h,m,s,ms) and I was wondering if there was an easier way than having to pause the video and retype the text by hand. Is there a way to load in + make scripts for MPC-HC?

**Comment by clsid2** [comment]
You need to use some external scripting tool like AutoIt.

**Comment by ale5000-git** [comment]
@helpimnotdrowning: If you double click on video time it get copied to clipboard.

**Comment by clsid2** [comment]
Screenshots also include the timestamp in the filename.
