### ISSUE TITLE
Regression: fullscreen fails when moving window from 2k monitor to 4k monitor

### ISSUE THREAD

**Issue by SanderBouwhuis** [clsid2/mpc-hc#1115]
There is a regression in v1.9.12 (ca0f5c3d2)

**Setup**
Monitor 1 = 3840x2160
Monitor 2 = 2560x1440

**Steps to reproduce**
1. Open MPC in windowed mode on monitor 2 (2k)
2. Open a 1920x1080 video
2. Move the window to monitor 1 (4k)
3. Double click the window to go to fullscreen.
4. It fails in a weird way. The movie is playing in the top left corner and part of a previous frame is still visible in the rest of the screen but is frozen.

**Workaround**
1. Open MPC in windowed mode on monitor 2 (2k)
2. Move the window to monitor 1 (4k)
3. Quit MPC
4. Open MPC in windowed mode on monitor 1 (4k)
5. Now fullscreen should work again.

**Comment by clsid2** [comment]
If 1.9.11 worked ok, then please test the 1.9.11.x development builds.

**Comment by clsid2** [comment]
Try this setting in the Registry:
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\Settings
DesktopSizeBackBuffer = 1

**Comment by chris-kwl** [comment]
Worked for me, had the same problem.
MPC-HC.1.9.11.36.x64 is the last version where the registry edit is not needed.

**Comment by clsid2** [comment]
Good, then I know which change caused it.

Can you test if this setting also solves it?
Options > Playback > Output > Reinitialize when changing display
(with DesktopSizeBackBuffer = 0)

**Comment by chris-kwl** [comment]
Yeah, this works also.

**Comment by SanderBouwhuis** [comment]
> Good, then I know which change caused it.
> 
> Can you test if this setting also solves it?
> Options > Playback > Output > Reinitialize when changing display
> (with DesktopSizeBackBuffer = 0)

This indeed works for me too. This should automatically happen when you detect when you move the window to a 4k (or higher) monitor. This should happen without the user needing to have the 'Reinitialize when changing display' option on. I am certain I would never have figured this out on my own because this always used to work.

**Comment by clsid2** [comment]
Should be fixed in 1.9.12.4 hotfix.
Available on the releases page.

**Comment by SanderBouwhuis** [comment]
Confirmed, v1.9.12.4 fixes this bug.
(This player is absolutely amazing, and so are you clsid2)
