### ISSUE TITLE
MPC-HC black bar detection/crop with madVR

### ISSUE THREAD

**Issue by andrew89898** [clsid2/mpc-hc#1116]
Hi I have mpc-hc setup with madVR and the internal LAV filters. I have a 21:9 (ultra wide monitor), usually I use mpc-hc ‘zoom to widescreen’ to zoom to full view. I have a movie which is switching between 16:9/IMAX and 21:9 ratios and found that madVR ‘zoom control’ should be able to detect this and auto zoom in. But it’s not working for me. I asked on their support forum and they aren’t sure of my issue, I’m using dxva2 copy back and d3d11 - tried everything. This is in fullscreen mode too with touch window from inside and DAR set for the video.

Is there anyway I can get full 16:9 with left/right black bars so I can see the imax content then get it to zoom in for the 21:9 scenes?

Thanks

**Comment by clsid2** [comment]
For madvr it is recommend to use "touch window from inside" (which is default). For hardware acceleration DXVA2 copyback is best choice. With those settings the black bar detection in madvr should work. If it doesn't work it is a problem in madvr itself.

I am not able to help you with this.
