### ISSUE TITLE
Unable to play local m3u8/HLS

### ISSUE THREAD

**Issue by FX8350** [clsid2/mpc-hc#1117]
Online m3u8/HLS works perfectly, but local m3u8/HLS cannot be played.
The playlist segments are marked with relative paths, not URLs. (Please see the attached sample file).
In VLC, it can be played.
[~~test.zip~~](https://github.com/clsid2/mpc-hc/files/6563661/test.zip)
[test2.zip](https://github.com/clsid2/mpc-hc/files/6563673/test2.zip)
(Re-uploaded the sample file.)

**Comment by clsid2** [comment]
LAV Splitter doesn't work with this local playlist. That would need to be fixed in LAV/FFmpeg.

Letting MPC-HC parse the playlist isn't an good option, because then it loads it as individual videos, which results in interruptions between the segments.

**Comment by FX8350** [comment]
OK, I'll open a new issue on the LAV github.

**Comment by Nevcairiel** [comment]
https://github.com/Nevcairiel/LAVFilters/issues/423#issuecomment-1005856373

This is an MPC-HC issue, it never even asks LAV to open it.
