### ISSUE TITLE
Blurry subtitles on UHD screen

### ISSUE THREAD

**Issue by pstranak-sw** [clsid2/mpc-hc#1119]
After updating from MPC-HC 1.9.11 to 1.9.12, the subtitles are rendered blurry on my UHD screen. The following screenshots are from Sintel, a 4K movie played on an UHD monitor. But I see the same issue also with HD and FullHD recordings. Before the update, I used the Desktop subtitle texture resolution.

Here are a couple of screenshots of the subtitles.

Fullscreen:
![fullscreen](https://user-images.githubusercontent.com/37192399/120067822-ee83eb80-c07d-11eb-9480-96788410e455.jpg)

Fullscreen in the previous version (or when re-setting the texture resolution to UHD):
![fullscreen_original](https://user-images.githubusercontent.com/37192399/120067898-44589380-c07e-11eb-8981-95667d20dfc5.jpg)

Maximized window:
![maximized](https://user-images.githubusercontent.com/37192399/120067913-563a3680-c07e-11eb-953d-4ff0966e84d8.jpg)

Maximized window in the previous version (or when re-setting the texture resolution to UHD):
![maximized_original](https://user-images.githubusercontent.com/37192399/120067936-6ce08d80-c07e-11eb-9026-abe8703c2613.jpg)

The slight blurriness in a maximized window is probably to be expected, considering this change: 5236405311e59b9b0d0617a3754a142311375b37. However, the full screen is bad.
Also, interestingly, when I play the video in a maximized window, switch to a fullscreen and then back to a maximized window, the subtitles stay extremely blurry and do not reset to the expected resolution.

A workaround is to manually set the UHD texture resolution, both in case of new installations and upgrades. So it doesn't really block me. But it might be a problem for new or inexperienced users.

**Comment by clsid2** [comment]
It looks more blurry than I expected. Does it look the same if you explicitly set max texture to 1080p?

**Comment by clsid2** [comment]
Fullscreen should look the same as in maximized window. Just slightly blurry. Something is definitely wrong.

**Comment by pstranak-sw** [comment]
Resolutions 640x480, 800x600, 1280x720, 1600x900 and 3840x2160 provide increasingly better image.
Resolutions 1920x1080, 2560x1440 and 2560x1600 look the same and worse than 640x480.
Resolution 1920x1200 looks a little bit more blurry than 800x600, but similar.

**Comment by clsid2** [comment]
Here is a build with some extra debug logging:
https://www.sendspace.com/file/cdnt3k

Options > Advanced > EnableLogging

It creates a log file here:
%appdata%\mpc-hc\subpic.log

**Comment by pstranak-sw** [comment]
I opened the movie, switched to fullscreen, jumped to a position with some subtitles and then closed the player. The maximum texture resolution was set to 1440p.
```
17:48:04.382: InitMaxSubtitleTextureSize 2560x1440
17:48:04.746: SetVideoSize 4096x1744
17:48:04.746: SetVideoSize 4096x1744
17:48:05.529: SetPosition window=3838x1634 video=3838x1634
17:48:05.529: SetMaxTextureSize 1919x817
17:48:06.283: SetPosition window=3840x2160 video=3840x1635
17:48:06.283: SetMaxTextureSize 389x219
17:48:09.981: RTS init size=389x219 vidrect=389x165
```

**Comment by pstranak-sw** [comment]
This is the output, when I launch the video directly in fullscreen:
```
18:01:01.611: InitMaxSubtitleTextureSize 2560x1440
18:01:01.963: SetVideoSize 4096x1744
18:01:01.963: SetVideoSize 4096x1744
18:01:19.597: RTS init size=2560x1440 vidrect=2560x1090
```
It this case, the subtitles are rendered as expected. But once I exit the fullscreen and re-enter it, the resolution is bad again.

**Comment by clsid2** [comment]
I think I have found the bug.

**Comment by clsid2** [comment]
Should hopefully be fixed now:
https://www.sendspace.com/file/13iovp

**Comment by pstranak-sw** [comment]
The latest build seems to work correctly. This is the output:
```
19:03:47.550: InitMaxSubtitleTextureSize 2560x1440
19:03:47.898: SetVideoSize 4096x1744
19:03:47.898: SetVideoSize 4096x1744
19:03:48.511: SetPosition window=3838x1634 video=3838x1634
19:03:48.511: SetMaxTextureSize 1919x817
19:03:49.165: SetPosition window=3840x2160 video=3840x1635
19:03:49.165: SetMaxTextureSize 1920x1080
19:03:59.536: RTS init size=1920x1080 vidrect=1920x817
```

**Comment by pstranak-sw** [comment]
And this is the screenshot:
![fullscreen_secondTestBuild](https://user-images.githubusercontent.com/37192399/120078755-50117d80-c0b1-11eb-8cf3-c48c80ea6b37.jpg)
The subtitles are slightly blurred when compared to the 2160p subtitle texture resolution. But I guess that's the intended behavior. Anyway, I'll keep using the desktop resolution as I like the text sharp.

Thank you for fixing it so quickly.

**Comment by clsid2** [comment]
Thanks for testing.
