### ISSUE TITLE
Has not enough privileges grammer

### ISSUE THREAD

**Issue by FCBester** [clsid2/mpc-hc#112]
On the Options > Formats screen, when clicking on a file extension it comes up with a box saying.

![image](https://user-images.githubusercontent.com/1446679/59901196-c5bb3c00-93fa-11e9-827b-873e7b39cd10.png)

English is my second language, so not 100% sure, but should it not be

MPC-HC does not have sufficient privileges

**Comment by ValZapod** [comment]
No, obviously. https://www.google.com/search?q=has+not+enough

**Comment by zrneely** [comment]
"Has not enough" sounds strange and unnatural to me (a native US English speaker). I'd recommend either "does not have enough" (less formal, less precise) or what you suggested, "MPC-HC does not have sufficient privileges to ...".

**Comment by Eagle3386** [comment]
I may be late to the party, but shouldn't it also be spelled "to change file format associations" instead of "to change _file**s**_ _format**s**_ associations" and "click the" instead of "click _**on**_ the", too?

**Comment by Eagle3386** [comment]
> No, obviously. https://www.google.com/search?q=has+not+enough

Citing Google results is no valid proof - it aggregates mistakes just like valid results.

**Comment by Eagle3386** [comment]
@clsid2 Please provide some details about why this issue got closed without any fix.

**Comment by adipose** [comment]
It was fixed recently in a PR I did.  It was merged here:

https://github.com/clsid2/mpc-hc/commit/dcdb404bbb890d1206f94f356798ca8df3db0896#diff-e330b60e6237a2310f470b242205a602
