### ISSUE TITLE
ToDo: internal audio renderer -> show errors on its status page

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#1120]
If an internal error or failure occurs, then put a descriptive message on the status page, so users can see what went wrong.

**Comment by cajhin** [comment]
Related? I have a single audio out, an external USB amp.
It would be very nice if "your amp is turned off" was maybe mentioned in the status bar, but does NOT result in a full blown error message popup, where MPC shows 100 lines of media file info, when it simply doesn't have an Audio Switcher::Out. 

This is only cosmetic, of course, but it's ugly, I have to close the popup, and I often start MPC without turning my amp on, to check a download or whatever.

**Comment by clsid2** [comment]
Options > Playback > uncheck "Report pins which fail to render".

**Comment by cajhin** [comment]
Yes! :)
Thank you, that was a bit annoying, now it's fine. I thought I looked at all the options, but I missed that one.
MPC is my favorite player since the gabest days, so I appreciate it very much that you maintain it.
