### ISSUE TITLE
MPC-HC does not load External Audio anymore?

### ISSUE THREAD

**Issue by honeyo1** [clsid2/mpc-hc#1121]
Hi

First time github user, so please bear with me. 

So I have been using K-lite codec pack Standard version for more than a decade and MPC-HC has been my primary player. But the issue is present in MPC-HC.1.9.12.x86.zip too. From past few weeks, it does not load any external audios. Usually I run them via File > Open File thing.

The external audio does not load, hence I cannot toggle with the 'A' shortcut. There is no error, but external file just does not load. I have googled and made sure these options were checked~

Options > Playback > Auto-load audio files
+
Settings > Internal Filters > Audio Switcher > Enable built-in audio switcher

Don't recall changing any options but I have even tried uninstalling and re installing k-lite :/

Did some trials and renamed the external audio same as the video (just like we do with external subs). External mp4 or m4a audios still don't work, surprisingly mp3 audio works via this method.

Can you guys look into it? Thanks

**Comment by clsid2** [comment]
It only loads external audio file when it has a known audio extension. So that is why mp4 wasn't working, as that is considered to be a video file.

I just tried with a .m4a file and it works fine in case of same filename. Using OpenFile menu indeed gave an issue. I will try to fix that.

Allowing to manually load a video file as a dub might get implemented in the future.

**Comment by honeyo1** [comment]
Thank you @clsid2 for the response.

Afaik both mp4 and m4a audios both used to work for me via  OpenFile menu method.
So does rename method. Never had any issues in mpc-hc installed with k-lite standard.

Its just that something changed few weeks back. So I assumed I must have pressed some wrong key combination (and changed some setting unknowingly). Tried un-installing and re-installing k-lite with no luck. 

Since you mention duplicating OpenFile issue, I hope its sorted out fully. Thanks again :)

**Comment by clsid2** [comment]
Fixed.

**Comment by honeyo1** [comment]
Much thanks @clsid2
Will wait for update.

**Comment by clsid2** [comment]
Already available in K-Lite 16.2.3

**Comment by honeyo1** [comment]
@clsid2

Happy to report that both mp4 & m4a audios work in klcp_update_1623_20210530.

Edit~ Now it loads dub instantly and no need to press the 'A' key.
Thanks heaps.
