### ISSUE TITLE
Need to apply 16-235 -> 0-255 shader should not be needed?

### ISSUE THREAD

**Issue by Eno77** [clsid2/mpc-hc#1122]
I got a weird issue, mpc-hc seems not to output the right "black levels" so I need to apply the according shader.

Video Render Output is already set to 0-255 and I did not find any other setting, which is wrong here.
I think the issue occurs, since I changed to a new Graphics card (RX580 -> 6900XT) because the "grey black" was no problem before.
Otherwise Hardware decoding on/off does not change anything.

VLC for instance works good without any changes and no difference between old an new graphics card.

Is there a possible issue with mpc-hc?

**Comment by clsid2** [comment]
It is the fault of the graphics driver. Re-install the driver with the "factory reset" option enabled.

**Comment by Eno77** [comment]
OK, thanks for the quick reply.
Did not work - still have to use the shader.

Maybe filing a Bug Report to AMD would be a good idea? But I dont know how the right wording would be for them to recognize the issue.

**Comment by clsid2** [comment]
"0-255" is called "full range" and "16-235" is called "limited range".

Mention them which video renderer you are using:
Options > Playback > Output
Default one is "Enhanced Video Renderer (Custom Presenter)"

Check if this setting is correct:
AMD driver settings > Display > Pixel Format > Full RGB

**Comment by Eno77** [comment]
Yes, already checked the different renderers (with no change) and tried different pixel formats (default to the AV Receiver was YCbCr 4:4:4, no change with Full RGB)
On all Monitors the issue is present, regardless of Pixel Format and color depth setting (8, 10, 12 bpc) but most noticeable on the TV set, since the full array backlight does not go out on black screens and the greyish look / reduced contrast is very annoying.

Hardware Rendering on/off does not change anything too.

However for other players (I tested vlc) there is no issue with black levels.

Btw:
With the mentioned shader the picture seems OK - how much "loss" or (unnoticed) quality reduction is there with the shader active?

I will file a bug report with a short description to AMD, lets see if something happens.

**Comment by clsid2** [comment]
The shader does not give any significant quality reduction.

Try with this video renderer:
https://github.com/Aleksoid1978/VideoRenderer/releases
You can select in MPC-HC after installation.

**Comment by Eno77** [comment]
Seems even after I run the install script it is not recognized in mpc-hc (zip file version)

But I noticed with the Video Mixing Renderers 9 and 7 the black is OK, but the edges of fonts (credit scenes for example) look weird with these renderers)

Best result until now is achieved with the enhanced custom presenter renderer with the 16-235 -> 0-255 shader active.

I filed a bug report with a link to this issue here and a screenshot from a movie which should make it very visible.

**Comment by clsid2** [comment]
Right-click on the .bat and "run as administrator".

**Comment by Eno77** [comment]
Short feedback on this:

It seems AMD has fixed it unnoticed.
I dont need to apply the shader anymore to have the right black levels with the actual driver version
(I noticed it on Driver 21.6.2)

So there is a chance, that they actually read and had a look into my Bug Report ;)

**Comment by clsid2** [comment]
Good to hear.
