### ISSUE TITLE
[Feature request] Seeking bar shift+click feature on short videos as default

### ISSUE THREAD

**Issue by IvikN** [clsid2/mpc-hc#1124]
Right now when you click on seek bar of very short videos it will jump to the nearest point of it not into the precise frame which is not very convenient cause I want to be able to see exact frame from desirable second over and over (I'm art director and I often overview others people work, like animations and VFX) this is working precisely only when you hold shift and click on the seek bar which will set player to the frame you are clicking. Could you please make this shift+click default precision feature? On a long videos as I remember this is not a problem cause player sets exact frame where you want to start from. 

Thanks for all that you do guys. This is the best player of all.

**Comment by clsid2** [comment]
I can't promise anything. Up to which duration do you consider a video to be "short"?

**Comment by IvikN** [comment]
Less than a 20-30 sec in general.

**Comment by clsid2** [comment]
Anything up to 60 seconds will now do accurate seek by default instead of a keyframe seek.
