### ISSUE TITLE
Using 'Jump Forward (medium)' command restarts video

### ISSUE THREAD

**Issue by bintheir** [clsid2/mpc-hc#1126]
When using 'Jump Forward (medium)' multiple times in a row, the video restarts from the beginning.
This behaviour was introduced in version v1.9.9

Every newer version still has this issue and reverting back to v1.9.8 solved the issue every time.

**Comment by clsid2** [comment]
You are the only person with this problem, so you need to provide more detailed steps to allow me to reproduce the problem.

**Comment by clsid2** [comment]
I can make a debug build to analyze what goes wrong. But before I do that I need to know if you have the time to test the debug build and generate logs for me.

**Comment by bintheir** [comment]
I got the 'Jump Forward (medium)' on my scroll wheel on my mouse and scroll through a video like you do with a website. And without a regular interval the video resets to the start. Sadly I can't be more specific as sometimes it happens faster than other times. I do gotta say that it doesn't happen after just a few scrolls, you gotta scroll some more than that to experience the issue.

Yes I'm prepared to use a debug build.

**Comment by clsid2** [comment]
Try with this build:
https://www.sendspace.com/file/27cbbh

It includes a potential fix for your issue.

**Comment by bintheir** [comment]
I've experienced the issue with v1.9.13 a few times, but feels less frequent than v1.9.9-v1.9.12
Your test build didn't fail on me once, yet. But gotta mention that it took some videos for the issue to appear on v1.9.13 as well.
I'll keep you updated.
