### ISSUE TITLE
Media Player Classic Fullscreen onload no longer working

### ISSUE THREAD

**Issue by jabcreations** [clsid2/mpc-hc#1127]
I recently updated to MPC 1.9.12 and full screen no longer works automatically after loading a file to play; definitely a regression as I've never had a problem with this before.

**Comment by DRON-666** [comment]
I can confirm that. Neither `/fullscreen` option nor `Launch files in fullscreen` flag works anymore in 1.9.12.

**Comment by DRON-666** [comment]
I think I found the reason why this happens. Without [this lines of code](https://github.com/clsid2/mpc-hc/commit/3ddeda6699e58226c63df2b9b34e535e309c15b9#diff-95d009fa9830e480fbb6f600e662e10278d1eb3dbe7c5b7e1fb1218727aaa7d9R3733-R3736) automatic full-screen mode works as before.

**Comment by clsid2** [comment]
`Launch files in fullscreen` is still working for me. `/fullscreen` also works when opening a file in new instance. Do you mean it doesn't work when player is already active?

**Comment by DRON-666** [comment]
For me it doesn't work on first fresh start. And even `Next\Previous File` button results in immediately exit from full-screen mode.

**Comment by clsid2** [comment]
I am unable to reproduce.

**Comment by DRON-666** [comment]
I have two monitors setup. Maybe that's the reason?

**Comment by clsid2** [comment]
No, I have two monitors.

Does 1.9.11.0 work, and is 1.9.11.14 broken for you?

**Comment by DRON-666** [comment]
Yes. I tested releases from 1.9.11.14 to 1.9.11.59 and they all broken, but 1.9.11.0 work.

**Comment by clsid2** [comment]
@adipose
Can you reproduce it?

**Comment by DRON-666** [comment]
Additionally I can see some glitch during exe launch, as if mode changes to full-screen and immediately goes back.

**Comment by jabcreations** [comment]
I looked in AppData and the installation directories and I couldn't find the settings file(s) otherwise I'd dump the settings here.

 - Player: Launch new player for each instance.
 - Playback / Fullscreen: Launch files in Fullscreen.
 - Playback / Output: D3D Fullscreen.

I'm not sure what other settings are relevant? Absolutely nothing changed except MPC itself. Is there anything else I could share that would help?

**Comment by adipose** [comment]
I will take a look soon.

**Comment by adipose** [comment]
> I think I found the reason why this happens. Without [this lines of code](https://github.com/clsid2/mpc-hc/commit/3ddeda6699e58226c63df2b9b34e535e309c15b9#diff-95d009fa9830e480fbb6f600e662e10278d1eb3dbe7c5b7e1fb1218727aaa7d9R3733-R3736) automatic full-screen mode works as before.

This is intended to keep it from going full screen when no files were opened. To confirm, you are opening a file?

**Comment by jabcreations** [comment]
Yes, I open the file from Windows Explorer in Windows 10 x64 1909.

**Comment by DRON-666** [comment]
>This is intended to keep it from going full screen when no files were opened.

I link to lines 3733-3736, not line 1965.
>To confirm, you are opening a file?

I use `mpc-hc64.exe /fullscreen "somevideo.mp4"` to launch the player. The file opened and played fine, but in windowed mode.

**Comment by jabcreations** [comment]
Using `mpc-hc64.exe /fullscreen "somevideo.mp4"` did not work from the MPC directory with the full file path in quotes.

I'd be happy to try a build to test. Apparently the last version I had installed was Media Player Classic Home Cinema 64bit 1.7.13.

**Comment by clsid2** [comment]
It only happens here with D3D Fullscreen Exclusive enabled. So as a workaround, disable that option.

**Comment by clsid2** [comment]
Fixed

**Comment by jabcreations** [comment]
Great! What was the problem and when will the fix debut in a binary download please? Thank you for maintaining MPC!

**Comment by clsid2** [comment]
1.9.12.10 is available with the fix

**Comment by jabcreations** [comment]
It works! Thank you for your hard work!
