### ISSUE TITLE
[Feature Request] External font loading

### ISSUE THREAD

**Issue by Faberman** [clsid2/mpc-hc#1128]
Fansub groups often use (and include) custom fonts for their translations. Installing them for a one-time use is the way to bloat the system. AssFilterMod has this feature, but it hasn't been updated since 2017, and there are no any advantages over the MPC-HC internal subtitle renderer except that one feature.

**Comment by clsid2** [comment]
If you mux the fonts and subtitles into a Matroska (mkv) file, then they get loaded automatically. That is what the fansubbers should be doing, and that is also what most of them do.

I am not interested in adding support for external fonts. But anyone can submit a patch for it.

**Comment by Faberman** [comment]
Okay, I get it.
UPD. Here is a patch: #1140

**Comment by MononeV** [comment]
@Faberman Sorry to bother but I'm just looking for help on supporting TTC font file. I've digged into #1140 and think it might work with extra code like this:
```
           hFind = FindFirstFile(path + L"*.ttc", &fd);
            if (hFind != INVALID_HANDLE_VALUE) {
                do {
                    m_FontInstaller.InstallTempFontFile(path + fd.cFileName);
                } while (FindNextFile(hFind, &fd));

                FindClose(hFind);
            }
```
Are you interested in adding this to your patch?
