### ISSUE TITLE
Is possible Add a new usefull Function?

### ISSUE THREAD

**Issue by hjli1988** [clsid2/mpc-hc#113]
The Function " After Playback " " Play next file in the folder" is usefull . But when i used the function, and simple double click a file in a folder,  the player will play all file in the folder one by one, but cannot continue play the first file after already play the last, so it is possible to add a new chooice to Repeat Play file in the folder one by one and continue play the first file after already play the last file?

Thank you very much !

![捕获](https://user-images.githubusercontent.com/52433053/60562400-fd769c00-9d89-11e9-919c-c23c01a20af7.PNG)

**Comment by clsid2** [comment]
It now loops the folder in version 1.8.7

**Comment by hjli1988** [comment]
Thank you very much.

**Comment by Septdir** [comment]
How disable loop.
Very uncomfortable when you watch TV shows.
The last episode of the season is over and now the first one starts.

**Comment by clsid2** [comment]
You can disable it in:
Options > Advanced

**Comment by Septdir** [comment]
@clsid2 Thanks!
![Disable loop](https://user-images.githubusercontent.com/18382023/61494690-819e6580-a9bf-11e9-8db2-d034f35aceff.png)
