### ISSUE TITLE
Annoying dragging issue

### ISSUE THREAD

**Issue by Erehr** [clsid2/mpc-hc#1131]
Is there any way to limit window draging only to standard windows title bar and nothing else?

As it is now clicking and draging on almost any element (video, area around buttons) and dragging cause the entire MPC window to drag. I find myself often misclicking when trying to quickly change video position and it starts to be really annoying. Especially because when the window is maximized dragging cause it to snap into smaller version every time.

**Comment by clsid2** [comment]
There is no such option at this moment. Only in fullscreen state a minimum amount of drag distance is currently required for the action to count as a drag to avoid accidental fullscreen exit.

Something similar could probably be done for maximized/snapped state.

**Comment by ale5000-git** [comment]
I think maybe it make sense to just disable dragging completely when window is maximized.
Does it have any use dragging MPC-HC when window is maximized?

**Comment by clsid2** [comment]
Yes, when moving to another screen.

**Comment by Erehr** [comment]
But that's the function of title bar in any windows application and everyone is already used to it. Having it in another place where user don't expect it that could be missclicked is another thing especially if it can't be disabled.

Potplayer e.g. has setting for that
![image](https://user-images.githubusercontent.com/13292573/122196277-63855c80-ce97-11eb-85fe-0ec812f9bda7.png)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/issues/427

See here.  We had disabled this option and added it back with the minimum drag distance, due to the two screen issue clsid2 mentioned.  It could be an advanced option to disable it entirely, or else we could make the drag distance configurable (set it high enough and it won't be noticeable).

**Comment by clsid2** [comment]
Well, if the problem mostly occurs in the area above the seekbar, then another possibility would be to add a safezone above the seekbar where clicks are ignored. Kasper made an experimental patch for that long ago:
https://github.com/kasper93/mpc-hc/commit/185bd36e6cba5512c4d6fd95cf05ba135582d0e8

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1171

This part of the code seems to work fine.  I increased the size to 20 pixels, as larger seekbars and higher res might not work too well with 5.

Other changes in there actually look good, but not really related to this. ClientToScreen seems cleaner for a single point, for example.
