### ISSUE TITLE
Full screen display is corrupted when using multiple monitors

### ISSUE THREAD

**Issue by project-flower** [clsid2/mpc-hc#1132]
Ver.1.9.12
Monitor A: 1920x1080
Monitor B: 1280x1024
Video frame: Touch Window From Inside
Video size: 640x480

1. Set monitor A as the main display.
2. View the video in full screen on monitor B.
3. Set monitor B as the main display.
4. Turn off the full screen display and move the window to monitor A.
5. Display in full screen on monitor A.
The display position of the video is disturbed.

This phenomenon does not occur in 1.9.11.

**Comment by clsid2** [comment]
Already fixed in 1.9.12.4
