### ISSUE TITLE
[Feature Request] Add auto-hide option for progress bar

### ISSUE THREAD

**Issue by chaoxi24** [clsid2/mpc-hc#1133]
Thank you for maintaining MPC-HC, this made me start using it again. But I still face the same old problem: the progress bar is redundant for me.
My usual preset state is "clean" with hidden borders, and the MPC-HC window has only "video" and the progress bar. I can judge the progress by the MPC-HC button on the system taskbar, and I only move the mouse to the bottom when I need to adjust the progress. If the progress bar can be auto-hidden, i.e. when the mouse moves to the bottom, the progress bar is shown, and when the mouse leaves, it is hidden. Then auto-hide doesn't affect me in any way, but saves space.

**Comment by clsid2** [comment]
That option already exists (for many years).

Options > Advanced > HideWindowedControls
