### ISSUE TITLE
Store file history data in separate INI file or Registry key

### ISSUE THREAD

**Issue by chaoxi24** [clsid2/mpc-hc#1134]
I have a large number of files in the directory where some of my video files are located, for example, the cartoon - Kureyon Shin-chan, which has 1600 episodes, and I have to record the exact information of the currently playing file, otherwise it's hard to find the progress of watching it back. But unfortunately, I have a bad habit of usually opening many videos. And the MPC-HC history policy seems to be that when there are multiple MPC-HC processes, only the last one closed is recorded. This means that if other MPC-HC processes exist when I close a Kureyon Shin-chan video, then the Kureyon Shin-chan record is lost. This is a huge disaster for me, because I have to find out my current progress from 1600 videos.
Same problem with the MPC-HC option, if another MPC-HC process exists after one MPC-HC process has finished setting up, then if that MPC-HC process closes first, then the settings are lost.
MPC-HC's policy for using mpc-hc.ini seems to be that it reads mpc-hc.ini at runtime and overwrites mpc-hc.ini at end. i think this is extremely unreasonable.
Could it be possible to change its policy to modify the corresponding entries when a change occurs, rather than overwriting the entire file?
For example, process A and B exist at the same time, process A is set to show tray icon and process A is closed. Process B is set to hide the border and process B is closed. And the settings of both process A and B are valid.
For example, there exist three processes that open three videos, and all three processes close and record the video file and playback location correctly.

Another question, is it possible to save the playback history and playback position in a separate configuration file, separate from mpc-hc.ini.
The history file needs to be changed frequently, while the mpc-hc configuration is rarely changed. And if the history file is separated from the mpc-hc configuration, we can use a more complex data format to record it. For example, using sqlite database.

**Comment by clsid2** [comment]
Storing history in a separate file is acceptable. But someone else has to implement it.

Keeping settings consistent with multiple instances is too complex. It is practically impossible to keep things synchronized. And it is not even possible to apply changes from another instance on the fly without major changes to the code and lots of possible bugs.

**Comment by chaoxi24** [comment]
I think you misunderstood. I don't mean synchronizing all processes, but not interfering with each other and not overwriting each other's configuration.
Process A is set to show tray icons, process B is set to hide borders, these settings are not valid for other processes, they are just effectively logged to mpc-hc.ini. only when a new process-C is loaded, it reads the modified mpc-hc.ini and the above settings are valid for C.

Sorry, I'm new to programming and may not be able to help. I don't know C, but I'm learning rust, and if you need, I can provide a compiled DLL with sqlite functionality. it creates a database with four columns: file path, play location, creation time, modification time. It provides two APIs,

```
1. add(file path, play location, creation time, modification time)
2. get(All or Number)
```

**Comment by clsid2** [comment]
It doesn't write only changed settings. So no, it doesn't work the way you think.

I am not interested in implementing this.

**Comment by chaoxi24** [comment]
So, can you add an option to "save history and playback location when pausing"?
If this option is supported, I can use a script to listen to the mpc-hc64.ini changes and extract the history to avoid losing it. This is also a solution in disguise.

**Comment by clsid2** [comment]
My ToDo list is already far too big.

**Comment by chaoxi24** [comment]
Thank you for your reply, I have no further questions.

**Comment by honeyo1** [comment]
Until a solution is found.. also assuming I have understood OP's problem correctly.. can I suggest an easy way of saving progress?
When I'm watching something and have to stop midway, I just press F5 and a screenshot with filename that contains exact duration is saved. Next time I need to open the same file, can just look at the pic & know where to begin.

**Comment by clsid2** [comment]
Better is to disable the option to use multiple instances. Then this whole problem doesn't occur at all.

**Comment by chaoxi24** [comment]
> 
> 
> Better is to disable the option to use multiple instances. Then this whole problem doesn't occur at all.

I tried your suggestion. I found that only one video can be played at the same time. This horrifies me, does this mean you never play multiple videos at the same time?

**Comment by clsid2** [comment]
You can open extra instances manually. For example through a pinned shortcut on Start menu, taskbar, or desktop. But it will of course also have same issue with settings.

I would guess 99% of people never watch multiple video at same time.

**Comment by lifegpc** [comment]
> > Better is to disable the option to use multiple instances. Then this whole problem doesn't occur at all.
> 
> I tried your suggestion. I found that only one video can be played at the same time. This horrifies me, does this mean you never play multiple videos at the same time?

Maybe use multiple portable version and store settings in .ini file.

**Comment by adipose** [comment]
If history was simply updated on each file open, multiple instances could interleave history entries. Actual behavior could be interesting. For example, does each instance load the current history every time it appends or does it keep its own history?

The actual backend is kind of irrelevant. Could be implemented in the registry. Only issue would be the rare race condition.

Another way might be to timestamp entries. When closing the app they could be merged with existing entries. Duplicates could be easily discarded.

**Comment by clsid2** [comment]
It currently uses a numbered list:
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\Recent File List
And position information is stored separately here:
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\Settings

A more flexible way to store the information would be for example this way:
Create a subkey for each history entry, where the subkey name is a simple hash value of the filename/url. This to have a short and fixed length for the key name.
Inside that subkey we can store any information we want in individual values: timestamp of last change, filename/url, position, audio dub, external subtitle files, index of selected audio/sub track, A-B repeat markers.
When reading the data, it needs to create a sorted list, based on the timestamp of last change. It can discard oldest entries when the list becomes to large.

The benefit of this implementation would be that it supports multiple instances, as long as those use different files. It also allows to store additional information very easily.

**Comment by adipose** [comment]
Maybe Adler32.

**Comment by clsid2** [comment]
Or std::hash

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1384 for easy reference.

**Comment by adipose** [comment]
@clsid2 can this be closed?
