### ISSUE TITLE
[Feature Request] Quick Open File into directory of currently playing file

### ISSUE THREAD

**Issue by God-damnit-all** [clsid2/mpc-hc#1135]
I recently stopped using PotPlayer because of how annoying it's become since the developer started putting ads in it.

But one feature I miss from it was the ability to go to the 'open file' option and it just started in the directory of the currently playing file. I'd like to see that done in MPC-HC as well.

**Comment by clsid2** [comment]
It remembers the folder that you last opened from. Changing that would probably result in complaints as well. So I am not keen on changing anything.

**Comment by God-damnit-all** [comment]
> It remembers the folder that you last opened from. Changing that would probably result in complaints as well. So I am not keen on changing anything.

Advanced setting maybe?

**Comment by clsid2** [comment]
There is this way to open Explorer in folder of current file:
Menu > File > Open File Location

**Comment by God-damnit-all** [comment]
> There is this way to open Explorer in folder of current file:
> Menu > File > Open File Location

I'm aware of this, but I allow multiple mpc-hc instances so it's a bit annoying to have to pop up a new explorer, open a new mpc-hc, and close the previous one with every new episode.

For a personal compilation, which line of code could I change to make Quick Open File go to the directory of the current file?

**Comment by clsid2** [comment]
You can just press PageDown to play the next file in a folder.

**Comment by God-damnit-all** [comment]
> You can just press PageDown to play the next file in a folder.

Interesting, I'll try that out. Especially since, after combing through the code, it seems like Quick Open uses the function defined here https://github.com/Samangan/mpc-hc/blob/master/src/apps/mplayerc/OpenFileDlg.cpp#L38 which currently does not have a parameter for specifying the initial directory, so it looks like it'd be a pain for a novice (notably me) to implement properly.
