### ISSUE TITLE
failed to load the sub

### ISSUE THREAD

**Issue by hooke007** [clsid2/mpc-hc#1136]
This situation happens when I use the xyvsfilter/xysubfilter as the default sub renderer.
To reproduce,
open one video, `drag` the another subtitle into the mpc window.
![Snipaste_2021-06-02_10-55-29](https://user-images.githubusercontent.com/41094733/120417202-11b9de00-c391-11eb-8264-75abafb17ff3.jpg)

**Comment by clsid2** [comment]
Drag&drop of subtitles is only supported with the internal subtitle renderer. I am not interested in implementing it for other renderers.

Name the subtitle file same as the video file to make it load automatically.
