### ISSUE TITLE
[feature request] Make "Don't seek to keyframe for videos shorter than 1 minute." configureable

### ISSUE THREAD

**Issue by isarrider** [clsid2/mpc-hc#1137]
Like the title says, in Options > Advanced, make the time configurable...

**Comment by clsid2** [comment]
What is the reason you need keyframe seeking in a very short video? I need to understand everyone's use cases.

**Comment by isarrider** [comment]
Actually I meant it the other way around - I want Keyframe seeking on loooong vids, but everything below, in my case, lets say like 10min, should seek precisely (like when you have videos of my kids or slowmo videos)....

**Comment by ale5000-git** [comment]
Have you tried to disable "Fast seek" inside Tweaks in the Options?

**Comment by clsid2** [comment]
You can have precises seeking in long(er) videos by holding Shift button when clicking on the seekbar.
