### ISSUE TITLE
Blury subtitles 

### ISSUE THREAD

**Issue by DoTheDevilDance** [clsid2/mpc-hc#1138]
I found that the recent update suddenly made subtitles blurry. It didn't take me long to figure out how to fix it. The Reload option in the Subtitle Track sub menu did the job, but the subtitles go blurry again whenever I change the size of the window. Is it possible to have the app reload the subtitles automatically whenever the window changes size?

**Comment by clsid2** [comment]
This is already fixed in version 1.9.12.4
