### ISSUE TITLE
Blurry subtitles

### ISSUE THREAD

**Issue by TheMNSTR** [clsid2/mpc-hc#1139]
Hi,

Since updating to 1.9.12 (Windows 10 64bit), I've noticed an issue with blurry subtitles. See screenshot of SRT subtitles below.

![blurry](https://user-images.githubusercontent.com/19676500/120647960-72254a00-c47b-11eb-9910-47217286ee74.jpg)

The issue presents itself when switching between fullscreen, and windowed mode. I've tested SRT, VobSub, and PGS formats, and it appears that, out of those three, only PGS remains unaffected. Toggling subtites on and off, without switching the view, makes them look correct again.

**Comment by clsid2** [comment]
Already fixed in 1.9.12.4
