### ISSUE TITLE
Where are config files stored?

### ISSUE THREAD

**Issue by mr-falafel** [clsid2/mpc-hc#1141]
Sorry if this isn't the best place to ask this but I couldn't find the information anywhere online.

Where does MPC-HC store its configuration files on the system? I've configured it quite heavily on one PC and wish to copy that configuration to another. I've checked the usual suspects of AppData/Roaming and Local and am seeing nothing. I ran a search for "MPC-HC" on my C drive and found only the installation directory in Program Files and the Start Menu directory. I can't see anything that looks like a config file in the installation folder and so that's why I'm desperate enough to ask here...

Thanks!

edit: I thought I should mention that I'm running the latest version of Windows 10.

**Comment by clsid2** [comment]
By default it stores settings in the Windows Registry:
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC

You can view contents of Registry with regedit.exe
(warning: don't mess with the content of the registry if you don't know what you are doing)

**Comment by mr-falafel** [comment]
Interesting! Could you propose a good way to copy these settings over to another windows installation?

**Comment by clsid2** [comment]
You can export the registry key into a .reg file with regedit.exe by right-clicking on the key.
To import the .reg simply double-click on it.

**Comment by clsid2** [comment]
You can also do it through:
MPC-HC Options > Miscellaneous > Export

**Comment by mr-falafel** [comment]
> 
> 
> You can also do it through:
> MPC-HC Options > Miscellaneous > Export

That's perfect! How would I then import this reg file on the other machine?

**Comment by clsid2** [comment]
Just double-click on the .reg file.

I recommend to do this on the other machine before importing:
MPC-HC Options > Miscellaneous > Reset

**Comment by mr-falafel** [comment]
Brilliant. Thank you so much for your time and help! :)
