### ISSUE TITLE
Github Actions compiler

### ISSUE THREAD

**Issue by God-damnit-all** [clsid2/mpc-hc#1142]
A lot of projects have been taking advantage of the new Github Actions to provide compilations of new development versions with every commit. It's very useful, and it's easy to crib off other project's yml files to put something together. Worth looking into.

**Comment by clsid2** [comment]
I am not interested in spending my time on this.

**Comment by God-damnit-all** [comment]
> I am not interested in spending my time on this.

If someone else made a working one, would you use it?

**Comment by clsid2** [comment]
I think you underestimate the complexity of the build and release process. So my answer right now, is "probably not".

**Comment by God-damnit-all** [comment]
> I think you underestimate the complexity of the build and release process. So my answer right now, is "probably not".

I don't doubt you, but now you've got me curious. What makes it more complex than one might expect?

**Comment by clsid2** [comment]
Compilation for example involves MinGW.

**Comment by God-damnit-all** [comment]
> Compilation for example involves MinGW.

I figured that was a given.

**Comment by lifegpc** [comment]
MSYS2 have an action to setup MingW on Github Actions. https://github.com/msys2/setup-msys2

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/120931738-7aa0ad80-c725-11eb-8689-36a34f3060c0.png)
Hope it will works well

**Comment by clsid2** [comment]
Don't waste your time on this. It is unlikely that I will use it.

**Comment by God-damnit-all** [comment]
> Don't waste your time on this. It is unlikely that I will use it.

May I ask why? The only reason given before was the complexity of the compilation.

**Comment by clsid2** [comment]
I want control over which versions are released. I don't want to mess up the releases page with dozens of useless builds for insignificant changes.
Binaries and pdb files also need to be uploaded to DrDump. Unofficial builds could result in conflicting files.

**Comment by God-damnit-all** [comment]
> I want control over which versions are released. I don't want to mess up the releases page with dozens of useless builds for insignificant changes.
> Binaries and pdb files also need to be uploaded to DrDump. Unofficial builds could result in conflicting files.

You're mistaken, the builds don't go to the releases page. Here's an example on lifegpc's fork here: https://github.com/lifegpc/mpc-hc (He got the x86 builds working, probably didn't do the rest because you said you weren't interested.)

As you can see, they're a bit off the beaten path, you have to go to the Actions section or click on a green checkmark next to a commit, then in the top right, there's an artifacts dropdown. You can control what artifacts are downloadable and how they're packaged fairly easily.

You can even have the resulting files not be publicly downloadable at all and just use this as a way to make it more convenient for you, so you don't have to compile it yourself and can just grab the files from the latest commit and do with them as you see fit. I would personally prefer you let them be publicly downloadable, but if it makes your life easier, then it's still well worth it.

**Comment by clsid2** [comment]
Can it run on demand instead of automatically?

**Comment by lifegpc** [comment]
> Can it run on demand instead of automatically?

Yea. It has a button to run manually. You can see this page: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
You can also disable all automatically work.

**Comment by clsid2** [comment]
Good. In that case it could be useful.

Some issues that need fixing after quickly looking at your last test build:
* Set build trigger to manual by default.
* The .exe artifact should preferably not be zipped. Same for the 7z archive.
* The 7z archive is missing MediaInfo and D3D DLLs and CrashReporter folder. That is missing in current build script, so could be separate patch.
* VS Community edition is sufficient for compilation.

Thanks

**Comment by lifegpc** [comment]
The second one I can't fix it. GitHub will compress all artifacts by using zip format.

**Comment by God-damnit-all** [comment]
> The second one I can't fix it. GitHub will compress all artifacts by using zip format.

Any idea if it's able to upload the data elsewhere before the job finishes?

**Comment by lifegpc** [comment]
> Any idea if it's able to upload the data elsewhere before the job finishes?

That need create Release or upload to a third party server.

**Comment by God-damnit-all** [comment]
> > Any idea if it's able to upload the data elsewhere before the job finishes?
> 
> That need create Release or upload to a third party server.

Well, since it's being manually ran, why not publish the release to a private github repo then?
