### ISSUE TITLE
Add option to show current frame number in status bar

### ISSUE THREAD

**Issue by TheLockeCole** [clsid2/mpc-hc#1143]
Maybe make it an advanced option, but it would be nice if I could see what exact frame I'm paused on (or when playing in real time, what exact frame is being displayed).

**Comment by clsid2** [comment]
You can press Ctrl+G to see framenumber and detailed time. The framenumber is a calculated value. Exact value is not tracked.

You can also right-click on the time in statusbar to enable high precision.

I am not going to add an option to display framenumber. It isn't accurate and doesn't provide better information than timestamp.
