### ISSUE TITLE
Please rename "MPC-HC on the Web"

### ISSUE THREAD

**Issue by opusforlife2** [clsid2/mpc-hc#1146]
Whenever MPC-HC is updated, this shortcut keeps coming back to the Start menu.

Normally, I open the Start menu, type "mpc" and hit Enter, which opens the player without needing to list the entire search. But after every update, I end up needing to rename or delete this shortcut, because the steps I follow open a tab in my browser instead.

Or, as an alternative, please rename MPC-HC x64 to something else?

**Comment by clsid2** [comment]
I have removed the whole shortcut.
