### ISSUE TITLE
Backward frame movement issue

### ISSUE THREAD

**Issue by krisfail** [clsid2/mpc-hc#1147]
Version:1.9.13
There is a problem with moving frames using Ctrl+←→.
Briefly, the behavior of Ctrl+← frame movement is obviously wrong.
For example, if you use Ctrl+→ to move one frame forward, and then press Ctrl+←, there seems to be no change in the frame.

**Comment by clsid2** [comment]
Modern video formats utilize "reference frames", which means that information from several frames is needed when decoding a frame. As a result you can't play in reverse order. Instead the player seeks to the desired frame. Internally the filters will then seek to a preceding keyframe and then decode (and discard) frames until the desired frame is reached. What goes wrong in your case is that the splitter does not have frame accurate seeking for the format that you are playing. So two different timestamps seek to same frame.

There is not really anything I can do without an example file. With most files backwards frame stepping should work properly.

**Comment by Sensor66** [comment]
I have the same problem. I am trying to see the exact time / frame-number at the end of a set of DVD-files, but it does not work: the application even crashes. 
I attached the DVD-files in a ZIP. (At the end of the file, there is a few seconds of blue screen. I need to know the frame number where that starts, but MPC seems to crash there. 

(Sorry, attaching the ZIP does not work. Is the size prohibitive? It's ~3GB.)
Here is a download link. https://ecloud.global/s/kfDGNpeCHRHZkji   The whole directory is in a ZIP.

**Comment by clsid2** [comment]
You need to use another file host such as Google Drive or Dropbox.

**Comment by clsid2** [comment]
Fixing framestep backwards is impossible for DVD, because the DVD Navigator filter gives inaccurate timing, meaning we can't accurately seek (backwards) to a specific frame.
But the crash should probably be fixable.

**Comment by clsid2** [comment]
The DVD Navigator only updates time once per 500 milliseconds.

I can make framestep back take a 500ms jump backwards. That does work reasonably well. But it means a jump of 12 to 15 frames (depending on framerate).

**Comment by lifegpc** [comment]
> The DVD Navigator only updates time once per 500 milliseconds.
> 
> I can make framestep back take a 500ms jump backwards. That does work reasonably well. But it means a jump of 12 to 15 frames (depending on framerate).

Yea. This fucking navigator cause subtitles can only update every 0.5 s.
I notice videolan have a [library](https://code.videolan.org/videolan/libdvdnav) to do dvd navigate and have a high precise (Aniamted subtitles works fine on VLC, so it should have a high precise).

**Comment by krisfail** [comment]
The problem can be seen very clearly in the black and white border in the last few seconds of this file.
These do not seem to occur in MPC-BE or mpv. They seem to be redrawing from keyframes when going back frame by frame. (Guessing based on the slight time lag.)
Is it possible to make such exact seek available in MPC-HC?

https://files.catbox.moe/tlfk5g.mkv

**Comment by krisfail** [comment]
I feel like I'm being rude.
I apologize.

**Comment by Sensor66** [comment]
@clsid2 
> 
> 
> You need to use another file host such as Google Drive or Dropbox.

I updated my post https://github.com/clsid2/mpc-hc/issues/1147#issuecomment-856953062 with a download link.

**Comment by Sensor66** [comment]
@lifegpc 
> I notice videolan have a [library](https://code.videolan.org/videolan/libdvdnav) to do dvd navigate and have a high precise (Aniamted subtitles works fine on VLC, so it should have a high precise).

I have been testing my case with VLC also. There, showing frame-number is indeed reasonably good, but by no means perfect. (Using addin [Time v3.2](https://addons.videolan.org/p/1154032/).) And it can only step frames forward <e>, but not backward.

**Comment by clsid2** [comment]
@yuuki76
Seems to work fine here.
Latest development build:
https://www.sendspace.com/file/udxqn4

**Comment by krisfail** [comment]
There appears to be no improvement.

**Comment by clsid2** [comment]
It works for me. There is nothing I can do to improve it.

**Comment by krisfail** [comment]
Thank you for your support.
I will review the settings on my end and let you know if the problem improves.

**Comment by clsid2** [comment]
Test with hardware accelerated decoding disabled. I could be lagging due to slow hardware decoding.

**Comment by krisfail** [comment]
It does not work. Thank you.
