### ISSUE TITLE
x265 10bit color issues

### ISSUE THREAD

**Issue by FX8350** [clsid2/mpc-hc#1148]
When playing x265 10-bit encoded video, noise occurs at the edge between black and red. (Looks like rough pixels)
I've attached a sample below, but it always happens in scenes that include black and red, not just this sample. 

Original : 00007.m2ts
![original_trim](https://user-images.githubusercontent.com/10481430/121276143-0e7e9f00-c909-11eb-91eb-13be14be8bc4.png)

x265_10bit.mkv
`ffmpeg -i 00007.m2ts -pix_fmt yuv420p10le -an -c:v libx265 -preset medium -crf 18 -g 48 x265_10bit.mkv`

![x265_10bit_MPC-HC_trim](https://user-images.githubusercontent.com/10481430/121276172-1fc7ab80-c909-11eb-9e81-49a520732be8.png)

with the "YV12 chroma upsampling" shader
![x265_10bit_MPC-HC_with_shader_trim](https://user-images.githubusercontent.com/10481430/121277220-1a6b6080-c90b-11eb-8904-5361a27d1f1a.png)

x265_8bit.mkv
`ffmpeg -i 00007.m2ts -an -c:v libx265 -preset medium -crf 18 -g 48 x265_8bit.mkv`
![x265_8bit_MPC-HC_trim](https://user-images.githubusercontent.com/10481430/121276287-5b627580-c909-11eb-89c8-380045a5362f.png)

<details>
<summary>MPC-HC with MPC Video Renderer</summary>

DX9
![x265_10bit_MPC-HC_with_MVR_DX9_trim](https://user-images.githubusercontent.com/10481430/121277014-b21c7f00-c90a-11eb-9a9a-131074399b9d.png)

DX11
![x265_10bit_MPC-HC_with_MVR_DX11_trim](https://user-images.githubusercontent.com/10481430/121277036-be084100-c90a-11eb-803a-33a6aec214a5.png)
</details>

<details>
<summary>MPC-BC</summary>

Options > Video > Surface format: 8bit or 10bit Integer
![x265_10bit_MPC-BE_8bit_trim](https://user-images.githubusercontent.com/10481430/121276584-e04d8f00-c909-11eb-974a-95683673bc28.png)

Surface format: 16bit Floating Point
![x265_10bit_MPC-BE_16bitFP_trim](https://user-images.githubusercontent.com/10481430/121276798-4c2ff780-c90a-11eb-9d37-136e1e36b736.png)
</details>

<details>
<summary>VLC</summary>

![x265_10bit_VLC_trim](https://user-images.githubusercontent.com/10481430/121276488-bac08580-c909-11eb-95e1-93a43cdc911a.png)
</details>

the sample video here
https://www.dropbox.com/s/n83yglzsijhwv41/x265.zip?dl=1

**Comment by clsid2** [comment]
Change DXVA2 Native to DXVA2 copyback. NVIDIA can give bad chroma quality with Native and DX9 surface.

**Comment by FX8350** [comment]
Hmm... sorry, I don't have a GPU that supports 10bit HEVC decoding. (In other words, I'm playing it back with software decoding).
I tried changing the LAV settings to Copy-back and None, but there was no change.
Does that mean `NVIDIA GPU + DX9(without DXVA) = Bad Chroma quality`?

**Comment by clsid2** [comment]
Chroma scaling is the job of the video renderer. This problem is not a bug and I can't do anything about it.

For the internal EVR-CP renderer you can find some options here:
Menu > Play > Renderer Settings > Presentation

I am not developing the internal renderer, so don't bother asking for improvements for it. Use madVR or MPCVR if you want something better.

**Comment by FX8350** [comment]
The problem was solved by enabling full floating point processing in the renderer settings.
I will decide whether to use full floating point processing, the YV12 shader, or MPCVR.
Thank you.
