### ISSUE TITLE
Version 1.9.11 introduced a bug with Opus files

### ISSUE THREAD

**Issue by FallenLeaf54** [clsid2/mpc-hc#1149]
As mentioned in the title, I've noticed a bug introduced in version 1.9.11 regarding playing Opus audio files (for example contained in MKV or MP4). I'm attaching the sample file below. I suspect updated LAV Filters are to blame.
Opus track was created from source using `ffmpeg` settings: `-acodec libopus -apply_phase_inv 0 -cutoff 20000 -frame_duration 60 -ac 1 -b:a 32k`
I've also tested the file with `ffplay` - sounds well, as expected. Works in most recent versions of VLC and `mpv` as well.

See: [sample_opus_bug.zip](https://github.com/clsid2/mpc-hc/files/6622310/sample_opus_bug.zip)

**Comment by clsid2** [comment]
I can't fix LAV/FFmpeg bugs.

https://github.com/Nevcairiel/LAVFilters/issues

**Comment by Kurineko** [comment]
im really sorry to put this here but i cant find anywhere else to, is there any way to donate? (ill delete this comment once i get an answer)

**Comment by clsid2** [comment]
Fixed in latest LAV Filters, which are included in MPC-HC 1.9.13.21
