### ISSUE TITLE
A question about mpc-hc and AutoIt

### ISSUE THREAD

**Issue by harmandmen** [clsid2/mpc-hc#1150]
I tried yesterday to playback a _".ts"_ video file coming from a video recorder (PVR unit).

Avast antivirus blocked the operation saying:
*** _xxxxxx.ts has been blocked because it was infected with IDP.HELU.Autolt10._ ***

Both the video file and the mpc-hc executable were quarantined and I had to "restore" them.
I'm almost sure it was a false positive, because I find it hard to believe that such a video file can actually contain a virus or malware, being the PVR not connected to any PCs or LANs or networks but only to the SAT cable and the USB key where recordings get saved.
Anyway, as I'd like to understand what happened, I did some enquiry and the Avast people told me that most probably the antivirus detection mechanism _"thought that the video file was executed via AutoIt, which isn't common on normal systems"_.

So I'm asking:
does that make any sense to you, as a developer?
Has AutoIt actually something to do with the way mpc-hc opens .ts video files?

PS. In order to prevent misunderstandings: I'm **NOT complaining** in any way.
Just trying to understand, from a technical point of view.

**Comment by clsid2** [comment]
MPC-HC is not in any way related to AutoIt. Avast people don't seem to have any clue why their crappy software is failing to work properly.
