### ISSUE TITLE
Video files with integrated cover art show the cover instead of the video

### ISSUE THREAD

**Issue by radoyankov** [clsid2/mpc-hc#1151]
Playing .mkv files with integrated cover art (like some movies) on MPC 1.9.13 doesn't play the video file, and shows only the cover art instead. Disabling the "Enable cover-art support" option doesn't work.

![Screenshot 2021-06-09 213719](https://user-images.githubusercontent.com/17084989/121410082-e162d880-c96a-11eb-9e8f-aad510052fd2.png)

**Comment by clsid2** [comment]
I need a link to one of these files.

You might be able to switch to correct track here:
Menu > Play > Video Track

**Comment by radoyankov** [comment]
After some tests I discovered it's because of Haali Media Splitter, not because of MPC, so not really a MPC issue.

**Comment by clsid2** [comment]
You should uninstall Haali. It is inferior compared to the internal LAV Splitter. Haali also doesn't support HEVC/H265 video,

**Comment by radoyankov** [comment]
Yea I know but tbh I only use it in combination with ffdshow and avisynth for motion interpolation of videos. Not really sure how to do that with LAV.

**Comment by clsid2** [comment]
You don't need Haali for that. You should enable all internal filters in MPC-HC.

When installing ffdshow, select only "ffdshow raw video processor". You don't need the decoder.
Then add that as a preferred external filter in MPC-HC settings.

You can use this filter for Avisynth as alternative for ffdshow:
https://github.com/CrendKing/avisynth_filter
Add it as a preferred external filter in MPC-HC settings.

**Comment by radoyankov** [comment]
Nice, the first method worked! Thanks for the help, not really familiar with filters, codecs etc.
