### ISSUE TITLE
WMV Playback Speed Issue 

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1153]
I have noticed that, MPC-HC does not allow to change the playback speed of WMV Videos. The playback speed is stuck at 1.00 when I try to change it. Apparently, MPC-BE also has the same issue. So, think its related to the player.
Thanks

**Comment by ale5000-git** [comment]
It works for me but I use:
- Internal audio renderer
- LAV splitter / LAV video / LAV audio for wmv files

**Comment by clsid2** [comment]
If speed change does not work it is because one of the filters in the graph does not support it.

Usually it is the audio renderer, so change it to internal one here:
Options > Playback > Output > Audio Renderer

**Comment by IMAMSGIT** [comment]
> If speed change does not work it is because one of the filters in the graph does not support it.
> 
> Usually it is the audio renderer, so change it to internal one here: Options > Playback > Output > Audio Renderer

Worked for me - Options > Playback > Output > Audio Renderer > MPC Audio Renderer
