### ISSUE TITLE
How to change skimming/fast seek to 100ms or less? 

### ISSUE THREAD

**Issue by DV2FOX** [clsid2/mpc-hc#1155]
I remember in a very old version (before 1.9.8) of the app where they changed the internal ms to 100 i think or even less, making the click+drag  / skimming much more precise etc, but they changed that in the later versions

Is there a way for a USER to modify the file(s) or setting that contains the ms thing just like that previous release (Previous from 1.9.8)?

I tried to make all the values in the fast seeking area thingy to 100ms but the original skimming (fast seek enabled or not) is still present

Thanks in advance

**Comment by clsid2** [comment]
It is currently 150ms and I am not going to add an option to lower that.

The jump distances options are totally unrelated to how fast seek are performed.

**Comment by clsid2** [comment]
I am talking about the time between seeks, not the time between points on the timeline.

If fast seek is disabled, then seeks are accurate. You can also hold Shift button to temporarily disable fast seek.

**Comment by clsid2** [comment]
I made a small modification to make it update after moving smaller distance in timeline
