### ISSUE TITLE
[Bug] Videos with clip title disables video-jumping?

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [clsid2/mpc-hc#1156]
It seems that I can't video-jumping to another one that hasn't a clip title on the window title. It was caused by a video that has a clip title.

My version: 1.9.13.9 (728958c2c)

Any help? Thank you for understanding this.

Regards
Rebecca Streisand (Frontier/Nana Mizuki Another/NMA7).

**Comment by clsid2** [comment]
Fixing it now.

**Comment by NanaMizukiAnother7** [comment]
Alright. I will wait until another development build is released. Thank you and cheers!

**Comment by NanaMizukiAnother7** [comment]
I just updated version to 1.9.13.18 and it fixes that bug! Thank you very much!
