### ISSUE TITLE
Bad URL in opensubtitles dialog

### ISSUE THREAD

**Issue by TzarAlkex** [clsid2/mpc-hc#1157]
It says to make an account at opensubtitle.com, so I did. And it was unusable since you use opensubtitles.org in MPC. They don't seem to be related (I for sure couldn't login in MPC or .org with the .com account I made).

I believe the text should be changed to say .org

![image](https://user-images.githubusercontent.com/7955709/121732000-f28a2180-caf1-11eb-8b7e-5a84e4d6913f.png)

MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.13 (d8c13f3fb)
    Compiler:           MSVC v19.26.28806
    Build date:         Jun  5 2021

LAV Filters:
    LAV Splitter:       0.75.0.2
    LAV Video:          0.75.0.2
    LAV Audio:          0.75.0.2
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 10.0 (build 18363)
    Version:            10.0 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
    GPU1:               NVIDIA GeForce GTX 970 (driver version: 27.21.14.6647)
    GPU2:               NVIDIA GeForce GTX 970 (driver version: 27.21.14.6647)

**Comment by clsid2** [comment]
I will fix that
