### ISSUE TITLE
[Feature request] Bring back the old demux function

### ISSUE THREAD

**Issue by Dr-Flay** [clsid2/mpc-hc#116]
M.I.A. Last seen in v1.3.1249 presumed dead.
MPC used to have a file menu item "Utils->DSM Converter" which I still use so have to keep old copies in my system.

Being able to extract parts of a media file without recompressing is a simple task, but since it was removed every other tool I have found is bloated and aimed at recoding.
MPC has the advantage that I can swap codecs when one is not behaving with a file for some reason.
Nothing else lets you do that. MPC was a better Demux tool than FFMPEG (and smaller).

**Comment by clsid2** [comment]
I am not interested in added that. Someone else should make a patch for it.
