### ISSUE TITLE
Last file already open but... no

### ISSUE THREAD

**Issue by KyotoIro** [clsid2/mpc-hc#1161]
Hello,

When I watch a series, mpc tells me that this is the last file, but there are still some left in the same folder.

![image](https://user-images.githubusercontent.com/79862241/121815203-820c0d80-cc75-11eb-8109-245f6a1987fc.png)

Best regard

Thx for your works

**Comment by clsid2** [comment]
Try with version 1.9.13.18
1.9.13.9 had a bug that could cause this.

**Comment by KyotoIro** [comment]
Thanks,

Perfect
