### ISSUE TITLE
0-255 color range broken

### ISSUE THREAD

**Issue by chrcoluk** [clsid2/mpc-hc#1165]
I upgraded direct from the old unmaintained version to this so a big jump of code, on the old one the right click menu option on videos encoded in limited color format, would allow me to switch from 16-235 to 0-255, on this version I see the OSD saying its switched, but the colors dont change.

Is this a bug, or a deliberate change?

I dont see it mentioned in the changelog history.

--

I noticed it does work, but now requires a restart to take effect whilst before it was instant.

**Comment by clsid2** [comment]
You should not need to change that setting. Both limited and full range video should get handled automatically, unless a file wrongly identifies its range.

Also, this setting is for renderer output. Not for how the input should be interpreted. Although the end result can be the desired correction.

**Comment by chrcoluk** [comment]
I use it alot for testing videos I produce.

If you consider it a "wont fix" "works as desired", then please at least remove the OSD change confirmation as that is now misleading, and maybe move it to the options instead of the right click menu.  As right click menu is for things to change on the fly.

**Comment by clsid2** [comment]
I fixed the issue that setting change was not applied directly.
