### ISSUE TITLE
Cannot record playback record

### ISSUE THREAD

**Issue by RrowR** [clsid2/mpc-hc#1167]
There are a lot of videos in my computer, and I need to record the video location to save my progress, but recently this software can't record my playback location, and my other computer doesn't use it very much. I'm sure the function of recording playback position has been checked, and I don't know why I can't record the playback record.

**Comment by clsid2** [comment]
Update to latest development build.

Videos need a minimum duration to remember position. You can change that in: Options > Advanced

**Comment by RrowR** [comment]
thanks.I change options solved this problem
