### ISSUE TITLE
Hotkey "space" is not worked when using chinese IME

### ISSUE THREAD

**Issue by abc1236762** [clsid2/mpc-hc#117]
Hotkey "space" is not worked when using chinese IME.
For default, hotkey "space" is used for "play/pause", but I always need to switch IME to EN that "space" can be worked for "play/pause", if IME is a chinese's IME (e.g. bopomofo) and on chinese input mode, press space is not worked for "play/pause".

**Comment by yjlin0224** [comment]
Will be fixed?

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/335
