### ISSUE TITLE
Select and play multiple files or "Add to Playlist" in Windows Explorer not sorted

### ISSUE THREAD

**Issue by SDXC** [clsid2/mpc-hc#1170]
When opening multiple files or a folder they are not added by alphabet but rather random. I know that I can sort them manually but I normally don't use the playlist functionality and always showing the playlist, sorting and then hide it again is a pain. Creating a playlist for all folders is also not a good option because the file count grows regularily.

I'm not entirely sure, but I think in older versions the files were initially sorted when adding them to the playlist.

Would it be possible to sort the files on adding them to the playlist (again)?

Thanks and have a nice weekend.

**Comment by clsid2** [comment]
There is a sort option in the right-click menu of the playlist.

Adding files through Explorer context menu in sorted order is not possible unless a custom shell extension is used. I am not interested in doing that.
