### ISSUE TITLE
Switch to NASM assembler

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#1172]
I tried updating libass and some other libraries, and found that libass no longer compiles with YASM due to some minor macro changes.  They switched to NASM in 2017, apparently, but YASM has been working until recently.

I suggest adding this to our builds:

https://github.com/ShiftMediaProject/VSNASM

This has an easy installer for nasm that will make it available to VS builds.  I was able to add it to libass and compile ok, after updating the project.  YASM is used for other assembly and could probably be ripped out of there, too.

No urgency on this, of course, and we could also use both for a time.

**Comment by clsid2** [comment]
Using NASM for libass is fine with me.

**Comment by clsid2** [comment]
I imported the VSNASM stuff. The install script did not work well on my system. I needed it to run from elevated VS developer command prompt instead of normal command prompt, otherwise it failed to detect the VS installation. It also failed to unpack the downloaded nasm zip.

**Comment by adipose** [comment]
Hmm.  This is what mine did from an elevated command prompt:
```
Detected 64 bit system...
Downloading required vswhere release binary...
Visual Studio 2017 environment detected...
Installing VS15 customisations into "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
Installing build customisations...
Downloading required NASM release binary...
Installing required NASM release binary...
Finished Successfully
Visual Studio 2019 environment detected...
Installing VS16 customisations into "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"
Installing build customisations...
Using existing NASM binary...
Installing required NASM release binary...
Finished Successfully
```

**Comment by clsid2** [comment]
Here it failed to download vswhere, even though the URL is correct and firewall disabled. Maybe some issue with my powershell (on Win7).

**Comment by adipose** [comment]
If you right click and run as administrator? I didn't use PowerShell but cmd.exe.

**Comment by clsid2** [comment]
Yes, cmd.exe as admin. The script itself uses powershell for some actions.
