### ISSUE TITLE
ToDo: add auto-fit (smaller only) zoom option

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#1174]
This should zoom video when video is smaller than specified auto-fit factor. Otherwise same behavior as 100% zoom.  So basically the auto-fit factor acts as a minimum size.

**Comment by adipose** [comment]
Good idea.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/issues/964

Is this the same issue?

**Comment by clsid2** [comment]
No, it is a bit different.

This issue is to specify a minimum size. For example 50%. Then tiny videos will be upscaled. The rest will show at 100%, or max window size for huge stuff.

The other issue is to auto-fit huge stuff only, and display the rest at 100% original video size. It currently does not zoom to 100% when window is large enough already.

Maybe we can replace the existing two auto-fit options with a single one that has two parameters. A minimum factor and a maximum factor. Defaults could be for example 40% and 80%.
Video is shown at 100% original size if fits between the factors. Otherwise either downscaled or upscaled to nearest factor. Or maybe if exact doubling is possible, use that size.

**Comment by adipose** [comment]
OK, see https://github.com/clsid2/mpc-hc/pull/2542

I am not sure about the 2x option.  It seems doable but the existing code was not really set up for such calculations.  But this at least will bring small videos up to min size, and large down to max size.
