### ISSUE TITLE
MPC player crashes playing HEVC video stream

### ISSUE THREAD

**Issue by sispli** [clsid2/mpc-hc#1179]
After opening a MKV video file which contains a HEVC video codec, MPC HC (v.1.9.13) plays the audio stream but not the video stream, and after about 1 minute also the audio stops playing. If a mouse click is issued inside the MPC window, the player freezes and has to be forcefully closed via the Windows Task Manager. For technical details see the attached files.

[MPC HC info.txt](https://github.com/clsid2/mpc-hc/files/6721418/MPC.HC.info.txt)
[Video file Media Info.txt](https://github.com/clsid2/mpc-hc/files/6721419/Video.file.Media.Info.txt)

**Comment by clsid2** [comment]
What is show here:
Menu > Play > Filters

If you see Haali Media Splitter there, then you should uninstall it, and enable the internal splitter.

**Comment by sispli** [comment]
Haali Media Splitter was not installed and internal splitter was already enabled..

**Comment by clsid2** [comment]
Then disable hardware acceleration:
Options > internal filters > video decoder > hardware decoder = none

If you are able to play other HEVC videos correctly, and the problem only occurs with this specific file, then I need a link to the file.

**Comment by sispli** [comment]
After changing the hardware acceleration setting from default (DXVA2 native) to NONE, the video played properly. Thank you!

**Comment by clsid2** [comment]
In that case, updating the graphics driver might fix the problem with hardware decoding.
