### ISSUE TITLE
video capture error

### ISSUE THREAD

**Issue by Aglan** [clsid2/mpc-hc#118]
Constantly there is a "video capture error" when watching any mkv-video.

example of mkv-file: http://animelayer.ru/torrent/5d1b8238fd897858f5143293/
I can help with debugging if necessary.

**Comment by clsid2** [comment]
Make a screenshot of the error. I think it is another application that is showing it.

**Comment by Aglan** [comment]
I can make a screenshot, but it will be on russian.
Is it really necessary? It's definitely an MPC-HC error, because the text is shown in the status bar of the player. Also, after downgrade, there is no such error.

**Comment by clsid2** [comment]
You can change the Language to English in: Options > Player

Does playback stop when the error is shown? In that case you might be pressing Ctrl+V (= open capture device).

Try resetting settings:
Options > Miscellaneous > Reset
