### ISSUE TITLE
Files are slow to load

### ISSUE THREAD

**Issue by KAELINS** [clsid2/mpc-hc#1180]
Files are slow to load in MPC, even when MPC is already running the screen goes black for a second or two and then new file starts playing... I mean yeah 1-2 seconds isn't much but I wonder what is different with MPC as with VLC the playback starts almost instantly (no exaggeration). When you first start VLC it takes 2-3 seconds to load but all the loads after that are almost instantaneous, whether you load by dropping the file on VLC, by playlist, or double clicking from the file explorer, all from HDD and no matter if the video is a several gig movie or a 2 second meme.

MPC on other hand always takes a second or two... even when both MPC and the video file are on SSD, no matter the size of file.
What gives?

**Comment by clsid2** [comment]
Loading should be fast. There is a problem on your system.

Did this problem start recently? Because a recent Windows 10 update caused a slowdown in file loading.

Another possible cause:
https://griffeltavla.wordpress.com/2014/02/10/resolved-mpc-hc-taking-10-seconds-to-launch-a-clip/

**Comment by KAELINS** [comment]
No this is not anything new... It has always been like this for me. 
I have two systems Intel and AMD both same situation, I've tried disabling NVIDIA card but still same issue.
There have been several windows reinstalls in between and several driver upgrades but that slight delay is always there.
I tried to google this issue but after lot of looking decided to post here.

It's not a deal breaker, just 1-2 seconds is no big deal but sometimes I wonder why.

**Comment by clsid2** [comment]
Try latest development build. That should be a little bit faster.

Here it loads in 1 second.

**Comment by MadokaAyukawa** [comment]
I've noticed that the subtitles load before the video. If the file has a subtitle that starts at 0:00:00 then the sub appears for a second on a black background before the video appears and starts playing. This doesn't happen on VLC. Not a big deal as few subs start right at the beginning.

**Comment by clsid2** [comment]
It works fine here with subs at 0:00:00. The subs are blended by the video renderer, so if you get a black screen, that is coming from the renderer. Could be maybe because you enabled display rate switching or delay playback options in madVR.

It is unrelated to slow loading.

**Comment by KAELINS** [comment]
So after even more fiddling with settings and codecs I have found that my system loads fastest when Video Output is set to "Video Mixing Renderer 9 (renderless)", I can scroll through a playlist at about 1 second per video
("Video Mixing Renderer 9 (windowed)" and "Enhanced Video Renderer" perform similarly but there is a flickering window in top left whenever I change a video)

"Enhanced Video Renderer (custom presenter)" is slightly slower but it is enough to notice.

MPC video renderer is slowest and takes 2 seconds per video load (sometimes more), and struggles even worse with Webm files.

(sorry If am being annoying by bringing up VLC again and again)
With VLC(3.0.8) I can move through a playlist at about 4-5 videos per second

While testing, I keep a few hundred small videos of memes in playlist (Mp4 + webm each about 1-5MB in size)
because unlike movies memes don't have black screens in the beginning so you can easily see how quickly the file is loaded
MPC performance is same in both cases whether the files are being loaded from a playlist or next file in folder.

I have also noticed that when changing videos in MPC the disk activity is higher as compared to VLC
Testing Loading from HDD:

Activity while constantly loading files in MPC(1 file per second)
![](https://i.imgur.com/EyHzndH.png)

Activity while constantly loading files in VLC(4-5 files per second)
![](https://i.imgur.com/y50BCKy.png)

Seems MPC is doing some sort of buffering from disk while VLC starts playing the file right away

**Comment by clsid2** [comment]
It is not because of file buffering. The delay obviously happens in the video renderer in your case.

Test if disabling hardware decoding in the video decoder settings makes any difference. I suspect it will.
Updating your graphics drivers might also solve the problem.
Windows 10 settings > Display > Advanced > here you can configure which GPU an application should use, that might also make a difference

I can't fix your problem because it is not a bug in the player.
