### ISSUE TITLE
v1.9.13.0 (Stable) has problem with Windows Kits

### ISSUE THREAD

**Issue by YMahmoudnia** [clsid2/mpc-hc#1181]
Hello Guys.
I trying to compile MPC-HC v1.9.13.0 (Stable) but I have compiler error 

`Failed to load and parse the manifest. The system cannot find the file specified.`
`failure during running mt.exe`

But in v1.9.10 I have not this error.

MPC-HC installed on driver C
Windows Kits installed on drive C and it's version is 8.1
Windows 10 20H2 - 19042.1081

**Comment by clsid2** [comment]
Have a look at this:
https://developercommunity.visualstudio.com/t/manifest-embedding-impossible-if-users-folder-cont/225593

**Comment by YMahmoudnia** [comment]
Thanks @clsid2 
But My computer username doesn't any space 
I use same VS (2019 16.10.2 )for MPC-HC v1.9.13 and v1.9.10

DPI Awareness is None and when I set embed manifest to NONE I have only one error
`Failed to load and parse the manifest. The system cannot find the file specified.`

I know this error generally caused on username or path that has space character but I have this error just on v1.9.13

**Comment by clsid2** [comment]
I can't help you.

**Comment by YMahmoudnia** [comment]
@clsid2 
The problem is, you forgot put mpc-hc.exe.manifest to "src\mpc-hc\res" in your source (v1.9.13) or anything else. I copy this file from another version and project compiled without any error.

**Comment by clsid2** [comment]
The manifest is generated by version.sh script. Your system is missing bash.exe, which should be included in Git or MingW installation.
