### ISSUE TITLE
Play two subtitles at the same time

### ISSUE THREAD

**Issue by xmha97** [clsid2/mpc-hc#1182]
Hey @clsid2 
Could you possibly add a feature that lets me play two subtitles at the same time?
**(In-app and without installing any plugins or external apps)**
This feature is currently available in some apps such as `PotPlayer`, `KMPlayer`, `SMPlayer`.
![KMPlayer](https://user-images.githubusercontent.com/23485114/123585721-e80d9e80-d7f8-11eb-9b36-a5f181b2cc48.png)
You may think this feature is not very important, but it's very important to me.
(English is not my native language and I watch instructional videos with two subtitles)
Please don't close this issue until this feature is added. 🙏
Thanks.

**Comment by clsid2** [comment]
I am not going to implement that.

**Comment by xmha97** [comment]
Why? Is it difficult to implement?

**Comment by clsid2** [comment]
Yes, and I don't want to spend time doing things that I don't want to do.

**Comment by ale5000-git** [comment]
@xmha97: You can in any case merge the 2 subtitle files in one (if they are external subtitles) then the automatic  overlap detection will place them in a way they don't overlap every other.

**Comment by xmha97** [comment]
> 
> 
> @xmha97: You can in any case merge the 2 subtitle files in one (if they are external subtitles) then the automatic overlap detection will place them in a way they don't overlap every other.

Do you know an offline app for this?

**Comment by ale5000-git** [comment]
No, I have only found online apps like this: https://srtmerge.github.io/

**Comment by xmha97** [comment]
OK, Thanks.

**Comment by lifegpc** [comment]
[this](https://www.codecguide.com/faq_subtitles.htm#item28) may solve your issue.

**Comment by xmha97** [comment]
> 
> 
> [this](https://www.codecguide.com/faq_subtitles.htm#item28) may solve your issue.

Wow, thanks.
