### ISSUE TITLE
Seeking in 1.9.13.37 Messes Up Subtitle Sync

### ISSUE THREAD

**Issue by MadokaAyukawa** [clsid2/mpc-hc#1184]
While moving the mouse over the seek bar, while the preview is visible, one can see the subtitles also being changed in the main video window as if the seeking also affected the subtitles, but this makes the subtitles go out of sync.

**Comment by clsid2** [comment]
Confirmed. It messes with subtitle time. I will investigate later.

@adipose
We should also look into possibilities of optimizing EVRCP code in case of preview usage. Some code segments like OSD/sub handling can be skipped.

**Comment by adipose** [comment]
EVRAP has m_bIsPreview variable which can avoid some segments.  

Maybe subpictime() is involved with this bug?  Would be easy to no-op that bit.

**Comment by adipose** [comment]
@MadokaAyukawa , can you upload a test video that demonstrates the bug?

**Comment by MadokaAyukawa** [comment]
Not my file or even my upload, but this file does it. This is internal subs; I found the bug with external subs.

https://wetransfer.com/downloads/7dc161c44ea241657492f99f49091e5620210705144116/2bf5b1

**Comment by clsid2** [comment]
I have committed a fix for the sub issue.

@adipose
I think the code can be simplified a lot more in the preview case. The VSync code can probably be skipped as well, making preview use default behavior.

**Comment by ale5000-git** [comment]
@clsid2: You have committed the fix but you haven't re-enabled EVRCP if I'm not wrong.

**Comment by MadokaAyukawa** [comment]
This is back in 1.9.14.14.

**Comment by clsid2** [comment]
Fixed another issue in 1.9.14.18

**Comment by ale5000-git** [comment]
@clsid2: The is still the aspect ratio issue on the case where EVRCP isn't used as explained [here](https://github.com/clsid2/mpc-hc/issues/1099#issuecomment-882822831).
