### ISSUE TITLE
{Open previous/next file in folder on "skip back/forward"} only works alphabetically 

### ISSUE THREAD

**Issue by EXiLExJD** [clsid2/mpc-hc#1185]
When the setting in tweaks {Open previous/next file in folder on "skip back/forward" when there is only on item in playlist} is enabled, it seems to not care if the folder is sorted by size and only skips backward and forwards alphabetically. (Used both latest stable branch and latest dev branch, same result.)
![Screenshot 2021-07-02 114207](https://user-images.githubusercontent.com/86840530/124287443-959aed80-db2a-11eb-9adc-6f7421cd533d.png)

**Comment by clsid2** [comment]
The sorting order in Explorer does not have any influence at all on the order used by MPC-HC.

It uses the standard (alphabetical) order as defined by the file enumeration API of Windows. That is simply how it works, and there will not be any options to change that behavior.

**Comment by clsid2** [comment]
Make a playlist if you want to play in a specific order.

**Comment by EXiLExJD** [comment]
Yeah that's what I have been doing. I just thought the behaviour of the setting may have been a bug or something easily changed, if not that's fine. Thanks for the quick response.
