### ISSUE TITLE
The menu needs some rearranges

### ISSUE THREAD

**Issue by OutshineIssue** [clsid2/mpc-hc#1186]
Some strange things I noticed:

- _Options_ under view.
- _Renderer settings_ under view.
- Navigate or favorites have their own unique menu but subtitles doesn't (this is more important that you might think).
- The dark theme shouldn't be in a menu, is not something that users change on regular basis, it should be in options.

And finally the help menu is quite bloated, _Download toolbar images_ links to a github issue that then again links to a no longer available website, only fetched by archive.org. _Donate_ links to a github issue that says that the project doesn't accept donations. _Home page_ links here when there's a link again in about. Do we need all this?

**Comment by clsid2** [comment]
I am not changing locations of menu items that have been in hose locations for over a decade.

**Comment by OutshineIssue** [comment]
To my knowledge dark theme wasn't even a thing a decade ago, nor the links to this repository. New features already modify the menu, it's natural for the whole thing to evolve.
