### ISSUE TITLE
Add Previous Frame button in toolbar

### ISSUE THREAD

**Issue by xmha97** [clsid2/mpc-hc#1187]
Please add Previous Frame button in toolbar.
![mpc-hc](https://user-images.githubusercontent.com/23485114/124309974-c9a0fd80-db80-11eb-9345-8054bb71486c.png)

**Comment by clsid2** [comment]
That button will not be added.

You can use Ctrl+Left.

**Comment by xmha97** [comment]
Thanks, I did not know this shortcut key.

**Comment by clsid2** [comment]
You can find all shortcuts here:
Options > Player > Keys
