### ISSUE TITLE
Use K-Lite MPC icon pack

### ISSUE THREAD

**Issue by xmha97** [clsid2/mpc-hc#1188]
Hi,
Please use K-Lite MPC icon pack.
![image](https://user-images.githubusercontent.com/23485114/124339369-4ce34300-dbc3-11eb-93e8-0d194da2ef2f.png)
Just replace the following file:
[mpciconlib.zip](https://github.com/clsid2/mpc-hc/files/6757668/mpciconlib.zip)

**Comment by clsid2** [comment]
No.
