### ISSUE TITLE
Screen tearing on HD video

### ISSUE THREAD

**Issue by madjarov42** [clsid2/mpc-hc#1191]
I've installed both madVR and MPC video renderer, but whenever I run an HD video and there's a lot of stuff going on in the screen (like a camera pans quickly) there is very noticeable screen tearing. I'm using a RX580 with Core i3-6100. I'm sure there's an easy fix but I've looked everywhere and come up empty.

**Comment by clsid2** [comment]
For tearing there is just one main solution:
Enable Vertical Sync (VSync) in the driver settings. Disable FreeSync (AMD) / GSync (NVIDIA).

**Comment by oomek** [comment]
It's a bit annoying to have to disable Freesync every time I launch mpc-hc. For some reason when I create a custom driver profile for mpc-hc64.exe and disable freesync there mpc is still tearing. Is there really no hope for a solution?

**Comment by clsid2** [comment]
Disable FreeSync globally, and use profiles to enable it for games.
