### ISSUE TITLE
Preset3 is omitted

### ISSUE THREAD

**Issue by lunter2** [clsid2/mpc-hc#1193]
Preset3 is omitted when default Preset1 and Preset2 are not defined in mpc-hc64.ini

mpc-hc64.ini
---------------------------
; MPC-HC
[Settings\PnSPresets]
Preset3=Test,0.500,0.500,1.000,1.333

**Comment by clsid2** [comment]
I am not going to spend time to fix that. You should just include the other presets if you create a custom INI.
