### ISSUE TITLE
[Feature Request] Shortcut to change subtitle size on the fly

### ISSUE THREAD

**Issue by Troncek** [clsid2/mpc-hc#1194]
As video resolution changes, I always have to go into subtitle settings and change the size by trial and error. Would be great if I could do it on the fly while video is playing.

**Comment by clsid2** [comment]
Change the size of the video window. Then the subtitle will always be same size.

**Comment by Troncek** [comment]
Not sure I understand. I watch full screen, 1080p.

**Comment by clsid2** [comment]
Then SRT subtitles should have same size for each video. It is scaled relative to screen size, unless you have changed settings.

**Comment by Blackbird88** [comment]
I can confirm that subtitle size isn't consistent across videos too. I have Default style set to Segoe UI 20 and while the font choice is fine, the size isn't. I'm not sure what causes it, as I always use SRT subtitles.

**Comment by owaimori** [comment]
would be cool if its be able to change subtitle size (and only size, not apply the default style), and with a shortucts >w> i use .ass subtitles and they have beautiful fonts, styles and everything, but often they are too big

**Comment by Korb** [comment]
> I can confirm that subtitle size isn't consistent across videos too. I have Default style set to Segoe UI 20 and while the font choice is fine, the size isn't. I'm not sure what causes it, as I always use SRT subtitles.

I have MPC-HC (64-bit) 1.9.14 (4488e7d5a). When opening MKV with subtitles in SRT format, the style set in the player settings is ignored (and the size of the text is huge). The size of the subtitle letters depends on the size of the player window. I don’t understand how to make the subtitles appear in the font size that is set to "Subtitles" / "Default Style"?

**Comment by clsid2** [comment]
Added hotkeys to adjust size.

Default font size is based on a reference video size. Watching at larger video size means text size is scaled accordingly. If you guys don't understand why that is done, then that is because of a lack of intelligence.
