### ISSUE TITLE
[Bug] The sound is stretched when changing the speed upwards twice (ctrl+up arrow twice)

### ISSUE THREAD

**Issue by StormProductionsMusic** [clsid2/mpc-hc#1196]
Hi,

The title says it all - the sound is stretched when changing the speed upwards twice.
To be more clear, the sound is clippy and a bit laggy.

**Comment by clsid2** [comment]
This is not a bug in the player. It is a limitation of the default audio renderer from Windows.

Use the internal audio renderer. That works better with video speed changes.
Options > Playback > Output

**Comment by ToxicSmurf** [comment]
It's not a limitation of Windows, VLC does not increase pitch with playback speed increase on Windows. There is no longer an internal audio renderer option in mpc and no audio renderers seem to automatically adjust pitch.

**Comment by clsid2** [comment]
MPC-HC has two internal audio renderers: SaneAR and MPC Audio Renderer and both adjust pitch.
