### ISSUE TITLE
youtube-dl not working with some streams

### ISSUE THREAD

**Issue by rzumer** [clsid2/mpc-hc#120]
Using the last x64 release build I am unable to view some streams using youtube-dl on mpc-hc. Testing on some streams from Twitch I get the advertisement, a split second of audio and then nothing. Stopping playback and resuming gets me one live frame of video, and no audio.

Using the latest youtube-dl version and ffmpeg nightly I have no problem using mpv.

Does mpc-hc work with statically-compiled youtube-dl and ffmpeg builds? If so, I would assume they need to be updated.

**Comment by Rikk** [comment]
I doubt mpc-hc will be updated as often as youtube-dl, so I think we need to update binary manually.

**Comment by clsid2** [comment]
It works better with yesterdays nightly build of LAV Filters, which MPC-HC uses as internal codecs. It correctly loads the stream now, but there is still a playback issue. Reloading (Ctrl+E) make it play.
