### ISSUE TITLE
A-B repeat show the set time

### ISSUE THREAD

**Issue by plorerfisfct** [clsid2/mpc-hc#1200]
Hi,

it would be great View -> Status or something like that shows me the set time on A-B repeat.

An example could look like this:

A-B (Mark A): 00:04
A-B (Mark B): 01:00

**Comment by cw2** [comment]
I could contribute such change... What would be the preferred/recommended format for displaying A-B mark timestamps in the status bar (one line)? I guess it could look something like:

`Playing [H/W] [A-B: 00:05:21 - 00:07:02]`
or
`Playing [H/W] Repeat [A-B (Mark A): 00:05:21 A-B (Mark B): 00:07:02]`
(the texts would be the existing menu items so there is no need for additional translation/localization)

Also, I would add `ShowABMarksInStatusbar` advanced setting.

**Comment by cw2** [comment]
Or perhaps it could be placed at the right hand side, in front of the elapsed/remaining time?

**Comment by clsid2** [comment]
Something that is relatively short, like this:
[A-B 00:05:21 > 00:07:02]
Should be obvious what it means when someone enables the option.

Keep it left for simplicity.
