### ISSUE TITLE
A-B Repeat set only with one key

### ISSUE THREAD

**Issue by plorerfisfct** [clsid2/mpc-hc#1201]
Currently under Player -> Keys I find these two commands.

A-B Repeat: Mark A Position [

A-B Repeat: Mark B Position ]

Unfortunately I didn't find a command to set with only one key A-B Repeat: Mark A Position and Mark B Position.

This is how I imagine it a new command.

A-B Repeat: Mark A Position and Mark B Position "Key"

What exactly will happen?

When I click the key, Mark A is set first and when I click the same key again, Mark B is set second. When I click again (the third time) A-B Repeat is reset.

**Comment by clsid2** [comment]
During implementation the current method was chosen as most flexible.

I am not going to change it, nor discuss it again.
