### ISSUE TITLE
Add a safe area as an option so that A-B Repeat markers are not gone

### ISSUE THREAD

**Issue by plorerfisfct** [clsid2/mpc-hc#1202]
For example, set A-B (marker A) and A-B (marker B).
You will then see 2 red markers in the seek bar.

The current problem is that when I click with the mouse outside of these red markers, the 2 red markers are immediately gone. 

It would be very helpful if there was an option to enable a safe area. When I enable this option, the red markers do not disappear. That is, if I select a different position with the mouse outside the red markers, playback continues what I selected with the mouse. If I select a position within the red marks in the seek bar, for example, with the mouse, the playback continues exactly there with A-B Repeat mode.

**Comment by clsid2** [comment]
Clicking outside the A-B range signals that the repeat should be aborted.

I am not going to change that.
