### ISSUE TITLE
Incorrect orientation for some vertical videos in preview on seek bar

### ISSUE THREAD

**Issue by VladWinner** [clsid2/mpc-hc#1203]
This behavior is seen in some vertical videos made on smartphones.
### Screenshots
![image](https://user-images.githubusercontent.com/13555921/125159558-da550300-e180-11eb-8066-0a8fb7c41aec.png)
![image](https://user-images.githubusercontent.com/13555921/125159809-792e2f00-e182-11eb-8cea-241e7ff6d923.png)

However, this does not apply to videos that have been post-processed by YouTube or Telegram:
![image](https://user-images.githubusercontent.com/13555921/125160381-302baa00-e185-11eb-91b8-5f9beece2425.png)
![image](https://user-images.githubusercontent.com/13555921/125159947-1ee19e00-e183-11eb-9027-32ad6d62b8f3.png)

I'm not sure, but maybe it related to #1190 or already fixed after #1190. I use madVR as main video renderer

### Sample files:

https://user-images.githubusercontent.com/13555921/125159819-877c4b00-e182-11eb-87e4-7f628047d561.mp4
https://user-images.githubusercontent.com/13555921/125160652-c01e2380-e186-11eb-9e7e-c38b25ea243d.mp4

---
MPC-HC v1.9.14

**Comment by clsid2** [comment]
Preview rotation will be supported in a future version.
