### ISSUE TITLE
Question - double click or enter adds files to playlist instead of playing it

### ISSUE THREAD

**Issue by somacruz10** [clsid2/mpc-hc#1204]
Sometimes or some files when I double click them or select them and press enter, it plays the file. But sometimes it just adds them to playlist. 

For example I click on first file, it starts to play, then I click on second file it starts to play second file, then I click on third file and it's adds to the playlist. Is that changeable in settings? This happens when I do double click fast

**Comment by clsid2** [comment]
This can happen if you click on next file within 1 second. This is done this way to handle how Windows opens a selection of multiple files. It simply spawns multiple processes. So the player assumes that very quick successive file openings belong together in a group.

I am not going to add yet another option to shorten this timeframe. Just wait a second and the problem will not occur.
