### ISSUE TITLE
aspect ratio scaling bug with madvr renderer set

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1206]
that has even been a known issue in the past

[here's a thread from 2015 that illustrates the bug](https://codecs.forumotion.net/t2091-touch-window-from-inside-option-behaving-differently-in-11-5-0). unfortunately, it seems that after the bug was fixed it has become broken yet again.

**Comment by clsid2** [comment]
You need to give a detailed example:
resolution of input video + AR override value + size that madVR shows + size that you expected in madVR
