### ISSUE TITLE
Can not play any .mp4 file on Windows 11

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1207]
When I open a .mp4 file on Windows 11, mpc-hc shows a loading bar, and shortly it closes.

**Comment by clsid2** [comment]
Update your graphics driver.

Disable hardware accelerated decoding:
Options > Internal Filters > Video Decoder > Hardware decoder = None

**Comment by ghost** [comment]
Your solution doesn't work.

I don't have the issue on Windows 10, and I think the issue is caused by some changes of Windows 11.

**Comment by clsid2** [comment]
Windows 11 is a preview build that is riddled with bugs. If you have problems, report them to Microsoft. I can't help you.

Video playback works fine for me with the first leaked build. There are no changes in the default codecs.

**Comment by ghost** [comment]
After I updated Windows 11 to build 22000.71, the problem was resolved.
