### ISSUE TITLE
Can't opening downloded from Vidmate or Playit player 

### ISSUE THREAD

**Issue by Sahinujjaman** [clsid2/mpc-hc#1209]
![image](https://user-images.githubusercontent.com/55046181/125184144-fe741b00-e238-11eb-9a49-cf6ca25b1c71.png)
![image](https://user-images.githubusercontent.com/55046181/125184170-25325180-e239-11eb-9d44-a61d60d0e135.png)

**This type of video only opens on playit or vidmate video player...**

**Comment by clsid2** [comment]
Any video that shows such messages should be deleted immediately. The file was modified to trick you into installing software that contains malware or advertising. Do NOT install such software!

Vidmate installs malware on your mobile phone.
