### ISSUE TITLE
Can not play url

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#1210]
[URL](https://cs.kanahanazawa.com/tiktokRSS?type=url&vid=6945812541574499585&sign=a54f4153b2fbf7285f070507646267cfece04468c7dbc7c8ff0fa18bb4fa400edc452a71437303d8a18b4fcace1c3480a54d0805092b1fe2dc03ad48e38700f0)

**Comment by lifegpc** [comment]
Try add a vaild video extension to url, but also open failed.

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/125383012-4d50ba80-e3c9-11eb-863b-2c700c844362.png)
Strange, it say is a download issue.

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/125383574-2e065d00-e3ca-11eb-9e76-fd8f80f9bf39.png)
Looks like bug in LavFilter

**Comment by lifegpc** [comment]
Looks like it is schannel's problem. Microsoft's schennel don't support TLS v1.3.

**Comment by lifegpc** [comment]
> Looks like it is schannel's problem. Microsoft's schennel don't support TLS v1.3.

![image](https://user-images.githubusercontent.com/41434272/125391201-a07d3a00-e3d6-11eb-88cf-693951b4332b.png)
Now I try to use openssl.

**Comment by clsid2** [comment]
Works here. Release builds of LAV use gnutls. Only debug builds use schannel.

**Comment by lifegpc** [comment]
A little strange, I try openssl with debug mode and try mpc-hc prebuild version which download from codecguide.com , all display can not renderer file.

**Comment by clsid2** [comment]
Maybe you are GEO-blocked by the server.

**Comment by lifegpc** [comment]
That's my server and I can access it by using broswer, ffplay, vlc. All works well. Only mpc-hc don't work.

**Comment by ale5000-git** [comment]
@lifegpc: Are you sure your firewall isn't blocking mpc-hc.exe or youtube-dl.exe?

**Comment by lifegpc** [comment]
> @lifegpc: Are you sure your firewall isn't blocking mpc-hc.exe or youtube-dl.exe?

YouTube with youtube-dl works fine.

**Comment by clsid2** [comment]
It doesn't need ydl.
The URL also works here in GraphStudioNext with LAV Splitter Source.
