### ISSUE TITLE
.ts file smooth skipping

### ISSUE THREAD

**Issue by naifqarni** [clsid2/mpc-hc#1211]
when skipping .ts videos using mpc the video is delayed for like 3 seconds   
here is the video info:
Video: MPEG4 Video (H264) 1280x720 24fps [V: h264 high L4.1, yuv420p, 1280x720]
Audio: AAC 48000Hz 6ch 40kbps [A: aac lc, 48000 Hz, 5.1, 40 kb/s]

**Comment by clsid2** [comment]
Not a bug.

MPEG-TS container format does not contain a seek index. If you want fast seeking you should remux it into a .mkv file.
