### ISSUE TITLE
Volume slider and mute button have no effect when playing MIDI files

### ISSUE THREAD

**Issue by UrsusArctos** [clsid2/mpc-hc#1215]
Whenever I play MIDI file in MPC-HC, the volume slider and mute button do nothing.

**Comment by clsid2** [comment]
The audio renderer that is used for MIDI playback does not support volume changes. It has the standard functions for volume control, but simply ignores the changes. Blame Microsoft for not implementing that functionality.

Probably the only way to change the volume is to modified it directly in the output audio device. That is not easily accessible from the player, and I am not interested in implementing that.
