### ISSUE TITLE
Unable to download or find subtitles if file is not fully downloaded

### ISSUE THREAD

**Issue by vdurante** [clsid2/mpc-hc#1216]
If I use mpc-hc to open unfinished torrent downloads. This is the file:

![image](https://user-images.githubusercontent.com/5401232/126035344-1d950c43-43f9-422e-9476-f88893ced638.png)

Since it is unnamed and unkown, the Download Subtitles popup fails to fetch any results, which is expected.

But then I attempt to search for a file name, which gets me zero results. Is this expected? I feel like there is something else being filtered, which results into zero results.

If I wait for the download to finish and open the file, I can find subtitle results, and if I use the search functionality it also works!

**Comment by clsid2** [comment]
The search uses a hash value calculated from some data at being and end of file. So to be sure that subtitle search works good, make sure those pieces have been downloaded.

It also has a fallback that searches based on filename, but it is less accurate, and depends on a good filename.

**Comment by vdurante** [comment]
Thank you for the response!

> It also has a fallback that searches based on filename, but it is less accurate, and depends on a good filename.

Is there a way of passing the filename as a command line argument when running MPC-HC through command line? This could be a solution.

Alternatively, I just checked and it shares the file name as a "clip" property. Is there a way of configuring which field it uses to search?

<img width="270" alt="mpc-hc64_fNl4JPP6q9" src="https://user-images.githubusercontent.com/5401232/127026358-56a8c424-a961-4e22-9342-c9c1add7960c.png">

**Comment by clsid2** [comment]
If you want good search results, you should keep the original filename of your download. I am not going to add silly options because you are renaming to a non-descriptive filename.

The results window has a searchbox in the right-bottom corner where you can do a manual search.

**Comment by vdurante** [comment]
@clsid2 thank you! Yeah, search definitely doesn't work, no matter what I type. And I have logged into OpenSubtitles.

Regarding the filename, it is not passed since it is streamed into MPC-HC. You can read it [here](https://github.com/popcorn-official/popcorn-desktop/issues/2255#issuecomment-887582882) from the dev

**Comment by clsid2** [comment]
I have committed a fix that should solve the broken manual search.
