### ISSUE TITLE
Serious deficiency: Lack of S-LOG/HLG HDR colors

### ISSUE THREAD

**Issue by Cuberlain** [clsid2/mpc-hc#1219]
Hello MPC Team!

The colors of the videos are weird if I play  HDR or HLG/Slog contents.
The competitor Potplayer already knows that color formats, also able to play them correctly..
Can you fix this problem/deficiency in MPC-HC ?

Thank you for your reply!
Best  Wishes!
Bye!

**Comment by lifegpc** [comment]
You should use MPC-VR or madVR as video renderer to support HDR.

**Comment by Cuberlain** [comment]
Hello lifegPC!
Why doesn't HDR part of the standard MPC-HC (without any extra stuff),  after all we live in 2021 and not in 2011?

**Comment by clsid2** [comment]
If you want extras, use a package such as K-Lite Standard.
