### ISSUE TITLE
Opus metadata information isn't being shown 

### ISSUE THREAD

**Issue by Destroyer** [clsid2/mpc-hc#1220]
Even though the metadata is present in the opus file, MPC doesn't display them in its info view

![obrazek](https://user-images.githubusercontent.com/289988/126070706-59e63768-dfe3-4742-b583-efbfc49fedde.png)

**Comment by clsid2** [comment]
You can report issues with the internal LAV Filters here:
https://github.com/Nevcairiel/LAVFilters/issues

**Comment by Aleksoid1978** [comment]
Upload sample file.

**Comment by lifegpc** [comment]
> Upload sample file.

I test a ogg(opus) file which converted by ffmpeg, has same issue. (`ffmpeg-msvc -i "01 FUN FUN MERRY JAM.flac" -c libopus -b:a 320k test.ogg`)
[File](https://1drv.ms/u/s!Aoq8mAMlVv8Us17my_itqCXzL2Nd?e=O0m2sm)

**Comment by Destroyer** [comment]
created a sample using
`opusenc.exe --music --vbr --bitrate 192 src.flac dest.opus`
`ffmpeg -i .\dest.opus -c:a copy -t 30 02.opus`

opusenc is the only needed to get the result, ffmpeg was used to trim it to first 30secs

https://www.mediafire.com/file/aowbhpmr09msw83/02.opus/file

**Comment by cw2** [comment]
This seems to be a bug in LAV Filter `CLAVFDemuxer::GetBSTRMetadata(const char *key, BSTR *pbstrValue, int stream)` function
https://github.com/Nevcairiel/LAVFilters/blob/c0c873a0cb045620af48ed2a944a8a1f77b05d19/demuxer/Demuxers/LAVFDemuxer.cpp#L3133-L3134
where the `stream` parameter has its default value `-1` that never changes during metadata retrieval and thus `m_avFormat->streams[stream]->metadata` is never returned.

**Comment by NBruderman** [comment]
@clsid2 does this bug still exist in LAV?
