### ISSUE TITLE
Scripts? Auto-Skip Chapters?

### ISSUE THREAD

**Issue by Obegg** [clsid2/mpc-hc#1221]
I watch videos that have chapters, and I would like to **AUTO-SKIP** those chapters, is there any option to do so?
If not - I noticed that there is a script "[chapterskip](https://github.com/po5/chapterskip)" that answers my needs, and I did not find any way to integrate this script to MPC-HC.
Is there any option to integrate scripts to MPC-HC?
If not - will there be any option similar to this in the future?

**Comment by lifegpc** [comment]
> Is there any option to integrate scripts to MPC-HC?

No.

**Comment by Obegg** [comment]
> > Is there any option to integrate scripts to MPC-HC?
> 
> No.

So there's no option to auto-skip certain chapters and there's no option to integrate scripts?
Then this is now a feature suggestion.
1) Auto-Skip certain chapters
2) Integration with scripts

**Comment by clsid2** [comment]
MPC-HC does not support scripts and I have no interest in adding any kind of script support.

Skipping chapters based on title is something that could be implemented, but I am also not interested in doing that myself.

The Matroska container has the ability to mark individual chapters as disabled/hidden. So you could edit the headers of your files to disable the unwanted chapters.

**Comment by Obegg** [comment]
> MPC-HC does not support scripts and I have no interest in adding any kind of script support.
> 
> Skipping chapters based on title is something that could be implemented, but I am also not interested in doing that myself.
> 
> The Matroska container has the ability to mark individual chapters as disabled/hidden. So you could edit the headers of your files to disable the unwanted chapters.

Is it possible that skipping chapters will be implemented (not by you, since you are not interested)?

I tried using "MKVToolNix 59.0.0", it doesn't answer my need to auto-skip chapters.
All it does is marking the chapter and that's it, so you can know it's a chapter, but that's it.

**Comment by clsid2** [comment]
If someone submits a patch for a good clean implementation, then I will consider using it.

**Comment by Obegg** [comment]
> If someone submits a patch for a good clean implementation, then I will consider using it.

Oh, I thought there's like a team working on MPC-HC, guess I was wrong.
If that's the case - I doubt this feature will be implemented anytime soon :(

**Comment by ale5000-git** [comment]
Just an idea: once "[Dynamic Toolbars](https://github.com/clsid2/mpc-hc/pull/1217)" is implemented, a custom buttom could be added called "Skip" that gets enabled when the video is in chapters like "Intro" or similar and disabled in other chapters.
The list of chapters to skip can be in an .ini file in the MPC-HC folder (since it should be rarely modified).

It can be similar to Netflix in the way it skip.

**Comment by clsid2** [comment]
The whole point is that it is automatic. You can already manually skip a chapter with the existing buttons or by pressing PageDown.

**Comment by ale5000-git** [comment]
Maybe there can be an .ini setting that allow to set manual/automatic skip (separate from base settings .ini).
My idea is a button (usable directly with the mouse) that isn't able to skip main film but just opening/intro and ending.

**Comment by Obegg** [comment]
> The whole point is that it is automatic. You can already manually skip a chapter with the existing buttons or by pressing PageDown.

Exactly!
For example:
![image](https://user-images.githubusercontent.com/13978119/126340229-7e25d01f-fd94-43df-9abc-d5d6723e4b42.png)
Blue chapters = Not skip
Red chapters (OP + ED) = Skip
In order to skip you need to manually click PageDown,
My suggestion/request/question is to make it skip automatically, without the need to click a key or mouse.

**Comment by ale5000-git** [comment]
I just had an idea, since yt-dlp support [SponsorBlock](https://github.com/yt-dlp/yt-dlp#sponsorblock-options) it may be easier for streamings to just get SponsorBlock chapters (see `--sponsorblock-mark all`) and use these to skip chapters.

**Comment by clsid2** [comment]
This request is primarily for local files. It obly involves handling of chapters, not the creation of chapters. So SB is not helpful at all.

**Comment by ale5000-git** [comment]
If I haven't read incorrectly the author of the issue haven't specified if it is for local files or streamings but still it may have implied them to be local files.
Also I mean just use chapters from SB, not create and send them.

**Comment by clsid2** [comment]
The requested functionality is for when chapter information is already available. Getting chapter information is a totally different and unrelated topic. So please stop commenting with irrelevant suggestions.

**Comment by hubblec4** [comment]
Skipping chapters is an easy task for Matroska. Use ordered chapters in different Editions and delete the chapters you don't want to watch.
In a good Matroska player you can change between the Editions and you can watch what you have set.

My wife like it to watch reviews and intros, but me not. So there is an Edition "With review and intro" and a second Edition "Episode only".
That's all.

**Comment by Obegg** [comment]
> Skipping chapters is an easy task for Matroska. Use ordered chapters in different Editions and delete the chapters you don't want to watch. In a good Matroska player you can change between the Editions and you can watch what you have set.
> 
> My wife like it to watch reviews and intros, but me not. So there is an Edition "With review and intro" and a second Edition "Episode only". That's all.

I'm sorry, can you explain how?
Currently I'm using MPV but I did see something about "edition", how can I make use of it?

**Comment by hubblec4** [comment]
MPV is unfortunately not a good Matroska player and the support for Editions is there but not easy to use.
The best Matroska player is MPC-HC.
In my Matroska-Playback [repo](https://github.com/hubblec4/Matroska-Playback) you will find useful info.

For easy and fast creating multiple Editions you can use [chapterEditor](https://forum.doom9.org/showthread.php?t=169984).

**Comment by adipose** [comment]
An idea. Rather than scripts there could be options loaded per file.

video.mkv
video.opt

Various options could be loaded for supported features. One could be chapters to skip. Regex perhaps.

Could have

all_mkv.opt for globals.

**Comment by clsid2** [comment]
I am not interested in added that.

**Comment by ncflagg** [comment]
> The Matroska container has the ability to mark individual chapters as disabled/hidden. So you could edit the headers of your files to disable the unwanted chapters.

I took this to mean that a disabled/hidden chapter would not be played by MPC-HC. I tested this with all variations of disabled/hidden in an mkv file using mkvtoolnix and playing with MPC-HC 2.2.1, but the chapters were still played (and visible).
