### ISSUE TITLE
Go to frame not working correctly

### ISSUE THREAD

**Issue by ask2018** [clsid2/mpc-hc#1222]
Hi,
if I open any video and use CTRL + G and try to jump to specific frame, then it is not working correctly. The frame where it ends it's not always the same frame, even if the input is the same.
To reproduce try this:
Open some video - let's say its 100000 frames long and 25 FPS.
Now go to 10000, 25.000. Here if you click "Go!" button multiple times (10x should be enough) the resulting video frame you can see it's not always the same.
Now try to open the same video twice (two instances of MPC-HC). In first video go near to frame 10000 - for example few seconds before that. In second video just pause at video start. And now try to go in both videos to 10000, 25.000. The resulting frame is again not the same frame in both videos.

**Comment by clsid2** [comment]
This is not a bug in the player. DirectShow does not have guaranteed frame accurate seeking. It depends on the file and the DirectShow filters used.

If you provide a sample file, then I can have a look if anything unusual happens in the splitter.

**Comment by ask2018** [comment]
I see, but it is not related to any specific video. I have the same issue on any random video included those sample ones for example here - https://sample-videos.com/ https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4
Well if this is not supposed to be frame accurate, maybe there should be some warning written it is not frame accurate. Because my idea was to use this  to easily compare some video frame content in 2 videos where I need to do some edits later and I've realized only way to do this is go maybe 20-30 frames before the frame I need and then go frame by frame manually. But if I use exact frame number, it will not always show the same one.
Maybe it would be possible to make this frame accurate using some indexer like DGIndexNV? I mean an option to use external indexer in MPC-HC, when the user needs "go to frame" frame accurate.

**Comment by clsid2** [comment]
You misunderstood. Seeking should be accurate in most situations. Also for that mp4 file. It works just fine here. It is not possible to modify how the splitter works or use external indexer.

It does not actually seek to a frame number, it seeks to a timestamp calculated from the frame number and fps. Right-click on the timer on the bottom of the player and enable high precision mode to see detailed time.

Which video renderer are you using? That may be buffering or dropping frames.

**Comment by ask2018** [comment]
I'm using madVR as default renderer. Will try with others after weekend, cannot atm. But detailed time and frame number seems to be the same, but visually the frame content is changing or its different depending on where from I go to it.

**Comment by ask2018** [comment]
So I've been able to test this with different renderers and seems to be issue only with madVR.

**Comment by clsid2** [comment]
It might be due the "present frames in advance" option in madVR. Try setting that to 1 or disable it.

**Comment by ask2018** [comment]
I've tried both - disable and set to 1 and it is still the same issue.

**Comment by clsid2** [comment]
I can't really help with madVR issues. I don't see the problem here after several tries, so try with default madVR settings.
