### ISSUE TITLE
to auto-load audio tracks from subfolders

### ISSUE THREAD

**Issue by Aliaksandr3by** [clsid2/mpc-hc#1223]
Folder may have a structure:

![image](https://user-images.githubusercontent.com/11432724/126796227-67ce002b-9526-450b-a079-41c283bf1187.png)

I think, if the MPC auto-loads audio tracks (if they will particly consist the same name), this will be good.

01 video_en.mka
01 video_by.mka
01 video_en.ass
01 video.mkv

p.s. as feature for subtitles that player has 
![image](https://user-images.githubusercontent.com/11432724/126797438-240e380c-9739-4dab-a4ff-33a9aac6c994.png)

**Comment by clsid2** [comment]
I am not going to implement this for audio.
