### ISSUE TITLE
auto-choice subtitles and audio tracks by a language lable: e.g. by, pl, en, it and so on

### ISSUE THREAD

**Issue by Aliaksandr3by** [clsid2/mpc-hc#1224]
auto-choice subtitles and audio tracks by a language lable: e.g. by, pl, en, it and so on

![image](https://user-images.githubusercontent.com/11432724/126797898-7b856eb3-aa42-43a7-8315-255005f992cf.png)

**Comment by lifegpc** [comment]
MPC-HC already have this option.
![image](https://user-images.githubusercontent.com/41434272/126798356-4d057281-8df1-474d-95f5-f2cc604d0245.png)

**Comment by clsid2** [comment]
You can find even more advanced track selection settings in the splitter.

Options > Internal Filters > Splitter

**Comment by Aliaksandr3by** [comment]
thx)
