### ISSUE TITLE
Subs bug with 1.9.14

### ISSUE THREAD

**Issue by coudrak** [clsid2/mpc-hc#1225]
I experiment problems with subtitles, they no longer display, just sometimes, randomly during the movie, same problem with external .srt or subtitle track, I can't explain.
So I went back to the version 1.9.13.

**Comment by clsid2** [comment]
Try the 1.9.14.19 development build.

**Comment by coudrak** [comment]
I don't reproduce even with the 1.9.14.14, I close the issue.
