### ISSUE TITLE
exclude the external audio as split file from playlist if It is a track for video

### ISSUE THREAD

**Issue by Aliaksandr3by** [clsid2/mpc-hc#1226]
exclude the external audio as split file from playlist if It is a track for video

![image](https://user-images.githubusercontent.com/11432724/126871812-1cae4c39-9929-447d-9f88-8b611b96fbb6.png)

**Comment by clsid2** [comment]
Options > Playback > disable "Auto-load audio files"

**Comment by Aliaksandr3by** [comment]
No, sorry, I explained badly 
I want to auto-load the audio track files, but I don't want to add that track to playlist.
![image](https://user-images.githubusercontent.com/11432724/126872917-d6f594f4-4fca-4424-a403-c45eb6bd8670.png)

**Comment by clsid2** [comment]
I don't have any motivation to implement a filter for that.

Open the folder. Select the videos that you want to add to playlist. Drag the selection onto the player window. Hold Ctrl button while doing the drop to append to playlist.

**Comment by Aliaksandr3by** [comment]
might you add the feature: to auto-load a last language subtitle/audio?

**Comment by clsid2** [comment]
Options > Playback > Default track preference

I am not adding any new features.
