### ISSUE TITLE
Feature request: Can we have a full screen toolbar button please

### ISSUE THREAD

**Issue by ptallett** [clsid2/mpc-hc#1227]
Great app!

On my TV I only have a mouse, so when I want to go fullscreen (always) I have to navigate through the menus. I can't press F11 as I don't have a keyboard.

A full screen button next to the volume slider would be awesome. Seems an odd omission - most players have it.

I saw there's a PR about dynamic toolbars waiting to go in, but I don't think it adds this button.

I could probably submit a PR for this, but its 15 years since I did C++, I've been doing C# since.

Cheers,
Paul

**Comment by clsid2** [comment]
The toolbar buttons can not be customized at this moment. This may change in the future.

You can go fullscreen by double-clicking on the video.
