### ISSUE TITLE
The sound of the player becomes louder after CTRL-ALT-DELETE screen closed

### ISSUE THREAD

**Issue by jason990420** [clsid2/mpc-hc#1228]
Platform
- WIN10 Home 21H1
- MPC-HC (64-bit) 1.9.14(4488e7d5a), MSVC v19.26.28806, LAV Filter 0.75.1.0

When MPC player is playing a video
- CTRL-ALT-DELETE pressed
- Select task manager or Cancel
- The sound of the player becomes louder
- Close MPC player, re-open it with same video, it will be back to original volume.

Of course, it can work in both cases, but just show the case what will happen.

**Comment by clsid2** [comment]
Sounds like a bug in Windows.

You can press Ctrl+Shift+Esc to open Task manager directly.

**Comment by jason990420** [comment]
I can open task manager by right button on task bar.
I open windows media player at the same time, after CTRL-ALT-DELETE screen closed, MPC player is the only one program/application which looks like refresh then become louder.

**Comment by clsid2** [comment]
No problem here. Sound keeps playing normally when Ctrl-Alt-Del screen is active. No volume change when pressing cancel to close it. There is a small hickup on Windows 10 after the close. Maybe this triggers a reset when you have enabled the volume normalization option in the settings. No hickup on Windows 7.

I don't see any evidence of a bug in the player. Certainly not something I can fix. And I honestly don't really care much about this kind of weird issues that don't happen during normal usage.

Maybe someone else can reproduce the problem and analyze it.
