### ISSUE TITLE
Unexpected error - Access Violation

### ISSUE THREAD

**Issue by garland-charest** [clsid2/mpc-hc#1230]
This error occurs to me sometimes on new file loading.
Once file is already playing it never happens, loading new file might trigger it.
I dont know steps to reproduce but it keeps repeating randomly, (system reinstallation gives nothing)
It might be worth to mention that I'm using Windows 10 LTSB 2016 with latest security updates.
![error - Copy](https://user-images.githubusercontent.com/88022032/127106250-101e71a9-aa85-4e6f-9bf2-c592c3f843f6.PNG)

**Comment by clsid2** [comment]
Down the ZIP of latest development build:
https://github.com/clsid2/mpc-hc/releases
Replace you current version. Also copy the CrashReporter folder. Then it should generate a more detailed error message.

**Comment by garland-charest** [comment]
It still has happened with latest development build 1.9.14.18 and no any external filters enabled
About crashreporter, is there a way to get that more detailed error message offline? (and upload it on here or directly later)
I mean when crash has happened it wanted to directly connect internet but my current environment is mostly offline or heavily firewalled

**Comment by clsid2** [comment]
Crash reporter works online only. It will generate a stack trace, which will show where in the code the problem occurs.

**Comment by garland-charest** [comment]
https://drdump.com/UploadedReport.aspx?DumpID=65427682

**Comment by clsid2** [comment]
Last part of the call stack is all in the DirectShow code of Windows. It might not be a bug in the player itself. I know it is probably a threading issue. I will need to analyze additional dumps to find out more.

I assume you are using the default EVR-CP video renderer. Can you test if it also happen with plain EVR or Sync Renderer (which also uses EVR)?

**Comment by garland-charest** [comment]
If I remind correctly it wasn't happening when I was using Win10 LTSC 1809 for short period of time
And is happening on my two devices with Win10 LTSB 1607 (both are using very different drivers since one is amd based, another is intel + intel gpu)
Because it happens _not so often_, I ignored this for over year. Sometimes I could close window using OK button on error message, other time process manager was needed because even mpc error message was frozen.

Yes I'm using default EVR-CP video renderer
Now I have switched over plain EVR for test
Getting any feedback will be rather slow...

**Comment by garland-charest** [comment]
Ok I've end up using Sync Renderer (with same resizer as EVR-CP) for whole week with not even single crash so far.
Actually I might stay with sync renderer as mitigation, thanks for help!
