### ISSUE TITLE
Youtube links problems and missing functionality

### ISSUE THREAD

**Issue by formlessdao** [clsid2/mpc-hc#1231]
1.At this time I don't know how to change the resolution for the youtube video in MPC-HC
Potplayer makes so easy to choose the resolution you want your video to play at.
2.Am not able to just send link from the browser while on youtube to be added in MPC playlist neither from Chrome or Firefox.
3.Playlist does not show thumbnails for youtube links.
4.Does not have "Paste URL from Clipboard"

**Comment by ale5000-git** [comment]
1) It is implemented differently, it always use the biggest resolution possible but you can cap maximum in advanced settings (YDLMaxHeight).
2) It has nothing to do with MPC-HC, you can drag 'n' drop the website over MPC-HC and it works or search a browser extension that do it automtically.
3) It is intended, it doesn't show preview in any streamings.
4) You can simply do File => Open File/URL => Ctrl + V

**Comment by clsid2** [comment]
I am not adding any new functionality.

**Comment by formlessdao** [comment]
> 
> 
> 
> 
>     2. It has nothing to do with MPC-HC, you can drag 'n' drop the website over MPC-HC and it works or search a browser extension that do it automtically.
> 
>   
> 
>
There is no browser extension that does that.


> 
> 
> 
> 
>I am not adding any new functionality.
> 
> 
> 
> 
This amazing player barely has a functional playlist. Only functionality it absolutely needs is to have thumbnails for every youtube link is added in playlist.That's all you need to implement.

**Comment by clsid2** [comment]
You can click on the lock icon in front of the URL in the browser address bar, and then drag&drop it onto MPC-HC. If you hold CTRL button when dropping, then it will append to playlist instead of opening it directly.

**Comment by ale5000-git** [comment]
For Firefox there is this: https://addons.mozilla.org/it/firefox/addon/send-to-media-player-classic/

**Comment by formlessdao** [comment]
> 
> 
> For Firefox there is this: https://addons.mozilla.org/it/firefox/addon/send-to-media-player-classic/

Abandoned long ago..but it shows how much you cared, you just copy pasted the first thing that you found and did not bother to test... I have already tried everything available on mozilla addons, nothing works.

**Comment by ale5000-git** [comment]
I'm busy with other things so I don't have time to test but there are a lot of them and also drag 'n' drop is simple to use.
I will create an extension in the future but I don't know when I will have time.
