### ISSUE TITLE
[Feature Request] Favourites Max Amount + Store to file

### ISSUE THREAD

**Issue by Funghie** [clsid2/mpc-hc#1232]
Delighted to find out that this is still being developed.

I work with multimedia and a lot (yes a lot!) of projects.

- It would be sooo useful if the number of favourites (with position) could be increased above 999.
- Also it would be very useful to be able to store these in a separate file instead of in the registry.

Is there any chance of this happening?

Thank you. :-)

**Comment by clsid2** [comment]
The menu itself is limited to 999 entries and that can not be increased. The organize favorites dialog should be able to show them all. I can't find any size restriction in the code for the number of favorites.

I am not going to implement storing stuff in a separate file. It is easy to make a backup. Exporting a registry key is trivial to do and can even be done from command line.
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\Favorites

**Comment by Funghie** [comment]
Aha thanks I never thought to actually check in the dialog. Dealing with the Reg key is fine too. I already made a number of utilities to sort and so on, (which I will gladly share). The only thing I struggle with is the timings. What on earth does that big number mean?

**Comment by clsid2** [comment]
Time is measured in units of 100 nanoseconds. So divide by 10.000.000 to get the number of seconds.

**Comment by Funghie** [comment]
Thank you ever so much for the guidance. Much appreciated.
