### ISSUE TITLE
H.265(.mp4) and MPEG-TS(.ts) video files' thumbnails are missing.

### ISSUE THREAD

**Issue by Crispin777** [clsid2/mpc-hc#1237]
Video thumbnails aren't generating.
OS: Windows 10 20H2

**Comment by NanaMizukiAnother7** [comment]
Did you install Icaros? I have Icaros installed on my computer and it works fine.

**Comment by clsid2** [comment]
The player is not involved in any way with generation of thumbnails in Explorer.

You need to install [H265 Media Foundation codec](http://codecguide.com/media_foundation_codecs.htm) or [Icaros](https://www.videohelp.com/software/Icaros).
