### ISSUE TITLE
Having Time Displayed in the OSD Prevents Other Functions From Displaying Properly

### ISSUE THREAD

**Issue by MadokaAyukawa** [clsid2/mpc-hc#1240]
Normally when I change volume or ask to display the name of the file in the OSD, the requested information stays on screen for several seconds. If the time is displayed in the OSD, then the current volume or name of the file only displays for a fraction of a second before disappearing, much to fast to read. Ideally, this information should display for as long a time as if the OSD time were not currently displayed.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2625
