### ISSUE TITLE
Reattach to lost and recovered drive (currently crashes)

### ISSUE THREAD

**Issue by BreakPoints** [clsid2/mpc-hc#1244]
I am using an external SATA to USB enclosure for most of my media and it has the "feature" of turning off power to the drive itself when no access request is made for 10 minutes or the computer goes to sleep. I cannot change this. When the computer wakes the drive is momentarily unavailable and then almost instantly I get the "new device connected" sound in Windows, it's back.

After this MPC-HC crashes if I try and continue to play the file that was open when the computer slept. Usually I get a second or two of content (probably buffered) then a crash or an instant lockup if I try and seek the file.

**Comment by clsid2** [comment]
The file is opened by the source filter, not the player itself. I can't fix it.

**Comment by BreakPoints** [comment]
Unfortunate, is there any way to send a new open file request to reset the source filter and seek to the last known time? If we can figure out where in the code this crashes could we not add a try/catch type scenario for an attempt at a recover. Even just closing the open file should avoid the crash.

**Comment by clsid2** [comment]
You can use Ctrl+E to reload the file. If you enable the option to remember playback position, then you can resume from same position.

When the player crashes it should open a DrDump crash report. Give link to that page.

**Comment by BreakPoints** [comment]
I don't get a DrDump crash report, even on the build just released (1.9.15).

Seems to be MadVR causing the crash, when that is the output Windows detects MPC-HC as not responding and does the fade to white. In task manager the process is still using CPU and GPU.

When EVR-CP is used the file still is unable to be played or scrubbed passed the buffer but there is no crash, Ctrl-E reloads the file and it can continue.

**Comment by clsid2** [comment]
Right-click on the hanging process in the task manager and create a dump file. Zip/rar/7zip the dump and upload it somewhere. For example http://www.sendspace.com

**Comment by BreakPoints** [comment]
I wasn't able to upload to sendspace as the dump was too large, here's a mega link:
https://mega.nz/file/2sp3FKAI#F7Ttk3dWs70zSyC_YlTj5d92e65ytFiEOP0cmvbHz0Y

**Comment by clsid2** [comment]
I don't see anything obvious in the player related threads in the dump. So problem is likely in madVR.

I will consider implementing an automatic file reload after a long pause.

Does seeking backwards once with left arrow, while still paused and thus before resuming play, also trigger the hang?

**Comment by BreakPoints** [comment]
Stepping back once and playing also leads to the same crash

**Comment by BreakPoints** [comment]
I see an automatic file reload mechanism has been added recently. Once a build is available I'll test for this issue again.

**Comment by clsid2** [comment]
1.9.16.51 is available now

**Comment by BreakPoints** [comment]
I was able to reproduce the bug only in cases where the video reloaded before the external drive had time to reconnect, for example leaving a file playing and setting the computer to sleep leading to an immediate reload on logging back in.

I'm unsure we can get any better without the reload being attempted at the point of lockup/crash being hit

**Comment by clsid2** [comment]
What you could do is:
Menu > File > Open File Location
Then wait until drive is running before resuming playback.
