### ISSUE TITLE
Scroll to seek - sometimes restarts the file

### ISSUE THREAD

**Issue by zoidbergthepopularone** [clsid2/mpc-hc#1245]
When using the scroll to seek feature (Ctrl+MouseWheel) extensively, MPC-HC will sometimes reset the seek pointer and start from the beginning of the file. I was unable to reproduce it reliably and sometimes it does not occur at all, but more often than not, if I perform a lot of seeks in this way, the position *will* eventually reset. I suspect that it might in fact be Windows who is sending an incorrect trackbar position to MPC-HC, but it would be nice to have some kind of an optional workaround - e.g. "if the trackbar position jumps a lot without a keypress or a mouse button click, ignore the jump".

**Comment by clsid2** [comment]
Here is a debug build:
https://www.sendspace.com/file/3myzqf
Run dbgview.exe to capture a log. It should show the seek positions.

**Comment by zoidbergthepopularone** [comment]
Thanks. I was unable to reproduce the behavior yet, but I will keep trying and post results when I succeed.

**Comment by clsid2** [comment]
Were you using version 1.9.13 or older? Because a seek issue was already fixed in 1.9.14

**Comment by zoidbergthepopularone** [comment]
I am actually not sure. I think I encountered it with 1.9.14, but it might have been 1.9.13. I will keep trying to reproduce the problem in the current version.
