### ISSUE TITLE
Unable to scan DVB-T network

### ISSUE THREAD

**Issue by epbk** [clsid2/mpc-hc#1246]
Scannig of Czech DVB-T2 networks does not work.
Tunnig works fine (manualy edited mpc-hc channel registry).

Log:
```
11:36:22.444 - CFGManagerBDA::Scan: Scanning frequency 578000.......... (C:\Code\clsid2\mpc-hc\src\mpc-hc\FGManagerBDA.cpp:793)
11:36:37.445 - CFGManagerBDA::Scan: ParseSDT failed. Result: 0x80040206. (C:\Code\clsid2\mpc-hc\src\mpc-hc\FGManagerBDA.cpp:796)
11:36:37.445 - CFGManagerBDA::Scan: Scanning frequency 578000 done. (C:\Code\clsid2\mpc-hc\src\mpc-hc\FGManagerBDA.cpp:810)
```

SDT block dump:
[SDT_578000.zip](https://github.com/clsid2/mpc-hc/files/6967732/SDT_578000.zip)

**Comment by clsid2** [comment]
The error is coming from Microsoft code.

I don't have DVB hardware. Someone else will have to investigate this problem.

**Comment by adipose** [comment]
https://social.msdn.microsoft.com/Forums/en-US/6a616630-63b7-477b-b30e-36437f0a6dc9/idvbsiparser-returning-vfwenotypes-0x80040206?forum=windowsdirectshowdevelopment

VFW_E_NO_TYPES means a pin supports no media types.

Pretty hard to test without being in your area with supported DVB hardware. How did you get that dump?  I did remote debugging one time before with success, but I had a custom build to export it.  You could go try to find that, but I don't recall if I saved the branch.

**Comment by epbk** [comment]
The SDT dump comes from my own C# SAT>IP scanner with BDA support. I'm using only SampleGrabber to get TS and my own code to get the specific sections from TS. Not IMpeg2Data::GetSection method. TS and SDT data are intact.
Forgot to mention I'm using Win7 32bit.
I have suspicion that there must be a bug in DirectX library.
Btw, both VLC and MediaPortal TV Server working fine.
Interesting is that old DVB-T network was running fine in MPC-HC but new DVB-T2 not.

**Comment by adipose** [comment]
I guess it is failing in GetSection or GetSectionData.  The code parsed your data just fine, when loaded from the file.

**Comment by adipose** [comment]
`MPEG2_E_SECTION_NOT_FOUND` is defined as `MAKE_E_ITF_HRESULT(MPEG2_BASE + 0x06)` = 0x80040206

This is also a possible return value from `IMpeg2Data::GetSection` ("The filter did not receive a matching table section." ).

Looking at the code, it uses a filter for the section number.  However, it doesn't seem to be initialized for ParseSDT (except for the structure being zeroed), so that means it likely expects section "zero".  As far as I can tell this filter is pointless except for ParseEIT, but maybe I don't understand the code.  I have a test build here that ignores the filter.

https://mega.nz/file/0FQQhBoI#A61iiAKMxkRSH5gm0OZuVt1fyNJS8GbjIpGfKdakTZ4

**Comment by epbk** [comment]
I have some progress.
The scan works but only if mpc-hc is in playback mode (i.e. playing). If stopped then does not.

**Comment by adipose** [comment]
Well, that seems pretty unlikely to me, but maybe I'm missing something.

If you want me to try further, would you consider plugging your tuner into a machine that I could test remotely?  I would like to see what's actually happening step by step.

If not, I could do some debug builds, but this is a pretty low priority feature, so I don't want to spend too much time on it.

**Comment by epbk** [comment]
I'm sorry adipose,
I forgot to mention that I was testing on latest mpc-hc build(1.9.15) on 2 different PCs (Win7 32bit and 64bit), not on your build.
I can confirm 100% reproducibility on 2 different PCs. The result was always the same: if I start the scan while stopped then scan fail.
Currently I don't have spare PC to be used for remote testing, sorry.

**Comment by adipose** [comment]
> 
> 
> I'm sorry adipose,
> I forgot to mention that I was testing on latest mpc-hc build(1.9.15) on 2 different PCs (Win7 32bit and 64bit), not on your build.
> I can confirm 100% reproducibility on 2 different PCs. The result was always the same: if I start the scan while stopped then scan fail.
> Currently I don't have spare PC to be used for remote testing, sorry.

No worries.  Any reason you didn't try the test build?

**Comment by epbk** [comment]
Hi adipose,
did some tests with your build, no difference. Scan fails in stopped mode.

**Comment by adipose** [comment]
> 
> 
> Hi adipose,
> did some tests with your build, no difference. Scan fails in stopped mode.

Can you show the log results?

**Comment by epbk** [comment]
> Can you show the log results?

Here is the log report:

[bda.log](https://github.com/clsid2/mpc-hc/files/7093986/bda.log)

**Comment by adipose** [comment]
Hmm, maybe I'm confused, but that looks like a log from a clsid2 build, not the one I uploaded.  

`C:\Code\clsid2\mpc-hc\src\mpc-hc\FGManagerBDA.cpp`

**Comment by epbk** [comment]
It looks like I did something wrong.
Is this the right one?

[bda.log](https://github.com/clsid2/mpc-hc/files/7095033/bda.log)

**Comment by adipose** [comment]
> 
> 
> It looks like I did something wrong.
> Is this the right one?
> 
> [bda.log](https://github.com/clsid2/mpc-hc/files/7095033/bda.log)

Yep, that's it.  Same error.  It seems it couldn't find any section at all.  I can make another build to export all the data to a bin file and see what's going on.

**Comment by adipose** [comment]
I'll look at this again in a few weeks.  I don't have the equipment to test it but I may have found something that will work.

**Comment by adipose** [comment]
I now have DVB-T2 emulation equipment sufficient to test scanning.  I tested the stream from here:

https://tsduck.io/streams/?name=france-dttv

https://tsduck.io/streams/france-dttv/tnt-uhf22-482MHz-2019-01-22.ts

Success!

![image](https://user-images.githubusercontent.com/3324395/133707176-2e72729e-8bd7-48b9-afd5-7cfa37bf24f1.png)

So, I don't know what your problem scanning DVB-T2 is.  Btw my tuner is a TBS5580.

**Comment by adipose** [comment]
I could reproduce it not scanning when the tuner was "stopped".  Behavior is weird, something like this:

1. Click stop
2. Click scan
3. Fails immediately
4. Click scan again
5. Fails after a nice delay
6. 4-5 can repeat forever
7. Quit scan
8. Tuner shows in "play" mode
9. Click scan.
10. It works now

So, somehow the scanning enables the tuner (maybe on the first fail), but not sufficiently to work until the scan interface is restarted.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1312

**Comment by epbk** [comment]
Yes, it is working now. Tested on latest version 1.9.16. 
Thanks adipose.
