### ISSUE TITLE
Mosaic like effect when playing HEVC

### ISSUE THREAD

**Issue by bbeessii** [clsid2/mpc-hc#1247]
Mosaic like effect started to appear diagonally when playing HECV video.

Is this some kind of bug, or does it have to do something with config

Attached is a screenshot in which the issue is visible. 
![bug](https://user-images.githubusercontent.com/88655885/129188061-b58465c1-94be-4bf3-aba2-49d82e499df5.jpg)

Thanks

**Comment by clsid2** [comment]
Most likely a bug in your graphics driver.

Try disabling hardware decoding in the video decoder settings.

**Comment by bbeessii** [comment]
> Most likely a bug in your graphics driver.

I thought so, but the issue is not present if i use another player such as vlc (which i don't like one bit) so i figured it must be something worng with MPC-HC.

**Comment by clsid2** [comment]
Which GPU do you have?

It doesn't mean anything that it works in VLC.
For example, VLC blocks hardware acceleration for certain Intel GPUs.
Also, some post-processing that drivers do is only done for the video renderers from Microsoft, which VLC does not use.

**Comment by bbeessii** [comment]
> Which GPU do you have?
> 
> It doesn't mean anything that it works in VLC.
> For example, VLC blocks hardware acceleration for certain Intel GPUs.
> Also, some post-processing that drivers do is only done for the video renderers from Microsoft, which VLC does not use.

By default is uses Intel HD Graphics, i will try the same using Nvidia Geforce MX150.

It felt weird because until 2 weeks ago it worked perfectly with Intel and Nvidia.

I'll get back to you in a few minutes.

Thanks a lot.

**Comment by bbeessii** [comment]
> Which GPU do you have?
> 
> It doesn't mean anything that it works in VLC.
> For example, VLC blocks hardware acceleration for certain Intel GPUs.
> Also, some post-processing that drivers do is only done for the video renderers from Microsoft, which VLC does not use.

By default is uses Intel HD Graphics, i tried Nvidia GPU Mx150 and the same issue.

It is a little weird since it was working without issue just two weeks ago, but after a few updates the issue appeared.

I am not very "fluent" with renderers, so if you have any suggestion i would greatly appreciate.

Thanks a lot.

**Comment by hooke007** [comment]
>By default is uses Intel HD Graphics, i tried Nvidia GPU Mx150 and the same issue.

There is no hw-decoding support in MX series GPU. If it was related with decoding. There's no diff by choosing HD Graphics or MX (you may still were using HD to decode the video).
I used to see this error when I use dxva video processor, not sure if it would be the cause.

**Comment by clsid2** [comment]
In the Intel graphics control panel, disable all video enhancements such as "Contrast Enhancement" and "Skin Tone Enhancement" and "Noise Reduction". Those options actually often reduce quality, and are also known to cause playback problems.
