### ISSUE TITLE
[DrDump] MPC-HC crashed due to a fault in LAV Filters

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#1248]
This page opened because a crash occurred in the internal codecs of MPC-HC.

**First update to latest version of MPC-HC.** The problem might have already been fixed.

**Please share details about the file that crashed.** Then hopefully we can reproduce the problem and fix it.

There have been hundreds of crashes, and we get almost no feedback at all, which means no fixes! So don't be lazy and assume someone else will submit a crashing file.
(Please ignore the fact that this issue is marked as "closed" below, that is just to hide it from general view.)

You can submit files here or send details privately to:
clsid2@users.sourceforge.net
You can share for example a torrent link or website link of where you got the file.
Or upload the problematic file to for example Dropbox, Google Drive, or a file hosting site like sendspace.com

**MKV file with ordered chapters**

If the crash occurred when transitioning to the opening/ending chapter in a video with ordered chapters (where chapters are in separate linked files) then check if the files were encoded with different video formats. That is not supported and will not be fixed. Tell the encoders who made the file to stop mixing different video formats. As a workaround you can delete the OP/ED chapter files to avoid the crash.

**Partially downloaded file**

If a file is incomplete or damaged, then that could be a reason why a crash occurred due to invalid data. But share the incomplete file with us could still be useful to make decoder more resilient.

**Comment by luffs** [comment]
I suppose this video is a bit of an edge case.
[cat.webm](https://user-images.githubusercontent.com/733345/185990660-f25d8198-41f7-4a4d-b601-8a94d0c4ff00.webm)

**Comment by Lopolin-LP** [comment]
[a Video I found on the MC@H Discord Server, intended to be viewed in different browsers and devices](https://cdn.discordapp.com/attachments/774412973158432809/957634723264483368/4dff80e50e7d1525.webm) **Warning: Contains Flashing lights**

mhh... a webm again...

**Comment by DexLuther** [comment]
Just got this crash, which I presume is why I'm here as this page opened because of it. Playing a 1080p MKV. The audio was 5.1 AC-3 and the video was a plain ol' x264 MP4.

First time it played for a few seconds, second time it crashed on opening the file. There's no indication of whether or not any kind of log or crashdump is generated or where it would be located. It just shows the windows 10 "X has stopped working" dialogue where it searches for a second and then opens this page.

**Comment by truehd24** [comment]
Tried to open a file with DNxHR 444 12-bit encode. Opens fine in VLC. 
[https://we.tl/t-QWymZjOKpE](url)

**Comment by clsid2** [comment]
Doesn't crash here. Try latest development build.

**Comment by truehd24** [comment]
Yeah I tried it on another pc and it plays fine. Must be something wrong on my end.

**Comment by danieleg1** [comment]
Hi, I just experienced a crash and this issue opened. Here is the video file.

https://github.com/user-attachments/assets/f8a3e617-e84f-47da-94c2-2ef9d4bdc827

It's coming from recording a screen capture with a PiKVM (more detailes here: https://docs.pikvm.org/video/#video-recording)
