### ISSUE TITLE
Files deleted or disappearing during playing in MPC-HC.1.9.14.x64

### ISSUE THREAD

**Issue by ki-dragon** [clsid2/mpc-hc#1249]
Hi there,

Sounds very strange but I've experienced this issue twice in last two days.
During the playing of a video the player stops like no video available.
Checking the files It really disappeared or have been deleted!
There is not file anymore which have been played.
Very strange.

Using Windows 10 20H2 I'm pretty sure that it started after the last cumulative Windows update KB5005033 installed two days ago.
Of course it could be other updates installed on the same day (.NET etc.) or something else too.

Now I'll backup all files played first in order to be sure not to loose them.
Updated to MPC-HC.1.9.15.x64 too and hoping that it will never happen again.

Regards

**Comment by clsid2** [comment]
I can't help you with Windows bugs.
