### ISSUE TITLE
Windows 10 flags MPC-HC.1.9.15.x64.exe as security risk (unrecognised app/unknown publisher)

### ISSUE THREAD

**Issue by BK0506** [clsid2/mpc-hc#1251]
When you double-click to install MPC-HC.1.9.15.x64.exe on Windows 10, you get the following alert:

"Don't run.
Windows protected your PC.
Microsoft Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk.

Application: 
Publisher:  Unknown publisher "

**Comment by lifegpc** [comment]
That's normal. This program don't have a certificate to verify it's publisher. You should just download file from which u trust or u can compile it yourself.

**Comment by clsid2** [comment]
Click on "More Information", and then "Download anyway" or "Run away".

SmartScreen is stupid and blocks anything that has not yet been downloaded a lot of times.
