### ISSUE TITLE
Online Subtitle search window not appearing

### ISSUE THREAD

**Issue by katamu** [clsid2/mpc-hc#1252]
Using Windows 7, pressing D or 'File>Subtitles>Download Subtitles' the Status bar will show "searching for subtitles online" and will even say "xx subtitles found" but the actual subtitle download window is nowhere to be found. Trying to search again does nothing. Using dev build  1.9.15.4 but also happens in stable  1.9.15 version.

**Comment by clsid2** [comment]
Working fine for me and others.

Are you perhaps using Slack application? That might be messing with the subtitle window, according to some reports.
