### ISSUE TITLE
[Feature request] Show video stream progress in the seekbar 

### ISSUE THREAD

**Issue by SilverKnight-Z** [clsid2/mpc-hc#1254]
Like I indicate in the title, would it be possible to show the amount of loaded cache of a video stream while playing it?
I mean something like coloring the seekbar like in YouTube and VLC, or showing the time loaded in cache like mpv.
Sorry if i offend someone with these comparisons, but I mention them just to illustrate my point.

Thank you for your attention

My system specifications:
Windows 7 starter SP1 32-bit
Intel Atom n450 1.66 GHz processor
Intel GMA 3150 integrated graphics
1 GB RAM
MPC-HC 1.9.15 x86 zip

**Comment by clsid2** [comment]
Not possible because the source filter does not expose such information.

I am also not adding any new functionality.
