### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by ezequiel2000** [clsid2/mpc-hc#1255]
Audio stops working when I unplug my headphones or plug it in while watching something, my laptop has 2 different audio setups: Headphones and speakers high definition audio device that switches automatically depending on what I'm using.

**Comment by clsid2** [comment]
You can select the output device in the options.

**Comment by clsid2** [comment]
The internal audio renderer does not support changing the endpoint during playback. Try with Default DirectSound Device. If that also doesn't work, then all I can suggest is to use Ctrl+E to reload your file. In the player options you can enable "remember playback position".

**Comment by ezequiel2000** [comment]
I see, is that something you would be able to add in a future release?

**Comment by clsid2** [comment]
Yes, maybe.

Were you using the internal audio renderer? Does DirectSound do switch properly?

**Comment by ezequiel2000** [comment]
I just switched it to internal audio renderer and it seems to work. I am now able to hear audio perfectly when unplugging my headphones and switching to speakers and vice versa.
