### ISSUE TITLE
[Feature request] Mass load youtube videos based off a list in a text file

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1256]
Right now you have to add the videos one by one, which is a drag. `youtube-dl` does support importing entire playlists but if it's very big it's bound to freeze `mpc-hc`.
Alternatively, let the user add in multiple files at once, with paths separated by newlines.

**Comment by clsid2** [comment]
Already possible.

Put list of URLs in a .m3u playlist file.
