### ISSUE TITLE
ASS subtitle not loaded automatically when there is WebVTT subtitle embedded

### ISSUE THREAD

**Issue by bagusnl** [clsid2/mpc-hc#1259]
I have some video files that have webVTT embedded and also ASS sub in the same folder with .[language code].ass prefix on it, but it wont show on the subtitle picker of mpc requiring me to load it up manually either with drag and drop (when using MPC Internal Subtitle Renderer) or by using load subtitle function (when using something like XySubFilter/VS-Filter)

Example for the file structure:
![image](https://user-images.githubusercontent.com/28079733/130389488-dbc45a21-b7eb-42b7-972e-80fb17bae51a.png)
the one without the language prefix on it I added manually by duplicating the en.ass one for testing, it still wont load it automatically
![image](https://user-images.githubusercontent.com/28079733/130389526-0b9d71bb-8f72-41e2-a44d-f1e681680a1b.png)

**Comment by clsid2** [comment]
The filenames are different at the end. The video has [ ].
