### ISSUE TITLE
Contextual menu option (Windows Explorer)

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1261]
![image](https://user-images.githubusercontent.com/17074394/130680168-63d95c02-5de6-428e-a9a5-815be7095962.png)
Is there an option to remove these from the contextual menu (right click) of windows (file) explorer?
I went through options and found nothing

**Comment by clsid2** [comment]
It looks like you are using K-Lite. You can find options for removing these menu entries in its installer.
