### ISSUE TITLE
[Feature Request] Allow multiple keys for the same command

### ISSUE THREAD

**Issue by derickso** [clsid2/mpc-hc#1262]
So for instance Space and Down Arrow can both Pause a video

**Comment by clsid2** [comment]
Already possible. The red coloring is to warn you about duplicates.

**Comment by derickso** [comment]
No, not possible

I don't want Space to Pause the video and Go to full screen,

I want two buttons to perform the same command like I listed in my original comment

**Comment by clsid2** [comment]
That will not be implemented.
