### ISSUE TITLE
Allow to enter full-screen mode before video is loaded

### ISSUE THREAD

**Issue by ltguillaume** [clsid2/mpc-hc#1265]
Currently, when a video is still loading, you cannot enter the full-screen mode.

This is especially annoying when opening a stream, e.g. a YouTube link: you need to wait seconds before pressing the hotkey for full-screen mode even registers.

So, you need to keep trying _and_ you can never watch the video in full-screen right from the start.

I think the easiest way is to just allow full-screen mode when the logo is showing/playback is stopped.

**Comment by clsid2** [comment]
Options > Playback > Fullscreen >Launch files in fullscreen
