### ISSUE TITLE
Default menu items are not rendered in bold

### ISSUE THREAD

**Issue by cw2** [clsid2/mpc-hc#1275]
Apparently, `MF_DEFAULT` flag passed to `AppendMenu()` function does not cause the menu item to be rendered in bold font:

![no-default](https://user-images.githubusercontent.com/10730406/131472162-5327c418-3b95-485f-9008-31196c16aa01.png)

However, calling `SetDefaultItem()` afterwards fixes it:

![bold-default](https://user-images.githubusercontent.com/10730406/131472307-13000318-facc-4a9a-b01e-215eb50a00f6.png)

This affects both audio and subtitles submenus; I already have fix in progress. The question is whether the default item should be bold if there is only one?

Edit: MF_DEFAULT is not included in neither MFC nor Win32 AppendMenu() documentation:
https://docs.microsoft.com/en-us/cpp/mfc/reference/cmenu-class?view=msvc-160#appendmenu
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-appendmenua

**Comment by clsid2** [comment]
I have no idea. I do see a highlight value here:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmenustate

**Comment by ArcticGems** [comment]
> 
> This affects both audio and subtitles submenus; I already have fix in progress. The question is whether the default item should be bold if there is only one?

Yes. I think consistency is important.
