### ISSUE TITLE
Favorites List has no scrollbar.

### ISSUE THREAD

**Issue by noto10** [clsid2/mpc-hc#1277]
I am using 1.9.15 stable (64 bit) and there is no vertical scrollbar for my Favorites list which is longer than the screen (See below). It is also not possible to scroll down using the mouse wheel.

Is there something amiss with my configuration or is this a bug?

![mpchc_scroll](https://user-images.githubusercontent.com/13828004/131543304-763004e1-4324-4940-ad51-d54e29d84aec.jpg)

**Comment by clsid2** [comment]
Menus don't have scrollbars. You can scroll at the bottom of the menu. To view list with scrollbar click on "organize favorites".
