### ISSUE TITLE
[Request] Display Current Time without OSD on

### ISSUE THREAD

**Issue by jbiribi** [clsid2/mpc-hc#1280]
Can you add an option to show the current time of the video without needing the OSD to be on? Or maybe a way to customize OSD to show only the information you want.

**Comment by NanaMizukiAnother7** [comment]
The current time is not displaying when the OSD is off because it can only be displayed with the OSD is on.

You can turn on the OSD to display the current time.

**Comment by jbiribi** [comment]
> The current time is not displaying when the OSD is off because it can only be displayed with the OSD is on.
> 
> You can turn on the OSD to display the current time.

I know that. I'm asking to implement an option to show the current time without OSD on.

**Comment by Thespikedballofdoom** [comment]
and without statusbar!
(the entire statusbar needs an option to integrate into the controls honestly, or be side by side in some way)

**Comment by clsid2** [comment]
#1340
Duplicate
