### ISSUE TITLE
[Request] Fit to window if larger than window only

### ISSUE THREAD

**Issue by Thespikedballofdoom** [clsid2/mpc-hc#1281]
No player really has this option, but it'd be nice to have this one with it. Just switched over cause mpc can framestep backward.

**Comment by ArcticGems** [comment]
I haven't tested it, but have you tried this? =

View->Zoom->Auto Fit (Larger Only)

**Comment by Thespikedballofdoom** [comment]
Ah, that does it. I only messed with the size display settings

**Comment by Thespikedballofdoom** [comment]
Actually it doesn't seem to work like that. auto fit (larger only) doesn't seem to even do anything.

I don't even know if the definition of "zoom" means anything related to the video at this point so to mention the options that I do understand: Basically I'm trying to get "touch to window from inside" but only if the video is too large to display, because scaling up small videos is bad for me.

**Comment by ArcticGems** [comment]
If you have this =

Options->Player->History->Uncheck option "Remember last windows size"
Options->Playback->Zoom and Alignment->Auto-Zoom: 100%
View->Video Frame->Touch Window From Inside

Player window will adapt to the video resolution size = no upscaling.

Does this answer your question?

**Comment by clsid2** [comment]
The default settings should already do what you want.
