### ISSUE TITLE
Video frozen when playback resumed after extended pause

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1285]
Video is frozen when playback is resumed after an extended period of time or windows resumes from hibernation.

This behavior showed up on release v1.9.13 and is present in all releases after on my machine.

OS Name	Microsoft Windows 10 Enterprise LTSC
Version	10.0.17763 Build 17763
madVR v0.92.17, Direct3D 11
MPC Audio Renderer - CLSID : {601D2A2B-9CDE-40BD-8650-0485E3522727}, WASAPI exclusive, sync video to audio
GPU: GTX 670

**Comment by ArcticGems** [comment]
It could coincidentally be your graphic card driver.

Have you tried an older release of MPC-HC with your current graphic card driver?

If you still have a problem, try updating your graphic card driver and report back.

**Comment by ghost** [comment]
@ArcticGems Yeah, currently using the older v1.9.12 release which doesn't have this issue.

**Comment by clsid2** [comment]
This problem actually already existed in older versions. In version 1.9.11 I added a workaround that helped solve it for some people. I made it perform a seek (to current position) before resuming playback.

Can you test if seeking backwards a little before resuming prevents the frozen video with 1.9.15?

Can you also test 1.9.12.4 and 1.9.12.10?
https://github.com/clsid2/mpc-hc/releases/tag/1.9.12

**Comment by ghost** [comment]
Okay, v1.9.15 seems to work with or without seeking a little backwards. I will also test 1.9.12.4 and 1.9.12.10 and report back.

**Comment by clsid2** [comment]
If v1.9.15 works then you don't need to test the older versions.

**Comment by ehoogeveen-medweb** [comment]
What Hardware Decoder (if any) are you using in the (LAV) Video decoder settings? I've always had issues with large seeks or resuming after an extended pause with the D3D11 Hardware Decoder (it causes the player to hang forever and I was never able to reproduce it on command).

**Comment by clsid2** [comment]
One decoding hang issue with D3D11 was fixed six months ago. So it is possible that no longer happens.

**Comment by ehoogeveen-medweb** [comment]
I'll try enabling it again and see what happens. Is it possible to debug a hang with Dr. Dump?

**Comment by clsid2** [comment]
If the player hangs, create a dump with the Windows Task manager.

**Comment by ghost** [comment]
I'm actually still having frozen images after a long period of time but the audio keeps running in v1.9.15. A related issue is the entire player freezes when seeking from an HDD that takes about 10 seconds to spin-up, especially problematic when in full screen.

Also using D3D11 decoder and madVR. Maybe buffers need to be flushed?

**Comment by clsid2** [comment]
You can press Ctrl+E to completely reload the file.

D3D11 + madVR doesn't work well on some systems. The problem seems to be in madVR. Maybe triggered by certain settings or driver combo. Did you change any non-scaling related settings in madVR, such as buffer sizes?

**Comment by clsid2** [comment]
1.9.16.51 does an automatic file reload after long pause. It resumes at current position.

**Comment by MD-78** [comment]
I also have these hangs but only with MPC Video Renderer
