### ISSUE TITLE
Small/simple feature request: change and save the default location where you quickly open the files

### ISSUE THREAD

**Issue by Felipefpl** [clsid2/mpc-hc#1289]
When you make MPC open a file it always starts in the documents folder of the library section, the C:\ would be a better choice and it would be even better if we could choose a default location ourselves and keep this location saved in the registry/.ini file.

**Comment by clsid2** [comment]
It already remembers the last used folder. If it resets to default folder it means the last folder probably doesn't exist anymore.

I am not going to add another option.

Use Winkey+E to open Explorer if you want to quickly navigate to a favorite folder.

**Comment by Felipefpl** [comment]
> It already remembers the last used folder. If it resets to default folder it means the last folder probably doesn't exist anymore.

The folder used is NEVER deleted, the option isnt saved.

**Comment by clsid2** [comment]
Then do this:
Menu > File > Open File

The Open: dropdown menu contains recently opened files. If you select a file and then click the browse button, it will open the folder that contained that file.

If it doesn't work, then you might have disabled the option to remember file history.

**Comment by Felipefpl** [comment]
Ccleaner removed the saved folder in the file history, indeed it isnt mpc's fault but it'd be good to have an option that couldnt be deleted like this. ;)

**Comment by ale5000-git** [comment]
CCleaner on purposely remove it as like the last saved folder on Internet Explorer for example, it is to avoid leave trace on the PC of what you do.
If it isn't what you want or you didn't know it maybe you musn't use CCleaner.

PS: I didn't mean to be harsh, it is just that doing thing without know the details can cause damage.
