### ISSUE TITLE
Crash on playback -- Issue with RTSS: Riva Tuner Statistics Server

### ISSUE THREAD

**Issue by Irfy** [clsid2/mpc-hc#129]
*I am reporting this issue as a guide for others that may encounter it. The issue is not with MPC-HC, but with another utility, however the only symptom is that MPC-HC crashes all the time*

I have the 64-bit MPC-HC v1.8.7 installed as part of K-Lite Mega Codec Pack. Recently it crashes on any playback attempt. Windows Event Viewer reports a null-pointer access violation.

After some digging i caught the exception with WinDbg and looked at the call stack, finding `RTSSHooks64` and friends at the top. Some googling indicated that this function is part of the *Riva Tuner Statistics Server* (installed version: 7.2.2) bundled with *MSI Afterburner* (installed version: 4.5.0).

Setting the RTSS application profile for the MPC-HC executable to *Application Detection Level: None* or enabling *Custom Direct3D support* fixes the issue. Currently, the latest beta version of the software (7.2.3b2 and 4.6.2b respectively) still exhibit the issue and require the fix above.

**Comment by clsid2** [comment]
RivaTuner Statistics Server 7.2.3 is available and it should solve the problem.

**Comment by Irfy** [comment]
I can confirm that the problem is gone with 7.2.3.

However, the final 7.2.3 version is --ironically-- far more buggy for me than 7.2.3 Beta 2, and it took several system restarts and full antivirus-disabling for it to load properly so that I can test it. I ended up reverting to the version I had previously installed, and simply continued using the workaround I reported in my original post.
