### ISSUE TITLE
[Regression] Using frame step forward causes stutters

### ISSUE THREAD

**Issue by Ryuji12** [clsid2/mpc-hc#1293]
Whenever using frame step forward for some seconds the player as well as the video looks like it just hung for the same amount of seconds the frame step button was held. This did not happened before 16.4.0 update.

**Comment by clsid2** [comment]
You need to explain better what happens. Do you mean it hangs after resuming playback?

Which audio and video renderer is used?
(Options > Playback > Output)

**Comment by Ryuji12** [comment]
No, it hangs for the same amount of seconds as the frame step button was held after which it works normally. If during the hang time I press the mouse nothing happens. Alt tab does not work either. If I use the frame step when the playback goes on, it feels just like when the fps drop in a game to 0 and then back up.

Video renderer: madvr
audio renderer: system default

**Comment by clsid2** [comment]
Found the problem. Will be fixed soon.
