### ISSUE TITLE
Misaligned text in command line help dialog

### ISSUE THREAD

**Issue by cw2** [clsid2/mpc-hc#1294]
I have noticed there is a misaligned 'Hibernate' command description in the **Command line help** dialog:

![cmdline-hibernate](https://user-images.githubusercontent.com/10730406/132467871-e86c3999-409d-4a39-b179-80d3076a6c3b.png)

There is a missing tab delimiter; I have fix already in progress.

_Tip for an improvement: Add "Copy to clipboard" button (?) Although it is possible to "Select All" and "Copy" in the edit context menu..._

**Comment by clsid2** [comment]
You also need to fix any affected translations (*.po) to make the same chance to the English string.
