### ISSUE TITLE
[Feature request] Subtitle options: Letter spacing, border width, shadow depth...

### ISSUE THREAD

**Issue by pqsmmobile** [clsid2/mpc-hc#1295]
![LOdqiewN_o](https://user-images.githubusercontent.com/80322801/132505095-c198cfed-7162-4266-970c-44c3cbcf89ab.jpg)

**Comment by NanaMizukiAnother7** [comment]
It's already there!

**Comment by pqsmmobile** [comment]
> 
> 
> It's already there!

Where exactly are these settings? Cause for now those settings are only present in MPC-BE? The steps are +1, there is no fine tuning.

**Comment by ale5000-git** [comment]
Have you tried in the options? :)
![options](https://user-images.githubusercontent.com/15793015/133390758-38eb0086-0b12-4605-ab01-e36752920be2.png)

**Comment by pqsmmobile** [comment]
> 
> 
> Have you tried in the options? :)
> ![options](https://user-images.githubusercontent.com/15793015/133390758-38eb0086-0b12-4605-ab01-e36752920be2.png)

Can you actually set Width/Shadow to 0.4 for example?

**Comment by ale5000-git** [comment]
Your ticket is misleading and make it seem the features aren't supported at all.
You should have simply said, for example: 

> Could you please add decimal support to letter spacing, border width and shadow depth options of subtitles?
