### ISSUE TITLE
Question about Chocolatey Package

### ISSUE THREAD

**Issue by gep13** [clsid2/mpc-hc#13]
I have a quick question..

You may or may not know what Chocolatey is, but we have had a question over there about the currently Chocolatey package for MPC-HC (https://chocolatey.org/packages/mpc-hc).  Chocolatey allows the installation of this software application by simply using the command `choco install mpc-hc`.  Now, the question that we have had is about your fork of the MPC-HC application.  Would you consider your fork as being known as a different name?  Or is it still the same application?

The reason that I ask is that we have been asked to try to push the new releases of your fork to the Chocolatey package id of `mpc-hc`, however, your application is a fork, so I am not clear or whether this is the correct course of action, even though you have continued the versioning numbering in your fork.

My concern is that if the original mpc-hc application starts development again, and in the meantime we have pushed the new versions of your fork to the same package id, then there would be a conflict.

I would love to hear your thoughts on this matter.  Thanks in advance!

**Comment by gep13** [comment]
@clsid2 thanks for getting back to me.  In which case, I think I am inclined to allow pushing additional package versions to the same package id on Chocolatey.org.

Side Question: I am just curious about the history of how this fork got started.  Was there an effort to get the current admins/owners of the existing repository to give you access to the project directly to continue to do the work you are doing there, rather than having this active fork?  Just curious, and I apologise if this has been asked/answered elsewhere.

**Comment by clsid2** [comment]
They pretty much just lost interest in the project and only wanted to continue if there were multiple active developers.

**Comment by gep13** [comment]
> @clsid2 said...
They pretty much just lost interest in the project and only wanted to continue if there were multiple active developers.

That is a real shame, and results in dilution of the eco-system.  

I applaud you for doing what you are doing though, it seems as though people are getting a great benefit from what you are doing. 👍
