### ISSUE TITLE
voices being drowned when music/effects get louder

### ISSUE THREAD

**Issue by yepyepyep4711** [clsid2/mpc-hc#130]
Hello everyone,

I see the issue that when the general loudness picks up, the voices will noticeably sound quieter, instead of keeping up with general loudness. I'm having a hard time pinning it on an audio format or a setting. I'm trying to find out if it's an encoding or decoding problem. Any help would be appreciated.

Cheers
Version is 1.8.7

**Comment by clsid2** [comment]
In the audio decoder settings, enable Mixer and set it to Stereo. Also set "Center mix level" to 1.0 to increase the volume of voices.

**Comment by yepyepyep4711** [comment]
hey, thanks, but I had this set already. I've checked, these controls work as advertised, so it's not a software problem. It seems the dynamic correction is too drastic, but that I guess that happened during encoding :(

**Comment by clsid2** [comment]
It doesn't do any dynamic adjustments. At least not unless you have enabled volume normalization. So something may be wrong in your Windows sound settings.
