### ISSUE TITLE
MPC Audio Renderer

### ISSUE THREAD

**Issue by fcuk02** [clsid2/mpc-hc#1303]
Only 48kHz 2ch files has sound
44.1 and 96kHz need Exclusive mode

**Comment by clsid2** [comment]
Works fine for me.

**Comment by clsid2** [comment]
@adipose

**Comment by clsid2** [comment]
Might be an issue with resampling in the renderer. Silence happens when input is 44100Hz and output is 48000.

**Comment by Aleksoid1978** [comment]
Resampler working. Maybe some "bug" using ffmpeg, maybe linking or you don't enable swresample.

**Comment by clsid2** [comment]
swresample is enabled. I think soxr isn't fully enabled in our ffmpeg.

**Comment by clsid2** [comment]
Fixed
