### ISSUE TITLE
/File/Recent Files List Edit

### ISSUE THREAD

**Issue by Bliickie** [clsid2/mpc-hc#1305]
Any thought to adding the capability to Edit the Recent Files List to remove a Recent File String?  On the Leading or Trailing part of the line, add a Trash Can Symbol that when selected, removes the file from the Recent File List.

Thanks

**Comment by clsid2** [comment]
I am not interested in adding such functionality.

**Comment by cw2** [comment]
Hm, I don't think there is a direct support for such functionality in Win32 menus, resp. the notification sent after user selects a menu item does not include mouse coordinates needed to determine what exactly was clicked on; it would require custom menu implementation...

However, what could be done relatively easily is for example adding a new menu command "Clear invalid items" (similar to "Clear list" but remove only entries whose files do not exist anymore) and/or removing recent file entry with invalid/non-existing file after selection (perhaps with a confirmation message like "File does not exist, remove entry from the list?" Yes/No/Cancel).

**Comment by ale5000-git** [comment]
I think the only way to add it properly is to add another window to organize them (like Favorites => Organize Favorites...).

**Comment by clsid2** [comment]
It is probably to hide traces of watching pr0n...
