### ISSUE TITLE
[Feature Suggestion] Show Subtitle Status in Status Bar if Subtitles are Off When Advanced Option is On

### ISSUE THREAD

**Issue by MadokaAyukawa** [clsid2/mpc-hc#1306]
Currently if HC is set to show subtitles in the status bar, and subtitles are turned off, say with the hot key, the status bar will not show the SUB: section. If one didn't realize subtitles were off, this can look as if there are no subtitles available. It would be helpful if instead of not showing up in the status bar, it would say SUB: off instead.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2701
