### ISSUE TITLE
Conspicuous Data Usage

### ISSUE THREAD

**Issue by DrHilarious** [clsid2/mpc-hc#131]
I have noticed substantial data usage for an application that does not update itself and I use only to watch local content. What could be the cause of this issue?

![mpc-hc_high_data_usage](https://user-images.githubusercontent.com/633083/65388691-f40b2900-dd13-11e9-9331-ffeedb0dc239.png)

**Comment by clsid2** [comment]
The player itself only connects to Internet if you enable its subtitle download option.

**Comment by DrHilarious** [comment]
I disabled that feature some time ago. I have reset my data usage statistics. Thank you.
