### ISSUE TITLE
No audio output on sampling frequency 384kHz

### ISSUE THREAD

**Issue by TheDarkDnKTv** [clsid2/mpc-hc#1311]
I installed new audiocard in my PC and notest I have no sound playing any video/audio with different codecs.
I have audio in any other places (browser, other players, games) but not in MPC

Audio settings: 32bit 384kHz output (tried 16/24 bits also)
OS: Windows 10 20H2 x64
Audio card: Creative Sound BlasterX AE-5

**Comment by NanaMizukiAnother7** [comment]
Can you please use MPC Audio Renderer?

**Comment by clsid2** [comment]
Enable the internal audio renderer. The standard DirectSound renderer does not support more than 192kHz.
