### ISSUE TITLE
uTorrent Stream URL opens through youtube-dl first

### ISSUE THREAD

**Issue by Molkree** [clsid2/mpc-hc#1316]
I've added youtube-dl (just dropped .exe in the Windows folder) today and it worked fine through MPC-HC. However, when I tried playing a video file that's still being downloaded through uTorrent, I get an error from youtube-dl first.

Step by step:
1. Right-click video file in uTorrent -> Copy Stream URL
2. In MPC-HC Ctrl+O, paste the URL and play.
3. At the bottom of the window I see "Calling youtube-dl..." and then this error:
![image](https://user-images.githubusercontent.com/12860284/134223482-f3acffe3-8247-4b15-a0eb-36a89b502612.png)
4. After clicking OK on error, file opens and plays just fine.

So the question is, is it possible to avoid calling youtube-dl for such links?

**Comment by clsid2** [comment]
How does that URL look like?

**Comment by Molkree** [comment]
http://pairing:A6235D9ED132CB5D6234D235B76D229A40EA0254@127.0.0.1:63066/proxy?sid=ab671f7c&file=0&token=A6235D9ED132CB5D6234D235B76D229A40EA0254&pairing=A6235D9ED132CB5D6234D235B76D229A40EA0254&service=STREAMING

**Comment by clsid2** [comment]
Fixed
