### ISSUE TITLE
Choppy video when playing any "x265" (HEVC/H.265) format video

### ISSUE THREAD

**Issue by dftf-stu** [clsid2/mpc-hc#1317]
Hi all

If I download an "x264" format video (AVC/H.264), my computer can play the video without issue.

However, with any "x265" (HEVC/H.265) format video, the audio playback is normal, but the video constantly skips-frames (it plays-back at around half the framerate).  I have also tried such files in the latest _VLC Media Player_, which exhibits the same issue.

From an example file, these are the properties:

> **Video Properties -> Details tab:**
> Video: HVC1 1920x1080 23.976fps (hevc main 10 L4.0, yuv420p10le, 1920x1080)
> Audio: Dolby AC3 48000Hz 6ch 640kbps (ac3, 48000 Hz, 5.1, 640 kb/s)
> 
> **Video Properties -> MediaInfo tab:**
> Format                         : Matroska
> Format version                 : Version 4
> Overall bit rate               : 2 643 kb/s
> Writing application            : Lavf58.20.100
> Writing library                : Lavf58.20.100
> ErrorDetectionType             : Per level 1
> 
> Video
> Format                         : HEVC
> Format/Info                    : High Efficiency Video Coding
> Format profile                 : Main 10@L4@Main
> Codec ID                       : V_MPEGH/ISO/HEVC
> Bit rate                       : 2 000 kb/s
> Frame rate mode                : Constant
> Frame rate                     : 23.976 (24000/1001) FPS
> Color space                    : YUV
> Chroma subsampling             : 4:2:0
> Bit depth                      : 10 bits
> Bits/(Pixel*Frame)             : 0.040
> Writing library                : x265 3.3+4-rarbg-30eb4de83092:[Linux][GCC 8.3.1][64 bit] 10bit
> Color range                    : Limited
> 

Are such files only playable on newer PCs -- I'm guessing either the CPU needs some instruction mine is missing (5th-gen Intel Core i7), or the format requires a GPU where it can natively decode the format, or at-least the GPU's driver provides support?

Otherwise, if such video-files should work, are there any settings within Windows 10, or the MPC-HC app, I can check?

I've already gone to Start > Settings > System > Display > Graphics Settings and have ensured the "mpc-hc64.exe" executable is set to run on my system's discreet GPU ("High performance") and not the CPU-integrated GPU ("Power saving").

So... should I expect such files to work, or is a newer-spec system required?

Thanks

**Comment by clsid2** [comment]
You either need a faster CPU or a GPU that supports hardware acceleration of HEVC video.

Your integrated GPU supports partial acceleration of 8-bit HEVC. However, this video is 10-bit, which it doesn't support.

Modern hardware can play this file without problems.

**Comment by butterw** [comment]
Disable hardware acceleration for (10 bit) hevc and this type of file should play fine using cpu (works fine on 4th gen celeron @1080p) .
  
You need at least intel UHD graphics igpu (8th gen intel) for hw-dec of 10bit hevc.
 
EDIT: This type of problem is typically encountered when playing (high bitrate) 4K hevc on igpus before gen8 (or on some old nvidia gpus) with only partial hardware decoding support for it (gpu load maxed out at 100%).

**Comment by dftf-stu** [comment]
I wish this ticket hadn't been closed as I've not had chance yet to reply!

@butterw Can you explain what I'm supposed to do please to disable hardware-acceleration, as I'm unclear.  I'm guessing either I have to go to View > Options... > Playback > Output and change something there, or go to the "Internal Filters" category then click the [Video decoder] button and change something there?

It would be nice to have some sort-of step-by-step before closing the ticket, as the app has so-many settings it's confusing to know what I should be altering.

Also, just out of interest: if you need an 8th-gen Intel CPU (or AMD equivalent) or above for hardware-decoding of 10-bit HVEC, and the answer is to dropback to CPU-only rendering on 7th-gen or lower... is there a reason MPC-HC doesn't make the setting change automatically when it detects it is running on a CPU that doesn't offer the support?  Were it to do so, I'd likely never have needed to raise this ticket to begin with...

**Comment by clsid2** [comment]
Options > Internal Filters > Video Decoder

Automatic configuration is a complex task. The player installer doesn't do that. If you want such functionality, you should install K-Lite Codec Pack. That includes MPC-HC and does automatic configuration based on the GPUs detected during its installation.

**Comment by dftf-stu** [comment]
@clsid2 Sorry, but I still don't understand what settings I'm supposed to be adjusting!

![MPC-HC_VideoSettingsDialog](https://user-images.githubusercontent.com/83965343/134370411-96fd3680-74f7-48dd-b284-da816f3b7114.png)

I first went into the "Video Decoder" button dialog and un-ticked "HEVC" in the "Codecs for HW Decoding" group, then closed the app and tried the video again.  But it still runs at around half the framerate.

So I then un-ticked both "HD" and "UHD (4K)" which I assume means no hardware-decoding for any video that is in one of those resolutions, regardless of format.  Again, closed the app fully and opened my video-file again and have the same issue.

Is it possible perhaps for @butterw to explain what they did please, as they say on a CPU generation older than mine it was working fine for them, but I can't make it work for me... and I'm still unsure exactly what I'm supposed to be altering

**Comment by dftf-stu** [comment]
Am I supposed to untick all of the "10-bit" options in the "Output Formats" group -- is that it?

**Comment by clsid2** [comment]
Press Ctrl+Shift+Esc to open the Windows Task Manager. Look at the CPU usage. If that is near 100% then your CPU is simply too slow.

He has a totally different CPU, and probably a desktop CPU, which are generally more powerful than a laptop CPU. So the claim that you should be able to play the file is based on absolutely no valid facts.

**Comment by dftf-stu** [comment]
The CPU use (which is a laptop one) hovers at around 25-30% only.

My CPU is 2 core, 4 thread so I'm guessing the app is only using a single thread to decode?

I have tried both changing the "Hardware Decoder to use" dropdown to "None", which made no difference, and also tried changing it to "D3D11", and then testing on both my CPU-integrated GPU, and my discreet AMD GPU, but again, no difference.

I'm puzzled why a 4th-gen Celeron would be able to run at full-speed, but not a Core i7 5th-Gen, even if one is desktop and one mobile... surely the Core i7 should still be more-powerful overall?

But I fear the only answer is for me to simply not download any videos in that format in-future, as I cannot see how to make them work

**Comment by clsid2** [comment]
What is shown under:
Menu > Play > Filters

**Comment by dftf-stu** [comment]
The following options:
> Copy filters list to clipboard
> Default DirectSound device
> Enhanced Video Renderer (custom presenter)
> Audio Switcher ->
> LAV Video Decoder (internal)
> LAV Audio Decoder (internal)
> LAV Splitter Source (internal) ->

**Comment by dftf-stu** [comment]
If it helps, this is a typical output from Task Manager while the HEVC-format video was running full-screen in MPC-HC.

![TaskManagerWhileHEVCRunning](https://user-images.githubusercontent.com/83965343/134377941-f05b6033-946a-4694-acad-174d963d94f5.png)

CPU use on-average is around 25%, and fluctuates between around 20% and 30%, but never higher.
No other apps were running.

**Comment by dftf-stu** [comment]
HEVC-format decoding appears to be single-thread only -- at-least, it's not listed as supported in this ScreenTip:
![HEVCSingleThreadOnly](https://user-images.githubusercontent.com/83965343/134378754-0298307d-ac4c-434c-b620-d8ec004cfc67.png)

So maybe my CPU just can't cope?  Though it does seem odd an older _Celeron_ apparently can, but an i7 cannot.

**Comment by clsid2** [comment]
HEVC is also multi-threaded. You can manually set the thread count, but I doubt it will help.

Your CPU is just too slow.

**Comment by dftf-stu** [comment]
@clsid2 I've just downloaded a "x264" format-video as a test.

The properties of the video are given as:
> Video: MPEG4 Video (H264) 1280x720 25fps [V: h264 main L3.1, yuv420p, 1280x720 [default]]
> Audio: AAC 48000Hz stereo [A: aac lc, 48000 Hz, stereo [default]]

When I play that video, CPU-use is around 15%, and rarely moves up past that.

However, given that the ScreenTip for "Threads for Multi Threading" clearly says H264 is a supported format, it's odd it's also using only a single-thread.  (I did try altering the dropdown from "Auto" to "2", and also to "4", closing the app between each test but CPU use still never goes-past 15% for that video -- though the framerate is fine).

So to me it seems like the issue is that the app doesn't seem to be able to use more than one thread for the CPU in my system -- and I've no-idea why this would be.  I've changed barely any settings from the defaults since first using it

**Comment by clsid2** [comment]
The app uses multiple threads just fine. It never goes past 15% because there is not more work to do for that file. Increase playback speed rate if you want to increase load as a test.

The CPU might not work at full performance due to thermal throttling or some other system issue. I can't help you with that.

You may need to enable High Performance power plan as well in Windows.

**Comment by dftf-stu** [comment]
Okay, problem solved.

I have tried looking at a number of articles for MPC-HC and VLC 3.0.x series, both of which have the same poor-framerate when playing back these 10-bit, HEVC format videos.  Whatever I tried, nothing seems to work.

But I noticed in a number of forums others saying they too have the same issue with both players, but to download the "nightly" ZIP file for the new VLC Media Player 4.x series, which I have.  I dragged the video over the "vlc.exe" executable to start it playing and amazingly perfect framerate at around 25-30% CPU use.

So not sure what is different between VLC 3.0.x series and MPC-HC and the new VLC 4.x series, but it's worked for me just on the default settings that come with it!

So thanks for your help here, but I'll just run such videos in VLC 4.x instead of trying to troubleshoot MPC-HC further

**Comment by butterw** [comment]
With a desktop Celeron (G1840, no hevc-dec, no avx2) the cpu load is less than 1 core. 

The lav video decoder threading option doesn't list h265, so it might not support multithreading with hevc, which would be a problem if single core perf is weak.

**Comment by dftf-stu** [comment]
@butterw If you could perhaps share a screenshot of what settings you changed, that might help.

According to the "CPU-Z" utility, my processor supports the following:
> MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, AES, AVX, AVX2, FMA3, TSX

I have tried all-sorts of things inside the MPC-HC app:
- Trying different "Hardware Decoder" options ("DXVA2 (native)", "DXVA2 (copy back)", "D3D11" and "None")
- Un-ticking the "HD" and "UHD (4K)" options, and the "HEVC" option
- Going to Start > Settings > Display > Graphics Settings and testing both my integrated and discreet GPU
- Changing the "Threads for Multi Threading" dropdown to "2" or "4"
- Un-ticking all the "10-bit" options in the "Output Formats" area
And nothing has worked -- if you can offer anything-else I could try, go-ahead.

But for now I have visited https://artifacts.videolan.org/vlc/nightly-win64/ and downloaded the latest "vlc-4.0.0-dev-win64-cc9d9444.zip" file, extracted it and then dragged my video-file over the main "vlc.exe" executable and the video plays there at full-framerate, averaging around 25% CPU.

So I'm not sure why MPC-HC is unable to play the file at full-speed on the same system.  My guess is that for whatever reason it is not able to use more than one thread of my CPU, as while the video is playing, Task Manager reports the CPU-use never goes above 25%.  If it was able to, it would likely then work at full framerate.  But VLC 4.x is able to do full framerate even within the same limits (using 1 thread only) as MPC-HC.

So clearly they've done something in their code that makes it work-better on older CPUs...

**Comment by dftf-stu** [comment]
@butterw If you want to compare CPUs, to see if you can spot anything mine might lack...

Here is your CPU:
https://ark.intel.com/content/www/us/en/ark/products/80800/intel-celeron-processor-g1840-2m-cache-2-80-ghz.html
And here is my CPU:
https://ark.intel.com/content/www/us/en/ark/products/85215/intel-core-i7-5600u-processor-4m-cache-up-to-3-20-ghz.html

**Comment by the-marox** [comment]
I have the same problem but with an AMD 5800H CPU and RTX3060 GPU. sh265 video is not hardware decoded and some high-bitrate are stuttering
