### ISSUE TITLE
Weird Subtitles Issue:

### ISSUE THREAD

**Issue by LucianAndries** [clsid2/mpc-hc#1319]
Hello!

Dunno if anyone reported this yet, but I discovered one of the most random issues.........

It's about the embedded(?) subtitles in the container.
The issue is like this: If there are TONS of subs in the container, that fills up the entire display vertically, MPC can not scroll that list to see all of them. Let alone get to the bottom of the list to choose the "No subtitles" option.......
The issue happened because I have a 1080p TV. If it were 4K maybe the list would have had fit. Maybe...

I know, this was 1 in 500 chances... But, it would not hurt to have those lists scrollable. Either by scroll wheel or arrow buttons on the lists themselves. Of course, the arrows would only appear when/if the lists are retarded packed until they fill up the entire tv/monitor screen.

By "lists" I mean both Audio Track and Subtitle Track lists.

Also, if by any chance this scroll feature already exists, then it was not working on version 1.9.15.x64.
Now I don't have that movie anymore, to test version 1.9.16.x64 as well...

PS: I hope you can understand what the issue was, because I forgot to take a screenshot of it.
But here is a visual explanation anyway: https://imgur.com/a/6tjLCIt

Thank you for your time!

Oof, I forgot... Can I ask you something?
Is there any Audio option/setting to Normalize the Audio Tracks? Something like "Loudness Equalization". If yes, then I'm dumb and can't find it.
But if not, then can one be added, and somehow make it work on "Bitstreaming" as well? Because my AVR doesn't care about this... The only option for Dynamic Sounds is Standard, and that implies "play soundtrack as is"................ And every god damn movie has every sound and voice at 1% volume, and music and explosions at 150% volume. Why???! Dumb holywood sound directors, or what they're called..........!

Thank you again!

**Comment by clsid2** [comment]
Volume normalize option is in the audio switcher options page. It is not possible to modify volume when bitstreaming. If you use HDMI, then just disable bitstreaming.

I can't do anything about the sub problem without a sample file.

**Comment by LucianAndries** [comment]
Bummer with bitstreaming.

A sample file? The only thing I can do is mux you a very small mkv file, and put 100 subs in it. It is literally the exact same thing. You can do it yourself too, but if you want me to do it I don't mind.

**Comment by clsid2** [comment]
I am not going to spend time to make such a file. I have better things to do.

Normally a super large menu can be scrolled by holding your mouse pointer at the bottom of it. There should be a tiny triangle shaped arrow to put your mouse pointer on.

The internal splitter has options to specify your preferred language(s). Then it should automatically select the correct subtitle track.

**Comment by LucianAndries** [comment]
Yeah, the thing you said, did not work. No arrows, no nothing.
I know about preferred languages! Only that time I wanted to select No Subtitles and I couldn't, for said reasons.

Ok, I will make you a file, don't need to get angry. I said it because it is a very easy thing to do.
Ok, brb...

**Comment by LucianAndries** [comment]
Hmm, this version seems to be working fine. It has those arrows.
But the previous version did not. That or maybe the file was broken? But that doesn't make any sense..

Either way, here's the new screenshot..................
![Untitled](https://user-images.githubusercontent.com/59364663/134388561-ba6ae0eb-9e21-4e18-abb3-760f5bc7ceb4.png)
.

**Comment by clsid2** [comment]
You probably just didn't notice the arrow before. It is easy to overlook when expecting a scrollbar.

**Comment by LucianAndries** [comment]
Probably. Oh well, thank you anyway. :)
