### ISSUE TITLE
yt-dlp fails

### ISSUE THREAD

**Issue by MDM-79** [clsid2/mpc-hc#1320]
In latest 1.9.16 (no mater if the path/file name is specified or not, or where the file is) it does not work with yt-dlp.exe
This is the error I get:
![Screenshot 2021-09-23 025343 PNG](https://user-images.githubusercontent.com/87946426/134440592-a1c1445a-ca28-4aa1-974a-872b212212f6.jpg)

**Comment by clsid2** [comment]
Works fine for me.

The error is in yt_dlp itself, so you have to go there for help.

**Comment by MDM-79** [comment]
OK, will do so!

Anyway **_how_** does it work for you? I tried even their x86 file, full or short YT address, file in MPC folder or not, name only, full path... - not once it worked! Do I do something wrong? Do I need a line preface before the address?
It woks just fine with youtube-dl tho.
Sorry for the bother, and probably stupid question...

**Comment by clsid2** [comment]
The fact that you see that error message means that MPC is already using it! So that part is working for you.

The bug in in yt_dlp and is completely unrelated to MPC.

**Comment by MDM-79** [comment]
Thank for you answer; I get it now what you meant by "work", am writing a new issue there right now.
