### ISSUE TITLE
Add chords as a keybinding method

### ISSUE THREAD

**Issue by eugenesvk** [clsid2/mpc-hc#1321]
Thanks a lot for keeping this awesome video player alive! I'd like to propose a feature that would make it more manageable despite all the configuration complexity

Given the multitude of various video options configurable it's a challenge to have (and remember!) a convenient set of keybinds.
One excellent way to avoid a lot of complexity would be to allow __chords__ — a sequence of keys to be pressed one after another rather than a set of keys to be pressed at the same time — as keybinds

For example, currently there are __8__ options in the `View→Video Frame` menu (~Half/Normal/Double/Stretch/TouchIn/Zoom1/Zoom2/TouchOut), so it's hard to find and remember 8 keybinds for them all (or even 3-4 for the ones you could use), but with chords it'd be trivial:
- you press <kbd>f</kbd> to "enter" the `frame` keybinding state
- you then press easy to remember keys, e.g. 
  + <kbd>h</kbd> for `Half Size`
  + <kbd>n</kbd> for `Normal size`
  + etc.
- (if you don't press anything after <kbd>f</kbd>, then a non-chord <kbd>f</kbd> keybind is executed)

Ideally you could even have a helper tool that would show you those 8 keybinds/options once you press <kbd>f</kbd>, but even without it it's already much simpler

**Comment by clsid2** [comment]
I am not interested in implementing that.
