### ISSUE TITLE
It load 2 streams where both have audio and video

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#1323]
Sample: https://www.wittytv.it/temptation-island/prima-puntata-mercoledi-30-giugno/

I'm not sure if the bug is in MPC-HC, LAVFilters or yt-dlp but instead of loading 1 stream for audio + 1 stream for video (or 1 with both) it loads in 2 streams where both have audio and video.

**Comment by clsid2** [comment]
Problem was that for dash manifests, each individual audio and video streams has its own entry in the formats list.

Fixed now by checking formats list for matching audio entry.
