### ISSUE TITLE
Show duration in playlist immediately on adding files

### ISSUE THREAD

**Issue by demovirus** [clsid2/mpc-hc#1324]
When I drag files in playlist I want to see durations of all of them. Now I need to start each file to see durations. It's very inconvenient. Please show durations on adding files

**Comment by clsid2** [comment]
Determining the duration requires parsing each file. That can introduce a large delay when adding many files to playlist.

I am not going to implement this.

**Comment by demovirus** [comment]
Why don't you make it optional?
I don't think users often add too many files to playlist. I checked VLC and loaded 474 files of 39GB and it took 22 seconds to calculate. It's not much for such count of files. I usually add not more 20 files and I need to see all durations. I had to start each file to see. It's annoying to do it.

**Comment by maipoohsmelsFUnny** [comment]
I, too, would appreciate if this feature were to be implemented, as well.

**Comment by I-Megaman-I** [comment]
+1
