### ISSUE TITLE
[Feature request] Safezone above and below seekbar as option (enable/disable)

### ISSUE THREAD

**Issue by bouhpwet** [clsid2/mpc-hc#1325]
Hello,
Could you please make the safezone introduced in version 1.9.14 an option ? I.e. I would really appreciate to be able to turn it off. When using MPC-HC, the safezone proves to be a bit annoying.
Many thanks in advance for your consideration.

**Comment by clsid2** [comment]
It is just a small area, so I don't see how it can cause any big issues.

I am not adding an option unless a significant amount of people need it.
