### ISSUE TITLE
MPC-HC & Twitch ads

### ISSUE THREAD

**Issue by reallyuniquename** [clsid2/mpc-hc#1326]
## Description

Twitch has a system that embeds ad segments directly into an M3U playlist. It doesn't contain actual ad streams but you get placeholder segments lasting as long as ads would. Pre-roll ads play right after you start viewing a live stream. They usually take about 15 seconds to finish. Mid-roll ads can take up to a few minutes. Both prevent you from getting actual stream content. This is how it looks. 

<img src="https://user-images.githubusercontent.com/10516120/134771151-14d89f62-cd70-4eac-83af-61cf3d6fb20e.png" width="300">

As of right now Twitch does this only to live streams or reruns. 

## How other apps solve this

There are well known tools that successfully deal with Twitch ads. My understanding is it involves stripping/filtering/skipping ad segments from an M3U based on their `#` comments. At worst you get a few seconds gaps in a stream but you don't get full length ads either.

For example streamlink has a feature [--twitch-disable-ads](https://streamlink.github.io/cli.html#cmdoption-twitch-disable-ads).
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/twitch.py#L39
```python
        is_ad = (
            daterange.classname == "twitch-stitched-ad"
            or str(daterange.id or "").startswith("stitched-ad-")
            or any(attr_key.startswith("X-TV-TWITCH-AD-") for attr_key in daterange.x.keys())
        )
```
And this is how one of the uBlock Origin [filter](https://www.fanboy.co.nz/fanboy-problematic-sites.txt) lists does it with web based player.
```
twitch.tv##+js(json-prune, /^X-TV-TWITCH-AD/)
...
```
### Pre-roll ads

1. Go to https://www.twitch.tv/directory/all
2. Pick any popular live streamer
3. Open URL through MPC-HC
4. Verify that stream starts with an ad segment

### Mid-roll ads

Same as above but you would have to wait up to half an hour for ads to appear.

## Things to consider

Obviously asking for a fully fledged ad blocker in MPC-HC is absurd. But if I remember correctly you implemented some Twitch specific fixes related to M3U parsing so there should be some kind of M3U preprocessor. How complicated would it be to just skip segments based on substrings?

**Comment by clsid2** [comment]
Streaming playlist are handled directly by LAV Splitter. The player doesn't parse it and thus can't manipulate it.

**Comment by reallyuniquename** [comment]
That's unfortunate. I just rechecked #560 and it turns out that fix did the opposite of what I thought. I expected it would be a good entry point to strip ads.

Well another option is to feed already cleaned up stream to MPC-HC. That requires support for `streamlink --twitch-disable-ads --stdout` and most importantly reading from `stdin`. Does this look feasible?

Originally I've been thinking about running some external M3U parser acting as a proxy. But then it should either be natively supported by MPC-HC or masquerade as youtube-dl.

**Comment by clsid2** [comment]
I should already be compatible with Streamlink:
https://streamlink.github.io/players.html

**Comment by reallyuniquename** [comment]
True. What I meant is a proper integration the same way youtube-dl is supported plus reading from its stdout, e.g. favorites, correct window title, recent files, etc.

I believe yt-dlp would catch up on ad blocking so eventually we'll hit the same issue there.

**Comment by clsid2** [comment]
I am not interested in implementing such functionality, or any other new functionality.

**Comment by ale5000-git** [comment]
@reallyuniquename: yt-dlp (the successor of youtube-dl) probably already has something similar although I haven't tried.

**Comment by reallyuniquename** [comment]
@clsid2 Alright. Is some kind of advanced option to read from youtube-dl stdout when it's launched through MPC-HC UI out of the question too?

@ale5000-git Unfortunately they don't and even if they did there would be the same problem with integration. Besides, outdated youtube-dl has a better Twitch support for some use cases.

**Comment by clsid2** [comment]
That requires big changes. So no.

**Comment by ale5000-git** [comment]
@reallyuniquename: youtube-dl seems died (at least for now), if you have any problem with Twitch (using yt-dlp), then I suggest reporting to them.
