### ISSUE TITLE
Automatic Playback on MPC-HC Open

### ISSUE THREAD

**Issue by maipoohsmelsFUnny** [clsid2/mpc-hc#1328]
Starting with v1.9.16, MPC-HC now begins automatic playback of any files that were in the playlist on last close and, as far as I can tell, there is no option to prevent this from happening. I don't see any mention of this in the release notes. Is this behavior intentional? Can an option be implemented such that this behavior can be reverted back to how it was in v1.9.15? Thanks for your attention on this.

**Comment by clsid2** [comment]
It isn't automatic. You are probably clicking on the video area.

**Comment by btu1398** [comment]
I'm not sure if OP is saying the same thing as what I am seeing, but when I start a video, it no longer starts at the start but starts where I left off, and I don't see a setting to prevent that from happening.  When I add a video to my playlist and it has multiple audio/subtitle sources, I will skip ahead and make sure it's using the audio and subtitle languages I want it to use.  Now, when it actually reaches that file in the playlist, it starts playing from where I skipped ahead to.

I'm not sure what version I started seeing this in.  My Windows drive died last week and I've been trying to get everything all set back up correctly.

**Comment by ale5000-git** [comment]
The option always existed: Options => Player => Remember File position

**Comment by btu1398** [comment]
I keep forgetting the category has its own settings.  Thanks.  I don't remember it being enabled by default previously...

**Comment by AhEhIhOhU** [comment]
> I keep forgetting the category has its own settings.

If it can reassure you, you are not the only one x)



>  I don't remember it being enabled by default previously...

You are probably using K-Lite Codec Pack, this was modified on 2021-09-03: https://codecguide.com/changelogs_standard.htm

**Comment by maipoohsmelsFUnny** [comment]
Thanks for the reply.

Yeah, that should have clicked when I looked at the changelog. It was because I was opening MPC-HC with AutoHotKey, and it was expanding the Playlist as part of the process. However, if the playlist was already expanded it was clicking the video area, thereby triggering the playback.

So I removed that part of the script, which now requires that I often have to manually (and precisely) double-click in the (rather small) area that triggers the playlist expansion. Is there a reason that the playlist might get minimized, rather than staying expanded and remaining in it's last saved position? Is it possible to turn off the click-to-play feature that was added? Again, thanks for your attention.

**Comment by clsid2** [comment]
I don't know what you mean with "expansion" of playlist. You mean moving it outside of player window?

I am not adding an option for it.

**Comment by maipoohsmelsFUnny** [comment]
Yes, expanding the playlist, undocking the playlist - however, you'd like to describe it - such that the playlist is separated out from the video playback window (so that it can be pulled / extended down the length of the monitor and made much more useful in its intended use as a playlist), rather than being placed on top of the relatively smaller video playback window.

I'm not asking for an option to undock the playlist window. That's already possible. I was wondering if you might know of a reason why it might get docked again, seemingly of it's own accord. If there is some underlying reason whereby it might get automatically docked again, perhaps, I can avoid whatever might be causing that and, thereby, not have to undock it manually, since, using AutoHotKey is now problematic due to the newly implemented click-to-play feature.

Hence, my inquiry, in terms of options, as to whether it was possible to turn off the click-to-play feature (i.e., playback of the playlist when any click is registered in the video area). After all, that was how it was in the previous version. Therefore, it's not like it would require implementation of a new feature. Could simply be an option to revert back to it by switching a value in the Advanced Settings tab.

In any case, if you have no desire to allow the option to turn off the click-to-play feature, I'd appreciate it if you could just tell me what would trigger the playlist to automatically get docked on re-opening of MPC-HC. Thanks.

**Comment by clsid2** [comment]
The playlist should remember its position/size/(un)docked state. If you can reliably reproduce it loosing the undocked state, then export your settings before and after it happens (options>miscellaneous). Then I can compare and hopefully reproduce it.
