### ISSUE TITLE
download subtitle, option to "enter your own search text"

### ISSUE THREAD

**Issue by ronkwann** [clsid2/mpc-hc#133]
many times i am not able to find the right subtitle through your automatic downloader.  i request to add an option that we can "enter our own search text" like other players, eg. mxplayer for android.

a photo to illustrate:
https://i.ibb.co/9ys9Kvh/https-i-imgur-com-1r-DXj-DJ.png

**Comment by clsid2** [comment]
I am not adding new functionality like this. Someone else will have to implement it.

**Comment by clsid2** [comment]
Has been implemented by adipose.
