### ISSUE TITLE
Bug with Drag and Drop folder in playlist

### ISSUE THREAD

**Issue by cirruswazza1** [clsid2/mpc-hc#1330]
I updated MPC-HC from version 1.9.15 x64 to version 1.9.16 x64.

Since the Drag and Drop of a folder containing the media (audio or videos) to the playlist (ctrl+7) does not work anymore.
Only the folder appears.
When you click on it, the following message appears in the status bar: File not found.

I tried to reset all the settings, the problem is the same.
I tried to install version 1.9.16 x64 on a new computer, the problem is the same.

After uninstalling version 1.9.16 x64 and reinstalling version 1.9.15 x64.
Drag and Drop works correctly again.

While waiting for the problem to be fixed, I continue to use the previous version 1.9.15 x64.

This problem is the same in x86 version

**Comment by cirruswazza1** [comment]
In addition: I tested the development builds.
The problem is not present in the following versions: 1.9.15.4 and 1.9.15.7.
The problem is present from version 1.9.15.20 to version 1.9.15.74

**Comment by cirruswazza1** [comment]
Important clarification:
The problem appears only with a folder containing one or more subfolders.

If the folder does not have a subfolder, Drag and Drop works correctly with the all development build 1.9.15.x and stable release build 1.9.16

**Comment by clsid2** [comment]
I am able to reproduce.

As a workaround until it is fixed you can drag&drop onto the video area. If you hold Ctrl button while dropping, then it will append to playlist (instead of replace).

**Comment by clsid2** [comment]
Fixed

**Comment by cirruswazza1** [comment]
I just tested the development builds 1.9.16.13
I confirm that the correction made has fixed the problem.

Thank you for the fast correction.
