### ISSUE TITLE
1809 LTSC Inconsistent Dark Mode ( Title Bar)

### ISSUE THREAD

**Issue by Damthe** [clsid2/mpc-hc#1334]
Both windows and mpc-hc dark mode is enabled.

This is not an issue in 20h2 21h1 or other newer versions.

No other programs doesn't present this kind of behaviour notepad++ has dark title bar inline with the dark theme. This is only on MPC-HC

![Screenshot](https://user-images.githubusercontent.com/21695940/135725795-7bc8e18a-57dd-4293-b600-cc1956bcdcd3.PNG)

**Comment by clsid2** [comment]
Windows Settings > Personalization > Colors > Accent Color > Use for title bars and window borders

**Comment by adipose** [comment]
I did implement custom draw of the titlebar. However, once the API for dark titlebar was exposed in Windows 10, I deprecated that code. If you are running an old build of 10, you may not get it, which is too bad. Upgrade to newer releases of 10.
