### ISSUE TITLE
[Suggestion] UI and Dark Mode improvements

### ISSUE THREAD

**Issue by Ryuji12** [clsid2/mpc-hc#1335]
Hi @clsid2 @adipose!
1. The UI of MPC hasn't received any updates for a very long time which makes it kind of obsolete. I'd like to suggest updating it by implementing round edges of all the menus as well as the main window. 
2. The dark theme is actually more of a gray theme. Changing the color of the menus from gray to black should make it more genuine to the name of the theme.

**Comment by adipose** [comment]
1. Actually there have been some minor improvements along with the dark theme, like volume control and seek bar, as well as miscellaneous improvements brought by fonts and glyphs for the dark theme. Rounded menus might look nice, though personally I don't consider anything wrong with squared edges and UIs have been going back from overuse of rounding.

2. Dark and black are not synonymous. The theme is significantly darker than classic mode. More importantly, it was modeled on Windows Explorer in "dark" mode. It's nearly pixel identical except when it improves on bad draw code from Microsoft.

**Comment by DRSDavidSoft** [comment]
This is related to #2141
