### ISSUE TITLE
Latin language not recognized

### ISSUE THREAD

**Issue by rogeeerrrr** [clsid2/mpc-hc#1336]
There's an issue with Latin language, MPC-HC don't recognize the external subtitles in this language when its code is "LAT". 
The Latin embedded subtitles are ignored, if your preferred languages are "lat spa" the program is going to pick "spa". On the other hand, with external subtitles it works, but language name is not shown.
Edit: MPC-HC v1.9.16
![image](https://user-images.githubusercontent.com/60176451/135750868-e9d9f9a0-81bb-4c2b-8c36-f015ea686a3c.png)

**Comment by clsid2** [comment]
I need a link to this video file.

**Comment by rogeeerrrr** [comment]
> I need a link to this video file.

There you go.
https://drive.google.com/file/d/1qbTEqEILurrz2r3pTzUov12_4V3G6Z8T/view?usp=sharing

**Comment by clsid2** [comment]
I have fixed the language not being displayed for the external subtitle.

**Comment by clsid2** [comment]
Also fixed the embedded track selection.
