### ISSUE TITLE
Strange Bug when installing new programs.

### ISSUE THREAD

**Issue by SonsofAnakin** [clsid2/mpc-hc#1337]
Ok, so I don't know if this would be classed as an MPCHC bug or a Windows 10 bug but since I don't know where else to start, here I am.

If I install a game to my Windows 10 machine, Pin that game to the Start Menu, then move the icon... MPCHC unpauses itself and resumes playing.

I always have at least 2 MPCHC windows open and this only happens on the first installation of a new standalone game/program. As soon as I move the newly pinned icon, MPCHC resumes playback.

It's not a huge deal, it takes 3 seconds to pause the playback again but if there was a simple fix, I'd kinda like it if it didn't happen. It's done this for quite a long time, through many updates but it did it again just now and I just thought I'd mention it... low priority though.

Anyway, love the program and really appreciate your work to keep MPCHC alive.
Cheers.
SOA

**Comment by clsid2** [comment]
Options > Keys > disable "Global Media Keys"

It is Windows that sometimes sends play/pause event. Very annoying.

**Comment by clsid2** [comment]
Very weird stupid bug in Windows. I can reproduce by just moving a pinned item. Happens only on the first item move during a session. After reboot/logout it happens again on first move.

**Comment by SonsofAnakin** [comment]
Many thanks for the reply and the fix. Glad it was something simple that didn't require a whole lot of your time.
