### ISSUE TITLE
Don't stop playback of video playlist when screen locked

### ISSUE THREAD

**Issue by jonpsp** [clsid2/mpc-hc#1338]
I'm using v1.9.16 on Windows 10 Pro 21H1.  When I play https://videocdn.dnalounge.com/live/index.m3u8 , if my screen locks (e.g. if the screensaver activates, or if I press Windows+L), the playback stops.  I'm usually listening via Bluetooth headphones from another part of the house (I'm not that interested in the video, only the audio), so this is inconvenient.

(Incidentally, that URL is the one used by https://www.dnalounge.com/webcast/video.html)

**Comment by ale5000-git** [comment]
I have noticed it also happens when the Null video renderer is set.

**Comment by jonpsp** [comment]
I'm using "Enhanced Video Renderer (custom presenter)"

**Comment by clsid2** [comment]
I have added an option to disable this automatic pause.

**Comment by rustyshakelford2** [comment]
> I have added an option to disable this automatic pause.

Where is said option? I have the same issue and can't find it.

**Comment by clsid2** [comment]
options > advanced > locknopause
