### ISSUE TITLE
PGS subtitles are rendering according to the window aspect ratio, not the video aspect ratio

### ISSUE THREAD

**Issue by vermian** [clsid2/mpc-hc#134]
Issue occurs when I have PGS subtitles enabled and the MPC-HC window is fullscreen or maximized and is a different aspect ratio than the video's aspect ratio - the PGS subtitles are rendering at the incorrect position/aspect ratio. In my scenario, I have a secondary monitor that is rotated, so the aspect ratio of it is 9:16. When I have a 16:9 video playing fullscreen on it with PGS subtitles, the subs are way out of the video frame and and stretched vertically near the bottom where the black bars are. I tested with both EVR-CP and madVR renderers and the issue occurs in both. This issue does not occur when using VobSub subtitles, or ASS. I'm using the MPC-HC internal subtitle renderer, Win7 x64 SP1, with MPC-HC x64 v1.8.8. I also tried playing with the "Position subtitles relative to the video frame" flag, but changing it made no difference to this issue. Here is an example of what it looks like: [https://imgur.com/a/92hHHDc](url)

**Comment by adipose** [comment]
See https://github.com/clsid2/mpc-hc/pull/172

Test build here: https://mega.nz/#!xMoWVIoS!VfiwUalbEk0G-XZF9Cud8umlBL4_LJIr9s2F86VMy7M

**Comment by vermian** [comment]
Tested with the new build and PGS subtitles are now rendering in the correct aspect ratio. Thank you very much!

**Comment by adipose** [comment]
Can you test this build?

https://mega.nz/#!dRgUBYCQ!W4ecHCZJmscfkShRQQxEY1fl0PSuakeUek_M4wdyVwM

Thanks.

**Comment by vermian** [comment]
Tested the new build and it seems to work well. I tested PGS, VobSub, ASS, and SRT subtitles in different window sizes and also checked the behavior of the "Position subtitles relative to the video frame" flag and everything seems to work as expected. Thanks!

**Comment by adipose** [comment]
Thanks!  One more test if you please!  This has a feature to make the subs show up on cropped videos, and I want to make sure I didn't break something.

https://mega.nz/#!AUhEjIYL!jE2rUaA3ry-4r_hgtNyEp9j55kh3_JggRaIALirfO3s

**Comment by vermian** [comment]
Tested everything again, as well as the new feature to force showing the subs in a cropped video like the Gravity sample provided. Everything seems to work well to me. Cool!

**Comment by clsid2** [comment]
Patch has been committed.
