### ISSUE TITLE
Option to make “Display current time - Ctrl+I “ turn on by default

### ISSUE THREAD

**Issue by shawn8888** [clsid2/mpc-hc#1340]
I know the hot key Ctrl+i can turn on "display current time" feature. However, this is reset every time mpc-hc is closed.
Is there a way to turn it on by default?
Thanks in advance!

**Comment by clsid2** [comment]
No.

**Comment by shawn8888** [comment]
> 
> 
> No.

Is it possible to add it to advanced settings or ini file as a feature request? Thanks.

**Comment by adipose** [comment]
When Tivo removed the time LCD from their devices I had to go buy a clock. I suggest you get a small digital clock if you want to see the time while full screen is active.

If the OSD showed time,maybe pausing would be enough.

**Comment by clsid2** [comment]
Ctrl+I show the playback time, not the actual time.

Maybe in future I we can add advanced option to control OSD settings. But it is low priority.

I was thinking of a bitflag value, that allows to disable display of each unique type of OSD event, like volume change. Or in this case enable showing of time by default.

**Comment by adipose** [comment]
Yes I meant if it showed current time (not possible today).

Could also have a custom formatter with substitutions.

**Comment by shawn8888** [comment]
I like the idea showing the current time and being able to customize the OSD format! Looking forward to this feature!

**Comment by Ripley00** [comment]
> Ctrl+I show the playback time, not the actual time.
> 
> Maybe in future I we can add advanced option to control OSD settings. But it is low priority.

Hello,
I created an account on Github specifically to request this feature. A future update that included this type of feature would be a welcome addition to this already excellent program.
-Thanks

**Comment by butterw** [comment]
My issue with the OSD, is that the automatic filename display can be disruptive in windowed mode (in particular for short (ex: 10s), low-res videos). I would sometimes like to be able to switch this off, without switching the OSD off completely.

**Comment by CatPlanet** [comment]
Oh I'd love to see current time to be configurabe so I can set it to be on by default.
It's one of those small things that make a huge difference in day-by-day use.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2702
