### ISSUE TITLE
[Feature Suggestion] FSR for upscaling

### ISSUE THREAD

**Issue by r57zone** [clsid2/mpc-hc#1342]
Hi, the MagPie utility has recently appeared, it upscales games, but it also works with any other applications. I checked the [FSR](https://www.amd.com/en/technologies/radeon-software-fidelityfx-super-resolution) scaling in some movies and TV shows and the picture gets better and clearer (compared to conventional stretching) if the content is small.
If you find it interesting, it would be great to see this feature in MPC.

Original MagPie repository: https://github.com/Blinue/Magpie
Translated fork: https://github.com/7Brandyn7/Magpie
(maybe the implementation will be useful)

Thank you for working on MPC.

**Comment by clsid2** [comment]
I am not interested in that. FSR is for games. If it was useful for video, then AMD would have used it for their DXVA2 scaling implementation.

If you want to use high quality upscaling algorithms in MPC-HC, you can use madVR as video renderer. Or use [MPC Video Renderer](https://github.com/Aleksoid1978/VideoRenderer) to use the DXVA2 scaling capabilities of your GPU.

**Comment by r57zone** [comment]
https://wccftech.com/vlc-media-player-adds-support-for-nvidia-rtx-video-super-resolution-available-now/

**Comment by clsid2** [comment]
SuperRes has already been available for MPC-HC for weeks!

https://github.com/Aleksoid1978/VideoRenderer/releases

SuperRes quality is pretty crap for the amount of extra energy that it uses.

**Comment by r57zone** [comment]
thanks for sharing

**Comment by BuyMyMojo** [comment]
While fsr was meant for games I have found it's 1.0 implementation to be a nicer and lightweight upscaler for other content too. I use it for bringing up clean 1080p anime for my 4K monitor or of course for video content of games.

There is a [GLSL implementation](https://gist.github.com/agyild/82219c545228d70c5604f865ce0b0ce5) that works inside of MPV, would it be possible to convert that over for use with MPV-HC?

**Comment by butterw** [comment]
FSR is a 2-pass luma upscaler, so it can't be ported to mpc-hc/be as a user shader. You could ask the mpc-video renderer devs. 
It's not only for games and quite good for 1080p>1440p. 
I've ported the CAS sharpener: https://forum.doom9.org/showthread.php?p=1993947#post1993947

**Comment by r57zone** [comment]
FFmpeg Adds AMD AMF Decoder, FSR-Based Upscaling
https://www.phoronix.com/news/FFmpeg-AMD-AMF-Decoder-FSR
