### ISSUE TITLE
Eternal issue of low volume on downmix needs fixing

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1343]
I keep seeing people asking for help on MPC-HC (on many tech/media forums) because when they listen to a surround sound file on their stereo speakers or headphones, the volume is way too quiet.
This has been an issue for many years, and it keeps coming up. Normalization is not the solution as it works on the overall volume on all channels equally.

So is there a proper way to fix this issue (so I can recommend to these people since it comes up very often)? 
Or maybe some default settings need to change to help the less tech savvy person avoid this issue altogether (so it just works out of the box)?

Is there even a reason for how downmixing works right now, which results in output volume being extremely low?

**Comment by clsid2** [comment]
In the internal audio decoder settings, on the Mixer tab, select 1.0 as center mix level. That helps to get higher volume when downmixing. To be specific, it increases sound of voices, which are mostly coming from the Center channel in a surround track.

The problem for most people is probably that they did not configure mixing in the audio decoder. In that case the downmixing is done by Windows. Some may even have 5.1 set in Windows Sound settings, which is wrong of course and causes part of the sound to get lost.

**Comment by ghost** [comment]
@clsid2 
> In the internal audio decoder settings, on the Mixer tab, select 1.0 as center mix level. That helps to get higher volume when downmixing. To be specific, it increases sound of voices, which are mostly coming from the Center channel in a surround track.

Yes but what about the other channels? and why are the default settings even the way they are? 

> The problem for most people is probably that they did not configure mixing in the audio decoder. In that case the downmixing is done by Windows. Some may even have 5.1 set in Windows Sound settings, which is wrong of course and causes part of the sound to get lost.

It's been a while since I had a fresh install of MPC-HC myself, but are you saying downmixing is not on by default? Why would that be? since most people have stereo speakers only and the people that do have surround speakers know enough to check their settings.
Windows sound setting also defaults to stereo.

**Comment by clsid2** [comment]
The default settings are the "standard" way of doing channel mixing. It is a different story that it doesn't give desired results for some people.

Mixing is not enabled by default because that requires knowing the desired output configuration of the user. Windows does not necessarily default to stereo, and there often are multiple audio output devices in a system. Mixing in audio decoder should also not be needed if Windows (and sound driver) do the mixing properly themselves.

**Comment by ghost** [comment]
@clsid2 so should mixing in MPC-HC be turned off for windows to take it over? 
What about the audio rendered and audio switched in MPC-HC? do they also need to be turned/kept off for that?

**Comment by clsid2** [comment]
You should only disable mixing in MPC-HC if you want Windows to take over.

Audio switcher is unrelated to mixing.
