### ISSUE TITLE
Filename or Title Shown in Seek Bar

### ISSUE THREAD

**Issue by ekk88d** [clsid2/mpc-hc#1344]
Showing the filename or title in the seek bar is especially useful when in full screen.

If the playlist isn't active or doesn't show a full filename, the seek bar has plenty of real estate to do so. It's a feature seen in other media players, but MPC-HC is my favorite player, so I'd like to see this feature in this project.

**Comment by clsid2** [comment]
I have no plans to add that.

If you have OSD enabled then you can press **N** to display current filename.
