### ISSUE TITLE
windows 11 no sound on home cinema, no hdr possible and weird launch issue

### ISSUE THREAD

**Issue by tirrorex** [clsid2/mpc-hc#1345]
Hello,
using latest stable build of mpc-hc plus mad-vr and the latest build of windows 11 release.

When i use the player to watch a video my screen goes black for a few seconds before loading the player (remind me of exclusive mode, which is disabled).

The video launches without hdr for hdr content and there is no sound (i tried several format from basic anime stuff to 1080p movie and ripped bluray).
Also there is a resolution change happening in the background for the other windows.

The hdr issue can be "fixed" by enabling hdr in windows but it has to stay on unlike windows 11 where mpc-hc can "force" hdr for the video like some videogames do.

It seems the video doesn't send the sound format to my receiver thus making it unable to play the sound.
My oled tv is plugged into my graphic card with hdmi 2.1 and i use the earc on the tv to passthrough the sound to the receiver (with dolby atmos home theater enabled on this source in windows)

There is no issue with sound if i use my earphones plugged with jack or if i turn the spatial audio in stereo (but obviously i cannot get dolby atmos this way).

I'm trying to troubleshoot this so any suggestions would be welcome at this point.

ps: for comparison i can reproduce the sound issue with mpc-be freshly installed aswell, something changed in windows but no clue what

**Comment by clsid2** [comment]
For the HDR issue, try this solution:
https://www.avsforum.com/threads/improving-madvr-hdr-to-sdr-mapping-for-projector.2954506/page-682#post-61080188

For sound issue, go to Windows Sound settings and view the Properties of the audio device. There should be a tab where it shows the supported bitstream formats. If not, update the driver.

**Comment by tirrorex** [comment]
Tried the solution (deleting all identifications under device) and it solve EVERY issues (so the screen doesn't black out when launching a video, sound works with atmos supported and hdr works aswell)

Very nice, thank you !
