### ISSUE TITLE
Subtitles are ahead by exactly 1 second only on "Video Mixing Renderer 9 (renderless)"

### ISSUE THREAD

**Issue by zoasr** [clsid2/mpc-hc#1346]
As the title says any subtitle on any video on the **"Video Mixing Renderer 9 (renderless)"** decoder only are exactly 1 second ahead of the timestamp in the srt file.
It works fine on every other decoder and on different video players

this happens on version:
 ### 1.9.16

haven't tested previous versions

**Comment by clsid2** [comment]
You should use EVR-CP instead.

Disabling "VMR-9 Mixer Mode" seems to solve the problem. With that enabled it is ahead by around 3 frames (120ms) on a quick test.

**Comment by zoasr** [comment]
> You should use EVR-CP instead.

Yes, i'm aware that **EVR-CP** is better in this regard, but i prefer to use **VMR9**  because it has much less GPU footprint (due to it not using DXVA i assume) it just had this subtitle issue.
And sure i could just add the delay myself using **F1/F2** but it is a little bit annoying to do every time i open up a video.

**Comment by clsid2** [comment]
I can't fix this because it seems to be a bug in VMR9 itself, not in the player code. Disabling mixing mode solves it. Downside is that you loose color control functionality, but you probably don't use that anyway.

Why do you need lower GPU usage? You probably have higher CPU usage now.

**Comment by clsid2** [comment]
Right-click on the time in the statusbar and enable high-precision. Try to get a more accurate estimate of how much earlier the subtitle is.

**Comment by zoasr** [comment]
> I can't fix this because it seems to be a bug in VMR9 itself, not in the player code. Disabling mixing mode solves it. Downside is that you loose color control functionality, but you probably don't use that anyway.

you're right, i dont have any sort of color control, thanks  disabling it fixed it

> Why do you need lower GPU usage? You probably have higher CPU usage now.

It's mainly battery conservation not a big deal

**Comment by clsid2** [comment]
Can you test if the time difference is around 3/4 frames for you as well (instead of exactly 1 second)? Then maybe I can implement  workaround by adding some artificial delay.

**Comment by zoasr** [comment]
> Can you test if the time difference is around 3/4 frames for you as well (instead of exactly 1 second)? Then maybe I can implement workaround by adding some artificial delay.

Time in MPC-HC:
![image](https://user-images.githubusercontent.com/44146518/136665430-406608fb-ab37-43ea-94a4-89fe2548110c.png)

Time in srt file:
![image](https://user-images.githubusercontent.com/44146518/136665491-090a93ef-e919-478d-8ba7-d39fc5d7f285.png)

it is a little bit hard to get it to the exact frame but it looks like 1 second (or 1200 millisecond according to the timestamps and some quick tests on several files i did)

**Comment by clsid2** [comment]
Please try this test build:
https://www94.zippyshare.com/v/24LhBoha/file.html

This should hopefully fix the problem.

**Comment by zoasr** [comment]
> This should hopefully fix the problem.

it did fix it with vmr9 mixer mode on and off
