### ISSUE TITLE
Youtube-dl.exe error: Unable to download webpage SSL Certificate failure

### ISSUE THREAD

**Issue by missingfoot** [clsid2/mpc-hc#1347]
I get this error message every time I stream from a URL.

The video streams fine after pressing OK.

Present on:
Windows 10 Pro 10.0.19043

Present using:
MPC-HC.1.9.15.x64
MPC-HC.1.9.16.x64

Tried resinstalling the program, down grading to older version, placing a fresh build of youtube-dl into the install directory

This error is not present in any other programs like VLC or PotPlayer

![Screenshot 2021-10-10 012810](https://user-images.githubusercontent.com/5360847/136676449-1dda9612-b1cf-4338-90b1-700cb51af3d6.png)

**Comment by clsid2** [comment]
The error is coming directly from youtube-dl. This is wrong place to report such problems.

Create a configuration file:
https://github.com/ytdl-org/youtube-dl/blob/master/README.md#configuration
Add this setting: `--no-check-certificate`
