### ISSUE TITLE
Subtitles desynchronized with external video filters

### ISSUE THREAD

**Issue by bernid** [clsid2/mpc-hc#1348]
Hi, 
I use MPC-HC 1.9.16.
When I use external video filters (e.g. H264/AVC from Cyberlink)
https://www.dropbox.com/s/vc2cihvyh0gu7ja/cyberlink13_07%272013.zip?raw=1
 I have an issue  with subtitles which is no synchronized with the video. 
I like this Cyberlink filters since in my opinion has better video quality than the default LAV Video Decoder 0.75.1.4

Can this be fixed in the next version of MPC-HC ?
Thanks for the software. I've been using it for over 10 years and it's my favorite for playing movies.

**Comment by clsid2** [comment]
H.264 decoders are supposed to give identical output. So you should not get any different quality unless the decoder does some kind of extra postprocessing.

Which video renderer and which subtitle renderer are you using?
Did you confirm that sync is correct with internal decoder for exact same video file?
How is the sub out of sync? Ahead/behind, by how much, and is it constant throughout the video.

**Comment by bernid** [comment]
> Which video renderer and which subtitle renderer are you using?

EVR (cp) + embedded subtitle renderer

> Did you confirm that sync is correct with internal decoder for exact same video file?

Yes I confirm.
The sync video subtitles + external Cyberlink filters worked fine in the last version of MPC-HC I used - 1.7.13 

> How is the sub out of sync? Ahead/behind, by how much, and is it constant throughout the video.

It seems like subtitles start from beginning each time  I change (using the slider) the playback time

**Comment by clsid2** [comment]
Fixed
