### ISSUE TITLE
[Bug] Framestep is skipping frames

### ISSUE THREAD

**Issue by BoomerangAide** [clsid2/mpc-hc#1349]
Hello,

I'm trying to watch the tool assisted speedrun (mkv version) from here: http://tasvideos.org/859M.html
Since it's a rpg, I have to use framestep to see some texts as they only last 1 frame or something.
It used to work.
But right now, I met a failure: around 44 seconds in, around the time a character turn toward the left and another move up, framestep only allow me to see a black box without text when advancing through framesteps.
But if I play normally, I briefly see the same box with purple text in it.
It seems the frame when it happen get skipped somehow with framestep, even though it's framestep forward (I thought only the backward one gave random results).

MPC HC version: 1.9.13

edit: I was looking for a workaround, tried to display the "Go to" menu while on the black box, to try to jump around, and when I framestepped again, it did stop on the right frame. I will hope it work again, but it's weird it's acting that way.

**Comment by clsid2** [comment]
Start by updating to 1.9.16

**Comment by BoomerangAide** [comment]
I tried updating to 1.9.16, at first it worked, then after an accident with the ini file, it's broken again, though sometimes it randomly work.

**Comment by clsid2** [comment]
I can reproduce with EVR-CP as video renderer. Try with one of the other renderers.

**Comment by BoomerangAide** [comment]
Thank you.
Apparently, during my attempts so far, the "Sync Renderer" allowed framestep back and forward to work properly, while still having Shaders and DXVA.
It has its shortcomings, but it's probably the appropriate solution for my current use case.

**Comment by clsid2** [comment]
You can also try MPC Video Renderer:
https://github.com/Aleksoid1978/VideoRenderer

**Comment by clsid2** [comment]
Fixed
