### ISSUE TITLE
[Feature Suggestion] Allow port range for web server so multiple instances can be controlled

### ISSUE THREAD

**Issue by Revenent** [clsid2/mpc-hc#1352]
Instead of a single port number, allow a range of ports to be provided, and the instance will attempt to listen on the first port in the range that allows it.

I couldn't find the code that binds to the port, but that code would have to walk the range instead of just trying one port.  Correspondingly, the app settings would have to have two settings for the start and end of the range instead of just one setting for the port.

The UX would have to have two numeric fields instead of one.  The link to launch the web browser would have to match the port that was actually selected.

**Comment by clsid2** [comment]
If you want multiple instances like that, then create copies of the player and store setting in INI file.

I am not interested in expanding the port option.
