### ISSUE TITLE
subtitle splitter selects the "Forced Subtitle (auto)" track that does not exist on the media. 

### ISSUE THREAD

**Issue by FX8350** [clsid2/mpc-hc#1353]
Hi

When playing mkv or Blu-ray with subtitles, MPC-HC will display a non-existent "Forced Subtitles" track and select it by default. (For mkv, if the other subtitle track contains the "Default" flag, it will be played by default.)

When this "Forced Subtitles" is played, no subtitles are displayed. (Same as "No Subtitles") 

What's the difference between "Forced Subtitles (Auto)" and "No Subtitles"?

![image](https://user-images.githubusercontent.com/10481430/137621496-11f9680e-996c-47b8-8743-7752a8bf12d2.png)

**Comment by clsid2** [comment]
That track is generated by the splitter. It contains only the "forced" subtitles that are in the full Japanese track. It can be empty if that aren't any.

Options > Internal Filters > Splitter

**Comment by FX8350** [comment]
thanks helping!
![image](https://user-images.githubusercontent.com/10481430/137624710-e896dca1-0079-4c42-afe2-8b0c5dcf0dc9.png)
