### ISSUE TITLE
[Bug] Missing key 811

### ISSUE THREAD

**Issue by BoomerangAide** [clsid2/mpc-hc#1355]
Hello,

In version 1.9.16, In Options/Player/Keys, there's a line for an unnamed entry with id 811 (between "Download Subtitles..." which is 812 and "Close" which is 804).

While I was at it, I checked the other entries, and another case of weirdness is entry 937, that display "&Organize Favorites...".
Maybe the '&' was expected to be transformed into something else?

**Comment by clsid2** [comment]
I have removed the obsolete empty entry.

The & is there because same string is used in the menu. Removing that requires workaround, and I am not motivated to do that right now.
