### ISSUE TITLE
Possible BUG

### ISSUE THREAD

**Issue by LucianAndries** [clsid2/mpc-hc#1358]
Hello again.

I'm having this issue on the latest version: When pausing a movie for a toilette break, etc, after coming back and hitting play again, the video becomes a picture slideshow................. The audio is fine though.
And sometimes it just gets audio-video desync.....................

And to fix this, I have to close MPC and start the movie again. And yes, it works fine afterwards.
I tested this on my collection of movies, that I know they work 100%, and still got the issue.

I'm using MADVR as the video renderer, and DXVA2 (copy-back) for Hardware Acceleration.
My GPU is a 1080 Ti.
And Windows 10.

I hope this can be reproduced and that it's not exclusive to my PC............... 
But here is my msinfo32 to see my system.
[msinfo32.txt](https://github.com/clsid2/mpc-hc/files/7388919/msinfo32.txt)

If you need more files let me know.

**Comment by clsid2** [comment]
You can press Ctrl+E to reload the video.

Test if it also happens with another video renderer.

What is the minimum amount of time it needs to be paused to trigger the problem?

**Comment by LucianAndries** [comment]
I'll test those things.

As for the time to trigger, I dunno. But the breaks are at least 5 minutes...

**Comment by clsid2** [comment]
Do you have the "delay playback start until render queue is full" option enabled in MadVR? If so, make sure the delay after seek is disabled, as that can cause stuttering.

**Comment by LucianAndries** [comment]
I've checked and it's disabled. I keep it on default settings, coz I played once with it and nothing was working anymore........ lol

**Comment by LucianAndries** [comment]
Btw, what is SaneAR Audio Renderer? What does it do?
Coz there's this and there's another in the Output settings...

I disabled it. And the Output one I set it to System Default, coz I have an AV Receiver. Did I do good, or...?

**Comment by clsid2** [comment]
That is one of the internal audio renderers. You can choose whichever you like best.

**Comment by LucianAndries** [comment]
Yeah, but what does it do exactly? Is it for when you don't have a professional audio device, i.e. an AV Receiver, or what?
Me dum...

**Comment by clsid2** [comment]
A renderer interacts with the Windows sound system and the sound driver of the audio hardware in your computer. It is irrelevant what is connected to that (speaker/headphones/receiver/whatever).

**Comment by LucianAndries** [comment]
So it's better to have a Renderer set, than just be on System Default?
Also, why does it need to be 2? One internal and one for the Output...

Ok, after this is clear to me, I'll keep it to the post's subject. But I am testing the issue as we speak. I'm trying to see a difference in pause times.

**Comment by LucianAndries** [comment]
Shit, I remembered about this setting that doesn't make any sense..............................................

In the settings --> Player --> History. What is "Remember File Position"?

Is it supposed to open the movie at the same time stamp, in case you closed the player midway?
If it's not this, then a setting like this would be awesome!!

**Comment by clsid2** [comment]
Yes, that remembers timestamp for next time you open same file.

**Comment by LucianAndries** [comment]
Well it's not working. For me anyway. And yes, keep history is enabled.
What should I do?
Dumb question, but does it work for you? :|

Back to BUG:
- For the wait time, it needs some time for it to trigger. So 5 min minimum from what I saw.
- Ctrl+E works, but temporarily.
- I changed to MPC Video Renderer, but the issue is even weirder... The video gets a slooooow start, and there's no audio at all..................... It starts working if I hit Ctrl+E, but like I said, it's temporary.

So, guess it wasn't madVR at fault. What now?

Btw, you still didn't answer the previous question. I'm still confused...

**Comment by clsid2** [comment]
Remember position works fine for me and everyone else.

"System Default" in most cases equals "Default DirectSound Device". That is DirectSound Audio Renderer, with the default audio output device set in Windows.
But to say it more simple: EVERY choice in that list equals exactly 1 audio renderer. Only difference is the implementation (DirectSound/WaveOut/SaneAR).
If you don't understand then I can't help you. I can't explain better.

All I can suggest is to try the different audio renderers and maybe also update you sound driver.

If you use HDMI connection to receiver, then you can also try with bitstreaming disabled, sending uncompressed PCM audio instead.

**Comment by LucianAndries** [comment]
Ok I somewhat get it with the Audio Renderer. BUT I have no issues with audio, I asked about it out of curiosity.

Now, position might work for everyone else, but it's not working for me. And I tried it on multiple file types, mp4, mkv, avi, etc. Not working.
Do I need to enable additional stuff? Can you show me some screenshots in how you have configured your MPC? Maybe I'm doing something wrong.

As for the thread's bug issue................. Well, it has to be a bug. If not, then I don't know.
BUT I swear that the previous 1 or 2 versions ago, I did not have this problem. I think I skipped 2-3 versions when I updated it, coz I haven't used it for a few months. So I can't tell when the issue actually started... :(

**Comment by clsid2** [comment]
Older versions are still available for download here. So you can test those if it didn't happen in the past.

**Comment by LucianAndries** [comment]
So I should stay forever on an old version. Cool...

**Comment by clsid2** [comment]
I did not say that. You should test older version to confirm if that does still work. Then we can maybe pinpoint where the problem started for you. That could help to figure out what the cause is.

But first just do a complete reset of the settings:
Options > Miscellaneous > Reset

And in case you were previously using the option to store settings in INI file, disable that and don't enable it again.

**Comment by LucianAndries** [comment]
Oh, I understand.

I will do that! But tomorrow when I get home, coz I'm beat.

Have a good night / day.

**Comment by LucianAndries** [comment]
Hey, I'm back.

So I'll be starting the tests, starting with the previous version. I'll let you know when I see a change.

**Comment by LucianAndries** [comment]
Hmm, version 1.9.15 doesn't do any of that. And I tested a lot...
You can compare it to version 1.9.16.

**Comment by clsid2** [comment]
Then also test these versions in between:
https://github.com/clsid2/mpc-hc/releases/tag/1.9.15.4

**Comment by LucianAndries** [comment]
Sure thing!

**Comment by LucianAndries** [comment]
Hmm, 1.9.15.20 seems to be fine too.

**Comment by LucianAndries** [comment]
Wait, did you edit the post? I could've sworn you said 1.9.15.20............
Damn, I'll install the 1.9.15.4 version.
Wait, but there's 1.9.15.74 as well.......... I'm confused. :|

**Comment by clsid2** [comment]
There are several versions between 1.9.15 and 1.9.16

If 1.9.15.20 is ok, then pick a higher version to test next.

**Comment by LucianAndries** [comment]
Hey, can you also tell me why all the other codecs sound quiet as hell, and PCM is the only one sounding loud?

Everything from Dolby Digital and DTS i can barely hear them....... Is it something with my AVR, or is that how they actually record the movies, mute? 😡

**Comment by clsid2** [comment]
If you bitstream, then your AVR does the decoding and volume control.

With PCM the audio has been decoded on the computer.

**Comment by LucianAndries** [comment]
I chose 1.9.15.74 from the start... And go backwards if necessary.

**Comment by LucianAndries** [comment]
I know how bitstreaming works. But is Windows preamplifying sounds by default? Or is my AVR just quieter when decoding stuff? And if so, then are all AVRs the same?

What is your personal experience? In case you have / had an AVR, and is / was not an Yamaha...

**Comment by clsid2** [comment]
I can't help you with that.

**Comment by LucianAndries** [comment]
Hmm, 1.9.15.74 had a/v desync for 1 sec after resume, then fixed itself....
Should I test 1.9.15.7 as well?

**Comment by clsid2** [comment]
The only big difference between 1.9.15.74 and 1.9.16.0 is updated internal LAVFilters.

First test if the problem still happens if you use 1.9.16.0 now. If it does still happen, try 1.9.16.0 with the LAVFilters64 folder from 1.9.15.74

**Comment by LucianAndries** [comment]
Ok. I copied the folder.

**Comment by LucianAndries** [comment]
Hmm, 1.9.16 seems to not do that anymore..................... Why? :|
Maybe it's a temporary thing, I'll test it better tomorrow.

**Comment by clsid2** [comment]
Maybe because of settings reset.
Maybe because of PCM to receiver.

**Comment by LucianAndries** [comment]
I never reset settings when installing / updating.
The movie was a mkv file, with Dolby Atmos. Besides, the issue was on every file type, and every sound codec.
I'll test it better tomorrow.

**Comment by LucianAndries** [comment]
Sorry for the delay!

Yep, seems to be working now. And I didn't need to use the old LAV filters.........

So, when I update or reinstall MPC, I never reset its settings, I just install on top of the old one. And I keep my .ini file as read-only, so it will never screw with my settings.
That's why I'm very surprised and interested why it works now. :|

Any ideas?

**Comment by clsid2** [comment]
A read-only INI file would be the reason why remembering file position did not work. It may also cause other problems.

I strongly advice to stop using the INI file. It is trivial to back up the registry settings. There is even a button in the options to do that (options > miscellaneous).
