### ISSUE TITLE
I hope to add a new view to rotate a landscape video by 90 or 270 deg.

### ISSUE THREAD

**Issue by kato80** [clsid2/mpc-hc#136]
Because any videos for smart-phone are landscape, But I want to avoid bending my neck.

**Comment by cdlvcdlv** [comment]
Try Alt-Keypad 3. 

Keypad keys change picture size. Ctrl-keypad keys move picture. Alt-keypad keys rotate it.

**Comment by kato80** [comment]
Oh, Thank you.

I did not notice this feature, because it is not on the View menu.
I think it should be added to the View menu so that everyone will notice.

**Comment by SanderBouwhuis** [comment]
Ooooh! I agree! This should really be in the view menu (please).

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/283
