### ISSUE TITLE
Emojis on styled webvtt breaks subtitle rendering 

### ISSUE THREAD

**Issue by anounyym1** [clsid2/mpc-hc#1362]
I noticed that emojis on styled vtt-subtitles breaks whole subtitle rendering, example youtube video source: https://www.youtube.com/watch?v=1OwKVtiKcbw  
Tested with MPC-HC versions 1.9.16 and 1.9.16.51

[sample vtt.zip](https://github.com/clsid2/mpc-hc/files/7403759/sample.vtt.zip) line 642
Rendered by MPC-HC:
![mpc-hc](https://user-images.githubusercontent.com/1563598/138573768-f1afb652-9e8b-40b2-bdda-e2aa270a5b55.png)
Rendered by Youtube player:
![youtube](https://user-images.githubusercontent.com/1563598/138573771-a63af249-1ac5-4d53-a111-80964f527270.png)

**Comment by clsid2** [comment]
Fixed the text rendering. The emojis are now replaced by spaces.
