### ISSUE TITLE
How can I set ScaledBorderAndShadow:yes? 

### ISSUE THREAD

**Issue by erickyun** [clsid2/mpc-hc#1364]
I'm using xySubFilter as renderer.

İs this possible with mpc-hc to change .ass subtitle to ScaledBorderAndShadow:yes?

**Comment by clsid2** [comment]
If you want to change the subtitle you need to modify the subtitle file.

**Comment by erickyun** [comment]
> If you want to change the subtitle you need to modify the subtitle file.


With mpv I can set ScaledBorderAndShadow:yes in mpv.conf so was wondering if the same could be done for mpc?

it would be handy if mpc would support this feature
:( cuz now we have to extract the subtitle and write ScaledBorderAndShadow:yes everytime

is there no simpler way to do this with mpc?

**Comment by clsid2** [comment]
MPC isn't even the one which is rendering the subtitles, because you are using xySubFilter. But even with internal renderer it is not possible, and I am not going to add an option for it.

**Comment by erickyun** [comment]
😑😒 ok
