### ISSUE TITLE
Dialog of clear file histories has incorrect window size

### ISSUE THREAD

**Issue by FX8350** [clsid2/mpc-hc#1365]
Hi.

here is dialog window of
File > Recent Files > Clear list

en:Are you sure that you want to delete recent files 
**_list?_**
![en](https://user-images.githubusercontent.com/10481430/138884972-158b8aa9-ce57-41f6-a24d-8c33c2b65f6a.png)

ja:最近使ったファイルの一覧を削除してもよろしいです
_**か？**_
![jp](https://user-images.githubusercontent.com/10481430/138884988-adc656dd-9aad-4751-87ca-5ffed3212e4e.png)

I'm using Windows 10 in Japanese, which may be the cause.

**Comment by clsid2** [comment]
Works fine here, so it is probably bug in Windows. I have seen weird dialog height issues before on Korean and Japanse systems. It is related to font heights being wrong/weird for the fonts that are used.

I can't fix this.
