### ISSUE TITLE
file load lag from loading timeline previews

### ISSUE THREAD

**Issue by Thespikedballofdoom** [clsid2/mpc-hc#1367]
(low priority)

I know it's performance intensive, but is it possible to load it asynchronously or delayed so file load isn't slowed down? For me after enabling previews it slows down loading new files by around 3 seconds.

**Comment by clsid2** [comment]
Not possible. It needs to build both filter graphs during opening.

Here a file loads in less then 2 seconds.

You should try latest development build. That may be a little bit faster for you. But there is nothing else I can do to speed it up.
