### ISSUE TITLE
Request: add option to avoid auto-search for subtitles in some cases

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [clsid2/mpc-hc#1369]
For example when you just have numbers, it doesn't make sense to auto-search subtitles.

An exception for this is perhaps if the app could fetch the folder name in such cases, to help identify what it's belonging to.

**Comment by clsid2** [comment]
If you want good results, use proper filenames.

**Comment by AndroidDeveloperLB** [comment]
@clsid2 I'm not the one who named it. Sometimes when you download, the files names have no meaning, too short, or Gibberish. 
It's annoying to have to see this dialog of subtitles for when it doesn't make sense to search for them.
Also not always it's possible to rename the file, as it might be shared with others while playing (preview or torrent).

Why close this?

**Comment by clsid2** [comment]
There is no easy way to exclude things, because valid movies names can be short or even just a number. And I really just don't care about this issue. If you download such crappy named stuff, disable the automatic search and do a manual search.

**Comment by AndroidDeveloperLB** [comment]
OK, so alternatively, can you please add a button on the toolbar to toggle auto-search of subtitles, or to manually do it ?
Or maybe have an indication that subtitles are available, and pressing it will offer the dialog we have today?
Sometimes I know that in the coming hour or so I will see only such files, for example.
