### ISSUE TITLE
request: make it possible to put the toolbar on an other screen (make it floatable)

### ISSUE THREAD

**Issue by fdebeer** [clsid2/mpc-hc#1370]
I always use this program to start video's on the second screen fullscreen. to keep it fullscreen , i cant open the toolbar to see the remaining time or to scroll to the end of the video.
It would be great to have the toolbar floating so i can place it on the other screen while playing a video to control the video.
other option is to keep the player in one screen and play it fullscreen on the 2nd screen simultanious

**Comment by adipose** [comment]
Hmm, it could probably be rendered in another window but there are some assumptions that it's a docked bar.  Maybe there could be a second rendering of it that can be dragged around.  I'll think about it for later.  Low priority.

**Comment by fdebeer** [comment]
thanks for your comment, the playlist can made floating in the other screen already. it shows the total time of a clip. maybe also add remaining time to the playlist window. it wil help me a lot :)

(maybe even controls there also? just play and pauze)

**Comment by clsid2** [comment]
If you have Windows 10/11:
Options > Advanced > useSMTC

Then you can control player through the volume icon of Windows. It will have play/pause and next/previous buttons.

**Comment by fdebeer** [comment]
> If you have Windows 10/11: Options > Advanced > useSMTC
> 
> Then you can control player through the volume icon of Windows. It will have play/pause and next/previous buttons.

i know, and i use this, but no remaining time of the video. when playing a video on second screen, i need to know when the video ends, so i can count it down for last 10 seconds. there is no (free) player for windows who can do this.

**Comment by clsid2** [comment]
Enable OSD.
Press Ctrl+I to display time in OSD.
Right-click on the time in statusbar to select remaining time.

**Comment by fdebeer** [comment]
and this on the other screen as where the video plays :) 
I use the player in presentations to play video's during events on a big screen. I cant show the osd there, so i need remaining time on the other screen. i need remaining time, so i know when to switch to camera or powerpoint. i know this requires a bit of programming, and unfortunately i can't code...
If it is possible to show remaining time in the playlist-window it would be great. maybe this isn't to difficult to code?

**Comment by clsid2** [comment]
Abusing playlist for that is a no-go.

**Comment by adipose** [comment]
- Let's see, so it is not possible to just full-screen to the second monitor and see all the controls on the first screen?

**Comment by clsid2** [comment]
It is possible with exclusive mode enabled for EVR-CP.

But that has a bug that you can't set focus to player window by clicking on it in taskbar. Plus the bug that breaks playback after exiting fullscreen and then entering it again.

MadVR has API to detect if it uses exclusive mode, but that is not yet used by MPC-HC.

**Comment by adipose** [comment]
Ah ok. And mpc vr?

I think we should solve this problem by rendering videotape only to second screen and just using the main window for controls.

We don't even need exclusive mode really. Full screen should be good enough.

**Comment by clsid2** [comment]
Sure, if you want to work on that, would be great.

**Comment by clsid2** [comment]
The exclusive mode code does something similar, so that can maybe be adjusted to also handle normal fullscreen on other monitor.
See CMainFrame::CreateFullScreenWindow() and search for "D3DFullScreen" for relevant code.

**Comment by adipose** [comment]
Spent some time but stuck on a bug with the main window wanting to size itself to screen size despite no calls to movewindow or setwindowpos.

**Comment by clsid2** [comment]
Maybe maximize command in WindowProc?

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1614

I have gotten it working.  Problem was in "onsetwindowpos" btw.

It's not quite done.  In particular, there is nothing added to determine when/how this should be used.  Right now there's a hard coded boolean to send it to the second screen.  But it could be an option similar to D3D.

**Comment by clsid2** [comment]
Could be advanced option. For example "ShowGUIWhenFullscreenOnOtherMonitor" (a bit long). The fullscreen page in settings doesn't have free space.

Then do it if that is setting true and the player gui is on a different monitor than the target fullscreen monitor.

**Comment by adipose** [comment]
No advanced option, but it now detects if the fullscreen monitor is other than the current monitor.  If so, it can enable the new "empty" controls interface.

Maybe we don't need an advanced option.  You can even minimize the main controls on the other screen if you like, but overall it seems useful to have it.

**Comment by fdebeer** [comment]
really love the work you are doing now on this. hope to see the results soon.

**Comment by clsid2** [comment]
1.9.20.10 development build has this new functionality

**Comment by clsid2** [comment]
There will be a new build with some fixes later today or tomorrow.

**Comment by clsid2** [comment]
Now optional.

Options > Advanced > FullscreeSeparateControls

**Comment by fdebeer** [comment]
perfect, working as a charm. many thanks for this
