### ISSUE TITLE
Next/Previous behaviour when chapters are in a different order

### ISSUE THREAD

**Issue by LightArrowsEXE** [clsid2/mpc-hc#1371]
There are cases where chapters are ordered differently by the muxer (like for example through the way they set up their automatic merging setups).

```
Menu
00:01:50.010                             : Part A
00:11:18.990                             : Part B
00:22:59.980                             : Preview
00:00:00.000                             : OP
00:21:50.000                             : ED
```

Currently, MPC will strictly follow this order, causing you to jump all over the video. It would be great if it instead ordered it by timestamp. So rather than go from Part B -> Preview -> OP -> ED, it would go from Part B -> ED -> Preview.

**Comment by clsid2** [comment]
Sorting the chapters by time causes problems with Matroska files that contain multiple editions. So I am not going to change the current behavior.

The muxer should not use a stupid order. They should 'fix' this.
