### ISSUE TITLE
Fix for "skip forward"

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1372]
Hi,

currently there is a bug in MPC, where the "skip forward" button is not working. This bug occurs when only one video file is left in the directory after deleting the previous one with the delete key on the keyboard. To help you understand the issue, I recorded a video showing the bug:

https://user-images.githubusercontent.com/85796777/139719251-21328433-24ac-4a5e-b675-03bcebd5b8d0.mp4

I'm using the newest nightly version (1.9.16.51 x64 on WIndows 10)

Thanks for your help.

**Comment by clsid2** [comment]
Fixed

**Comment by ghost** [comment]
Wow, thank you. That was really fast. Now I just need to wait for the next compiled nightly version to test it.
