### ISSUE TITLE
Is MPC-HC limited to listing a maximum of 55 to 56 subtitles?

### ISSUE THREAD

**Issue by didamsko** [clsid2/mpc-hc#1374]
Hi, I came across a .mkv media file that has 74 subtitles, several are additional subtitles for commentary tracks, and what i noticed is that MPC-HC only lists 56 of them. 

See the screenshot below showing MediaInfo and MPC-HC, The green arrow shows that there are 74 subtitles, the red arrows show where MPC-HC stops listing the subtitles. VLC and Cyberlink PowerDVD do list all 74 subtitles. 

![mpc-hc-list-56-subtitles-max](https://user-images.githubusercontent.com/60958082/139771629-39ca4dca-cbbb-471b-aa83-18ced464eed3.png)

Is there an option to increase the number of subtitles that MPC-HC lists? It looks like its set somewhere in MPC-HC, I removed subs 56 and 57 to see if they might have an issue preventing the others getting listed but that still resulted in MPC-HC listing 56 subtitles max. So there seems no way to access 18 of the available subtitle tracks via MPC-HC. I also checked another .mkv media file with a lot of subtitle tracks (106) and on that one MPC-HC stopped listing them after subtitle number 55. 

I'm running MPC-HC (Nightly, 64-bit)
```
Build information:
    Version:            1.9.16.46 (1a862bba3)
    Compiler:           MSVC v19.29.30136
    Build date:         Oct 20 2021

Operating system:
    Name:               Windows NT 6.1 (build 7601, Service Pack 1)
    Version:            6.1 (64-bit)
```
It came bundled with the K-Lite Codec Pack Mega.

**Comment by clsid2** [comment]
There might be a limitation on the splitter where the total number of tracks (including audio and video) is max 64.

**Comment by clsid2** [comment]
You can see what the splitter exposes here:
Menu > Play > Filters > LAV Splitter Source

**Comment by didamsko** [comment]
Looks like you correctly identified what is causing this. The LAV Splitter Source indeed only lists 64 tracks of the 82 tracks in total: 1 video, 7 audio and 56 subtitle: 

![mpc-hc-max-64-tracks-lav-splitter-source](https://user-images.githubusercontent.com/60958082/139841674-15375aa7-61dd-4f31-9511-1fe09ae234c5.png)

Is there a way to increase that maximum? Or otherwise a place where i can request the maximum number of tracks to be increased?

**Comment by clsid2** [comment]
Can you give a link to that file?
I should be able to increase the limit. But I need to test it just to be safe nothing else breaks.

**Comment by didamsko** [comment]
Yes will post a temporary wetransfer link to a segment of that file here in a couple minutes. The file itself is to big to share for me but the segment will have the same number of tracks and characteristics.

**Comment by didamsko** [comment]
Here is the segment: _`obsolete wetransfer link removed`_

Is that enough and OK to test? And if you increase could you then increase to about 128 tracks max?

**Comment by clsid2** [comment]
Here is a test build with 128 tracks max:
https://www.sendspace.com/file/5e3mod

**Comment by didamsko** [comment]
Thanks! Works perfect! 

Will remove the wetransfer link.

**Comment by didamsko** [comment]
PS. clsid2, will you also make that the change from 64 to 128 tracks max in the LAV Splitter is also permanently implemented into LAVFilters (https://github.com/Nevcairiel/LAVFilters)? 

Thanks in advance!

**Comment by didamsko** [comment]
For future reference: the above change ended up getting reverted due to problems: https://github.com/clsid2/mpc-hc/issues/1382
