### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by awawa-dev** [clsid2/mpc-hc#1375]
Hi
Trying to clean compile latest development version. Getting error:
![obraz](https://user-images.githubusercontent.com/69086569/139916433-08d2b6bf-570a-4530-8d98-e63c9073cb1b.png)

In fact something is not right with the src\thirdparty\ffmpeg\libavutil\ffversion.h that is generated dynamically:
![obraz](https://user-images.githubusercontent.com/69086569/139916731-2cc5062e-6415-43ef-8d2a-5e7c7574135a.png)

Using build.bat with the following args:
![obraz](https://user-images.githubusercontent.com/69086569/139916001-f76dd969-9057-4b8f-a8b6-7f9153b50ed9.png)
Do you know what can cause it?
Regards
Awawa

**Comment by awawa-dev** [comment]
I think that could be related somehow: https://github.com/clsid2/mpc-hc/pull/1239

**Comment by clsid2** [comment]
Undo the changes to ffversion.h and you should be able to compile.

**Comment by adipose** [comment]
`ffversion.h` is not generated dynamically, I don't think (despite the comments).  I do have a script there for generating makefiles from the configure, but it's not set to run as part of the build.

You didn't change `ffversion.h` manually?

Was this a new build or did you have an old tree?

Note current source of ffversion.h is not what you are showing: https://github.com/clsid2/mpc-hc/blob/develop/src/thirdparty/ffmpeg/libavutil/ffversion.h

**Comment by awawa-dev** [comment]
It's generated dynamically from src\thirdparty\ffmpeg\ffmpeg-msvc.mak 

````$(VERSIONH): Changelog
	sh ffbuild/version.sh . $(MAK_DIR)libavutil/ffversion.h
````
when you comment it then it works for clean builds. 
The relative path for src\thirdparty\LAVFilters\src\ffmpeg\ffbuild\version.sh (notice it's a different ffmpeg folder) is included so it breaks the compilation process when run from src\thirdparty\ffmpeg\ffmpeg-msvc.mak : the problem is reproduced not only on my desktop but using GitHub Action also so definately a bug for me...

**Comment by adipose** [comment]
Yes, I was just checking this, you're right.  It's based on the changelog updating.  I'm reviewing it now.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1378

Try updating your `ffmpeg-msvc.mak` and deleting `ffversion.h`.  Then build again.

**Comment by awawa-dev** [comment]
I applied your PR on my forked branch that is even with develop and it works:
https://github.com/awawa-dev/mpc-hc/actions/runs/1418662760
https://github.com/awawa-dev/mpc-hc/commits/GithubAction
Before the PR I had to use workaround in the script (comment-out that problematic line)
Thanks!
