### ISSUE TITLE
After long pause, MPC-HC continues playing with reload the media file, but the audio and / or subtitle track selection will be reset.

### ISSUE THREAD

**Issue by FX8350** [clsid2/mpc-hc#1377]
Hi.
After long pause, MPC-HC continues playing with reload the media file, but the audio and / or subtitle track selection will be reset.
I confirmed it with mkv and Blu-ray (mpls) where there are multiple tracks.

**Comment by adipose** [comment]
I'm sure it's a side effect of reloading the file, introduced recently.

**Comment by clsid2** [comment]
I will look into storing/restoring the selected track later when reloading.

**Comment by clsid2** [comment]
Fixed

**Comment by FX8350** [comment]
Thanks fixing, its works fine.

~~Is it possible to store the zoom rate (windows size) as well?~~
~~Currently, the window size changes when file reload according to the "Zoom and Alignment" settings in Options> Playback~~
simply solutions : use Options > Player > History > "Remember last window position/size"

**Comment by clsid2** [comment]
Use option "remember last pan&scan zoom" or "remember window size". I am not going to implement anything specifically for reload.

**Comment by FX8350** [comment]
Woo...Sorry to take your time.
