### ISSUE TITLE
Crash when attempting to stream video to discord

### ISSUE THREAD

**Issue by sudo-bayan-gcc** [clsid2/mpc-hc#1379]
Steps to reproduce:
Open video file using MPC-HC
Open a discord call
Stream video file playing on MPC-HC to discord

System Information:
MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.16 (b395227da)
    Compiler:           MSVC v19.29.30133
    Build date:         Sep 22 2021

LAV Filters:
    LAV Splitter:       0.75.1.4
    LAV Video:          0.75.1.4
    LAV Audio:          0.75.1.4
    FFmpeg compiler:    MinGW-w64 GCC 10.2.0

Operating system:
    Name:               Windows NT 10.0 (build 22000)
    Version:            10.0 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    GPU:                NVIDIA GeForce RTX 2060 (driver version: 30.0.14.9649)

**Comment by clsid2** [comment]
Discord settings > Voice & Video > disable "Use our latest technology to capture your screen"
