### ISSUE TITLE
Three suggestions for better Keys list handling

### ISSUE THREAD

**Issue by lkintact** [clsid2/mpc-hc#138]
The Keys list (View > Options > Player > Keys) is rather long and not sorted (the Command column items are grouped by functionality, to be exact), which sometimes makes it difficult to find the needed command/key/id, etc.

To make it easier I suggest three features in the order of descending (or at least it seems so) implementation difficulty:
1. A filter input field at the top of the Keys list. The list would only display items matching the filter.
2. Enabling ascending/descending sorting by any of the columns by clicking on the column name (clicking for the second time would reverse the sort direction).
3. Keys list items are now selectable, but cannot be copied to the clipboard. Implementing a context menu "Copy" item and/or just the standard Ctrl+c (copy to clipboard) functionality would allow searching for/filtering/sorting etc the items in an external text editor.

MPC-HC 1.8.8.

**Comment by clsid2** [comment]
I am not adding new functionality like this. Someone else will have to implement it.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/171

Filter and sorting enabled.

Test build here: https://mega.nz/#!FY4xTIxK!uTTK9I0HrhOCoelmUf2uS_91U8U0dE9fy9-r3g9AgSE
