### ISSUE TITLE
About G-SYNC

### ISSUE THREAD

**Issue by ROOOCCCK** [clsid2/mpc-hc#1380]
NVIDIA control panel can't use G-SYNC function for MPC-HC, will you consider adding it later?

**Comment by clsid2** [comment]
Video playback only works good with a FIXED refreshrate. Variable refreshrate technologies are completely utterly useless for video playback.

**Comment by ROOOCCCK** [comment]
> Video playback only works good with a FIXED refreshrate. Variable refreshrate technologies are completely utterly useless for video playback.

I think it should be able to reduce the drag phenomenon
