### ISSUE TITLE
Speed-Modifier Pitch Correction Clipping

### ISSUE THREAD

**Issue by akash329d** [clsid2/mpc-hc#1381]
Hi,

I'm using the internal audio renderer (SaneAR), and speeding up the video does do correct pitch correction, but the audio seems to be clipping a bit, or at least has some weird high pitched artifacts. This is very noticeable by playing a YouTube video through MPC and speeding it up 2x and comparing that to the YouTube video at 2x. It's less noticeable at lower speeds. Is there any way to fix this?

**Comment by clsid2** [comment]
You could try MPC Audio Renderer instead.

I can't fix it.
