### ISSUE TITLE
Issue with the 64 tracks to 218 tracks change in the LAV Splitter

### ISSUE THREAD

**Issue by didamsko** [clsid2/mpc-hc#1382]
I cheered to early on this report: https://github.com/clsid2/mpc-hc/issues/1374 

As mentioned i use MPC-HC as how it comes bundled with the K-Lite Codec Pack. Everything looked to be working fine but now that the change has been rolled out and also ended up into the K-Lite Codec Pack 16.5.1 update i found that things are not working as they should. I applied the update and MPC-HC plays as usual on files with a limited number of tracks but when i then tried the media file with the 74 subtitles the playback hangs after a couple seconds. Same happens on other files with a lot of tracks. 

I reverted back to K-Lite Codec Pack 16.5.0 and then things are working normal again although then of course the number of listed subtitles is limited again. I tried and found that i can update all files but not the "avformat-lav-58.dll", when i update that one the problem starts. 

Not sure why i did not notice the issue the first time because when i now place the "mpc-hc_128track_test.zip" MPC-HC over the K-Lite Codec Pack 16.5.0 one it now also has the problem that it hangs on media files with a lot of subs like the one with the 74 subtitles. Maybe i did not let the file play long enough before reverting back to the K-Lite Codec Pack 16.5.0 version. 

If there is a way that i can help pinpointing the problem by providing a log of the application hang? I'm on 64-bit Windows 7 Pro SP-1. I probably would need a pointer how to create a useful log as the Windows event log does not seem to hold much on the hangs.

**Comment by clsid2** [comment]
I am going to revert the change. I don't have any time or interest in debugging this. There is probably a reason why the limitation exists.

**Comment by didamsko** [comment]
OK. Sorry for the troubles. Might be something for the future to still look into. A lot of web releases are getting more and more subtitle- and audio tracks.

**Comment by clsid2** [comment]
That is up to the LAV developer to do.

I wouldn't be surprised if there are duplicate subtitle streams in such webrips.
