### ISSUE TITLE
Wildcards broken in m3u playlists after 1.9.1

### ISSUE THREAD

**Issue by Thornburgh** [clsid2/mpc-hc#1383]
After 1.9.1, m3u playlists with wildcards no longer work.  That is, I have m3u playlists that include wildcards like d:\music\*.*.  With 1.9.1 and older, that would add all the files contained in that folder into my playlist.  Now it just gives an error and adds no videos.

**Comment by clsid2** [comment]
Fixed

**Comment by Thornburgh** [comment]
Thank you.  I find this feature super useful with my collection of music videos.
