### ISSUE TITLE
Next file in folder playback from the beginning

### ISSUE THREAD

**Issue by hat3k** [clsid2/mpc-hc#1385]
Hello. I would like to ask for a feature.

Now we have a feature to "**play next file in the folder**". But if the next file was ever played on one's PC it starts from last remembered position. I would like to have an option to play such "next files" from the beginning, ignoring another option "remember File position".

It is useful when you watch the whole season one episode by one, but the history of playback contains some file's remembered positions.

Thank you in advance.

**Comment by clsid2** [comment]
I can't add options for every possible scenario.

You can press Home button on keyboard to start file from beginning.

**Comment by tmssngr** [comment]
The remembered position only makes sense if one launches with this file. Pressing next/prev should always ignore the remembered position. I can't imagine any usecase where it would make sense to press next/prev and start from the previous position.

**Comment by clsid2** [comment]
Example use case:
You have partly watched episode 5 of a series. Next session you accidentally open episode 4, which then resumes during end credits, making you realize you have already watched that one. You press next. In this case you expect episode 5 to resume from remembered position.

**Comment by tmssngr** [comment]
Hm, this seems like a very constructed/rare usecase for me.

**Comment by clsid2** [comment]
I disagree. I have had that happen myself.

Please explain how in your case the file ended up in the file history. Did you already watch it fully before?

**Comment by hat3k** [comment]
If you click on the file yourself you will see the credits and you will realize you have watched it already. But if you want to watch the whole season once again you just start the first episode and want to see all the rest files from the beginning, automatically played one by one from the beginning.

**Comment by tmssngr** [comment]
Maybe when going to the next/prev video where a last used position was remembered, it could show some button/link for a certain time (e.g. 10s) that, when clicking it, will forward to the remembered position?

**Comment by clsid2** [comment]
In latest version, pressing stop button resets position to 0. You can do that before going to next file.
