### ISSUE TITLE
Request: add more options to the subtitles-auto-search dialog

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [clsid2/mpc-hc#1386]
Currently, when there are no subtitles found, there is a status bar text about it.
When there are, there is a dialog showing a list of the results.

I'd like to request to have more options about this behavior:

1. When manually showing the dialog, auto fill the text based on the file name. If there is also a metadata, offer alternatives there when you focus on the textbox. It could be nice that it would auto-search for metadata results too, especially if there are no results based on file name alone.
2. Add option of what to do when subtitles are found: Show the dialog (what we have today), have indication that there are available via the status bar (and allow to press it to show the dialog), a checkbox to auto-choose most suitable one (especially if it has a perfect match or very high matching score). 
3. In the dialog, offer to order by matching score and always remember the sorting choice for next time. Also make it have second sorting order (meaning that if 2 have the same score, order by something else that we chose, such as number of downloads).
4. Add option to avoid playing the video while showing the dialog. It's annoying to see that it plays while I try to choose the best subtitle.

**Comment by clsid2** [comment]
1. It searches using file hash and filename. That is the only data that is really useful for getting good results when searching. I am not interested in using other data.
2. When there is an exact match it already downloads automatically and that is already shown in status.
3. I am not interesting in implementing this.
4. It could do a pause/resume. But someone else has to implement it.

**Comment by AndroidDeveloperLB** [comment]
@clsid2 
1. There is no such a thing as "title" or "description" that could be useful?
2. I see. Does it have any kind of special logic ? 
3. Why? It can help choosing the next best subtitle this way.
4. Please do consider adding it.
5. I'm not sure you understood one of what I wrote, so will write in a new point: option to choose that when it finds available subtitles, it won't auto-show a dialog, and instead have a silent information in the status bar "Found subtitles", which you can press to show the dialog and choose one.

**Comment by clsid2** [comment]
1 No.
2 Matching hash
3/4/5 I am not interested in implementing this.

**Comment by AndroidDeveloperLB** [comment]
1. I checked now. There is such a thing. Tested on some random mp4 file. Please check it out.
2. ok
3+4+5. Why not? What's bad about these? Also you wrote that 4 could still be. Now you say it shouldn't 

:(

**Comment by AndroidDeveloperLB** [comment]
Too bad. It's my favorite player on Windows...

**Comment by awawa-dev** [comment]
Anyway there is already problem with the subtitles priority I think....for example podnapisy returns whole bunch of false hits. But sometime it returns a valid result among them. So I want to give that provider lowest priority. It's similar problem for language version version: if I set pl,en in that order and the first provider returns some result with only 'en' version then the player will be use it. it won't wait few/fracture of second to give a chance for other providers to find higher priority language version.

**Comment by AndroidDeveloperLB** [comment]
@awawa-dev @clsid2 Why be against temporary pausing in case the dialog showed up when starting to play?
You usually can't see what's on the player when it's playing in this situation, as the dialog is on top of it...

**Comment by clsid2** [comment]
I am not against it. I said "I am not interested in implementing this"  and that means exactly that. Other developers can submit patches. You continually ignore what I say and keep whining. That annoys me and that is why this is closed and stays closed.
