### ISSUE TITLE
Audio file slight skip at beginning?

### ISSUE THREAD

**Issue by Thespikedballofdoom** [clsid2/mpc-hc#1388]
In vlc, you can hear the first part of this song clearly, but mpc-hc seems to force it to start a slight bit later in the file.
I tried messing with audio delay, video and audio renderers, but it still forces it to start late.
https://raw.githubusercontent.com/Thespikedballofdoom/bbuhgf/main/hip_to_be_shit.mp3

This problem exists even on the first release

**Comment by clsid2** [comment]
Beginning sounds the same to me in VLC, WMP, Winamp, and MPC-HC. Durations are identical as well.

**Comment by Thespikedballofdoom** [comment]
I keep getting a difference like this.
![image](https://user-images.githubusercontent.com/43627353/140593621-f46ef12c-c959-4e18-ba93-82bc73466106.png)

Should I set some sort of delay or change a setting?

**Comment by clsid2** [comment]
What am I looking at in that picture?

There is nothing that you can configure. Setting a delay is wrong.

I can't fix this. The internal codecs are a different project (LAV Filters).

**Comment by ale5000-git** [comment]
It isn't clear the unit of measure in the image but it is like 50 millisecond difference?
I don't think anyone can hear it.
