### ISSUE TITLE
mpc does choose hardsub video for crunchyroll how can I choose video without hardsub?

### ISSUE THREAD

**Issue by erickyun** [clsid2/mpc-hc#1389]

**Comment by clsid2** [comment]
It is not possible to choose the video.

**Comment by erickyun** [comment]
> It is not possible to choose the video.

I did found it is possible with yt-dlp.
create yt-dlp.conf and edit:
`--extractor-args "crunchyroll:hardsub=None" `

this method works but now I can't get any subtitle.
