### ISSUE TITLE
REPRODUCCION MALA

### ISSUE THREAD

**Issue by NEXUS-SEIS** [clsid2/mpc-hc#1390]
**Alguien sabe porque este reproductor reproduce películas HDR o 4k prácticamente sin color? el resto de películas si las reproduce con colores vivos, pero en HDR o 4K el color es muy muy apagado, al contrario de VLC que reproduce esos formatos con el color vivo y como tiene que ser.
Alguien sabe a que se debe?
Alguien sabe si es problema de configuración?
Ya he probado todas las configuraciones posibles y no hay nada que hacer?

Gracias amigos

Rafa**

**Comment by clsid2** [comment]
You need to install this and select it in MPC-HC options:
https://github.com/Aleksoid1978/VideoRenderer

**Comment by NEXUS-SEIS** [comment]
**Cual es el procedimiento para seleccionarlo?

Esta carpeta donde tengo que copiarla? o todo lo que ella contiene?, porque hay archivos y directorios dentro de la misma.

Porque todo esto no lo incluyen dentro del archivo de instalación de este reproductor, o sea, que cuando hagas la instalación estos archivos ya estén incluidos al hacer la instalación?

Gracias**

**Comment by clsid2** [comment]
Install K-Lite Codec Pack. That will install everything for you.

**Comment by NEXUS-SEIS** [comment]
**Ok muchas gracias, lo voy a hacer y te comento como fue, saludos.

Rafa**

**Comment by NEXUS-SEIS** [comment]
Hola, oye no hay manera, instalado el K-lite codec pack y el reproductor sigue igual, todo lo reproduce con colores vivos y cuando reproduzco cualquier peli 4k el color casi se apaga, con VLC reproduzcas las pelis normales o las 4k se reproducen con una calidad de color bestial, porque con MPHC no pasa eso?.

**Comment by clsid2** [comment]
MPC options > Playback > Output > Video Renderer > MPC Video Renderer

**Comment by NEXUS-SEIS** [comment]
En el apartado de los renderizadores no aparece MPC Video Renderer, aun habiendo instalado el K-lite codec pack basico, no aparece el renderizador que me comentas, a que puede ser debido?

**Comment by NEXUS-SEIS** [comment]
**Actualización:
Solucionado, instalada la versión estándar de K-Lite y desinstalada la versión de MPC-HC anterior, al instalar la básica de K-Lite no instala la ultima versión del MPC-HC y aun habiendo una instalada antes de instalar el K-Lite, este ultimo  no actualiza los renders del MPC-HC, así que desinstale el MPC-HC y procedí a instalar el K-Lite Standard y ahí si que instaló junto con los codecs el reproductor, ahora probare con el render de MPC a ver como se ven los videos 4k, te comento en unos instantes, muchas gracias, saludos.

Rafa**

**Comment by NEXUS-SEIS** [comment]
**Ok, problema solucionado, ahora ya se ven bien las películas 4k, muchísimas gracias y un saludo a toda la comunidad, cuídense y hasta pronto, sigan con este arduo trabajo de facilitarnos la vida informáticamente hablando, saludos a todos.

Rafa**
