### ISSUE TITLE
Global Media Keys always on even if unchecked

### ISSUE THREAD

**Issue by xirasu** [clsid2/mpc-hc#1391]
The Global Media Keys are always caught, despite having it in settings unticked.
Tried turning it on, and restarting mpc-hc.
Tried turning it off again, and restarting mpc-hc.

Issue with 1.9.16.46.

**Comment by clsid2** [comment]
With option disabled they should only be caught if the player has focus. The option is only for when the player doesn't have focus.

If you want to disable it completely you need to adjust the keys settings.

**Comment by xirasu** [comment]
Issue persists also while not in focus.

And I would like to disable it even when in focus too, but where? There's no column for it, nor an entry for the media-keys in key-settings. Nothing in advanced either.

**Comment by clsid2** [comment]
It is the "App Command" column. You can click on the column header to sort, and show they all on top.

**Comment by xirasu** [comment]
Ah, well that was already unassigned on my side. But I assigned it again, closed, tested. Unassigned again, closed, and tested again.

At least there seems to be a difference in display between when assigned and using it focused, and using it unassigned focused & unfocused. For the latter WinX's "notification" pop up in top left appears as well, like for Spotify (for which I have the notification disabled).

**Comment by clsid2** [comment]
If they were unassigned before then your key assignments were messed up.

What is the contents of this registry key?
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\Commands2

**Comment by xirasu** [comment]
Oh, have it in file, but it says:
```
CommandMod0=969 1 51 "" 5 0 0 0 0 0
CommandMod1=800 9 51 "" 5 0 0 0 0 0
CommandMod10=897 7 25 "" 5 17 0 17 4 4
CommandMod11=33449 1 52 "" 5 0 0 0 0 0
CommandMod12=33450 1 0 "" 5 0 0 0 0 0
CommandMod13=922 1 4e "" 5 13 0 13 0 0
CommandMod14=921 1 50 "" 5 10 0 10 0 0
CommandMod15=920 5 4e "" 5 0 0 0 0 0
CommandMod16=919 5 50 "" 5 0 0 0 0 0
CommandMod17=998 1 0 "" 5 0 0 0 0 0
CommandMod18=830 1 46 "" 5 3 0 3 0 0
CommandMod19=909 1 4d "" 5 0 0 0 0 0
CommandMod2=889 3 20 "" 5 2 0 2 0 0
CommandMod20=995 1 0 "" 5 0 0 0 0 0
CommandMod21=944 1 13 "" 5 0 0 0 0 0
CommandMod22=952 1 42 "" 5 0 0 0 0 0
CommandMod23=953 5 42 "" 5 0 0 0 0 0
CommandMod24=954 1 56 "" 5 0 0 0 0 0
CommandMod25=955 5 56 "" 5 0 0 0 0 0
CommandMod26=32777 1 0 "" 5 0 0 0 0 0
CommandMod27=33243 1 0 "" 5 0 0 0 0 0
CommandMod28=912 9 58 "" 5 0 0 0 0 0
CommandMod3=887 3 0 "" 5 0 0 0 0 0
CommandMod4=888 3 0 "" 5 0 0 0 0 0
CommandMod5=890 1 53 "" 5 0 0 0 0 0
CommandMod6=900 1 0 "" 5 0 0 0 0 0
CommandMod7=904 1 be "" 5 18 0 18 4 4
CommandMod8=903 1 bc "" 5 19 0 19 4 4
CommandMod9=898 7 27 "" 5 16 0 16 4 4
```

**Comment by clsid2** [comment]
If you ever get trouble again, then clear that section.

Also, when using INI file, make sure the player has write access to the file. But don't do stupid things such as running the player as admin.

**Comment by xirasu** [comment]
Done that, removed next the media key assignments. Yet issue still persists:

Media keys still work on it. 
If it's assigned and focused, it works directly in the player without Windows' media popup. 
If it's unassigned (focused/unfocused) or assigned and not focused, it works as if you didn't have it focused with Windows' media popup.

Is the box for "[_] Global Media Keys" saved in different section? Wanted to try, if it's not under "Commands2", to delete that.

/edit
Forget that I asked. Found the entry just by searching for "Global"... Anyhow, I deleted that entry "UseGlobalMedia=0", and tried again by checking and unchecking. Same result.

**Comment by clsid2** [comment]
Maybe you mean the Windows playback controls?
Options > Advanced > UseSMTC = false

**Comment by xirasu** [comment]
Uff, yes! Thank you! Didn't know what it's called, but that fixed it!

Was already checking previous releases to see when it first appeared, and after you wrote it, I checked in 1.9.16 for that, which wasn't present. Reinstalled 1.9.16.46 and found it. Turned it to "false", closed, and tested: Issue is fixed.

/edit
Just to clarify: I wasn't using the buttons of "Windows playback controls", but hitting the media-keys I have on my keyboard or assigned on my mouse. Perhaps the keys have access to the playback controls, which is used in mpc-hc when "useSMTC = true". Perhaps that was it.
