### ISSUE TITLE
Please add "Ask before Dr.Dump upload". Reason: Nvidia.

### ISSUE THREAD

**Issue by Joachim-Otahal** [clsid2/mpc-hc#1392]
Reason are dumps like this:
https://drdump.com/UploadedReport.aspx?DumpID=78084725
The actual reason is: nvlddmkm - aka nvidia gfx card driver crashed AGAIN. Windows recovers from it, but as a follow up MPC crashes.
OS: Windows 11 + a user who is annoyed by the "quality" of nvidia drivers.
Another way could be: Give us the chance the revoke or delete the dr.dump upload.

**Comment by clsid2** [comment]
Options > Advanced > EnableCrashReporter = false
