### ISSUE TITLE
A few dialogs can't be resized, at least one dlg doesn't have a scrollbar

### ISSUE THREAD

**Issue by JonasNo** [clsid2/mpc-hc#1393]
Those I know about are:
File->Properties dialog can't be resized.

When opening a rar file with multiple videos in it the video selection dialog can't be resized and it doesn't have a horizontal scrollbar.

**Comment by adipose** [comment]
Fixed in

https://github.com/clsid2/mpc-hc/pull/2680
https://github.com/clsid2/mpc-hc/pull/2683

@clsid2
