### ISSUE TITLE
Portuguese (Portugal) language installer

### ISSUE THREAD

**Issue by hugok79** [clsid2/mpc-hc#1394]
The **Portuguese** or **Portuguese** **(Portugal)** language is missing in the installation process. Currently only **Portuguese** **(Brazil)** is available, as shown in the image below.

I believe the entire translation is complete in Transifex...
Could this feature be added to the installer or is there something missing to make this possible?

![Captura de ecrã 2021-11-09 112402](https://user-images.githubusercontent.com/16929048/140916496-c27761ba-03aa-4ca0-bd0e-b965937770e1.png)

**Comment by clsid2** [comment]
Added.
