### ISSUE TITLE
madvr not loading?

### ISSUE THREAD

**Issue by erickyun** [clsid2/mpc-hc#1396]
![WhatsApp Image 2021-11-10 at 19 38 02](https://user-images.githubusercontent.com/71968711/141154585-edfe578e-f4f2-4fe2-8011-018d61e3ef20.jpeg)

I'm getting this error: the selected video renderer has failed to load.

can someone help please?

this started when I changed folder location from d drive to c drive 
but I did run as admin the bat file don't know why this happend now?

**Comment by clsid2** [comment]
It means madvr is not properly installed.

Open up an administrative command prompt, navigate to the new madvr folder, and manually run this command and see if it is succesfull:
`regsvr32 madvr64.ax`

**Comment by erickyun** [comment]
> It means madvr is not properly installed.
> 
> Open up an administrative command prompt, navigate to the new madvr folder, and manually run this command and see if it is succesfull: `regsvr32 madvr64.ax`

did just try it didn't work?

**Comment by clsid2** [comment]
Another reason for it to fail is if your graphics driver is not working properly. If you moved other software as well, then you also need to re-install those.
Or you did not copy the DirectX files that are bundled with MPC-HC.

Test if EVR-CP works.

**Comment by erickyun** [comment]
> Another reason for it to fail is if your graphics driver is not working properly. If you moved other software as well, then you also need to re-install those. Or you did not copy the DirectX files that are bundled with MPC-HC.
> 
> Test if EVR-CP works.

EVR-CP does work fine.

I did copy the cut paste the whole folder. 

edit:
I did download the portable mpc

**Comment by clsid2** [comment]
If your madvr folder contains a settings.bin file, then remove that.

Otherwise I have no idea what is wrong on your system.

**Comment by erickyun** [comment]
> If your madvr folder contains a settings.bin file, then remove that.
> 
> Otherwise I have no idea what is wrong on your system.

I did try deleting but didnt work?
I did even factory reset my pc but it still didn't work!!!

I do have an portable hard drive installing madvr there fixed the problem? why does my c drive not work?

**Comment by clsid2** [comment]
Maybe the file permissions on your c drive are messed up.
https://winaero.com/reset-ntfs-permissions-windows-10/

**Comment by erickyun** [comment]
> Maybe the file permissions on your c drive are messed up. https://winaero.com/reset-ntfs-permissions-windows-10/

I thank you for your respond.
I did found that madVR doesn't work if the path to its location contains non-latin characters. removing non-latin characters did fix the problem.
