### ISSUE TITLE
Playlist issue. Adding the rest of files in folder don't add them after the chosen file.

### ISSUE THREAD

**Issue by TheSwead** [clsid2/mpc-hc#1398]
When I use "Add containing folder", the rest of files don't add under the file I used to use for adding the rest of files, but they are added at the end of the playlist.
The MPC-HC v1.9.16.36, added the rest of files under the chosen file.
And because I can't select more than 1 file at once, I can't move them to the correct position, after the file that I wanted the rest of the folder from.

To sum it up, when righclick on a file and chose "Add containing folder", the files are added at the bottom of the pkaylist, not where the start-file was.

**Comment by TheSwead** [comment]
MPC-HC v1.9.16..63 was the last version that added the rest of the files added with the option to add the rest of the files in that folder. The later MPC-HC version adds the files AFTER all the files in the playlist. So for me MPC-HC v1.9.16..63 is the last usable MPC-HC.  If I wantes the rest of the files be assed AFTER every other media-files I could have dragged the folder to the playlist. So thanks for the updates to MPC-HC v1.9.16..63, but if this problem is not fixed, the updates after is to no use as the fixes don't mean a thing when I must drag every media-file to the right place, because I can only drag one at a time. An d I like to make a playlist with tv-series, so to move 20 files one at a time is not want I like to do.

**Comment by ctuais** [comment]
Lastest version 1.9.18.35 still doing this, does not work to me neither.
(thanks you, i will use the 1.9.16 o similar..)

**Comment by TheSwead** [comment]
The MPC-HC v1.9.19, still hass these issues with the playlist, adding the rest of the media-files with right click only adds the rest at the bottom, NOT after the initial file. So the playlist is still useless for more then 3-4 files, if you want some sort of adding/sorting. 
I can't see the function for adding the rest of the music/film/videos, if the player add these at the bottom of the list, and not in sorted position.
So the working version is, STILL, MPC-HC v1.9.16..63.
So some code changed, regarding the play-list, changed after MPC-HC v1.9.16..63 that made these horrible issues with this function to add the rest in the folder.

**Comment by clsid2** [comment]
It has not been fixed, otherwise this issue would have already been closed.

I didn't not have time or motivation yet to work on this.

**Comment by TheSwead** [comment]
Sorry if I offended you.
I added things to mark it not fixed yet, because I can't see if the issue has been acknowledged, looked at. I have looked at the difference between v1.9.16..63 and the next "beta", but it's not easy to see. Looked at the playlist-part. Maybe the playlist was affected by other source-updates/fixes.

**Comment by clsid2** [comment]
I know exactly what change caused it. But this issue is low priority for me, so don't expect a fix anytime soon.

**Comment by TheSwead** [comment]
Just an information, MPC-HC v1.9.21.2 still has this issue(s) with the playlist.

**Comment by prre527** [comment]
[update] MPC-HC v1.9.23 still has this issue(s) with the playlist. @clsid2

**Comment by clsid2** [comment]
Replies like the two above will NOT speed up a fix. It will only reduce my motivation.

**Comment by TheSwead** [comment]
For me it's to let people to know that this issue exist in the latest version.
I didn't know that there was any motivation for fixing playlist-issues. You wrote that you know what is doing this, so the knowledge exist, but you maybe don't care about the playlist-function. That's up to you.
But I hope you will fix these issues with the playlist. Because a playlist that put all the added files at the bottom, is not really usefull. It would have been great if the playlist-editing, like moving the movies/songs/audio, several at the same time, but that was not done before. I don't know if something like that would be possible at all. But now I think you have, maybe, abandon this "playlist". Hope not. But I can't update until I can use the playlist. But I hope you stay with this player, as it needs updating/fixes in the future.

**Comment by ketwaroo** [comment]
@clsid2 @TheSwead 

I found the old playlist behaviour more useful too. I submitted PR #1908  for a theoretical fix based on how that playlist feature used to behave vs how it's behaving now.

I can't say I'm a c++ expert by any stretch. I can't even sort out all the missing dependencies to get it to build locally.

**Comment by TFWol** [comment]
@ketwaroo Thanks for trying; I don't know c++ to even start to help.

I do miss the feature the way it was. Turns out I used it _way_ more than I realized; I tend to open files from the jumplist and do a quick 'add containing folder' for an instant ordered list without needing to bother with launching an Explorer window for manual drag and drop.

**Comment by clsid2** [comment]
There is a "Sort by Path" option the playlist right-click menu. That should help for most of you.

I do not have any motivation to work on this in coming months. Do NOT reply with messages on how important this feature is for you. That will lead to an immediate close and it will NEVER be fixed.

**Comment by adipose** [comment]
I've attempted to find a solution to this here: https://github.com/clsid2/mpc-hc/pull/2307
