### ISSUE TITLE
Feature Request: Shortcut Key to Toggle Subtitle Default Style

### ISSUE THREAD

**Issue by frankrizzo1687** [clsid2/mpc-hc#140]
I like to use my own style of subtitles most of the time but sometimes I would like to be able to switch back and forth to the file's style temporarily and would like to be able to do this without having to navigate the menu, thank you.

**Comment by adipose** [comment]
Test build here:  https://mega.nz/#!UABBzKrJ!R4hjvZjIBJnXplBhE4y5IQiWiwxoHTas6O2H_OL8zjg

https://github.com/clsid2/mpc-hc/pull/209

You will have to assign a shortcut key here:

![image](https://user-images.githubusercontent.com/3324395/71712872-09382f00-2dbc-11ea-8ee2-c54d42f19811.png)

**Comment by frankrizzo1687** [comment]
Works fine for me, no OSD notification if it even matters to anyone, I appreciate you taking the time to fill my request, thank you
