### ISSUE TITLE
subtitle not reloaded after the new improvement with very long pause

### ISSUE THREAD

**Issue by ronkwann** [clsid2/mpc-hc#1401]
Win 10 x64, mpc-hc 1.9.17 x64

with the new : " The player now reloads the video file when resumed after hibernate or very long pause (> 30 min). This is done as a workaround for driver bugs. It will remember playback position and track selection. "

it's a great improvement, it works for me but it doesn't remember the subtitle *(in my case, an external .srt file) that previous loaded.  it would be great if mpc-hc could remember or reload the subtitle along with the video after a long pause.

much thanks.

**Comment by clsid2** [comment]
It currently doesn't always update the file history when an external sub is added. That part of the code is probably going to get rewritten soon, so this issue can get fixed then.

**Comment by clsid2** [comment]
Fixed

**Comment by WakeXT** [comment]
Downloaded subtitles (meaning after pressing the D-key) still disappear in 2.0.0 after the reload - is there an option I could set to remedy this behavior (storing it temporarily so it gets reloaded or similar)?
