### ISSUE TITLE
Is there a HDR correction for playing HDR videos on non-HDR screens?

### ISSUE THREAD

**Issue by Damthe** [clsid2/mpc-hc#1402]
I own a basic monitor which doesn't have native HDR support. But i've read some players do have a correction methods but i couldn't find the option in MPC-HC? Sorry if i have missed something but any help would be greatly appreciated? I always try to go with non-HDR videos but sometimes they are unavailable.

**Comment by clsid2** [comment]
Install this renderer and select in in MPC-HC output options:
https://github.com/Aleksoid1978/VideoRenderer

**Comment by Damthe** [comment]
Thank You!

**Comment by SanderBouwhuis** [comment]
Totally awesome!!! Thanks for the renderer.
