### ISSUE TITLE
Portuguese (Portugal) language interface

### ISSUE THREAD

**Issue by hugok79** [clsid2/mpc-hc#1403]
Although the installer already appears with the **Portuguese** **(Portugal)** language, by the way, thanks again https://github.com/clsid2/mpc-hc/issues/1394,
when i start MPC-HC for the first time the default language is Portuguese (Brazil)!!! That is, I have to go to the options to change the interface language to **Portuguese** **(Portugal)** manually.

**Comment by clsid2** [comment]
It selects the default language based on the LocaleID in Windows.
Brazil = 1046
Portugal = 2070
That might be set wrong on your system.

**Comment by hugok79** [comment]
I don't think that's it, my system is in Portuguese (Portugal)

![Captura de ecrã 2021-11-13 131939](https://user-images.githubusercontent.com/16929048/141645382-5679a5c6-9e79-4f69-b25d-b185cfa34ccc.png)
![Captura de ecrã 2021-11-13 132045](https://user-images.githubusercontent.com/16929048/141645388-98997cef-84c0-41df-811d-7ac37cb2862d.png)

**Comment by clsid2** [comment]
Try resetting settings:
MPC options > Miscellaneous > Reset

**Comment by hugok79** [comment]
Yes, that worked. (But why didn't this happen the first time I started mpc-hc?)
In fact, only now popped up the "periodically check for updates to MPC-HC" window/dialog. 
The first time I did the fresh installation that window/dialog didn't pop up... usually appears after starting MPC-HC for the first time
![Captura de ecrã 2021-11-13 135659](https://user-images.githubusercontent.com/16929048/141647714-a955b9a9-e491-4d79-8589-180850f759f8.png)
!

**Comment by clsid2** [comment]
It means that you already had old settings in the Registry on your initial installation. Possibly because you have multiple user accounts on your computer. The uninstaller is only able to remove the settings of your admin account.

**Comment by hugok79** [comment]
I've made a new install of MPC-HC in a fresh installation of Windows 10 and after selecting the Portuguese (Portugal) in the installer, the interface in the first start appears in Portuguese (Brazil) instead of Portuguese (Portugal).... I've had to change the language manually!
This is not fixed after all!

**Comment by clsid2** [comment]
Fixed

**Comment by hugok79** [comment]
Thank you!

**Comment by hugok79** [comment]
I also made some improvements to the Portuguese (Portugal) translation...
See https://github.com/clsid2/mpc-hc/pull/1624

**Comment by hugok79** [comment]
@clsid2 It would be nice to do a transifex sync (mpc-hc/src/mpc-hc/mpcresources/PO/) since I have also done some Portuguese (Portugal) improvements there(Transifex).
