### ISSUE TITLE
Make the time always visible in seek bar preview

### ISSUE THREAD

**Issue by williamsp** [clsid2/mpc-hc#1404]
Currently, when the video has a long chapter name, the time is not visible because the text is center aligned
Maybe we can make the text left aligned, or implement a word wrap, or just truncate the text and add ellipsis?

Screenshot:
![image](https://user-images.githubusercontent.com/3760416/141690417-5a9f45fa-d4e2-4bd1-ab56-9a6acbe54157.png)

**Comment by clsid2** [comment]
Fixed
