### ISSUE TITLE
Weird artifacts/patterns in 4K MKV videos on 1080p screen

### ISSUE THREAD

**Issue by TinyTrbl** [clsid2/mpc-hc#1405]
Hello i am not sure if this issue really related to MPC-HC or internal LAV codecs or video scaling(?) but i have some really weird artifacts (or more like patterns) while playing 4K videos on my 1080p display both in windowed and full-screen modes.

This happens mostly with black (easy to spot on ending titles) or really dark scenes.

Here are some unaltered examples (you can barely see these artifacts here, not sure if you will able to see them on IPS monitors, i have VA monitor so i can see them...):
![1](https://user-images.githubusercontent.com/45721596/141693456-ca140876-7880-4ed1-8248-9da7e60b61d0.png)
![2](https://user-images.githubusercontent.com/45721596/141693458-f81eefd2-5eae-4f97-b3c8-74e08a897c8d.png)
![3](https://user-images.githubusercontent.com/45721596/141693459-52e35215-cbda-4266-8295-9e1240f8a8ba.png)

Here are altered versions with bumped contrast:
![1altered](https://user-images.githubusercontent.com/45721596/141693578-4a517381-537c-4437-ba0d-4cf0c78a2256.png)
![2altered](https://user-images.githubusercontent.com/45721596/141693579-375bec91-55f0-41f6-babc-741d391292f2.png)
![3altered](https://user-images.githubusercontent.com/45721596/141693581-45de4bbf-533b-4a38-ae19-da4781b8bdbd.png)

Funny thing is that you cannot see them on screenshots captured with CTRL+I and they are changing rapidly (from BIG circles to small ones for example) if you scale the player window with your mouse, so they are not static. Also they are blinking really fast as video scenes changes.

(I have tried MPC-BE but the results were quite similar.)

Does anyone know a possible source of these artifacts or how can i remove them?

**Comment by clsid2** [comment]
Not fault of player or the internal codecs.

Almost certainly a driver problem. If you have an Intel GPU, then you should disable Contrast Enhancement in the driver settings. I can't provide any help with drivers.
