### ISSUE TITLE
Loading subtitles fails when mkv has subtitle tracks inside

### ISSUE THREAD

**Issue by pyrescene** [clsid2/mpc-hc#1406]
I have an MKV with English srt forced subtitles included.

Loading or dragging idx/rar, idx/sub, srt, ... fails: "Failed to load subtitle file"

Loading online subtitles with "Download Subtitles..." works.

Expected behavior: all subtitles are loaded again :)

Options -> Subtitles -> Misc
First three checkboxes are checked.

**Comment by clsid2** [comment]
Must be a wrong setting on your end.

Check if you have selected a compatible video renderer:
Options > playback > output

**Comment by pyrescene** [comment]
I'm using madVR. Switching to Enhanced Video Renderer makes the above case work.

Is this a madVR bug? Loading subtitles when the mkv doesn't contain them works fine otherwise. They work fine too when I choose one from the mkv. How is it possible the downloaded subtitle with mpc-hc shows but loading one already on my disk fails?

**Comment by clsid2** [comment]
Works normally for me with madVR.
Did you perhaps did something weird such as adding madVR to external filters (which is wrong).

**Comment by pyrescene** [comment]
madVR in combination with the Internal Subtitle Renderer works!
It was set to VSFilter / DirectVobSub. External filters are empty.

Loading an external subtitle makes the original choices from the mkv in the subtitle menu disappear. (minor issue)

I have subtitle auto loading set up. It didn't work (not showing in the Subtitles menu) but I had to look at the dvobsub tray icon to switch tracks. It also failed because the settings line ended with a **;**

Now with this working setup the auto loading of external subtitles fails when the mkv has subtitles included.  The options "Prefer external subtitles over embedded subtitles" and "Ignore embedded subtitles" are checked so I would expect them to show up in the list. Now none is showing (per setting) but I only see the included subtitles.

**Comment by clsid2** [comment]
Manually loading subs only works with the internal renderer. That is not a bug. External filters have to take care of loading subs themselves.

You should not be using VSFilter because it is inferior compared to internal renderer.

It is unnecessary to enable "ignore embedded subs". It is also the cause why the embedded ones get hidden once you load an external one.

**Comment by clsid2** [comment]
It is better to adjust the settings in the internal Splitter to disable embedded subs by default. Then you always still have the ability to select them in case you do want to display those subs.
