### ISSUE TITLE
1.9.17 - Thumbnail preview issue

### ISSUE THREAD

**Issue by bobsage123** [clsid2/mpc-hc#1407]
When I hover over the slider to see a preview thumbnail, it always shows this broken error image for about a second before showing me the preview. This only started happening to me in 1.9.17.

![image](https://user-images.githubusercontent.com/20603861/141704964-4c819d15-ab30-4f2b-ae6a-0a92cd7f73e1.png)

**Comment by clsid2** [comment]
That is intentional as indication that it is still loading the thumb.
