### ISSUE TITLE
[Bugreport] MPC-HC stopped working on multiple screen

### ISSUE THREAD

**Issue by Feriman22** [clsid2/mpc-hc#141]
I found a possible bug in MPC-HC 1.8.8 and older versions as well.

Follow these steps to reproduce this bug and crash the software:

1., Use multiple screen (I use two screens is mirror mode)
2., Play one video with MPC-HC
3., Disconnect one screen
4., MPC-HC crashed

I tested it with notebook and one connected external display. In this case I closed the notebook for disconnect the screen. OS is Windows 10.

**Comment by clsid2** [comment]
This might help:
Options > Playback > Output > Reinitialize when changing display

**Comment by Feriman22** [comment]
Unfortunately it didn't help. Still frozen.

**Comment by clsid2** [comment]
I don't have a solution for you.

**Comment by Feriman22** [comment]
Can you reproduce this bug?

**Comment by clsid2** [comment]
I have not attempted to reproduce. My laptop also doesn't have a connector for external screen.

I don't have the time and expertise to fix every bug that is reported.

**Comment by adipose** [comment]
I have seen a similar bug, where when launching MPC-HC over RDP, if RDP is not in the foreground when it launches, it crashes.  I suspect because it can't "find" the "monitor."  I will try to repro when I get around to it.

**Comment by clsid2** [comment]
A similar issue also exists with resuming playback after sleep/hibernate.

**Comment by Feriman22** [comment]
@clsid2  I would like to send a debug log here. How can I turn on debug in MPC-HC and where is this log file?

**Comment by adipose** [comment]
I was unable to reproduce this error by disconnecting a second screen (both in mirror and extend mode).  Closing the notebook is more than just disconnecting a screen, though--it could cause other changes.  I did try closing the notebook and this did not crash it, either--but at the time I didn't have an external display connected.

**Comment by clsid2** [comment]
There is no debug logging for this.

What you can do is:
Don't close the player when the crash message is shown. Open the Windows Task manager, right-click on the mpc-hc process and select "Create Dump File". Zip/rar that file and upload it somewhere. It might give us some clues where in the code the crash happens.

**Comment by adipose** [comment]
@clsid2 
I reproduced it.  It is due to GetAdapterDisplayModeEx returning D3DERR_NOTAVAILABLE, which is normal when the display has changed (https://docs.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9-idirect3d9ex-getadapterdisplaymodeex).

Also, Intel is a common video adapter on laptops, and it seems it has been hardcoded to not allow resetting.  I have a solution for both that worked in testing.

See here: https://github.com/adipose/mpc-hc/compare/patch6...adipose:patch7?expand=1

**Comment by clsid2** [comment]
Great. Some comments:
1) That whole code block to get nPCIVendor can be removed if its no longer needed.
2) I don't think the fallback of using D3D9b_SDK_VERSION is needed anymore since XP is no longer supported.
3) In the added code there should be a NULL check for m_pD3DEx before calling m_pD3DEx->GetAdapterDisplayModeEx

**Comment by Feriman22** [comment]
@clsid2 I created a dump file. You can download from these links:

Uncompressed (406.6MB) - mpc-hc64.DMP
https://mega.nz/#!uwwXEK4a!VLI-yKc3FDyZwkbiomhKIEIr0HL6Atm3eEPWDQIdOxM

Compressed (62.5MB) - mpc-hc64.7z
https://mega.nz/#!CkxTESYR!qiEq6U-4vhsK-VycgDbQVh5MnuCOlv8omcmAsjtFD-8

@adipose Thank you for your effort! :)

**Comment by adipose** [comment]
> 
> 
> Great. Some comments:
> 
>     1. That whole code block to get nPCIVendor can be removed if its no longer needed.
> 
>     2. I don't think the fallback of using D3D9b_SDK_VERSION is needed anymore since XP is no longer supported.
> 
>     3. In the added code there should be a NULL check for m_pD3DEx before calling m_pD3DEx->GetAdapterDisplayModeEx

All done.

https://github.com/clsid2/mpc-hc/pull/152

**Comment by clsid2** [comment]
Here is latest build of MPC-HC for testing the fix:
https://www.sendspace.com/file/3wsrqn

**Comment by Feriman22** [comment]
Working well, thank you! :)
