### ISSUE TITLE
Characters displayed in the playlist

### ISSUE THREAD

**Issue by cirruswazza1** [clsid2/mpc-hc#1411]
This is just a display bug (MPC HC works perfectly despite the point raised)

1/ when drag and drop files or adding files via the right click in explorer, the files appearing in the playlist respect the case of the file visible in the explorer
eg:
Name in explorer --> Name in Playlist
My File Number 1 --> [1] My File Number 1
My FILE Number 2 --> [2] My FILE Number 2
My File NUMBER 3 --> [3] My File NUMBER 3

2/ when dragging and dropping a folder, only the first file is case sensitive, the next ones are in lower case
eg:
Name in explorer --> Name in Playlist
My File Number 1 --> [1] My File Number 1
My FILE Number 2 --> [2] my file number 2
My File NUMBER 3 --> [3] my file number 3

The OSD also displays the same thing as the playlist so in case 2/ the other files are displayed in lower case except the first file

**Comment by clsid2** [comment]
Fixed
