### ISSUE TITLE
Unintentional lowercasing of files in playlists

### ISSUE THREAD

**Issue by zoidbergthepopularone** [clsid2/mpc-hc#1413]
Commit 166ebe5934933b65b8ab26e3c95e3ddda52b01c6 introduced what I take is an unintentional error, which causes lowercasing of playlist items. E.g. if you run MPC-HC for a whole directory:
```
mpc-hc.exe c:\music
```
the first filename will get loaded with the correct case but all other files will have their filenames lowercased. That can be a problem with files stored on Linux-based NAS devices, for example. 

The attached patch (for 02afc1fc5b7a8735716c5b9a519b33c5945d3daf) should fix it.
[0001-Fixed-unintentional-lowercasing-of-all-filenames.patch.zip](https://github.com/clsid2/mpc-hc/files/7554652/0001-Fixed-unintentional-lowercasing-of-all-filenames.patch.zip)

**Comment by clsid2** [comment]
Fixed. Thanks.
