### ISSUE TITLE
Files in playlist open in fullscreen - versions greater than v1.9.8

### ISSUE THREAD

**Issue by NoEscape** [clsid2/mpc-hc#1414]
When the fullscreen option "Launch files in fullscreen" is enabled, files in playlist will open fullscreen even if you switch to windowed mode. This behavior differs from version 1.9.8 and earlier.

Steps to reproduce with any version above v1.9.8:
1. - Start MPC-HC. Enable Playback - Fullscreen option "Launch files in fullscreen"
2. - With MPC-HC in Windowed mode drag and drop a folder containing several video files, a selection of several video files or a playlist.: **Video will open fullscreen.**
3. - Switch to Windowed mode (alt-enter)
4. - Skip to next file in playlist: **Video will open fullscreen**
5. - repeat steps 3 and 4: **Video will open fullscreen**

Behavior in v1.9.8 or earlier
1. - as above
2, - Video opens. MPC-HC: **stays in windowed mode**
3. - not necessary as already in windowed mode.
4. - next video opens: **stays in windowed mode**
5. - repeat steps 3 and 4 - **stays in windowed mode**
 
In version 1.9.8 or earlier the only time MPC-HC will launch a video fullscreen is a the program launch time (e.g. MPC-HC is not running or loaded into memory).
Example: with MPC-HC closed/shut down double-click on a video or a playlist in Windows. MPC-HC will launch in fullscreen mode.

This new behavior is disruptive in many situations such as side-by-side viewings. Either restore the behavior or give an option to use the old behavior.

**Comment by clsid2** [comment]
I am not going to fix this because that would break launching files in fullscreen when opening from Explorer when player is already active. I don't have any motivation at all to create all kinds of workarounds and extra options.

If you don't want to launch in fullscreen, then disable the option and manually go to fullscreen whenever you need it.
