### ISSUE TITLE
[Feature Suggestion] Remember pan/scan after long pause or hibernation

### ISSUE THREAD

**Issue by iliketodev** [clsid2/mpc-hc#1415]
when the player reloads the video file when resumed after hibernate or very long pause, it already remembers playback position and track selection, i wish it would also remember the pan&scan setting :)

edit : oh and also when switching to the next file in the folder, or when drag&dropping another file into an open player, even when the option setting is disabled (previously the player did remember the pan&scan zoom in those cases)

**Comment by clsid2** [comment]
Use the option to remember last pan&scan zoom.

**Comment by iliketodev** [comment]
first, thanks for the answer.
then, i'm sorry for my english, i expressed poorly...
it's not even a functionality suggestion i'm so sorry...
i try again :

> **Title** : Change of behavior in the "Remember last Pan & Scan Zoom" functionality

> **Version where the change occurred** : 1.9.11 and after

> **In what case the behavior stayed the same** : when the setting is modified from the "Options..." dialog box (i.e. persistent setting that applies to all new player instance)

> **In what case the behavior changed** : when the setting is modified from the "Pan & Scan" menu or shortcut Keys (i.e. temporary setting that applies to the current player instance only)

> **Old behavior** : the setting was applied to the current player instance, _**for its entire lifetime**_ (i.e. when you switched to the next file in the folder or drag&dropped a new file, it applied to it)

> **New behavior** : the setting is applied to the current player instance, _**but only for the current open file**_ (i.e. when you switch to the next file in the folder or drag&drop a new file, it does NOT apply to it anymore, and nether after the "long pause or hibernate" file re-open)


to better understand what i'm talking about, lets say the same change happened in the "After Playback" functionality : the new behavior would mean you have to set the temporary setting "After Playback > Play next file in the folder" again after _**every**_ next file...

i hope i am more understandable now
thanks :)

**Comment by clsid2** [comment]
The old behavior was incorrect. There is no guarantee that next file is similar to the current one. It could have completely different size and aspect ratio, so blindly re-using P&S settings is just wrong. I am not going to revert to old behavior.

What is the original video size, what P&S setting do you apply and why? There might be a better solution to achieve the same result...

**Comment by clsid2** [comment]
I assume you are playing a series? I might consider implementing something that compares filenames and if they are almost identical, remember some stuff.

**Comment by iliketodev** [comment]
yes that's exactly what it is, watching a TV show with many episodes, in full screen, but when the quality of the files is too low, I use "Pan & Scan > Decrease Size" until I dont see the low quality anymore...
my usage of this only concerns some features of the "Pan & Scan" functionality, namely full resizing or panning, and not aspect ratio or 16:9 or anything like that.
but I understand that the old behavior is wrong is the cases you mention, so I believe you know best what to do !
but on the other hand, in the case where this change happen when re-loading the file after the "long pause or hibernate", it is wrong 100% of the time I believe :D
thanks :)
