### ISSUE TITLE
[Minor Bug] Showing operating system as Windows 10 instead of Windows 11 in the About dialog box

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1416]
## Description
When I select about from the help menu it is showing the operating system as Windows 10 when it is running on Windows 11.

**Comment by clsid2** [comment]
Windows 11 is technically still version 10.0, so the information displayed is actually correct. But I will think about adjusting the displayed name for clarity.

**Comment by clsid2** [comment]
Fixed
