### ISSUE TITLE
Bug: "Play next file in the folder" is ignored

### ISSUE THREAD

**Issue by tmssngr** [clsid2/mpc-hc#1419]
Since a couple of builds there is following bug:
- have a directory with multiple .mp3 files
- double click one to open MPC-HC which will start playing it
- option "Play | After Playback | Play next file in the folder" is selected
- after playing the double-clicked mp3 file, it will not start the next file in the folder, but instead restart the same file
- however, pressing "Skip Forward" will play the next file in the folder

**Comment by clsid2** [comment]
I just created a test folder with three mp3 files. It correctly moves to next file here after playback end.

Maybe you have enabled the repeat file option?

**Comment by tmssngr** [comment]
Yes, sorry, repeating the playlist was selected. Not very obvious this combination.

What happens when repeat is unselected and the last mp3 in the folder was played? Will that repeat automatically or just stop?

**Comment by clsid2** [comment]
It can loop folder optionally:
Options > Advanced > LoopFolderOnPlayNextFile
