### ISSUE TITLE
Is it possible to block the PC standby during playing ?

### ISSUE THREAD

**Issue by Dim3333** [clsid2/mpc-hc#1421]
Hello,

I don't find in options the possibility to block the PC standby during playing.

Does this option exist?

Thanks

**Comment by clsid2** [comment]
It automatically blocks the screensaver during playback. There is no option.

**Comment by Dim3333** [comment]
During playing music, I would like to stop the standby of my computer.

The standby of my computer is set to 10 minutes.  After 10 minutes, my computer goes to sleep and the music stops.

**Comment by clsid2** [comment]
I should already prevent Windows from going into sleep mode when idle. I just tested on my laptop with an audio file and it works correctly.

**Comment by Dim3333** [comment]
Not sure to understand well....
I don't want to modify the Windows sleep parameters each time that i listen music.
Is it not possible to include in MPC-HC, an option to desactivate the windows sleep mode ?

**Comment by clsid2** [comment]
It already tells Windows that it should not go into sleep.

If it does not work on your computer, then I can not help you.

**Comment by Dim3333** [comment]
OK thanks, so it doesn't works on my Windows 11.
Is it a bug from MPC-HC ?
Why have you closed this discussion, i would like to know if other people have the same problem ?

**Comment by clsid2** [comment]
It is not a bug in MPC-HC. It uses the correct Windows API for signaling to Windows that it should not sleep. If Windows decides to do otherwise, it is a bug in Windows.

It is closed because it works for me on Windows 10. Others can still reply even when an issue is closed.

**Comment by Dim3333** [comment]
OK, thanks again @clsid2

**Comment by bw4518** [comment]
Since you closed (https://github.com/clsid2/mpc-hc/issues/3235) for comments, the use case might be e.g. listening an audiobook, or similar, it is basically the same issue pointed out here by @Dim3333. I understand it's low-priority at best, I just wanted to clarify it isn't a Windows setting issue.

**Comment by clsid2** [comment]
IT IS A WINDOWS SETTINGS ISSUE BECAUSE YOU CAN JUST FUCKING DISABLE SLEEP MODE ALTOGETHER IN THE FUCKING WINDOWS SETTINGS. SLEEP MODE IF FOR STUPID BOOMER PEOPLE.
