### ISSUE TITLE
Seek Bar Responsiveness from 1.9.8 onwards

### ISSUE THREAD

**Issue by MPC-HC-Fan** [clsid2/mpc-hc#1422]
Between 1.9.7 and 1.9.8 the seek bar took on an unpleasant laggy or delayed behaviour when seeking with quick mouse drags.
I think the change happened here on 23 Oct 2020:
[PlayerSeekBar.cpp](https://github.com/clsid2/mpc-hc/commit/d1ca4ddbf50d124de176f2353e58481210aabf86)
"Finetuned the behavior when clicking/dragging the seekbar. This should fix an issue where two simultaneous seeks could be done"

Seeking in 1.9.7.96 (7a65 f9990-dirty)
![Version 1 9 7 96 (7a65f9990-dirty)](https://user-images.githubusercontent.com/94777863/142754937-2e2a7f70-436b-4ad3-8442-7e69348f8921.gif)

Seeking in 1.9.8.11 (3a56 c2fcb)
![Version 1 9 8 11 (3a56c2fcb)](https://user-images.githubusercontent.com/94777863/142754933-4e8d43c3-14df-4b0f-8ad7-633d8b92b1c9.gif)

I love MPC-HC, thanks for all the hard work!

**Comment by clsid2** [comment]
It isn't less responsive. It just better shows what is actually happening. You should click instead of drag if this annoys you. Or get a faster computer.

What kind of file are you playing? Can you upload it for me?

**Comment by clsid2** [comment]
Try this test build:
https://www.sendspace.com/file/6irax8

**Comment by clsid2** [comment]
I have changed its behavior to follow the mouse pointer instead of reflecting the actual seek actions during a drag.

**Comment by MPC-HC-Fan** [comment]
* Sorry, not less responsive, I understand more now
* It seems to better show the current drag position but doesn't stay at the mouse click up position
* I'll can try to click from now on but I've enjoyed dragging this way for 10+ years
* Faster computer probably won't help, tested two PC including decent gaming PC (RTX 3070)
* Same with all audio/video files tested including the demonstration mp4 attached here

Here's a much better screen recording to show the different seek behaviours
6 instances, 3 release versions:
Left two 1.9.7 - Middle two 1.9.8  - Right two: the test build "Drag Test" you sent

If you can, download and check it at 0.125x speed to really see the action

https://user-images.githubusercontent.com/94777863/142985284-b6469def-f407-4c8e-8f11-20014c1e8aef.mp4

**Comment by clsid2** [comment]
Try the 1.9.17.10 development build. That contains the new change I mentioned yesterday.

**Comment by MPC-HC-Fan** [comment]
Seems to be improved but still doesn't consistently stay at the the correct mouse-up seek position when seeking with quick mouse drag movements.
Most noticeable when a user attempts to quickly seek to the beginning:
https://user-images.githubusercontent.com/94777863/143234124-255b6655-dbaa-4ad6-80ca-56b7cd092afb.mp4
