### ISSUE TITLE
1.9.17 breaks /play

### ISSUE THREAD

**Issue by bptrsn** [clsid2/mpc-hc#1423]
Hey, I have a "Play in MPC" right click menu item allowing me to right click on a directory with a rarset inside which contains a video file.

This has always worked, and works in 1.9.16 but stops working in 1.9.17.
The .reg file to add said right click menu item looks like the following:

```
Windows Registry Editor Version 5.00 

[HKEY_CLASSES_ROOT\Directory\shell\MPCLink]
@ = "Play in MPC"
[HKEY_CLASSES_ROOT\Directory\shell\MPCLink\command]
@ = "\"C:\\Program Files\\MPC-HC\\mpc-hc64.exe\" \"%L/*.rar\" /play"
```

Hope it's an easy rollback,
cheers.

**Comment by clsid2** [comment]
Fixed.
