### ISSUE TITLE
[Feature request] Fixed window position cmd-line parameter

### ISSUE THREAD

**Issue by TechTrooper** [clsid2/mpc-hc#1424]
Hello,

MPC-HC already has some useful parameters for multi-monitor setups like "/monitor # /fixedsize x y".
Would it be possible to add parameter e.g. "/fixedposition" with x,y coordinates on monitor?

We also have a setting to remember last window position, so perhaps fixed window position setting might be feasible?

It's a bit niche use case and I understand if there's no interest to look into it.

**Comment by zoidbergthepopularone** [comment]
In my custom build, I use something a little bit similar - a command-line option to put MPC-HC into a specific screen corner. Precise coordinates are not interesting for me, but the corner is. Perhaps it would be sufficient for your needs? (Note that as I am not on a multi-monitor setup, I am not certain my solution would work in that scenario.)

**Comment by TechTrooper** [comment]
> In my custom build, I use something a little bit similar - a command-line option to put MPC-HC into a specific screen corner. Precise coordinates are not interesting for me, but the corner is. Perhaps it would be sufficient for your needs? (Note that as I am not on a multi-monitor setup, I am not certain my solution would work in that scenario.)

Sure, screen corner could work too.
I've seen some powershell examples to do the same, but most script examples seemed to be incomplete and a tad too complex to be worth the trouble.

**Comment by zoidbergthepopularone** [comment]
This patch (intended for commit c805ff0b79b2417403ca04637430aa7fa680be25) implements an optional positioning of the MPC-HC window during startup using the `/fixedsize w,h[,pos]` syntax (where the optional `pos` argument can be `topleft`, `topright`, `bottomleft`, `bottomright`, `center`).
[0001-Command-line-argument-for-initial-positioning-of-the-main-window.zip](https://github.com/clsid2/mpc-hc/files/7669216/0001-Command-line-argument-for-initial-positioning-of-the-main-window.zip)

**Comment by TechTrooper** [comment]
> This patch (intended for commit [c805ff0](https://github.com/clsid2/mpc-hc/commit/c805ff0b79b2417403ca04637430aa7fa680be25)) implements an optional positioning of the MPC-HC window during startup using the `/fixedsize w,h[,pos]` syntax (where the optional `pos` argument can be `topleft`, `topright`, `bottomleft`, `bottomright`, `center`). [0001-Command-line-argument-for-initial-positioning-of-the-main-window.zip](https://github.com/clsid2/mpc-hc/files/7669216/0001-Command-line-argument-for-initial-positioning-of-the-main-window.zip)


Thanks. I wonder if it would be possible to get this code committed? Can you do a pull request?
I have absolutely no idea how to build this with the patch file.

**Comment by adipose** [comment]
Can be closed.

Position is x,y instead of the relative areas.
