### ISSUE TITLE
Increase EVR Buffers beyond 60

### ISSUE THREAD

**Issue by xknat** [clsid2/mpc-hc#1425]
Hey there!

I watch from a nas over a bit of latency network.
I did look up https://superuser.com/questions/842203/how-to-make-mpc-hc-to-cache-more-aggressively and was wondering if you can maybe add a feature to increase EVR (options -> playback -> EVR Buffers) would be helpfull.

**Comment by clsid2** [comment]
Renderer is at the end of the playback chain. You want to buffer at the beginning, meaning in the splitter. You can find a queue setting in the internal splitter. Increase those values and it will buffer more data.
