### ISSUE TITLE
The option to disable auto reload after pause is broken.

### ISSUE THREAD

**Issue by JSCFORCE** [clsid2/mpc-hc#1426]
I first tried changing it in the advanced options section, no dice.

I even tried manually editing the ini file

ReloadAfterLongPause=0

It just resets back to

ReloadAfterLongPause=30

when I close the video player.

Thank you for the most amazing windows video player of all time.

I install it on every computer I come in contact with. (hundreds)

P.S. I have version 1.9.17.16

**Comment by clsid2** [comment]
Fixed

**Comment by JSCFORCE** [comment]
Thank you!
