### ISSUE TITLE
Internal subtitles have HTML span tags

### ISSUE THREAD

**Issue by JonasNo** [clsid2/mpc-hc#1427]
I've checked the extracted srt file and no span tags was found. When I used the extracted subtitle file the span tags disappeared. Maybe some extra data is not extracted when using ffmpeg to extract the subtitle? I've tried to view the internal subtitle with View->subresync but that displays nothing.

Command used to extract the subtitle:
`ffmpeg -i Cowboy.Bebop.2021.S01E02.mkv -map 0:s:0 subs.srt`

This screenshot was taken at time code 02:43.
![MPC-HC - Cowbot Bebop episode 2 - broken subtitles](https://user-images.githubusercontent.com/770975/143673837-3ef99f17-1c1c-4e72-bd10-259426024581.PNG)

The extracted subtitle:
[Cowboy.Bebop.2021.S01E02 - sub English.srt.zip](https://github.com/clsid2/mpc-hc/files/7611448/Cowboy.Bebop.2021.S01E02.-.sub.English.srt.zip)

**Comment by clsid2** [comment]
I need a link to the original video file.

**Comment by JonasNo** [comment]
I'm unsure if any of the original links still work. Please remove this post when you have grabbed it. This site really needs a for the project members eyes only feature.
```
File name: Cowboy.Bebop.2021.S01E02.Venus.Pop.720p.10bit.WEBRip.2CH.x265.HEVC-PSA
https://psarips.top/tv-show/cowboy-bebop-2021/


Here's a fresh one just in case. You have 29 days from 2021 Dec 08 to grab the one below.
Link: https://easyupload.io/llh5sb
password: clsid2
```

**Comment by clsid2** [comment]
Got your file. The span tags are not shown here. Make sure that you are using the latest version of MPC-HC. Also be sure to use the internal subtitle renderer, and not external one such as VSFilter or XySubFilter.
