### ISSUE TITLE
''Move to Recycle Bin'' doesn't automatically play the next file in playlist

### ISSUE THREAD

**Issue by hashimaziz1** [clsid2/mpc-hc#143]
Hi,

I initially tried to post these bugs on Trac, but kept on getting a Cloudfare error that said I'd been blocked from accessing mpc-hc.org?

I'm using the MPC-HC 1.8.8 that's bundled with the latest version of the K-Lite Codec Pack, on Windows 7.

**Bug 1**

This one is the most severe.

When using Windows Media Player to select all of the individual music files in a folder and then right-clicking and clicking Play or any of the WMP context menu items to open the files, Windows Media Player will open these files as if they were opened in a playlist, allowing skipping and shuffling between them. 

Selecting the same set of files and right-clicking and clicking ''Play with MPC-HC'' or ''Add to MPC-HC playlist'' causes probably the most fatal freeze-up I've ever seen on my system in recent years, which is saying something. I've never had Ctrl+Shift+Esc for the Task Manager refuse to run before, but the tons of resulting C++ exception errors and "Do you want to report this?" prompts? - likely because it's trying to open each file individually - overwhelmed my system so much that the only way to end it is to hold down the power button.

**Bug 2**

When right-clicking on a folder and selecting the ''Play with MPC-HC'' context menu item, the files will play, but deleting a file from the playlist with ''Move to Recycle Bin'' doesn't automatically play the next file as is the usual behaviour. 

These bugs combined mean that the ONLY way to add files in a folder to a playlist with the ability to naturally delete files and have them keep autoplaying is to use the ''Add to MPC-HC playlist'' context menu item on a folder, and even this takes much longer than selecting all the files and playing them with Windows Media Player.

**Comment by clsid2** [comment]
Windows has a 15 file limit for opening files. So I assume you have increased that value with the MultipleInvokePromptMinimum Registry tweak.

Yes, it invokes the .exe multiple times. That is how Explorer works. Blame Microsoft. Only way around it is to put a shell extension in between. I am not interested in that at this moment.

The player has code to direct everything to the first instance. It works fine for me even with a large number of files. If it is unstable for you, then you are unlucky. I am not able to fix it.

One workaround is to open MPC-HC and then drag&drop the files onto it. Current playlist will be replaced with the selection of files. Same can be achieved as well by adding MPC-HC to the "send to" menu in Explorer.
C:\Users\[username]\AppData\Roaming\Microsoft\Windows\SendTo

**Comment by adipose** [comment]
@Kaos-Industries 

I tested the behavior of the folders, and I don't have this bug.

I added a folder to mpc-hc, then deleted the playing video (move to recycle bin).  It played the next video immediately.

I added a folder to mpc-hc, then deleted the next video (move to recycle bin).  It played the video after the deleted video once it finished the current video.

Can you give more info on how to reproduce this bug?

**Comment by adipose** [comment]
@clsid2 , can you repro bug 2 here?  I cannot.

**Comment by clsid2** [comment]
Nope, works correctly here.
