### ISSUE TITLE
Massive .srt subtitles

### ISSUE THREAD

**Issue by Jiur13** [clsid2/mpc-hc#1430]
![mpc-hc64_PEE4B00nnz](https://user-images.githubusercontent.com/66332803/144124692-3514f4c7-2aa6-4a61-8ff5-f053ee641ecc.png)

When trying to watch something that has embedded .srt subtitles, they appear as absolutely massive and literally none of MPCs subtitle settings affect them.

**Comment by clsid2** [comment]
Reset settings:
Options > Miscellaneous > Reset

If that does not solve it, give me a link to that file.

**Comment by Jiur13** [comment]
Reset does make them appear properly, but I'd really rather not have to nuke all my current settings, since I have stuff like XySub and MADVR "installed" and already configured, I was hoping for a solution that wouldn't affect those. The files in question are any one of these https://nyaa.si/view/1140101, but anything with embedded .srt subs does this. Would you like me to upload my current MPC settings that I've exported to take a look at them?

**Comment by clsid2** [comment]
The subtitle settings in the player only have effect when you use the internal subtitle renderer. If you use an external subtitle renderer such as XySubFilter, then you need to adjust settings in that renderer.
