### ISSUE TITLE
ass subtitle with animation not shows the animation.

### ISSUE THREAD

**Issue by xqdoo00o** [clsid2/mpc-hc#1432]
If using "http://mysite/sub.ass" after "/sub" command, the animation not shows up.
But using local ass(same file as http ass), the animation shows normally.
So rendering http ass may not calls the ParseSSATag function?

**Comment by clsid2** [comment]
Give example link to an actual file so I can test with exact same conditions.

**Comment by xqdoo00o** [comment]
Hi, maybe you could test this ass subtitle with a local web server, after 1m 56s the difference shows between local and http ass. thanks! 
[S02E12.zh.ass.zip](https://github.com/clsid2/mpc-hc/files/7643444/S02E12.zh.ass.zip)

**Comment by clsid2** [comment]
Animation works for me with latest development build.

**Comment by xqdoo00o** [comment]
Thx. The Animation now works with last dev build. 
But still a bug could find in 2m 8s, there shows some code above the sub, then the animation disappeared

**Comment by clsid2** [comment]
Happens at 00:02:09.120
At offset of exactly 1MB into the file. Doesn't happen with local file.

**Comment by clsid2** [comment]
Turns out that there was a size limit. Fixed.
