### ISSUE TITLE
The default track preference tooltip uses "jap" as an example.

### ISSUE THREAD

**Issue by FX8350** [clsid2/mpc-hc#1433]
Hello.

The default track preference tooltip uses "jap" as an example.

Probably, most native Japanese speakers (including me) use "jpn" as the language code for Japanese language (same as ISO 639) and "jap" sounds like a discriminatory term for **some** Japanese people. (Not all, and I don't think it's used discriminatory in MPC-HC) 
So, if possible, please change the text from "jap" to "jpn".

Or if "jap" is more intuitive for English-speaking users, can I change from "jap" to "jpn" only for the Japanese version in the translation project with Transifex?

**Comment by clsid2** [comment]
Changed it to jpn

**Comment by FX8350** [comment]
thanks.
