### ISSUE TITLE
Repeat button at toolbar? 

### ISSUE THREAD

**Issue by ScottsplaysSus** [clsid2/mpc-hc#1434]
Hello dev! I hope you have a nice day. I am wondering is there a setting to add a “repeat button” that can switch between modes (example: repeat playlist/repeat file)? I know that I can do that by going to Play > Repeat > (options) but it will be much easier and faster if it can be done by just pressing a button on the toolbar. Anyway, thanks for maintaining this media player, I really appreciate it :D

**Comment by clsid2** [comment]
At this moment it is not possible to add any buttons. In the future there might be options to customize the toolbar.

**Comment by ScottsplaysSus** [comment]
Alright. Thanks for the info. Have a nice day :D
