### ISSUE TITLE
[Feature request] Please add Anaglyph 3D option for playing 3D SBS video

### ISSUE THREAD

**Issue by steve1821** [clsid2/mpc-hc#1435]
If any developer is reading this please implement this feature in MPC-HC. Take your time but please do this. I know clsid2 is not interested in adding any new feature, that's why I'm requesting other developers to do that.

All other players have this feature for a very long time. Please add this. Humble request. Thank you.

**Comment by ale5000-git** [comment]
There are Shaders to do it for MPC-HC here: https://forum.doom9.org/showthread.php?t=170475
but I haven't tried how it works.

**Comment by steve1821** [comment]
It's very difficult, not for common people like us.
So I'm requesting @clsid2 or any other developers to implement this feature internally in MPC-HC.

Because this feature is already available in other players like VLC. You guys can check their code and implement it.
Again I'm not a programmer. Just hoping for positive response from developers.
