### ISSUE TITLE
[Feature request] option to not start playlist item through play/pause click

### ISSUE THREAD

**Issue by BoomerangAide** [clsid2/mpc-hc#1436]
Hi,

Recently (version-wise), something was added:
```
Enabled processing of play/pause command when no media is loaded, but playlist is not empty. This now also allows resuming playback by pressing spacebar or clicking on the video area.
```
The issue is that I, and probably most users, have a single-click assigned to play/pause, et double-click assigned to toggle fullscreen.

So when trying to quit fullscreen after playing videos and not having one loaded, it cause the next video in playlist to load.

Could we have an option (checkbox or True/False in Advanced) to exclude clicks from the mentioned behavior (since only clicks have a "single" and "double" use) ?

**Comment by clsid2** [comment]
Better to just check if window is fullscreen, and ignore the action in that case.

Btw it does automatic exit by default:
Option > Playback > Fullscreen > Exit fullscreen at end of playback

**Comment by BoomerangAide** [comment]
The fullscreen quitting was just an use case.
I really think the issue is that a double-click would cause the effects of both a single and double click at the same time, and unlike while on a playing video (where the first click pause/play the video, then the 2nd click play/pause, cancelling the first), the 2nd click with no video loaded is not canceled by the first.

But because I think maybe some users would be fine with it, an option is better so that it can be turned on/off depending on how one use the player.

**Comment by clsid2** [comment]
I will at some point investigate the possibility to delay the first left click in anticipation of a double click. That should also solve this problem.

**Comment by clsid2** [comment]
Use F11 to exit fullscreen, or unassign left mouse click.
