### ISSUE TITLE
Misleading "jap" track preference hint text

### ISSUE THREAD

**Issue by yupinov** [clsid2/mpc-hc#1438]
There are 46 search results for the word "jap" in the code base - I assume most are related to the subtitle/audio preference hint. However, that is wrong. The 3 letter code for Japanese is "jpn", not "jap".  This is not even the first time this hint screws me over, having me scratch my head "why doesn't the Japanese audio track get selected". I assume the fix is trivial...

**Comment by ale5000-git** [comment]
Isn't the same issue of #1433?
(Already fixed [here](https://github.com/clsid2/mpc-hc/commit/83c7d74589ee78b5e04e258b4d52b430621f3db0))

**Comment by yupinov** [comment]
Sorry! I swear I searched :s
