### ISSUE TITLE
Support DSD or DSF (I don't know what is the difference)

### ISSUE THREAD

**Issue by BonjourBen** [clsid2/mpc-hc#1439]
Hi, I'm not a developer, but I still have a request.

I don't know if what I'm going to ask is difficult or time consuming to do (like asking in your pre-application preventive).
But is it possible to add a support in DSD / DSF format?

Anyway thanks to all you do, MPC-HC is by far the best video player I've used.

**Comment by BonjourBen** [comment]
I don't what I mean is very english but I'm french
(The excuse given by all French people because they do not assume that they have used google translate and that they know that google translate is average)

**Comment by clsid2** [comment]
Such files should already be supported.

You do need to change the audio renderer in the player options, because of the very high samplerate used by those files.

MPC-HC options > Playback > Output > Audio Renderer > SaneAR Audio Renderer
