### ISSUE TITLE
Minor issue with Logitech LCD support

### ISSUE THREAD

**Issue by phaax** [clsid2/mpc-hc#1440]
The current date is displayed wrong on the LCD screen. (Swedish locale)

Displayed: `6en 6 december 2021`
Expected: `Den 6 december 2021`

As you can see it's replacing the D with the number of the current day, which is kind of strange. 

I don't know enough C++ to fix this and create a pull request, but looking through the source code I can see that the function (LcdSupport.cpp line 56) is using `%#x` to format the string. I hex edited the .exe to use `%F` instead and it shows the date as yyyy-mm-dd (personal preference) and it is displayed properly.

**Comment by clsid2** [comment]
Difference between `%#x` (long date format) and `%F` does not explain the wrong value. The bug may be in Microsoft code, maybe even a typo specific to your locale. This code in MPC-HC is super old and has not been touched in very long time.

What value does it show today?

**Comment by phaax** [comment]
> What value does it show today?

Today it's showing `7en 7 december 2021`. 

> Difference between `%#x` (long date format) and `%F` does not explain the wrong value. The bug may be in Microsoft code, maybe even a typo specific to your locale. This code in MPC-HC is super old and has not been touched in very long time.

Yeah, the bug has been there for as long as I can remember, but I haven't bothered looking into it until now. Even if `%F` isn't addressing the real issue it'll still look better than before. :)

**Comment by clsid2** [comment]
I will change it.
