### ISSUE TITLE
Monitor flickers off/on, HDR disables, with every new video

### ISSUE THREAD

**Issue by rugabunda** [clsid2/mpc-hc#1444]
Continued from: https://www.reddit.com/r/MPCHC/comments/rca4rs/screen_flickers_off_hdr_disables_upon_playing_any/

Just did a fresh clean install to fix some other unrelated issue, videos used to play fine before this, except not stretch to fit full screen.

Now, every time I play a new video in MPC, the monitor flickers off, then on. HDR disables, leaving color washed out/un-viewable 

I have to re-enable HDR in windows settings each time manually now, after using MPC. 

Using windows 10.

**Comment by clsid2** [comment]
Are you using madvr or MPC Video Renderer? One of those video renderers is required for correct playback of HDR.

Also:
NVIDIA control panel > "Adjust desktop color settings"
At the bottom of that page, change the option "Content type reported to the display" from "Auto-select (recommended)" to "Desktop programs".

If things worked good before, problem might also be caused by bug in your current graphics driver.

**Comment by clsid2** [comment]
If this happens with MPC Video Renderer, then adjust the "Auto HDR on/off" option in its settings.

**Comment by rugabunda** [comment]
> 

I'm using MPC Video Renderer, default settings across the board. I don't see "madvr" as a renderer option.
There is no option for "content type reported to display"
![Example](https://user-images.githubusercontent.com/38260267/145586140-0521fe35-46e9-435c-b266-48d2bdfc3a1e.png)
I never changed my graphics driver, just did a clean install of MPC to clear the settings.

MPC Video Renderer nor does any renderer  appear to offer any HDR on off settings. Is there another setting im missing?
![MPC Example](https://user-images.githubusercontent.com/38260267/145586384-04382228-ea70-4e58-abf9-c7187a387c5b.png)

**Comment by rugabunda** [comment]
Where is the option to disable auto hdr for MPC? 

Using Enhanced Video Renderer (custom presenter) seems to be one work around. I also downloaded madvr just now and am testing that out. Which one is better?

**Comment by rugabunda** [comment]
Madvr seems to work as good as 'enhanced video renderer (custom presenter)

**Comment by clsid2** [comment]
You can access the settings of MPC Video Renderer here (when it is used):
Menu > play > Filters > MPC Video Renderer > "Auto HDR on/off" = never

**Comment by rugabunda** [comment]
> You can access the settings of MPC Video Renderer here (when it is used): Menu > play > Filters > MPC Video Renderer > "Auto HDR on/off" = never

Got it, that worked. It looks fine, close to MadVR. Why does it automatically disable HDR and make everything look bad?

**Comment by clsid2** [comment]
That is a 'bug' in the renderer. Or rather more a case of a bad assumption. The developers assumed disabling HDR would give better results for non-HDR video. This behavior will probably get corrected in a coming update.

Can you confirm these statements?
1) The renderer only turned off HDR on your system when playing SDR video.
2) For HDR video input it didn't change monitor mode.
3) Normal SDR video plays with correct colors in windowed mode when Windows HDR is enabled.
4) Normal SDR video plays with correct colors in fullscreen mode when Windows HDR is enabled.

**Comment by rugabunda** [comment]
I leave HDR on all the time. First, HDR mode is closely tied to Nvidia Control Panel custom color profile I created.  When HDR mode is disabled, this color profile remains enabled, rendering everything dark and faded.

1. Renderer only turned off Windows HDR while playing SDR videos. HDR color looks correct,  On HDR videos, monitor flickers on and off for 10 seconds, leaving it totally black for about 5 seconds. 

2. HDR videos do not change the monitor mode.

3 Windowed SDR disables HDR, everything looks terrible, very darkly lit. Incorrect lighting. Still using Nvidia color profile for HDR mode.
4. Full screen is the same as #3

On first try  Fullscreening HDR left renderer as a black screen, even after switching to windowed mode, I could only hear the audio. Second try worked, color has a slightly higher contrast fullscreen compared to windowed, but not significant (similar effect with MadVR)

**Comment by rugabunda** [comment]
timing

**Comment by rugabunda** [comment]
syncronicities http://www.visibleorigami.com/2011/02/love-in-time-of-hadron-collider.html

**Comment by mctrafik** [comment]
Finding this thread a couple years later. Super resolution in RTX cards is making people try the renderer and for those of us w/ HDR displays the flickering is very annoying and sadly this solution isn't easy to find. :(

**Comment by BarteJJ** [comment]
> You can access the settings of MPC Video Renderer here (when it is used): Menu > play > Filters > MPC Video Renderer > "Auto HDR on/off" = never

I have no "Auto HDR on/off" in my settings. :(

**Comment by clsid2** [comment]
It is called "Windows HDR" now.

**Comment by BarteJJ** [comment]
Well, I chose every option there. Nothing works!
