### ISSUE TITLE
Options>Playback>DVD more consistent

### ISSUE THREAD

**Issue by ArcticGems** [clsid2/mpc-hc#1445]
Can we make `Options>Playback>DVD` more consistent??

Change:

`Options>Playback>DVD` into: `Options>Playback>DVD/BD`

`Preferred language for DVD` into: `Preferred language for DVD/BD`

**Comment by clsid2** [comment]
That preferred language setting is for DVD only.

Changing page title text messes with the translations. Not going to do that right now.
