### ISSUE TITLE
missing audio bitrate data when using mkv container

### ISSUE THREAD

**Issue by FX8350** [clsid2/mpc-hc#1446]
Hi.

Right click > Audio Track are displayed audio codecs, sample rates,channels, and bitrate.
However, when using the mkv container, the bitrate data will not be displayed (Excluding linear PCM) .

I have tried several formats and codecs below
mkv: : only linear PCM (pcm_s24le) can display bitrate (probably)
mp4: AAC,MP3, and Opus displayed bitrate
m2ts: AAC,AC-3, and PCM displayed bitrate but TrueHD didn't

Is this due to the mkv specification? Or due to splitter ?

**Comment by clsid2** [comment]
The track selection menu does not contain such unimportant information.

Look at:
File > Properties
