### ISSUE TITLE
New HC version...no HDR support

### ISSUE THREAD

**Issue by 55trucker** [clsid2/mpc-hc#1447]
Hello there: I've started to use HC now seeing as it has been reinvigorated, 
I've come across an issue, the player as it is does not have the capability to properly play HDR encoded vid files. The player does play an HDR file but the contrast/colour is washed out.
Where the program is concerned does LAV handle this portion of the display? The most resent version of LAV (0.75.1) has no provision displayed to enable this. 

thx

**Comment by clsid2** [comment]
HDR requires [MPC Video Renderer](https://github.com/Aleksoid1978/VideoRenderer/releases) or [madVR](http://forum.doom9.org/showthread.php?t=146228)
After installation one of these renderers can be selected here:
Options > Playback > Output

LAV is used for decoding, the renderer is another piece of the playback chain.
