### ISSUE TITLE
[Bug?] Seekbar preview shows a brief "no image to display" (since version 1.9.17 included)

### ISSUE THREAD

**Issue by bouhpwet** [clsid2/mpc-hc#1448]
Hello,
You can clearly see in the attached snapshot what has become noticeable since version 1.9.17: When moving the cursor around the seekbar to generate a preview, there's a very brief moment when a "no image" appears.

![2021-12-15 08-17-14 flv_snapshot_00 03 251](https://user-images.githubusercontent.com/91374740/146141263-86370576-22cf-49cf-b46f-c6bce47346ad.jpg)

With version 1.9.16, that "no image" icon isn't shown at all. Actually, while the preview is generated the background is transparent, which is a lot less distracting than the full solid black background with the "no image" icon.

![2021-12-15 08-23-36 flv_snapshot_00 07 541](https://user-images.githubusercontent.com/91374740/146142114-c9be77d1-2b85-4a31-be0c-c722fc114fc7.jpg)

**Comment by clsid2** [comment]
This was intentionally added to indicate that the preview is still in process of being generated.
