### ISSUE TITLE
Fullscreen exclusive seek bar active zone is misaligned with madVR

### ISSUE THREAD

**Issue by sserdda-liamE** [clsid2/mpc-hc#1449]
When I switch to fullscreen exclusive, clicking on the seekbar is a dead zone.  In order to seek I need to click some 10 pixels below the seek bar.  The zone where it will register inputs seems to be about the height of the seek bar, just offset from where it should be.

**Comment by hooke007** [comment]
Nothing with mpc. what you click on is madvr's internal osd seekbar
![Snipaste_2021-12-16_08-26-52](https://user-images.githubusercontent.com/41094733/146285842-098ef684-5e8e-4033-b229-4667368135f3.jpg)

**Comment by clsid2** [comment]
Fixed

**Comment by sserdda-liamE** [comment]
Thank you
