### ISSUE TITLE
Subtitle On/Off not working

### ISSUE THREAD

**Issue by YoderofKansas** [clsid2/mpc-hc#145]
Tried hitting the 'w' key to turn subtitles on and off, but doesn't seem to do anything.  Info box in the top left corner never shows like when you hit 'Shift + S' when cycling thru subtitles.  Tried restarts, different videos, and different keybindings, none of them worked.  Version is 1.8.8, 64-bit version on Windows 10.

**Comment by clsid2** [comment]
Works fine here.

This option only works in combination with the internal subtitle renderer.
Options > Playback > Output
