### ISSUE TITLE
Is it possible to stream video content using MPC HC?

### ISSUE THREAD

**Issue by githubdotcomuser** [clsid2/mpc-hc#1451]
Whenever I either copy and paste a link in the "Open File/URL" menu or drag and drop a video stream link to the player, I get the following error window.
![2021-12-16 19_39_08-PTV Sports Live Stream _ PTV Cricket Live Streaming - Cricsala, Sportsala, Crict](https://user-images.githubusercontent.com/46681247/146387915-929c7985-3258-409f-80ec-0e1a8959cdec.png)

**Comment by clsid2** [comment]
You need to put yt-dlp.exe in the MPC-HC folder.

https://github.com/yt-dlp/yt-dlp

**Comment by githubdotcomuser** [comment]
I checked and see that I already have it in my MPC-HC folder.

![2021-12-16 20_40_56-MPC-HC](https://user-images.githubusercontent.com/46681247/146397756-94086a9b-ad6f-4a8f-89e4-89ed3e2810f1.png)

I tried again and still got the same error.

![2021-12-16 20_42_09-PTV Sports Live Stream _ PTV Cricket Live Streaming - Cricsala, Sportsala, Crict](https://user-images.githubusercontent.com/46681247/146397962-b48511db-3642-49a4-a74f-c9711bcd8a14.png)

**Comment by clsid2** [comment]
You are using a 32-bit version of MPC-HC. You need to use yt-dlp_x86.exe instead of yt-dlp.exe
You need to specify the location here:
MPC-HC options > Advanced > YDLExePath

**Comment by githubdotcomuser** [comment]
I don't understand what I am doing wrong because even when I have set it up exactly how you say, it still doesn't work.

https://user-images.githubusercontent.com/46681247/146421123-08b8f388-4987-420b-8d1a-ec3a8d21c162.mp4

I stopped the recording rather abruptly and forgot to include this screen in the recording. It's still there.

![2021-12-16 23_19_16-Warning](https://user-images.githubusercontent.com/46681247/146423090-58037395-3316-47fa-943c-45e1dde552f8.png)

**Comment by clsid2** [comment]
The path must also include the filename, not just the folder.

Also copy the URL here that doesn't work. It might be an unsupported website.

**Comment by githubdotcomuser** [comment]
I tried it with many different URLs. Here are two:

https://stream-as.movies4discord.xyz/episode/jGA6sk6Pyc9jGkCMzcafDoMQWvd0fpZExZfrzri6ahCYIpKoZSOt2mGhPLWs

https://stream-as.movies4discord.xyz/movie/izzpsWbU2iCGxGMgEVhk2ck5sDSvkkTAq3BCw9bgENnzKHjPTuHXGxGOh6dL

People usually recommend VLC or MPV to use to stream these. I assumed MPC-HC should work as well.

**Comment by ale5000-git** [comment]
The links just give: `Expired Key!`

**Comment by githubdotcomuser** [comment]
Yes, they remain active only for around six hours.

You could try this:

https://stream-as.movies4discord.xyz/episode/MIW17dBq2U2x5MRBbPuNE6PJOi5xTtYmYybspv0YGCejnBTPdEEvdXiRtfw3

**Comment by ale5000-git** [comment]
@NomaanMalick: The link works perfectly for me on both 32 and 64-bit version.
I use MPC-HC from K-Lite Codec Pack 16.6.5.

Also check that you have yt-dlp 2021.12.01 (at least).

**Comment by githubdotcomuser** [comment]
@ale5000-git Thank you very much for your response. However, I am not sure if it's really a codec problem because I downloaded MPV and drag-dropping the link into the player streams the content without any issue.

**Comment by clsid2** [comment]
Works totally fine for me with MPC-HC.

You are probably haven't got this installed: Microsoft Visual C++ Redist
https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe

**Comment by githubdotcomuser** [comment]
@clsid2 Thanks for replying! I checked and I already had Microsoft Visual C++ Redist installed but just to be sure, I installed it again. Unfortunately, the problem still remains. You don't suppose changing the default settings has anything to do with it, do you? I am asking because I have set up my MPC-HC according to this [guide.](https://shittastes.wordpress.com/tutorials/properly-installing-and-setting-up-mpc-hc/)

**Comment by clsid2** [comment]
That guide is full of stupid advice.

You need to figure this out for yourself. I am done wasting my time.

**Comment by ale5000-git** [comment]
@NomaanMalick

I suggest to uninstall all that you have installed, then install latest KLCP from here: https://codecguide.com/download_kl.htm

During installation enable all these:
- Reset all settings to their default
- [Windows] Optimize preferred decoder settings
- Enable internal subtitle renderer (ISR)
- Use internal audio renderer

I suggest to select as Video renderer: MPC Video Renderer
And as decoding method for MPC-HC: "LAV Video - D3D11VA" or "LAV Video - DXVA2 native".
