### ISSUE TITLE
Seek preview <10% won't stick via UI, only via manual edit of settings

### ISSUE THREAD

**Issue by Stone-D** [clsid2/mpc-hc#1452]
Attempting to set the seek preview size via the settings dialog to a number under 10 does not stick, it reverts to 10%.

Editing the settings file works, and the UI shows 5%. Attempting to increase this to 6, 7, 8, or 9 sets it to 10.

Version 1.9.18 (79b4c6b79)

Not a priority, as there is a workaround.

**Comment by clsid2** [comment]
Fixed
