### ISSUE TITLE
Version 1.9.18 does not play file

### ISSUE THREAD

**Issue by Cheeerd** [clsid2/mpc-hc#1453]
The new version, 1.9.18 (79b4c6b), does not play this file: https://nyaa.si/view/1381399
It opens the file and can seek to any position, but it is like it is always on pause.
The previous version plays it fine.
Here is ffprobe output for this file:
> [matroska,webm @ 000001a16ca2e840] Could not find codec parameters for stream 2 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 000001a16ca2e840] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, matroska,webm, from 'D:\Anime\[Beatrice-Raws] Steins;Gate Fuka Ryouiki no Deja vu [BDRip 1920x1080 HEVC TrueHD]\[Beatrice-Raws] Steins;Gate Fuka Ryouiki no Deja vu [BDRip 1920x1080 HEVC TrueHD].mkv':
  Metadata:
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2021-05-03T22:33:25.000000Z
  Duration: 01:30:02.40, start: 0.000000, bitrate: 14761 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 583.416000
      Metadata:
        title           : Avant
    Chapter #0:1: start 583.416000, end 850.349000
      Metadata:
        title           : Part A
    Chapter #0:2: start 850.349000, end 1046.712000
      Metadata:
        title           : Part B
    Chapter #0:3: start 1046.712000, end 1650.858000
      Metadata:
        title           : Part C
    Chapter #0:4: start 1650.858000, end 2008.506000
      Metadata:
        title           : Part D
    Chapter #0:5: start 2008.506000, end 2520.518000
      Metadata:
        title           : Part E
    Chapter #0:6: start 2520.518000, end 2789.996000
      Metadata:
        title           : Part F
    Chapter #0:7: start 2789.996000, end 3095.342000
      Metadata:
        title           : Part G
    Chapter #0:8: start 3095.342000, end 3871.326000
      Metadata:
        title           : Part H
    Chapter #0:9: start 3871.326000, end 4439.560000
      Metadata:
        title           : Part L
    Chapter #0:10: start 4439.560000, end 5067.354000
      Metadata:
        title           : Part J
    Chapter #0:11: start 5067.354000, end 5196.691000
      Metadata:
        title           : Part K
    Chapter #0:12: start 5196.691000, end 5402.397000
      Metadata:
        title           : ED
  Stream #0:0(jpn): Video: hevc (Main 10), yuv420p10le(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)
    Metadata:
      title           : BDrip by Jensen
      BPS             : 13491205
      DURATION        : 01:30:02.397000000
      NUMBER_OF_FRAMES: 129528
      NUMBER_OF_BYTES : 9110605866
      _STATISTICS_WRITING_APP: mkvmerge v56.1.0 ('My Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-05-03 22:33:25
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(jpn): Audio: truehd, 48000 Hz, stereo, s32 (24 bit) (default)
    Metadata:
      BPS             : 1022097
      DURATION        : 01:30:02.395000000
      NUMBER_OF_FRAMES: 6482874
      NUMBER_OF_BYTES : 690221804
      _STATISTICS_WRITING_APP: mkvmerge v56.1.0 ('My Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-05-03 22:33:25
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: hdmv_pgs_subtitle (default)
    Metadata:
      title           : Eng
      BPS             : 297240
      DURATION        : 01:29:17.310000000
      NUMBER_OF_FRAMES: 7701
      NUMBER_OF_BYTES : 199051453
      _STATISTICS_WRITING_APP: mkvmerge v56.1.0 ('My Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-05-03 22:33:25
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(jpn): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : Jpn
      BPS             : 275300
      DURATION        : 01:25:53.022000000
      NUMBER_OF_FRAMES: 7774
      NUMBER_OF_BYTES : 177328991
      _STATISTICS_WRITING_APP: mkvmerge v56.1.0 ('My Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-05-03 22:33:25
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

**Comment by clsid2** [comment]
@nevcairiel
Regression with decoding the TrueHD audio after latest FFmpeg update.

I have cut a 30 MB sample:
https://www.sendspace.com/file/9g8e12

**Comment by clsid2** [comment]
Looks like same issue as this:
http://trac.ffmpeg.org/ticket/9511

**Comment by clsid2** [comment]
Fixed
