### ISSUE TITLE
Limit slowest playback rate to 0.1 (or 0)

### ISSUE THREAD

**Issue by ObjectInSpace** [clsid2/mpc-hc#1456]
Speed steps must be set in multiples of .1, however the lowest playable rate in MPHC is 0.05. If your speed is set to this level, subsequently raising the speed causes the rate to remain .05X above your target speed, making live streams virtually unplayable.

Steps to reproduce:
1. Set the speed step to 50 under playback options.
2. Play a file
3. Press ctrl+down arrow twice, then press ctrl+up arrow twice. Observe the status bar.

Result: speed goes down from 1.0 to 0.5, then from 0.5 to 0.05. The speed then goes up to 0.55, and 1.05. Since you cannot set a speed step of 55, your speed will be permanently stuck at the wrong level. the only way to fix this was to set the speed step to auto, hit buttons until the .05 turns into .00, then set it to 10 to get it back to 1.0, then reset the step to wherever it was initially. I would file this experience under the heading "never, ever, again."

**Comment by clsid2** [comment]
This is your own fault by choosing a bad value. Leave it at "auto" to halve/double speed at each step.

It doesn't need to be a multiple of 0.1.

You can also apply specific rates through the menu:
Menu > Play > Playback rate

**Comment by ObjectInSpace** [comment]
I usually listen to voice at around 3X, so auto doesn't suit my purpose because 2x is too slow, but 4X is too fast. Anyway, Thanks--I forgot about the menu. When this happened yesterday, I tried changing the step to 25 in playback, and that didn't work. I'm not sure why though, because it is working fine today! 🤷‍♂️

**Comment by clsid2** [comment]
I will change it so it can go back to 1.0 when using custom values.
