### ISSUE TITLE
The seekbar can't be controlled when playing a relatively long flv vedio

### ISSUE THREAD

**Issue by Renshk** [clsid2/mpc-hc#1458]

**Comment by Renshk** [comment]
If the vedio is longer than 90 minutes, this is a must

**Comment by Renshk** [comment]
I added a vedio that can reproduce the bug

Link: https://pan.baidu.com/s/1sala0pp7tJRAVi7yxW_yog 
Extraction code: cadb 
After copying this content, open the Baidu Netdisk mobile phone App, the operation is more convenient

**Comment by clsid2** [comment]
If seekbar is disabled it means the file is broken.

**Comment by Renshk** [comment]
> If seekbar is disabled it means the file is broken.

I have tried other players, they can all play this question video normally

**Comment by clsid2** [comment]
I can't download your file. Use a different file host such as http://www.sendspace.com
