### ISSUE TITLE
[bug] weird aspect ratio of subtitle-rendering while switching from pgs to ass subtitles

### ISSUE THREAD

**Issue by hooke007** [clsid2/mpc-hc#1459]
### reproduce-steps:

1. play the video with multi-subs
2. the default subtitle which was rendering default is PGS
3. switching to the another ass sub
4. the ASS's aspect ratio and position seem to be affected by the previous PGS, but it could be fixed by changing the size of mpc window

### expectation:

the ASS would adapt to the video immediately

### preview:

posted from others' report
![Snipaste_2021-12-20_00-03-18](https://user-images.githubusercontent.com/41094733/146681808-c42c6408-2132-48c6-94b1-bbfec1e5b403.jpg)

**Comment by clsid2** [comment]
I need sample file. Also tell me approximate size of window.

**Comment by hooke007** [comment]
[04-Rec2020-Red-100%.zip](https://github.com/clsid2/mpc-hc/files/7741141/04-Rec2020-Red-100.zip)

My window-size in the reproduce-step is 1936x916

The first time of rendering pgs should be at 7 or 8 second.

**Comment by clsid2** [comment]
Edit: can reproduce with these steps:
Load video. Reduce window size. Then switch to ass.

**Comment by hooke007** [comment]
I am sure it only happens on internal vsfilter. And I just followed the original one who found this bug to reproduce. @tasty0tomato

**Comment by clsid2** [comment]
Fixed

**Comment by tasty0tomato** [comment]
Maybe not fixs? Use file in https://github.com/clsid2/mpc-hc/issues/1459#issuecomment-997421403 to do these test.
Wait until PGS subtitle appears. And then drag any ASS subtitle file to it and all of the ASS files under test do not render in the right way.
PGS:
![2022-03-30_12-45_1](https://user-images.githubusercontent.com/48764449/160753269-2949812f-6ed1-466a-8a58-b225b2850475.jpeg)
Three ASS:
![2022-03-30_12-48](https://user-images.githubusercontent.com/48764449/160753544-1667f6ae-3202-435b-b15a-1be7fb648c7c.jpeg)
![2022-03-30_12-48_1](https://user-images.githubusercontent.com/48764449/160753546-1d15c104-3211-43a1-8ed6-d6882ecfeeab.jpeg)
![2022-03-30_12-48_2](https://user-images.githubusercontent.com/48764449/160753547-7902b920-cd43-44aa-aa4c-0a624919a4fd.jpeg)
Maybe right place for the first ass:
![04-Rec2020-Red-100% mkv_snapshot_00 08 519](https://user-images.githubusercontent.com/48764449/160753632-e3b8d57c-3439-4acd-a0fb-ee935e584da0.jpg)

**Comment by clsid2** [comment]
Will look at this later.

**Comment by clsid2** [comment]
Fixed again
