### ISSUE TITLE
[Regression] Using frame step causes stutters

### ISSUE THREAD

**Issue by Ryuji12** [clsid2/mpc-hc#1460]
Whenever frame step is used, either forward or backward, after 3-5 sec the player does not respond to any action for the same amount of time as the key was held. This also happened back when ver 16.4.0 was released and you've increased the cache of something to fix it.
https://github.com/clsid2/mpc-hc/issues/1293
Video renderer: madvr
audio renderer: system default

**Comment by clsid2** [comment]
Fixed
