### ISSUE TITLE
MP4 (HEVC AC-3) audio sometimes gets out of sync

### ISSUE THREAD

**Issue by JNavas2** [clsid2/mpc-hc#1461]
- Audio Renderer: System Default
- Built-in Audio Switcher enabled.
- Windows 8.1 Pro x64.

When playing MP4 (HEVC AC-3), the audio very occasionally falls out of sync, delayed by 250-750 ms.
I can correct the problem with Audio Time Shift, or simply by exiting and restarting MPC-HC.
I have no idea what's causing this.

**Comment by clsid2** [comment]
Is it reproducible? Because if it happens totally random it is probably performance related.

**Comment by JNavas2** [comment]
I have not been able to consistently reproduce it.
What do you mean by performance related?
These are 720p videos stored on NVMe SSD that otherwise play without incident.

**Comment by clsid2** [comment]
Decoding performance. So high CPU usage.

I can't fix issues that are not reproducible.

**Comment by JNavas2** [comment]
My CPU utilization during playback is 3-4%, so I doubt it's performance related.
As a developer, I do understand the difficulty of problems that cannot be readily reproduced.
I'm starting a conversation to:

1. See if anybody else had seen the issue.
2. See if there's a logging option that might capture the issue.
3. Get suggestions on avoiding the issue.

**Comment by clsid2** [comment]
Which graphics processor do you have? If it is an Intel from Haswell generation then try disabling hardware decoding in the video decoder settings. That generation has only partial acceleration for HEVC which can give issues.

There is no logging ability that can capture this kind of problems.

**Comment by JNavas2** [comment]
Thank you for the fast responses.
My CPU is 7th gen Kaby Lake i7-7820HQ, which has full HEVC decoding:
"full hardware fixed function HEVC/VP9 (including 4K@60fps/10bit) decoding"

**Comment by clsid2** [comment]
If you ever get a reproducible use case, then leave a reply. A the moment there is nothing else that I can do to help.

AC3 audio in MP4 is pretty rare. If you are creating these files yourself, then consider using AAC audio instead. Or use Matroska container (.mkv).

**Comment by JNavas2** [comment]
Thank you.
I've only seen the problem one more time, and when I retried on that same video, I was not able to reproduce it.
Oh well.

**Comment by JNavas2** [comment]
I now think this was a problem with Windows Power Management.
I had Windows in Power Saver mode, which runs Wireless at minimum power.
I changed Wireless to Medium power, and the problem is largely resolved.
