### ISSUE TITLE
Seeking back sometimes causes future subtitles to show briefly

### ISSUE THREAD

**Issue by Zerowalker** [clsid2/mpc-hc#1463]
At title says, it seems to be 2 subtitles ahead when this happens.
So if i jump back 5 sec, the next-next subtitle will briefly show.
It's a bit rare and i don't know what triggers it, my pure guess is that perhaps it happens if one happens to seek on a keyframe or something?

it's a bit annoying as it can spoil some cases, so would love for it to be solved.
I wish i could provide more info though, but i don't really know how to debug this,
hopefully someone knows what might cause this or at least know where to look.

I don't know if it happens in all cases where subtitles exist, but it at least happens with mkv and embedded subtitles.
But i am quite sure it also happens with mkv and external subtitles.

**Comment by clsid2** [comment]
All rendered subtitle buffers should get thrown away at each seek. I can't reproduce your problem, nor have I seen any other people report this problem.

If you use a non-default video renderer such as madvr, then try with EVR-CP.

**Comment by clsid2** [comment]
Once you get a reproducible case, then leave a reply. Otherwise there is nothing I can do.

**Comment by Zerowalker** [comment]
It might be a madvr issue then, as that's what i generally use?

**Comment by clsid2** [comment]
Yes, likely a bug with madvr.

**Comment by Zerowalker** [comment]
Ah, sorry for wasting your time and thanks for clarifying stuff for me:)
