### ISSUE TITLE
long path names not supported for external subtitles

### ISSUE THREAD

**Issue by Zerowalker** [clsid2/mpc-hc#1464]
Basically if the external subtitles exist with a long path name (260+ characters) it won't load.
But media files themselves seem to work fine even if they got long paths.

So it's probably an "easy" fix where the search mechanism for the subtitles just don't handle long paths.
Will try look into this myself later to see if i can figure out something, but thought it best to still write the issue.

info: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by clsid2** [comment]
Should be fixed in latest commit.

**Comment by Zerowalker** [comment]
why that was quick, appreciate the work:)
