### ISSUE TITLE
[Request] load any subs in folder if none match

### ISSUE THREAD

**Issue by ANaPhOrAX** [clsid2/mpc-hc#1466]
> That will never be implemented because it is a terrible idea.
> 
> There can be hundreds of different video and subtitle files in the same folder.

Actually, it's not a terrible idea at all. Potplayer i.e. has this, and it works wonderfully. They have it as "load any subs in folder if none match", which would honestly be a godsend (and would as such also not cause an issue in the situation you're describing (which btw - increasingly rare, since a lot of rips nowadays have softcoded subtitles, instead of separate SRT etc. files)).

For the past couple hours I've been trying to solve this specific annoyance: A lot of torrents will have subtitles in a subfolder called i.e. "Subs". Now, potplayer for some reason doesn't scan subdirectories for subtitles, and you can't even add those as like ".\Subs" either (sigh), and mpc-hc _can_ scan subdirectories, but doesn't have the option to load any subtitle files if none match the filename of the media file... sheesh. Yes, I can go into the subfolder and drag the subtitle file onto mpc.. _but I shouldn't have to_. This is honestly so silly. I was even looking at a batch script that would rename and move the SRT file from the Subs subfolder into the main folder and delete the Subs subfolder.. but that one broke as soon as the Subs folder contained more than 1 SRT file. Sigh. Please reconsider implementing this.

_Originally posted by @ANaPhOrAX in https://github.com/clsid2/mpc-hc/issues/1288#issuecomment-1001115267_

**Comment by clsid2** [comment]
Don't create duplicate issues.
