### ISSUE TITLE
crash due to unexpected error (LAV filter)

### ISSUE THREAD

**Issue by bulldozerecske** [clsid2/mpc-hc#1468]
![mpc-hc_unexpected_error](https://user-images.githubusercontent.com/8028500/147497584-926b5d67-1aab-4fe5-ae44-8778dc42ac87.jpg)

When I got this error I had been trying to open .mp4 video files one after another.
Version: 1.9.18.22 (b58777f21)

**Comment by clsid2** [comment]
Can you reproduce the crash with a specific file?

I can only fix a problem if I can reproduce it.

**Comment by bulldozerecske** [comment]
Sorry, but I could not reproduce the crash yet. It happened only once at some point when I ended the process in the taskbar (player was running in the background only w/ high CPU usage and LAV filter icons were active). 

They are hikvision security camera video files, some of them seem to be corrupt (e.g. unreally long length ones).

Also, I'm getting the following message at the bottom bar in the beginning of each playback:
`Failed to set both pre-resize and post-resize shaders.`

**Comment by clsid2** [comment]
Remove any shaders that you activated here:
Options > Playback > Shaders
Or change video renderer to one that is compatible:
Options > Playback > Output
