### ISSUE TITLE
Wired sound after stopping playback on SPDIF digital output

### ISSUE THREAD

**Issue by theblond** [clsid2/mpc-hc#1469]
Hello,

**Setup**
I am using the coax SPDIF audio output of my mainboard with Realtek ALC1150 audio chip.

**Issue**
- After stopping playback or closing MPC while playback MPC plays a wired sound. I have samples in the attachment. It is not always the same noise, but similar.
- MPC does not play this noise, if I pause and then exit MPC. Other audio software on my PC does not make that noise.
- If I am playing on the same audio output on another software (in my case Serato DJ), pause playback and keep the software open, I have no issue in MPC at all. When I close Serato, it happens again.

**Attachment**
[sound samples.zip](https://github.com/clsid2/mpc-hc/files/7795511/sound.samples.zip)

**Comment by clsid2** [comment]
Might be one of the Windows sounds that is being played. Disable sounds in the Windows settings.

This is not fault of MPC-HC, so I can't help more.

**Comment by theblond** [comment]
If someone has similar problems, I found the cause. I have this issue with various hard and software on SPDIF Toslink or coaxial outputs. Windows turns the SPDIF output off, as soon as there is nothing playing.

The solution is to keep the output alive. The Sound Keeper Tool does an excellent job on this.

Here the link:
https://veg.by/en/projects/soundkeeper/
https://github.com/vrubleg/soundkeeper
