### ISSUE TITLE
Drag&drop visual issue in playlist with dark theme

### ISSUE THREAD

**Issue by Aleksoid1978** [clsid2/mpc-hc#147]
Dran'n'Drop in playlist when black theme enabled - selected items are not displayed.

**Comment by clsid2** [comment]
I did notice that the currently played file doesn't have different color in dark theme. Drag&drop seems to work same as with normal theme. First one of added files gets selected. At least on Win7.

@adipose

**Comment by Aleksoid1978** [comment]
Windows 10, standard(white) theme. MPC-HC latest git build.
![dark](https://user-images.githubusercontent.com/11625603/67530153-93e81800-f701-11e9-9de6-bfb95bd7d4c0.png)
![classic](https://user-images.githubusercontent.com/11625603/67530154-9480ae80-f701-11e9-9f53-a8a0d9330a2d.png)

**Comment by adipose** [comment]
It was deliberate not to hl the playing item, as it didn't fit the "grayscale" theme to have colors.  I tried bolding, and some different fade levels, but they all look bad when combined with the selected item.  So I added a new feature, with a bullet on the playing item.

![image](https://user-images.githubusercontent.com/3324395/67607486-76cf3b80-f739-11e9-9d82-34a2e77a904c.png)

https://github.com/clsid2/mpc-hc/pull/148

**Comment by clsid2** [comment]
It doesn't have to be completely grayscale. Perhaps it will look good with some of the colors used in W10 dark theme. For example the yellow from folder icons, or the light blue from the harddrive size usage.

The bug Aleksoid means is drag&drop within the playlist window to re-arrange order of files. The dragged item has missing text.

Other minor issue I noticed:
Options > player > web interface > launch in web browser
When enabled it doesn't have blue URL link color.

**Comment by adipose** [comment]
Yes, I don't 100% avoid the colors, but I try to when possible, as colors often clash, and the Windows ones aren't always great.

For example that blue color looks great until it's the highlighted row.

![image](https://user-images.githubusercontent.com/3324395/67622223-26a1b900-f7cd-11e9-97ee-eaa4dc99fea8.png)

![image](https://user-images.githubusercontent.com/3324395/67622228-2bff0380-f7cd-11e9-9786-e01caa88313a.png)

**Comment by clsid2** [comment]
Maybe a bit darker grey for the highlight will look better? And/or a darker blue when highlighted.

**Comment by adipose** [comment]
How about this:

![image](https://user-images.githubusercontent.com/3324395/67622586-5f8f5d00-f7d0-11e9-88c9-363647bf46bf.png)

![image](https://user-images.githubusercontent.com/3324395/67622589-63bb7a80-f7d0-11e9-9ad7-4c543bfebe80.png)

**Comment by adipose** [comment]
BTW that highlight color is just the same as windows explorer.  It works well for black and white fonts.  Not so much middle colored fonts.

**Comment by clsid2** [comment]
Looks good.

**Comment by adipose** [comment]
OK, that's pushed to patch4.  I'll take a look at drag and drop.

**Comment by adipose** [comment]
Drag and drop is fixed.  This was actually an existing bug, where even in classic mode the bg color of the text wasn't right, causing an ugly box around the title and time.  In dark theme it was worst because bgcolor=white and fgcolor=white, so it was unreadable.  Fixed for both modes.

![image](https://user-images.githubusercontent.com/3324395/67627362-a3558700-f80f-11e9-9bd5-72ff8697b46e.png)

![image](https://user-images.githubusercontent.com/3324395/67627373-dbf56080-f80f-11e9-886b-cb25c1d3c4f8.png)

![image](https://user-images.githubusercontent.com/3324395/67627380-f62f3e80-f80f-11e9-992b-6737a2b202aa.png)

**Comment by adipose** [comment]
@clsid2 And if you could rename this ticket to use the word "drag" :)
