### ISSUE TITLE
Fullscreen bottom controls remain when mouse exits to another monitor

### ISSUE THREAD

**Issue by junpeikun** [clsid2/mpc-hc#1470]
Hello!
I use MPC-HC on a monitor placed at the top of my laptop and when a video is playing in fullscreen, moving the mouse away (exiting through the controls and to the bottom) doesn't trigger the controls to hide again. The option is set to only show the controls on mouse over and the time to hide to 0ms. If the latter value is set to some non zero value (eg 100) the problem is worked around.
I hope you can fix this when you have the time.
Thanks and happy holidays!

**Comment by drmadcow** [comment]
I'll second this issue but ONLY when I drop from a monitor that is vertically aligned above the monitor I drag down to.  Going between monitors horizontally doesn't cause the seek bar to appear.  Issue happens in the dark theme.

**Comment by clsid2** [comment]
Fixed
