### ISSUE TITLE
There is a newer version of MadVR

### ISSUE THREAD

**Issue by MuhammetEminCakir** [clsid2/mpc-hc#1471]
![image](https://user-images.githubusercontent.com/64583157/147842335-a67d82ff-43c2-4215-8f87-f4f0d7057bf4.png)
I saw a newer version of MadVR in this site: https://www.videohelp.com/software/madVR/old-versions
Do you know it's official built?

**Comment by clsid2** [comment]
That is a beta test version. It has an expiry date.

https://www.avsforum.com/threads/improving-madvr-hdr-to-sdr-mapping-for-projector.2954506/page-696
