### ISSUE TITLE
Please add the "move" box on Sourceforge to inform

### ISSUE THREAD

**Issue by Neustradamus** [clsid2/mpc-hc#1472]
Dear @clsid2,

In first, Happy New Year!

Can you add the box on Sourceforge to inform that the project is now on GitHub like other projects?

On https://sourceforge.net/projects/guliverkli2/ -> https://github.com/clsid2/mpc-hc

Can you publish ffdshow-tryout on GitHub too?
- https://sourceforge.net/projects/ffdshow-tryout/

Thanks in advance.

**Comment by clsid2** [comment]
ffdshow is dead and no longer maintained.

**Comment by Neustradamus** [comment]
@clsid2: You have not replied to all...

About ffdshow-tryout, I know, but it is good to have official archive code.

**Comment by Neustradamus** [comment]
About the box, it is like: https://sourceforge.net/projects/handbrake/ for example.

I contact Gabest to do same on https://sourceforge.net/p/guliverkli/.

**Comment by Neustradamus** [comment]
@clsid2: You have not replied to all...

About ffdshow-tryout, I know, but it is good to have official archive code.

About the "move" box, it is like: https://sourceforge.net/projects/handbrake/ for example.

I contact Gabest to do same on https://sourceforge.net/p/guliverkli/.

Have you some rights on https://github.com/mpc-hc, do you see all owners?
The goal is to put the project alive again.

**Comment by Neustradamus** [comment]
@kasper93, @XhmikosR, @vBm, @JellyFrog: In first, Happy New Year!

I would like to relive the "initial" project.

Access needed:
- SF: https://sourceforge.net/projects/mpc-hc/
- GitHub: https://github.com/mpc-hc
- Transifex: https://www.transifex.com/mpc-hc/mpc-hc/
- Facebook: https://www.facebook.com/MediaPlayerClassicHomeCinema
- Twitter: https://twitter.com/mpc_hc
- Others?

Thanks in advance.

**Comment by clsid2** [comment]
Dream on. Ain't going to happen...
