### ISSUE TITLE
Support for Visual Studio 2022 build

### ISSUE THREAD

**Issue by cw2** [clsid2/mpc-hc#1474]
If there is any interest in building with the latest Visual Studio 2022, I can contribute changes to support the free Community edition.

Notes:
- The update of MPC-HC direct dependencies basically means just retarget their toolchain to version `v143` - but I have not checked how it can potentially affect minimal supported operating systems _(personally, I am focused only on 64-bit Windows 10 and newer)_.
- There are two projects **libbluray** and **qsdecoder** in **LAVFilters** submodule that require change in their respective project configurations (either add condition for $(VisualStudioVersion)==17.0 or generalize existing condition for 16 to handle future versions automatically too). I am not sure what would be the best approach for change like this - I know MPC-HC already uses its own LAVFilters submodule, but if was better to use own submodules for libbluray and qsdecoder too or try to contact the maintainer of LAVFiletrs project and coordinate necessary changes from bottom-up ? (unfortunately, the original git repos are not hosted at github but at git.1f0.de server).

Alternatively, there could be a separate branch with VS2022 support and a special release (?)

**Comment by clsid2** [comment]
I am going to wait with upgrading until nevcairiel updates LAV Filters.

Until then you can simply use VS2022 with v142 toolchain. The installer should give option to install that. At least VS2019 did offer such options.
