### ISSUE TITLE
No hotkey shortcut for Playlist shuffle

### ISSUE THREAD

**Issue by KAELINS** [clsid2/mpc-hc#1475]
There is no option to set a hotkey for playlist shuffle toggle.
![](https://i.imgur.com/X80K5GL.png)
![](https://i.imgur.com/xN3Ot7T.png)

**Comment by KAELINS** [comment]
You can set a key for the repeat mode, this should have a shortcut too

**Comment by earhax** [comment]
1 year later, still waiting/hoping for this...

**Comment by adipose** [comment]
> 1 year later, still waiting/hoping for this...

I hate to tell you this, but it was really two years.

https://github.com/clsid2/mpc-hc/pull/2708

Note, the shortcut WON'T WORK if you have the playlist focused.  I learned that shortcuts don't trigger from the playlist window, which in this case you may find confusing.  But as long as you are on the video window it will work.
