### ISSUE TITLE
Capture DVD Menu image overlay

### ISSUE THREAD

**Issue by skot013** [clsid2/mpc-hc#1477]
![1](https://user-images.githubusercontent.com/43721178/148331907-8f1ee024-dd98-4499-bae1-54a86192aa4d.jpg)
![QQ截图20220106131353](https://user-images.githubusercontent.com/43721178/148332070-236a8872-9b5d-49c3-b173-dbb1e9f24f0b.jpg)

Can only be rename to capture success
When I captured multiple different menu images, only captured one

**Comment by clsid2** [comment]
Options > Advanced > SaveImageCurrentTime
