### ISSUE TITLE
[Feature request] Option for smart hiding of Playlist

### ISSUE THREAD

**Issue by AbeFromanGitHub** [clsid2/mpc-hc#1478]
I use playlists about as much as I don't, but I hate having to manually hide or unhide the playlist.
I open a folder as a playlist, and then I have to manually set the playlist to visible.
Then I double click a video file, and the playlist eats up the same amount of real estate as it did before.
Then, I hide the playlist, but the video doesn't resize, so I have to close and re-open the video.
Right now, this is my major gripe with an otherwise flawless program that I've used for years.  It doesn't have to be this way.

How about an optional feature to try to auto-hide the playlist when appropriate?
If I double click a file, and it's obviously not a playlist - hide it.
If I right-click a folder and select "Play with MPC-HC", a playlist is created - show it.  "Add to MPC-HC Playlist" - show it.

Or to make it simple, hide playlists when they only have one item.
This could be a simple feature to add, but would add much user-friendliness.

**Comment by clsid2** [comment]
I am not going to add any new functionality.

You can drag&drop the playlist outside of the playlist window. Then it doesn't mess with video size. You can press Ctrl+7 to hide/unhide.
