### ISSUE TITLE
Menu function is not displayed when playing DVD

### ISSUE THREAD

**Issue by skot013** [clsid2/mpc-hc#1480]
![GIF 2022-1-6 16-30-31](https://user-images.githubusercontent.com/43721178/148353838-8ffed0a1-ae87-4b52-aadf-0e4af4d22768.gif)
 **DVD DOWNLOAD LINK：https://1fichier.com/?fhxbffr0ml3xjivphy51**

**Comment by clsid2** [comment]
The ISO has incorrect file structure for DVD disc. The VIDEO_TS folder should be in the root.

Menu options will be shown correctly if you open the video_ts.ifo file.
Or Menu > File > Open DVD
