### ISSUE TITLE
Can't choose format options when playing video through YDL

### ISSUE THREAD

**Issue by ObjectInSpace** [clsid2/mpc-hc#1482]
MPC-HC only respects format options specified in the YTDL commandline under advanced options when a video is being downloaded. For example, using -f "ba+wv" will download the best available audio with the worst available video, but only after selecting "save a copy." If you just play the video, it is displayed in full resolution. I see options for setting the resolution and video format, but none for audio, so it's not clear to me what logic determines what streams are played. My preference would be to pick from all available streams in the playback menu like for local files, but youtube videos for example show only one video+audio codec at a time. If this is not feasible, YTDL's format parsing is quite extensive, and I'd really appreciate having that flexibility when playing as well as downloading video.

**Comment by clsid2** [comment]
There is an option to restrict the resolution (height) and to specify preferred video format.

I am not going to add any more options.
