### ISSUE TITLE
DVD mediainfo Incomplete

### ISSUE THREAD

**Issue by skot013** [clsid2/mpc-hc#1483]
![QQ截图20220107192814](https://user-images.githubusercontent.com/43721178/148537674-23ff3e2c-78e9-4f70-a34c-088a3f93bddd.png)

![QQ截图20220107192614](https://user-images.githubusercontent.com/43721178/148537525-b364d4d1-b109-4f35-99ca-bf7ae53d8939.png)

**Comment by clsid2** [comment]
MediaInfo does not show that extended information for VIDEO_TS.IFO
It does show it for VTS_0X_0.IFO

Fixed.
