### ISSUE TITLE
Choppy playback on volume change

### ISSUE THREAD

**Issue by bw4518** [clsid2/mpc-hc#1484]
I don't have the fastest hw but I don't see any issues with playback except when I'm changing the volume during which I see considerable stuttering. Any ideas?

**Comment by clsid2** [comment]
Options > player > disable "Show OSD"

**Comment by bw4518** [comment]
Alright, that solves the stuttering, but I sort of need the seek bar.

**Comment by clsid2** [comment]
Don't use exclusive mode option for the video renderer.
