### ISSUE TITLE
MPC HC always on top in fullscreen

### ISSUE THREAD

**Issue by OshidaBCF** [clsid2/mpc-hc#1488]
While watching a video in fullscreen, the app stay on top, with no way to turn it of so it's quite hard to select an app that might be behind the video window.

**Comment by clsid2** [comment]
No it does not, unless you enabled "always on top" or exclusive mode in the video renderer.

**Comment by OshidaBCF** [comment]
What do you mean by "exclusive mode" ?

**Comment by clsid2** [comment]
That is an option that some renderers have. For example madvr.

You can press F11 to exit fullscreen or double-click on the video.

**Comment by OshidaBCF** [comment]
![image](https://user-images.githubusercontent.com/61458287/148656977-61c30b3a-7809-4b8f-843b-5b95546eaa91.png)
I use the same renderer, but there really isn't any "off" for the "on top" option when you right click on the screen : 
![image](https://user-images.githubusercontent.com/61458287/148657005-9c6fbdb8-43d0-4513-8f6e-5e9f10b1bee6.png)

**Comment by clsid2** [comment]
You can access madvr settings this way:
Menu > Play > Filters > madvr
Or through its system tray icon

madvr settings > renderer > general settings

**Comment by OshidaBCF** [comment]
I seeeeee

so i guess that this need to be turned off.
![image](https://user-images.githubusercontent.com/61458287/148657629-873ff6a6-012e-4e89-8425-e4a36f8bcd5a.png)

**Comment by Aleksoid1978** [comment]
In fullscreen always On top.
