### ISSUE TITLE
zoom presets (Alt+number) not working anymore, except Alt-1 (50% zoom)

### ISSUE THREAD

**Issue by gawate** [clsid2/mpc-hc#149]
Hi, I went from the last official build of MPC-HC to 1.8.8 and now I notice the preset zoom functions (Alt+number) don't work, only Alt-1 (zoom to 50%) works. Details here: https://pastebin.com/uehtdcmy
If you need more details, please let me know.

**Comment by clsid2** [comment]
Works fine for me and everyone else.

Options > Miscellaneous > Reset

**Comment by gawate** [comment]
That did it for me too, sorry I didn't think of that first.
