### ISSUE TITLE
Warning when all audio devices disabled

### ISSUE THREAD

**Issue by gabbsmo** [clsid2/mpc-hc#1491]
I only have a Bluetooth speaker. When it is turned of I have no enabled audio playback devices. If the speaker turned on everything works as expected. If I open a file in MPC-HC I get the following warning:

> MPC-HC could not render som of the pins in the graph, you may not have the needed codecs or filters installed on the system.
> 
> LAV Splitter Source (internal)::Audio
> LAV Audio Decoder (internal)::Output
> Audio Switcher::Out
> 
> Media Type 0:
> --------------------------
> Audio: IEEE Float 48000Hz stereo 3072kbps
> 
> AM_MEDIA_TYPE: 
> majortype: MEDIATYPE_Audio {73647561-0000-0010-8000-00AA00389B71}
> subtype: MEDIASUBTYPE_IEEE_FLOAT {00000003-0000-0010-8000-00AA00389B71}
> formattype: FORMAT_WaveFormatEx {05589F81-C356-11CE-BF01-00AA0055595A}
> bFixedSizeSamples: 1
> bTemporalCompression: 0
> lSampleSize: 8
> cbFormat: 18
> 
> WAVEFORMATEX:
> wFormatTag: 0x0003
> nChannels: 2
> nSamplesPerSec: 48000
> nAvgBytesPerSec: 384000
> nBlockAlign: 8
> wBitsPerSample: 32
> cbSize: 0 (extra bytes)
> 
> pbFormat:
> 0000: 03 00 02 00 80 bb 00 00 00 dc 05 00 08 00 20 00 ....»...Ü.... .
> 0010: 00 00                                           ..
> 
> 
> Media Type 1:
> --------------------------
> Audio: PCM 48000Hz stereo 1536kbps
> 
> AM_MEDIA_TYPE: 
> majortype: MEDIATYPE_Audio {73647561-0000-0010-8000-00AA00389B71}
> subtype: MEDIASUBTYPE_PCM {00000001-0000-0010-8000-00AA00389B71}
> formattype: FORMAT_WaveFormatEx {05589F81-C356-11CE-BF01-00AA0055595A}
> bFixedSizeSamples: 1
> bTemporalCompression: 0
> lSampleSize: 4
> cbFormat: 18
> 
> WAVEFORMATEX:
> wFormatTag: 0x0001
> nChannels: 2
> nSamplesPerSec: 48000
> nAvgBytesPerSec: 192000
> nBlockAlign: 4
> wBitsPerSample: 16
> cbSize: 0 (extra bytes)
> 
> pbFormat:
> 0000: 01 00 02 00 80 bb 00 00 00 ee 02 00 04 00 10 00 ....»...î......
> 0010: 00 00      

This could be more graceful. Not sure if this is a bug or a feature.

                                     ..

**Comment by clsid2** [comment]
That error means it could not create an audio renderer. Which is logical in your case.

Options > Playback > uncheck "Report which pins fail to render"
