### ISSUE TITLE
Video doesn't display properly when moved from a lower res monitor

### ISSUE THREAD

**Issue by MrComexs** [clsid2/mpc-hc#1493]
When I open a video in my second monitor and then move it to my first it doesn't render properly when I full screen it or make the window bigger. This doesn't happen when I open it in my first monitor and when I move it to my second.
https://www.dropbox.com/s/dnyzjssu57le3et/1.mp4?dl=0
First monitor is 2560x1440
Second monitor is 900x1440

**Comment by Aleksoid1978** [comment]
Options -> Playback -> Output -> Reinitialize when changing display.

**Comment by MrComexs** [comment]
> Options -> Playback -> Output -> Reinitialize when changing display.

Cool it works thanks for the help but it takes a frame or two for it to reset every time I switch it to another monitor.

**Comment by Aleksoid1978** [comment]
Yes, it's ok.

**Comment by clsid2** [comment]
That option should theoretically not be needed for this specific situation. The renderer should use a backbuffer that is large enough for the largest screen. Just to confirm, are you using version 1.9.18 and not something older?

**Comment by clsid2** [comment]
Another setting to test:
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\Settings
DesktopSizeBackBuffer = 1

If that also works, then there might be a bug in the monitor detection code.

**Comment by MrComexs** [comment]
![image](https://user-images.githubusercontent.com/57308435/148988240-0030148c-0664-487c-bec8-bbe14344016e.png)
I also change DesktopSizeBackBuffer = 1 (Reinitialize when changing display is true) and I restarted my pc but it still goes black for a frame and repeats a frame every time a move it to another monitor.

**Comment by clsid2** [comment]
With DesktopSizeBackBuffer setting enabled, you can try with the reinitialize option disabled.

If that works, then I can make a debug build for you to log what goes wrong with default settings.

**Comment by MrComexs** [comment]
Okay I disabled reinitialize setting and I don't get the problem where it would go black for a frame and repeats a frame when I move the windows to another monitor but now my first problem returned (it doesn't display my media properly when I open a video is my second monitor and move it to my first). oh in DesktopSizeBackBuffer is it supposed to be in Hexadecimal or Decimal because its Hexadecimal for me.

**Comment by clsid2** [comment]
Thanks for testing.

You will have to use the reinitialize option for now.

**Comment by ale5000-git** [comment]
@MrComexs: For numbers from 0 to 9 Hexadecimal and Decimal is exactly equal.

**Comment by MrComexs** [comment]
@ale5000-git for some reason I was thinking Decimal is binary.
