### ISSUE TITLE
[bug] No OSD when playing audio files

### ISSUE THREAD

**Issue by Alekwk** [clsid2/mpc-hc#1495]
With audio files, there's no OSD. No time, name or volume display. The same OSD should be visible as with video files.

**Comment by clsid2** [comment]
The OSD requires a video renderer. So not possible for audio only files.

**Comment by Alekwk** [comment]
How does MPC-BE do it?

**Comment by clsid2** [comment]
That has a different implementation that can also draw on a window. I am not interested in porting that. Someone else has to do it and submit a patch.
