### ISSUE TITLE
Windows 7 Autoplay Defualt

### ISSUE THREAD

**Issue by Sin-Shadow-Fox** [clsid2/mpc-hc#1496]
So something happened to my first thread and it doesn't seem anyone can comment on it anymore so I'm making a new thread. Below are the contents of the original thread and the comments from it.

 Sin-Shadow-Fox commented 10 days ago

I'm about 2 seconds away from uninstalling this thing. Why is it when i try to select windows media player for my dvd movie and enhanced dvd movie autoplay options the only options that show up are vlc, dropbox and media player classic?
![148615331-23cacf07-2d30-48c4-b014-83223fd6f089](https://user-images.githubusercontent.com/96899282/149826412-996a89f7-c5a4-435d-b928-37dcd7f37925.PNG)

 clsid2 commented 10 days ago

If WMP options are broken it is not the fault of MPC-HC.
@clsid2 clsid2 closed this 10 days ago
@Sin-Shadow-Fox
Author
Sin-Shadow-Fox commented 10 days ago •

As you can see in the upper menus WMP options are not broken.
EDIT: Also this didn't become an issue until media player classic was installed so it does have something to do with it.
@clsid2
Owner
clsid2 commented 9 days ago

MPC_HC did not cause this !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
@clsid2
Owner
clsid2 commented 9 days ago

Registry key:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers\EventHandlers\PlayDVDMovieOnArrival
-> should contains empty string value with name "MSPlayDVDMovieOnArrival"
@Sin-Shadow-Fox
Author
Sin-Shadow-Fox commented 9 days ago

Hmm. You seem angry. Maybe this will help. (hugs) ^_^
@Sin-Shadow-Fox
Author
Sin-Shadow-Fox commented 9 days ago

Also how do i find this local machine folder? When i put it in windows explorer my webrowser pops up with
"Hmm. We’re having trouble finding that site.

We can’t connect to the server at www.hkey_local_machine.com."
@clsid2
Owner
clsid2 commented 9 days ago

You can edit the Registry with regedit.exe
If you have never done that before you need to be very careful not to do anything stupid.

In your screen shot you say "Windows Media Player" is "Classic", which does not make any sense at all, because they are two totally different and unrelated players. And if you say you can't select WMP, then why is it already selected by default...

I can't provide anymore help. I have better things to do with my life.

If you mean that MPC-HC is NOT shown there, then you need to let it create the autoplay entries first.
MPC-HC options > Player > Formats

Again...
Windows Media Player is a player made by Microsoft
Media Player Classic is a totally different player and has no relation to Microsoft at all, nor is it based on an old version of WMP. It only has a similar look as a very old WMP.
@Sin-Shadow-Fox
Author
Sin-Shadow-Fox commented 9 days ago

The audio cd and enhanced audio cd autoplay options open windows media player as intended but dvd and enhanced dvd autoplay options open media player classic instead.
@Sin-Shadow-Fox
Author
Sin-Shadow-Fox commented 9 days ago

Also you still sound kinda angry. So here, have another hug. (hugs again) ^_^
@Sin-Shadow-Fox
Author
Sin-Shadow-Fox commented 5 days ago

Bump.
@Sin-Shadow-Fox
Author
Sin-Shadow-Fox commented 16 hours ago

Bump.
@clsid2
Owner
clsid2 commented 6 hours ago

I can't help you.
@Sin-Shadow-Fox
Author
Sin-Shadow-Fox commented 6 hours ago

That's ok. Github is a big place so I'm sure there is someone else who can. And you did help me learn that whatever is wrong with media player classic has something to do with regedit.exe and that i should definitely not mess around with it on my own so you did help me a little so thank you. ^_^
Repository owner locked and limited conversation to collaborators 6 hours ago

**Comment by clsid2** [comment]
Nothing is wrong with Media Player Classic. Something is wrong with your Windows Media Player.
