### ISSUE TITLE
Black level all washed out.

### ISSUE THREAD

**Issue by Snik99** [clsid2/mpc-hc#1497]
At first I thought it was my tv, or video card, but after combing every possible setting I turned to comparing different video players. I see that the issue does not exist, for example, on vlan. Total pitch black where it's supposed to be. Using the latest mpc, on windows 10 x64 with an AMD RX 570 video card, this issue came out of nowhere and did not seem to exist on previous versions.

Other than going back to a previous version, are there any thoughts...??
Thanks.

**Comment by clsid2** [comment]
Not fault of the player. Probably AMD driver issue that affects renderers that use DXVA2/D3D11 scaling. Try setting "full range" is the driver display settings.

You can try different video renderer here:
MPC options > Playback > Output

Good alternative renderer is MPCVR:
https://github.com/Aleksoid1978/VideoRenderer/releases

In case you are already using that renderer. Then try disabling "use Direct3D 11" in its settings.

**Comment by Snik99** [comment]
Hey I'm already ahead of the game because more often than not I'm the bloody problem...
Ok then. I will dive in to these things after the hockey game which is about to begin.(go habs)

Thanks

**Comment by Snik99** [comment]
Hey hey hey, I tried the alternative renderer MPCVR as you suggested, and that solved my issue. Thank you very much...
