### ISSUE TITLE
M3u playlist with twitch urls doesn't use yt-dlp.

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1498]
Creating a m3u playlist for a twitch playlist with yt-dlp and trying to use it with mpc-hc doesn't work. When trying to do this with a YouTube playlist it does work.

In the case with YouTube links it tries to use the given youtube_dl executable. Twitch urls dont do that.

### MPC-HC (Nightly, 64-bit)

Build information:
    Version:            1.9.18.46 (ca362098f)
    Compiler:           MSVC v19.29.30138
    Build date:         Jan 11 2022

LAV Filters:
    LAV Splitter:       0.75.1.43
    LAV Video:          0.75.1.43
    LAV Audio:          0.75.1.43
    FFmpeg compiler:    MinGW-w64 GCC 10.2.0

Operating system:
    Name:               Windows 10 (Build 20H2)
    Version:            10.0.19042 (64-bit)
### YouTube example:
`echo #EXTM3U > yt_playlist.m3u & yt-dlp.exe --flat-playlist -g <PLAYLIST_URL> >> yt_playlist.m3u `
```
#EXTM3U  
https://www.youtube.com/watch?v=...
https://www.youtube.com/watch?v=...
https://www.youtube.com/watch?v=...
https://www.youtube.com/watch?v=...
```

### Twitch example:
`echo #EXTM3U > tw_playlist.m3u & yt-dlp.exe --flat-playlist -g <PLAYLIST_URL> >> tw_playlist.m3u `
```
#EXTM3U  
https://www.twitch.tv/videos/...
https://www.twitch.tv/videos/...
https://www.twitch.tv/videos/...
https://www.twitch.tv/videos/...
```

**Comment by clsid2** [comment]
YDL functionality is only called for M3U playlist URLs for a few whitelisted sites.

I will add twitch.tv
Meanwhile you can fix your issue by using twitch.com urls, as that is already on whitelist.
