### ISSUE TITLE
Hope to the Dark interface（Dark Theme） can automatically switch according to the mode set by the Windows

### ISSUE THREAD

**Issue by loveis0** [clsid2/mpc-hc#1499]
Hope to the Dark interface（Dark Theme） can automatically switch according to the mode set by the Windows

**Comment by clsid2** [comment]
I already does if you reset the settings. I am not going to add an automatic mode. Too much other stuff to do already.

**Comment by loveis0** [comment]
but Auto Darkmode is really important, it's too cumbersome to switch manually😩

**Comment by ghost** [comment]
To be honest, light mode in an video player does not make sense in 2022. Dark mode should be on by default.

**Comment by ale5000-git** [comment]
@fossist: It is opinable

**Comment by adipose** [comment]
> but Auto Darkmode is really important, it's too cumbersome to switch manually😩

It does default to the windows setting.  What kind of psychopath changes their windows themes back and forth???

;-)

**Comment by adipose** [comment]
Anyway, I could add an advanced option to always follow the windows theme on open, but I'm not interested in doing it live, because re-initializing all the GUI was a bit of a nightmare.

**Comment by loveis0** [comment]
> > but Auto Darkmode is really important, it's too cumbersome to switch manually😩
> 
> It does default to the windows setting. What kind of psychopath changes their windows themes back and forth???
> 
> ;-)


I think Most software is Auto Darkmode
> 
such as the latest Windows11 Explorer
> 
As the picture shows：

![Make-Windows-11-Taskbar-Black](https://user-images.githubusercontent.com/13910215/154978185-b796deac-dd9b-408f-bda0-df53f5fde6dc.jpg)
![Make-Windows-11-Taskbar-Black-1](https://user-images.githubusercontent.com/13910215/154978319-81c8b276-8e6b-42f3-b788-84d6e83062d8.jpg)
![how-to-automatically-switch-between-light-and-dark-themes-on-windows-11-1](https://user-images.githubusercontent.com/13910215/154978346-75d67b83-dea3-44ba-9ab3-cb777e05cbf2.png)
