### ISSUE TITLE
Monitor numbers keep changing

### ISSUE THREAD

**Issue by chinagreenelvis** [clsid2/mpc-hc#1502]
Where does MPC pull its monitor information from? In order to force MPC onto my secondary monitor (when I have it activated) I have an AutoHotKey script that writes the following to the .ini file:

`FullScreenMonitor=\\.\DISPLAY2`

This usually works, but sometimes MPC seems to change what it thinks is the second monitor, and I have to rewrite my script to change it to

`FullScreenMonitor=\\.\DISPLAY1`

instead. Then this only works for a short while (weeks, usually) before I have to change it back again.

At this point opening up MPC and looking at the monitor options manually doesn't even show #1 or #2; it shows something like #6 and #7 now and displays them both as my VR headset (and I almost always have that disabled via the device manager).

**Comment by clsid2** [comment]
Those names are how Windows identifies them. It is not a MPC-HC problem. I can't help with Windows problems.

You can use Display Driver Uninstaller to remove all monitors, and re-detect them.
Instead of disabling unused display devices in device manager, just disconnect them.

**Comment by chinagreenelvis** [comment]
Sometimes the numbers that MPC displays are the reverse of what windows displays when identifying the monitors with an on-screen number.

**Comment by clsid2** [comment]
The player gets those device names directly from Windows API. These names are likely based on the detection order. It has no direct connection with the identification numbers shown by Windows in its display settings.

The fact that the numbers in the names keep increasing means that Windows somehow is detecting (some of) your displays as new devices occasionally. Why I don't know.

This is NOT in any way the fault of the player. So I can't help you.

**Comment by chinagreenelvis** [comment]
I really would suggest implementing a new way of populating the drop-down list for MPC, since pulling from the API in whatever way it does currently produces terribly inconsistent results.

In contrast, AutoHotKey consistently returns the correct numbers for active monitors, the same numbers displayed by Windows, the NVidia control panel, and even UltraMon. I can write an AHK script to reliably push MPC to my secondary monitor without error, but MPC really should be able to do this on its own.

Anyway, that's my only real suggestion at this point, since using MPC alone is and has never been a dependable solution for getting fullscreen video onto the correct monitor every time I use it. Having to unplug cables and restart the machine isn't viable for firing up videos on the fly.

I understand if you don't have the time or inclination to take on that task, but I'm certain that it must be possible to do. Maybe I'll have a look at the source myself if I can't find an alternative player for my needs.

**Comment by clsid2** [comment]
I am not changing anything. It is your system that is not working properly.

**Comment by chinagreenelvis** [comment]
> It is your system that is not working properly.

No, it's a consequence of how whatever part of the API that MPC is pulling from functions, which has nothing to do with "my" system and everything to do with how Windows and MPC are each designed. 

What Media Player Classic *should* be doing - which is not your fault since you almost certainly weren't involved in it when it was designed this way - is handling the monitor numbering in the same way that the Windows frontend does when it shows a user what numbers each monitor is, the same way that NVidia control panel does it, the same way that AHK does it, and the same way that UltraMon does it. If that were the case, it would never wind up designating the primary monitor as #2, which is almost inevitably does on any system that doesn't keep the same monitor setup 24/7.

If you have no time or interest in addressing this problem, that's fine, but it's dishonest to suggest that there isn't anything that can't be done to solve it.

in fact, reading some of your responses to other requests, I'd say it looks like you don't have a whole lot of interest in actually developing MPC at all, which, again, is fine since without you, probably nobody would be paying it any attention whatsoever. If feature development is dead or restricted, then you're better off just stating that instead of treating every issue as if it's the fault of the end-user.

**Comment by chinagreenelvis** [comment]
And anyhow, as I said already, if I can't find a better alternative overall, I'll probably just have a look at the source myself and contribute a potential fork if I can figure out what needs to be done, since MPC is obviously in a state where anyone who wants to see even a moderate feature change or request probably needs to step up and do it themselves.

**Comment by chinagreenelvis** [comment]
After all:

> It has no direct connection with the identification numbers shown by Windows in its display settings.

It probably _should_. Why couldn't it?

**Comment by clsid2** [comment]
>in fact, reading some of your responses to other requests, I'd say it looks like you don't have a whole lot of interest in actually developing MPC at all

I am not interested in implementing every idiotic request that people throw at me. My time is limited, so I restrict development to things that I actually care about. I do this for free, for fun, and I don't like people telling me what to do.

Your system does have a problem, because it keeps giving the same hardware a new name/identifier. That is not normal, and the reason why others may not have the same problem as you have.

You can give the enumerated names an index and ignore the names. What I said is that the names themselves do not have direct connection.

**Comment by chinagreenelvis** [comment]
Well, I don't know how much interest you have in continuing this thread or if you think my request is _idiotic_, but here's a screenshot that can better explain exactly what it is that I'm talking about.

![Screenshot (1)](https://user-images.githubusercontent.com/8682349/153253043-b8ebb70e-0970-4dcf-9f2f-7060735883dc.png)

The card is an RTX 3080. (I was having this issue long before upgrading to this card.)

I was able to produce these results by leaving my headset plugged into the HDMI port, my secondary monitor plugged into the middle DisplayPort, and unplugging my primary monitor from the outermost DisplayPort and restarting the machine.

After rebooting windows, I plugged my primary monitor back in and it was automatically recognized.

As you can see, AutoHotKey, NVidia CPL, and UltraMon all display the correct numbers, despite the secondary monitor being active at boot-up. Meanwhile, MPC now has the primary monitor enumerated as #2.

It seems to me that whatever method MPC is using to populate that list _is not the ideal way of doing it_.

Other users probably do not have this complaint because most people probably do not need this feature (fullscreen on a secondary monitor) on a system where the monitor setup is likely to change frequently and sometimes between restarts. I do, unfortunately. Short of any interest you'd have in attacking this issue, my only options are

1. find an alternative to MPC that has a monitor detection method more consistent with screen management programs

2. find a way to get the numbers that MPC expects using AHK in order to pre-set the INI (the MPC INI doesn't actually need the full monitor name, you can set "MonitorNumber=\\.\DISPLAY2" and it will pick the display it believes is secondary)

3. start combing through the MPC source myself and do a pull request at some point

Thanks for your time so far, if you have anything constructive to add, I'm open to suggestions.

**Comment by clsid2** [comment]
I am not spending time on this. You or someone else has to improve the code.
