### ISSUE TITLE
[BUG] Jump Forward or Back freezes MPC-HC in Full Screen (Windows 8.1 Pro x64)

### ISSUE THREAD

**Issue by JNavas2** [clsid2/mpc-hc#1503]
- When in Full Screen, pressing Left or Right Arrow during playback causes MPC-HC to freeze.
- Atl+Tab causes MPC-HC to unfreeze.
- When not in Full Screen, Left and Right Arrow work fine.

- Video file: 1080p HEVC.
- Screen resolution: 2560 x 1440.
- Processor: i7-7820HQ
- Graphics: Intel 630 and NVIDIA 940MX
- OS: Windows 8.1 Pro x64

**Comment by clsid2** [comment]
Try different video renderer in the player options.

**Comment by JNavas2** [comment]
@clsid2 Thank you for the fast response (and for MPC-HC).

My Options > Output > DirectShow Video was set to `Enhanced Video Renderer (custom presenter)`.
I switched to `Sync Renderer`, and no longer got the problem.
Is there any downside to the change?

**Further investigation:**
I experienced the problem when running on battery with Windows Power Management set to `Power Saver`.
When I plug in to mains power, I no longer get the problem.
Likewise no problem on battery when I switch Power Management to `Balanced`.

I checked, and MPC-HC is set to use `Intel 630` rather than `NVIDIA 940MX`.

Another possible factor is that the video file I'm playing is stored on my Google Drive,
which is downloading it to a virtual drive as I play it, and the Wi-Fi connection wasn't the best.

**Comment by clsid2** [comment]
If your Wifi is unstable, then I suggest copying the file to a local drive before playback.

**Comment by JNavas2** [comment]
@clsid2 Sure. In Google Drive virtual drive terms, that means selecting `Available Offline`.
But that can mean waiting 20-30 mins for the download to complete, which can be frustrating.
The advantage to virtual drive is that it downloads and caches invisibly what you need when you need it.
