### ISSUE TITLE
File associations can be set without administrator rights

### ISSUE THREAD

**Issue by dantmnf** [clsid2/mpc-hc#1507]
Just tried to replace all `HKEY_CLASSES_ROOT` and `HKEY_LOCAL_MACHINE` in `FileAssoc.cpp` with counterparts in `HKEY_CURRENT_USER` and it works well on Windows 10/11.

No idea if it will work on earlier versions of Windows though.

**Comment by clsid2** [comment]
You don't need to tell me anything about file associations and the windows registry. I already know everything.

I am not interested in implementing any changes.
