### ISSUE TITLE
Bandwdith utilization - When using Dark Mode!

### ISSUE THREAD

**Issue by Feejus** [clsid2/mpc-hc#1509]
Background: I been using this for a long time and had no issue. Computer is a bit old but still copes well with day to day task. Yet i noticed since last update something very particular. 

Problem: I use FlashFXP to download files, This has been working flawless. Yet I noticed something very particular. The speed to the FTP server nearly halfed! I could not figure out why. I raised a ticket with ISP and the FTP server owner and both of them could not find a fault.  I turned everything off and noticed that when using the Media Player in "Dark Mode" I would loose ½ of my bandwidth to the ftp server. As soon as i run in normal mode it works fine. Ran Anti-virus check which has come clean. 

Troubleshoot:
1. Turn off all application (browser, mail etc). Run a speed test against the ftp server.  - Result full badwidth use. 
2.  Open video file and now watch the video while downloading file in normal mode (after reinstall). Based on my observation the bandwidth is good. 
3.  Now at this stage i changed the player to "Dark Mode" - within second the bandwidt dropped by half!

I could potentially run a debug log, but would apricate before running it, get guidence what information you might need to troubleshoot this issue.

**Comment by Feejus** [comment]
In fact, i just noticed, as soon as i run any video low res or high res the connection speed drops!

**Comment by clsid2** [comment]
Not fault of the player. I can't help you.

Your computer is probably just too slow or you have buggy audio/video drivers that increase DPC latency affecting your network stack.

**Comment by Feejus** [comment]
I understand, but you did not even took the time to look at logs. Yes computer is a few years old but the issue started from now where. When i run this in VLC, this does not occur! Surly this is worth to look into?

**Comment by clsid2** [comment]
So WHICH log should I look at? What EXACTLY do you expect me to see in that log?

**Comment by Feejus** [comment]
Dear clsid, 
I did find the tone of your answer rather aggressive. If you do not wish to support the issue its fine, but your statement  "probably just to slow or have buggy audio/video drivers" show that you not looking to prove the fact rather shut it down. 
Without any evidence, how do you know how old computer is? Or if it is a buggy driver? Maybe a change in the code cause some sort of leak? There are other logs, like Network logs etc! Again, I am no coder to be able to understand why this started to happen last 3-4 weeks. Just pointing out that i notice a change. 

For example, (i can't read debug code) if you look at what is happening when i run the file you could come to the conclusion that there is an issue with latest code which causes the issue to occur. 

Again i raised the issue to help the community and if you standby your comment and don't want help that is fine, but no need to be rude about it.

**Comment by ale5000-git** [comment]
@Feejus: There is a know issue on some version of Windows that network and audio affect every other).
I suggest to run Windows update to install all updates, and then update drivers (specially audio and lan/wireless) with "Snappy Driver Installer Origin" (it usually have drivers more updated in comparison of the ones that you find in official sites).

I have installed Windows 10 Pro on a lot of PC of 15 years ago (with SSD and updated drivers) and everything works perfectly.

**Comment by clsid2** [comment]
I react this way because I am 100% right.

I expect an apology when you finally realize that your problem is not the fault of the player.

**Comment by Feejus** [comment]
> @Feejus: There is a know issue on some version of Windows that network and audio affect every other). I suggest to run Windows update to install all updates, and then update drivers (specially audio and lan/wireless) with "Snappy Driver Installer Origin" (it usually have drivers more updated in comparison of the ones that you find in official sites).
> 
> I have installed Windows 10 Pro on a lot of PC of 15 years ago (with SSD and updated drivers) and everything works perfectly.

Truly appreciate the more positive feedback. I have ran windows update (I can provide build number etc). There is no updated drivers for LAN (Network, which btw i use Ethernet directly into the router) or sound. 

I was keen to better understand a full root cause analysis. Yet it is very clear that I am not getting much support from the developer. Thank you for the kind support.

**Comment by Feejus** [comment]
> I react this way because I am 100% right.
> 
> I expect an apology when you finally realize that your problem is not the fault of the player.

What you say is that the code is 100% flawless and would not have any bug, all other bugs are with other system. I am sorry that is just no true, I appreciate your directness and can see that you have no keen interest to look into this matter. Pls go ahead and close this case, however if you do want to work with me to find the root cause, I am here to provide you logs and anything else you might need to be able to troubleshoot this matter.
