### ISSUE TITLE
[Feature requeast] Auto Subtitle Translation

### ISSUE THREAD

**Issue by MuhammetEminCakir** [clsid2/mpc-hc#1510]
Please, add auto translate subtitles option like Youtube.

**Comment by MuhammetEminCakir** [comment]
I think i did not explain correctly. I want to a feature for translate subtitle files automatically like PotPlayer and MXplayer. Developers can use Google Translate API for this. 

PotPlayer can translate subtitles to any language with Google Translate, Yandex Translate, etc.
![Ekran görüntüsü 2022-02-02 023216](https://user-images.githubusercontent.com/64583157/152071148-61eb7fb9-61ac-4821-8e32-f30d81d4da49.png)

MXplayer can only translate to English.
![WhatsApp Image 2022-02-02 at 02 38 42](https://user-images.githubusercontent.com/64583157/152071314-1072219d-744f-49f2-befc-944b379060c0.jpeg)

**Comment by clsid2** [comment]
I am not interested in adding such functionality.
