### ISSUE TITLE
Subtitles staying in screenshots when I screenshot while the video is playing 

### ISSUE THREAD

**Issue by poitar** [clsid2/mpc-hc#1514]
When I was on .1.9.1 whenever I took a screenshot while the video was not paused the subtitles would not show up in the screenshot, and when I paused the video and took a screenshot the subtitles where there.
But since updating to 1.9.18 the subtitles are always there no matter if the video is playing or not, And now I have to manually go to my madVR options to turn off subtitles showing in the screenshots. And when I do want subtitles in my screenshots I have to manually turn it on again.
The previous way screenshotting worked was very convenient to me, and I wonder if there was anyway to get it back?

**Comment by clsid2** [comment]
madvr is responsible for the screenshot, and its options control if subtitle is included or not. There should not be any difference in paused vs unpaused.
