### ISSUE TITLE
 Incorrect rendering of ass

### ISSUE THREAD

**Issue by dyphire** [clsid2/mpc-hc#1516]
Test sample: 
```
[Script Info]
ScriptType: v4.00+
Collisions: Normal
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1920
PlayResY: 804
Timer: 0.0000
WrapStyle: 0

[V4+ Styles]
Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,Strikeout,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding
Style: Test1,方正宋黑_GBK,35,&H002F2F2F,&H000000FF,&H005854FB,&H00000000,0,0,0,0,100,100,0,0,1,0,0,2,10,10,13,1

[Events]
Format: Layer,Start,End,Style,Name,MarginL,MarginR,MarginV,Effect,Text
Dialogue: 0,0:00:00.00,0:00:10.00,Test1,,0000,0000,0000,,{\fad(0,182)\pos(246.8,737)} \h抱歉！！\N\h\h\h\h\h\h\h\h今天要试镜！\N\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h\h滚
```
here is how it is rendered by MPC-HC
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/01/26/20220126222953.png)

XySubFilter by Pinterf renders:
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/01/26/20220126223048.png)

libass by mpv renders:
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/01/26/20220126224933.png)

 Font file:
[Font.zip](https://github.com/clsid2/mpc-hc/files/7942550/Font.zip)

**Comment by dyphire** [comment]
When fontname uses `SourceHanSansSC-Regular`, MPC-HC can render it correctly.
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/01/26/20220126225349.png)
This is confusing.

**Comment by clsid2** [comment]
Maybe an issue with \h character (= non-breaking space) in that first font.

**Comment by dyphire** [comment]
> Maybe an issue with \h character (= non-breaking space) in that first font.

Could it be fixed？

**Comment by clsid2** [comment]
This is super low priority for me.

I recommend to use a font that is not broken.

**Comment by dyphire** [comment]
> This is super low priority for me.
> 
> I recommend to use a font that is not broken.

However, both libass and XySubFilter can render normally. Shouldn't MPC-HC improve this compatibility?

**Comment by clsid2** [comment]
libass can fallback to a different font if a character is missing in a font. So saying that works correct is not always true, as it just hides the problem. MPC-HC does not have that ability, nor will it get it. Individual fonts can have their own fallback, but many do not.

Again, since this only happens with a specific font, it is low priority for me.

**Comment by dyphire** [comment]
In fact, I also tested other fontname: `方正准圆_GBK`,`方正兰亭黑_GBK`,`华康圆体W7-A`,`宋体`,`黑体`,..., and MPC-HC can't render normally. so it's not a issue with a font, it is a issue for  MPC-HC.
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/01/26/20220126235538.png)
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/01/26/20220126235615.png)
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/01/26/20220126235709.png)
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/01/26/20220126235724.png)
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/01/26/20220126235758.png)
.......
Similarly, XySubFilter and  libass can render.

**Comment by dyphire** [comment]
If this is indeed a font issue, I'm afraid it is common in Chinese fonts. Then this will affect more users. I still hope that MPC-HC can fix it as a higher priority.

**Comment by clsid2** [comment]
Can you replicate the problem with a font that doesn't have Chinese letters in its name?

**Comment by clsid2** [comment]
Fixed

**Comment by dyphire** [comment]
> Fixed

It works, thanks.
