### ISSUE TITLE
Pan&Scan options - steps too large

### ISSUE THREAD

**Issue by andrewz1986** [clsid2/mpc-hc#1517]
From time to time, the video I'm playing have to be cropped on the fly because it has ugly borders. I use View -> Pan&Scan -> Increase/Decrease for this, or to be more specific, default numpad shortcuts. 

![obrazek](https://user-images.githubusercontent.com/40487872/151387311-36a90b7f-c13b-40bf-b880-e51c1a4a12de.png)

Unfortunately, default steps are too large, so the result is that I crop more pixels than I want. Could there please be an option to change how large these steps are? Keys 3 and 7 on numpad could be used for this, because no shortcut is assigned at the moment.

Thanks.

**Comment by clsid2** [comment]
Sorry, I am not going to add options for that. Default step size is already small.
