### ISSUE TITLE
Just a small feature request

### ISSUE THREAD

**Issue by KTriebler** [clsid2/mpc-hc#1518]
Hello Dev Team,

I use MPC-HC exclusively to play my MP3 files on my PC (still haven't found yet any adequate music player with folder playback), and of course for all my video files as well.

The one thing I wish MPC-HC was capable of is displaying more MP3 id3 tag infos during playback (when selecting View-->Information (Ctrl+3)). Currently it shows Title and Author, but I (classical music lover) would love to see the id3 tags "composer" and "year" (of recording) too. Ideal would be a configurable display (not an overlay display, just below the main (cover) view). WinAmp used to have a neat feature to select an individual text by means of a script with variables that was kind of ok, but it was scrolling - I would prefere to see all info at the same time. I know that developing an own script interpreter for this is too much to ask, but maybe you could let the user select in the options which tags to be shown during playback?

I would gladly pay 50 Dollars into your coffee kitty for this.

Thanks and best regards
Karsten

**Comment by clsid2** [comment]
I am not interested in adding such options.

There are lots of better audio players, for example Winamp and Foobar.

**Comment by KTriebler** [comment]
Hi,

 

You're breaking my heart :,(

 

WinAmp only supports playlist based playback, Foobar, while it's powerful (I use it for other tasks), it's not an appealing media player.

 

But if you think it's a too big to add feature I will have to live with it.

 

Cheers

KT

 
 

Gesendet: Donnerstag, 27. Januar 2022 um 19:28 Uhr
Von: "clsid2" ***@***.***>
An: "clsid2/mpc-hc" ***@***.***>
Cc: "KTriebler" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [clsid2/mpc-hc] Just a small feature request (Issue #1518)


 

I am not interested in adding such options.

There are lots of better audio players, for example Winamp and Foobar.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by clsid2** [comment]
My Winamp can play folders just fine.

**Comment by KTriebler** [comment]
Huh? That's news to me. Ok, I'll try it out, thanks.

 

Which version are you using?

 

Cheers

KT
 

Gesendet: Donnerstag, 27. Januar 2022 um 19:49 Uhr
Von: "clsid2" ***@***.***>
An: "clsid2/mpc-hc" ***@***.***>
Cc: "KTriebler" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [clsid2/mpc-hc] Just a small feature request (Issue #1518)


 

My Winamp can play folders just fine.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by clsid2** [comment]
5.666

**Comment by lifegpc** [comment]
I am currently using [MusicPlayer2](https://github.com/zhongyang219/MusicPlayer2). It have good lyrics support

**Comment by KTriebler** [comment]
Thanks for the hint, lifegpc, will try it.
