### ISSUE TITLE
MPC-HC noticing screen tearing lately

### ISSUE THREAD

**Issue by FA-TAAA** [clsid2/mpc-hc#1519]
i uninstalled and reinstalled mpc-hc , i disabled freesync and enabled vsync anc i still have the screen tearing can someone help pls

**Comment by clsid2** [comment]
If you are using "Enhanced Video Renderer (Custom Presenter)", then you can enable VSync in the renderer by pressing **V**. If that does not help, then there is a bug in the graphics driver.

**Comment by sserdda-liamE** [comment]
There may have been a bug with one of Nvidia's drivers.  Out of the blue I was getting a synchronous tear about 1/3rd of the way down the screen using madVR fullscreen.  A clean driver reinstall fixed it.  (on 497.29 now with no issues)

**Comment by AdrX003** [comment]
on my case the tearing was solved by disabling V-Sync (on a GeForce GX 710M)
