### ISSUE TITLE
YTDLVideoFormat Options do nothing. 

### ISSUE THREAD

**Issue by Haiyami** [clsid2/mpc-hc#1522]
So I tried going to Options>Advanced>YTDLVideoFormat settings. In default settings on 0. The video format downloads the file as the extension webm.  I tried using Option 1 and 2 for H.264 and options 7 and 8 for AVI. The file still downloaded with an extension of .webm so I'm really confused on why it isn't working. Was i only supposed to copy the ffmpeg.exe file into the MPC-HC home directory? When I unzipped ffmpeg.zip file, inside the uncompressed folder were a bin folder, doc folder, and presets folder. Are those supposed to go somewhere as well? I also threw in the madVR and MpcVIdeoRenderer-0.6.7.1807 folder inside the MPC-HC directory folder and then clicked the installation files for each plugin respectively. 

So I'm not sure if things are working correctly to download a video from youtube. I don't want to just have the file extension .webm as it doesn't play nice with my video editing software nor with mkv  extract or aegis sub when I'm trying to either do mashup montages or making English subtitles for videos in another language. 

Much appreciated if someone could steer me in the right direction.

**Comment by clsid2** [comment]
That setting is for streaming playback only.
You can use the YDLCommandLine setting to customize the download behavior.
ffmpeg.exe needs to be copied directly into the MPC-HC folder. The other files from the ZIP are not needed.
For issues with video editing you need to seek help elsewhere.
