### ISSUE TITLE
[Feature] Paused State

### ISSUE THREAD

**Issue by blohsh71** [clsid2/mpc-hc#1523]
I was wondering if there could be an option to check mark in settings to start video in paused state, i mean what ever video i start or if i play next file it is started in paused state and i manually have to play it.

**Comment by BoomerangAide** [comment]
What would be the difference with going in Options/Playback, then in the Playback area, setting Play to "0 times"?
That may help making the details easier to understand.

**Comment by clsid2** [comment]
Play to "0 times" should do what you want.

I am not going to add any new options.
