### ISSUE TITLE
Two questions about playback speed adjustment

### ISSUE THREAD

**Issue by harmandmen** [clsid2/mpc-hc#1524]
I've just upgraded to the latest 1.9.19 and I'm still experimenting a longstanding (at least in my Win10-64 PC) _"problem"_ with changing the playback speed.

Despite using, as recommended, the _"SaneAR audio renderer"_, I still have frequent lags when changing the speed, either with the menu or with the Ctrl+up/down key combinations. Sometimes the speed change occurs immediately, other times it takes even 10-15 seconds, during which the program window turns black and the title bar reports _"not responding"_.

Moreover, I noticed that the "overview of features" in the readme file mentions some _"buttons in the player that control playback rate"_.
Where should those buttons be located? I can't see them in my toolbar and I didn't find any way to enable them.

Thanks in advance for any help.

**Comment by clsid2** [comment]
The 5th and 6th button. They literally have tooltips that say increase/decrease speed. So how the fuck are you unable to find them? It is not like there dozens of buttons...

Changing speed works totally fine for me. Playing at a faster rate means the decoder has to do more work. Your computer might not be fast enough. You have a pretty old GPU. Or your audio driver has some issues. I don't know how to help you. Make sure that you are using the internal codecs. Try different audio renderer. Changing speed may also not work with audio bitstreaming, so turn that off if you are using that.

**Comment by harmandmen** [comment]
There is no need to answer in an annoyed manner.
My question was no rude or argumentative at all.

My PC is almost new (i9-11900) and has no problems whatsoever in changing playback speed with other players.
So I just was asking some advice about the possible reason why mpc-hc behaves so strangely.
Just asking, not arguing or complaining.

**Comment by clsid2** [comment]
In your previous issue you mentioned you have a GeForce 9800 GT, which is super old (2008).

The only suggestions I have are to try different video and audio renderer in the player settings.

**Comment by harmandmen** [comment]
If the problem comes from the "super old" GPU, then also other media players should be affected, which does not happen.
Moreover, as far as I remember, in the past it didn't even happen with mpc-hc and even now it does not happen always, regularly, but somehow randomly; which seems hardly attributable to the GPU, because its performance is obviously always the same.

Anyway, as I said, I'm not arguing or complaining and I certainly can live with this little "problem".
I simply wanted to ask and also to report this behaviour, just thinking it maybe could be useful information for developers.
