### ISSUE TITLE
Feature request: Toolbar buttons hiding in fullscreen

### ISSUE THREAD

**Issue by bw4518** [clsid2/mpc-hc#1525]
Would it be possible to add an option to Fullscreen settings to turn off toolbar buttons when mpc is in normal fullscreen (not exclusive) mode?

**Comment by clsid2** [comment]
The toolbar already hides automatically if you move your mouse away from it.

I am not adding any options.

**Comment by bw4518** [comment]
That's a funny answer :D Of course I know it hides, but I just need the seekbar in fullscreen, that's why I asked. Not a big deal though.

**Comment by clsid2** [comment]
That option already exists:
Menu > View > Controls

**Comment by bw4518** [comment]
Excellent, not what I initially wanted, but gave me an idea that I don't need the controls in windowed mode either. Thanks.
