### ISSUE TITLE
preview problem

### ISSUE THREAD

**Issue by EgeGurkan** [clsid2/mpc-hc#1526]
As seen in screenshot. subtitles windows is shown when i hover on preview. but actually. subtitle window is closed. not even background. it is closed. but somehow when i hover on preview. it is there.

https://i73.servimg.com/u/f73/20/40/36/69/110.png

**Comment by clsid2** [comment]
Do you have the subtitle search option enabled in the player settings?
If you close subtitles window, does it re-appear again each time you hover on the taskbar preview?

Do you have Slack messenger installed? That has a bug that can cause hidden windows of other applications to suddenly appear.

**Comment by EgeGurkan** [comment]
-subtitle search option enabled
-when i hower it appears, if i move mouse from taskbar to close the window > then it dissapears because i am not howering anymore, so i can't manually close it
-no i don't have slack messenger

_+ another bug, when i go to fullscreen by double clicking SOMETIMES embedded subtitle changes to another subtitle (the movie i tested had more than 4 embedded subtitles, i experienced it changed english to german and then german to italian)_

I realised, it happens when you press "S", it changes between embedded subtitles, i thought it was for hiding/showing subtitles??? it switches between embedded subs now. how to hide subs then.

**Comment by clsid2** [comment]
W is for toggling subtitles on/off
S is to toggle between tracks, but this also includes a "no subtitles" choice. See: Menu > play > Subtitles.

**Comment by clsid2** [comment]
@adipose
Are you able to reproduce this?

**Comment by EgeGurkan** [comment]
here i recorded my screen to show it
https://www53.zippyshare.com/v/FhchSDUj/file.html

**Comment by EgeGurkan** [comment]
here are my regedit
https://www43.zippyshare.com/v/97wJ6leb/file.html

**Comment by adipose** [comment]
> @adipose Are you able to reproduce this?

Not so far.  Maybe the callback is opening the window after the search finishes?

**Comment by clsid2** [comment]
You can see very clearly what happens in the recorded video. The subtitle search window appears at the moment he moves the mouse pointer on top of the video of the taskbar preview. Here that action minimizes other windows (if maximized) or makes them transparent (if non-maximized). Same happens if I do it with my browser or Explorer, so that is a Windows action. Somehow that triggers unhiding the search window.

**Comment by adipose** [comment]
Yes, I saw the video, but I couldn't reproduce the behavior.  However, if the window is really still around, we could probably just destroy it, and solve the problem.  But I'm not sure what keeps it open/alive.  A lot of popup windows are destroyed after they are closed, but maybe this one was still hanging onto a thread or something.

I don't remember how it works but I will take a look.

**Comment by clsid2** [comment]
I think it is kept alive in case a user want to re-open to download a different search result.

**Comment by clsid2** [comment]
I can reproduce on Windows 11.

**Comment by adipose** [comment]
Reproduced.

**Comment by adipose** [comment]
Closest thing I have seen: https://stackoverflow.com/questions/66159456/hidden-jdialog-still-visible-in-windows-10-taskbar-peek-preview

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1564/files

**Comment by adipose** [comment]
https://techcommunity.microsoft.com/t5/report-an-issue/hidden-non-modal-dialogs-displayed-during-peek-preview/m-p/3206463#M8446

**Comment by adipose** [comment]
https://techcommunity.microsoft.com/t5/report-an-issue/hidden-non-modal-dialogs-displayed-during-peek-preview/m-p/3206614#M8448

**Comment by xLn2** [comment]
It is still happening on Windows 10 21H1.  Mpc-hc Version:  1.9.19.21 (6856deaaa)
   

- Open video 
- Press D 
- Close subtitle download screen
- Minimize media player or swap another application
- preview mpc
![image](https://user-images.githubusercontent.com/3073922/155446726-e6561d12-adab-4a27-b7a6-496f22bdc4fc.png)

Behavior continue until activation of media player.  When media player activated subtitle downloader has not seen anymore.

p.s (maybe its irrelevant, during screenshotting I changed mpc-hc language and subtitle downloader's language did not change. Probably its intended behavior that follow language at application start.)

**Comment by adipose** [comment]
Good to know it affects older builds too. Must have been fixed in 10. I can enable fix for older 10.x

**Comment by ale5000-git** [comment]
Any problem using the workaround under all version of Windows?

It is worth testing if it can also workaround the Slack issue (#1084).

**Comment by adipose** [comment]
It is safe to use on Windows 10 I think, but I wanted to a avoid it when possible.

**Comment by adipose** [comment]
> It is still happening on Windows 10 21H1. Mpc-hc Version: 1.9.19.21 ([6856dea](https://github.com/clsid2/mpc-hc/commit/6856deaaa7c724af876859e109aff3a1b8274d60))
> 
>     * Open video
> 
>     * Press D
> 
>     * Close subtitle download screen
> 
>     * Minimize media player or swap another application
> 
>     * preview mpc
>       ![image](https://user-images.githubusercontent.com/3073922/155446726-e6561d12-adab-4a27-b7a6-496f22bdc4fc.png)
> 
> 
> Behavior continue until activation of media player. When media player activated subtitle downloader has not seen anymore.
> 
> p.s (maybe its irrelevant, during screenshotting I changed mpc-hc language and subtitle downloader's language did not change. Probably its intended behavior that follow language at application start.)

I could not get this behavior on 21H1.  Unsure why, but maybe there's a difference in the taskbar settings.

**Comment by xLn2** [comment]
> > It is still happening on Windows 10 21H1. Mpc-hc Version: 1.9.19.21 ([6856dea](https://github.com/clsid2/mpc-hc/commit/6856deaaa7c724af876859e109aff3a1b8274d60))
> > ```
> > * Open video
> > 
> > * Press D
> > 
> > * Close subtitle download screen
> > 
> > * Minimize media player or swap another application
> > 
> > * preview mpc
> >   ![image](https://user-images.githubusercontent.com/3073922/155446726-e6561d12-adab-4a27-b7a6-496f22bdc4fc.png)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Behavior continue until activation of media player. When media player activated subtitle downloader has not seen anymore.
> > p.s (maybe its irrelevant, during screenshotting I changed mpc-hc language and subtitle downloader's language did not change. Probably its intended behavior that follow language at application start.)
> 
> I could not get this behavior on 21H1. Unsure why, but maybe there's a difference in the taskbar settings.

My windows version
	Windows 10 Pro
	21H1
	‎4.‎12.‎2020
	19043.1526
	Windows Feature Experience Pack 120.2212.4170.0
____
also tested on windows 10 20H2, MPC 1.9.19.32 seems same behavior.

**Comment by adipose** [comment]
![image](https://user-images.githubusercontent.com/3324395/155610180-bdd43929-5811-4a4e-a2cd-6cf61b211a42.png)

**Comment by adipose** [comment]
Well, I created a patch for win10.  I don't understand why the issue is rare in 10, but the java dialog issue I found also had issues with win10.  It may be a setting I have disabled on win10, like animations or something.

https://github.com/clsid2/mpc-hc/pull/1569/files

**Comment by adipose** [comment]
I reproduced the issue in 10 21H2.
