### ISSUE TITLE
[Bug] Changing playback speed when paused forces the playback to start again

### ISSUE THREAD

**Issue by MobButcher** [clsid2/mpc-hc#1527]
When I use keyboard shortcuts to change the playback speed (Increase Rate and Decrease Rate, as they are called in Keys) while on pause, the playback resumes, which I do not believe to be an intended behavior. It causes me a lot of problems because I can't watch certain scenes in 100% speed (my PC is too slow to decode them fast enough). When I try to decrease the playback speed, the program freezes for minutes until it could once again regain control.

What should happen:
When pressing Increase Rate/Decrease Rate shortcuts, play/pause state should stay the same, playback should not resume until user unpaused the video manually. (Or at least have an option to toggle this behavior).

What actually happens:
When pressing Increase Rate/Decrease Rate shortcuts when paused, playback immediately resumes, causing lag and inability to change playback speed until video decoding catches up to realtime.

Tested on latest version of MPC-HC, 1.9.19 on Windows 10 21H2.

**Comment by clsid2** [comment]
It was actually intentional, because it seems logical to resume.

If you need to adjust rate more than once, then I assume you want to play at less than half speed? Maybe use the rate options in the menu to directly set the desired rate.
Menu > Play > Playback Rate
