### ISSUE TITLE
[Bug] Cannot play linked .MKV files

### ISSUE THREAD

**Issue by zwei7** [clsid2/mpc-hc#1529]
Tried playing episode 1 of this file
https://nyaa.si/view/780428

And all I get is an unresponsive MPC-HC 1.9.19x64 saying "opening file" in the status bar. It just hangs there indefinitely.

MPC-BE 1.6.1 can open it and play it, though it fails somewhat since it cannot link the files to form the full 24 minute episode, only 21 minutes, since it is using its own internal mkv filter that cannot link mkvs together.

MPV-HC 1.7.13x64 can do it, even though it is older than this fork you made. Something broke along the updates.

Edit: I did not read that 1.9.19 was a buggy development build, will revert back to stable 1.9.18.

**Comment by clsid2** [comment]
It plays correctly here. The linked Opening and Ending are playing normally.

1.9.19 is a stable build, and I have no idea where you go that wrong information about it being buggy.

**Comment by zwei7** [comment]
Must be me, but I uninstalled 1.9.19 and installed 1.9.18 to fix it. It works again.

**Comment by clsid2** [comment]
This video was encoded with a buggy version of x264. The decoder has a workaround to decode it properly, but that only works if you play it from the beginning of the video (because there it has metadata that contains the x264 version). If you start at a non-zero position, for example due to remember position, it will give corrupted playback.

**Comment by zwei7** [comment]
That explains all the green screen corrupted frames I've been getting with 1.9.18 when seeking.
However 1.9.19 displayed a black screen and wouldn't play the video at all.

**Comment by clsid2** [comment]
For me it is same green with 1.9.19. Press Home button on keyboard to jump to begin, and payback should be normal, including seeks after that.

**Comment by bibsp** [comment]
Well I have tested the file. The video is playing without any problem in MPC-HC 1.9.19 x64, Win 10. Even no problem when seeking. No green screen, black screen nothing. MX Player Pro (Android) is also playing it without issue.

But one thing is common in both system. Both PC and Android is not showing thumbnail of this particular video. But they are able to play it flawlessly.
And one more thing. Windows default Movies & TV app is not able to play it. Black screen. Stuck at 0. So the video is problematic. But MPC is handling it without issue.
