### ISSUE TITLE
In the Chinese language state using the subtitle download tool will appear search file name garbled code

### ISSUE THREAD

**Issue by l100n** [clsid2/mpc-hc#153]
In the Chinese language state using the subtitle download tool will appear search file name garbled code

![1](https://user-images.githubusercontent.com/56714143/68083546-c95cd600-fe64-11e9-9ebc-71c71ffb4418.png)
![2](https://user-images.githubusercontent.com/56714143/68083547-c95cd600-fe64-11e9-9515-f0c1f38a6071.png)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/334
