### ISSUE TITLE
Hide SMTC Pause play + name

### ISSUE THREAD

**Issue by ArtyomEnRage** [clsid2/mpc-hc#1530]
Hey, it's possible to add in the advanced tab, a way to disable the "media key handling" like chrome does ?
I'm not talking about the volume, only the part with pause play - name of video

**Comment by ArtyomEnRage** [comment]
Also, with SMTC on i can play pause with keyboard, even on different desktops but my issue is the overlay stuff (not the sound)

**Comment by clsid2** [comment]
There already is an option for that.

UseSMTC

**Comment by ArtyomEnRage** [comment]
No, i think you did not understand, I want to use SMTC but without  the overlay, because if I disable"Use SMTC", I can't use my keyboard shortcut for "play, pause, next and previous video"

**Comment by lifegpc** [comment]
Disable useSMTC and enable `Global Media Keys` (Player->Keys)

**Comment by ArtyomEnRage** [comment]
Thanks a lot
