### ISSUE TITLE
Bug? Messages not showing correctly

### ISSUE THREAD

**Issue by 8DL9** [clsid2/mpc-hc#1532]
Hi.
Messages not showing correctly:

Old Ver v1.7.13:
Good:
[https://i.postimg.cc/ryb7rDKn/1.png](url)

Ver 1.9.18.x64 and 1.9.19: 
Bug:
[https://i.postimg.cc/c1p0N9ML/2.png](url)

This bug appeared since version 1.9.18.

Win 21H2.

**Comment by clsid2** [comment]
Fixed
