### ISSUE TITLE
subtitle missing issue

### ISSUE THREAD

**Issue by jak9819** [clsid2/mpc-hc#1533]
I have a problem
I am a new user of the program, I was previously using v1.7.13 This problem was not there
for example :
I opened an episode of a series
Dexter.S01E01.1080p.BluRay.x264-FLHD
I downloaded a subtitle file via subscene.com
When I add the subtitle file to episode , everything is fine
example
I'm watching Dexter.S01E01, I stopped it at the 15th minute and left the laptop for an hour or put the laptop to sleep, 
The problem starts here
When I want to continue watching the episode and press play , the subtitle file that I previously added to the episode has disappeared and I have to add it again

**Comment by clsid2** [comment]
Already fixed yesterday. Will be in next development build.

**Comment by jak9819** [comment]
Now I am using version No.[1.9.20]
The problem is still there, not resolved
