### ISSUE TITLE
time display - lower right corner

### ISSUE THREAD

**Issue by isarrider** [clsid2/mpc-hc#1536]
Hi,

MPC-HC is my daily video player...
I like it a lot!

My feature request would be to dispay the
remaining time and elapsed time with the video time in total
and additionally when the video will end...
(and maybe so in the OSD when jumping in a video)

Example:
we have an 120min video and now it is 10:00

[01:30:00 / -00:30:00 / 02:00:00 - ends at 10:30]

Thoughts?

Thx,
Alex

**Comment by clsid2** [comment]
I am not adding such options.

You can show remaining time by right-clicking on the time in status bar.

**Comment by isarrider** [comment]
:(
