### ISSUE TITLE
Feature request: display subtitles when seeking to a moment after the subtitle is initially triggered

### ISSUE THREAD

**Issue by heddy1** [clsid2/mpc-hc#1537]
Expected behavior: I seek a video to a few seconds ago. The subtitle that originally displayed on that frame displays.

Actual behavior: I seek a video to a few seconds ago. The subtitle that originally displayed on that frame does not display.

Details: Let's say for example a subtitle line is set to appear for the time 1:34-1:38 in a video. When watching the video normally, the subtitle appears at 1:34, and disappears at 1:38. At 1:45, if you decide to press the left arrow key which seeks 10 seconds back, it seeks to 1:35, and no subtitle appears. The subtitle does not appear, because it is only designed to appear at 1:34, even if you seek to a short moment after that it does not display. This is inconvenient, because it requires you to press the seek button again and seek back more seconds than you wanted to, just to get the subtitle to appear. Could a feature be added to check if a subtitle should be currently displaying? The check should be made whenever a seek button is pressed, like the left arrow key for example.

**Comment by clsid2** [comment]
It already does that.

Your files are "broken" in a sense that they are missing subtitle cue data which is essential for this behavior to function correctly. You can fix your files by remuxing them with MkvToolNix.
