### ISSUE TITLE
[Bug/Suggestion] in dark mode

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#1538]
When I hover mouse pointer over top menu bar the options are getting highlighted in light mode.
But in dark mode it does not.
In dark mode the options get highlighted only when I actually click on them to expand.

This is a very little thing which you can fix I think.
![1](https://user-images.githubusercontent.com/98865389/153171277-91048a8d-f3c1-408a-beaf-5ccb268fe997.jpg)
![2](https://user-images.githubusercontent.com/98865389/153171289-0dbb60af-3a7e-41a5-a559-58da2618b50b.jpg)
![3](https://user-images.githubusercontent.com/98865389/153171292-17352601-3640-4109-ad7b-badf78c3fb22.jpg)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1547

**Comment by xLn2** [comment]
Additionally, menu text color always same whether its top most level or bottom level. 

![resim](https://user-images.githubusercontent.com/3073922/156905026-475846ca-f962-4c13-85ae-8d38133072ca.png)
_
![resim](https://user-images.githubusercontent.com/3073922/156905034-8750d0fb-5d26-4167-97ed-bc174a08f698.png)
in example at second picture, menu text color might be grayish like title text as been.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1630

It now fades the menu text a bit when the window is not in the foreground.  Note that in Windows Explorer (the inspiration for this theme), it does not fade it, but it also has a toolbar based menu which is dissimilar to MPC-HC's menu style.  But I think this looks a bit better.

**Comment by xLn2** [comment]
Thanks, It looks nice. 
![resim](https://user-images.githubusercontent.com/3073922/160737043-005e4621-a808-4418-bf3b-cdb7d1f03990.png)

I noticed after you mentioned. that windows explorer file menu does not fade out (during bottom state) or getting highlighted on mouse hover but instead when I drag mouse on any file or folder it gets highlighted. I can only guess, that is intended behavior for windows that clickable things get highlighted. So i think that everything is clickable in mpc-hc during bottom state so I think its match with windows dark theme somehow. Thanks again for your efforts.

**Comment by bibsp** [comment]
Still one small detail mismatched.
When window is not in foreground Dark and Light theme behavior is different.

![Untitled](https://user-images.githubusercontent.com/98865389/161371686-e4ccb4b7-0065-43fb-adc1-7a318a5da467.gif)
