### ISSUE TITLE
[Feature Request] Clicking on a file in "Recent Files" will add the file to the playlist instead of clearing it.

### ISSUE THREAD

**Issue by trymion** [clsid2/mpc-hc#1539]
Hello,

My playlist is essentially a "currently watching" list and grows/shrinks over time as I watch new/old shows/movies and when it's accidentally cleared, I lose track of what episode I may have been on for whatever shows I'm watching.

Currently, if you click on a file in the "Recent Files" list that isn't on your current playlist, it will clear the playlist and add the one file to it.  

It would be a small QOL option for me if there was a way to make MPC-HC default to add new files to a playilst (when clicking in "Recent Files" or even random files/episodes/movies) instead of automatically clearing the current playlist.

**Comment by clsid2** [comment]
I am not adding any new options.

You can add to playlist by holding Ctrl button while drag&dropping a file onto the player. There is also an "add to MPC-HC playlist" entry in Explorer context menu if you set up file associations properly.
