### ISSUE TITLE
Play keyboard shortcut doesn't work after mpc starts

### ISSUE THREAD

**Issue by silverqx** [clsid2/mpc-hc#1541]
I think this is partial regression of #1301 

I can still reproduce this problem in a specific case, steps to reproduce:
- open some movie
- check all Remember checkboxes in Options - Player - History 
- play movie ( this is not really needed )
- press Alt+enter to enter fullscreen mode
- press alt+f4 to close the player
- open mpc-hc again, **last played movie and fullscreen should be remembered now**
- press space to invoke play and nothing happens

I think the problem is that fullscreen mode 🐛.

**Comment by clsid2** [comment]
Fixed

**Comment by silverqx** [comment]
Thx
