### ISSUE TITLE
Allow for yt-dlp to mark and/or remove sponsors within videos

### ISSUE THREAD

**Issue by Sn0whax** [clsid2/mpc-hc#1542]
Just looking to add a request to allow for yt-dlp to mark and/or remove sponsors within videos.
It would also be nice to have them in the "Advanced" area along with the other features (Like max height).

yt-dlp.conf also appears to be ignored (Or at least the "--sponsorblock-mark all" and "--sponsorblock-remove all" functions are ignored" when playing or saving as in a yt video.

**Comment by clsid2** [comment]
The player uses yt-dlp just to extract the URL of the stream for playback. Once it plays the stream yt-dlp is not involved anymore in any way. The player completely ignores sponsorblock data and other extra information. The player does not yet have any ability to automatically skip part of a video and I am not interested in adding that either. Someone else has to submit a patch for that.

The config file and parameter should get used when downloading, as that does get fully handled by yt-dlp.
