### ISSUE TITLE
"View" -> "Information"

### ISSUE THREAD

**Issue by radpopl** [clsid2/mpc-hc#1544]
What should the "Information" option display?
For me, it does not display anything additional.

![image](https://user-images.githubusercontent.com/11005341/153590887-8d92d1df-6ce7-4fcb-8f3e-38d7d833d2dc.png)

**Comment by lifegpc** [comment]
That video don't contain any informations. Such as title, author etc.
![image](https://user-images.githubusercontent.com/41434272/153591378-585bb639-9573-4318-97e0-fe5bb980b459.png)

**Comment by radpopl** [comment]
OK, thx, I understand. I was expecting information about codecs, resolution, etc. That would be cool :)

**Comment by clsid2** [comment]
File > Properties
