### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by githubbapoopa** [clsid2/mpc-hc#1548]
Win 10 21H2, i7 8550u,16GB

MPC-HC.1.9.19.x64 portable

mpc-hc (decoder: DXVA2 native) is configured with madvr as Video-Renderer

On playing a single x265 file mpc-hc uses about 600MB of RAM.

Am I mistaken if i think this is way to high for such a simple task? VLC uses about a third.

BTW. As of 1.9.19 frame seeking with madvr runs nice now. Thanks.
But it intruduces a kind of a "sloppy start". meaning it takes a few milisecs before video and sound actually plays.

**Comment by clsid2** [comment]
I get just 300MB usage with a 4K 10bit video. A bit less even with a different renderer.

Higher usage can be result of increased queue sizes in madvr or increased buffer sizes in the splitter.
