### ISSUE TITLE
Seek bar preview chapter name does not fit and support some characters

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#1550]
> MPC-HC (Nightly, 64-bit)
> ------------------------
> 
> Build information:
>     Version:            1.9.19.9 (690c6295b)
>     Compiler:           MSVC v19.29.30140
>     Build date:         Feb 12 2022
> 
> LAV Filters:
>     LAV Splitter:       0.76.0.2
>     LAV Video:          0.76.0.2
>     LAV Audio:          0.76.0.2
>     FFmpeg compiler:    MinGW-w64 GCC 10.2.0
> 
> Operating system:
>     Name:               Windows 10 (Build 21H1)
>     Version:            10.0.19043 (64-bit)

open seek bar preview ( Options > Tweaks > show preview on seek bar ), Open a video file that contains "&" character in chapter name and you will see that it wont be displayed on seek bar preview chapter name section. Example: Tom & Jerry will be seen as "Tom  Jerry". I noticed this one a time ago, maybe further test might need. 
And also long chapter name does not fit specified area on seek bar preview, some brainstorming can give idea.

**Comment by clsid2** [comment]
Long names should already be shortened using an ellipsis symbol (three dots).

Give example file that has problems.

**Comment by xLn2** [comment]
I do not remember the movie I watched that has long chapter name and contains "&" symbol. I do not know how to create one video file with desired chapter name so I need time to learn how to do it or someone else can give some basic video that manually edited chapter name. When I prepared a sample file I will comment on this topic.

**Comment by xLn2** [comment]
I did some test,
if "&" before space it makes half underscore to space. Chapter name: "`Tom & Jerry's best_friend?*-/%^!`"
![image](https://user-images.githubusercontent.com/3073922/153955895-f8099ec7-0312-40aa-92a6-a095dfcb9a5e.png)
______
if "&" before letter it gives underscore to letter. Probably only latest "&" works. Chapter name: "`&C&h&a&p&t&e&r 6`"
![image](https://user-images.githubusercontent.com/3073922/153956399-752f57b0-9d90-47be-b41f-3dd9e878bf48.png)

if "&" before letter it gives underscore to letter. Chapter name: "`&Hello,world`"
![image](https://user-images.githubusercontent.com/3073922/153957896-0c759a55-0bb1-4eae-9d36-865a237aaac6.png)

______
if long chapter name during dragging seek bar (same chapter) first 2 number can not rendered correctly
![image](https://user-images.githubusercontent.com/3073922/153957357-8a020863-e874-4bc6-9d63-eac0e42e1d7a.png)
______
dragging long chapter name to short one can sometimes cause 
![image](https://user-images.githubusercontent.com/3073922/153957697-aee831a2-d07d-450a-b92d-1ff4a74ed072.png)

As far as I understand its behaving like menu items, with "&" symbol it makes underscore following letter. 

Chapter list file (.mks) added below.
https://www.mediafire.com/file/voyqy0ltqwv4ebz/Breach_%25282007%2529.mks/file

You can use MKVToolnix GUI to mix video file with chapter list.
add video file and mks file
![image](https://user-images.githubusercontent.com/3073922/153959893-9f8fda95-9422-469a-867f-401fac92fd48.png)

and 
![image](https://user-images.githubusercontent.com/3073922/153959358-34dcd86f-59d3-48cf-853d-32fa8215a910.png)

**Comment by clsid2** [comment]
@adipose
Can you take a look at the redraw bug in that last "hello world" image? Probably just minor issue with calculation of the caption rect.

The & issue can easily be fixed by a string replace, but I wonder why it is being handled as a menu caption.

**Comment by adipose** [comment]
Almost surely it's a text setting for accelerator handling.  I'll see here.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1553

You can try this.  I didn't test due to not having a good video.

**Comment by clsid2** [comment]
Fixed the text redraw issue as well.
