### ISSUE TITLE
Change/revert behaviour of subtitle border style (opaque box width)

### ISSUE THREAD

**Issue by tekwarfare** [clsid2/mpc-hc#1552]
## Issue:
The subtitle border style has seen a change in 1.9.19 regarding the opaque box which, in my eyes, is a regression. In essence, the end-user has lost the ability to have an opaque border with _no overlap_.

## The old (expected, and preferred) [1.9.18] behaviour is:
Width=0 - "background" or opaque border is drawn with _zero_ overlap
Width=1 - "background" or opaque border is drawn with overlap (of "one")

![1 9 18 WIDTH 0](https://user-images.githubusercontent.com/15717600/153895424-4b567d25-a822-4a60-9e42-6970f5546539.png)

## The new [1.9.19] behaviour is:
Width=0 - "background" or opaque border is not drawn
Width=1 - "background" or opaque border is drawn with overlap (of "one")

![1 9 19 WIDTH 0](https://user-images.githubusercontent.com/15717600/153895428-ffb952ac-6d6c-416a-9d37-0c87d0279d81.png)
![1 9 19 WIDTH 1](https://user-images.githubusercontent.com/15717600/153895433-d700fea3-a320-41f7-aeb2-85e51ba611b8.png)

This stems from the fix seen in the release notes for 1.9.19: 
> Fixed subtitle issue where opaque border style could be draw even when both border and shadow were zero.

## Proposed solutions:
- Revert the width behaviour so that a value of 0 draws the opaque border with zero overlap. The border can be made invisible by setting transparency to 0%.
- Change the behaviour of Width=1 so that it draws the border with _zero_ overlap akin to Width=0 in 1.9.18. This will also require a change for all values of Width>1 -  a knock-on effect - so values of 2 and above are effectively mapped to one value lower, e.g.
OLD -> NEW
0 -> 1 (Width=1 draws border with zero overlap)
1 -> 2 (Width=2 draws border with "one" overlap)
2 -> 3 (Width=3 draws border with "two" overlap)

**Comment by clsid2** [comment]
I am not reverting it. It is an intentional change to make behavior similar to other renderers. It also fixes subtitles that rely on that behavior.

In future fractional values may be possible, then you can use 0.1 as a solution.

**Comment by clsid2** [comment]
Next build will allow setting 0.0001 as border width.
