### ISSUE TITLE
dtswav, wavdts - not working 

### ISSUE THREAD

**Issue by 1wojak** [clsid2/mpc-hc#1555]
Hi,
I use mpc-hc ver. 1.9.19. Whenever I try to play files with dts sound with extensions such as .WAVDTS or .DTSWAV or .DTS the player just skips them or stucks at the begining and nothing plays. Not even a noise. I think I tried all  the possibilities and nothing works. I changed extensions to DTSWAV, to WAVDTS to DTS, changed audio outputs (or renderers), changed filters (lav, ffmpeg), checked bitexact (or bitperfect) options and so on. I want to use Wasapi exclusive to bitstream 5.1DTS from wav files. What is interesting it works with .m2ts files but does not with wavs. When I use vlc the sound is bitsreamed to my AVR, when I use foobar the sound is decoded to 5.1 pcm and played to AVR. What to do in order to play those files in mpc-hc?

By the way is it possible to add ASIO output to the player (for usb dac usage)? But I do not mean external thirdparty asio renderer (most of them do not work or crash the palyer). I mean a function in the player (like foobar asio plugin).

**Comment by clsid2** [comment]
DTS inside WAV is working fine here. Test if it plays if you disable bitstreaming.

If that also fails, then please upload that file for me.
http://www.sendspace.com

There is no ASIO option.

**Comment by 1wojak** [comment]
The only thing that "works" for dtswav is checking "fallback to pcm if bitstreaming is not supported" in Internal filters/internal lav filters/audio decoder/audio settings/bitstreaming. It then plays pcm5.1 even though DTS and DTS-HD are checked.  If I uncheck that box there is no sound at all. Are there any other particular options to passthrough dts? Or maybe I have to install some decoders or filters or codecs? Strangely it works in other players (vlc) and it works in mpchc from avi, mkv and other "movie" files. 
I know that there is no asio but is it possible to implement that feature?

**Comment by clsid2** [comment]
I am not interested in adding ASIO support.

All internal filters must be enabled in the player settings.
It should use "LAV Splitter Source (internal)" and "LAV Audio Decoder (internal)" when looking at:
Menu > Play > Filters
Get rid of any external filters that you have installed.

Please upload one of the files for me.

**Comment by 1wojak** [comment]
All internal filters must be enabled in the player settings. 
**_All are checked (both columns)._**

It should use "LAV Splitter Source (internal)" and "LAV Audio Decoder (internal)" when looking at:
Menu > Play > Filters
_**It is like that.**_

Get rid of any external filters that you have installed.
_**I have no external filters.**_

Please upload one of the files for me.
**_It is full album in one big file, no cue, no chapters...._**

**Comment by clsid2** [comment]
I just tested with receiver, and bitstreaming indeed fails.

@nevcairiel
Is bitstreaming of DTS inside WAV supported?

**Comment by tebasuna51** [comment]
This dtswav is passthrough bitstreaming like DTS to my Denon AVR-X1500H played with MPC-HC internal LAV Filters 0.76.1
(the audio render is System Default than point to my DENON-AVR connected by HDMI to PC) 
> General
> Complete name                  : D:\Musica\Surround\sample.wav
> Format                         : Wave
> File size                      : 584 MiB
> Duration                       : 57 min 50 s
> Overall bit rate mode          : Constant
> Overall bit rate               : 1 411 kb/s
> 
> Audio
> Format                         : DTS
> Format/Info                    : Digital Theater Systems
> Codec ID                       : 1
> Duration                       : 57 min 50 s
> Bit rate mode                  : Constant
> Bit rate                       : 1 411.2 kb/s
> Channel(s)                     : 6 channels
> Channel layout                 : C L R Ls Rs LFE
> Sampling rate                  : 44.1 kHz
> Frame rate                     : 43.066 FPS (1024 SPF)
> Bit depth                      : 24 bits
> Compression mode               : Lossy
> Stream size                    : 584 MiB (100%)

I have many samples, tested with extension .wav or .dtswav or .dts, all work fine (my Denon show always DTS).

**Comment by 1wojak** [comment]
> This dtswav is passthrough bitstreaming like DTS to my Denon AVR-X1500H played with MPC-HC internal LAV Filters 0.76.1 (the audio render is System Default than point to my DENON-AVR connected by HDMI to PC)
> 
> > General
> > Complete name                  : D:\Musica\Surround\sample.wav
> > Format                         : Wave
> > File size                      : 584 MiB
> > Duration                       : 57 min 50 s
> > Overall bit rate mode          : Constant
> > Overall bit rate               : 1 411 kb/s
> > Audio
> > Format                         : DTS
> > Format/Info                    : Digital Theater Systems
> > Codec ID                       : 1
> > Duration                       : 57 min 50 s
> > Bit rate mode                  : Constant
> > Bit rate                       : 1 411.2 kb/s
> > Channel(s)                     : 6 channels
> > Channel layout                 : C L R Ls Rs LFE
> > Sampling rate                  : 44.1 kHz
> > Frame rate                     : 43.066 FPS (1024 SPF)
> > Bit depth                      : 24 bits
> > Compression mode               : Lossy
> > Stream size                    : 584 MiB (100%)
> 
> I have many samples, tested with extension .wav or .dtswav or .dts, all work fine (my Denon show always DTS).

Nothing works for me.
What are your exact settings in the following sections:
-playback/output/audio renderer
- internal filters - what is checked/unchecked in Source Filters and in Transform Filters
- internal filters/audio decoder/audio settings
- internal filter/audio swithcer 
- internal filter/audio renderer    and MPC Audio Renderer Settings
- external flters
- any other audio settings available which I did not mention?
Thanks in advance.

**Comment by clsid2** [comment]
You don't need special settings. Just enable bitstream in the audio decoder. If bitstreaming works for other file formats, then everything is already correct.

In Windows Sound settings you must enable "exclusive mode" in your audio device properties. That is required for all bitsteaming.

**Comment by 1wojak** [comment]
> You don't need special settings. Just enable bitstream in the audio decoder. If bitstreaming works for other file formats, then everything is already correct.
> 
> In Windows Sound settings you must enable "exclusive mode" in your audio device properties. That is required for all bitsteaming.

I do have bitstreaming enabled and exclusive mode. It does not work with dtswav. Bitstreaming works with for example movies with AC3 or DTS sound but does not with dtswavs. It works in VLC though. Just not in MPCHC.

**Comment by tebasuna51** [comment]
- internal filters - what is checked/unchecked in Source Filters and in Transform Filters
All checked except WMV,WMA

- internal filters/audio decoder/audio settings
DRC,Delay,Options all unchecked
Bitstreaming,Output formats all checked except Force Max DTS-HD rate
Mixing: all unchecked

- internal filter/audio swithcer
Activated but the rest unchecked

- internal filter/audio renderer and MPC Audio Renderer Settings
**Unchecked SaneAR**
the rest not available to change (but exclusive mode and ignore mixer channels checked)

- external flters
nothing

**Comment by 1wojak** [comment]
> * internal filters - what is checked/unchecked in Source Filters and in Transform Filters
>       All checked except WMV,WMA
> 
>     * internal filters/audio decoder/audio settings
>       DRC,Delay,Options all unchecked
>       Bitstreaming,Output formats all checked except Force Max DTS-HD rate
>       Mixing: all unchecked
> 
>     * internal filter/audio swithcer
>       Activated but the rest unchecked
> 
>     * internal filter/audio renderer and MPC Audio Renderer Settings
>       **Unchecked SaneAR**
>       the rest not available to change (but exclusive mode and ignore mixer channels checked)
> 
>     * external flters
>       nothing

This still does not work for me. No DTS from DTSWAV. Only if I check fallback to PCM, it plays 5.1 PCM if that option is unchecked there is no sound and the timer stucks at 0 seconds.

**Comment by clsid2** [comment]
It is NOT a settings issue, so stop wasting your time with that.

It needs to be fixed in LAV Filters.
