### ISSUE TITLE
Some playlist.m3u does not show Channel titles when the line #EXTM3U is missing

### ISSUE THREAD

**Issue by SuperPat45** [clsid2/mpc-hc#1557]
Hi,

Some playlist.m3u does not show Channel titles when the line:
`#EXTM3U`
is missing at the top of the file.

For example, all playlists of the site: https://iptv-m3ulist.live/

**Comment by clsid2** [comment]
#EXTM3U is required for parsing title metadata. Those files are invalid according to M3U specification.

Implementing a workaround for this is low priority. I suggest you contact that website so they can fix their file generation.
