### ISSUE TITLE
Proxy support for streaming from URL

### ISSUE THREAD

**Issue by AyraHikari** [clsid2/mpc-hc#1559]
mpc-hc seems ignored http and https proxy from system environment, i tried search options but did not found any proxy settings.
It will good if this player will support proxy settings later, because some country censored/blocked some streaming websites and it can solved by using proxy.
Thanks

**Comment by lifegpc** [comment]
Try `HTTP_PROXY` or `HTTPS_PROXY` environment variable. (It seems works well here.
Or use some transparent proxy such as Proxifier, phantomsocks

**Comment by AyraHikari** [comment]
> Try `HTTP_PROXY` or `HTTPS_PROXY` environment variable. (It seems works well here. Or use some transparent proxy such as Proxifier, phantomsocks

Thanks it works, mine `http_proxy` and `https_proxy` weirdly did not work
