### ISSUE TITLE
problem playing movies.

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#156]
I have a problem. the second time I turn on the movie, the mpc hc freezes (does not play the movie). I have to turn my computer back on and it will work again and again.

I have windows 10 64 bit, amd ryzen 5 3400g.

**Comment by clsid2** [comment]
Disable hardware acceleration in the video decoder settings. If that solves it then the fault in in the graphics driver.

**Comment by ghost** [comment]
pleasse screen

**Comment by krystian3w** [comment]
Zobacz tak: https://www.thewindowsclub.com/hardware-acceleration-windows-7
<sup>(Look at this:)</sup>

Niby jest opis pod Windows 10 @lukjan32. Jedynie brakuje tam opisu o AMD, wzorują się na intelu.
<sup>(There's a description under Windows 10 @lukjan32. Only there is no description about AMD, they are based on intel.)</sup>

---

Potem może poszukam, gdzie player ma wyłączenie, by nie grzebać w systemowych ustawieniach:
<sup>(Then maybe I'll find out where the player has a disable, so I don't have to go through the system settings:)</sup>

> https://www.avsforum.com/forum/26-home-theater-computers/1357375-advanced-mpc-hc-setup-guide.html
> 
> To access the video decoding options:
> 
> 1.  **open** mpc hc, 
> 2. **press** `o` (KEY: o jak "`ołowek`") for options, 
> 3. go to **internal filters**, 
> 4. and click **Video Decoder** at the bottom.
> 
> 
> ![obraz](https://user-images.githubusercontent.com/35370833/68534230-358e7c80-0332-11ea-8dd2-d92dc86724a3.png) |
> --- |
>

**Comment by ghost** [comment]
mozna ustawic na intel quicksync?

**Comment by krystian3w** [comment]
Można, ale najpierw zobacz na `none`.
<sup>(You can, but first look at the `none`.)</sup>

**Comment by ghost** [comment]
dziala na 3 pierwszych, ustawilem na intel quicksync

**Comment by krystian3w** [comment]
Czyli problem z akceleracją na Ryzenach.

Najlepiej zobacz jakieś wideo w minimum FullHD czy nie robią się dziwne efekty na klatkach filmu.

**Comment by ghost** [comment]
aha, zawsze sciagam w 720p oraz 720p hevc x265

**Comment by clsid2** [comment]
QuickSync does not support HEVC video. Plus you don't have Intel or NVIDIA GPU, so those will effectively be the same as NONE.

If DXVA2 doesn't work well, then you should use different graphics driver version.

**Comment by ghost** [comment]
Okay.

I don't have a graphics card driver installed at all
