### ISSUE TITLE
YouTube playlist video supported or not?

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#1560]
When pasting a single video link (not whole playlist link) from saved playlist, Player becomes not responding. Playlist was public, so it should not be a problem.
Only works when I manually search the video on YouTube then copy the link.

Is it supported by yt-dlp or bug?

**Comment by lifegpc** [comment]
That's normal behavior, just wait for a while. (Maybe should create a new thread to do that.

**Comment by bibsp** [comment]
> That's normal behavior, just wait for a while. (Maybe should create a new thread to do that.

I waited for almost 30-40sec. Not responding. Then I killed MPC-HC from task manager.

**Comment by clsid2** [comment]
A large playlist can take several minutes.

The link you used probably still points to a playlist, as that is standard behavior of YT. The url contains `&list=`. Remove that part to get just one video.

**Comment by bibsp** [comment]
Removing that part works.

But sir mpcbe can play such url without any url modification 😒

**Comment by clsid2** [comment]
Fixed by adding  `--no-playlist` parameter.

**Comment by bibsp** [comment]
@clsid2 sorry for commenting on closed issue.

**_I created a test playlist of 2 videos._**
1. Whole playlist link works. Also can skip to next file
2. Single video link from that playlist works (_without removing &list=_). Also can skip to next/prev file

So the problem was not **&list=**. Problem was number of videos. Removing that part of url is just like workaround. After removing that you can't go to next file.
So the actual solution is to reduce loading time of playlist. Even a 20-30 videos playlist is taking several minutes. If loading time is fixed then no need to add _**--no-playlist**_ parameter. Because everything is already working well for extremely short playlist.
Is there any way to fix that? If not then it's ok.

Hope you got my point.

**Comment by clsid2** [comment]
I can't fix youtube-dl being super slow.

Playlist extraction for Youtube would have to be split into two steps. First extract IDs with --flat-playlist, construct URLs and add them to playlist, then re-process them when playing.

Issue 1: playlist often contain invalid/removed/blocked entries, which will give errors, once they get processed individually. 
Issue 2: I don't have time for this right now. You are out of luck.
