### ISSUE TITLE
Audio skipping at starting

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#1563]
Audio is skipping at starting of video for some files. Windows default video player or mpcbe not having this problem.
I found that, this is because of a default settings in LAV Audio decoder. **Auto A/V sync correction**. When unchecked this option the problem is gone.

![3](https://user-images.githubusercontent.com/98865389/154900953-89c71fbe-a98a-4900-9714-4d61c9258c7e.jpg)

This settings should be disabled by default, as it creates problem only.

Problem sample https://anonfiles.com/h2y4seJex6/2022-02-21_11-15-10_mp4
When A/V sync disabled https://anonfiles.com/x365sbJ9xe/2022-02-21_11-17-43_mp4

**Comment by clsid2** [comment]
I need a link to the actual file itself.

**Comment by bibsp** [comment]
https://drive.google.com/file/d/1L0DJp0cWu35m-hdc3Y1X5r9RF_DX5T5G/view?usp=sharing

Either **A/V sync disable** or **use SaneAR** fixes the problem. May be SaneAR ignores that A/V sync setting. That's why SaneAR does not create problem. May be.

I found 2 more mpc hc only bugs. Those I will share later after this.

**Comment by clsid2** [comment]
The file does have a small sync issue, which it tries to correct.

I have increased the threshold, so it won't trigger correction in this case.
