### ISSUE TITLE
[Bug] Recent files cannot be cleared?

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [clsid2/mpc-hc#1565]
**Expected Behavior**:
Recent files are cleated correctly.

**Actual behavior**:
Recent files still appear after I cleared. Using version 1.9.19.21.

**How to reproduce**:
Click "File", select "Recent files", then click "Clear list", and click "Yes",

**Specs**:
Build information:
    Version:            1.9.19.21 (6856deaaa)
    Compiler:           MSVC v19.29.30140
    Build date:         Feb 17 2022

LAV Filters:
    LAV Splitter:       0.76.0.7
    LAV Video:          0.76.0.7
    LAV Audio:          0.76.0.7
    FFmpeg compiler:    MinGW-w64 GCC 10.2.0

Operating system:
    Name:               Windows 7 (Service Pack 1)
    Version:            6.1.7601 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
    GPU:                NVIDIA GeForce GT 710 (driver version: 30.0.14.7111)

**Comment by clsid2** [comment]
Are you storing settings in INI file?

**Comment by NanaMizukiAnother7** [comment]
Yes, I keep storing it.

**Comment by clsid2** [comment]
Fixed
