### ISSUE TITLE
Rotation problem and over sharp video

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#1566]
**1.**   Video rotation is not working correctly both in window mode or full screen mode when using default EVRCP.

**2.**   MPC-HC is giving this kind of over sharp or pixelated video, when the video contains sharp objects or text. Looks like missing of anti-aliasing.
This it how it looks vs how it should.

![1](https://user-images.githubusercontent.com/98865389/155267042-aa80d1c9-ed7a-4846-8448-d39e5029eb9a.jpg)
![2](https://user-images.githubusercontent.com/98865389/155267045-3a4aced4-fd9d-4d16-8c5d-99f166082503.jpg)

Don't think that the problem is only on vertical video. It's also there in normal horizontal video. But in vertical video the area is small, so it looks much worse and becomes easy to notice.

**Comment by bibsp** [comment]
Video link:   https://drive.google.com/file/d/1zBHuAr1yhE9E2f47fOi8Ymq7qVCN7-hb/view?usp=sharing


As of now the only solution is to use external renderer like MPCVR.
But trust me, I found no problem in mpcbe with default EVRCP. (No MPCVR)

**Comment by clsid2** [comment]
1. There already is an open issue for issues with manual rotation. Low priority for me.
2. Bad quality when downscaling is due to the simple scaling algorithm used by EVRCP. Again not a priority for me. Use MPCVR for better quality.

**Comment by bibsp** [comment]
Ok then keep it open. Some other developers like adipose, speeder or someone else might show some interest to fix these.

EVRCP should be bug free because it is default in MPCHC.

**Comment by bibsp** [comment]
Closing this one. You were right. This is super low priority.
