### ISSUE TITLE
最近使ったファイルリストの消去ができない。

### ISSUE THREAD

**Issue by bengal-f** [clsid2/mpc-hc#1567]
使用OS:Windows10 X64 (21H2)
MPC-HC　バージョン1.9.19.21バージョンでは、
INIファイルに設定を保存を選択している状態だと
最近使ったファイルの履歴の消去ができない問題があります。
安定バージョン　1.9.19では、履歴削除が働いています。

**Comment by adipose** [comment]
In MPC-HC version 1.9.19.21 version,
If you have selected Save settings to INI file
There is a problem that the history of recently used files cannot be deleted.
In stable version 1.9.19, history deletion is working.

**Comment by NanaMizukiAnother7** [comment]
Looks like #1565.

**Comment by bengal-f** [comment]
標準バージョンでは、まだリスト消去できなかったと記憶しています。
Ver 1.9.19.32 で修正されているようです。
ありがとうございました。

以上

2022年2月24日(木) 1:31 clsid2 ***@***.***>:
