### ISSUE TITLE
Increasing the pitch of the audio frequency while increasing the playback speed

### ISSUE THREAD

**Issue by boris-gu** [clsid2/mpc-hc#1571]
When I increase the playback speed, the sound becomes higher.
I have seen recommendations to change the sound rendering to " Internal Audio Renderer", but for some reason I do not have such a function.
![image](https://user-images.githubusercontent.com/44787162/155810668-507e3507-0554-4c3a-99fb-6e0d89a81b7d.png)

**Comment by lifegpc** [comment]
Now it named as SaneAR Audio Renderer

**Comment by boris-gu** [comment]
> Now it named as SaneAR Audio Renderer

Yes, it helped

**Comment by ToxicSmurf** [comment]
I have the same issue and this did not solve it.

**Comment by juttex0** [comment]
> I have the same issue and this did not solve it.
u can solve it?

**Comment by mrpenguinb** [comment]
> I have the same issue and this did not solve it.

Did you try to select the MPC Audio Renderer?
