### ISSUE TITLE
TODO: Is it possible to load two subtitles at the same time?

### ISSUE THREAD

**Issue by ssrlive** [clsid2/mpc-hc#1573]
I have used vsfilter but it doesn't work.

**Comment by clsid2** [comment]
Options > Advanced > BlockVSFilter = false

You must also change hardware decoder from DXVA2 Native to DXVA2 Copyback.

**Comment by reserveword** [comment]
> Options > Advanced > BlockVSFilter = false
> 
> You must also change hardware decoder from DXVA2 Native to DXVA2 Copyback.

I did as above, but that Filter > XySubFilter still won't work. It reads XySubFilter (=> !!!)
Here's my Options:
![图片](https://user-images.githubusercontent.com/12995615/188329418-78cf019a-e7ea-49dd-9416-7963bc7f8ff9.png)
![图片](https://user-images.githubusercontent.com/12995615/188329381-ff79ed9e-462f-4951-9118-03bb8eddf357.png)
![图片](https://user-images.githubusercontent.com/12995615/188329436-8710c3d0-7dae-4589-b37f-6cf982c15057.png)
![图片](https://user-images.githubusercontent.com/12995615/188329447-059e5787-bc61-4a91-882a-4fdeb56f589e.png)

And When I change the Playback > Output > Subtitle Renderer,
![图片](https://user-images.githubusercontent.com/12995615/188329634-74d7734b-a162-4ebf-890c-ecb39298b5ef.png)

1. If I change it to VSFilter / DirectVobSob, the player crashes on reopen.
2. If I change it to XySubFilter, the Internal Subtitle Renderer stops working.

Am I missing something?

P.S. I get VSFilter / XySubFilter from [https://github.com/pinterf/xy-VSFilter/](https://github.com/pinterf/xy-VSFilter/), don't know if it matters.

**Comment by clsid2** [comment]
You must uninstall XySubFilter.
Adding VSFilter to external filters is also not needed.

**Comment by reserveword** [comment]
> You must uninstall XySubFilter. Adding VSFilter to external filters is also not needed.

Should I install VSFilter from https://github.com/pinterf/xy-VSFilter/ ?
I tried uninstall mpc-hc completely and unregistered VSFilter / XySubFilter and reinstall mpc-hc, it says VSFilter is `***unavaliable***`. I then
1. changed Options > Advanced > BlockVSFilter = false
2. changed Options > Internal Filters > Video Decoder > Hardware Decoder to use = DXVA2 (copy=back)
3. registered VSFilter.dll from https://github.com/pinterf/xy-VSFilter/
4. changed Options > Playback > Output > Subtitle Renderer = VSFilter / DirectVobSob
5. open a video
and it crashes.
If it was xy-VSFilter to blame then where can I get a good VSFilter ?
If it wasn't, then is there any crash logs to see where went wrong?

**Comment by clsid2** [comment]
You must select Internal Subtitle Renderer in MPC-HC.

I can't help you with crashing third party software.
