### ISSUE TITLE
.webm file association

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#1575]
In format section all formats are selected.
But webm files are not getting associated with mpchc.

Link: https://anonfiles.com/ncx7R1K8xb/test_7z

**Comment by Aleksoid1978** [comment]
Windows 10/11 ?
If yes - it's Windows "issue". The system simply does not allow you to associate if there has already been an association to another program. You can only "Open with" and select MPC-HC. There is a "hack" - but the MPC-HC does not use it.

**Comment by bibsp** [comment]
Win 10 21h2
Initially (means before installing any video player) all videos do have association with default windows movies and tv app.

After all file association, everything is associated with mpc.
Only webm file remains associated with windows default movies and tv app.
Windows is preventing this.

So this is windows bug.

**Comment by FX8350** [comment]
Applications register extensions to the system that can be opened (e.g., .avi .mkv .mp4 .wmv ).
When a new application is registered, a dialog is displayed when the file is opened for the first time to let the user set the application to start by default.
This "first time dialog" can also be done from the Window settings.
Settings > Apps > Default Apps > Video Player

However, Windows 10 does not identify .webm as a video file, so changing the default Video Player will not change the default player for .webm.

So, after registering .webm file in MPC-HC, you will need to open the .webm file to get the "first time dialog" or manually register the .webm. 
Settings > Apps > Default Apps > Choose default app by file type

I hope this helps.

**Comment by kkdexz** [comment]
Hmm that is odd, I've never had this problem before. In addition to, or an alternate method of @FX8350 's suggestion would be to :

1. Go to the specific webm file you wish to play (or any webm file actually) using explorer.
2. Right-click -> Open with -> Choose another app
3. Select MPC-HC (If it's not already visible in selection dropdown, click "More apps" at very bottom. If still not visible, click "Look for another app on this PC" at very bottom and browse to folder containing mpc-hc.exe)
4. Check box stating "Always use this app to open .webm files".
5. Click OK.

This should register the file format to permanently open w/ MPC-HC by default from now on (until you manually change it again), w/out needing to go into Windows Settings app. Hopefully you've been able to fix this issue by now.
