### ISSUE TITLE
Title bar color changes for a second in dark theme

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1576]
When opening a URL video the color of title bar changes for a second to light theme then again goes back to dark theme automatically.
Example video: https://anonfiles.com/d2t3v0Lfxa/2022-03-02_10-13-15_mp4

Also sir I have 2 queries:
1. Which is better AR? MPC Audio Renderer or SaneAR?
and
2. You have mentioned in read me section: Microsoft Visual C++ 2010 SP1 Redistributable Package (x86) is also required for online video. But without having that installed in my pc I am able to play online content.

**Comment by clsid2** [comment]
Title bar says "not responding" during that moment. The player is not able to apply the theme in that case. So can't be fixed.

1. Both are good.
2. Others do need it. Your PC is irrelevant.
