### ISSUE TITLE
Screen Tearing

### ISSUE THREAD

**Issue by FA-TAAA** [clsid2/mpc-hc#1579]
when i play a video on MPC-HC , there's a big screen cut in the video , i tried vlc and mpv.net and i have no problems, it only bugs with mpc-hc.

edit : i tried to disable freesync on mpc and enable vsync , it still doesnt work

what can i do?

**Comment by clsid2** [comment]
Assuming you are using the default EVR-CP renderer:
Menu > View > Renderer Settings > VSync > Vsync

That is the only suggestion I have.
