### ISSUE TITLE
HDR pass through seems to work only with certain files

### ISSUE THREAD

**Issue by ShoGUN1Master** [clsid2/mpc-hc#1580]
Whether using up-to-date MPC video renderer or MadVR, MPC-HC launches (triggers) HDR only for e.g. .m2ts Dolby demo videos but not "normal" .mkv. Both being HEVC SMPTE ST 2086, HDR10 compatible. MPC-BE triggers the HDR normally with the mentioned mkvs. What could be the issue and is this a wider issue or some strange curiosity with my setup? What could be the variable making this difference?
![Pic 2022-03-04 165534](https://user-images.githubusercontent.com/100950202/156785977-a7e64be6-ade5-428a-b706-1127a688f399.jpg)

**Comment by clsid2** [comment]
That file might be missing HDR metadata. See the "Transfer characteristics" line and the ones below it.

**Comment by YukiNeeSan** [comment]
> That file might be missing HDR metadata. See the "Transfer characteristics" line and the ones below it.

Is this the culprit? I couldn't find the same config in MPC-HC
<details>
  <summary>MPC-BE surface format</summary>

![2022-03-04-min](https://user-images.githubusercontent.com/79769464/156866728-eb5cc804-a058-4413-94a8-4b20d4fa95bf.png)
</details>

[Khronos org Image format](https://www.khronos.org/opengl/wiki/Image_Format)
[glTexImage3D](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage3D.xhtml)
[mpv fbo format](https://mpv.io/manual/master/#options-fbo-format)

**Comment by clsid2** [comment]
No, that is completely unrelated.

**Comment by clsid2** [comment]
Not bug in player. Either broken file or bug in LAV Filters. Based on MediaInfo details the file is the problem.

**Comment by ale5000-git** [comment]
@ShoGUN1Master
I suggest to report (with a sample file here): https://github.com/Nevcairiel/LAVFilters/issues
If there is a misdetection in LAVFilters, it can only be fixed there; and once it is fixed MPC-HC will pick it.
