### ISSUE TITLE
Problems with m3u files

### ISSUE THREAD

**Issue by EgeGurkan** [clsid2/mpc-hc#1581]
I created my own IPTV list. and hosted it on github, there are 2 problems
1) can't see groups i created (entertainment, news, documentary etc etc.)
2) if i use second link (shortened) mpc-hc only opens first channel and other channels are not even shown in playlist (vlc can open even shortened)

long link: https://github.com/CrypticCus/IPTV/blob/main/IPTV.m3u?raw=true
shortened: https://bit.ly/IPTVTR

**Comment by clsid2** [comment]
Grouping is not supported, and I am not interested in adding support for it either.

Handling redirection is not something I care about either at this moment.

**Comment by EgeGurkan** [comment]
i just reported, so dev knows it. i don't really use mpc for it already.
