### ISSUE TITLE
GPU decoding hardware acceleration

### ISSUE THREAD

**Issue by YukiNeeSan** [clsid2/mpc-hc#1583]
That's really a bug or seems just software limitation?
*compressed to reduce bandwidth

1. DXVA2
<details>
      <summary>DXVA2 (copy back)</summary>

![SPOILER_mpc-hc_dxva2_copy-min](https://user-images.githubusercontent.com/79769464/156875946-2a016f4b-7786-47ab-837e-766fb0573828.png)

</details>

2. D3D11
<details>
      <summary>found dedicated/hybrid GPU</summary>

![SPOILER_mpc-hc_d3d11-min](https://user-images.githubusercontent.com/79769464/156876347-5d117a35-f1a3-4ef1-aa00-8347adce118a.png)

</details>

3. D3D11 select dedicated/hybrid GPU
<details>
      <summary>seems not respond</summary>

![SPOILER_mpc-hc_d3d11_could_not_use_hybrid_gpu-min](https://user-images.githubusercontent.com/79769464/156876578-01e2b7a7-7ce4-4413-bb7e-dd950cb7da6a.png)

</details>

4. D3D11 select integrated GPU
<details>
      <summary>H/W Decoder d3d11 copy-back active</summary>

![SPOILER_mpc-hc_d3d11_Intel_HD-min](https://user-images.githubusercontent.com/79769464/156876896-67a30c0a-3a62-4fbc-85bb-eb7079e75a52.png)

 </details>

5. mpv set `--d3d11-adapter=Radeon (TM) R5 M430` to dedicated GPU `--hwdec=d3d11va-copy`
<details>
      <summary>success use d3d11va-copy</summary>

![SPOILER_mpv_hybrid_gpu_d3d11va_copy-min](https://user-images.githubusercontent.com/79769464/156877107-cd2e679a-edcd-4262-855f-3ad2d19c42ba.png)

 </details>

6.  mpv set `--d3d11-adapter=Radeon (TM) R5 M430` to dedicated GPU `--hwdec=dxva2-copy`
<details>
      <summary>success use dxva2-copy</summary>

![SPOILER_mpv_hybrid_gpu_dxva2_copy-min](https://user-images.githubusercontent.com/79769464/156877266-6abf0b45-dc26-481f-ba7a-379e57b80144.png)

</details>

7. mpv bloating with shader for upscaling & downscaling 
<details>
      <summary>AMD-FSR-rgb_v1.0 No Alpha-Denoise.glsl (luma) + KrigBilateral.glsl (chroma) +  AMD-CAS-scaled_luma_trc-sRGB.glsl (rgb scaling)</summary>

![SPOILER_d3d11va_AMD-FSR-rgb_v1 0 No Alpha-Denoise_KrigBilateral_AMD-CAS-scaled_luma_trc-sRGB_02-min](https://user-images.githubusercontent.com/79769464/156877528-4fd42658-1f78-485e-b6ae-3c9fe52ea034.png)

</details>

try another media player such as daum pot player, vlc media player, gom player, kmplayer the problem persist, Is it due to windows limitation or mpv in on different level?
#81, #413 #676 #1079 #1292 #984 #1429 
Not sure that might related to the MPC or LAV Filter, What do you think @clsid2 @Nevcairiel?
If this topic is not relevant pardon me, you could close it

**Comment by clsid2** [comment]
Device used by render is separate from device used by decoder. If you want D3D11 renderer you need to install MPC Video Renderer or MadVR.

D3D9 can only see one device in case of switchable graphics.
