### ISSUE TITLE
No subtitles are displayed, when temporarily played for a period of time

### ISSUE THREAD

**Issue by yaray** [clsid2/mpc-hc#1584]
1. No subtitles are displayed, when temporarily played for a period of time

2. Subtitles are also not displayed when the Windows 7 system returns from sleep to running.

**Comment by yaray** [comment]
Version: MPC-HC(64 bit) 1.9.18 (79b4c6b79) 
Compile Date: Dec 14, 2021
Windows 7 (64 bit) with SP1

**Comment by clsid2** [comment]
Update to latest version. That should work better.

The player reloads the video file after sleep. You may need to redownload the subtitle if you used the search functionality.

Next version will have option to disable reload.

**Comment by yaray** [comment]
It's OK, upgraded to the lastest version (1.9.19, 64-bit).
Thanks for your reply!
