### ISSUE TITLE
Speeding through random section after ffmpeg encode

### ISSUE THREAD

**Issue by truehd24** [clsid2/mpc-hc#1585]
I don't think this is an ffmpeg issue because the file seems to play fine in VLC.
I have some mkv files where I used ffmpeg and avisynth to reencode each of the file's video stream and copy over their respective audio streams. At a specific random point in each file mpc-hc will decide to rapidly play through a section, essentially skipping over it. It's always the same point in each file after multiple reencodes, but the point isn't the same across files. The audio streams are dts-hd ma and ac3. Switching between audio streams yields the same result. Switching between video and audio renderers yield the same result.

MediaInfo:
[MediaInfo.txt](https://github.com/clsid2/mpc-hc/files/8194857/MediaInfo.txt)

MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.19 (b64326a16)
    Compiler:           MSVC v19.29.30139
    Build date:         Jan 30 2022

LAV Filters:
    LAV Splitter:       0.76.0.2
    LAV Video:          0.76.0.2
    LAV Audio:          0.76.0.2
    FFmpeg compiler:    MinGW-w64 GCC 10.2.0

Operating system:
    Name:               Windows 10 (Build 21H2)
    Version:            10.0.19044 (64-bit)

Hardware:
    CPU:                AMD Ryzen 7 5800X 8-Core Processor
    GPU:                NVIDIA GeForce RTX 3060 (driver version: 30.0.15.1165)

**Comment by clsid2** [comment]
Try remuxing with MkvToolNix.

Either the file is broken or you need to report the bug at LAV Filters project. But developer can not do anything without a sample file to reproduce.

**Comment by bibsp** [comment]
> At a specific random point in each file mpc-hc will decide to rapidly play through a section, essentially skipping over it.

You can trim the defective part of video without re-encoding using Avidemux, and upload the file to somewhere.

**Comment by truehd24** [comment]
Trimming and copying with Avidemux didn't copy over the issue and remuxing with MkvToolNix also seems to have fixed the issue. Strange.
