### ISSUE TITLE
YouTube Audio renderer error when played alongside MPC-HC

### ISSUE THREAD

**Issue by Amax0** [clsid2/mpc-hc#1587]
Did several fresh restarts and tests just to ascertain it. Whenever I attempt to play any videos on YouTube alongside MPC-HC, the YouTube player either stops or crashes and gives me the Audio Renderer please restart your computer error. Also happens on Edge and the Opera GX Browser. 

I'm using the MadVR thing for output and the SaneAR Audio Renderer. Used to use the K-Lite Codec Pack and didn't have this problem until I swapped to this, so it may be a settings thing. I'm very unsure what information you may need to help advise me with this problem so feel free to just ask me for whatever info you think might help.

**Comment by clsid2** [comment]
Disable exclusive mode in the audio renderer settings.

**Comment by Amax0** [comment]
That worked, thanks a lot!
