### ISSUE TITLE
DVD Mediainfo error，Lack

### ISSUE THREAD

**Issue by skot013** [clsid2/mpc-hc#1589]
![网页捕获_10-3-2022_18429_github com](https://user-images.githubusercontent.com/43721178/157645281-69b3cc8e-8dea-4f7a-afb7-e04591e92236.jpeg)
Add IFO files still lacks mediainfo：MPC-HC.1.9.19.55
It can be clearly seen that MPC-HC does not display DVD sub text and menus
Apparently this bug has not been fixed
When I upload DVD I need to use other software to see the complete media information
![1](https://user-images.githubusercontent.com/43721178/157646354-442e1bdb-c130-413f-b2a6-0d63c004c87b.gif)
![2](https://user-images.githubusercontent.com/43721178/157646847-afcdcf0b-b6bd-4ef1-b4d4-a33404037b01.gif)
This DVD cannot display the menu in Windows 10! When it plays on Windows7 it shows up correctly! I do not know why
I will upload this DVD!
DVD download LINK：https://anonfiles.com/Rcu3j8N4x9/_DVD_iso
![3](https://user-images.githubusercontent.com/43721178/157650382-f4dcc8b0-440c-4411-8513-404ec1ebbcea.gif)

**Comment by clsid2** [comment]
It shows the MediaInfo for the title on the disc that you are playing. If you are in the menu, then it show the generic details of video_ts.ifo. This is how it works now, and I am not going to make any further changes.

The DVD Navigator filter from Microsoft is used for DVD menus. If it does not work properly with certain discs, then there is nothing I can do.
