### ISSUE TITLE
Inconsistent subtitle rendering for text and drawing tags when playing anamorphic video

### ISSUE THREAD

**Issue by arch1t3cht** [clsid2/mpc-hc#1590]
Hello,

there could be multiple bugs involved here, and some of them might be intended, so I'll just document everything I found:

**Behaviour / How to reproduce**
Take [this](https://github.com/clsid2/mpc-hc/files/8224621/anamorphic_test_video.zip) zip file (github wouldn't let me upload it otherwise) containing
- a `704x480` dummy video (which is 10% wider than the 4:3 `640x480`), which has been muxed to an aspect ratio of 4:3. It's made up of `132x120` pixel rectangles, which will appear square when playing in 4:3.
- an `.ass` subtitle file with script resolution set to `704x480`, which contains various types of events (standard text, vector drawings, and lines clipped to rectangles or vectorial areas), aligned to the video squares. Throughout the video, these events are given styles with various ScaleX values (`100%`, `101%`, `110%`).

The following image shows screenshots of how mpv and MPC-HC render these subtitles. The setting "Apply aspect ratio compensation for anamorphic videos" is turned off for the first row of MPC-HC screenshots, but turned on for the second row.

![comparison](https://user-images.githubusercontent.com/99741385/157695969-7da5f66e-6d45-49a1-9634-a741cec44997.png)

Even without the comparison to mpv, this behaviour seems inconsistent in several places:
- For a ScaleX value of 100% the compensation setting does not change the rendering. However, with compensation turned on, changing the ScaleX to 101% (i.e. a very small change) makes both text and drawings jump to a *smaller* size. This would break any animation involving increasing font scale.
- With compensation turned on, a "square" is 132 pixels wide in terms of the coordinates used for drawing a clip, and that is what you would expect for a script resolution of 704x480. But the bottom side of the red trapezoid (which is drawn using `\p1`) is also 132 units wide, which doesn't cover the square and is not as wide as a clip drawn using the same numbers. In particular, this means that when drawing a polygon and clipping it to that same polygon, the clip might actually cut off parts of the polygon (if it's not convex), which wouldn't be something you would expect.

**Interpretation**
My interpretation of this is that two bugs are involved:
1. Aspect ratio compensation does not trigger if the subtitle style has ScaleX = ScaleY = 100%
2. Vector drawings are too small by a factor equal to the difference in aspect ratios (i.e. 110% in this case) - whether this is a bug only for compensation enabled, or in all cases is a question of interpretation, but I'd argue it's the former.

Now, I can guess that you are reluctant to change behaviour of subtitle rendering, even if it differs from how mpv or other libass players render, but I'd argue that
- This only happens for anamorphic video, so a fix would only change behaviour in that case
- It's very clear that at least some of this behaviour cannot have been intended.

**I would ask you, however - if you do only fix parts of this, please don't only fix point 1 while keeping point 2.** Right now, giving text styles a ScaleX of 110%, but drawing styles a ScaleY of 100% is the only possible way of making drawn subtitles work for both mpv and MPC-HC (for 704x480 video muxed to 4:3). Fixing only the first point would remove that workaround. (But fixing both points would not break it!)

**Proposed fix**
I found a patch that could fix this, but with my limited knowledge of the code I'm reluctant to make a pull request, since I might break 5 other subtitle formats in the process. So I'm proposing changes here.

The following seems to be the problematic section:
https://github.com/clsid2/mpc-hc/blob/12956e64e8147476293b1069125608a61407a35d/src/Subtitles/RTS.cpp#L2875-L2885

There is a check `tmp.fontScaleX != tmp.fontScaleY` here which probably causes the first issue. I believe the second issue is caused by the fact that `tmp.fontScaleX` and `tmp.fontScaleY` are also modified for drawn polygons. Changing this section to the following:
```C++
        if (m_nPolygon) {
            ParsePolygon(sub, str.Mid(iStart, iEnd - iStart), tmp);
        } else {
            if (tmp.fontScaleX == tmp.fontScaleY || m_ePARCompensationType == EPCTAccurateSize_ISR) {
                tmp.fontScaleX *= dFontScaleXCompensation;
                tmp.fontScaleY *= dFontScaleYCompensation;
            }

            ParseString(sub, str.Mid(iStart, iEnd - iStart), tmp);
        }
```
fixes the issue in all cases I tested.
(I don't know why the check `tmp.fontScaleX == tmp.fontScaleY` needs to be there, but I'm copying it from the current code. All I did was remove the condition `tmp.fontScaleX != tmp.fontScaleY` from the ISR case and move the check into the String case)

Fixing this would make typesetting for anamorphic video much easier.

**Comment by clsid2** [comment]
The code should be changed to
```
if (m_ePARCompensationType != EPCTDisabled) {
    tmp.fontScaleX *= dFontScaleXCompensation;
    tmp.fontScaleY *= dFontScaleYCompensation;
}
```

Skipping the scaling for the polygon feels wrong even though it gives the expected result. Polygon is also good with PAR compensation disabled. Because PlayResX is 704, there is already horizontal scaling happening. Rendering is done relative to display size (640), not encoded size, so I am thinking that PAR compensation is not needed at all.

So maybe text is actually scaled twice?

**Comment by clsid2** [comment]
If I change font size to 40 and disabled PAR compensation, then font scaling seems to work ok, when measuring the width on screen. So question is whether it is correct at 100%. I think so, when using the subtitle with another video.

**Comment by arch1t3cht** [comment]
- In this case, `dFontScaleXCompensation` is equal to 100%/110%, so it's smaller than 1. So I don't think it's possible that the text is scaled twice, since it's wider than equally wide polygons in most cases. In fact I was thinking that it's possible that the polygons are scaled twice (that is, one more time than necessary for each setting), but I came to the conclusion that they just shouldn't be scaled (at least with respect to the compensation) even if compensation is enabled - see the next point.
- I think the scaling of the polygons should be independent of whether PAR compensation is enabled or not. This is consistent with how clips seem to currently work in MPC-HC, and what you would naively expect: If your PlayResX is 704, then you'd expect a horizontal line that's 704 units wide to exactly cover the screen, and you'd expect a rectangular clip from (0, 0) to (704, 480) to exactly clip the screen.
- I can't say I understood every detail of the code, but I'm rather sure that polygons are not only being scaled by `dFontScaleXCompensation`, but also by `sub.m_scalex`, which is also equal to 100%/110% in this case. So I think also scaling polygons by `dFontScaleXCompensation` would scale them twice.

These are my thoughts on the matter. I do believe that the way mpv is rendering this is the most sensible one, for the reasons I gave above.
Again, what would be the most important for me is that there should be at least one way to make these scalings work the same way in MPC-HC as they do in mpv, to ensure compatibility between players.
- My patch (or an equivalent one) would make it so that MPC-HC scales everything like mpv does as long as PARCompensation is enabled.
- Currently, it's possible to ensure compatibility by giving text a ScaleX of 110% and polygons a ScaleX of 100%.

so only changing behaviour for 100%, or only changing behaviour for anything else than 100% would make things more difficult.

**Comment by clsid2** [comment]
Yes, everything is already scaled based on m_scalex. The PAR compensation option should probably be removed entirely.

I think MPV renders the text wrong. It looks too narrow at 100%.

**Comment by arch1t3cht** [comment]
> Could you measure?

For the test line at the bottom it's:
- mpv: 1060 pixels at 100%
- mpv: 1071 pixels at 101%
- mpv: 1166 pixels at 110%
- MPC-HC no compensation: 1166 pixels at 100%
- MPC-HC no compensation: 1178 pixels at 101%
- MPC-HC no compensation: 1238 pixels at 110%
- MPC-HC with compensation: 1166 pixels at 100%
- MPC-HC with compensation: 1071 pixels at 101%
- MPC-HC with compensation: 1166 pixels at 110%

... up to 1px inaccuracies with anti-aliasing, of course.

**Comment by arch1t3cht** [comment]
If text scaling is changed in such a way that it's different from mpv for multiple ScaleX values, maybe the PAR compensation option should stay but only affect text. Doesn't need to be on by default, but it'd be very helpful for compatibility.

**Comment by clsid2** [comment]
This needs to be fixed in both MPC and MPV.

I don't like the idea of giving an option just for badly authored subs, as people will be tempted to enable it and then actually get bad results for good subs.

**Comment by arch1t3cht** [comment]
I still don't see how the subs are too narrow in mpv. Take these two screenshots:
Normal 704x480 mp4:
![mpv-shot0001](https://user-images.githubusercontent.com/99741385/158026356-f4a02555-0c04-432d-901b-6c1e081a264f.png)

This 704x480 mp4 muxed to 4:3:
![mpv-shot0002](https://user-images.githubusercontent.com/99741385/158026357-aa74990b-a3ec-4750-8df0-6e0ccc0d4f20.png)

These are two screenshots of mpv, one for the 704x480 test video, and one where it was muxed to 4:3 and thus opens in 704x528. I'm loading the exact same subtitle file with a PlayResX of 704, which is still the video size in pixels.

The black squares cover the exact same sections of the subtitle in both cases. The `I I I I I` text in the left white square is precisely one white square plus one I wide.

This is exactly what I'd expect - muxing to a different aspect ratio should just scale the image to said aspect ratio. So taking subtitle lines with a ScaleX of 100% which look normal for 704x480 should make them look narrower when muxed to 4:3. If one plans to mux to 4:3 from the beginning, one should use a ScaleX of 110%.

**Comment by arch1t3cht** [comment]
GitHub shows both of these images with the same width, but one is 704 pixels wide, while the other is 640px. But you can see that the images look identical on the website.

**Comment by clsid2** [comment]
Fixed
