### ISSUE TITLE
Clarification on yt-dlp.exe & ffmpeg.exe

### ISSUE THREAD

**Issue by nollinvoyd** [clsid2/mpc-hc#1591]
> Put [yt-dlp.exe](https://github.com/yt-dlp/yt-dlp/releases) in the MPC-HC installation folder.
> 
> Tip: to be able to download in best quality with yt-dlp/youtube-dl, it is recommended to also put [ffmpeg.exe](https://www.gyan.dev/ffmpeg/builds/) in the MPC-HC folder.

Are we saying that the yt-dlp.exe and ffmpeg.exe files by themselves (with no other accompanying folder and files) should be put in to the main MPC-HC installation folder?

**Comment by clsid2** [comment]
Put yt-dlp.exe either in the player folder, or in a custom location that you specify in the options:
Options > Advanced

ffmpeg.exe must be in same folder as yt-dlp.exe
No other files are needed.

**Comment by nollinvoyd** [comment]
thanks

**Comment by DRSDavidSoft** [comment]
@clsid2 Sorry for asking a question here,

Would it be possible to use yt-dlp/ffmpeg from the `%PATH%` variable instead _or_ in addition to the one in the installation folder?

That would be easier to maintain with external binary providers or package managers. Thanks!

**Comment by clsid2** [comment]
It uses the path specified in advanced options.
If that is empty, then it uses either `youtube-dl.exe` or `yt-dlp.exe` from MPC-HC folder if those exist.
Otherwise it executes `youtube-dl.exe` hoping it exists in %PATH%.

This is how it works. No additional changes will be applied.

**Comment by DRSDavidSoft** [comment]
Thanks for the clarification!  I presume the same thing is for `ffmpeg`, too?

**Comment by clsid2** [comment]
MPC-HC does nothing with ffmpeg. That is loaded by the YDL exe.

Read this on how to specify custom FFmpeg location:
https://github.com/ytdl-org/youtube-dl/blob/master/README.md

**Comment by harakiwi** [comment]
> Put yt-dlp.exe either in the player folder, or in a custom location that you specify in the options: Options > Advanced


Sorry to re-open/dig up this issue but I don't know how to tell MPC-HC the "custom location that you specify".
Do I have to enter the full path "C:\YT-DLP\yt-dlp.exe" in YDLCommandLine? 

I tried the yt-dlp.exe in my install folder but adding a URL to a Youtube video always ends with "File not found"

**Comment by clsid2** [comment]
You need to put full path in `YDLExePath`.
YDLCommandLine is for something else. Read the tooltip that appear when hovering mouse over it.

**Comment by harakiwi** [comment]
I don't have that YDLExePath option.
I'm still on 1.9.15 (a later release broke my playlist/position data and I had to roll back the update)

**Comment by clsid2** [comment]
I only provide support for the latest version.
