### ISSUE TITLE
What does subtitle reload option do?

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1593]
![Screenshot (335)](https://user-images.githubusercontent.com/100745985/157871341-56f26cda-6681-4247-b810-e70c0058dc7a.png)
MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.19 (b64326a16)
    Compiler:           MSVC v19.29.30139
    Build date:         Jan 30 2022

**Comment by clsid2** [comment]
Reload the subtitle file. Can be used by people who make modifications to the file during playback.
