### ISSUE TITLE
为什么打开 URL 视频会占用 C: 空间？ Why does opening URL video take up C: space?

### ISSUE THREAD

**Issue by DOSforever** [clsid2/mpc-hc#1597]
以 Ctrl-O 方式打开以 http 协议传输的视频文件进行播放，发觉会占用 C: 空间，随着打开文件的增多， C: 空间会越来越小，甚至撑满。我想这也许是缓存的原因，但关闭播放器后占用的空间并没有得到释放，在临时目录中也看不到缓存文件，也即无法手工删除临时文件，必须要重新启动计算机后所占用的空间才会得到释放。请问这是为什么？能否手工删除缓存文件？

Open the video file transmitted by the http protocol in Ctrl-O mode for playback, and find that the C: space will be occupied. With the increase of open files, the C: space will become smaller and even full. I think this may be the cause of the cache, but the space occupied by the player is not released after closing the player, and the cache files cannot be seen in the temporary directory, that is, the temporary files cannot be deleted manually, and the space occupied will not be freed until the computer is restarted . Is that why? Can I delete cache files manually?

**Comment by lifegpc** [comment]
我用 1.9.19.63 版本测试了一下，观察不到相关现象。你能发一下出现问题的 URL 吗？
I test it with 1.9.19.63 and I can not reproduce it.  Can u provide URL which cause these problems.

**Comment by lifegpc** [comment]
我从GitHub Release下的，我用你给的链接再测试一下。照理说URL都是由FFMPEG处理的，应该不会有缓存

**Comment by lifegpc** [comment]
哦，用你那个网页里的播放地址的确会触发缓存。如果我这时候打开另一个视频，的确会出现该情况
Oh i see, use the playback URL in that web page will let MPC-HC to buffer video content. And if I open another video, the problem occurs. The buffer is not freed.
![image](https://user-images.githubusercontent.com/41434272/158573703-942aecc2-651c-484b-8e06-6d66bfad3412.png)

**Comment by lifegpc** [comment]
我知道原因了，由于MPC-HC把整个视频缓存在了内存，导致C的pagefile.sys的体积飙涨。
This problem is cause by mpc-hc cache entire file in memory, and system write lots of data to pagefile. @clsid2 We need to limit cache if the length of video is too long.

**Comment by lifegpc** [comment]
@DOSforever 如果我没分析错的话，重启后应该就会恢复正常

**Comment by clsid2** [comment]
The Microsoft "File Source URL" filter buffers whole file on disk. I can't fix or change that.

You should use the internal HTTP source filter instead. That buffers in memory and has options to control have much it buffers (default is max 128MB).
It seems to fail with http:// link for that website, but works if you change to https://

**Comment by clsid2** [comment]
Hmm, now it also works with http://
Maybe that web server is behaving weird and refuses connection sometimes.

**Comment by lifegpc** [comment]
Just a little weird, when I test http://localhost , no buffer for all videos.

**Comment by DOSforever** [comment]
感谢回复。
再问个问题，同样是打开文件，Ctrl-O 和 Ctrl-Q 有什么区别？难道仅仅是 Ctrl-O 可以另外加载音频文件的区别吗？我同样打开一个 URL 文件，Ctrl-O 立即可以播放，而 Ctrl-Q 要等老半天，甚至假死机，难道 Ctrl-Q 是要把文件全都缓存到内存吗？但似乎无响应的时间并没有等同于把整个文件都下载下来那么长。

**Comment by lifegpc** [comment]
Ctrl+Q我只用来打开本地文件

**Comment by DOSforever** [comment]
又查看了下， Ctrl+Q 是把文件缓存到本地的，按 Shift+F10 是可以看到本地文件名和位置的。
