### ISSUE TITLE
Resetting file position to 0

### ISSUE THREAD

**Issue by vortaj** [clsid2/mpc-hc#1599]
1.9.20 has this new feature: "Remembered file position now resets to 0 when playback has reached 95% of file duration when closing the player. We assume that end credits have been reached in that case."
Can this be disabled? Because you "assumed" it wrong, at least for my usage patterns.

**Comment by clsid2** [comment]
No.

**Comment by vortaj** [comment]
Let's look at some examples.
1. Let's say I have a whole season of some TV series. I've watched episode 6 (out of 24) to the credits and closed it for today. Tomorrow (or in a week) I return to the series, but I don't exactly remember where I left. I open episode 5 and see credits, then I try 6th - same, and then 7th is on 0. Now I know where I stopped, but not in the new version.
2. Let's say I watch some anime episode to the ending. The ending takes 2 minutes of 24 total, so the position in the new version will be saved anyways = pointless.
3. Let's say I watch a 10 hour let's play of some game (of course, you couldn't possibly think of such use case). If I stop in the latest 30 minutes, everything will be lost. So I am now forced to seek through 10 hours to see where I have stopped (especially if I didn't know about this new "feature").

I guess there are other peolple who use MPC differently, but for me the new behavior is literally destructive and nothing else. I always liked this "remember position" feature of MPC and especially its reliability, unlike VLC or Youtube or Twitch, which remember only half the time or so. So it would be nice to see a simple switch for this feature in extra settings and also maybe have it off by default for those who don't even realize it exists.

**Comment by Alex1238** [comment]
I would also like an option in advanced settings to disable this behaviour.  Example 1 given by Vortaj above is something I find myself doing quite often.

**Comment by githubbapoopa** [comment]
+1 

This is a stupid decision imho as not all files have "end credits"

You assume people are only watching movies. That's simply not true.

Why are you forcing *your use case* to all users rather than staying focused on overall usability?

**Comment by Alp1821** [comment]
> point me to the donation link.

Under **Help** section inside MPC-HC software

**Comment by clsid2** [comment]
Reverted.

**Comment by githubbapoopa** [comment]
Thanks for having the courage and greatness to revert a mistake. And to listen to your "users". That's what makes mpc-hc outstanding.

So I guess there will be 1.9.20.1 then?

**Comment by clsid2** [comment]
I am not making a new release just for this.

**Comment by githubbapoopa** [comment]
Where to get the newest reverted version?

**Comment by githubbapoopa** [comment]
Nevermind MPC-HC.1.9.20.17.x64 seems to have been reverted. Thanks.
