### ISSUE TITLE
mpc-hc64.exe Flagged as Malicious on VirusTotal

### ISSUE THREAD

**Issue by r43fgr** [clsid2/mpc-hc#1603]
I am a beginner, so please pardon me.
I installed the latest mpc-hc using the MPC-HC.1.9.20.x64 on github. (https://github.com/clsid2/mpc-hc/releases/tag/1.9.20)
However, after running the above setup exe, to play safe I decided to scan the exe (mpc-hc64.exe) located in the Program Files/MPC-HC folder, by uploading the exe to VirusTotal. Surprisingly, the exe was flagged by Trellix (FireEye) as malicious: Generic.mg.4bd73f6517c3912f

[VirusTotal Detection](https://www.virustotal.com/gui/file/6388ef88aec8d52882f5a73e5af1b22c979fdeb5ebe5fe950b10f4fa2f467307/detection)

I would highly appreciate if anyone can check the code to see if there is really any malware, or it is just a false positive.

Thank you so much.

**Comment by clsid2** [comment]
It is a false positive.

**Comment by ale5000-git** [comment]
@r43fgr
If you want you can report false positive to the antivirus directly: https://www.fireeye.com/

**Comment by clsid2** [comment]
The FireEye engine on VT only gets updated twice a year. It is already fixed in their internal builds, so reporting is pointless.
