### ISSUE TITLE
Opening a file while another file is playing sometimes adds it to the queue

### ISSUE THREAD

**Issue by mikdonl** [clsid2/mpc-hc#1605]
I've noticed an odd behavior of MPC-HC, and I'd like to find an explanation and possibly a fix for it. As a music producer, I frequently have to preview audio samples in quick succession. However, if I start playing one file, then quickly open another, it will add the second file to the queue. If I wait a short time before playing the second file, it will instead replace the currently playing file, which is the behavior I want at all times. Is there any way to change the time I have to wait, or perhaps turn it off entirely? For what it's worth, I noticed MPC-BE has a much shorter delay.

**Comment by clsid2** [comment]
Next version will have advanced option RedirectOpenToAppendThreshold to adjust this behavior.
