### ISSUE TITLE
Not opening files when playing short files

### ISSUE THREAD

**Issue by HispidaBytes** [clsid2/mpc-hc#1607]
While the player is reproducing a short file in loop mode, it is impossible to open another file from Windows Explorer by double clicking on it.
Dragging the file to player does work, as well opening from the "File" menu
See the gif below.

MPC-HC 1.9.20 on Windows 10 x64

![Animation](https://user-images.githubusercontent.com/34475384/159124095-f37e291a-ea72-4075-af0a-4e9cfc3f6b56.gif)

**Comment by clsid2** [comment]
Read the last two closed issues....
