### ISSUE TITLE
PGS subs too close to center now

### ISSUE THREAD

**Issue by SSCBryce** [clsid2/mpc-hc#1608]
PGS subs are being put very close to the center of the screen now suddenly, probably due to this versions PGS changes I guess? Running with madvr. Changing sub options in MPCHC doesn't seem to do anything, I tried to edit the style for example, to no avail.
![oy0S9yem1WOL](https://user-images.githubusercontent.com/2372953/159143757-4771bf2c-073d-41f9-b73d-6eb175dde513.jpg)

**Comment by clsid2** [comment]
Style only has effect on text based subtitle formats. PGS are images.

You can move the subtitle down with Ctrl+Shift+Substract

**Comment by clsid2** [comment]
Can you give a link to that video?

**Comment by SSCBryce** [comment]
Ah that's right, completely forgot. How many times have I OCR'd PGS... However, not trying to complain here but, it would have to be done for each episode (at least I don't know if there's a more permanent option), but also, ancillary subs at the top of screen will now also be awful in the center. File is from https://nyaa.si/view/1223561

**Comment by bibsp** [comment]
Is this the same?
![Screenshot (368)](https://user-images.githubusercontent.com/98865389/159146769-ca717c1d-b470-4477-9852-aa348c42c694.png)
I never reported that, because I thought it is normal for Image based subs.

**Comment by SSCBryce** [comment]
It is normal to an extent. But I can tell you for sure, at least with the specific show release I posted, the subs have shifted drastically higher with 1.9.20. My buddy and I have been watching that show for a few months now, and we both updated to 1.9.20 and are experiencing the same thing.

**Comment by bibsp** [comment]
For vobsub the behavior was same in previous versions. It is not new in 1.9.20.
I can not comment on PGS.
I mentioned that behavior because both are image based subs.

**Comment by SSCBryce** [comment]
Right, I'd definitely say not normal.

**Comment by clsid2** [comment]
@Alp1821
Can you give link to that video?

I have some ideas to improve the subtitle placement. It will take some time to implement, because there are a huge amount of different combinations of video/window/subtitle size and AR combinations it has to deal with.

**Comment by bibsp** [comment]
When I tried to trim the **movie [1280x544]**, avidemux removed the sub from output file.
Then I made a short **sample video [1364x768]** and added the sub in mkvtoolnix. **(Sub starts at around 2 min)**.
But here the sample video is full screen, so it is giving different result. The same gap from bottom video frame.
I don't think this a bug, at least for vobsub. For vobsub it is respecting video bottom frame.

https://anonfiles.com/LeheA3Pax0/test_mkv

**Comment by bibsp** [comment]
> But here the sample video is full screen, so it is giving different result. The same gap from bottom video frame.

Same behavior in mpcbe and windows default player.

**Comment by Squall-Leonhart** [comment]
Just spent an hour trying to work out why a friends subs were so high compared to mine.

19.20
![image](https://user-images.githubusercontent.com/1098176/159429688-0bda80e1-ca34-4066-a51c-ab0410bddcab.png)

19.18
![Judas  Card Captor Sakura - S01E02 mkv_snapshot_04 41 685](https://user-images.githubusercontent.com/1098176/159430069-cc026ab6-392e-4488-85c7-1ef8021471a5.jpg)

**Comment by clsid2** [comment]
Fixed in 1.9.20.10

**Comment by clsid2** [comment]
@[Alp1821](https://github.com/Alp1821)
Do you have a link/torrent for that movie with the embedded vobsubs? Then I can maybe improve positioning for vobsubs as well in case of cropped videos.

**Comment by bibsp** [comment]
No. Old movie. No link.
I don't have unlimited net to upload whole movie.
Only thing I can do is, I can make another sample video of 1280x544. Do you really need this?

But it's not necessary in my opinion. All other players are behaving same.

**Comment by SSCBryce** [comment]
Looks amazing cid. Great work, and thanks for keeping the project alive.
