### ISSUE TITLE
Inconsistency - [Local] file indication for audio also.

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#1609]
Right now it only gives [Local] indication  for external subs.
![Screenshot (362)](https://user-images.githubusercontent.com/98865389/159147068-b3e81bb4-814a-49bc-8a2f-88a3df6fe3cc.png)
![Screenshot (363)](https://user-images.githubusercontent.com/98865389/159147069-2a2784e4-3b88-459a-9792-1aa12eae0178.png)

**Comment by clsid2** [comment]
Not something I care about.
