### ISSUE TITLE
Jump hotkeys don't jump correct distance

### ISSUE THREAD

**Issue by IonicSquid** [clsid2/mpc-hc#161]
When using the "jump" hotkeys (left and right arrow keys by default), the video doesn't jump the actual distance specified in the settings. The amount it jumps doesn't seem consistent, as if it is snapping to predefined points in the video (which are often multiple seconds apart) rather than jumping the specified amount.

Is this a change in functionality in more recent releases of MPC-HC (the last release I've used consistently is the version contained in the latest CCCP release, which was four years ago), me misunderstanding something, or a bug?

Thanks.

**Comment by clsid2** [comment]
It jumps to a keyframe by default. You can disable that in:
options > tweaks > fast seek

With proper files the inaccuracy should be small, like 1 second or less. If you have a large inaccuracy on files that you have created yourself, then I advice to significantly reduce the keyframe interval in your encoding settings.
