### ISSUE TITLE
Selecting MPC-HC as the application to stream in Discord crashes MPC-HC

### ISSUE THREAD

**Issue by SamehAmnoun** [clsid2/mpc-hc#1610]
When you try to play/pause while MPC-HC is shared in Discord, the app crashes. You can select to stream the whole screen and it will work normally, but choosing MPC-HC specifically causes the crash.

**Comment by clsid2** [comment]
https://github.com/clsid2/mpc-hc/issues?q=is%3Aissue+is%3Aclosed+discord
