### ISSUE TITLE
Question about full screen mode

### ISSUE THREAD

**Issue by MIhidoype** [clsid2/mpc-hc#1612]
Hello,

First of all, thank you for making this application continue being updated, your job is amazing and really appreciated!

I am using it for some experiments, for which I need the video to be in full screen mode. But I've noticed that when the video finishes and stops, the screen leaves the full screen mode. Is there a way to avoid this leaving of full screen mode once the video finishes? I've searched all around the place and tried different combinations, but I'm failing to find a way.

Thank you!

**Comment by clsid2** [comment]
Options > Playback > Fullscreen > Exit fullscreen at end of playback
