### ISSUE TITLE
[Feature Suggestion] ShowAudioInfoInStatusbar ?

### ISSUE THREAD

**Issue by mdnava** [clsid2/mpc-hc#1613]
Please consider adding the option ShowAudioInfoInStatusbar to show bitrate of the playing audio, and perhaps other info, similar to the existing option ShowVideoInfoInStatusbar, which is very useful.

**Note:** I read post https://github.com/clsid2/mpc-hc/issues/1387 about feature requests. I just thought it could perhaps be a simple idea to implement. Feel free to ignore. I might try to familiarize with the project in the future to include it.

**Comment by clsid2** [comment]
You can see that information in:
Menu > Play > Audio Track

There are already 1000 other "easy" things that also need implementation...

Audio bitrate is one of the most useless pieces of information.

**Comment by mdnava** [comment]
Thank you for answering..

> You can see that information in:
> Menu > Play > Audio Track

I know this info is easily available in "properties".. But it requires to open an extra window for each file.

> There are already 1000 other "easy" things that also need implementation...

I understand...

> Audio bitrate is one of the most useless pieces of information.

For video files.. most probably yes!. For audio/music I consider it very useful, as (for example) I can identify 128k vs 356k files much faster. For audio, to me it has somewhat the same usefulness as having the dimensions available for video files.

I mean, I know there's actually no guarantee that the bitrate is accurate without analyzing the file's spectrogram, but more often than not it does help; at the very least to identify lower bitrates faster.

Have a nice week!

**Comment by clsid2** [comment]
Windows Explorer shows the bitrate for mp3 files. You don't need a player to identify that. Plus good encoded files are VBR anyway.

I am not adding bitrate to statusbar. For audio maybe only format and channel count in future.

**Comment by mdnava** [comment]
I understand.
Thank you for answering.
