### ISSUE TITLE
Lag when changing subtitles

### ISSUE THREAD

**Issue by tealkami** [clsid2/mpc-hc#1615]
Micro lag when I change subtitles while playing video on "Enhanced Video Renderer (custom preset)". When I tried "MPC Video Renderer" then the lag is with black screen. 

Tested on HEVC/X264 MKV files, with new/reset MPC setting, Turn off/on Hardware Acceleration (my default is HW:off); tried all GUI options in MPC-HC, still lags. 
MPC-HC 1.9.19/1.9.20
MPC Video Renderer 0.5.6.1807
AMD Ryzen 7 5700G with Radeon Graphics
Windows 10 (Build 21H2) , 10.0.19044 (64-bit)

MPC-BE 1.5.8 have no lag, so I guess I didn't find the right setting in MPC-HC, or is it something in LAV splitter.
My guess is that MPC-HC don't load the other subtitles, because when I change subtitles while video is stopped it doesn't load current text.

EDIT : after sending this ticket I did check buffer in MPC-HC and MPC-BE, MPC-HC buffers only 3 tracks, while MPC-BE buffers 5, where I can change how many thing will be in buffer ?

----------

Suggestion for subtitles :
Can you add toggle in Advanced option for not showing the "S:No subtitles" in Subtitles track? If I want to turn off subtitles I press "W"(on/off subtitles) or uncheck "enable".
Doesn't make sense why there is a "S:No subtitles" option, when you have toggle for turning off subtitles in general.

**Comment by clsid2** [comment]
"S:No subtitles" will not be hidden.

The default frame buffer for EVR is 5 if that is what you mean. That setting is on output page.

I don't know why you get lag.

**Comment by clsid2** [comment]
It repaints the video after changing the subtitle. That causes the microstutter or black flash with MPCVR.

Normal behavior.

**Comment by tealkami** [comment]
It wasn't "normal" before.
Same MKV file, with 26subtitles in the file

MPC 6.4.9.1
https://i.imgur.com/XTEEn0O.png

MPC-BE 1.5.8
https://i.imgur.com/aEOEjji.png

MPC-HC 1.7.13 - LAV 0.75.1.0
https://i.imgur.com/7it5YLt.png

MPC-HC 1.9.20
https://i.imgur.com/pPohfEP.png

of course in the old **MPC 6.4.9.1** it doesn't microstutter when changing subtitles/audio

Is there a way to make it load all subtitles/audio ? like it was in MPC 6.4.9.1 or in MPC-BE ?

**Comment by clsid2** [comment]
Showing information for inactive streams is stupid.

MPC-BE has same microlag when using LAV Splitter. That is effect of stream switching.

It works the way it works. It will not be changed.

**Comment by tealkami** [comment]
Subtitles are like 50-100 KB as whole
When I change Audio in MPC-BE it does lag/microstutter, but subtitles are seamless; in the MPC-BE buffer , the subtitles aren't even showing any 000/0 KB usage, so... **Subtitles takes so small amount of resources, it shouldn't be problem to load all of them into buffer.**

**So main point :**
Is there a way/option to make LAV/your MPC-HC to load all text sources into buffer? or you need code that in as new option?
I guess you would need to code that in... so...
Understandable, Have a Nice Day

-----
> Showing information for inactive streams is stupid.
>
and yet you have "S:No subtitles", when you can just turn off subtitles.
