### ISSUE TITLE
subrip/srt and some vobsub subtitles are shifted left on 4:3 videos

### ISSUE THREAD

**Issue by Stone-D** [clsid2/mpc-hc#1616]
This is new behaviour in 1.9.20, I have reverted to 1.9.19 for now.

External .SRT:
![Zack Snyder's Justice League  2021 1080p BRRip x264-MIRCrew m4v_snapshot_01 09 27 443](https://user-images.githubusercontent.com/522690/159638798-b891948d-ca0d-42bc-ac98-d702e905cbc5.png)

vobsub:
![Zack Snyder's Justice League (2021) (1080p BluRay x265 10bit Tigole) mkv_snapshot_01 02 12 458](https://user-images.githubusercontent.com/522690/159638873-6691569a-f7f8-43c5-8c76-d7e01321f3a8.png)

**Comment by bibsp** [comment]
![Screenshot (385)](https://user-images.githubusercontent.com/98865389/159649433-94d4a7ad-29a2-42aa-87bd-871040ff33cf.png)
![Screenshot (386)](https://user-images.githubusercontent.com/98865389/159649443-0c9f29ef-cbea-48bd-a2f8-af64e30083e1.png)
@Stone-D Not true for external srt.
I don't have external vobsub to check.

You have more black bars on both sides. Monitor resolution and Aspect Ratio maybe the reason.
Working well on 16:9 screen.

**Comment by Stone-D** [comment]
Yes, sorry I forgot to mention that this ONLY occcurs when maximized or full screen. My monitor is an ultrawide, 38GN950 3840x1600.

**Comment by clsid2** [comment]
For vobsub/pgs it is problem that I will fix soon.

Are you using exclusive fullscreen? That has an issue where SRT may be rendered at wrong size. But for normal fullscreen I can't reproduce atm.

**Comment by Stone-D** [comment]
Both full and simply resized windows. As  I stretch the window horizontally and black bars are added, the subtitle is gradually shifted to the left:

![Clipboard Image](https://user-images.githubusercontent.com/522690/159804911-e13a91c9-a12f-4223-9505-84e34641dca9.jpg)

It seems that it is only happening with MadVR (madVRhdrMeasure112b.zip I think, one of the last builds before the timeout was added)

Here's my ini file in case it's useful.

[mpc-hc64.ini.txt](https://github.com/clsid2/mpc-hc/files/8337033/mpc-hc64.ini.txt)

**Comment by clsid2** [comment]
Try 1.9.20.10 development build.

I am unable to reproduce your problem with stable MadVR build.

**Comment by Stone-D** [comment]
No change, unfortunately.

First of all, [here's a video of the issue.](https://drive.google.com/file/d/1hckFyDOBLY_oD9pejILrx6oBYKBDDsqu/view?usp=sharing)

It turns out the issue is something in my settings.bin file. Delete that, and the issue is no longer present in either 1.13b or the latest 1.59 build.

I will investigate further to narrow down the specific setting later after work. In the meantime, I've attached that settings.bin.

[settings.zip](https://github.com/clsid2/mpc-hc/files/8358861/settings.zip)

**Comment by clsid2** [comment]
This is the cause:
madvr settings > processing > zoom control > move subtitles into active video area

It is a bug in madvr, because it does not offset for the added black bar on the side.

**Comment by Stone-D** [comment]
Confirmed! Thanks for that. I've disabled it. Odd that it worked fine in previous builds, but it doesn't matter.

**Comment by clsid2** [comment]
You can use this instead;
MPC-HC options > Subtitles > Default Style > Position subtitles relative to video frame

**Comment by Stone-D** [comment]
Aha, thank you. I had forgotten that. I set my preferred margins years ago and never revisited that area.
