### ISSUE TITLE
When video/music is paused and you click on notification from action center the video/music starts playing.

### ISSUE THREAD

**Issue by Kitsune2431** [clsid2/mpc-hc#1618]
Basically title. I'm on windows 10. Is this fixable?

**Comment by clsid2** [comment]
Options > Player > Keys > disable "Global Media Keys"
Options > Advanced > UseSMTC = False

**Comment by mbartlett21** [comment]
It seems to be something with WinUI. Dragging tabs in Microsoft's new Terminal also does it.

I'm running with Global media keys turned off and UseSMTC on and haven't run into any more issues.
UseSMTC needs to be on to get play/back/forward keys to work when other programs are focussed.
