### ISSUE TITLE
Bad behavior of "Override placement" in subtitle settings

### ISSUE THREAD

**Issue by manuelrn** [clsid2/mpc-hc#1619]
Hi!

If the `Vertical` option of `Override placement` is set to 85%, if the SRT subtitle is located bottom it behaves fine but if the subtitle is located top (line with `{\an8}` tag) it produces a strange behavior.

A sample of this:

Bottom (default - 'Override placement' unchecked):
![](https://i.imgur.com/M9T0EpW.png)

Bottom (85%):
![](https://i.imgur.com/6cwXy0J.png)

Top (default - 'Override placement' unchecked):
![](https://i.imgur.com/4bq6n9C.png)

Top (85%):
![](https://i.imgur.com/JlzpO4B.png)
<br/>
As you can see, Top (85%) behaves strangely, it should be displayed where the red rectangle I have painted but however it is displayed in another area.

Thanks and regards!

**Comment by clsid2** [comment]
Override placement is not designed to do what you want.

Use SSA/ASS subtitle if you want to more control over placement.

**Comment by clsid2** [comment]
If you want to move them out of black border, use render relative to video option.

**Comment by manuelrn** [comment]
Okay, thanks for the answer!

So this behavior is correct?
It had seemed a bit strange to me and that's why I commented on it.
<br/>
What I wanted is to show the subtitles inside the image, but currently I already do it using the `Screen Alignment & Margins` option in the `Default Style` section with the following settings: Left/Right: 20 & Top/Bottom: 43.

I don't know if this is what you mention in your last comment.

**Comment by clsid2** [comment]
"Position subtitles relative to video frame". Below the margins.

Override position completely overrides all original positioning.

**Comment by manuelrn** [comment]
Yes, I have that option checked (although I see no difference with it checked or unchecked), in addition to what I said before:  Left/Right: 20 & Top/Bottom: 43. This way everything works well.

Then, if "Override placement" option works correctly, we can close this Issue.

Thanks again!
