### ISSUE TITLE
[request] set window title via command line

### ISSUE THREAD

**Issue by lastmetroid** [clsid2/mpc-hc#1620]
Would be handy and very welcome, if you could implement a command line argument, to set the window title.

This would be very useful, if you open mpc-hc via batch file with a file name, but want to set the window title to something else, so you can kill the window title via 

taskkill /fi \"Windowtitle specific unique title which was set before*\" /im " + exeFile + " /F

would be handy, if you could implement something like /title "window title" as a start argument, which overwrites the window title.

**Comment by clsid2** [comment]
I am not adding that.

MPC has an advanced API for remote control. Google for "mpc api /slave".

**Comment by lastmetroid** [comment]
I dont care about the remote control. Why did I know this answer would come? That was just an example.

This is a simple easy to add and logic to add request. VLC has this option as argument too. It makes no sense to not implement a titel argument. Why?

Another example:

opening MPC-HC with some https m3u8 link like: lflfhhsdlhghjhj3rhj2khj32hj43hj24hkj23hk4h234hjk234hkk32h4h234hj3jhk24jhhk23jk4jk32h4jhkj23h432hk4khj23hk432hjk4hkj234hjk32kh4k32hj4j32h4hkj32jk432hjk4hjk324jh32jh4hj32hj4hk4h234hjk234hkk32h4h234hj3jhk24jhhk23jk4jk32h4jhkj23h432hk4khj23hk432hjk4hkj234hjk32kh4k32hj4j32h4hkj32jk432hjk4hjk324jh32hk4h234hjk234hkk32h4h234hj3jhk24jhhk23jk4jk32h4jhkj23h432hk4khj23hk432hjk4hkj234hjk32kh4k32hj4j32h4hkj32jk432hjk4hjk324jh32hk4h234hjk234hkk32h4h234hj3jhk24jhhk23jk4jk32h4jhkj23h432hk4khj23hk432hjk4hkj234hjk32kh4k32hj4j32h4hkj32jk432hjk4hjk324jh32hjk23.m3u8

Now the title of that mpc is "lflfhhsdlhghjhj3rhj2khj32hj43hj24hkj23hk4h234hjk234hkk32h4h234hj3jhk24jhhk23jk4jk32h4jhkj23h432hk4khj23hk432hjk4hkj234hjk32kh4k32hj4j32h4hkj32jk432hjk4hjk324jh32jh4hj32hj4hjk2hk4h234hjk234hkk32h4h234hj3jhk24jhhk23jk4jk32h4jhkj23h432hk4khj23hk432hjk4hkj234hjk32kh4k32hj4j32h4hkj32jk432hjk4hjk324jh32hk4h234hjk234hkk32h4h234hj3jhk24jhhk23jk4jk32h4jhkj23h432hk4khj23hk432hjk4hkj234hjk32kh4k32hj4j32h4hkj32jk432hjk4hjk324jh32 ..."

It is logic you want to name the title of this window to something else via command line argument.

**Comment by clsid2** [comment]
I AM NOT ADDING ANY NEW FEATURES!

Options > Player > Titlebar > Don't prefix anything

Then title will always be "Media Player Classic Home Cinema".

**Comment by lastmetroid** [comment]
Then fix this bug:

![image](https://user-images.githubusercontent.com/6721083/160242161-d59f7f58-d3ad-48a4-8cce-f479205d5514.png)

in combination of m3u8 files with meta data / title:

#EXTINF:0,Title
https://link.m3u8

MPC ignores the meta data title and just sets the file name as title.

**Comment by clsid2** [comment]
The streaming m3u8 file is handled directly by LAV Splitter. The player does not parse its contents.

And at this moment I just don't care at all about this problem.

**Comment by lastmetroid** [comment]
I didnt say that this was a high priority at all. All I just was asking nicely. I presented you a bug / example, which this is not intended behavior AND which would add to the functionality of MPC and also would be easy to implement. Any other media player handles this, that the title of the window is the title of a media content if there is meta data. There is also an option here, but it seems to be ignored for m3u8 files and the meta data is not being used.
