### ISSUE TITLE
[request] Adding extra audio file via Drag & Drop during playback, like subs.

### ISSUE THREAD

**Issue by djrooli** [clsid2/mpc-hc#1621]
Hello!
I am not sure you have this option, but I am glad you have the D&D feature for subtitles. I would be happy if there would be the same function for audio files, like holding CTRL and D&D audio to the actual played video with instant change to that track.
Often, If I want to try different audio, I have to browse them, or copy to the folder & rename it. 
If it is possible, than thank you in advance. ;)

**Comment by clsid2** [comment]
The answer is NO. There is no way to distinguish between a dub and a regular audio file.
