### ISSUE TITLE
MP4 plays first MIDI in the directory where it is located

### ISSUE THREAD

**Issue by ivanka2012** [clsid2/mpc-hc#1622]
MPC-HC version: 1.9.20
OS: Windows 10 20H2

I have an mp4 called `1.mp4` that when it is opened, plays a MIDI in the same directory where it is located called `130.mid - superstars v5.14.mid`, which is the first MIDI file in the directory by ascending name order. This only happens to `1.mp4` and not to other MP4s or video files. I opened `1.mp4` in VLC and Windows Media Player and they played it just fine.

The MIDI and MP4 are attached along with a recording of the behaviour.

[1.mp4](https://user-images.githubusercontent.com/16673946/160244807-1826b050-1879-4e17-9f97-d770b757f045.mp4)

[130.mid - superstars v5.14.zip](https://github.com/clsid2/mpc-hc/files/8355671/130.mid.-.superstars.v5.14.zip)

[Recording of the bug](https://user-images.githubusercontent.com/16673946/160244931-a055adf8-e312-4d14-9abd-367b3ba9a444.mp4)

**Comment by clsid2** [comment]
Options > playback > disable "Autoload audio files"

**Comment by ivanka2012** [comment]
> Options > playback > disable "Autoload audio files"

Thanks for the quick reply, that fixes it

**Comment by clsid2** [comment]
Since it looks at the filename for making a match, renaming the video will also avoid this.
