### ISSUE TITLE
cant log in opensubtitles

### ISSUE THREAD

**Issue by Frankeinst** [clsid2/mpc-hc#1623]
Hi, i cant login in opensubtitles, i am using the correct username and password.
![image](https://user-images.githubusercontent.com/52982539/160280313-40df4b1b-e9d8-4d1c-934a-cbeffc81600e.png)

**Comment by clsid2** [comment]
If you have moved the .exe to a different location, then you need to fill in the username and password again.

Otherwise I can't provide any help with login issues on a third party service.
