### ISSUE TITLE
Subtitle delay fine-tuning does not work.

### ISSUE THREAD

**Issue by ssrlive** [clsid2/mpc-hc#1625]
My video and subtitles are out of sync, delayed by 10 seconds, so I pressed F1 to advance the subtitle time by 10 seconds, but I found that this function no longer works. 

I tested the origin version from https://github.com/mpc-hc/mpc-hc/releases and it works fine.

Please check where the code is modified.

**Comment by bibsp** [comment]
Sub delay working well in 1.9.20
Try resetting MPC-HC settings or fresh install.

Or wait for official's reply.

**Comment by clsid2** [comment]
Working fine for me.

Make sure that you are actually using the internal subtitle renderer, and not some external renderer such as VSFilter.
