### ISSUE TITLE
The Zoom in/out hotkeys should take into account the window position (just like the other zoom hotkeys)

### ISSUE THREAD

**Issue by CoolCmd** [clsid2/mpc-hc#1626]
In version 1.9.19 Zoom in/out hotkeys were added. They always grow the window in the bottom right direction. Thus, these hotkeys are useless if window is close to the right or bottom edge of the screen.

They should take into account the window position, just like Alt+1..4 keys do. For example, the window should grow **from the center** if there is a room in all directions, and should grow to the left if there is no room on the right.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2710

This follows the normal zoom rules.  It has a behavior that the window grows wider but not taller, once it is out of room.
