### ISSUE TITLE
audio options confusion (documentation needed!)

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1627]
Is there a way to make audio options more clear? perhaps with preset modes or just better documentation (or tooltips like "use this option for x, turn this option off for y"?
For example, we've got:

- Audio decoder > audio settings & mixing
- Audio switcher
- Audio renderer

Multiple options depend on other options, and they're all split, and to be frank, the average user can never figure it all out.

For example: for proper downmixing to stereo where certain channels like dialog aren't quieter than the rest, what are ALL the options that need to be either turned on or turned off?
What about the Audio renderer and audio switcher?

a preset system could look like:
Choose audio setup: surround or stereo speakers, PCM or Bitstream, and whatever reasons there are for using certain audio switcher or renderer over another.

or like a quick setup wizard type of deal

just so the end user knows the audio settings are set correctly for optimal audio quality

**Comment by clsid2** [comment]
If you want automatic configuration wizard, install MPC-HC as part of the K-Lite Codec Pack.

**Comment by ghost** [comment]
@clsid2 I want to understand the audio settings so I can make sure they're set correctly...
clear **_documentation_** would be great

**Comment by ghost** [comment]
@clsid2 am I in the wrong here or is there no documentation on the various audio settings?

**Comment by clsid2** [comment]
I am not going to do the boring job of writing documentation. Most options are self explanatory.

If you want stereo output, simply enable mixing in the audio decoder. Or fix your Windows settings.

**Comment by ghost** [comment]
@clsid2 
When should someone use SaneAR audio renderer and why?
When should someone use the built-in audio switcher filter and why?
Why is the MPC Audio Renderer Settings button under SaneAR greyed out even though SaneAR Audio Renderer is enabled?

If you don't want to write the documentation by yourself, at least create an official place for a wiki type documentation so that other people can contribute and make this player have some decent documentation. 
Everything I look up about mpc-hc settings are on random websites and blogs from 10 years ago, so none of the recent additions are ever mentioned.

**Comment by clsid2** [comment]
Sane AR and MPC AR are two distinct renderers (but with similar capabilities). Biggest advantage compared to directsound is pitch correction.

I am not writing documentation, nor setting up anything for it. I don't have any time for that and I do not care about that. Period.
