### ISSUE TITLE
[Feature Request] Auto update

### ISSUE THREAD

**Issue by aosfan** [clsid2/mpc-hc#1629]
First of all I want to say that MPC-HC is an absolutely wonderful program, which I use with great pleasure.
Could you please add an auto-update feature?
Right now the update process is monstrously inconvenient: you get a notification about a new version, you have to go to the site, download it yourself and manually install it. God... Why?

Why not do it in one click or even silently, as in any modern software? There's a new version, update?, yes, boom! Done.

**Comment by clsid2** [comment]
I am not going to spend time on implementing that.
