### ISSUE TITLE
Version 1.8.8 hang on end of Youtube stream - Lav Filters related - Regression from 1.8.7

### ISSUE THREAD

**Issue by t3chnical1** [clsid2/mpc-hc#163]
To reproduce, open any video on YouTube through YouTube-DL with version 1.8.8. Either wait for it to reach the end or use the seek bar to reach -3 seconds and let it play through.

If you click on STOP, PLAY or the middle of the screen, the player hangs (100% cpu). 

Instead, when the video ends, you can use the seek bar to go back to any part of the video and it will not hang. You can also use the skip forward to skip to the next item in the playlist without hanging.

When the video ends, it's as if the player does not detect the end of the video. Its seems to be directly related to the latest Lav Filters in version 1.8.8 since this issue is not present in 1.8.7. I have not debugged MPC-HC so I simply don't know if the issue is in MPC-HC or Lav Filters.

For testing purposes, I have also used the 1.8.7 version and updated only the files in LAVFilters64 to version 1.8.8, which does reproduce the anomaly.

Oh, and hats off to clsid2 and everyone contributing to this fork. It's awesome to see it still alive and well :)

**Comment by clsid2** [comment]
This is already fixed in latest LAV Filters. So it will be fixed in next release version of MPC-HC. Maybe later this week.
