### ISSUE TITLE
File history "Remember File position" behavior change introduced in 1.9.20 - make the 95% reset logic configurable

### ISSUE THREAD

**Issue by itisafrickinhighlander** [clsid2/mpc-hc#1631]
Would it be possible to make the logic resetting the position when it is closed beyond 95% progress, at least in the Advanced Settings, configurable to switch this logic off? 
I tend to close the files like that so that when I get back to some older ones in the future I will know where I ended (I set the history manually to 1000). 
I am not sure how others use the feature, but it sucks a bit to have something like this forced now.

**Comment by clsid2** [comment]
It is already removed in latest development build.
