### ISSUE TITLE
Save Image with PGS subtitle seems wrong

### ISSUE THREAD

**Issue by tasty0tomato** [clsid2/mpc-hc#1633]
Find during https://github.com/clsid2/mpc-hc/issues/1459
Take https://github.com/clsid2/mpc-hc/issues/1459#issuecomment-997421403 for example, this is what it looks like with PGS subtitle.
![2022-03-30_12-45_1](https://user-images.githubusercontent.com/48764449/160754010-031fe0e0-be93-4b44-b7bb-871ecb9b41b8.jpeg)
But if I click **Save Image...**, the output image looks like this.
![04-Rec2020-Red-100% mkv_snapshot_00 08 519](https://user-images.githubusercontent.com/48764449/160754163-d91fd609-cb16-474b-886b-721def55808a.jpg)

**Comment by clsid2** [comment]
Duplicate.
