### ISSUE TITLE
OSD stretching out during changing window size

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#1634]
As the title mention, OSD drawing behavior is a bit weird, it scales itself by window size. It is also noticeable while View > video frame > aspect ratio > 4:3 and again revert it to default. I also noticed that Ctrl + I (show time) has a different behavior. It tries to catch true size during resize but play, pause, volume of OSD things stays stretching out until OSD display time ends. 

![resim](https://user-images.githubusercontent.com/3073922/160757826-ba252797-9605-45fd-9973-3f884d89dc1d.png)
![resim](https://user-images.githubusercontent.com/3073922/160757901-93186128-ff4b-4383-b1c0-f168ce5e1c78.png)

view > video frame > aspect ratio section:
https://i.imgur.com/iDR4quw.gif

ctrl + I 
https://i.imgur.com/FtI4uhC.gif

play, pause and volume :
https://ibb.co/YhWCMW5

mpc-be is handle OSD nicely:
https://ibb.co/GT0xJpq

This stuff is just visual glitch so its not core part of software, if developers have free time can look up or maybe if it's possible, copy OSD behavior from mpc-be. I am just reporting.

**Comment by adipose** [comment]
Maybe a default font size scaled to DPI. Say 20 pointed font?

**Comment by clsid2** [comment]
BE uses a totally different way of showing the OSD afaik. Last time I checked it draws on top of the window instead of doing it through the video renderer.

**Comment by OneOfMany07** [comment]
Drawing directly onto the window might be a superior option.  Less chance of video filters messing with it.  And no chance of redirected output having the OSD messages.  Though no idea if saving output is a use case for MPC-HC...I only play movies to my screen 😁.

Would directly writing on the video surface limit render types (maybe only newer versions like EVR)?  Or acceleration options like "overlay mode"?  Just trying to think ahead to possible reasons not to work on a change.

**Comment by adipose** [comment]
@clsid2 maybe can close.
