### ISSUE TITLE
EVR-CP/Sync bug.

### ISSUE THREAD

**Issue by Aleksoid1978** [clsid2/mpc-hc#1636]
If you open a video file with very low fps, then very often the filter(EVR-CP/Sync) is not unloaded when the file is closed, the it's destructor is simply not called. After closing MPC-HC we take memory leaking.

Sample file in attach. Open it and close before 5 seconds.
[0.2fps_2frames.avi.zip](https://github.com/clsid2/mpc-hc/files/8386539/0.2fps_2frames.avi.zip)

The same in MPC-BE.
That's how I understood after sitting in the debugger - it looks like a bug in the system libraries of DirectShow.

**Comment by clsid2** [comment]
Yes, I can confirm that `~COuterEVR()` destructor was not called when the problem occurs. I don't know why.

**Comment by v0lt** [comment]
You can try [this solution](https://github.com/Aleksoid1978/MPC-BE/commit/0037ed41889b08fbf909b04f03b41be39b2d3904).

**Comment by clsid2** [comment]
I tried your patch, but it doesn't fully work.

It does work if I also pause the graph before resetting position to 0. Stopping before the position reset does not work. Very weird behavior of EVR.

**Comment by clsid2** [comment]
Do you have a similar sample file with 10 frames? I am curious to test how that behaves and if it depends on the EVR buffer size.

**Comment by clsid2** [comment]
Fixed in https://github.com/clsid2/mpc-hc/commit/fa6c141737f4ba1b2757038e424033f9d36cc3b9

**Comment by v0lt** [comment]
> Do you have a similar sample file with 10 frames? I am curious to test how that behaves and if it depends on the EVR buffer size.

Download from the link. The archive will contain samples for 1, 2, 3 and 10 frames. 
https://cloud.mail.ru/public/5rvg/5yiKjzck7/
https://www.sendspace.com/file/tmzff2
