### ISSUE TITLE
Make separate fullscreen compatible with D3D exclusive

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#1637]
- Left clicking on main window does currently not work. Right click works.
- Main frame is not cleared. Currently it shows last frame from before fullscreen switch.

@adipose
I can't find the code that blocks the left click.

**Comment by adipose** [comment]
There was a property of the full screen window NCACTIVATE that might be an issue.

**Comment by adipose** [comment]
```

LRESULT CFullscreenWnd::WindowProc(UINT message, WPARAM wParam, LPARAM lParam)
{
    if (message == WM_NCACTIVATE && m_pMainFrame->IsD3DFullScreenMode()) {
        return FALSE; //do not permit taking focus from fullscreen window.  only in D3D mode
    }

    return __super::WindowProc(message, wParam, lParam);
}

```

I added the part about d3d to make the other one work. You could make the rule apply only when same screen...

**Comment by adipose** [comment]
By the way, the full-screen code for the second monitor mirrors the d3d code for the most part. If d3d is supported too, it could be done in a common routine.

**Comment by clsid2** [comment]
Fixed the two issues.

I have removed the whole code block there in WindowProc. Not sure if preventing focus steal is really needed.

**Comment by adipose** [comment]
Some other notes:

I added special code in `CreateFullScreenWindow()` for the off-screen window, so that it doesn't steal focus.  This could also be used for d3d, now.  The general idea is, if the mainframe is showing, there's no reason for it not to retain focus, and if it's not showing, you can't really tell as there's no titlebar on the other window.

```
    if (isD3D) { //for d3d window, we will take focus as no other window is visible
        return !!m_pFullscreenWnd->CreateEx(WS_EX_TOPMOST | WS_EX_TOOLWINDOW, _T(""), ResStr(IDS_MAINFRM_136), WS_POPUP | WS_VISIBLE, monitorRect, nullptr, 0);
    } else { //for second monitor fullscreen mode, allow the mainframe to keep focus
        bool ret  = !!m_pFullscreenWnd->CreateEx(WS_EX_TOPMOST | WS_EX_TOOLWINDOW, _T(""), ResStr(IDS_MAINFRM_136), WS_POPUP, monitorRect, nullptr, 0);
        if (ret) {
            m_pFullscreenWnd->ShowWindow(SW_SHOWNOACTIVATE);
        }
        return ret;
    }
```

The focus steal issue seems pointless, but there must have been a reason.  I tried to take focus in d3d mode and could not, even with the mainframe, on a single monitor.  And on two monitors, you need to take focus to use the other window.  There once was a horrible thread that tried to keep focus, and it was replaced by the NCACTIVATE bit (https://github.com/clsid2/mpc-hc/commit/20985ac0cf7dc4c746f0a3997463a1910d77164a).  Maybe there has been an issue with other applications stealing the focus of the D3D window.

**Comment by ale5000-git** [comment]
@adipose
It probably isn't related to new code but it still annoying:
Enable exclusive fullscreen in MPC Video renderer (DXVA2 native on Windows 7 with K-Lite Codec Pack 16.9.5), open a video and go fullscreen.
While fullscreen press ctrl+alt+canc, then choose to open Task Manager, MPC-HC screw up (sometime recover and some other not), when exiting full-screen something the screen remain all back for a while (like 5 seconds).

**Comment by clsid2** [comment]
@adipose
Do you mean to use SW_SHOWNOACTIVATE for D3D case as well? And remove WS_VISIBLE flag?

@ale5000-git 
This issue is just for discussing the internal D3D exclusive mode of EVR/VMR, not for bugs with external renderers. I don't recommend using exclusive mode at all with any renderer.

**Comment by adipose** [comment]
> @adipose
> 
> Do you mean to use SW_SHOWNOACTIVATE for D3D case as well? And remove WS_VISIBLE flag?


Right. Basically all its does is keep focus on the mainframe. It's weird to popup full-screen but have the controls lose focus.

**Comment by clsid2** [comment]
D3D still has the old bug that video is not shown when switching to fullscreen a second time. Any idea where the cause of that may be?

**Comment by clsid2** [comment]
Working a bit better after 5aeade509bb7f9275259f0b2e0da1299089a4987. But still D3D fullscreen can fail to show the video randomly.

**Comment by clsid2** [comment]
As a test I added a 5 second sleep before
`pD3DFS->SetD3DFullscreen(true);`
That seems to help to prevent the problem, but of course not usable in practice.

**Comment by Raziel-SSJ** [comment]
> D3D still has the old bug that video is not shown when switching to fullscreen a second time. Any idea where the cause of that may be?

Not sure if this is related so sorry if I'm polluting this thread, but something similar happens when automatically switching display mode (resolution or frequency) with MadVR's related option.

**Comment by clsid2** [comment]
Problem is not related to switching display mode.

**Comment by adipose** [comment]
I managed to hang EVR-CP switching from D3D mode and back.  This is in debug mode...

**Comment by adipose** [comment]
Try this (add lock line):

```cpp
STDMETHODIMP CDX9AllocatorPresenter::SetD3DFullscreen(bool fEnabled)
{
    CAutoLock cAutoLock(this);
    fullScreenChanged = (fEnabled != m_bIsFullscreen);
    m_bIsFullscreen = fEnabled;
    return S_OK;
}
```

**Comment by clsid2** [comment]
Problem seems to be related to the FocusThread stuff. Disabling that fixes the transparent fullscreen problem at first test.
Edit: taking away focus now hides the fullscreen window
But problem is probably due to focus being set to wrong window handle.

**Comment by adipose** [comment]
I reverted the minor changes you made (to force the issue) and added the lock. After that it never failed for me.

**Comment by clsid2** [comment]
Did you test with a second monitor? It only fails for me when using a different fullscreen monitor.

**Comment by adipose** [comment]
Yes, I was using D3D and second monitor for testing.  I couldn't get it to fail at all, until I reverted your fixes.  Then it failed consistently.  As soon as I added the lock, though, the problem went away.

**Comment by clsid2** [comment]
Weird. Here is works for 2 or 3 switches, then fails (a few times), then work again, then fail, etc.

**Comment by adipose** [comment]
Darn.  What if you try the render lock (or both)?

```
    CAutoLock cAutoLock(this);
    CAutoLock cRenderLock(&m_RenderLock);
```

**Comment by clsid2** [comment]
Already have both. Also tried with just the first one.

**Comment by adipose** [comment]
By any chance is your second monitor on a separate adapter?

**Comment by clsid2** [comment]
No, just one adapter. I also tried with the reinitialize option enabled.

It is a Win7 system. Maybe that makes a difference.
