### ISSUE TITLE
Prevent loading of huge .xchp files

### ISSUE THREAD

**Issue by dechamps** [clsid2/mpc-hc#1642]
For somewhat contrived reasons (see oniony/TMSU#242), the latest version of MPC-HC caused problems with my setup because it attempted to load a bogus multi-GB `.xchp` file. This resulted in playback taking a long time to start.

The circumstances in which this can occur are somewhat silly/contrived, but still, it would make sense for MPC-HC to detect when a `.xchp` file is obviously bogus (e.g. it's >10 MB in size, I don't know) and refrain from attempting to load it if that is the case. This seems like a good idea any way because it would make MPC-HC more resilient to bad files.

**Comment by clsid2** [comment]
I made a little chance to abort early when parsed data is invalid.

Having such a file exist is user error.
