### ISSUE TITLE
DTS Bitstreamed Audio Garbled in 1.9.20

### ISSUE THREAD

**Issue by bedub1** [clsid2/mpc-hc#1643]
I'm bitstreaming DTS audio, over my Nvidia RTX2060, to my Onkyo receiver.  I have the latest Nvidia drivers installed.  

In version 1.9.19 the audio is perfect.  In 1.9.20, the audio is garbled.  I uninstalled 1.9.20, reverted back to 1.9.19, and the audio is back to normal.

**Comment by clsid2** [comment]
Working fine for others. I can't help you.
