### ISSUE TITLE
mpc-hc cannot select correct font from ass file

### ISSUE THREAD

**Issue by yangzhaofeng** [clsid2/mpc-hc#1647]
I use mpc-hc 1.9.20 on windows 10 21h2, and the display language is en-us. I found that mpc-hc cannot correctly load system font when the subtitle is from ass files. Here is an example:

[[LoliHouse] Shoujo Kageki Revue Starlight The Movie [BDRip 1920x804 HEVC-10bit FLAC].chs.zip](https://github.com/clsid2/mpc-hc/files/8416779/LoliHouse.Shoujo.Kageki.Revue.Starlight.The.Movie.BDRip.1920x804.HEVC-10bit.FLAC.chs.zip)

While 思源黑体 is Source Han Sans CN, 思源宋体 is Source Han Serif SC, 方正宋黑_GBK is FZSongHei-B07.

Using either Chinese or English name of the font do not work. I have to select fonts manually for all parts in `Subtitle Track -> Style`

**Comment by clsid2** [comment]
Try without "bold" in the name. Name should be equal to what is shown in the fonts list when selecting it manually.

**Comment by yangzhaofeng** [comment]
Using without "bold" works, but font name also has to match the system language.

**Comment by clsid2** [comment]
That is not something I can fix.
