### ISSUE TITLE
Feature After Playback will be  reset to "Do Nothing" each time the app playing

### ISSUE THREAD

**Issue by mhmdshz** [clsid2/mpc-hc#1650]
MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.20 (4ba465350)
    Compiler:           MSVC v19.29.30141
    Build date:         Mar 16 2022

LAV Filters:
    LAV Splitter:       0.76.1.0
    LAV Video:          0.76.1.0
    LAV Audio:          0.76.1.0
    FFmpeg compiler:    MinGW-w64 GCC 10.2.0

Operating system:
    Name:               Windows 10 (Build 21H2)
    Version:            10.0.19044 (64-bit)

Hardware:
    CPU:                AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
    GPU:                AMD Radeon(TM) Vega 8 Graphics (driver version: 26.20.11030.22001)

**Comment by clsid2** [comment]
That menu option is only for the CURRENT file.

This one is for every time:
Options > playback > after playback
