### ISSUE TITLE
Finer adjustment of playback speed ?

### ISSUE THREAD

**Issue by Mrnofish** [clsid2/mpc-hc#1653]
I'm using MPC-HC to watch/listen to long files at a sped-up rate, and sometimes I wish mpc-hc had finer adjustment options to accommodate speakers that talk at different speeds.

Through the menu I can only select 1.10, 1.25 or 1.5x. Ctrl-Up/Down has even bigger steps.

Occasionally I find it useful to slow-down below real-time (e.g. to help with transcripts), here there are more options, however 0.25x is almost impossible to use and 0.5 can be too slow.

Thanks for all the excellent work.

**Comment by clsid2** [comment]
Options > playback > Speed step

You can set that as low as 5% per step.

**Comment by Mrnofish** [comment]
That's great, thank you very much.

**Comment by rbpaiett** [comment]
You can actually change the speed step to 1%.  Just put 1 (instead of auto) and click 'apply'.
