### ISSUE TITLE
Options, keys page has ampersand bug

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#1657]
In options > Player > Keys page has ampersand bug that cause underline character next to "&". This is probably similar to #1550 

![resim](https://user-images.githubusercontent.com/3073922/162431194-1817e03f-4614-4895-96a6-8eed2fafcd8d.png)

**Comment by clsid2** [comment]
Fixed

**Comment by xLn2** [comment]
version 1.9.20.52 
It looks like the underlining fixed, but this time the ampersand became invisible.
![resim](https://user-images.githubusercontent.com/3073922/162644036-b9ed4aec-bb82-4070-8399-e9a5c0b72aaa.png)

and I think for organize favorites ampersand might be unnecessary.

**Comment by clsid2** [comment]
Fixed again.
