### ISSUE TITLE
Play last open file broken

### ISSUE THREAD

**Issue by Revenger** [clsid2/mpc-hc#1659]
I used to be able to click play and it would load the last opened file.

This was handy for anime and long series as I use a Android remote and if I stopped watching say episode 14 when I reloaded mpchc and clicked play it would reload up episode 14 so I could easily move to episode 15.

Now I need to remember what episode I left off from and use the file browser on my remote app to go into 'drive letter / group folder / show folder/ then scroll and load the next file to watch.

When your watching shows with 200+ episodes at various accounts each day or so remembering you left on episode 146 the night before is tedious.

Please bring back opening last file on pressing play.

I have both remember playlist and history turned on.

**Comment by clsid2** [comment]
That should still work.

**Comment by Revenger** [comment]
Have version 1.9.20 installed.
Somehow it's working now on a test, I'll do more testing and figure out the actual cause and reply back.

**Comment by clsid2** [comment]
If player crashes, then it can happen that playlist is not saved, disabling the play button on next start.

**Comment by Revenger** [comment]
Thought that may the reason as I shut down the PC while mpc is still open after watching, but that should also close the player.
Used to work like this fine.

**Comment by clsid2** [comment]
That might terminate the player process, instead of closing it normally. Because playlist is saved when closing normally. So not a good idea to do.

I will apply a patch to save it when loading file as well.
