### ISSUE TITLE
Feature Request - Add support to normalize/boost/decrease the audio volume in all audio/video files

### ISSUE THREAD

**Issue by Felipefpl** [clsid2/mpc-hc#1660]
Vlc has this feature although it's complicated to use on it. There are movies' videos where the several music/sound effects are all misplaced, some are too loud and others too low to hear.

**Comment by clsid2** [comment]
There already is a normalize option in the audio switcher.

I am not adding any new functionality.

**Comment by Felipefpl** [comment]
> There already is a normalize option in the audio switcher.
> 
> I am not adding any new functionality.

I should have explained myself better, what i meant was a tool to normalize the audio changing the audio/video files themselves.

**Comment by ale5000-git** [comment]
This is a player, it isn't a video editor.
