### ISSUE TITLE
Filter properties dialogs are modal and it'd be nice if they weren't.

### ISSUE THREAD

**Issue by OneOfMany07** [clsid2/mpc-hc#1665]
If I open any filter property while playing a video I can't left click the video to change the pause/play state until I close the property dialog.  MadVR seems to get around this by having MPC-HC open a dialog that itself opens the settings window (click "edit settings" button).  Annoying to need the extra click + dialog close to see the true settings page, but I do appreciate the end effect.

I'd prefer to be able to use/view multiple filter property dialogs, all while still being able to control the video through the main window or view other parts of MPC-HC.

Is this an MPC-HC choice?  Or do the filters have this setting?

**Comment by clst** [comment]
Oh so I am not the only one who would love to see that.  
It works pretty well when I just change the window properties of the LAV dialogs manually.
