### ISSUE TITLE
Image viewing with mpc-vr may cause mpc-hc crash

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#1667]
In last 2 days it #1666 probably happened to me. I was looking image opening behavior and drag and drop single image file on mpc-hc after 15-20 image is viewed it crashed. I just assume that viewing .jpg .bmp and .png files on Mpc hc caused that. Some file types i.e .png are not get playing state but .jpg and .bmp gets playing state and it plays probably until app close or crash. Memory leak might happened in my case or mpc-vr has issue with png files.

In my system tray I see that Lav splitter and decoder but these programs are not I am used to see it. These are opened when I open png file. (dark theme lav window is what I am used to see and I am suprised when I see different lav window.)
![resim](https://user-images.githubusercontent.com/3073922/163057162-216c8372-9b2c-4f1d-a8d6-e11670aa8330.png)

![resim](https://user-images.githubusercontent.com/3073922/163059066-374a077a-821f-4412-ad00-1844ab333a03.png)
![resim](https://user-images.githubusercontent.com/3073922/163059110-90c2e0d7-3872-467b-aa49-f4b86022e4db.png)
I dont understand how these lav splitter version may vary and settings different. 

lav splitter input formats: https://i.imgur.com/Vn58I6v.png
my mpc-hc language settings:
![resim](https://user-images.githubusercontent.com/3073922/163060604-abbc2456-fbc4-4b50-b3e8-8f53117e0683.png)

Findings:
- opening png files started paused state and do not get playing state and somehow stuck black screen. Same bug in MPC-BE.
- apng does not supported. Example file. [APNG-Beispiel.zip](https://github.com/clsid2/mpc-hc/files/8477004/APNG-Beispiel.zip)
- png files does not go fullscreen with double click, only alt+enter can make it fullscreen.
- (EVR-CP) when you somehow achieve fullscreen png file, Black bar is persistent (described two bullet down) and controller time shows stucked unless mouse pointer is not on control bar.
- jpeg and bmp files plays infinitely (time counts until pause) it may be expected behavior.
- alt tab or in full screen when playlist snapped right or bottom corner it gives black bar until image drawing refresh in my system it takes 5-15 seconds. https://i.imgur.com/VfLKwVu.gif
- (EVR-CP) dragging 2 jpeg files to mpc-hc it shows black screen until you click on video area or alt+enter. Mpc-vr is fine here.
- dragging multiple png files to mpc-hc cause glimpse and only latest one being visible. Probably because of no duration time.

Suggestions:
- I have no idea about the possibility but for image files, Mpc-hc may take control and use EVR-CP or which renderer is better.
- Add advanced options to allow users to specify static image duration or you can determine a specific value. For example, in pot player for 10 seconds.
- OSD might be closed for image type of files. except filename.

Sorry for the confusing explanation, there may be a few intertwined issues, or there may be problems with my usage.

**Comment by clsid2** [comment]
JPG and BMP are handled by the Microsoft "Generate Still Video" source filter, which creates artificial infinite video.

Double-clicking on PNG will pause/unpause and that breaks "playback" because images do not have duration when handled by LAV. I don't think the LAV developer is interested in improving images support to make it behave like "Generate Still Video". Use F11 to toggle fullscreen. I might look into the black screen issue, but it is super low priority.

MPC-HC is not a image viewer. Its support for images is very limited and I am not really interested or capable of improving that. Using DirectShow for rendering images is just not a good method.

Swapping renderer based on file extension is not something I will ever implement. Again, this is a video player, not an image viewer.

**Comment by clsid2** [comment]
I have send patch for the crash to MPCVR developer.

For PNG and other formats you can use [MPCImageSource](https://github.com/v0lt/ImageSourceFilter) which works similar to "Generate Still Video".

And no, I am currently not interested in integrating that.
