### ISSUE TITLE
Don't support .VTT subtitles!

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#167]

**Comment by clsid2** [comment]
There are no plans to support such subtitles.

You can convert them to SRT:
https://subtitletools.com/convert-to-srt-online

**Comment by adipose** [comment]
@riadrox, I added minimal support for vtt in the test build below.  To be clear, vtt is a fairly complex format compared to srt, but at its core it's nearly the same format.  All this does is support the vtt file to the level of srt capabilities (about the same as if you simple converted the file to srt).

Most of the additional features would provide no benefit for MPC, anyway, being tailored to web use cases.  But if those cases prove necessary some of them could later be supported.  The only one I can think of that would matter would be style blocks, but trying to support full-blown HTML styles in MPC-HC seems like a losing game.

https://mega.nz/#!RYQFHKBL!lbRoIp8e_TU0c77V0vVqHmuFbQ4FRZqj_H71jsP_YW8

**Comment by adipose** [comment]
@clsid2 

I don't think I committed this code, did I?  No one had tested this build.

**Comment by clsid2** [comment]
I opened it to get more exposure for testing.

**Comment by adipose** [comment]
Sounds good.

@riadrox, any chance of you testing it?

**Comment by adipose** [comment]
@thelastzombie, you could also test.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/303
