### ISSUE TITLE
[Bug] Internal LAV Audio Decoder fails at PCM audio

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [clsid2/mpc-hc#1670]
When I play a PCM audio (WAV), it uses external LAV Audio Decoder instead of the _internal_ one.

```
Filters currently loaded:
  - DirectSound: Another Live Adventure (Rea...
  - Audio Switcher
  - LAV Audio Decoder
  - LAV Splitter Source (internal)
```

**Comment by clsid2** [comment]
That is intentional. PCM does not need decoding.

**Comment by NanaMizukiAnother7** [comment]
Oh. I see commit 576aa25918685495386cea95eeda2db99c32431f.

**Comment by NanaMizukiAnother7** [comment]
Um... I can still see the PCM/ADPCM.:
![image](https://user-images.githubusercontent.com/78664512/166900024-810dfb3a-f400-408e-9edf-0abcf364220d.png)

**Comment by clsid2** [comment]
You see wrong. That is non-standard PCM.

**Comment by NanaMizukiAnother7** [comment]
Oh. I see wrong. I'm sorry.
