### ISSUE TITLE
save file position

### ISSUE THREAD

**Issue by LetsPlayNintendoITA** [clsid2/mpc-hc#1673]
hi,
I can't mantain the save file position without admin rights, and if I use admin rights, I can't save the settings or viceversa.
somethign wrong is going with that.
can you help pleasE?

**Comment by clsid2** [comment]
Don't store settings in INI file. Program files folder is not writable without admin elevation.

**Comment by LetsPlayNintendoITA** [comment]
and how do i save it then? it doesn't save settings without it

**Comment by clsid2** [comment]
Settings are saved in the Registry. If that isn't working then your user profile is completely fucked up.

Delete this Registry key to reset settings:
HKEY_CURRENT_USER\Software\MPC-HC
