### ISSUE TITLE
UNEXPECTED ERROR 

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1676]
NOT ONLY THIS NEW PATCH 
I HAVE SAW IT MANY TIMES
![mpc-hc error](https://user-images.githubusercontent.com/7498798/163942227-d0b2051a-4dce-4858-b3ff-6f4af76db37f.PNG)
 
IT WAS HAPPENED WHEN I WATCH ONLINE STREAM

**Comment by ghost** [comment]
I DIDNT TURN ON THE SETTING : ENABLECRASHREPORTER.
IF U NEED I WOULD TURN ON 
BUT PLZ TELL ME HOW TO UPLOAD OR  TO WHERE. MAYBE JUST START THE sendrpt.exe?

**Comment by ghost** [comment]
https://drdump.com/UploadedReport.aspx?DumpID=95546847
HAHA. NO MORE NEED THE ANSWER.

**Comment by clsid2** [comment]
I need a link to the stream that triggers this crash.

**Comment by ghost** [comment]
https://live.bilibili.com/p/eden/area-tags?areaId=92&parentAreaId=2
just open any stream and F12 network search .m3u8 paste to play
or use https://github.com/wbt5/real-url/blob/master/bilibili.py this and print the room number to got stream link.

**Comment by clsid2** [comment]
Tried first stream, but no crash here.

**Comment by clsid2** [comment]
Does the crash happen immediately when loading the stream? Or randomly during playback?

**Comment by ghost** [comment]
> Does the crash happen immediately when loading the stream? Or randomly during playback?

 no idea. i found its not crash at start but when u keep watch few minutes sometimes  warn u with new windows and sometimes just stay at the play state like the streaming is over. Recently i keep found the regulation but no result.

**Comment by clsid2** [comment]
I can't reproduce. Also, it is problem in the internal filters, which I can't fix.
