### ISSUE TITLE
Changes in 'Default track preference' not working

### ISSUE THREAD

**Issue by Kyyo17** [clsid2/mpc-hc#1677]
![mpc 3](https://user-images.githubusercontent.com/81768223/164212058-8be93fa5-8fc7-45fc-8e29-854f26a5a420.png)
Changes made in Option, but it is not working.

![mpc 1](https://user-images.githubusercontent.com/81768223/164212186-f411ed0c-9de7-41df-8ed5-7c7e5f5465b0.png)
![mpc 2](https://user-images.githubusercontent.com/81768223/164212204-ecf68994-2a51-4859-aa4d-3041a6a3bc43.png)

What's the correct way to do it?

**Comment by clsid2** [comment]
Options > Internal Filters > Splitter

**Comment by Kyyo17** [comment]
> Options > Internal Filters > Splitter

Thanks!

**Comment by chinhnhguyen090** [comment]
> Options > Internal Filters > Splitter

thanks. I've been looking for this for a long time
