### ISSUE TITLE
Are binaries available somewhere? What do I need to compile it in Visual Studio 2012?

### ISSUE THREAD

**Issue by pboettcher** [clsid2/mpc-hc#1678]
* Are binaries available somewhere?
* What do I need to compile it in Visual Studio 2012? I tried to compile it after conversion to VS2012, but there are a lot of errors (645 errors), for example "Error	30	error C1083: Cannot open source file: 'freetype2\builds\windows\ftdebug.c': No such file or directory	D:\Work\Paul\Documents\Programm\Experiments\MPC-HC\mpc-hc\src\thirdparty\freetype2\c1	freetype2". What are the dependencies?

**Comment by clsid2** [comment]
You need VS2019 or newer.

Binaries are here:
https://github.com/clsid2/mpc-hc/releases

**Comment by xLn2** [comment]
https://github.com/clsid2/mpc-hc/blob/develop/docs/Compilation.md

Hope this helps.
