### ISSUE TITLE
Fast Seek is wrongly replaced with Normal Seek

### ISSUE THREAD

**Issue by mikhaelkh** [clsid2/mpc-hc#1681]
Fast Seek - enabled, nearest keyframe, AllowInaccurateFastSeek - true.
Fast seek should have maximum inaccuracy of 20s, but on small jumps (10s) it is sometimes replaced with normal seek even when inaccuracy is lower than 5s.

**Comment by clsid2** [comment]
That setting does not apply to SMALL jumps (only MED/LARGE). It uses max 30% inaccuracy for SMALL.

**Comment by clsid2** [comment]
I have applied a small tweak to also use it if SMALL jump is equal 5 seconds or more.
