### ISSUE TITLE
`Explorer Context Menu -> File(s)` is always checked

### ISSUE THREAD

**Issue by mikhaelkh** [clsid2/mpc-hc#1682]
When I uncheck `Explorer Context Menu -> File(s)`, it is still checked the next time I open `Options -> Player -> Formats`.

**Comment by clsid2** [comment]
That will always be checked whenever there is any registered file association ProgID. So whenever something is enabled in the formats list above.

If you want to remove file associations, you need to uncheck everything in the list.

**Comment by mikhaelkh** [comment]
What should I do if I want to keep file associations and don't want to enable Explorer Context Menu?
Don't touch said option and ignore that it's wrongly checked?

**Comment by clsid2** [comment]
Having an association requires that the "open" (Play with MPC-HC) context menu exists.

I will modify the option so it will control existence of the optional "enqueue" (Add to playlist) context menu entry.

**Comment by clsid2** [comment]
Just to be clear an association means you can set it as the default player. 

You do not need to have anything enabled on the Format page to be capable of playing those formats. Of course it does mean you need to manually open a file with the player.

**Comment by mikhaelkh** [comment]
Just to be clear, Explorer Context Menu is the menu which opens when I right-click on a file or a folder in Explorer, right?
And having an association requires me to add Play and Enqueue entries in Explorer Context Menu? I don't see these entries there, MPC-HC appears only in 'Open With...' submenu and I'd like it to stay this way.

**Comment by clsid2** [comment]
It appears in the root context menu only when it is set as the default application for a file extension.
