### ISSUE TITLE
Configurable audio delay amount 

### ISSUE THREAD

**Issue by itcwlt** [clsid2/mpc-hc#1684]
Hope the amount of audio delay could be configurable since the 10ms value is too small. If the value cannot be configurable, hope change it to 100ms is more better. Thanks.

**Comment by clsid2** [comment]
You can set audio delay in either the audio decoder or audio switcher settings.

**Comment by JNavas2** [comment]
> You can set audio delay in either the audio decoder or audio switcher settings.

Yes, but then finding the correct audio delay can be a long, painful trial and error process. The advantage of a shortcut key is that it is quick and easy. (Even better would be a modeless floating adjustment control.)
