### ISSUE TITLE
[Feature request] Theme changes and improvements

### ISSUE THREAD

**Issue by TheFangster** [clsid2/mpc-hc#1688]
Hello and good day,

I've been a long time user of MPC-HC and only discovered your fork a few months ago. I've wanted to thank you for your extended support for this application.

I often redesign GUIs for software and so have I done with this one.
My version has new app/media icons, splash screen and a new toolbar giving the application a modern look, and dare I say it blends very well with your dark theme which the base MPC-HC was lacking.
The theme can be viewed here: 
https://www.deviantart.com/adzearts/art/MPC-HC-Minimal-Theme-v2-881744699
And here is the preview for the media icons:
https://www.deviantart.com/adzearts/art/MPC-HC-Minimal-Icons-541579527

Now to the actual request, If you would agree on this, I would like to merge the theme in the main MPC-HC project.
What future updates I might do on the visual design, would be done on the base project.

Think about it and let me know when you have the time.

**Comment by clsid2** [comment]
There are plans to redesign the toolbar in the future. With additional buttons and customization options.

I am not going to use your theme. People can can load custom toolbar designs as external file: https://github.com/clsid2/mpc-hc/issues/382
