### ISSUE TITLE
Sub out of bounds

### ISSUE THREAD

**Issue by i2324561w2** [clsid2/mpc-hc#1689]
VLC shows it better, can you fix it?
https://www.mediafire.com/file/qf62da1nj8rx6u8/Magazine.mkv/file
I tried with both XySubFilter_3.1.0.752_x64 and Internal Sub of MPC-HC V1.9.21.2.
Thanks for your work.

**Comment by clsid2** [comment]
The text is rendered at correct size.
The second line on the magazine uses non-breaking spaces at the begin. But the font that is used does not contain that character glyph (hence the square characters you see instead). I can't fix that. It is bad choice by creator of the subtitle.
VLC can use a fallback font for missing glyphs. MPC does not support that.
