### ISSUE TITLE
MPC-HC 1.8.8+ - FFMPEG - Compile issues - Missing headers

### ISSUE THREAD

**Issue by t3chnical1** [clsid2/mpc-hc#169]
I've grabbed the latest code and managed to compile everything in VS2019 except for the LAVFILTERS. Right now, the issue is with FFMPEG. I know I`ve managed in the past (maybe a year ago). I've tried both the VS interface and the build.bat with the same results.

I've read the instructions for installing MSYS2, MINGW, YASM from this fork and the original, but nothing seems to make it work. I've grabbed the latest code in the trunc.

When I tried to grab an older tag (v1.8.7), the Lavfilters source folder (SRC) was empty. I also noticed the folder is empty in the .ZIP release version of the source code on this page : 

https://github.com/clsid2/mpc-hc/releases

Does anyone have an updated guide to compiling it or would be willing to share their MSYS2 configuration?

As seen below, the first error is "features.h" file that isn't found (part of glib2?) : 

`test_cpp_condition features.h defined __UCLIBC__
test_cpp
BEGIN /c/Users/myuser/AppData/Local/Temp/ffconf.X2TT8mX8/test.c
    1	#include <features.h>
    2	#if !(defined __UCLIBC__)
    3	#error "unsatisfied condition: defined __UCLIBC__"
    4	#endif
END /c/Users/myuser/AppData/Local/Temp/ffconf.X2TT8mX8/test.c
x86_64-w64-mingw32-gcc -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-tree-vectorize -D_WIN32_WINNT=0x0600 -DWINVER=0x0600 -I../../../thirdparty/64/include -std=c11 -E -o /c/Users/myuser/AppData/Local/Temp/ffconf.X2TT8mX8/test.o /c/Users/myuser/AppData/Local/Temp/ffconf.X2TT8mX8/test.c
C:/Users/myuser/AppData/Local/Temp/ffconf.X2TT8mX8/test.c:1:10: fatal error: features.h: No such file or directory`

I've also tried multiple versions of MSYS and MinGW to no avail. Note that is just one of around 20 missings files.

[config.log](https://github.com/clsid2/mpc-hc/files/3914687/config.log)
[LAVFilters.log](https://github.com/clsid2/mpc-hc/files/3914688/LAVFilters.log)

I'll be glad to update the Compilation.md instructions if I figure it out, as it does need a bit of work :)

**Comment by clsid2** [comment]
The release ZIP only contains code for this repository. It doesn't contain external repositories that are needed for compilation. You should use Git to make a clone of the repo. That way you get all required code.

Install MSYS without mingw. Instead, get mingw gcc 9.2 from here:
http://files.1f0.de/mingw/
Compilation will fail with older version.
