### ISSUE TITLE
Queuing time threshold when double-clicking files in a folder

### ISSUE THREAD

**Issue by frenksisco** [clsid2/mpc-hc#1690]
Seems to be a minimum playback time, something like 1 o 2 seconds of time threshold, within which MPC-HC does not replace the current playing file with the new double-clicked one in a folder but queues it in the playlist. 
It's really annoying for example when you're looking for a certain sample audio file in a folder, switching from one to another quickly as soon as you realize it's not the right one, and instead of hearing each one as soon as you double-click them you end up with 5 or 6 files in the queue.
Is there any way to avoid this? Thanks

**Comment by xLn2** [comment]
Did you check 
_Options > advanced > redirectopentoappendthreshold_
![resim](https://user-images.githubusercontent.com/3073922/165066308-7d9d98e3-2e9c-4e8c-885d-d80fcae140b8.png)

**Comment by frenksisco** [comment]
Thank you so much, this option is exactly what I was looking for. Unfortunately it can't be set to value 0 like I need.
Problem: If you use the double-clicking on audio files - like in a soundboard - a 250 milliseconds threshold is still too much. MPC-HC keeps sending many lounched files to the queue. 
I really don't understand why queuing can't be disabled completely.

**Comment by clsid2** [comment]
This feature exist to do exactly as described in the tooltip. Without this the stupid Windows Explorer will open a new instance of the player for each selected file. That is super annoying and not what people want.

I will not be changed. Never!

If you don't like it I suggest you use an actual audio player or soundboard.

**Comment by frenksisco** [comment]
Weird. Vlc (which I hate for everything else and will never use instead of mpc-hc) without any kind of queuing threshold instantly opens each file replacing the previous one while keeping only one instance active. Anyway I understand, thanks for all the work behind this great program.
