### ISSUE TITLE
Video does not repeat

### ISSUE THREAD

**Issue by Josepseven** [clsid2/mpc-hc#1691]
Hi i have an issue with the player, I want a video to repeat but it does not play, only the audio is played with a static image. does anyone know how I can solve it?

**Comment by clsid2** [comment]
You did not mention if the video played ok the first time. You also did not mention any details about the video file.

So my only suggestion would be to update your graphics driver.

**Comment by Josepseven** [comment]
The first time it plays fine, then when it comes to repeating the video it shows a static image and only the sound plays. It happens with all types of files, mp4, mkv, avi, etc. I have checked the graphics drivers (Intel UHD 730) and it says that it is updated to the latest version.

**Comment by clsid2** [comment]
It is likely a driver bug with hardware accelerated decoding.

You can get latest Intel driver here:
https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html?wapkw=uhd%20730
Windows Update does not show all driver versions.

You should also update to latest version of the player (1.9.21.2)

**Comment by xLn2** [comment]
Something similar happens to me. but my issue is a bit different but maybe related. My issue simply is play button does not work for first time when video ends.
 When this happens you will notice that screen doesn't go black (a video has static album image cover .webm music video downloaded from youtube). Normally when video ends, it goes full black. I click play button but the first one did not have any effect but the second one works.

It might be related to _reload after long pause_, I will try to find how to reproduce.  When I found i will reply on this issue.

1. i found one possible tip how to recreate, when video end i double click video and double click again, click play button. (did not reproduce again somehow)
![resim](https://user-images.githubusercontent.com/3073922/165855589-5dc213be-cb76-4df2-ae8b-6bdf5254827d.png)
1a. Tooltip of control button has drawing problem after these tryings. But volume slider has no issue.

https://user-images.githubusercontent.com/3073922/165857654-3262e57f-619a-49bc-8a93-b5f65a3cc936.mp4
