### ISSUE TITLE
MPC-HC disturbs MicroSIP EC (Echo Cancellation)

### ISSUE THREAD

**Issue by HAL9081** [clsid2/mpc-hc#1692]
Whenever just starting MPC-HC 1.9.21.2 it does something to the echo cancellation option in MicroSIP settings.
The option is still checked, but does not work anymore. Callers will hear themselves talking - which is annoying.
To fix this I have to quit MPC-HC, go to MicroSIP settings, uncheck EC, save settings, reenter settings, check EC, save settings.

Thanks for reading and for your dedication to MPC-HC.
Best regards Martin

**Comment by clsid2** [comment]
No, it does not do anything to other software. I can't help you. If MicroSIP stops working properly, they need to fix something.
