### ISSUE TITLE
tearing on the picture

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1693]
I have a Dell S2421HN monitor, with amd freesync, from this point on in mpc hc, there is a tear in the image, please add to mpc hc amd freesync

**Comment by clsid2** [comment]
Variable refresh rate is not supported and will never be supported. Video payback needs a stable and predictable refreshrate. You must enable Vertical Sync to fix tearing.

**Comment by Lukjan39** [comment]
how and where?

**Comment by Lukjan39** [comment]
@clsid2 Please correct

**Comment by clsid2** [comment]
https://www.youtube.com/watch?v=5aiuzfmCZGs

If you are still incapable if understanding, then google it, or ask AMD for help.
