### ISSUE TITLE
webm causes computer to ran out of memory in a matter of seconds

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1694]
This specific video causes a gigantic memory usage to the level that if you left it running for too long, everything in the OS falls apart (in my case crashed the display driver, lol)
![Taskmgr_OgCciLT0Dz](https://user-images.githubusercontent.com/19242209/165880670-afe9f5de-c198-400a-b59b-c4c7dd4cc751.png)
[This zip file](https://github.com/clsid2/mpc-hc/files/8587916/videos.zip) contains two videos, UOOOOPA.webm which is the video causing the issue, and ffmpeg.webm is the same video but optimized with ffmpeg (no additional flags) which fixes the issue, included to see if there is some notable difference that can help debugging this issue. 

Build information
------------------------

    Version:            1.9.21.2 (6167a9d8c)
    Compiler:           MSVC v19.29.30142.01
    Build date:         Apr 16 2022

**Comment by clsid2** [comment]
Similar FFmpeg bug:
http://trac.ffmpeg.org/ticket/9738

I can't fix problems in LAV Filters or FFmpeg. That is external project.
