### ISSUE TITLE
Uninstaller of release version 1.9.21.2 says "Nightly".

### ISSUE THREAD

**Issue by FX8350** [clsid2/mpc-hc#1696]
Uninstaller of release version 1.9.21.2 says "Nightly" on my Windows Settings

![image](https://user-images.githubusercontent.com/10481430/166104166-3a17efa6-b1b8-4f39-bb85-333d7aa725b3.png)

**Comment by clsid2** [comment]
That is because of the version.

I don't really care and obviously I can't fix an existing release.
