### ISSUE TITLE
Add tsa extension

### ISSUE THREAD

**Issue by 89z** [clsid2/mpc-hc#1697]
https://github.com/clsid2/mpc-hc/blob/59a30798842cb2bb552aafd62f86a6465923cd48/src/mpc-hc/MediaFormats.cpp#L172-L176

This should allow `.tsa` files to play with a sibling video file.

<https://wikipedia.org/wiki/MPEG_transport_stream>

**Comment by clsid2** [comment]
Use .mpa for audio.

Or mux both together into .mkv and enjoy faster seeking.

**Comment by 89z** [comment]
I did some research, the wiki was updated in 2013, I did find a reference from 2011:

http://tvnt.net/forum/akira-dhb-b31hdr-double-tuner-enregistreur-tnt-hd-mkv-divx-dts-t26336.html

**Comment by 89z** [comment]
Actually, it seems like a good option is to use `.ts` for video and `.aac` for audio. Technically in my case, both files are MPEG-TS, but it seems to work with MPC-HC regardless

**Comment by 89z** [comment]
I changed my mind again. I think `.mts` is a good choice, as it works with both MPC-HC and FFmpeg
