### ISSUE TITLE
Seek bar's delayed response time

### ISSUE THREAD

**Issue by kamild1996** [clsid2/mpc-hc#1698]
Seeking through the video by dragging the mouse through the seek bar is laggy - there's up to a full second of delay between me settling on a position on the seek bar and the video actually playing back from the selected moment.
Video showcasing the problem below. The showcased scrolling method is overexaggerated to make the delay more obvious to see for showcasing, but this unresponsiveness is easily felt when smoothly moving through the seek bar as well. It wasn't a thing in the original MPC-HC.
Tested on latest release 1.9.21.2 and older 1.9.20.

https://user-images.githubusercontent.com/5320414/166414769-e547f482-290b-4c1c-bf3e-a51ddf66c892.mp4

.

**Comment by clsid2** [comment]
I have downloaded that same video from Youtube and seeking is instantaneous. You probably did something stupid such as disabling fast seek.

Options > Tweaks > Fast Seek

Otherwise it could be problem with graphics driver giving slow hardware decoding. It is not a bug in the player.

**Comment by bibsp** [comment]
I also have some mp4 movies which are little bit slow seeking. All other players are fast for those videos.
If it's a driver fault then mpc be must be affected. But BE is fast.
I can upload full movie if you want to check this issue.

**Comment by clsid2** [comment]
You can upload.

**Comment by bibsp** [comment]
https://drive.google.com/file/d/1FuGTYRWhFnQOfU4Iq8ZrVxWUszkWkH1I/view?usp=sharing

**Comment by clsid2** [comment]
Seeking working normally here.

**Comment by kamild1996** [comment]
> I have downloaded that same video from Youtube and seeking is instantaneous. You probably did something stupid such as disabling fast seek.
> 
> Options > Tweaks > Fast Seek
> 
> Otherwise it could be problem with graphics driver giving slow hardware decoding. It is not a bug in the player.

I haven't touched any setting ever since I installed MPC-HC, so Fast Seek is on and right now set to "Nearest keyframe".
It doesn't look like a problem with a graphics driver, I have just tried changing the DirectShow Video output to other options without DXVA and I'm seeing the same behavior. If any other player, incl. old MPC-HC, MPC-BE, VLC and more are having no such issues, then what else could it be other than the player?

**Comment by bibsp** [comment]
> Seeking working normally here.

But how? Just check this example https://drive.google.com/file/d/1unezsaqk7pNBkGmxCTyFBOTtVy0N79x8/view?usp=sharing

Can you check the seeking code of BE or any other players? Maybe something small is missing. Don't mind. I'm just saying.

**Comment by clsid2** [comment]
@[kamild1996](https://github.com/kamild1996)
If it only happens with specific files, then upload that file. If it happens with everything then I don't know what is wrong.

@[Alp1821](https://github.com/Alp1821)
Please keep the file online. Might be bug in LAV Filters. Seems 1 frame difference in keyframe timestamps with that file.

**Comment by kamild1996** [comment]
> @[kamild1996](https://github.com/kamild1996) If it only happens with specific files, then upload that file. If it happens with everything then I don't know what is wrong.

It does happen to every file I checked (MP4, MKV, AVI, DVD/IFO containers; AVC, HEVC, DivX, MPEG2 codecs). I'm guessing it's a pure UI issue, because if I spam left click all across the seek bar instead of dragging my mouse around like I did in the video I posted, there are no delays.

**Comment by clsid2** [comment]
I am unable to reproduce any issue with dragging.
