### ISSUE TITLE
windows not resizing after change of resolution

### ISSUE THREAD

**Issue by LetsPlayNintendoITA** [clsid2/mpc-hc#1699]
so the dvd for The Dead Zone Season 4 has a problem.
the intro for cbs is 4:3.
then the video changes to 16:9 for the rest of the dvd.
but the player doesn't change size and resolution to 16:9 and shows everything in 4:3.
How do i solve please?

**Comment by clsid2** [comment]
I don't have solution for you. I need an ISO of the DVD to reproduce.

**Comment by kkdexz** [comment]
Won't manually selecting the aspect ratio through right-click menu > video frame > aspect ratio (or alternately using the hotkey that cycles through the AR's) address this issue? Or does this not apply to DVDs? I've never actually come across this type of situation personally. Just thought it might be worth a suggestion. And perhaps for future reference in case I ever do.
