### ISSUE TITLE
Accessing the info page of the web server when a file changes causes error

### ISSUE THREAD

**Issue by Guerra24** [clsid2/mpc-hc#17]
I'm using a simple program that pulls the current file from the info page on a rate of 500ms, MPC-HC trows an *access violation* when the file changes and a request is in progress.

![img](https://puu.sh/Bso7n/dcb057f7e5.gif)

Playback continues but once I click OK, it closes.

**Comment by clsid2** [comment]
Can you share that program?

**Comment by Guerra24** [comment]
It doesn't really matter what program is, I was able to recreate it using the browser. But here is it [mpc-discord.zip](https://github.com/clsid2/mpc-hc/files/2367558/mpc-discord.zip)

**Comment by Guerra24** [comment]
Update: Has gotten worse, now crashes when there is no file open.

![img](https://puu.sh/BBHQE/b475fe4fb0.gif)

**Comment by clsid2** [comment]
Fixed.
