### ISSUE TITLE
Hotkey to enable/disable audio delay

### ISSUE THREAD

**Issue by githubbapoopa** [clsid2/mpc-hc#1704]
When connecting or disconnecting a bluetooth headphone a hotkey for enabling or disabling the audio delay would be very useful. Could you add such a feature?

**Comment by bekard** [comment]
@githubbapoopa @clsid2 Where i can find this option? Has it been implemented?

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2777
