### ISSUE TITLE
Playlist with timeout / TTL for specific content (Image)

### ISSUE THREAD

**Issue by reidsneo** [clsid2/mpc-hc#1705]
Hello I make a playlist with format .mpcpl,
it is possible to add a timeout (TTL) to the picture in the playlist?

MPCPLAYLIST
1,type,0
1,filename,ad_BMW5sec.mp4
2,type,0
2,filename,ad_BMW10sec.mp4
3,type,0
3,filename,sample_640×426.bmp

before playlist repeat to be played to number 1, I would like to show the picture BMP about 10 sec before repeat play the first playlist again

Thanks

**Comment by clsid2** [comment]
Next version will have option for this. Default is 10 seconds. Works only in combination with Generate Still Video filter, which is used for JPG and BMP.
