### ISSUE TITLE
Goto Prev/Next Subtitle

### ISSUE THREAD

**Issue by assignmentchampionship** [clsid2/mpc-hc#1706]
With (internal) subtitles. it will only work for a few seconds worth of subtitles. Then using the reload video file hotkey, (and having file history remembered) (or using the reload subtitle key) it will work for another 3-7 or so subtitles. Is there some way of fixing this? Being able to quickly scroll through subtitles but having to press the [reload subtitle] hotkey after every 3-7 subtitles seems like an 'issue' that can be fixed simply by (automatically) reloading the subtitle file each time Goto Prev/Next Subtitle is pushed. Could an option be added to enable this feature? I'm aware I can overlap the hotkeys and probably get it to work. But I think a frequency toggle might be a better option. Or am I misunderstanding the Goto feature?

**Comment by assignmentchampionship** [comment]
To add to this: When reloading a subtitle file it will only 'seek forward', so it won't allow you to go to a previous subtitle and remain on the first subtitle that appears from that timestamp onward. Even after going back in the video towards a subtitle and letting it play out. You'll have to reload while on the subtitle and it will latch onto that subtitle as the first subtitle available. Going forward is no problem.

**Comment by clsid2** [comment]
With embedded subtitles you don't have access to all subtitle content that is spread over the file. If you want to seek based on subtitle you need to use external file.

**Comment by assignmentchampionship** [comment]
Is this not a bug? This is not unintended behavior? This is fixable. It's not supposed to merely search for X seconds worth of subtitles is it? You claim I need to use an external file, while using an internal file and 'reloading' it works 100%. It's simply an extra step and as such I'm here reporting a bug. Am I wrong? I'm aware it works externally. It just doesn't internally work as it is supposed to, or as it is capable of doing.

**Comment by clsid2** [comment]
With embedded subtitles the data is split into many pieces. The player can only see whatever data has been extracted by the splitter. So subs that are far ahead are not known yet.

Instead of reloading the whole file, there is shortcut to reload only the subtitle data.

The subtitle jump/resync functionality is designed for external subs. It is impossible to make it work properly for embedded stuff.

**Comment by clsid2** [comment]
I have added automatic reloading of the subtitle data when pressing the Goto Prev/Next Subtitle hotkeys. So it will work a little better in the future. But search range will still be limited to whatever data is currently available.

You can increase the amount of data available by increasing the values under "Queue Settings" in the internal splitter settings.

**Comment by assignmentchampionship** [comment]
"Queue Settings"
Thank you. This works when seeking forward. This solves that issue. But when seeking backward it doesn't work. Even when starting at the end of the video. Even if the entire internal subtitle track can be preloaded with appropriate memory allocation. It will still refuse to go backwards if you reload (Or if you start fresh).

So backwards seeking still doesn't function. 

"I have added automatic reloading of the subtitle data" 
The drawback here is that you can't seek backwards with this. I wouldn't suggest adding this feature after having tested it more. Increasing the queue is better than auto reload since backwards seeking doesn't work /w reload.

I think there can be a fix in LAV Splitter. If it can somehow queue backwards. I don't know whether this is possible.

**Comment by clsid2** [comment]
It does not queue backwards. You can forget about such functionality ever being implemented.

It works the way it works, and not further changes will be made. If you want to seek based on subtitle, use external subtitle.

**Comment by assignmentchampionship** [comment]
I understand. But it will retain queue that is backwards if it has been there. What is the logic behind keeping a queue in memory that has passed, but no ability for backwards queuing when starting from any point that isn't the start? I'm not trying to argue. I'm simply pointing out a fix for a bugged feature that isn't a mere work-around.

**Comment by clsid2** [comment]
It is not bugged. There will be no changes. Period.

**Comment by assignmentchampionship** [comment]
So if it isn't bugged, how can I have suggested a fix?
