### ISSUE TITLE
URL in argument won't open playlist anymore

### ISSUE THREAD

**Issue by Albirew** [clsid2/mpc-hc#1710]
Before updating to Klite codec pack 16.x (should be around MPCHC 1.9.9.0), I had shortcut to MPCHC like this:
`"C:\Program Files (x86)\K-Lite Codec Pack\MPC-HC64\mpc-hc64.exe" https://github.com/iptv-org/iptv/raw/master/streams/is.m3u`
This way, it opened the m3u playlist in MPCHC and i was able to choose stream using the playlist.

Since 1.9.9.1 playlist won't load (MPCHC opens, freeze for 1mn, try to open file for 30s, then says "cannot read file") and i have to do the extra steps like copy url, "file > open file" and paste URL there.

I waited until Klite codec pack 17.0.0 (MPCHC 1.9.21.24) but it hasn't been fixed so I report.

**Comment by clsid2** [comment]
It opens the playlist correctly for me. It currently contains 3 streams, 2 of which are offline.

```
#EXTM3U
#EXTINF:-1 tvg-id="N4.is" status="online",N4 (720p)
https://live.tv.c.is/n4/index.m3u8
#EXTINF:-1 tvg-id="RUV2.is" status="error",RÚV 2 (720p)
https://iptv-all.lanesh4d0w.repl.co/iceland/ruv2
#EXTINF:-1 tvg-id="RUV.is" status="error",RÚV (360p)
https://iptv-all.lanesh4d0w.repl.co/iceland/ruv
```

**Comment by Albirew** [comment]
yes, the feed in itself have no problem, i can open it directly if downloaded beforehand, or i can manually open the feed url using the "open file" submenu.

what i was able to do until 1.9.9.0 was to put a specific shortcut on my desktop that opens MPCHC with this url (`"C:\path\to\mpc-hc64.exe" https://github.com/iptv-org/iptv/raw/master/streams/is.m3u`), wiwtch has stopped working for me.

is there a console view or logs to see what's happening on MPCHC side?

**Comment by Albirew** [comment]
adding /debug argument made it works, and now it's working even without...
1min freeze still exists but cannot reproduce the "cannot read file" anymore now.

**Comment by clsid2** [comment]
It might have hung while trying to play the first stream instead of issue being related to loading the playlist itself.
