### ISSUE TITLE
The subtitle does not appear immediately after changing to another one.

### ISSUE THREAD

**Issue by Sire-code** [clsid2/mpc-hc#1711]
Subtitle does not appear immediately after changing to another one on my second 4K monitor. This problem occurs only with my second 4K monitor.

**Comment by clsid2** [comment]
I assume it is an mkv file with embedded subtitles?

Does it appear if you seek back a little bit? If so, it is not a bug. Data for current subtitle is stored in the file in front of current position. It is not available if you switch track after the stored position, unless the file contains cue data to find it. Remux with MkvToolNix to fix the file.

**Comment by Sire-code** [comment]
Yes, it is an mkv file with embedded subtitles.
No, it does not but most of the time I should exit fullscreen mode so it can work I don't know exactly why.

**Comment by clsid2** [comment]
Update to latest version.

**Comment by Sire-code** [comment]
I did before opening the issue but unfortunately the same problem.

**Comment by clsid2** [comment]
Which video renderer?
Did you move the player from one monitor to another after opening the video? Does the problem also occur if you reload the video (CTRL+E) when being already on the 4K monitor?
What is the resolution of your first monitor?
Which subtitle formats? (e.g. ASS or PGS)

**Comment by Sire-code** [comment]
- It appears to me that it is MPC video renderer 
- No I always open the video on the 4K monitor because it causes problems if I open it on the first monitor and move it to the second.
- I tried it and the default subtitle appears but not the one I choose.
- 1080
- The problem always occurs with ASS but works fine with PGS.
