### ISSUE TITLE
Access Violation crash d3d9on12.dll

### ISSUE THREAD

**Issue by ej8989** [clsid2/mpc-hc#1712]
Cannot play any video file (mp4, mkv, avi, etc.)

Unexpected error
An error has occurred. MPC-HC will close now.
Exception:
ACCESS VIOLATION
Crashing module:
C:\Windows\SYSTEM32\d3d9on12.dll
Offset: 0x4CC3FEB16, Codebase: 0x7FF680E00000
The thread 6788 tried to read memory at address 0xFFFFFFFFFFFFFFFFFFFF

![2022-05-15 01_38_33-Unexpected error](https://user-images.githubusercontent.com/105561083/168442967-1a476af6-043c-47a1-98e5-63df6bda5c0e.png)

MPC-HC v1.9.21.19 
(also tried v1.9.21.2, same error/crash occurs)
Windows 10 21H2 19044.1706
Intel i5-12600 Alder-Lake CPU
Intel UHD Graphics 770 - Version: 30.0.101.1960

1. I already tried using older graphics drivers.
2. I already tried uninstalling and reinstalling MPC-HC, restarting the pc every install.
3. All video renderers produce the same error
4. Videos play when there are no drivers installed

**Comment by clsid2** [comment]
That is caused by a bug in latest Windows update [kb5011831](https://support.microsoft.com/en-us/topic/april-25-2022-kb5011831-os-builds-19042-1682-19043-1682-and-19044-1682-preview-fe4ff411-d25a-4185-aabb-8bc66e9dbb6c). Uninstall that update.
