### ISSUE TITLE
Limited range (16-235) media levels not expanded to 0-255 unless using madVR

### ISSUE THREAD

**Issue by jbruchon** [clsid2/mpc-hc#1716]
I [reported this issue to HandBrake](https://github.com/HandBrake/HandBrake/issues/2859#issuecomment-1131758626) and they said that it's a player issue. After some testing, I found that MPC-HC handles full range (0-255) media fine, but limited range (16-235) media is not expanded to 0-255 ranges unless using the madVR renderer. I've tested most of the renderers available (EVR CP, Sync, VMR9 renderless, etc) and the only renderer that doesn't exhibit this issue is madVR. I have the latest AMD video drivers, but the fact that switching to madVR fixes the issue makes me think the issue is with the other renderers, not with my video drivers or monitor or source files.

The files used for this testing are available here: http://core.nctritech.com/da/hb/issue_2859/

Full range source video w/histogram:
![image](https://user-images.githubusercontent.com/1005586/169359216-32aeeba1-1b0a-4d8c-a838-ca116f0c2e79.png)

Limited range encoded video w/histogram:
![image](https://user-images.githubusercontent.com/1005586/169359745-df6abb83-8b08-40c0-a2c3-b4939f9111b7.png)

**Comment by clsid2** [comment]
It is 100% a graphics driver bug. The reason it does not happen with MadVR is because that bypasses certain processing done by the driver.

**Comment by jbruchon** [comment]
Thank you for letting me know!

**Comment by DBotThePony** [comment]
EVR CP can also work properly if you specify color range as 16-235 in renderer settings (by opening context menu when already playing video), so this must be not videodriver issue, but something with MPC-HC or LAV Splitters themselves (including just default settings being wrong).

**Comment by DBotThePony** [comment]
I made an explaination here: https://github.com/Aleksoid1978/VideoRenderer/issues/51#issuecomment-1909363894

**Comment by clsid2** [comment]
No. Wrong. That setting is for renderer OUTPUT. Not related to the range of the video INPUT.
