### ISSUE TITLE
“Associate with video formats only” option not working correctly

### ISSUE THREAD

**Issue by przemo20** [clsid2/mpc-hc#1718]
-- Steps to reproduce --
1. Open MPC-HC.
2. Go to View → Options... → Player → Formats → File extensions and click on the “Clear all associations” option.
3. Click on the “Associate with video formats only” option.

-- Actual result --
No video file extensions are being checked in the list under the “File extensions” heading. This option seems to only mark the boxes under “Autoplay” heading.

-- Expected result --
Program should check all video related extensions from the list.

**Comment by clsid2** [comment]
Fixed
