### ISSUE TITLE
Remember Audio Track selection

### ISSUE THREAD

**Issue by quctex** [clsid2/mpc-hc#1719]
Add option to remember Audio Track under options -> player -> history.

Expected behavior:

- Open video file
- Select Audio Track (main menu Play -> Audio Track)
- Close video file
- Open video file again
- The same Audio Track should be automatically selected

Especially useful together with [remember subtitle selection #1291](https://github.com/clsid2/mpc-hc/issues/1291): if you prefer to choose original audio track in combination with translated subtitles, then, as a rule, you have to change both options.

**Comment by tealkami** [comment]
MPC-BE does save/remember subtitles+Audio selection, maybe clsid2 can copy the code from MPC-BE ? 
I use both MPC-HC & MPC-BE, this feature would be good in MPC-HC, too.

Sometimes you have videos without named tracks, so you can't use LAV Splitter to auto pick tracks.
