### ISSUE TITLE
Unexpected network requests when opening remote content

### ISSUE THREAD

**Issue by reallyuniquename** [clsid2/mpc-hc#1721]
I've been cleaning up an old system of mine and I've just realized a bunch of remote stuff that I open with MPC-HC ends up in Internet Explorer temporary files. At least partially.

Here is a quick example. File -> Open File/URL, paste `https://www.httpwatch.com/httpgallery/chunked/chunkedimage.aspx`. It responds with an image that MPC-HC should handle just fine.

Wait a bit till MPC-HC renders it. Now depending on your system check these folders including nested ones with random names for `chunkedimage[1].jpg`.

```
C:\Users\[username]\AppData\Local\Microsoft\Windows\INetCache\
C:\Users\[username]\AppData\Local\Microsoft\Windows\Temporary Internet Files\Content.IE5\
```

Another example, this one is trickier. You need to add to favorites an URL that responds with a generic error. For that I use Twitch channels that are currently offline. To speed things up edit your `Favorties\Files` and add something like `Name45=Test;0;0;https://www.twitch.tv/oddler`. Open MPC-HC, Favorites -> Test. Wait till youtube-dl says the channel is offline then notice MPC-HC says `Cannot render the file` in the status bar. There is no video stream, youtube-dl process is already terminated, what is it trying to render? Check the folders listed above, there will be `ie11-deprecated[1].htm`. That's Twitch correctly thinking that page is requested by Internet Explorer. And that file is what MPC-HC tries to render for some reason.

I launched a local HTTP server that logs request headers to see what's going on. Say, I open `http://localhost/any`. Here is requests by user agent.

> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36

OK, that's youtube-dl.

> User-Agent: MPC-HC

OK, that's MPC-HC.

>User-Agent: Lavf/59.15.100

OK, that's libavformat, part of MPC-HC.

> Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/8.0; .NET4.0C; .NET4.0E)

What's this? When I open something remote with MPC-HC the last thing I expect is that some component related to Internet Explorer will make that request.

Also similar things happen when you search or download subtitles. They all end up in IE temporary files, I've also seen some M3U playlists and other things there.

Why address this? First of all, security. Who knows how HTTP response is handled. Second, it breaks things since modern platforms do not act well if you use IE user agent (like Twitch in the example above). 

I'm guessing this is either a by-product of using WinInet for HTTP requests (hasn't that been deprecated in favor of WinHTTP long time ago?) or something related to implicit support for HTTP URLs in various file operations.

Any ideas?

**Comment by clsid2** [comment]
If YDL processing fails, then the player will try to open the URL directly.

When internal source filter fails to play an URL, then other source filters on the system will be tried, including "File Source (URL)" filter from Microsoft. That one caches content in IE cache.

If you think you can improve something, submit a patch.

**Comment by reallyuniquename** [comment]
Interesting! Is this tweakable on user side? Can this Microsoft filter be disabled? How come bits and pieces related to downloaded subtitles end up in IE cache too?

>When internal source filter fails to play an URL, then other source filters on the system will be tried

Why would internal filters fail to open a static image from URL?

> If YDL processing fails, then the player will try to open the URL directly.

I don't think it does that when I use `Open File/URL` dialog. It stops after yt-dl reports an error. Only happens for URLs from favorites.

**Comment by clsid2** [comment]
The fallback after YDL failure is skipped for a select few domains.

I don't really care if downloaded subs end up in IE cache. Sorry. I am not spending time on this issue.

**Comment by ale5000-git** [comment]
@reallyuniquename 
The real issue is this:
`When internal source filter fails to play an URL, then other source filters on the system will be tried, including "File Source (URL)" filter from Microsoft. That one caches content in IE cache.`

If you post an url where the internal source filter fails then it may be easier to fix (although I cannot be completely sure).

**Comment by reallyuniquename** [comment]
Could you please leave this open with `PatchFromAnotherDeveloperRequired` tag?

Security and incorrect responses to IE user agent is a concern. Filling up cache? Not so much. Honestly, it would be better to hard-fail than touch any IE component. 

@ale5000-git
>If you post an url where the internal source filter fails then it may be easier to fix (although I cannot be completely sure).

I did in the openning post. It appears internal filters do not support chunked encoding for HTTP requests. It's only part of the problem though.

**Comment by clsid2** [comment]
I am not going to leave open an issue in which nobody is interested.

You can block `File Source (URL)` in external filters.

There is no security issue.

**Comment by reallyuniquename** [comment]
Oh, I just had to add it first and only then block it. Although that still leaves MPC-HC with no internal support for any remote content that is served with chunked encoding. But then I should probably create a separate issue for that.

>I am not going to leave open an issue in which nobody is interested.

Well, it's been less than a day. Maybe give it some time?

**Comment by clsid2** [comment]
This is wrong place for reporting issues with the internal filters. Doing it at LAV Filters project is pointless as well, as I doubt its developer is interested in supporting http served images. You might have more luck with actual video content.
