### ISSUE TITLE
Can't move subtitles up or down (or left or right)?

### ISSUE THREAD

**Issue by Ksh1ft** [clsid2/mpc-hc#1724]
I used to be able to resize the subtitles on-the-fly with hotkeys and also lower or raise the position of the subtitles, but now it doesn't seem to work - on any of my videos with subtitles. Whether it's .srt or .ass or any other format - same goes for video files. I have tried everything, including reinstalling, double-checking hotkeys, Nothing has worked. Any help would be appreciated. Thank you.

**Comment by Ksh1ft** [comment]
I just want to add on the fact that I can still resize the subtitles but I have cannot change their vertical or horizontal positions.

**Comment by clsid2** [comment]
Update to latest development build.
