### ISSUE TITLE
Bug for FullscreenSeparateControls

### ISSUE THREAD

**Issue by chelpus** [clsid2/mpc-hc#1725]
The FullscreenSeparateControls mode only works for one video from the playlist. When switching to the next video, the image from the second monitor disappears, and the player itself freezes.
And if the program is closed and opened with the option of playing in full screen, the separation of the interface does not occur.

Режим FullscreenSeparateControls работает только для одного видео из плейлиста. Когда происходит переключение на следующее видео, изображение со второго монитора пропадает, а сам плеер зависает.
И если програму закрыть и открыть с параметром проигрывания на полный экран, разделение интерфейса не происходит.

**Comment by clsid2** [comment]
Disable exclusive fullscreen option. I am unable to fix the problem with fullscreen breaking with that on Windows 7.

**Comment by chelpus** [comment]
My OS is Windows 10, exclusive mode disabled in madvr, but the problem remains. Even if you open video on one monitor and press PgDn, then when you switch to the next video in the playlist, the video disappears, but sound work)) I apologize in advance if I misunderstood you.

**Comment by clsid2** [comment]
I can reproduce with MPCVR and madvr.

But don't expect a fix anytime soon. I don't have any motivation or desire to work on MPC-HC right now.

**Comment by chelpus** [comment]
I understand you perfectly. I myself support a free application for more than 10 years :)

**Comment by clsid2** [comment]
Fixed
