### ISSUE TITLE
bug with Ukrainian translation

### ISSUE THREAD

**Issue by uniss2209** [clsid2/mpc-hc#1727]
Version:            1.9.21.24 (1c7cdd24a)
The first picture shows the menu with Ukrainian translation. It indicates the items that are displayed in RUSSIAN! In the second picture, the corresponding part of the translation file with these lines, where you can see that the lines have a Ukrainian translation, but which is not displayed.
![2022-05-15 18_27_54](https://user-images.githubusercontent.com/24721923/170831512-23840f1e-052f-4800-8654-015b6f5e342a.png)
<img width="337" alt="2022-05-28 18_11_43" src="https://user-images.githubusercontent.com/24721923/170831479-22ce6d3d-af54-46dd-824c-2ff0200e90ec.png">

**Comment by xLn2** [comment]
It's static text based on your first installation language. If you did install mpc-hc with polish you can see these settings were polish. If Ukrainian translation has problem you can edit on transifex. Or if you want short way just change these text (preset actually) on view > Зиминити

Uninstall and install mpc-hc with desired language.

**Comment by uniss2209** [comment]
> Uninstall and install mpc-hc with desired language.

I'd rather rename them in mpc-hc64.ini )))
Thank you
