### ISSUE TITLE
Internal subtitles are not shown automatically

### ISSUE THREAD

**Issue by IsaacHub** [clsid2/mpc-hc#1728]
Videos with internal subtitles are not shown automatically when opening a video, always `No subtitles` is selected even though subtitles are enabled in settings. Video has only one subtitle. I have to press `S` to load the subtitle every time which is frustrating.

This issue doesn't occur with external `.srt` files.

MPC version: `1.9.21.2`
`Ignore embedded subtitles` is not checked in options dialog under Subtitles.

**Is this a known issue? Is there any workaround to force display the subtitle by default?**

![no_subtitle](https://user-images.githubusercontent.com/20126441/170922047-38575c19-4b59-4f12-be1d-14e119d8e767.png)
![mediainfo](https://user-images.githubusercontent.com/20126441/170922058-beaefd73-9be3-41d7-b2d4-1dcfa297ecbc.png)

**Comment by bibsp** [comment]
Because the sub is neither default nor forced.

**Comment by IsaacHub** [comment]
@Alp1821  Really ? To my eyes it says `Default : Yes` in the MediaInfo.

**Comment by bibsp** [comment]
Oops... In the first screenshot it is not mentioned. Didn't notice that.

**Comment by clsid2** [comment]
It depends on the configuration in the splitter:
Options > Internal Filters > Splitter

**Comment by IsaacHub** [comment]
Thanks, just added `eng` in the "Subtitles:" _( previously it was empty )_ hit "Apply", and restarted the player, and **it worked.**

![sub](https://user-images.githubusercontent.com/20126441/171029135-2a76f1da-4137-4c57-91a2-a89c108677b6.png)
