### ISSUE TITLE
Maintain movie proportions

### ISSUE THREAD

**Issue by MIGHZEST** [clsid2/mpc-hc#1729]
The horizontal image and the 16:9 ratio image are normally displayed, but the vertical image is not output properly. Is there a function to automatically adjust the video ratio according to the size of the player window?

How can I maintain the original ratio of the video?

**Comment by clsid2** [comment]
Please make a screenshot so I can see what you mean.

If it only happens with one specific video, then the video itself may have wrong aspect ratio.

These are default settings:
Menu > View > Video Frame > Touch Window From Inside
Menu > View > Video Frame > Aspect Ratio > Default

**Comment by MIGHZEST** [comment]
It's been solved. I didn't know and touched the settings
