### ISSUE TITLE
MPC-HC 64-bit does not remember size correctly

### ISSUE THREAD

**Issue by pipja** [clsid2/mpc-hc#173]
Windows 10 Pro 1909
MPC-HC v1.8.8.30

Seems to happen if you move the MPC window to a non-primary monitor, resize then close it. Upon opening a new video the size of the MPC window changes to 4:3 proportion. Does not happen if MPC window is on the primary monitor.

**Comment by clsid2** [comment]
Works correctly here on secondary monitor.

**Comment by CookiePLMonster** [comment]
This almost sounds like a DPI scaling issue? Maybe one of the monitors has different DPI than the other?

**Comment by pipja** [comment]
> This almost sounds like a DPI scaling issue? Maybe one of the monitors has different DPI than the other?

Sounds like it, my main monitor is 1080p and the side monitors are 1440p. Windows does its magic to keep the things look reasonably "same" size. Any suggestion on how to fix this? Or will this require changes to MPC-HC binary itself?

Thanks.

**Comment by CookiePLMonster** [comment]
> Any suggestion on how to fix this? Or will this require changes to MPC-HC binary itself?

You can try to nail this down further by setting both displays to 100% DPI. Sadly I can't direct you towards a specific option as I don't have multimonitor here, but I know it's possible to have different DPI on each monitor as I've been doing this elsewhere.

**Comment by pipja** [comment]
Thank you changing the non-primary monitors to 100% DPI scaling solved the issue. However, it's kinda sad that everything is tiny now. Maybe I'll just stick to use MPC-HC on the primary monitor...

**Comment by CookiePLMonster** [comment]
That's good info though, this kind of information should be enough to reliably reproduce that :) I assume @clsid2 has both his monitors at 100% DPI and thus he couldn't repro, so this is the missing piece of the puzzle.

**Comment by CookiePLMonster** [comment]
@pipja @clsid2: I had a chance to try MPC-HC on a multimonitor setup and I **did** reproduce the issue. I did things **exactly** as follows:

1. Setup I used has a primary monitor with 3840x1600 resolution, 200% DPI scaling, and a secondary monitor with 1920x1080 resolution, 100% DPI scaling.
2.  In Options I enabled _Remember last window position_ and _Remember last window size_.
3. I started MPC-HC on a primary monitor, resized it to a distinct shape and closed. Upon reopening, window was still sized like I left it. ✔️
4. I started MPC-HC again, moved it to a secondary monitor and resized it again. Upon reopening, **window size got reset to something which looks like a default, nowhere close to the shape I left it at.** ❌

Do note that it does not seem to happen when the setup is inverted (3840x1600, 100% DPI scaling + 1920x1080, 150% DPI scaling), which almost led me to saying I could not reproduce.

If I were to make an educated guess, I assume initial sizing does not take secondary monitor's DPI into the account properly and ended up with invalid dimensions (either too big or too small), causing them to be ignored. I say that without having looked at the code, so I may be more than wrong.

This has been tested on:

MPC-HC (64-bit)
---------------

Build information:
    Version:            1.8.8 (82efc58f7)
    Compiler:           MSVC v19.16.27034
    Build date:         Oct  3 2019 10:51:21

Operating system:
    Name:               Windows NT 10.0 (build 18362)
    Version:            10.0 (64-bit)

**Comment by adipose** [comment]
I could reproduce it.  Interestingly, it depends on the "active" monitor.  If I keep my mouse on the remembered monitor, the size is right. If I move it back to the primary monitor (dpi scaled), the size is reverse scaled (shrunken).

The application seems to assume the active monitor is the "base" DPI, and the remembered size will have to be scaled accordingly to fit on the destination monitor.

**Comment by adipose** [comment]
I think I have fixed this.

https://mega.nz/#!UcgyVYxS!QJef9qUMSBKU4Z2VZHDSXeH20i-AIRBKWvWW-n1SufI

**Comment by pipja** [comment]
Sweet :D
