### ISSUE TITLE
[Question/Feature Request] "Automatically search and download subtitles"

### ISSUE THREAD

**Issue by kdebro** [clsid2/mpc-hc#1731]
In Options > Subtitles > Misc > "Automatically search and download subtitles if none are found locally" I expect the app to automatically download the subtitles. However, what actually happens is that a menu pops up and I have to select which subtitle file I want to download and then click to confirm. Subtitles are not automatically downloaded

What I would like to do: If there is a subtitle searched online that matches my filename, then automatically download and use it without any popup or confirmation. If there is a similar subtitle filename to the video filename but no exact match, then give me the option to 1) automatically download and use the subtitle file with the highest Download number without confirmation,  2) open the download menu to select which subtitle manually (exactly like what happens now), or 3) skip it/do nothing

If an automatic download happens, then I want the option to automatically save the subtitle file as the same filename as the video file to directoryOfThisVideo/subtitles

**Comment by clsid2** [comment]
It actually does download automatically when an exact match based on file hash. When there is no exact match it shows you the dialog to choose the one you think is best.

This is the way it works, and no changes will be made. This topic has been discussed a million times already.

**Comment by kdebro** [comment]
i did not say by hash, i said by filename

**Comment by kdebro** [comment]
Maybe if the subtitles actually downloaded automatically, as the app says, then you wouldn't have had to discuss it "a million times"

**Comment by clsid2** [comment]
I am not implementing any new requests. Other developers can submit patches for improvements.

**Comment by kdebro** [comment]
That's fine you won't do it, but why close it? Now that you've closed, any future developer can't see that a patch might be useful
