### ISSUE TITLE
MPC+EVR(custom presenter) = Incorrect handling of clips with "Color range: full"

### ISSUE THREAD

**Issue by radpopl** [clsid2/mpc-hc#1732]
When playing mp4 clips with full color range ("Color range: full") the "Output range->0-255" does not work, more precisely it works the same as 16-235. As a result, the program cuts out the ranges 0-16 and 235-255 (shades of black and white disappear and the image has too much contrast).
Changing renderer from EVR(c.p.) to EVR helps temporarily.

This is best seen in the file below. Ranges 0-15 and 235-255 are washed out.

https://user-images.githubusercontent.com/11005341/172675005-9aec550c-2598-474a-bf86-5d7cfb438f9e.mp4

**Comment by clsid2** [comment]
Displays correctly here with EVR-CP and wrong with EVR.

I works for me, and I consider this to be a driver problem. So don't expect any fix.

This setting has effect:
NVIDIA control panel > Video > adjust video and color settings > with the video player settings

**Comment by radpopl** [comment]
I have a Radeon Vega (Ryzen 4650G) with newest drivers. I don't see any options in the driver.

In MPC-BE I can solve the problem by selecting the range 16-235 in the program options at EVR (cp).

**Comment by clsid2** [comment]
Changing the output range is a wrong solution. The range of the input video should be irrelevant for correct playback.

MPC-HC has same option here:
Menu > View > Renderer Settings > Output range

This is a better renderer than EVR:
https://github.com/Aleksoid1978/VideoRenderer

**Comment by radpopl** [comment]
In MPC-HE with EVR (c.p) this function with "Color range: full" clips does not work at all (both settings give the range 16-235). In MPC-BE, in turn, both settings work the opposite of what they should.
I am testing MPC VR for now and it works fine so far. Thanks!

**Comment by clsid2** [comment]
In 1.9.21.38 development build, the 16-235 output setting will have effect for full range input.

The output setting is for what your screen expects. It is unrelated to the input range of the video! So you should not need to change it based on the video that you are playing. If that is needed then there truly is a bug in your driver.

**Comment by radpopl** [comment]
I changed the renderer as recommended and that solved the problem (at least for now).

Edit:
Summary:
- EVR (c.p.) - working bad
- EVR - GOOD!
- MPC Video Renderer - GOOD!
- Sync Renderer - working bad (+ slow start)
- VMR (renderless & windowed) - GOOD!

**Comment by radpopl** [comment]
> In 1.9.21.38 development build, the 16-235 output setting will have effect for full range input.

I tested with version 1.9.20.56 (12.04) and it is still the same - each full range clip is treated as limited at EVR (CP) and the 0-255 / 16-235 switch does not change anything.
Changing to MPC Renderer solves the problem.

W10 64bit + Radeon 4650G + latest Adrenaline (default settings)
