### ISSUE TITLE
Yes/No dialog blocking video controls

### ISSUE THREAD

**Issue by PaulBags** [clsid2/mpc-hc#1733]
I tried to play a video. MPC-HC came up with some box about icons and wouldn't let me pause the video so I just closed everything and opened up MPC-HC without a video, but it didn't ask me again and I can't find anything about whatever it was asking about. I have no idea what I said no to.

Dialog boxes shouldn't block video controls. I'd also appreciate if someone could tell me what that thing was.

**Comment by clsid2** [comment]
Missing icon library file for file associations. It will now use player icon instead.

**Comment by PaulBags** [comment]
Ok, so how would I enable that now?

And what about the dialog bug, that just gets closed?

**Comment by clsid2** [comment]
I don't consider it a bug and I am not going to do anything about it.

If icons are wrong, re-apply the file associations or re-install the player.

**Comment by PaulBags** [comment]
Reinstall, lol, I'm uninstalling because you apparently don't care about or even understand the behaviour of your program.

**Comment by clsid2** [comment]
You are the idiot who clicks away stuff without reading.

The icon check is done asynchronously to avoid unwanted delay during start.
