### ISSUE TITLE
Subtitle download

### ISSUE THREAD

**Issue by ags1234** [clsid2/mpc-hc#1735]
Why does MPC-HC ask for an OpenSubtitles account to download, but other players download subtitles from that site just fine without user/pass? For example, PotPlayer.

**Comment by clsid2** [comment]
A login is required.

I don't care what PotPlayer does.

**Comment by ags1234** [comment]
How about VLC? It uses OpenSubtitles, too. Do you care about it?

**Comment by clsid2** [comment]
https://forum.opensubtitles.org/viewtopic.php?f=11&t=17110
