### ISSUE TITLE
Playlist docks to top when multiple players are open.

### ISSUE THREAD

**Issue by torporous** [clsid2/mpc-hc#1736]
I'm using v1.9.21.24 from k-lite codec pack on win10 x64.

I like to keep my playlist visible and undocked in a corner of the screen.  But when I open a second player, it opens with the playlist docked to the top of the window instead.

I have settings saved as a .ini and I can see that [ToolBars\Playlist] -> DockState changes while a player is open.
The usual values are 59419 for top dock, ...20 for left, 21 for right, 22 for bottom, and 23 for undocked. BUT when at least one player is open, the number becomes something invalid and random. I've seen it become 132928, 158464, 164976, and 1464176. In any case, and the second player instance fails to parse this gibberish number and falls back to docking the playlist to the top.

When no windows are open, the DockState value is set correctly to whatever state the last player closed was in.

This can be "solved" by setting the .ini security settings so the player cannot edit it, but then things like remembering file position don't work.  The problem also exists when settings aren't saved to .ini at all, it's just easier to see what's happening when they are.

**Comment by adipose** [comment]
Sounds like a bug.  This only happens with ini file? Not registry.

**Comment by torporous** [comment]
It still does it when settings are saved to the registry.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2779
