### ISSUE TITLE
Small improvement - Mouse click to pause/play

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#1738]
When video is playing in windowed mode. You click on any of the top menus and that particular menu expands.
Now if you click on blank area of video, then player should close the menus only. It should ignore mouse click to pause/play action at that situation.

**Comment by clsid2** [comment]
You can press Escape to close menus.

**Comment by bibsp** [comment]
This is not logical at all. This is very small issue.
Check the same thing in BE.
Hope someone will fix this in HC.

No further comment from my side in this topic, Bye.
