### ISSUE TITLE
option to choose whether to obey rotational metadata?

### ISSUE THREAD

**Issue by gartha1** [clsid2/mpc-hc#1739]
Hi

Is there any option to choose whether or not to obey rotational metadata?

e.g. 

C:\test1>"C:\Program Files\Combined Community Codec Pack 64bit\MPC\mpc-hc64.exe" "VID_20220615_071854175.mp4"
(version 1.7.8.162   build oct 2015)
does not obey rotational metadata

C:\test1>"c:\Program Files\MPC-HC\mpc-hc64.exe" "VID_20220615_071854175.mp4"
(very recent version). april 2022.
does obey rotational metadata

C:\test1>

ffplay has the option, where the default is -autorotate, which means obey rotational metadata, and there's an option for -noautorotate too.   ffplay  -autorotate VID_20220615_071854175.mp4  compared to ffplay  -noautorotate VID_20220615_071854175.mp4

**Comment by bibsp** [comment]
If you are asking this feature just because your video has wrong rotation metadata, then you can fix the video using Avidemux.
You can rotate it without re encoding. No quality loss. Just make sure video and audio option is selected to ***Copy***.

**Comment by gartha1** [comment]
I'm not asking just for that. I can "fix" it with ffmpeg copying the codecs as you do with avidemux, or I can use alt+numpad3, to keep rotating 90 degrees.  So there are those workarounds. 

But I would find a feature to choose whether or not to obey rotational metadata, like ffplay has, to be useful.

**Comment by clsid2** [comment]
There will not be such an option.

You can change the renderer to one that doesn't rotate, such as standard EVR.
