### ISSUE TITLE
Internal Audio Renderer not working after windows 1909 update

### ISSUE THREAD

**Issue by xav982** [clsid2/mpc-hc#174]
After I updated to windows 1909 build no: 18363.476, internal audio renderer stopped working. Other audio renderer options are working fine. Could you look into the issue?

Meanwhile is there any other audio renderer that supports audio playback speed without increasing the pitch?

**Comment by clsid2** [comment]
Re-install your sound driver. Windows might have messed something up during the update.
Also check if the correct audio device is selected in MPC-HC settings. Sometimes HDMI output device gets set as the default audio device in Windows after installing graphics driver.

**Comment by xav982** [comment]
Did what you said, still no audio when I use internal audio renderer

**Comment by clsid2** [comment]
It works here with 1909.

Make a screenshot of the status page:
Menu > Play > Filters > Internal Audio Renderer

**Comment by xav982** [comment]
Ah, thanks a lot, now it works .
Device was not selected in the Menu > Play > Filters > Internal Audio Renderer page. I was fiddling only in the playback options.
