### ISSUE TITLE
Subtitle duplicates when playback speed is changed

### ISSUE THREAD

**Issue by msamiluludag** [clsid2/mpc-hc#1741]
![image](https://user-images.githubusercontent.com/23271600/174266605-c34fb49c-fd11-4f30-a1cb-84372887e96f.png)

I think the problem is with webm or vtt.

I have attached the video for those who want to see the bug ↓↓↓

[video.zip](https://github.com/clsid2/mpc-hc/files/8926229/video.zip)

**Comment by xLn2** [comment]
I am using Internal Subtitle renderer and have no issue. Internal subtitle renderer is currently recommended one by mpc-hc maintainers. Also includes better compatibility to webvtt.

![image](https://user-images.githubusercontent.com/3073922/174287621-f97c2c26-cdeb-46fb-9783-095f80e29e2e.png)

`Options > Playback / Output > Subtitle Renderer`

Sorry for misunderstanding. Until the fixed version is available there is one shortcut of this problem. open video with no subtitles and change speed and then select subtitles.

**Comment by clsid2** [comment]
Fixed
