### ISSUE TITLE
Tooltips and Subtitle downloader has minor glicthes

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#1742]
Subtitle downloader has one issue that when you hover any file on the list and when it contains non latin letter it causes to show weird characters on tooltip. 
![image](https://user-images.githubusercontent.com/3073922/174291811-c72817e1-2ba5-4318-9a83-f7993efb61fc.png)
Kôkaku kidôtai:Ghost in the Shell. Solid State Society | `https://www.opensubtitles.org/en/download/nfo/3083795`

I did not test much but it probably effects Turkish, Greek, German, French and all other -non 26 letter latin- languages.

- Tooltip has issue with when media player Always **on top**, tooltips go background of media player and does not show up. It effects on Organize Favorites, Settings and subtitle downloader (file colums is fine, just Title(s) has problem).

![image](https://user-images.githubusercontent.com/3073922/174295929-4231cb64-2bf8-470c-bd1d-c1151172be7b.png)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1768
