### ISSUE TITLE
[Feature Request] Transparent Controls While in full Screen

### ISSUE THREAD

**Issue by SamRohod** [clsid2/mpc-hc#1744]
Add the ability to make the controls transparent while in full screen. Maybe with a transparency slider.

**Comment by DumZee** [comment]
I just thought of this, thinking how cool it would look:
![transparent_controls](https://user-images.githubusercontent.com/79674440/184649246-1de5a1ba-5014-40d2-92c6-7c138383a905.jpg)
... but seeing, how you have no plans to implement it made me sad.
