### ISSUE TITLE
Exiting fullscreen after changing video put half of the player offscreen

### ISSUE THREAD

**Issue by OshidaBCF** [clsid2/mpc-hc#1745]
While in full screen, if I change what video I'm watching (I'm using the "next file in folder" keys in the video, but selecting from folder do the same), exiting full screen will put the player window half out of the screen
https://user-images.githubusercontent.com/61458287/174457008-0ffc32c2-142d-4461-b196-eb4ba4ab1d40.mp4

It would be better if it would simply be full window like this
![image](https://user-images.githubusercontent.com/61458287/174457010-fd4c4603-8b18-4faf-a137-1028bab7c9b5.png)

it's annoying when you forgot which video you're watching..

**Comment by clsid2** [comment]
Then your settings are wrong.

Options > Playback > Zoom & Alignment > enable Auto-zoom

**Comment by OshidaBCF** [comment]
Ohhhhh thanks
