### ISSUE TITLE
Any way to watch playlist on remote and choose another track/video?

### ISSUE THREAD

**Issue by Barabba11** [clsid2/mpc-hc#1747]
Hi, sorry to open an issue if there is no one, I've tried different remotes on my android and tried also to access directly via web, but seams there is no way to watch playlist and select from there another file.. 
yes I can chose a file on the actaul folder to play, but this will destroy the playlist, so how can I just play the desidered track from the actual playlist? 
Thank you for your kind support!

**Comment by clsid2** [comment]
There is no way to view playlist using the web interface or remote control app.

I am also not adding new functionality.

Only possibility is to use next/previous button to skip through the files of the playlist in order.

**Comment by Barabba11** [comment]
thanks for quick reply, I'm sorry for this, I hope you may consider that in future, it's really helpful
