### ISSUE TITLE
Any way to make the player always start in windowed mode on desired resolution and desktop position.

### ISSUE THREAD

**Issue by wooshaq** [clsid2/mpc-hc#1748]
Basically I want the player to start at the lower left edge of the screen as a small rectangle (so the video must be rendered at desired constant resoltion) and while there is an option to remember video size and another one to remember window position I sometimes switch the video to fullscreen and when I close the video while it is like this next time I launch the video starts fullscreen as well. Is there a way to force the video to start on the window mode so it will always start on the lower left side of the screen regardless if I closed the movie while it was on fulscreen state or not?

**Comment by clsid2** [comment]
Easiest solution is to just exist fullscreen before closing.

Menu > Help > Command Line
That is parameter to specify fixed size. Not yet for position.

There already is another open issue for position parameter. I can't say if or when that will be added. I am not really motivated to work on new things right now.
