### ISSUE TITLE
Audio stops working when selecting new file

### ISSUE THREAD

**Issue by daniel-san-fried** [clsid2/mpc-hc#1749]
I have a bug where the audio always plays just for the first media file i click. When the window is open and playing a file and I click another file, it loads it but plays no audio. I have to close the player every time I want to watch or listen to another file. Does anybody have that?

**Comment by clsid2** [comment]
Change the audio renderer:
Options > Playback > Output

For someone else with same problem Default WaveOut Device  worked, or selecting the desired device directly.

Updating your sound driver might also fix it. The bug is outside of the player.
