### ISSUE TITLE
Update MPC-HC links

### ISSUE THREAD

**Issue by stdedos** [clsid2/mpc-hc#175]
Hello there,

1. Could it be that there will be some link on https://mpc-hc.org/ pointing to this repository?
2. Could "Help -> Webpage" point to, either the updated https://mpc-hc.org/, or here http://www.codecguide.com/changelogs_mpchc_lavfilters.htm, or to this repository instead? Finding either of the last two is "not straighforward"

**Comment by clsid2** [comment]
I don't have any control over the mpc-hc.org website.

**Comment by stdedos** [comment]
For [1], https://github.com/XhmikosR has last wrote messages on the site. Since I have seen him on reviews around mpc-hc (I don't know if it's this fork, another fork, or the main repo), I was wondering if your fork is somehow is been followed / helped by him.

For [2], I don't see why you couldn't change it to http://www.codecguide.com/changelogs_mpchc_lavfilters.htm, or to this repo https://github.com/clsid2/mpc-hc

**Comment by clsid2** [comment]
My builds already link to my own repository.

**Comment by stdedos** [comment]
I am not home right now to test; however, I think Help->Website goes to ~https://mpc-hc.org/~ _okay, that is not true - it goes to http://www.codecguide.com/_

I am installing/updating via https://codecguide.com/download_k-lite_codec_pack_standard.htm, if that makes any difference

**Comment by stdedos** [comment]
I was hoping that the website we were greeted would have more information _for MPC-HC itself_ (i.e. http://www.codecguide.com/changelogs_mpchc_lavfilters.htm), rather than the generic website
