### ISSUE TITLE
Commit 4358753 breaks dot as an argument

### ISSUE THREAD

**Issue by zoidbergthepopularone** [clsid2/mpc-hc#1754]
Commit 4358753522fa7b55272c440300b34517b124d936 breaks calling MPC-HC as `c:\path\to\mpc-hc\mpc.hc.exe . /play`: Before the commit, it started playing files in the current directory, after the commit it does nothing. As far as I can tell, the behavior is caused by the last change in mpc-hc/AppSettings.cpp - where the original code works:
```
                const_cast<CString&>(param) = ParseFileName(param);
                slFiles.AddTail(param);
```
the new one does not:
```
                CString strFile = ParseFileName(param);
                slFiles.AddTail(strFile);
```
I am not sure why, it seems like the new code should be just fine, but it isn't.

**Comment by clsid2** [comment]
I just tested, and that command line still works for me.

It loads files relative to MPC location, not from your current command line folder. If you use a batch file you can use `"%~dp0"` to get current folder path.

**Comment by zoidbergthepopularone** [comment]
Note that `.` should be a current working directory, not "directory where the executable resides". Interpreting it as such is certainly confusing and IMHO quite pointless - why would anyone want to load their media files from the player's directory?

Also, `%~dp0` is the directory in which the currently running script is located, not the current working directory. One would have to use `%cd%`. But in either case, these symbols will only work from a script. What if you don't want to use a script? The conventional interpretation of `.` would work from anywhere.

**Comment by clsid2** [comment]
The `.` is expanded to full path by `GetFullPathName` which is Windows API call. That part of the code is not touched by this commit.

**Comment by zoidbergthepopularone** [comment]
True. I can only assume that the code hasn't been working properly for a long time and the change to how `ParseFileName` gets called in the place shown above suddenly fixed that. You can easily verify it by trying the dot in the current MPC-HC, then change the two lines and try again - you will see that `.` resolves to different things in each case.

My point is about something different, though - specifically, that `.` should refer to the current working directory (as it used to do before the change above) rather than the directory of the executable. Preferably, the code should be properly fixed rather than just reverted, but if that is not feasible, an imperfect revert is better than keeping the current behavior.

**Comment by clsid2** [comment]
I have reverted the two lines.
