### ISSUE TITLE
Can you release the file from the process?

### ISSUE THREAD

**Issue by superuser7777** [clsid2/mpc-hc#1755]
First of all, I would like to thank the developers of MPC, the premier media player.

I use AHK to rename while zapping videos.
I'm having trouble with the close command terminating the video, but it doesn't release me from the process. MPC is running.

The AHK rename process succeeds when MPC is terminated.

**Comment by clsid2** [comment]
Renaming in Explorer works fine for me after closing a file.

I don't use AHK. Since it works in Explorer, I am not going to try it either.

If you are triggering the close from AHK, try adding a small delay before doing the rename.

**Comment by adipose** [comment]
Probably AHK chooses to lock the file when renaming, which isn't necessary.
