### ISSUE TITLE
Weird toolbar when I go fullscreen

### ISSUE THREAD

**Issue by Neekodesu** [clsid2/mpc-hc#1756]
I don't know why everytime I go into fullscreen my toolbar is weird and I don't like it. It changes to this: 
![image](https://user-images.githubusercontent.com/47283957/176602595-a772bf28-d483-4ef5-8579-8cca965c27bb.png)
Can someone tell me how to get it back to normal without resetting all my settings?

**Comment by clsid2** [comment]
Disable exclusive mode in madvr settings.
