### ISSUE TITLE
Multimonitor fullscreen subtitle rendering

### ISSUE THREAD

**Issue by Sp3EdeR** [clsid2/mpc-hc#1757]
Given: Two different size monitors (1920×1080 and 1280×1024) in use. Using DX9 subpic renderer, MPC video renderer. Using a pre-saved SRT subtitle.

Repro: Open a video with the MPC-HC window on the smaller monitor. Drag the window over to the larger monitor. Set the video window to full screen.

Issue: The subtitles rendered on the bottom of the screen are clipped, seemingly due to an insufficiently sized buffer.

Expected behaviour: The subtitles are rendered fully.

**Comment by Sp3EdeR** [comment]
Sample image when the issue is manifested:
![subpic_issue](https://user-images.githubusercontent.com/22780322/176741795-56f9692d-4827-4388-bbb4-da94ce6eee44.jpg)

**Comment by Sp3EdeR** [comment]
Analysis status:
* Setting the DesktopSizeBackBuffer to 1 does not affect this issue.
* The `CDX9SubPicAllocator::SetMaxTextureSize` function is called with the correct resolution when the window is resized.
* The `CRenderedTextSubtitle::Render` seems to use correct clipping boxes.

**Comment by clsid2** [comment]
Disable "Use Direct3D 11" in MPC VR.
Or use latest development build of MPC VR which support DX11 subs.

**Comment by Sp3EdeR** [comment]
Indeed, I needed to update the filters! For future reference for anyone with the same issue:
MPC VR source code: https://github.com/Aleksoid1978/VideoRenderer
MPC VR latest nightly builds: https://disk.yandex.ru/d/X0EVMKP4TcmnHQ
