### ISSUE TITLE
Dark Theme template for Saving thumbnails

### ISSUE THREAD

**Issue by jupiter104** [clsid2/mpc-hc#1758]
![thumbs](https://user-images.githubusercontent.com/24752210/176869663-5021cdb4-b033-4750-b925-8837eb49f8d3.jpg)

I really like the new dark theme of MPC-HC. However, when you save thumbnails, it still uses the older light theme template. I think it would be better if a new dark theme template was used, kind of like the photoshopped image above.

**Comment by adipose** [comment]
I can't say I am against it, but it seems to me tangential to theming.  It's just a format for a thumbnail document.  But if @clsid2 is ok with it, I guess I can make it use that format if you are currently using the dark theme, as that indicates a preference for "dark things."

**Comment by clsid2** [comment]
Yes, not really related to the player theme itself.

But I won't object against using a dark template for thumbs if dark theme is enabled.

**Comment by bibsp** [comment]
Sharing idea:
Instead of following theme, if you add a check box (Use dark theme) in thumbnail save dialogue box it will be better for user.

In this way if someone is using light theme and wants to save thumbnail in dark, he doesn't need to change the player theme to to this. During save thumbnail he can choose.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1782

I agree with @Alp1821 that an improvement would be to allow the user to choose rather than defaulting to the theme, but this is probably good enough.

**Comment by serious-raul** [comment]
Is this implemented? how does one use it?

**Comment by adipose** [comment]
Yes, I think so.  What part are you having trouble with?
