### ISSUE TITLE
File context menu

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#1759]
Previous versions had option to disable **Play with MPC-HC** from right click menu. But in recent 1.9.22.2 version **File(s)** option is replaced by **Playlist** or this is bugged. Now I can't  untick this.
![21](https://user-images.githubusercontent.com/98865389/177000790-4fac2f95-8693-40de-bd14-5ff6207d04f2.jpg)
![22](https://user-images.githubusercontent.com/98865389/177000791-30d1a5db-43aa-4ea5-9db5-589193da7f69.jpg)

My default player is always mpc-hc. I don't need or like this. Want to disable it.
![123](https://user-images.githubusercontent.com/98865389/177000671-6f6b6349-4593-4b87-8311-6eb9f8c82ff3.jpg)

If you have moved the setting to another place, tell me how can I disable. Or revert the change or give option to disable please.

**Comment by clsid2** [comment]
The default app should always be shown in the context menu.

I am **not** going to add any new options or change this one.

**Comment by bibsp** [comment]
> The default app should always be shown in the context menu.

Have you changed this option? Confirm it. Or just telling this is normal.
Your reply is confusing to me.

Coz I'm doubting that you haven't understood my issue.

**Comment by clsid2** [comment]
This is normal and intended.

**Comment by bibsp** [comment]
Maybe you can change the bold Play with MPC-HC text to Normal text.
Bold is so annoying. Consider this one atleast when you get free time later. 😭
Bye. Last msg.

**Comment by clsid2** [comment]
Explorer is making it bold because it is the default action. It does that for everything. Completely unrelated to the player.
