### ISSUE TITLE
Wrong timing of external subtitles when playing DVD

### ISSUE THREAD

**Issue by MikieMikie** [clsid2/mpc-hc#1760]
If you load external .srt subtitles when playing a DVD (Open DVD/BD...) the timing of the subtitles is wrong - they are shown about 800ms earlier.

How to reproduce:
Take a DVD, rip subtitles using SubtitleEdit and save into .srt. Play the DVD, show the original subpicture subtitles and also load the external .srt file. The external subtitles are shown significantly earlier than the corresponding original subpicture subtitles.

VLC media player does not suffer from this defect, so it seems to be a bug in mpc-hc.

**Comment by clsid2** [comment]
MPC depends on the DVD Navigator filter from Windows, and that provides inaccurate timing. To be specific there are big gaps between timestamp updates (400-500ms). I can not fix or change that.

Any subtitle issues are because of that. I am not interested in implementing any hacky workarounds.

**Comment by MikieMikie** [comment]
I see.
Are you sure this the core reason?
It seems to me that the low frequency of the timestamp update alone would result in an inconsistent timing, some subtitles would be shown more accurately than others according to the interference of the timestamp update frequency.
This however does not seem to be the case. The delay seems fixed throughout the whole DVD.
When I shift the timing manually using F2 to about 800ms, I do observe some timing imprecisions consistent with what you describe, but this is about 50ms, whis is fine.

**Comment by clsid2** [comment]
I would expect the subtitles to be a tiny bit too late (when wrong) instead of being too early.

You should look at the actual timestamps in the SRT file and compare that to when they are displayed. The problem might be in the ripping process due to audio delays or whatever.

**Comment by MikieMikie** [comment]
So I have done more research:

The timestamps in the .srt file are frame exact. As I explained earlier, the timings are exported directly from the subpicture stream of the .vob using SubtitleEdit. I have double checked them in DVDSubEdit, which displays the actual PTS (internal DVD stream timing in 90kHz master clock) and I also used VirtualDub to go over the .vob frame by frame and yes, the timings are frame exact.

VLC player has no problems showing the subtitles essentially in the correct frames.

Now it seems to me that in mpc-hc the DVD video stream is actually delayed somehow (and so the subtitles are displayed earlier).
I have tried to experiment with pausing the video at certain frames and get the frame number by ctrl+G. As a reference I took VirtualDub where you can examine the video frame by frame.
When playing just the .vob file the frame numbering seems mostly ok (differs by 2 from the reference) - and the subtitles work there. However, when playing the video as a whole 'DVD bundle', the frame numbering differs by around 30, and so the video stream is delayed by around 1sec.

Is this really caused by the DVD Navigator filter?

**Comment by clsid2** [comment]
Yes, seems fault of DVD navigator filter.

I can not help you.
