### ISSUE TITLE
File is not played

### ISSUE THREAD

**Issue by Cheeerd** [clsid2/mpc-hc#1761]
File: https://nyaa.ink/view/1545505
30 sec sample without audio and subtitle streams: https://disk.yandex.ru/d/WQkoDAqRwdwHqA
The MPC-HC opens it but does not play. But it can show preview on seekbar.
For example Windows Media Player plays it.

P.S. I didn't notice at first, but there is mentioned that to play the video with MPC-HC you should use K-Lite Codec Pack. If this is how it should be, then I'm sorry for opening this issue.

**Comment by bibsp** [comment]
@Cheeerd File is playing fine in standalone MPC-HC. I never used K-Lite Codec.
Note: My PC does not support HW decoding for AV1. In SW decoding it is playing fine.

**Comment by clsid2** [comment]
Disable hardware accelerated decoding for AV1.
Updating your graphics driver might also fix the problem.
