### ISSUE TITLE
MPEGTS audio

### ISSUE THREAD

**Issue by 89z** [clsid2/mpc-hc#1762]
Some mpegts files, are audio only:

~~~
Input #0, mpegts, from 'CBC_DOWNTON_ABBEY_S01E05':
  Duration: 00:49:39.93, start: 0.000000, bitrate: 200 kb/s
  Stream #0:0[0x12d]: Audio: aac (LC), 44100 Hz, stereo, fltp, 192 kb/s
~~~

However currently no mpegts audio is available:

https://github.com/clsid2/mpc-hc/blob/ad99c234c5e44c620a46f7872f7fd6aec5708348/src/mpc-hc/MediaFormats.cpp#L194-L220

**Comment by clsid2** [comment]
It is the way it is and nothing will be changed!

You can invent any new extension you want and add it yourself on the options page to "other audio" to make it load a an audio dub.

**Comment by 89z** [comment]
I guess `.aac` works. Its not really the same format, as its actually ADTS, but it matches the codec

**Comment by clsid2** [comment]
As I have already said before. You can use MkvToolNix to easily merge your audio and video files into a single file. Matroska container also has the advantage that seeking will work much better then with MPEGTS.

**Comment by 89z** [comment]
I think I will just use `.m4v` and `.m4a` for everything. None of the present audio options are MPEG-TS, so no matter what I choose its going to be wrong. At least this way, it matches what DASH uses, and even some HLS.
