### ISSUE TITLE
[Bug] There is sound but no video

### ISSUE THREAD

**Issue by MuhammetEminCakir** [clsid2/mpc-hc#1764]
The image does not work but sound works when I try to play a video that was interrupted after the screen was locked.
By the way, i recorded a part of the video where there is little speech, but there is sound. (I realized later, sorry)

https://user-images.githubusercontent.com/64583157/177202413-fe3cf4a7-4d43-4a8d-968e-0f497279204c.mp4

Media info:
[Stranger.Things.S04E03.720p.WEB.h264-KOGi.mkv.MediaInfo.txt](https://github.com/clsid2/mpc-hc/files/9041479/Stranger.Things.S04E03.720p.WEB.h264-KOGi.mkv.MediaInfo.txt)

**Comment by clsid2** [comment]
Press Ctrl+E to reload the video.

If video stops working after lock or sleep, it is fault of Windows or graphics driver. I can't fix it.
