### ISSUE TITLE
3d steroscopic video image

### ISSUE THREAD

**Issue by 55trucker** [clsid2/mpc-hc#1765]
Hello there: I'm making use of vs 1.9.21.2

there appears to be no capability for the program to play 3d video.
When attempting play such there is nothing in the Options that covers 3d stereo mode.

I do make use of MadVR which does have 3d capability but still there is nothing in the main program.

**Comment by clsid2** [comment]
3D video is handled by the renderer (madVR) and the decoder (LAV). The player does not do anything special with regard to 3D.

If you have only installed MPC-HC and madVR, then you are probably missing the H.264 MVC decoder plugin that is required by LAV for decoding 3D video. You can download that [HERE](https://files2.codecguide.com/intel_libmfxsw_2018r2.exe).

**Comment by 55trucker** [comment]
According to the Options/Internal Filters/Video decoder the H.264 MVC can only be activated if one is making use of an onboard Intel graphics GPU, seeing as I am using  a Radeon HDMI card the H.264 MVC is not possible.

**Comment by clsid2** [comment]
Wrong. H.264 MVC decoding works with ALL graphics cards. It uses software decoding by default. Intel GPU is only required when enabling hardware acceleration for MVC, which is not recommended anyway due to it being a bit buggy.

**Comment by 55trucker** [comment]
Ok, I'm only relaying to you what the pop-up notice states that appears when one moves their cursor over the tick box

**Comment by 55trucker** [comment]
*MVC acceleration is not supported on other graphics cards.*

**Comment by clsid2** [comment]
That notice applies only to hardware acceleration.

The plugin I linked to is required, even for software decoding.

**Comment by 55trucker** [comment]
I have dl'ed & installed the file you pointed to.......the program is still *not happy*

**Comment by 55trucker** [comment]
try this again......

**Comment by 55trucker** [comment]
still no *attached photo*

**Comment by 55trucker** [comment]
https://i.imgur.com/LgymVGI.jpg

this is how the image appears, I've seen this in the past....was never capable over getting the image to properly appears as a 3d image

**Comment by clsid2** [comment]
3D frame packed video output is not supported by Windows 7.

**Comment by 55trucker** [comment]
I'm not using W7, didn't say I was......

**Comment by clsid2** [comment]
If this is side-by-side (SBS) encoded video, then that isn't supported by madVR.

**Comment by 55trucker** [comment]
The video isn't side-by-side by default, the image should appear as two images overlaid each other. Odd, MPC-BE plays the 3d files with no issues, but, I've always leaned toward HC as my go-to player.
Here again, there's no provision within the HC player to setup the 3d image properties.

**Comment by 55trucker** [comment]
https://imgur.com/vhzVm0h

When viewed on a regular 2D screen the image should appear as above....this is MPC-BE, it has the built in provision to set up the 3d image properties. I had hoped that the current version of HC had the same capabilities.

**Comment by 55trucker** [comment]
https://i.imgur.com/vhzVm0h.jpg

**Comment by clsid2** [comment]
MPC-HC does not support that and never will. 
If you disable stereo 3D in madVR, then it should display only the left eye frame, instead of both. That will be proper 2D. Or just use any other renderer.

That image from MPC-BE looks terrible. You should not download 3D video if you have a regular 2D screen. Completely utterly pointless.

**Comment by 55trucker** [comment]
You're missing the point entirely, I HAVE a 3D 60" plasma screen, what you're seeing is my desktop monitor, HC.
Never assume
when one assumes one makes an *ass* of *u* & (in this case) not *me*
