### ISSUE TITLE
After sleep or hybernate, screen remains black when resuming paused video.

### ISSUE THREAD

**Issue by Dim-Tim-1963** [clsid2/mpc-hc#1766]
Subj.  To resume normal play, I switch to another video and then back to the paused one.
Ini file attached, with history deleted.

[mpc-hc64.ini.zip](https://github.com/clsid2/mpc-hc/files/9047075/mpc-hc64.ini.zip)

**Comment by clsid2** [comment]
Update to latest version.

Options > Advanced > ReloadAfterLongPause = 0

This will reload the video automatically. The problem itself is caused by bug in graphics driver.

**Comment by Dim-Tim-1963** [comment]
Thanks!
