### ISSUE TITLE
MPC Audio Renderer WASAPI Exlusive

### ISSUE THREAD

**Issue by pensionerik** [clsid2/mpc-hc#1769]
MPC Audio Renderer WASAPI Exlusive in this mode, strong dropped frames. This is especially noticeable with SVP 4 Pro. WASAPI Shared is fine. I want to output audio bypassing the Windows mixer. Is it possible? Topping DX3 Pro+ audio card. Same with Audient id14 MK2. 
Will there be ASIO driver support?
Thank you.

**Comment by clsid2** [comment]
ASIO will never be supported.

If it happens with SVP, it is likely that the problem is performance related (hardware interrupts). I do not have a solution for you.

**Comment by Aleksoid1978** [comment]
> MPC Audio Renderer WASAPI Exlusive in this mode, strong dropped frames. This is especially noticeable with SVP 4 Pro. WASAPI Shared is fine. I want to output audio bypassing the Windows mixer. Is it possible? Topping DX3 Pro+ audio card. Same with Audient id14 MK2. Will there be ASIO driver support? Thank you.

Show CPU load in this situation.
