### ISSUE TITLE
Subtitles do not follow the speed of the video

### ISSUE THREAD

**Issue by stdedos** [clsid2/mpc-hc#177]
Regardless of the video playback speed, subtitle speed is always constant i.e. x1

The only workaround is to go back and forth to x1 video speed

**Comment by clsid2** [comment]
This is a known bug.

It works correctly with embedded subtitles. So as a workaround you can use MkvToolNix to create a file with the subtitles embedded.

**Comment by THEtomaso** [comment]
> This is a known bug.

MPC-BE handles this correctly.
Judging from its changelog, it looks like it was fixed a long time ago, in v1.4.4.
Perhaps you could "borrow" a bit of code from them? :)

**Comment by clsid2** [comment]
Yes, I know. But there is much to to and very little free time to do it.

**Comment by adipose** [comment]
Do you have a sample file that's not working?

**Comment by lifegpc** [comment]
@adipose The file which use external subtitles have this bug, I can give you a sample file.
https://1drv.ms/u/s!Aoq8mAMlVv8UkztUpMXpy3oXbdDI?e=revoHP

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/374

**Comment by adipose** [comment]
> 
> 
> > This is a known bug.
> 
> MPC-BE handles this correctly.
> Judging from its changelog, it looks like it was fixed a long time ago, in v1.4.4.
> Perhaps you could "borrow" a bit of code from them? :)

It was actually fixed in 1.5.2:

"Correctly display external subtitles when changing playback speed."

Here's the commit:

r3551 | aleksoid | 2018-04-19 19:37:04 -0700 (Thu, 19 Apr 2018) | 1 line

Изменение : Добавлен "хак" для корректного отображения внешних субтитров при изменении скорости проигрывания, работает с EVR-CP/Sync.

**Comment by clsid2** [comment]
Fix ported
