### ISSUE TITLE
Default apps

### ISSUE THREAD

**Issue by zeref-dragneel** [clsid2/mpc-hc#1770]
I want to set MPC-HC as default app but I don't see MPC-HC in settings. But VLC can be set as the default application

<img src="https://i.imgur.com/HcjLarK.png" height="300" />

**Comment by adipose** [comment]
Did you install using k-lite or other method?

**Comment by bibsp** [comment]
This happens in standalone MPC-HC always.

Steps to reproduce:
uninstall MPC-HC and clean all registry using CCleaner. Then install MPC-HC again. Then you will find this.
I always thought it was normal for MPC-HC.

**You will get option in windows default app settings, once you associate all video and audio in MPC-HC settings. Option - formats.**

**Comment by bibsp** [comment]
Another similar behaviour:
After clean install MPC-HC, Right click on any video file. Open with option will not show MPC-HC. You have to browse executable file from desktop. But VLC shows its name in open with option.

I think MPC-HC by default doesn't register itself as a video player. So windows doesn't show it untill all file association.

As I said above, i always thought MPC-HC is built this way. So i never care about it.

**Comment by zeref-dragneel** [comment]
Thank you

**Comment by zeref-dragneel** [comment]
Thank you for the information

**Comment by Aleksoid1978** [comment]
MPC-HC register itself as video player - when you do file association in player.
