### ISSUE TITLE
Color issue with "enhance video renderer (custom presenter)"

### ISSUE THREAD

**Issue by Geobert** [clsid2/mpc-hc#1771]
Hi, 

I don't know what's wrong on my system but using any renderer gives me an orange Netflix logo where when using madVR, the Netflix logo is red as expected.

What setting should I look for?

Thanks for any help

**Comment by clsid2** [comment]
You are probably watching a HDR video.

The only renderers that are compatible are MadVR and [MPC Video Renderer](https://github.com/Aleksoid1978/VideoRenderer/releases).

**Comment by Geobert** [comment]
That is correct, thanks for the answer!
