### ISSUE TITLE
Status bar doesn't scale with desktop

### ISSUE THREAD

**Issue by ApeHound** [clsid2/mpc-hc#1773]
When dragging the window from a 1080p display (at 100% scaling) to a 2160p display (at 200% scaling) the status bar doesn't scale up - the rest of the UI does. Additionally, when opening MPC-HC on the 200% scaled 2160p screen, the status bar itself seems to be scaled but its text and speakers icon is still displayed at 100% scaling.

I've tried a few versions, and this scaling issue appears since 1.9.9.

100% scaling on 1080p monitor:
![mpc_hc_1080](https://user-images.githubusercontent.com/109384447/179299896-97900b7a-3bb5-4bed-b9e0-b8eaf1fc410b.jpg)

200% scaling on 2160p TV, windows was dragged fom the monitor:
![mpc_hc_2160p_dragged](https://user-images.githubusercontent.com/109384447/179299905-145e9a87-2945-4eee-8b4e-3b359e4fc92a.jpg)

200% scaling on 2160p TV, windows was opened on the 2160p screen:
![mpc_hc_2160p](https://user-images.githubusercontent.com/109384447/179299903-932fc3a3-40f3-49e8-914a-84f1658707ed.jpg)

**Comment by clsid2** [comment]
@adipose

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2128
