### ISSUE TITLE
MPC-HC stop window from moving on single click of video

### ISSUE THREAD

**Issue by plattze** [clsid2/mpc-hc#1774]
Sorry if this is obvious, but I can't figure out how to tell MPC-HC to NOT move the Window when I single click (and then move my mouse) on the video rendering during playback.  A single click appears to grab the window.  

Any tips?

**Comment by clsid2** [comment]
It drags only as long as you hold down the mouse button. If anything else happens, your mouse behavior is wrongly configured in Windows.

You can disable mouse click actions in player options.
Options > player > Keys

**Comment by plattze** [comment]
Yes thats right, how do I stop the window from being able to move when I click and drag?

I can see "Mouse Windowed" and "Left DblClk".  But I cant see any options for "Left" to disable this dragging behaviour?

**Comment by clsid2** [comment]
It seems there is no such option.

Why are you dragging the window? And how much?
