### ISSUE TITLE
Dropped characters in subtitles

### ISSUE THREAD

**Issue by i2324561w2** [clsid2/mpc-hc#1775]
The subs at seconds 8+17+19 drop some chars, both with XySubFilter and Internal Sub of MPC-HC, while VLC shows them correctly. Can you fix it, please?
[seconds= 8, 17, 19.zip](https://github.com/clsid2/mpc-hc/files/9126173/seconds.8.17.19.zip)

**Comment by clsid2** [comment]
I don't know how to fix that.

**Comment by adipose** [comment]
I have reproduced this in a small example.

https://mega.nz/file/RYITSSiA#rz_IzKxpziQXXcXqe-qvn9XDtcTxZuaP3gY8rhaupjE

Keys to problem:

1. Attached TTF font must be used (FRANKREACTION-REGULAR.ttf)
2. Use an SSA subtitles calling for that font.

```
Style: Default,Frank Reaction,52,&H00FFFFFF,&H000019FF,&H00020814,&H00000000,-1,0,0,0,100,100,0,0,1,2.5,0.5,2,70,70,44,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:10.07,Default,NTP,0,0,0,,{\fs24}ABCD EFG HIJK LMNOP QRS TUV WXYZ

```
Result is a weird case of a bunch of characters disappearing.  I haven't tried yet, but I suspect the libass renderer won't have an issue.  Maybe this font has bad metrics or funny metrics, I don't know. It's a very "scripty" font and Windows takes a long time to render it in the font preview window.

Note letters B-K just disappear...

![image](https://user-images.githubusercontent.com/3324395/185252421-57296849-00f7-423d-9c17-3ded7b72fc08.png)

**Comment by clsid2** [comment]
The lowercase letters all render normally. The original sample had issue with capital C.

If I change ScaleX/ScaleY to 98% or smaller, then `LMNOP` disappears. At 59% only the `A` is rendered. Super weird.

**Comment by adipose** [comment]
Yeah, I did notice that lowercase was working.  I thought maybe font metrics are not fitting or something...

**Comment by clsid2** [comment]
For this sub:
```
Dialogue: 0,0:00:00.00,0:00:05.00,Default,NTP,0,0,0,,{\fnFrank Reaction\fs24}A
Dialogue: 0,0:00:05.00,0:00:10.00,Default,NTP,0,0,0,,{\fnFrank Reaction\fs24}B
```
Then in `Rasterizer::ScanConvert()` for character B `mPathPoints` is 0.

Problem seems to be issue with the GDI functions in `CText::CreatePath()`.

**Comment by adipose** [comment]
Agreed, it can't seem to handle creating the path for many characters of this font.

1. Font fails many font validator tests due to "overlapping contours"
2. I used Fontlab to simplify the curves on A-Z, and it works, now.  But it's a different font, so I don't really see how that helps anyone unless they want to replace the font in the attachment...I can send it to @i2324561w2
3. MFC is able to draw this font fine, but at 1500 point font it may not, I didn't try that.

**Comment by clsid2** [comment]
Maybe we should update and fix the libass codepath, so users can choose to use that when ISR fails.

**Comment by adipose** [comment]
Probably so, but just now I tried defining the preprocessor def, and I think it took effect--and still failed on that font.

**Comment by clsid2** [comment]
The original file renders ok with [libass xy-subfilter](https://github.com/Masaiki/xy-VSFilter/releases). Note: test with embedded subs, as it may not load for external ones.

The current libass code in MPC-HC was a bit broken last time I played around with it.
