### ISSUE TITLE
[Request] Explorer Thumbnail Preview

### ISSUE THREAD

**Issue by ardissaps** [clsid2/mpc-hc#1776]

**Comment by clsid2** [comment]
That is not the job of a player.

**Comment by ardissaps** [comment]
Well, some pdf reader can preview pdf thumbnail on explorer.

**Comment by clsid2** [comment]
You can use [K-Lite](http://codecguide.com/download_kl.htm) which contains MPC-HC and a plugin for thumbnails.

**Comment by ardissaps** [comment]
> You can use [K-Lite](http://codecguide.com/download_kl.htm) which contains MPC-HC and a plugin for thumbnails.

does the included mpc_hc same as here? or old one?

**Comment by clsid2** [comment]
Newest one
