### ISSUE TITLE
cant play yotube in browser, when i playing vidio on mpc hc (HELP)

### ISSUE THREAD

**Issue by asagichan** [clsid2/mpc-hc#1778]
cant play yotube in browser (audio renderer error. please restart your computer), when i playing vidio on mpc hc. i must close the mpc hc to play youtube. 

before i reinstall mpc hc its normal i can play both yotube in browser & mpc hc playing other video same time.

error in youtube browser only occurred with mpc hc player

how i can fix this? HELP

**Comment by clsid2** [comment]
This is not the fault of the player.

If you have enabled exclusive mode in the audio renderer settings, then disable that. Exclusive mode means that only one application can output audio.

You can change renderer here:
Options > Playback > Output

If that does not help you need to update/re-install your sound driver.
