### ISSUE TITLE
Remove adverts from subtitles

### ISSUE THREAD

**Issue by FreddyZar** [clsid2/mpc-hc#178]
See you guys are taking suggestions so figure I'd try my luck with something that's been annoying me for years.

When a move auto downloads subtitles from OpenSubtitles it has adverts build into the first and last lines always. 
![image](https://user-images.githubusercontent.com/32035834/70861520-b3e4cc80-1f37-11ea-9138-b85073678f47.png)
![image](https://user-images.githubusercontent.com/32035834/70861525-be9f6180-1f37-11ea-854d-7aeefe3550ab.png)

So my suggestion is a tick box on the Subtitles tab to not display these 2 lines. Or if you want to be fancy a regex filter to block strings that contain 'www.OpenSubtitles.org'
![image](https://user-images.githubusercontent.com/32035834/70861509-957ed100-1f37-11ea-9c27-6086f208cfd3.png)

**Comment by clsid2** [comment]
I am not implementing this. You can't expect them to provide a free service without advertising.

You can store the subtitle file and remove it with a text editor.
