### ISSUE TITLE
Some subtitles cause huge amount of lag

### ISSUE THREAD

**Issue by OshidaBCF** [clsid2/mpc-hc#1780]
It seem that subtitles that use some "animation" like scaling, rotating, ect, cause an enormous amount of lag.

I don't know if that could be fixed with some settings, or it's literally the subtitle fault if it happen and cannot be fixed.

**Comment by clsid2** [comment]
You need a faster computer.

To improve performance at cost of quality:
Options > Subtitles
Lower maximum texture resolution. And/or disable animation or lower the animation rate.

**Comment by OshidaBCF** [comment]
i consider already having a really good pc, but i'll try to lower the max res, any way to know what res the subtitles is?

**Comment by clsid2** [comment]
It is the size at which the subtitle is rendered. That is then scaled to final size. The "size" if the subtitle itself is irrelevant.

**Comment by OshidaBCF** [comment]
i see.
Thanks
