### ISSUE TITLE
Supporting non-standard file types - willing to contribute myself

### ISSUE THREAD

**Issue by DasBnow** [clsid2/mpc-hc#1781]
Hi, first of all I wanted to say THANK YOU for maintaining this project. I really appreciate the work you have put into it.

I have a small annoyance, and while I don't expect you to fix it for me, I was wondering if maybe you can point me to where in the code I should be looking. I have very limited experience with C++, but if it's a straightforward fix (as I imagine it might be) then maybe I can have a go.

I want to use the playlist and navigation features (e.g. PgDn for "next file in folder"), but with files that have non-standard extensions yet are nonetheless perfectly valid video files. So for example the file name might be "Video.test" but the file is actually an .mp4 file.
These files are associated with MPC-HC in Windows, and they open just fine when I click them from Windows Explorer. But if I open the first file in a folder full of them, then MPC-HC does not respond to the PgDn or PgUp commands, nor does it allow me to add the files to a playlist. Regardless of whether I try to add them individually or add the entire folder.

I figure I should be able to configure my own list of extensions I want MPC-HC to recognize, or it should read from the associated file types in Windows. This would also help future-proofing the software, as new file types are sure to arise in the future. This is already happening with images - extensions such as .webp or .heic are very common now, not to mention all kinds of manufacturer-specific raw formats such as .orf.

Again, happy to have a stab at this myself if you can point me in the right direction. Thanks in advance!

**Comment by clsid2** [comment]
You can add extensions here:
Options > Player > Formats > Other

MPC-HC is a video player. Not an image viewer! Use IrfanView or some other specialized image viewer.

**Comment by DasBnow** [comment]
Thanks! That was embarrasingly simple 🙈 Problem solved!

I'm not using it for image files. These are video files, just with a different extension.
