### ISSUE TITLE
Subtitles not showing

### ISSUE THREAD

**Issue by Thornburgh** [clsid2/mpc-hc#1783]
I'm using the latest stable version and noticed an issue not present in older versions.  When I turn on subtitles for a file that has them embedded (my default is off), the subtitles don't appear full screen until I switch to windowed mode and back to fullscreen.  Then they work.  In the past, they worked right away in fullscreen.

**Comment by Thornburgh** [comment]
I was able to fix this by unchecking "position subtitles relative to the video frame."  Don't know what changed to cause that.  The videos in question are 1080p scaled up to 4k on my TV.

**Comment by clsid2** [comment]
Which type of subtitles were affected? (SRT/PGS/ASS)
Which video renderer are you using? (options>playback>output)
Are you launching in fullscreen?

**Comment by Thornburgh** [comment]
Thanks.  I don't know the answer to SRT/PGS/ASS.  Subs were embedded into mp4 files by a YouTube downloader.  This is what MPC-HC info says about format: Subtitle: UTF-8 [S: SubtitleHandler [eng] (tx3g)]

I'm using EVR-CP, which says it supports subtitles; also using Internal Subtitle Renderer

Launching in fullscreen (screen is 4k while video is 1080p)

**Comment by clsid2** [comment]
Fixed in 1.9.22.18

**Comment by Thornburgh** [comment]
Thanks!

On Jul 25, 2022, at 7:33 AM, clsid2 ***@***.***> wrote:

﻿
Fixed in 1.9.22.18
