### ISSUE TITLE
Player hangs while press seek wile playing file that is downloading

### ISSUE THREAD

**Issue by Sparklingx** [clsid2/mpc-hc#1784]
So MPV does not have this problem. 
I am downloading something with torrent( in sequential order, so it downloads from start to finish)  while downloading I  play the video but if I seek(press right arrow key or with mouse)  the player hangs after quite  sometime it starts working normally and no problem with seeking.

**Comment by clsid2** [comment]
Make your torrent app prioritize downloading the beginning and end of file. Some video file formats contain important data at the end (such as seek index).

**Comment by xLn2** [comment]
I did not test to jump incompleted part of video file but there is a seek preview issues. When you hover mouse on seekbar where video files are not downloaded yet (i.e file is 10percent downloaded both beginning and ending and you hover on the middle of the seekbar) video player hangs. Maybe preview frame seeking is forcing itself too much for 0 bytes (probably).

**Comment by clsid2** [comment]
You can't expect proper functionality when parsing the random data of incomplete parts. So disable seek preview or don't hover above incomplete parts.

**Comment by Sparklingx** [comment]
> Make your torrent app prioritize downloading the beginning and end of file. Some video file formats contain important data at the end (such as seek index).

I am already doing it. I know what I am doing. as I said  mpv do not have this problem but MPC has.  lets say 30% downloaded(from the beginning sequentially)  if I play the file and  press the right arrow for a 10s seek the player hangs

**Comment by clsid2** [comment]
There is nothing I can do about it.

I don't have any hanging issues with partial files with uTorrent.

**Comment by Sparklingx** [comment]
> There is nothing I can do about it.
> 
> I don't have any hanging issues with partial files with uTorrent.

Did you press the right arrow key to seek? or seek using mouse?  I am going to check utorrent

**Comment by Sparklingx** [comment]
> There is nothing I can do about it.
> 
> I don't have any hanging issues with partial files with uTorrent.


Looks like its the problem of qbittorrent!!!  just checked transmission  and  its working fine on files downloaded by transmission
