### ISSUE TITLE
Glitch in video file

### ISSUE THREAD

**Issue by CNeko** [clsid2/mpc-hc#1786]
I'm not sure if it's eligible to post here. I just stumbled upon some glitch fragment in There.Is.No.Evil.2020.1080p.BluRay.x264-USURY. I've clipped it into a tiny file (no sound, just video). "Action" starts in about 23 sec from the start. 
https://drive.google.com/file/d/1E4x4DRh2sJkUtrtuasB7gngvWsMyE20b/view?usp=sharing
It plays correctly in VLC and MPV, but not in MPC-HC. 

MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.22 (734896a23)
    Compiler:           MSVC v19.29.30145
    Build date:         Jun 26 2022

LAV Filters:
    LAV Splitter:       0.76.1.0
    LAV Video:          0.76.1.0
    LAV Audio:          0.76.1.0
    FFmpeg compiler:    MinGW-w64 GCC 11.3.0

Operating system:
    Name:               Windows 7 (Service Pack 1)
    Version:            6.1.7601 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
    GPU:                NVIDIA GeForce GTX 760 (driver version: 27.21.14.6192)

**Comment by clsid2** [comment]
I don't see any glitch.

**Comment by bibsp** [comment]
Same here. **No glitch**

**Comment by CNeko** [comment]
Looks like I hesitated to upload this for a reason. Such kind of issues are always tricky. I tried to switch renderer from madVR to another one from the list of available options: 
![](https://i.ibb.co/t2qY6FJ/renderer.png)

And with Video Mixing Renderer 9 and 7 the file was played perfectly.

All other options got two scenes mixed up (if show anything at all):
![](https://i.ibb.co/qNZ4Ssf/katto-mkv-snapshot-00-38-154.jpg)

**Comment by clsid2** [comment]
Probably a graphics driver issue with hardware accelerated decoding. Those other two old renderers are not compatible with DXVA2 Native, so the decoder will fall back to software decoding.

So either disable hardware decoding in the video decoder options, or try a different driver version.

**Comment by CNeko** [comment]
Yep, it works. I guess the problem here is the age of videocard :) Thanks for advice!

**Comment by clsid2** [comment]
You could try if it works better with "CUVID" as hardware decoder choice.

**Comment by CNeko** [comment]
Yep, CUVID works too. At least I have a little bit of acceleration here :)
