### ISSUE TITLE
YouTube URLs added to playlist or opened via API don't get processed by yt-dlp

### ISSUE THREAD

**Issue by SiliconExarch** [clsid2/mpc-hc#1788]
As the title says, if an external application tries to open or enqueue a YouTube URL using MPC API commands this bypasses yt-dlp, resulting in a **Cannot render the file** error. 

Following this, if I open the playlist bar within MPC, copy the new playlist entry to the clipboard and paste it into the Open File/URL box then the video opens successfully, proving that the URL has been properly passed through the API, however yt-dlp isn't called in the same way as it would be when opening the URL manually.

I'm not sure if this is something which could potentially be resolved as part of https://github.com/clsid2/mpc-hc/issues/1572 in which case I'm happy for you to merge this issue into that one.

**Comment by clsid2** [comment]
Fixed
