### ISSUE TITLE
Supporting translations of new features going forward

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#179]
@clsid2 

It seems the original project was translated via site "transifex."  The scripts don't seem to have any code specific to that site, though.  And the translations are mostly >98%, but at times I add a new text for a button, etc.  The "manual search" feature I added uses a new string "Search" which surprisingly was never needed before.

Manually editing the translation files isn't too bad, but if we hope for outside translation support, using transifex once again may be worth considering, and building some scripts to automate the builds/check the po files into the source tree might be worthwhile.

What do you think?

In anticipation of this I created an account on transifex and wrote python scripts to upload the current translation files.  The account requires an api key or password to work with the script, so we would need to solve that (maybe a read-only API key is possible, or else the "sync" step can be offline).  Transifex claims to have an "unlimited free" account for open source projects--right now I am using demo as it wouldn't allow me to convert it for some reason.

If you are interested in enabling this and asking for translation help, let me know and I can work on it.  And perhaps it's time to consider creating an alternate website so people know where to look for support.

**Comment by clsid2** [comment]
If you want to set things up and manage it, then go ahead ;)
We can open an issue here with a link to the Transifex page and instructions for translating. I can put a translation request in the changelog of next release.

In the past one of the admins would sync locally once in a while and then commit the changes.

**Comment by adipose** [comment]
Sounds good--I may regret it, but avoiding new strings is difficult when adding new options.  A configuration page for the theme might be worth doing, too.

**Comment by adipose** [comment]
I put in a PR to do the initial import.  Transifex seems to work pretty well with github.  For now I have it doing commits to a branch called transifex on my fork.  It can also do PRs, but it does one per translation, which is a lot of PRs for the initial import.

One thing that was lost was the original translator names.  It seems those are populated by Transifex, so if the translators come back, their name will reappear if they do a translation.  Not sure we care, but we can always check history to find those names.

**Comment by clsid2** [comment]
Can you open a new issue with translation instructions and a link to the new Transifex page?
