### ISSUE TITLE
Audio track switching leads to reduced and disabled audio

### ISSUE THREAD

**Issue by HypuTrainu** [clsid2/mpc-hc#1790]
Video: MPEG4 Video (H264) 1920x1080 23.976fps [V: h264 high L4.1, yuv420p, 1920x1080 
Audio: PCM 48000Hz stereo 1536kbps [A: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s
Audio: DTS 48000Hz 6ch 4608kbps [A: dts-hd ma, 48000 Hz, 5.1]

Switching between the two audio tracks while playing leads to significantly reduced volume the first switch, and the audio going away totally on the second switch. Happens across different titles with the same audio track formats (releases from the same company). All settings on installation default.

Issue does not exist on other players such as VLC and older CCCP versions of MPC-HC (on different PC).

**Comment by clsid2** [comment]
It is not the fault of the player.

Enable the mixer in the audio decoder settings. Set center mix level to 1.0.

**Comment by clsid2** [comment]
Also try if disabling "clipping protection" in the audio decoder helps.

if it does, can you give a link to one of those problematic videos?

**Comment by HypuTrainu** [comment]
> Also try if disabling "clipping protection" in the audio decoder helps.
> 
> if it does, can you give a link to one of those problematic videos?

Unfortunately, neither the center mix level change nor the disabling of clipping protection work. I have found that it works correctly with the original bluray, but does not when it is ripped into mkv.

Here's a [clip](https://www.mediafire.com/file/8pyc9shr80gm5qx/test01.mkv/file). Both the full length rip and the clip suffer from the same problem.

**Comment by clsid2** [comment]
The first track is uncompressed PCM audio, which doesn't need a decoder.

You can fix the missing audio by enabling "remove audio decoder on audio stream switch" option in the splitter.

Volume seems fine here on second track. I am downmixing to stereo.

**Comment by HypuTrainu** [comment]
That resets the volume to 100% with every switch though. I get that volume control should ideally be done on hardware, but it's still a slight inconvenience. No idea what causes the audio to be lost, here's hoping it could be resolved in the future. 

Thanks for the help and input even when the problem might not fall on the player.

**Comment by bibsp** [comment]
I have slightly different problem with this video.
1st time audio switch - no problem.
2nd time audio switch - video frame freezed. No audio also. Progress bar at the end of the video. Toolbar showing paused.

**Comment by clsid2** [comment]
I found a fix for the volume problem. Try 1.9.22.25 development build when it is available.
