### ISSUE TITLE
AC3 Filter integration 

### ISSUE THREAD

**Issue by Sparklingx** [clsid2/mpc-hc#1795]
Is Ac3 filter now integrated with MPC-HQ?  Because if I  open ac3 filter from MPC  right click > Filters > AC3 filter  I can see its working  but if I open the AC3 filter from my pc programs I can see its dull like stone(it looks like this when its not working) 
But I am sure it is working. Also how can I show it in right side of task bar when I paly video?

![dJqoKFbN](https://user-images.githubusercontent.com/85538352/182364435-528becc0-203a-40a6-8f8d-fe203da286e2.png)

**Comment by clsid2** [comment]
AC3Filter is not included with MPC-HC. It must have been installed by something else. If you do not want to use it, then disable PCM on its system tab, or uninstall it.

It has an option for showing system tray icon.
It only shows volume animation when you open the setting though an active instance.

**Comment by Sparklingx** [comment]
> It must have been installed by something else

Not by something else  I  installed AC3 Filter and  use it all the time when watching movies because of the DRC control feature( I cranked up the DRC level to full)  and downmixing to 2.0. And it works just so perfectly.

**Comment by clsid2** [comment]
The player also has volume normalization option in its audio switcher, and mixer settings in the audio decoder.

**Comment by Sparklingx** [comment]
> The player also has volume normalization option in its audio switcher, and mixer settings in the audio decoder.

Which doesnt work well like AC3-Filter. Volume normalization is a very very bad Idea  it works very bad specially during  "very quite to boom"  you can tell that there is some kind of filtering is going on . Just increase the DRC in ac3filter and keep other thinks as it is  you wont even realise that there is any filtering going on
