### ISSUE TITLE
Make the UI of Dark mode to Match with Windows 11 (Like in Light Mode)

### ISSUE THREAD

**Issue by Adish08** [clsid2/mpc-hc#1796]
White mod menu has rounded corners...

![image](https://user-images.githubusercontent.com/69076256/182591782-f5686870-3858-4643-87a8-f3fcbd064764.png)

But,
Dark one has no rounded corners...

![image](https://user-images.githubusercontent.com/69076256/182591950-af3fdd1f-0b59-45e4-961d-c06cbe476bba.png)

**Comment by DRSDavidSoft** [comment]
This is same as #2141 (even though this one was created sooner)
