### ISSUE TITLE
MPC is not showing the correct font style

### ISSUE THREAD

**Issue by Bamboozul** [clsid2/mpc-hc#1799]
MPC-HC is not showing the correct style (I think it's not loaded at all) for this font "A Negaar" when using "Internal Subtitle Render' when you launch the video for the first time.

The solution is to change the font every time I launch the video & change it back to ''A Negaar''

### **Some screenshots:-**

1. Correct style using "mpv":
Version: mpv-x86_64-20220731-git-284fecc

![mpv-x86_64-20220731-git-284fecc](https://user-images.githubusercontent.com/101983929/182615461-abf8fce3-88b1-4cfa-932c-4ffe76f97f0c.png)

2. Correct style using MPC v1.9.22 with XySubFilter:
[XySubFilter with libass version 20220516](https://github.com/Masaiki/xy-VSFilter/releases/tag/20220516)

![MPC v1 9 22 with XySubFilter](https://user-images.githubusercontent.com/101983929/182616123-7935123f-4a25-4e20-8a8b-e93e921ae6a5.png)

3. Incorrect style using MPC v1.9.22 with Internal Subtitle Render:

![MPC v1 9 22 with internal subtitle render](https://user-images.githubusercontent.com/101983929/182616529-01b6cca7-e145-4b41-8714-ab8791605d30.png)

Font & Sub File:
[Font & Sub File.zip](https://github.com/clsid2/mpc-hc/files/9251619/Font.Sub.File.zip)

**Comment by clsid2** [comment]
Fixed

**Comment by astiob** [comment]
This is a bug in the specific subtitle file and in libass. Note how all of the provided screenshots use libass. (The provided “XySubFilter” screenshot uses not XySubFilter at all but rather “XySubFilter with libass”. Talk about naming things.)

ASS styles explicitly define their desired font encoding: see the `Encoding` field. There’s also a dedicated override tag for it: `\fe`. And the style in this particular subtitle file at the affected time (0:03:03, as reported in the MPC-BE issue) explicitly defines Encoding=0, which is [`ANSI_CHARSET`](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-wmf/0d0b32ac-a836-4bd2-a112-b6000a1b4fc9), or the “English character set”. `ARABIC_CHARSET` would be 178. The named font does not contain any Latin letters, only Arabic, so Windows rejects it when it is asked for an English font and instead selects the system-default English font, Arial (which happens to also contain Arabic). To use the named font, the style should specify `Encoding=178` or `Encoding=1` (`DEFAULT_CHARSET`, as used in other styles in the same file).

To recap: the provided subtitle sample explicitly asks this font not to be used.

The style’s declared `Encoding` goes directly into `lfCharSet`:
https://github.com/clsid2/mpc-hc/blob/714321a83d33a80019ec89be0d4a347aeeac4e00/src/Subtitles/STS.cpp#L3814-L3816
But now, the supposed fix overwrites this field with a constant value of `DEFAULT_CHARSET`.

This has two effects:

* Despite Microsoft’s documentation saying “DEFAULT_CHARSET is set to a value based on the current system locale. For example, when the system locale is English (United States), it is set as ANSI_CHARSET”, it appears that passing `DEFAULT_CHARSET` to `CreateFontIndirect` simply turns off charset-based font filtering entirely. So in this sense, the committed fix seems to work as intended and like current libass.

* Unfortunately, this breaks other real subtitle files. Here’s one genuine example of a subtitle stream that names a non-Latin font and `Encoding=0` and renders correctly _only_ when the font fails to be selected and Arial is used instead. And it isn’t just different-font-but-still-perfectly-readable as the sample OP posted here; it’s using this to draw a background box for a sign translation. With the named font actually selected (as in current MPC-HC and libass*), it looks like a complete mess:
    <img width="320" alt="Various boxes and pieces of text overlap in a disorganized way. Parts of the text are hard to read." src="https://user-images.githubusercontent.com/515193/201436797-15cac897-9fea-4c32-948b-be381e56e869.png">
    \* (Except in libass it’s even worse due to [another issue](https://github.com/libass/libass/issues/618) stacked on top of this.)

    FWIW this file was originally released in 2009 and may or may not have been rereleased more recently. I know this show has been rereleased by other people with Blu-ray video and I believe all of them used these same subtitles, but I don’t know if the subtitle streams were edited in any way.

Given how this fix explicitly renders a dedicated feature of the ASS format unusable and there are real files that rely on that feature, I’d like to suggest reverting the fix and concluding that the OP sample was rendered precisely as it should be. It’s libass that needs to be fixed, and indeed I totally already have this on my to-do list.

If I may, I’d also like to suggest that for future subtitle change requests, people be routinely requested to provide comparisons not only to libass but also to xy-VSFilter or (real) XySubFilter, as indeed libass itself does.

**Comment by clsid2** [comment]
There are likely many of these "broken" subtitles due to people using broken libass as reference.

I will adjust it so that it only applies DEFAULT_CHARSET if style value is ANSI_CHARSET.

A script that depends on font failing to render is by definition BROKEN. We should not support such bullshit stuff at all. If you want Arial, use Arial, it is as simple as that.

**Comment by astiob** [comment]
> I will adjust it so that it only applies DEFAULT_CHARSET if style value is ANSI_CHARSET.

How is that meant to be helpful? Why is ANSI supposed to be better/worse than any other?

In particular, in the specific sample I showed, ANSI_CHARSET is precisely the value that was used.

> We should not support such bullshit stuff at all.

The format has a field that has a well-defined meaning. Your patch completely breaks this field and renders it useless. It affects font substitution, too, in cases when the named font doesn’t exist at all and probably in cases when it exists but lacks glyphs for some (or all) of the characters actually used in the text—maybe you’ll find this to be less “bullshit”.

(Then again, ASS is filled to the brim with bullshit anyway, even if you consider this to be it. Kind of fitting for the name, ironically. And we keep supporting it to break scripts from breaking.)

**Comment by astiob** [comment]
> A script that depends on font failing to render is by definition BROKEN

I agree that depending on specifically Arial without naming it is sketchy, although the fact it is the default for ANSI is reliable (and unfortunately [used in many scripts](https://github.com/libass/libass/issues/42), sometimes even without explicitly requesting ANSI, which is certainly not right™ but shows how widespread this fallback is).

But more pertinently, the script I showed depends on the font selection acting exactly as defined and a font that doesn’t match the requested properties not being selected. On the contrary, the script OP posted here explicitly asks a font not to be used but looks better when the font is actually selected nevertheless. Which script is the broken one?

**Comment by astiob** [comment]
As a counterargument to myself, FFmpeg-generated ASS files (until now) unfortunately always have `Encoding=0` (“ANSI”), so they should indeed benefit. But FFmpeg-generated files tend to rely on other libass inconsistencies and thereby look various degrees of bad in VSFilter, including MPC-HC’s. Oldest ones don’t play in VSFilter at all, then some play but have wrong border & shadow scaling, and all use `\{` `\}` escapes and sometimes `\\`, which not even libass renders as FFmpeg intends. libass itself handles all of this by having special detection for FFmpeg-generated files that toggles some settings to be more in line with what FFmpeg came to expect from older libass.

**Comment by astiob** [comment]
Another real sample that required `\fe` in a much saner way than the one I mentioned above: https://github.com/libass/libass/issues/233 although, of course, it also relied on font fallback and would’ve been better with the font named explicitly (as do & would, regardless of `\fe`, all too many other ASS files). Full disclosure: it required `\fe2`, so the awkward fix-to-the-fix to only special-case `\fe0` would indeed unbreak it. I wouldn’t be surprised if `\fe2` (SYMBOL) were a particularly common offender.
