### ISSUE TITLE
WebVTT rendered as black

### ISSUE THREAD

**Issue by u1735067** [clsid2/mpc-hc#1800]
Hello, 

I have an issue with a WebVTT file (extract: https://pastebin.com/TpiiSMaf), the text is all dark: 
![image](https://user-images.githubusercontent.com/1735067/182737385-5ca2c214-6c69-45d7-a22a-334c56e7c95c.png)

From trying to read the code a bit, the color tags (that this file use a lot) seems to be stripped, but the default colors seems to be ignored too?

---

Settings:

![image](https://user-images.githubusercontent.com/1735067/182737453-2f8d9034-a742-495c-b024-6b1c108a6731.png)
![image](https://user-images.githubusercontent.com/1735067/182737467-c1eb608e-d6eb-4c9a-b0c8-cc7dac966d80.png)
![image](https://user-images.githubusercontent.com/1735067/182737483-c6ef4285-62e0-48ef-9f14-1b75a104ff0b.png)

Edit: oh btw, thanks a lot for MPC-HC, I really like to use a light player

**Comment by clsid2** [comment]
The colors set in MPC-HC do not apply because the subtitle file defines its own styles.

@adipose
The bug happens in `WebVTT2SSA` on line 601.
`clrMap.count` with input `.bg_black` returns the entry for `.black`. Any idea why?

```
WEBVTT
 
STYLE
::cue(.black) {
 color: black;
}
 
STYLE
::cue(.white) {
 color: white;
}
 
STYLE
::cue(.bg_black) {
 background-color: black;
}

00:00:00.000 --> 00:01:00.000
<c.white>test</c>
 
00:00:00.000 --> 00:01:00.000
<c.white.bg_black>test</c>
```

I also noticed that forcing default style doesn't work.

**Comment by u1735067** [comment]
> The colors set in MPC-HC do not apply because the subtitle file defines its own styles.

Oh ok, I though they were stripped (https://github.com/clsid2/mpc-hc/blob/1.9.22.2/src/Subtitles/STS.cpp#L630)

> I also noticed that forcing default style doesn't work.

I've seen this ability in the issues already but I'm not sure were it's enabled, is it `Play` (toolbar) > `Subtitle tracks` > `Default style` (was enabled for me)?

**Comment by clsid2** [comment]
No, only unsupported tags are stripped. Colors tags are being parsed.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1806

Looks like color was matching "background-color" and getting the wrong value. I fixed that.
Also, it previously only supported "background" tag but not more explicit "background-color" tag.  Fixed that too.
