### ISSUE TITLE
MediaInfo data is no longer displayed when playing from archive

### ISSUE THREAD

**Issue by ryehamstrawberry** [clsid2/mpc-hc#1801]
Between build v1.9.22 and v1.9.22.25 the ability to view MediaInfo data seems to have been lost when playing video files direct from .rar archives.

I'm sure I'm not alone when I say that losing this functionality is a big inconvenience and that the ability to read MediaInfo data without the time consuming extra step of file extraction is of great benefit.

Please continue offering archive support for MediaInfo, thanks in advance.

**Comment by clsid2** [comment]
Fixed
