### ISSUE TITLE
Does the history of played files keeps dates?

### ISSUE THREAD

**Issue by OutshineIssue** [clsid2/mpc-hc#1802]
It only shows file names, can it show dates too?

**Comment by clsid2** [comment]
I am not interested in letting it show extra information.

**Comment by OutshineIssue** [comment]
@clsid2 Maybe not implemented inside the player but as a .txt file inside the installation folder? I need to keep a log of the things I watch on the player, there's no other way around to it if it's not implemented natively.

**Comment by clsid2** [comment]
I am not adding any new functionality. Certainly not for things I do not care about at all.

If you do a simple web search, you will find plenty of tools that you can use to log what you watch. Like trakt or Allmymovies.
