### ISSUE TITLE
Another "Remember File Position Not Working" Thread:

### ISSUE THREAD

**Issue by LucianAndries** [clsid2/mpc-hc#1805]
Hey.

We talked about this a while ago, too. And I read the thread that I put into my title.

Personally I agree with you, Stopping the video should not remember the file position. It is dumb, and the arguments are just as dumb! Just drag and drop the file on the player, you door knob...... omega nuclear facepalm
Only Pausing the video should remember it, or just closing the Player while playing.

I'm on version 1.9.22, and I still have the issue. But my issue is different, and I discovered how to make it work, but it's a drag.......................... :((((((
To make the player remember the freaking file position for me, I need to run the Player as an Admin first, and then drop in the movie file. BUT I have to run the Player again as Admin, to resume what it saved. And this is frustrating as hell!
And I'm also missing the "MediaHistory" subfolder in the Registries, "HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\MediaHistory".

I have no clue why it works only in Admin mode, because I did not install it as an Admin. Like running the setup file as an Admin. I installed it normally. Also I uninstalled it and reinstalled it, and nothing changed.

My only question is, can you force it to work as none Admin? On the PC I'm the only user, and I am an Admin, so it should work as is... :(
Also, the exact same issue is with the Player settings. I HAVE to run it as Admin, to set the settings how I want, in order for IT to remember them. If I run it normally, change something, save and close it. Then I run it again and check the settings, nothing was saved, it regressed to default.
And it's the same with and without the .ini file.

So for some reason on my PC it has an issue with Admins and whatnot. How can I troubleshoot it so I can give you the right files?

I bet you never seen this before, and you can't reproduce it either. This will need some out of the box ideas...

I'm on Windows 10 Pro 21H2, 64 Bit, btw.

**Comment by clsid2** [comment]
Stop using the goddamn ini file! That requires write access in the folder.

If you have disabled UAC in Windows, then that can be a cause of problems, as Windows becomes buggy. Put it in its lowest setting instead.

Delete the whole HKEY_CURRENT_USER\Software\MPC-HC key. That may help if something is broken with the registry permissions.

But anyway, the problem is entirely the fault of your system, so I can not provide any further help. The player does not require running as admin, unless user error (ini), or some system error (corrupt user profile, wrong file permissions, etc).

**Comment by LucianAndries** [comment]
Dude, I said the issue persists WITH and WITHOUT the .ini file. Sheeeesh........

But I discovered the issue. It was the fkg "madVR" renderer!!!!!!!!!!!!!!!!! How the fk does that even relate, god knows!
I switched to MPC Renderer and it started working instantly.....

**Comment by LucianAndries** [comment]
So fk madVR and their shit!!!!!!!!!! I'll never use it again!!

I only have 1 request please please? Can you guys make a better OSD than what madVR had?
- First of all you don't have an OSD... Or it does not show up with the MPC Video Renderer?
- Second, it should show big on a top corner when changing the volume, the file position when scrubbing and when a movie is paused and playing(I sometimes pause it by mistake, and don't know why a scene is so long...). But be a white font over a black box, for 100% visibility. Not dark grey over a black box, how madVR did it... facepalm

Pretty please? It's the only thing I ask now. Everything else finally works.

**Comment by LucianAndries** [comment]
Better yet, can you make it standalone, so it can be loaded as an external filter?
This way it can be worked upon, without having to wait for an entire MPC release.

**Comment by LucianAndries** [comment]
Nevermind. I updated MPC Video Renderer and now the OSD works flawlessly too.
