### ISSUE TITLE
Video file will be closed unexpectedly after window is moved.

### ISSUE THREAD

**Issue by Mogez** [clsid2/mpc-hc#1807]
When I hold Ieft mouse down on an ongoing video, move the player window and then release the button, the video will stop and close. Is it a bug?

MPC-HC (Nightly, 64-bit)
------------------------

Build information:
    Version:            1.9.22.29 (4a321a1e2)
    Compiler:           MSVC v19.29.30145
    Build date:         Aug 10 2022

**Comment by clsid2** [comment]
I am unable to reproduce such problems, and nobody else has reported anything similar.

**Comment by Mogez** [comment]
Thanks.

But it's weird that I can't reproduce it either today. I'll see if there is a specific pattern, for it's not the first time for me. In fact it's the reason I updated it to recent nightly version.

**Comment by clsid2** [comment]
I suggest completely resetting settings:
Options > Miscellaneous > Reset
