### ISSUE TITLE
"Show Preview on seek bar" option enabled causes the desktop environment to stutter and slowdown.

### ISSUE THREAD

**Issue by JMD13** [clsid2/mpc-hc#1808]
I have had this issue for serveral months now and i was never able to pinpoint the culprit, until now. 
My system is:

-  Windows 10 21H2
- 16gb of ddr3 ram
- RX 470 4gb on drivers 22.6.1
- MPCHC version 1.9.22 (32bit) ive also tried 64bit problem occurs on both.
- Im using madVR but im pretty sure it also happened with the default enhanced renderer.

Way to replicate the problem was to just watch anything on non-exclusive full screen, use the seek bar to preview the video and then close the app. After this moving around windows on desktop was stuttering. It felt as if the CPU was used at 100% all the time on an old Core 2 Duo machine.
Way to fix it was turn on fullscreen exclusive mode for madVR or restart the gpu drivers with control+win+b but that beats the purpose of the seek preview feature.

**Comment by clsid2** [comment]
There is nothing I can do about this. It is almost certainly a GPU driver bug. Try the new 22.8.1 driver.

**Comment by clsid2** [comment]
If you have an AMD system, you should also update your BIOS and chipset drivers.
