### ISSUE TITLE
Download Subtitles empty space

### ISSUE THREAD

**Issue by FreddyZar** [clsid2/mpc-hc#181]
Hi guys, got the new 1.8.8.40 build and on the Download Subtitles it has this wasted space beneath the new search function that seems to do nothing? Doesn't go away when resizing
![image](https://user-images.githubusercontent.com/32035834/71062241-b2ebaf00-2172-11ea-8acb-d647599995a4.png)

**Comment by adipose** [comment]
Should be fixed, here's a test build.

https://mega.nz/#!tAw3CQTK!30TOaq7csKyZs4obzkxQYrD-lx8LhL6oKPEGYwr6xoY

![image](https://user-images.githubusercontent.com/3324395/71233822-91421300-22ab-11ea-826e-2d12856c2bc7.png)

**Comment by FreddyZar** [comment]
Thanks @adipose quick other suggestion, how about populating the file name into the "search" text box by default?

**Comment by adipose** [comment]
I could, but to be clear it doesn't search by filename when you do the manual search.  It uses the generic "search" option that some sub searches allow.
