### ISSUE TITLE
Driver timeouts on 1.9.21.2 with MadVR

### ISSUE THREAD

**Issue by Drakyry** [clsid2/mpc-hc#1811]
hey frens, recently had two driver timeouts while using mpc hc on my amd card. amd driver app gives a warning that the driver crashed and both my monitors get disconnected. the pc itself seems to keep up running fine though (as I could still use it via a second screen app on my phone) but nothing except for a full reboot fixes the monitors getting disconnected

no otherheating issues on my gpu and both crashes happened only during using mpc hc even though i game and do other stuff on my 'puter a lot

Anyone know if this might be caused my mpc, or madvr, or even lavfilters? thanks

**Comment by clsid2** [comment]
It is a driver problem.

**Comment by Drakyry** [comment]
> It is a driver problem.

Are you sure though? As mentioned, the driver crashes only happened when using mpc-hc. Additionally when I first googled the problem before asking here I found several mentions of driver crashes caused my mpc-hc some time back like this one that you've yourself written 2 years ago: https://github.com/clsid2/mpc-hc/issues/444

thanks in advance

**Comment by clsid2** [comment]
Yes, it is not the fault of MPC-HC in any way and there is absolutely nothinf I can do about this.
