### ISSUE TITLE
HW decoding not working for this mp4

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#1813]
1. I have tested on differnt systems. Same results.
2. I have not changed any settings in LAV Decoder. Everything is default.
3. BE/Windows default video player are using HW decoding for same file.

[File Link](https://drive.google.com/file/d/1Q4xFga3IutCpTpHGpimguvsuDLSHoj4X/view?usp=sharing)

Edit: Seeking is also little bit slower on HC.

**Comment by clsid2** [comment]
This video uses H.264 baseline profile, which officially does not support hardware acceleration. Forcing HWA for baseline may work for most files, but is not guaranteed to work. So at this moment not supported.

**Comment by bibsp** [comment]
Ok. I thought it's a bug.
