### ISSUE TITLE
Add a 75% zoom hotkey?

### ISSUE THREAD

**Issue by kkdexz** [clsid2/mpc-hc#1817]
I was wondering if you could maybe add a hotkey entry for 75% zoom (perhaps also a 150% zoom too if you're feeling generous). I've often thought to myself that this would be quite useful, for example, 75% of a 1440p video would be 1080p and you would then be able to fit 2 videos side by side perfectly on a 4k display. Or similarly for 720p videos on a 1080p screen, both videos then being 540p. Or even for single video viewing, which should enable quick resizing in say, a PiP context.

(I'm aware that there already currently is a customizable auto-fit function, but I tend to and prefer to leave it untouched at somewhere between 25% and 50%, for PiP purposes mostly, and find it a hassle to continuously fiddle w/ the auto-fit value depending on the context. I also found out that it also isn't quite exact, as it's not a % of the video's resolution, but rather of your desktop resolution. Minus the taskbar that is, so I guess it's more like your viewport? Hiding/unhiding the taskbar results in diff vid resolutions at the same auto-fit value. It also factors in the caption, menu bar, and borders towards total "window size", so the actual video res when all of those are enabled/visible is quite a bit smaller than when none of them are, with none enabled actually being the only way to get the vid res to be "bit exact" with the % set in the options. But depending on how many of those elements you hide, the res varies by quite a bit, under the same setting. I'm assuming this is intentional.)

I know that you're not taking any requests for additional functionality, but this would seem to be quite a simple add to a layman like myself, i.e. perhaps kind of a "plug n play"/copy+paste type of thing?, given we already have the existing zoom values, plus adding a hotkey. But sigh, yes, I know simplicity isn't a determining factor in these things, just thought it worth an ask.

An alternative would be to add additional/multiple custom auto-fit values, but I def know you are not and will never be interested in implementing that.

**Comment by clsid2** [comment]
In Windows you can drag any window to the side of your screen to snap it in place there at exactly half screen width.

I am not adding new scaling options.

**Comment by kkdexz** [comment]
Yes, I know of the Windows snapping feature, which can also be done using the Win + arrow keys. However, if just snapping the window to either side of the screen, yes, it takes up exactly half of the width, but then its height is extended entirely from top to bottom, resulting in huge black bars on both the top and bottom of the video (if the video is natively landscape). Not very practical or ideal as this results in a lot of lost desktop space.

On the other hand, the window can also be snapped to quadrants of the screen. Although better, the downside to this is that the window is now "stuck" to one of the 4 corners and it cannot be freely moved around. Doing so causes the window to revert back to its pre-snapped size. So this makes it impossible to put 2 windows in the center of the screen, either side-by-side or top-to-bottom (stacked on one another); only side-by-side on either the top or bottom of the screen is possible AFAICT.

So while not the perfect solution, I do appreciate your response and suggestion.


Oh btw, I did come across a related issue while experimenting with the snap feature. It seems that it does not function at all whatsoever when hiding all menus and borders, i.e. on Menu -> View -> Minimal preset, neither via manually dragging w/ mouse nor w/ Win + arrow keys. You need to have the border visible at a minimum. Not sure if this is intentional or not (or an issue on my end), but I would've assumed it would work regardless of menu/border visibility.

**Comment by clsid2** [comment]
That is a limitation of Windows. It needs border to snap.

I am not adding any new options or functionality. No arguments are going to change that. I only work on things I care about personally.

**Comment by kkdexz** [comment]
Oh I know. Thanks for the response.
