### ISSUE TITLE
Seekbar preview stuck

### ISSUE THREAD

**Issue by anonghuser** [clsid2/mpc-hc#1818]
Since I updated to 1.9.22, every now and then something happens and the seekbar preview window remains stuck open when the mouse is not over the seekbar. Usually it also contains black background with broken image icon instead of actual preview when it happens. The stuck window survives clicking menus, alt-tabbing away and back, entering and exiting fullscreen, moving the main window and such. Bringing the mouse to the seekbar and away again is the only way to get rid of it. 

Unfortunately it is quite hard to try and reproduce the issue on purpose.

Also I am not sure which version I had previously, but it did not have this issue. If my "downloads" folder is to be trusted, the previous installer I had was for 1.9.18, but I can not promise I didn't install some in-between version as well and deleted that installer.

**Comment by clsid2** [comment]
The broken image icon is shown when it is still busy generating the preview. Perhaps it happens more on files with slow or broken seeking?

I am unable to reproduce the problem.

**Comment by anonghuser** [comment]
While I said it is hard to reproduce when wanting to on the spot, it is still somewhat reliably possible eventually with a minute of wild flailing of the mouse across the seekbar and off of it. It happens on multiple of my videos from very different sources so I doubt it is related to the specific video files.

**Comment by anonghuser** [comment]
I just got it to happen on a h264 mp4, h264 mkv, and hvc1 mkv. The last one gets stuck with the correct preview image, the prior ones with the broken image icon (I think I see a flash of a correct preview image before that; probably irrelevant tho).
Edit: And on yet another h264 mkv I had it happen with both correct preview and broken one.
Edit 2: Reproduced on a wmv as well. Loading over wifi to see if it's easier, can't say if it is tho. The preview generation is obviously slower, i.e. both when it gets stuck and when it is properly showing it shows the broken image icon for a noticeable second before the correct preview appears. But getting it stuck... i'm not sure. Feels a bit easier, but not as easy as if it were guaranteed by moving within that preview generation delay. Might be some placebo effect and still be just as rare.

**Comment by anonghuser** [comment]
For what it's worth, I reinstalled 1.9.18 and although I feel it might be harder, I was able to reproduce the stuck preview on it too.

**Comment by anonghuser** [comment]
I can no longer reproduce it, and the only reason I can think of is that it was only happening while I had my system under a lot of load. In particular, I think I had a huge amount (1200-1500) of tabs open in Edge for some period (kept even through restarts etc) even to the point of occasionally crashing out the "dwm" process etc. While I still think mpc-hc should handle the situation better (i.e. even if due to whatever async/timing issues "mouseout" equivalent was not processed, subsequent moving of the mouse outside of the seekbar should re-trigger it), it is no longer a high importance/annoyance for me.
