### ISSUE TITLE
Equivalent option of Subtitle Autodetection Paths?

### ISSUE THREAD

**Issue by Damthe** [clsid2/mpc-hc#1819]
Is this feature available in MPC-HC? It automatically loads the subtitles from pre-determined folders. E.g subs. 

Thank you,

![1](https://user-images.githubusercontent.com/21695940/185805464-8b398adb-2e8a-413f-9367-415ad235cb6f.png)

**Comment by clsid2** [comment]
If you spend 5 seconds looking in the options you will find it.

**Comment by Damthe** [comment]
Dear clsid2,

It does not work. even though it has been set as "\subs"

Is it capital letter sensitive?

**Comment by clsid2** [comment]
You must put a dot before the backslash.

**Comment by ale5000-git** [comment]
@Damthe: If you know command-line, `\subs` refer to `c:\subs` if you are on c:, instead `.\subs` refer to the `subs` as subfolder of the current folder.
