### ISSUE TITLE
Not tataly support Canon 5D4 M-jpeg 500Mb/s video 

### ISSUE THREAD

**Issue by milesmilesx** [clsid2/mpc-hc#182]
It can play Canon 5D4 M-jpeg 500Mb/s video,
But fps is too low ,CPU not used great on it.
It is the Canon video download:
http://www.photographyblog.com/reviews/canon_eos_5d_mark_iv_review/sample_images/

http://img.photographyblog.com/reviews/canon_eos_5d_mark_iv/sample_images/canon_eos_5d_mark_iv_01.mov

**Comment by clsid2** [comment]
I can't help you. Decoding such high bitrate MJPEG video is slow. You need to find a decoder that supports hardware accelerated decoding.

**Comment by milesmilesx** [comment]
1
