### ISSUE TITLE
frame by frame/shorter second scrubbing with mouse setting?

### ISSUE THREAD

**Issue by osayra** [clsid2/mpc-hc#1820]
is there a way to change how much time is scrubbed when you seek using your mouse? like drag along the progress bar. i dont like how it skips every .5 seconds it feels very juttery/laggy to me. if theres a setting for this please let me know!! <3

**Comment by clsid2** [comment]
Options > Tweaks > Disable fast seek

This will cause much slower and inefficient seeks. Effect depends on the file format. So don't come complaining if things don't work well. It is your own damn fault.
