### ISSUE TITLE
re: option for frame by frame/shorter second scrubbing with mouse?

### ISSUE THREAD

**Issue by osayra** [clsid2/mpc-hc#1821]
remaking this issue because someone closed it saying to enable/disable fast seek which is something i have tried previously, which i shouldve stated!! its my fault for not doing that

but to clarify i mean when you click and hold the progress bar forward/backwards it only updates the video player 2 frames every second of scrubbing. this vs the built in windows 11 player for example, updates the frame 4 times every second which makes scrubbing appear much smoother. im just wondering if theres anyway to change this in MPC-HC to make going through footage less annoying <3

**Comment by clsid2** [comment]
Do not re-create issues. You can still reply to closed ones.

Options > Tweaks > Jump distance (medium)
Adjust to any value you want. Then use left and right arrow to scrub.

There is no option for dragging the seekbar, nor will there ever be one.

**Comment by osayra** [comment]
oh okay sorry i didnt know you could still reply to closed threads, and thats alright ill see if i can find a different player to suit my needs, but thank you for answering <3
