### ISSUE TITLE
Seek preview corruption with QuickTime video file

### ISSUE THREAD

**Issue by BreakPoints** [clsid2/mpc-hc#1823]
When viewing the seek bar on the linked QuickTime video with H264 video stream encoding, most preview images become corrupt:
![image](https://user-images.githubusercontent.com/11966090/186464933-1fb1051d-99d3-43f4-afe4-0c90e97869c2.png)

The file in question is the 1080p copy of The Thief and the Cobbler: Recobbled Cut Mark 4 of which a torrent can be found at: https://recobbled.neocities.org/

**Comment by clsid2** [comment]
@nevcairiel
Can you please have a look at [this file](http://orangecow.org/thief/ThiefCobbler-91713-HD-H264.mov.torrent)?
Some frames might be wrongly marked as keyframe. For example 00:03.461.
Or timestamps may be wrong altogether. With MPC-BE splitter, the keyframes have slightly different timing.

**Comment by BreakPoints** [comment]
Worth me opening an issue in the LAVFilters repository?

**Comment by clsid2** [comment]
Has been fixed in LAV Filters. Will be included in next MPC-HC release.
