### ISSUE TITLE
MPC-HC reports two audio tracks in this file even though there is only one.

### ISSUE THREAD

**Issue by radpopl** [clsid2/mpc-hc#1824]
MPC-HC reports two audio tracks in this file even though there is only one.

https://files.fm/u/79m6ap9hj
(if the file does not exist yet, i.e. it is still being uploaded)

![image](https://user-images.githubusercontent.com/11005341/186526154-99735905-2567-4e85-9c94-6fbade3e3124.png)

![image](https://user-images.githubusercontent.com/11005341/186526222-4eed5609-a8d5-4e5c-abe9-22be5f3f7f4c.png)

**Comment by clsid2** [comment]
Latest development build only shows one audio track here.

**Comment by radpopl** [comment]
I downloaded the latest version and I can still see 2 audio tracks.

![image](https://user-images.githubusercontent.com/11005341/186655643-6d2dfa56-2ff3-46da-b6b9-713d498f0b05.png)

![image](https://user-images.githubusercontent.com/11005341/186655731-dcc6d071-9206-41e7-9ccc-42147408d49d.png)

**Comment by clsid2** [comment]
What is shown in:
Menu > play > Filters

Perhaps you have an audio file with name "4" in same folder? The player loads such audio dubs by default.

**Comment by radpopl** [comment]
> Perhaps you have an audio file with name "4" in same folder? The player loads such audio dubs by default.

Yes, I have wav file. Case closed :)

Maybe it would be a good idea to put e.g. * in front of such a soundtrack?

**Comment by clsid2** [comment]
You can disable it:
Options > Playback > Auto-load audio files

**Comment by radpopl** [comment]
Yes, I found it, but a sign would be a nice idea anyway.
