### ISSUE TITLE
Disable open last played file on startup

### ISSUE THREAD

**Issue by AvangionQ** [clsid2/mpc-hc#1828]
Reopening last played file on startup is an unwanted feature. Where's the option for how can I disable it?

**Comment by clsid2** [comment]
Options > player > Keep history
Options > player > Remember last playlist

**Comment by AvangionQ** [comment]
That's a decent workaround until this problem is actually resolved.
I would prefer to retain my previously opened files history though.

**Comment by clsid2** [comment]
There will not be any new options.

It does not open last file automatically. You must be clicking on the video area to trigger playback. Or play button. Or spacebar.

**Comment by kkdexz** [comment]
>  I would prefer to retain my previously opened files history though.

Just disable "Remember last playlist" then? The player will start up completely blank in that case (no last-played loaded).
