### ISSUE TITLE
Request: combine seek bar and status

### ISSUE THREAD

**Issue by AvangionQ** [clsid2/mpc-hc#1832]
There's a large amount of unused space between step and volume
Please combine the seek bar and the status bar
Move the paused/playing to the left/middle of the seek bar
Move the time/total to the right/middle of the seek bar
This will save space for those who don't like fullscreen mode

**Comment by clsid2** [comment]
Stupid idea.

There are several options to show extra information in status bar and there may be more buttons in future.
