### ISSUE TITLE
Love this App MISSING 1 IMPORTANT FEATURE

### ISSUE THREAD

**Issue by Supah736** [clsid2/mpc-hc#1833]
The one thing I miss with vlc media player after switching is when I'm listening to recorded calls in VLC I was able to turn the volume up higher to hear important thing with Mpc It only goes to 100. Can you add this feature into mpc that way its perfect for me then?

**Comment by clsid2** [comment]
Options > Internal Filters > Audio Switcher > Boost

You can configure hotkeys for it here:
Options > Player > Keys

This is the functionality that is available. Not other related functionality will be added.

**Comment by kkdexz** [comment]
In the same options tab as above, you can also try checking "Normalize" and "Regain Volume", then also cranking up the "Max amplification: %" right below that, I think it goes up to 1000%. These are also able to bind hotkeys to.

I personally noticed these 2 alone boost the volume greatly, e.g. MPC is now about 2-3x louder than Firefox browser, but YMMV, it may depend on your audio setup. Apparently these aren't recommended if you're a true audiophile wanting the highest fidelity possible, but if you just want to use it for recorded calls...eh, think it might be ok.

I think this is better than just the volume boost, as after a certain point, the audio starts getting quite distorted (around +100% in my case). You can always use boost on top of the above normalization if you do need it tho. Max boost is 300%.

You can also try tinkering with the Audio Decoder settings:
Internal Filters -> Audio Decoder

But I'm not too familiar with these settings, so can't really help you out much there.

As a side note, although my volume is a lot better/louder now, it gets even **louder** right after (and only after) I seek, for about half a second, then it normalizes to its "original" volume.

@clsid2 do you know if this has anything to do with the normalize setting? I also have both "Normalize Matrix" + "Clipping Protection" enabled in the audio decoder settings, under mixing. DRC is off.

**Comment by clsid2** [comment]
Normalize matrix in audio decoder actually lowers volume. So do not use that if you want boost.
