### ISSUE TITLE
5.1 > 2.1 LFE downmix

### ISSUE THREAD

**Issue by kraM1tt** [clsid2/mpc-hc#1835]
I have good subwoofer (PB1000) with studio monitors (2.1) and use MPC-HC for my HTPC.

I understand when 5.1 is mixdown it's -3db for Center and Surrounds to avoid clipping.
LFE is created with a -10db offset and then boosted +10db by the receiever in a typical HT setup, this is specified on Dolby site.

I want to add LFE track to mixdown in MPC, but it isn't in db it's in decimals. I assume 0.71(default) = -3db for C and SL + SR.

So can I assume for the LFE track that 1.00 = 0db and 2.00 = +10db?

The track is already pre-mixed at -10db remember.

![image](https://user-images.githubusercontent.com/89113987/188641078-2e298c0e-2e83-49cf-8b42-7a7fc478c396.png)

Thanks if you can help.

**Comment by clsid2** [comment]
The correct level for LFE is 1.58
