### ISSUE TITLE
Bad sound with "Speex" audio codec.

### ISSUE THREAD

**Issue by somebody2979** [clsid2/mpc-hc#1836]
It is not a very popular codec, but MPC-HC has problems with this audio codec from version 1.9.18 to the current one (1.9.23).
Version 1.9.17 and earlier sounded fine.

**Comment by Aleksoid1978** [comment]
Upload sample file.

**Comment by clsid2** [comment]
http://samples.ffmpeg.org/A-codecs/speex/speex_openacm.avi
http://samples.ffmpeg.org/A-codecs/speex/testingSpeex.flv

@nevcairiel
I narrowed this down to https://github.com/Nevcairiel/LAVFilters/commit/2fdaad482b5ffa16e27c9696942612fe86e5e432 or the ffmpeg update done on same day. MPC-BE internal decoder still works fine, so ffmpeg is probably not at fault. Also now that there is a native decoder for speex, maybe no more need for libspeex?

**Comment by Nevcairiel** [comment]
I can't reproduce any issues with the latest FFmpeg update anymore.

**Comment by clsid2** [comment]
Yes, fixed now. Thanks.
