### ISSUE TITLE
Record delay seconds

### ISSUE THREAD

**Issue by ssrlive** [clsid2/mpc-hc#1838]
Please add a function to automatically generate a file that records the delay seconds of the subtitle file. The file name has the same name as the subtitle file and adds a .delay suffix. The content of the file is the delay seconds. For example, 3000 means delay 3 seconds, -3000 means advance 3 seconds. The information for this delay file is automatically loaded the next time the subtitle file is loaded. Like shooter player.
![image](https://user-images.githubusercontent.com/30760636/189472352-c0d1bb81-fead-4a67-a4da-b7315415ba9a.png)

**Comment by ssrlive** [comment]
If I implement this feature, would you be happy to merge it into the master branch? @clsid2

**Comment by clsid2** [comment]
No.

Menu > File > Subtitles > Save Subtitles
There you can apply delay and replay existing file.
