### ISSUE TITLE
E-AC-3 5.1 audio track not recognized

### ISSUE THREAD

**Issue by Naf185** [clsid2/mpc-hc#1839]
Hi

I have the last stable version of MPC HC, but recently I have noticed a strange problem, some E-AC-3 5.1 audio tracks are not recognized

![image](https://user-images.githubusercontent.com/101669249/189488551-9b7e0be0-611e-4a0a-af94-e9444e059ce5.png)

Please see the attached files to understand the issue

![image](https://user-images.githubusercontent.com/101669249/189488208-3780aff9-d7dd-4828-8d0f-4bdc3b3a080f.png)
As you can see, medianfo shows 3 audio EAC3 5.1 tracks but only the english one is not recognized 

https://krakenfiles.com/view/qJNkZ39tiT/file.html

(No problem on other audio players)
Thanks for your help
N.

**Comment by clsid2** [comment]
That track is probably set as disabled in the file. You can use the header editor of MkvToolNix to check that and fix it.

**Comment by Naf185** [comment]
Thanks for your help
it worked  (even if other audio players can read it without editing the file)
N.

**Comment by clsid2** [comment]
The behavior of MPC-HC is correct and the other players are wrong and do not adhere to the Matroska specification.
