### ISSUE TITLE
Informally clearing an A-B bound (by seeking out of it) not recorded by Remember File Position

### ISSUE THREAD

**Issue by AllThisThen** [clsid2/mpc-hc#1840]
If "Remember File Position" is on, and an A-B repeat section is set in a file, then cleared by manually seeking out of the A-B bound twice, the seekbar will be inactive when MPC-HC loads that file again. Selecting "A-B (Reset)" in the new player corrects this and reactivates the seek bar smoothly.
Choosing Stop and then Play again in the new player will also fix the problem for that instance of the player for that file, but the A-B bound is still present and will be active in subsequent instances until "A-B (Reset)" is selected.

**Comment by clsid2** [comment]
Fixed
