### ISSUE TITLE
Request - YDL chapters

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1842]
MPC is not loading chapters from youtube.
https://youtu.be/7_Xdtd-cZ70

It is very useful.
yt-dlp already supports chapters. But player ignores it when streaming. Please enable this little feature.

Or fix it, if it is bug. Maybe nobody noticed this bug.

**Comment by ghost** [comment]
Reposted the above.

Actually I created account for this only. Then github showed your account has been flagged, profile is hidden from public. I created issue.
Then I realised that the issue is also hidden. I was not sure if you can see or not. I had no opttion left. So created new account. and reposted it.

**Comment by ghost** [comment]
Hi guys, is there any update on this? Pls fix it in next release 1.9.24. It's very small I guess.
Thanks in advance.

**Comment by ghost** [comment]
Admin, What is the reason of suddenly closing it?

You could say you are busy/you need time/not now/etc. I was not forcing you. I can only request. If I made mistake then sorry.
It is really useful for music videos with chapters.
Please consider this. There are other developers who can do this. Please try to understand.

**Comment by clsid2** [comment]
There is a big fat pinned topic about requests. I suggest you read it.

I DO NOT FUCKING CARE HOW MUCH YOU WANT IT.
I am not your slave and I am not interested in implementing this. It got closed because of you wining action. So no hope for other developers anymore either.
