### ISSUE TITLE
no sound when play moive with default sound track TrueHD 7.1 Atmos

### ISSUE THREAD

**Issue by wsyonline** [clsid2/mpc-hc#1843]
if change to 5.1 then back to TrueHD 7.1 Atoms, the sound will back.
MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.23 (a8e9113b5)
    Compiler:           MSVC v19.29.30145
    Build date:         Aug 26 2022

LAV Filters:
    LAV Splitter:       0.76.1.25
    LAV Video:          0.76.1.25
    LAV Audio:          0.76.1.25
    FFmpeg compiler:    MinGW-w64 GCC 11.3.0

Operating system:
    Name:               Windows 11 (Build 21H2)
    Version:            10.0.22000 (64-bit)

Hardware:
    CPU:                11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    GPU:                NVIDIA GeForce RTX 2060 (driver version: 31.0.15.1694)

movie information
General
Unique ID                      : 69535548196624939962692541646552861613 (0x34500F37ED46CBF560457758FD9A8BAD)
Complete name                  : G:\闪灵.The.Shining\睡梦医生.Doctor.Sleep.2019.PROPER.THEATRICAL.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv
Format                         : Matroska
Format version                 : Version 4
File size                      : 80.5 GiB
Duration                       : 2 h 32 min
Overall bit rate mode          : Variable
Overall bit rate               : 75.8 Mb/s
Movie name                     : Doctor.Sleep.2019.PROPER.THEATRICAL.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT
Encoded date                   : UTC 2022-09-12 06:28:55
Writing application            : mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
Writing library                : libebml v1.4.2 + libmatroska v1.6.4

**Comment by clsid2** [comment]
Enable the mixer in the internal audio decoder.
