### ISSUE TITLE
Bug for FullscreenSeparateControls + "Launch files in fullscreen"

### ISSUE THREAD

**Issue by chelpus** [clsid2/mpc-hc#1844]
If there are two monitors and enable the FullscreenSeparateControls option, and then expand the video to full screen, then everything is correct: the control interface is on one monitor, and the image is on the other. But if you enable the "Launch files in fullscreen" option, then when you start the video file, both the control and the video appear on the same screen in a strange way.
Apparently, when launching a file with the "Launch files in fullscreen" option, the code that works when expanding a video from windowed mode to full screen from the player itself does not work. I apologize for my English, if it was not clear somewhere. Ready to clarify.

**Comment by adipose** [comment]
Hmm, have to look into this.  You expect it to open controls on the last control screen?

**Comment by chelpus** [comment]
> Hmm, have to look into this. You expect it to open controls on the last control screen?

Yes exactly. More precisely, it will even be like this: the control interface should be where it is, if the player is not running in full screen mode. If I run the file with the "Launch files in fullscreen" option, the player should launch in normal non-fullscreen mode and already apply "FullscreenSeparateControls" to fullscreen on another monitor.
So far, it looks like the code simply did not take into account the situation of such a launch, and the FullscreenSeparateControls option simply does not apply when the file is launched immediately in full-screen mode, but it works correctly if you first start the player and then click full-screen playback. Sorry for my English, I have to use google translator.

**Comment by Wille-Helm** [comment]
Although not having experienced the same issue, I have often been fooled by the "Launch files in fullscreen" option, because - at least in my configuration - DISPLAY1 and 2 like to swap around from time to time.
But I think that has more to do with Windows and/or graphics drivers, because I have my 2nd display not always attached to it. So it could matter if the 2nd display is present while booting up or plugged in after boot.

**Comment by chelpus** [comment]
> because - at least in my configuration - DISPLAY1 and 2 like to swap around from time to time.

This option has nothing to do with this issue. The glitch is purely in the code. The image opens to full screen and the interface is located there, although the control interface should remain on the other monitor. The settings in the player itself cannot change this for the "FullscreenSeparateControls" option.

**Comment by adipose** [comment]
> > Hmm, have to look into this. You expect it to open controls on the last control screen?
> 
> Yes exactly. More precisely, it will even be like this: the control interface should be where it is, if the player is not running in full screen mode. If I run the file with the "Launch files in fullscreen" option, the player should launch in normal non-fullscreen mode and already apply "FullscreenSeparateControls" to fullscreen on another monitor. So far, it looks like the code simply did not take into account the situation of such a launch, and the FullscreenSeparateControls option simply does not apply when the file is launched immediately in full-screen mode, but it works correctly if you first start the player and then click full-screen playback. Sorry for my English, I have to use google translator.

I think this is potentially a confusing option.  I have tested and the option seems to work as I expect:

1. Choose a fullscreen monitor in `Playback/Fullscreen`
2. Put the controls on a different screen than chosen in `#1`
3. Launch a file.  It opens in fullscreen while controls stay on the other screen

If, however, I do this:

1. Choose a fullscreen monitor in `Playback/Fullscreen`
2. Put the controls on the same screen as `#1`
3. Launch a file.  It opens in fullscreen and separate controls is effectively disabled.

Questions:

1. Do you launch the player into fullscreen when it was previously closed, or do you open a new file while player is already open?
2. What is the "strange" situation you mentioned before?  Can you take a video of the strange behavior?

Thanks.

**Comment by chelpus** [comment]
> Questions:
> 
> 1. Do you launch the player into fullscreen when it was previously closed, or do you open a new file while player is already open?
> 2. What is the "strange" situation you mentioned before?  Can you take a video of the strange behavior?


1. The player is closed. I'm launching a file with "Launch files in fullscreen" and "FullscreenSeparateControls" enabled. Result: There are no controls on monitor N1, but the video opened in full screen on monitor N2
2. Here's a video. First, it shows the correct operation when the video is expanded to full screen from a running player. And then the "Launch files in fullscreen" option is enabled, and the video file is launched, it opens in full screen, but there is no control on monitor N1.
https://github.com/clsid2/mpc-hc/assets/1729612/e327b171-6842-4865-b936-277e8add5ffa

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2120

I think this should fix it.
