### ISSUE TITLE
Left clic and drag doesn't work properly

### ISSUE THREAD

**Issue by remizik** [clsid2/mpc-hc#1847]
Hi,

In windowed mode, you can left clic and drag the window around.
But there's a "circle" around the spot where you left clic and hold that is not taken into account, making impossible to quickly adjust the window position. You need to clic and hold, drag out of that "dead circle" and then come back to the location you want the window to be.

here's a video to illustrate : https://streamable.com/6yudo4

I just noticed it's also present on the original MPC-HC, but that "dead circle" is much much smaller, so small that I never noticed.

**Comment by clsid2** [comment]
It is intentional and not debatable.

Drag the title bar instead.

**Comment by remizik** [comment]
> It is intentional and not debatable.
> 
> Drag the title bar instead.

Why not configurable ?

**Comment by clsid2** [comment]
I am not going to add tons of bullshit options.
