### ISSUE TITLE
MPC + DTS Sound Unbound will heard breaking sound

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1848]
Windows 11 latest stable
Using :
Sony WH-1000XM3
intel driver assistant latest stable driver
SVP4 Pro latest
MPC-HC 1.9.23 default setting come from SVP

**Comment by zhenjie1999** [comment]
I found the problem, is the intel improvement program problem.
I uninstall it solved the problem.
After seen this post, is ok to close issue.

**Comment by clsid2** [comment]
MPC-HC options > Playback > Output > Audio Renderer
Try different renderer. Any problems are the fault of Windows, so I can not help you if nothing works.

Selecting 2 channels in headphone properties seem wrong if you want surround sound.
