### ISSUE TITLE
Audio dropouts with MPC H64

### ISSUE THREAD

**Issue by Robert3750** [clsid2/mpc-hc#1849]
I often experience two or three brief (1 second or less) random audio dropouts when playing videos in my theater room. Video is unaffected. Problem occurred when I was using Windows 7 and now when I’m using Windows 10. Music files are never affected. The problem occurs when using Kodi and when using MPC H64 player with MadVR. The HDMI output from my PC is split, with a 12 foot cable going to my bedroom system, and a 25 foot cable going to my theater room. I’ve never noticed the problem on the bedroom system. I’ve tried changing HDMI cables to the theater room preamp, including an 8k certified fiber optic HDMI cable, and it makes no difference. The problem occurred with my old preamp and with my new preamp (both Anthem). Video card is an Nvidia. Updating the Nvidia driver has made no difference. Any help would be appreciated.  Someone suggested that I downgrade to LAV filter 0.74.1, but I don't know how to do that.

**Comment by clsid2** [comment]
I can't help you.

It is almost certainly a driver problem.

Is is not a player problem and also not the fault of LAV.
