### ISSUE TITLE
Videos don't play on repeat - Windows 11

### ISSUE THREAD

**Issue by mckealty** [clsid2/mpc-hc#1850]
Hi all...

Just got a new PC with Windows 11. When playing a list of videos, when one is finished and the next one starts, the screen is blank. There's audio but no video.

Let me know if you need any more information, thanks.

**Comment by clsid2** [comment]
Update your graphics driver.

**Comment by mckealty** [comment]
Latest Intel UHD 730 drivers are installed and it doesn't seem to work.

**Comment by clsid2** [comment]
Disable hardware accelerated decoding in the internal video decoder settings. I have no other suggestions. I can't provide any further help.

**Comment by oceanful** [comment]
If it's helpful, I was able to fix the problem by changing the `Options > Playback > Output > DirectShow Video` setting to anything that did not enable DXVA (i.e. "Video Mixing Renderer 9 (or 7)" and "Old Video Renderer").

**Comment by mckealty** [comment]
Absolutely great work! Thank you for taking the time to help.

**Comment by clsid2** [comment]
You should not use old renderer. Simply disable DXVA in the video decoder settings. Or update your graphics driver.

**Comment by mckealty** [comment]
As I said in the previous comment, my graphics driver is updated and is updated regularly, I'm not an idiot. 

https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html

Oceanful's solution worked perfectly.

**Comment by clsid2** [comment]
Try this renderer:
https://github.com/Aleksoid1978/VideoRenderer/releases

**Comment by mckealty** [comment]
That worked, too. Thanks for the assist! I'll probably stick with that renderer.

**Comment by oceanful** [comment]
For posterity, changing the hardware accelerator (DXVA or otherwise) did not work for me, but setting the video renderer to  "Video Mixing Renderer 9 (or 7)", "Old Video Renderer", and @clsid2's recommended "[MPC Video Renderer](https://github.com/Aleksoid1978/VideoRenderer/releases)" resolved the problem.

@clsid2, thank you for your help and for maintaining this software.

**Comment by clsid2** [comment]
Then it is likely some kind of bug in the EVR renderer from Microsoft.

**Comment by mckealty** [comment]
For what it's worth, this doesn't happen when using the Windows media player "TV and Movies" or whatever it's called.

**Comment by clsid2** [comment]
THIS IS NOT A BUG IN THE PLAYER WHICH MEANS THAT I CAN NOT FIX IT !!!

Disable dynamic contrast in the Intel graphics driver settings. That often causes problem.
