### ISSUE TITLE
Request - option to have an immediate reaction to draging the window by a video screen

### ISSUE THREAD

**Issue by Yoksven** [clsid2/mpc-hc#1851]
Hi. Maybe I'm misremembering, but I think in recent versions there's now a "delay" when you drag the window by clicking on a video. There's, what feels like, a pretty big box around the mouse and until you reach the edge of that box the window won't react to your attempts to drag it. It's pretty noticeable if you're trying to drag it slowly or move it a small amount.
I don't know if I'm misremembering how it always was or it's a recent change, but regardless, I'd like to have an option to not have that box or maybe to adjust the size of it, so dragging by video would be immediate or as close to it as you want. I'm okay with it just being an advanced setting (I was actually hoping to find it in advanced settings, but alas).

**Comment by clsid2** [comment]
I am not adding an option for it.
