### ISSUE TITLE
Continuing a movie that was paused for more than 15-20 minutes causes a revert in settings

### ISSUE THREAD

**Issue by Gwyll** [clsid2/mpc-hc#1853]
I often watch movies during work and I pause the movie as needed.
I'm not sure about the time ... but after 10-15 minutes continuing the movie reverts many things.

The window switches to full screen and the downloaded (but not saved) subtitle gone.
Continuing the movie within 1-10 minutes works as expected.

Tiny bug.

**Comment by clsid2** [comment]
Options > Advanced > ReloadAfterLongPause = -1

Options > Subtitles > Misc > Automatically save downloaded subtitles
