### ISSUE TITLE
Feature request: default audio track

### ISSUE THREAD

**Issue by Dim-Tim-1963** [clsid2/mpc-hc#1854]
Would be nice to have a possibility to choose (in settings) default audio track language, as it is now with subtitles.  And to remember the last selected track for TV series.  Use case example: to watch anime TV series in Japanese, but with subtitles in viewer's native language.

**Comment by clsid2** [comment]
That is already possible.

Options > Playback > Default track preference
Options > Internal Filters > Splitter > Preferred languages

**Comment by Dim-Tim-1963** [comment]
Ah, that option just hidden a bit.  Thanks! :)
