### ISSUE TITLE
[Feature Suggestion] Decode immersive formats to a custom channel layout via ASIO

### ISSUE THREAD

**Issue by fgaleko** [clsid2/mpc-hc#1856]
For quality control of ATMOS files, Dolby offers the Reference Player to its partners. https://customer.dolby.com/content-creation-and-delivery/dolby-reference-player-with-dolby-ac-4-v310

There is no further information on it there and it's not a commercially available solution. Based on the little info there is, it apparently works by decoding ATMOS in software and outputting to a set configuration (see screenshots on the website). Set output device (ASIO), select the channel, set which speaker/position corresponds to the channel. 

There is a Multichannel Asio Renderer filter for MPC-HC which lets you use an interface to listen to up to 7.1 audio on the same setup where you're doing film mixing in Resolve, etc (which can otherwise be problematic because Windows will set up a new WDM device for every 2 channels on a 3rd party interface). But when you try to set LAVAudio to bitstream Dolby TrueHD, that's meant for digital passthrough, and there's no way to decode it on device to allow the Multichannel Asio Renderer to play it back on 12-16 channels. 

I am wondering if MPC-HC can implement this somehow to be the open source platform for quality control of immersive format files. 

https://github.com/VoidXH/Cavern This is an open source object audio rendering engine that adapts to user configurations. I am wondering if there is a connection to be made here.

**Comment by clsid2** [comment]
No.

**Comment by fgaleko** [comment]
Thanks for replying!
