### ISSUE TITLE
Medium jump and long jump cannot be set below 5000 ms

### ISSUE THREAD

**Issue by jmlarch** [clsid2/mpc-hc#1857]
The Tweaks page of the Options dialog will let you set jump distances as, for instance, 1000, 2000 and 3000; but, in this case, the medium and long jumps will be 5 seconds. 

This could be due to a bug rather than a design decision, because a 2s long jump worked for a few minutes, until it reverted to a 5s jump.

**Comment by clsid2** [comment]
It is working perfectly correct.

By default the player seeks to keyframes, so if your crappy files have a large keyframe interval then this is what the behavior will be.

You can disable it here:
Options > Tweaks > Fast Seek
