### ISSUE TITLE
No Polish subtitles on Polish film, in mpc hc

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1860]
How in a Polish film to set the subtitles to appear themselves, in mpc hc?

Subtitles
![napisy](https://user-images.githubusercontent.com/104568362/192482536-031b40ae-b189-4d8e-9678-f1783e974c5b.jpg)

mpc hc
![mpchc](https://user-images.githubusercontent.com/104568362/192482618-a9075d19-16d7-44d0-b04d-a357a1045813.jpg)

I have so set in mpc hc.

**Comment by clsid2** [comment]
Use only **pol** there.

**Comment by ghost** [comment]
unfortunately no changes :(

**Comment by clsid2** [comment]
https://1f0.de/lav-splitter/lav-splitter-stream-selection/

Select advanced mode.
Use `*:pol|h,*:pol|!f,*:pol,*:*|d`

That means prefer hearing impaired, then non-forced, then other polish, then whatever is default.

**Comment by ghost** [comment]
thank
