### ISSUE TITLE
[Feature request] Two hotkey for function

### ISSUE THREAD

**Issue by r57zone** [clsid2/mpc-hc#1861]
Hi, it would be great if it would be possible to make 2 hot buttons for functions, for example, for the "Play / Pause" function.
This feature would be useful for users of PC remote controls that don't have a pause button (compact modern remotes).
I think it's enough to duplicate the hot key "Play / Pause" in the list of hot keys, add "Play / Pause (second)" so as not to change the architecture of adding hot keys. The duplication would allow "Space" to be used for this, when using the keyboard, and another button when using the remote.

Thank you for working on MPC, it's the best player for windows.

**Comment by kkdexz** [comment]
Not sure if this is exactly what you're looking for, but in the HotKeys options, if you keep scrolling all the way to the right, after the mouse shortcuts, there is a column titled "App Command". If you click on any one of those cells, there is a dropdown menu with quite a lot of choices.

Idk what kind of PC remote control you have, that doesn't even have a pause button (never heard of that before), but if there are other buttons on it, you're bound to find a few that are also available as choices in MPC-HC in that dropdown menu. For example, perhaps you have a "MEDIA_PLAY" or "MEDIA_STOP", those might be of use.

It's not exactly a duplicate entry for each command, but there's a ton there, so try checking it out if you haven't. There are also browser controls like forward/back, as well as general media/app launch/PC commands. For example, I use the command "BROWSER_REFRESH" to also reopen or "refresh" the file in MPC-HC.

You might also want to experiment with :
1. "Global Media Keys" setting at the bottom of the Keys options, which means they're used even when the player is not in focus.
2. Options > Advanced > "UseSMTC" (Hover over to see description in settings)

There's also a "RemoteCmd" column to the right of App Commands. Not sure what that is as I don't use it myself, but I'm guessing they're for command line/terminal input. If you're comfortable with that sort of thing, you can try that too.
