### ISSUE TITLE
Playlist context menu not going away

### ISSUE THREAD

**Issue by Gold-Phoenix** [clsid2/mpc-hc#1862]
As stated by your previous update deselecting the playlist option in formats should remove the context menu for "Add to MPC-HC playlist" however whenever i choose that and reopen it, it re-selected with the context menu option still there. Also I've running and changing the option as administrator and it does nothing.

Running Windows 7 with the lastest version of MPC-HC, cheers

**Comment by clsid2** [comment]
To remove stuff you need to uncheck all formats. Then re-enable them with context menu unchecked.

Doing it directly is super ultra low priority for me.

**Comment by Gold-Phoenix** [comment]
Awesome that worked for me! Thank you!

Edit: Ok so that didnt work, its deselected and the playlist context option is unticked, and ive tried changing the settings as admin and rebooting and it still doesnt work
