### ISSUE TITLE
Feature Request - Remember Last Folder Used by Subtitles

### ISSUE THREAD

**Issue by Felipefpl** [clsid2/mpc-hc#1863]
Right now mpc only remembers the last folder used by the videos/music, it would be nice if it remembered the folder used by the subtitles because it sucks having to choose the same folder every time you want to load a subtitle which happens when you have a very specific folder for videos (like it happens with videos downloaded through torrent).

**Comment by clsid2** [comment]
It opens the current folder of the video and I am not going to change that.
