### ISSUE TITLE
".sub" MicroDVD format subs affected by the option "Position subtitles relative to the video frame".

### ISSUE THREAD

**Issue by Max33Verstappen** [clsid2/mpc-hc#1865]
As the title says.
When the tri-state checkbox is checked or partially-checked, it happens.
The details and the sample sub can be found here [https://sourceforge.net/p/mpcbe/tickets/956/](url). (Sorry to link tickets from another project if that's a problem because I find this bug also exists in MPC-HC.)

**Comment by clsid2** [comment]
That option is for text based subtitles, so it is working as intended.

**Comment by Max33Verstappen** [comment]
But .srt are not affected?

**Comment by clsid2** [comment]
Everything is working fine for me and that is all that matters. You must be doing something wrong.

**Comment by Max33Verstappen** [comment]
It's when this option is partially checked (square) that the inconsistency occurs, that is, ".sub" is relative to the frame while ".srt" relative to the viewport.
Hopefully, I didn't miss something this time. And I'm not sure if it's a bug?

**Comment by clsid2** [comment]
Fixed
