### ISSUE TITLE
After a few music files mpc-hc stop playing and glitched

### ISSUE THREAD

**Issue by Shisizuwa** [clsid2/mpc-hc#1866]
Please fix it, this glitch started after the last update, i don't want use another player 
![glitch](https://user-images.githubusercontent.com/115166137/194334746-be5e3c19-4582-4cbf-b4c6-6cdc19e12c94.gif)

**Comment by clsid2** [comment]
You need to explain in more details what is happening.

If it only happens with specific (ogg) files then you need to upload samples.
http://www.sendspace.com

**Comment by Shisizuwa** [comment]
no it happend with all (common) audio files, mp3,ogg,wav

**Comment by clsid2** [comment]
Options > Miscellaneous > Reset

A playlist of audio files is working normally here.

**Comment by clsid2** [comment]
Try these development builds to pinpoint when the problem started:
https://github.com/clsid2/mpc-hc/releases/tag/1.9.22.2

**Comment by Shisizuwa** [comment]
yup its only in version 1.9.22 and 1.9.23

**Comment by clsid2** [comment]
Then test older builds:
https://github.com/clsid2/mpc-hc/releases/tag/1.9.21.19

I can not fix the problem if I can not reproduce it.

**Comment by Shisizuwa** [comment]
yeah i know,
i have the problem only in the versions 1.9.22 and 1.9.23 in the versions before there are no problems.

**Comment by clsid2** [comment]
The link above points to versions in between 1.9.21 and 1.9.22.

**Comment by Shisizuwa** [comment]
yup with Version1.9.21 i have no problem

**Comment by clsid2** [comment]
You need to test the development versions in between! Then I have more information about which changes may be responsible for your problem.
