### ISSUE TITLE
Slowdown with codec x265 - MPC 

### ISSUE THREAD

**Issue by Felipefpl** [clsid2/mpc-hc#1868]
Is there any reason why the movies encoded with x265 are slow? I dont have this problem with other codecs. Config below:

MPC-HC
------

Build information:
    Version:            1.9.23 (a8e9113b5)
    Compiler:           MSVC v19.29.30145
    Build date:         Aug 26 2022

LAV Filters:
    LAV Splitter:       0.76.1.25
    LAV Video:          0.76.1.25
    LAV Audio:          0.76.1.25
    FFmpeg compiler:    MinGW-w64 GCC 11.3.0

Operating system:
    Name:               Windows 7 (Service Pack 1)
    Version:            6.1.7601 (64-bit)

Hardware:
    CPU:                Intel(R) Celeron(R) CPU G460 @ 1.80GHz
    GPU:                Intel(R) HD Graphics (driver version: 9.17.10.2828)

**Comment by clsid2** [comment]
It is because of your old hardware.
