### ISSUE TITLE
Using different embedded subtitles over the default in the same language

### ISSUE THREAD

**Issue by yolorag** [clsid2/mpc-hc#1869]
So I have series that have two different versions of subtitles in English.
The first ones that are displayed automatically are in ugly yellow color, the other ones are white, other than that, they seem to be the same.
I've tried overwriting the color, but they are still yellow.

The yellow ones have "(vobsub)" ans white ones "(subrip)" if that matters.
Is there any way i can make the player use the second version automatically?

**Comment by clsid2** [comment]
Vobsub is an image based subtitle format, so font and color settings do not have any effect on it.

It is not possible to configure the player to handle this specific situation.

You can use the header editor of the MkvToolNix application to change the default selected subtitle track in those files.
