### ISSUE TITLE
Video glitching out on my PC (x265 12 bits HEVC)

### ISSUE THREAD

**Issue by exegg** [clsid2/mpc-hc#187]
Title. The video opens to a green screen, then plays with lots of glitching artifacts

![KSXL-367 mkv_snapshot_00 00 18 278](https://user-images.githubusercontent.com/19347211/71314976-33d3d080-2429-11ea-93ec-7e9e08855700.jpg)

![KSXL-367 mkv_snapshot_00 10 59 075](https://user-images.githubusercontent.com/19347211/71314977-3a624800-2429-11ea-84a6-9f48b5398fef.jpg)

I disabled HW acceleration (which the iGPU of my CPU doesn't support for x265 anyways). Problem still persists.
I reencoded a tiny bit of the video to h264 and it was fine so something is going on with the original format and my PC or player. I have the latest stable release from here, and my CPU is a 4th gen Intel Celeron G1820 (Haswell).

Mediainfo of the video (clipped the encoding settings since they were very large)
Video
ID                             : 1
Format                         : HEVC
Format/Info                    : High Efficiency Video Coding
Format profile                 : Format Range@L4@High
Codec ID                       : V_MPEGH/ISO/HEVC
Duration                       : 2 h 24 min
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 23.976 (24000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 12 bits
Writing library                : x265 3.2.1+1-b5c86a64bbbe:[Windows][GCC 8.3.0][64 bit] 12bit
Encoding settings              : -clipped-
Default                        : Yes
Forced                         : No
Color range                    : Limited
Color primaries                : BT.709
Transfer characteristics       : BT.709
Matrix coefficients            : BT.709

**Comment by exegg** [comment]
Fixed by installing madVR and using it as video Directshow in the playback output.

**Comment by clsid2** [comment]
Which colorspace is shown here when using the EVR-CP renderer?
MPC-HC menu > Play > Filters > EVR > Pin Info

**Comment by exegg** [comment]
Hi, @clsid2 I really don't know if this is what you requested so I copied the entire text
And here's a 20 second sample of that video I cut with ffmpeg to see if you can reproduce it
https://www21.zippyshare.com/v/3AdCDOuL/file.html

Filter : Enhanced Video Renderer - CLSID : {FA10746C-9B63-4B6C-BC49-FC300EA5F256}

- Connected to:

CLSID: {EE30215D-164F-4A92-A4EB-9D4C13390F9F}
Filter: LAV Video Decoder (internal)
Pin: Output

- Connection media type:

Video: P016 1920x1080 23.976fps

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Video {73646976-0000-0010-8000-00AA00389B71}
subtype: MEDIASUBTYPE_P016 {36313050-0000-0010-8000-00AA00389B71}
formattype: FORMAT_VideoInfo2 {F72A76A0-EB0A-11D0-ACE4-0000C0CC16BA}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 6220800
cbFormat: 1152

VIDEOINFOHEADER:
rcSource: (0,0)-(1920,1080)
rcTarget: (0,0)-(1920,1080)
dwBitRate: 0
dwBitErrorRate: 0
AvgTimePerFrame: 417083

VIDEOINFOHEADER2:
dwInterlaceFlags: 0x00000000
dwCopyProtectFlags: 0x00000000
dwPictAspectRatioX: 16
dwPictAspectRatioY: 9
dwControlFlags: 0x2880a581
dwReserved2: 0x00000000

BITMAPINFOHEADER:
biSize: 40
biWidth: 1920
biHeight: -1080
biPlanes: 1
biBitCount: 24
biCompression: P016
biSizeImage: 6220800
biXPelsPerMeter: 0
biYPelsPerMeter: 0
biClrUsed: 0
biClrImportant: 0

pbFormat:
0000: 00 00 00 00 00 00 00 00 80 07 00 00 38 04 00 00 ...........8...
0010: 00 00 00 00 00 00 00 00 80 07 00 00 38 04 00 00 ...........8...
0020: 00 00 00 00 00 00 00 00 3b 5d 06 00 00 00 00 00 ........;]......
0030: 00 00 00 00 00 00 00 00 10 00 00 00 09 00 00 00 ................
0040: 81 a5 80 28 00 00 00 00 28 00 00 00 80 07 00 00 ¥(....(......
0050: c8 fb ff ff 01 00 18 00 50 30 31 36 00 ec 5e 00 Èûÿÿ....P016.ì^.
0060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0070:|01 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 ................
0080: 00 00 02 00 00 00 00 00 01 00 00 00 00 00 00 00 ................
0090: 00 00 02 00 00 00 00 00 70 00 00 00 00 00 00 00 ........p.......
00a0: 00 00 00 00 00 00 00 00 70 00 00 00 00 00 00 00 ........p.......
00b0: 5c 00 5c 00 3f 00 5c 00 53 00 57 00 44 00 23 00 \.\.?.\.S.W.D.#.
00c0: 4d 00 4d 00 44 00 45 00 56 00 41 00 50 00 49 00 M.M.D.E.V.A.P.I.
00d0: 23 00 7b 00 30 00 2e 00 30 00 2e 00 30 00 2e 00 #.{.0...0...0...
00e0: 30 00 30 00 30 00 30 00 30 00 30 00 30 00 30 00 0.0.0.0.0.0.0.0.
00f0: 7d 00 2e 00 7b 00 32 00 33 00 35 00 33 00 34 00 }...{.2.3.5.3.4.
0100: 39 00 65 00 37 00 2d 00 39 00 39 00 66 00 62 00 9.e.7.-.9.9.f.b.
0110: 2d 00 34 00 31 00 31 00 36 00 2d 00 61 00 37 00 -.4.1.1.6.-.a.7.
0120: 65 00 37 00 2d 00 31 00 33 00 37 00 37 00 64 00 e.7.-.1.3.7.7.d.
0130: 34 00 63 00 34 00 37 00 30 00 36 00 34 00 7d 00 4.c.4.7.0.6.4.}.
0140: 23 00 7b 00 65 00 36 00 33 00 32 00 37 00 63 00 #.{.e.6.3.2.7.c.
0150: 61 00 64 00 2d 00 64 00 63 00 65 00 63 00 2d 00 a.d.-.d.c.e.c.-.
0160: 34 00 39 00 34 00 39 00 2d 00 61 00 65 00 38 00 4.9.4.9.-.a.e.8.
0170: 61 00 2d 00 39 00 39 00 31 00 65 00 39 00 37 00 a.-.9.9.1.e.9.7.
0180: 36 00 61 00 37 00 39 00 64 00 32 00 7d 00 00 00 6.a.7.9.d.2.}...
0190: 01 00 00 00 00 00 00 00 c8 4f c3 78 4a 10 ca 4a ........ÈOÃxJ.ÊJ
01a0: 9e a4 52 4d 52 99 6e 57 00 01 00 00 00 00 00 00 ¤RMRnW........
01b0: 00 00 00 00 00 00 00 00 12 00 00 00 8a 00 00 00 ...............
01c0: 18 36 a0 0f b4 02 00 00 8a 00 00 00 00 00 00 00 .6 .´..........
01d0: 53 00 57 00 44 00 5c 00 4d 00 4d 00 44 00 45 00 S.W.D.\.M.M.D.E.
01e0: 56 00 41 00 50 00 49 00 5c 00 7b 00 30 00 2e 00 V.A.P.I.\.{.0...
01f0: 30 00 2e 00 30 00 2e 00 30 00 30 00 30 00 30 00 0...0...0.0.0.0.
0200: 30 00 30 00 30 00 30 00 7d 00 2e 00 7b 00 32 00 0.0.0.0.}...{.2.
0210: 33 00 35 00 33 00 34 00 39 00 65 00 37 00 2d 00 3.5.3.4.9.e.7.-.
0220: 39 00 39 00 66 00 62 00 2d 00 34 00 31 00 31 00 9.9.f.b.-.4.1.1.
0230: 36 00 2d 00 61 00 37 00 65 00 37 00 2d 00 31 00 6.-.a.7.e.7.-.1.
0240: 33 00 37 00 37 00 64 00 34 00 63 00 34 00 37 00 3.7.7.d.4.c.4.7.
0250: 30 00 36 00 34 00 7d 00 00 00 00 00 00 00 00 00 0.6.4.}.........
0260: 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ...............
0270: 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0280: 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 ................
0290: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
02a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
02b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
02c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
02d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
02e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
02f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0310: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0320: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0330: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0340: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0350: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0360: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0370: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0380: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0390: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
03a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
03b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
03c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
03d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
03e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
03f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0400: 00 00 00 00 00 00 00 00 0d 00 00 0d 88 05 19 00 ...............
0410: 10 54 93 11 b4 02 00 00 00 aa 9b 0f b4 02 00 00 .T.´....ª.´...
0420: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0430: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0440: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0450: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0460: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0470: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................

**Comment by clsid2** [comment]
Thanks for the info. Which version of Windows 10 do you use? Does 10-bit work ok?

**Comment by exegg** [comment]
> Thanks for the info. Which version of Windows 10 do you use? Does 10-bit work ok?

Yes, both 8 and 10 bit work just fine. I use Windows 10 LTSC 1809

**Comment by clsid2** [comment]
MPC-HC 1.9.0 has a workaround for this driver issue. It won't use P016 when connecting to EVR renderer.

**Comment by exegg** [comment]
Yup, 12 bit works now on EVR :D
Even then, this only reminded me to look out for at least an i3 since it is pushing the limits of my current CPU or get a GPU that takes it... Wonder if there's any hardware support for 12 bit HEVC...
Anyways, thanks for your work and your time
