### ISSUE TITLE
A little bug with 2 videos in the same mkv with 2 different time

### ISSUE THREAD

**Issue by KyotoIro** [clsid2/mpc-hc#1870]
Hello,

Thanks for mpc-hd :)

I've find a little problem with 2 videos in the same mkv with 2 different time. If the 1st video is more short than the 2nd. The time bar is stop a the first end video but if the sound corresponds to the second video, we still hear it but the bar is stopped.

If neccessary, i've an exemple file.

Thanks

**Comment by clsid2** [comment]
Sample file is required.

But big chance I am not going to fix it.
