### ISSUE TITLE
DPI Scaling Issue with Multiple Monitors and Different DPIs

### ISSUE THREAD

**Issue by gashtal** [clsid2/mpc-hc#1871]
I have a 4k monitor on which I use 200% DPI scaling. I started using the Dark mode of MPC-HC today, but the dark mode in particular does not seem to support text scaling for menus, while the light theme does. Also neither the dark mode nor the light mode seem to support text scaling of the content of the status bar. This makes the text near-impossible to see on my TV. I am using the latest v1.9.23. I was hoping these issues could be addressed in the next version.

**Screenshots (important parts are highlighted with red boxes):**

Light mode:
![Light Mode](https://user-images.githubusercontent.com/27990818/194803419-4e75ee6e-b7da-4e22-a106-5e770315cc23.jpg)

Dark mode:
![Dark mode](https://user-images.githubusercontent.com/27990818/194803423-a3615239-7867-4344-9e63-afb1cab003e1.jpg)

**Comment by clsid2** [comment]
It does support DPI text scaling. So you must be running the player in some kind of compatibility mode. Or you didn't restart the player after switching theme.

**Comment by gashtal** [comment]
I am not running in any compatibility mode and player was restarted after switching theme as the theme won't switch without a restart.

In light mode everything (title bar, menu bar, menus, buttons) scales fine with HiDPI except status bar. In Dark mode only title bar and buttons scale, but menu bar, menus and status bar don't.

**Comment by clsid2** [comment]
Here both themes have identical size.

**Comment by gashtal** [comment]
Further testing shows that the issue is related to multi-monitor and probably MPC-HC setting some scale factors based on the DPI of the main monitor, instead of the active monitor. If I change the DPI on my main monitor and keep MPC-HC's window in the same monitor, all fields scale fine in both themes. On the other hand, if I change the DPI on any secondary monitor and move MPC-HC's window to that monitor, then the status bar doesn't scale in the light theme, and menu bar, menus, and status bar won't scale in the dark theme.

For example, if I set DPI to 100% on my main monitor, and 200% on my second monitor, when I drag MPC-HC's window from the main monitor to the second monitor:

- **Light mode:** Title bar, menu bar and buttons immediately enlarge, but status bar doesn't change and remains at 100% DPI.
- **Dark Mode:** Title bar and buttons immediately enlarge, but other elements remain at 100% DPI.

Similarly, if I set main monitor to 200% but second monitor to 100%, elements that remained at 100% DPI in the experiment above, will remain at 200% instead and won't scale down.

**Comment by gashtal** [comment]
@clsid2 Any luck reproducing this with two monitors having different DPI factors?

**Comment by gashtal** [comment]
@clsid2 Any hope of a resolution to this issue?

**Comment by svatoupravdu** [comment]
I can confirm this erratic behavior: 
**LIGHT MODE**: status and info pane font doesn't scale according to Windows DPI setting and is always at 100 %. Everything else works OK, even when dragging player from one monitor with 100 % DPI to another with higher DPI.
**DARK MODE**: status and info pane font still doesn't scale at all. Main menu font doesn't get rescaled when the window is
 moved from high DPI monitor to normal DPI monitor and thus remains too large. And vice versa.

**Comment by adipose** [comment]
I will have to look at this.  A number of custom hooks are related to dark theme and multi monitor dpi has been complicated.  I thought most things were working including dragging.

**Comment by gashtal** [comment]
@adipose Greatly appreciate you looking into this.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2128

I think this should solve most of these issues.

**Comment by clsid2** [comment]
New development build is available for testing.

**Comment by gashtal** [comment]
@adipose Fantastic, thank you very much for looking into this. I just tested build 2.0.0.51 and I can confirm that both the menu bar and status bar scale correctly when MPC-HC is moved across monitors with different DPIs. However, there still seems to be a minor issue with the right click menu, only in **_dark mode_**:

If the right click menu is opened in one monitor with a specific DPI for the first time, and then MPC-HC is moved to another display with a different DPI, even though the size of the font inside the menu scales correctly, the size of the menu itself does not. This only seems to happen in dark mode, and doesn't happen in light mode. The size of the menu seems to get locked to the DPI of whichever display it is opened in for the first time, and gets reset when MPC-HC is closed and opened again, so this might be caching issue. This issue doesn't seem to apply to sub-menus of the right click menu and sub-menus seem to always open with correct font and menu size.

**Examples:**

Menu opened in 100% DPI display for first time:

![image](https://github.com/clsid2/mpc-hc/assets/27990818/b4a4f3d2-405b-4d26-b84a-7a901cdc57a1)

MPC-HC moved to 200% DPI display and menu opened again:

![image](https://github.com/clsid2/mpc-hc/assets/27990818/728f9097-dc46-43a6-8811-d395c7cea788)

Menu opened in 200% DPI display for first time:

![image](https://github.com/clsid2/mpc-hc/assets/27990818/c17cc7be-3d01-4727-a195-22ed159fb6c8)

MPC-HC moved to 100% DPI display and menu opened again:

![image](https://github.com/clsid2/mpc-hc/assets/27990818/9a021b87-4ef4-4369-a864-b018cef61e5e)

Sub-menu scales correctly even though main menu does not:

![image](https://github.com/clsid2/mpc-hc/assets/27990818/4b70ec38-83e3-415a-858c-35a1d39f8ac2)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2136

**Comment by gashtal** [comment]
@adipose Thank you for fixing the last issue. I just found another corner case. Looks like if MPC-HC is opened directly on the non-main monitor, rather than opened on the main monitor and moved to the non-main monitor, DPI scaling still doesn't happen. Screenshots are below:

When opened on main 100% DPI monitor and moved to non-main 200% DPI monitor (correct DPI scaling):

![1](https://github.com/clsid2/mpc-hc/assets/27990818/34b8dbbc-5c7e-4ff7-a8f2-fb940f09f265)

When opened on non-main 200% DPI monitor directly (no DPI scaling):

![2](https://github.com/clsid2/mpc-hc/assets/27990818/e3268c3c-a54b-43ee-9e83-50bca00b0321)

**Comment by adipose** [comment]
@clsid2 we can reopen this.

**Comment by adipose** [comment]
> @adipose Thank you for fixing the last issue. I just found another corner case. Looks like if MPC-HC is opened directly on the non-main monitor, rather than opened on the main monitor and moved to the non-main monitor, DPI scaling still doesn't happen. Screenshots are below:

I can confirm it behaves differently if you start it from a different monitor.  If you open it from monitor 1, but it was last on monitor 2, it is ok.  But if you actually launch if from monitor 2 (desktop for example), it behaves differently.  Hard to debug this, but I'll take a look.

**Comment by adipose** [comment]
> @adipose Thank you for fixing the last issue. I just found another corner case. Looks like if MPC-HC is opened directly on the non-main monitor, rather than opened on the main monitor and moved to the non-main monitor, DPI scaling still doesn't happen. Screenshots are below:

https://github.com/clsid2/mpc-hc/pull/2154

I believe this should fix your issue and one more with the playlist.

**Comment by adipose** [comment]
@clsid2 , the same playlist issue theoretically can affect the subresync tb, but I cannot identify any case in which it can be open upon player launch.  Do you know a way?

**Comment by clsid2** [comment]
No, I think that can only be opened later.

**Comment by adipose** [comment]
@gashtal , can you test and report back?

**Comment by gashtal** [comment]
@adipose Just tested build 2.0.0.70. Indeed the font scaling issue is largely fixed when MPC-HC is opened directly from a HiDPI display. However, the status bar is still abnormally large in this case, and the text in the status bar is still not scaling with DPI:

When opened on main 100% DPI monitor and moved to non-main 200% DPI monitor (correct status bar scaling):

![1](https://github.com/clsid2/mpc-hc/assets/27990818/a48b7f4c-ff9f-45e2-a48f-987dd54de18f)

When opened on non-main 200% DPI monitor directly (incorrect status bar scaling):

![2](https://github.com/clsid2/mpc-hc/assets/27990818/722644c3-2a8a-44be-91e6-b2922cf49454)

Hoping this is the last corner-case that needs to be fixed. 😓

**Comment by adipose** [comment]
> @adipose Just tested build 2.0.0.70. Indeed the font scaling issue is largely fixed when MPC-HC is opened directly from a HiDPI display. However, the status bar is still abnormally large in this case, and the text in the status bar is still not scaling with DPI:
> 
> When opened on main 100% DPI monitor and moved to non-main 200% DPI monitor (correct status bar scaling):
> 
> When opened on non-main 200% DPI monitor directly (incorrect status bar scaling):
> 
> Hoping this is the last corner-case that needs to be fixed. 😓

https://github.com/clsid2/mpc-hc/pull/2160

Similar issue to the playlist I fixed before.  We hijack the built-in measure code and scale it to our DPI.  The problem is the built-in code remembers the old DPI and keeps returning bad values.  Since we are using custom code to measure (OnMeasureItem and CalcFixedLayout), we have to deal with this old cached dpi somehow.

A better solution probably is to reverse engineer the sizing calculators.  One thing I observed here is that we get inexact scaling.  For example the preferred height is 19 @ 96dpi but 36 @ 192dpi.  When we do a dpi scale we end up with 18px instead of 19px.  So it's subtlely different when you move monitors vs. starting on a specific monitor.

**Comment by gashtal** [comment]
Great, thank you for fixing this. When the changes are merged and new build is available, I can test and report back.

**Comment by adipose** [comment]
https://mega.nz/file/8A5EgDCD#QJ2YJ_gA8vMfsPKebmN4xpi-ciBwtqf6cHxELWtEXC8

Here's a test build.

**Comment by gashtal** [comment]
I did a quick test and indeed it seems the issue is resolved; thank you for your diligence in fixing the DPI scaling issues!

**Comment by adipose** [comment]
> I did a quick test and indeed it seems the issue is resolved; thank you for your diligence in fixing the DPI scaling issues!

Thank you for the feedback and testing!
