### ISSUE TITLE
Audio crossfeed filter reduces higher frequencies

### ISSUE THREAD

**Issue by nji9nji9** [clsid2/mpc-hc#1873]
I recently noticed that using the crossfeed filter
(Audio renderer / Options / stereo crossfeed,
both flavours, default settings)
significantly reduces frequencies up from 400 Hz
to about 2dB.
I noticed it when hearing my music with foobar2000
and its crossfeed filter.

Reproducing:
Record an audio playing with mpc-hc.
Compare the frequency responses (with an audio editor)
of orig and record.
foobar2000, with or without meyer-crossfeed
doesn't have that effect on freq. response.
(Sorry, I still use mpc v.1.8.7-64 bit. But maybe
you didn't change anything on crossfeed since then).

**Comment by clsid2** [comment]
Bug reports for old versions are invalid.

I know nothing about this filter, so I can't improve it.

**Comment by nji9nji9** [comment]
Sorry for that.
I thought you might be interested in severe degradation of sound quality,
that would affect most of the audiophile headphone users.
