### ISSUE TITLE
Requires adobe flash player for ie with killswitch patch

### ISSUE THREAD

**Issue by lynrayy** [clsid2/mpc-hc#1874]
Requires adobe flash player for ie with killswitch patch. What i supposed to do? Where can i get patched flash player for windows 10?
Don't tell me that flash is dead, i do not care. I want to check old flash games and old YT flash player. Just give me link to patched flash or instruction how to get it
![image](https://user-images.githubusercontent.com/59417884/195248229-8b5c9cca-9838-4fe2-9246-20493ef2ea2f.png)

**Comment by clsid2** [comment]
FLASH IS DEAD !!!!!!!!!!!!!!!!!!!!!!!!!!!!

A 5 second search would give you this:
https://github.com/darktohka/FlashPatch

**Comment by lynrayy** [comment]
_FLASH IS DEAD !!!!!!!!!!!!!!!!!!!!!!!!!!!!

A 5 second search would give you this:
https://github.com/darktohka/FlashPatch_

But it says:
![image](https://user-images.githubusercontent.com/59417884/195329408-7d28db68-3951-4b29-bbe5-b3e07873b076.png)

**Comment by clsid2** [comment]
You need to install the Flash ActiveX plugin for IE. That is literally what the player tells you.
