### ISSUE TITLE
Bug in built-in stereo crossfeed

### ISSUE THREAD

**Issue by nji9nji9** [clsid2/mpc-hc#1875]
I'm with MPC-HC for movies and audios since many years
being satisfied with it.
As mostly I use (quite good) headphones the (built-in!)
crossfeed filter in MPC-HC is compulsory for me.
Recently it seemed to me that the crossfeed option makes
the sound "muffled".
I had a closer look at the frequency responses
of (newest versions of) MPC-HC and foobar2000,
both with and without meyer crossfeed.
It showed that all are very similiar, with the exception
of MPC-HC with crossfeed enabled.
(Audio renderer / Options / stereo crossfeed,
both flavours, default settings).
I think this is a fundamental bug of MPC-HC
 - as audio via headphone is important and
 - as it concerns many users.

I tried to delete my obsolete issue
https://github.com/clsid2/mpc-hc/issues/1873
but didn't succeed.

![mpc_with_crossfeed](https://user-images.githubusercontent.com/29798181/195324918-a09f81a7-5ddc-4cc2-aff6-d33c1385a2d4.png)

**Comment by clsid2** [comment]
I already told you that I can't fix it.

**Comment by nji9nji9** [comment]
A misunderstanding, I beg your pardon.
I thought you would think that "filter" was extern
and not of importance.
Now I got it :)

BUT...
This is the end of MPC-HC.
At least for me.
I can't tolerate an unnecessary degradation of sound
due to a bug.
It would be like accepting "greenish" movies etc.

Sad, as MPC's user interface was exact to my needs
and liking. So far I don't know of any similiar.

P.S.
If that code is too specific for _you_,
what about this (especially the last posts)?
https://hydrogenaud.io/index.php?PHPSESSID=tr84jtcgfqnjp3qblhon15b3a7&topic=108412.50

**Comment by nji9nji9** [comment]
Addendum:
Having read some articles about crossfeed
I'm not so sure anymore if MPC's crossfeed is wrong
but foobar2000's...
(As crossfeed seems to "mono" a stereo signal more at low frequencies.
And "mono-ing" reduces loudness...)

**Comment by nji9nji9** [comment]
Having read some articles about crossfeed
I'm not so sure anymore if MPC's crossfeed is wrong
but foobar2000's...
https://www.head-fi.org/threads/crossfeed-frequency-response.652172/
