### ISSUE TITLE
Wrong keyboard layout for hotkeys

### ISSUE THREAD

**Issue by Rikk** [clsid2/mpc-hc#1877]
I was updating from 1.9.11 to 1.9.23, and while looking for new things I found `ShowABMarksInStatusbar` option, then I decided to learn how to use A-B Markers. I was wondering why it was not working properly. Finally, I found that MPC-HC is not using my correct keyboard layout.

For example, I can type `[` and `]` properly in search box (Options/Keys), so it's not a problem in Windows:
![ab-marker-bug 1](https://user-images.githubusercontent.com/2916485/195777794-cf6f4293-0ef5-4ba1-94db-b8c054ee0469.png)

But when I try to input the same default keys (`[` and `]`), the problem is revealed:
![ab-marker-bug 2](https://user-images.githubusercontent.com/2916485/195778119-aee04bf6-57bc-46b1-9159-854d813d8e50.png)

Conclusion: not only Options/Keys is using wrong keyboard layout, but also the player itself.

PS: both 1.9.11 and 1.9.23 are affected.

**Comment by clsid2** [comment]
You are the only one for which it is incorrect. The problem is at your end, not in the player.

Options > Miscellaneous > Reset

**Comment by Rikk** [comment]
I also tested with a clean portable install of mpc-hc before posting.
Do you know another program that implements hotkeys like mpc-hc, so I can test? Because I don't have another program behaving this way.

**Comment by Rikk** [comment]
> Options > Miscellaneous > Reset

I tested with a clean portable profile before posting...

But yeah, it seems something on my side, at least partially. While most programs can properly detect all pressed keys, others like MPC-HC (at options/keys) and Vivaldi browser (at settings/keyboard) fail for some keys. Perhaps, it could be a Windows 10 LTSC bug on the api you use -- btw, LTSC seems to have some nasty bugs regarding typing (eg. emoji panel never open). Hard to find the exact cause.

**Comment by clsid2** [comment]
Installing the Store might help with the keyboard issue:
https://www.reddit.com/r/Windows10LTSC/comments/sd8e22/windows_10_ltsc_2021_touch_screen_keyboard_fix/

Also check if there are multiple keyboard layouts enabled in the Windows settings. Remove the ones that you don't need.

**Comment by Rikk** [comment]
(_I'm writing this as a simple suggestion of a possible path to follow, my knowledge on the matter is very basic, therefore an experienced dev like @clsid2 will find a proper solution (on his time)_)

I've done a basic investigation of how the [virtual keys codes](https://github.com/clsid2/mpc-hc/blob/develop/src/mpc-hc/vkCodes.cpp) are mapped by mpc-hc, the [official doc](https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) etc...

As it seems, we map the virtual key codes manually similarly to the suggestion of the MS docs, but as noted, these suggestions are better suited for "US standard keyboard".

Using a very basic [keylogger](https://github.com/nemzutkovic/Windows-Keylogger/blob/master/keylogger.cpp) I learned how our mechanism works. It also doesn't properly translate especial key names (eg `´` `[` `ç` `~` `]`) for non-us keyboards like mine.

A simple test using [`MapVirtualKey`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapvirtualkeya) and [`GetKeyNameText`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeynametexta) functions ([example 1](https://stackoverflow.com/a/38107083)/[example 2](https://stackoverflow.com/questions/38584015/using-getkeynametext-with-special-keys)) we can get correct translation of key names. My keyboard keys `´` `[` `ç` `~` `]` become `AGUDO` `[` `ç` `TIL` `]` (maybe some adjustments will be needed to fix these two translated to input locale*). If we use the conversion of MPC, it becomes `[` `]` `;` `'` `\` (completely wrong).

In initial example of this Issue, `[` and `]` are the defaults for Mark A and B, respectively.
Comparing the hexadecimal value of the `vkCodes`, in my keyboard the key `[` is translated to 0xDD (`VK_OEM_6`), however, the [docs](https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) (and mpc) translates `[` to 0xDB (`VK_OEM_4`) (US Std Keyboard). Similarly, `]` is 0xDC (`VK_OEM_5`) (in docs: 0xDD VK_OEM_6).

Finally, this problem is very confusing to me, I don't know if a better implementation of the Keys Options would be to save keys as names (eg. `[`) and translate them using an official c++ function. Currently, I see MPC saves as hex in the .ini file and translates them to names using the [manual conversion](https://github.com/clsid2/mpc-hc/blob/develop/src/mpc-hc/vkCodes.cpp), often with errors for non-US keyboards.

___

*From [`GetKeyNameText`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeynametexta):
> Remarks
> The format of the key-name string depends on the current keyboard layout. The keyboard driver maintains a list of names in the form of character strings for keys with names longer than a single character. The key name is translated according to the layout of the currently installed keyboard, thus the function may give different results for different input locales. The name of a character key is the character itself. The names of dead keys are spelled out in full.

**Comment by clsid2** [comment]
GetKeyNameText is buggy as well, so not a good alternative for the hardcoded table:
https://stackoverflow.com/questions/58760357/getkeynametext-numpad-missing-text

You should just type the correct key and just ignore what is being displayed.
