### ISSUE TITLE
MPC frame-steps instead of moving through menus

### ISSUE THREAD

**Issue by M3n747** [clsid2/mpc-hc#1879]
1. Open a video, let it play.
2. Press Alt to activate the menu bar and down to access the File menu.
3. Press left twice to move the cursor over to the Help menu - notice that Help is highlighted, but not open.
4. Press left once more to move over to the Favourites menu.
5. Instead of moving the cursor to the Favourites menu, pressing left now frame-steps the video.

The frame-step also occurs if you press right instead of left in step 4 (only in the opposite direction). Also, if you open the File menu in step 2 and move the cursor to the right instead of left, the bug will occur after you move the cursor over from the Help menu to the File menu. It will not happen, however, if the menus are only highlighted but not open.

I found the bug in MPC-HC (CCCP Build, 64-bit) version 1.7.8.162 (ff72737) but it's still present in version 1.9.23 (a8e9113b5) , both x32 and x64. I'm using Windows 10 build 1809, version 10.0.17763 (64-bit).

**Comment by clsid2** [comment]
Looks like a Windows (MFC) bug to me. It is not worth my time to investigate any further.

**Comment by Rikk** [comment]
Imo, it would be interesting to investigate this in the future.
Other programs that use menus (eg. Notepad++, LibreOffice, Process Explorer, Internet Explorer) doesn't transfer focus to content area when walking through menus using keyboard arrows.
