### ISSUE TITLE
Drop down menu in cumulative update for Win11 Version 22H2 x64 

### ISSUE THREAD

**Issue by Xamo76** [clsid2/mpc-hc#1881]
It seems that after the cumulative update to Windows 11 Version 22H2 x64 none of the drop down menus no longer function. I have uninstalled the package, reinstalled and have tried the portable version all to no avail... has anyone else experienced this issue?

![MPC-HC](https://user-images.githubusercontent.com/115960926/196075924-2e7e47ab-cf0a-4264-95a2-424c683b84e6.jpg)

**Comment by Remi-Turcotte** [comment]
Yup! same here:
Windows 11 Version 22H2 x64 none of the drop down menus no longer function.

**Comment by abmprottoy** [comment]
Just tried the portable version to check. I did not have it installed before the update.
It's working for me.

![image](https://user-images.githubusercontent.com/115341293/197079857-908325af-11a5-4c0a-8112-d299fbbafd15.png)

**Comment by Remi-Turcotte** [comment]
> 
(didn't think about tryin the portable version, good one)
Noticed I was a "windows update" behind you, tried again (including portable) Same win same build, no luck... :(

**Comment by icedterminal** [comment]
All good here. Please start with a Windows repair and then reboot.

`dism /online /cleanup-image /restorehealth`

https://user-images.githubusercontent.com/4755734/197113390-07b363f4-9b7f-4f54-a092-8a24ca9cd810.mp4

**Comment by clsid2** [comment]
Could also be a graphics driver bug, given that many parts of the Windows GUI use hardware acceleration.

**Comment by abmprottoy** [comment]
There were also two new .NET Framework update for 22H2. KB5017859 and KB5017271. It fixed various WinForms, WPF and other related bugs for Windows 11 systems. Do you have them installed?

**Comment by clsid2** [comment]
MPC-HC does not use .NET.
It uses MFC for GUI.

**Comment by Remi-Turcotte** [comment]
waddayaknow, tried again the portable version: works... guess a winupdate fixed it ;)

**Comment by clsid2** [comment]
Installer and portable ZIP version contain identical application.
