### ISSUE TITLE
Add chapter markers with name to a video from a txt file

### ISSUE THREAD

**Issue by YahyaAlameddine** [clsid2/mpc-hc#1882]
How can i import chapters' locations and names from a txt file to a video file?

Thanks

**Comment by clsid2** [comment]
If you would have read the changelog you would have found this:
> Now supports loading chapter metadata from .xchp file. Use text file (UTF-8 encoding). Each line is a chapter defined as HH:MM:SS,ddd timecode, optionally followed by a space and chapter name.
