### ISSUE TITLE
mpc hc crashes/stops responding if discord application share is on

### ISSUE THREAD

**Issue by ferrobolt95** [clsid2/mpc-hc#1884]
mpc hc crashes frequently if using application screen share from discord. Very easy to reproduce.
Start any media in mpc hc > run discord and select screen share, select mpc hc application > double click for fullscreen on mpc hc to easily reproduce.
It may also crash on pause/play, or while seeking, or changing audio/subtitles.

**Comment by clsid2** [comment]
Discord settings > Voice & Video > disable "Use our latest technology to capture your screen"

**Comment by ferrobolt95** [comment]
Thank you very much!! This is the best media player I have ever used!
