### ISSUE TITLE
[bug] 2 problems relating to subtitle

### ISSUE THREAD

**Issue by Max33Verstappen** [clsid2/mpc-hc#1885]
- 1st problem:
Switching from PGS to text-based subs results in the text-based subs being in the wrong aspect ratio (It seems they're stretched to the AR of the monitor at this point. ). You must resize the window or exit then re-enter the fullscreen to get it right.
Also note that this is when "Position subtitles relative to the video frame" is **un-checked**. When it's **checked**, switching makes the text subs completely missing, while **half-checked** makes them rendered on weird positions.
Wrong AR:
![2022-10-23_16 55 00 597_mpc-hc64_wrong](https://user-images.githubusercontent.com/97274607/197384020-0a0a0349-8f3f-40c2-bd98-14df574a55ff.jpg)
Correct AR after resizing the window:
![2022-10-23_16 55 20 561_mpc-hc64_right](https://user-images.githubusercontent.com/97274607/197384030-f0f8bb4e-0e12-4f24-a1df-1d0a4627fde6.jpg)

- 2nd problem:
PGS subtitles captured in the image have the wrong AR. This might be the cause of having a monitor AR different than the video.
![mpc-hc_Capture_wrongAR](https://user-images.githubusercontent.com/97274607/197384375-d8723e65-1f00-4e4e-a5e0-3501f8228076.jpg)
Should be:
![2022-10-23_16 54 05 723_mpc-hc64_Capture_CorrectAR](https://user-images.githubusercontent.com/97274607/197384413-4f4ea6a9-36c3-491e-8b37-17df75c7ce90.jpg)

**Comment by clsid2** [comment]
I need a link to this video.

The capture issue is because the video has different resolution than the PGS. There already is an open issue for that. I can't fix it as that part of the code is very complicated and my time for working on MPC is limited.

**Comment by Max33Verstappen** [comment]
Ok, the capture issue is no big deal. I just came across it when I used it to capture the subtitle for the 1st problem.

Link is here:
https://disk.yandex.com/d/2fmJw--pHq-nyQ
I don't know if you can reproduce. I also tested on other videos and found it's not just for this specific video and others also have this problem. (I also reset the setting but same problem).
Note that to easily observe this issue, you must stretch the playing window, so it has a different AR than the video, and then switch from PGS to srt/ass etc.

**Comment by clsid2** [comment]
Fixed first issue.
