### ISSUE TITLE
YCbCr Matrix header isn't fully compatible with XySubFilter and libass

### ISSUE THREAD

**Issue by TheOneric** [clsid2/mpc-hc#1886]
From reading the current code
https://github.com/clsid2/mpc-hc/blob/bb9223e0c6bbcd0947b38a914a22da39f4499c29/src/Subtitles/RTS.cpp#L3477-L3504
it appears to me as if MPC-HC’s ISR defaults to using effectively no colour mangling (by using the video colourspace) if no header was set and doesn't explicitly implement`YCbCr Matrix: None`. `None` is a special header value to opt out of any colour mangling as far as possible for the renderer. Instead though all unknown values *(so including `None`)* are assigned `ColorConvTable::NONE`.
I'm not sure where this value is later used by ISR for ASS subs, but from the conditionals for `::NONE` in [PGSSub.cpp](https://github.com/clsid2/mpc-hc/blob/29a1254b5d4cadd3916b3ae4d3456bc3410af213/src/Subtitles/PGSSub.cpp#L250) and [DVBSub.cpp](https://github.com/clsid2/mpc-hc/blob/29a1254b5d4cadd3916b3ae4d3456bc3410af213/src/Subtitles/DVBSub.cpp#L104) it appears like this amounts to a resolution dependent guess between `TV.601` and `TV.709`.

Regardless of what `::NONE` really does, this doesn't line up with xy-VSFilter/XySubFilter's behaviour and libass' recommendations as `YCbCr Matrix: None` should be different from an invalid value.
No header or an invalid value should be equal to an explicit `TV.601` and while xy-VSFilter (but not XySubFilter) does a similar guessing for explicit `None`, it only does so due to lack of actual colour information which ISR appears to have. Assuming you want ISR to be more compatible with other renderers *(and if I understood the code correctly)*, I suggest using `yuvVideoMatrix` for `YCbCr Matrix: None` and equate no or an invalid header to `"TV.601"`.
For more information and some historic background, see e.g. libass docs:
https://github.com/libass/libass/blob/5f57443f1784434fe8961275da08be6d6febc688/libass/ass_types.h#L152-L199

Also the libass rendering backend should read `track->YCbCrMatrix` and deal with it as described in the above docs. It appears like this field is currently unused. *(Same for `ass_set_storage_size` but that's unrelated to colour mangling.)*

**Comment by clsid2** [comment]
> I suggest using yuvVideoMatrix for YCbCr Matrix: None and equate no or an invalid header to "TV.601".

It already does that.
If you have a sample that renders with wrong colors, then provide that sample.

**Comment by TheOneric** [comment]
Sometimes issues pop up about this with samples in the trackers of misconfigured libass users, but the last sample and only one I have at hand right now, won't show a big difference for what MPC-HC ISR does here. Not every colour and matrix mismatch produces a large deviation in the final output, but some do. (And I cannot test MPC-HC ISR myself btw).
I filed this issue since you asked for tickets about incompatibilities and from the cited code excerpt it seems impossible to me for the header to always be handled correctly. In particular `YCbCr Matrix: None` which isn't even explicitly handled at all, seems troublesome.

It's certainly possible I missed or misunderstood something about MPC-HC ISR's pipeline though. I'm not too familiar with it after all. In that case it would be great if you could explain to me how the colour mangling process works in ISR. Related question: does MPC-HC output final subtitles as sRGB or does it output YUV frames? *(Depending on this ISR can completly skip any mangling for `None` or only avoid most mangling effects by using the video matrix for RGB to YUV conversion.)*

Now with how I understood the cited code, here's what seems problematic to me in more detail:

**Case 1: No YCbCr header or an empty `YCbCr:`**

The `!m_sYCbCrMatrix.isEmpty()` will fail and the video colourspace be parsed.
This will be wrong unless the video colourspace by incident happens to be TV-range BT601.

**Case 2: `YCbCr Matrix: None` or `YCbCr Matrix: Invalid`**

The `!m_sYCbCrMatrix.isEmpty()` will succeed and the parser will receive either `None` or `Invalid`. Regardless of what the absence of a dot means for the resulting `range` and `matrix` values, those won't match anything. The final result is `yuvRange = ColorConvTable::RANGE_TV;` and `yuvMatrix = ColorConvTable::NONE;`.<br />

Now we have roughly three options and none is fully correct.
  1) `::NONE` equates to `::BT601`. Then `Invalid` is correct but `None` incorrect, since the latter should avoid mangling.
  2) `::NONE` equates to a resolution dependent guess like for PGSSubs. In that case the result for `None` is similar to xy-VSFilter, but suboptimal and different from from XySubFilter and libass if the guess was wrong. `Invalid` will be wrong for all video resolutions not resulting in `::BT601`.
  3) `::NONE` does actually fully avoid colour mangling (including ignoring the limited range for full-range video). Then `None` was dealt with correctly, but `Invalid` is dealt with incorrectly.

---

For the libass backend I'm fairly certain though that it is handled incorrect, since the parsed value is never read. (cc @adipose)

**Comment by clsid2** [comment]
The libass backend is not in use yet.

It outputs to RGB.

I need samples to test, and if nobody can provide me anything that obviously renders wrong, then I won't spend any time on this.

**Comment by clsid2** [comment]
Torrent links for any existing anime release are fine btw. I can remove those comments after I use the links.

**Comment by TheOneric** [comment]
Well, since I don't and cannot use MPC-HC ISR, I also won't notice when a script is affected by this. Not knowing what `::NONE` actually does makes it all the harder to search for a sample. I guess you can just take this as a heads up then for ISR, so you know where to look for when eventually someone reports mismatching colours for a sample.

For the libass backend though, you may want to consider implementing colour mangling before it is being made available to users even without samples. libass docs clearly state this being required for accurate rendering *(see OP)*.

**Comment by clsid2** [comment]
Any good sample with an explicit NONE would be helpful.

NONE currently equals BT.601(TV), which results in no mangling afaik.

**Comment by VincentOpel** [comment]
I don't know if I have that specific problem but I have several videos of a series that have false colors. The Netflix logo is orange for example and all the colors look washed out. One video is 1.4Gb so I don't know how to host it best. 
[Arcane MediaInfo.txt](https://github.com/clsid2/mpc-hc/files/9883599/Arcane.MediaInfo.txt)

**Comment by VincentOpel** [comment]
<img width="1762" alt="Screenshot 2022-10-28 004220" src="https://user-images.githubusercontent.com/116849331/198411596-029d261d-e703-4093-9443-e5b426d16343.png">
MPC new install; latest stable version and VLC side by side.

**Comment by clsid2** [comment]
Fort HDR video you need to use a compatible video renderer. Either MPC Video Renderer or MadVR. Your problem is unrelated to subtitles.

**Comment by TheOneric** [comment]
> NONE currently equals BT.601(TV), which results in no mangling afaik.

It does. One reason being “TV” means the luminance range is limited, so not all sRGB colours can be represented. The other being, that many (e.g. most non-HDR HD videos) using a different colourspace than ASS' BT.601 leading to a colour shift.

E.g. here's an example extracted from a report about some `YCbCR Matrix: TV.601` subs which were paired with some `BT.709` (likely TV-range) video. The original release was reported to be `[SakuraCircle] Acchi Kocchi - 09 (BD 1920x1080 HEVC FLAC) [CB0433CA].mkv`, though I only ever looked at provided screenshots and ASS excerpt, never the full original file.

The ASS subs specify `\c&HA184F4&`, i.e. directly translated to sRGB `0xf484a1`, for a vector drawing hiding the original Japanese Text. But the expected final output colour is sRGB `0xfd90a1` to match the background from the video.
If there's no mangling at all (i.e. ideal `None`) and in this case despite the limited range also when `TV.709` is used instead of `TV.601` the output colour will be `0xf484a1` matching what's specified in the subs rather than what's in the original video.

Here's an archive with this example but a replacement video: [test_headers.zip](https://github.com/clsid2/mpc-hc/files/9891333/test_headers.zip). To create the video with appropriate colourspace from the image I used:
```sh
# ffv1 is a lossless codec used here to avoid any more colour shifts apart from what's necessary for the conversion
ffmpeg -loop 1 -i colourrange+space_test_original.png -t 5 \
  -vf scale=out_color_matrix=bt709 -c:v ffv1 -pix_fmt yuv420p \
  -color_range 1 -color_primaries bt709 -color_trc bt709 -colorspace bt709 \
  test_tv.709.mkv
```
Note that the sRGB to YUV420-BT.709 conversion already wasn't lossless, but it is barely noticeable. The ASS excerpt is provided in four variants only differing by the `YCbCr` header: `TV.601` (the original one), `TV.709`, `None` and “no header”. This is not exhausitive though, so if you want you can experiment with more valid and invalid header values, an empty header and video colourspaces.

**Comment by clsid2** [comment]
What should be the behavior in case of no header in the script, and video renderer specifies NONE? Use untouched RGB?

**Comment by TheOneric** [comment]
I don't know what madVR or any other video render mean with video colourspace "NONE".

**If** it means the video itself is native (s)RGB and not YUV, then this is an interesting case regardless of what header the subs use and one I haven't seen in distributed videos yet.
mpv with `sub-ass-vsfilter-color-compat=full` on a GBR video results in heavily skewed colours likely from following through with the mangling formula and interpreting the luminance channel as another colour channel. A first check with xy-VSFilter suggests, that if the video already is native RGB, as a special case subs are treated as if `YCbCr Matrix: None` were specified regardless of what the file actually does. If that turns out to also be the case for XySubFilter+madVR, I'll need to update our docs and fix or inform mpv.

**Comment by clsid2** [comment]
MadVR has an option that controls whether it sends the colorspace info or NONE. So the value isn't for native RGB video.

madvr settings > rendering > trade quality for performance > optimize subtitle quality for performance instead of quality

Enabled by default and that gives colorspace info. Disabling gives NONE. I am not sure if MadVR does any internal color adjustments in that case.

http://bugs.madshi.net/view.php?id=276

**Comment by TheOneric** [comment]
This means madVR's `NONE` stands for “unknown video colourspace”, right?
If the video colourspace is not known, the mangling cannot be done correctly for all cases anyway. I'd say just do what makes most sense to you in that case. Using untouched RGB as you mentioned seems fine.

**Comment by TheOneric** [comment]
Thanks for implementing `None`!
Looking at the current code though, I suspect the “no header” and “empty header” cases still aren't handled correctly. They should be equivalent to an explicit `"TV.601"` but the video colourspace being parsed in the final `else` clause makes me think it will be similar'ish to `None` instead.
Just to be sure, could you check the `no-header.ass` sample I linked earlier again?

https://github.com/clsid2/mpc-hc/blob/4bd69a95c9472ec0234282039faf74cad63fd46f/src/Subtitles/RTS.cpp#L3478-L3516

**Comment by clsid2** [comment]
In that case either the value of the header or the absence of the header will always control the parameters used. The info from the video decoder/renderer is then never needed/used for ASS. Is that what you want?

**Comment by TheOneric** [comment]
> In that case either the value of the header or the absence of the header will always control the parameters used.

Since the renderer is capable of native RGB (for `"None"`), yes the initial conversion to YUV will be fully determined just from the subtitle file, but:

> The info from the video decoder/renderer is then never needed/used for ASS.

this isn't quite right. The video colourspace is still used for conversion *back* to RGB. Quoting the docs I linked in the original post, for values other than `"None"` the final output colour for ASS is determined like this with `ass_rgb` being the colour value specified in ASS:
```
  screen_rgb = video_csp_to_rgb( rgb_to_ycbcr_header_csp(ass_rgb) )
```
