### ISSUE TITLE
The Parameter is incorrect error when searching for subtitles

### ISSUE THREAD

**Issue by Bloomfear** [clsid2/mpc-hc#1887]
Whenever i open the subtitle search window, i get an error box that says the parameter is incorrect.

**Comment by clsid2** [comment]
Working fine for me, so I can't help you.

**Comment by Bloomfear** [comment]
Would you mind sharing your "mpc-hc-settings.reg" file?  Maybe i messed up the registry entries for searching subtitles. I tried to uninstall and reinstall but it didn't fix the issue.

**Comment by clsid2** [comment]
Options > Miscellaneous > Reset

But this is not a settings problem. "Parameter is incorrect" is usually caused by a Windows issue with accessing files.
