### ISSUE TITLE
Playlist experiences / undocked playlist movement issue on multi-monitor

### ISSUE THREAD

**Issue by Wille-Helm** [clsid2/mpc-hc#1888]
Hi!

MPC-HC is THE media player for me for years! I use it for watching all my movies, series, and when regularly throwing 80s parties at my home. Particularly when using it as a hobby DJ there is one thing I would love to see improved: the playlist.

Besides file handling generally, no total length _*)_ of a loaded playlist, I endure rendering issues with that playlist when using a second monitor for a long time.

I use one monitor to playback video in fullscreen, while the other is for editing the playlist live. Dragging and resizing the playlist window in this mode is dreadful because it draws endless frames on screen until released, therefore it is nearly impossible to estimate its next appearance. On a single monitor it is not happening.

By the way, is there a reason why it does not show window contents while dragging?

Specs: Windows 10 x64, AMD Ryzen (previously AMD FX), Radeon RX 590 (previously Radeon R9 280X), latest drivers

Regards

_*) I know this has been rejected earlier, nevertheless I would put that to good use too, because for reviewing purposes I have to save the playlist and open it in VLC to get this information several times per event._

**Comment by clsid2** [comment]
On Windows 7 dragging/resize only shows the outline of the new window, and playlist is redrawn only when releasing the mouse button. So the "bad" behavior in your case might simply be Windows 10 behavior. I can't fix it as I don't know anything about the GUI code.

**Comment by TFWol** [comment]
> Dragging and resizing the playlist window in this mode is dreadful because it draws endless frames on screen until released...

@Wille-Helm I'm not able to replicate this on my end. Playing a video fullscreen on one monitor while dragging a playlist around on the other acts as though it should (how @clsid2 mentioned).

Specs on a test machine: Win10 x64, Intel, NVIDIA GeForce RTX 3080
