### ISSUE TITLE
.pls not working...again in 1.9.23

### ISSUE THREAD

**Issue by toddk63** [clsid2/mpc-hc#1889]
Any URL stream ending in "/listen.pls?sid=1" will not work in 1.9.23 (works in 1.9.0 and VLC FWIW)
Workaround is to remove "/listen.pls?sid=1"  from the URL.

**Comment by clsid2** [comment]
I need an actual working link to reproduce. Otherwise I am not going to spend time on this to fix.

**Comment by toddk63** [comment]
[07 Demo World 118aac.m3u.txt](https://github.com/clsid2/mpc-hc/files/9888993/07.Demo.World.118aac.m3u.txt)

The URL is http://209.133.216.3:7831/listen.pls?sid=1 , which plays fine if dropped in as a URL.  Problem is when it is inside an .m3u or .pls

**Comment by clsid2** [comment]
It fails because it is a PLS playlist file inside a M3U playlist. The actual URL it points to is http://209.133.216.3:7831/stream

Nested playlists are currently not supported. Fixing this is low priority for me.

**Comment by clsid2** [comment]
You are lucky today. Fixed.

**Comment by toddk63** [comment]
Thanks
