### ISSUE TITLE
Disabling XBox Controller Input?

### ISSUE THREAD

**Issue by chinagreenelvis** [clsid2/mpc-hc#189]
I only recently noticed that my XBox 360 controller is acting as an input device when running MPC-HC, version 1.8.8. I'd like to know if there is some way to disable this functionality.

**Comment by ValZapod** [comment]
@chinagreenelvis Xbox controller IS an input device. For example in windows 10 settings you can use it. As in any UWP app, because they share codebase with Xbox.

**Comment by clsid2** [comment]
All keybindings can be found here:
Options > Player > Keys

Unchecking the "Global Media Keys" option might help.

The player has no control over how Windows uses input devices.

**Comment by Korb** [comment]
@chinagreenelvis, I use the Xbox Wireless Controller model 1914 for gaming and would be comfortable using it to control my MPC-HC player. However, when I tried to assign some actions to the controller buttons in Options / Player / Keys, I was faced with the fact that the player does not see any presses. Does the app still allow you to control yourself using your Xbox 360 controller?

```
MPC-HC (64-bit):
Build information:
Version: 2.3.2 (605081abb)
Build date: Jul 1 2024
LAV Filters:
LAV Splitter: 0.79.2.18
LAV Video: 0.79.2.18
LAV Audio: 0.79.2.18
FFmpeg compiler: MinGW-w64 GCC 13.3.0
Operating system:
Name: Windows 10 (Build 22H2)
Version: 10.0.19045 (64-bit)
Ansi Codepage: 65001

Xbox Wireless Controller Firmware version 5.21.3241.0
Xbox Controller driver 10.0.19041.4355 (2024-04-12)
Xbox 2407.1001.1.0
Xbox Accessories 2406.2405.7001.0
Xbox Live 1.24.10001.0
Microsoft Windows 10.0.19045.4717
```
