### ISSUE TITLE
Mediainfo data incomplete

### ISSUE THREAD

**Issue by tessa112** [clsid2/mpc-hc#1892]
Since version 1.9.23 (including 1.9.23.16) i have noticed mediainfo data is not available for some rar files on a win7 x64 os.
When playing the same file using version 1.9.22 the complete media info data is displayed.

I have tested with rar files created on same x64 win os with mixed results, some are shown correctly, some not. All the files are displayed correctly using version 1.9.22

The problem is that some files only displays the first 4 lines in the mediainfo tab:

General
Format                         : MPEG-4
Format profile                 : Base Media
Codec ID                       : isom (isom/iso2/avc1/mp41)
File size                      : 945 MiB

**Comment by clsid2** [comment]
I need a sample file that fails.

**Comment by tessa112** [comment]
The one thing in common with the non working files was they all seems to be muxed using "Writing Application           : Lavf59.9.102  (or other 5x.xxx versions)"
I am currently away from home but i will provide an example file once i am back.

**Comment by clsid2** [comment]
Fixed
