### ISSUE TITLE
Black Screen and no audio while playing BluRays

### ISSUE THREAD

**Issue by eyeliar** [clsid2/mpc-hc#1893]
The previous version worked but now playing any blu-ray gives a black screen with no audio but the timeline moves and can be paused normally.
Build information:
    Version:            1.9.23 (a8e9113b5)
    Compiler:           MSVC v19.29.30145
    Build date:         Aug 26 2022

LAV Filters:
    LAV Splitter:       0.76.1.25
    LAV Video:          0.76.1.25
    LAV Audio:          0.76.1.25
    FFmpeg compiler:    MinGW-w64 GCC 11.3.0
Filters currently loaded:
  - Default DirectSound Device
  - Enhanced Video Renderer (custom presenter)
  - Audio Switcher
  - LAV Video Decoder (internal)
  - LAV Audio Decoder (internal)
  - LAV Splitter Source (internal)

![black screen](https://user-images.githubusercontent.com/75148530/198917104-451dfe0b-228c-468c-a974-d3365940c556.png)
![output](https://user-images.githubusercontent.com/75148530/198917106-33314e31-752e-47a5-8e20-676e71a963cb.png)

**Comment by clsid2** [comment]
You must use a decrypting tool such as PasskeyLite or AnyDVDHD.
