### ISSUE TITLE
External audio file (dub) not loading automatically

### ISSUE THREAD

**Issue by mojo-jojo-7** [clsid2/mpc-hc#1894]
Audio files with extension .eac3 don't load automatically when the video (with same file name) is opened. Even when opening manually, the files with .eac3 extension are not recognized as audio files. But manually switching to "All files" in the open dialogue box and selecting a .eac3 file works as intended.

Is it possible to add eac3 to the list of extensions recognized as audio files?

**Comment by clsid2** [comment]
You can add extensions yourself on the formats page in the settings. Add it to "other audio" and your problem is solved.
