### ISSUE TITLE
How do I decrease the space between these subtitle lines?

### ISSUE THREAD

**Issue by tough-grass** [clsid2/mpc-hc#1897]
![image](https://user-images.githubusercontent.com/117590731/200183957-fbd9774f-37a5-457a-9164-25f84815bb65.png)
Using mpc hc with directvobsub auto loading version

The red lines indicate the space I'm talking, between two separate lines of a subtitle. This space is too much, I want to decrease it.

**Comment by clsid2** [comment]
Not possible.

**Comment by tough-grass** [comment]
> Not possible.

Why did you close it? It is definitely possible. Those lines used to be closer together before I installed the K-Lite codec pack.

**Comment by clsid2** [comment]
I only provide support for the internal subtitle renderer of MPC-HC.

Neither that nor directvobsub has an option to adjust line spacing.

I can't help you.
