### ISSUE TITLE
Video playback is choppy during panning or when objects move quickly

### ISSUE THREAD

**Issue by tough-grass** [clsid2/mpc-hc#1898]
The playback itself does not stutter, but the objects look like they're struggling to move by just a few milliseconds. Its hard to describe. [Here](https://streamable.com/7wznya) is an example of choppy playback and ghosting when the video is panning or objects are moving quickly. This is especially prominent with a lot of lines present in the frame, vertical and/or horizontal. If I were to explain it with words, whenever the video pans, some portions of them lag by a few milliseconds, just enough to bother. Its not screentearing though.

I have tried VLC, MPC-HC and every other media player I could. It happens with MKV too. I have v-sync turned on, even forced on through the NVIDIA control panel. Happens with youtube too, and games, though not as much. My PC specs are quite decent (12 core processor, 64 gigs of ram, rtx 2060), so its not a hardware related issue. My display is 22 inch, 1080p max. The videos I play back are bluray, x265. I hope that is all the required information.

**Comment by clsid2** [comment]
Panning is never smooth with typical video framerates of 24 to 30 fps.
