### ISSUE TITLE
Scaling issue/broken images with audio file cover art 

### ISSUE THREAD

**Issue by SayakaMaizono** [clsid2/mpc-hc#1899]
Hi. With my collection of MP3's and FLAC's, when I open them with MPC-HC, it looks like this.

![image](https://user-images.githubusercontent.com/24898649/200231528-e8d9c523-6895-4b61-b892-c6992b587323.png)

Scaling MPC makes this happen:

![image](https://user-images.githubusercontent.com/24898649/200231581-063f3ed5-959a-443d-8cf6-e67843f45043.png)

And if I keep MPC open and change the song, the new song plays, but the old broken cover art remains, whichever was opened first. That fixes itself on reopening MPC.

![image](https://user-images.githubusercontent.com/24898649/200231701-a56cdbf8-a966-4d5e-a65c-ef8990e25bef.png)

Video files play perfectly with no issues, just audio images.

Thank you for any help with this, as always when using software, I hate if I've been blind and missed an obvious fix, or bug report of this same issue solved.

**Comment by clsid2** [comment]
Coverart is working normal for me. Might be a bug in Windows.
