### ISSUE TITLE
AV1 files not working in MPC-HC 1.8.0

### ISSUE THREAD

**Issue by jamrial** [clsid2/mpc-hc#19]
Tried with mp4, matroska and ivf samples, the result is the same, and the error message similar or equal to the one I'd get with versions 1.7.xx

Thanks for keeping mpc-hc alive, for that matter.

![av01](https://user-images.githubusercontent.com/2442845/45503658-da78ee00-b75d-11e8-84bf-9038d0dc0889.jpg)

**Comment by jamrial** [comment]
I should also mention i did a settings reset when updating from 1.7.17 to 1.8.0, and the AV1 checkbox is ticked in the list of internal decoders (Or "Transform Filters" as it's called).

**Comment by lvqcl** [comment]
Apparently ffmpeg libraries were built without AV1 support?

**Comment by jamrial** [comment]
Indeed, looks like that's the problem. Commit 1755077ef67991d256857c5e3d811e5a3b2f9082 updated LAV Filters to a version supposedly building ffmpeg with libaom, but it's clearly not the case.

>$ ls -l /c/Program\ Files/MPC-HC/LAVFilters64
total 17709
-rwxr-xr-x 1 jamrial None 11926528 Sep 13 11:52 avcodec-lav-58.dll
-rwxr-xr-x 1 jamrial None   201728 Sep 13 11:52 avfilter-lav-7.dll
-rwxr-xr-x 1 jamrial None  1717248 Sep 13 11:52 avformat-lav-58.dll
-rwxr-xr-x 1 jamrial None   161792 Sep 13 11:52 avresample-lav-4.dll
-rwxr-xr-x 1 jamrial None   501248 Sep 13 11:52 avutil-lav-56.dll
-rwxr-xr-x 1 jamrial None   489984 Sep 13 11:52 IntelQuickSyncDecoder.dll
-rwxr-xr-x 1 jamrial None   304640 Sep 13 11:52 LAVAudio.ax
-rw-r--r-- 1 jamrial None      493 Sep  2 14:15 LAVFilters.Dependencies.manifest
-rwxr-xr-x 1 jamrial None   672256 Sep 13 11:52 LAVSplitter.ax
-rwxr-xr-x 1 jamrial None  1248256 Sep 13 11:52 LAVVideo.ax
-rwxr-xr-x 1 jamrial None   342016 Sep 13 11:52 libbluray.dll
-rwxr-xr-x 1 jamrial None   544256 Sep 13 11:52 swscale-lav-5.dll

> $ strings /c/Program\ Files/MPC-HC/LAVFilters64/avcodec-lav-58.dll | grep "suffix=-lav"
--x86asmexe=yasm --extra-ldflags=' -L../../../thirdparty/lib64' --extra-cflags='-fno-tree-vectorize -D_WIN32_WINNT=0x0600 -DWINVER=0x0600 -I../../../thirdparty/include' --enable-shared --disable-static --enable-gpl --enable-version3 --enable-w32threads --disable-demuxer=matroska --disable-filters --enable-filter='scale,yadif,w3fdif' --disable-protocol='async,cache,concat,httpproxy,icecast,md5,subfile' --disable-muxers --enable-muxer=spdif --disable-bsfs --enable-bsf='extract_extradata,vp9_superframe' --disable-cuda --disable-cuvid --disable-nvenc --enable-libspeex --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-avresample --enable-avisynth --disable-avdevice --disable-postproc --disable-swresample --disable-encoders --disable-devices --disable-programs --disable-debug --disable-doc --build-suffix=-lav --arch=x86_64 --enable-cross-compile --cross-prefix=x86_64-w64-mingw32- --target-os=mingw32 --pkg-config=pkg-config
$

>$ strings /c/Program\ Files/MPC-HC/LAVFilters64/avcodec-lav-58.dll | grep libaom
$

**Comment by clsid2** [comment]
Fixing it now.
