### ISSUE TITLE
Fuzzy image only when using MPC-HC

### ISSUE THREAD

**Issue by HannahBanana1312** [clsid2/mpc-hc#1900]
https://imgsli.com/MTMzNDU2

A slider comparison of the same frame of the same video file when watched through MPC-HC and VLC
If there is any sort of setting I can do so that it isn't fuzzy, that would be awesome.
And if there is any info that would be helpful to provide, please let me know.
Thank you for your time!

**Comment by clsid2** [comment]
Install this video renderer and select in in MPC-HC output options:
https://github.com/Aleksoid1978/VideoRenderer/releases

**Comment by HannahBanana1312** [comment]
I've installed it and selected it, but unfortunately it's still fuzzy.
![image](https://user-images.githubusercontent.com/36461227/200630633-359a2b4d-721f-4810-b03e-4402e7450b8d.png)

**Comment by clsid2** [comment]
Options > Internal Filters > Video Decoder

Change the hardware decoder settings to DXVA2 Copyback or D3D11.

**Comment by HannahBanana1312** [comment]
Neither option is fixing it, unfortunately ☹️

**Comment by clsid2** [comment]
Which graphics card do you have?

Can I download this video somewhere?

**Comment by HannahBanana1312** [comment]
I have a laptop with GTX 1660 Ti Mobile as a dGPU, and a Ryzen 7 4800H with a Radeon iGPU

Here is a snippet of the video, the same behavior happens with any video file played through MPC-HC
https://user-images.githubusercontent.com/36461227/200653245-0258a532-8165-4227-99e3-8ef9aaf15541.mp4

**Comment by clsid2** [comment]
Here it is looking the same as with VLC.

I am not sure what is wrong in your case. Do you have scaling enabled Windows settings? Do the problem go away if you set that to 100%?

**Comment by HannahBanana1312** [comment]
Scaling is not on, it's already set to 100%. It sucks that we can't find a solution, but thank you so much for your time

**Comment by clsid2** [comment]
In Windows Display settings, Advanced section, you can specify which one of the two GPUs should be used by each individual application. You could try to explicitly set MPC-HC to either one and see if that has any effect.

**Comment by HannahBanana1312** [comment]
Neither GPU helped unfortunately

**Comment by clsid2** [comment]
I am out of ideas.
