### ISSUE TITLE
Add support for subtitles in RAR archive

### ISSUE THREAD

**Issue by Sopor** [clsid2/mpc-hc#1902]
MPC-HC do support `multivolume RAR archives` with compression method `STORED`.

The problem is external subtitles. It doesn't load if the subtitles are in a RAR archive.

It doesn't matter if the compression method is `STORED` or `BEST`, it won't load it (neither automatically nor manually).

Most of the times the sub file is using compression method `BEST` and the idx file is using `STORED`, so i assume it need to extract it before it could load it because it use compression (I know Kodi do extract the subs if it is compressed).

It would be really nice if auto-load (and manually) of subtitles in a RAR archive could work the same way as in Kodi.

**Comment by clsid2** [comment]
It supports compressed .sub, but not compressed .idx. I have no interested is supporting that.

**Comment by Sopor** [comment]
What do you mean by compressed? I can't load any idx file that is in a RAR file even if it is STORED only.

**Comment by clsid2** [comment]
Do not put the tiny .idx file in RAR. Only put the large .sub inside RAR.

**Comment by Sopor** [comment]
Strange that you support `multivolume RAR archives`, but not idx in RAR when the subs (idx/sub) that come along is in a RAR archive. 😮

**Comment by clsid2** [comment]
Not supported. Period. Nothing strange about it at all. Go use another player.
