### ISSUE TITLE
no translation in Polish

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1904]
I found no translation in Polish in three places
![1](https://user-images.githubusercontent.com/104568362/201491143-15d5d877-c3e4-4dcf-aa46-97a19c42fc61.jpg)
![2](https://user-images.githubusercontent.com/104568362/201491144-cfd9bd46-2c00-4b83-be82-c42928b15b85.jpg)
is it supposed to be like this?

**Comment by clsid2** [comment]
Yes. Translations are not updated often.
