### ISSUE TITLE
A-B points no longer kept when 'Remember file position' enabled [1.9.24]

### ISSUE THREAD

**Issue by impetus-maximus** [clsid2/mpc-hc#1906]
This was working using 1.9.22
I updated to 1.9.24 and it's no longer working. It remembers the position, but the A-B points are gone.

Thank you

**Comment by clsid2** [comment]
Fixed

**Comment by impetus-maximus** [comment]
thank you. so expect it in next release then? [edit] never mind, i see it on the commit list. 

cheers
