### ISSUE TITLE
[DrDump] Crash in Avisynth Filter - Error C06D007E

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#1907]
MPC-HC has crashed due to an exception in AviSynth Filter.

The most likely cause is a missing dependency, meaning a required DLL is missing on your system. Possibly you forgot to install a required [Visual C++ Runtime](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170).

For help go to:
https://github.com/CrendKing/avisynth_filter

**Comment by DarthVaderBloody** [comment]
Добрый день! При попытке зайти в настройки AviSynth Filter, нажав два раза на него, выскакивает ошибка и перенаправляет сюда. Установил все Visual C++, но ошибка не устранилась. Помогите пожалуйста
