### ISSUE TITLE
Seek doesn't work on some online videos

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#1910]
**Website:** https://www.mxplayer.in/movie/watch-96-hindi-dubbed-movie-online-c36e83925b09709b4a255ae5ec73c221?watch=true
**Stream URL extracted by yt-dlp:** https://llvod.mxplay.com/video/5283e818e2179ed497bf9555bcf22ba5/hls/h264_1080_high_5800k.m3u8

**India** IP is needed if geo blocked.

vlc can seek the same stream.

**Comment by clsid2** [comment]
I can't fix that.
