### ISSUE TITLE
Cannot click in the bottom-half of the MPC-HC window titlebar to activate the window

### ISSUE THREAD

**Issue by dftf-stu** [clsid2/mpc-hc#1911]
_MPC-HC_ doesn't allow me to click in the bottom-half of its titlebar to activate the window (i.e. to make it the "foreground window").

In this screenshot, anywhere inside the red-rectangle does not work:
![MPC-HC_CannotActivateWindowArea](https://user-images.githubusercontent.com/83965343/201902344-7b270aed-0958-4a9f-90b2-4dca589202c5.png)

Interestingly, if I increase the height of the MPC-HC app (so you can see some of the album-art) then it does work, so I'm guessing it's a bug -- maybe because I have the app's menu-bar hidden?

MPC-HC version: 1.9.24 (ffe50c0c7) 64-bit build
OS: Windows 10 Home 64-bit (non-ARM) Version 22H2 Build 19045.2251 (Nov 2022 update-level)

**Comment by clsid2** [comment]
There is a safezone above and below the seekbar to ignore miss clicks. I need to adjust that in case of audio only playback.

**Comment by dftf-stu** [comment]
@clsid2: okay, that is helpful to know why.  In a future-update, maybe under View > Options > Advanced you could add a "IgnoreSafeZoneForSeekBar" setting with a "True" or "False" option I could use please?

OR maybe allow the app elements to be re-ordered?  So instead of titlebar > seek-bar > player controls > status-bar, I could have titlebar > player-controls > seek-bar > status-bar?  Then by moving the seek-bar down one row, the overlap should then not affect the window titlebar?

Thanks

**Comment by clsid2** [comment]
Fixed
