### ISSUE TITLE
Broken bitstreams which have timestamp offsets result in the player constantly dropping frames

### ISSUE THREAD

**Issue by brian6932** [clsid2/mpc-hc#1913]
Crossposting from https://github.com/streamlink/streamlink/issues/4960
>With MPC-HC: Once the discarding stops, and the player unfreezes, it starts to constantly drop frames.

>>Yes, this is because of the stream discontinuity and broken bitstream with timestamp offsets. If your player can't recover from this, then use a different player. There is literally nothing which can be done here. Both ads and ads filtering causes a stream discontinuity, and filtering out ad stuff is less of an issue, because it's still the same stream, just with a gap of data and timestamps.

<details>
  <summary>I'm on MPC-HC 1.9.24 (ffe50c0c7)</summary>
  
```
MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.24 (ffe50c0c7)
    Compiler:           MSVC v19.29.30145
    Build date:         Nov 12 2022

LAV Filters:
    LAV Splitter:       0.77.0.1
    LAV Video:          0.77.0.1
    LAV Audio:          0.77.0.1
    FFmpeg compiler:    MinGW-w64 GCC 12.2.0
```
  
</details>

**Comment by clsid2** [comment]
Not a player issue, but issue with the internal LAV Filters.

Considering that it also happens with MPV, it is likely a bug in FFmpeg.

Test with [FFplay](https://www.gyan.dev/ffmpeg/builds/) from FFmpeg project and [report bug](http://trac.ffmpeg.org/query?status=new&status=open&status=reopened&col=id&col=summary&col=status&col=type&col=component&col=version&col=time&col=changetime&report=1&desc=1&order=changetime) to them.

**Comment by brian6932** [comment]
Well dropping frames doesn't happen with mpv @clsid2.
The freeze is intended, as that is an ad segment, I know it's weird, but the ad segments are embedded in the video stream itself now, and can't be filtered apparently.

Even when I increase the LAV stream analysis duration to literally 3 minutes long, the same issue happens, so I'm thinking this may actually be a player issue.

Update: I swapped renderers around, and the issue persists with MPC-VR and EVR-CP. However, with MPV-VR the video just freezes (even after the period  is finished and audio starts playing), and then after a few minutes it starts playing again.
![image](https://user-images.githubusercontent.com/18603393/202447491-3a472b3d-b581-4014-a043-73156f5e172c.png)
7.2k frames were skipped:
![image](https://user-images.githubusercontent.com/18603393/202448247-099cd6a5-2dcc-446e-a1c9-373b2ca3040e.png)

With madVR and EVR-CP it does continue, with madVR the video drops frames forever, EVR-CP eventually recovers, but of course at that point you're behind.

**Comment by clsid2** [comment]
I am not going to do anything about this. It is **not** a player issue.

You can try disabling "Auto A/V sync correction" in the audio decoder settings.

If MPV does not skip over the gaps, then it is a bug in FFmpeg.

**Comment by brian6932** [comment]
> You can try disabling "Auto A/V sync correction" in the audio decoder settings.

This didn't work, I'll mess with ffmpeg and ffplay to see if the issue occurs there as well 👍
