### ISSUE TITLE
Enable custom channel mapping not working

### ISSUE THREAD

**Issue by kpcenti** [clsid2/mpc-hc#1914]
I am trying to map the center channel only and it still proceeds to play all the channels
![image](https://user-images.githubusercontent.com/10696951/202784223-ecd5038e-2e86-47e1-a8f7-f35ee81300e6.png)

I'm on the 1.9.24

**Comment by clsid2** [comment]
There is no center channel when input has 2 channels...

**Comment by kpcenti** [comment]
How would I isolate the center channel then?

**Comment by clsid2** [comment]
Start by selecting 6 inputs if you are playing a 5.1 audio track.
