### ISSUE TITLE
Can't load two subs in 1.9.24

### ISSUE THREAD

**Issue by atdfgdfbdftdrfdsf** [clsid2/mpc-hc#1915]
In 1.9.23, I can load two subs by using BlockVSFilter.One is inner sub filter,one is Xysubfilter
But in 1.9.24, the Xysubfilter can't be loaded.I can only use one sub filter.BlockVSFilter is open

**Comment by clsid2** [comment]
Fixed.
I have changed it to allow loading Xysubfilter, but only if VSFilter is not installed. Because otherwise both can potentially get loaded.
