### ISSUE TITLE
Dolby True HD not playing properly

### ISSUE THREAD

**Issue by watcher1025** [clsid2/mpc-hc#1916]
Files with Dolby True HD audio don't playback properly.

On initial listen only the surround channels playback with reduced levels and no dialogue.
Switching to Dolby Digital restores full audio.
Switching back to Dolby True HD restores lossless playback albeit with slight level drop compared to Dolby Digital.

This has only started within the last couple of updates.

Using Windows 10 on an HP EliteDesk Intel i5-4570S 2.90GHz

**Comment by clsid2** [comment]
The problem is at your end.

Most likely the Windows mixer is messing up. Enable the mixer in the internal audio decoder settings.

**Comment by watcher1025** [comment]
Fixed, thanks !
Realtek high def audio was off,
Dunno how as I never touched it.
Thanks Windoz
:D

**Comment by watcher1025** [comment]
Tried that on 3 different machines.
Dolby THD playback still problematic

**Comment by watcher1025** [comment]
Did that to no effect.
Same problem on three different computers.

**Comment by vladvalmont** [comment]
I have the same problem on two different computers. One of them with fresh OS install. Tryed old MPC HC player with internal LAV filters - True HD playing properly.

**Comment by clsid2** [comment]
Found your sample cut. Looks like a bug in FFmpeg or LAV.

**Comment by clsid2** [comment]
Fixed in 1.9.24.51
