### ISSUE TITLE
[FEAT] Playlist behavior vs After playback

### ISSUE THREAD

**Issue by Kochise** [clsid2/mpc-hc#1917]
#### Problem 

Hi, generating a M3U file out of a folder content, I had to add a "breaker" line (___playlist_end___) at its end to prevent the next file in the folder to be played at the end of the playlist (if "After playback" is set to "Play next file in folder") :

https://github.com/Kochise/youtube-dl_portable/blob/master/yt-dlp_playlist_m4a_generate.bat

I often use MPC-HC to play various M4A files in a folder, hence the "Play next file in folder" behavior is expected. Yet, when I specifically run a playlist, at its end, it continues with the next file in alphabetical order.

If you set "After playback" to "Do Nothing", it stops at the end of the playlist (GOOD !) but when launching a M4A file in a folder, it also stops at the end of its playback. Which in **that** case is not _really_ the expected behavior.

#### Request

Could it be possible that when running a M3U (or any other playlist format, see "Options/Player/Format/File extensions/Playlist (asx m3u ...)") it stops at the end, without continuing to the next file in the folder ?

Running one file : continue to the next of "After playback" is set to "Play next file in folder"
Running a playlist : disregard "After playback" and stop at the end of the playlist

#### Alternative

Adding an option for playback behavior (ie. "After playlist")

Regards.

**Comment by clsid2** [comment]
You can overrule the after playback behavior for current session:
Menu > Play > After playback

I am not adding any new functionality.

**Comment by Kochise** [comment]
![okaay](https://user-images.githubusercontent.com/23077417/202980524-5b3011be-6c8d-4a68-b51a-7556d4563515.gif)
