### ISSUE TITLE
blob:https://protocol link

### ISSUE THREAD

**Issue by huangsijun17** [clsid2/mpc-hc#1919]
Excuse me, can MPC open the link of the blob:https:// protocol?

**Comment by clsid2** [comment]
No, and it never will. You are copying the wrong url from your browser.

**Comment by vaclavec** [comment]
> 

Whats the mpc-hc protocol then?

**Comment by clsid2** [comment]
Simply `http://`

So WITHOUT `blob:`. That is something internal to your browser, not an actual protocol.

If you don't understand, then I suggest you use a different player.
