### ISSUE TITLE
MPC-HC capped to 1080p when streaming 4k yt videos by opening URLs

### ISSUE THREAD

**Issue by RetroAbstract** [clsid2/mpc-hc#1920]
MPC-HC's streaming quality seems to be capped at 1080p when streaming 4k youtube videos with yt-dlp by opening URLs through it.

Streamed a 4k video directly from yt-dlp through MPC-HC (stdin/stdout using command line) and MPC-HC streams it in 4K no issues.

**Comment by clsid2** [comment]
Options > Advanced > YDLMaxHeight

High resolution content can potentially give stuttering playback due to bandwidth throttling done by YT servers.
