### ISSUE TITLE
[Feature Request] Enable MIDI timecode as master/slave

### ISSUE THREAD

**Issue by leocb** [clsid2/mpc-hc#1922]
This is really useful for synchronizing media across devices in a network, specially useful in this open source project because as far as I know, there isn't an free option available that does this.

References:
- https://en.wikipedia.org/wiki/MIDI_timecode
- https://www.midi.org/specifications/midi1-specifications/midi-time-code

I'm willing to develop this feature myself, I just need guidance of whether to implement it as plugin or as a native part of the software, and if so, where to put it and it's configurations

Bonus feature would be to also include Art-net timecode, However I'm not familiar with this one, but it doesn't look too daunting

**Comment by clsid2** [comment]
I am not interested in that at all. I suggest you find another player.
