### ISSUE TITLE
[Feature Request] Temporarly disable a subtitle

### ISSUE THREAD

**Issue by FrankBKK** [clsid2/mpc-hc#1923]
In my settings I have subtitles by default enabled. 
Sometimes I'd like to turn off a subtitle but just for that particular movie. 

Of course I can use the pop-up menu Subtitle Track and uncheck the 'Enabled' option, 
but on the next movie I then need to manually turn it on again. 

It would be so much more convenient to just turn off an already selected subtitle just for the current video playing.

**Comment by bibsp** [comment]
Keep pressing keyboard shortcut `S` until you get no subtitle.

**Comment by FrankBKK** [comment]
sorry, that does not work - pressing s only scrolls through the existing subtitles and rolls over

**Comment by clsid2** [comment]
`W` toggles subtitles on/off. `S` also includes a "no subtitles" choice. And the menu does as well.
