### ISSUE TITLE
Changing Playback rate affects the pitch too

### ISSUE THREAD

**Issue by Ansh4011** [clsid2/mpc-hc#1924]
Changing the playback rate also change the pitch of the audio. It is a very important feature especially while watching recorded lectures, please pal fix it asap. Thanks!

**Comment by clsid2** [comment]
https://github.com/clsid2/mpc-hc/issues?q=is%3Aissue+is%3Aclosed+pitch

**Comment by Ansh4011** [comment]
@clsid2 Thanks a lot bro! Have a great day ahead!
