### ISSUE TITLE
OSD not showing up on audio-only playback

### ISSUE THREAD

**Issue by FabTheZen** [clsid2/mpc-hc#1928]
Some time ago I noticed MPC-HC was not showing any OSD message when playing an audio file, I thought it was a misconfiguration my side but that doesn't seem to be the case, plus OSD properly shows when playing video.
For example, changing volume during MP3 playback through hotkeys works fine but won't show the OSD message related to the volume being changed.
This happens with both MP3, FLAC, WMA and several other audio files, it seems that if there isn't any video stream happening, then the program is unable to draw the OSD over the MPC splash screen, cover art or black screen.

**Comment by clsid2** [comment]
That is how it is and I have no plans to change it.
