### ISSUE TITLE
Mouse left click delay logical issue

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#1929]
I think there is a logical issue in mouse left delay setting. Hard to explain. Version 1.9.24.18 x64

My setting 250ms.
Video is playing in window mode. Single click -> video paused. Another click should play the video again because previous click is registered as single click. But now it is doing both like first go to full screen then play the paused video.

Fast double clicking is fine.

https://user-images.githubusercontent.com/98865389/205560751-2cf1e6de-695e-480c-90cf-331d60fdb9fc.mp4

**Comment by bibsp** [comment]
And if I consider the time gap of my 1st and 2nd click is less than 250ms (my setting), then player should not pause the video on my 1st click, rather it should go to full screen directly.

**Comment by bibsp** [comment]
To reproduce set windows mouse click delay to slowest point, which I use. And MPC's setting to 250ms. Then the problem will be more visible.
![Screenshot (754)](https://user-images.githubusercontent.com/98865389/205564424-4149cc00-7ccf-4d5d-bffd-f0b008a79d17.png)

**Comment by clsid2** [comment]
The first click is NOT just a single click. In Windows a double-click is also two single clicks. So three events (or even more if you count up/down separately). So not a bug.

**Comment by bibsp** [comment]
You have not understood what I have said.
Behavior of previous build and latest build should be same. Right? The only difference is now users can set time delay inside player. Am I right?
If this is right, then previous build and latest build is different in behavior.

If you can't reproduce then try it. Set Windows delay setting to slowest point. Play a video. Pause it with mouse click. As soon as video is paused single click again very fast. It will not play the video. Instead it will go to full screen then it will play the paused video. Which is wrong. How can 1 click perform two actions? Previous build was not like that. It was correct.

Don't lock the issue, it is important. I want someone else come and explain.
Or revert it. Users will set the delay in windows mouse delay setting. No need of advanced settings for that.

**Comment by clsid2** [comment]
It works exactly as intended and you do not understand how Windows works.

It stays the work it works now. I am not reverting or discussion this any further.
