### ISSUE TITLE
无法播放某些视频文件

### ISSUE THREAD

**Issue by sfanking** [clsid2/mpc-hc#1930]
同一视频文件，mpc-hc无法打开，mpc-be和potplayer可正常打开，观看文件属性，发现mpc-hc似乎对文件编码识别有问题。截图如下
![2022-12-05_210808](https://user-images.githubusercontent.com/64935210/205646189-2ad0eb64-89fc-4c02-82f0-5cb76284bff1.jpg)
![2022-12-05_210847](https://user-images.githubusercontent.com/64935210/205646200-5fbb5266-77c7-41fb-b6b3-8b2c83e10cbb.jpg)
![2022-12-05_210712](https://user-images.githubusercontent.com/64935210/205646203-ee0dbf3c-98f6-40e7-a815-21d1e492f01f.jpg)

**Comment by clsid2** [comment]
Give link to the file.

**Comment by clsid2** [comment]
I can't read or download that.
