### ISSUE TITLE
5.1 audio to 2.0/headphones?

### ISSUE THREAD

**Issue by alidan** [clsid2/mpc-hc#1931]
I have no idea if this is the right place to ask, I can't really find a feature like this that's obviously sticking out and my solution in program kind of sucks. 

So I have a 5.1 speaker system that sucks, its reciever/brain has headphone out

so the computer constantly thinks its 5.1 out, even though its really going to headphones, for me there is no other way to do this without disconnecting and reconnecting the speakers whenever I want to use them.

In program, I cant find a way to mix the 5.1 to 2.0 in a clean way

The way that I came up with is taking a the speaker configuration for a 7.1 and mapping everything to either left ear or right ear with center and sub going to both, this does fix the problem with 5.1/7.1 videos, but when you play normal 2.0 it causes problems with volume and clipping.

So im wondering if there is any filter or way to do this cleanly or if this is the best option I have?

**Comment by clsid2** [comment]
There is a mixer setting in the internal audio decoder. You can also adjust the speaker count of the device in the Windows audio settings.

Or connect the headphone directly to the computer. Then change the audio output device to switch between headphones and speakerset.
https://apps.microsoft.com/store/detail/eartrumpet/9NBLGGH516XP

There is no clean way that does not require any user interaction.
