### ISSUE TITLE
Issues with online subtitle 

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#1932]
1. Automatically save downloaded subs is enabled. For example many episodes are there in a folder, ep01, ep02, ep03 etc......
Now ep02 is playing. Online subtitle is loaded. If I click on next button to go to next episode then it saves that previous episode's sub as ep03.srt.

_Works perfectly if ep02 is closed, and relaunch MPC._

2. Online loaded subs show different (I think default settings of MPC) style. While toggling full screen style is fixed.

https://user-images.githubusercontent.com/98865389/206103612-d47dd7b2-64a2-49c4-a031-24c7fe056b60.mp4

**Comment by clsid2** [comment]
Filename issue is fixed.

I am unable to reproduce any style issues. Does it also happen after reload with the stored subtitle?

**Comment by bibsp** [comment]
> Does it also happen after reload with the stored subtitle?

No, everything is **fine** after reload also.
_If sub is loaded when video is in full screen then also I need to exit full screen once to get my default style._

I'm not using default MPC-HC settings. My changes are here.
![Screenshot (756)](https://user-images.githubusercontent.com/98865389/206182782-f31bd0e6-9d10-43ec-ad00-e8d9115b2ab8.png)
![Screenshot (757)](https://user-images.githubusercontent.com/98865389/206182790-ea3e7e8e-4335-449f-bd35-0fa110f41501.png)
All other style related settings are untouched. Monitor resolution  1366x768

**Comment by clsid2** [comment]
Try 1.9.24.27

**Comment by bibsp** [comment]
**The above 2 issues are fixed.**

While testing with 1.9.24.27 I found embedded subs no longer works.
For example srt, webvtt, tx3g are not working. I don't know if there are any other formats that don't work also.
**Ass is working fine.**

Last working build was 1.9.24.8.

**Comment by bibsp** [comment]
The style issue was also introduced recently. 1.9.24.8 was okay.
Although that is fixed now.
Just mentioning because there might be many things(Sub related) which are broken after 1.9.24.8.

**Comment by clsid2** [comment]
Hopefully everything working correctly again in 1.9.24.31

**Comment by bibsp** [comment]
Those are fixed I think.
If I get any new bug I will let you now.
Closing it. Thanks.
