### ISSUE TITLE
 black color looks greyish with evr-cp player

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1933]
mpc+madvr and vlc can display normally
Using the limited to full range shader seems mitigate the problem.

It this normal?

images for your reference
[https://slow.pics/c/GR86VaYx](url)

Thanks

**Comment by clsid2** [comment]
Not normal. It is fault of your graphics driver settings.

**Comment by ghost** [comment]
I think I found the reason, the video is limited range and I set the render output to 0-255. That caused the wrong color mapping.

**Comment by clsid2** [comment]
The range of the input video is irrelevant when everything is configured correctly. Both ranges should display correct. You have likely set limited range in the driver settings.

Here is another good renderer:
https://github.com/Aleksoid1978/VideoRenderer

**Comment by ghost** [comment]
I set intel input range to be full.
<img width="533" alt="image" src="https://user-images.githubusercontent.com/20217680/206417593-0fbe35e6-a166-4845-ba7d-43830f4658ef.png">

And MPC Video Renderer produces different output to madvr
at 00:00:07
[https://slow.pics/c/ySnY17Cx](https://slow.pics/c/ySnY17Cx)

video file
[https://www.mediafire.com/file/vy6crwf313gksbq/copy.mp4/file](https://www.mediafire.com/file/vy6crwf313gksbq/copy.mp4/file)

**Comment by clsid2** [comment]
You should set that to `Application Settings`.
There may also be bugs in the driver:
https://community.intel.com/t5/Graphics/Video-input-range-quot-Application-Settings-quot-not-working/m-p/1246999

In the Intel driver settings also disable stuff such as `dynamic contrast`.
