### ISSUE TITLE
Feature Request - Support for xmv files

### ISSUE THREAD

**Issue by Felipefpl** [clsid2/mpc-hc#1934]
This is a file format from Microsoft XBOX Audio/Video File. It can be found on Baldur's Gate Dark Alliance's port from xbox to PC.

Right now mpc doesnt display the video, only the audio or stops with a mistake such as this one:

File Source (Async.)::Output
LAV Splitter (internal) (low merit)::Video

Media Type 0:
--------------------------
Video: 2VMW 840x448 25fps

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Video {73646976-0000-0010-8000-00AA00389B71}
subtype: Unknown GUID Name {574D5632-0000-0010-8000-00AA00389B71}
formattype: FORMAT_VideoInfo {05589F80-C356-11CE-BF01-00AA0055595A}
bFixedSizeSamples: 0
bTemporalCompression: 1
lSampleSize: 1
cbFormat: 92

VIDEOINFOHEADER:
rcSource: (0,0)-(840,448)
rcTarget: (0,0)-(840,448)
dwBitRate: 0
dwBitErrorRate: 0
AvgTimePerFrame: 400000

BITMAPINFOHEADER:
biSize: 44
biWidth: 840
biHeight: 448
biPlanes: 1
biBitCount: 12
biCompression: 2VMW
biSizeImage: 564480
biXPelsPerMeter: 0
biYPelsPerMeter: 0
biClrUsed: 0
biClrImportant: 0

pbFormat:
0000: 00 00 00 00 00 00 00 00 48 03 00 00 c0 01 00 00 ........H...À...
0010: 00 00 00 00 00 00 00 00 48 03 00 00 c0 01 00 00 ........H...À...
0020: 00 00 00 00 00 00 00 00 80 1a 06 00 00 00 00 00 ...............
0030: 2c 00 00 00 48 03 00 00 c0 01 00 00 01 00 0c 00 ,...H...À.......
0040: 32 56 4d 57 00 9d 08 00 00 00 00 00 00 00 00 00 2VMW...........
0050: 00 00 00 00 00 00 00 00|00 00 b4 80             ..........´

**Comment by clsid2** [comment]
If you install MPC-HC as part of K-Lite Codec Pack, then you should be able to play such files.

**Comment by Felipefpl** [comment]
I did that, installed mega pack with everything except mpc-hc and i still got a black screen with sound like i did before.

**Comment by clsid2** [comment]
Upload the video file.
http://www.sendspace.com

**Comment by Felipefpl** [comment]
here https://www.sendspace.com/file/34qw30

**Comment by bibsp** [comment]
MPC-BE failed. VLC can play but it is buggy.
MX Player (Android) can play it properly.
If MX can play then LAV should play it by itself without having K-Lite installed.

**Comment by Felipefpl** [comment]
@bibsp - thanks for testing it. :+1: 

For those who didnt see it and are curious this file is a logo of Black Isle, it can be loaded properly when the game is run but not on mpc-hc.

**Comment by clsid2** [comment]
Plays fine for me with K-Lite. If doesn't for you try enabling internal WMV1/2 decoder in MPC-HC. LAV Filters from K-Lite is required. Vanilla LAV does no expose all capabilities of FFmpeg.

Seeking does not work for this format and will give black screen.

No further support for this will be given.
