### ISSUE TITLE
mpc-hc64 high cpu load using xmouse simulated keys

### ISSUE THREAD

**Issue by bandaid** [clsid2/mpc-hc#1935]
I have a trail cam that I am attempting to capture images from a video file. I'm using mpc-hc64 to view the captured information. I currently have mpc-hc64 to make small increments of "Frame-step" with the left and right keyboard arrows and F5 for quick capture of that frame. So, when I find a set of frames I'll spam the left arrow and F5 to capture them and I have no issues with CPU load. However, when I set up xmouse to minimize fatigue and automate the process the CPU spikes to 100% even when I have a wait set to 1 second per frame capture and that is slower than me spamming the keyboard manually. I'll also experience input delay after pressing the mouse button 5 10-20+ times in a row.

wmp-hc64 is at 60-70% when using xmbc. xmbc is around 6-12% when using simulated keys.

it's an i5-6200, but that's the beside the point. I can take more frame captures manually maybe 10-15 in a second and there is no load on the CPU other than the normal wmp-hc operation of around 20% vs using xmbc which seems to spike wmp-hc to 60-70%.

xmbc post
https://forums.highrez.co.uk/viewtopic.php?f=6&t=4638&p=23390#p23390

**Comment by clsid2** [comment]
The player is called MPC-HC. It has no relation to WMP.

I can't help you.

**Comment by bandaid** [comment]
This has nothing to do with Windows Media Player, it was clearly a typo at the end. The issue is with MPC as clearly stated before.
