### ISSUE TITLE
SAMI subtitle HTML tag support is desired

### ISSUE THREAD

**Issue by Hackjjang** [clsid2/mpc-hc#1937]
HTML tags are applied to SRT subtitles without any problems, but SAMI (smi) subtitles ignore font face and font size, so I want them to be supported in the same format as SRT. SAMI subtitles are subtitles used in Internet Explorer, so they support all HTML supported by the web browser.

Reference -
[Understanding SAMI 1.0 - MSDN](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/dnacc/understanding-sami-1.0)

It's a Google translation, so I'm not sure if it will be delivered properly, but I hope it's corrected.

**Comment by clsid2** [comment]
I have never in my life played such subtitles so i have ZERO interest in supporting it.

Internet Explorer is dead.

There are websites that can convert it into SRT for you.
