### ISSUE TITLE
MPC-HC VOB Do not show subtitles (LavFilter)

### ISSUE THREAD

**Issue by skot013** [clsid2/mpc-hc#1938]
MPC-BE Display is normal，MPC-HC，LavFilter Do not show subtitles，
![22](https://user-images.githubusercontent.com/43721178/206825149-b0ad707c-c24d-41cc-a78b-fa80f957adee.png)
![1](https://user-images.githubusercontent.com/43721178/206825004-b1709f9c-5c26-4e4a-b8d0-f8f3e5fa8799.png)
Video File:https://gofile.io/d/nrLJgM

**Comment by clsid2** [comment]
You will have to report this to LAV Filters.
