### ISSUE TITLE
[Regression] : Options\Player\Keys-> Listbox scrolling fails

### ISSUE THREAD

**Issue by SanderBouwhuis** [clsid2/mpc-hc#194]
When you go to Options\Player\Keys I can no longer properly scroll through the list. It used to work, but no longer does.
The scrollbar 'jumps/jitters', and scrolling with the cursor keys also doesn't work.

Edit:
I found the problem: if you filter the list (e.g., filter on 'step') and then remove the filter, the list bugs out.

**Comment by adipose** [comment]
https://mega.nz/#!QIR0AKZI!3gbX5yjxuBRSQQe8ehm3wZEd7brDjD-8J6XLrnOruJg

This latest test build should have fixed it.
