### ISSUE TITLE
Video cant resume A-B postitions after waking from Hibernate

### ISSUE THREAD

**Issue by Theletha** [clsid2/mpc-hc#1941]
If i leave the player on with the video with A-B positions and then place the PC in hibernation and then wake up again the video won't resume. It gets a black screen and wont do anything, not even stopping and starting again helps. I have to reload the hole video again. 

The videos are running from my NAS connected via windows via a shared drive. 

In VLC at least the video reloads itself but the A-B positions gets wiped. Would be nice if it could reload while saving the A-B positions. For now i have to use the favorites to save but would be extremely convenient to have it work without the reload.

**Comment by clsid2** [comment]
Options > Advanced > ReloadAfterLongPause

**Comment by Theletha** [comment]
> Options > Advanced > ReloadAfterLongPause

Does it remember the time it got paused? thinking if it accounts for the sleep time of the pc. 
what's the difference on 0 and +1?

**Comment by clsid2** [comment]
Yes it remembers playback position. Also A-B. I recommend updating to latest development build because that fixes an AB related bug.

-1 is disabled. 0 is for sleep/hibernate only. Larger values will also reload if paused longer than X minutes.

The cause of the hang is likely related to flaws in the graphics driver. That is why this setting is only needed on certain systems.

**Comment by Theletha** [comment]
> Yes it remembers playback position. Also A-B. I recommend updating to latest development build because that fixes an AB related bug.
> 
> -1 is disabled. 0 is for sleep/hibernate only. Larger values will also reload if paused longer than X minutes.
> 
> The cause of the hang is likely related to flaws in the graphics driver. That is why this setting is only needed on certain systems.

The 0 setting works great for me, now it reloads the video and the A-B is still saved after Hibernation. The only issue I have now is that it is removing A-B when seeking in the timeline. Should I create a new thread for it, or is there a setting for it too? 

It should be playing the video normally if it's before A-point until its inside the A-B point then it should repeat normally between A-B if untouched. If you Seek after the B point it should immediately move to A-point and repeat normally. It should remember the A-B points at all times under above scenarios until they are manually cleared for that session or you close the player or maybe open another file in that session. Without it makes it hard to precision repeat quick which is nice to just press somewhere past B-point and it starts again at A-point. 

Maybe there could be an advanced setting with the term "A-B Sticky"  or something. I think vlc has this by default along with their A-B button at the bottom if you have it visible which is quite nice but i have already made keybinds for it anyways.

**Comment by clsid2** [comment]
If you seek outside of the A-B range, it will reset.

That is intentional. I will think about changing it. But I will not be adding more options.
