### ISSUE TITLE
Pause delay after left-click on video during playback

### ISSUE THREAD

**Issue by ryehamstrawberry** [clsid2/mpc-hc#1942]
The last few development builds (up to and including 1.9.24.38.x64) seem to include an issue where there's a slight delay after left-click on video during playback.

I've noticed that using the spacebar to pause video playback mitigates this issue, but sometimes using MB1 is preferable for any number of reasons.

I don't think it's a settings issue because the problem does not appear to exist in previous stable builds I've tested:
MPC-HC.1.9.22.x64
MPC-HC.1.9.23.x64

**Comment by clsid2** [comment]
Options > Advanced > MouseLeftUpDelay
