### ISSUE TITLE
Two quick questions

### ISSUE THREAD

**Issue by mckealty** [clsid2/mpc-hc#1943]
Hi, I have a playlist with hundreds of episodes. I have trouble remembering which was the last episode I watched.

1. Is it possible, like the way "remember File position" works, to "Remember last file played in playlist"?
2. Is it possible to increase the font size in options screens?
![Screenshot 2022-12-16 193846](https://user-images.githubusercontent.com/108241183/208213903-267e50cd-d281-48a5-bbc9-7ac8d2ca2dc2.png)

**Comment by clsid2** [comment]
No. No. And no new functionality will be added.

You don't need a playlist. Simply open last episode from recent file menu. Press PageDown to move to next file in folder at end of episode.

**Comment by mckealty** [comment]
Ok, thanks for the tip. Sorry to have bothered you.
