### ISSUE TITLE
Close file when STOP pressed

### ISSUE THREAD

**Issue by ags1234** [clsid2/mpc-hc#1944]
The video cannot be deleted from disk because MPC-HC is locking it, even after STOP is pressed.

What reason is there for the MPC-HC to keep the file open after the user hits STOP button?

**Comment by Aleksoid1978** [comment]
STOP - it's not close, it's just stop playing - but file steel is open in player.

**Comment by ags1234** [comment]
Make an option to close the file when user stops the playback.
It could be next to the one that closes the file when playback reaches the end.

**Comment by clsid2** [comment]
Press Ctrl+C to close. Or press Del to directly delete the current file.

**Comment by ags1234** [comment]
Thanks!
