### ISSUE TITLE
Transparent Properties screen on Windows 11 for RTL language

### ISSUE THREAD

**Issue by yonizaf** [clsid2/mpc-hc#1947]
This seems to be related to #1454. Options screen got fixed apparently, but other screens are having the same issue, including: File Properties screen, Filter properties (e.g internal LAV settings) and possibly others.

![image](https://user-images.githubusercontent.com/598326/209025537-da8172eb-b04c-46a5-b94a-4247e7fe7943.png)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2115

If you know of more dialogs that have the issue they can likely be fixed as well.

**Comment by yonizaf** [comment]
not sure what changed, but the Properties screen got messed up again the same way.

Should I create a new issue? or can this one be re-opened?

**Comment by adipose** [comment]
I bet it's because I made them resizable. Different parent class.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2725

**Comment by yonizaf** [comment]
Follow up: File Opening dialog has this problem as well.

![Image](https://github.com/user-attachments/assets/057af34f-45c3-4eca-887d-5a1f18a010d3)

**Comment by yonizaf** [comment]
ping: File Opening dialog ('Quick Open File') still broken when UI set to RTL language. 
(might not be evident until you try to resize the window)
