### ISSUE TITLE
A-B looping positions not remembered upon re-opening a file

### ISSUE THREAD

**Issue by rkgs** [clsid2/mpc-hc#1948]
I'm on 1.9.24, I have "remember file position" on as well. I saw this same exact issue closed when the update was released but it is still there. It's not just me either, I've contacted people I know and they are having the same issue.

It was working until the past couple updates it seems

**Comment by clsid2** [comment]
You need the latest development build.

It is working fine for me.

**Comment by rkgs** [comment]
Sorry about the late reply, but yeah it's working on that build when I tested it this morning, thanks.
