### ISSUE TITLE
Security Issues and Other Stuff:

### ISSUE THREAD

**Issue by LucianAndries** [clsid2/mpc-hc#195]
Hello!

Nice update and features for version 1.9.0! Awesome!

But can I ask, why Windows keeps warning me each time I run it or update it, that it's an unrecognized app and my PC is at risk? Also "publisher unknown"...
I tried to install this update, and "Windows Defender SmartScreen" popped up with a button that says Don't run............ :((((((((((((

Can you please do something about these issues? They're annoying af... :(((
There were no issues with the original MPC-HC, regarding computer and security risks. :|

While at it, can you add actual settings for the OSD? Like making the text bigger, move it on screen, font, color, etc? Also, make the name of the video/file visible, each time I move the cursor? Like on YouTube videos...

Oh, and a way to search for subtitles? Not all movie name files are in the OpenSubtitles' data base, and the window for downloading subtitles doesn't pop-up every time. :(
And since you said something about "hardcoding", a feature that comes by default in MPC-HC, "right click on opened video -> subtitle track -> search for subtitle" is a must have.

But, all this after the new years. You have a life too. :)
Thank you for your hard work!

**Comment by clsid2** [comment]
The smartscreen error happens on files that are brand new. I can't fix that.

OSD font/size: Options > Tweaks
OSD position: there is no option for this, and I am not interested in adding it.

There already is a subtitle search option. Press D.

**Comment by gp-slick-coder** [comment]
![image](https://user-images.githubusercontent.com/1906169/71786354-d2a42380-300a-11ea-9933-c42f68f72ea0.png)

:-|
