### ISSUE TITLE
font rendering problem

### ISSUE THREAD

**Issue by eddilara** [clsid2/mpc-hc#1950]
so I had a problem with the rendering of a font (japanese font)
I was able to solve it by using the libass version of xyfilter
I think you should either switch over to libass...since xy-vsfilter isn't updated very often...or add that version of xy-vsfilter as an option to the subtitle rendering

**Comment by clsid2** [comment]
Give link to the problematic video. And timestamp at which the problem occurs.

Using libass is NOT going to happen anytime soon and I am NOT going to debate that.

**Comment by eddilara** [comment]
thats to bad cause libass is pretty useful

**Comment by clsid2** [comment]
If you can't give a link then I will close this.
