### ISSUE TITLE
I would like to participate in the Korean translation of MPC-HC.

### ISSUE THREAD

**Issue by Hackjjang** [clsid2/mpc-hc#1952]
I am using MPC-HC, but I would like to be able to partially modify the parts that have not yet been translated into Korean. 

It's already coming out well enough in Korean, but I want to participate because I think there are parts that haven't been done yet.

[mpcresources.ko.zip](https://github.com/clsid2/mpc-hc/files/10300329/mpcresources.ko.zip)

**Comment by clsid2** [comment]
https://github.com/clsid2/mpc-hc/issues/215
