### ISSUE TITLE
Netflix Sample Unplayable and Causes AMD Driver Crash

### ISSUE THREAD

**Issue by war59312** [clsid2/mpc-hc#1953]
Netflix samples at:

http://download.opencontent.netflix.com/?prefix=AV1/Chimera/

Chimera-2397fps-AV1-10bit-960x540-1658kbps.mp4 plays back fine via HW:

Win 11 22H2
AMD Ryzen 9 7900x
AMD Graphics Driver V31.0.12042.4 

madVR or Enhanced Video Renderer (custom presenter)
Lava Video Decoder to set D3D11 and Pick AMD Radon Graphics

Chimera-2397fps-AV1-10bit-960x540-1658kbps_cbcs.mp4 does not work.

Gives either green screen (AMD HW) or just all screwed up if software.

Even worse it causes the AMD Video Driver to crash:

`Display driver amdwddmg stopped responding and has successfully recovered.`

All the OBU files play back fine if opened manually. At 144fps too, matches my display. But should be matching what the video says, for example 23.98 fps. FYI VLC gets this right it seems. Update: MadVR is causing the 144fps FYI.

I think the cbcs is the problem. As I can play back the none cbcs files in the older directory, but sure enough, if I try and play back any of the cbcs. versions, same issue, driver crash and green/screwed up video.

Note: The Win11 Media Player (after installing AV1 Video Extension) can't paly back these cbcs files either. Tells you format not supported, that is probably what MPC-HC should do?

Win11 Media Player plays back the none cbcs versions just fine.

**Comment by war59312** [comment]
Another sample at https://github.com/SPBTV/video_av1_samples/blob/master/spbtv_sample_bipbop_av1_960x540_25fps.mp4 plays back fine as well.

**Comment by war59312** [comment]
If someone could grab the samples from https://testweb.playready.microsoft.com/Content/ContentAV1, I would love to test.

Edit: Open as URL tries to play it but video is all screwed up, green screen, and AMD driver crash.

VLC does a bit better than MPC-HC. Video still garbage but no AMD driver crash at least.

**Comment by v0lt** [comment]
> Chimera-2397fps-AV1-10bit-960x540-1658kbps_cbcs.mp4 does not work.
> 
> Gives either green screen (AMD HW) or just all screwed up if software.

I think this file is corrupted because it plays with errors in MPC-BE, VLC and mpv. Firefox and "Movies & TV" do not play this file.

> Even worse it causes the AMD Video Driver to crash:
> 
> `Display driver amdwddmg stopped responding and has successfully recovered.`

It would be more correct if you file a bug report in AMD.

**Comment by clsid2** [comment]
Stop wasting everyone's time with DRM protected stuff and bullshit streaming sample files. If you want normal AV1 content, you can get it from Youtube.

**Comment by war59312** [comment]
OK. Well then perhaps just make it so MPC-HC wont even try and play them?

Display some sort of msg about DRM and cant play them?

**Comment by clsid2** [comment]
Not possible.
