### ISSUE TITLE
Color clipping issue

### ISSUE THREAD

**Issue by Molkree** [clsid2/mpc-hc#1955]
I have recorded a bunch of videos using built-in Windows recording capability (Win+Alt+R) but when I play them through MPC-HC I see weird color clipping in huge chunks of videos. Unfortunately, those were recordings of a private video call so I can't share them in full but I have trimmed/cropped a small example.

https://user-images.githubusercontent.com/12860284/210102826-f8006e9d-91ab-4589-996d-dc3f2dcfcf3b.mp4

Near the 5 second mark part of the color gets clipped:

![image](https://user-images.githubusercontent.com/12860284/210102906-af92d21b-e211-4987-81d4-28e2f07568f4.png)

Yes, I know the video quality is bad and lighting is bad however I don't see this clipping when playing through VLC or even Windows Photos app. Additionally this is present in the recording with relatively good lighting in the video as well.

This is the first time I encounter this with MPC-HC, I have some recordings made in the same fashion from August that look well.

Tried a few older versions to check if it's a recent regression but all of them exhibit the same clipping. I've checked on 1.9.24.38, 1.9.24, 1.9.20, 1.8.2.

**Comment by clsid2** [comment]
That problem does not happen here. Just the normal compression artifacts.

It is the fault of your graphics driver. Update your driver.
If you have Intel, then disable `Contrast Enhancement` and `Fleshtone Enhancement` in the driver settings. Those fuck up the video quality.

**Comment by Molkree** [comment]
Thank you, it was `Contrast Enhancement` with Intel driver ♥
I only thought it was an MPC-HC issue because other players displayed correctly.
