### ISSUE TITLE
Lagging/Dropping frame when playing 1080p videos

### ISSUE THREAD

**Issue by Binh1412** [clsid2/mpc-hc#1957]
When I play 1080p files, there's many frame drop and lag. I had tried several things, but none of that work. Please help. Also, 720p videos are playable with no frame drop.
Also, I'm using Windows 10 Pro with an Intel Core i3-2330M

**Comment by bibsp** [comment]
What does the status bar show (at bottom)? `Playing` or `Playing [H/W]` ?

Install [MPC Video Renderer](https://github.com/Aleksoid1978/VideoRenderer/releases/tag/0.6.3). Select it from `Options > Output > DirectShow Video`.
It performs better than internal EVR-CP.

**Comment by v0lt** [comment]
You have provided very little information.

> Intel Core i3-2330M

Your processor may not be powerful enough to decode some file types.
Also note that the x64 decoder is faster than x86.

**Comment by clsid2** [comment]
Computer is too old and slow.
Avoid playing video in HEVC format and download H264 instead.
