### ISSUE TITLE
Don't drop XP and Vista!

### ISSUE THREAD

**Issue by Trancer03** [clsid2/mpc-hc#1958]
Could you please bring back compatibility with XP and Vista in future releases?

**Comment by v0lt** [comment]
There is no way to return support for XP. This issue has been closed for a long time. Forget about it. If necessary, use older versions of MPC-HC.

It's easier to make Vista support easier. But. The first problem is that developers will need to change not only the player code, but also patch external libraries (for example, dav1d). The second problem is that Vista is hardly used in the world (developers don't use Vista either). In sum, no one wants to do this for free for a long time. So the answer would be "no".

**Comment by clsid2** [comment]
Only retarded people still use XP.
