### ISSUE TITLE
M3U playlist loaded from URL is truncated after first HTTP response chunk

### ISSUE THREAD

**Issue by wfraser** [clsid2/mpc-hc#1959]
I've got a server that generates M3U playlists dynamically. When loading it in MPC-HC (either via command line or thru File -> Open File/URL), it is only reading the first HTTP response chunk (i.e. `Transfer-Encoding: chunked`) and this results in a truncated playlist. I ran `curl -v --raw https://my-server/path.m3u` to print the raw HTTP response and observed where the first chunk ended matched where the URL of the last playlist entry was truncated in MPC-HC.

If I force the playlist to be sent by the server all at once (i.e. by buffering it and sending a `Content-Length` header with the right size first), MPC-HC reads the whole playlist fine, so the bug is something specific to reading HTTP chunked transfer encoding.

**Comment by wfraser** [comment]
I haven't been able to get a debug build of it running so I can actually verify, but from just browsing around the code, it looks like `CWebTextFile` is used to read the playlist from a URL, and this line in there looks pretty sus to me:

https://github.com/clsid2/mpc-hc/blob/d5dda5fd258db665354407d64de4ea13b6e8053c/src/Subtitles/TextFile.cpp#L781

That `(len = f->Read(buff, 1024)) == 1024` should probably be `(len = f->Read(buff, 1024)) != 0` instead (and the rest changed accordingly). It looks like any time a chunk results in a less-than-full buffer, it would stop reading early, resulting in the truncated file I'm seeing.

**Comment by clsid2** [comment]
Can you give an example link to reproduce?

**Comment by wfraser** [comment]
It's a little tricky to get the chunks to be a completely consistent size, so I had to make a slightly contrived example. Here's a script which intentionally disables all buffers and sleeps 1 sec between outputting tracks so I can be sure it sends it in multiple chunks. It should have 20 tracks.

https://odin.codewise.org/~wfraser/m3u_chunked.php

Loading this in MPC-HC v1.9.24 I only get the first two tracks. If you add `?buffer` to the URL, the script will try to send the playlist all at once, and then I get all 20 tracks. Using a web browser to fetch the file first gives 20 tracks either way.

**Comment by clsid2** [comment]
Works ok now after my latest commit.

**Comment by wfraser** [comment]
Thanks!
