### ISSUE TITLE
Improve compatibility with Windows text scaling

### ISSUE THREAD

**Issue by LucianAndries** [clsid2/mpc-hc#196]
Dude, why do you behave like this?????? If you don't have time, then don't read them! But don't give a half-assed answer, and instant close!!

I wanted to give extra feedback after the installation. Jeeeeezzz!!!!!

How about you SIGN the app, add every bit of necessary info for windows, to not see it as adware and other things? I don't get this on any other third party apps, so it must be a signature issue. It even says unknown publisher... Put something there, anything. :|

The OSD:
Yeah no. I asked you to add/code in, better/actual settings/options for it. To have it's own tab or section, that is dedicated for the OSD. And work on/with any renderer.
Also, I need the file's name to show up on the OSD, so we don't exit full screen and get off the bed to read a freaking small title on the player's top bar. The freaking title appears on screen when first open the video anyway, so make that appear each time I move the mouse and the controls appear.

Subtitle Search:
Freaking keyboard shortcut.........! Unfortunately not everyone knows about it. So make it appear on right mouse click as well. And me personally, do not use a keyboards in bed, just a wireless mouse. :|

Also, there are a lot of issues in v1.90, mostly on the dark theme.
It's scaling the text in the Options very bad. I attached some print screens for you.
![Untitled6](https://user-images.githubusercontent.com/59364663/71588967-fa3b4d80-2b2b-11ea-836f-882353f208e0.png)
![Untitled](https://user-images.githubusercontent.com/59364663/71588968-fa3b4d80-2b2b-11ea-9f0d-551d7a69b137.png)
![Untitled2](https://user-images.githubusercontent.com/59364663/71588969-fa3b4d80-2b2b-11ea-92c0-9281e6e6a26e.png)
![Untitled3](https://user-images.githubusercontent.com/59364663/71588970-fa3b4d80-2b2b-11ea-918b-fa73577ab589.png)
![Untitled4](https://user-images.githubusercontent.com/59364663/71588971-fa3b4d80-2b2b-11ea-8752-adfdd4b47288.png)
![Untitled5](https://user-images.githubusercontent.com/59364663/71588972-fad3e400-2b2b-11ea-98c3-5895ceb0773e.png)

**Comment by clsid2** [comment]
This is MY github project page, so I decide what I work on and what not. I am sick and tired of assholes who think they can demand stuff.

I don't want to digitally sign it. That costs money and is an invasion of my privacy.

Menu > File > Subtitles > Download

Your layout issues are because of text scaling in Windows 10. It works correctly if you instruct Windows to make everything bigger, instead of just text.

@adipose, can we ignore/override text scaling in the options?

**Comment by adipose** [comment]
@clsid2 

>can we ignore/override text scaling in the options?

Yes, I think so, but only if you change this most annoying of issue titles ;)

**Comment by adipose** [comment]
>Dude, why do you behave like this?????? If you don't have time, then don't read them! But don't give a half-assed answer, and instant close!!

This project is in maintenance mode, as the front page makes clear.  New features are going to be rare and only if someone has time or cares enough to make them.  You can reply to a closed issue if you want.

You are lucky clsid2 has kept this project alive.  I only work on it because I love this program.  Leaving every request open forever is just going to make it harder to find the higher priority issues.  And pretty much only bugs are high priority, since this software has worked well enough for a long time.

**Comment by LucianAndries** [comment]
> This is MY github project page, so I decide what I work on and what not. I am sick and tired of assholes who think they can demand stuff.
> 
> I don't want to digitally sign it. That costs money and is an invasion of my privacy.
> 
> Menu > File > Subtitles > Download
> 
> Your layout issues are because of text scaling in Windows 10. It works correctly if you instruct Windows to make everything bigger, instead of just text.
> 
> @adipose, can we ignore/override text scaling in the options?

Yes, I know it's yours, and I was VERY appreciative of it! And I asked very nicely. But you didn't see that, did you? smh

I wasn't an insensitive "demanding asshole". I literally said NEXT YEAR, 'coz you have a life, etc. And I said IF you have time.
And instead of just telling me NO, I DON'T WANT TO, 'COZ YOU'RE A DEMANDING BITCH, you didn't mention anything and just closed the thread instantly. Not fair.

Oh, I didn't know signing costs money. Sorry. I wouldn't had asked if I knew. Ok, I learned something.

Version 1.88 didn't have any scaling issues. Its own text was a fixed size, independent of Windows' scaling thing. Which makes this a BUG. And it's even more unusable on the black theme... The white theme HAS it too, but on a very small..............................scale. The answer is hidden between the 2 themes.
Scaling everything up... They are big enough as is, imo. My TV is just crap 1080p. If it were 4K, that would've made actual sense. And despite being 46", stuff on screen is big. :|
Hmm, if ignoring Windows Scaling is complicated, then maybe make the Options resizable? Or is this more complicated... :(

Look, I wasn't the bad person here. You just put me in the same barrel with bad ones.
I'm sorry for whatever I did. But i still have the right to the first question of this thread.
I wanted a nice back and forth conversation, not an entire complaining thread. Sorry. :(

**Comment by LucianAndries** [comment]
Different scaling between the themes. It's a weird one...

![white](https://user-images.githubusercontent.com/59364663/71609925-fe4f8580-2b94-11ea-96d6-d10abc0700ed.png)
![dark](https://user-images.githubusercontent.com/59364663/71609930-03acd000-2b95-11ea-8ded-f7fea502f0f4.png)

**Comment by adipose** [comment]
@LucianAndries 

I couldn't reproduce this.  Which version of windows are you running?

At 200% scaling, dialog looked like this for me:

![image](https://user-images.githubusercontent.com/3324395/71615249-2de69980-2b65-11ea-9796-3bcba0119f4a.png)

**Comment by adipose** [comment]
Never mind, I see it now.

**Comment by LucianAndries** [comment]
> Never mind, I see it now.

You see what?

I'm on Windows v1909, not insider.
Also: System -> Display -> Scale and Layout is set to 100%. And it's big enough for me already...
Ease of Access -> Display -> Make Text Bigger is set to 160%. And Make Everything Bigger is set to 100%.

Text might be 160%, but it's an ok size for my TV. If I set it lower, I won't be able to see anything.
Still, the White theme has small text, despite it being 160% in Windows. Sure, it has big text here and there, but not everywhere, like the Dark theme.
Version 1.88 MPC-HC didn't have any scaling issues though. That's why I call all of this "weird"...

**Comment by LucianAndries** [comment]
File -> Subtitles, is still too hidden... It would make more sense if you put **everything** about subtitles, in the "Subtitle Track". One setting here, one there, it's too shuffled....... :(

I'm not demanding anything. I'm just suggesting, nicely. You do what you want.

**Comment by adipose** [comment]
@LucianAndries Here is a test build for the font scaling issues:

https://mega.nz/#!QIR0AKZI!3gbX5yjxuBRSQQe8ehm3wZEd7brDjD-8J6XLrnOruJg

https://github.com/clsid2/mpc-hc/pull/201

**Comment by adipose** [comment]
> 
> 
> File -> Subtitles, is still too hidden... It would make more sense if you put **everything** about subtitles, in the "Subtitle Track". One setting here, one there, it's too shuffled....... :(
> 
> I'm not demanding anything. I'm just suggesting, nicely. You do what you want.

Please enter a separate issue if you have one.

**Comment by LucianAndries** [comment]
> @LucianAndries Here is a test build for the font scaling issues:
> 
> https://mega.nz/#!QIR0AKZI!3gbX5yjxuBRSQQe8ehm3wZEd7brDjD-8J6XLrnOruJg
> 
> #201

Yep, this one works fine. I see you made it ignore Windows' scaling.

Yes, it'd be cool if more features were added and stuff. But I understand you guys are just the few that try to keep this project alive. And it's hard when you are doing it for free. And way harder when ungrateful assholes like me start complaining... :P

Thant you for your hard work, dummies! And happy new year!

**Comment by adipose** [comment]
> Yep, this one works fine. I see you made it ignore Windows' scaling.

It honors the inherited dialog font, instead of overriding it with the "system" fonts. First versions of the dark theme replaced the hardcoded dialog fonts with system ones, but I didn't take into account that font zooming does not resize the dialogs.  Dynamically scalable dialogs are a different matter, but they could be done.

Since then I changed the default fonts of the dialogs to the more recent Windows UI fonts.  So I don't need to dynamically replace them anymore.  I threw out that old code, now.  It used the Windows API to detect the right fonts, but had the side effect of scaling them within an unscaled dialog.
