### ISSUE TITLE
Slider in filter property dialog not displayed correctly in dark mode

### ISSUE THREAD

**Issue by d3xMachina** [clsid2/mpc-hc#1960]
As per title, on the AC3Filter property dialog, the vertical sliders background is completly black in dark mode. There should be a vertical line visible.

Dark mode :
![image](https://user-images.githubusercontent.com/16732772/210460899-39686cf0-9b5d-4923-892c-ba9cdfdfe5ea.png)

Light mode :
![image](https://user-images.githubusercontent.com/16732772/210462792-b9b67f6a-b6a2-4349-96b8-ef218e249f39.png)

**Comment by adipose** [comment]
@adipose

Reminder to look at this.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2117

Turns out we had no vertical sliders in the core properties.  I also found that GetChannelRect is crazy, and returns the same values for vertical and horizontal sliders.  Maybe it's useful for a common draw formula, with everything rotated 90 at the end.
