### ISSUE TITLE
Speed setting for the lectures

### ISSUE THREAD

**Issue by xsoft** [clsid2/mpc-hc#1961]
In reaction to: [1.9.24](https://github.com/clsid2/mpc-hc/releases/tag/1.9.24)
And mirror from: https://codecs.forumotion.net/t4226-mpc-speed-setting-for-lectures#22281

I have a suggestion about speed control at MPC.

Is it possible to make it more like eg. YouTube?

**1) steps**
With automatic steps (which can be changed at options) to change from:
4x 2x (1x) 0.5x 0.25x 0.13x 0.06x 0.05x
to
8x 4x 2x 1.75x 1.5x 1.25x (1x) 0.75x 0.5x 0.25x.

**2)** also notice that when on **automatic steps**, and moving top bottom (to 0.05x) that when moving up, its:
(0.05x) 0.10x 0.20x 0.40x 0.80x 1.60x 3.20x
It will NOT hit 1.00x but skip instead up (due to rounding like 0.13x instead 1.25x or 0.0625x instead, which make sense to do) .

**3) the sound**
When changing video speed, then the audio is pitched up/down.
Can you use some filter to keep pitch constant?
I know this is not trivial to do (since you need some Fourier transformation to do that),
but maybe there is a clever filter that can do it instead of you.

Thanks for considering.
This would be really great when looking eg. on lectures. To speed them 1.25x, 1.5x would be great at MPC.
Direct jump to 2.00x (by default) and with high pitch is unusable.

Besides that, thanks for making MPC, its awesome and I'm happy users for like 20 years?

**Comment by clsid2** [comment]
Already possible!!!
Beyond the current options available, there will be no additional changes.

1) Options > Playback > Speed step
Menu > play > Playback rate

3) Options > Playback > Output > Audio Renderer > Sanear or MPC Audio Renderer
Those have automatic pitch correction
