### ISSUE TITLE
Mouse wheel in fullscreen always changes volume

### ISSUE THREAD

**Issue by FrankyBoy** [clsid2/mpc-hc#1963]
Hi,

I've rebound mouse wheel in settings to jump back/forward, but in full screen it still does volume up/down. Even worse, it also does volume up/down while hovering over the progress bar as well then. I cannot find any setting or key binding in that regard, which is flabbergasting, because it worked before I did a clean reinstall (due to other reasons).

**Comment by FrankyBoy** [comment]
Uhm, how about some actual response? This is not a feature request but a bug report about stuff that worked in the past.

**Comment by TechLooper** [comment]
Yes, I can confirm this is still a valid bug in v2.0.0.45. 
The mouse wheel works correctly to Jump Forward/Backward in window mode. But, changes to volume up/down in full screen mode. When back in window mode it behaves as expected again. 

Also, mouse button keys, like the mouse X2 Button, forget their programming and revert to default settings ("Next" video) when in full screen mode.  When back in window mode it behaves as expected again. 
 Thanks

**Comment by clsid2** [comment]
Look in the settings and you will notice there are TWO columns for mouse bindings, one for windowed and one for fullscreen.

So 100% user error.
