### ISSUE TITLE
[v1.9.24.51] Recurring disabled playlist

### ISSUE THREAD

**Issue by ryehamstrawberry** [clsid2/mpc-hc#1964]
Beginning with v1.9.24.51 it appears that enabling playlist in full screen mode will become disabled if full screen is exited then re-engaged.

This bug seems to persist even after exiting MPC-HC while playlist is enabled.

Previous versions have not had this issue.

**Comment by clsid2** [comment]
It re-appears when you move your mouse towards the area where playlist is located. It has always been that way, and there have not been any recent changes.

**Comment by ryehamstrawberry** [comment]
> It re-appears when you move your mouse towards the area where playlist is located. It has always been that way, and there have not been any recent changes.

I am aware of this being the correct behavior, but it is not behaving that way.

The playlist is literally being disabled on every full screen exit so that the playlist must be re-enabled via menu or CTRL+7.
Every time full screen is exited.

Is there some debug log I can send you?

**Comment by clsid2** [comment]
It works normally here. Test if the video renderer has any effect on the issue. Or the position of the playlist. Or if related to multiple monitors.

There is no debug logging.

**Comment by ryehamstrawberry** [comment]
Issue was due to operator error.

"Hide on Fullscreen" was apparently enabled, which I had no idea even existed as an option.
