### ISSUE TITLE
Doesn't Remember Sub Delay After Resuming Playback After a Long Pause

### ISSUE THREAD

**Issue by tamirkitan** [clsid2/mpc-hc#1966]
There used to be an issue in MPC-HC that after resuming playback after a long pause it would not remember the external subtitle file used, which seems to have been fixed in recent versions.

However, it still doesn't remember the sub delay that was set before pausing the playback.

**Comment by clsid2** [comment]
Options > Advanced > ReloadAfterLongPause = -1

I am not going to implement it for reload. Delay is not used often enough for me to spend time on it.
