### ISSUE TITLE
ESET GUI vs MPC-HC

### ISSUE THREAD

**Issue by eppelcs** [clsid2/mpc-hc#1967]
I have ESET Endpoint Security v10 on my computer. A video paused/stopped, when I open ESET's GUI then the mpc-hc immediately resumes/starts the video playback. You can watch the behavior inside the uploaded zip file.
[2023-01-02_11-10-40.zip](https://github.com/clsid2/mpc-hc/files/10383080/2023-01-02_11-10-40.zip)

**Comment by clsid2** [comment]
That is a bug in Windows 10/11. Has existed for a long time, so unlikely that Microsoft is ever going to fix it.

MPC-HC Options > Player > Keys > Uncheck "global media keys"

**Comment by eppelcs** [comment]
Thanks a lot.
