### ISSUE TITLE
Questions about files

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1969]
Hello

1) If I already have DirectX installed on my system, can I remove the files D3DCompiler_47.dll and D3DX9_43.dll?

2) If I don't use the MediaInfo tab, can I remove the MediaInfo.dll file?
![MediaInfo](https://user-images.githubusercontent.com/61148267/211926325-286c78d0-c9b0-410b-a78c-bcd3317d6691.png)

3) If I don't use shaders, can I delete the Shaders and Shaders11 folders?

4) If I only use the Russian language, can I delete everything in the Lang folder except mpcresources.ru.dll?

5) If I don't report errors in the program settings (EnableCrashReporter = false), can I delete the CrashReporter folder?

**Comment by clsid2** [comment]
1. Yes, but only if you have those files in your Windows system32 folder.
2. Yes
3. Yes
4. Yes
5. Yes
