### ISSUE TITLE
Dark Mode Distorts Options Window

### ISSUE THREAD

**Issue by jake9wi** [clsid2/mpc-hc#197]
If I activate the new dark mode It distorts the options window making it unusable. Switching off dark mode restores the options window.

![mpchc-darkmode-opts](https://user-images.githubusercontent.com/1775323/71611989-16bfa000-2b95-11ea-8f8f-88d74c4585d9.PNG)

![mpchc-opts](https://user-images.githubusercontent.com/1775323/71612079-a6654e80-2b95-11ea-95cd-126a7086baa3.PNG)

**Comment by adipose** [comment]
Seems like a dup of https://github.com/clsid2/mpc-hc/issues/196

**Comment by LucianAndries** [comment]
Cool, so it wasn't only me...
