### ISSUE TITLE
Disable video

### ISSUE THREAD

**Issue by trimechee** [clsid2/mpc-hc#1970]
Hello, thank you very much for this awesome wonderful amazing media player ! 🥇 💯 

Please i have request, sometimes when I go to sleep, I like to put a video that I downloaded previously or put a youtube video but the screen must be off to save the battery of my laptop so it will be great if our beloved Mpc-hc adds an option or button on the main interface to quickly deactivate the video and thus only listen to the audio of the video and thus save energy when you do not want to watch the video just like vlc player which also has this option, thank you very much !

**Comment by clsid2** [comment]
It is not possible disable video during playback and just hiding it does not save any decoding performance.

**Comment by trimechee** [comment]
Interesting ! thank you :)

**Comment by ale5000-git** [comment]
You could have a separate portable version of MPC-HC where video render is set to Null (anything), so the CPU use is reduced.
Also you can enable the advanced option `LockNoPause` to avoid stopping the video when the pc is locked.

**Comment by trimechee** [comment]
@ale5000-git Great ! Thank you very much for these precious ideas :) 🥇
