### ISSUE TITLE
Donations only possible in crypto currencies

### ISSUE THREAD

**Issue by Elementari** [clsid2/mpc-hc#1972]
Hello, MPC-HC 2.0 release has been mentioned in many online magazines etc, including hints that you're running out of coffee. And you say you only got 2 donations over a very long period of time.
I really think it would be be good if you made paypal donations or other methods of donation available, or at least explain why you don't. Crypto comes with some issues for some, depending on country etc. etc.

**Comment by awalkonthebeach** [comment]
I came to this forum to post about that.  
I wanted to donate, but the developer only accepts BC, which I've never used and I'm staying away from that stuff.  If you provide other means of accepting dono's, you may get more support.  

This developer definitely deserves more.

**Comment by clsid2** [comment]
Paypal is an evil company and not privacy friendly.

**Comment by clsid2** [comment]
Paypal also supports bitcoin for those use want to use it:
https://www.paypal.com/us/digital-wallet/manage-money/crypto
