### ISSUE TITLE
Irregular-sized videos seem to be not able to use GPU decoding

### ISSUE THREAD

**Issue by astroboylrx** [clsid2/mpc-hc#1975]
Common-resolution (e.g., 4K) videos can be played fine and use GPU for decoding. 

![image](https://user-images.githubusercontent.com/3999966/212244939-f35e8841-6192-429d-8c09-c9aaedc3707f.png)

---
But it seems videos with uncommon resolution may only be played with CPU decoding. What's the limit? Where may I find some materials to learn more about? Thank you very much in advance.

![image](https://user-images.githubusercontent.com/3999966/212245292-e68a00b6-481e-4236-8e8c-ffb34011bf1e.png)

**Comment by clsid2** [comment]
That one is wider than 4k.
Limits are defined by the GPU driver.
