### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by bege10** [clsid2/mpc-hc#1977]
> In the past years just 2 people have donated, so I am completely out of coffee to stay awake while coding :(

Thank you for development! I am one of the many others and I need other options than bitcoin. Easiest for me is Paypal.

**Comment by clsid2** [comment]
Other methods are not possible at this moment.

**Comment by clsid2** [comment]
Paypal also supports bitcoin:
https://www.paypal.com/us/digital-wallet/manage-money/crypto
