### ISSUE TITLE
Donations.

### ISSUE THREAD

**Issue by Kame03** [clsid2/mpc-hc#1978]
`In the past years just 2 people have donated, so I am completely out of coffee to stay awake while coding :(
`
As much as I'd like to donate I'd prefer to do it via Debit Card, Paypal or Monero. 
So I think you should look into adding these options.
also this: https://github.com/clsid2/mpc-hc/issues/383
it should be added to readme.md so more people can see and donate, I've been using MPC-HC for years and I never knew there was donations.

**Comment by clsid2** [comment]
Other methods are not possible at this moment.

**Comment by clsid2** [comment]
Paypal also supports bitcoin:
https://www.paypal.com/us/digital-wallet/manage-money/crypto

**Comment by TFWol** [comment]
@clsid2, I'm just hopping on a related thread to let you know to expect ~$98 or $100 your way, however bitcoin and 'gas fees' work.

I was shocked when you mentioned the lack of donations. This software is pretty important to me and I'd be annoyed too if people kept asking about features without giving some sort of support.

**Comment by clsid2** [comment]
Thanks!

**Comment by Kame03** [comment]
> Paypal also supports bitcoin: https://www.paypal.com/us/digital-wallet/manage-money/crypto

I'm from Serbia, we can only use paypal from the web browser, app is not released in our country, also I think they didn't add option here for bitcoins, also crypto is taxed.
