### ISSUE TITLE
ASS subtitle text broken

### ISSUE THREAD

**Issue by Hackjjang** [clsid2/mpc-hc#1981]
![image](https://user-images.githubusercontent.com/120134269/212537698-3db1f806-bf47-4bf6-bcb4-8b802a5bc894.png)
MPC-HC x64 ver.2.0.0

![image](https://user-images.githubusercontent.com/120134269/212538726-20c0d91a-2a43-4f69-9a04-2620db2e2384.png)
MPC-HC x64 ver.1.9.24

'♪' It happens intermittently when expressing notes.
ver.1.9.24 not problem.

Subtitle [here](https://github.com/clsid2/mpc-hc/files/10420019/GST.Isekai.Ojisan.-.12.1080p.zip).

**Comment by clsid2** [comment]
Fixed
