### ISSUE TITLE
Alternate donation links

### ISSUE THREAD

**Issue by smoopmeister** [clsid2/mpc-hc#1984]
I saw you mentioned the lack of donations; I personally clicked right away to donate but I will *not* use a crypto service to do so.

There are some alternatives that will make it much more appealing to others of a similar mindset. One I've used previously is https://ko-fi.com. I'm unsure of their split. buymeacoffee.com you keep 95% of the donation.

Just an idea, it might help, I'd already have donated if it was more accessible.

Apologies for raising an issue, couldn't think of another way but it does relate to the project...

**Comment by clsid2** [comment]
I appreciate the help people are trying to give, but I don't need suggestions for other methods.

**Comment by clsid2** [comment]
Paypal also supports bitcoin:
https://www.paypal.com/us/digital-wallet/manage-money/crypto
