### ISSUE TITLE
Donate!

### ISSUE THREAD

**Issue by anastrophe** [clsid2/mpc-hc#1985]
Yeah this isn't a real issue I know. But maybe it could help get the ball rolling with others. I've been using mpc-hc for many many years. I use it almost daily. It's great software, and the author certainly deserves a contribution. I just dropped a small ($10USD equivalent, at least as of today lol) of bitcoin, which is still on its way over the wire.

$10 is nothing, all other things being equal. Hard work should be rewarded. If only a tiny percentage of mpc-hc were to donate the author could buy enough coffee to stay away for years. Right?

So, donate!

**Comment by clsid2** [comment]
Thanks

**Comment by agentlemandoesnotconga** [comment]
Can I ask where you bought the $10 of bitcoin from? The places linked in the donation post (Coingate and Moonpay) require a $50 minimum, which I think discourages people from looking any further into donating.

**Comment by clsid2** [comment]
You can use Paypal:
https://www.paypal.com/us/digital-wallet/manage-money/crypto

**Comment by smoopmeister** [comment]
how about ko-fi.com? lol

**Comment by anastrophe** [comment]
Paypal unfortunately takes a fee on pretty much all transactions, except with registered non-profits. As a quickie method though, and a $1 minimum, hard to argue against them (many other arguments against them though, but unrelated). It looks like another method was mentioned but deleted, I looked them up - had never heard of them - and they seem like a legit option too actually.

As far as where I got my crypto, I bought years ago during the boom so have a large sum in reserve. I bought almost all of mine through Gemini, but as a large crypto exchange, you have to give them a LOT of information just to get started - photo ID, financial info, etc - so your best bet most of the time is to find a friend or relative you trust who already has crypto, and see if they'll sell you some.

**Comment by smoopmeister** [comment]
> It looks like another method was mentioned but deleted, I looked them up - had never heard of them - and they seem like a legit option too actually.

Wouldn't bother, repo owner wants crypto and not actual, easy donations. You'd think I'd used bad language or conversed negatively towards their mother.
Bet this gets deleted, too. Oh well, I'll go but myself a coffee instead.

**Comment by clsid2** [comment]
I do not want to use Paypal myself for many reasons. That should be obvious by the fact that I am explicitly not offering it as a choice.

Ko-fi (and others) also use Paypal. I do not want that. I also do not want suggestions for alternatives.

**Comment by vritme** [comment]
Gratefully donated.
MPC-HC is a gem ;).
YT playlist parsing into MPC playlist is a dream).

**Comment by Hara1234** [comment]
Hier meckert einer, das er sich kein Kaffee mehr leisten kann. Dann mein lieber Freund entscheide dich. Mach dein Krypto-Scheiss alleine oder gewöhne dir mal ordendliche Geldwege an. Mit Krypto und so ein Zeug bekommst du von mir kein Mitleid und auch keinen Cent. Ich habe schon vielen aus der Patsche geholfen und Massen mobilisiert- aber dieses Getue ist eine ganze Nummer zu Hoch. MfG Haraldwue@gmail.com

**Comment by zcraber** [comment]
@clsid2 Since you accept crypto, can you add your GitHub profile to [Brave Creators program](https://publishers.basicattentiontoken.org/)? Users who use Brave browse can donate to you with BAT.
