### ISSUE TITLE
Sound stop playing in Fullscreen mode on Display2?

### ISSUE THREAD

**Issue by bernid** [clsid2/mpc-hc#1986]
Hi, 
Thanks for great player. I've been using it happily for years.
Recently, I connected my thin client computer HTC to the TV (display2)  (DP->HDMI) in extended mode, switched audio renderer TV (audio to Intel displays) and wanted to watch a movie. Unfortunately in Fullscreen mode the sound turns off. 
I do not know what is it. In windowed mode on display2 (DP->HDMI), sound and video works. Also in Fullscreen mode on the display1 sound works. When I switch Fullscreen to  display2 the sound turns off.
My x86 MPC-HC and system:
```
Build information:
    Version:            2.0.0 (973b644a3)
    Compiler:           MSVC v19.29.30147
    Build date:         Jan 11 2023

LAV Filters:
    LAV Splitter:       0.77.1.1
    LAV Video:          0.77.1.1
    LAV Audio:          0.77.1.1
    FFmpeg compiler:    MinGW-w64 GCC 12.2.0

Operating system:
    Name:               Windows 11 (Build 22H2)
    Version:            10.0.22621 (64-bit)

Hardware:
    CPU:                Intel(R) Celeron(R) J4105 CPU @ 1.50GHz
    GPU1:               Intel(R) UHD Graphics 600 (driver version: 31.0.101.2115)
    GPU2:               Intel(R) UHD Graphics 600 (driver version: 31.0.101.2115
```
My computer has two DP.
screen1 i set to 1920 x 1200 @60p Hz
```
Supported Modes
640 x 480 (60p Hz)
720 x 400 (70p Hz)
800 x 600 (60p Hz)
1024 x 768 (60p Hz)
1280 x 960 (60p Hz)
1280 x 1024 (60p Hz)
1600 x 1200 (60p Hz)
1680 x 1050 (60p Hz)
1920 x 1080 (60p Hz)
1920 x 1200 (60p Hz)
```
screen2 TV I set to 1920 x 1080 @60p Hz
```
Supported Modes
640 x 480 (60p Hz)
720 x 400 (70p Hz)
720 x 480 (60p Hz)
720 x 576 (50p Hz)
720 x 576 (50i Hz)
800 x 600 (60p Hz)
1024 x 768 (60p Hz)
1152 x 864 (60p Hz)
1280 x 720 (50p Hz)
1280 x 720 (60p Hz)
1280 x 1024 (60p Hz)
1920 x 1080 (24p Hz)
1920 x 1080 (25p Hz)
1920 x 1080 (30p Hz)
1920 x 1080 (50p Hz)
1920 x 1080 (50i Hz)
1920 x 1080 (60p Hz)
1920 x 1080 (60i Hz)
1920 x 1080 (100p Hz)
1920 x 1080 (120p Hz)
2560 x 1080 (60p Hz)
2560 x 1080 (100p Hz)
2560 x 1440 (120p Hz)
3840 x 2160 (24p Hz, 4K)
3840 x 2160 (25p Hz, 4K)
3840 x 2160 (30p Hz, 4K)
3840 x 2160 (50p Hz, 4K)
3840 x 2160 (60p Hz, 4K)
4096 x 2160 (24p Hz, 4K)
4096 x 2160 (25p Hz, 4K)
4096 x 2160 (30p Hz, 4K)
4096 x 2160 (50p Hz, 4K)
4096 x 2160 (60p Hz, 4K)

```
EDIT: I tested the similar configuration with my laptop (not HTPC) connected via (HDMI not DP) to the same TV. 
Result the same: sound disappears when I switch to screen2 (option/playback/fullscreen)
My laptop:
```
Build information:
    Version:            2.0.0 (973b644a3)
    Compiler:           MSVC v19.29.30147
    Build date:         Jan 11 2023

LAV Filters:
    LAV Splitter:       0.77.1.1
    LAV Video:          0.77.1.1
    LAV Audio:          0.77.1.1
    FFmpeg compiler:    MinGW-w64 GCC 12.2.0

Operating system:
    Name:               Windows 11 (Build 22H2)
    Version:            10.0.22621 (64-bit)

Hardware:
    CPU:                Intel(R) Pentium(R) Silver N5000 CPU @ 1.10GHz
    GPU:                Intel(R) UHD Graphics 605 (driver version: 31.0.101.2115)
```

**Comment by clsid2** [comment]
You could try Sanear audio renderer and select device on the internal audio renderer page. Or if you already use that, try DirectSound.

Other than that I have no idea what is wrong. Might be a driver bug.

**Comment by bernid** [comment]
It mostly work (AC3, EAC3) with Sanear audio renderer and Microsoft DTV-DVD Audio Decoder (LAV Audio filters disappear). Thank you for pointing out.

I have still issues with 5.1 ACC streams. 
I used ffdshow audio decoder before (AC3 SPDIF encode mode)  but it seems like it doesn't work with Sanear renderer anymore.
Are there any ways (in MPC or with external filters) to encode acc 5.1 streams to ac3 or eac3?

**Comment by clsid2** [comment]
If LAV stops being used then it means that:
You are using bitstreaming, and you have "fallback to pcm" disabled, and bitstreaming isn't accepted by the audio device.

Most TVs only support AC3, DTS and 2.0 PCM.

If you are only using a TV and not a receiver, then I suggest to simply mix to stereo PCM output with LAV Audio. No point in bistreaming just to let the TV do downmix to stereo.

ffdshow should work fine with Sanear. Don't use the decoder, but instead use ffdshow audio processor as a preferred external filter in MPC. Enable Mixing + Resample + AC3 encode in ffdshow.

**Comment by bernid** [comment]
Thanks for valuable information. I will experiment with different player and TV settings. The most important thing is that it works.
I've had my new TV for a short time and haven't fully figured it out yet. Encoding multichannel AAC to ac3 works when I start playing from window to fullScren mode. It doesn't work when start to fullscreen right away (but it is not a problem). 
I connected the TV set to the old, good AVR (AC3/DTS) by the optic spdif cable. The TV can transcode multichannel Atmos and EAC3 streams to 5.1 AC3. Sometimes I use TV speakers, sometimes I switch to the external ac3/DTS AVR decoder.

![Schowek01](https://user-images.githubusercontent.com/1912477/213437567-8fe54bda-844d-48e1-b573-3cbb2ea8fa05.png)
