### ISSUE TITLE
After long pause reloading the video-file doesn't reload downloaded subtitles

### ISSUE THREAD

**Issue by WakeXT** [clsid2/mpc-hc#1989]
Downloaded subtitles (meaning after pressing the D-key) disappear in 2.0.0 after the reload.
Need to download it again which works around it (usually the already loaded subtitle is blocked from being downloaded again but in this instance it's unblocked again).

**Comment by clsid2** [comment]
Enable the option to save the downloaded subtitle.

**Comment by WakeXT** [comment]
Thanks for the quick reply.
I figured enabling that option might help but getting the temporary ones to return would require changing how they're handled in an event like this.
