### ISSUE TITLE
[Request] subtitles menu

### ISSUE THREAD

**Issue by Chicos123** [clsid2/mpc-hc#199]
**1. option to select multi language SAMI(.smi) file**

Request menu to select language A or language B or A&B in screen
![1](https://user-images.githubusercontent.com/23288869/71621202-3f857b00-2c11-11ea-8462-7c3d379664a0.png)

For now mpc-hc is mixing A and B language
![3](https://user-images.githubusercontent.com/23288869/71621915-9d1bc680-2c15-11ea-8ec3-3d8169174d70.png)

Example of multilanguage SAMI(.smi) file
[test.smi.txt](https://github.com/clsid2/mpc-hc/files/4012651/test.smi.txt)
```
<STYLE TYPE="text/css">
<!--
P { margin-left:8pt; margin-right:8pt; margin-bottom:2pt;
    margin-top:2pt; font-size:12pt; text-align:center;
    font-family:arial, sans-serif; font-weight:normal; color:white;
    }
.KRCC { Name:Korean; lang:kr-KR; SAMIType:CC; }
.ENCC { Name:English; lang:en-EN; SAMIType:CC; }
#STDPrn { Name:Standard Print; }
#LargePrn { Name:Large Print; font-size:20pt; }
#SmallPrn { Name:Small Print; font-size:10pt; }
-->
</STYLE>
```

**2. Request option to adjust subtitles delay window popup**

For manually inputting subtitles delay
![2](https://user-images.githubusercontent.com/23288869/71621531-2bdb1400-2c13-11ea-8d00-d8172372c6fb.png)

Best regards

**Comment by clsid2** [comment]
There already is a subtitle delay function:
Options > Subtitle > Delay step
You can press F1/F2 to add/subtract that value from the current delay. By with default settings, 2 second delay is 4 presses.

New functionality is not added, unless someone volunteers to implement it.

**Comment by Chicos123** [comment]
I know F1/F2 to adjust subtitles delay
but this function can't manually inputting subtitles delay

If i setting "delay step" to '1' ms, and pressing F1/F2
That should be a lot work to adjust

So i need single step setting subtitles delay
That is what i really want
![1](https://user-images.githubusercontent.com/23288869/71638379-e0bc1200-2ca1-11ea-924f-7a0eb2bb75f5.png)


Best regards

**Comment by clsid2** [comment]
Simply enter any desired value and press F1/F2 once. Then it acts exactly as you want, except that you need to press a key to activate the specified delay.

**Comment by clsid2** [comment]
There are no developers available that are interested in implementing this.
