### ISSUE TITLE
DVD subtitles (.sub) not loading

### ISSUE THREAD

**Issue by Daimie** [clsid2/mpc-hc#1992]
The following (binary) DVD .sub works fine with VLC, but MPC-HC doesn't load it at all:

https://mega.nz/file/qLhmgKxQ#9pTb1V6xUTC9F4GqYwq649hDajj8LtQLoij48PiBLmY

Any way to fix this?

**Comment by clsid2** [comment]
VobSub subtitles are a pair of .idx and .sub file. You need to open the .idx file.

**Comment by Daimie** [comment]
I thought so too, but for some reason this particular .sub file doesn't need .idx file to function (nor is there one available), the timestamps are included in the .sub.

(I tried with another .sub/.idx subtitle, VLC couldn't show it either so often you'll need both files.)

**Comment by clsid2** [comment]
This isn't a VobSub .sub file. It is a Matroska file with subtitles. The correct extension is .mks.

This format is not supported as an external subtitle by MPC-HC.

You can use MkvToolNix to merge it with the video file.

**Comment by Daimie** [comment]
Thank you for the clarification and solution.
