### ISSUE TITLE
Subtitle change settings are not applied

### ISSUE THREAD

**Issue by VetaLioSTV** [clsid2/mpc-hc#1993]
Hello. For a long time i have a problem while using mpc-hc, since it's not clear for me why and how that happening (i tried before with zero success).

Long story short, i'm watching frequently **BDRemux** .mkv (and not only) which has built-in different set of subtitles. Usually i need "forced"(they're marked as default approx everytime or just forced) subtitles. 

So my goal to achieve scenario -> apply automatically forced subtitles with corresponding(specific) language otherwise do nothing (automatically).

Problem: i do not understand why, but any setting which i'm trying to change on subtitles section are not applied / reflected for some reason. 

I tried to go step by step with provided instructions here - https://1f0.de/lav-splitter/lav-splitter-stream-selection/ , but as i said previously with zero effect.

Such variants for subtitles - 

- `*:rus;*:*|f;*:*|d”`
- `rus:rus|f;`

With no success.

I'm confused, where and which one category / setting should i change / revert and etc? 

I tried here (**_MPC-HC itself -> Options -> Internal Filters -> Splitter_**)
![image](https://user-images.githubusercontent.com/15155286/213882435-021998ee-ee18-4486-a10f-4236d95edfa1.png)

later here (**Codec tweak tool -> Direct Show Filter Configuration-> (both) LAV Splitter \ LAV Splitter (MPC-HC)** )
![image](https://user-images.githubusercontent.com/15155286/213882517-f2e2fe71-2085-4bc7-9b71-9c261bf30b59.png)

**LAV Splitter**
![image](https://user-images.githubusercontent.com/15155286/213882534-2e5be25f-dc54-464f-a6f8-41356a1bbadd.png)

**LAV Splitter (MPC-HC)**
![image](https://user-images.githubusercontent.com/15155286/213882594-a1b5bb8d-6d8f-4c4b-a8fc-567e62b0c305.png)

By the way, which one has priority, because i had impression that **Codec Tweak Tool** like "override's" / intersects one with other(but sounds like **LAV Splitter (MPC-HC)** and **Splitter** inside **MPC-HC** itself are the same stuff. What is difference between LAV Splitter vs LAV Splitter (MPC-HC) ?)  and has "more" power rather than changes inside of **MPC-HC**, i'm right here? Totall mess for me, sorry... 

Where should i do these changes, directly in **MPC-HC** either i can do changes at **Codec Tweak Tool** ?

I dont know what i changed today(somewhere in settings of **MPC-HC** i guess), but for now by default it chooses "No subtitles" everytime (previously it choosen always "english" non forced subtitles)

Examples - 

Movie 1
![image](https://user-images.githubusercontent.com/15155286/213882745-0e44f09c-ef0e-4fc2-b485-86c1ee737e64.png)

Movie 2
![image](https://user-images.githubusercontent.com/15155286/213882796-2fe3a8b8-54e3-4460-af71-57f2c08dee07.png)

and etc.

**Subtitles Settings** (Options -> Subtitles -> Misc) -
![image](https://user-images.githubusercontent.com/15155286/213882889-75326c05-7255-4171-98d4-de24d6816f7c.png)

**Playback Settings** -
![image](https://user-images.githubusercontent.com/15155286/213883529-1fdd3a0d-0a53-485d-af1c-45057527167a.png)

My **MPC-HC** version -
![image](https://user-images.githubusercontent.com/15155286/213883140-ce5e7c9e-7157-4fa3-8624-64e0958db68f.png)

Please advice.

**Comment by clsid2** [comment]
You need to configure it in the internal LAV Splitter, which is equal to LAV Splitter (MPC-HC) in CTT.

This is wrong `*:rus;*:*|f;*:*|d”` due to the quote at the end.

Use something like `*:rus;*:eng|df;*:*|df`
That means in order: Any russian sub, then default/forced English, then any other default/forced, then no sub.

Also select MPC Video Renderer, so that HDR videos do not look washed out.

**Comment by VetaLioSTV** [comment]
> You need to configure it in the internal LAV Splitter, which is equal to LAV Splitter (MPC-HC) in CTT.
> 
> This is wrong `*:rus;*:*|f;*:*|d”` due to the quote at the end.
> 
> Use something like `*:rus;*:eng|df;*:*|df` That means in order: Any russian sub, then default/forced English, then any other default/forced, then no sub.
> 
> Also select MPC Video Renderer, so that HDR videos do not look washed out.

thanks for fast reply, but it doesn't work. 

I made how you proposed (internal LAV Splitter) -
![image](https://user-images.githubusercontent.com/15155286/213894546-d0acfb0d-5e53-4945-a997-4cd6c0612ebb.png)

result is the same - 
![image](https://user-images.githubusercontent.com/15155286/213894589-7f67ece2-d53f-48f4-aab6-76d92b9e8416.png)

What i'm doing wrong..? Looks like some settings always overrides / interesects with internal LAV Splitter and thats why it doesn't updates as it should..?

`Also select MPC Video Renderer, so that HDR videos do not look washed out.`
Where?

**Comment by clsid2** [comment]
Options > Playback > Output

Show me what is shown in: Menu > Play > Filters

**Comment by VetaLioSTV** [comment]
> Options > Playback > Output
> 
> Show me what is shown in: Menu > Play > Filters

Finally i managed to make it work. I dont know why, but it requires for some reason(maybe bug?) to be duplicated as on **LAV Splitter (MPC-HC)** and at basic **LAV Splitter (non MPC-HC ?)** on **CTT**.

So currently i'm stopped on that setting - 
`*:rus|df;*:*|df`

Satisfied with it for now, maybe later i will tweak it, because finally i'm getting expected result! 

same movie looks now like that-
![image](https://user-images.githubusercontent.com/15155286/213894984-f577d4f2-f4ac-4673-95fb-9a484da46e2b.png)

About your suggestion (MPC Video Renderer), already did it, thank you! I hope it will change "noise" effect.

By the way, i remember previously i had huge problems with HDR / BDRemux / BD movies, since they was too laggy with no reason and usually after rewinding back / forward and solution was to use **Enhanced Video Renderer (custom presenter)** , which i think is some old fix(?). Unfortunately i didn't made note and i do not remember reference, but it was somewhere posted on forums / bugtracker i guess.

**Comment by clsid2** [comment]
Maybe somehow you have internal source filters disabled? That might explain why you needed to change for external LAV as well.

Enhanced Video Renderer (custom presenter) does not do HDR processing. So that could be why it has better performance, but also wrong colors. You can get help for that at K-Lite forum.

**Comment by VetaLioSTV** [comment]
> Maybe somehow you have internal source filters disabled? That might explain why you needed to change for external LAV as well.

Where i can check it? All settings should be as default, since i'm not too familiar with MPC-HC and i dont think that i disabled it somewhere

> Enhanced Video Renderer (custom presenter) does not do HDR processing. So that could be why it has better performance, but also wrong colors. You can get help for that at K-Lite forum.

ah ok, clear

**Comment by clsid2** [comment]
Options > Internal Filters

**Comment by VetaLioSTV** [comment]
> Options > Internal Filters

![image](https://user-images.githubusercontent.com/15155286/213940800-615760ed-6df1-4ddf-a94a-9d5ea8d1debf.png)

![image](https://user-images.githubusercontent.com/15155286/213940736-cd441a42-9bc4-4655-b91e-4cf91f859930.png)

![image](https://user-images.githubusercontent.com/15155286/213940738-a3df212c-118b-459f-9a25-20dfaa6fe6bd.png)

![image](https://user-images.githubusercontent.com/15155286/213940763-1d7d8033-6147-4add-bea9-189b7900ce59.png)

![image](https://user-images.githubusercontent.com/15155286/213940772-60c99a67-6e7f-4256-a57d-64abd65288da.png)

**Comment by clsid2** [comment]
In that second image, enable everything in the left column. So enable `Matroska` etcetera.

You can also use:
Codec Tweak Tool > Reset Settings

**Comment by VetaLioSTV** [comment]
@clsid2 already did it. (each check mark on left column).

I will check it and let you know if something dramatically changed. Thank you!
