### ISSUE TITLE
Incorrect subtitle style renderization in Windows 7

### ISSUE THREAD

**Issue by LazaroOnline** [clsid2/mpc-hc#1994]
Note: This issue does not occur in Windows 10.

In Windows 7 SP1, the custom subtitle styles are not rendered properly.
The size, custom fonts, positioning, fill-color, border-color etc are not displayed correctly, mostly are just skipped.
These custom styles are commonly used for on-screen signs and karaokes.
The version of MPC used was x64 v2.0.0 (973b644a3)

See the following video as a reference:
"[Judas] Dr. Stone S1 - 23.mkv" (314.1 MiB)
that can be downloaded from this torrent:
https://nyaa.si/view/1209184

VLC player v3.0.18 supports all these styles under the same Windows 7,  
while MPC skips the custom styles displaying the plain subtitles in the wrong position and size.

Here are some screenshots comparing the MPC and VLC renders of the same file and same subtitles.

Custom fonts example:  
<img width="1904" alt="Comparison-MPC-VLC-CustomFonts" src="https://user-images.githubusercontent.com/13026853/213932345-41e9c75b-f79d-4b57-b955-50feaaba4f58.PNG">

Signs position color and size example:  
<img width="1904" alt="Comparison-MPC-VLC-Signs-FontStyleAndSize" src="https://user-images.githubusercontent.com/13026853/213932382-77c4971c-0639-4adc-b9c9-faf693e00e4c.PNG">

Shape styles example:  
<img width="1904" alt="Comparison-MPC-VLC-RectangleShapeStyles" src="https://user-images.githubusercontent.com/13026853/213932418-3045ff9d-ae5f-4591-a806-6324c53e1abb.PNG">

Karaoke example:  
<img width="1906" alt="Comparison-MPC-VLC-Songs-Karaoke" src="https://user-images.githubusercontent.com/13026853/213932436-28377d74-30fc-4c0f-b248-6027f4e3f6bc.PNG">

This issue may help to decide if Windows 7 is actually supported or dropped out from the requirement list.

**Comment by clsid2** [comment]
Subs are rendered correctly here on Windows 7.

You probably have enabled forcing of default style.
Menu > Play > Subtitles > uncheck "Default Style"

**Comment by LazaroOnline** [comment]
> Subs are rendered correctly here on Windows 7.
> 
> You probably have enabled forcing of default style. Menu > Play > Subtitles > uncheck "Default Style"

Yes, that worked, thank you!
