### ISSUE TITLE
Incorrect color scheme

### ISSUE THREAD

**Issue by ValeriiYusenko** [clsid2/mpc-hc#1995]
Hi! I've got some problem with the color scheme in MPC-HC (64-bit) 2.0.0 version. For example, the Netflix logo color is orange, but it should be red, and it is red in other players. Please help me to resolve this problem, beacuse your player is the most comfortable to me, and I don't wanna switch to another one.
![Screenshot_1](https://user-images.githubusercontent.com/123325149/213934459-8c547bb9-e8c9-4507-abf8-cb626dd9836a.png)

**Comment by clsid2** [comment]
Read the information regarding HDR video here:
https://github.com/clsid2/mpc-hc/releases/tag/2.0.0

**Comment by ValeriiYusenko** [comment]
> Read the information regarding HDR video here: https://github.com/clsid2/mpc-hc/releases/tag/2.0.0

Thank you very much. I've installed K-Lite Codec Pack and it helped.

**Comment by THEtomaso** [comment]
Just a thought, but it might be time to include HDR support by default in MPC-HC, like in MPC-BE.
There are lots of people watching such videos these days, you know..
