### ISSUE TITLE
styles not applied to embedded subtitles

### ISSUE THREAD

**Issue by azk963** [clsid2/mpc-hc#1997]
Styles are not applied to embedded subs (mkv file)
I can live with no custom colors/font etc.  but at least the transparency should work.

I'm just trying to get the subs 60% opaque, that only works with external srt files though :(  
(i can't find well synced / good quality SRTs on some videos, so i must use embedded ones, but the pure white text is horrible on dark scenes...)

**Comment by clsid2** [comment]
ASS/SSA subtitles have their own styles. You can force the "Default Style" by enabling that option in the subtitle menu. But be aware that it will look bad for certain subtitles.

If it truely is embedded SRT (subrip) that is giving problems, then you are not using the latest version of the player.

**Comment by Azzuray** [comment]
This is an actual issue, this are not present on earlier version like 1.9.21 / 1.9.24 etc , but when i went to update to 2.0 subtitle where all wrong, and no .ASS style were present or if i uncheck "default" style , on SRT its over bold + opaque and such , im not willing to réinstall the 2.0 version to redo all my settings to show you

**Comment by clsid2** [comment]
It is working perfectly fine for me with 2.0.0 so if I do not get a reproducible case it will never be fixed.

**Comment by Kered13** [comment]
Thank you, I can confirm that was the issue. I looked all over the options for it and couldn't find the force option, before realizing it was in the Play menu. I'm not sure when or how that got enabled.

**Comment by 13gears13** [comment]
2.4.0 here, same same

**Comment by clsid2** [comment]
User error
