### ISSUE TITLE
Playlist ui bug when snapping to the right

### ISSUE THREAD

**Issue by vathanac** [clsid2/mpc-hc#1998]
![image](https://user-images.githubusercontent.com/87689818/214377063-c0464643-3c97-42c4-b35b-5ab293ea2af8.png)

**Comment by vathanac** [comment]
Only occur in dark mode

**Comment by adipose** [comment]
@adipose

Reminder to look at this.

**Comment by adipose** [comment]
@vathanac , I could not reproduce this.  Can you give more details of how to make it happen?

**Comment by clsid2** [comment]
I am also not seeing those two grey vertical lines. I do see a grey inner border around the playlist, which is missing in the screenshot above. Maybe related and rendered in wrong place somehow. Or maybe just cropped away in the screenshot.

Maybe a different inner borderstyle will look better? Also in light mode.

I am also considering if maybe having it docked at right side by default is better than at bottom at default. adipose, what do you think?

**Comment by adipose** [comment]
> I am also not seeing those two grey vertical lines. I do see a grey inner border around the playlist, which is missing in the screenshot above. Maybe related and rendered in wrong place somehow. Or maybe just cropped away in the screenshot.
> 
> Maybe a different inner borderstyle will look better? Also in light mode.
> 
> I am also considering if maybe having it docked at right side by default is better than at bottom at default. adipose, what do you think?

Either right or left makes more sense for a playlist, esp. with wide screens.

For the border, not sure if a border is needed at all.  I can't remember exactly why I did it that way, but I think I just made it as narrow as possible.  I can check it and see if the border is easy to remove.

**Comment by adipose** [comment]
Border is the default border for listctrl, which is generally necessary in a form.  In a window where it's the only thing, it's not as necessary, but it does look a bit weird:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/03da2c7e-d4ac-4bb8-ab34-d20e9818964e)
