### ISSUE TITLE
Cannot play RTSP stream

### ISSUE THREAD

**Issue by vico93** [clsid2/mpc-hc#1999]
Hello!

I'm trying to view my ipcam's RTSP stream on mpc-hc, but although no error happens when i paste the url, neither audio or video appears when i try to reproduce it.

According to Details tab on properties, the stream is:
```
Video: MPEG4 Video (H264) 1280x720 33fps [V: h264 constrained baseline L3.1, yuv420p, 1280x720]
Audio: AAC 48000Hz stereo [A: aac lc, 48000 Hz, stereo]
```

I only installed mpc-hc (current version: 2.0 973b644a3), and no codec packs on my system.
My OS is Windows 10 x64 build 22H2.
If i use VLC i can play normally the same stream.

**Comment by clsid2** [comment]
I can't help you.

**Comment by vico93** [comment]
> I can't help you.

Best issue-close comment ever
