### ISSUE TITLE
Multi monitor issue

### ISSUE THREAD

**Issue by iG8R** [clsid2/mpc-hc#20]
Hi.
During the playback of Twitch streams in MPC-HC, after minimizing the MPC-HC window on monitor#1 an interruption in audio and video streams is initiated until its ultimate stop. Youtube streams only have some interruptions in audio and video but not stop. At the same time nothing happens while minimizing on monitor#2.

**Comment by clsid2** [comment]
Try changing this setting:
Options > Playback > Output > Reinitialize when changing display

**Comment by iG8R** [comment]
Thank you!
I unchecked this setting and It helped.
