### ISSUE TITLE
Subtitles are no longer centered with Internal Subtitle Renderer after resizing the video

### ISSUE THREAD

**Issue by Shajirr** [clsid2/mpc-hc#2001]
After upgrading to v2.0.0, subtitles are no longer rendered at the centre of the screen after resizing the video, 
instead they are rendered to left, can even be partially outside of the video frame.

So far this happened in all videos I've tested.

Restarting the player does nothing.
Downgrading to previous version - 1.9.24 - also does nothing.
This happens regardless of "Default style" being selected or not.
None of the subtitle settings fixed this.

Another subtitle renderer - XySubFilter - seems to work fine, this happens only with internal renderer selected.

**Comment by Shajirr** [comment]
Further testing revealed that this is somehow related to MadVR - when other video renderers are selected, internal subtitles are displayed correctly. However, I did not change any MadVR settings and cannot figure out what causes subtitle offset.

**Comment by clsid2** [comment]
madvr options > processing > zoom control > move subtitles = to bottom, or disabled
It messes up when moving to active video area.
