### ISSUE TITLE
Video quality declining

### ISSUE THREAD

**Issue by Sensio79** [clsid2/mpc-hc#2006]
I have used media player classic for a while. And never had the quality been bad. But today the quality was so bad, and i knew the file quality was pristine. So whats wrong?

**Comment by clsid2** [comment]
You have provided zero information, so my guess would be your graphics driver post processing.

**Comment by Sensio79** [comment]
Since i have not changed my system lately, and i have updated the player when needed i dont know what changed. Running version 2.0.0 now the 64 bit version. In a windows enviroment. Nothing changed. But the video quality is bad. Shadows, dark. Coulours...

**Comment by clsid2** [comment]
If you have Intel graphics driver, then disable "Contrast Enhancement" in the driver settings.

If you are playing HDR video, then you need to install this and select it as video renderer in MPC-HC settings:
https://github.com/Aleksoid1978/VideoRenderer/releases

**Comment by Sensio79** [comment]
Yes its look like i am using an intel driver. I actually use my television as a screen. Doesnt seem to find this driver setting. Been looking in the system. Also dont se any video render option in Media player classic settings. But thanks for the help anyway Have a nice day..

**Comment by clsid2** [comment]
Option is in the Intel graphics control panel. If you can't find that you need to install driver from Intel website.

MPC-HC options > Playback > Output > Video Renderer

Check if your computer is using correct resolution to output to the TV.
