### ISSUE TITLE
MPC ask to update but I already have the latest version 2.0

### ISSUE THREAD

**Issue by Onizuka20** [clsid2/mpc-hc#2008]
Hello,

Like I said in the title, I have the version 2.0 installed, but if I go to info shows 1.9.23 and sometimes ask me to update:

MPC-HC
------

Build information:
    Version:            1.9.23 (a8e9113b5)
    Compiler:           MSVC v19.29.30145
    Build date:         Aug 26 2022

And I think this happened to the previous version too.

Thank you.

Regards,
Onizuka20

**Comment by clsid2** [comment]
If info shows 1.9.23 then it is that version that is installed.

**Comment by VetaLioSTV** [comment]
@clsid2 can be added "code push" strategy for updates? Its pretty annoying to do same things when updates comes, you need download / install manually. :(
