### ISSUE TITLE
Inversed rgb to bgr on amd 680m

### ISSUE THREAD

**Issue by safarirat** [clsid2/mpc-hc#2014]
Video: HVC1 3840x2160 23.976fps 16554kbps [V: video handler [eng] (hevc main 10 L5.0, yuv420p10le, 3840x2160, 16554 kb/s)]
![изображение](https://user-images.githubusercontent.com/23118902/217050307-10cf6582-829a-4279-beef-78cb57250dd5.png)

**Comment by safarirat** [comment]
Ok, it's video driver issue. have same issue in other players/

**Comment by clsid2** [comment]
Looks like this file might contain Dolby Vision. That requires special colorspace handling and that is not supported by MPC-HC and most other players. You should get regular HDR video instead.
