### ISSUE TITLE
Contrast, Saturation going to -100

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2015]
**This happens with MPCHC+MPCVR(D3D9), when playing 10bit movie or HDR video from youtube.**
MPCHC+MPCVR(D3D11) is okay.
MPCHC+EVRCP is also okay.
LAV settings are untouched.

GPU: Intel HD graphics 4400
Intel's image enhancement related settings are all disabled.

_[Tested on amd and nvidia. It is okay there.]_
Problem video: https://anonfiles.com/H7BcP6W5y9/2023-02-09_11-15-19_-_Trim_mp4

**Comment by bibsp** [comment]
> This happens with MPCHC+MPCVR(D3D9), when playing 10bit movie or HDR video from youtube.

Why I'm reporting this is MPCBE+MPCVR(D3D9) is okay.

**Comment by clsid2** [comment]
It must be bug in Intel driver.

What is the range shown of the sliders? -100 to +100?
Does reset button change values to 0?

**Comment by bibsp** [comment]
> What is the range shown of the sliders? -100 to +100?

Yes.


> Does reset button change values to 0?

Reset button **doesn't** work when such video is playing.
Reset works if different video is playing or lauch the empty player.

**Comment by clsid2** [comment]
Then it seems the driver is giving a wrong default/neutral value.
Are you able to manually change the value to 0?
Do changes have any visual effect?
Do brightness changes work?

**Comment by bibsp** [comment]
> Are you able to manually change the value to 0?

**No**. I can move the slider. But value is always -100


> Do changes have any visual effect?

**No** visual effect with 8bit/HDR video.
Other videos show visual change.

> Do brightness changes work?

No. Nothing works.

**Comment by clsid2** [comment]
Does adjusting values show visual effect in MPCBE?

**Comment by bibsp** [comment]
**No** visual change in BE.
Then it is definitely driver bug. Thanks.

**Comment by clsid2** [comment]
Are there any issues with the wrong value being remembered if you first play the HDR file and then a normal one?

**Comment by bibsp** [comment]
No. there is no issue with that -100 value with normal video. -100 does nothing.

**Comment by clsid2** [comment]
Here is a test build that uses 0 when the range is invalid:
https://www.sendspace.com/file/1uzsg1

**Comment by bibsp** [comment]
Test build is broken maybe. Can't play any video. Can't render the file.

**Comment by clsid2** [comment]
It is just the player exe. Replace the exe of your current installation.

**Comment by bibsp** [comment]
Yes, it is fixed.

**Comment by bibsp** [comment]
> Here is a test build that uses 0 when the range is invalid: https://www.sendspace.com/file/1uzsg1

In this build there is a issue with ass subtitle.
My shadow value is 1.0000
With srt everything is okay.
With ass and **force default style is checked**, the shadow is not visible. It gives similar amount of shadow if I increase the value like, 4.0000.
Then with srt this 4.0000 value gives huge amount of shadow.
Basically it is not matching.

**Comment by bibsp** [comment]
Your commit on 25th Jan might be causing this issue.
Version 2.0 is fine.
Do you need screen recording?

**Comment by clsid2** [comment]
Already fixed. You need to wait for new build and use 2.0.
