### ISSUE TITLE
Feature request: Preferred audio and subtitle track

### ISSUE THREAD

**Issue by Dr-InSide** [clsid2/mpc-hc#2016]
(Sorry, Pull Request is somehow not working properly, so I write my request here).

I've been missing for years in MPC-HC a function where you can select preferred language for audio and subtitle tracks for normal video files [mp4, mkv, ...] (just like in DVD settings). The function should be switchable on/off and it should be selectable automatically (by system language) or manually. Of course for audio and subtitles separately adjustable.

Maybe a simple solution would be to rename the DVD settings in general to language settings and apply the settings not only for DVD/BD but also for individual files. MP4 and MKV usually have language IDs stored in the tracks.

Every time I open a video file with multiple languages, MPC-HC always takes the first available language and you must then change the language each time. This is a bit annoying, especially when watching series.

I would be very grateful if this could be implemented.

Thank you!

**Comment by Dr-InSide** [comment]
Sorry for the request. I did not see that you do not accept requests.

**Comment by clsid2** [comment]
Already exist in the settings of the internal splitter.

I suggest that you install the K-Lite Codec Pack. That offers language options directly in the installer.
