### ISSUE TITLE
Potential undefined behaviour in SyncRenderer?

### ISSUE THREAD

**Issue by tobi-tobsen** [clsid2/mpc-hc#2018]
I just stumbled upon this line in the SyncRenderer and it might be nothing, but I wondered anyways: 

https://github.com/clsid2/mpc-hc/blob/29a1254b5d4cadd3916b3ae4d3456bc3410af213/src/filters/renderer/VideoRenderers/SyncRenderer.cpp#L2965

is there specific a reason why you are not defining that member variable as `volatile bool m_bPendingRenegotiate;` or even `std::atomic<bool> m_bPendingRenegotiate;` (not sure if e.g. WAIT_TIMEOUT is called from a different thread)?

**Comment by clsid2** [comment]
I have no idea. I did not write that code.

**Comment by v0lt** [comment]
I changed the type of m_bPendingRenegotiate to std::atomic_bool [in the MPC-BE code](https://github.com/Aleksoid1978/MPC-BE/commit/4d4e2a068b8d2cc15f3e7a8f895d1d7d5e2615a4).

**Comment by clsid2** [comment]
Did same change for EVR-CP/Sync
