### ISSUE TITLE
Incorrect playback length for old AVI file

### ISSUE THREAD

**Issue by BreakPoints** [clsid2/mpc-hc#2019]
The linked archaic AVI file has a video Cinepak stream that is 36 seconds long and an audio stream of the same length but when played through MPC-HC the video ends at 22 seconds, cutting off the speech.

Could be the video is coded incorrectly, other video files from the same source seem to be okay.

[Video in question](https://mega.nz/file/GsB0kAzb#de5wb1XP9yCjshTiGL3vKuNlb69WUkZYx1YMRBzj63o)

**Comment by clsid2** [comment]
Probably broken file.
The internal filters are developed in a different project. If you want to fixed you need to report the issue to FFmpeg.
