### ISSUE TITLE
Custom toolbars no longer work with the new dark theme 

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [clsid2/mpc-hc#202]
@clsid2  please allow for some time before closing the issue, as helpful as the yesterday @adipose's answer was, (since it's maybe pointing in the right direction) the issue is however not solved. 

This is what the toolbar_dark looks in .bmp
![Toolbar_bmp](https://user-images.githubusercontent.com/17363930/71649444-24009a00-2d0f-11ea-98c5-8bdc6534735a.PNG)

And this is what it looks like in .png
![Toolbar_png](https://user-images.githubusercontent.com/17363930/71649450-3084f280-2d0f-11ea-9002-3063122f06b4.PNG)

This is what it looks like with white theme, when rendered properly.
![Toolbar_white](https://user-images.githubusercontent.com/17363930/71649453-37ac0080-2d0f-11ea-81d1-ad9e24b1679d.PNG)

**Comment by adipose** [comment]
Do you have a link to the toolbar file?

Not all toolbars will be compatible. It tries to invert the colors, but a multi colored toolbar may not work. Lots of custom toolbars are working, but I can't guarantee they all will.

**Comment by adipose** [comment]
Also difference between bmp and png makes no sense, unless you lost the alpha channel when converting.

**Comment by Vulgaris-Viridis** [comment]
>Do you have a link to the toolbar file?

Sure, here you go:
https://trac.mpc-hc.org/raw-attachment/wiki/Toolbar_images/mpc_toolbar_oxygen_white_32.zip

>Not all toolbars will be compatible. It tries to invert the colors, but a multi colored toolbar may not work. Lots of custom toolbars are working, but I can't guarantee they all will.

I see... Well the dark theme is obviously worth sacrificing the look a little bit if it doesn't work but the thing is, I've been using this toolbar for the past couple of years and now with any other mpc looks just wrong if you know what i mean. So i'd like to keep it if possible.. Anyway, thanks for looking into this @adipose..

**Comment by adipose** [comment]
@Vulgaris-Viridis There are special rules for colored toolbars (a recent change).  On reflection, I think it is a bug that the dark theme doesn't entirely honor them.  Here's a test build to fix that issue.

https://mega.nz/#!hUBTyKDA!Rcom2bHdu3_A7f1OA4IrWkT2EVWr19wVequb-pStxHA

Now you can name your toolbar color_toolbar_dark.bmp, and it won't mess with it.  If you don't like it, tough--adjust the colors in photoshop. ;)

https://github.com/clsid2/mpc-hc/pull/207

**Comment by Vulgaris-Viridis** [comment]
Hi @adipose, well first of I appreciate you taking the time to look into this, I've just tested it, it works great!

I feel there's no need to keep this issue open any longer, especially since the official fix is on it's way as well.

Once again, much appreciated!
