### ISSUE TITLE
Please add the Long Path Manifest

### ISSUE THREAD

**Issue by Squall-Leonhart** [clsid2/mpc-hc#2020]
When dropping a selection of folders containing videos onto the play list, MPC:HC will add the files inside via relative path handling unlike dropping the file directly which is converted to 8.3 short name, as a result the former is subject to the Path Limit 

Both a registry change and Manifest update are required for Long Path awareness, the feature cannot do anything unless both the system has it enabled, and the application has the manifest change.  Having the feature enabled also does not alter the behavior of dropping the video file directly either.

I have confirmed with https://github.com/eladkarako/manifest that nothing has broken as a result.

```<application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
        <ws2:longPathAware>true</ws2:longPathAware>
    </windowsSettings>
</application>
```

**Comment by clsid2** [comment]
It already supports long paths by using the `\\?\` prefix.

The manifest does not change how dropping a folder is handled.

**Comment by Squall-Leonhart** [comment]
> It already supports long paths by using the \\?\ prefix.

Except it doesn't, drop a a collection of folders onto the play list where one or more have file paths exceeding 260 characters, and those that do will throw "Invalid Path" when you attempt to play them.

> The manifest does not change how dropping a folder is handled.
it lets MPC:HC read the >260 character path for the file that could be inside that folder.

**Comment by clsid2** [comment]
Fixed in a better way that works out of the box on all supported version of Windows.
