### ISSUE TITLE
[bug] change in playback speed changes the audio wierdly

### ISSUE THREAD

**Issue by venkat2305** [clsid2/mpc-hc#2024]
i changed the playback rate in mpc-hc and vlc for a downloaded video. on vlc there's no issue but on mpc-hc audio has changed wierdly(probably the pitch is increased) and is not comfortable to hear. sorry for my poor explanation, im happy to answer any questions. thanks

**Comment by clsid2** [comment]
https://github.com/clsid2/mpc-hc/issues?q=is%3Aissue+pitch+is%3Aclosed
