### ISSUE TITLE
Natural sorting on automatically detected folder with local subtitles

### ISSUE THREAD

**Issue by Wiethoofd** [clsid2/mpc-hc#2025]
Currently when there is no embedded or local subtitle, but a folder with automatically detected subtitles the ordering is incorrect as can be seen in the provided screenshot.

Ideally the automatically detected subtitle files would be 'natural sorted' based on their filenames, so it starts with 2_English followed by 3_Arabic, in this case. Instead of starting at the `10-19, 20-29 , 2, 30-39, 3` etc.
![MPC-HC Subtitles](https://user-images.githubusercontent.com/9917564/218288269-da179c6d-1b0a-4d02-9173-3ad6099c91cc.jpg)
Setting language order in the subtitle preference to be `English,eng` (in case English is preferred) does work as workaround, but the file order is now inconsistent with what Windows Explorer/Finder display.

**Comment by clsid2** [comment]
It uses logical alphanumeric ordering.

I have no interested in making any changes. The people who creates these files should use 01 and 02.
