### ISSUE TITLE
[feature request] Save displayed image (auto)

### ISSUE THREAD

**Issue by JasioNiezdara** [clsid2/mpc-hc#2026]
Hey.
I love your work on MPC-HC. My favorite player for as long as I can remember. Glad you picked up the support for it.

The player is pretty much perfect to me. But I recently switched from madVR to MPC Video Renderer, and now I'm missing one feature - saving upscaled screenshots.

madVR allows you to save screenshots upscaled to your desired resolution using whatever scaling method you choose.
But I don't need something that advanced. MPC-BE allows you to capture what you see on screen (including any kind of processing).

For example, I'm watching a 1080p video in 3840x2160 using Jinc upscaling, so the saved screenshot will be exactly what I'm seeing on screen (3840x2160 upscaled with Jinc).

Any chance of adding such feature? I'd really appreciate it!

**Comment by clsid2** [comment]
I am not adding any new functionality.

You can use Winkey+Prtscr function from Windows to save fullscreen screenshot.
