### ISSUE TITLE
Choppy playback of V_MPEG4/ISO/ASP (xvid) streams when in an mkv container

### ISSUE THREAD

**Issue by dio-gh** [clsid2/mpc-hc#2029]
Hi,

I was moving some old xvid content between containers (avi -> mkv) with ffmpeg, but upon trying to play it, I noticed that the playback was choppy. After confirming it's not an issue with the contents of the file per se (every frame is unique, the framerate is set correctly, plays correctly in mpv), I checked the playback statistics, and noticed that MPC-HC is hovering at around 12.5-15 FPS. This lead me to believe that this is probably a bug of some sorts (the video should be running at 25 FPS, so pretty much exactly every other frame is dropped).

I also checked with the last official release of MPC-HC as well from years ago and found the same issue. If the fork doesn't intend to fix issues of this kind because it was also present in the original release, I suppose this ticket should be discarded.

~~I'm not sure if it's fine to share samples here due to legals, if it is, I'll try and cut one.~~ If there are other ways I could collect info about what might be going on, please let me know.

**Update:** seems like even though the contents of the file is *alright*, the issue ***is*** specific to the file; I just remuxed two others and those work fine. I'll try conjuring up a sample after I get back home.

**Update 2:** here's a two minute sample, if it's legally problematic to have it here, please let me know and I'll remove it:

[mkv_sample.mkv.gz](https://github.com/clsid2/mpc-hc/files/10774613/mkv_sample.mkv.gz)

The incantation used to generate it was the following (the filenames have been censored):

```
ffmpeg -fflags +genpts -i input.avi -ss 0 -t 120 -c:v copy -c:a copy output.mkv
```

The rationale behind me using the `+genpts` flag: https://superuser.com/a/1424470

Sample of the source file, generated using the ~same command:

[avi_sample.avi.gz](https://github.com/clsid2/mpc-hc/files/10774662/avi_sample.avi.gz)

**FFmpeg revision identifier:** `N-109234-g0c5af908c1-20221126`
**MPC-HC revision identifier:** `2.0.0 (973b644a3)`
**OS:** Windows 11 Pro 22H2 (revision: `22621.1265`)

**Comment by clsid2** [comment]
Use MkvToolNix to remux your files.

**Comment by clsid2** [comment]
Menu > View > Renderer Settings > Presentation > Enable frame time correction

**Comment by dio-gh** [comment]
> Menu > View > Renderer Settings > Presentation > Enable frame time correction

Works, thanks. I reckon FFmpeg produces malformed MKVs then? Tested it with MKV Toolnix now and that does produce a file that works proper.

**Comment by clsid2** [comment]
Yes, FFmpeg must be messing up timestamps.
