### ISSUE TITLE
subtitle problem when using xysubfilter

### ISSUE THREAD

**Issue by zozi81** [clsid2/mpc-hc#2030]
Hello

if i use mpc-hc with xysubfilter there are more problems.
if there is an external subtitle in the mkv (.srt) or if it is downloaded, then this is loaded and cannot be changed. The OSD shows the next subtitle, but the active subtitle remains the .srt

With xysubfilter the subtitle on/off does not work. (w)

the internal subtitle renderer works fine, but I need the xysubfilter for HTPC and madvr for CS Screen.

mpc black edition works in this setup, but i prefer to use mpc-hc.

Thanks in advance.

**Comment by clsid2** [comment]
All those subtitle functionality that you are talking about are only for the internal subtitle renderer. They do not work with external renderer, and I have no plans to implement that.
