### ISSUE TITLE
Making MPC-HC available on the Msoft Store for download and auto updates?

### ISSUE THREAD

**Issue by veermaharaj** [clsid2/mpc-hc#2031]
I didn't know who/how to ask about this, so this is a shot in the dark.

I would like to make MPC-HC available on the Msoft Store for download and auto updates? Would this be possible and what would it entail?

Is it something I could do for the community and oversee?

I am seriously green behind the ears and not familiar with this kind of thing. I am very willing to help.

**Comment by clsid2** [comment]
That is never going to happen. I hate the MS store. It has zero benefit for me.
