### ISSUE TITLE
Consider another way to donate, e.g. Zelle, gift card to email, etc...

### ISSUE THREAD

**Issue by alexwilliamsdr** [clsid2/mpc-hc#2033]
I use this program a lot and on many computers and highly recommend it to others since 2015, with that said, I really do appreciate all the development that has been done and is being done to keep this program running....can you find other ways to donate other than bitcoin? I'm sure there are more than 2 people who would donate if other options were available where they'd feel more comfortable doing it that way.

**Comment by Yanngo** [comment]
I've also considered donating. 2 donations over the course of several years? Damn. I feel sorry. This work deserves more reward.
But donating via Bitcoin is a bit tricky. If only there were other options...

**Comment by clsid2** [comment]
There are already like 10 closed issues about this. There are no other methods.

**Comment by alexwilliamsdr** [comment]
Ok thanks, sorry, didn't see those, I hope there is in the future, and thank you for all the work you've put into this project.
