### ISSUE TITLE
Where does mpc-hc store its favorites?

### ISSUE THREAD

**Issue by hundenase** [clsid2/mpc-hc#2035]
Dear you,

thank you very much for continuing this great project.

1 question bothers me:
Where are the favorites stored, how do I export or transfer the favorites to a new installation?

THX,
Marcus

======================

Moin:

(wie) ist es möglich, die angelegten Favoriten (für Internetstreams) zu sichern bzw. mitzunehmen in eine neue Installation?

Herzlichen Dank,
Marcus

**Comment by clsid2** [comment]
Options > Miscellaneous > Export

HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\Favorites
