### ISSUE TITLE
Paste from clipboard

### ISSUE THREAD

**Issue by trimechee** [clsid2/mpc-hc#2036]
Hello, thank you so much for this awesome player ! 🥇 
Please it will be great and very important to any media player if we can open links quicly specially streaming links, and it will be amazing to add shortcut "ctrl+v" to quickly  open link from clipboard or add option "paste from clipboard" to play quickly streaming links, thank you !

**Comment by clsid2** [comment]
Ctrl+O then Ctrl+V

I am not adding any new functionality.

**Comment by trimechee** [comment]
It already exists ? Thank you :)
