### ISSUE TITLE
Chosse video streaming quality 

### ISSUE THREAD

**Issue by trimechee** [clsid2/mpc-hc#2037]
Hello, my connection is not very powerful and i whish to play only standard video quality 360p for smooth playback and not HD videos, so i go to advanced settings but i don't know what i should change to choose standard quality by default , i see YDLMaxHeight, should i put 360p or 144p to play standard quality or worst quality please ? 
Also and i see YDLvideoformat, what value should I choose to play standard quality please ?

**Comment by clsid2** [comment]
Select H264 and 480p.

**Comment by trimechee** [comment]
Wonderful !! Thank you very much for your great help :)
