### ISSUE TITLE
Migrate settings from portable to installed version

### ISSUE THREAD

**Issue by mozomoid** [clsid2/mpc-hc#2038]
Hi there,

Not an issue but a question:

In the portable version, when clicking on _"Options > Miscellaneous > Export"_, the settings are exported in an INI file instead of a REG file.

**Is there a way to import those settings in an installed version ?**

I tried to copy both _mpc-hc-settings.ini_ (exported) or _mpc-hc64.ini_ (from the portable app folder) in _%APPDATA%\MPC-HC_ but it doesn't work that way...

**Comment by clsid2** [comment]
Options > Player > Uncheck "store settings in INI file"
