### ISSUE TITLE
Issues with player wider than 1080 on 1080p monitors

### ISSUE THREAD

**Issue by Jademalo** [clsid2/mpc-hc#2039]
This is a bit of a weird one. It used to work absolutely fine, so I've no idea why it doesn't work now. I don't know when it broke either.

I have 3 1080p monitors all connected to my GPU. What I will do if I'm watching a film in 21:9 is span the MPC-HC window across all 3, and use `View->Pan & Scan->Zoom to Widescreen` if necessary.
However, I now have an issue where if the window is wider than 1080, on the right hand side any additional pixels just turn into a weird smear of what was on that edge last, or end up transparent. 
This isn't an issue to do with the monitor edge border, if I move it between the left and middle screens then it displays the first 1080 pixels fine, but any additional width isn't displayed correctly.

Any ideas why this could have broken recently, but worked fine in the past?
I'm running the latest release, Windows 11.

Thanks

**Comment by clsid2** [comment]
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\Settings
Change "DesktopSizeBackBuffer" to 1

**Comment by Jademalo** [comment]
Awesome, that worked perfectly.
Thanks for the *incredibly* quick response!
