### ISSUE TITLE
"Exit fullscreen at end of playback" option not respected when the "After Playback" option is set to "Play next file in the folder"

### ISSUE THREAD

**Issue by sr1canskhsia** [clsid2/mpc-hc#2040]
Steps to reproduce:
1. Install a fresh copy of MPC-HC 2.0.0
2. In the options page, set "After Playback" to "Play next file in the folder" and uncheck "Exit fullscreen at end of playback"
3. Play the last video in any folder and press Alt+Enter to enter fullscreen
4. When the video ends, MPC-HC still exits fullscreen

Is this the intended behaviour or is it actually a bug? Thanks in advance

**Comment by clsid2** [comment]
Intended.

Before you even ask. There will not be any new options for this.
