### ISSUE TITLE
YDL Twitch 720p VideoFormat=0 (automatic) isn't grabbing a 720p stream

### ISSUE THREAD

**Issue by Yoksven** [clsid2/mpc-hc#2041]
When loading a twitch stream/vod though yt-dlp with YDLMaxHeight=720 and YDLVideoFormat=0, it grabs 1080p stream instead, even though 720p is available with YDLVideoFormat=8.

**Comment by clsid2** [comment]
Give the link of the stream where this happens.

I suspect you are using an old version. Update to version 2.0.0.

**Comment by Yoksven** [comment]
I am on 2.0.0, and after some more testing, maybe it was a yt-dlp problem, because I had to use the daily version of yt-dlp because of a Youtube bug, and I guess the daily one had a regression on the Twitch side of things. I now got the latest main release of yt-dlp and it seems to be working as expected. Although I do get "NoneType" error every once in a while, but retrying the same link eventually produce a working stream/vod.
