### ISSUE TITLE
Stuttering using Enhanced Video Renderer (custom presenter) every few seconds on OLED TV

### ISSUE THREAD

**Issue by CorpusBava** [clsid2/mpc-hc#2042]
I've been using MPC-HC for many years (thank you, btw!) and noticed recently using it with my LG C2 65" TV on a windows-based HTPC that it stutters every few seconds playing a 60FPS video (no matter what resolution).  When I change to the standard Enhanced Video Renderer or MadVR the issue goes away.  Since I much prefer the default renderer for its OSD renderer statistics feature and minimal GPU utilization (MadVR runs hot on my video card otherwise I'd use it as my preferred renderer) I'd like to find out what causes it and if there's a fix or setting.  It happens with all recent builds of MPC-HC  but I can;t recall it occurring with my old TVs and monitors just on the OLED.

Edited:  Just discovered that enabling vsync seems to have fixed it.  Might have something to do with the OLED TV's different adaptive vsync (g-sync) and VRR modes so enabling vsync within MPC-HC might be the solution.

**Comment by clsid2** [comment]
Video playback requires a constant refresh rate. So either enable VSync in renderer or in graphics driver settings.
