### ISSUE TITLE
Support Nvidia Video Super Resolution?

### ISSUE THREAD

**Issue by lietu** [clsid2/mpc-hc#2046]
Nvidia just released the Video Super Resolution -feature for use in at least Chrome and Edge. Any idea if the APIs are open enough that it would be possible to integrate this functionality to MPC-HC as well?

https://blogs.nvidia.com/blog/2023/02/28/rtx-video-super-resolution/

**Comment by clsid2** [comment]
The internal renderers use D3D9.

It might get added to MPCVR which you can use with MPC-HC.
https://github.com/Aleksoid1978/VideoRenderer/issues/77
