### ISSUE TITLE
"Move to Recycle Bin" option automatically removes item from playlist

### ISSUE THREAD

**Issue by opusforlife2** [clsid2/mpc-hc#2049]
If you Right Click on a playlist item and select "Move to Recycle Bin", this action immediately removes the item from the playlist, even before the dialogue shows up.

Could the playlist item removal action be done only after the user confirms the Recycle Bin dialogue? This way, if the user ultimately decides not to delete the item, it will stay in the playlist.

**Comment by clsid2** [comment]
Fixed

**Comment by opusforlife2** [comment]
Hi. Could I implore you to release a new version so I can make use of this great feature?
