### ISSUE TITLE
Donation - Wallet & Pay

### ISSUE THREAD

**Issue by Canzerastor** [clsid2/mpc-hc#2050]
Hi clsid2.

First of all you have my high respect for still coding this great project with all the time you have next to your job. I have full sympathy with your actions to close down stupid issues of people who don't know anything or little of coding and the related effort.

Second I apologize for creating an issue which isn't really one.
I can't really code myself, but I'd like to contribute my efforts to this project and your work. Since I'm new to BTC and all other digital currencies, I only have two questions regarding issue #383:

1. If you already changed your address, will my transaction be cancelled or get on an account of an unknown person?

2. Did you receive the money on your wallet "bc1qsctkttngdty2jzj970tweu2f4trsmfm6k3pqad" or can you reply when you got it?
I created an account at MoonPay and did all the instructions. Since I'm new, I didn't want to get overboard or get any issues from my bank, so I only sent a small amount to that wallet address. I sent it on that address about 1:30 PM UTC+1 and Moonpay tells me it was sent on 1:57 PM UTC+1.

Thank you for your help and understanding.
Best regards

**Comment by clsid2** [comment]
Thank you.
