### ISSUE TITLE
Default subtitles download path?

### ISSUE THREAD

**Issue by mpek** [clsid2/mpc-hc#2051]
Trying internal subtitle downloader for the first time and cannot seem to find where downloaded subtitles are being put into. 
Could someone please direct this guy to the right path? 

A suggestion with this question releases writer's brain to write: 
Why are the downloaded subtitles not being put in the same folder with the video file? Or at least an option to do so would be nice. Thank you for considering.

**Comment by clsid2** [comment]
They are put in the same folder when you enable the option to save them. With that option disabled they are loaded in memory and not stored.

**Comment by mpek** [comment]
Where is that option to save them?

**Comment by clsid2** [comment]
Options > Subtitles > Misc (bottom of page)

**Comment by mpek** [comment]
If you mean "Automatically save downloaded subtitles to the first autoload path folder" 

1. that was already marked prior asking
2. Then turned it off, to test it
3. now turned it on again
4. but no subtitle being saved in the same folder with video file
5. The videos to test it are being loaded from external USB HDD

I'd be happy if it worked as intended but it doesn't. Perhaps that system is doing something to not work it?
It's Windows 11 Home with german language. Please have a look at the settings: 

https://i.imgur.com/zqjoerM.png

**Comment by clsid2** [comment]
Subtitles are saved when closing the file.

**Comment by mpek** [comment]
Okay, did not consider that! Thanks for quick response. 
Another is, when selcted more than one subtitle to download, only one subtitle is being saved. 
Is there a setting to check to be able save all downloaded subtitles?

**Comment by mpek** [comment]
Do you know if there is an error, because only one subtitle is being downloaded but more than one is selected?

**Comment by clsid2** [comment]
Downloading multiple works fine here. It only saves the subtitle that is active when closing. That is intentional.

**Comment by mpek** [comment]
Okay, thank you for clarification. Why is it intentional?

**Comment by clsid2** [comment]
Because it makes no sense to save ones that are not active.

I am not make any changes at all to any of this behavior.

**Comment by mpek** [comment]
I understand, it makes a lot of work i guess. 
Another thought is, if it does not make even sense, when you want to watch that movie later, for instance only with forced and another time with regular subtitles or when moving it to a different system (without internet, like your private collection of best movies) to have all subtitles you want available?
I know there are solutions, but I like how this works with MPC-HC. Thanks anyway.
