### ISSUE TITLE
Please add persistent global playback speed setting

### ISSUE THREAD

**Issue by asho23** [clsid2/mpc-hc#2053]
This is the only feature missing for me. Pretty please

**Comment by asho23** [comment]
And also finer grain speed selections, or just ability to type in desired speed

**Comment by clsid2** [comment]
This already exists!
Look in the options and in the menu.

**Comment by asho23** [comment]
I've looked so much but can't find it. Using latest stable and beta builds. Please advise

**Comment by clsid2** [comment]
Options > playback > speed step

Menu > Play > Playback rate

**Comment by clsid2** [comment]
A persistent setting that applies every time does not exist. It will also **NOT** be added.
