### ISSUE TITLE
Disable Cover Art for Audio

### ISSUE THREAD

**Issue by redsigma** [clsid2/mpc-hc#2057]
I want to only keep the playlist section into view and disable the covert art for songs.

Currently the best I can do is manually resizing it until it's no longer seen, but this causes the playlist to no longer resize if i try to resize the player.

My goal is to replicate the visuals of VLC as much as possible because I am more familiar with it.

**Comment by clsid2** [comment]
Options > Advanced > CoverartSizeLimit = 0

**Comment by redsigma** [comment]
That does not disable it. It only resizes it to 0. If I fullscreen the player the cover art shows again. And it also shows again if I manually resize the player.

**Comment by clsid2** [comment]
Options > Player > Enable covert-art support

**Comment by redsigma** [comment]
Thanks that worked but now it seems the logo is still showing and if i try to resize the player, it resizes the logo instead.

![image](https://user-images.githubusercontent.com/20425476/223155405-58247f84-aca7-4847-9fd7-d041ef568a37.png)

**Comment by clsid2** [comment]
Options > Player > Logo > select empty one

Instead of resizing the player, you can drag the playlist outside of player and resize just the playlist. Drag the left edge below the X.
