### ISSUE TITLE
Change audio delay doesn't work

### ISSUE THREAD

**Issue by Eincrou** [clsid2/mpc-hc#2058]
Normally, the functions "Audio Delay +10 ms" and "Audio Delay -10 ms" are accessed by using hotkeys.  By default they're bound to the "Add" and "Sub" keys.  A message appears on screen when audio delay has been successfully adjusted.

Now when trying to adjust the audio delay on a video that was slightly out of sync, nothing happens when pressing either hotkey.  The audio/video sync doesn't change and there's no message on screen.

I was using v2.0.0.5 when I noticed it this morning.  I updated K-Lite to 17.4.5 to see if a more recent version MPC-HC 2.0.0.19 still had this issue, and it does.  It's probably been a while since I tried using this audio delay function, so I don't know which version it stopped working.

Changing the functions to use different keys didn't work.  Changing the video and audio output renderers didn't work.  The subtitle delay function works similar to the audio delay function and I'm able to change the delay on subtitles.

That brings me to the second issue I encountered this morning, but I'll post that separately.

**Comment by clsid2** [comment]
Working fine here.

It needs the internal audio switcher to be enabled.

**Comment by Eincrou** [comment]
Yeah, somehow that was disabled.  Most likely, I was trying to troubleshoot something else a while ago and I forgot to reenable it.

Its connection to changing the audio delay one of those situations where one thing is dependent upon another, but there's no way for the user to know that.  I'm reluctant to even try 80% of the options in MPC for fear of situations like this.

Enabling the internal audio switcher has made change audio delay work again,  This issue issue has been resolved and the ticket can now be closed.  Thanks.
