### ISSUE TITLE
Load Subtitles function doesn't work

### ISSUE THREAD

**Issue by Eincrou** [clsid2/mpc-hc#2059]
While writing report  #2058 on a problem using the audio delay functions, I noticed another issue.

I just updated K-Lite to get MPC-HC 2.0.0.19 and it won't allow me to use the load subtitles function (default hotkey is CTRL+L).  I used that function just last night with 2.0.0.5 to load external subtitles.

![image](https://user-images.githubusercontent.com/8196586/223486794-0eb60f05-c25e-4227-9156-3b7100fb6909.png)
`To load subtitles you have to change the video renderer type and reopen the file.  DirectShow: EVR (Custom Presenter), Sync, VMR-9 (renderless), madVR. MPC VR or Haali VR`

I tried all of them except Haali, and it's the same error for every video renderer when trying to use Load Subtitles.

However, loading subtitles by dragging and dropping a subtitles file onto the MPC-HC window works.  Video files with embedded subtitles work, too.  Subtitles display properly when loaded with these methods.  The problem seems to be just with the function, "File > Subtitles > Load Subtitles..."

**Comment by clsid2** [comment]
Already fixed

**Comment by Eincrou** [comment]
Already fixed, eh?  Good stuff.  Thanks.

**Comment by Eincrou** [comment]
I've tried MPC-HC 2.0.0.21 and confirmed that load subtitles function works again.  The issue has been fully resolved and this ticket can now be closed.
