### ISSUE TITLE
Playlist doesn't play next video if there is other active wasapi exclusive player 

### ISSUE THREAD

**Issue by vritme** [clsid2/mpc-hc#2060]
1. Foobar2000 is playing in wasapi exclusive mode.

2. In MPC I can play any video in playlist while using SaneAR in exclusive mode, conflict of audio devices is silently ignored.

3. However, MPC doesn't start next video in playlist automatically, probably because of the conflict of audio devices. 

To enable autoplay-next-video-in-playlist while using other wasapi exclusive audio player, I need to choose Null audio renderer. 
Then there is no conflict of wasapi audio devices, and video playlist playback go smoothly.

Wouldn't it be more gracefully, if MPC in playlist playback will silently ignore audio device conflict for continuous videos, as it already does for a single video, hence allowing to play whole playlist even with other wasapi exclusive audio player running whilst staying on SaneAR exclusive audio renderer in MPC (not forcing user to choose Null audio renderer, and then back...)?

**Comment by clsid2** [comment]
If you want to use multiple players at same time then you should disable exclusive mode.

**Comment by vritme** [comment]
Ok, thx, that works, 1 tick box instead of changing audio renderer, a lot easier.

Anyway, for a single video manually selected in video playlist or just for directly played videofile conflict of devices seems to be handled ok, MPC is only confused when it needs to start video "itself" in playlist queue.
I've just thought it would be more consistent if it will be able to manage this conflict in playlist mode also, just playing next video with other player using audio device in exclusive mode.

If it doesn't disrupt much of the whole order of things, of course).

**Comment by clsid2** [comment]
The second file in a playlist is handled no different than a first one. So if behavior is different its cause may be outside of player code.

But anyway, you are using exclusive mode wrong. It also isn't some magical option that improves your audio quality.
