### ISSUE TITLE
Saving chosen audio/subtitle track index per file

### ISSUE THREAD

**Issue by SergeVDev** [clsid2/mpc-hc#2063]
A minor improvement would be cool: saving somewhere, what audio/subtitle tracks were chosen for the file, and select them automatically the next time this file is being open. Right now I have to select them every time I start the program.

MPC-HC (Nightly, 64-bit)
------------------------

Build information:
    Version:            2.0.0.16 (1a1bbdf30)
    Compiler:           MSVC v19.29.30147
    Build date:         Feb 16 2023

**Comment by clsid2** [comment]
Duplicate.
