### ISSUE TITLE
Saving 'Show current position time and total duration' flag globally

### ISSUE THREAD

**Issue by SergeVDev** [clsid2/mpc-hc#2064]
>Get a watch/clock/phone.

_Originally posted by @clsid2 in https://github.com/clsid2/mpc-hc/issues/2062#issuecomment-1460176935_

Hi, this feature shows current position / total duration, not the current time. Getting a phone doesn't help :)

![mpc-hc64_FnFQu90w77](https://user-images.githubusercontent.com/105910814/223847844-f8ee572b-b84a-4d90-bccc-7709f519bd37.png)

It's already implemented and works like a charm. The only problem is that it's always off when one runs the player, even if it was on during the previous session.

**Comment by clsid2** [comment]
I am not adding new options.

I have got a million things to do already and very little time and motivation.
