### ISSUE TITLE
Last window type not remembered when using "Launch files in fullscreen" option

### ISSUE THREAD

**Issue by Eddie370** [clsid2/mpc-hc#2065]
When exiting fullscreen after using the "Launch files in fullscreen" option, you have to maximize the window to see the seekbar and controls. When the "Launch files in fullscreen" option is disabled and you manually enter fullscreen, it correctly remembers the window type after exiting fullscreen.

**Comment by clsid2** [comment]
It works normally for me. Try resetting the settings. Or enable auto-zoom if you disabled that.

**Comment by Eddie370** [comment]
Resetting settings doesn't fix it, auto zoom is enabled. I also enable "Remember last window position" and "Remember last window size". The issue doesn't occur in MPC-BE.

**Comment by clsid2** [comment]
Is fullscreen on different monitor? Monitors with different resolutions?

How exactly does the window look when problem occurs? Are seekbar/controls outside of visible area?

**Comment by Eddie370** [comment]
It's just a single 3840x2160 monitor playing a 1080p video. When exiting fullscreen it will fill almost the whole screen but with a small gap on all sides, the seek bar will be hidden by the taskbar. If I hide the taskbar then I can see the seek bar at the bottom.

**Comment by clsid2** [comment]
I am unable to reproduce it.

**Comment by Eddie370** [comment]
In MPC-BE's configuration file there is a setting that reads "LastWindowType=0" when it is not maximized like in MPC-HC. When it is maximized the setting reads "LastWindowType=2". MPC-HC has the exact same setting when storing settings in an ini file, but it appears to not be reading it correctly when launching in fullscreen. Maybe you could check their launch in fullscreen code and see how they are handling it differently?

**Comment by clsid2** [comment]
Maximized window and fullscreen are two different things.

I see issue when going from maximize to normal.

**Comment by clsid2** [comment]
Try 2.0.0.25 development build

**Comment by Eddie370** [comment]
Still the same problem in the development build.

**Comment by adipose** [comment]
@Eddie370 , can you upload your settings?

I am unable to reproduce.  I tried:

1. Maximize window
2. Check "launch in fullscreen"
3. Close MPC-HC
4. Launch video file to fullscreen
5. Exit fullscreen

When I exit fullscreen, it doesn't go back to maximized.  Instead it goes to a regular size window (zoomed to 100% video size).  All controls are visible.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2120

This patch does affect that field so it may help.
