### ISSUE TITLE
Opening an external srt sub "over" a PGS sub results in wrong AR of the SRT.

### ISSUE THREAD

**Issue by Max33Verstappen** [clsid2/mpc-hc#2067]
While having a PGS sub displayed and then dragging and dropping or opening an external SRT sub ("Ctrl + L"), the SRT sub seems to have the wrong AR (maybe inherits the AR of the current viewport) until reloading the SRT sub or changing the viewport of the video.

Wrong AR:
![2023-03-11_01 20 46 686_mpc-hc64_Nope 2022 BluRay 1080p x264 TrueHD7 1-HDChina mkv](https://user-images.githubusercontent.com/97274607/224381684-4e4fdae3-a538-4eaa-8cb6-b48f57076510.jpg)
After reloading the sub or changing viewport:
![2023-03-11_01 14 36 684_mpc-hc64_Nope 2022 BluRay 1080p x264 TrueHD7 1-HDChina mkv](https://user-images.githubusercontent.com/97274607/224381866-f3e831b0-b757-40d7-a154-02580679be1b.jpg)

**Comment by clsid2** [comment]
Are you using latest version?

I need link to a video. The ones I have all work fine.

**Comment by Max33Verstappen** [comment]
I'm using 2.0.0.25
Here's the video https://disk.yandex.com/d/mlbmND0lkHDjrg
After opening the video please select the English PGS embedded, and then drag and drop or load the "test Srt Over PGS.srt". SRTs **already loaded** are **not** affected.
This problem may be somewhat related to #1885, but that problem also affects **already loaded** SRTs.

BTW, in previous example I have "Subtitle -> Default Style -> Position subtitles relative to the video frame" half-checked or unchecked, and if it's **checked**, the subtitle position of newly loaded SRT is:
![2023-03-11_15 38 44 184_mpc-hc64_Srt_Over_PGS mkv](https://user-images.githubusercontent.com/97274607/224472280-dd3efacd-f069-4776-b779-a5e6b2246cf4.jpg)

**Comment by clsid2** [comment]
Which video renderer are you using? If you use madvr you must disable its option to move subtitles.

It is working properly here, so you must be using some other non-default settings. The AR of your screenshots is different than the video itself?

**Comment by Max33Verstappen** [comment]
I made the screenshot in windowed mode, but my MPC-HC window's AR is higher than the actual video (thus there're black bars on the left and right side).

I found the non-default setting that causes the problem -- "Subtitle -> Sub picture to buffer" set to non-zero.
So dunno if it's a problem.

**Comment by clsid2** [comment]
I can reproduce now.

**Comment by clsid2** [comment]
Try this test build:
https://www.sendspace.com/file/e140nd

**Comment by Max33Verstappen** [comment]
Working well!
Thanks.
