### ISSUE TITLE
Latest version plays back dark

### ISSUE THREAD

**Issue by vmoutsop** [clsid2/mpc-hc#2068]
After install of new version, all videos play dark and there is no apparent way to change the brightness settings.  MP4 & MKV files.

![MPC-HC Dark](https://user-images.githubusercontent.com/63555918/224421407-e90ca22a-1c84-47b1-8b0f-ff17fa449f36.jpg)

**Comment by clsid2** [comment]
Not fault of the player. Either bug in the graphics driver, or wrong color settings in the driver.

**Comment by vmoutsop** [comment]
Thank you. At least someone responded. You are correct. Didn’t even think of that.  I should have known
