### ISSUE TITLE
Hardware acceleration does not work when decoding

### ISSUE THREAD

**Issue by Meivyn** [clsid2/mpc-hc#2069]
I noticed it on this very high-resolution video, but it happens on lower resolutions: https://www.reddit.com/r/IntelArc/comments/ys6256/comment/ivycwtd/?utm_source=share&utm_medium=web2x&context=3

Confirmed the issue by looking at the task manager. Graphics shows simply nothing. The video and sound are also both choppy.
I was able to get it working with MPC-BE and the native Windows player. A quick comparison (graphics shown are from native player):
![image](https://user-images.githubusercontent.com/793322/224477394-2343712c-6f3a-4bf2-a6c3-372414240083.png)

I also have an Intel Arc A380, and neither actually makes use of the hardware acceleration... However, it is my second GPU so I am not sure if I actually have to do anything special to benefit from it... Other than installing the latest drivers.
In case, link to the corresponding AV1 encodes: https://www.reddit.com/r/IntelArc/comments/ysul5h/av1_handbrake_nightly_testing_8k60_to_1080p60/

Here are some details about my setup:

Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz 
64.0 Gb RAM
GeForce RTX 2060 Super
Intel Arc A380
Windows 11 22H2

**Comment by clsid2** [comment]
In the internal video decoder settings, select D3D11 hardware decoder. If Intel does not work with DXVA2 it is fault/limitation of driver.

**Comment by Meivyn** [comment]
Selecting D3D11 or anything else on this list doesn't fix the issue. Also do note that my main video card is the RTX, not the Intel.

**Comment by clsid2** [comment]
The player shows "H/W" in its status bar when hardware decoding is active.

If it doesn't use hardware acceleration then it means your hardware does not support the video format (or resolution). The RTX 2060 does not support AV1.

**Comment by Meivyn** [comment]
I mean, my hardware *do* support the video format since it is able to make use of hardware acceleration with other players, and it was with HEVC (format of the first video I linked) and the native Windows player or MPC-BE (which makes use of D3D11 by default, so I already tried to see if using the same settings would help, but seems like not) or VLC. Only MPC-HC didn't work with it.

There's nothing that works when decoding AV1, but the Intel card should support decoding it, hence why I wonder why it doesn't do a thing. I know my RTX doesn't support it.

**Comment by clsid2** [comment]
By default main GPU gets used. If you want to use the Intel GPU you must select that in the video decoder settings.

The player works correctly, so any problem you have is because of wrong configuration by yourself.

Using a non-primary GPU for decoding means the decoded video must be copied back into main system memory and then again to the primary GPU. With 8K video that is a GIGANTIC amount of data and that will COMPLETELY destroy performance.

**Comment by Meivyn** [comment]
Wrong configuration? I use default configuration. I only changed what you asked me to and that's it. 

I also recall having tried to select the Intel GPU in the settings for AV1 but I'll try again. But resolution here doesn't matter, since it doesn't decode anything else I record in 1440p, but thanks for the info. I'll assume it isn't going to work regardless with the 8K one.

HEVC though definitely doesn't work at all as it should with my RTX. And I am not alone with this issue (see https://www.reddit.com/r/IntelArc/comments/ys6256/comment/ivz7xc8). CPU is always used for HEVC videos.

**Comment by Meivyn** [comment]
Can confirm that changing the video decoder to `D3D11cb` does work to decode AV1 videos in MPC-BE. MPC-HC doesn't have that option, but selecting `D3D11` in the list and then the intel GPU doesn't change a thing.

**Comment by clsid2** [comment]
D3D11 + selecting device = D3D11 copyback (cb)

And AV1 checkbox must be enabled.

**Comment by Meivyn** [comment]
Yeah, this is what I did. For some reason, HW acceleration simply doesn't want to work in MPC-HC. Gonna delete the config from AppData and see if it changes anything...

**Comment by clsid2** [comment]
Options > Miscellaneous > Reset

**Comment by Meivyn** [comment]
Actually, it seems that this is saved in Registry... Might have used some settings from an old installation. After resetting, it works fine. Thank you for your help and sorry for the false report.
