### ISSUE TITLE
"Folder in use" after opening a file

### ISSUE THREAD

**Issue by vanlokja** [clsid2/mpc-hc#2070]
When i open a file in MPC-HC 2.0.0 and then close the program, i can't move the folder the file is in ("file in use" error in explorer).
But i can move the file and after that i can move the folder.
It's weird, but i have seen this behavior on 2 computers (bot Windows 10) and only with HPC-HC.

Thanks for looking in to it.
It's wonderful media player!

**Comment by clsid2** [comment]
Not fault of the player.

You can use Process Explorer to find which process is holding a reference to the file.
https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer

**Comment by vanlokja** [comment]
Process Explorer points to flow.exe
So it is not the player. Weird, never had this problem.

**Comment by clsid2** [comment]
flow.exe seems to be part of Conexant SmartAudio driver.

I have no idea why that is accessing the video file. You would have to ask them for help.

**Comment by clsid2** [comment]
You can remove the unneeded Flow thing.

Run this command from an administrator command prompt:
`C:\Program Files\Conexant\Flow\Setup64.exe -U -IFlowSetup`

https://h30434.www3.hp.com/t5/Notebook-Audio/Flow-exe-spikes-to-20-CPU-and-causes-sporadic-windows-freeze/td-p/6483020

**Comment by vanlokja** [comment]
thanks!
