### ISSUE TITLE
Video stuttering with new Nvidia card

### ISSUE THREAD

**Issue by Robert3750** [clsid2/mpc-hc#2071]
I recently upgraded my video card from an Nvidia 1050 Ti to an Nvidia RT 3060.  I made no changes to MPC  H64.   I played a 24p 4k video, and it now has noticeable stuttering, which didn't happen with the previous card.  I played the same video on Kodi, and it had no problems, which tells me there's something not right in MPC H 64.  Can you help me?

**Comment by clsid2** [comment]
If you are using EVR-CP as renderer:
Menu > View > Renderer Settings > VSync > enable VSync

If you are using MadVR:
Set frames to present in advance to 1 in madvr settings.
