### ISSUE TITLE
[OSD] Matrix and Primaries bug - swapped places

### ISSUE THREAD

**Issue by radpopl** [clsid2/mpc-hc#2072]
In the OSD, the Matrix Coef and Color Primaries fields are swapped. It should be otherwise.

![image](https://user-images.githubusercontent.com/11005341/224827736-5872c9e8-832b-48e2-9b06-39ca8c6b58a7.png)

**Comment by clsid2** [comment]
That is an external renderer.

**Comment by radpopl** [comment]
Oh sorry, got the addresses wrong :)
