### ISSUE TITLE
Feature Request: Color Seekbar

### ISSUE THREAD

**Issue by mkruer** [clsid2/mpc-hc#2073]
Feature Request: On both the Modern and Classic Seekbar can you add an option to specify a color? This is to help up the contrast when viewing the progress the video at a distance. The default light grey (classic) and blue (modern dark) are very difficult to see when viewing at a distance and using a 4K display.

_Originally posted by @mkruer in https://github.com/clsid2/mpc-hc/issues/862#issuecomment-1469248300_

**Comment by clsid2** [comment]
Next version has a modern light theme with green seekbar.

You can customize seekbar height in the options.
