### ISSUE TITLE
Moving the player window

### ISSUE THREAD

**Issue by Spuner** [clsid2/mpc-hc#2075]
Since version 1.9.23, the mouse behaves strangely when you try to move the player window. It has to overcome more distance than before... I don't know what this is about, but it's very annoying. To fully understand the problem, here's a [**video**](https://mega.nz/file/ostA0IzC#S0dAMY-VokGyun2ovj_5T9Gj7JVcB8JeQOhJ6s1lPLA).

**Comment by clsid2** [comment]
This is intentional to prevent accidental moves when clicking.

It will not be reverted. There will not be any options for it.

Drag the window title bar instead.
