### ISSUE TITLE
Skins for MPC-HC where the controls scroll to next video frame?

### ISSUE THREAD

**Issue by peytontodd** [clsid2/mpc-hc#2081]
My users will need the multiple brief videos that they view (about 4 sec each) to pause on the last frame instead of closing or going to a logo. So far I've found only two players that do this: Quicktime and MPC-HC. But Quicktime for the PC has a security hole what leads it to be locked down on the internet, and one is scared to use it off line. So that leaves MPC-HC. But my users also need to ability to scroll through one video frame at a time (the videos are sign language sentences that need to be studied carefully).

MPC-HC has this ability but a user has to know what combination of controls will work, and it's not intuitive to use. Are there any skins for MPC-HC where the left-and right arrows have simply advance or recede a single frame at a time? (The default definition of those controls looks for each next video on the hard drive, which my users will have no interest in or use for!)

**Comment by clsid2** [comment]
You can framestep with Ctrl+Left/Right on keyboard.

Is is not possible to change what buttons do. Nor will there be any such options in near future, and maybe never at all.

**Comment by peytontodd** [comment]
Yes, the Ctrl+Left/Right key combination was just what I regard as not intuitive since it requires the special knowledge of what to do, and also requires remembering to do it each time since one's natural inclination will always be just to press the arrow keys and expect the usual response. 
Another commentator, responding to my post of this same problem to a different thread (which is now locked down so I cannot respond to him directly) says that one can change what the buttons do in Options. Indeed there is a section in Options where all manner of keys can APPARENTLY  be given different definitions but I see no way to do that. The Left and Right Arrows are already assigned to "medium" jumps (jumps too great for my purpose), and all my attempts to change them have failed. The technique is simply to type the character combination one wants,, but it won't let me reassign left and right arrows.

**Comment by ghost** [comment]
In that case you should first delete the assignments for 'medium jumps' with administrative rights and then you should be able to reassign the left and right arrows for framestepping.

**Comment by peytontodd** [comment]
THANKS! It seemed not to work at first, but I found that if I select the keystroke name, wipe it out, then enter (by simply keying) a substitute that HPC-HC didn't complain about - which turned out to be Shift+[ and Shift + ] - then it let me use simple Left Arrow and Right Arrow for movements of just one frame at a time!
