### ISSUE TITLE
v2.0 crashes on change of resolution , plugging/unplugging HDMI cable

### ISSUE THREAD

**Issue by mike000000000001** [clsid2/mpc-hc#2083]
It just freezes, with the video slightly garbled but is crashed. must end manually via task manager. This occurs when the HDMI cable is unplugged, using output to TV/display only (not the lcd of the laptop) and is then unplugged. The resolution of the TV is different than resolution of the LCD display (lower). Using defautl settings from install, evr, reinitialize when changing display is checked. Also, don't know if it matters but the movie is x265, mkv and running off a usb plugged in drive.

**Comment by clsid2** [comment]
I don't have a laptop with HDMI port, so I can not test or fix this.
