### ISSUE TITLE
Have the Mark A-B feature not automatically removed when going out of the selected marked range.

### ISSUE THREAD

**Issue by Xiarno** [clsid2/mpc-hc#2085]
The Mark A-B feature is one that I use pretty commonly for lots of different things. However, one thing that makes it problematic in many places is when going outside of the marked range, the marker gets immediately removed, which forces me to put them up again. This happens very commonly, especially when I'm not at the end of the marked range yet and I want to go back to the start, so I go backyard but overshoot, and thus the marker disappears.

I can think of an easy solution to this.
If a range is marked, when going outside of the range and playing the file, it "teleports" the playhead to the beginning (A) marker.

Also, when pressing the keyboard shortcut "[" and "]", if the marker is not at the playhead, it should instead move the marker instead of removing both markers. So if you want to remove the marked range altogether, you would need to press twice. Some sort of confirmation basically.

**Comment by clsid2** [comment]
You can press HOME button to jump to A mark.

To change mark press the shortcut twice. Once to remove mark, then again to set at new point.
