### ISSUE TITLE
Rename/delete file while open

### ISSUE THREAD

**Issue by gbdematos** [clsid2/mpc-hc#2086]
Is it possible to rename or delete a file from Windows Explorer while the file is still open?

You can do this with the default Windows video player (and afterward in the player, it shows an error that the file could not be found anymore, which is normal).

However, with MPC-HC, it says the file is in use and cannot be renamed/deleted without closing the file first.

So, is it possible to tweak any settings to be able to do this?

Thanks

**Comment by clsid2** [comment]
You can not delete a file that is being accessed. You can delete the currently playing file in MPC-HC by pressing Del button. It will automatically stop playback first.

**Comment by bucketcat** [comment]
If you mean that you can not delete a file at all while it's being used, then that is wrong. ImageGlass allows this specifically for images makes reviewing and cleaning galleries very efficient. And playing a video, and deleting it as it's playing works just fine on windows. Well, at least moving it to the bin which is technically just a dummy folder on the some drive, but it still marks it for deletion.

You should be able to move it to the bin on windows while it's playing. Doesn't stop playing when doing it through explorer.
