### ISSUE TITLE
MPC-HC Crash

### ISSUE THREAD

**Issue by CardboardFreedom** [clsid2/mpc-hc#2089]
This is an issue I had with the original MPC-HC and it seems to have evolved in this version.

When I screen share MPC-HC through Discord, I get an "ACCESS VIOLATION" whenever I resize it or it's in full screen.

I can begin the screen share at any size, it specifically crashes when resized. It also will crash when its in full screen mode, whether it was already in full screen mode or not when I begin the screen share.

The specific memory address for the access violation always changes, but was 0x0 (AKA NULL) the first time the error happened.

Codebase: 0x7FF659670000

The crashing module always changes, here's a list:

ffdshow.ax
SYSTEM32\ntdll.dll
System32\Driver\....(several more directories)...\nvd3dumx.dll

ntdll.dll showed up twice, the others once. Usually, the crash will give no error, sometimes it'll give two error messages, each being an access violation.

If it may help:

When I suffered this issue with the original (non-github version) of MPC-HC, it was about a 50/50 chance whether or not it would crash when setting the video player to full screen while being screen shared.

**Comment by clsid2** [comment]
https://github.com/clsid2/mpc-hc/issues?q=is%3Aissue+is%3Aclosed+discord
