### ISSUE TITLE
How to report files that fail to render?

### ISSUE THREAD

**Issue by dandrei** [clsid2/mpc-hc#2090]
What's the best way to report files that fail to render on MPC-HC clsid2? Especially in cases where for reasons of privacy or for other legal reasons, the videos can't be referenced on Github.

**Comment by clsid2** [comment]
You can email links to [clsid2@users.sourceforge.net](mailto:clsid2@users.sourceforge.net)

If it is a common file format such as mkv or mp4 that fails, then there is a very high change that you got a fake or broken file.
