### ISSUE TITLE
Subtitles streaming via yt-dlp.exe stopped working

### ISSUE THREAD

**Issue by vritme** [clsid2/mpc-hc#2091]
Couple days ago it worked just fine.
Now youtube video is working, but subs are not.
Subs setting is enabled, use auto subs is enabled, video contains respectable subs.
Subs are downloadable via yt-dlp.exe as a file.
Video for check, subs language used in mpc "en": https://www.youtube.com/watch?v=ukKwVsjQqUQ

Yt-dlp.exe version 2023.3.4 (latest), MPC-HC version 2.0.0 (latest).

**Comment by clsid2** [comment]
Working fine here.
