### ISSUE TITLE
MKV Default tag and Default track preference is ignored. Track order is used

### ISSUE THREAD

**Issue by PrSinister** [clsid2/mpc-hc#2093]
When playing an MKV file with multiple audio tracks and/or multiple subtitle tracks, the Default tag is being ignored and the 1st track is selected.

Also, the Default track preference in the playback settings is not working

![image](https://user-images.githubusercontent.com/247870/231799990-6b2ad52d-2bff-4218-a110-18840dcc963d.png)

![image](https://user-images.githubusercontent.com/247870/231800314-976fd67f-125c-46be-9c7d-8060508cb9cb.png)

![image](https://user-images.githubusercontent.com/247870/231800510-40e110f8-6e2f-4c81-b355-3c374527c375.png)

**Comment by clsid2** [comment]
You can configure it in the internal splitter settings.
