### ISSUE TITLE
Limited colour range instead of Full while playback (colour washed-out).

### ISSUE THREAD

**Issue by KulakovAD** [clsid2/mpc-hc#2095]
[Version](https://github.com/clsid2/mpc-hc/files/11234758/version.txt) : 2.0.0.30

[Output settings](https://user-images.githubusercontent.com/53341050/232095085-32d5c70f-7f21-4bac-b630-959427c507bc.PNG)

[Decoder settings](https://user-images.githubusercontent.com/53341050/232095012-f83661f5-289c-4580-bd02-899a80bae88e.PNG)

Full range [video](https://user-images.githubusercontent.com/53341050/232095149-c4368414-61f1-44ab-b913-89d9b6a92373.mp4)

[mediainfo.txt](https://github.com/clsid2/mpc-hc/files/11234757/mediainfo.txt) / [ffprobe.txt](https://github.com/clsid2/mpc-hc/files/11234751/ffprobe.txt):
> Color range                 : Full
> Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(**pc**, bt709, progressive)

Image from video with [Player settings](https://user-images.githubusercontent.com/53341050/232095007-2471ad79-dd9a-4f21-ba13-0e9f257e75c4.PNG) in NVIDIA Console - [PLAYER_SETTINGS](https://user-images.githubusercontent.com/53341050/232095087-3f3dae93-72db-47d8-b4ec-120171888033.png)

Image from video with [Forced full colour](https://user-images.githubusercontent.com/53341050/232095009-69978af5-e97b-4734-b004-9b2100365569.PNG) in NVIDIA Console - [FORCE_FULL_COLOUR](https://user-images.githubusercontent.com/53341050/232095018-be6be551-7cfe-41d3-935c-6ac760bcfb9e.png)

It is visible that image with PLAYER settings rendered as "Limited colour", but should be rendered as "Full colour".

**Comment by clsid2** [comment]
Give link to the video so I can test it on my computer.

This is usually a driver bug.

**Comment by KulakovAD** [comment]
Thank you for taking a look.

This video - https://user-images.githubusercontent.com/53341050/232095149-c4368414-61f1-44ab-b913-89d9b6a92373.mp4

**Comment by clsid2** [comment]
Colours are same as with madVR which suggests they are correct.

If you don't like it, override the colours, or use another player. File could also be wrongly encoded.
