### ISSUE TITLE
Subtitle Changes don't stay in place

### ISSUE THREAD

**Issue by gosndka** [clsid2/mpc-hc#2097]
Hello, I currently use mpc v2.0.0 on windows 10 pro and after changing the font size and the placement in the styles section, As soon as I enter the full screen mode it reverts back to default font size and placement. Can anyone help me out?

**Comment by clsid2** [comment]
Change it in the options, not in the styles dialog. That seems buggy right now.

**Comment by gosndka** [comment]
> Change it in the options, not in the styles dialog. That seems buggy right now.

I see, I usually change diff fonts for different shows. Hope you fix it soon.

**Comment by clsid2** [comment]
Fixed

**Comment by gosndka** [comment]
> Fixed

Thank you for the quick resolution, if I may ask when can I download the program that has the updated fixes? @clsid2

**Comment by gosndka** [comment]
Hey sorry to bother you, but when you can release the beta version with this fix? @clsid2
