### ISSUE TITLE
Remember playlist

### ISSUE THREAD

**Issue by vivadavid** [clsid2/mpc-hc#2101]
Hi,

The same way that the programme remembers the position of a media file even if, in betweeen, you played something else, it would be great if the programme could remember the track (and its position) in a playlist even if, in between, you clicked on and played a different playlist. Basically, it would be like making "Remember last playlist" into just "Remember playlist".

Here is my case scenario:

- I have a playlist with podcasts that I listen to in particular moments during the day.
- When I get tired of listening to my podcast playlist, I shut the programme and I open the playlist of an album.
- Later on, I shut the programme again and I open my podcast playlist. In its current state, the programme doesnt't resume but, instead, plays the playlist from the beginning, though it would be useful if it could jump to the last track I listened to and resume from the last position.

Thank you for considering my suggestion.

**Comment by clsid2** [comment]
It remembers if you close and re-open without playing anything else in between.

I have very little time and motivation to implement it.
