### ISSUE TITLE
Newest Release, x64 only ? and diffrent x64 Releases ?

### ISSUE THREAD

**Issue by blackcrack** [clsid2/mpc-hc#2102]
Hi,

what's going on, at the newest Release is no x86 and an more older x64 Release for it ?
https://github.com/clsid2/mpc-hc/releases

There is no x86 Architecture Build ..
imho buildsh.. \*s\*

best Blacky

**Comment by clsid2** [comment]
Development builds are x64 only. Look below it for 2.0.0 x86
