### ISSUE TITLE
[FEATURE REQUEST] Assign multiple keys to one action

### ISSUE THREAD

**Issue by yolorag** [clsid2/mpc-hc#2103]
.I'm trying to spare my arrow keys so I have reassigned fast jump forward and backwards to other keys, but sometimes I still try to use them lol.

Is there a way to do make two different, separate keys perform the same action already, or would it be possible to add this feature?
Tried googling for relevant keywords, but couldn't find anything if it is possible.

Thanks

**Comment by clsid2** [comment]
There are three jump sizes that you can use.
options > tweaks
