### ISSUE TITLE
Command MEDIA_PLAY_PAUSE

### ISSUE THREAD

**Issue by sebastian-czarnecki** [clsid2/mpc-hc#2104]
Hello.

In current version (and very probably in earliers), program command MEDIA_PLAY_PAUSE don't work if window hasn't focus. When focus is set, function work properly.

Reproduce procedure: Open MPC, start playing, unset window focus, use key with function MEDIA_PLAY_PAUSE.

**Comment by clsid2** [comment]
Options > Player > keys > global media keys

**Comment by sebastian-czarnecki** [comment]
Unfortunatelly options You sent are not available. Screens in attach:
![screenshot_2023-05-02_09-59-28](https://user-images.githubusercontent.com/84023357/235611896-993af787-4e7f-4989-afe0-79809627983a.png)
![screenshot_2023-05-02_09-59-32](https://user-images.githubusercontent.com/84023357/235611902-df084dc9-5f83-499f-bb45-c372477998bc.png)
![screenshot_2023-05-02_09-59-37](https://user-images.githubusercontent.com/84023357/235611904-9887e429-0d9f-44f9-b150-a2de0306b6de.png)

**Comment by clsid2** [comment]
Look at the bottom of the page
