### ISSUE TITLE
File association does not work on win 11

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2105]
On win 10 it was possible to associate with all known audio and video files with few clicks from `Options>Formats`.

Now on win 11 it does not work. I've to do it one by one in file explorer manually. This is super annoying.
Can you apply any kind of hack to fix it?

**Comment by clsid2** [comment]
Install MPC-HC as part of [K-Lite Codec Pack](https://www.codecguide.com). That will take care of creating file associations for you.

**Comment by ueyome** [comment]
It's an absolute nightmare for anyone who doesn't want to install K-Lite. If only file associations were as easy as they are in MPC-BE.
