### ISSUE TITLE
Add Containing Folder currently also adds subfolders

### ISSUE THREAD

**Issue by Butterfly-Dragon** [clsid2/mpc-hc#2106]
it did not use to behave like that.

Is there an option i am missing that prevents adding subfolders?

Like if i can choose between both it's good otherwise adding subfolders right now makes it impossible for me to use.

**Comment by clsid2** [comment]
Has already been fixed for future build.

**Comment by Butterfly-Dragon** [comment]
out of curiosity: how? with an option? or just removing the adding of subfolders?
