### ISSUE TITLE
Reliability going down

### ISSUE THREAD

**Issue by SanderBouwhuis** [clsid2/mpc-hc#2107]
I have been using MPC for many many years now, and it could pride itself on being rock solid. Unfortunately, the reliability has gone down significantly in the last year or so.

1. When I start a video, sometimes I hear sound but I only get a black screen. When I hover over the seek bar, the preview works correctly. I cannot fix this other than exiting MPC and restarting it (I always start MPC by double-clicking a video file in a file manager).

Suspected cause:
Initialization problem?

2a. I have turned on the feature where MPC remembers where I left off in a video. I've noticed that when a video has been stopped close to the end, going back to that video will sometimes confuse MPC. It doesn't quite crash, but the video and audio are out of sync and it keeps jumping around frantically. I need to then stop the video (pause doesn't work) and restart it to fix it. It seems to be more prevalent when either the distance to the end of the video is very short, or the total length of the video is very short (only a few second long in total).

2b. Like 2a, I noticed the same issue when you set an A-B region for looping, and you go from another video to the video we again have MPC confused. It seems to be more prevalent if the A-B region is very short.

Suspected cause:
It may have to do either with buffering or key frames?

**Comment by clsid2** [comment]
1. That is likely be a graphics driver issue. The preview does not use hardware accelerated decoding, so that is probably where the issue is.
2a. Options > Advanced > RememberPosForLongerThan = 1
That will avoid problem for very short files.
I can not do anything without a file to reproduce problem.
Stopping clears the remembered position.
2b. Need sample and timestamps. Some formats have bad seeking when points are not a keyframe.

**Comment by SanderBouwhuis** [comment]
1. Can I turn on debug logging, so that when it occurs again I can send you a debug log?

2a. My RememberPosForLongerThan was set to 0 (the default). I changed it to 1, but I highly doubt it will work. Most videos are much longer than that where this occurs. I can try to reproduce it by jumping to the next video 1 second or so before the video ends, and then jump back. But, only if I can send you a debug log.

2b. Seeing I can't easily reproduce it, this is very difficult.

Could problem 2 be caused by the fact the video is between the last key frame and the end of the video? Maybe you search for the next or prev key frame and something fails?
Or maybe you already pre-load/cache (part of) the next video in the directory, but the video starts so late that the trigger to do that doesn't happen?

PS
All of this mostly regards videos from IGN.com (a video game website). I would say 95%+ of the videos I watch are from that website. But, as I said it is seemingly random. If I try the same video again it works again until it happens with some other video.

**Comment by clsid2** [comment]
There is no debug logging for this.

Given your first problem, disable hardware decoding, and see if that maybe also solves the second issue.
