### ISSUE TITLE
GIFs play with swapped R and B channel

### ISSUE THREAD

**Issue by PPLToast** [clsid2/mpc-hc#2108]
From checking and comparing old versions this seems to be due to some change done to LAVSplitter in 1.7.16. The issue is still present as of latest 2.0.0.37 for me with any GIF file I try.

https://i.imgur.com/oYHMJo3.png

**Comment by clsid2** [comment]
Colors are fine here with GIFs.

Since you are using the old VMR9 renderer, I can also suggest to try a different video renderer in the options.

**Comment by PPLToast** [comment]
I gave EVR and madVR a try and the same thing still happens. LAV Splitter is still used as part of the pipeline regardless of the renderer picked which I think has the issue. Is there some other way to troubleshoot this? For whatever it's worth, replacing the LAVSplitter.ax with the one from 1.7.15 corrects it for me but maybe there is some deeper issue at play.

**Comment by clsid2** [comment]
Provide a GIF that has the problem.

**Comment by PPLToast** [comment]
All of them do, but I'm sure it'll work properly for you. Just a matter of figuring out what the difference in our setups is.

https://i.imgur.com/1feEEn4.gif

**Comment by clsid2** [comment]
Yes, working fine for me.

You might have an old version of LAV Filters installed, given that it is using an external LAV Video Decoder instance.

**Comment by PPLToast** [comment]
Is LAV Splitter 0.77.2.2-git not the latest?

**Comment by clsid2** [comment]
Look at the version of the video decoder.

**Comment by PPLToast** [comment]
Ahh, I see. I updated from Nevcairiel's repo to 0.77.2 and it is indeed working now. How come the decoder is being loaded externally?

**Comment by clsid2** [comment]
Because uncommon mediatypes are not explicitly defined for the internal decoder. It has low merit fallback for all supported formats.
