### ISSUE TITLE
Playback speed/rate should be in 0.1 increments (e.g. 1.1x)

### ISSUE THREAD

**Issue by simo1994** [clsid2/mpc-hc#211]
Hello,
I'd like to accelerate the playing speed in 0.1 increments, e.g. 1.1x 1.2x.
Instead, if I press CTRL+up it goes to 2x or 4x, which is excessive for me.

Is there an option I'm missing?
Thank you in advance!

**Comment by adipose** [comment]
This will do .1 increments:

![image](https://user-images.githubusercontent.com/3324395/71762828-749c0280-2e89-11ea-879c-d04cad68df49.png)

**Comment by simo1994** [comment]
Thank you very much!
