### ISSUE TITLE
Add a dialog box to easily sync subtitle

### ISSUE THREAD

**Issue by Tarek-Hasan** [clsid2/mpc-hc#2111]
Following problems occurs with existing solution to sync subtitle:
- F1 and F2 keys to sync subtitle doesn't work on laptop keyboard. 
- Subresync is hard to use than dedicated subtitle software, e.g. [Subtitle Edit](https://nikse.dk/subtitleedit). (PS. I wasn't able to use it even for a single time)
- Last one exist deep in option (Option > Subtitle > Delay Step). Subtitle sync doesn't require in every video and certainly not require same value, so having this in option is just unnecessary complication.

Please, add option to delay/advance (increase/decrease) subtitle with few clicks. I suggest introducing an interface similar to VLC for audio and subtitle synchronization.

![vlc sync](https://user-images.githubusercontent.com/27731012/236426370-d9e45838-6765-4f18-b4a7-89d42b41da8c.png)

This will be helpful than remembering shortcut key anyone rarely uses or complicated Subresync console in MPC. And also remove Subresync from MPC-HC; you're better off using a dedicated subtitle editing software.

**Comment by clsid2** [comment]
I am not going to add any new functionality.

F keys do work on laptops. Learn how to use the keyboard. Hint: Fn button.

Delay step is NOT the delay. It is the step size for each time you press F1/F2.
