### ISSUE TITLE
no cover-art with FullscreenSeparateControls

### ISSUE THREAD

**Issue by Wille-Helm** [clsid2/mpc-hc#2116]
Hi,

I use mpc-hc to play back music videos (mixed with other music and cover-art) on a second display.

That's where FullscreenSeparateControls comes in handy.
Sadly it quits fullscreen mode every time there is no video content present, like simple music files with (or without) cover-art file, but resumes fullscreen as soon as a new video is loaded.

Any chance to get the same functionality as without SeparateControls?

Thanks in advance!

Regards,
Wilhelm

**Comment by clsid2** [comment]
@adipose
In `CMainFrame::OpenSetupVideo()` the fullscreen window get destroyed for audio files. But `ToggleFullscreen` doesn't get called, so it is in a semi broken fullscreen state in case of FullscreenSeparateControls. Only after double-click in turns into correct size on main window.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2134

This seems to fix it...I don't fully understand why, or why it's only necessary for FSSC.

**Comment by Wille-Helm** [comment]
Thanks a lot, I'm looking forward to it!
