### ISSUE TITLE
streaming via yt-dlp.exe does not work through web proxy

### ISSUE THREAD

**Issue by HautdenLukas** [clsid2/mpc-hc#2119]
mpc-hc version 2.0.0
yt-dlp version 20230304

In my network all access to web pages needs to go through a web proxy. Downloading youtube content via yt-dlp is working fine in mpc-hc. I added the option "--proxy http://<proxy ip address>:<proxy port>" to the YDLCommandLine parameter in mpc-hc to make downloads work.
However, this does not apply to streaming. When I open a youtube address in mpc-hc, I can see that yt-dlp is invoked, but it tries to reach the address directly on port 443, trying to go around the web proxy. mpc-hc then stays in a deadlock forever, because yt-dlp can't reach the address.
I tried adding above proxy option to the YDLExePath, but that only causes mpc-hc to fail to invoke yt-dlp.exe completely.

It would be great if mpc-hc supported yt-dlp to stream media via proxy, just as it allows to download media. Thank you.

**Comment by clsid2** [comment]
When streaming yt-dlp is only used to gather the URLs. Playback is done using LAV Filters. That doesn't support proxy.
