### ISSUE TITLE
Adding support for libass kerning extension to VSFilter

### ISSUE THREAD

**Issue by Witiko** [clsid2/mpc-hc#212]
This issue regards the VSFilter library, which is responsible for the display of SubStation Alpha subtitles in MPC-HC, and which lacks support for font kerning.

[The libass library](https://github.com/libass/libass) supports the `Kerning` parameter in the `[Script Info]` section of SubStation Alpha subtitles, which enables the kerning of fonts. Kerning greatly improves the letterspacing in subtitles:

![71684032-83ed5400-2d94-11ea-90cc-31b0233e9942](https://user-images.githubusercontent.com/603082/71754120-33095880-2e85-11ea-8d1d-634bc52603c8.png)

Although the extension is non-standard, it is helps to produce more readable subtitles. Is there either any intention of adding this extension to MPC-HC's VSFilter or a reason to reject a pull request that would implement this functionality?

This issue is also discussed at https://github.com/Aegisub/Aegisub/issues/164.

**Comment by clsid2** [comment]
I have no interest in this.

Accepting a patch would depend on its performance impact.

But you should realize that the majority of your audience is using old software, and won't benefit from this.

**Comment by Witiko** [comment]
> But you should realize that the majority of your audience is using old software, and won't benefit from this.

It is my understanding that the kerning extension has been supported by [libass](https://github.com/libass/libass) since before 2010 (https://github.com/libass/libass/commit/0d3ddc12295e38cdcb11c79f8dcb5c8d9f1a8b69), so there should be a moderately-sized user base for libass-based players, such as [mpv](https://github.com/mpv-player/mpv) and [vlc](https://github.com/videolan/vlc), which already display subtitles differently than VSFilter does.

Adding support for the kerning extension will not change things overnight, but it would be a first step towards a more unified and typographically sound viewing experience.
