### ISSUE TITLE
Playback at increased speed sounds like a chipmunk

### ISSUE THREAD

**Issue by dannymalt** [clsid2/mpc-hc#2121]
VLC can playback a video at a faster speed and still sound normal (albeit faster). But MPC HC, when you play a video back at a faster speed it sounds high pitched and chipmunk like. Would love if this could be fixed.

**Comment by adipose** [comment]
> VLC can playback a video at a faster speed and still sound normal (albeit faster). But MPC HC, when you play a video back at a faster speed it sounds high pitched and chipmunk like. Would love if this could be fixed.

Try using the internal or mpcbe AR option.

https://github.com/clsid2/mpc-hc/issues/705

**Comment by dannymalt** [comment]
Thanks that worked! So what I had to do if anyone else finds this later is this.
View > Options > Playback > Output > Audio Renderer. Switch that to MPC Audio Renderer. Apply.
