### ISSUE TITLE
Allow right-clicks on toolbar buttons

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2122]
Right-click on skip forward could be used to skip to next file. Left will skip to next chapter if a file has any chapters.

Right-click on step button could step backwards.

Right-click on stop could close file.

**Comment by bekard** [comment]
@clsid2 Hi! I can't understand how messages are translated from `CPlayerToolBar` to `CMainFrame`. When I left-click on "Step", the `CPlayerToolBar` calls `::CallWindowProc` with `Msg == WM_LBUTTONUP`. `CMainFrame` receives a `WM_COMMAND` message with parameter 891 which is `ID_PLAY_FRAMESTEP`. How does this happen, where does `CMainFrame` get `ID_PLAY_FRAMESTEP` as a parameter in this call? I would be grateful for any hint or direction in which to look.
![image](https://github.com/clsid2/mpc-hc/assets/42998026/ab84caf9-14d8-4035-9add-016cf77bc1c3)

**Comment by clsid2** [comment]
Search for IDB_PLAYERTOOLBAR in mpc-hc.rc and you find a table with IDs of actions associated with the buttons. That is used for left-clicks.

For right-click a different implementation is needed. Something like adding `CPlayerToolBar::OnRButtonUp`. There use `getHitButtonIdx` to find which button was clicked and then doing a postmessage to mainframe.

**Comment by bekard** [comment]
Thanks! If done with `PostMessage`, then the click (that the button is pressed) is not displayed on the toolbar. Perhaps clicking a button can be emulated somehow...
Also, have you considered the option of making separate buttons on the toolbar for these actions? Wouldn't this be a better solution?

**Comment by clsid2** [comment]
I am not adding buttons. These specific actions are very suitable as secondary action.

A visual button press animation is not important. Emulating that can be added later. Adipose knows a lot about the GUI related stuff.

**Comment by bekard** [comment]
Made Pull Request: #2245
