### ISSUE TITLE
FN+Fnn keys to control playback ceased to work

### ISSUE THREAD

**Issue by SteKme** [clsid2/mpc-hc#2126]
Hi,

I used to control playback with keyboard -- many keyboards have FN+Fnn key combinations to change volume and also play/pause and prev+next track skip (in my case FN+F6/7/8).
MPCHC has supported this control, however couple releases back, this has ceased to function - tested in Win10 and 11 as well. Other players (win media player...) still work just fine. 
Please, would it be possible to re-enable this? Point of this is the shortcut shall be global, i.e. the player gets paused even when the window is not in focus - this is the most important function, instead of finding the player's window, have a fast way to kill the playback when needed.

Thank You so much for considering and best regards,
Stepan

**Comment by clsid2** [comment]
Options > Player > Keys > Global Media Keys
