### ISSUE TITLE
Weird sub issue

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2144]
Sample file: https://drive.google.com/file/d/1W5Hq72B7XkzBKWxMfORvwrdXCtz2Dlw_/view?usp=sharing
Both MPC-HC & BE have same problem.

![Screenshot (37)](https://github.com/clsid2/mpc-hc/assets/98865389/54357a60-3a5a-4e89-9ce6-abed4eba6e08)
![Screenshot (38)](https://github.com/clsid2/mpc-hc/assets/98865389/04111660-233f-4665-9581-e1608b36c05f)

**Comment by clsid2** [comment]
Fixed
