### ISSUE TITLE
Flicker when resizing window

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2147]
@adipose
There is a flicker issue after commit https://github.com/clsid2/mpc-hc/commit/2a2411e28a3dab7c24e5e1dfdbf4f3c7a517dfee.
Happens when resizing window, or when showing/hiding the toolbar in fullscreen. Best noticeable with EVR-CP.

I have tracked it down to `CMouseWndWithArtView::OnEraseBkgnd`. Skipping the `FillSolidRect` at the end fixes it. I am not sure why it happens as this OnEraseBkgnd function has same code as before when it was in CChildView. So maybe it gets called more often now?

Edit: I have committed a possible fix.

And another pre-existing issue, unrelated to the above. The volume bar in dark theme flickers with light background when resizing the window.

**Comment by bibsp** [comment]
After your latest patch flicker issue is fixed. But now when opening file, a small window is flashing for a second.
Please check this video.
[Problem recording.zip](https://github.com/clsid2/mpc-hc/files/11659478/Problem.recording.zip)

**Comment by adipose** [comment]
> @adipose
> 
> There is a flicker issue after commit https://github.com/clsid2/mpc-hc/commit/2a2411e28a3dab7c24e5e1dfdbf4f3c7a517dfee.
> 
> Happens when resizing window, or when showing/hiding the toolbar in fullscreen. Best noticeable with EVR-CP.
> 
> 
> 
> I have tracked it down to `CMouseWndWithArtView::OnEraseBkgnd`. Skipping the `FillSolidRect` at the end fixes it. I am not sure why it happens as this OnEraseBkgnd function has same code as before when it was in CChildView. So maybe it gets called more often now?
> 
> 
> 
> Edit: I have committed a possible fix.
> 
> 
> 
> 
> 
> And another pre-existing issue, unrelated to the above. The volume bar in dark theme flickers with light background when resizing the window.

Cchildview wasn't used for dedicated fullscreen window.  I made it support it, but perhaps we should limit it to one time after media change.

**Comment by clsid2** [comment]
The problem happens with windowed and regular fullscreen. So not related to changes to the dedicated fullscreen window.

**Comment by adipose** [comment]
I experienced going fullscreen and back (with a paused video), that the window was drawn black and even the logo flashed briefly.

**Comment by adipose** [comment]
@clsid2 , if you checkout 2a2411e do you have the same issue?  I couldn't repro it under 2a2411e branch.

edit...

I can repro it now, just needed a higher-res video.

**Comment by adipose** [comment]
Seems to be caused by this change:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/7be055f3-86bf-458c-99b5-e3f39cdc7b1a)

In particular, this causes flickering during a fullscreen mouse-over of the menu.  I believe this was meant to apply when the window was D3D only?

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2149

This fixes the issue that the fullscreen window cliprect was never initialized.  After changing this, I don't get flicker when mousing over the bottom toolbar anymore.

**Comment by clsid2** [comment]
Yes that fixes it. The `return false` part in efc4403 does not seem needed anymore. Can you confirm that? 

I still don't understand why one window is having effect on another one.

**Comment by adipose** [comment]
> Yes that fixes it. The `return false` part in [efc4403](https://github.com/clsid2/mpc-hc/commit/efc440398a002506fb169520c3b4320f4a8e7f7a) does not seem needed anymore. Can you confirm that?
> 
> I still don't understand why one window is having effect on another one.

Yes, I guess I didn't include that in my patch...still seems to work ok, though.

https://github.com/clsid2/mpc-hc/pull/2150

I also find this confusing, need to review the window types.

**Comment by adipose** [comment]
> I still don't understand why one window is having effect on another one.

OK, I found it now.  `CChildView` was still shadowing the `m_vrect` variable.  By moving the function for updating it to the parent class, it got around it.  But I've now removed that var from `CChildView` as well.

What was happening was `m_wndView.SetVideoRect(&windowRect)` was actually updating the shadowed copy which is ignored in the erasebg call.

**Comment by clsid2** [comment]
Thanks for looking into it.

**Comment by clsid2** [comment]
Are you able to reproduce the flicker of the volume slider when resizing the window?

**Comment by adipose** [comment]
> Are you able to reproduce the flicker of the volume slider when resizing the window?

No, I cannot get it to flicker yet.
