### ISSUE TITLE
Shadow Copy | VSS Stops MPC-HC playback and sits on a black screen

### ISSUE THREAD

**Issue by lssyadmin** [clsid2/mpc-hc#2152]
Hi there.  We have been having issues with playback stopping somewhat randomly and correlated it to system protection being on Win10 and a shadow copy being made.  We confirmed this by looking at the event viewer and camera footage of these systems.

We are running 1.9.22 and trying to reproduce by taking a manual restore point with video playing did not work.

Very odd one

**Comment by clsid2** [comment]
Press Ctrl+E to reload the video.

I am not interested in VSS and its bugs.

**Comment by lssyadmin** [comment]
We do an /add of a directory path every 60 seconds, but MPC-HC continues to stay on a black screen.  We will test if disabling system restore does the trick or not.  Otherwise, we'll move on to a more stable player.  Thx

**Comment by clsid2** [comment]
If you keep adding a whole directory to the playlist, then it will grow huge. I don't think that is what you want to do?
/add also does not change the currently playing file.

And "sits on black screen" is not really a very detailed description of what is happening. Was a file playing normally initially? Does the sound also stop?
