### ISSUE TITLE
Autochange fullscreen mode doesn't work with HDR files

### ISSUE THREAD

**Issue by Qwertylala1** [clsid2/mpc-hc#2153]
The setting "Use autochange fullscreen monitor mode" doesn't work with HDR files. I have it set to only switch the frame rate and not the resolution but when I open a HDR file the screen stays in 60 Hz according to the TV, and I can see that the movement isn't smooth.

If I open the movie without the automatic full screen setting and change to full screen manually it works fine. The automatic setting seems to work with SDR files, when I open them it switches to the correct frame rate.

I use MPC Video Renderer in DX 11 Mode with HDR passthrough. The problem exists in both MPC-HC 2.0.0 and the development version 2.0.0.64, both Windows x64.

**Comment by clsid2** [comment]
HDR passthrough requires its own display mode switch. Doing them at same time causes problem. Solution is to disable automatic fullscreen.

I can't fix this. 

You should update MPCVR to latest version.
