### ISSUE TITLE
problem with subtitle positioning

### ISSUE THREAD

**Issue by eddilara** [clsid2/mpc-hc#2155]
so got a few subs here where the subs are not being positioned properly 
they work properly with madvr+xysubfilter...and on vlc they work properly
they also work properly on aegisub
https://github.com/arch1t3cht/Aegisub

I could attach the sub files...might be pointless tho without the video file
[[TechMod] Gatchaman Crowds Insight.zip](https://github.com/clsid2/mpc-hc/files/11714017/TechMod.Gatchaman.Crowds.Insight.zip)

https://file.io/jku236PZSERC
the opening karaoke is whats positioned wrong

**Comment by clsid2** [comment]
Caused by https://github.com/clsid2/mpc-hc/commit/77d51e65c12f204406a99e068e08d8c33dde05de

**Comment by clsid2** [comment]
Fixed
