### ISSUE TITLE
Disable video area drag

### ISSUE THREAD

**Issue by Perplexer1** [clsid2/mpc-hc#2159]
I don't know if there were any requests for this here before but if I may borrow an example from https://sourceforge.net/p/mpcbe/tickets/806/ then I am probably not alone thinking about this.

Basically I don't like how MPC-HC window can be moved by clicking and dragging the mouse in the video area. It makes it hard for me to pause the video (especially considering I just upgraded from an earlier version which didn't have this). In earlier versions it was only possible to drag the window by the title bar or by the controls bar / seek bar / status bar.

MPC-BE eventually heard the requests and added a checkbox to the Options, which is the right way to go.

![Image1](https://github.com/clsid2/mpc-hc/assets/29666913/d9067748-d0e9-40bd-a193-061cd442091a)

Would it be possible to add something like that to MPC-HC, perhaps as a checkbox under the Player section in Options or under Advanced (like "AllowVideoAreaDragging" False or "DisableVideoAreaDragging" True) ?

**Comment by clsid2** [comment]
I am not adding an option for this. It already requires a certain amount of movement before it starts a drag. So small movements are ignored.
