### ISSUE TITLE
Interface issues when using fullscreen

### ISSUE THREAD

**Issue by Twichigo** [clsid2/mpc-hc#2166]
Version 2.0.0.69 Build date June 8 2023, but these issues have been around for at least a year, I can't now recall for how long.

1.  When "Launch files in fullscreen" is on, skipping forward/back to next/previous file always forces fullscreen. Before, this option only affected launching a file.
2. After using skip back or forward in fullscreen at least once, exiting fullscreen will forcefully un-maximize the window. Before, if you maximized the window it would always stay that way, even after reopening the player.

There's a chance these aren't bugs but features. Still, thought I'd mention this inconvenient behaviour.

**Comment by adipose** [comment]
I can confirm both behaviors.  Number 1 seems debatable, but number 2 seems wrong.

**Comment by adipose** [comment]
Number 2 is pre-existing.

**Comment by adipose** [comment]
@clsid2 

Introduced in https://github.com/clsid2/mpc-hc/commit/3ddeda6699e58226c63df2b9b34e535e309c15b9

Should it go full screen when hitting next, if it is not currently fullscreen?

**Comment by clsid2** [comment]
I think it was requested in the past to go fullscreen for every file. But it is fine with me to keep current window state when going to next/previous.

Edit: when player is already running and a new file is opened through Explorer, then it should go fullscreen again. That was what was requested in the past. I am not sure if it is easy to distinguish properly between use cases. Maybe just keep current behavior of lauching fullscreen for every file.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2260

It still goes FS if you launch from explorer with this patch.

**Comment by Rikk** [comment]
Regarding `#2` above, I can still reproduce it in 2.0.0.162

**Comment by adipose** [comment]
Patch only addresses issue 1.
Issue 2 is older and unrelated.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2801

Fixes issue #2.
