### ISSUE TITLE
Incorrect Contrast Intel GPU

### ISSUE THREAD

**Issue by FireCulex** [clsid2/mpc-hc#2167]
Description:
When playing subsequent videos in a directory on a secondary monitor, I have observed that the video quality becomes visibly harsher. I believe the next video "Reinitializes" the display. This behavior can be reliably reproduced using the following steps.

Steps to Reproduce:

1. Enable the "Reinitialize when changing display" setting found in Playback -> Output.
2. Load a video on Primary display
3. Drag the video to the Secondary display and see the contrast change
4. Drag the video back to the Primary display and see the contrast back to normal

Additional Information:
The main monitor used in this scenario is an RX 580, while the secondary monitor is connected to the motherboard, utilizing the onboard Intel HD Graphics 630. 

I tested using the video available at https://test-videos.co.uk/bigbuckbunny/mkv.

To better illustrate this strange contrast behavior, I have recorded a video which can be viewed at https://youtu.be/nvpFXNS8mac

Software Version: 2.0.0 (973b644a3)

edit: I verified this occurs on the Intel GPU being the only monitor. I also verified VLC displays correctly.
https://youtu.be/eR0Z6Ci6ZnM - alt-tabbing between mpc-hc and VLC on Intel GPU

**Comment by clsid2** [comment]
This is not a fault of the player.

In Intel driver settings, disable options such as Contrast Enhancement, Fleshtone Enhancement, and Dynamic brightness.

If that does not help you need to complain to Intel.
