### ISSUE TITLE
[Feature request] Change aspect ratio via shortcut (either Video Frame or Pan Scan)

### ISSUE THREAD

**Issue by furopi** [clsid2/mpc-hc#2168]
Title reads it all. I want to set shortcuts for switching the aspect ratio, but there seems no way to do it. Or am I missing something. If yes, I would be glad to be enlightened.

Tank you @clsid2  for creating such a powerful tool for free!!! I really appreciate it and use it every day!

Kind regards,
Florian from Germany

**Comment by clsid2** [comment]
There is shortcut called "Next AR preset" for toggling through the various AR modes. There are also shortcuts for Pan&Scan.

I am not adding any new shortcuts.

**Comment by furopi** [comment]
TY!!!!!!!!
