### ISSUE TITLE
Suddenly crashing with madVR

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [clsid2/mpc-hc#2170]
Since yesterday I suddenly cannot use madVR in ouptions > playback > output.

I can't even get any crashlogs, the window for sending crashlogs never appears. But sendrpt.ext is running. How can I find out why suddenly madVR stopped working?

**Comment by clsid2** [comment]
Crashlogs are useless for MadVR. I can't fix bugs in MadVR.

If it started yesterday it must be related to settings changes that you have made in MadVR, or software/drivers that you have installed or updated.
