### ISSUE TITLE
Seekbar preview for mp4

### ISSUE THREAD

**Issue by Ansh4011** [clsid2/mpc-hc#2176]
Hi just wanted to inquire if seekbar preview works for mp4, at least for me it doesn't, but when I edit the extension of the mp4 file to webm the seekbar preview shows up although the file explorer thumbnail for the video goes away. Thanks, and awesome work on mpc-hc mate, makes it do much better to watch lectures on mpc-hc than the website lol.

**Comment by clsid2** [comment]
Yes, seek preview should work for mp4 and all other video formats as well.
I don't know why it isn't working for you. Maybe internal codecs are disabled or missing. Re-install the player and reset settings.

The player is not involved in any way with thumbnails in Explorer.

**Comment by Ansh4011** [comment]
Thanks mate, just installed k-lite codec and everything is working as complete as expected. Have a good day!
