### ISSUE TITLE
Randomly skipping or reversing ahead, in ByteScout Screen Capturing v3.0.2.79's long WMV files, sometimes freezes 64-bit MPC-HC v1.9.0.

### ISSUE THREAD

**Issue by antdude** [clsid2/mpc-hc#218]
Hello.

I don't know if other users have this problem too. When I reverse or skip ahead (doesn't matter if it is playing or in paused) with ByteScout Screen Capturing v3.0.2.79's WMV files (e.g., 250 MB and over 17 minutes), my 64-bit MPC-HC v1.9.0 sometimes freezes (crashes to force me to kill its process if stuck). I didn't have this problem with the older versions like v1.8.8.

I'm using a decade old 64-bit W7 HPE SP1 PC with 6 GB of RAM, ATI Radeon 4870 video card (512 MB of VRAM), etc. http://zimage.com/~ant/antfarm/about/MyComputerStuff.txt for it detailed primary PC specifications. My MPC's help about shows:

MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.0 (bfaf63b3b)
    Compiler:           MSVC v19.16.27034
    Build date:         Dec 29 2019 12:59:31

LAV Filters:
    LAV Splitter:       0.74.1.31
    LAV Video:          0.74.1.31
    LAV Audio:          0.74.1.31
    FFmpeg compiler:    MinGW-w64 GCC 9.2.0

Operating system:
    Name:               Windows NT 6.1 (build 7601, Service Pack 1)
    Version:            6.1 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7 CPU         950  @ 3.07GHz
    GPU:                ATI Radeon HD 4800 Series (driver version: 8.17.10.1129)

Thank you for reading and hopefully answering. :)

**Comment by clsid2** [comment]
I can't really do anything about this without a sample file.

Try disabling the internal WMV source filter and WMV transform filter.

**Comment by antdude** [comment]
MPC-HC had its source filter unchecked so I checked it, and exited and relaunched MPC-HC to retest. It seems to work. If not, then I'll share a big WMV file.

**Comment by antdude** [comment]
FYI. I had to check WMV1/2/3 transform filters as well since my today's WMVs stopped playing, but their audios kept playing.

**Comment by clsid2** [comment]
Yes, it works best when either both are enabled or both disabled.

Your files might be missing a seek index. You can 'fix' them with this tool:
http://www.radioactivepages.com/asfbindetails.aspx
