### ISSUE TITLE
MPC Video Render - When changing subtitles the video go black

### ISSUE THREAD

**Issue by tealkami** [clsid2/mpc-hc#2181]
Hi, I want to change from  EVR-CP to MPC Video Renderer , because for some reason EVR-CP don't want to do D3D native, when MPC video Renderer does... but :
**The Issue:**
When I change subtitles while playing the video/frame goes black+freeze(it is only for like 1ms, yes, I know it is just buffering new data) , but if I change audio track it will only freeze with last frame instead of being black frame while buffering.
in MPC-BE + MPC Video Renderer it just stop when changing only the audio (no black frame when changing any tracks)

So can you please fix it so it will show last frame, instead of black frame ? It is very disturbing having black frames, when I compare subtitles.

-----
or... is there a way to force EVR-CP to use D3D11 Native instead of copy-back ? in LAV Filter I have only option for : Automatic or forced copy-back for D3D11 , everyone say the D3D11 is better than the DXVA2, so it would be nice if it was some way to make it work

Few months ago I experienced what is it to have slower CPU, I changed something in UEFI , and most things were non-lagy, but 4K were dropping frames, and 5K 60fps was unplayable, it was like 4K in SW was 60-80% CPU utilization , and everything else was loading longer while playing 4K video, with D3D11 copy-back , CPU utilization was like 20-40% (still like file explorer was not instantly open), and with D3D native CPU utilization was like 1%, and could use PC without problem, after I tried that 5K 60fps, I did reset my UEFI settings, but the point I am writing about this still apply , some people can have old CPU and newest GPU.

My specs:
iGPU : Ryzen 5700G - Vega 8 - allocated 4GB RAM - Cezanne - AMD Radeon drivers 23.5.1
MPC-HC 2.0.0 32bit
LAV Filter 0.77.2
MPC Video Renderer 0.6.7.2013
Win 10 64bit - 19044.1889

-----
And one more thing on this [Wiki (VCN 2.0/Cezanne)](https://en.wikipedia.org/wiki/Unified_Video_Decoder) , they say it support 8K decoding, but when I tried with any combination of MPC-HC/BE/MPC Video render, my h264 5K 60fps was rendered in software.
How does the player<=>driver communication look? it is like "Player: Can you decode this codec?" "Driver: yes/no", or like it give list of codecs which it can decode ? I can't find any spec sheet for older GPUs on AMD side. 

Is there a way that I can like write some command and it will give me the list what my iGPU supports (like 8K only in VP9 and H265, and 4K in h264 8b) ?

**Comment by clsid2** [comment]
Changing subs requires a repaint. I don't care if this gives a black frame.

EVR-CP does not support D3D11 native. Only MPCVR and MadVR support that. There is no benefit in using D3D11 decoding in EVR-CP because that renderer uses D3D9. Use DXVA2 Native.

If it supports 8k it probably can't go above 30 fps.
DXVA Checker application can show details about what is supported.

**Comment by tealkami** [comment]
Aren't subtitles on different layer ? Can't the changing of subtitles only repaint the subtitle layer ?

-----

Thank you for the clarification

and DXVAChecker says 8K is only for VP9(Profile0,10bit Profile2) . HEVC (Main,Main10) , MJPEG; everything else is 4K
