### ISSUE TITLE
Instagram Video Hang.......

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#2182]
instagram video hang, see screen recording

instagram link use in video: https://www.instagram.com/reel/CuUUeJDtJfV/

https://github.com/clsid2/mpc-hc/assets/120308983/63794621-9b1f-407b-a7b4-c52d8b21850a

**Comment by clsid2** [comment]
Either connection is slow or it is being throttled. There is NOTHING I can do about that.

Updating yt-dlp can often help with throttling problems.

https://github.com/yt-dlp/yt-dlp-nightly-builds/

**Comment by ghost** [comment]
Actually problem with **LAV Splitter Source**

**Comment by ghost** [comment]
MPC-BE (without LAV Filter) = working fine

https://github.com/clsid2/mpc-hc/assets/120308983/98064123-e21f-46e3-8614-50f6640345a9


MPC-BE (with LAV Filter) = some problem

https://github.com/clsid2/mpc-hc/assets/120308983/9dcdb9c2-a4e3-4e88-931a-81733e2b7b18

**Comment by ghost** [comment]
..
[MPC-HC](https://github.com/clsid2/mpc-hc/) [MPC-BE](https://github.com/Aleksoid1978/MPC-BE) [LAV Filters](https://github.com/Nevcairiel/LAVFilters/)

**Comment by ghost** [comment]
@clsid2 @Aleksoid1978 @Nevcairiel
