### ISSUE TITLE
Scale/Align Problems on Multi Monitor Setup

### ISSUE THREAD

**Issue by FrankBKK** [clsid2/mpc-hc#2184]
I have a three monitor setup, 2 x FHD, 1 x QHD, 
Video Frame is set to "Touch Window from Inside"
MPC starts in window mode 

When I start MPC on a FHD screen and drag it over to the QHD screen and then dbl-click on the title bar 
the movie is not properly scaled, actually it looks like there is no scaling at all and the movie aligns only to the top right corner of the MPC window leaving a gap on the right side. 

Starting on QHD screen and moving to the FHD screen and dbl click on the title bar works fine though. 

Version 2.0.0.96 (also occurs on older versions)

![Clipboard02](https://github.com/clsid2/mpc-hc/assets/12725516/eabe40d0-042f-4ce7-9b59-fc04c37afdfc)

.

**Comment by adipose** [comment]
I could not reproduce this one.

Can you record a video of it?

**Comment by FrankBKK** [comment]
Hmm, just checked with 2.2.1 - seems the issue is gone with the latest version ...

**Comment by adipose** [comment]
That's good, bugs don't usually fix themselves but maybe we got lucky!

**Comment by adipose** [comment]
If you are bored you can try builds and figure put when it was last broken.
