### ISSUE TITLE
Audio / Subtitle Tracks not detected (.mkv format)

### ISSUE THREAD

**Issue by ISpectre23** [clsid2/mpc-hc#2186]
I have a .mkv file which includes subtitles and 2 audio tracks, MPC-HC does not detect them while Windows media player and films does.

WINDOWS MEDIA PLAYER
<img width="963" alt="Captura de pantalla 2023-07-15 021142" src="https://github.com/clsid2/mpc-hc/assets/133978042/ba07e469-1fe6-4bf7-8e45-2c06e3f3ad8b">

MPC-HC
<img width="963" alt="Captura de pantalla 2023-07-15 020916" src="https://github.com/clsid2/mpc-hc/assets/133978042/c9d69565-612a-425b-8ce9-a8dd209f123c">

<img width="963" alt="Captura de pantalla 2023-07-15 021335" src="https://github.com/clsid2/mpc-hc/assets/133978042/f6e9f7ed-ec1f-4199-aca5-e8b23b27d8ad">

**Comment by clsid2** [comment]
I can do nothing without the file.
