### ISSUE TITLE
Navigation panel not working

### ISSUE THREAD

**Issue by Rhiannon81** [clsid2/mpc-hc#219]
The navigation panel is unresponsive in version 1.9.0.

When using a capture device, clicking on an item (channel name) in the navigation panel will not switch the channel.

Changing the channel by using PageUp/PageDown or the media keys does work.

Edited to add: The panel did work in v. 1.8.8, and it still works when downgrading again to 1.8.8 without resetting the user preferences.

**Comment by adipose** [comment]
@Rhiannon81 

Is this true with classic theme and without?  I have some difficulty testing this, but I created a virtual capture device when working on the dark theme, and I think it was working fine.

Can you test with both themes?

**Comment by Rhiannon81** [comment]
Just tested, confirmed not working even with dark theme.

One thing that works instead, with both dark theme and classic theme, is right click -> watch.

**Comment by Rhiannon81** [comment]
Fixed in version 1.9.1. Thanks.
