### ISSUE TITLE
Open DVD/BD to treat the folder as the content of Blu-ray disc

### ISSUE THREAD

**Issue by hh8923** [clsid2/mpc-hc#2190]
When use File -> Open DVD/BD ans select a folder which contains the content of a Blu-ray disc, it opens one of the m2ts file instead treating the folder as a Blu-ray disc.  This means it can only play the m2ts file I chose even though the folder may contain multiple timelines.  It also miss the Blu-ray menu etc.

Appreciate if this can be fixed.  

Thanks

**Comment by clsid2** [comment]
It does open it as bluray. It opens the longest video on the disc by default. You can select different content through the Navigate menu.

Bluray menus are not supported and will likely never be supported.
