### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by lx30011** [clsid2/mpc-hc#2191]
I would really like to have multiple MPC-HC instances with different settings. E.g. one instance that outputs audio to my speakers next to my default instance that uses Windows default output. I don't see a way to do this with the config stored in registry. But perhaps there is a way or MPC-HC could be rewritten to store config in a file?

**Comment by clsid2** [comment]
Options > Player > Store settings in INI file

To be able to use INI file you must put the player files in a folder where you windows user account has write access (without admin elevation!!!). So not in protected Windows folders such as program files.
