### ISSUE TITLE
interfering Elements

### ISSUE THREAD

**Issue by mewnm** [clsid2/mpc-hc#2193]
Hello! Good morning. I was wondering how to disable these things that appear on the top left while imputing commands with the keyboard. 

![Captura de tela 2023-07-21 102813](https://github.com/clsid2/mpc-hc/assets/55022044/c942e44a-d614-4ef1-9c97-cedbc517262e)

Thanks

**Comment by clsid2** [comment]
Options > Player > Show OSD
