### ISSUE TITLE
Something strange with EVR custom presenter

### ISSUE THREAD

**Issue by AL1-1956** [clsid2/mpc-hc#2194]
Hello team and everybody
First of all , i am French so my English may not be very accurate
I have recently a problem of colors wich are very saturated with EVR custom presenter 
and with video having Variable Bit Rate I eve get a black screen
so I had to switch to VR7 to have right colors or simply in case of VBR something on the screen.
I do not know when the problem appeared
![BA](https://github.com/clsid2/mpc-hc/assets/96848008/824947da-73b9-4109-be16-e2daeab44b09)

On the left it's EVR CP and on the right it's VR7 with exactly same settings
Thank you for help and have a great day

Alain

**Comment by clsid2** [comment]
It is a bug (or setting) in your graphics driver that does this.

VMR7 does not support DXVA2 hardware decoding and video processing, so problem does not show up in that case.

If you have Intel graphics, then disable `Contrast Enhancement` and `Fleshtone Ehnhancement` in the driver settings.

**Comment by AL1-1956** [comment]
Okay
So I went into the Intel graphics 4600 settings and nothing changed  when I did what you say.
But then I made a reset of all settings and now it's OK
Mysteries of computers.
Anyway thank you for the tip
