### ISSUE TITLE
Normal Size/Touch Window From Inside

### ISSUE THREAD

**Issue by lx30011** [clsid2/mpc-hc#2195]
Could you implement a scaling mode that displays videos at 100% size (pixel-perfect) up until where it would break out of the screen, in that case just touch window from inside. Thanks!

**Comment by clsid2** [comment]
That is already what it does by default in windowed mode with default settings. So reset your settings.

I am not adding any new modes.

**Comment by lx30011** [comment]
Yes, that's what I'm using. But it would be good if the same thing were possible in full screen so there's only a black background and the video. Maybe you can consider it.
