### ISSUE TITLE
如何设置才能最大限度地利用 GPU?  How to set up to maximize GPU usage?

### ISSUE THREAD

**Issue by DOSforever** [clsid2/mpc-hc#2196]
当播放视频时，我打开 Open Hardware Monitor 监测 GPU 使用情况，发现 GPU Core, GPU Frame Buffer, GPU Bus Interface, GPU Memory 都或多或少地有些数值变化，但唯独 GPU Video Engine 却始终是 0% 。是我本身的显卡不被支持还是显卡或 MPC-HC 在某些方面需要设置才能用到 GPU Video Engine ？或还是我对这一项的意义理解有误？

When I open Open Hardware Monitor to monitor GPU usage while playing a video, I see that GPU Core, GPU Frame Buffer, GPU Bus Interface, GPU Memory are all more or less the same, but GPU Video Engine is always at 0%. Is it because my graphics card is not supported or is there something about the card or MPC-HC that needs to be set up to utilize the GPU Video Engine? Or am I misunderstanding the meaning of this item?

**Comment by clsid2** [comment]
You can enable hardware decoding in the video decoder settings.

**Comment by DOSforever** [comment]
> You can enable hardware decoding in the video decoder settings.

Where is the settings in options?

**Comment by clsid2** [comment]
Options > Internal Filters > Video decoder
