### ISSUE TITLE
Specific instances of issues with resolving long path files

### ISSUE THREAD

**Issue by bashenk** [clsid2/mpc-hc#2198]
### Situation

I noticed some issues when trying to add files that are above the normal path limit to a playlist after stripping the 8dot3 name from those files. That is, when attempting to add such a file by dragging it onto the playlist, nothing happens; furthermore, when trying to play it after adding it to the playlist via dragging in the containing folder instead, the file becomes grayed out, the text "Invalid" appears on it, and it gets skipped over.

### Affected versions
At minimum:
* 2.0.0 (973b644a3)
* 2.0.0.104 (cd0d5358b)

### Example
```cmd
C:\>reg query HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
    LongPathsEnabled    REG_DWORD    0x1

C:\>dir /X "C:\testing\some bad directory name 123456789123456789123456789123456789\another terrible directory name 123456789123456789123456789123456789123456789123456789\why would you do this 123456789123456789123456789123456789123456789123456789123456789123\"
 Volume in drive C has no label.
 Volume Serial Number is ****-****

 Directory of C:\testing\some bad directory name 123456789123456789123456789123456789\another terrible directory name 123456789123456789123456789123456789123456789123456789\why would you do this 123456789123456789123456789123456789123456789123456789123456789123

07/25/2023  03:54 PM    <DIR>                       .
07/25/2023  03:54 PM    <DIR>                       ..
07/25/2023  01:54 AM       438,010,771              TestVideo.mkv
```
Above shows an arbitrary situation of a file in a "too-long" path that does not have an 8dot3 name (This "short name" would appear in the area between the file size and the file name when using the `/X` flag for `cmd`'s `dir`).

#### When interacting with this file:
* Drag & Drop onto playlist = Nothing happens
* Drag Folder onto playlist = File gets added to playlist, but the file is deemed invalid and gets skipped over during playlist playback
* Open file from Explorer (opening with MPC-HC) = Plays video as expected
* Open file from MPC-HC's "Open" dialog = Plays video as expected

#### Expectation
Rather, the file is added to the playlist as normal and opens properly in every situation.

### Hypothesis
The [ExtendMaxPathLengthIfNeeded](https://github.com/clsid2/mpc-hc/blob/develop/src/DSUtil/DSUtil.cpp#L1355) function is missing usage in some places.

### Comments
I contemplated adding a comment to suggest reopening issue #2020 for this but decided that a new issue is likely to be more appropriate.
After further testing, the 8dot3 name thing I've mentioned in a few places is somewhat tangential, though perhaps still relevant. I believe that when I originally encountered this issue, it just so happened that the short name for some file I was working with was able to bring it under the path limit, but that is an edge case scenario that could depend on a variety of things, such as the containing folders also having 8dot3name creation enabled. Though, to be clear, in that situation for me, the files worked "properly" in all other aspects besides them being listed in the playlist by their short name and showing up in the playlist with their file location being the short name version.

**Comment by clsid2** [comment]
Drag&drop onto playlist works fine for me with a long path. Explorer uses shortened name in that case. If you disable 8dot3, then yes, things can fail. I don't really care as fault is then in the input to the player.

LongPathsEnabled is not needed. Explorer does not support it anyway for compatibility reasons.

**Comment by bashenk** [comment]
If that's the case, I'll concede that the file drag & drop scenario with 8dot3 disabled could be considered an input problem. Although, to me it's a bit weird when they all appear to show up when dropping in the folder—only to end up failing to play for the ones over the path limit. Is there a compelling reason for not having a countermeasure for either situation?

Also, you say the long path works for you, but what about a situation with 8dot3 creation enabled but where there are too many folders, thus rendering the 8dot3 workaround ineffective?
E.g.
```cmd
C:\>fsutil 8dot3name set C: 0
Successfully ENABLED 8dot3name generation on "C:"

C:\>mkdir C:\testing\Lorem\ipsum\dolor\sit\amet\consectetur\adipiscing\elit\sed\do\eiusmod\tempor\incididunt\ut\labore\et\dolore\magna\aliqua\Ut\enim\ad\minim\veniam\quis\nostrud\exercitation\ullamco\laboris\nisi\ut\aliquip\ex\ea\commodo\consequat\Duis\aute\irure\dolor\in\reprehenderit\in\voluptate\velit\esse\cillum\dolore\eu\fugiat\nulla\pariatur\Excepteur\sint\occaecat\cupidatat\non\proident\sunt\in\culpa\qui\officia\deserunt\mollit\anim\id\est\laborum

C:\>copy C:\testing\TestVideo.mkv C:\testing\Lorem\ipsum\dolor\sit\amet\consectetur\adipiscing\elit\sed\do\eiusmod\tempor\incididunt\ut\labore\et\dolore\magna\aliqua\Ut\enim\ad\minim\veniam\quis\nostrud\exercitation\ullamco\laboris\nisi\ut\aliquip\ex\ea\commodo\consequat\Duis\aute\irure\dolor\in\reprehenderit\in\voluptate\velit\esse\cillum\dolore\eu\fugiat\nulla\pariatur\Excepteur\sint\occaecat\cupidatat\non\proident\sunt\in\culpa\qui\officia\deserunt\mollit\anim\id\est\laborum\

C:\>dir /X C:\testing\Lorem\ipsum\dolor\sit\amet\consectetur\adipiscing\elit\sed\do\eiusmod\tempor\incididunt\ut\labore\et\dolore\magna\aliqua\Ut\enim\ad\minim\veniam\quis\nostrud\exercitation\ullamco\laboris\nisi\ut\aliquip\ex\ea\commodo\consequat\Duis\aute\irure\dolor\in\reprehenderit\in\voluptate\velit\esse\cillum\dolore\eu\fugiat\nulla\pariatur\Excepteur\sint\occaecat\cupidatat\non\proident\sunt\in\culpa\qui\officia\deserunt\mollit\anim\id\est\laborum
...
 Directory of C:\testing\Lorem\ipsum\dolor\sit\amet\consectetur\adipiscing\elit\sed\do\eiusmod\tempor\incididunt\ut\labore\et\dolore\magna\aliqua\Ut\enim\ad\minim\veniam\quis\nostrud\exercitation\ullamco\laboris\nisi\ut\aliquip\ex\ea\commodo\consequat\Duis\aute\irure\dolor\in\reprehenderit\in\voluptate\velit\esse\cillum\dolore\eu\fugiat\nulla\pariatur\Excepteur\sint\occaecat\cupidatat\non\proident\sunt\in\culpa\qui\officia\deserunt\mollit\anim\id\est\laborum

07/25/2023  06:26 PM    <DIR>                       .
07/25/2023  06:21 PM    <DIR>                       ..
07/25/2023  01:54 AM       438,010,771 TESTVI~1.MKV TestVideo.mkv
```
In my case, the above file does not work with drag & drop, in the exact same way as I mentioned before. Assuming that it works for you just as well as the other one...gives me additional concerns. If so, do you have any other idea for what could be causing this for me then? Like, conflict with any other system settings or some MPC setting somewhere?

**Comment by clsid2** [comment]
```
BOOL CDropTarget::OnDrop(CWnd* pWnd, COleDataObject* pDataObject, DROPEFFECT dropEffect, CPoint point)
{
    BOOL bResult = FALSE;
    CAtlList<CString> slFiles;

    if (auto pClient = dynamic_cast<CDropClient*>(pWnd)) {
        if (pDataObject->IsDataAvailable(CF_HDROP)) {
            if (HGLOBAL hGlobal = pDataObject->GetGlobalData(CF_HDROP)) { // fails for long paths
```
It fails in a Windows API function. Adding the manifest does NOT solve the problem.

I am not spending any more time on this problem.

**Comment by bashenk** [comment]
While I may wish that something could be done about it, I can understand when such is not always feasible. Thanks for your consideration regardless.
