### ISSUE TITLE
Dark picture and brightness adjusting has no effect

### ISSUE THREAD

**Issue by Quwy** [clsid2/mpc-hc#2199]
No matter renderer type.

My config is very specific and generic recommendations are not match (inside VMWare virtual machine on Linux host with Intel integrated graphics).

Workaround:
1. Use any renderer with shaders support.
2. Extract attached file to "MPC-HC\Shaders\" directory.
3. Add this shader in pre-resize section if video is too dark.

[0-255 to 32-255.hlsl.zip](https://github.com/clsid2/mpc-hc/files/12205445/0-255.to.32-255.hlsl.zip)

Dynamic range will some narrowed but brightness becomes higher.

**Comment by clsid2** [comment]
Color adjustment settings requires support of the graphics driver for adjusting those parameters.

With EVR-CP as video renderer you can try:
Menu > View > Renderer Settings > Output range

I am not able to provide any more help. Problem is not in the player.
