### ISSUE TITLE
mp3 covers (and cd cover images) are not color managed

### ISSUE THREAD

**Issue by ValZapod** [clsid2/mpc-hc#220]
As you know AMOLED displays (in particular AMOLED TV LG C9 as the best in the market) are using non sRGB color gamut. If we are talking about HDR, then Windows automatically converts sRGB to bigger target display DCI-P3 color gamut with all primaries transform (even on Desktop). But if we have just non-HDR display (but with 125% of sRGB (different white and black point, gamma and 3 color primaries (blue, red, green))) then it still need to support ICC color conversion! Desktop is not converted as Windows does not support it (as well as Android (only Galaxy s10 supports it and you need support in apps)) and only ones are macOS and iOS that support "color managment" system wide.
Renderer Settings --> Color managment --> Enable is using perfect library https://github.com/mm2/Little-CMS

The problem is that while video itself is color managed after that, mp3 covers (and cd cover images) are not color managed.

Go to Win-R --> colorcpl.exe and assign to Display this [C34F791.zip](https://github.com/clsid2/mpc-hc/files/4032853/C34F791.zip)
 profile. Now, those apps that support color managment should change colors to 125% sRGB. So that means that if it were 255, 0, 0 in sRGB. it will be 200, 0, 0 in 125% sRGB, for example. You can use, e.g. Instant color picker http://www.youngsmarts.com/ to check colors in chrome https://rgb.to/rgb/255,0,0 or in photoshop or in windows 7 style photos viewer (windows 10 viewer does not support Color managment, ha). Try to open this album, e.g. magnet:?xt=urn:btih:6F3AB164FE2ED73B473369D076E558FEEE4A23CA

This thing is cool as VLC does not support color managment at all and Pot Player as well does not color manage cd cover images.

**Comment by clsid2** [comment]
I am not interested in this personally. So a volunteer is needed to implement this.

**Comment by adipose** [comment]
I have an experimental build for this here:

https://mega.nz/#!5Ag2UaIR!50e45pZT2k346b7JNBpDpv_0NLRQJ7W6H3L1xDrog_I

If this doesn't work, I will probably not work on it more.  But if this works, I can clean it up a bit.

**Comment by ValZapod** [comment]
@adipose Yes, it is perfect now! Bravo! Can you do so that it will redraw it immidiatelly when you enable/disable color managment? And also on pause (with video). See how it behaves in Pot player.

**Comment by ValZapod** [comment]
@adipose It is my mistake to give you such simple profile. You can use DCI P3 RGB (Gamma 2.6) 
in colorcpl.exe (choose from add menu), it will be obvious when it works and when not, because DCI is obviously enough "bigger" color space so it will bad on you 100% sRGB display...

**Comment by adipose** [comment]
"Renderer Settings --> Color managment --> Enable" is per renderer.  There is no option for ICC profiles in general or for static images.  So the interface has no way to enable/disable at the moment.

**Comment by ValZapod** [comment]
@adipose Ok, still good)) 

> will be redrawn on pause as enable/disable

Can you do this?

**Comment by adipose** [comment]
> But can you do so video will be redrawn on pause as well not only when playing?

You mean when the video is paused, the icc profile isn't used?

**Comment by ValZapod** [comment]
@adipose No, I mean when video is paused, you cannot see the difference when yiu disable icc (yiu need to press play to see it).

**Comment by adipose** [comment]
Ah, ok. It makes sense, as it won't go through the render code again.

**Comment by ValZapod** [comment]
@adipose Well, in pot player it is applied and deapplied even on pause. Which makes sense)

**Comment by adipose** [comment]
I mean it makes sense from the code point of view.  The render code is what applies the color profile.  Once it's paused, it doesn't go through it again.  Not saying that's the right choice.

**Comment by ValZapod** [comment]
@adipose Pull request?))

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/238

Here's an updated test build with the ability to update with live color profile changes.

https://mega.nz/#!oJgDnArT!wi4yP7X6MIFOge0d5QSG-STIB1tHIcZXm5NGEK7sOZQ

I also used some of my code in the DX9Renderer.  In theory it should help it load the active color profile.  From looking at it, I don't believe it should have worked on pause/play as you said, but only after restartng mpc-hc?

The API for this is terrible.  There's no notification from windows when it changes, and you have to restart the application to see the new icc profile.  However, I hacked in some code to mitigate those disappointing issues.

**Comment by ValZapod** [comment]
Will check now)

**Comment by ValZapod** [comment]
@adipose No, bad! This build broke "default" profile system, it is now always one profile, not the one you use as default in color managment colorcpl.exe. Even for video!

**Comment by clsid2** [comment]
An icc profile is not something that you change often. So I don't think we should support dynamic updates if that needs workarounds in the code. I prefer just simple code.

**Comment by ValZapod** [comment]
@clsid2 

> An icc profile is not something that you change often

With latest build you cannot change it even once. Only edid icc is supported.

> should support dynamic updates

It is already supported. (For videos.) Latest build broke it. The first is good.

**Comment by ValZapod** [comment]
@clsid2 Sorry, no, dynamic updates are not supported... My mistake. Though I do not need it really...
The only thing I want is support to turn off and on on pause... But! Really the first build is enough. @adipose No need to invent anything else. BTW, I read in chromium docs that Windows 10 already have 

> The API for this is terrible. There's no notification from windows when it changes

better API... Though not sure)) But chromium is not immediately switching profiles, so... And yes, youtube and other players (<video> and flash) are color managed in chromium/chrome.

**Comment by adipose** [comment]
@ValZapod can you show me your colorcpl screenshots?  It is working for me on both system default and use default.

**Comment by ValZapod** [comment]
@adipose Here you are 
![image](https://user-images.githubusercontent.com/31514790/72668840-f2d8d700-3a3b-11ea-8d4f-329ec9c24d68.png)

**Comment by adipose** [comment]
> 
> 
> An icc profile is not something that you change often. So I don't think we should support dynamic updates if that needs workarounds in the code. I prefer just simple code.

If you think the code is an issue I will take it out.  Basically what it does is watch the affected registry keys in the user/system profile (for this it needs a thread with an event watcher).  This generates the main thread event letting it know ICC profile has changed.

Second part is simple enough--it looks at the registry value and uses that instead of the one supplied by GetICMProfile, since that is cached on app start.

Code could be eliminated or enabled only with an advanced option, as well.

**Comment by ValZapod** [comment]
Do you still use GetICMProfile in the beginning?

**Comment by adipose** [comment]
Yes--I see the bug with your issue.  I was checking only the default device profile, not per monitor ones.

**Comment by adipose** [comment]
I have reverted all the realtime changes, so it just does a simple apply of the color profile that was loaded with the application.

**Comment by ValZapod** [comment]
@adipose So, it is like with 1st build, yep? Nice))

**Comment by clsid2** [comment]
Patch has been applied.
