### ISSUE TITLE
Skip forward not skipping to next file

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2200]
Other files with chapters have no problem.

But with this file the player doesn't play the next file. At the end of the chapters if I click on next it again plays the same file from beginning, chapter 1.
https://drive.google.com/file/d/1lAo_1xWyF50y8zLr3MLQrMHtnoa25yTn/view?usp=sharing

This happens when Repeat is checked.
![Screenshot (157)](https://github.com/clsid2/mpc-hc/assets/98865389/63da5232-585f-4d7f-92e1-3e58896e92b0)

**Comment by clsid2** [comment]
It is working here.

**Comment by bibsp** [comment]
> It is working here.


https://github.com/clsid2/mpc-hc/assets/98865389/4c5d960e-04c5-45ce-b182-ae9c94db4cd4

I'm on version 116. I don't know if stable version is okay or not.

**Comment by clsid2** [comment]
You are playing a single file, not a playlist. So repeat is going to repeat the same file. If you want to jump to next file in folder you need to disable repeat.

**Comment by bibsp** [comment]
Then other files should also repeat. But with other files the player goes to next file with same setting.
And even though I disable repeat, then player gives black screen. It doesn't go to the next file.

Can you see the recording? Mpc hc is not playing the last chapter. Mpc be is playing last chapter.

**Comment by bibsp** [comment]
> You are playing a single file, not a playlist. So repeat is going to repeat the same file. If you want to jump to next file in folder you need to disable repeat.

No, this is not how mpc hc or be reacts to other files with chapter. Test with my settings shown in above screenshot.
See with same settings but differnt file.

https://github.com/clsid2/mpc-hc/assets/98865389/28a01453-ae70-4198-96ca-ed827e63efd7

**Comment by clsid2** [comment]
Press Ctrl+PageDown to jump to next file and ignore all chapters.

Or disable repeat forever.

But regardless of that it WORKS FINE FOR ME even with repeat enabled. The last chapter is very close to end of file. So you must be too slow with pressing next at that moment, causing the file to reach end and triggering repeat. User error.
