### ISSUE TITLE
Extension to allow use of Clipboard Inserter for current displayed subtitle line

### ISSUE THREAD

**Issue by SecretX33** [clsid2/mpc-hc#2201]
# Main point

Hi, I would like to develop an MPC-HC extension allowing users to use Clipboard Inserter by automatically copying all displayed subtitles lines to the PC clipboard. In summary, **I need the current subtitle line to somehow appear in the system clipboard**.

## Why I am asking here?
I don't know much of C++, so digging into the code is still very hard for me, so I thought I was better off just asking here instead.

## What I've tried already

I know how to read another process memory to get data, but I don't know how to find the text in memory, I could not find the current displayed subtitle line in the memory, or in the times I did find it, the line was somehow only partially there. 

## What I need to know
I would like to know from you guys who know the codebase well, is this even possible? Does MPC-HC store the current subtitle lines somewhere in memory? If so, what encoding does the program use to store the characters? And if not, how could I do that?

## More thoughts

I also thought of forking MPC-HC to add this functionality, but I know nothing of C++ so this would be very hard for me to do.  I could do that by:

- (Supposedly) Reading the program memory directly and fetching the current line every X ms via a pointer;
- Extend the MPC-HC codebase to add the auto "copy-to-clipboard the current subtitle line" functionality to the program.

Ofc I could also do more than that if I have more information, such as:

- The current opened file path;
- The timings of the current subtitle line.

The idea is to later mine the subtitle words through Clipboard Inserter by using a browser extension. Having the extra information allow for more functionality to exist, but having only the Clipboard Inserter would be already really good.

**Comment by clsid2** [comment]
I am not spending any of my time on this. You obviously haven't even tried to look at the code. And if you don't know a bit of C++ then you are incapable of doing this anyway.
