### ISSUE TITLE
Can't choose showing subs when taking screenshots

### ISSUE THREAD

**Issue by MurasakiZerozaki** [clsid2/mpc-hc#2202]
Maybe I'm blind or stupid, but, early, when you take screenshot with Alt + I there is an option to show or not show subtitles. I've installed the last 2.0.0 version, and the times before I don't have this feature, it was only a year ago maybe. Is it cut out?

**Comment by clsid2** [comment]
It still exists. It still works,

So you must be using either madvr, which has its own options for screenshots. Or you are not using the internal subtitle renderer.

**Comment by MurasakiZerozaki** [comment]
> It still exists. It still works,
> 
> So you must be using either madvr, which has its own options for screenshots. Or you are not using the internal subtitle renderer.

I use madvr and internal sub. r. Madvr for HDR functions. Is there any solution or I should ask madvr's authors?

**Comment by clsid2** [comment]
There are screenshot settings in madvr options. There you can find subtitle option.

**Comment by MurasakiZerozaki** [comment]
There only an option "have or not", but not at taking shot. It is what it is or should search more?
![image](https://github.com/clsid2/mpc-hc/assets/115612114/60e887b2-f54a-47e8-ae5b-e665ae3636d4)

**Comment by clsid2** [comment]
Yes, that is the only option.

The option in MPC-HC that is "per screenshot" is only available with other renderers.

**Comment by MurasakiZerozaki** [comment]
Ok, thanks for help.
