### ISSUE TITLE
Subtitles search always considers all languages

### ISSUE THREAD

**Issue by pedr0rp** [clsid2/mpc-hc#2207]
If I remember correctly in other/older versions of MPC if you had an account on OpenSubtitles with preferred languages, when you setup the account on MPC, it only searched on those selected languages. In my case I have an account setup with English, Japanese and Brazilian Portuguese but even after setting up the account, all languages are still being listed and used to search for subtitles. 

I don't know if there's something in the Open Subtitle's API that prevents this behavior, but, in any case, I think that at least there should be an option to insert/edit the languages parameters manually (considering that they are used to send requests to the subtitles provider). In the mean time, some subtitles searches eventually returns a enormous list has a result with a lot of itens irrelevant to the user. 

![image](https://github.com/clsid2/mpc-hc/assets/14652653/d9299ce2-9db6-4e52-b703-5f882b81cf56)

![image](https://github.com/clsid2/mpc-hc/assets/14652653/08de796b-61ba-4bdd-b840-4dff0883e835)

![image](https://github.com/clsid2/mpc-hc/assets/14652653/a24e83ca-060e-4fa9-b753-27236ecd487a)

**Comment by clsid2** [comment]
There is literally a language option in your second screenshot.

**Comment by bw4518** [comment]
"in order of preference" might be a little misleading, I overlooked it as a language filtering option at first too, just saying..
