### ISSUE TITLE
The player stops after reaching the last item in the folder

### ISSUE THREAD

**Issue by mrrezaie** [clsid2/mpc-hc#2209]
Hi, thanks for keep developing MPC.

In the following configuration, the player stops after reaching the last item in the folder. It would be great if the player plays the beginning item in the folder after playback.

![image](https://github.com/clsid2/mpc-hc/assets/38867713/02b63f1c-b6b4-476d-82de-c33b22bcfefe)

Thank you.

**Comment by clsid2** [comment]
Options > Advanced > LoopFolderOnPlayNextFile

**Comment by mrrezaie** [comment]
Great
