### ISSUE TITLE
OSD problem with Intel graphics card

### ISSUE THREAD

**Issue by YMahmoudnia** [clsid2/mpc-hc#2214]
Hello,

I used MPC-HC v1.9.13.0, and I checked the m_OSD.CanShowMessage() function. However, the OSD was not able to show.

Is the OSD feature compatible with Intel(R) HD 520 - 620 or Intel(R) UHD graphics, or is it not related to the graphics card?

Thanks.

**Comment by clsid2** [comment]
That is an old version.

OSD should work fine that GPU. You need to select a compatible video renderer.
