### ISSUE TITLE
Request support for .ttc files when loading external fonts

### ISSUE THREAD

**Issue by MononeV** [clsid2/mpc-hc#2215]
The auto-loading font feature is very usful. However, it skips the .ttc font files in the Fonts folder. As a result, I have to load the fonts manually everytime when there are .ttc files.

**Comment by adipose** [comment]
Do you have an example file to demonstrate this issue?

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2236

I think this should solve the issue.

**Comment by MononeV** [comment]
> #2236
> 
> I think this should solve the issue.

That is good to hear. Thank you very much! I presume it will come with the next release?
