### ISSUE TITLE
"Geometric adjustment" of subtitles [Question]

### ISSUE THREAD

**Issue by SmutnyStefan** [clsid2/mpc-hc#2218]
Many years ago on the Polish internet there was a player called SubEdit (now long defunct) which was fairly popular locally. It had a peculiar, but great feature called (in Polish) something like "Geometric adjustment of subtitles" 
I don't know how to name it properly since I am a non technical person. I look for it in every player I can since then, but surprisingly no one seems interested in implementing it. I don't understand why, since it worked pretty well.
Basically one had to select the very first and last line of dialogue and point it to the actual audio timestamps and then the subtitles "adjusted themselves" in line with the rest of the audio. I am unable to tell how it worked I only know that it worked. It would be really great to have it, since most subtitles downloaded from online sources are misaligned with the audio in one way or the other, and adjusting it by some fixed amount of time usually does not work.
Could you consider implementing it?

**Comment by clsid2** [comment]
There are websites where you can modify subtitle timestamps like that. Or subtitle editing tools. Google for it.

I do not add any new functionality.
