### ISSUE TITLE
MPC never finds subtitles from OpenSubtitles.org

### ISSUE THREAD

**Issue by thericle** [clsid2/mpc-hc#2220]
I have tried:
-resetting OpenSubtitles' credentials inside MPC
-creating a new OpenSubtitles account
-resetting my IP address
-completely uninstalling and reinstalling MPC

Unfortunately, no luck.
I have tried a lot of movies but no subtitles from OpenSubtitles.org appear.
It was working 1-2 months ago, and maybe even more recently.
Podnapisi works fine but it isn't very good at automatically recognizing the movie title.
I wonder if it's related to the API changes mentioned here: https://github.com/clsid2/mpc-hc/issues/1876

**Comment by clsid2** [comment]
opensubtitles.org website is offline for maintenance

**Comment by thericle** [comment]
I believe the site was offline for just a few hours. Correct me if I'm wrong.
The site is up now, but unfortunately, it still doesn't work.
I've tried it with a fresh installation on another device where the only common link, I believe, was me, the user.
So, unless I'm doing something terribly wrong, it doesn't seem to work.

**Comment by clsid2** [comment]
I just tested and it works again here.

**Comment by Fern99** [comment]
![Screenshot_2024_05_03-1](https://github.com/clsid2/mpc-hc/assets/40309155/b7a12fbc-a03a-4428-bc85-7eff94960281)

It says 'opensubtitles.com' in mine as attached, not 'OpenSubtitles.org.
And yes, it is not working.
