### ISSUE TITLE
YouTube vp9 always playing 144p

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2222]
Youtube vp9 streams are misbehaving. Player always opens 144p. Can't play any other resolution.
YDL video format 3,4,5,6 have this issue.
h264 and av1 are okay.
I'm on latest daily build of yt-dlp. Yt-dlp can download all vp9 streams. So it's not Youtube's server issue or yt-dlp issue.

**Comment by clsid2** [comment]
Fixed.

As workaround use format 0 to get VP9.

**Comment by bibsp** [comment]
Okay thanks.
But I would like to inform you that, vp9 seek works on mpcbe. You need to try latest development build of mpcbe.
