### ISSUE TITLE
Consider supporting logical cropping via Matroska header

### ISSUE THREAD

**Issue by Marat-Tanalin** [clsid2/mpc-hc#2224]
Matroska (MKV) container format supports a header that specifies amount of pixels that should be cropped-out. This would be useful for setting proper cropping for videos that contain **black bars** hard-encoded together with true video data, with **no need for re-encoding** the video that is both time-consuming and leading to extra quality-loss.

In MKVToolNix (official Matroska muxing tool), the header is specified via “Properties” → “Video properties” → “Cropping” in properties panel of the video track.

<details>
<summary>View MKVToolNix <strong>screenshot</strong></summary>

![mkvtoolnix-crop](https://github.com/clsid2/mpc-hc/assets/1833563/42f86cf5-3b91-4fa9-bc34-163802d80629)
</details>

MPC-HC apparently does not currently take the cropping header into account (tested with the latest build 2.0.0.124). Thanks.

**Comment by clsid2** [comment]
Must be done in LAV Filters.

**Comment by Marat-Tanalin** [comment]
Is that supposed to mean that LAV Filters _already_ support the feature, or that you believe requesting the feature is just better suitable for LAV Filters? Thanks.

**Comment by clsid2** [comment]
LAV Filters must implement it.
