### ISSUE TITLE
Question: Title info in web interface

### ISSUE THREAD

**Issue by Velkas** [clsid2/mpc-hc#2226]
I'm currently writing some scripts to capture some data from MPC-HC while it's running.

The main info I want to get is the title of a video (not the video file/url). Right now the best I have figured out is enabling the web interface and making a webrequest from the info url (info.html).

However, since my current use case is to open a youtube playlist (yt-dlp/ffmpeg) it only provides the url of the current track, even though the UI shows the title.

Is there any way to get the current title info from either web interface or some built in API that I haven't discovered yet?

**Comment by clsid2** [comment]
https://github.com/clsid2/mpc-hc/blob/develop/src/mpc-hc/MpcApi.h

I don't have time and interest to provide any further help.

I am not adding any new functionality.
