### ISSUE TITLE
Audio and video desync after pausing a Youtube video

### ISSUE THREAD

**Issue by Yoksven** [clsid2/mpc-hc#2228]
It started happening a month or so ago. Desync doesn't happen every time, but quite often. It usually takes a a minute after unpausing to start desyncing. Video usually gets several seconds ahead of the audio and it can be forced to sync by going back a couple of seconds in the video, but sometimes it takes a couple of tries to get it to sync. There is also no noticable moment of when it desyncs. I just sort of notice "oh, it's desynced" without seeing or hearing any anomalies.

I'm using the latest mpc-hc build and the latest build of yt-dlp. Enhanced video renderer (custom presenter) and MPC Audio Renderer. I usually watch at 720p with YDLVidoFormat set to "1", which gives a stream where audio and video come together as one file and not as two separate streams, which, up until this bug, lead to the video behaving more reliably then separate streams. So far I haven't been able to replicate the desync on other YDLVideoFormat settings, but I've only tried a couple of videos, so can't say for sure that it's isolated to the "1" setting.

**Comment by Yoksven** [comment]
I've been testing YDLVideoFormat "7" and it seems that desync issue isn't present there, but I'm running into a different issue entirely. Some videos will just not playback correctly from anything other then h264 streams. They will start as normal and if I don't touch anything they will play as normal, but if I skip anywhere in the video or change the speed or reload the video not from the starting position, it will stop playing the video and only the audio will play. For some reason all those problematic videos are about cameras. I'm not sure what's exactly different about them in the technical aspects, but here they are:
https://www.youtube.com/watch?v=zFXEPKq3CMk
https://www.youtube.com/watch?v=0535kWBSJ0I
https://www.youtube.com/watch?v=FuSwyI8vEcE
https://www.youtube.com/watch?v=3MxxYLmRNl8

If I download them and play from the local storage they playback completely normally. Also this issue affects a relatively small portion of the videos that I've encountered, but it's annoying non the less.

**Comment by clsid2** [comment]
Use latest development build, because I suspect you aren't actually using latest one. If that does not help, then you are out of luck. The problem is not in the player, so I can not fix it. A future update of the internal codecs will have to solve it.
