### ISSUE TITLE
Audio renderer device configuration are not working(?)

### ISSUE THREAD

**Issue by FX8350** [clsid2/mpc-hc#223]
Options > Internal Filters > Audio Renderer >Device
I changed that setting, but the sound always output from the "default device" of Windows.

Windows 10 1903 64bit
Realtek High Definition Audio (M/B)
Sound BlasterX G1 (USB)
NVIDIA High Definition Audio (HDMI,LCD Speaker)

**Comment by clsid2** [comment]
That setting only has effect if you are using the internal audio renderer:
Options > Playback > Output > Audio Renderer

**Comment by FX8350** [comment]
Thanks!
