### ISSUE TITLE
D3D Fullscreen broken with PlayList on Windows 10

### ISSUE THREAD

**Issue by User1X1** [clsid2/mpc-hc#2230]
MPC-HC
Version:            2.0.0 (973b644a3)
Compiler:           MSVC v19.29.30147
Build date:         Jan 11 2023

When I have activated

MPC-HC >>> View >>> Options >>> Playback >>> Output >>> **D3D Fullscreen**

and a PlayList is running, at the moment it changes to the next video, the player is minimized to a window and does not show a video image.
This happens in updated Windows 10, I use Nvidia driver 537.13 (latest).
But it didn't happen with updated Windows 7 (with latest Nvidia 474.44).

It's a shame to lose this feature, because videos play more smoothly with frame rate interpolation.

**Comment by clsid2** [comment]
Exclusive fullscreen has little benefit on Window 10 compared to Windows 7. So just disable it.

Or use this renderer instead:
https://github.com/Aleksoid1978/VideoRenderer/releases

**Comment by User1X1** [comment]
> Exclusive fullscreen has little benefit on Window 10 compared to Windows 7. So just disable it.
> 
> Or use this renderer instead: https://github.com/Aleksoid1978/VideoRenderer/releases

I didn't know "MPC Video Renderer", it is definitely much better. Thank you so much.
