### ISSUE TITLE
Does not support VVC decoding.

### ISSUE THREAD

**Issue by Hackjjang** [clsid2/mpc-hc#2231]
![image](https://github.com/clsid2/mpc-hc/assets/120134269/cb4d6ea2-2325-4493-bc7a-c8505aa6a8b2)

I'd like you to provide a way to play it back.

**Comment by v0lt** [comment]
MPC-HC uses LAV Video Decoder for video decoding.
LAV Video Decoder uses FFmpeg to decode videos.
There is no VVC support in the FFmpeg master branch yet.

**Comment by Hackjjang** [comment]
https://github.com/MartinEesmaa/VVCEasy/tree/master/LAVFilter

The MPC-HC has LAV Filters that support VVC.

**Comment by clsid2** [comment]
VVC is still an irrelevant format at this point in time. Once it starts being used more commonly it will almost certainly get added to official LAVFilters.
