### ISSUE TITLE
MPC-HC caches all my output devices, even though they're disconnected or not available

### ISSUE THREAD

**Issue by StormProductionsMusic** [clsid2/mpc-hc#2237]
Hi,

I have connected a lot of Bluetooth speakers and headphones over the past years since I'm using MPC-hC, and now I noticed that in settings, it shows all the output devices I have ever connected, even though they're not available anymore due to them being disconnected. 

Is there any way I could prevent it from doing that, and make it show only the current available devices instead of showing them all? 

Thanks!

**Comment by clsid2** [comment]
It is Windows that is caching them.

Codec Tweak Tool > Fixes > Clear audio device filter cache
