### ISSUE TITLE
CMD_NOWPLAYING, CMD_LISTSUBTITLETRACKS and CMD_LISTAUDIOTRACKS beeing send continously

### ISSUE THREAD

**Issue by FoLLgoTT** [clsid2/mpc-hc#2239]
The three status information CMD_NOWPLAYING, CMD_LISTSUBTITLETRACKS and CMD_LISTAUDIOTRACKS are beeing send continously by timer to the API (CMainFrame::SendNowPlayingToApi()).

I think this is not right, because there are Get commands for the three status information (e.g. CMD_GETNOWPLAYING). And these static information usually don't change during playback.

What is the reason for that? Can that be removed?

**Comment by clsid2** [comment]
Data such as title can change during playback in case of for example a radio stream.

I don't really care about this API at all and I am not changing anything.
