### ISSUE TITLE
[Bug] Missing MediaInfo tab in Properties (v2.0.0.138)

### ISSUE THREAD

**Issue by ryehamstrawberry** [clsid2/mpc-hc#2242]
I'm unsure if this is a unique issue to me me or if others are also no longer able to access the MediaInfo tab via Properties dialog (Shift+F10) using the newest v2.0.0.138 x64 build.

I can confirm that I am able to access the MediaInfo tab by downgrading to v2.0.0.96 x64.

**Comment by v0lt** [comment]
I don't confirm.
MPC-HC x64 2.0.0.138, Windows 10 22H2.

**Comment by ryehamstrawberry** [comment]
Since @v0lt reported not encountering this problem, I decided to nuke all traces of MPC-HC and setup a fresh instance of v2.0.0.138 x64, which seemed to resolve the issue.

Despite being easy to resolve, I'm still going to leave this thread open since something is still causing this issue to occur.

**Comment by clsid2** [comment]
You have old version of the ZIP that contained x86 mediainfo dll
