### ISSUE TITLE
[request] show time index as total seconds and frames in OSD, statistics or seek bar

### ISSUE THREAD

**Issue by makedir** [clsid2/mpc-hc#2243]
It would be nice and helpful, if there was a way to show the current position as total seconds and also total frames in the player somewhere. for example put it into the OSD, statistics frame or seek bar, that there is a line which shows the current frame and time index position as total seconds and frames into the video. and/or also show this in the seek bar maybe optional so you can enable it in the options.

For example, if you are 300 seconds into the video and pause, it shows total 300 seconds and also total frame count for the current position.

This would be helpful to get quickly information to extract parts from the video for example through ffmpeg.

It would also be nice to configure a hotkey which copies the current time index as total seconds and also another to copy total frame index into the clipboard.

**Comment by clsid2** [comment]
I am not adding such functionality. 
FFmpeg supports hh:mm:ss notation.

You can press Ctrl+G to get current time and framenumber. The frame is a calculated value.
