### ISSUE TITLE
Inconsistent MPC Audio Renderer behavior when speeding up or slowing down the footage

### ISSUE THREAD

**Issue by Yoksven** [clsid2/mpc-hc#2246]
When audio is AAC, MPC Audio Renderer compensates for the change of speed and the tone doesn't change. But if an audio is OPUS, FLAC or MP3, then sound waves are just squished or stretched without any compensation, changing the tone to be higher or lower. Also, adding to the inconsistency, I have some videos with an MP3 audio where the compensation does happen and the tone doesn't change.

And while SaneAR Audio Renderer always compensates and can be a work around, the sped up footage has weird stutters when it's used with anything other then Synced Renderer for the video output. So, it would be nice if MPC Audio Renderer could also always compensate, regardless of the audio type.

**Comment by clsid2** [comment]
Fixed

**Comment by Yoksven** [comment]
Thanks
