### ISSUE TITLE
Problem compiling - error C2039: 'atomic_bool': is not a member of 'std'

### ISSUE THREAD

**Issue by rjappleton** [clsid2/mpc-hc#2247]
I've just downloaded the current version, then followed the build instructions, and tried a first compile using 64 bit "Release Lite", but compilation quickly fails with

26>PixelShaderCompiler.cpp
29>bs2b.vcxproj -> D:\MPC-HC\mpc-hc\bin\lib\Release_x64\bs2b.lib
26>d:\mpc-hc\mpc-hc\src\filters\renderer\videorenderers\evrallocatorpresenter.h(186): **error C2039: 'atomic_bool': is not a member of 'std'** (compiling source file OuterEVR.cpp)
26>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\condition_variable(22): note: see declaration of 'std' (compiling source file OuterEVR.cpp)
26>d:\mpc-hc\mpc-hc\src\filters\renderer\videorenderers\evrallocatorpresenter.h(186): error C3646: 'm_bPendingRenegotiate': unknown override specifier (compiling source file OuterEVR.cpp)
26>d:\mpc-hc\mpc-hc\src\filters\renderer\videorenderers\evrallocatorpresenter.h(186): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file OuterEVR.cpp)

I'm using Visual Studio 2017 community edition on Windows 11. The mpc properties include these settings:

Windows SDK version: 8.1
Platform Toolset: Visual Studio 2017 (v141)
C++ Language Standard: ISO c__17 Standard (/std:c++17)

I'm pretty sure this must be a simple configuration problem - but any suggestions how to fix this?

**Comment by clsid2** [comment]
Use VS2019

**Comment by rjappleton** [comment]
Thanks. The Compilation.md file still says "Visual Studio 2019 (or 2017)", so might need updating to remove mention of 2017.
