### ISSUE TITLE
Middle click again to re-enable video previews

### ISSUE THREAD

**Issue by bottleblue** [clsid2/mpc-hc#2249]
I recently found out that middle clicking the seekbar will disable video previews. Not sure how useful that feature is but good to have options I guess. After disabling I middle clicked again thinking it would re-enable previews but it didn't. When I go into options the "Show Preview on seekbar" is still checked. Unchecking/rechecking doesn't work. There doesn't seem to be anyway to re-enable previews other than restarting MPC. 

Why not allow middle click again to re-enable them? Seems like the obvious thing to do.

**Comment by clsid2** [comment]
Update to latest development build.

Toggling the setting itself requires a player restart because it need to create an extra window and filter graph.

**Comment by bottleblue** [comment]
Thx it worked
