### ISSUE TITLE
Play Youtube videos without audio

### ISSUE THREAD

**Issue by hellishvictor** [clsid2/mpc-hc#2250]
Hi, trying to play any video from youtube with [MPC-HC](https://github.com/clsid2/mpc-hc/releases/download/2.0.0/MPC-HC.2.0.0.x64.exe), but it just load the video but without audio.
![sshot-1](https://github.com/clsid2/mpc-hc/assets/34694956/2cbd2cce-06ef-4d09-8ae6-cc11cedff88a)

I've updated to the latest [yt-dlp](https://github.com/yt-dlp/yt-dlp/releases/download/2023.10.07/yt-dlp.exe) but its still the same. The thing is that if I select "Save a copy..." the video has audio in there. Anything than that, it works great.
Cheers.

**Comment by clsid2** [comment]
Works fine for me.

Update to latest development build and reset settings.
