### ISSUE TITLE
Output levels differ depending on selected renderer

### ISSUE THREAD

**Issue by Wille-Helm** [clsid2/mpc-hc#2251]
Hello,
the output/black level is unexpectedly different depending on selected renderer.
Some renderers (including the default one) are converting to "TV levels" (too bright).

### TV (16-235)
- **Enhanced Video Renderer (custom presenter)**
- **Sync Renderer**

![TV](https://github.com/clsid2/mpc-hc/assets/22815902/1f26d1f1-04ce-4779-9122-1ae8d756a3ef)

### PC (0-255)
- **Enhanced Video Renderer**
- **Video Mixing Renderer 7/9**
- **Old Video Renderer** _at default "PC (0-255)"_
- **madVR** _at default "PC levels"_

![PC](https://github.com/clsid2/mpc-hc/assets/22815902/e1f5acaf-9593-4e60-afdb-b7b9885f6547)

Tested on several PCs, all Windows 10, Radeon RX (590 / 5700 XT / 6800 XT), latest MPC at default.
Selecting Video/Hardware decoder "None" instead makes no difference.
Changing "RGB Output levels" in _Internal Filters > Video decoder_ only makes a difference when using the Old Video Renderer.

P.S.:
However it would be useful to be able to change the black levels within MPC because there are a lot of incorrectly mastered Blu-rays on the market with wrong (too dark) black levels.

**Comment by clsid2** [comment]
You should NEVER touch the RGB output level setting in the decoder. That is only used when converting to RGB, which under normal circumstances should never happen.

The color range issue is an AMD bug.

There are shaders to fix wrong ranges.

**Comment by clsid2** [comment]
Try this test build:
https://www.sendspace.com/file/kjsyqb

It has a potential workaround in EVR-CP. So test only that renderer.

**Comment by Wille-Helm** [comment]
Normally I wouldn't change the RGB Output setting there, it was for testing purposes only. And it does not work with the default EVR(custom) anyway.

However, if it does not convert to RGB, then why isn't it "Untouched (as input)" by default?
I thought I knew that it definetly converts to RGB at some point because virtually everything after the video codec works in the RGB range (Windows, display driver, monitor).

P.S.: Download impossible, it's the Windows Defender false alarm again... 😞

**Comment by clsid2** [comment]
RGB is full range by definition. The option does not have effect because it isn't outputting in RGB!
FORGET about that option and never touch it again.

You can temporarily disable defender in its options.

**Comment by Wille-Helm** [comment]
Sorry, no change in output levels with the new build.
I have done a reset to defaults again.

Has this something to do with the Radeon bug you mentioned?
It shows inactive decoder and no HW acc., although there is activity in Task Manager (Video Codec 0):

![radeonbug](https://github.com/clsid2/mpc-hc/assets/22815902/288f4723-53cd-402f-a531-16bd8cba2911)

**Comment by clsid2** [comment]
It says inactive because you are opening an inactive instance.
For active one:
Player menu >Play > Filters

If levels are still wrong, then I can not help you. You could try if disabling hardware decoding makes a difference. AMD bug is related to DXVA video processing.

**Comment by Wille-Helm** [comment]
A side note in my first post was that I have already disabled hardware decoding - which is my personal preference by the way - but has no impact. I would think that DXVA is not in use this way.

Then again, isn't DXVA used by the other renderers too? Also madVR set to DXVA follows strictly its PC levels setting, regardless of the used decoder.

Maybe I find a nVidia card to check this out.

Thanks for trying anyway. 💪

**Comment by clsid2** [comment]
DXVA hardware decoding and DXVA video processing (colorspace handling, etc.) are separate things.

Madvr is a fully custom renderer and its behavior can't be compared to EVR based renderers.

[MPC VR](https://github.com/Aleksoid1978/VideoRenderer/releases) is my recommend renderer for MPC-HC.

**Comment by BreakPoints** [comment]
Just wanted to add that I also have this issue on my AMD laptop and software decoding still outputs the incorrect levels with the EVR Custom Presenter.

**Comment by clsid2** [comment]
AMD needs to fix it.

NVIDIA driver has setting to adjust the level range. Maybe AMD has too.

I don't have AMD, so I can not help. Can't be fixed in EVR-CP.
