### ISSUE TITLE
Subtitles disabled on any additional MPC-HC instance

### ISSUE THREAD

**Issue by n-99** [clsid2/mpc-hc#2254]
Whenever I open more than one MPC-HC, all but the first one disable the subtitle track. This problem has existed for at least a couple of months.

Version used:
```
MPC-HC (Nightly, 64-bit)
------------------------

Build information:
    Version:            2.0.0.138 (2a8f4208f)
    Compiler:           MSVC v19.29.30151
    Build date:         Sep 17 2023

LAV Filters:
    LAV Splitter:       0.77.2.3
    LAV Video:          0.77.2.3
    LAV Audio:          0.77.2.3
    FFmpeg compiler:    MinGW-w64 GCC 12.2.0

Operating system:
    Name:               Windows 7 (Service Pack 1)
    Version:            6.1.7601 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
    GPU:                Intel(R) HD Graphics 4600 (driver version: 10.18.14.5180)
```

**Comment by clsid2** [comment]
Working fine for me.

If a track is available but not selected, then your settings may be wrong.

**Comment by n-99** [comment]
I think I found the problem (need to test some further things out myself, though):
The program Subtitle Edit uses MPC-HC and disables the subs, while showing them. So the settings of MPC-HC got changed by another application.
