### ISSUE TITLE
Not really an issure, just a question

### ISSUE THREAD

**Issue by Yoksven** [clsid2/mpc-hc#2256]
Sorry to bother. I just don't know if I could ask a question in other way, other then by opening an issue. But my question is simply - when is the new stable release is approximately happening? The reason is, I have some issues that are fixed in the dev build, but I need an x86 version to get some old plugins to work, and dev builds are all x64. So, I know that the stable release with an x86 version will happen at some point, and I'm not trying to rush or ask to release it faster. I'm just want to know how long I'll be waiting. Before 2.0.0 new stable releases were pretty frequent, but it seems like things are different now.

**Comment by clsid2** [comment]
Maybe later this month.

I will make a x86 dev build.

**Comment by Yoksven** [comment]
Thanks.
