### ISSUE TITLE
Subtiles shortcut doesnt work with Enhanced Video Renderer

### ISSUE THREAD

**Issue by gh-log** [clsid2/mpc-hc#2257]
Works with MPC Video Renderer.

![Screenshot 2023-10-18 214644](https://github.com/clsid2/mpc-hc/assets/16019542/666dadf1-c468-4b17-81c2-4023e6be7c31)

image if for Enhanced Video Renderer but subtitles dont show and shortcut doesnt work.

**Comment by clsid2** [comment]
The internal subtitle renderer does not work with standard "EVR". Only with "EVR Custom Presenter".
