### ISSUE TITLE
Open URL Youtube video (2k resolution) freezes after scrubbing

### ISSUE THREAD

**Issue by Shadowdevo** [clsid2/mpc-hc#2258]
Discovered that a similar bug that was previously fixed is still a problem a higher resolutions. Pausing and unpausing **doesn't** trigger the screen to freeze, but any scrubbing, both forwards or backwards, will cause the video to freeze and it cannot be unfrozen. I have tried scrubbing through videos that are 1080p or lower and they do not freeze.

I have a 2k monitor, so I think to reproduce this problem you would need one as well. All you do is load up a video from youtube that has a 2k resolution option (here's one for example: https://www.youtube.com/watch?v=_XdD-TQseU4) and then once the video begins to play, click on a different time on the timeline or use the arrow keys and it will freeze. 

I'm also running windows 10 with up to date nvidia drivers and the most recent yt-dlp executable as well as ffmpeg/ffplay/ffprobe. If additional information is needed let me know! I'm guessing this is going to be related to whatever was causing the freezing before, but I don't know enough to try and fix it myself.

**Comment by Shadowdevo** [comment]
Forgot to mention that once it freezes the audio will still play properly at whatever time you skip to. It's only the video that freezes.

**Comment by bibsp** [comment]
Everything is fast, **No freeze**. Even 4k has no problem. The only thing I don't have is 2k monitor.

**Comment by clsid2** [comment]
Playback works fine here.

Use latest development build of MPC-HC and update yt-dlp.exe
