### ISSUE TITLE
hotkey for subtitles on/off doesn't work

### ISSUE THREAD

**Issue by alidan** [clsid2/mpc-hc#2259]
I have changed it from default hotkeys (I think default) to several other keys that aren't used in case there is interference, but none of them work. 

I can just cycle till no subs, but if its possible to make the toggle work that's better.

**Comment by clsid2** [comment]
Works fine for me.

It toggles this option:
Menu > Play > Subtitle Track > Enable

Maybe you are not using the internal subtitle renderer.
