### ISSUE TITLE
subtitles selection being ignored

### ISSUE THREAD

**Issue by ecktt** [clsid2/mpc-hc#2261]
Subtitles auto selection stopped working. Normally, I would play the first file in a series, select the appropriate subtitles, goto to Options/Playback/Subtitles and enter the appropriate subtitles numerical position. Every file after would continue to use the subtitles associated with that position. For example, if the subtitles appear like this:

English (Signs-Songs)
English (Full)
No subtitles

I would enter 2 for English (Full) and all other files would use position 2 subtitles. Now everything defaults to No subtitles. I've uninstalled, deleted the MPC-HC folder and re-installed. Any suggestions?

**Comment by clsid2** [comment]
Options > Internal Filters > Splitter

Either (1) to use MPC settings:
Subtitle selection mode = Default
Subtitles = empty

or, (2) to use splitter settings:
Subtitles = non-empty

With advanced mode you can add something like this: `*:eng@full,*:eng`
This prefers tracks with "full" in the title.

**Comment by ecktt** [comment]
The Advance suggestion seems to have worked with most things except for a few older encodes. TY!

**Comment by clsid2** [comment]
Here is more detailed documentation for the advanced setting:
https://github.com/Nevcairiel/LAVFilters/blob/master/README.txt
