### ISSUE TITLE
Display songs lyrics 

### ISSUE THREAD

**Issue by LunaDoll** [clsid2/mpc-hc#2262]
Hi Hi,

I love your player and thank you for its development,
Unfortunately, I'm probably stupid and I can't figure out how to display the lyrics in songs.

Example: https://www.mediafire.com/file/ic2xyle61xetbcb/6._Full_Bodied.ogg/file

**Comment by clsid2** [comment]
Lyrics are not supported and I have no plans to add such functionality.
