### ISSUE TITLE
[DrDump] Crash in ExplorerPatcher

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2265]
MPC-HC crashed due to a bug in ExplorerPatcher.

Disabling `Simple Window Switcher` in EP settings may solve the majority of crashes.

If that does not solve the problems entirely, then do this:
**EP settings > File Explorer > untick `Register as shell extension`**
That should completely eliminate crashes when opening file dialogs in MPC-HC (and many other applications).

**Comment by Makar8000** [comment]
Personally I am still getting these crashes on the latest version of ExplorerPatcher (tried both latest stable and prerelease)

**Comment by Makar8000** [comment]
Hey @clsid2 - could you help provide instructions on where to locate the crash information from MPC-HC for me to forward to the ExplorerPatcher developers?

**Comment by clsid2** [comment]
The stack traces above is the only data that is publicly available. If they can not figure it out, they need to contact me.

**Comment by qmarsn** [comment]
hey gents, if you apply a [4gb patch](https://ntcore.com/?page_id=371) to the MPC-HC.exe file, it will get rid of the access violation as it wont go over the allocated VRAM amount..

Let me know if any issues after applying the patch.
