### ISSUE TITLE
Loading a huge playlist is slower due to dark theme

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#227]
A huge playlist (2000+) causes a delay when loading the player. Before theme changes it loaded nearly instantly.

**Comment by adipose** [comment]
How are you loading it?

**Comment by clsid2** [comment]
Re-opening the player is enough to reproduce it, with "remember last playlist" enabled. And the playlist window must be visible of course. I clearly see it being busy drawing the playlist window content. The list area appears as a white rect until it is done. It takes 1 second extra with 2000 entries, so you might need an even larger list to reproduce it well. I simply dragged a same selection of 100 files onto the playlist multiple times to create a big list.

There are people who have their entire music collection as a playlist, so there are cases with 50.000+ entries.

**Comment by adipose** [comment]
How is the performance on this one?

https://mega.nz/#!pFBVnSgb!VWuw_8XUm1M3j8IYi2y7yeE2-4mu9gs_MIth7p6rmFg

I've never been happy with the speed of customdraw of the listctrl.  It generates many function calls (one for each cell).  In this case it's a pretty simple list so maybe something is going on with the resize forcing a redraw that's not necessary.  For now I added some code specific to the main playlist.

**Comment by clsid2** [comment]
Loads much faster now.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/231

**Comment by clsid2** [comment]
Are there more cases where each cell gets repainted? For example when adding something, or changing to a different file? The user who originally reported this problem also had some extra delay when going to next file in playlist.

**Comment by adipose** [comment]
It should only repaint those cells that are updated.  If using older OS, it would have to repaint the scrollbar possibly, which is slower than the native toolbars.
