### ISSUE TITLE
Cut off titles at custom scale 140% in settings

### ISSUE THREAD

**Issue by rainman74** [clsid2/mpc-hc#2270]
Cut off titles at custom scale 140% in settings

MPC-HC Version: 2.0.0.163

![image](https://github.com/clsid2/mpc-hc/assets/16306963/01ce743d-9b5a-4c58-9f6f-47231983837f)

**Comment by adipose** [comment]
It only fully supports 96, 120, 144, 168, 192.

That being said, the dpi scaling should probably round to the closest of those. Otherwise the scaling code and the per-dpi assets won't always align.

@clsid2, should dpihelper round the dpi?

**Comment by clsid2** [comment]
Whatever you think is best solution is fine with me. Rounding to closest seems logical.

**Comment by rainman74** [comment]
> Rounding to closest

Rounding to closest would be fine.

**Comment by adipose** [comment]
@rainman74 
What OS are you using?

**Comment by adipose** [comment]
Well, I am not sure I am too worried about funny DPI settings, but I did observe that even at regular DPIs, sometimes the sizing could be better.  I was using a font size of "80% of the rectangle height," which is pretty arbitrary. At 175% scaling, this gave me a font height of 36 to fit in a box of 33.  And it seemed to center fine, but the descent was always cut off.

Now I force it to keep trying until it finds a font that fits in the rectangle, as well as manually center it to make room for the descent (the bottom of the "y" for example).  The result should be that even funny DPI scaling will be forced to find a font that fits, so it should fix your issue (though yours is much further off than it should be, meaning it's probably the result of createfontindirect and dpi).

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2297

**Comment by rainman74** [comment]
@adipose @clsid2 

With v2.1.0.22 it's much better, still a bit squashed but you can live with it. Thank you!

![image](https://github.com/clsid2/mpc-hc/assets/16306963/8a4d9f79-a3e7-49a7-b5aa-d49392a9181c)
