### ISSUE TITLE
LAV Filters 0.78 included in 2.0.0.167?

### ISSUE THREAD

**Issue by Hackjjang** [clsid2/mpc-hc#2271]
![image](https://github.com/clsid2/mpc-hc/assets/120134269/aae88282-7bf1-4241-a046-f8ad0f59cfbb)

The update history shows LAV filters 0.78, but the registered version is 0.77.2.25.
I checked the update history, so I know there is no difference in content, but... Unlike the update log, it doesn't seem to be reflected, so I'm reporting it.

**Comment by clsid2** [comment]
I did not rebuild LAV. Only difference is the version bump.

**Comment by Hackjjang** [comment]
Yes, this is what I also checked.
I only mentioned it because it was in the update history. :)
