### ISSUE TITLE
The app craches when I stream on Discord 

### ISSUE THREAD

**Issue by MhmdBu50** [clsid2/mpc-hc#2272]
I use MPC-HC Version: 2.0.0 and when streaming on Discord the app freezes and needs to be forcefully closed 
this only happens on my PC (on my laptop it works and steams with no issue) and both devices use Windows 11
I checked the settings and tried to change some stuff but couldn't fix it
I compared the settings to my laptop and made them the same and nothing changed 
I Updated the GPU drivers (I have RTX3070) but nothing changed 

hope you can fix the issue.

**Comment by clsid2** [comment]
https://github.com/clsid2/mpc-hc/issues?q=is%3Aissue+is%3Aclosed+discord
