### ISSUE TITLE
libass doesn't always render fonts correctly

### ISSUE THREAD

**Issue by motbob** [clsid2/mpc-hc#2273]
Version: 2.1.0, 64-bit, windows

Use "Internal Subtitle Renderer." In "Subtitles > Default Style," check the "Use libass for SSA/ASS" option. When you do that, fonts will not reliably render correctly. I can't figure a rhyme or reason to when it works or doesn't work.

EDIT: Fonts appear to render correctly when they are installed on the system, but not when they are only embedded in the mkv.

[Sample mkv](https://github.com/clsid2/mpc-hc/files/13199487/MPC_sample2.zip)
[This is what I see (image link)](https://github.com/clsid2/mpc-hc/assets/6509353/e3b221d1-fc0b-4aa6-9743-61f99eeb4474)
[This is how the font should look (image link)](https://github.com/clsid2/mpc-hc/assets/6509353/501f88f1-c56f-43f4-af98-87d776b47ab5)

The font renders properly in mpv/VLC.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2284

**Comment by motbob** [comment]
> #2284

https://github.com/mpv-player/mpv/blob/cb2b579f61764452652c6cf5c6a94ae5e67c77ed/sub/sd_ass.c#L104
no idea if it would be helpful to you or not, but this is mpv's list

**Comment by adipose** [comment]
Hmm, looks like a good list.  Probably wouldn't hurt to add those.

**Comment by clsid2** [comment]
More can always be added if you have other broken files.
