### ISSUE TITLE
Feature question - ASIO driver compatibility

### ISSUE THREAD

**Issue by harmandmen** [clsid2/mpc-hc#2275]
I just would like to know if there is any way to have **mpc-hc** use the **ASIO drivers** (when available in the system).
I guess not, as I didn't find any related options in the program, but there are so many options that I could well be wrong.
So I ask.

In case the use of ASIO drivers is not actually present, are there any plans to enable it in the future?

PS. Just to prevent any misunderstandings, I would like to point out that mine is just a question, with **no** intention whatsoever of complaining or anything like that.

**Comment by clsid2** [comment]
Google for "DirectShow ASIO".

I am not interested in ASIO and will not provide any further help.
