### ISSUE TITLE
[DrDump] Crash in H.264 DXVA2 decoding

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2277]
MPC-HC crashed while hardware decoding H.264 video.

The cause is likely a damaged/corrupted video stream. Or maybe a graphics driver bug.

If you can reproduce it consistently with a specific file, then please share details.

**Comment by storfors** [comment]
I got a 15 minute long clip that looks to be corrupted from the beginning until 4:13. It's a clip saved from Nvidia's Shadowplay. The clip looks corrupted in windows media player as well. Audio seems to work fine.

Letting the clip play for ten-ish seconds inside the corrupted area crashes MPC-HC. But playback after the corrupted bit works fine.

**Comment by clsid2** [comment]
I need feedback and sample file !!!

Was it indeed a broken/incomplete file?
Was it a DVB stream with transmission error?
Was the GPU perhaps running out of free memory because your were also gaming/browsing at same time?
Any other anomaly worth mentioning?
