### ISSUE TITLE
[DrDump] Crash while decoding AV1 video

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2278]
MPC-HC crashed while (hardware) decoding AV1 video.

We need user feedback to fix this crash. Please provide details about the circumstances under which the crash occurred.

**Comment by Dfeghali** [comment]
Could it be a damaged file? NO
Did your graphics driver perhaps crash during playback? running a Gforce 3090 TI with latest drivers
Were you playing multiple videos at the same time (including videos in Internet browsers or other players)? No
Were you playing a game or using some other application that uses the GPU? No
Did it happen after resuming from hibernation or sleep mode in Windows? No
Did it happen directly after making any (Display) settings changes in Windows? No
Or any other activity that might have triggered the problem? none! 

If you can consistently reproduce the crash with a specific file, then please share details about that file, so that we can download it.

- yes its a anime series from [Trix] Tensei Shitara Slime Datta Ken S01+02+OADs+Tensura Nikki - AV1

you can find this anime from: https://nyaa.si/view/1670325

After playing season 1 episode 1, it always happens when I click on stop.

**Comment by andrewfitz** [comment]
I also have this issue when stopping a video. It is a new bug that did not occur in last version. AV1 codec. 

Could it be a damaged file? no
Did your graphics driver perhaps crash during playback? no
Were you playing multiple videos at the same time (including videos in Internet browsers or other players)? no
Were you playing a game or using some other application that uses the GPU? no
Did it happen after resuming from hibernation or sleep mode in Windows? no
Did it happen directly after making any (Display) settings changes in Windows? no
Or any other activity that might have triggered the problem? stopping the video

**Comment by clsid2** [comment]
Does it also happen when hardware decoding is disabled?

Does it happen every time when stopping, or does it happen randomly?

**Comment by clsid2** [comment]
Let me know if this test build solves the crash:
https://www.sendspace.com/file/lxhtp3

**Comment by andrewfitz** [comment]
> Does it also happen when hardware decoding is disabled? have not tried
> 
> Does it happen every time when stopping, or does it happen randomly? randomly at this point, it is not happening at all today, wheras 2 days ago it was happening with every av1 file.

**Comment by andrewfitz** [comment]
Happened again after 2 weeks not, 4k 10bit mkv file av1 recorded from OBS. Seems to occur more frequently when reaching the end of the file, stopping, and clicking the video to play again.

**Comment by Reelix** [comment]
Had it happen with the following file using 2.1.3 (0cad76c96) on Windows 11

https://github.com/clsid2/mpc-hc/assets/289404/eec019d7-4004-401f-a4ef-bfe9227f3863

1.) Download + Play file
2.) Wait for file to finish
3.) Click in middle of video to play again
4.) Repeat Steps 2+3 about 2-5 times
5.) Crash, get redirected to this page

This can be replicated on multiple files created using the following ffmpeg command from a gif (Required width and height each divisible by 2)

ffmpeg -i file.gif -c:v libsvtav1 -svtav1-params film-grain=50 test.mp4

Using 2023-12-28-git-c1340f3439-full_build-www.gyan.dev from https://www.gyan.dev/ffmpeg/builds/ (ffmpeg-git-full.7z)

**Comment by andrewfitz** [comment]
Been a while, this time happened from av1 file exported from Davinci Resolve encoded with nvenc.

**Comment by phr00t** [comment]
I got this crash and was forwarded here. I was using OBS to play an AVI NVENC video in mkv format. The crash happened when I was trying to close the player (it might have been still playing when I closed the player).

**Comment by Enverex** [comment]
The file that crashed my MPC is tiny so I'm attaching it here. Just an OBS recorded video of what I believe was supposed to be Battlefield 6.

Or not, because GitHub is still garbage and supports AVI and MP4 but not MKV, boooo.

**Comment by clsid2** [comment]
You can ZIP it or upload to a site such as https://www.sendspace.com

**Comment by Enverex** [comment]
Done  - https://www.sendspace.com/file/bsyx40rg

**Comment by clsid2** [comment]
Which GPU and driver?

**Comment by Enverex** [comment]
Windows 11 Pro 25H2, RTX 4090, Driver version 591.86.

**Comment by clsid2** [comment]
See if you can reproduce with this version:
[test version for diagnosing FFmpeg crash](https://github.com/clsid2/mpc-hc/releases/download/2.7.4.34/MPC-HC.2.7.4.34.x64.ffmpeg_debug.zip)
