### ISSUE TITLE
Add a Option to Mute Audio for ~2 Seconds after Videostart

### ISSUE THREAD

**Issue by namornoditz** [clsid2/mpc-hc#2285]
Starting Videos, from commandline or from the Playlist, makes sometimes a loud noise sound for about one second.
Some Problem with MPC-BE or older Versions of MPC-HC older LAV.

A Workaround could be a Option to Mute Audio for configurable Time after starting/resuming a Video.

**Comment by clsid2** [comment]
The problem is with your audio hardware. Not normal behavior.

I am not adding such functionality.

**Comment by namornoditz** [comment]
Thank you for the quick response!
Thank you for your work!
I'll check my audio hardware - You mean the GPU?

**Comment by clsid2** [comment]
Clicking/popping sounds can happen due to high DPC latency caused by a driver. For example recent NVIDIA drivers have had some issues.

https://resplendence.com/latencymon
