### ISSUE TITLE
Remember File Position no longer works

### ISSUE THREAD

**Issue by SiLenCe-WB** [clsid2/mpc-hc#2287]
As the title says, the option **Remember File Position** is no longer working in version 2.1.0.

I've tried disabling it and enabling it again and it's still not working.

**Comment by clsid2** [comment]
Works fine here.

For audio or videos shorten than 10 minutes:
Options > Advanced

**Comment by SiLenCe-WB** [comment]
Thanks! I experienced the issue while watching a videoclip under 5 minutes and I thought it was an issue with the player. Sorry for the confusion 🙏🙏
