### ISSUE TITLE
DJI Mini 4 Pro - Metadata Embedded In Footage

### ISSUE THREAD

**Issue by Simon12148** [clsid2/mpc-hc#2289]
Hi

Been using mpc-hc for a while now and certainly the best player, but I have just purchased a DJI Mini 4 Pro drone, when I open up the footage in mpc-hc there is metadata embedded in the actual footage, I don't seem able to disable this.

Best regards

Simon

**Comment by clsid2** [comment]
Obvious place to look would be the subtitle menu.

**Comment by Simon12148** [comment]
Cheers, missed the obvious!!
________________________________
