### ISSUE TITLE
[docs] nasm.exe does not exist in the provided folder link

### ISSUE THREAD

**Issue by nopeless** [clsid2/mpc-hc#2290]
In Part G in the compilation.md https://github.com/clsid2/mpc-hc/blob/develop/docs/Compilation.md

**Comment by clsid2** [comment]
Link works fine for me.

**Comment by nopeless** [comment]
@clsid2 no exe file is in the zip file. am i missing something?

**Comment by clsid2** [comment]
https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip

**Comment by nopeless** [comment]
~~Do you want a PR for the docs?~~

(this has been reflected in a commit, no need for further action)
