### ISSUE TITLE
Window position is not being saved for files with no image/video.

### ISSUE THREAD

**Issue by Tsalnor** [clsid2/mpc-hc#2292]
The window position is not being saved for files with no image/video. This was working as expected before the latest update.

**Comment by clsid2** [comment]
Still working fine here.

**Comment by Tsalnor** [comment]
Has this been fixed? This also happens when MPC-HC is opened without any files.

**Comment by clsid2** [comment]
I can not fix something that I can not reproduce.

Options > Miscellaneous > Reset
Then change options one by one until the problem happens. Then tell me what changes you made.

And development builds to pinpoint when it started:
https://github.com/clsid2/mpc-hc/releases/tag/2.0.0.21

**Comment by Tsalnor** [comment]
2.0.0.21 works as expected while 2.0.0.25 has the issue. I have reset the options and turning on just "Remember last window position" is enough to cause this issue.

**Comment by clsid2** [comment]
That is is due to this commit:
https://github.com/clsid2/mpc-hc/commit/a08b773ca80a35b0aaa53b5f921852ad751dee6a

Is your window maximized or super small?

**Comment by Tsalnor** [comment]
It's the automatic size when opening MPC-HC without a file. I made a recording demonstrating the issue:
https://www.youtube.com/watch?v=1v-bfurEORQ

**Comment by clsid2** [comment]
Try this test build:
https://www.sendspace.com/file/d2sfre

**Comment by Tsalnor** [comment]
An error pops up that says "LastWindowPos invalid size?"

**Comment by clsid2** [comment]
Should be fixed now:
https://www.sendspace.com/file/abkgyp

**Comment by Tsalnor** [comment]
Yes, it works as expected. Thank you for fixing this.
