### ISSUE TITLE
temp folder for history open file

### ISSUE THREAD

**Issue by cekra007** [clsid2/mpc-hc#2298]
Does anyone know where the temp folder is to store this list? I'm looking for an IPTV link that I often play here, but because there's too much history, the IPTV link isn't there anymore, where is the temp folder located?

i using this version
MPC-HC (Nightly, 64-bit)
------------------------

Build information:
    Version:            2.0.0.5 (22dccf89a)
    Compiler:           MSVC v19.29.30147
    Build date:         Jan 22 2023

LAV Filters:
    LAV Splitter:       0.77.1.2
    LAV Video:          0.77.1.2
    LAV Audio:          0.77.1.2
    FFmpeg compiler:    MinGW-w64 GCC 12.2.0

Operating system:
    Name:               Windows 11
    Version:            10.0.22631 (64-bit)

Hardware:
    CPU:                AMD Ryzen 5 5500U with Radeon Graphics
    GPU1:               AMD Radeon(TM) Graphics (driver version: 31.0.12044.3)
    GPU2:               AMD Radeon(TM) Graphics (driver version: 31.0.12044.3)

![image](https://github.com/clsid2/mpc-hc/assets/16054105/d93acb7d-5ac1-4c67-95dd-509f089e2c89)

**Comment by clsid2** [comment]
Settings are stored in the registry.
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\MediaHistory

Here you can increase number of remembered entries:
Options > Advanced > RecentFilesNumber

And for stuff that you use often, you can also use Favorites menu.
