### ISSUE TITLE
still images ignore StillVideoDuration, picked up by internal LAV filter

### ISSUE THREAD

**Issue by vvuk** [clsid2/mpc-hc#2300]
If I add some still images to a playlist (jpg, png, etc.), each image just stays forever -- the playlist never advances. Looking at on-screen stats, the decoder is listed as "LAV Video Decoder (internal)". I'm guessing this results in the graph not outputing CLSID_StillVideo or CLSID_MPCImageSource, and so this path is never chosen: https://github.com/clsid2/mpc-hc/blob/0994fd605a9fb4d15806d0efdd6399ba1bc5f984/src/mpc-hc/FGManager.cpp#L2812

But I also see CLSID_StillVideo and CLSID_MPCImageSource not used anywhere else; is this some legacy MPC-HC stuff that got refactored at some point? As it is, I don't think there's a way to work with playlists with still images and have them auto-advance.

**Comment by clsid2** [comment]
The first is a standard filter from Windows and [MPCImageSource](https://github.com/v0lt/ImageSourceFilter) is a third party filter. Install that and set it as preferred to solve your problem.

LAV Splitter does NOT support setting image duration.

**Comment by vvuk** [comment]
Gah thank you -- I never thought to look and see if MPCImageSource was a standalone thing.
