### ISSUE TITLE
Add button for 'Renderer Settings' in Output page

### ISSUE THREAD

**Issue by Rikk** [clsid2/mpc-hc#2304]
When I was testing MPC VR, every time I needed to play a video, right-click to open the menu, go to Filter submenu and find the MPCVR there just to open its options.

It would have been convenient if we had a 'Renderer Settings' button right in the Output page of Settings, just like we have three for LAV Filters.

I'm not sure we have other Renderers that expose options, I know only MPCVR, but in the future we may have more, and a button to open its options would be useful.

**Comment by clsid2** [comment]
You can create a shortcut to open its settings directly.
`rundll32.exe "C:\location\of\MPCVR\MpcVideoRenderer64.ax",OpenConfiguration`

**Comment by Rikk** [comment]
> You can create a shortcut to open its settings directly. `rundll32.exe "C:\location\of\MPCVR\MpcVideoRenderer64.ax",OpenConfiguration`

Would it be a feasible feature (for the future) to save MPCVR (or other renderers) settings restricted at player level instead of system, similar to what is done for LAV?

**Comment by clsid2** [comment]
I see no use for that. Other apps don't use it or would be fine with exact same settings. I have zero interest in unneeded complexity.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2310

Yes this is quite an annoyance, but this supports madvr and mpcvr now.  Would have been useful while fixing that ESC bug in madvr...
