### ISSUE TITLE
Could not build lavfilters

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#2314]
zlib library complained about lack of unistd.h.  I added it from fontconfig and it works now.

**Comment by clsid2** [comment]
When did this start? Debug or release?

**Comment by adipose** [comment]
> When did this start? Debug or release?

I built debug full and it happened.  Not sure when it started.

**Comment by clsid2** [comment]
I had similar problem in the past with debug build. Not sure why you are getting it now.

**Comment by adipose** [comment]
I'm not sure, maybe something in the build dependencies is different, so unistd.h can be picked up from somewhere else, or maybe debug flags causes it to be needed for zlib.

**Comment by clsid2** [comment]
Debug lav uses msvc instead of gcc for building ffmpeg. It is related to that. You may need to build the other stuff first.

**Comment by adipose** [comment]
Oh, I forgot about that.  Yeah.

My other problem is:

```
15>Subtitles.lib(STS.obj) : error LNK2019: unresolved external symbol "public: class SubRendererSettings __cdecl CAppSettings::GetSubRendererSettings(void)" (?GetSubRendererSettings@CAppSettings@@QEAA?AVSubRendererSettings@@XZ) referenced in function "public: __cdecl CSimpleTextSubtitle::CSimpleTextSubtitle(void)" (??0CSimpleTextSubtitle@@QEAA@XZ)
15>Subtitles.lib(RTS.obj) : error LNK2019: unresolved external symbol "class CRenderersSettings & __cdecl GetRenderersSettings(void)" (?GetRenderersSettings@@YAAEAVCRenderersSettings@@XZ) referenced in function "private: class CSubtitle * __cdecl CRenderedTextSubtitle::GetSubtitle(int)" (?GetSubtitle@CRenderedTextSubtitle@@AEAAPEAVCSubtitle@@H@Z)

```

**Comment by adipose** [comment]
Further problem:

15>EXEC : error : gnutls not found using pkg-config

This is during lavfilters build.

**Comment by adipose** [comment]
Maybe caused by this:

`c:/msys64/mingw/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../../thirdparty/64/lib/libgnutls.a(global.o):(.text+0xb8): undefined reference to 'pthread_mutex_lock'
`

**Comment by clsid2** [comment]
Try with latest GCC:
https://files.1f0.de/mingw/mingw-w64-gcc-13.2-stable-r40.7z

**Comment by adipose** [comment]
Yes, I already have that.

I fixed it by rolling back the libgnutls.a file.

**Comment by Nevcairiel** [comment]
You are obviously not using that compiler, but some 9.3.0 version, as the error says.

**Comment by adipose** [comment]
> You are obviously not using that compiler, but some 9.3.0 version, as the error says.

Oh...I guess that is true.  I'm not sure why it's not using the one from `C:\msys64\mingw64`

**Comment by clsid2** [comment]
Try a fresh MSYS install. Don't let it install GCC. Then extract the mingw-gcc pack from above in mingw64 folder.
I don't have a `mingw` subfolder. And the `mingw32` folder is empty.

**Comment by adipose** [comment]
So I found in the logs, this line:

`FOUND='C:\msys64\mingw\bin\gcc.exe'`

It looks like my user.bat needs updating.  It previously pointed at c:\msys64\mingw, which needs mingw64 now.

**Comment by adipose** [comment]
Success! Sorry about that.
