### ISSUE TITLE
Two red stripes move during video playback sometimes after pause-play

### ISSUE THREAD

**Issue by vadimkantorov** [clsid2/mpc-hc#2316]
I could not identify a stable repro for now (besides it's a h.264+mkv video), but if I get more information, will paste here (including screenshots). But basically sometimes after pause-play cycles two vertical red stripes start moving from left to right in loops. Sometimes it's just the red stripes, sometimes, the decoded video is also corrupted  around these two red stripes

```
MPC-HC (64-bit)
---------------

Build information:
    Version:            2.1.0 (82c53e9b7)
    Compiler:           MSVC v19.29.30152
    Build date:         Oct 29 2023

LAV Filters:
    LAV Splitter:       0.78.0.0
    LAV Video:          0.78.0.0
    LAV Audio:          0.78.0.0
    FFmpeg compiler:    MinGW-w64 GCC 12.3.0

Operating system:
    Name:               Windows 11 (Build 22H2)
    Version:            10.0.22621 (64-bit)

Hardware:
    CPU:                11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz
    GPU:                Intel(R) Iris(R) Xe Graphics (driver version: 31.0.101.4502)
```

**Comment by clsid2** [comment]
You probably enabled **demo** mode in AMD graphics driver settings.

This is not done by the player, renderer, or codecs.

**Comment by vadimkantorov** [comment]
I don't have an AMD video chip. It's a Dell XPS13-9310 laptop and it has Intel video chip and Intel drivers. Attaching output of `dxdiag.exe`
[DxDiag.txt](https://github.com/clsid2/mpc-hc/files/13308080/DxDiag.txt)

I've used on this same system the old mpc-hc (from mpc-hc.org), and never had such an artifact. I'll post in this issue screenshots/video if I'll have this again.

**Comment by clsid2** [comment]
Maybe you pressed Ctrl+T to activate tearing test?

**Comment by vadimkantorov** [comment]
Indeed! This is what happened. I thought I switched to the browser window (by pressing Alt+Tab) and pressed Ctrl+T, but in fact the mpc-hc window stayed in focus (because of "always on top"). it might be nice, if this tearing test overlayed somewhere a text "tearing test", then it would be more clear

Thanks for helping investigating this!
