### ISSUE TITLE
Is it possible to display buttons on the control panel of the MPC-HC program?

### ISSUE THREAD

**Issue by naumgod** [clsid2/mpc-hc#2317]
Is it possible to display buttons on the control panel of the MPC-HC program?
1). Next frame, back frame.
2). Rotate video 90 degrees.
3). A control strip for brightness, contrast and color saturation?
This would make my life a lot easier and I would really like to see such convenient controls.

**Comment by clsid2** [comment]
Adding new buttons is not going to happen.

Framestep button is already present. Right-clicking on it goes backwards.
For rotate there are keyboard shortcuts.
For color controls as well. Options > Player > Keys.
