### ISSUE TITLE
Double Subtitle When Fast Forwarding

### ISSUE THREAD

**Issue by rahaaatul** [clsid2/mpc-hc#2318]
# Example

https://github.com/clsid2/mpc-hc/assets/86149861/6108d2ef-b69d-4df3-88fc-544d2e4fe233

**Comment by rahaaatul** [comment]
OS: `Windows 11`
App Version: `2.1.1`

**Issue appeared after installing this version.** It didn't happen before.

**Comment by clsid2** [comment]
What subtitle format?
Embedded or external?

If possible give link to the video file.

**Comment by rahaaatul** [comment]
> What subtitle format? Embedded or external?

Embedded. Media Info:
```
Video: MPEG4 Video (H264) 1280x720 30fps [V: h264 high L3.1, yuv420p, 1280x720 [default]]
Audio: AAC 48000Hz stereo [A: aac lc, 48000 Hz, stereo [default,forced]]
Subtitle: UTF-8 [S: English [eng] (subrip) [default,forced]]
Subtitle: UTF-8 [S: Arabic [ara] (subrip)]
Subtitle: UTF-8 [S: Bulgarian [bul] (subrip)]
Subtitle: UTF-8 [S: Chinese [chi] (subrip)]
Subtitle: UTF-8 [S: Dutch [dut] (subrip)]
Subtitle: UTF-8 [S: Finnish [fin] (subrip)]
Subtitle: UTF-8 [S: French [fre] (subrip)]
Subtitle: UTF-8 [S: Indonesian [ind] (subrip)]
Subtitle: UTF-8 [S: Italian [ita] (subrip)]
Subtitle: UTF-8 [S: Japanese [jpn] (subrip)]
Subtitle: UTF-8 [S: Korean [kor] (subrip)]
Subtitle: UTF-8 [S: Lithuanian [lit] (subrip)]
Subtitle: UTF-8 [S: Polish [pol] (subrip)]
Subtitle: UTF-8 [S: Portuguese [por] (subrip)]
Subtitle: UTF-8 [S: Serbian [srp] (subrip)]
Subtitle: UTF-8 [S: Spanish [spa] (subrip)]
Subtitle: UTF-8 [S: Swedish [swe] (subrip)]
Subtitle: UTF-8 [S: Turkish [tur] (subrip)]
Subtitle: UTF-8 [S: No subtitles]
```

> If possible give link to the video file.

If you are on Telegram, I can send you the file.

**Comment by clsid2** [comment]
@adipose
To fix above issue I have reverted the recent libass rate change fix. But now the libass issue is back.
We need to do with libass something similar to what `pRTS->RemoveAll(); pRTS->CreateSegments();` does for normal ISR.
Any ideas?
Edit: flush events does the trick

**Comment by clsid2** [comment]
Fixed

**Comment by rahaaatul** [comment]
Woah! Fastest fix I've ever seen! @clsid2 rocks!
