### ISSUE TITLE
SPDIF Audio problem - encode to AC3

### ISSUE THREAD

**Issue by gsapient** [clsid2/mpc-hc#2319]
I am using ffdshow to encode the audio output of mpc-hc to ac3.
This worked fine up to version 2.0, but starting with 2.1 (and including 2.1.1) ffdshow has stopped encoding the output, instead passing it on as PCM. Reverting to 2.0 fixes the problem. 

Details: Windows 11 x64, x64 versions of mpc-hc and ffdshow, tested using eac3 input, decoded by mpc-hc to pcm and then passed to ffdshow for encoding to ac3 (my soundbar only supports ac3, not eac3)

**Comment by clsid2** [comment]
Still working fine here.

- Disable Mixer in LAV Audio Decoder
- Enable Resample to 4800Hz in ffdshow audio processor
- Enable Mixer in ffdshow audio processor, set to 3/0/2 + LFE
- Enable AC3 pass-through and AC3 encode mode in ffdshow audio processor
- Select a compatible audio renderer in MPC-HC
Options > Playback > Output
Note: for SaneAR you can select the desired audio device on the `Audio Renderer` settings page
Note: for MPC Audio Renderer you can select device in `menu > play > filters > MPC Audio Renderer`, reload video after change
Note: you only need to specify device if the correct one is not set as default in Windows

**Comment by gsapient** [comment]
Enabling the mixer in ffdshow fixed it. This was not necessary with mpc-hc 2.0
I think the newer versions do not label the channels correctly, so the mixer is necessary

edit: My windows configuration is set correctly to 3/0/2 + LFE, so that might have been enough before, but not anymore

**Comment by clsid2** [comment]
Mixer in ffdshow should always be enabled. Otherwise you will have trouble re-encoding stuff like 7.1 input and other combinations that are not supported by the AC3 encoder.

LAV Audio Decoder shows the output channel mapping on its Status page. Do you see an different/incorrect value there? If so, I need a link to a sample file.

**Comment by gsapient** [comment]
Actually, I do see something different:
In v.2.0 the channels were correctly shown as: L, R, C, LFE, **B**L, **B**R
In newer versions the channels are incorrectly shown as: L, R, C, LFE, **S**L, **S**R

edit: This happens with all tracks I tested, so you shouldn't need a sample

**Comment by clsid2** [comment]
That is not wrong.
Controlled by option "Use Legacy 5.1 layout" in LAV Audio Decoder.

Still, you should enable Mixer in ffdshow.

**Comment by gsapient** [comment]
Weirdly, in v2.0 and prior, the channels were always labeled BL, BR (a bug?), so I never paid any mind to that option. But since v2.1, that option actually makes a difference!

**Comment by clsid2** [comment]
It is not a bug.

For the third time, enable Mixer in ffdshow!
