### ISSUE TITLE
Feature Request: Increase Rate in Backward Direction

### ISSUE THREAD

**Issue by rahaaatul** [clsid2/mpc-hc#2321]
# Example

https://github.com/clsid2/mpc-hc/assets/86149861/9894a813-08c1-4d9a-8c88-347561ce2316

**Like Fast Forwarding but to the backward direction**

Is this possible? Can you add it (including a shortcut for the function) if it's not too hard to add?

**Comment by rahaaatul** [comment]
Seems like I missed the feature request post...sorry about that.

But I'll leave it open, hoping that you'll accept the request.

**Comment by butterw** [comment]
Just seek back (with key, multiple times).
