### ISSUE TITLE
Wrong tooltip for the last advanced option

### ISSUE THREAD

**Issue by vsemozhetbyt** [clsid2/mpc-hc#2324]
The last advanced option has a wrong tooltip. It is duplicated from the previous one. Maybe this is a mouse pointer issue (Windows 10 x64).

![err](https://github.com/clsid2/mpc-hc/assets/10393198/800ddc50-bc7b-4b38-84ca-9d83851525b9)

**Comment by clsid2** [comment]
Already fixed
