### ISSUE TITLE
Settings are lost if no free space is available

### ISSUE THREAD

**Issue by sergeevabc** [clsid2/mpc-hc#2326]
Problem:
* MPC-HC is configured to save settings in .ini file instead of Windows registry
* One day the disk becomes overloaded with data, so no free space is available
* MPC-HC tries to save .ini (e.g. on close event) and cannot do that
* Next time you launch MPC-HC, its settings are lost, silently reset to default

Proposed solutions:
* Do not save/overwrite .ini file if not enough free space is available
* Use temporary file, verify it is saved properly (e.g. like KeePass does), then replace .ini with it

**Comment by clsid2** [comment]
Having zero free space on disk is just plain wrong. I am not spending even a millisecond on this non issue. Use Registry instead. Which is faster and better.

**Comment by sergeevabc** [comment]
@clsid2, what's the point of rolling out portable version for years if you don't understand that registry is not meant for portable scenario at all? This app can be stored on a flash drive, which is easy to overfill. It’s also easy to overfill a disk partition with torrent pieces, a microphone or camera recording, cache residues of a graphics editor, etc. This player has a lot of settings, restoring them takes time, so your lack of understanding of such an obvious thing is puzzling.
