### ISSUE TITLE
changing current subtitle track stops displaying any subs until full-screen mode is exited

### ISSUE THREAD

**Issue by MicroB9** [clsid2/mpc-hc#2327]
When playing movie in full-screen window and I change the selected subtitle track, all subtitles stop showing. I have to switch to window mode and back to full screen in order to get the new subtitle track showing properly. This issue has been around for a couple of years now, and I thought I might as well report it. It is a slight annoyance but annoyance none the less.

**Comment by clsid2** [comment]
It works fine here. Similar issue was fixed long ago, so make sure that you are using latest version.

Which video renderer?
Which file format?
Which subtitle format? Embedded or external?

**Comment by MicroB9** [comment]
I am using the latest version of player and codecs. Video renderer: madVR. Format: definitely mkv. subtitle format: definitely internal.
Perhaps I should upload my .ini settings file to see if it will cause same issue on your end? I copied the ini files to my other PCs and they all have the issue.

**Comment by clsid2** [comment]
You can the subtitle formats in:
Menu > Play > Subtitle Track

If you get delays when opening files, then it is due to use of INI file (in combo with Madvr).

**Comment by clsid2** [comment]
Problem is related to the Subtitle Texture Resolution setting in MPC-HC.
If smaller than screen size, there is a bug.

**Comment by MicroB9** [comment]
My screen size is 4K. How can I resolve this bug?

**Comment by clsid2** [comment]
Options > Subtitles > maximum Texture Resolution

I will try to fix the bug.

**Comment by MicroB9** [comment]
My current maximum Texture Resolution here is set to 2560x1440. When I change it to 3840x2160, it does not save and goes back to 2560x1440 after player restart. Not sure if this is related to the bug, or if it even has any impact at all.

**Comment by clsid2** [comment]
If it does not save, then your INI probably does not have write access.

My advice: STOP using INI
You can backup registry through:
Options > Miscellanous > Export
And to import:
Reset setting first, followed by double-click on the .reg file.

**Comment by clsid2** [comment]
Fixed

**Comment by MicroB9** [comment]
My INI file definitely has write access because it saves in it position of each movie mid viewing, i.e. it will resume in the last position when viewer was closed. I will test the new version when it's released and report back.
