### ISSUE TITLE
Improve Toolbar Tooltips

### ISSUE THREAD

**Issue by tsubasanouta** [clsid2/mpc-hc#2328]
Would you improve toolbar tooltips when you have time.
They would look nice.

Play → Play | Open
Stop → Stop | Close
Skip Back → Skip Back | Previous File
Skip Forward → Skip Forward | Next File
Step → Step | Step Backwards
Mute → Mute |  Next Audio Track

**Comment by clsid2** [comment]
That will confuse people who don't know about the right-click.

And given that a lot of users are pretty stupid, I think it is a bad change.
