### ISSUE TITLE
Access Violation Exception when combining D3D11 Native with MPCVR D3D11 Rendering Mode

### ISSUE THREAD

**Issue by feena** [clsid2/mpc-hc#233]
Corresponding information as follows when using version 1.9.0:

Offset: 0x23FF6E, Codebase: 0x7FF7B0B70000
The thread () tried to read memory at address 0x0

The exception will only occur when setting D3D11 Native mode in LAV Video Decoder along with D3D11 rendering mode in MPC Video Renderer. 

Version 1.8.8.14 (a700e197b) does not throw this exception.

**Comment by clsid2** [comment]
I think this is already fixed. Try version 1.9.0.20
