### ISSUE TITLE
Some msgbox title bar text doesn't seen

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2330]
MPC-HC (64-bit)
_Build information:
    Version:            2.1.2 (2b85bfdeb)
    Name:               Windows 10 (Build 22H2)
    Modern Light theme_

- Options > Formats > File extensions > change any file association
Title bar text doesn't seen, but on dark theme it is visible.
![image](https://github.com/clsid2/mpc-hc/assets/3073922/ccd44016-af20-435a-894f-c2ed9711739d)

https://github.com/clsid2/mpc-hc/blob/974220e6837010ee829b40f51b6a79a5f260ca1c/src/mpc-hc/PPageFormats.cpp#L315
And maybe adding information symbol to message box can make it look nice.

### There are also small visual inconsistences:

- Options > DVD
![image](https://github.com/clsid2/mpc-hc/assets/3073922/9958ca36-7d05-4b0a-9c2f-80b48e00bb8a)
- Options > Playback > Shaders 
![image](https://github.com/clsid2/mpc-hc/assets/3073922/7ce625bd-7890-447a-9164-e7f2156e582e)
- Favorites > Organize Favorites
![image](https://github.com/clsid2/mpc-hc/assets/3073922/93a83523-b09e-4467-8bca-d5ed4cd8d113)
- Download subtitles (d)
![image](https://github.com/clsid2/mpc-hc/assets/3073922/7187840a-8fb9-4def-a47f-c0f2bab5bfa5)

**Comment by adipose** [comment]
> * Options > Formats > File extensions > change any file association
>       Title bar text doesn't seen, but on dark theme it is visible.

https://github.com/clsid2/mpc-hc/pull/2333

The default is `AfxGetAppName()` but it was being forced to NULL.  Also `::MessageBoxW` has a different default than `CWnd->::MessageBoxW`.  Fixed.
