### ISSUE TITLE
Video encoded with HEVC yuv420p10le appears discolored, more gray

### ISSUE THREAD

**Issue by 7heS4ge** [clsid2/mpc-hc#2339]
I have new videos encoded with HEVC codec in HDR 10bits yuv420p10le. This videos appear discolored, more gray, on Media Player Classic. On VLC, this videos appear with good colors.

**Comment by NBruderman** [comment]
Which video rendered do you use?

**Comment by clsid2** [comment]
You need to use a HDR compatible renderer.

**Comment by 7heS4ge** [comment]
LAV video decoder 0.78 seems used by MediaPlayerClassic
With my video : Filter : Enhanced Video Renderer.
What I need to do/change in the player settings ?

**Comment by NBruderman** [comment]
You can set it in the options for another one. MPCVR should support that.

________________________________

**Comment by clsid2** [comment]
Read the comments about HDR here:
https://github.com/clsid2/mpc-hc/releases/tag/2.1.2

**Comment by 7heS4ge** [comment]
OK thank you.
I installed MPC Video Renderer from https://github.com/Aleksoid1978/VideoRenderer/releases
And I choose this renderer in the player : Options/Playback/Output
