### ISSUE TITLE
MPC appears to be loading some videos in a rotated state

### ISSUE THREAD

**Issue by POD-io** [clsid2/mpc-hc#234]
I have some videos that appear upright in other players and editing software, but MPC-HC is playing the videos in a rotated state compared to the others.

How can I change this and/or is there a way to determine the 'true' state of the video, in case it needs to be rotated and re-saved?

Thanks!

**Comment by ValZapod** [comment]
ffplay of ffmpeg. https://ffmpeg.zeranoe.com/builds/

And give the video please. (Just drag and drop zip archive here.)

**Comment by clsid2** [comment]
You can see the encoded size of the video here:
Menu > File > Properties > MediaInfo

It auto-rotates when the file has rotation metadata. Videos recorded with phones often have that.

**Comment by POD-io** [comment]
Thank you! That menu was very helpful. I have found that some of the videos have a row called 'Rotation' and others do not. I expect that those with 'Rotation' means the RAW data of the file was recorded in a rotated manner?

Total aside, but any recommendation on the best way to fix rotated video? Thanks again!

**Comment by clsid2** [comment]
You can re-encode and rotate the video with Handbrake.
https://handbrake.fr/
