### ISSUE TITLE
libass performance issues

### ISSUE THREAD

**Issue by motbob** [clsid2/mpc-hc#2340]
2.1.2, Windows 64-bit.

When playing demanding subtitles, both ISR without libass and mpv with libass perform better than ISR with libass. In the below sample, I consistently get ~60 dropped frames with ISR+libass, 12-13 dropped frames with default ISR, and zero dropped frames in mpv. The tests assume that you are not full-screening while watching.

[Sample with very heavy subtitles](https://github.com/clsid2/mpc-hc/files/13366001/heavy-subtitles.zip)

**Comment by clsid2** [comment]
For ISR without libass, the subpic queue can help.

Libass is disabled by default for a reason. I don't recommend using it. I can't fix its performance.

**Comment by NBruderman** [comment]
I tried your sample, and got similar results both with Libass and with ISR.
Actually, when I tried heavier sample, libass performed noticeably better, with ISR I got some massive frame drops.
@motbob Can you recommend me a simple software when I can cut the relevant sample with? Because its part of a 23 min episode

**Comment by motbob** [comment]
> I tried your sample, and got similar results both with Libass and with ISR. Actually, when I tried heavier sample, libass performed noticeably better, with ISR I got some massive frame drops. @motbob Can you recommend me a simple software when I can cut the relevant sample with? Because its part of a 23 min episode

Sure. I used `ffmpeg -i file.mkv -an -c copy -ss 2:40 -to 2:50 test.mkv`. This command will not copy the fonts, so if it's the fonts that are causing the framedrops (which can happen if they are very fancy/intricate), you will need to mux them in afterwards.

Or if you need a GUI, use [handbrake](https://handbrake.fr/) and change the following settings:

Summary > Format --> MKV
Video > Framerate (FPS) --> 23.976 (or whatever the original FPS is)
Audio --> remove the audio track
Subtitles --> select "1 English [SSA]" (or whatever your desired track is), uncheck "Burn In", and check "Default"

Near the top of the screen, set "Range" to seconds and set your desired time.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2364

You can try a test build here: https://mega.nz/file/tU5WTbLa#NtCT4HNI1bxXiMaBCOUdvVzjDiJPvfcfGnjetKzn2Ww

**Comment by motbob** [comment]
Thank you. Now I have zero dropped frames on the sample, which is better performance than vanilla ISR
