### ISSUE TITLE
[v2.1.2 Bug] MediaInfo properties inaccessible on first click

### ISSUE THREAD

**Issue by ryehamstrawberry** [clsid2/mpc-hc#2341]
Using the latest version v2.1.2, I've noticed that the MediaInfo properties tab no longer appears on first click.
The current behavior forces the properties dialog to be opened once > closed > then opened again before the MediaInfo tab is displayed.

This was not an issue in previous versions and for anyone who views metadata a lot, this is certainly an inconvenience that will amount in a lot of wasted time if users are forced to perform a function twice before it's made available.

**Comment by clsid2** [comment]
Next time check closed issues first.
