### ISSUE TITLE
[Bug] PGS subtitles unavailable to enable

### ISSUE THREAD

**Issue by ryehamstrawberry** [clsid2/mpc-hc#2342]
PGS subtitle tracks do not appear to be available to enable despite being muxed correctly.
Tried several videos that fail to display said subtitles in MPC, but display fine in VLC.

> Text #1
> ID                             : 3
> Format                         : PGS
> Muxing mode                    : zlib
> Codec ID                       : S_HDMV/PGS
> Codec ID/Info                  : Picture based subtitle format used on BDs/HD-DVDs
> Duration                       : 43 min 5 s
> Bit rate                       : 41.9 kb/s
> Frame rate                     : 0.440 FPS
> Count of elements              : 1138
> Stream size                    : 12.9 MiB (0%)
> Language                       : English
> Default                        : No
> Forced                         : No
> 
> Text #2
> ID                             : 4
> Format                         : PGS
> Muxing mode                    : zlib
> Codec ID                       : S_HDMV/PGS
> Codec ID/Info                  : Picture based subtitle format used on BDs/HD-DVDs
> Duration                       : 43 min 5 s
> Bit rate                       : 37.9 kb/s
> Frame rate                     : 0.412 FPS
> Count of elements              : 1066
> Stream size                    : 11.7 MiB (0%)
> Language                       : French
> Default                        : No
> Forced                         : No
> 
> Text #3
> ID                             : 5
> Format                         : PGS
> Muxing mode                    : zlib
> Codec ID                       : S_HDMV/PGS
> Codec ID/Info                  : Picture based subtitle format used on BDs/HD-DVDs
> Duration                       : 43 min 5 s
> Bit rate                       : 21.9 kb/s
> Frame rate                     : 0.369 FPS
> Count of elements              : 954
> Stream size                    : 6.74 MiB (0%)
> Language                       : Japanese
> Default                        : No
> Forced                         : No
> 
> Text #4
> ID                             : 6
> Format                         : PGS
> Muxing mode                    : zlib
> Codec ID                       : S_HDMV/PGS
> Codec ID/Info                  : Picture based subtitle format used on BDs/HD-DVDs
> Duration                       : 43 min 5 s
> Bit rate                       : 38.1 kb/s
> Frame rate                     : 0.412 FPS
> Count of elements              : 1066
> Stream size                    : 11.7 MiB (0%)
> Language                       : Spanish
> Default                        : No
> Forced                         : No

**Comment by clsid2** [comment]
You need to report this at LAV Filters project.
Report should include a sample file to increase chance of a fix.

My quess is that it is due to: `Muxing mode : zlib`.
Changing settings in your muxing tool should avoid the problem.

**Comment by Sopor** [comment]
According to the LAVFilters repo this is because the subtitles are set to false `enabled = false`, but why does Kodi, VLC and even MPC-BE show the subtitles?

I use subtitles a lot and it is sad if i have to abandon MPC-HC because of this.

Maybe you can add an option to make these subtitles visible too even if subtitles have been set to false?

**Comment by clsid2** [comment]
Those other players are not following the Matroska specification correctly.

You can fix your files with MkvToolNix.

**Comment by Sopor** [comment]
If the subtitles are set to
`Default track: No`
`Forced display: No`
it seems that MPC-HC will still enable the subtitles when starting the video.
In that case that is not by the Matroska specification.
When Default track is No, subtitles should be disabled when starting a video and i should manually have to enable them.
