### ISSUE TITLE
Dark Mode in view sidebar Missing in Pre-Release 

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [clsid2/mpc-hc#2343]
![](https://i.imgur.com/XTB58Qm.png)

**Comment by ZEROPOINTBRUH** [comment]
Correction, its missing in view sidebar

**Comment by clsid2** [comment]
Options > Player > Theme

**Comment by ZEROPOINTBRUH** [comment]
I hate to be a jaw breaker but your readme says 

### Dark interface
Menu > View > Dark Theme
