### ISSUE TITLE
Repeat A-B marks reset problem

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2344]
MPC-HC (Nightly, 64-bit)
_Build information:
    Version:            2.1.2.17 (91f79523c)_

Open video > Mark A and Mark B positions > A-B Reset 
is just hide A-B marks, not reset. Close media player and open same video again you will see marks are there. To reset A-B marks I have to seek out of the A-B range to reset it.

**Comment by clsid2** [comment]
Fixed
