### ISSUE TITLE
[DrDump] Crash while decoding VobSub subtitle file/stream

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2345]
MPC-HC crashed.

Please provide a subtitle file or video file (in case of embedded subtitles) that triggers this crash.

You can upload sample to Dropbox, Google Drive, or any other free file host such as [SendSpace](https://www.sendspace.com). A magnet/torrent link is fine as well.

**Comment by xLn2** [comment]
I am not sure about it but that might be mine. 
Using MpcVr, SaneAR, Internal Subtitle renderer

Steps to reproduce

- Drag a subtitle(srt) file from the zip archive to the program > sync subtitle and save it via Ctrl + S (to video location)
- Change video renderer to EVR-CP
- Re open media with Ctrl + E
- It frezes but sometimes it come back but cannot open first expected subtitle, it opens subtitle within zip file.

**Comment by clsid2** [comment]
This page opens only when the specific crash occurs. So not same problem.

It remembers location of files you add. So if you want to replace it, you need to open the reloaded sub. Or clear history.

**Comment by clsid2** [comment]
I STILL NEED A SAMPLE FILE !!!

WHY IS NOBODY CAPABLE OF SHARING A FILE ???

All my files play perfectly. Why is is so difficult to understand that developers CAN NOT FIX bugs if they can not reproduce them.

**Comment by clsid2** [comment]
Thanks. That specific issue was indeed fixed. The video contains two truncated vobsub packets at begin.

Two other vobsub related crashes still exist, so anyone that gets crash with latest version should still give samples.

**Comment by grimbob** [comment]
Confirmed I'm no longer able to repro the crash with the provided sample or similar files using MPC-HC.2.6.2.21.x64. Thanks!
