### ISSUE TITLE
MediaInfo tab not showing up on the first open of the Properties dialog

### ISSUE THREAD

**Issue by n-99** [clsid2/mpc-hc#2348]
I noticed this bug very recently (last release or one of the very recent betas). I only ever see the MediaInfo tab after opening the Properties dialog for the second, third, … time.

Release:
> MPC-HC (64-bit)
> ---------------
> 
> Build information:
>     Version:            2.1.2 (2b85bfdeb)
>     Compiler:           MSVC v19.29.30152
>     Build date:         Nov  9 2023
> 
> LAV Filters:
>     LAV Splitter:       0.78.0.0
>     LAV Video:          0.78.0.0
>     LAV Audio:          0.78.0.0
>     FFmpeg compiler:    MinGW-w64 GCC 12.3.0
> 
> Operating system:
>     Name:               Windows 7 (Service Pack 1)
>     Version:            6.1.7601 (64-bit)
> 
> Hardware:
>     CPU:                Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
>     GPU:                Intel(R) HD Graphics 4600 (driver version: 10.18.14.5180)

**Comment by clsid2** [comment]
Read closed issues first next time!
