### ISSUE TITLE
A couple of suggestions about playlist management.

### ISSUE THREAD

**Issue by The-Solutor** [clsid2/mpc-hc#2349]
Call me weird but I always felt wrong what happens opening a m3u...

I mean I personally would expect that opening a m3u file would do just that: loading a list of files/urls, not opening it AND start playing the first item on that list (or the last played one). I wish that autoplaying was an optional setting (maybe a flag buried inside the advanced options, but optional).

Also I feel weird that m3us aren't shown in the history/jumplist of opened files, the actual behavior is to remember the last file(s) played from the playlist. That seem inconsistent/inconvenient to me.

Both aren't for sure earth shattering bugs, but still I think shouldn't be that problematic to improve.

Thanks in advance for evaluating what I'm suggesting here.

**Comment by clsid2** [comment]
You can disable autoplay by setting repeat to 0 times in options.

For history there is other issue already.

For remember position, not planned for now. I am not debating this. Position is remembered if you don't play anything else in between.

**Comment by The-Solutor** [comment]
OK, thanks

**Comment by The-Solutor** [comment]
Sorry for adding a further comment to a closed item (not sure what would be the correct way to behave here)

But I tried the autorepeat= 0 suggestion, and it doesn't do what I hoped.

It's true the file (url in my case) isn't played, but the stream is requested anyway, the channel request (to TV server in my case) it's still triggered, and the TV server still starts to serve the url/channel until it times out.

Also, this way, once the playlist is opened, ANY item of the playlist dont start playing after I click on the item, in short not really a solution.

I still hope you evaluate an option to load the m3u w/o doing anything else, even if as a low priority task.
Thanks again.

**Comment by clsid2** [comment]
You can use command line parameter `/open`
