### ISSUE TITLE
Large spacing gaps in playlist

### ISSUE THREAD

**Issue by btu1398** [clsid2/mpc-hc#235]
![MPC issue](https://user-images.githubusercontent.com/59989073/72583351-fe999180-38b3-11ea-838e-447d5ce0c282.png)
![MPC issue 2](https://user-images.githubusercontent.com/59989073/72583352-ff322800-38b3-11ea-8207-4e887eee34fd.png)

After installing the latest MPC-HD update, my playlist gained some massive spacing above and below each line.  I only see this on my 4K monitor.  When I move MPC to my regular PC monitor, all the spacing and sizing looks correct.

I think this has to do with Windows Display scaling.  For the 4K monitor, the recommended scaling is 300%, but I have it set to 200% (300% is way too large).  At 300%, each line in the playlist has no spacing issues - it's like the lines in the playlist are 300% scaling, but the text on the lines is 200%.  I think this scaling is having issues elsewhere too - like the attached settings image where several strings are much larger than the others.

**Comment by adipose** [comment]
Probably a duplicate of https://github.com/clsid2/mpc-hc/issues/196

Try the test build at the end of that thread.

**Comment by btu1398** [comment]
Hey, sorry for the delay.  I gave the test build a shot, and the playlist has the same issue still.  The random cases of giant font in the Settings was fixed by the test build however

**Comment by adipose** [comment]
@btu1398 

What OS do you have?  I am using latest W10.  Here's what my playlist looks like @200% font zoom.

![image](https://user-images.githubusercontent.com/3324395/72839203-add4c080-3c46-11ea-8a78-4d070f8ac6aa.png)

![image](https://user-images.githubusercontent.com/3324395/72839224-bdeca000-3c46-11ea-9229-ba26c430566d.png)

I will upload a recent test build here, just in case you were testing something old:

https://mega.nz/#!RJ5XUYLJ!jC_RlZgxhWokMoEMIEc1J1u-rY0HATMqmddkGIdhd1w

**Comment by btu1398** [comment]
Downloaded and tried the build you just linked, and still see the same issue.  This PC is also running the latest Windows 10 release.

I think I might have been barking up the wrong tree with the font scaling.  If I keep switching between my 2 monitors and maximizing, the spacing becomes worse and worse:
![MPC issue 3](https://user-images.githubusercontent.com/59989073/72855916-16dc2880-3c87-11ea-91e0-b23221bee7e4.png)
![MPC issue 4](https://user-images.githubusercontent.com/59989073/72855918-19d71900-3c87-11ea-925c-ace66ed599d3.png)
![MPC issue 5](https://user-images.githubusercontent.com/59989073/72855923-1c397300-3c87-11ea-8d71-51428aa8d09c.png)

After checking this, I re-opened MPC-HC and it opened on my smaller monitor, and I noticed I had no spacing issues on the smaller monitor.  It was also windowed (ie not maximized).  When I moved it to my other monitor, the playlist still had no spacing issues.  As soon as I maximized the window, the spacing issue came back.  If MPC-HC opens on my larger monitor, the spacing issue is seen right away (though I'm noticing on the larger monitor, it is opening already maximized...)

Hopefully this helps

**Comment by adipose** [comment]
Thanks, I can reproduce it now.  Switching from full screen to windowed on a dpi aware second monitor grows the row height repeatedly.

**Comment by btu1398** [comment]
I do software testing for a living and the complexity of this stuff is always stunning.  Even with a list of requirements I doubt a corner case like this would ever come up when trying to think up test cases.  I'm actually really curious what kind of change ended up breaking this.

Anyways, thanks for looking into it!

**Comment by adipose** [comment]
I have a fix for this.  This is what caused it: https://github.com/clsid2/mpc-hc/pull/162

It seems the controlbar is sending an extra measureitem request, which causes some issues.  I have a workaround, but it's actually a bit of a weird request it makes.  As far as I can tell, it isn't easily identifiable as coming from the controlbar, other than having what appears to be garbage data in some of the fields.  But possibly, that data has meaning...

**Comment by adipose** [comment]
Try out this build:

https://mega.nz/#!RUwTAIZA!gBfb0mqfpsVdoWdk-TGwJ7j9RxauAze9BACkedcO_rU

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/243

**Comment by btu1398** [comment]
That works great - tried switching between monitors, switching between maximized and windowed, and I'm not seeing any spacing gaps appear.

Should I be closing the issue now, or should I be waiting for the change to be merged into main and checking there?

Thanks for your help!

**Comment by adipose** [comment]
Assuming it gets merged you could just close it.

**Comment by btu1398** [comment]
Ok, thanks again!

**Comment by adipose** [comment]
@btu1398 thanks for testing and feedback!
