### ISSUE TITLE
Can I have dark mode without the new modern theme?

### ISSUE THREAD

**Issue by nexus226** [clsid2/mpc-hc#2353]
I feel unsatisfied with the new seekbar and volume slider, especially because the dark mode is now limited to the modern theme and I can't use it in the classic theme.

**Comment by clsid2** [comment]
Dark mode is limited to modern theme.

**Comment by nexus226** [comment]
Wonder why this wasn't the case with previous releases.

**Comment by clsid2** [comment]
It was changed and I am not changing it back.
