### ISSUE TITLE
rename pan and scan in history

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#2354]
Options→Player→History
Remember last Pan & Scan zoom
Do you improve Pan & Scan to PnS Frame Adjust?

_Originally posted by @tsubasanouta in https://github.com/clsid2/mpc-hc/pull/2335#issuecomment-1823496196_

I indeed missed this one.

**Comment by butterw** [comment]
Pan & Scan zoom is clearer for me.

**Comment by adipose** [comment]
Does it only remember zoom or other PnS selections?

**Comment by butterw** [comment]
AFAIK Pan & Scan zoom only.

**Comment by adipose** [comment]
> AFAIK Pan & Scan zoom only. 

PnS Video Zoom

?

**Comment by butterw** [comment]
I would leave exactly as is. Pan & Scan is accurate here and clearer than PnS.

**Comment by clsid2** [comment]
Just leave it as is

**Comment by adipose** [comment]
Pan and Scan refers to converting usually 2.35:1 video to 4:3 aspect ratio, through a "panning" of the frame left and right to find the most important part of the frame.

Zooming can be used to correct for letterboxing.  It is pretty useless for pan and scan.
