### ISSUE TITLE
Bug: Key Window in Options

### ISSUE THREAD

**Issue by tsubasanouta** [clsid2/mpc-hc#2355]
A black bar appears when you point to the scroll bar of Key window  in Options.
![WS000005](https://github.com/clsid2/mpc-hc/assets/129067724/891b6a5d-8c0a-4908-8ff2-796c42260d6f)

**Comment by clsid2** [comment]
Fixed

**Comment by xLn2** [comment]
MPC-HC (Nightly, 64-bit)
------------------------
Build information:
    Version:            2.1.2.49 (a159a8bd3) and 2.1.2.42 tested both
Operating system:
    Name:             Windows 10 (Build 22H2)
    Version:           10.0.19045 (64-bit)
    GPU:                Intel(R) HD Graphics 630 (driver version: 31.0.101.2125)

Screen resolution: 1920x1080  DPI: 125%

vertical bars in `Options > Player > Keys` and `Menu > Help > Command Line Switches` have problem.
![image](https://github.com/clsid2/mpc-hc/assets/3073922/cddfaa60-0cb8-4903-a05f-b62a3262240c)

On the Keys page vertical bar has trouble at showing itself unless you hover it or scroll down. Sometimes it gliches visually but I didn't reproduce.

Command Line Help window vertical bar has visualy glitches also effect horizontal bar.
![image](https://github.com/clsid2/mpc-hc/assets/3073922/a28bb2ed-ab6a-4a62-beb1-248292b659a0)

![image](https://github.com/clsid2/mpc-hc/assets/3073922/70b01bb6-0e83-475b-a9fd-5cce0274a832)

![image](https://github.com/clsid2/mpc-hc/assets/3073922/296fc0e0-cc5e-4663-bbe1-e47b82c0e9a2)

**Comment by clsid2** [comment]
@adipose

**Comment by xLn2** [comment]
Also effected mediainfo, subresync,  playlist, Mpc-vr>Information, pin info tabs and seperated subresync(i.e) to docking corners.
![image](https://github.com/clsid2/mpc-hc/assets/3073922/96fd2aea-4b6f-40ea-a290-8e5835688951)

Light theme have small issues 
on click it doesn't highlighted white, command line helper and probably other external windows (pin info, information, media info)
![image](https://github.com/clsid2/mpc-hc/assets/3073922/060d9f82-b9e1-4cd3-85a3-e2e42bf88ba7)

unnecessary scrolls: properties (Shift+F10) , command line helper, external windows (renderer settings, pin info, information, media info)
![image](https://github.com/clsid2/mpc-hc/assets/3073922/63376968-5295-4016-9846-ef6a528eadda)

I am sorry for disturbing, just wanted to report before stable release.

**Comment by clsid2** [comment]
Do glitches still happen with 2.1.2.59? I don't see any issues here.

Unneeded scrollbar is not a problem.

**Comment by xLn2** [comment]
It is solved. Thanks.

just this continue

> - Light theme have small issues
> 
> on click it doesn't highlighted white, command line helper and probably other external windows (pin info, information, media info)

**Comment by adipose** [comment]
I think this should fix lite mode issues:

https://github.com/clsid2/mpc-hc/pull/2408
