### ISSUE TITLE
Sub position glitch when changing video frame

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2356]
Sub relative to video frame is enabled.
Latest MPCHC and MPCVR.
Display resolution: 1366x768

https://github.com/clsid2/mpc-hc/assets/98865389/7bffea19-1575-49e2-9337-4014d3bf12d4

**Comment by clsid2** [comment]
Fixed

**Comment by adipose** [comment]
@bibsp can you test if this bug is an issue in the test build here: https://github.com/clsid2/mpc-hc/issues/3423

**Comment by bibsp** [comment]
No issue in your build.
