### ISSUE TITLE
MPC-HC's SaneAR Audio Renderer & MPC Audio Renderer can't play AVI video with zero size ADPCM audio stream

### ISSUE THREAD

**Issue by anjari** [clsid2/mpc-hc#2357]
I want to report a possible bug with the MPC-HC's built-in renderer. I have an AVI file that is encoded with MJPG video and ADPCM audio stream, the MPC-HC (v2.1.2, part of K-Lite codec pack standard v17.9.4) can't play the video file, the player just freezes at the first frame. But VLC and windows media player can play the video. I thought there is compatibility issue with the K-Lite video decoder, but I found out the ADPCM audio stream has zero size, and by default, the MPC-HC's audio renderer is set to "SaneAR Audio Renderer", so I changed the audio render to "MPC Audio Renderer", but the video still can't be played, and then I set the audio renderer to "System Default", now the video file can be played (obviously there will be no sound since the audio stream has zero size).

So although the video file itself has problem (there shouldn't be zero size audio stream in the first place, and if I remove the audio stream from the AVI file, the MPC-HC can play the video with SaneAR Audio Renderer or MPC Audio Renderer), I think the SaneAR Audio Renderer & MPC Audio Renderer must still be able to play the video file with zero size audio stream (just like the VLC and windows media player) by treating the zero size audio stream as non-existent stream.

**Comment by clsid2** [comment]
Sample file is needed.

**Comment by Aleksoid1978** [comment]
It's broken file - audio stream is present but there is no data.
When audio stream is present - it's use for A/V sync via audio renderer.

**Comment by anjari** [comment]
Sorry I can't share the file for privacy reason. It's an old AVI file that I got from someone else. This is the MediaInfo data if it could help:

```
Format                      : AVI
Format/Info                 : Audio Video Interleave
Format settings             : BitmapInfoHeader / WaveFormatEx
File size                   : 3.48 MiB
Duration                    : 18 s 254 ms
Overall bit rate            : 1 599 kb/s
Frame rate                  : 40.977 FPS

Video
ID                          : 0
Format                      : JPEG
Codec ID                    : MJPG
Duration                    : 18 s 254 ms
Bit rate                    : 1 591 kb/s
Width                       : 320 pixels
Height                      : 240 pixels
Display aspect ratio        : 4:3
Frame rate                  : 40.977 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Compression mode            : Lossy
Bits/(Pixel*Frame)          : 0.505
Stream size                 : 3.46 MiB (99%)

Audio
ID                          : 1
Format                      : ADPCM
Codec ID                    : 11
Codec ID/Hint               : Intel
Duration                    : 18 s 254 ms
Bit rate mode               : Constant
Bit rate                    : 32.2 kb/s
Channel(s)                  : 1 channel
Sampling rate               : 8 000 Hz
Bit depth                   : 4 bits
Stream size                 : 71.8 KiB (2%)
```

Note: despite MediaInfo reports 71.8 KiB audio stream size, if I demux the audio stream with VirtualDubMod, it produces zero size file. If I save the audio stream as WAV file, it produces 60 bytes WAV file that's unplayable. Here is the MediaInfo data of the WAV file:

```
Format                      : Wave
Format settings             : WaveFormatEx
File size                   : 60.0 Bytes
Overall bit rate mode       : Constant

Audio
Format                      : ADPCM
Codec ID                    : 11
Codec ID/Hint               : Intel
Bit rate mode               : Constant
Bit rate                    : 32.2 kb/s
Channel(s)                  : 1 channel
Sampling rate               : 8 000 Hz
Bit depth                   : 4 bits
Stream size                 : 0.00 Byte (0%)
```

I had been trying to find other sample AVI file out there with zero audio data size, but I can't find any.

@Aleksoid1978 So this is the limitation of SaneAR Audio Renderer & MPC Audio Renderer? VLC and Windows Media Player still can play the video file directly though. I agree that the video file is broken, but the problem with this situation is normal users might think it's the MPC-HC (or K-Lite Codec Pack) that's broken since the other video players can still play the file.

**Comment by Aleksoid1978** [comment]
It's can try to fix only have problematic file.

**Comment by anjari** [comment]
Here is the sample broken AVI file: [sample.zip](https://github.com/clsid2/mpc-hc/files/13466713/sample.zip)

I managed to create it by combining a sample AVI file without sound (taken from [here](https://file-examples.com/index.php/sample-video-files/sample-avi-files-download/)) and the extracted no-sound WAV file with Avidemux. The audio stream in the video file isn't exactly ADPCM, but PCM, however it still produces same issue.

------

On the other side, I found an interesting feature in MPC-HC. If I have a pure video file (without audio stream) and an audio file with same filename in the same directory, the MPC-HC would automatically load both files and combine them for playing. For example, if I have these two files in same directory:

test.avi (no audio stream)
test.wav

The MPC-HC would load and combine the video and audio stream and play them.

Is there an option in the MPC-HC player to enable/disable this feature?

**Comment by clsid2** [comment]
Options > Playback > Auto-load audio files

**Comment by adipose** [comment]
I reproduced this.  Could it be an attempt to sync the two streams?

I couldn't find any easy way to avoid it, but manual seeking is working.

**Comment by Aleksoid1978** [comment]
Easy way - it's in audioswitcher in **CStreamSwitcherInputPin::NewSegment()** send empty packet. But - sometimes it's working not good :)
https://github.com/Aleksoid1978/MPC-BE/blob/master/src/filters/switcher/AudioSwitcher/StreamSwitcher.cpp#L977-L996

**Comment by adipose** [comment]
I saw it hit newsegment one time only.  Couldn't quite figure out how to prevent it.

**Comment by clsid2** [comment]
The audio renderer provides the reference clock of the graph. Problem is related to that clock not working properly. See `CAudioSyncClock::GetAudioClockTime()`

NewSegment triggers on seek, rate change, or track change.

That empty packet hack is not a real solution.

**Comment by clsid2** [comment]
Unrelated to the issue, but we can replace IAudioClock with IAudioClock2 since Vista is not longer supported.
https://learn.microsoft.com/en-us/windows/win32/api/audioclient/nf-audioclient-iaudioclock2-getdeviceposition

**Comment by Aleksoid1978** [comment]
Audio clock need "start", but without audio packet it's not happened.

**Comment by clsid2** [comment]
I already tried starting it manually in NewSegment. But even then GetPosition stays at 0.

**Comment by Aleksoid1978** [comment]
> I already tried starting it manually in NewSegment. But even then GetPosition stays at 0.

But when this happens, playback starts and the video continues.

**Comment by clsid2** [comment]
It doesn't change anything here. No running playback.

**Comment by Aleksoid1978** [comment]
Commented code in MPC BE is working, playback running.

**Comment by clsid2** [comment]
I was trying to do it without sending empty packet.

**Comment by adipose** [comment]
See how this works.

https://github.com/clsid2/mpc-hc/pull/2436

**Comment by Aleksoid1978** [comment]
The case when there is no data in the audio track is not all. There are also cases when audio packets have a very large delay in relation to video - playback also does not start.

If necessary, I can post a sample.

**Comment by adipose** [comment]
> The case when there is no data in the audio track is not all. There are also cases when audio packets have a very large delay in relation to video - playback also does not start.
> 
> If necessary, I can post a sample.

Sure.

**Comment by clsid2** [comment]
Workarounds in AudioSwitcher are not ideal, since this is an optional filter in the graph. Better is to fix it inside the audio renderers. DirectSound renderer does not have the issue, so it must be possible.

Maybe `start()` device directly during filter connection. And then `reset()` when receiving first sample?

This workaround does seem to work. Does it indirectly cause the reference clock to be changed to base graph?

**Comment by adipose** [comment]
> This workaround does seem to work. Does it indirectly cause the reference clock to be changed to base graph?

Probably so, but I didn't check that.

**Comment by clsid2** [comment]
It doesn't call the renderer clock anymore. So I suspect it switches to System Reference Clock.
https://learn.microsoft.com/en-us/windows/win32/directshow/reference-clocks

**Comment by Aleksoid1978** [comment]
> > The case when there is no data in the audio track is not all. There are also cases when audio packets have a very large delay in relation to video - playback also does not start.
> > If necessary, I can post a sample.
> 
> Sure.

https://disk.yandex.ru/d/LVPm3G8pH3nE-A

**Comment by clsid2** [comment]
Playback does start here, but it jumps directly to 1:52 which must be time of first audio packet.

Larger queue settings in LAV Splitter helps with playback start issue for files where audio is muxed in far from begin of file.

**Comment by Aleksoid1978** [comment]
> Playback does start here, but it jumps directly to 1:52 which must be time of first audio packet.
> 
> Larger queue settings in LAV Splitter helps with playback start issue for files where audio is muxed in far from begin of file.

It's bad, playback must started from begin.

**Comment by clsid2** [comment]
Yes of course it is bad.

**Comment by adipose** [comment]
I couldn't get that video to play at all with any sound output, unless I manually seeked.

**Comment by clsid2** [comment]
Increase the queue sizes in LAV Splitter options.
