### ISSUE TITLE
Cannot render video

### ISSUE THREAD

**Issue by pipja** [clsid2/mpc-hc#2358]
I would like to know what exact codec am I missing for this error below. Thank you very much :)

Here's the dump of the Warning window
```
File Source (Async.)::Output

Media Type 0:
--------------------------
Unknown

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Stream {E436EB83-524F-11CE-9F53-0020AF0BA770}
subtype: Unknown GUID Name {08E22ADA-B715-45ED-9D20-7B87750301D4}
formattype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 0


Media Type 1:
--------------------------
Unknown

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Stream {E436EB83-524F-11CE-9F53-0020AF0BA770}
subtype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
formattype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 0
```

I have attached mediainfo's dump of the same file.
[mediainfo.txt](https://github.com/clsid2/mpc-hc/files/13466054/mediainfo.txt)

**Comment by clsid2** [comment]
Re-install and reset settings.

If it still does not work after that, then I need a link to this file.

**Comment by pipja** [comment]
Video is 3GB, opens fine in MPC-BE and VLC, just can't open in MPC-HC

**Comment by clsid2** [comment]
I can not do anything without having this exact same file.

**Comment by ahmednour12** [comment]
when playing video :file source (async.)::output media type 0: -------------------------- unknown am_media_type: majortype: mediatype_stream {e436eb83-524f-11ce-9f53-0020af0ba770} subtype: unknown guid name {08e22ada-b715-45ed-9d20-7b87750301d4} formattype: time_format_none {00000000-0000-0000-0000-000000000000} bfixedsizesamples: 1 btemporalcompression: 0 lsamplesize: 1 cbformat: 0 media type 1: -------------------------- unknown am_media_type: majortype: mediatype_stream {e436eb83-524f-11ce-9f53-0020af0ba770} subtype: time_format_none {00000000-0000-0000-0000-000000000000} formattype: time_format_none {00000000-0000-0000-0000-000000000000} bfixedsizesamples: 1 btemporalcompression: 0 lsamplesize: 1 cbformat: 0
