### ISSUE TITLE
Please help msix packaging

### ISSUE THREAD

**Issue by atplsx** [clsid2/mpc-hc#2359]
I'm trying to package the application using the Microsoft MSIX packaging tool, but it doesn't work. Can you help me. Best regards

**Comment by clsid2** [comment]
I do not want MPC-HC to be added to the Microsoft store.

I will take legal action against you.

**Comment by atplsx** [comment]
I don't want to add it to the store, I asked for help for my own personal use. I'm not a developer either.
If you find it in the microsoft store, please let me know. I don't want to be rude, but you immediately acted prejudiced.
Also, I didn't do anything illegal. I don't understand why you are so angry.
I just wanted help. But I'm sorry, I'm sorry, it was a mistake to ask for your help.
