### ISSUE TITLE
If you click a favorite involving the current file, don't reload the file.

### ISSUE THREAD

**Issue by dandoor** [clsid2/mpc-hc#2363]
Just jump to the clicked favorite timestamp, the same way when you manually navigate through the seek bar.

**Comment by adipose** [comment]
Not sure I agree.  I typically use recent files for this scenario, but for example if I turn libass on or off, I need to reload to take effect.  It might be useful to reload the file being clicked?

@clsid2, advanced option or default behavior, or leave as is?

**Comment by clsid2** [comment]
For simple reload we have Ctrl+E hotkey.

And to quickly jump back to certain point, A-B repeat can be used, even with favorites.
