### ISSUE TITLE
Broken seeking after reaching end of file

### ISSUE THREAD

**Issue by Molkree** [clsid2/mpc-hc#2366]
After playback reaches the end and I press the left arrow to seek backwards, the image stays still but the sound correctly seeks backwards.

In [this video](https://drive.google.com/file/d/1QHP-vdWxuqXxpF3IRRVMElJW39C-lF2y/view?usp=sharing) you can see that the image doesn't move but the sound still works.

Attaching sample below but it works with all videos I tried:

https://github.com/clsid2/mpc-hc/assets/12860284/3c4552b9-5a3c-46f3-aeaa-bc49abd9a9f7

**Comment by clsid2** [comment]
Works properly here.
Player should go into paused state when reaching end of video. That doesn't seem to happen in your video.

It is likely a bug in your graphics driver related to hardware decoding. I have seen these symptoms before for some people with Intel GPUs.

**Comment by Molkree** [comment]
> Player should go into paused state when reaching end of video. That doesn't seem to happen in your video.

It is what happens, I pressed Spacebar to start playing after seeking.

And yes, you are right, it's Intel issue again :/
For anyone else encountering this in Win11 you can go to Settings->Display->Graphics->MPC-HC->Change graphics preference to High performance to use your discrete GPU. It does say "This GPU preference may cause undesired behaviour for the app." though. Is it not advisable to use it?
Is there a way to change hardware device from within MPC-HC?

P.S. Alright, MPC-HC actually [crashed](https://drdump.com/UploadedReport.aspx?DumpID=124616858) when I played my second video while using discrete GPU 🥲 so I guess it really is not the best idea to switch.

**Comment by butterw** [comment]
I had a similar issue on Win10:
"With intel i3-12100 (uhd730), I have following issues with mpc-hc (all versions) in default evr-cp mode:
1) after reaching the end of the video, when seeking back the picture remains frozen and only the sound plays. I need to Stop to return to normal operation."

The issue also occured with hw decoding disabled.

This solved it for me:
rename mpc-hc64.exe to mpc.exe.

**Comment by clsid2** [comment]
If renaming helps, then that means that the Intel driver is using some hidden application profile that does bad things.

Report the problem to Intel or Microsoft:
https://arstechnica.com/gadgets/2022/08/intel-turns-to-code-translation-to-run-old-directx9-games-on-its-newest-gpus/

I recommend using MPC Video Rendererer:
https://github.com/clsid2/mpc-hc/releases/tag/2.1.2
