### ISSUE TITLE
Winget Package Outdated

### ISSUE THREAD

**Issue by rahaaatul** [clsid2/mpc-hc#2367]
I don't know where to post this but MPC-HC is outdated in [here](https://winget.run/pkg/clsid2/mpc-hc).

Last update was 2.0.0.

**Comment by rahaaatul** [comment]
Oh, I maybe wrong, It shows `2.0.0` but downloaded and installed `2.1.2`.

**Comment by rahaaatul** [comment]
Oh, I maybe wrong, It shows 2.0.0 but downlload and installs 2.1.2

**Comment by clsid2** [comment]
I am not maintaining that or any other third party download stuff.
