### ISSUE TITLE
Drag and Drop feature not supported on URL

### ISSUE THREAD

**Issue by mohitmeanslove** [clsid2/mpc-hc#2369]
Whenever you drag and drop any URL on media player then it doesn't work.

**Comment by bibsp** [comment]
Place latest [yt-dlp.exe](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases) inside mpchc installation folder.

**Comment by mohitmeanslove** [comment]
> Place latest [yt-dlp.exe](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases) inside mpchc installation folder.

I am not talking about youtube video. I am not talking about drag and drop feature.

Please drag and drop any online streaming link in mpc-hc.It won't work
Here is one example : http://playertest.longtailvideo.com/adaptive/wowzaid3/playlist.m3u8

**Comment by clsid2** [comment]
Works perfectly fine here with that link.

**Comment by xLn2** [comment]
Dragging Url to media player works fine, but selecting url and drag drop doesn't work (dragging from selected text of browser address bar works in mpc-hc). Mpc-be handles plain text drag drop behavior.

**Comment by clsid2** [comment]
I have added support for plain text
