### ISSUE TITLE
Auto-zoom 

### ISSUE THREAD

**Issue by thankuverymuch** [clsid2/mpc-hc#237]
Auto Fit (Larger Only) is doesn't work.
Always keep maximization.
But Auto Fit is no problem.
Only (Larger Only) is a problem.

* I think it's a resolution problem.
1920x1080 video is working
1920x800 video is not working

Thank you.

mpc-hc.1.9.0.x64.zip
Win 10 LTSC 1809 x64
1050Ti (441.87-desktop-win10-64bit)

**Comment by clsid2** [comment]
What is the size of your screen?
At which size is the video displayed, and what size did you expect?

You may need to increase the "auto fit factor" value.

**Comment by thankuverymuch** [comment]
FHD (1920x1080)
I set the Auto Fit (Larger Only) 75%

1920x1080 video is 75%
1920x800 video is 100%

Does the width of the image resolution not affect?

**Comment by clsid2** [comment]
75% means it uses at most 75% of the width and height of your screen.

If your intention is to maximize the window, then you should use fullscreen or the maximize window button.

**Comment by thankuverymuch** [comment]
I want to see it run in 75% window size when I click on the 1920x800 video. But it turns on 100% size.
1920x1080 video runs at 75% size. Works fine.

Auto Fit (Larger Only) = Only by height?
I think the 1920 resolution video should also be reduced to 75%.

**Comment by thankuverymuch** [comment]
Oh.. I understand now.
I think it's because of the size of the seek bar in the mpc-hc window.

1920x1080 + seek bar size (22pixel) = 1920x1102 (lager)
1920x800 + seek bar size (22pixel) = 1920x822 (small)

Wouldn't it be more reasonable to reduce the resolution to 75% if the resolution is the same even if it doesn't exceed the resolution?

**Comment by clsid2** [comment]
I have changed the logic to always resize if it is larger than the specified percentage.

**Comment by thankuverymuch** [comment]
Thank you very much.
