### ISSUE TITLE
mpd file format not supported

### ISSUE THREAD

**Issue by mohitmeanslove** [clsid2/mpc-hc#2370]
MPC-HC doesn't seems to support mpd format. I am giving a link as an example. This link works on network stream player(Android Software) but not on on MPC-HC

Link: https://bpprod5linear.akamaized.net/bpk-tv/irdeto_com_Channel_252/output/manifest.mpd?%7CdrmScheme=clearkey&drmLicense=http://rftv.wtf/tp/rjiptv.php?contentID=24&key

**Comment by clsid2** [comment]
Look like DRM protected shit.

That is not supported.

**Comment by mohitmeanslove** [comment]
> Look like DRM protected shit.
> 
> That is not supported.

But It works on network stream player(https://play.google.com/store/apps/details?id=com.genuine.leone&hl=en&gl=US) . So If possible, please add this support in MPC as well

**Comment by clsid2** [comment]
NO means NO !!!!
