### ISSUE TITLE
Tooltips in subtitle downloader broken

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2372]
@adipose

**Comment by adipose** [comment]
What's the problem?  It seemed to be about the same in dark/classic.

**Comment by clsid2** [comment]
They are not showing anymore here. I think since the multi-select patch.

I am talking about the tooltip that shows list of video filenames (if there are multiple) when you hover above a search result filename.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2406

I think this fixes it.  When this was changed to use CPlayerListCtrl, it required some code changes to work properly.  Now that it inherits from CListCtrl (indirectly), this old commit can be mostly reverted.  So far I don't see any tooltip issues after doing it.
