### ISSUE TITLE
Default Reset Rate (Ctrl+ R) combo doesn't work

### ISSUE THREAD

**Issue by img02** [clsid2/mpc-hc#2375]
'Reset Rate' key works when reassigning to something else. I've tried 'Alt + N', 'R'

It seems that it's the 'Ctrl + R' combo that doesn't work, I tried assigning it to other functions and none of them work with that combo.

**Comment by clsid2** [comment]
Ctrl+R works fine here.

Some other application on your computer might already be using it.
