### ISSUE TITLE
Keep playback speed/rate the same after restart.

### ISSUE THREAD

**Issue by Slyceth** [clsid2/mpc-hc#2376]
The window size has no problem staying like before, but the playback speed always goes back to 1x even though I want every video to be booted up at 2x speed.

**Comment by Slyceth** [comment]
Please don't close it. There is no reason NOT to have this feature, it is a basic feature of VLC, MX Player, browser extensions and many more. It is very simple to implement, just like how the window size defaults back to what I had before, make the speed start at a number by editing an ini file value or number "playback speed"

I never ever play any video at less than 1.25x speed. This program is perfect in every way except for this, as even bigger creators can't use this program to look through their editing files, like DarkViperAU for example, as you can't look through hundreds of files at less than 1.8x speed.
Want a reason why speed is important? There is more scientific-ish info here: https://github.com/igrigorik/videospeed

**Comment by clsid2** [comment]
Request denied.
