### ISSUE TITLE
Internal Subtitle Rendered Fails to Draw non-standard Dash

### ISSUE THREAD

**Issue by gashtal** [clsid2/mpc-hc#2379]
MPC-HC's internal subtitle renderer fails to correctly draw the non-standard dash used in the attached subtitle file, and draws a box in its place instead. The dash seems to be the result of bad OCR, but I would expect it to be displayed correctly nonetheless. The libass renderer draws the dash correctly, but flickers rapidly on my system (incompatible with high-refresh rate monitors?) and as such, is not usable.

![image](https://github.com/clsid2/mpc-hc/assets/27990818/87ff964e-7567-4b4c-9051-648812111ff9)

[test.zip](https://github.com/clsid2/mpc-hc/files/13533767/test.zip)

**Comment by clsid2** [comment]
A square means that the character is not part of the font that is used.

Fix your subtitle file or use a different font.

This will can NOT and will NOT be fixed due to how GDI works. I am NOT debating it.
