### ISSUE TITLE
Can you please bring back 0 option for RememberPosForLongerThan ?

### ISSUE THREAD

**Issue by tealkami** [clsid2/mpc-hc#2380]
Hi, I noticed that in 2.1.2 RememberPosForLongerThan can't be set to 0, lowest is 1. 
Can you please bring back the option to set it up to 0 as it was in 2.0.0 ?
I am asking for the option for 0, **not** changing **the default** 5

**Comment by clsid2** [comment]
Why you need it for something less than 1 minute?
