### ISSUE TITLE
MPC-HC not releasing file locks

### ISSUE THREAD

**Issue by heliosyne** [clsid2/mpc-hc#2384]
If I press Ctrl-C to close the file, or exit MPC entirely, it will leave file locks that prevent file deletion. The locks are visible in smbstatus output on the server. The rename workaround does not work. The only fix is to delete the file from the server side. I can open those same files in any other app, verify it has a lock, and as soon as they close the file or exit, the lock is released. MPC always leaves its locks behind.

I've read some of the older issues about this problem, and all of those claim it has been fixed, but I'm running 2.1.2 and it's still happening.

Based on those older issues, I downgraded to 1.9.4 as a test and that version doesn't have this problem for me either.

It appears that whatever was fixed in 1.9.x has regressed again in 2.x.

**Comment by clsid2** [comment]
Deleting works fine here after closing file.

With Windows resmon.exe tool I see that file handle is gone after closing.
