### ISSUE TITLE
Some OSD notifications issue

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2385]
![image](https://github.com/clsid2/mpc-hc/assets/3073922/e1167815-8acf-437b-847c-2f0564483f0d)
These Video Frame options (don't know first three) has OSD text but cannot show with shortcut key and through menu, these osd text only visible when using "video frame switch zoom"  assigned key.

**Comment by clsid2** [comment]
That seems intentional, because if you click in menu you know what you did, whereas with switch it toggles through modes.

I am not changing it.
