### ISSUE TITLE
Subtitle not loading when jump forwards / backwards

### ISSUE THREAD

**Issue by Hqndler** [clsid2/mpc-hc#2387]
Using version 2.1.2 (2b85bfdeb), Internal subtitle renderer with libass. If you jump forwards by 5s and you land on a middle of a subtitle, the subtitle won't show, see below.
![just an example](https://github.com/clsid2/mpc-hc/assets/69089935/f40a954e-575a-42c4-af0b-2319b8bca66d)
Every line of subtitle are between bracket, let's say you land at 19:50, this line will not show up, but if you land at 19:48,5 just before, the line will be shown... Hope my explaination was clear. 
This also seems to happen only with ass files (not srt), testing with libass deseabled and xyfilter is fine.

**Comment by clsid2** [comment]
Provide a sample file.

It is likely a libass bug, so there is nothing I can do about it.

**Comment by NBruderman** [comment]
> Using version 2.1.2 (2b85bfdeb), Internal subtitle renderer with libass. If you jump forwards by 5s and you land on a middle of a subtitle, the subtitle won't show, see below.
> ![just an example](https://github.com/clsid2/mpc-hc/assets/69089935/f40a954e-575a-42c4-af0b-2319b8bca66d)
> Every line of subtitle are between bracket, let's say you land at 19:50, this line will not show up, but if you land at 19:48,5 just before, the line will be shown... Hope my explaination was clear. 
> This also seems to happen only with ass files (not srt), testing with libass deseabled and xyfilter is fine.

Can you see if you have the same issue with mpv player?

**Comment by Hqndler** [comment]
I mean you can test yourself but no, not a problem with mpv. I you want a file to test, you can download anything that have subtile... I don't know it's not a specific problem with a specific ass file...

**Comment by clsid2** [comment]
This problem can also happen with old files that do not have subtitle cue data. In that case it also happens without libass, and it that case it is also not a bug.

I need a sample and timestamp for which you have verified that the problem happens only with libass. Until then, this issue will be closed.

Also, get the latest development build first, as that has some fixes.

**Comment by Hqndler** [comment]
https://github.com/clsid2/mpc-hc/assets/69089935/1ab60fe6-b41c-47d6-b4c4-11a39875c295

This was on the latest dev build.

So in this example you can cleary see that there's a line missing... But to your credit this is really inconsistent. I think this inconsistency leads me to think that this only impact libass rendering but this problem also occurs with other renderer so I don't know, the behavior is strange.

Testing with mpv with the same settings (same video, same timing and same time jump), no problem here but I did notice some lines not being displayed either, but I have the feeling that is much harder to have this problem with mpv.

**Comment by clsid2** [comment]
Remux the file with MkvToolNix and test if it works better then.

If you seek to a spot AFTER where the relevant subtitle line data is interleaved into the file, then the data is unavailable (in old files or stuff muxed by old tools). The Matroska container supports Cue elements that specify where data can be found inside the file. When such information is provided for the subtitle track, then the splitter can gather it.

**Comment by Hqndler** [comment]
The ass was already muxed... After extracting and remuxing it with mkvtoolnix **v81.0** there are no problem to the first glance. The ass was muxed with mkvtoolnix **v4.9.1** so maybe something have change in 10 years with matroska or mkvtoolnix...

**Comment by clsid2** [comment]
Old versions did not write subtitle Cue information, as written above.
