### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by polosud** [clsid2/mpc-hc#2388]
Hi, I load a new skin in the main folder but it doesn't work anymore, how can I solve it?
[toolbar.zip](https://github.com/clsid2/mpc-hc/files/13559225/toolbar.zip)

**Comment by xLn2** [comment]
https://github.com/clsid2/mpc-hc/issues/382

> In this case you need to use one of these filenames:
> toolbar_dark.bmp [grayscale]
> color_toolbar_dark.bmp [colored buttons]
> toolbar_light.bmp [grayscale]
> color_toolbar_light.bmp [colored buttons]
> 
> Instead of BMP file you can also use PNG or SVG.
> BMP/PNG are fixed size. SVG toolbars are DPI scaled and size can be customized:
> Options > Advanced > DefaultToolbarSize

**Comment by polosud** [comment]
very kind everything resolved, where can I download other skins? thanks

**Comment by butterw** [comment]
One of the fluent design toolbars from 2021: color_toolbar_dark.svg
![color_toolbar_dark](https://github.com/clsid2/mpc-hc/assets/408915/bde7ce17-fa7b-499f-88be-3a2d4e34b681)
