### ISSUE TITLE
Some H264 videos wont play with any of the renderers

### ISSUE THREAD

**Issue by r3pr3z3nt** [clsid2/mpc-hc#2389]
They start paused, you can skip around, picture will change, but the video cant be played, just stays paused. No sound either.

Example:
Video: MPEG4 Video (H264) 1920x1080 30fps 5954kbps [V: h264 high L5.2, yuv420p, 1920x1080, 5954 kb/s]
Audio: AAC 48000Hz stereo 130kbps [A: aac, 48000 Hz, stereo, 130 kb/s]

**Comment by clsid2** [comment]
Usually that means that there is something wrong with the file. Remuxing it with MkvToolNix can possible fix it.

I can not provide any further help without a link to a sample file.

**Comment by r3pr3z3nt** [comment]
VLC plays it no problem.  I had it with multiple files recently - I can provide you with a link to a torrent of the whole file, but Im not sure if thats ok with the rules here...

**Comment by r3pr3z3nt** [comment]
MKVToolNix made it work. You were right. Big thanks!

**Comment by clsid2** [comment]
A torrent link is fine.

**Comment by r3pr3z3nt** [comment]
Both of these, two different releases of the same event. Had that issue with the previous events prelims too.
https://www.magnetdl.com/file/5873363/ufc.on.espn.52.dariush.vs.tsarukyan.prelims.1080p.web-dl.h264.fight-bb/
https://www.magnetdl.com/file/5873356/ufc.on.espn.52.prelims.1080p.web-dl.acc.2.0.h264-shreddie/

**Comment by clsid2** [comment]
Workaround:
Options > Internal Filters > Splitter > Queue Settings
With huge values such as 2048MB and 40000 packets it will play.

This is an indication that the audio in the file is badly muxed.

**Comment by r3pr3z3nt** [comment]
Thank you for your prompt solution, settings changed!
