### ISSUE TITLE
Larger Status bar compared to 1.8.8

### ISSUE THREAD

**Issue by benswolo** [clsid2/mpc-hc#239]
1.9.0 has a larger ("wider") status bar size compared to 1.9.0. Is there any way to return this to the previous size? Even better, is there a way to make the status bar + seek bar + controls disappear if inactive, like how you can in the "hide controls in fullscreen" option?

**Comment by clsid2** [comment]
You can press 1 to hide everything except the video. Press 3 to reset to normal view.

The width depends on the size of the toolbar buttons. You can change that in: Options > Advanced

**Comment by clsid2** [comment]
Options > Advanced > HideWindowedControls

Then it will show a black bar instead of the controls, and show controls only when hovering the mouse over it.
