### ISSUE TITLE
Random freezing when watching video.

### ISSUE THREAD

**Issue by Jiur13** [clsid2/mpc-hc#2391]
I recently built a new PC and for what it's worth this one is AMD based instead of NVIDIA, however I am now having an issue with watching videos with MPC. Basically, what will happen is that whenever I'm watching something in fullscreen, it will randomly freeze during the video, but the sound will continue to play - exiting fullscreen is enough to unfreeze the video, but it's very annoying to have to double click to exit fullscreen then double click to enter it again.

I thought it might have been because of MADVR, but it still happens using the default renderer after a fresh install. I've been using another player, MPV in the meantime and the issue does not occur with that, so it does seem like an issue with MPC-HC itself.

If you need the rest of my specs or anything just ask, but I'm currently using a 7800X3D and a RX7800XT.

**Comment by clsid2** [comment]
I don't have any issues, neither do millions of others. Can't reproduce so can't fix. It is likely a driver issue.

You can try MPC Video Renderer from our downloads page. That has DirectX11 rendering option. Maybe that works better on your system. Switch hardware decoder to D3D11 as well.
