### ISSUE TITLE
Question about playback speed options

### ISSUE THREAD

**Issue by geahad** [clsid2/mpc-hc#2392]
I'll appologize in advance if this is a stupid question, but I honestly coudn't find an answer online...

Currently, one can increase playback speed in factors of 2x, 4x etc... Is it possible to configure the player to do that in smaller incements, like on youtube? i.e. 1.25x or 1.50x?

Thank you in advance for your patience!

**Comment by xLn2** [comment]
`View > Options > Playback > Control > Speed step`

![image](https://github.com/clsid2/mpc-hc/assets/3073922/74b9b693-c3d3-4a9e-a254-be5823a85fcd)

You can change value to like 5% or 10% which is fit your needs.

**Comment by clsid2** [comment]
And also:
Menu > play > Playback Rate

**Comment by geahad** [comment]
Thank you!
