### ISSUE TITLE
unable to maintain aspect ratio during window resize.

### ISSUE THREAD

**Issue by KyleSanderson** [clsid2/mpc-hc#2394]
1080p panel, 4k video.

It's impossible to have the AR correct in a window. (I watch in 2/compact)

I seem to remember on MPC-HC there was a way to drag from the corner and it was always maintained, I don't know what happened but it seems like something removed it?

**Comment by clsid2** [comment]
Options > Player > Limit video proportions on resize

But video AR should already be preserved without that, unless you changed video frame setting. So I am assuming your are talking about Window AR.
