### ISSUE TITLE
subtitles too bright when watching hdr content with MadVR

### ISSUE THREAD

**Issue by Kas152** [clsid2/mpc-hc#2395]
Hi guys,

I'm using MPC with MadVR and when watching HDR content I notice that the subtitles are way too bright. This is especially bothersome at night. When using MPC video renderer there is a setting to change the brightness of the subs, but in MadVR I cannot find it. Is there a solution to this? 
I saw on other forums that this issue is not unheard of. Any help is highly appreciated.

Cheers.

**Comment by clsid2** [comment]
No proper solution for madvr.

Adjusting the color of the subtitles in the settings helps a bit. Use a greyer color.
