### ISSUE TITLE
Any keboard shorcuts for recent files?

### ISSUE THREAD

**Issue by harmandmen** [clsid2/mpc-hc#2399]
Maybe it's already there and I simply didn't find it, but It seems to me that there is no way to quickly re-open, with a keyboard shortcut, one of the "recent files" (for example, to continue viewing from the last point reached).

The usual keyboard-way to launch menu commands (_Alt+underlined letters_) seems to be non available for that task.
Obviously it's not a prominent issue, but maybe it could be useful to frequent users of the program.

Can keyboard shortcuts be customized to achieve such a goal, for example assigning a combination like _Alt+R+1_ to the first file in the "recent" list?

**Comment by butterw** [comment]
(O)ptions > Player \ History > x Remember Last Playlist 
you can reopen last opened file by pressing play (ex: SPACE shortcut) or left-clicking after launching mpc-hc.

**Comment by redfoxcz** [comment]
I also need this functionality - a keyboard shortcut for opening the list of recent files.
It is not about playlists, I never use one. Play only opens the last one. This is not sufficient.

I hoped that somebody would add this shortcut in the future, but it did not happen.

**Comment by clsid2** [comment]
Alt F F
