### ISSUE TITLE
DVD playback no longer works

### ISSUE THREAD

**Issue by koitsu** [clsid2/mpc-hc#24]
Since moving from 1.7.13 to 1.8.1 on Windows 7 Ultimate 64-bit, I've found that DVD playback no longer works -- MPC-HC gets stuck in an infinite loop after opening the disc.  For me the issue is 100% reproducible regardless of disc (I tried several).  I also tried with a fresh/empty mpc-hc64.ini; no difference.  Reverting back to 1.7.13 fixes the problem.

Methodology:

1. Insert DVD
2. Launch MPC-HC 1.8.1 x64
3. File -> Open DVD/BR...
4. Select root of disc, then click Select Folder
5. MPC-HC resizes the window (normal), status bar says "Opening...", then the application locks up.  I should note the window resize goes to a 4:3 aspect ratio before locking up, even for films that use a 16:9.  (For 1.7.13 with 16:9 films, usually it goes to 4:3 followed quickly by 16:9 and the status bar says "Playing [H/W]")
6. After a short while, title bar contains "(Not Responding)", after which Windows lets you force-close the program

If there's anything I can do to help debug the issue, let me know.  Thank you!

**Comment by nbmrjuhneibkr** [comment]
Can confirm, same thing happens to me.

**Comment by clsid2** [comment]
Will be  fixed soon. It is caused by a change in LAV Filters.

**Comment by koitsu** [comment]
Confirmed: 1.8.2 fixes the problem. Thank you so much!
