### ISSUE TITLE
Delete spam tickets in trac.mpc-hc.org

### ISSUE THREAD

**Issue by IsaacHub** [clsid2/mpc-hc#240]
Hi, I was shocked to see spam tickets in https://trac.mpc-hc.org/ , since there is no place to report this, I'm posting here,

List of some spam tickets:

https://trac.mpc-hc.org/ticket/6644
https://trac.mpc-hc.org/ticket/6642
https://trac.mpc-hc.org/ticket/6641
https://trac.mpc-hc.org/ticket/6640

screenshot of one of them

![Screenshot_7](https://user-images.githubusercontent.com/20126441/72687918-8f78a300-3b28-11ea-92f3-178d870cb711.png)

**Comment by ValZapod** [comment]
So what? We in chromium also do not delete spam just close it. https://bugs.chromium.org/p/chromium/issues/detail?id=1040541#c_ts1578588139.

**Comment by clsid2** [comment]
I don't have any control over Trac or any of the other content on mpc-hc.org
