### ISSUE TITLE
Thumbnails appear pixelated

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#2400]
Hi Clsid2,
first of all, thanks for continuing the development of this great player.
I just wanted to report something I noticed which seems odd since MPC-BE, with the same setting, does it well.
I posted two thumbnails of the same file, with the same settings, one made by MPC-HC, the other made by MPC-BE. I chose a sample video which exposes the issue very well. My OS is Windows 10 Pro x64, the video renderer is MadVR, but even wth other renderers the issue stays there.
![fish_-_62123 (Original) mp4_thumbs](https://github.com/clsid2/mpc-hc/assets/61087558/7b1acd2e-8b56-40bc-ab8e-4e3d8c3bde69)
![fish_-_62123 (Original) mp4_thumbs_ 2023 12 09_12 16 44](https://github.com/clsid2/mpc-hc/assets/61087558/4856a81f-f474-4204-8cec-5c497eb487c9)

**Comment by clsid2** [comment]
Give a link to that video file.

**Comment by ghost** [comment]
It happens to every video, this one just exposes it more. BTW, 

https://github.com/clsid2/mpc-hc/assets/61087558/1948955e-63bc-43db-b150-7b4698cd4358

**Comment by clsid2** [comment]
Seems to be due to scaling filter used:
https://github.com/Aleksoid1978/MPC-BE/blob/f9f8d22f89ed27cf3eb22d78c37885237c60f573/src/apps/mplayerc/ThumbsTaskDlg.cpp#L218

**Comment by v0lt** [comment]
To get the correct result when the image is greatly reduced, you need to use convolution.
Interpolation algorithms will perform poorly for reduction. This is especially noticeable in video frames with sharp edges.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2802

Similar method as mpc-be, but I used `stbir_resize` as we already have it in the project.
