### ISSUE TITLE
Subtitle issue: Audio Delay crash

### ISSUE THREAD

**Issue by kamaldarwish** [clsid2/mpc-hc#2401]
When I download from the software and try to adjust the audio delay, the software stops show the subtitle and have to close and open the software. the very old versions was working fine. I tried using Arabic subtitles.
below is the details of the software i am using:

MPC-HC (64-bit)
---------------

Build information:
    Version:            2.1.2 (2b85bfdeb)
    Compiler:           MSVC v19.29.30152
    Build date:         Nov  9 2023

LAV Filters:
    LAV Splitter:       0.78.0.0
    LAV Video:          0.78.0.0
    LAV Audio:          0.78.0.0
    FFmpeg compiler:    MinGW-w64 GCC 12.3.0

Operating system:
    Name:               Windows 10 (Build 22H2)
    Version:            10.0.19045 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
    GPU:                Intel(R) HD Graphics Family (driver version: 20.19.15.4531)

**Comment by clsid2** [comment]
Works normal here.
