### ISSUE TITLE
Lite debug build issue?

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#2402]
Can't figure out why this continues to happen with lite debug build.  Regular debug is fine.

![image](https://github.com/clsid2/mpc-hc/assets/3324395/1d889cea-e926-4667-8d2e-aebfcc1bed36)

**Comment by adipose** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/3324395/1e19eb11-7674-4a34-9dc8-061cf44b5265)

**Comment by clsid2** [comment]
`subtitlesDefStyle` seems to have some bogus values in the struct. I am not sure why. It should have been properly initialized at that point, since settings are loaded before creating mainframe.

**Comment by adipose** [comment]
Yeah, the strings are all wiped out.  But in debug build, they are fine...

**Comment by adipose** [comment]
Do you get the same error btw?

**Comment by clsid2** [comment]
Yes, I get the same error.

If I inspect `this` inside `SubRendererSettings CAppSettings::GetSubRendererSettings()` then there are a few more string members that have "Error reading characters of string". Members that did have proper values earlier when settings are read.

Weird.

**Comment by adipose** [comment]
It must be memory corruption. Mediainfo?

**Comment by clsid2** [comment]
I don't have mediainfo dll in the debug folder. I don't see how Lite build would behave differently.

**Comment by adipose** [comment]
Ok.  Well, just guessing based on recent commits.

Lavfilters is compiled in differently for LITE. Maybe something there.

**Comment by clsid2** [comment]
Same happens with LAVFilters disabled.

When is last time build succeeded?

**Comment by adipose** [comment]
Not sure but it was fine when I submitted the patch for scrollbars.

**Comment by adipose** [comment]
One other thing is I temporarily updated all submodules to later builds.  Not sure if that masked any issues.

**Comment by clsid2** [comment]
It is related to 8c8572b. Crash is gone if I disable the new entries in `InternalFilterConfig.h`

**Comment by adipose** [comment]
Initialization on the way 2092 maybe?

**Comment by clsid2** [comment]
What do you mean?

Out of the 6 new ones, I can enable any individual one without problem. As soon as I enable 2 or more, crash happens.

I don't see anything wrong or different compared to regular debug build.
If I use `#define INTERNAL_FILTERS_OTHER 0` also for regular debug build, then it still works fine.

**Comment by clsid2** [comment]
I am thinking this is some weird compiler bug. Or some alignment issue.

If I increase `TRA_LAST` to 50, then problem is gone.

43 to 44 = ok
45 to 49 = crash
50 to 52 = ok
53 to 57 = crash
58 to 60 = ok
61 = crash

Seems like a pattern of 3 good 5 bad.

**Comment by clsid2** [comment]
This solves it. But I am clueless why alignment is messed up only in Lite build.

`STSStyle alignas(16) subtitlesDefStyle;` in `AppSetting.h`

But funny thing is that if I add alignas to for example `m_RenderersSettings` too, then it suddenly breaks again.

**Comment by adipose** [comment]
Maybe has to do with the linking process.

I saw some lib built without debug symbols (freetype?).

**Comment by clsid2** [comment]
Why does Lite build need all libs explictly specified in linker options?

**Comment by adipose** [comment]
I think they are not included as referenced projects.  It builds much faster.

I haven't ever looked at it super carefully.  But if you add a lib to the main project, you have to link it manually or it doesn't link it in.

**Comment by adipose** [comment]
Here's my theory:

The enums in FilterEnum are different sizes depending on build properties.  As a result, the Lite build has a smaller enum than the Full build, but the libraries it links against may have had a different (full) size.  The enum size actually changes the index of the individual filters , meaning it may grab the wrong one, or worse, grab in uninitialized space in `SrcFiltersKeys` or `TraFiltersKeys`.

By removing all the `#if` statements in FilterEnum, the enum size will not change.  I don't think it actually is a problem as other code that might reference these areas is also `#if` controlled:

```
#if INTERNAL_SOURCEFILTER_CDDA
    if (src[SRC_CDDA] && !IsPreview) {
        pFGF = DEBUG_NEW CFGFilterInternal<CCDDAReader>();
        pFGF->m_extensions.AddTail(_T(".cda"));
        m_source.AddTail(pFGF);
    }
#endif
```

I removed all the #if from `FilterEnum.h` and it stopped crashing (after reverting your fix).

**Comment by clsid2** [comment]
It also happens with a full clean build. Enum size has effect on the alignment, see a couple posts above.

**Comment by adipose** [comment]
> It also happens with a full clean build.

I had done several clean full debug builds but never got the issue.  How did you duplicate it on a full build?

**Comment by clsid2** [comment]
Restore all #if and then do `SRC_LAST = 30` in the enum. That also avoids triggering the bug. You can experiment with the size to see the effect.

I get it on rebuild solution.

**Comment by adipose** [comment]
Well this is truly bizarre.  If you do SRC_LAST=25 (the default value in Lite), that also fixes it in Lite mode.

**Comment by adipose** [comment]
OK, so here is the result of testing the value using a static assert in Lite mode:

`static_assert(SRC_LAST <= 25, "Enumeration constant exceeds 25.");`

```
Build started...
1>------ Build started: Project: BuildConfig, Configuration: Release Win32 ------
2>------ Skipped Build: Project: AsyncReader, Configuration: Debug Win32 ------
2>Project not selected to build for this solution configuration 
3>------ Skipped Build: Project: BaseSplitter, Configuration: Debug Win32 ------
3>Project not selected to build for this solution configuration 
4>------ Build started: Project: ffmpeg, Configuration: Debug Win32 ------
5>------ Build started: Project: VideoRenderers, Configuration: Debug Win32 ------
6>------ Skipped Build: Project: BaseSource, Configuration: Debug Win32 ------
6>Project not selected to build for this solution configuration 
7>------ Build started: Project: Subtitles, Configuration: Debug Win32 ------
1>gccver=13.2.0
1>        1 file(s) copied.
1>        1 file(s) copied.
1>        1 file(s) copied.
1>Microsoft (R) Library Manager Version 14.29.30148.0
1>Copyright (C) Microsoft Corporation.  All rights reserved.
1>
1>LINK : warning LNK4014: cannot find member object lib32_libmingwex_a-strtoimax.o
1>        1 file(s) moved.
1>        1 file(s) copied.
1>Microsoft (R) Library Manager Version 14.29.30148.0
1>Copyright (C) Microsoft Corporation.  All rights reserved.
1>
1>LINK : warning LNK4014: cannot find member object lib64_libmingwex_a-strtoimax.o
1>        1 file(s) moved.
1>Done building project "BuildConfig.vcxproj".
8>------ Skipped Build: Project: DSMSplitter, Configuration: Debug Win32 ------
8>Project not selected to build for this solution configuration 
9>------ Skipped Build: Project: CDDAReader, Configuration: Debug Win32 ------
9>Project not selected to build for this solution configuration 
10>------ Skipped Build: Project: CDXAReader, Configuration: Debug Win32 ------
10>Project not selected to build for this solution configuration 
11>------ Skipped Build: Project: VTSReader, Configuration: Debug Win32 ------
11>Project not selected to build for this solution configuration 
12>------ Skipped Build: Project: DeCSSFilter, Configuration: Debug Win32 ------
12>Project not selected to build for this solution configuration 
13>------ Skipped Build: Project: RARFileSource, Configuration: Debug Win32 ------
13>Project not selected to build for this solution configuration 
5>RenderersSettings.cpp
7>STS.cpp
7>SubtitleInputPin.cpp
5>C:\dev\mpc-hc\src\mpc-hc\FilterEnum.h(123,24): error C2338: Enumeration constant exceeds 25.
7>C:\dev\mpc-hc\src\mpc-hc\FilterEnum.h(123,24): error C2338: Enumeration constant exceeds 25. (compiling source file STS.cpp)
4>make: Nothing to be done for 'all'.
5>Done building project "VideoRenderers.vcxproj" -- FAILED.
7>C:\dev\mpc-hc\src\mpc-hc\FilterEnum.h(123,24): error C2338: Enumeration constant exceeds 25. (compiling source file SubtitleInputPin.cpp)
7>Done building project "Subtitles.vcxproj" -- FAILED.
14>------ Build started: Project: mpc-hc, Configuration: Debug Lite Win32 ------
14>mpc-hc.vcxproj -> C:\dev\mpc-hc\bin\mpc-hc_x86_Debug Lite\mpc-hc.exe
========== Build: 3 succeeded, 2 failed, 42 up-to-date, 9 skipped ==========

```
`VideoRenderers` and `Subtitles` are using a different size.  That's why hardcoding it fixes things probably, because now they use the same results instead of different ones when compiled together.

The size of the actual enum is typically 4 bytes regardless, so I'm not sure where the issue comes from.  I hardcoded the size of the arrays (`SrcFiltersKeys` etc.) to `100` and it still had problems.

**Comment by clsid2** [comment]
I just figured out the same.
Those projects do not define MPCHC_LITE.

`GetSubRendererSettings` should be moved to mpchc project and then use external reference in subtitle project.

Edit: I am working on fix
