### ISSUE TITLE
MPC-HC hangs on playback of older XviD/DivX video

### ISSUE THREAD

**Issue by QuantumReality** [clsid2/mpc-hc#2403]
I have some ~20 year old DivX/XviD files, and what I have found happening in both 2.0.0.and 2.1.2 (64-bit) is that I can play back a file once, after which if I close the video and then try to open another one, it hangs or only plays the sound.

When I then force close MPC-HC it leaves behind unkillable "zombie" processes that I have to use the reset button to force a restart on.

When I then go and play *any* video, video does not play, only sound.

If I Reset all settings in MPC-HC and then manually reinstate my custom settings, the problem disappears but will recur if I try to play any of those files again.

Said older DivX and XviD movies play fine in the Windows 10 Media Player, with no corruption issues or hangups.

Unsure what I can upload in the way of crash logs or the like.

**Comment by clsid2** [comment]
I assume you have "remember file position" enabled?
In that case the replay will start at different position than your first play. Somehow the initial seek must go wrong for these files.

Does seeking work normally during your first play?
Did you disable fast seek (options > tweaks)? If so, does it also happen with that enabled?
Are you using CUVID hardware acceleration for MPEG4?
Does `Menu > File > Recent Files > Clear list` prevent the problem?

You can close the zombie process with Windows Task Manager (Ctrl+Shift+Esc).

Can you upload one of these video files for me? Use Dropbox, Google Drive, or any free file host like [Sendspace](https://www.sendspace.com)

**Comment by QuantumReality** [comment]
> I assume you have "remember file position" enabled?
> In that case the replay will start at different position than your first play. Somehow the initial seek must go wrong for these files.

It is disabled and greyed out. (I turn off all "memorize previous" type items on first installation/run)

> Does seeking work normally during your first play?

First playback does work normally, but subsequent playbacks of any media file - even after a reboot - will not work properly until a settings reset.

> Did you disable fast seek (options > tweaks)? If so, does it also happen with that enabled?

Fast seek is off - have not tried with it on yet, will report back.

> Are you using CUVID hardware acceleration for MPEG4?

Unsure where to find this option, can you elaborate?

> Does Menu > File > Recent Files > Clear list prevent the problem?

Recents are disabled.

> You can close the zombie process with Windows Task Manager (Ctrl+Shift+Esc).

Tried and failed. Does not work - gives access denied or the PID simply just stays. CLI taskkill, same result. Start | Restart hangs on the circular dots and only a hard reset with my reset button gets me out of it.

> Can you upload one of these video files for me? Use Dropbox, Google Drive, or any free file host like [Sendspace](https://www.sendspace.com/)

I will advise when done and also update with the other questions above once I find out the MPEG4 diagnostic option/data.

System specs if relevant - i9 12900KS, MSI PRO Z690-A DDR4, Intel Arc A770 16 GB, 32 GB DDR4-3200 and the videos in question are from a hard drive.

**Comment by clsid2** [comment]
The CUVID option is in the internal video decoder settings and is only for NVIDIA GPU. It is not used by default, so not relevant in your case. But you should try with hardware decoder set to NONE.

First apply your custom settings while the system is still working correctly. Then:
Options > Miscellaneous > Export

After the problem occurs, export settings again.
Upload both exported settings files for me.

**Comment by clsid2** [comment]
@QuantumReality
Did you manage to export settings?

I suspect the problem might be related to the d3d9on12 translation layer that the Intel driver uses.

You could try MPC Video Renderer from our download page as an alternative for EVR-CP. That uses DirectX11.
