### ISSUE TITLE
The media player freezes and crashes everytime i stream it on discord

### ISSUE THREAD

**Issue by Zed9K** [clsid2/mpc-hc#2404]
As the title says, i think its enough info to explain the issue,
i don't know what exactly im supposed to show here,
if there is a way to show logs or something please let me know how to do so,
sorry i didn't see if there is a specific way to write an issue,

sorry for bothering,

but yea the problem is, everytime i want to stream any video on discord and i use MPC-HC 2.1.2 it freezes forever, if i touch it will show the crash menu and ask me to either wait or close the program.

**Comment by clsid2** [comment]
https://github.com/clsid2/mpc-hc/issues/453
