### ISSUE TITLE
Why limit the minimum jpeg quality to 20? (SaveImageDialog)

### ISSUE THREAD

**Issue by Rikk** [clsid2/mpc-hc#2405]
https://github.com/clsid2/mpc-hc/commit/942933b50e0554fb36bc379808fed3a131978766
Why limit the minimum jpeg quality to 20? Was there a problem with using lower values?

**Comment by clsid2** [comment]
Why have pointless crappy quality?

I am not really interested in discussing facilitating bullshit settings values.

**Comment by Rikk** [comment]
I'm not interested in having things removed for the sake of removal.

It may be useful to save low quality pics in some cases, even if you personally won't make use.
