### ISSUE TITLE
where does MPC HC store remember data?

### ISSUE THREAD

**Issue by SandeepGT** [clsid2/mpc-hc#2407]
I don't know when MPC HC got resume function but its amazing. I want to tweak a local copy of MPCHC for personal use. I tried finding remember data but so far no luck. Any help would be great, Thanks

**Comment by clsid2** [comment]
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\MediaHistory

**Comment by SandeepGT** [comment]
thanks
