### ISSUE TITLE
Long mp3-files not playing till to the end

### ISSUE THREAD

**Issue by MarGeb1** [clsid2/mpc-hc#2410]
Hi there,

got two long mp3-files (audio book) with around 370MB and 6:45 hours each. MPC-HC does not play these files completely. Around 30 min. before the end MPC jumps back to the beginning.

I tested the same files with MPC-BE and Windows Media Player without any problems.

Maybe someone can check this?

Markus

**Comment by MarGeb1** [comment]
I forgot:

MPC-HC (64-bit)
---------------

Build information:
    Version:            2.1.2 (2b85bfdeb)
    Compiler:           MSVC v19.29.30152
    Build date:         Nov  9 2023

LAV Filters:
    LAV Splitter:       0.78.0.0
    LAV Video:          0.78.0.0
    LAV Audio:          0.78.0.0
    FFmpeg compiler:    MinGW-w64 GCC 12.3.0

Operating system:
    Name:               Windows 10 (Build 22H2)
    Version:            10.0.19045 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    GPU:                NVIDIA GeForce GT 710 (driver version: 30.0.14.7414)

**Comment by clsid2** [comment]
You need to provide a file that suffers from this problem.

**Comment by MarGeb1** [comment]
I uploaded one of the files.

How can I send you a pm? I can't publish the link here because it's copyrighted content.

**Comment by clsid2** [comment]
clsid2@users.sourceforge.net

**Comment by clsid2** [comment]
It seems to be a bug in FFmpeg. Problem also occurs with FFplay. But no indication of possible file corruption.

**Comment by MarGeb1** [comment]
Ok, thank you!

**Comment by adipose** [comment]
https://github.com/jaylinski/kodi-addon-soundcloud/issues/19

Maybe same issue.

Can you reencode and test?

**Comment by adipose** [comment]
FFMPEG fixed?

**Comment by clsid2** [comment]
No
