### ISSUE TITLE
ProRes 4444 XQ decoding to NV12?

### ISSUE THREAD

**Issue by dprestegard** [clsid2/mpc-hc#2411]
I tried the latest 2.1.2.59 development build and noticed that ProRes 4444 XQ is being decoded by the internal LAV filters into NV12 which, being 8 bit 4:2:0 is losing a ton of information since ProRes 4444 XQ is 12 bit 4:4:4 internally. Or 16 bit depending on who you listen to and how you interpret it :)

You'd ideally want to decode to at least 12 bit 4:4:4 YCbCr, since the open source ProRes decoder supports this. 16 bit is possible as well, so... Y416?

**Comment by clsid2** [comment]
I get Y416. You need a video renderer that supports that (MPCVR or MadVR).

**Comment by dprestegard** [comment]
That's odd. I'm using MPC-VR 0.6.9.2117 and definitely get NV12 output from AP4X.

Same with MadVR 0.92.17
