### ISSUE TITLE
RememberPosForLongerThan doesn't save in mpc-hc.ini file if the value is 0

### ISSUE THREAD

**Issue by tealkami** [clsid2/mpc-hc#2412]
When I go to the Options=>Advanced=>RememberPosForLongerThan=> change to 0 => click OK, and change videos shorter than 60seconds, it works, 
but when I close=>open MPC-HC, it change from 0 to default 5, every other number stay saved.

-----

Some less important question(which I didn't wanted to make "ticked" only for this question): Only way to turn on the libass is go to the mpc-hc.ini file(or registry) and change from 0 to 1 the  Libass settings ? (RenderSRTUsingLibass, RenderSSAUsingLibass)

and where can I check if I use Libass/Freetype/ or something other ? My guess was somewhere in the Filters, but can't find it there.
other than check the mpc-hc.ini if the value is not =0 but =1

**Comment by clsid2** [comment]
Fixed.

Options > Subtitles > Default Style

**Comment by tealkami** [comment]
Can you please push 32bit version of **Development Builds** ?
