### ISSUE TITLE
Subtitle rendering performance issue with attached demanding typesetting

### ISSUE THREAD

**Issue by samb91** [clsid2/mpc-hc#2413]
2.1.3, Windows 64-bit

Attached is a sample with demanding typesetting that causes a large number of dropped frames: ~110 with plain ISR and ~70 with ISR+libass. mpv does not drop any frames. These were all while playing back windowed.

[demandingtypesetting.zip](https://github.com/clsid2/mpc-hc/files/13666312/demandingtypesetting.zip)

As an aside, yes I raised this after seeing "Improved performance of libass" in the 2.1.3 changelog and [reading the associated issue](https://github.com/clsid2/mpc-hc/issues/2340), and yes that _did_ improve the performance with my attached sample - in 2.1.2 ISR+libass drops ~150 frames! I remembered this section being a problem, and after seeing mpc-hc still struggles on it I figured it would be worth raising if only as a stress test case.

And as an additional aside, I'm hugely grateful for the integration with libass. So thank you, clsid2 and adipose, for that.

**Comment by Terpsichora-0** [comment]
I don't think this other problem is performance related, but while we're are it, I also recently noticed entirely missing subtitles in some demanding scenes in the example bellow (the text on the train announcements display). Both an old-ass VLC I have around and MPV seem to have no problem showing them...

And of course: thanks a lot to the team for your work and all the improvements and new features you've been adding.

Here's the sample: https://files.catbox.moe/so6oy7.mkv

**Comment by clsid2** [comment]
Subs show fine here.

Disable subpic queue if you use libass.

**Comment by samb91** [comment]
@clsid2 to clarify, was this closed due to disabling subpic queue fixing the issue in RaulDJ's comment? If so, then I should note that that is unrelated to the performance issues that made me create this issue; I observed dropped frames while rendering the subtitles, not the subtitles missing, while playing the attached sample, and I have tested to confirm that it is not subpic queue related.

**Comment by Terpsichora-0** [comment]
> was this closed due to disabling subpic queue fixing the issue in RaulDJ's comment?

The issue I showed there is exactly the same though, nothing changed.

**Comment by clsid2** [comment]
@samb91
I can't think of any way to further improve performance, so this will not be fixed.

@RaulDJ
Enable libass option.
Windows GDI is unable to renderer the matrix font at the requested size.

**Comment by Terpsichora-0** [comment]
> Enable libass option.
> Windows GDI is unable to renderer the matrix font at the requested size.

Oh crap, that indeed did the trick, thanks. It seems to completely murder the framerate and a single core on my 5900X though, even when the video it's paused :") ...

**Comment by clsid2** [comment]
Set subpic queue to 0.

**Comment by Terpsichora-0** [comment]
> Set subpic queue to 0.

Perfect, that did the trick, thank you very much once again. I searched for that option before but it was somewhat strangely translated on my language, so I wasn't sure where or what it was.
