### ISSUE TITLE
Issue 1) playback exclusive fullscreen 2) contact e-mail

### ISSUE THREAD

**Issue by 1kartafal4** [clsid2/mpc-hc#2414]
Merry Christmas and good day, 

any way to contact the developer(s) by e-mail?
The ones shown in the ".mailmap" are 11 years old; are they correct?

First: Thanks a lot for the player and the work. I would like to donate, but sadly no bank account given, paypal etc. No clue how to use bitcoin.

Second: I got an issue when playing video with the mpc-hc player (current version 2.1.3) and madVR (current 203 version from the avs forum).
Did not had the issue before on my old PC Windows 10 OS, but now on the newly installed Windows 11 23H2 OS.

When starting video playback in the mpc-hc player (madVR as output), switching to fullscreen, the player still stays in "D3D11 fullscreen windowed (8 bit)" mode, instead switching to "D3D11 exclusive (10 bit)".
I checked the madVR setting correctly rendering > general settings > "use Direct3D 11 for presentation (Windows 7 and newer)".

Found an semi-solution, but that only works once, respectively for 5 minutes: Restarting the Windows explorer in the task manager.
Ater that it switches to exclusive fullscreen (10 bit), but when opening any mad VR settings, closing the player, or simply waiting 5 minutes, it doesn't work again.
![issue2](https://github.com/clsid2/mpc-hc/assets/111880217/90b3dea5-683d-4ce0-a6c3-1936137eb1aa)

Any idea, solution?
Thanks in advance and merry christmas.

**Comment by clsid2** [comment]
I do not provide support through mail.

I can not help you with MadVR and graphics driver problems.

https://www.avsforum.com/threads/madvr-player-support-thread.2215490/

**Comment by cepihomero** [comment]
> Merry Christmas and good day,
> 
> any way to contact the developer(s) by e-mail? The ones shown in the ".mailmap" are 11 years old; are they correct?
> 
> First: Thanks a lot for the player and the work. I would like to donate, but sadly no bank account given, paypal etc. No clue how to use bitcoin.
> 
> Second: I got an issue when playing video with the mpc-hc player (current version 2.1.3) and madVR (current 203 version from the avs forum). Did not had the issue before on my old PC Windows 10 OS, but now on the newly installed Windows 11 23H2 OS.
> 
> When starting video playback in the mpc-hc player (madVR as output), switching to fullscreen, the player still stays in "D3D11 fullscreen windowed (8 bit)" mode, instead switching to "D3D11 exclusive (10 bit)". I checked the madVR setting correctly rendering > general settings > "use Direct3D 11 for presentation (Windows 7 and newer)".
> 
> Found an semi-solution, but that only works once, respectively for 5 minutes: Restarting the Windows explorer in the task manager. Ater that it switches to exclusive fullscreen (10 bit), but when opening any mad VR settings, closing the player, or simply waiting 5 minutes, it doesn't work again. ![issue2](https://github.com/clsid2/mpc-hc/assets/111880217/90b3dea5-683d-4ce0-a6c3-1936137eb1aa)
> 
> Any idea, solution? Thanks in advance and merry christmas.

Hello colleague...were you able to solve the problem?

**Comment by clsid2** [comment]
https://www.avsforum.com/threads/madvr-player-support-thread.2215490/
