### ISSUE TITLE
Opensubtiles.com user name, password dialogue box not showing

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2415]
Reset all settings then try.
Version 2.1.3

**Comment by clsid2** [comment]
Works fine here.

**Comment by bibsp** [comment]
.com?
After resetting settings .com was selected by default.
Then I unchecked that and checked again to get the option to enter my details. But it's not showing.

.org gives option to enter user details.

**Comment by clsid2** [comment]
Right-click on it > Setup
