### ISSUE TITLE
Workaround to set MPC-HC as default app under Windows 11

### ISSUE THREAD

**Issue by Zero3K** [clsid2/mpc-hc#2416]
It would be nice if it used one because it's currently a pain to set every type of file it supports to use itself for opening them.

**Comment by clsid2** [comment]
K-Lite Codec Pack can do it for you.

**Comment by Zero3K** [comment]
I don't want to have to use a 3rd party installer that does things that I don't need or want. It should be possible to have the installer do what the one you mentioned does.

**Comment by clsid2** [comment]
Special tricks are needed to programmatically set preferred player.

I am not implementing that in MPC-HC.
