### ISSUE TITLE
Add option to hide logo top panel

### ISSUE THREAD

**Issue by redsigma** [clsid2/mpc-hc#2419]
I used VLC for quite a while and I would like to have a similar layout in MPC.  Is there a way to only keep the playlist and get rid of the top black panel. I tried to get rid of the logo but it didnt make the panel go away. It is honestly a waste of space.

![image](https://github.com/clsid2/mpc-hc/assets/20425476/779bc309-c1d3-4be9-9157-8e021d19b23e)

**Comment by clsid2** [comment]
You can resize the playlist.

**Comment by redsigma** [comment]
> You can resize the playlist.

ah right. Playlist doesnt keep the resized layout if i close and open mpc again. It reverts back to being small. And If i resize the player it resizes the black area instead.

**Comment by redsigma** [comment]
@clsid2 could you tell me how to make this black area smaller at least and persist if i restart the player ? I wanna make very small so it doesnt take a lot of space.

**Comment by clsid2** [comment]
You can drag the playlist outside of player window.

I am not making any changes.

**Comment by clsid2** [comment]
I have reduced minimum for empty logo to 16x16.  This same area is used for video playback so anything smaller would make video invisible giving potential influx of idiots that ask why they lost their video.
