### ISSUE TITLE
Custom Installation - Translation Selection?

### ISSUE THREAD

**Issue by hl2guide** [clsid2/mpc-hc#242]
Please consider improving the installer to allow us to select the translations individually.

In my case I'd like to select two: English (US) and British English.

e.g. of context

![1](https://user-images.githubusercontent.com/17044982/72875488-7b12f100-3d48-11ea-8861-e909a998e5d4.PNG)

**Comment by clsid2** [comment]
I am not interested in making things unnecessary complex.

If the tiny amount of space it uses is important to you, it is trivial to delete the unwanted translation files.

English (US) is the default language, and British translation is nearly identical, so in your case you could just not install translations.
