### ISSUE TITLE
opensubtitles.com subtitles not showing up in search results

### ISSUE THREAD

**Issue by DaimDaim** [clsid2/mpc-hc#2420]
so I've set up the new opensubtitles.com api for subtitles and it seems to work when opening the subtitle downloadscreen where it searches for subtitles based on the video title.
 
There it shows both subtitles for opensubtitles.org and .com with identical results, which is good. But when I search manually, when the subtitle I want isn't in that initial list, only subtitles from opensubtitle.org show up and not .com?  I know the subtitles exist I can find them on opensubtitles.com manually and I'd assume identical results from opensubtitle.org and opensubtitles.com in the search anyway.

I have .org still turned on for this reason as I often need to further specify and I'm scared I won't be able to find subtitles because the end of life of .org is soon

**Comment by justnope** [comment]
I forgot to implement the manual search. It's a quick fix. I'll submit a PR in the coming days.
