### ISSUE TITLE
Remembering directory from last opened file doesn't seem to work anymore

### ISSUE THREAD

**Issue by DL13784** [clsid2/mpc-hc#2421]
In older versions, when i used the shortcut ctrl+q, the "open file" box opened in the last directory i've opened a file from. Now it always opens in the top directory and i have to navigate to the folder where the files are stored in. 

Would be nice to have this fixed / brought back again the way it was.

Also: sorry if this is the wrong place for this issue, but i couldn't seem to find any other contact info.

**Comment by clsid2** [comment]
It still does that.

**Comment by DL13784** [comment]
Is there an option i have to enable or something? Because newer version seem to only randomly open in the same folder..

**Comment by clsid2** [comment]
Quick open is stored in player settings.
Regular open is stored in Windows settings. So you might have recent files disabled in Windows.
