### ISSUE TITLE
Unable to Grab and Drag Blank Areas

### ISSUE THREAD

**Issue by LouisVeg** [clsid2/mpc-hc#2423]
Hello,

Not sure if this counted as an issue or feature. It's just something that has been bothering me. There are certain points of the application that I can click to let me drag it. I've attached an image of what I'm talking about. 
![MPCAreasGrab](https://github.com/clsid2/mpc-hc/assets/118117961/02b53f3f-19b4-425c-86cf-f5ea788af436)

**Comment by clsid2** [comment]
There is a safezone above/below seekbar to prevent unintentional actions when using seekbar.

You can drag using the video area or titlebar.
