### ISSUE TITLE
Feature request: remember audio/subtitles setting position

### ISSUE THREAD

**Issue by DenisNovac** [clsid2/mpc-hc#2427]
It would be great if MPC could remember the audio track and subtitles position in menu and activated them automatically when moved to next video (when "skip forward" button pressed).

**Comment by clsid2** [comment]
I will not implement that. Next video is not necessarily of same series.

You can ensure it selects correct desired tracks automatically with the settings in the splitter.
Options > Internal Filters > Splitter
There you can have advanced track selection rules based on language, and even track name.
