### ISSUE TITLE
[Feature request] Save Thumbnails: add option to generate thumbnails for all the files in the playlist automatically

### ISSUE THREAD

**Issue by evgeni-nabokov** [clsid2/mpc-hc#2429]
I have many files in my playlist and want to generate thumbnails for all of them. It would be nice if "Save Thumbnails" function can automatically move next until the end of the playlist. Probably it can be an option in the "Save As..." dialog.

UPD
I read your post about future requests. Let me see if I can implement it myself. I would like to get a feedback how it can be designed.

**Comment by clsid2** [comment]
You could add command line parameter for generating thumbnail and then exit player.

Then you can drag a file onto a shortcut:
`mpc-hc64.exe /thumbnail %1`
