### ISSUE TITLE
Playing multiple audio tracks at once?

### ISSUE THREAD

**Issue by EDGE-ELITE** [clsid2/mpc-hc#2431]
Hi there, I wondered if anyone could answer a question for me regarding audio tracks, please?

I've been recording gameplay with OBS using 2 tracks, one for the game audio and one for the microphone. I'd like to preview these clips with MPC-HC with both tracks playing, which I've read is possible - however, I cannot get this to work.

Is this actually possible? And if so, can anyone help me enable this feature, please?

Thank you.

**Comment by v0lt** [comment]
It is a bad idea.
But if you really want to, then disable the built-in Audio Switcher and use the System Default (DurectSound) audio renderer.

Just remember to turn Audio Switcher back on when you're done experimenting.

**Comment by clsid2** [comment]
You can switch between audio tracks by pressing A.

Playing two tracks is only possible if the second track is an external file (with same name as the video). You also need to disable the audio switcher.

Playing two embedded tracks at same time is NOT supported and will NEVER be supported.

**Comment by EDGE-ELITE** [comment]
Thank you for the speedy reply! Disabling the Audio Switcher and using Direct Sound didn't seem to work, unfortunately. However, pressing A to swap between the tracks is a good enough work around, thank you.

**Comment by Tteyt** [comment]
> Thank you for the speedy reply! Disabling the Audio Switcher and using Direct Sound didn't seem to work, unfortunately. However, pressing A to swap between the tracks is a good enough work around, thank you.

This works if you click "Open File" and select both files—video and audio—at once. Then, both tracks—the embedded video and the audio file—will play simultaneously.
