### ISSUE TITLE
Error creating EVR Custom renderer

### ISSUE THREAD

**Issue by amirhamdidz** [clsid2/mpc-hc#2432]
when i choose "Enhanced Video Renderer (custom presenter)"
![EVR-MPC](https://github.com/clsid2/mpc-hc/assets/154467169/6ece3378-921d-4a1e-a466-13cc049732ae)

this error show :
![EVR-problem](https://github.com/clsid2/mpc-hc/assets/154467169/89200dd6-1d57-4bd4-802c-3a06f82661e3)

**Comment by clsid2** [comment]
That means your system does not contain EVR (such as a Windows **N** version). Or you got a damaged system.
