### ISSUE TITLE
Video cropped when player resized beyond screen dimensions

### ISSUE THREAD

**Issue by NextronNL** [clsid2/mpc-hc#2434]
It looks like video in MPC-HC is only rendered within the pixel dimensions equal to those of the monitor, even when the player window is resized beyond that. As a result the video appears cropped.

Situation:
Multi screen, monitors side by side. I can play media without issues on either screen. I can also drag MPC-HC across screens so video simultaneously plays partly on one screen and partly on the other.
However, when resizing MPC-HC to the full size of both screens, I see only video on the left screen. The right shows black or some artifacts of the video frame during resizing.
When I reduce the window width by dragging the left part of the window right, I see video appearing on the right screen by the same amount I reszed. So I only see video within the left 2560 pixels of the window, regardless of window position or actual window width.

A similar issue occurs when resizing beyond the screen height.

Stretching the player across screens worked fine until 1.9.11 and broke in 1.9.12 until current 2.1.3. Hotfix 1.9.12.4 "Video display issue when moving player to a larger resolution monitor" does not seem to remedy this.

**Comment by clsid2** [comment]
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\Settings
DesktopSizeBackBuffer = 1
