### ISSUE TITLE
Disable "...selected audio and subtitle track is now stored in file history."?

### ISSUE THREAD

**Issue by MoneyAllDay** [clsid2/mpc-hc#2435]
The recent addition of version [2.1.3](https://github.com/clsid2/mpc-hc/releases/tag/2.1.3) that remembers the last selected subtitle sometimes is not the best option.

Is there any way to disable it? I can't find anything related to it in the options.
All i could find are these but unrelated to the audio or subtitles:

Player>History
![screenshot 2023-12-25 22 10 45](https://github.com/clsid2/mpc-hc/assets/19583547/eea693c8-b596-43dc-af58-333eac0b2235)

**Comment by clsid2** [comment]
No.
