### ISSUE TITLE
Small menu glitch in dark theme

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#244]
@adipose
The line below the menu extends into the right window border:
![mpc_menu_glitch](https://user-images.githubusercontent.com/4704996/73006465-fe951680-3e0a-11ea-9f37-42b7fdb93428.png)

**Comment by adipose** [comment]
Strange, I can't repro that on 7.  Is that 7?

Do you have to resize to make it happen?  I tried a few ways but couldn't see it.

**Comment by adipose** [comment]
Looks like Vista Basic theme.

**Comment by adipose** [comment]
I can see it now with Windows 7 Basic theme.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/246
