### ISSUE TITLE
Turn off "2.1.3: The selected audio and subtitle track is now stored in file history."

### ISSUE THREAD

**Issue by 0xotHik** [clsid2/mpc-hc#2443]
Good day!
With the 2.1.3 version come
> The selected audio and subtitle track is now stored in file history.

Is there a way to turn this off? 

Because for me it keeps selected subtitles track №2, that are in the file — whereas I was on subtitles track №2, but among externally loaded

**Comment by clsid2** [comment]
There is no option for it, and there will be no option.

There is a bug that saves wrong index in this situation. That needs to be fixed.

**Comment by 0xotHik** [comment]
> there will be no option

:(

**Comment by clsid2** [comment]
Bug has been fixed.
