### ISSUE TITLE
Problem when opening contents from the favorites list

### ISSUE THREAD

**Issue by xiperfect** [clsid2/mpc-hc#2445]
When you open the contents in Favorites, it does not choose the Local subtitle file, but rather chooses the subtitle included with the video

that this problem only applies to the favorites list, when opening videos normally, it chooses the local subtitle

**Comment by clsid2** [comment]
There was a bug when saving the selected subtitle track index.

Try 2.1.3.32 development build.
You also need to clear history:
Menu > File > Recent files > clear list
