### ISSUE TITLE
Search order for configuration data

### ISSUE THREAD

**Issue by lunter2** [clsid2/mpc-hc#2451]
1. mpc-hc64.ini
2. %AppData%\MPC-HC\mpc-hc64.ini
3. HCU\SOFTWARE\MPC-HC

Currently is only:

1. mpc-hc64.ini
2. HCU\SOFTWARE\MPC-HC

You can't use mpc-hc64.ini in "Program Files" folder due not permisions.

**Comment by clsid2** [comment]
You can if you adjust file permissions.

Storing settings in Registry is better, so that is what you should use.

Registry key can be backed up easily as well. So don't use that as argument for using INI. It does not matter anyway, since I am not going to make any change at all for INI.

**Comment by lunter2** [comment]
I didn't mean any changes in the ini, just an additional location.
