### ISSUE TITLE
"2.1.3.32: Fixed a bug where wrong subtitle track index was saved into history when both embedded and external subs were present"

### ISSUE THREAD

**Issue by 0xotHik** [clsid2/mpc-hc#2452]
Good day!
The problem with remembering the selected internal subtitles track instead of external — https://github.com/clsid2/mpc-hc/issues/2443 — is still partially there.
If I switch subtitles by "S" hotkey to next subtitles track and close MPC — it will select internal subtitles instead of external on next playing of this file.
The problem does not occur with switching subtitles by "Shift+S"

_(Terribly sorry, but the checkBox "Remember file position, but not selected audio and subtitles" is still out of the question? 🤓
Great thank you for your work on MPC-HC anyway :))_

**Comment by clsid2** [comment]
Fixed.

I am not adding unnecessary options.
