### ISSUE TITLE
Washed Out Colours

### ISSUE THREAD

**Issue by Ashwini6516** [clsid2/mpc-hc#2457]
I don't think i am asking for a feature it's just a tweak/potential bug(?)
Originally i thought it was just me but even the friends i told about had washed out colors in their default install of mpc-hc
Vlc had correct colours and so did every other player 

finally i fixed it by changing output range from 0-255 to 16-235

I think this should be set by default as i see a lot of people online having same issue where the only answer everyone is giving is using madvr but that isnt needed and madvr is significantly more demanding and has performance like vlc(i started use mpc for performance in my low end laptop) and requires some setup

Better have it by default!

**Comment by clsid2** [comment]
The default will not be changed because that would be wrong.

The bug is in your graphics driver (AMD?).

You can use MPC Video Renderer as better performing alternative for Madvr.

**Comment by CatKasha** [comment]
I have same problem, washed out colors on 16-235 videos, AMD gpu, default render
Monitor is set to full rgb in gpu driver, changing color range to 16-235 in mpc-hc fix this issue for me
For 0-255 videos this setting does nothing (at least with my samples)

**Comment by Ashwini6516** [comment]
> For 0-255 videos this setting does nothing (at least with my samples)

it does do something to the videos i tested(very unnoticable)
the dark scenes have little less details and dark scenes with contrasting areas look a bit too contrasty(again wouldn't look off because it's very little)
It does seem like amd issue but since i have laptop(with custom amd software) i dont even have access to the color range
Updating to newer drivers causes other issues so i stick with the one i have by default

**Comment by clsid2** [comment]
If nobody reports the issues to AMD, then the driver bugs will not get fixed either...

Which GPU model and driver version do you have?

**Comment by CatKasha** [comment]
> Which GPU model and driver version do you have?

rx6600 (non xt), 23.12.1

**Comment by Ashwini6516** [comment]
I have opened a community thread and have reported the bug as well
@CatKasha If you have time you could also report the bug with amd bug report software
https://community.amd.com/t5/drivers-software/washed-out-colours-in-mpc-hc/m-p/657233/highlight/true#M186517
if you want to add something there

**Comment by clsid2** [comment]
I would like to emphasize the fact that the renderer range setting is just for the output of the renderer.
It is totally unrelated to the luminance range of the input video.

Your report should mention which video renderers suffer from the problem.
MPC-HC options > Playback > Output > Video Renderer > EVR-CP and VMR-9 (renderless)

Afaik, same problem occurs also with MPC Video Renderer, but only in DirectX9 mode, not in DirectX11. You should test that.

**Comment by CatKasha** [comment]
Did reset to default, for each test i did relaunch player, compared with vlc side by side

[V: h264 high 4:4:4 predictive L4.2, yuv444p, 1920x1080]
EVR-CP and VMR-9 (renderless) looks fine

[V: h264 high L4.2, yuv420p, 1920x1080]
[V: hevc main L6.2, yuv420p, 1920x1080]
VMR-9 (renderless) looks fine, EVR-CP have washed out colors

**Comment by clsid2** [comment]
And with hardware decoding disabled in the video decoder? Some say that bug may occur only with hardware decoding.

h264 high 4:4:4 can't be hardware decoded. VMR-9 does not support DXVA2 native hardware decoding. So effectively hardware decoding is disabled in those situations.

And if DXVA2 native has problem, then also test DXVA2 Copy-back and D3D11.

**Comment by CatKasha** [comment]
Where can i find these settings to test it? And what samples i should test? (i can make it via ffmpeg by using that h264 high 4:4:4 as base)

**Comment by clsid2** [comment]
Options > Internal Filters > Video Decoder

You don't need samples. Just disable/change hardware decoder settings and test if video is washed out or not.

**Comment by CatKasha** [comment]
None, DXVA2 Copy-back, D3D11 - washed out

**Comment by Ashwini6516** [comment]
Evr(custom) - washed out colors
Evr - slightly off colors 
mvr 9 (renderless) - washed out 
Sync redenderer also looks washed out
others seem to look fine

**Comment by Ashwini6516** [comment]
in video decoder settings changing the rgb output levels to pc or tv gives the same washed out results
changing hardware decoder had no effect
Nothing i did had any effect on the video

**Comment by clsid2** [comment]
DO NOT CHANGE RGB LEVELS!!!!!!
That is WRONG and only has effect when converting to RGB, which isn't even happening.

It is a driver bug. Any attempt to adjust color range of the video is just WRONG.

**Comment by CatKasha** [comment]
I'll send bug report, seems this issue is not new
https://community.amd.com/t5/drivers-software/two-full-generations-of-cards-still-no-fix-for-evr-mpc-video/m-p/518884
^ thanks @Ashwini6516 for the link

**Comment by Ashwini6516** [comment]
> DO NOT CHANGE RGB LEVELS!!!!!! That is WRONG and only has effect when converting to RGB, which isn't even happening.

Was just testing 
I get it!! from all the research i did in the last 2 days i realize just how wrong it is

I tested a 4k Hdr movie it looks terrible, there's no work around for it

**Comment by clsid2** [comment]
EVR-CP does not support HDR. For that you need MPC Video Renderer.

**Comment by CatKasha** [comment]
AMD released [24.1.1](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-24-1-1) and i saw that EVR (not EVR-CP) works fine and i did some testing
Reinstalled 23.12.1 with full wipe by using amdcleanuputility, EVR (none, native, copy-back) also works fine, strange
Also with EVR window resize is laggy on both version of drivers

EVR-CP is not fixed in 24.1.1, they dint email me or mention this issue in release note so idk if they will fix it or not

**Comment by ViperCode7** [comment]
Came here for the same reason... on my laptop, a 5600H with Vega 2 graphics and driver 23.11.1 (polaris) it works fine.
But on my desktop, an RX 6650 XT and driver 24.3.1, nothing works.

The most weird thing is that the color controls (Miscellaneous, EVR-CP) don't work at all on my desktop, but they do on the laptop.

I've tried all the output formats in LAV Video (software/none), and most seem to prefer the washed up colors, none of the controls work and AMD video profiles work inconsistently.

On EVR-CP, the amd video profiles work on non RGB formats, where the colors are washed up, while on RGB they don't work but the colors are proper.
On EVR, however, it's reverse, amd video profiles work on non RGB outputs likewise but the colors are proper this time, this might be the best option as custom video profile at least allows me to change brightness from amd's software, while on RGB formats colors are washed up and video profiles don't work.

So a 1 yay and 3 nays, but the color controls in MPC are dead in any case... good thing I mostly game on my desktop and watch movies on my laptop where everything works. Hate to think what will happen after an upgrade.

I did send a report to AMD, however I find it weird how the EVR-CP and EVR renders differ.

**Comment by clsid2** [comment]
Try MPC Video Renderer.

That gives option to choose between using DXVA2/D3D11 video processor (gpu driver color processing and resizing) or using the internal shaders of the video renderer.

Color controls in MPC-HC only work if GPU driver is configured to let application control colors. As soon as you configure color adjustment in driver, then applications can no longer make adjustments. That applies to Intel and Nvidia as well.

**Comment by ViperCode7** [comment]
OK, MPC Video Render seems to work with internal color settings, but the video profiles stopped working. I guess it's the most I could get. I understand regarding the driver, that means in the older drivers color adjustments were allowed unrestricted, since on my laptop I can do both video profiles and MPC's internal color control for EVR-CP. Weird thing tough that I just noticed, swapping through the output profiles LAV Video/EVR-CP on my desktop seems it defaults to NV12 for most of the non RGB ones. It doesn't do that on my laptop though. Anyway, thanks!
