### ISSUE TITLE
ToDo: ability to load MPC Video Renderer from appdir

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2459]
Load it without having to register it. Similar to how we load internal LAV Filters.

**Comment by SanderBouwhuis** [comment]
I am very unclear on what the MPC video renderer is anyway.

1. Does or doesn't it come with the default installer package?
2. When we download the video renderer, we can't just copy it in the MPCHC directory? We have to 'register' it?
3. What is the advantage/disadvantage of using the MPC video renderer? Is it the best to choose, or only useful for specific situations?
