### ISSUE TITLE
Hi! Friends, mpc-h plays very laggy for 4K 60 FPS VP9 encoded videos.

### ISSUE THREAD

**Issue by zhouxinghong** [clsid2/mpc-hc#2461]
Hi! Friends, mpc-h plays very laggy for 4K 60 FPS VP9 encoded videos.

[Video example](https://www.youtube.com/watch?v=FyTSAC9vxsQ)

PC environment:
Windows 10 19044
CPU i5 3210
Memory 8G
Western Digital mechanical hard drive 5400 rpm
The latest mpc-h client

This player is really great! none of them! Thank you so much for bringing mpc back to life again! 😜👍🎉

**Comment by zhouxinghong** [comment]
In addition, the effect of using the MPV engine to decode and play 4K 60 FPS VP9 encoded videos on the same PC is very good!
[Test Video](https://www.youtube.com/watch?v=FyTSAC9vxsQ)

**Comment by zhouxinghong** [comment]
The above problems also exist when playing local 4K 60 FPS VP9 encoded videos.

**Comment by clsid2** [comment]
Plays fine here.

Enable D3D11 hardware decoding in the video decoder settings.
Install MPC Video Renderer.
