### ISSUE TITLE
Unable to display preview on playback progress bar for 4K 60 FPS VP9 encoded videos

### ISSUE THREAD

**Issue by zhouxinghong** [clsid2/mpc-hc#2462]
Unable to display preview on playback progress bar for 4K 60 FPS VP9 encoded videos

[Test Video](https://www.youtube.com/watch?v=FyTSAC9vxsQ)

Hi! Friends, for 4K 60 FPS VP9 encoded videos, for example: .webm format videos cannot display the preview screen on the playback progress bar.
Windows 10
mpc-hc latest client

This player is really great! none of them! Thank you so much for bringing mpc back to life again! 😜👍🎉

**Comment by clsid2** [comment]
Preview is only shown for local files.

**Comment by zhouxinghong** [comment]
Local 4K 60 FPS VP9 encoded videos, such as .webm format videos, cannot be previewed either.

**Comment by zhouxinghong** [comment]
You can try it, but 4K 60 FPS VP9 encoded videos .webm format videos cannot be previewed on my machine

**Comment by clsid2** [comment]
Works perfect with local file as well.

Downloaded that video with yt-dlp. Maybe you use a bad download tool that creates files without proper keyframe index.

**Comment by zhouxinghong** [comment]
Thank you very much 👍! I will try again.
