### ISSUE TITLE
Clicking on 'Slack' icon in windows 10 tray causes MPC 2.1.3 to Play a paused or stopped track.

### ISSUE THREAD

**Issue by stitchsam99** [clsid2/mpc-hc#2463]
![MPC play on Slack](https://github.com/clsid2/mpc-hc/assets/156343623/32c29c54-9e8d-459e-8621-c389442c9040)

Pictured demonstration. Slack is the only program which clicking on its icon in the windows 10 tray causes MPC to resume playing if it was paused or stopped.

Behaviour only occurs in relation to Slack, no other tasktray icon affects MPC in this way. Behaviour only occurs when Slack is selected in the Tasktray, clicking Slack's toolbar entry doesn't exhibit this behaviour. 

Let me know what additional support information I can provide to assist in debugging this occurrence.

**Comment by adipose** [comment]
Thanks for the report, maybe related to other windows integration bugs.

**Comment by clsid2** [comment]
Options > Player > Keys > uncheck "Global Media Keys"

**Comment by stitchsam99** [comment]
> Options > Player > Keys > uncheck "Global Media Keys"

That did fix Slack from play/unpausing MPC, but also has the unfortunate side effect that my keyboard's dedicated play/pause/previous/next buttons no longer function globally unless MPC is the selected window in windows.

**Comment by clsid2** [comment]
Then you need to ask Slack to fix their software to stop sending unwanted commands.

There is nothing we can do.

**Comment by stitchsam99** [comment]
Thank you for the assistance, I will try to reach out to Slack and bug report the issue with them
