### ISSUE TITLE
How to switch shaders in mpc-hc right-click menu

### ISSUE THREAD

**Issue by zhouxinghong** [clsid2/mpc-hc#2468]
How to switch shaders in mpc-hc right-click menu
![image](https://github.com/clsid2/mpc-hc/assets/54253524/a20296cb-2d4a-4f9f-ac8d-3d55c04efe85)

Hi! friend!
How to switch shaders in mpc-hc right-click menu? This problem has troubled me for a long time.

**Comment by butterw** [comment]
use Select Shaders...
You have to first create and save shader presets  if you want to be able to switch directly.

https://raw.githubusercontent.com/butterw/bShaders/master/MPC-HC_Shaders-Menu.jpg
