### ISSUE TITLE
Logo has vertical lines on Windows 7 - v1.9.1

### ISSUE THREAD

**Issue by emc2peer** [clsid2/mpc-hc#247]
Logo (Steven, Marcel, Robbie) has colored vertical lines.
If it is used external logo, it is colored to yellow.
See the screenshots.
MPC-HC 1.9.1 (regardless x64 or x86) on Windows 7 x64. Windows 10 x64 without these issues.

![MPC-HC Logo](http://www.kopirky.org/img/MPC-HC_190-191_broken_logo.png)
![MPC-HC Logo](http://www.kopirky.org/img/MPC-HC_190-191_yellow_logo.png)

**Comment by adipose** [comment]
I wonder if the color management caused this.

**Comment by emc2peer** [comment]
MPC-HC is installed with the checked option "reset to default". This issue belongs only to the logo. Movie has no image quality problem.

**Comment by adipose** [comment]
It seem to have to do with transparency in the source image.  For some reason, it's not an issue on Window 10, but I can repeat the issue on Window 7 with color profiles enabled (in Windows, not MPCHC).

Try this build:

https://mega.nz/#!pF5SxQha!V4pvXNuHOJdeWUzH36NzmR_mfMPbQIrLDruQiaeQHHc

@ValZapod, please test this to make sure I didn't break color profiles for you.

**Comment by ValZapod** [comment]
@adipose Everything still works on this build.
