### ISSUE TITLE
Files skip to the end sometimes over HTTPS

### ISSUE THREAD

**Issue by is-this-c** [clsid2/mpc-hc#2471]
MPC-HC sometimes cannot play .mkv files over HTTPS.  It either plays fine or skips to the end after several minutes or immediately.

I have to download them manually through a browser so that I can play them locally while they continue to download.  Other players do not have this issue.

**Comment by clsid2** [comment]
That usually means it is a bad server that only supports sequential download or bad connection.

I can not fix it. Certainly not without an example link that fails.

**Comment by is-this-c** [comment]
I looked into it again where a file skips to the end immediately.  Its url turned out to be a redirect. 

I verified that `curl file -L -O -C -` is able to download or resume this file without issues.  The flag `-L` enables redirects.

The url that's redirected to actually plays fine in MPC-HC.

Is MPC-HC unable to follow redirects?  Why would it fail?

_EDIT_.  I verified that surprisingly MPC-BE does not have this issue.

**Comment by clsid2** [comment]
No working example link = no fix

**Comment by is-this-c** [comment]
This file unfortunately is not public.

However I found this issue to be a regression in LAV Filters 0.77.  MPC-HC 2.1.3 plays this stream fine if I use 0.76.1.  The latest `ffplay.exe` plays this stream fine as well.

I built LAV Filters 0.76.1 (GCC 11.2) myself.  But for some reason it had this regression too.
