### ISSUE TITLE
Long open m3u iptv playlists

### ISSUE THREAD

**Issue by sfilkex** [clsid2/mpc-hc#2473]
The application freezes for a long time, especially if there are non-working links in the playlist, while in MPC-BE there are no issues. Example playlists
[playlist.zip](https://github.com/clsid2/mpc-hc/files/13922687/playlist.zip)
Ru playlist work fast, UA - app not reply about 1 minute, while in BE open in 5 seconds, other playlists also slow open.

**Comment by clsid2** [comment]
I have fixed the slow parsing of the playlist.

But it now tries to play first stream and then continuously goes to next one if invalid, so can still take long time if there is a huge list of only invalid streams.

I probably need to add a limit to stop automatic skipping in case there are many invalid links/files in a playlist.

**Comment by clsid2** [comment]
Stops automatically now after 5 failed attempts.

**Comment by bibsp** [comment]
Switching between channels is still super slow. vlc somehow can quickly switch.
IPTV link: https://iptv-org.github.io/iptv/countries/in.m3u

https://github.com/clsid2/mpc-hc/assets/98865389/3da305ce-b939-4f0c-adcc-8c607b9e8c66

**Comment by clsid2** [comment]
Then use VLC.

**Comment by roberto-sartori-gl** [comment]
@clsid2 

> Stops automatically now after 5 failed attempts.

How about an option to simply disabling automatic playlist playback? I almost never need the first element in a m3u file, but I have to wait for MPC to load it anyway. Not a problem, just a suggestion! :)

Also, in my case MPC is pretty quick to switch between channels, I don't see the issue mentioned by @bibsp .
