### ISSUE TITLE
Theme and visual glitches

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2474]
MPC-HC (Nightly, 64-bit)
    Version:            2.1.3.37 (ebae66c35)
    Build date:         Jan  9 2024
Operating system:
    Name:               Windows 10 (Build 22H2)
    Version:            10.0.19045 (64-bit)
Hardware:
    CPU:                Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    GPU:                Intel(R) HD Graphics 630 (driver version: 31.0.101.2125)

125% dpi on 15,6" 1080p monitor.

1. **Options > Playback > Output**

Enable > D3D Fullscreen , messagebox doesn't fit theme and clicking "no" button also decolorize Audio renderer and Resizer options.
![image](https://github.com/clsid2/mpc-hc/assets/3073922/f5059fe1-fa32-4afa-b414-ea899a9d49b5)
![image](https://github.com/clsid2/mpc-hc/assets/3073922/de6c9532-00bd-4bc2-b9c1-baff4d162c8d)

might be related
https://github.com/clsid2/mpc-hc/blob/59f4cd3c5b0d87ee449ceb4958b23f3d5bba673c/src/mpc-hc/PPageOutput.cpp#L741

2. **Options > Player > Open options** // _actually any multiline controls or options_

Changing options makes ghost selection mark
![image](https://github.com/clsid2/mpc-hc/assets/3073922/c0af089b-3725-4fbc-8680-a191fa4ed5a0)

3. **Options > Advanced page**

Dragging "Value" 's right column line to beyond right corner cause repetitive artifacts and move left to by entire column.
![image](https://github.com/clsid2/mpc-hc/assets/3073922/19f2f60b-d335-47d4-9c22-9b13883cc0c6)

4. **Organize favorites horizontal scroll**

Open organize fav. windows, resize window, scroll horizontal with mouse wheel or by click.
![image](https://github.com/clsid2/mpc-hc/assets/3073922/364fd4a2-1e4f-4eac-8b87-7c048fa2133b)

horizontal scroll bar better fit 
![image](https://github.com/clsid2/mpc-hc/assets/3073922/00db5019-ba0f-4973-97a6-95d8a3c79dec)

5. Resizing window may cause visual glitches // _subresync panel and other resizable windows_

![image](https://github.com/clsid2/mpc-hc/assets/3073922/cffcdbc8-70a3-4efc-8658-b1b67e24919a)

might be not related but I suspect "Vertguide"s may cause it in some cases.  On my end I see some tearing while hovering on renderer option selections on Output page. It tears at exact vertical coordinate. Only visible on low ram.

6. Subresync > Style column > right click any rows on style column > Edit

opened window doesn't fit mpc-hc's theme
![image](https://github.com/clsid2/mpc-hc/assets/3073922/4d91fe50-ad68-44e9-a970-6d279914ae28)

7. Options > Playback > Fullscreen

Tooltips are trying to show up.
![mpc-hc64_L1PAqHIfUH](https://github.com/clsid2/mpc-hc/assets/3073922/4be4d131-f69c-484a-8463-222566d727be)

**Comment by bibsp** [comment]
Ghost selection mark also arrives on Apply, Ok button. Click on those buttons then it will appear.

Edit: Go to Help>About... There OK button has this issue.
![Screenshot (37)](https://github.com/clsid2/mpc-hc/assets/98865389/aaaee0b7-0d9b-4084-9e9f-3b8f516b950a)

**Comment by adipose** [comment]
1. https://github.com/clsid2/mpc-hc/pull/2509
2. https://github.com/clsid2/mpc-hc/pull/2509

**Comment by clsid2** [comment]
All fixed?

**Comment by adipose** [comment]
Not all of them, but I am going to break these into different issues.  You can leave it closed.

**Comment by xLn2** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/3073922/25b8e512-ad93-4581-8e31-797702a18d05) 2.1.4.14
![image](https://github.com/clsid2/mpc-hc/assets/3073922/c2a5300d-9038-4a84-a79a-63d6228d6b27) 2.1.4

![image](https://github.com/clsid2/mpc-hc/assets/3073922/eb4b523d-3b3f-4144-b5ee-365d8e879aa8) 2.1.4.14
![image](https://github.com/clsid2/mpc-hc/assets/3073922/3344ed93-2091-4285-941d-431df73b1ad7) 2.1.4

![image](https://github.com/clsid2/mpc-hc/assets/3073922/9660f4bd-bcf4-417d-a8bc-6c23235d871c) 2.1.4.14
![image](https://github.com/clsid2/mpc-hc/assets/3073922/71e8e7fc-3c4f-4f66-9477-7a88796e0c96) 2.1.4

@adipose 
Thanks for your efforts. Nightly version 2.1.4.14 has a issue that words _tails_ are cut off. Might be related with latest changes https://github.com/clsid2/mpc-hc/pull/2509

**Comment by adipose** [comment]
Hmm probably so.  Erasing the outline must come after the text render.

Please enter new issue.
