### ISSUE TITLE
Shuffling Tracks Within a Folder

### ISSUE THREAD

**Issue by StormProductionsMusic** [clsid2/mpc-hc#2475]
# Feature Request: Shuffle Play for Tracks in a Folder

## Description
Hello MPC-HC Developers,

I am reaching out to inquire about a specific feature in the MPC-HC player. Currently, I have a folder with approximately 100 audio tracks. When I play the first track, the player naturally proceeds to play the next tracks in alphabetical order. However, I am interested in a feature that allows for randomizing or shuffling all tracks in the folder after the first track finishes playing.

## Expected Behavior
After playing the first track in a folder, the application should have the ability to shuffle and play the remaining tracks in a random order, instead of the default alphabetical sequence.

## Current Behavior
Currently, after the first track finishes playing, the player automatically plays the next track in alphabetical order.

## Possible Solution
Implementing a shuffle feature that can be toggled on or off for playing tracks in a folder would be ideal. This feature would allow the user to listen to the tracks in a random, shuffled order after the initial track has finished playing.

## Context
This feature would enhance the listening experience by providing a more varied and unexpected sequence of tracks, similar to a shuffled playlist.

Thank you for considering this feature request. I believe it would add significant value to the user experience for those who enjoy a more dynamic and randomized playback order.

**Comment by clsid2** [comment]
Menu > View > Playlist

Right-click on Playlist > Shuffle

**Comment by StormProductionsMusic** [comment]
I know about this one, however I wanted it in a different way. Lett's say I have a folder with 100 tracks. I press enter on the first one, MPC-HC opens and starts playing it, but it's the only track shown in the playlist. I want that when I press the next button that will play the next track in the folder, it would instead shuffle all tracks in that folder, not play it alphabetically.  
Let me know if you need more details or to explain in another way.

**Comment by clsid2** [comment]
I am not adding that.

**Comment by StormProductionsMusic** [comment]
Understood.

Another question.
For me it works, but for a friend of mine, when selecting multiple files to add in a playlist, and then right clicking, the context menu doesn't show the option to add in a MPC-HC playlist, even though the player is installed and works perfectly. The only mention about MPC-HC is int he "Open with" submenu. But there's no option to make a playlist with the selected songs like it happens on my ed.

Any way I can bring MPC-HC into the context menu of my friend? Maybe there's an option I'm not aware of somewhere. 

Tried reinstalling it too but doesn't help.

**Comment by clsid2** [comment]
You need to create file associations.
Options > Player > Formats

**Comment by StormProductionsMusic** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/86001751/d32609fe-a6c1-49f5-9e44-1373d831590c)

Which one? I see nothing related to file associations here in the Keys section. It's just a bunch of shortcuts and some checkboxes that I don't know what they are for like those IP and port sequences.

**Comment by clsid2** [comment]
Options > Player > Formats
