### ISSUE TITLE
Wrong FPS at Status bar

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2478]
I have some videos with variable fps. All are from same camera. One Video has this issue. Mediainfo reports it as 30 fps. But Status bar shows as 120 fps. All other videos are fine.
![Screenshot (38)](https://github.com/clsid2/mpc-hc/assets/98865389/4d491ba4-6f29-4371-8ab3-bd4317cfe6fe)

File Link: https://drive.google.com/file/d/11biJqW3FpSlCUSmxryhXowIq-GVk_zQv/view?usp=sharing

**Comment by clsid2** [comment]
LAV Splitter mediatype indicates 120 fps.

@nevcairiel
Maybe bug in framerate logic?
FFplay correctly detects file as 30fps.
