### ISSUE TITLE
Ampersand bug on info bar tooltips

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2480]
Ampersands (&) marks looks like underscore on info bar tooltips. It might related to interpreting it as accelerator.

![image](https://github.com/clsid2/mpc-hc/assets/3073922/c2d18824-b5a4-43ac-b377-bef4c3a46121)
![image](https://github.com/clsid2/mpc-hc/assets/3073922/431034e7-e875-45ae-9067-d20c55967a99)

You can test with **G-Eazy & Halsey - Him & I**

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2481
