### ISSUE TITLE
[Bug] MPC Video Renderer conflicts with all subtitle tracks

### ISSUE THREAD

**Issue by ryehamstrawberry** [clsid2/mpc-hc#2483]
MPCVR fails to recognize all subtitle streams contained by file.
Tested multiple files with differing subtitle tracks, everything behaves correctly with MadVR but none of which work with MPCVR.
Version(s): MPCVR v0.7.1.2172 / v0.7.2.2177 Beta

**Comment by ryehamstrawberry** [comment]
> 1. What is the advantage/disadvantage of using the MPC video renderer? Is it the best to choose, or only useful for specific situations?
> 2. Does or doesn't it come with the default installer package?

1. MPCVR and MadVR are software video decoders that allow HDR -> SDR tone mapping. This allows uses without HDR capable hardware to consume HDR content. For example: your favorite movie is remastered in 4K UHD, but your GPU doesn't handle HDR. Filters like MPCVR and MadVR allow users to consume such media without an HDR capable GPU and/or monitor.
2. Until recently, I never noticed MPCVR bundled with MPC-HC, but as of the latest v2.1.4 MPCVR is now prominently advertised as literally the first feature of MPC-HC: _[Play HDR video](https://github.com/clsid2/mpc-hc/releases/tag/2.1.4)_.

**Comment by clsid2** [comment]
You are the only one with this problem.

The renderer has no effect on which streams are recognized. So I assume you mean the selected subtitle stream does not display any subtitles.

Reset settings of the player.
Use the internal subtitle renderer, and not external crap like XySubFilter.
Use this specific build of MPCVR:
https://github.com/clsid2/mpc-hc/releases/download/2.1.4/MPCVideoRenderer_0.7.1.2172.zip

**Comment by ryehamstrawberry** [comment]
> You are the only one with this problem.

Why are you so dismissive?
Not only have I reproduced this bug from fresh packages, but I've had friends and family replicate it as well.

> So I assume you mean the selected subtitle stream does not display any subtitles.

Correct.

> Reset settings of the player. Use the internal subtitle renderer, and not external crap like XySubFilter. Use this specific build of MPCVR: https://github.com/clsid2/mpc-hc/releases/download/2.1.4/MPCVideoRenderer_0.7.1.2172.zip

Done. Done. Done.
The OP clearly states that both MPCVR v0.7.1.2172 and v0.7.2.2177 Beta are affected,
I've tried multiple other video filters, ALL of them render selected subtitles EXCEPT crap MPCVR.
Find out what's causing the issue instead of crying "operator error" it if you want to advertise it as your top feature.
