### ISSUE TITLE
How does donating work?

### ISSUE THREAD

**Issue by SanderBouwhuis** [clsid2/mpc-hc#2484]
I would like to donate to the dev of the MPC-HC project, because it is great.
But, I'm confused about the process. The description is for another project (something to do with subtitles, or something like that?).
Can someone explain it more clearly, or supply a link which explains it better?

**Comment by Kosette** [comment]
As said in https://github.com/clsid2/mpc-hc/issues/383 ,donating to opensubtitles.com to help improve the search for subtitles in MPC-HC. According to my understanding, there is currently no way to directly donate to the MPC-HC developers through PayPal.

> You can make a donation to [OpenSubtitles](https://opensubtitles.onfastspring.com/mpc-hc-subtitles-support). We have made a deal to increase the download quota for the subtitle search functionality of MPC-HC. If we raise some money with donations, the anonymous usage limit will be significantly increased, so everyone can enjoy the functionality without the hassle of having to create a login. For frequent users I do urge to create a free account on the [opensubtitles.com](https://www.opensubtitles.com/) website.
