### ISSUE TITLE
[Bug] MPC Video Renderer fails to render subtitle tracks

### ISSUE THREAD

**Issue by ryehamstrawberry** [clsid2/mpc-hc#2485]
MPCVR v0.7.1.2172 / v0.7.2.2177 beta fail to render all subtitle streams contained by file.
Not only can I reproduce this bug using fresh instances of both the latest MPC-HC installer and portable builds, but I've had friends and family reproduce the bug as well (in fact someone reported the bug to me, which I then confirmed).

Tested multiple files with differing subtitle tracks, everything behaves correctly with MadVR but none of which work with MPCVR.
No custom subtitle filters are being used.

Also tried multiple video filters, ALL of them render selected subtitles except MPCVR.
This is not "operator error".

**Comment by clsid2** [comment]
Try this build of MPCVR:
https://github.com/clsid2/mpc-hc/releases/download/2.1.4/MPCVideoRenderer_0.7.1.2172.zip
It is different from the "official" one you are using. It has a fix to support DXVA2. Although that should be unrelated to subtitles.

Change the hardware decoder in the video decoder settings to `D3D11`.

Press Ctrl+J to show the MPCVR debug overlay and make a screenshot.

You can still comment on issues that are closed. Do not open new ones for same subject.

**Comment by ryehamstrawberry** [comment]
MPCVR:
![mpcvr](https://github.com/clsid2/mpc-hc/assets/110439000/b2919b74-750c-410e-8b05-ce9552d458d7)


MadVR:
![madvr](https://github.com/clsid2/mpc-hc/assets/110439000/ccaac6b8-5f82-4602-8d1a-9d2eab9785fb)

**Comment by ryehamstrawberry** [comment]
MPCVR:
![mpcvr](https://github.com/clsid2/mpc-hc/assets/110439000/6306a60e-579d-4a74-b6a1-b6b1b809ceb6)


MadVR:
![madvr](https://github.com/clsid2/mpc-hc/assets/110439000/8e760b82-1349-4a7e-8d77-d238c814459d)

**Comment by clsid2** [comment]
Your MPCVR screenshot is showing the Madvr overlay. So it isn't using MPCVR. Subtitles will not work if there is an issue with loading the selected renderer.

`Options > External Filters` should be empty.

The MPCVR files should also not be moved or removed after running its install script.

**Comment by ryehamstrawberry** [comment]
> Options > External Filters should be empty.

Disabling madVR under External Filters appears to resolve the conflict.
You may want to consider including such a disclaimer to assist users and mitigate duplicate issues being posted.

Attached screenshot w/ MPCVR renderer stats:
![mpc-hc64_B6FBD0o8RE](https://github.com/clsid2/mpc-hc/assets/110439000/1356711c-62a0-4a7d-9268-353f6ed9e1c0)

Please confirm whether everything appears correct or not, thank you.

**Comment by clsid2** [comment]
MPC-HC loads external filters fully automatically whenever needed. Just like any other DirectShow player.

External filter settings is purely to OVERRIDE standard filter merits. Normal users should not need to use it ever at all, with rare exceptions.

Latest version already prevents you from adding Madvr there.

I find it weird that your friends has the exact same problem. Did you all follow some weird online tutorial? Those are all full of crap advice.
