### ISSUE TITLE
Aspect Ratio options too deep in menu

### ISSUE THREAD

**Issue by cheeseandjamsandwich** [clsid2/mpc-hc#2489]
To change the aspect ratio of a video we have to do the following:
Right Click - View - Video Frame - Aspect Ratio - pick the one you want...

It Always seems way too deep into the menu.
And when you have a squiffy video with an odd aspect ratio, you often have to try a couple to find the right one.

It would just be a bit more usable if this option was easier, quicker to access, flattening the menu a bit.

**Comment by clsid2** [comment]
Use the Pan&Scan (PNS) functionality to stretch the video. That is much easier to fix incorrect AR. 

Numpad 2/4/6/8 on keyboard.
