### ISSUE TITLE
Aspect Ratio setting should reset by default

### ISSUE THREAD

**Issue by cheeseandjamsandwich** [clsid2/mpc-hc#2490]
Only very occasionally do i find a video that has the wrong aspect ratio.
This is easily fixed using MPC-HC's Aspect Ratio setting, but they are sticky... And the next video is unlikely to have the same squiffy aspect ratio, so it would probably be best if the AR setting was reset to default, DAR, when a new video is launched.
In MPC-HC's settings there could then be setting to switch it such that it does then remember this setting.  Thus covering all needs.

**Comment by clsid2** [comment]
I am not going to make a setting for this.

**Comment by cheeseandjamsandwich** [comment]
OK.
Could the default maybe be set to it resetting to DAR when loading a new video though?
As it is much more likely to not be a video with a wrong aspect ration.  Videos with incorrect aspect ratios are increasingly becoming rarer.

Thanks for MPC-HC anyway!  Thanks for taking on it's development and keeping it current.

**Comment by clsid2** [comment]
No, because others say the exact opposite and watch files from same series.
