### ISSUE TITLE
Brightness setting doesn't have any effect on Intel N100 with EVR

### ISSUE THREAD

**Issue by bviktor** [clsid2/mpc-hc#2491]
Hi,

Just got myself a new motherboard with an [Intel N100](https://ark.intel.com/content/www/us/en/ark/products/231803/intel-processor-n100-6m-cache-up-to-3-40-ghz.html) in it.

![n100](https://github.com/clsid2/mpc-hc/assets/5798552/6315e770-9560-4666-831d-41660b3afaca)

The GPU part is just called ["Intel UHD Graphics"](https://www.techpowerup.com/gpu-specs/uhd-graphics-24eu-mobile.c4146), [it might be](https://en.wikipedia.org/wiki/Alder_Lake#Desktop_processors_(Alder_Lake-S)) the UHD Graphics 730, but I'm really not sure, for whatever reason Intel does everything to hide the specific model.

- GPU driver version: 31.0.101.5085 (latest, according to Intel DSA)
- Release date: January 10, 2024
- OS is Windows 10 22H2 19045.3930

While on my old mobo with the [J5005 / UHD 605](https://www.intel.com/content/www/us/en/products/sku/128984/intel-pentium-silver-j5005-processor-4m-cache-up-to-2-80-ghz/specifications.html) things were working fine, on this new one the brightness setting has no effect with the default EVR.

If I change it to madVR, it's working properly.

The interesting part is that after your fix in #159 the minimum value used to be 99 - on this new system it's 100 again, maybe not coincidentally.

Any ideas to fix it on EVR?

Thanks,
Viktor

**Comment by bviktor** [comment]
Actually, I might add that using madVR is pretty unstable, especially when trying to switch to full screen mode. The picture freezes but audio keeps playing, CPU usage spikes, etc. But that might be madVR's fault...

Edit: indeed, after reading up on it, I'm supposed to blend together their latest "stable" with their latest "testing" release to update - then it no longer crashes, so nvm.

**Comment by clsid2** [comment]
The newer Intel GPUs work better with DirectX11 renderer. They use a compatibility layer for DirectX9 which has several bugs.

I recommend MPC Video Renderer. It is available on the Releases page.
Also change hardware decoder to D3D11 in video decoder settings.

**Comment by bviktor** [comment]
Thanks, I'll try MPCVR then.

For the record, I tried switching to DX11 in EVR, it behaved the same way.

But in this case, the question is, why is the (according to you) inferior and buggy renderer shipped and used by default, while the better one isn't even included in the release and has to be added manually by the user? That's rather inconvenient and confusing TBH.

**Comment by clsid2** [comment]
EVR itself is DX9.
Using DX11 in decoder is purely to match what renderer uses and get most efficiency.

It is an external renderer. It is clearly mentioned on the download page what the recommendation is. It may get bundled in the future.

This bug exists only with the newer Intel GPUs. It will hopefully get fixed in either Intel driver of the d3d9on12 compatibility layer from Microsoft.
