### ISSUE TITLE
A minor issue with HLS streaming

### ISSUE THREAD

**Issue by roberto-sartori-gl** [clsid2/mpc-hc#2492]
Hi!

Thank you for your work maintaining MPC-HC, still the best media player on Windows!

I started playing remove media lately using MPC (HLS).

I have a minor issue:

1) I use a setup with multiple screens. When moving the MPC window between the screens, the playback is stopped and it never resumes (only when using HLS, local file playback works fine): at the moment, I can solve this disabling the option [options->playback->output->reinitialize when changing display], but this was causing rendering issues with MPC versions 1.9.x. 

I just switched to version 2.1.4 and I think those issues are fixed, but I also think that this option should not break playback when streaming: ideally, when the playback is reinitiliaze, this should happen also while HSL is used. 

If I'm using a playlist, I can just double click again on the same element in the playlist to start the streaming again, so ideally this should happen automatically when switching display.

Of course this is a minor problem, and I don't know the complexity of implementing this, but I just wanted to mention it.

Thanks again for your work!

**Comment by clsid2** [comment]
That issue is completely unrelated to streaming. It is purely graphics driver related in relation to hardware decoding. That in combination with possibly multiple GPUs.

Using DXVA2 copyback instead of DXVA2 native may solve it.

That is nothing I can do to fix or improve it.

**Comment by roberto-sartori-gl** [comment]
> That issue is completely unrelated to streaming. It is purely graphics driver related in relation to hardware decoding. That in combination with possibly multiple GPUs.
> 
> Using DXVA2 copyback instead of DXVA2 native may solve it.
> 
> That is nothing I can do to fix or improve it.

But it works perfectly with any other H/W accelerated video. If I'm playing a video that I have locally, there is no issue switching display (well I have maybe a second of black screen on MPC, but the playback resumes fine).

As I said in the first post, this issue is *only* present using HLS, so I'm pretty sure it is related to streaming as it is the only condition that can trigger it.

**Comment by clsid2** [comment]
Are you using an Intel GPU? Their DirectX9 support is just buggy and broken.

But anyway, it is all irrelevant. The current situation is as it is, and will remain as is. There will be no improvement in MPC-HC. I don't have these problems, so I can also not fix these problems. Many issues are drive related, and there is nothing I can do about it.

You should try MPC Video Renderer. Maybe that works better for you.
