### ISSUE TITLE
[2.14_Bug] Player > User Interface/Language translation application problems

### ISSUE THREAD

**Issue by kfen** [clsid2/mpc-hc#2493]
After testing the application of the language selection of the countries including: Chinese Simplified/Chinese Traditional/Russian/Spanish, the page still displays the English interface.

![QQ图片20240122222725](https://github.com/clsid2/mpc-hc/assets/36830580/8361025e-fc3d-4db3-abba-6ef112ee5003)
![QQ图片20240122230235](https://github.com/clsid2/mpc-hc/assets/36830580/182a7ec3-eb43-4c39-b60e-6e54af6e7cf5)

**Comment by clsid2** [comment]
Recently added strings are not yet translated in all languages.

**Comment by Solomag** [comment]
> Recently added strings are not yet translated in all languages.

Is it possible to help you with translations?

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/issues/215

Might be translated already, but you are welcome to help.

**Comment by kfen** [comment]
> #215
> 
> Might be translated already, but you are welcome to help.


> Recently added strings are not yet translated in all languages.



**It should be a problem that some fields are not fully translated.**



> `msgctxt "IDD_PPAGETHEME_IDC_CHECK8"
> msgid "Hover:"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_STATIC8"
> msgid "Hover type:"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_STATIC7"
> msgid "Preview width (% of screen)"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_CHECK2"
> msgid "Show chapter marks on seekbar"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_STATIC10"
> msgid "Status Bar Elements"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_CHECK3"
> msgid "Track Language"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_CHECK4"
> msgid "Video Info"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_CHECK5"
> msgid "FPS"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_CHECK6"
> msgid "A-B Marks"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_STATIC21"
> msgid "Language"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_STATIC5"
> msgid "Language:"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_STATIC9"
> msgid "On Screen Display (OSD)"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_SHOW_OSD"
> msgid "Show OSD (requires restart)"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_STATIC6"
> msgid "Font:"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_STATIC23"
> msgid "Font size:"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_STATIC"
> msgid "Window Behavior"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_CHECK7"
> msgid "Limit window proportions on resize"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_CHECK9"
> msgid "Snap to desktop edges"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_CHECK10"
> msgid "Hide Windowed Controls"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_STATIC"
> msgid "Windows Integration"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_CHECK_ENHANCED_TASKBAR"
> msgid "Use enhanced taskbar features"
> msgstr ""
> 
> msgctxt "IDD_PPAGETHEME_IDC_CHECK11"
> msgid "Control via Windows UI (SMTC)"
> msgstr ""`
> 
> 
> 
>

**Comment by adipose** [comment]
https://github.com/adipose/mpc-hc/commit/9f5b98cdc82174a0888d69589f57b6a6887c22e2

Just needs to be merged.
