### ISSUE TITLE
Changing After Playback action does not persist

### ISSUE THREAD

**Issue by Koli0842** [clsid2/mpc-hc#2494]
My current after playback setting is "Do Nothing"
I open MPC-HC, Play > After Playback > Select "Play next file in folder". It works as expected at this point. Closing and reopening MPC-HC has the option back on the default "Do Nothing". I have not seen such preference under the Options screen either. Attempting to do the same steps as admin results in the same behaviour.

**Comment by clsid2** [comment]
The one in menu is only for current session.

Options > Playback > After playback

**Comment by xLn2** [comment]
[Overview of features](https://github.com/clsid2/mpc-hc#overview-of-features)
> You can perform automatic actions at end of file. For example to go to next file or close player.
> Options > Playback > After Playback (permanent setting)
> Menu > Play > After Playback (for current file only)

**Comment by Koli0842** [comment]
Thanks for the super quick reply!
I just went through the options and missed it, sorry! Maybe because I had the Playback option on "repeat forever" and the actual dropdown was grayed out. As a potential improvement, I would enjoy having a "repeat this file indefinitely" option for the current session options
Thank you for the continued development of this awesome player
