### ISSUE TITLE
Compilation instruction needs update, Source missing Libraries 

### ISSUE THREAD

**Issue by DibyaXPP** [clsid2/mpc-hc#2495]
Hello , I am trying to compile your MPC-HC , 

Here is a problem , their lots of missing libraries [C & CPP Files] 

I have ran git clone https://github.com/clsid2/mpc-hc/ , then build mpc-hc.sln in release lite configuration , 

Am i doing something wrong? 

Regards 

Here is log from VS 2019 [I Have MFC/ATL/UCRT/Win8.1SDK Installed] 

[buillog.txt](https://github.com/clsid2/mpc-hc/files/14049102/buillog.txt)

**Comment by v0lt** [comment]
Clone the entire repository with all submodules.
`git clone --recursive https://github.com/clsid2/mpc-hc.git`


In the future, update the previously cloned repository with something like this:
```
git pull
git submodule update --init --recursive
```

**Comment by DibyaXPP** [comment]
Thanks for help , 

After  git clone --recursive https://github.com/clsid2/mpc-hc.git

5 still failed, 
[BuildlOg2.txt](https://github.com/clsid2/mpc-hc/files/14049961/BuildlOg2.txt)


Severity	Code	Description	Project	File	Line	Suppression State
Message		see previous definition of '_libiconv_version' (compiling source file libiconv-for-Windows\libiconv\lib\iconv.c)	libiconv	C:\MPC_XP\mpc-hc\src\thirdparty\libiconv\libiconv-for-Windows\libiconv\include\iconv.h	32	
Error	MSB3721	The command "yasm.exe -X vc -f win32    -o "C:\MPC_XP\mpc-hc\bin\obj\Release_Win32\system\a_memory.obj" "C:\MPC_XP\mpc-hc\src\thirdparty\VirtualDub\system\source\a_memory.asm"" exited with code 1.	system	C:\MPC_XP\mpc-hc\src\YASM.targets	45	
Error	MSB3721	The command "yasm.exe -X vc -f win32    -o "C:\MPC_XP\mpc-hc\bin\obj\Release_Win32\Kasumi\a_bltrgb.obj" "C:\MPC_XP\mpc-hc\src\thirdparty\VirtualDub\Kasumi\source\a_bltrgb.asm"" exited with code 1.	Kasumi	C:\MPC_XP\mpc-hc\src\YASM.targets	45	
Error		Please define MPCHC_MINGW64 environment variable	BuildConfig	C:\MPC_XP\mpc-hc\build\EXEC	1	
Error	MSB3073	The command "..\update_mingwlib.bat" exited with code -1.	BuildConfig	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets	46	
Error	MSB3073	The command "ffmpeg.bat" exited with code 1.	ffmpeg	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets	46	
Message		see declaration of 'std::codecvt_utf8' (compiling source file LibassContext.cpp)	Subtitles	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\codecvt	33	
Message		see declaration of 'std::wstring_convert' (compiling source file LibassContext.cpp)	Subtitles	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xlocbuf	300	
Message		see declaration of 'std::codecvt_utf8' (compiling source file LibassContext.cpp)	Subtitles	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\codecvt	33	
Message		see declaration of 'std::wstring_convert' (compiling source file LibassContext.cpp)	Subtitles	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xlocbuf	300	
Error	C1083	Cannot open include file: '../build/version_rev.h': No such file or directory (compiling source file mplayerc.cpp)	mpc-hc	C:\MPC_XP\mpc-hc\include\version.h	46	
Message		see declaration of 'Microsoft::WRL::Wrappers::HString::MakeReference' (compiling source file MediaTransControls.cpp)	mpc-hc	C:\Program Files (x86)\Windows Kits\8.1\Include\winrt\wrl\wrappers\corewrappers.h	857	
Message		see declaration of 'Microsoft::WRL::Wrappers::HString::MakeReference' (compiling source file MediaTransControls.cpp)	mpc-hc	C:\Program Files (x86)\Windows Kits\8.1\Include\winrt\wrl\wrappers\corewrappers.h	860	
Error	C1083	Cannot open include file: '../build/version_rev.h': No such file or directory (compiling source file VersionInfo.cpp)	mpc-hc	C:\MPC_XP\mpc-hc\include\version.h	46	


Please can u have a look

**Comment by v0lt** [comment]
There are official instructions.
https://github.com/clsid2/mpc-hc/blob/develop/docs/Compilation.md
It looks like you haven't completed the following steps.
- Part C: Preparing the MSYS and GCC environment (optional)
- Part D: Yasm
- Part E: Config file with paths

PS: I haven’t tried to assemble MPC-HC for a very long time and may not know all the nuances. But in any case, you should follow the official instructions.
