### ISSUE TITLE
Opensubtitles.com  issue with pt-br

### ISSUE THREAD

**Issue by LeoKesler** [clsid2/mpc-hc#2498]
Hi.

I am unable to download subtitles for language pt-BR.  

Until december, I was able to download the subtitles from opensubtitles.org correctly.  The language configured was pob pb en . 

But after I upgraded to lastest available version, 2.1.4, the new opensubtitle.com do not find any subtitle for pt-br language. Same settings, same language order. I tried to use each one separately, only pob, only pb, without success.

**Comment by clsid2** [comment]
You will have to ask on OpenSubtitles forum why it does not give results for `pb`.

**Comment by opensubtitlesdev** [comment]
because the code for portuguese brazilian is pt-BR
the languages codes can be found here 
https://opensubtitles.stoplight.io/docs/opensubtitles-api/1de776d20e873-languages

using the api request to keep the list updated (the list in the docs is not up to date)

**Comment by LeoKesler** [comment]
@opensubtitlesdev Sorry, but it is not working. Using pt-BR or pt-br, the result is the same, the api returns results for different languages.
Look at screenshot. In the image, I use pt-br, but using pt-BR had the same result.

![mpc-hc-subtitles-issue](https://github.com/clsid2/mpc-hc/assets/5854679/cc49a112-e8dc-4f9f-b4d6-dee40eb5193f)

**Comment by opensubtitlesdev** [comment]
Sorry I don't know your application, or what these screenshots represent.

please go back to the basic and test the endpoints with insomnia, postman or a similar, then if you find something that isn't working you can copy it as CURL and send it to us, for example like this.

  curl --request GET \
  --url 'https://api.opensubtitles.com/api/v1/subtitles?query=matrix&=&languages=pt-BR' \
  --header 'Api-Key: MY_API_KEY' \
  --header 'User-Agent: test' \

**Comment by LeoKesler** [comment]
@opensubtitlesdev I am not a developer. I do not have an API Key. 

About the screenshot, I will explain. It  is easy to understand.

The white arrow shows the language I selected, pt-br.

The yellow arrow shows the subtitles and languages returned by API, when I use pt-br.

If you take a look, you will see the API returned many languages except pt-br. French, English, Italian etc... except pt-br.


![mpc-hc-subtitles-issue](https://github.com/clsid2/mpc-hc/assets/5854679/e8594355-3aa1-4481-a3db-5b05af3d4e72)

**Comment by clsid2** [comment]
@opensubtitlesdev 
.org uses `pb` instead of `pt-br`.
Can you give a list of all supported language codes for .com?
I need to add special handling to send `pt-br` as parameter. Currently all code uses ISO 639 format (2 or 3 letters).

**Comment by opensubtitlesdev** [comment]
> @opensubtitlesdev .org uses `pb` instead of `pt-br`. Can you give a list of all supported language codes for .com? I need to add special handling to send `pt-br` as parameter. Currently all code uses ISO 639 format (2 or 3 letters).

sure. it was in my first post 
https://opensubtitles.stoplight.io/docs/opensubtitles-api/1de776d20e873-languages

take the list from the API, I recently added more languages and the list in the docs is not up to date

as our app is rails based, we simply followed the rails way, having ISO 639-1 and ISO 3166-1 alpha-2, to handle either simple languages, or languages with a regional specific, with iso 639 in 3 chars you can't handle things like portuguese from mozambique or brasil, we had to use an alternative table with things like that pb that doesn't exist anywhere else...

**Comment by clsid2** [comment]
Fixed
