### ISSUE TITLE
Feature/fix:  Option to force 'Save Image' to output in the original resolution

### ISSUE THREAD

**Issue by Vagmer** [clsid2/mpc-hc#25]
It seems that currently, using ALT-I (File->Save Image) in a video always saves an image of the current frame in the current dimensions of the player window - exactly as the user sees it. So the output image includes the downscaling, upscaling or the black bars, accordingly. There is no option to manually select or type the target resolution you want.
This is actually a big issue in scenarios where you want a target resolution that is bigger than the maximum size that you can get the player window to. For example, assume that I want to save snapshots of videos in their original resolution, and my monitor and OS resolution is 1920x1080. If I open a 720p video, I just need to press ALT-2 (ensures the window size is the same as the size of the video) to resize the window, then press ALT-I to make the snapshot, and I get a 1280x720 image, accordingly. Now if I open a 1080p video, then using the previous method is not enough (the player window size doesn't actually cover the whole screen, because of the GUI and aspect ratios), to same a full-size image I must go to fullscreen first instead, so the sequence is ALT-ENTER and ALT-I. Well, that works.
The problem is when, say, I'm on my laptop with a monitor with the native resolution of 1366x768. Then I can save a full-size snapshot of a 720p video as per above, but I can't do so with a 1080p video, since even fullscreen I'd only save a downscaled 1366x768 image. Couldn't find a way to work around that with no amount of messing around (I can't even increase my OS resolution further, at least normally). So either I'm missing something crucial or it's a crucial oversight, and the 'Save Image' feature should have an option to manually change/select the output image's resolution (slightly more useful to allow customizable values in case someone may want like a 1500x843 output or something).
This issue may or may not be also relevant to the 'Save Thumbnails' feature.

On that subject, this reminds me/confirms that the image (/"screenshot") taken is always the result of what the player decodes and displays to the user during normal playback including any filters and processing done to the frame - would it be possible, if it's not particularly time consuming, to add an additional option/checkbox be added to save a screenshot as a mere 'frame extraction'. without the application of extra processing? Both approaches have their uses. I am pretty clueless as to whether that'd be much more work than I imagine and not worth it for this program, though.

**Comment by clsid2** [comment]
You are wrong, it already takes the screenshot at the original resolution of the video, when using the internal video renderer.

If you use MadVR as video renderer, then you can customize in its settings how screenshots are made.

**Comment by Vagmer** [comment]
Ah, I see. My bad, thanks!

**Comment by SweetCarrot0** [comment]
Thank You, Sir.
