### ISSUE TITLE
Audio skipping

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2501]
At 1 second of this video: https://drive.google.com/file/d/1SFx9Cofs-l7b-VPzYWpx-w5k31YD4lYX/view?usp=sharing

**Comment by clsid2** [comment]
Disable "Auto A/V sync correction" in LAV Audio Decoder.

**Comment by bibsp** [comment]
You should disable this setting in default settings of player. This option always creates problem. If anybody still likes this option he can enable this. By default enabling this option is useless. The reason is, no other players have this issue with their default settings.
