### ISSUE TITLE
[FEATURE] Set "Enqueue" file as default action

### ISSUE THREAD

**Issue by ryehamstrawberry** [clsid2/mpc-hc#2505]
Please implement the ability to enqueue files to the end of the active MPC-HC playlist.
I looked through the existing settings and couldn't find any way to enforce this behavior.

I'm only aware of two options to send a file to playlist:
1. shell integration via right-click context menu "Add to MPC-HC Playlist" or;
2. drag and drop files directly into the active playlist.

Am I overlooking something or is there another reason this basic functionality has been excluded?
Users should be able to simply double-click their video files and have them be added to their active playlist instead of being forced to open.

**Comment by clsid2** [comment]
You can also hold Ctrl while dropping on video area.

**Comment by ryehamstrawberry** [comment]
You already have "Add to MPC-HC Playlist" accessible via context menu, how much harder would it be to just extend this option to the Settings dialog and allow users the option to enable it by default if they choose?
Currently, users are forced to waste a lot of extra effort accessing a context menu entry that would otherwise be redundant if this very common action would be allowed to be enabled by default.


Examples of other popular media players including this very basic feature, this isn't a request for some niche feature:
![deadbeef_Xtz5w3uaOe](https://github.com/clsid2/mpc-hc/assets/110439000/94384c89-949c-4451-b10f-8594ac01c279)
![foobar2000_5X3b4cv0Hm](https://github.com/clsid2/mpc-hc/assets/110439000/833329e5-c74b-4ac9-a1dd-8d333fb2f95d)
![smplayer_Lk4gW3MnUc](https://github.com/clsid2/mpc-hc/assets/110439000/b63cbb04-365e-46c9-bb44-bed2aec376ca)
![vlc_4vptmhSegA](https://github.com/clsid2/mpc-hc/assets/110439000/b38a8ab3-4550-4039-b429-904be0c92a17)
![winamp_moDScMXpEu](https://github.com/clsid2/mpc-hc/assets/110439000/6919433b-178c-4587-95b6-5a4048993258)


I respectfully ask that you reconsider adding a simple option to permit the currently existing "Add to MPC-HC Playlist" context menu entry to be the default behavior for those who choose. This would mitigate the need to "plan" any work beyond a way to access the option in a way that would allowing users the option to enqueue files by default like any sane human. Thank you in advance.

**Comment by clsid2** [comment]
Then you have plenty of specialized audio players to choose from.

I am not implementing it.

You can manually modify your (audio) file associations to use /enqueue

**Comment by clsid2** [comment]
You can make a donation to get it implemented.

**Comment by ryehamstrawberry** [comment]
> You can manually modify your (audio) file associations to use /enqueue

This is done how? There's no documentation I can find on this.

> Then you have plenty of specialized audio players to choose from.

Enqueue by default isn't just for "special" audio use (it's strange you imply that) but is useful for anyone with a large workflow or entertainment setup that requires utilizing playlists regularly.

I bet a significant number of people would want their default action to be enqueue and don't even know it's possible because the only ways to add files to playlist are counter-intuitive.
Adding files to a playlist is a fundamental behavior of any media player, why prevent users from using the most common mouse action to access it?

There's almost no reason NOT to use enqueue by default since those users who want videos to play on open will still get that behavior as long as their playlist is empty (i.e. they remove their video after watching it).

**Comment by ryehamstrawberry** [comment]
For MPC-HC power users that utilize playlists frequently and want the option to enqueue files by default, modify the following registry keys:
- HKEY_CLASSES_ROOT\mplayerc64.mkv\shell\open\command
- Add /add switch:
Open By Default: "C:\Program Files\MPC-HC\mpc-hc64.exe" "%1"
Enqueue By Default: "C:\Program Files\MPC-HC\mpc-hc64.exe" /add "%1"
- Repeat for all desired extensions, example:
HKEY_CLASSES_ROOT\mplayerc64.avi\shell\open\command
HKEY_CLASSES_ROOT\mplayerc64.mov\shell\open\command
HKEY_CLASSES_ROOT\mplayerc64.mp4\shell\open\command
etc.

Here's to hoping a simple toggle will be considered.
