### ISSUE TITLE
Can you pleaase add total time of playlist?

### ISSUE THREAD

**Issue by Barabba11** [clsid2/mpc-hc#2506]
Hi, thab you for your kind attention, this is extremaly useful feature to determine if the quantity of media is enough to cover certain time.
It may load the device as it should process all files, you may add an option to skip it and calculate totale time on just the already known/loaded media, it's also useful. Thank you a lot!

**Comment by clsid2** [comment]
For preload:
Options > Advanced > UseMediaInfoLoadFileDuration

There is no display of total duration. Will not be added.
