### ISSUE TITLE
Flicker issues on Options > Playback > Fullscreen (cursor)

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#2513]
![image](https://github.com/clsid2/mpc-hc/assets/3324395/3c2ae063-5606-4ab6-adc8-01a1c06b2f06)

>Tooltips are trying to show up.

**Comment by adipose** [comment]
@xLn2, issue affects classic and modern theme.

I don't think it's a tooltip.

**Comment by xLn2** [comment]
I misinterpreted issue, non edit style overlaping on edit while editing probably.

![mpc-hc64_K4AVbKTeBm](https://github.com/clsid2/mpc-hc/assets/3073922/68f32873-b2fb-4263-9278-2489712ab149)

![mpc-hc64_AYeOHKR8Hz](https://github.com/clsid2/mpc-hc/assets/3073922/868a8eec-2419-4b36-9773-ed54fb701fa5)

**Comment by adipose** [comment]
I think so as well.  Probably a one-pixel gap between the listctrl and the edit overlay.  It's sneaking in a hover update or something...this is an old widget but I'll take a look.

**Comment by adipose** [comment]
The issue seems to be associated with the cursor.  As the cursor transitions from the hovering edit to the listctrl parent, it seems to show an inverted copy of the hand cursor.  It's almost as if it's trying to invert the hand cursor for the listctrl, but due to the edit being in the way, it has nothing to erase.

Disabling the cursor for the edit solves it, but then the bar cursor is not used correctly in the edit.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2532

Partially fixed, perhaps acceptable now.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2536

This fixes the double draw issue.
