### ISSUE TITLE
Options > Playback > Fullscreen tooltip issue

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#2514]
>     7. Options > Playback > Fullscreen
> 
> 
> Tooltips are trying to show up. 

![image](https://github.com/clsid2/mpc-hc/assets/3324395/ec76d7c2-7ee3-4c5c-919e-773f41ca77a1)

**Comment by xLn2** [comment]
dublicate of https://github.com/clsid2/mpc-hc/issues/2513
