### ISSUE TITLE
Help / About button selection draw issue

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#2516]
> Ghost selection mark also arrives on Apply, Ok button. Click on those buttons then it will appear.

![image](https://github.com/clsid2/mpc-hc/assets/3324395/3272bb51-4db2-4fae-9ee7-33364d70cc3b)

**Comment by xLn2** [comment]
Every active buttons have this dotted selection mark so I thought it isn't a problem. If it is perceived ugly,  It is useful to know that all buttons affected by this behavior.

**Comment by adipose** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/3324395/b36c0ad1-243c-4cfd-a379-be1b842f560c)

Agreed, closing this.
