### ISSUE TITLE
2.1.4.14 Nighly: Options' text letters tails are cut off

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2519]
![image](https://github.com/clsid2/mpc-hc/assets/3073922/25b8e512-ad93-4581-8e31-797702a18d05) 2.1.4.14
![image](https://github.com/clsid2/mpc-hc/assets/3073922/c2a5300d-9038-4a84-a79a-63d6228d6b27) 2.1.4

![image](https://github.com/clsid2/mpc-hc/assets/3073922/eb4b523d-3b3f-4144-b5ee-365d8e879aa8) 2.1.4.14
![image](https://github.com/clsid2/mpc-hc/assets/3073922/3344ed93-2091-4285-941d-431df73b1ad7) 2.1.4

![image](https://github.com/clsid2/mpc-hc/assets/3073922/9660f4bd-bcf4-417d-a8bc-6c23235d871c) 2.1.4.14
![image](https://github.com/clsid2/mpc-hc/assets/3073922/71e8e7fc-3c4f-4f66-9477-7a88796e0c96) 2.1.4

Nightly version 2.1.4.14 has a issue that options and checkboxes letters' _tails_ are cut off. Might be related with latest changes https://github.com/clsid2/mpc-hc/pull/2509

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2523
