### ISSUE TITLE
Options > Player > Keys: Toggle Dark theme, doesn't work as expected.

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2520]
![image](https://github.com/clsid2/mpc-hc/assets/3073922/0204e5c4-39f4-41dc-86e6-2757bc1e66fc)

Toggle works as Enable/Disable Modern theme, it doesn't check whether its modern light theme.

Maybe its function can be changed as switch modern theme color

or can be removed because it is not like toggle experience since it requires restart.

**Comment by clsid2** [comment]
I didn't even know that existed. I am fine with removing it.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2537
