### ISSUE TITLE
app crash when loading extra long URL/playlist

### ISSUE THREAD

**Issue by hadu-boired** [clsid2/mpc-hc#2521]
ongoing issue since version 2.x, prior builds work fine in this case.

a livestream playlist is generated with [streamlink](https://github.com/streamlink/streamlink) by scripted command like this, 

`streamlink.exe -p "mpc-hc64.exe" -a "/nofocus" "%URL%"`
 
is queued/opened in mpc no problem, switching from another file or reloading it consistently causes a hang.

example playlist content,

``` 
MPCPLAYLIST
1,type,0
1,label,CskEsjOKGjxKRlDesdpLIegXAGKIhL7LznmDPtBshzrbyeYdbwCTyds-sFIbttT4OJaOyeBPeBzRc8HSx2dCldrA1kkK9uI_Si-gDcR3r3K1YdrgVpZSh6DEAkRh5aTo3UgGYHl9HdsXwkbIY64wxsT792OxIt0oJ7N5Fmmb0ZX3yYO3b5qWyLD6G2kwhlT4Lc470FnfzbNQgAWWp02lAyuOss3lKPM7Qgo3rx9AHnxrB_f7r5XrEHoMgfmhbT5HFKuZ6kcHeMhRTOLkJ99_BELrv5XWSSZxi5G121oiyMKiDHNLC65eHN9S4BiufednDce7jSUZdSZK3YpRvPGee-Oap-oi8V5Fq28yWySaD4VIYHGALpC8-7PRnXqjT5Ok3am73ot8GMK9pfUAYrMTx6R6wuEuR_VGCoUkkU_KYp-SGLqe8BtmZDd03txYjxYYbxDHTCh_tlHIzqgtmWeacz81pShZ4UjX6yz4_d0Gv7eY1dQs-vo7gmUF-fcj5BRARN68mzFOi-UEhRRKDXHsU5fbTpezd8uCkLD50J-Mqcxdtetm1XeXrgunBYe2EtIMD__KXnW8fuMtPcn3l6eSfbNGD1-CTe_CN8d-WHRhrDlIBCnS0UVXYwQEwMea9AQPtAZzZeqB7yzkKovo1yBrrqDP4R5vdf6cFaha9Buk2rWFRL-GsMn6y_VVEI30gLAtj2qJbq9-JPQQOH2rvsvtyMoN09y6lb1MH3fkqRcWWOsFkHIRlb8irK_nwCiDBB2nT6pk7z9Cz6-YXkDqGgxw1fMSuxACOwedpkEgASoJdXMtd2VzdC0yMNEI 2024-02-03 19:47 (video-weaver.jfk04.hls.ttvnw.net)
1,filename,https://video-weaver.jfk04.hls.ttvnw.net/v1/playlist/CskEsjOKGjxKRlDesdpLIegXAGKIhL7LznmDPtBshzrbyeYdbwCTyds-sFIbttT4OJaOyeBPeBzRc8HSx2dCldrA1kkK9uI_Si-gDcR3r3K1YdrgVpZSh6DEAkRh5aTo3UgGYHl9HdsXwkbIY64wxsT792OxIt0oJ7N5Fmmb0ZX3yYO3b5qWyLD6G2kwhlT4Lc470FnfzbNQgAWWp02lAyuOss3lKPM7Qgo3rx9AHnxrB_f7r5XrEHoMgfmhbT5HFKuZ6kcHeMhRTOLkJ99_BELrv5XWSSZxi5G121oiyMKiDHNLC65eHN9S4BiufednDce7jSUZdSZK3YpRvPGee-Oap-oi8V5Fq28yWySaD4VIYHGALpC8-7PRnXqjT5Ok3am73ot8GMK9pfUAYrMTx6R6wuEuR_VGCoUkkU_KYp-SGLqe8BtmZDd03txYjxYYbxDHTCh_tlHIzqgtmWeacz81pShZ4UjX6yz4_d0Gv7eY1dQs-vo7gmUF-fcj5BRARN68mzFOi-UEhRRKDXHsU5fbTpezd8uCkLD50J-Mqcxdtetm1XeXrgunBYe2EtIMD__KXnW8fuMtPcn3l6eSfbNGD1-CTe_CN8d-WHRhrDlIBCnS0UVXYwQEwMea9AQPtAZzZeqB7yzkKovo1yBrrqDP4R5vdf6cFaha9Buk2rWFRL-GsMn6y_VVEI30gLAtj2qJbq9-JPQQOH2rvsvtyMoN09y6lb1MH3fkqRcWWOsFkHIRlb8irK_nwCiDBB2nT6pk7z9Cz6-YXkDqGgxw1fMSuxACOwedpkEgASoJdXMtd2VzdC0yMNEI.m3u8

**Comment by clsid2** [comment]
That URL opens fine here. Reloading also works fine.
I don't use Streamlink and I am not interested in trying it either.

**Comment by adipose** [comment]
Can track down the build where it broke?

**Comment by hadu-boired** [comment]
> Can track down the build where it broke?

1.9.3 is the last one that worked, tried the first 2.x stable release and others. they all do this

**Comment by adipose** [comment]
> > Can track down the build where it broke?
> 
> 
> 
> 1.9.3 is the last one that worked, tried other 2.x stable releases. they all do this

So 1.9.4 has the issue?

**Comment by hadu-boired** [comment]
> So 1.9.4 has the issue?

no such build in the release log, my own packs went up to 1.9.3 which maybe refers to 1.9.24.8? idk

**Comment by adipose** [comment]
> > So 1.9.4 has the issue?
> 
> no such build in the release log, my own packs went up to 1.9.3 which maybe refers to 1.9.24.8? idk

https://github.com/clsid2/mpc-hc/releases?page=5

You can download intermediate release builds here.  Please track down the build where it broke.

**Comment by hadu-boired** [comment]
went back to 1.9.9 and could not reproduce this, can get it to hang in 2.0.0 first try.

looks related to their preroll segment ("Preparing your stream...") and/or some relevant caching step. when frames continue from the live channel at that point, all versions run no problem. if it hangs on this preroll, 1.x can manually reload the channel, where 2.x crashes every time.

**Comment by adipose** [comment]
Between 1.9.9 and 2.0.0 there are many builds.  It goes all the way to 1.9.24 (24 > 9, it's a subrev not a decimal!).

So try going halfway, so 24 - 9 = 15; 15 / 2 = 7; 9+7=16; test 1.9.16.

If 1.9.16 doesn't have the issue yet, 24 - 16 = 8; 8 / 2 = 4; 16+4=20; test 1.9.20

etc.

**Comment by clsid2** [comment]
It is likely an issue with FFmpeg and not the player itself.

If it crashes, then copy link to drdump crash report.

**Comment by hadu-boired** [comment]
narrowed it down to 1.9.21.2, crash on hung prerolls every time. 1.9.20, no crash.

crash reporter is enabled but it isnt being handled

**Comment by clsid2** [comment]
Test 1.9.21.2 with LAVFilters folder from 1.9.20

**Comment by hadu-boired** [comment]
> Test 1.9.21.2 with LAVFilters folder from 1.9.20

no change in 1.9.21 or above versions

**Comment by adipose** [comment]
> > Test 1.9.21.2 with LAVFilters folder from 1.9.20
> 
> 
> 
> no change in 1.9.21 or above versions
> 

So 1.9.21 with LAVFilters from 1.9.20 still hangs?

**Comment by clsid2** [comment]
Here are more versions in between:
https://github.com/clsid2/mpc-hc/releases/tag/1.9.20.10

**Comment by hadu-boired** [comment]
> So 1.9.21 with LAVFilters from 1.9.20 still hangs?

yes just copy everything in .\LAVFilters64 from 1.9.20 right, it still crashes. but i can do the converse, eg. use filters from 2.1.4 in 1.9.20.17 and not crash.

> Here are more versions in between: https://github.com/clsid2/mpc-hc/releases/tag/1.9.20.10

good up to 1.9.20.17 here, reproduced in 1.9.20.21

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/compare/1a7116adf5a0d8a4c10d6cfe0ad27bfe4330b0f5...b7cfaace81d7ca748fb95a311b66ae9cde123b88

I think this is about the right diff, @clsid2  ?

**Comment by adipose** [comment]
It seems the main thing here that may have an impact would be fullscreenseparatecontrols, though I can't right now think of why it would.

@hadu-boired , do you have that enabled--can you disable it and retry?

**Comment by clsid2** [comment]
1.9.20.18 adds just the option. In 19.20.17 fullscreenseparatecontrols was already implemented.

Test if problem only occurs when fullscreen on second monitor.

**Comment by hadu-boired** [comment]
all tests run in windowed mode, single monitor only. not sure what fullscreenseparatecontrols refers to, is this the 'hide controls in fullscreen' option in playback > fullscreen? this is on, disabling it doesnt prevent crashing.

**Comment by clsid2** [comment]
Does removing /nofocus perhaps have an effect?
Which video renderer are you using?

Can you reproduce it if you execute mpc-hc yourself from windows command prompt?

**Comment by hadu-boired** [comment]
> Does removing /nofocus perhaps have an effect? Which video renderer are you using?

it does not, set to Enhanced Video Renderer (custom presenter)

> Can you reproduce it if you execute mpc-hc yourself from windows command prompt?

streamlink is needed to generate the playlist, i dont see a way to break this workflow before it gets handed to the media player. also where twitch.tv inserts the preroll and causes a potential crash, reloading the playlist from that point skips the preroll.

the crash could also be avoided by pausing playback, wait till the preroll is over (~15s), resume the appended stream

**Comment by clsid2** [comment]
If you put [yt-dlp.exe](https://github.com/yt-dlp/yt-dlp/releases) in MPC-HC folder, then you can open twitch links directly in MPC-HC. Maybe that works better.

**Comment by adipose** [comment]
> all tests run in windowed mode, single monitor only. not sure what fullscreenseparatecontrols refers to, is this the 'hide controls in fullscreen' option in playback > fullscreen? this is on, disabling it doesnt prevent crashing.

![image](https://github.com/clsid2/mpc-hc/assets/3324395/b2bb1aa5-745b-4e7a-a0c0-64c137006bed)

**Comment by hadu-boired** [comment]
^thats should be the default right, never enabled it since im not on a multimon setup

> If you put [yt-dlp.exe](https://github.com/yt-dlp/yt-dlp/releases) in MPC-HC folder, then you can open twitch links directly in MPC-HC. Maybe that works better.

i do this for youtube already, it doesnt support twitch.tv links at least from within mpc

but twitch is apparently among supported sites now that i look at the list of extractors

**Comment by hadu-boired** [comment]
```
youtube-dl -o - "twitch.tv/kitboga" | mpc-hc64 -
[generic] Extracting URL: twitch.tv/kitboga
WARNING: [generic] The url doesn't specify the protocol, trying with http
[twitch:stream] Extracting URL: http://twitch.tv/kitboga
[twitch:stream] kitboga: Downloading stream GraphQL
[twitch:stream] kitboga: Downloading stream access token GraphQL
[twitch:stream] 42294126425: Downloading m3u8 information
[info] 42294126425: Downloading 1 format(s): 1080p__source_
[download] Destination: -
[tcp @ 00000000004c0000] Connection to tcp://video-weaver.jfk04.hls.ttvnw.net:443 failed: Error number -138 occurred
https://video-weaver.jfk04.hls.ttvnw.net/v1/playlist/CrEEo25YeZN-govAwB5Cefxe85fkxHy9Vi8ghIzBi4ivZvIl0s4PediGyadILgZn85bEhPsMjJCWUjr8CL8v22m5YohcDQZDa-Hj1IFyGQ_CbaA8hb3GPUBiX_HrGBuHHNhuzhuqqqEP0-nTMP0ikHHWczYcUl_xP3-nPsv3UVkmjBzoZ6DcQxr1pnw9NVQObHzq25WQBgybbs5Qq53Wu2sLcrd30Qc-Sp1n-Lg5G3yk_sua9BnUZqtFlo2I0w49dOL0vQnVNxZZR-ZtLMSxCd-HqQFF0ZSgWmJfwjIiGdKskt92Y5ct3VF8o2AvM8Uf_BvtNPARU1BvJbIMHVglVDsLtgr3HTLLzHFePc3bSJiPj1lB6Ka5mD3YssEfooGOlo28xkmtToq6gSeA-HehwDNZT5oAZoS5GwL2T11KTeoEcN_XMmzEe0J7WcTzDkMnaozzFrd-hCj7m17921Bdvm81pbBhaKA-7VQsg_x7um7Rxjx1YjYCCVa4E6r3mtIstP-xuBWjxDKh5rZV67cvZEvFhsJ7_-HaP4kC9Uj0dkArSz_lFPBc2szzphfodhv-cw2s0iUJ6U_zTFRTEH5MTKrMP4jQNkPO6zk7Jblb_H4X4Vgi8VGDc2Hvwp579UkF77bz-E93h74b3ydjOa3ipb1Bb3gwYzk5YgaR6M8NJWJ2b_I53xAbBJqKV7MVqq_gCH8-IHKgXV-hG2hyA77h4dAYv77_RKkp79OSEBWDlAgUidjAGgzSlsGldYdy4atsFNAgASoJdXMtZWFzdC0xMIsH.m3u8: Unknown error


ERROR: ffmpeg exited with code 1
```

stdout no problem on yt

```
youtube-dl -o - "https://www.youtube.com/watch?v=wpAsU8m0TeI" | mpc-hc64 -
[youtube] Extracting URL: https://www.youtube.com/watch?v=wpAsU8m0TeI
[youtube] wpAsU8m0TeI: Downloading webpage
[youtube] wpAsU8m0TeI: Downloading ios player API JSON
[youtube] wpAsU8m0TeI: Downloading android player API JSON
[youtube] wpAsU8m0TeI: Downloading m3u8 information
[info] wpAsU8m0TeI: Downloading 1 format(s): 22
[download] Destination: -
[download] 100% of   88.32MiB in 00:03:35 at 419.59KiB/s
```

**Comment by clsid2** [comment]
Twitch works perfectly fine here. You should use yt-dlp, not the outdated youtube-dl.

**Comment by hadu-boired** [comment]
> Twitch works perfectly fine here. You should use yt-dlp, not the outdated youtube-dl.

i do, its just renamed for scripting purposes. i thought it also required for mpc unless we change YDLExePath

token error maybe, are you logged in?

**Comment by clsid2** [comment]
No login. You need to open URL from within MPC-HC, not pipe output.

yt-dlp.exe is supported directly. YDLExePath is only needed if outside of mpc-hc folder.

**Comment by clsid2** [comment]
Maybe use `--player-http` for Streamlink?

**Comment by hadu-boired** [comment]
never worked in mpc, only accepts `--player-passthrough=hls/http`

i managed to load twitch addys in 2.x mpc/updated yt-dlp. gets entirely different prerolls and apparently doesnt hang, guess i will switch to that if theres no other solution here.

**Comment by clsid2** [comment]
Tried Streamlink with all its default settings and it seems to work fine. No issue with pre-roll before stream start.

Stream discontinuities can cause (short) hangs. There is one after pre-roll according to Streamlink output log.

**Comment by hadu-boired** [comment]
doesnt happen every time, you get a preroll in maybe a third of your playlists, another third of those might hang. of the ones that fail to load live streaming frames (audio continues till the buffer runs out), 100% of them will crash if i try to close the player or touch the playlist entry at all.

**Comment by clsid2** [comment]
Tried several and no crashes. Do you have an example twitch URL that crashes?

If it send corrupt data that hangs LAV Filters, then there is nothing I can do. It does not appear to be an issue with the player itself.

**Comment by hadu-boired** [comment]
it's totally arbitrary, if you load a previous channel that already ran the preroll and watch it all the way, they may skip it too. the way i tested was just going down the page loading unviewed channels, also had a custom ui to automate this.

**Comment by clsid2** [comment]
Does Streamlink emit any errors or warnings right before problem happens?

I am not going to spend more time testing streams.

**Comment by hadu-boired** [comment]
`[stream.hls][warning] Encountered a stream discontinuity. This is unsupported and will result in incoherent output data.`

is a typical warning, but not consistent to any failed/successful channel loads far as i can tell
