### ISSUE TITLE
Double "\" in path name in specific situations

### ISSUE THREAD

**Issue by Max33Verstappen** [clsid2/mpc-hc#2525]
If a path with a trailing `\` but _**without quotes**_ (which implies it doesn't have spaces in it) is passed to MPC-HC, eg: (a BD Folder)
`\\XXX-NAS\test\`
It becomes `\\XXX-NAS\test\\BDMV\index.bdmv` opened by MPC-HC (note the `\\` after the "test"). 
Seem that the issue isn't present with quotes surrounding it.
![2024-02-06_01 10 25 347](https://github.com/clsid2/mpc-hc/assets/97274607/24fe2c19-f72f-47cd-bdac-058c0e067ca7)

**Comment by adipose** [comment]
This is specific to bluray folders.  I could not reproduce with DVD.  But fixed it.

https://github.com/clsid2/mpc-hc/pull/2814
