### ISSUE TITLE
DVB subtitles don't work

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2526]
Test streams: [test](http://livetv.ktv.zone/105/play.m3u8) & [test2](http://livetv.ktv.zone/107/play.m3u8)

dvb subtitles don't work. Stream goes paused state when subtitle selected. When I continue playing, subtitle does't appear.

Changing Audio track or Subtitle track makes video stop or paused state even selection of "No Subtitles".

MPC-BE handles dvb subs:
![image](https://github.com/clsid2/mpc-hc/assets/3073922/81ff6872-18a4-4800-8616-8ada6840db55)

**Comment by adipose** [comment]
Thanks, I recall seeing subs on DVB before but I'll take a look at your streams.

**Comment by adipose** [comment]
Not sure I would call this DVB exactly.  But it's not rendering any subs, that's true.

**Comment by xLn2** [comment]
Although I am not sure of the term, I have seen it named this way in 'Lav Splitter Source Pin info'.

> - Connection media type:
> 
> Subtitle: DVB Subtitles
> 
> AM_MEDIA_TYPE: 
> majortype: Unknown GUID Name {E487EB08-6B26-4BE9-9DD3-993434D313FD}
> subtype: MEDIASUBTYPE_DVB_SUBTITLES {34FFCBC3-D5B3-4171-9002-D4C60301697F}
> formattype: Unknown GUID Name {A33D2F7D-96BC-4337-B23B-A8B9FBC295E9}
> bFixedSizeSamples: 1
> bTemporalCompression: 0
> lSampleSize: 1
> cbFormat: 525
> 
> SUBTITLEINFO:
> dwOffset: 520
> IsoLang: fra
> TrackName:

**Comment by adipose** [comment]
TS files are video transport streams, which is the protocol used by DVB.  However, there is no DVB decoder involved when streaming the .ts files directly.  I'm curious if I stream this and receive it with a DVB receiver, if the subs work.

**Comment by clsid2** [comment]
`CDVBSub::ParseSample()` rejects the data.

**Comment by clsid2** [comment]
Links are dead

**Comment by adipose** [comment]
> Links are dead

https://github.com/iptv-org/iptv/issues/15859
