### ISSUE TITLE
Lost frames when bitrate jumps

### ISSUE THREAD

**Issue by radpopl** [clsid2/mpc-hc#2527]
I noticed that MPC-HC on clips with bitrate peaks tends to drop these frames.
I checked on MPC-BE - it doesn't drop frames in these places.
I use MPC-Renderer in both programs.

(Here all frames are lost at the last second of the clip.)

![image](https://github.com/clsid2/mpc-hc/assets/11005341/80131d65-88a3-4a14-84a1-49f303e7fd46)

![image](https://github.com/clsid2/mpc-hc/assets/11005341/669248cf-a58e-450e-bccf-25c726101c5a)

**Comment by clsid2** [comment]
Can't do anything without a sample file.

**Comment by radpopl** [comment]
I solved the problem - I changed the LAV decoder settings: DXVA2 from copy-back to native.

(I have Ryzen 4650G with Vega 8 1GB)
