### ISSUE TITLE
Problem remembering position for urls opened by yt-dlp originated from drag-drop

### ISSUE THREAD

**Issue by Rikk** [clsid2/mpc-hc#2528]
My tests indicate that versions up to 2.1.3.10 are ok, but version 2.1.3.32 already presents this problem.

You need the options: keep history, remember playlist and remember file position.

How to repro: play a long video that is loaded by yt-dl and stop(or pause) it at any desired time. (For example, drag and drop the url of a recorded live stream from the browser to MPCHC). Then, drag-drop the url of another video. Now, you'll notice the player will begin playing the new video in the same timestamp you stopped the first, instead of starting it from the beginning (or from a previously saved time).

Imo, this is the biggest problem it causes: it will overwrite the saved position if the url dropped was already played before.

When toggling videos using Recent Files, there is no problem.

**Comment by clsid2** [comment]
Can't reproduce.

Try clearing history.

**Comment by Rikk** [comment]
I can reproduce always, even on a clean config.
Did you **drag** a video url from the browser? It is important.

**Comment by clsid2** [comment]
Fixed
