### ISSUE TITLE
Untie OSD rendering from video frames... Would it be a possible change?

### ISSUE THREAD

**Issue by Rikk** [clsid2/mpc-hc#2529]
Currently, it seems to me that OSD text is rendered/refreshed as fast as the video frames go, ie, the higher fps the video is playing, the faster the OSD text will update on the screen. For example, when reducing the playback rate of the video, OSD text updates will be delayed accordingly.

This brings a few usability inconveniences. 1) The obvious: when reducing the playback rate, the feedback (let's say, for example, volume changes) will be lagged and unhelpful. 2) OSD updates in a higher fps video will use more processing (CPU/GPU) than in videos with lower fps, especially noticeable when playing on older systems/gpus. 3) On the edge case of a (broken?) video where the video stream is shorter than the audio stream (where the audio will keep playing after the video has already stopped), the OSD text will not update at all when only the audio is playing and the image is frozen.

I'm not sure if the 2nd case above (processing) is also affected by video resolution (or by the size of the video frame?), if OSD text is rendered as an overlay using the same resolution of the video, or whatever.

Curiously, when we open an image file and it is in "playing" state (the time is advancing), the OSD text doesn't update, but when it is in "paused" state, it updates.
Btw, why "play" an image for 10sec if there is nothing to come after it? It would make sense if we are doing a slideshow with more than one picture in the playlist, right?

\> Considering that when any video is paused the OSD text is refreshed perfectly fine, why is it tied to the video fps when playing?

If this change becomes true, I guess an OSD even for audio-only files could be thought about, perhaps?

**Comment by clsid2** [comment]
StillVideoDuration is to get slideshow behavior. May I remind you that MPC-HC is a video player not an image viewer.

I am not interested in making any OSD changes.

**Comment by Rikk** [comment]
I was pointing some reasons why OSD behavior can be improved. Imo, these things are pretty annoying.

> I am not interested in making any OSD changes.

Perhaps another dev might want to take a look at some time? You don't need to do it all by yourself.

>StillVideoDuration is to get slideshow behavior.

When there is only one file (a picture) in the playlist, why not open it in Paused state?
Really, this question about image is out-of-topic, as I'd like to talk about OSD here.
