### ISSUE TITLE
LAV Audio Decoder stopped working

### ISSUE THREAD

**Issue by Snipe3000** [clsid2/mpc-hc#253]
Did LAV Audio Decoder stop working for anyone else after the latest update?

**Comment by Snipe3000** [comment]
This might be a false alarm. It appears to be a specific movie, in which mpc-hc wont use the LAV audio decoder for. I'm trying to dig in and figure out what makes this file different than the others.

**Comment by clsid2** [comment]
Menu > File > Properties > MediaInfo
