### ISSUE TITLE
FEATURE REQUEST - Restart or Continue the Playback Where Left Off

### ISSUE THREAD

**Issue by dilushanka** [clsid2/mpc-hc#2530]
One of the practical features of VLC Media Player is the ability to continue the playback from where we left off. Imagine that a 2-hour-long documentary is playing in the application. You hit stop by accident. We would have to use the time toolbar and click on it several times to continue from the same part. It won’t be an easy task to get to the exact spot where you left off.

**Comment by clsid2** [comment]
This ability already exists for long time.

Options > Player > Remember file position

Do not press STOP. That resets file position. Simply close player or pause.

**Comment by dilushanka** [comment]
no. Sometimes I watch movies. Then when you don't watch it continuously, it will ask you to resume as a popup when you watch it, just like in VLC. Because songs are played from the previous stop. This is troubling. So ask as a popup whether to resume

**Comment by clsid2** [comment]
NO!

Options > Advanced > RemeberPosForAudioFiles
Options > Advanced > RemeberPosForLongerThan
