### ISSUE TITLE
Save subtitle dialogbox's some items don't fit theme

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2531]
Save subtitle dialogbox Windows dark & mpc dark theme, file type .srt selected:
![mpc-hc64_eIq1rJ1V1i](https://github.com/clsid2/mpc-hc/assets/3073922/59c93afb-e2b8-4845-b707-a9b09d656d09)

Save subtitle dialogbox Windows dark & mpc dark theme, file type .ass selected:
![mpc-hc64_1XWr0NJOfm](https://github.com/clsid2/mpc-hc/assets/3073922/473ca53a-5512-45cb-9c07-9b57bc1b137e)

Save Image dialogbox Windows dark & mpc dark theme
![mpc-hc64_vAdIyPbGr1](https://github.com/clsid2/mpc-hc/assets/3073922/a42c9586-3e80-4600-9807-4677d0e9966c)

**Dark theme Findings/suggestions:**

- `Delay (ms):` text color should be like `Quality (%):`
- Editbox frame/hover/text color should be same as on Save Image dialogbox
- `Save custom style` should follow same style with `Include subtitles`, text color shouldn't be blue.
- `Save custom style` checkbox should follow `Include subtitles` checkbox style

Save subtitle dialogbox Windows light & mpc light theme, file type .srt selected
![image](https://github.com/clsid2/mpc-hc/assets/3073922/e2329271-25aa-4754-af9f-78b122207827)

Save subtitle dialogbox Windows light & mpc light theme, file type .ass selected
![image](https://github.com/clsid2/mpc-hc/assets/3073922/b5c4f9ca-98b5-46a8-9839-a74c8debf1cd)

Save Image dialogbox Windows light & mpc light theme
![image](https://github.com/clsid2/mpc-hc/assets/3073922/240e1c22-0bff-4d3b-89a1-ec6c52889477)

**Light theme Findings/suggestions:**

- active `Control texts` (Save custom style & Include subtitles) should be same color with `Quality (%):`

**Behavioral suggestions:**

- Default subtitle save type should follow current subtitle format. If I have '.ass' subtitle I suppose default save method also should select it automaticaly.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2538

I suggest we close this issue and you can post your other issues separately.

The save dialogs are actually themed by Windows and not MPC-HC.  It requires some complex hooks to update the theming on the custom added fields that Windows allows (which Windows does not bother having match the current Windows theme).

If the _Windows_ theme is "light" then I believe it is not updating anything at the moment.  The assumption is that custom added fields will by default fit the default Windows light theme.  But I'm not averse to improving it if it's particularly mismatched.
