### ISSUE TITLE
Menu glitch when file is opening

### ISSUE THREAD

**Issue by Rikk** [clsid2/mpc-hc#2534]
When a file/url is in "Opening" or "Calling youtube-dl" state and you ~open a menu, submenus are~ open File menu, Recent Files submenu is not properly refreshed and severe visual artifacts happen. Video state in status bar isn't updated as well (timestamps are updated, however). Demo:

https://github.com/clsid2/mpc-hc/assets/2916485/d26f2c6c-117b-4963-b0e9-b7bb6a10204f

When changing from one menu to other or when reopening it, it refreshes.

_Edit: it seems other submenus doesn't glitch._

**Comment by adipose** [comment]
It's because it's changing contents while you already have the menu open.

**Comment by Rikk** [comment]
@adipose
So, nothing can be made to improve it?

Imo, two possible things could be done: 1. Change so it refreshes while menu is open (it seems that when the menu is open, it blocks refreshes of status bar and menus themselves), 2. The easy solution: disable Recent Files submenu while video is opening (I think this is what MPCBE does).
