### ISSUE TITLE
Subtitle saving default file extension should follow current sub extension

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2539]
Currently subtitle saving file extension defaultly choose subrip (srt) file extension.

My suggestion is:
If loaded subtitle has available saving extension (ass, ssa, srt, etc) for mpchc, choose it by default, and
If loaded subtitle isn't available for mpchc saving extension options but has custom styles, choose (recommended) style supported extension (like .ass/.ssa) by default, and
If none fit choose .srt by default

I tried to explain it simply, I hope it's not misunderstood or rude. Best regards.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2541
