### ISSUE TITLE
Add Windows 8/10 Media Control Support

### ISSUE THREAD

**Issue by ibnu-ja** [clsid2/mpc-hc#254]
Here's how it looks
Lockscreen:
![Lockscreen](https://user-images.githubusercontent.com/10094582/73512658-0103fb80-441d-11ea-8597-6a984da84e46.png)
Desktop:
![Desktop](https://user-images.githubusercontent.com/10094582/73512659-019c9200-441d-11ea-9fa1-7277114c777f.png)

**Comment by clsid2** [comment]
Options > player > keys > global media keys

**Comment by ibnu-ja** [comment]
No not the shortcut, but desktop track information. Even chrome have one.

Sorry but did you even look at the pictures?

**Comment by clsid2** [comment]
I am not interested in adding such functionality.
