### ISSUE TITLE
srt Subtitle with .style file does not apply custom default style

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2540]
I don't expect some fancy styles on subrip files. But I expected single custom style "Default" from .style file can be used. Mpc-hc successfully parse custom style but doesn't apply any subtitle line but instead of create Default 2 (Mpc-hc default) style and apply it to all lines. 

![image](https://github.com/clsid2/mpc-hc/assets/3073922/f169e4a8-086a-460b-8fb5-74532224eb3f)

[sub and style files.zip](https://github.com/clsid2/mpc-hc/files/14201753/sub.and.style.files.zip)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2839
