### ISSUE TITLE
Subtitles do not appear in full screen mode

### ISSUE THREAD

**Issue by KogucikPL** [clsid2/mpc-hc#2543]
While fansubbing, I came across an interesting case. I don't know if it's a direct fault of MPC or not, but VLC doesn't have the slightest problem with it, so I guess it is.

Namely, a certain line in the .ass script does not display in full screen mode. When the size of a given line of text exceeds 250 points, it simply disappears:
https://www.youtube.com/watch?v=QtYxe2f9HV4

The latest version of MPC
I didn't change any video or subtitle settings

.ass scripts:
Working: `{\fscx120\fscy120\t(\fscx110,\fscy110)\fnKozuka Gothic Pro H PL\fs200\c&H000000&\an5}\fscx120\fscy120\N\t(\fscx110,\fscy110)\fs200`
Not working: `{\fscx100\fscy100\t(\fscx90,\fscy90)\fnKozuka Gothic Pro H PL\fs250\c&H000000&\an5}\fscx110\fscy110\N\t(\fscx90,\fscy90)\fs250`

**Comment by clsid2** [comment]
That can happen if GDI fails to render the font at large point size.
Point size is scaled based on output resolution. So I would advice to test fansubs at 4k output.

You can solve it by using libass.
Options > Subtitles > Default Style > Use libass

But better is to keep compatibility with Windows GDI in mind, as that is used by default by many subtitle renderers. Use lower point size, and compensate it with font scaling.

**Comment by KogucikPL** [comment]
Oh, it works perfectly, thank you <3
(by the way, the lag problem with heavily animated subtitles has been fixed)
