### ISSUE TITLE
Separate mouse options page

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2544]
@adipose
Would you be interested in implementing something like this in future?

Screenshot from MPC-BE:
![mpcbe_mouse](https://github.com/clsid2/mpc-hc/assets/4704996/0e46acb5-4ef0-4d80-a1a7-3241de0251b4)

Then mouse columns on Keys page can be removed.

I do think this can be improved further by having just two columns, one for mousebutton+modifiers, and one for the action. I think initially just plain button and button+ctrl would be sufficient to have plenty of different actions.

Example:
mousewheel = volume
mousewheel + Ctrl = jump (large)

**Comment by KogucikPL** [comment]
If my opinion counts, all I can say is that the more customization options, the better.

**Comment by clsid2** [comment]
This doesn't add more options. It just moves them to a separate page to make it easier to configure.

**Comment by bibsp** [comment]
> Then mouse columns on Keys page can be removed.

Nice. Additionally move mouse left up delay setting from advanced page to this page.

**Comment by clsid2** [comment]
Yes, I was thinking:
`Left click` = empty | play/pause | play/pause (with delay)

Left/right/double-click should all go into the table with the rest.

`Move window by video area` is unneeded imo. We already have a threshold to prevent accidental movement.

`Right-click + Ctrl` could maybe be `Boss key` by default. With alternative choice `Exit Player`.

**Comment by adipose** [comment]
Shouldn't be too hard.

Main advantage is the limited mouse options means the list is only that long vs several columns on the whole keys page.

**Comment by clsid2** [comment]
Currently Keys also has separate columns/options for windowed and fullscreen, which is imo unnecessary.

**Comment by JamieRCHI** [comment]
> Currently Keys also has separate columns/options for windowed and fullscreen, which is imo unnecessary.

Yes. This is a 'feature' I don't like with VLC. Never understood why options should be different between 'windowed' and 'fullscreen'.

**Comment by adipose** [comment]
> > Currently Keys also has separate columns/options for windowed and fullscreen, which is imo unnecessary.
> 
> 
> 
> Yes. This is a 'feature' I don't like with VLC. Never understood why options should be different between 'windowed' and 'fullscreen'.

I believe the non-fullscreen shortcuts work by default in fullscreen.

But I have no use for them either.

**Comment by MoizSk** [comment]
hi, separate columns/options for windowed and fullscreen is disappeared not showing in shortcut keys. How to get back Mouse FS Mode in keys.

**Comment by clsid2** [comment]
That has been removed intentionally and will not return.

**Comment by xLn2** [comment]
#2800
