### ISSUE TITLE
unwanted character rendering of subtitles with incorrectly defined character set

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2548]
Some of old .ass subtitles' character sets are wrongly determined (ancient subs 13 years before) and mpc probably ignored this behavior 13 years ago, so no one even notice there was an issue about that. Since years passed and probably mpc behavior changed so people got used to this broken visual character rendering or watched hardcoded episodes.

Mentioned issues about Turkish language (8-bit character set is162). In our subtitle community, subtitles are mostly encoded as ANSI, but usually correct Turkish letters. This issue probably effected by other languages but I don't have samples, if you had please share these.

The mentioned .ass subtitles display ANSI-encoded when opened with notepad and characters are correct based on the language.

mpv .net automaticaly handles encoding detection
![mpvnet_leassQ81Pl](https://github.com/clsid2/mpc-hc/assets/3073922/cb127d26-13bb-4a0e-96fd-d6b2e1c2a3cc)

mpc-hc render text as character set defined "ğ" became russian letter "р"
![mpc-hc64_lM7UN8u5JD](https://github.com/clsid2/mpc-hc/assets/3073922/2f9d0e46-134e-4d78-b311-1ea0f6c1557b)

```
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Gintoki,Georgia,30,&H00ED0637,&H00FFFFFF,&H00FFFFFF,&H00222222,0,0,0,0,100,100,0,0,1,3,3,2,10,10,10,204
Style: Shinpachi,Georgia,30,&H002BF603,&H00FFFFFF,&H00FFFFFF,&H00181818,0,0,0,0,100,100,0,0,1,3,3,2,10,10,10,0
Style: Kagura,Georgia,30,&H000000FF,&H00FFFFFF,&H00FFFFFF,&H001A1A1A,0,0,0,0,100,100,0,0,1,3,3,2,10,10,10,0
Style: ???????,Arial,20,&H0003FA03,&H000000FF,&H00000900,&H00000000,0,0,0,0,100,100,0,0,1,1,1,2,10,10,10,204
Style: ??????????,Georgia,30,&H00FFFFFF,&H00FFFFFF,&H009805EC,&H00000000,0,0,0,0,100,100,0,0,1,3,3,2,10,10,10,204
Style: ????????,Kozuka Mincho Pro R,30,&H00BB08EF,&H000000FF,&H28E0F401,&H00F0034C,0,0,0,0,100,100,0,0,1,5,3,2,10,10,10,0
Style: ?????????,Georgia,30,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,3,2,2,10,10,10,204
Style: ???,Arial Black,50,&H00E79033,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,2,5,10,10,10,0
Style: ????,Monotype Corsiva,20,&H0096DEEC,&H000000FF,&H00000000,&H00000000,0,-1,0,0,100,100,0,0,1,2,2,2,10,10,10,0
Style: ???,Monotype Corsiva,20,&H00D8BC88,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,0
Style: ????,Century Gothic,20,&H0042543F,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,0
Style: ????????,Century Gothic,25,&H00030402,&H000000FF,&H00FFFFFF,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,0
Style: ?????,Century Gothic,20,&H0027221C,&H00000000,&H00585858,&H00000000,-1,0,0,0,100,100,0,0,1,1,0,2,10,10,10,0
Style: ???,Monotype Corsiva,20,&H007F368D,&H000000FF,&H00E3CDD8,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,0
Style: ????,Monotype Corsiva,20,&H005771D4,&H000000FF,&H000A1124,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,0
Style: ??????,Bookman Old Style,25,&H00938983,&H000000FF,&H00371F0F,&H00000000,0,0,0,0,100,100,0,0,1,3,3,2,10,10,10,0
Style: ???????,Arial Black,30,&H00FFFFFF,&H000000FF,&H000000FF,&H00000000,-1,0,0,0,100,100,0,0,1,1,3,2,10,10,10,0
Style: Default,Comic Sans MS,31,&H00FFFFFF,&H000000FF,&H00AB240B,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: Kırmızılar,Comic Sans MS,29,&H00FFFFFF,&H000000FF,&H002F0CE1,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: not,Comic Sans MS,24,&H00FFFFFF,&H000000FF,&H000000FF,&H00000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1
Style: bölüm ismi,Seven Monkey Fury BB,30,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: ön gösterim,Comic Sans MS,30,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1,2,2,10,10,10,1
Style: rtea,Arial Black,45,&H00CF992B,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,0,0,2,10,10,10,1
Style: new,Comic Sans MS,30,&H005BEDE5,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
Style: kokteyl,Arial,20,&H00000000,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,0,0,2,10,10,10,1
Style: çiöe,Comic Sans MS,40,&H00000000,&H000000FF,&H00FFFFFF,&H00000000,-1,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
Style: sav,Seven Monkey Fury BB,30,&H001112C5,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,0,0,2,10,10,10,1
Style: Op,Comic Sans MS,30,&H0003377C,&H0000FFFF,&H32BBE1F9,&H00604022,-1,0,0,0,100,100,0,0,1,5,0,2,10,10,17,204
Style: End2,Monotype Corsiva,33,&H00683602,&H0000FFFF,&H46F1CFB0,&H00604022,-1,-1,0,0,100,100,0,0,1,5,0,2,10,10,10,204
Style: ED,Comic Sans MS,35,&H00FFFFFF,&H0000FFFF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,5,0,3,10,10,7,204
```
also mpchc can't handle "Kırmızılar" style and "ı" became ANSI "ý" so style name became "Kýrýmýzýlar"
![image](https://github.com/clsid2/mpc-hc/assets/3073922/d12ff91c-ee7d-4900-9c5b-6c24c083767e)

You may think these are broken file or something but I think there are so much subtitles are suffering this behavior (maybe all ones before UTF-8). Since I can not manually edit 30 styles character encoding just for 1 episode and there are 300 more there should be a solution. When I searched this issue I found that mpv solved it by [handling encoding detection](https://github.com/mpv-player/mpv/pull/2193) and uses `uchardet` and `ENCA`. 

[ass subtitle examples.zip](https://github.com/clsid2/mpc-hc/files/14216134/ass.subtitle.examples.zip)

**Comment by adipose** [comment]
https://github.com/mpv-player/mpv/issues/908

I will take a look at some point.

**Comment by adipose** [comment]
chardetect results:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/ca6983e0-8388-4f57-9678-a384667065e6)

**Comment by adipose** [comment]
Notepad: 
![image](https://github.com/clsid2/mpc-hc/assets/3324395/65b89869-fe05-4582-992e-28eb8f9eebae)

Editplus:
![image](https://github.com/clsid2/mpc-hc/assets/3324395/5270d6ab-f22f-41ae-8a66-cab035eae111)

**Comment by adipose** [comment]
Editplus after choosing:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/120e28bf-7d29-42f8-b4b3-074b2daff5da)

![image](https://github.com/clsid2/mpc-hc/assets/3324395/6830e7d8-1fde-45b9-a684-93f6f9c5b39d)

**Comment by adipose** [comment]
uchardet test:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/149301ce-9aca-429e-a52f-3a99c900f2b7)

**Comment by clsid2** [comment]
There is an character set encoding setting in subtitle options.

**Comment by xLn2** [comment]
Character set options help if there is no custom styles or there is style's character set defined as Default(1). Otherwise characters are forced to determined charset responding. Also if custom style charset set ANSI(0) it leads bad characters.

Example letters: `ÂâĞğÜüŞşİiÖöÇçIıîÎ`
ANSI(0): `ÂâÐðÜüÞþÝiÖöÇçIýîÎ`
RUSSIAN(204): `ВвРрЬьЮюЭiЦцЗзIэоО`

Dialogue: 0,0:03:24.24,0:03:30.70,Op,,0000,0000,0000,,{\b1\c&H0000A8&\3c&H46D5FF&}Çok ama çok uzun zamandan beri
Dialogue: 0,0:03:31.29,0:03:36.04,Op,,0000,0000,0000,,{\b1\c&H0000A8&\3c&H46D5FF&}güvendiğim şey arkandı.
Dialogue: 0,0:03:37.54,0:03:42.42,Op,,0000,0000,0000,,{\b1\c&H0000A8&\3c&H46D5FF&}Geldiğim yer,
Dialogue: 0,0:03:43.80,0:03:48.89,Op,,0000,0000,0000,,{\b1\c&H0000A8&\3c&H46D5FF&}Bence orası emanet alınmış bir yerdi.

notepad++ and ms notepad show same
![image](https://github.com/clsid2/mpc-hc/assets/3073922/f6a36e41-6cfb-490f-9389-1ba37939078f)
![image](https://github.com/clsid2/mpc-hc/assets/3073922/10398fbc-ebec-4d82-91d7-588db2a2e67a)

![image](https://github.com/clsid2/mpc-hc/assets/3073922/88bf058e-adc6-49d2-bc5f-3701aeee6239)


and sometimes subtitle character encoding is set as `2` or `random number` which is unfamiliar even for mpchc.

**Comment by clsid2** [comment]
Do you have any sample files where it is set to an invalid charset value?

**Comment by xLn2** [comment]
Charset is defined as 4, seems it doesn't cause any  unwanted character encoding behavior. Other samples are attached to first post (undermost).

![image](https://github.com/clsid2/mpc-hc/assets/3073922/2a11206c-0631-4f3b-a931-dabac75de772)

[aaatama - 027 [DVDRip 704x528 x264 AAC].zip](https://github.com/clsid2/mpc-hc/files/14222773/aaatama.-.027.DVDRip.704x528.x264.AAC.zip)

**Comment by clsid2** [comment]
The styles in your first post define charset 204 for some styles. That is Russian. If that is wrong, then file is simply BROKEN.

**Comment by adipose** [comment]
> The styles in your first post define charset 204 for some styles. That is Russian. If that is wrong, then file is simply BROKEN.

Yeah they are definitely broken.  Issue is some old tool must have guessed wrongly at the encoding.

Uchardet seems useful.  But I don't think it should override encoding when it's specified. Maybe advanced option and maybe option to force default charset on any ANSI.

**Comment by xLn2** [comment]
Overriding charsets of all styles and force Default(1) charset `[or user charset setting in default style]` is doable? There is an option in subtitle menu "Default style" and it probably just forces font. Maybe addition to "Default style" setting there is "Default character set" could be added as submenu under "Force" to better understanding.

![image](https://github.com/clsid2/mpc-hc/assets/3073922/1698cab4-fb9b-4a45-9281-cbcf55108c19) 

```
Enable
Force  > Default Character Set
         Default Style{or Font}
```

**Comment by clsid2** [comment]
ANSI(0) in ASS/SSA is already being changed to DEFAULT(1) because majority of files only use value 0.

If a style has an explicit encoding value that is wrong, then you should just fix those files. Re-save them as UTF-8 as well.

Player should not correct what is broken, as that does not prevent people from creating broken stuff.

**Comment by adipose** [comment]
Are these embedded subs or separate files btw?

**Comment by xLn2** [comment]
@adipose These subtitles are seperate files.

**Comment by adipose** [comment]
I think I understand the problem.  The .ass files are actually setting the codepage to 1 = DEFAULT_CHARSET.  In theory this should have worked fine on a system running CP 28599 / ISO-8859-9.  But only the system codepage will be able to override this behavior.

@xLn2, what is your windows codepage set to?

`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage\ACP`

**Comment by xLn2** [comment]
> ANSI(0) in ASS/SSA is already being changed to DEFAULT(1) because majority of files only use value 0.

Sorry if I misunderstand, styles with ANSI(0) charset still looks as fallback characters of ANSI on mpchc
![image](https://github.com/clsid2/mpc-hc/assets/3073922/e607202e-7898-4807-abf2-cc11d1aea781)


Windows codepage ACP is 1254.
![image](https://github.com/clsid2/mpc-hc/assets/3073922/5ab796b9-af8f-4f3c-bd93-71c14955455f)

**Comment by clsid2** [comment]
Convert to UTF-8 to fix the files.

**Comment by adipose** [comment]
Here's some research.  Changing the windows ANSI codepage to 28599 (ISO-8859-9) has the following impacts on your test files:

1. Notepad / Editplus correctly render the turkish ANSI files, which have a codepage of 1 = DEFAULT_CODEPAGE
2. MPC-HC correctly renders the text using both MPC-HC ISR and libass.

![image](https://github.com/clsid2/mpc-hc/assets/3324395/2e2615d7-fbec-4359-b1ca-75f4609b025e)

However, I do not recommend changing the ACP in Windows.  Certain applications do not like it, though in your case it may be worth trying it.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2554

This may be a partial solution.

**Comment by xLn2** [comment]
As far as I understand, Encoding 1 uses the windows code page, so if people are using different windows language installations like English, Russian etc., they will most likely encounter the character corresponding to the OS code page. Maybe that's why people have come up with the conclusion that the language in which the subtitle is encoded and the system code page of the people who using it might be incompatible.

As Adipose pointed out, the mis-specified character sets may have been caused by the use of certain tools.
As we move closer to the present day, it seems that subtitles are better structured and published in a universal format. Of course, old things stay the same.
