### ISSUE TITLE
MPC Video Renderer GPU Decode?

### ISSUE THREAD

**Issue by RobuGH** [clsid2/mpc-hc#2549]
How do I enable the GPU to render video playback with MPC Video Renderer? It only uses the CPU which is pegged at 100% when playing 4K video. MadVR correctly uses the GPU such that even 4K 60FPS HDR plays smoothly. I've looked in both MPC-HC and MPC Video Renderer settings and I can't find any option to enable GPU rendering.

**Comment by bibsp** [comment]
LAV Decoder by default uses DXVA2 Native. Change it to D3D11.
Or you can keep it unchanged. And change MPC-VR settings. Uncheck use D3D11.

Recent changes in MPC-VR don't allow to use HW acceleration if you use DXVA2 in LAV and D3D11 in MPC-VR. You have to change any one of those.

**Comment by Aleksoid1978** [comment]
But in MPC-BE the decoder can automatically select D3D11/DXVA2 :)

**Comment by RobuGH** [comment]
@bibsp This doesn't work. If I disable D3D11 I get GPU decoding but no HDR. If I disable DXVA2 I get HDR but no GPU decoding. I don't get both. However, in MPC-BE I get both GPU decoding and HDR with the default settings. There seems to a problem with MPC-HC.

**Comment by bibsp** [comment]
> If I disable DXVA2 I get HDR but no GPU decoding.

Don't disable. If you disable, it will use software decoding. Just change the setting to D3D11 in LAV.
Then in MPC-VR's settings reset everything. It should work.

**Comment by clsid2** [comment]
You need to use D3D11 in both.

Or use the MPC Video Renderer build that is located on the MPC-HC download page, that one supports DXVA2 decoder with D3D11 rendering.

But if nobody follows instructions...

**Comment by RobuGH** [comment]
@bibsp OK got it. I misunderstood what you meant by "LAV Decoder" and where to change that setting. Works now. Thanks.

**Comment by RobuGH** [comment]
@clsid2 Yeah, I was already using that one though.
