### ISSUE TITLE
Once in a few days, sound suddenly gets lost and becomes silent while it is playing

### ISSUE THREAD

**Issue by CanadaBeaver** [clsid2/mpc-hc#2550]
Once in a few days, sound suddenly gets lost and becomes silent while it is still playing. Closing the program and restarting it has no use, unless restarting my computer. I recently updated to the following version:

Build information:
    Version:            2.1.4 (c82061aef)
    Compiler:           MSVC v19.29.30152
    Build date:         Jan 15 2024

I have been using MPC-HC for over 10 years. I upgraded twice for your latest two versions. Before upgrading, it had never had any problem.

**Comment by clsid2** [comment]
If restarting the computer helps, then it is probably one of Windows services related to sound that has crashed.

https://support.microsoft.com/en-us/windows/fix-sound-or-audio-problems-in-windows-73025246-b61c-40fb-671a-2535c7cd56c8#ID0EDBD=Windows_11
See solution 9. But check others as well.

**Comment by CanadaBeaver** [comment]
Thank you for your prompt response. I just followed the steps from
Microsoft at the weblink you provided. Let us see in the next few days if
the issue will not arise again.

Thank you again.
