### ISSUE TITLE
ToDo: Read Media History less often

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2551]
Currently it gets read on every file load and File menu access through `CMainFrame::SetupRecentFilesSubMenu()`.

Add a value to MediaHistory key that contains timestamp of last entry _creation_ (not minor updates to it such as position etc). This can then be used to determine if the list should be updated or not.

It should only update if another instance has been writing to history. So check it before adding a new entry.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2564

Fairly simple but maybe could use review.
