### ISSUE TITLE
Chapters in different languages

### ISSUE THREAD

**Issue by aleixJ** [clsid2/mpc-hc#2552]
Is there any way to change the language of the chapters depending on the language?
I have tried modifying the language of the application, the audio track and the subtitle track and in all cases the **first option** is always shown (in this case English).
It works better than the VLC media player, as it only concatenates the different options.
I'm testing it with .mkv

![image](https://github.com/clsid2/mpc-hc/assets/103207971/3e2fcd71-8857-4ce4-9b8b-a48fc9ee9c9c)

**Comment by clsid2** [comment]
No.
