### ISSUE TITLE
Forcing the Default Style ignores the undefined positioning of subtitles and causes subtitles to render according to the window

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2555]
Forcing the default style ignores the undefined positioning of subtitles and causes subtitles to render according to the window.

_libass enabled for ass/ssa_
Edited on 13.06.2024 // ANSI encoded subs don't work for with libass (yet) and fallback to ISR. 

**Steps:**

- ass subtitle loaded
- [Undefined] Position subtitles relative to the video frame
- Right click > Subtitle track > Default Style

![mpc-hc64_SNb437jTwm](https://github.com/clsid2/mpc-hc/assets/3073922/5fedabfd-ae29-45c0-8f2f-ea8b912a073c)

**to see expected result** 
- ass subtitle loaded
- [Enabled] Position subtitles relative to the video frame
- Right click > Subtitle track > Default Style

![mpc-hc64_8Er7S3Hkzs](https://github.com/clsid2/mpc-hc/assets/3073922/172ae1a4-4e92-4d24-886b-683abb6fa77b)

Before Default style
![mpc-hc64_J0HDpnYp72](https://github.com/clsid2/mpc-hc/assets/3073922/16a4fa2c-dd82-46e4-bb82-291558dcc0f0)

**Comment by adipose** [comment]
Can you still reproduce this?  I made a fix, but then I realized, it didn't actually change the behavior.

I cannot get it to render to the window when applying default style and relativeto is undefined.

**Comment by adipose** [comment]
If so, please upload your video. Maybe to do with some other defaults.

**Comment by xLn2** [comment]
> Can you still reproduce this? I made a fix, but then I realized, it didn't actually change the behavior.

4:3 Video + Ass subtitle produced for 4:3 , (or same resolution video and ass sub) is fine to reproduce it. Probably others also but I test it with these. 
Disable limit window proportions and enlarge width of window to see problem. Subs are rendering according to window, also try resize window to see how behaving.

![mpc-hc64_mj25zVHSvI](https://github.com/clsid2/mpc-hc/assets/3073922/a1360b88-7e60-43a8-bc5f-01305728bb5b)

**Comment by adipose** [comment]
I tried all my samples and none worked.  Do you have a 4:3 one?

**Comment by xLn2** [comment]
I can send subs here, for videos I have to send e-mail if you don't find video.
PlayResX: 640
PlayResY: 480
[ass subtitle examples.zip](https://github.com/user-attachments/files/15811774/ass.subtitle.examples.zip)

**Comment by adipose** [comment]
It seems the problem is that libass fails to load this file.

**Comment by adipose** [comment]
I can reproduce it now.  The problem is with internal subtitle renderer.  It falls back to that because your file is ANSI 1254 and libass requires UTF8.

Edit: in mpc-hc it uses UTF8.  It can support ANSI.

**Comment by adipose** [comment]
https://mega.nz/file/8VYj3bwT#rDHsjP2GREYTrZzE6P5noDSYexZ-AX3imEH0BhlKoSM

Can you test and confirm this is working?

**Comment by xLn2** [comment]
Both ISR and libass rendering looks fine.
