### ISSUE TITLE
When the relative positioning of subtitles is disabled, enabling it or making it undefined requires a restart to see the changes but the opposite is applied instantly

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2556]
When the relative positioning of subtitles is disabled, enabling it or making it undefined requires a restart to see the changes. But the opposite is applied instantly.

**Steps:**

[Disabled] `Position subtitles relative to the video frame`
ass subtitle loaded

![mpc-hc64_cAYhiv6MNn](https://github.com/clsid2/mpc-hc/assets/3073922/93bbe7d9-cacf-4dae-b3df-8964444c7e8f)

Enabling or making Undefined `Position subtitles relative to the video frame` does not effect until restart of player.

**Comment by adipose** [comment]
I cannot reproduce this on the latest.  Can you please test the test build I sent in the other one.  If you can reproduce, please indicate how.

For example, using Default style settings vs. editing the currently active style.

It worked ok for me in both libass and ISR.

**Comment by xLn2** [comment]
It is fixed, thanks.
