### ISSUE TITLE
2.1.4.29 Nightly: Subresync inner body visual glitch

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2557]
Both modern themes and classical themes are affected by this issue.

Subresync inner body inherits last mpchc cursor style and holds it.

![mpc-hc64_zqKAv6LZSx](https://github.com/clsid2/mpc-hc/assets/3073922/2357b4f5-b2f4-4697-91c1-b2b53baf23b6)

I also observed problems with the horizontal bar while resizing, do I need to open a separate issue?

**Comment by adipose** [comment]
I don't know quite what you mean, but I did find what I think was a bug. 

https://github.com/clsid2/mpc-hc/pull/2559

This was defaulted wrong which sounds like it could cause your issue.  However, I cannot identify exactly what is wrong in your screenshot.  Is it supposed to be a cursor other than arrow?

**Comment by adipose** [comment]
> I also observed problems with the horizontal bar while resizing, do I need to open a separate issue?

Yes.  I did fix some scrollbar issues already with resized windows.  Not sure if there were more.

**Comment by xLn2** [comment]
By 'inner body' I mean the area inside after the part attached to the head (Times, Preview, Text etc.). Screenshoots are gif extension and animated if you can't view it I can change it to video. I think cursors only should shows indicated jobs like if expanding column there is bow cursor, resizing window there is two-headed arrow or editing text there is nailed "I" cursor. Version 2.1.4 is works as expected. Gifs are below.

2.1.4
![mpc-hc64_RiIJDawA0R](https://github.com/clsid2/mpc-hc/assets/3073922/d4d6248a-b5e6-4314-be88-275febbca39a)


2.1.4.29 Nightly - Sometimes don't reproducible.(edit text cursor still happens even these time)
![mpc-hc64_5grioUZdlc](https://github.com/clsid2/mpc-hc/assets/3073922/21d0eba9-f6e2-425a-9dce-e848f132424e)

**Comment by xLn2** [comment]
Mpc-hc 2.1.4.45
Problem is gone. Can it be considered a bug if the cursor that appears when editing the line also seems in another region in the same way?

![image](https://github.com/clsid2/mpc-hc/assets/3073922/c07f4166-7787-4a03-bfc6-604721a476ad)

**Comment by adipose** [comment]
Do you mean the hover that's outside the edit?

**Comment by xLn2** [comment]
Yes.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2572

For some reason this issue didn't affect the fullscreen listctrl, but this seems to have fixed it.
