### ISSUE TITLE
Subtitles Not Displaying

### ISSUE THREAD

**Issue by Mind777** [clsid2/mpc-hc#2558]
Having a problem displaying subtitles for foreign language series.

Example,

S1+S2 have SubRip/SRT = displays correctly
S3 has HDMV/PGS = not displayed

Tested with MPC-BE and all subtitles are displayed.

Never had this issue before until latest release.

Is this a bug you are aware of?

**Comment by clsid2** [comment]
Nobody has reported such problems. It is working fine for me.

You need to give download link for one of those files.

Options > Miscellaneous > Reset

**Comment by Mind777** [comment]
Can you please try this file - https://mega.nz/file/8yVD2TCC#drsAxsAO2lO_NZ6PAM_MQvkIvOby9gUt1zgiyEN-giU

**Comment by clsid2** [comment]
File is too large. I am not installing MEGA software crap.

Verify that correct track is selected:
Menu > Play > Subtitle track

**Comment by Mind777** [comment]
Oh, didn't realize it would ask you to install something. Sorry about that. 

Let me find an alternate file host and i will post link.

Subtitle track is selected (there is only 1) and it works with mpc-be, so that's not the issue.

**Comment by clsid2** [comment]
You can split it into smaller pieces with MkvToolNix.

Options > Subtitles > Maximum texture resolution
Maybe that setting helps.

**Comment by Mind777** [comment]
i spilt the file as you suggested. Hope this file host is ok?

https://ufile.io/uffmd1pu

**Comment by clsid2** [comment]
English subs working fine here.

Subs may not show directly after seeking. That is fault of the file and you can fix it by remuxing it. That adds info that splitter needs to find that data.

**Comment by Mind777** [comment]
ok, thanks a lot for checking.

Are you using with madvr or other renderer? And also 32bit or 64bit player?

**Comment by clsid2** [comment]
I am using MPC Video Renderer. Works fine with madvr as well.

madvr options > processing > zoom control > uncheck "move subtitles"
That can sometimes cause trouble.

**Comment by Mind777** [comment]
As it was working on your end i just uninstalled and reinstalled MPC-HC. 

Works now, I can see the subtitles!

Not sure what was wrong before, but either way the reinstall fixed the issue.

Thanks again for your help :)

**Comment by adipose** [comment]
> File is too large. I am not installing MEGA software crap.

I was able to dl it via Chrome, but it made we wait 6 hours to get the second half :-/.

**Comment by Mind777** [comment]
> > File is too large. I am not installing MEGA software crap.
> 
> I was able to dl it via Chrome, but it made we wait 6 hours to get the second half :-/.

I provided another link and reduced file size, maybe you didn't see that message?

But yeah, sucks that you have to download software just to download a file. First time i used Mega, so i didn't know.

The other file host seemed ok though.

**Comment by adipose** [comment]
> I provided another link and reduced file size, maybe you didn't see that message?

Sure, I saw it, but I already left Chrome open overnight to get the mkv.  No worries just commenting on how to deal with MEGA.
