### ISSUE TITLE
2.1.4.29 Nightly: Scrollbar rendering issue due to resizing in modern dark theme

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2560]
Classic theme and modern light theme have no issue

https://github.com/clsid2/mpc-hc/assets/3073922/5d6db6a5-f754-419c-a622-db7cdff95f7a

Modern dark theme

https://github.com/clsid2/mpc-hc/assets/3073922/b1d4c7f5-1ff6-49a8-91c2-79d4a2099378

Playlist vertical scrollbar also effected. I can open a separate 'issue' if needed as I don't know if the origin of the problem is the same or not.

https://github.com/clsid2/mpc-hc/assets/3073922/dbbed539-b396-4f76-a5f2-334825c6b0c2

The scrollbar issue behaves similar to version 2.1.4. I just noticed that the problem of the graphic getting stuck when Subresync panel and window is resized to minimum size behaves the same way.
At Nighty version seems to have fixed the issue with remnant content. It was looked like this.
![image](https://github.com/clsid2/mpc-hc/assets/3073922/f7404f7b-8a81-426e-8af4-3b5868c10360)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2562

I think this should mostly fix it...lots of weird cases here.

**Comment by xLn2** [comment]
Mpc-hc 2.1.4.45 Nightly
The only thing that might be related to the scrollbar seems to be the residue in the header.
![mpc-hc64_4hHBxurvst](https://github.com/clsid2/mpc-hc/assets/3073922/35fff369-ab63-4aee-8fa2-4ec9541ae49c)

Probably not related to this, but there is a small thing with the rendering of the gray line next to the scrollbar. Because I remember I saw this also elsewhere. I will report back after I test it in detail.
![mpc-hc64_1SNR9ABW5p](https://github.com/clsid2/mpc-hc/assets/3073922/fd8fc1cd-bb1a-409d-acf5-5e9019eda27a)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2576

Header is a child window and wasn't getting invalidated like the rest of the listctrl.
