### ISSUE TITLE
[Suggestion] "replace filename with title" setting usage could show on caption as Author and Title just for music files

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2565]
The `Replace filename with title` option shows only the title as expected. Since author is also important for music files, I think showing author and title together would be useful and would not upset anyone. For music files without author information, only the title can continue to be used.

Example:
Author - Title     

MPC-BE uses different approach
Title (Record date)

**Comment by JamieRCHI** [comment]
I think it would be nice to see this for movies as well. Like for something I created, I would want my name to show as the Author.

**Comment by clsid2** [comment]
For movies that is a no go. I am not debating that.

**Comment by ghost** [comment]
Or maybe an option to keep it blank. I prefer a black title bar with nothing displayed. Less distractive when watching videos on a maximized window instead of using full screen.

**Comment by clsid2** [comment]
I am not adding options.
