### ISSUE TITLE
Issue with  pt-br subtitles :  found pt-br subtitles and unselected languages too

### ISSUE THREAD

**Issue by LeoKesler** [clsid2/mpc-hc#2566]
Hello.
After the issue: https://github.com/clsid2/mpc-hc/issues/2498

First:
I downloaded the version mpc-hc-2.1.4.29-c36a437b3 from k-lite codec pack. 

With that version, mpc-hc find the pt-br subtitles correctly but it shows subtitles for others languages too.  I configured mpc-hc to search for pt-br subtitles only.
Check the screenshot.
![mpc-hc-2 1 4 29-c36a437b3](https://github.com/clsid2/mpc-hc/assets/5854679/7f8bd9c2-97ad-46ac-86dd-155bbaa63a5d)

Second:
If I configure to search for pt-br and english subtitles ( pt-br en ), mpc-hc only finds english (en) subtitles.

**Comment by clsid2** [comment]
It is working fine here.
With "pob en" I only get English and pt-br results. With empty I get all languages.

Can you give link for that video? Then I can test with exact same file.

**Comment by LeoKesler** [comment]
@clsid2 
Thanks, now it is working.

Let me explain my mistake:  I was under impression the correct way was to write "pt-br".  
With the information of your message, I changed to  **pob**  and it worked .  And **pob en** is working too.
