### ISSUE TITLE
Bugs on some dialog boxes

### ISSUE THREAD

**Issue by tsubasanouta** [clsid2/mpc-hc#2569]
MPC-HC (64-bit)
Build information:
    Version:            2.1.4 (c82061aef)
    Compiler:           MSVC v19.29.30152
    Build date:         Jan 15 2024
Operating system:
    Name:               Windows 11 (Build 22H2)
    Version:            10.0.22621 (64-bit)
![WS000000](https://github.com/clsid2/mpc-hc/assets/129067724/d1c1ba9d-d2bf-4ee0-a39d-fbb160edf645)
![WS000001](https://github.com/clsid2/mpc-hc/assets/129067724/14ccb4ba-2b49-4aa2-8f0e-7d5cd465bc53)
![WS000002](https://github.com/clsid2/mpc-hc/assets/129067724/2dd5ee6c-cbc0-4c5e-a0e9-fe510bbb0389)
![WS000003](https://github.com/clsid2/mpc-hc/assets/129067724/4133c65b-df18-42c6-9f99-90900eca9d03)

**Comment by adipose** [comment]
What resolution.
What scaling factor.
What font scaling factor.

For me they are fitting.

![image](https://github.com/clsid2/mpc-hc/assets/3324395/27a841d7-dae4-40ae-81c1-25472a437217)

**Comment by xLn2** [comment]
I think I've seen similar to this problem before. On Windows installment with Asian languages, I guess the spacing of the latin letters was causing some display problems. But one of the message boxes ignores this.

Or if we look at the sample screenshoots, the window(text area) does not scale according to dpi but text does.

**Comment by tsubasanouta** [comment]
These strings and Y/N  buttons are in English on the dark theme.
These strings are in English on the light theme.
Only Y/N  buttons are in Japanese of Reset settings dialog on the light theme.
MPC-BE looks good and Y/N  buttons are in Japanese
Does these comment give you a clue to the solution?

**Comment by adipose** [comment]
> These strings and Y/N  buttons are in English on the dark theme.
> 
> These strings are in English on the light theme.
> 
> Only Y/N  buttons are in Japanese of Reset settings dialog on the light theme.
> 
> MPC-BE looks good and Y/N  buttons are in Japanese
> 
> Does these comment give you a clue to the solution?
> 
> 
> 
> 
> 
> 

Did you see my questions?

**Comment by clsid2** [comment]
I can reproduce the problem with the Reset Settings dialog in Light Theme. If uses English button text while Dark theme uses translated text.

The text not fitting is likely due to Windows bug with Asian fonts.

**Comment by adipose** [comment]
> I can reproduce the problem with the Reset Settings dialog in Light Theme. If uses English button text while Dark theme uses translated text.

I tried to reproduce this in light theme, but it shows the translations:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/8c44537a-6966-4719-8132-4004b84b1b81)

**Comment by xLn2** [comment]
> I tried to reproduce this in light theme, but it shows the translations:

Maybe misunderstanding about buttons translation strings. Maybe related this one https://github.com/clsid2/mpc-hc/issues/796#issuecomment-750401186

![resim](https://github.com/clsid2/mpc-hc/assets/3073922/54ec724a-2c09-4761-9318-fb7c55809200)
![resim](https://github.com/clsid2/mpc-hc/assets/3073922/314219f8-f431-4505-8157-55c4b6d75c89)

![resim](https://github.com/clsid2/mpc-hc/assets/3073922/6ab3abc5-06f2-40f4-8a24-628acab46dac)
![resim](https://github.com/clsid2/mpc-hc/assets/3073922/f7f655bd-37da-49c9-ac59-65e3ce0ab70e)

**Comment by adipose** [comment]
At 200% DPI on Windows 11, I produced a very strange one:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/ef0d9d74-5850-40da-96fa-4fb8252cba6f)

**Comment by xLn2** [comment]
![resim](https://github.com/clsid2/mpc-hc/assets/3073922/4a1cc3f5-78a3-4636-9f09-f9b96cc9c1f1)

First MPC-HC installation language may effect various places, I just randomly tried something for buttons translation. Wide scope investigation will be better.

**Comment by adipose** [comment]
It is a bit difficult to reproduce this problem.  After rebooting, the dialog box sizes correctly.  But if I change the display scaling settings around a bit, it breaks it (sometimes).  After changing back to 100%, it now does this:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/b3463635-c7cf-44e8-ae9c-4261e64ad93c)

Note, mpc-hc is CLOSED when I make these changes, but it still confuses it, which suggests that Windows itself isn't fully updating its behavior after a display scale change.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2835

This fixes:

1. DPI issues, especially when changing DPI after first run of mpc-hc
2. Dialog calculations are done based on the default message font instead of "current font," which makes text more likely to fit

I don't know for sure if it will fix the above issues, but it definitely is working better than before in my other tests.

**Comment by adipose** [comment]
Here's a test build, please test out the message box issues.

https://mega.nz/file/wJ4xzAZS#cCxFzCgeIE1u3DVyHv9pGtbYcazI1N-iAxiLe9Rfv2k

**Comment by adipose** [comment]
@tsubasanouta last call, I think this is fixed.

@clsid2, maybe we can close if no further activity.

**Comment by tsubasanouta** [comment]
This is fixed.
Thank you so much for your work.
