### ISSUE TITLE
OSD percentage position display

### ISSUE THREAD

**Issue by Kontus** [clsid2/mpc-hc#257]
Please add the ability to display the playback position in the OSD as a percentage.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/338

**Comment by clsid2** [comment]
Display only the %, or display both the time and the %?

00:10 / 01:00 [16%]

**Comment by adipose** [comment]
I couldn't find anything else that worked similarly.  Given the option, I find it more useful to have both.

**Comment by clsid2** [comment]
It would be fine with me to just always show both and not have an extra option for it.

**Comment by adipose** [comment]
In that case, should we also show it in the status timer, since that is where it normally copies the string from?

![image](https://user-images.githubusercontent.com/3324395/78085068-b6482680-736e-11ea-9557-d064e537b0c0.png)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/341

This one just shows the percent all the time.

**Comment by adipose** [comment]
Comment from doom9:

> Concerning 1.9.2.6, am I imagining it or has there been a change to the progress % down in the status area? I don't recall it rapidly counting up like that, or maybe the % being there at all. I guess I'd rather have the % not displayed at all, since it's distracting to see when in windowed mode and not really critical info like the information to its left (time thru, total time). Thanks. 

This is likely due to me leaving the percent on the status bar timer.  It is a bit distracting, I admit.  So maybe I will split the OSD and status bar texts?
