### ISSUE TITLE
Hi there Love your work but snap to desktop edges is options is not available anymore

### ISSUE THREAD

**Issue by alisufyanbaig-dev** [clsid2/mpc-hc#2570]
Hi there Love your work but snap to desktop edges is options is not available anymore

**Comment by xLn2** [comment]
Settings involving visual interaction between the user and the player and appearance (theme) settings were moved to the 'User Interface' page in version 2.1.4.

![mpc-hc64_xuGHSNS97M](https://github.com/clsid2/mpc-hc/assets/3073922/8fcce906-1f7d-4c67-a9a6-797edb189b7b)

**Comment by alisufyanbaig-dev** [comment]
Thanks
