### ISSUE TITLE
When replay is enabled, after the end of the video, the picture freezes and the sound starts over

### ISSUE THREAD

**Issue by mrfix1033** [clsid2/mpc-hc#2571]
https://github.com/clsid2/mpc-hc/assets/104345367/63d9a9af-8065-4f64-b375-da6ece8e1633

the latest (2.1.4) x64 version is installed, Windows 11 x64 23H2 (22631.3007)

**Comment by clsid2** [comment]
That is bug in Intel graphics driver with DirectX9.

To avoid it install MPC Video Renderer and change hardware decoder to D3D11 in video decoder settings.
