### ISSUE TITLE
Chrome and Windows detecting the setup file as virus [FALSE POSITIVE!!!]

### ISSUE THREAD

**Issue by sreeramp96** [clsid2/mpc-hc#2573]
![image](https://github.com/clsid2/mpc-hc/assets/16064120/50f3affa-bf69-4b64-9b00-26b0f5206e27)
![image](https://github.com/clsid2/mpc-hc/assets/16064120/2b5f71cc-b9a2-4285-b310-a49b87d26269)

Why it is detected as virus? Is it safe to use?

**Comment by clsid2** [comment]
Wacatac is a common false positive detection by Windows Defender.

**Comment by sreeramp96** [comment]
> Wacatac is a common false positive detection by Windows Defender.

Okay thanks for the info !!
