### ISSUE TITLE
Covers of audio files with embedded cover art resolution greater than 600 pixels cannot be displayed

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2574]
Unable to display covers of audio files with embedded cover art resolution of 1200px. If it is a player related issue and you are interested, I can send you samples by e-mail. 

I tested with old ms media player, modern ms media player, aimp and vlc player and these are shows covers.
mpc-hc, mpc-be can not show covers.

**Comment by clsid2** [comment]
Options >Advanced > CoverArtSizeLimit

If it shows nothing at all, then it might be FFmpeg problem with extraction of the metadata.

**Comment by xLn2** [comment]
> Options >Advanced > CoverArtSizeLimit

I tried it but I think this setting is for external cover. I send you samples via e-mail to take a look, if it's related to ffmpeg we'll necessarily wait. Thanks.

**Comment by clsid2** [comment]
It is also for embedded covers.

**Comment by clsid2** [comment]
FFmpeg issue.
It shows this warning:
```
Could not read mimetype from an attached picture.
```
