### ISSUE TITLE
Using w shortcut to cycle subtitles

### ISSUE THREAD

**Issue by MrPillze** [clsid2/mpc-hc#2575]
Hey, first of all thanks for all you do.

I have recently encountered an issue where I'm watching something, and some foreign talking comes on usually I would hit the shortcut W several times to cycle through the embedded subtitles but since the last 2 official releases when I hit the w shortcut it just flips from the first loaded one to turned off and back. It ignores the other embedded subs as if they are not there.

Not sure if I have missed something in the latest releases or I am encountering a bug!

Thanks

**Comment by xLn2** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/3073922/6d1b5871-8952-4ab4-8a1f-44941428ae39)
Could you be misremembering? When I checked, it seems that the W key turns subtitles on and off. The solution may be the S key.

**Comment by MrPillze** [comment]
yes you are bang on, thats what it was!   i swear w also used to cycle through too but no matter :P  fixed thanks
