### ISSUE TITLE
Frame-stepping Hangs MPC-HC if Player is Opened in Paused Mode with madVR as Renderer

### ISSUE THREAD

**Issue by gashtal** [clsid2/mpc-hc#2578]
Steps to reproduce:

- Use madVR as renderer
- Open a video in paused mode from command-line: mpc-hc64.exe /open *video_file_path*
- Try frame-stepping using keyboard shortcut

Outcome:
Video won't move, and MPC-HC windows becomes unresponsive for several seconds or indefinitely. If keyboard shortcut is used to un-pause at this time, after some time the video will suddenly jump to where it would have jumped to after frame-stepping, and start playing.

More info:
- Only seems to happen with madVR as renderer
- Won't happen if video is started in play mode, or if it is un-paused and paused and then frame-stepping is applied

**Comment by clsid2** [comment]
Madvr does not support frame stepping in this situation.
Framestep function returns an error.
