### ISSUE TITLE
Going to the next file will skip video files if GIF files are among them

### ISSUE THREAD

**Issue by SanderBouwhuis** [clsid2/mpc-hc#2579]
1. Have a directory with movies (mp4, avi, animated gif, webm, ...)
2. Start a video
3. After a video ends, it will automatically go to the next file

Bug:
If there is an animated gif file, then all videos (mp4, avi, webm, ...) will be skipped. Only gif files will be shown.

Solution:
Don't skip video files

**Comment by clsid2** [comment]
Gif is an image format and images are intentionally handled as a different group of content.

I might add an option. But right now, this is how it is intended to work. I am not interested in debating this right now, that will only increase likelihood of me closing this.

**Comment by SanderBouwhuis** [comment]
An option would be awesome. Just play all the supported files in a directory without looking at the type.
Currently, it goes from mp4 to gif, but not from gif to mp4.

**Comment by clsid2** [comment]
No, it doesn't go from MP4 to GIF.

**Comment by SanderBouwhuis** [comment]
Yes, it absolutely does!

I created an example where I put a random gif in the directory under the name 102.gif and 103.gif.
I start MediaPlayer with a file called 101.mkv.
After that video ends, it goes to the 102.gif, then it goes to 103.gif and then back to 102.gif ad infinitum. It goes from an mp4 file to a gif file, but never goes back to mp4.

Please fix (preferably in a way where all files are shown).

https://github.com/clsid2/mpc-hc/assets/10495173/e2404100-68a4-4c4e-867b-b6d24183126a

**Comment by clsid2** [comment]
It does not do that unless you have manually added .gif on the Formats settings page. I consider that a user error.

MPC-HC is a video player, not an image viewer.

**Comment by SanderBouwhuis** [comment]
1. Mediaplayer is a video player, which supports animated gifs. I turn it on in the settings, and then there is a side-effect that other videos are skipped.
2. As a workaround, if I rename the gif files to something else, like mp4, then it DOES play all the supported videos in the directory.

The workaround is very ugly, but if you don't want to fix this, I understand.
Considering it's open source, I hope maybe there is another person here on the forum who can fix this.

**Comment by clsid2** [comment]
GIF is an image format, not a video format.

If you want to treat it as video, rename to something like GIFV.
