### ISSUE TITLE
When showing a loop, the time briefly pops up

### ISSUE THREAD

**Issue by SanderBouwhuis** [clsid2/mpc-hc#2580]
1. Start a video
2. Set the start of the loop
3. Set the end of the loop

Bug:
Now, every time the loop loops to the beginning, the current time pops up in the screen.

Solution:
Don't show the time indicator when it's not on upon looping

**Comment by clsid2** [comment]
Disable OSD.

Any seek shows time, and a-b repeat performs a seek.

**Comment by SanderBouwhuis** [comment]
I tried it, but now no information is shown at all anymore. I just want to disable it when looping (a-b repeat as you call it). It's quite annoying when playing a shortish clip of for instance a fireplace or aquarium or waterfall or jungle.
Is there any way to suppress it just for a-b repeat? Even a hidden or advanced setting or so would be very helpful.

**Comment by SanderBouwhuis** [comment]
@clsid2 
This commit https://github.com/clsid2/mpc-hc/commit/090154eb406bea1e66f37a1c0a721596f7ea64bc fixed an annoyance where we couldn't properly read the video's name because it would hide almost immediately. That is awesome!

I'm not sure, but I think this commit may have also fixed the problem stated in this ticket.
Hooray!!! Now I can watch aquarium and fireplace videos without distracting pop-ups.
