### ISSUE TITLE
Am I crazy or preview seek bar feature has disappeared from the settings?

### ISSUE THREAD

**Issue by Pookson** [clsid2/mpc-hc#2581]
I've installed k-lite for most of my relatives and been using mpc-hc for almost 15+ years. I know it's a `new` release but wtf?? Had to downgrade to have more functions??

**Comment by bibsp** [comment]
It's in the User interface page. Newly added.
Options>Player>User Interface

**Comment by Pookson** [comment]
> It's in the User interface page. Newly added. Options>Player>User Interface

Thank you! Still, this feature turns off for me and my parents for no reason. Is it auto update?

**Comment by Pookson** [comment]
I'm stupid.

**Comment by slrgt** [comment]
@bibsp i can not find this option 
![image](https://github.com/clsid2/mpc-hc/assets/114287507/cd50dca0-fd32-4212-bb98-24b112a4f6d2)

EDIT: oh you have to change Hover Type option from Seek Time to Video Preview
