### ISSUE TITLE
Mediainfo file

### ISSUE THREAD

**Issue by faxalex** [clsid2/mpc-hc#2582]
Hello everyone, I need to create the mediainfo file via command line.

[Cars 2 (2011)-17.mkv.MediaInfo.txt](https://github.com/clsid2/mpc-hc/files/14319806/Cars.2.2011.-17.mkv.MediaInfo.txt)

I have tried using scripts in python (pymediainfo) but I cannot generate the same output file. But they are completely different files  

[Cars 2 (2011)-17.mkv.MediaInfo.txt](https://github.com/clsid2/mpc-hc/files/14319816/Cars.2.2011.-17.mkv.MediaInfo.txt)

Is there any way to do this?

**Comment by clsid2** [comment]
https://github.com/MediaArea
