### ISSUE TITLE
Opensubtitles.com needs username, not email. But no error.

### ISSUE THREAD

**Issue by cheeseandjamsandwich** [clsid2/mpc-hc#2583]
When setting up my opensubtitles.com account (moved from .org) my pw manager saved my email address, as os.com can use either for sign in.
When setting up os.com in the subtitles options, it signs in just fine when i use my email address. It doesn't give an error.
But when trying to download a subtitle, os.com was giving zero results.
So after enabling logging, it then showed the following error:
`OpenSubtitles2::CallAPIResponse: () ERROR: Server returned: 400 with message: {"message":"Error, invalid username/password   - remember to use your username and not your email to authenticate","status":400} (C:\Code\clsid2\mpc-hc\src\mpc-hc\SubtitlesProvider.cpp:826)`

After correcting the os.com setup to use my username, it all worked great.
Is the 'setup' not using the api in the same way, so it can take the email instead of the username?  Like the os.com website?
It would obviously be ideal if it created an error when setting up os.com.

Took me a few weeks to get round to looking into this! lol.  And an hour before reading about turning on logging.  Doh.

**Comment by clsid2** [comment]
Bad login is normally a 401 error.
I have added error dialog for this situation as well. They added this for usernames that contains an @.
Plus it now tests login directly after filling in credentials.
