### ISSUE TITLE
Subresync does not update style changes after subtitle loading except for its own part

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2585]
Subresync only updates changes made from menus accessed through its panel.

Steps:

- Load a subtitle file with multiple styles.
- Right click > Subtitle track > Styles > Change one styles "i.e. Font / Charset"
- Subresync panel stil shows old "Font / Charset"

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2879
