### ISSUE TITLE
[Suggestion] Manually adding Chapters

### ISSUE THREAD

**Issue by Olfdev** [clsid2/mpc-hc#2587]
Since MPCHC is able to remember the position in a file when we close it, it would be great to also be able to add a chapter manually and have MPCHC remember it.

We could for example right click in the seek bar and "Add Chapter" where we could give it a name and validate.
Manually added chapters could appear as a double thin bar instead of a single bold black bar and right clicking on them could give us the option to remove the Chapter.

One use case I've in mind would be adding a chapter at the end of a video intro and by simply going to the next chapter, it could act like a "Skip Intro" button.

Right now, the only way to do this is by extracting the chapters XML, editing the file and remuxing it with MKVToolnix which is quite cumbersome.

I've read that clsid2 is not looking into implementing new features but if someone with the skills needed is interested in the idea, feel free to give it a shot.

**Comment by clsid2** [comment]
You can use .xhcp file to define custom chapters. Read the changelog.

**Comment by clsid2** [comment]
There will be no extra chapter functionality.
