### ISSUE TITLE
Hi! friend! Please add video control parameters in the pop-up dialog window to customize the video

### ISSUE THREAD

**Issue by zhouxinghong** [clsid2/mpc-hc#2588]
Hi! friend! Please add video control parameters in the pop-up dialog window to customize the video

![image](https://github.com/mpvnet-player/mpv.net/assets/54253524/08c5d508-9528-4270-8d13-3e727d9ecb0b)

windows 10

Thank you very much for providing Mpc with a very excellent and good user interface🎉👍👏!

**Comment by clsid2** [comment]
Options > Miscellaneous

**Comment by zhouxinghong** [comment]
Standard player clients have integrated the above functions. We look forward to adding the above functions to mpc as soon as possible. Thank you very much for your efforts💪making the mpc player better🙏!
