### ISSUE TITLE
Rarsource filter broken

### ISSUE THREAD

**Issue by Tsoccerguy3** [clsid2/mpc-hc#259]
If a *.rar file has a multipart video and a movie poster jpeg ,jpg . it no longer asks what to play and defaults to display the jpg image in the rar archive

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/262

Test build: https://mega.nz/#!BEpCwSBZ!IgAifKlwR7Kqe_gP_OcLJGQRNKivGAKdYufrAivegYM
