### ISSUE TITLE
Hi! Friends, where is the cache file of mpc playing https://xxxxx.mp4?

### ISSUE THREAD

**Issue by zhouxinghong** [clsid2/mpc-hc#2590]
Hi! Friends, where is the cache file of mpc playing https://xxxxx.mp4?

**Comment by clsid2** [comment]
in memory

**Comment by zhouxinghong** [comment]
Is it possible to modify the cache location? I found that it is not cached in the memory, but cached in the C drive.

**Comment by clsid2** [comment]
Then you are not using the internal filters. So user error.

Microsoft filter uses temporary internet files cache location.
