### ISSUE TITLE
Seek bar stops working once video ends

### ISSUE THREAD

**Issue by DeKnep** [clsid2/mpc-hc#2592]
When a video stops because it reached its end and I then try to scroll back, the last video frame stays visible. Audio starts playing from the correct point though. I.e. the seek bar seems to influence only the audio stream once the video has ended.

Seeking before the video ends works fine.
When I stop the video and then restart it, seeking also works fine again.

This has been broken for a while now. Still broken in 2.1.5.
It doesn't matter which video renderer I choose.

**Comment by clsid2** [comment]
That is fault of Intel driver.

Recent generation Intel GPUs do not have hardware DirectX9 support. They use d3d9on12 compatibility layer to translate DX9 into DX12. That has several bugs.

You should install MPC Video Renderer. That can use DirectX 11.
In video decoder settings, change hardware decoder to D3D11.

**Comment by DeKnep** [comment]
That worked, thanks.
