### ISSUE TITLE
Video and audio go out of sync if left paused for a long time.

### ISSUE THREAD

**Issue by USSWashington** [clsid2/mpc-hc#2593]
This is a bit difficult to explain, but I'll try my best.
If I'm watching a video, and I leave it paused for a long time, long enough that my HDD “goes to sleep?” then resume it, the audio and video go out of sync where the video becomes ahead of the audio, or sometimes the video freezes, but the audio keeps playing.

VLC actually paused the video when it ran out of “buffer” until the HDD span back to speed and resumed playback then, I don't know why MPC doesn't do that as well.

**Comment by clsid2** [comment]
Options > Advanced > ReloadAfterLongPause
