### ISSUE TITLE
RTX Video HDR Crash

### ISSUE THREAD

**Issue by tychoid** [clsid2/mpc-hc#2594]
**Some** videos crash when "RTX Video HDR" is turned on
Crashes cease when "RTX Video HDR" is turned off

Error:
![Screenshot 2024-02-21 142632](https://github.com/clsid2/mpc-hc/assets/28597551/11133778-b9ef-4436-9235-124be639639f)

MPCVR:
![image](https://github.com/clsid2/mpc-hc/assets/28597551/c249823d-6814-4cb2-bfae-cacd7f8c25f7)

MPC-HC:
![image](https://github.com/clsid2/mpc-hc/assets/28597551/bb208a5d-7c89-4e88-86eb-569c18750018)

Sample Clip:
https://github.com/clsid2/mpc-hc/assets/28597551/fbed5539-47d2-4485-a4da-061fa7f3dbf2

**Comment by clsid2** [comment]
Likely a bug in NVIDIA driver.

Ask here for help:
https://github.com/Aleksoid1978/VideoRenderer/issues

This is not an issue in the player itself.

**Comment by Aleksoid1978** [comment]
Play normal in MPC-BE, don't crash.
