### ISSUE TITLE
1.85:1 aspect ratio not displaying correctly

### ISSUE THREAD

**Issue by nobananasforyou** [clsid2/mpc-hc#2595]
mpc-hc's output:
![MPC](https://github.com/clsid2/mpc-hc/assets/50061008/8074a405-39fd-4ad1-9948-ae347ed9ddd9)

mpc-be's output:
![MPCBE](https://github.com/clsid2/mpc-hc/assets/50061008/147fa07b-1622-4c11-a41e-ff811ac773f8)

sample:
https://file.io/xwTpXygMFbpI

I tested the sample on mpc-be, mpc-hc, and mpv but mpc-hc seems to be the only player stretching the image horizontally.

Kind Regards

**Comment by clsid2** [comment]
Displays perfectly fine here with 1.85:1 (50:27)

**Comment by nobananasforyou** [comment]
may I ask why it is stretching the image horizontally compared to mpc-be?

hc:
![mpc2](https://github.com/clsid2/mpc-hc/assets/50061008/f63932ef-f3f7-4a64-b20c-28bd64a83db1)

be:
![mpcbe2](https://github.com/clsid2/mpc-hc/assets/50061008/75902b45-6906-4e58-8ca8-0f839116067f)

**Comment by clsid2** [comment]
Your OSD shows wrong AR, so probably something wrong in your filter chain.

Menu > Play > Filters

**Comment by nobananasforyou** [comment]
Yes, it's fixed now. Thanks!

**Comment by clsid2** [comment]
Which filter caused the problem?

**Comment by nobananasforyou** [comment]
![qqqqqqqqqqqqqqqqqqqqqq](https://github.com/clsid2/mpc-hc/assets/50061008/44a122f2-e394-40c2-830f-91610680cb46)

I had it setup like so but I knew that I didn't specify any external filters for mpc-be so I removed everything. Now, it runs absolutely perfect on default settings.

Thank you for troubleshooting this for me.

Kind Regards

**Comment by clsid2** [comment]
MPC-HC includes LAV Filters, so adding it as external filters is not needed.

**Comment by nobananasforyou** [comment]
> MPC-HC includes LAV Filters, so adding it as external filters is not needed.

Yes, exactly. Realized this afterwards :)
