### ISSUE TITLE
MPC-HC stops playing TV-Recordings while they are recorded...

### ISSUE THREAD

**Issue by Mangerrione** [clsid2/mpc-hc#2597]
Often i use the player to watch TV-Recordings while they are recorded. The playback stops where the end of the recording was, when i started the playback. But the size/length of the recording changed in the meantime. It would be great if MPC-HC could check the filesize/length once in a minute.

**Comment by clsid2** [comment]
I am NOT interested in implementing this functionality. It would have to be done in the file source filter (splitter), not in player itself. And I can already tell you that developer of the splitter is also not interested.

You can press Ctrl+E to reload a file.
(enable remember position in options to resume at same spot)
