### ISSUE TITLE
Subtitle (.ass file) are broken in videos longer then 1 hour

### ISSUE THREAD

**Issue by Lacoi** [clsid2/mpc-hc#2598]
Since version 2.1.5 the subtitle in videos longer then 1 hours are broken.
mpc ignores the 1 hour at the start event and loads the subtilte after 1 seconds. the end event works correctly.

```csv
Format: Layer,Start,End,Style,Name,MarginL,MarginR,MarginV,Effect,Text
Dialogue: 0,1:00:01.00,1:00:04.00,Default,Test,0000,0000,0000,,Test message
```

**Comment by clsid2** [comment]
Fixed
