### ISSUE TITLE
DVB does not change channels now (regression) 

### ISSUE THREAD

**Issue by epigramx** [clsid2/mpc-hc#260]
After the issue of it losing audio under certain settings (https://github.com/clsid2/mpc-hc/issues/74) it now doesn't even change channel at all on the current version. Since the person that forked to this project doesn't have a DVB card I hope someone that does have one does something about it.

**Comment by adipose** [comment]
@clsid2 

I have an ATSC tuner, but I can't even get it connected.  It works fine with WinTV, but MPC-HC reports:

![image](https://user-images.githubusercontent.com/3324395/74078463-c5020500-49df-11ea-800d-38df4d25414a.png)

I tracked this down to IFilterGraph2.connectdirect E_NOINTERFACE.  Any hints as to what else I should try, or does ATSC not work at all?

Hauppage WinTV-HVR-955q:

![image](https://user-images.githubusercontent.com/3324395/74078482-2033f780-49e0-11ea-90c6-7a6dab880f0b.png)

Also tried ATSC network provider.

**Comment by clsid2** [comment]
I am not familiar with the DVB stuff, so I don't know either. Maybe some driver issue: https://trac.mpc-hc.org/ticket/3418

**Comment by adipose** [comment]
Thanks.  I have it working with SmartDVB, by enabling some non-obvious settings.  So I know the drivers can work.

**Comment by adipose** [comment]
@clsid2 

Maybe you can help with this.  I have gotten further by tuning the card with another application. Now, instead, it fails trying to connect filter:

BDA MPEG2 Transport Information Filter

I don't know why, but maybe you have an idea.

**Comment by clsid2** [comment]
Found this:
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/mstv/writing-digital-tv-applications-with-directx

A tune request must be send to the Network Provider filter before connecting the other filters.

**Comment by adipose** [comment]
Thanks.  I think that may be deprecated, as it uses ITuner:

![image](https://user-images.githubusercontent.com/3324395/74199272-8dca6880-4c18-11ea-9ccf-07b809192c27.png)

**Comment by clsid2** [comment]
This code may be helpful:
https://github.com/google/sagetv/blob/master/native/dll/DShowCapture-2/GraphManager.cpp
Look at "SetupBDATuningSpace" function.

**Comment by adipose** [comment]
I was able to get everything working except scanning, now, by adding this break statement to FGManagerBDA.cpp:

![image](https://user-images.githubusercontent.com/3324395/74259980-a33da200-4cad-11ea-9749-ba9721662637.png)

Without that break, it tries to attach the mpeg2demux pin twice, and it fails the second time.  I don't know enough about it to know why that might happen, but maybe it has to do with the tuner connecting to cable vs OTA (I'm trying OTA).

However, now I cannot get it to find anything when scanning.  I tried various settings based on what is working in SmartDVB, but no luck (though it does show S/Q):

![image](https://user-images.githubusercontent.com/3324395/74260339-38d93180-4cae-11ea-93c9-cc7acfec1ebc.png)

**Comment by epigramx** [comment]
Odd. Now on 1.9.1 I can scan and switch but audio is lost whenever I change channel whatever the mode of "stop filter graph" in settings. That is still a regression because previously that problem had as a workaround an "always" at "stop filter graph" but now even that doesn't fix it.

**Comment by adipose** [comment]
Good news.  I was able to make my ATSC tuner work with a few code changes and manually creating the channels.  There are some differences between ATSC and DVB that weren't handled.  I may update mpc-hc to support it, but there doesn't seem to be a lot of demand for this.

In any case, I can now change channels, and the audio continues to work.  So, I wonder, what is the problem on your end.

**Comment by adipose** [comment]
@epigramx , is the channel changing still broken for you?

**Comment by epigramx** [comment]
@adipose oh it works perfectly now even on "never rebuild" and "never stop filter graph" which makes it as fast on switching as a true TV!  Using a REALTEK DTV Filter. USB\VID_1F4D&PID_A803.

**Comment by clsid2** [comment]
How noticeable is the delay of graph rebuild? I wonder if I should revert the default back again after these fixes.

**Comment by epigramx** [comment]
@clsid2 oh it's very noticeable since it's about 5 seconds VS 0.5sec when the new channel is in the same stream/frequency and VS about 2sec when the new channel is in another stream/frequency.

**I found a bug though** since switching to channels of a specific frequency (out of ~5 frequencies available here) causes "not responding" of mpc-hc for ~10 seconds (previous video still plays)!

I guess before that is fixed fast-switching should not be default but it depends on if you prefer stability vs ease of use (e.g. I would not care if it's unstable if I can handle it).
