### ISSUE TITLE
Download Subtitles minor issues

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2604]
1. Download Subtitles' status bar
When the string does not fit, it is not shortened with ellipsis. _A separate reflection can be made on the position, size and significance of the progress bar._
![mpc-hc64_J3rjVlE1Ty](https://github.com/clsid2/mpc-hc/assets/3073922/d7b42be1-af9d-4bfa-9ae0-b7ca257e20da)

2. Same item can be downloaded again if it highlighted again
![image](https://github.com/clsid2/mpc-hc/assets/3073922/6bc96171-8251-425c-aa6f-ba25af147204) ![image](https://github.com/clsid2/mpc-hc/assets/3073922/72accb33-45b3-42c9-89af-9d3703213f7e)

3. Disc column context varieties according to provider
![image](https://github.com/clsid2/mpc-hc/assets/3073922/5cefdef8-a23a-4a22-a069-b9a0275f0efb)

4. Manual Search - navigating with Keyboard not working as expected
Enter a text and press ENTER key on your keyboard, will make download highlighted subtitle, if failed (already downloaded) windows error sound will be heard. I think ENTER key should behave as Search button while manual search box active.
![image](https://github.com/clsid2/mpc-hc/assets/3073922/f65acc75-d545-4c6b-8dea-ed06c2542d14)
Navigation with the TAB key may require a small adjustment, there seems to be a slight mistake in the ordering.

5. Manual Search - Manual search input is not updated in the caption section
![image](https://github.com/clsid2/mpc-hc/assets/3073922/e3145afc-7dd3-4352-9887-1589cef2518f)

6. Tooltips do not appear while main window is set as On Top
I do not know posibilities of it but I expect since "D.S" window is over main mpc-hc window, it should also show tooltips 'topmost' level.
![image](https://github.com/clsid2/mpc-hc/assets/3073922/a51d9f18-59d6-4d87-9615-6a0a6cd4add6)

**Comment by adipose** [comment]
1. Hmm, I suppose, but what harm does showing as much as possible do?
2. It's ok, if you want to redownload you can.  Maybe you have deleted it by accident.
3. Not sure what to do about this, but you can check the code to see where the difference comes from.  Maybe just in the subhelpers
4. Will take a look
5.
6. I don't know if it is possible to solve.  Topmost means topmost, so child windows with tooltips probably will be hidden.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2606

Fixes # 4.  The problem was <enter> was triggering the dialog OK which also does a single download. Overridden for the search field, now.

**Comment by adipose** [comment]
`#5` also should be fixed in that PR.

**Comment by xLn2** [comment]
> 1. Hmm, I suppose, but what harm does showing as much as possible do?

I don't think it does any harm either, but I've specified it to make it clear that there is a continuation of the text and to match the behavior in other parts of the application. If there is no easy solution, it may not be worth the effort.

> 3. Not sure what to do about this, but you can check the code to see where the difference comes from. Maybe just in the subhelpers

I am not sure I can understand but on opensubtitles dot com CD number show like "1". But I didn't check that OpenSubtitles where to got "-1" value. 1/1 or 0/0 makes sense, but this "-1" value has been there for a long time and no one has questioned whether it is normal or a bug.

**Comment by clsid2** [comment]
Does the Disc column ever show any actually useful information? If not, it could be removed.
Old movies that have been split into CD1/CD2 typically have that information in their filename already.

**Comment by xLn2** [comment]
I personally don't use it, but since mpchc has conservative users and that "Disc" column may be of use for some users, I thought it would be inappropriate to express my opinion. If the usage rate is not even 0.1% and is alternatively specified in the file names, I leave it to your discretion.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2609 fixes `#3`.
