### ISSUE TITLE
mpc hc subtitle delay always 500 ms

### ISSUE THREAD

**Issue by itachi93000** [clsid2/mpc-hc#2607]
Hello

i have always a delay for subs, i cant go 0 or no delay, it set 500 ms always,

![Capture d'écran 2024-02-25 224502](https://github.com/clsid2/mpc-hc/assets/161255857/c8e065d6-df60-4c73-8bae-e3cf314c687d)
![Capture d'écran 2024-02-25 224201](https://github.com/clsid2/mpc-hc/assets/161255857/00a0421b-d737-45a0-a114-ab791dae220f)
![Capture d'écran 2024-02-25 224236](https://github.com/clsid2/mpc-hc/assets/161255857/65776aa7-b858-4929-855d-629bebcfb37f)

**Comment by xLn2** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/3073922/9feaa5a8-4dd2-4dfe-871d-7c649e0ef2ed)

The value there is for setting the duration of the subtitle delay step (threshold) with the F1 and F2 buttons. If you press F1 your subtitle shown -{500} ms earlier or contrary you press F2 +{500} ms delayed.

So this is a threshold that is only used when the F1/F2 keys are pressed.
