### ISSUE TITLE
[Feature Request] A-B for playlist items

### ISSUE THREAD

**Issue by ericdelappe** [clsid2/mpc-hc#2608]
In MPC-HC you can mark A-B points to loop a section of a particular file. Skipping to the next file in the playlist completely clears out this selection.

I would like to be able to set a separate A-B section for each item in the playlist. That way, when playlist repeat mode is active, the A-B section will not loop but go straight to the A-B section of the next file in the list. So we can create playlists of partial sections of videos rather than full videos.

Of course the .mpcpl file format would have to be amended to include optional A-B timestamps for each item in the playlist.

(there is a third-party companion app called [MPC-HC-Looper](https://github.com/taburineagle/MPC-HC-Looper) which does this but having the functionality directly in MPC would be a lot more convenient)

Other improvements to A-B that I'd like to suggest

- currently when you place the playhead before the A point or after the B point, the entire A-B section is cleared out. I don't like this behavior at all, I'd like to be able to navigate to other parts of the video without losing the A-B points.
- I'd like a button/shortcut to toggle the entire A-B section on/off, without losing the positions. This could be indicated visually where the A-B section of the timeline is a different color when active.
- Buttons/shortcuts to jump straight to the A point and B point, respectively

**Comment by clsid2** [comment]
A-B settings are stored in file history. So if you played a file before, it will remember.

You can press Home to jump to A.
Jumping to B makes sense.

I am not interested in adding new functionality.

**Comment by clsid2** [comment]
You can use `videofilename.xchp` file to add custom chapters to a file. These are seek points when using PageUp/Down.

```
00:00:15,000 A
00:02:00,000 B
00:03:00,000 Chapter C
```

**Comment by ericdelappe** [comment]
sorry, I hadn't seen the post stating that you're not interested in feature requests

thanks for the additional info, it's very useful but unfortunately will not achieve my goal which is to make playlists of sections of videos. well, if I really want that functionality then I will have to learn to code it myself

**Comment by clsid2** [comment]
AB limits you to just one section per video.

You can use FFmpeg to cut pieces of a video.
