### ISSUE TITLE
ASS subtitles support is probably broken for version 2.1.5

### ISSUE THREAD

**Issue by hdkeeper** [clsid2/mpc-hc#2613]
Provided ASS script displays incorrectly in MPC 2.1.5. Multiple event lines are shown at once, filling entire screen with unreadable mess.

[[ReinForce] PSYCHO-PASS Providence (BDRip 1920x1080 x264 FLAC).ass.zip](https://github.com/clsid2/mpc-hc/files/14424611/ReinForce.PSYCHO-PASS.Providence.BDRip.1920x1080.x264.FLAC.ass.zip)

However, MPC 2.1.4 and earlier renders this script just fine. Perhaps one of updated libraries has caused this issue.

The video can be downloaded from https://rutracker.org/forum/viewtopic.php?t=6491360

**Comment by clsid2** [comment]
Already fixed in latest development build...
