### ISSUE TITLE
OSD Font size and Playback rate options

### ISSUE THREAD

**Issue by bw4518** [clsid2/mpc-hc#2615]
1) Why it is not possible to have an OSD Font over size 25? Editing the .ini directly didn't work either.

2) Any possibility to alter Playback rate options in the context menu?

**Comment by clsid2** [comment]
1. Changed max to 50.
2. The the pletora of options is not sufficient for you, then you can adjust the speed step in the settings to e.g. 5 or 10%. And if that also is not sufficient, then you are shit out of luck.
