### ISSUE TITLE
Suggestion for layout in OSD display when navigating between chapters with skip backward/forward command

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2616]
Currently seeking with skip backward/forward some logical and visual issues.
![image](https://github.com/clsid2/mpc-hc/assets/3073922/f2dad126-efeb-4d86-add1-7ccc27cfea57)
![image](https://github.com/clsid2/mpc-hc/assets/3073922/890afb40-52c6-421a-8699-7d1965506ff2)
![image](https://github.com/clsid2/mpc-hc/assets/3073922/ba0b28f9-7974-4ac5-bb94-f56fa43213e0) - ![image](https://github.com/clsid2/mpc-hc/assets/3073922/8e7f7f22-a1b9-4a20-a2b1-f173381db27a)

1. OSD shows hour even media does not have an hour duration
Media has 24min OSD shows 00:03:24/00:24:00

2. No space between elapsed time and duration
Normal seeking shows 03:24 / 24:00 but skip f/b cause to show like `#1`

3. Media lengths vary, it can be decided to display one of them for harmonization. (for OSD)

Currently (2.1.5) OSD displays while skip b/f: 
00:03:24/00:24:00 Chapter: 2/7 - "Preview"

My suggestions: 
03:24 / 24:00 - Chapter: •Preview (2/7)
03:24 / 24:00 (13.3%) - Chapter: •Preview (2/7)

The use of bullet points `•` at the beginning of chapter names may improve visual clarity. I hope the majority of fonts supported it.

**Comment by clsid2** [comment]
Bullet point is ugly.

**Comment by xLn2** [comment]
Since it `•` will be present in most fonts, and there are possible distracting cases like `Chapter: Chapter 1` hereby it makes sense to me. Quotation marks (also have different styles usages from country to country) and paranthesis also looks rude.

There is also a middle dot `·` option, although I don't think it makes much difference. It looks more polite, but I don't know how common it is in fonts.
If there are better suggestions, I expect people to share them.

https://fonts.google.com/specimen/Roboto?preview.text=03:58%20%2F%2024:40%20(13.3%25)%20-%20Chapter:%20%E2%80%A2%CE%87Preview%20(2%2F7)

**Comment by bibsp** [comment]
Add space and remove hour from OSD as xLn2 mentioned.

In my suggestion there is no need to mention the word "chapter". It will give more free space to the screen. In case of long chapter name, it will be helpful. Like,

03:24 / 24:00 - "Chapter Name" (2/7)
Or,
03:24 / 24:00 (13.3%) - "Chapter Name" (2/7)

**Comment by xLn2** [comment]
> In my suggestion there is no need to mention the word "chapter".

It may create more complexity in videos where chapter start times are specified as chapter names.

A scenario where the chapter translation is also in the chapter name can also be considered.
{search key}
{TranslatedChapter}: `Chapter 1`    

_if included ->_ Chapter 1

i.e. "Bölüm: Chapter 1" etc. I don't have a problem with different languages, but using the same words might not be nice.

If what I am trying to explain is feasible, there is no need for quotation marks or other marks. 

04:24 / 24:00 - Chapter: "Chapter 1" (3/7) `---------------->` 04:24 / 24:00 - Chapter 1 (3/7) 
04:24 / 24:00 (15.8%) - Chapter: Chapter 1 (3/7) `---------->` 04:24 / 24:00 (15.8%) - Chapter 1 (3/7)
03:24 / 24:00 (13.3%) - Chapter: "Preview" (2/7) `---------->` 03:24 / 24:00 (13.3%) - Chapter: Preview (2/7)

**Comment by clsid2** [comment]
I have made some tweaks.
This is final decision.
