### ISSUE TITLE
Can't display Japanese subtitle

### ISSUE THREAD

**Issue by onmyouji** [clsid2/mpc-hc#2617]
Build information:
    Version:            2.1.6 (4a9c40908)
    Build date:         Feb 28 2024

LAV Filters:
    LAV Splitter:       0.78.0.3
    LAV Video:          0.78.0.3
    LAV Audio:          0.78.0.3
    FFmpeg compiler:    MinGW-w64 GCC 13.2.0

Operating system:
    Name:               Windows 10 (Build 22H2)
    Version:            10.0.19045 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    GPU:                NVIDIA GeForce GTX 950M (driver version: 31.0.15.3734)

Text:
    Scale Factor:       1.000000
    Ansi Codepage:      1252

Hello,

I'm having issue displaying Japanese subtitle on MPC-HC. I've tested using other media player e.g. VLC and SMPlayer, they both have no issue displaying the subtitle.

On MPC-HC, the subtitle track is shown as `No subtitles`

![Copy of 2024-02-29_113836](https://github.com/clsid2/mpc-hc/assets/8424198/b0ee414b-4fd2-40d2-917d-ef6ac57ffe2b)

Can someone help to troubleshoot this? Thanks

**Comment by xLn2** [comment]
Is the subtitle embedded or external? Do you know the extension?
Could it be due to Options > Subtitles > Misc settings?
![image](https://github.com/clsid2/mpc-hc/assets/3073922/2bcc7de7-2a12-453d-91b5-3aa0ca7351e9)

A sample file may be needed for developers to diagnose.

**Comment by bibsp** [comment]
If subtitles are not flagged as enabled then player will not load those.

**Comment by clsid2** [comment]
Download MkvToolNix.
Use its header editor to change value of the `enabled` flag for the currently hidden track.

VLC only shows it because it does not correctly follow the Matroska specification. So actually the behavior of VLC is wrong! And this results in people to continue creating broken files.
