### ISSUE TITLE
Subtitle delay when watching AV1 video using SRT format

### ISSUE THREAD

**Issue by Firmeteran** [clsid2/mpc-hc#2618]
Hi, this bug kinda annoying to me,
there's this delay time using SRT subtite on AV1 clips, only by couple milliseconds. It can be easily reproduced.

For specs, I'm using [this](https://www.asus.com/laptops/for-home/vivobook/vivobook-s14-m433/) one. IMO doesn't really matter, since it's also happened on my PC with (kinda) med-high specs.

**Comment by clsid2** [comment]
User brain error.

Subtitle renderer works independent of the video format. There is no millisecond accuracy when rendering is limited to frame times, which are typically 41 ms apart.
