### ISSUE TITLE
Using MPC video renderer breaks Hardware Acceleration

### ISSUE THREAD

**Issue by xatornet** [clsid2/mpc-hc#2620]
Hi there,

I don't know what is causing it, but as soon as I enable MPC Video renderer, it breaks the hardware acceleration. If I use the stock EVR, it works fine.

I've checked with MPC-BE, and MPC Video Renderer works fine, even the version listed in this github. What can I do? 8K videos are very sluggish on MPC-HC without H/W acceleration. Is there any log I can add to this for you guys to help me pinpoint the issue?

Here's my system's specs:
Windows 11 Pro fully updated
AMD Ryzen 9 5950X
64GB DDR4 3600Mhz
RTX 3090
Nvme 2TB SSD
3440x1400 @ 144Hz screen.

Here's an example of the same video, played on the left with MPC Video Renderer and using EVR on the right, to make my point understandable:

https://github.com/clsid2/mpc-hc/assets/43992639/db4f4c82-d2a7-4ec1-a7dd-5d7211ec2300

Thanks :-)

**Comment by clsid2** [comment]
Use D3D11 hardware acceleration in video decoder.

**Comment by xatornet** [comment]
> Use D3D11 hardware acceleration in video decoder.

![image](https://github.com/clsid2/mpc-hc/assets/43992639/3e3e7583-81f0-42ff-b7c7-b8bf275fcde5)

It was already selected and it still exhibits the same behaviour...

UPDATE: You meant on the LAV filter. Ok, Thanks!!

**I wonder WHY is it not working with DXVA2 though...?**

**Comment by clsid2** [comment]
Because the renderer removed support for DXVA2 Native (DirectX9) in DirectX11 mode.
