### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by Rold1999** [clsid2/mpc-hc#2626]
If possible, I would like to be able to take screenshots where subtitles are visible. Thanks for the great player.

**Comment by bibsp** [comment]
File > Save Image

**Comment by Rold1999** [comment]
I don't think you understand what my problem is. I want to take screenshots
and have subtitles on them. I've tried everything in the player. All
screenshots are without subtitles.

вс, 3 мар. 2024 г., 19:10 clsid2 ***@***.***>:

**Comment by clsid2** [comment]
There is a subtitle option in the Save Image dialog.
