### ISSUE TITLE
mpc hc subtitle delay +100ms 

### ISSUE THREAD

**Issue by itachi93000** [clsid2/mpc-hc#2627]
Hi

By default, a delay of +100ms is applied to each video playback.

F1/F2 works, but each time, I have to press on startup to apply -100 ms.

On other players, I haven't seen any delay, so there's no problem with subtitles.  (I tested on several files)

Is it possible to get a fix or a regedit file to correct this ?

Thanks 

![Capture d'écran 2024-03-03 200647](https://github.com/clsid2/mpc-hc/assets/161255857/be3196e1-1ab1-4c8b-9eed-5b5e2025af0c)
![Capture d'écran 2024-03-03 200655](https://github.com/clsid2/mpc-hc/assets/161255857/c256bdd8-a6bf-4b1c-8811-b8dd6c8ff768)

**Comment by adipose** [comment]
Has this been the case on older builds?

**Comment by itachi93000** [comment]
Yes, im gonna test old builds

**Comment by clsid2** [comment]
Works fine for me.

**Comment by itachi93000** [comment]
Can you send me your settings please ? (reg file) if possible ?

**Comment by clsid2** [comment]
Options > Miscellaneous > Reset

**Comment by itachi93000** [comment]
Options > Miscellaneous > Reset > Done

Still same

**Comment by clsid2** [comment]
How are you making conclusion that delay is exactly 100ms?

**Comment by itachi93000** [comment]
after a test
i uninstall > Clean all folders files 
No problem anymore, thanks for your help
very weird, probably my computer
