### ISSUE TITLE
Playback rate change is more rapid when increasing/decreasing rate using shortcut key

### ISSUE THREAD

**Issue by fuweichin** [clsid2/mpc-hc#2632]
**Steps to Reproduce:**  
1. Open a video file
2. Press <kbd>Ctrl</kbd>+<kbd>ArrowUp</kbd> to increase playback rate
3. See current playback rate in the upper right corner

**Expected Result:**  
Playback rate shall be changed to next value, (e.g. the next value of 1x is 1.1x), as enumerated in Menu / Play / Playback Rate.

**Actual Result:**
Playback rate was changed from 1x to 2x, which is too jumpy.

Additional Information:
MPC-HC 2.1.6 x64

P.S. I use a mini custom keyboard with three knobs, to change volume, brightness and playback rate. I find the playback rate change of MPC-HC 2.1.6 (with shortcut key) is too rapid.

**Comment by clsid2** [comment]
No, that is not the expected result. Never has, never will.

It uses the speed step as defined here:
Options > Playback > Speed step

Auto = 2x. You can change it to 10% if you prefer that.

**Comment by fuweichin** [comment]
*Sorry for my inattention, this issue was reported in a bug report format, but I didn't mean it's a bug.*

I want to increase playback rate to 1.25x 1.5x or so with shortcut key, like the "Increase playback rate" of YouTube.com.

![shortcut](https://github.com/clsid2/mpc-hc/assets/1687235/be280fba-ae62-4c95-be7a-f72a093ef501)


If the behavior of "Increase Rate" cannot be changed for some reason, please add another shortcut key/action to "Step rate up" which will behave as Expected Result above.

**Comment by clsid2** [comment]
Read the instructions I gave on how to change the "speed step" value!

No other functionality will be added.
