### ISSUE TITLE
Forced resume playback while playback speed changes

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2633]
When the playback speed is changed, the current playback state is ignored and playback continues, a behavior that is not in line with user intent.

There is a paused video and I intend to resume playback after determining the appropriate slowdown value (i.e. watching surveillance cam recording). But with every speed change, even when the reset speed button is pressed, the paused video continues to play.

Expected behavior: 
The player should keep the current playback state on speed changes

**Comment by clsid2** [comment]
This is intended behavior, and I am not likely to change it.

**Comment by xLn2** [comment]
I checked my own usage scenario and also tested with Mpc-be and found that playback is not resumed there. It's up to you to decide.

**Comment by clsid2** [comment]
You can quickly set specific rates here:
Menu > View > Playback rate
