### ISSUE TITLE
2.1.6.17 will not play videos.

### ISSUE THREAD

**Issue by Tregis** [clsid2/mpc-hc#2637]
Just installed 2.1.6.17x64 did a refresh and it will not play any video type.  The first frame will load and then send the  GPU into 96-97% decode mode and hang.

Reverted to 2.1.6.8x64 and it works fine.

**Comment by NBruderman** [comment]
Can confirm the issue exists for me too,
version 2.1.6.12x64 (from the latest K-lite) works just fine.

**Comment by clsid2** [comment]
I have removed it.
I need to check what is wrong with LAV build.

**Comment by JOAOPUSERNET** [comment]
The avcodec-lav-60.dll file.

**Comment by clsid2** [comment]
New build is available

**Comment by Tregis** [comment]
Thanks!  Fixed the issue.
