### ISSUE TITLE
All videos frozen after upgrade from 2.0.0 to 2.1.6.17

### ISSUE THREAD

**Issue by RiesRobert** [clsid2/mpc-hc#2639]
Windows 10 Pro 22H2, Intel(R) Core(TM) i7-7600U

Opening a video of any filetype, with default settings. It will just show the first frame of the video frozen, and the playhead position will increment, but the video remains frozen, and there is no audio.

If you reposition the playhead, it will update the frozen frame.

v2.1.6 confirmed working.

**Comment by clsid2** [comment]
Get 2.1.6.18
