### ISSUE TITLE
"Download subtitles" function disabled

### ISSUE THREAD

**Issue by CatPlanet** [clsid2/mpc-hc#264]
Hi, I have a problem with mpc-hc, lastest beta 1.9.1.11 (d2d742e61).
For some reason unknown pressing default shortcut "D" doesn't bring popup with sub-search so I went to menu and

https://i.imgur.com/Z5khcI5.png

this is what I see. Everything is disabled. I see no other people in both open/closed issues bothered with this so my question is: what did I fucked up? Any help would be appreciated.

```
MPC-HC (Nightly, 64-bit)
------------------------

Build information:
    Version:            1.9.1.11 (d2d742e61)
    Compiler:           MSVC v19.16.27035
    Build date:         Feb  5 2020

LAV Filters:
    LAV Splitter:       0.74.1.31
    LAV Video:          0.74.1.31
    LAV Audio:          0.74.1.31
    FFmpeg compiler:    MinGW-w64 GCC 9.2.0

Operating system:
    Name:               Windows NT 6.1 (build 7601, Service Pack 1)
    Version:            6.1 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
    GPU:                Intel(R) HD Graphics 4000 (driver version: 9.18.13.5286)

```

**Comment by clsid2** [comment]
Options > Playback > Output

Select a video renderer that is compatible with subtitles, such as "Enhanced Video Renderer (Custom Presenter)". Also select Internal Subtitle Renderer.

**Comment by CatPlanet** [comment]
Thank you, I guess I set it to "Video Mixing Renderer 9" while I was drunk because it had working both subs and screenshots. Never computer while drunk.
