### ISSUE TITLE
ToDo list for Audio statusbar info and IAMStreamSelect code changes

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2640]
High priority:
- all fixed already

Low priority:
- Handle audio changes when done through splitter tray icon. [fixed]
- Audio info is shown even if track fails to connect to a decoder. Not sure if this can be prevented. Check if pin is connected? 
[Sample](https://github.com/clsid2/mpc-hc/files/14530264/speex_openacm.zip)

Not fixable:
- If source filter is also a decoder, then audio format shows as `PCM`. For example with BassAudioSource.

**Comment by adipose** [comment]
> * Handle audio changes when done through splitter tray icon.

Can we just use WM_TIMER?  I believe DVD updates are already handled there.

**Comment by adipose** [comment]
https://gix.github.io/media-types/

**Comment by clsid2** [comment]
CMainFrame::OnTimer()
I want to avoid repeatedly running code to check if tracks were changed. Better to do it just if something has actually changed.

**Comment by clsid2** [comment]
Can you test if DVB still works properly?
