### ISSUE TITLE
Gathering on demand informations

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2642]
The new commits seem to be intended not to bring information unless requested. From what I have seen mpchc 2.1.6.18 (and earlier) in Window Spy for AHKv2, some information seems to be called irrelevantly. I don't know how true it is, I just wanted to report it.

![image](https://github.com/clsid2/mpc-hc/assets/3073922/94d81c17-a316-439d-8820-29b4ef97cdc4)

```
08:33 / 24:53 (34.4%)
Paused [H/W] [HEVC 760x576 23.98 fps] [AUD: jpn]
Frame rate
-
Sync Offset
-
Frames
-
Jitter
-
Buffers
-
Bitrate
-
Title
[***********.mkv
Chapter
A Part (4/9)
Edit List Editor
Edit List Editor
User :
Hot folder :
Subresync
Navigation Bar
Navigation Bar
Info
Scan
Radio stations
Capture Settings
Video
Set
Audio
Output
Record Video
Preview
Record Audio
Preview
V/A Buffers:
...
Audio to wav
Record
Playlist
Playlist
```

**Comment by clsid2** [comment]
You need to point to code segments that are executed frequently and unnecessarily.

**Comment by xLn2** [comment]
I don't know if the information is required or how often it is updated. I opened this issue because as far as I can see,  I thought it might be relevant in addition to your work on making sure that statistic informations are not fetched unless user requests it.
