### ISSUE TITLE
Same MPEG format. But Video is UNKN, Audio is identified properly.

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2644]
`General
Complete name                  : G:\Tollywood\Wanted (2010)\AVSEQ03.DAT
Format                         : CDXA/MPEG-PS
File size                      : 438 MiB
Duration                       : 43 min 45 s
Overall bit rate mode          : Constant
Overall bit rate               : 1 411 kb/s
Frame rate                     : 25.000 FPS

Video
ID                             : 224 (0xE0)
Format                         : MPEG Video
Format version                 : Version 1
Format settings                : CustomMatrix / BVOP
Format settings, BVOP          : Yes
Format settings, Matrix        : Custom
Format settings, GOP           : M=3, N=15
Duration                       : 43 min 45 s
Bit rate mode                  : Constant
Bit rate                       : 1 150 kb/s
Width                          : 352 pixels
Height                         : 288 pixels
Display aspect ratio           : 4:3
Frame rate                     : 25.000 FPS
Standard                       : PAL
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Compression mode               : Lossy
Bits/(Pixel*Frame)             : 0.454
Time code of first frame       : 00:00:00:00
Time code source               : Group of pictures header
GOP, Open/Closed               : Open
GOP, Open/Closed of first fram : Closed
Stream size                    : 360 MiB (82%)

Audio
ID                             : 192 (0xC0)
Format                         : MPEG Audio
Format version                 : Version 1
Format profile                 : Layer 2
Duration                       : 43 min 25 s
Bit rate mode                  : Constant
Bit rate                       : 224 kb/s
Channel(s)                     : 2 channels
Sampling rate                  : 44.1 kHz
Frame rate                     : 38.281 FPS (1152 SPF)
Compression mode               : Lossy
Stream size                    : 69.6 MiB (16%)`

![Screenshot (45)](https://github.com/clsid2/mpc-hc/assets/98865389/5fa751c0-94b4-4a10-923c-21487722ed02)

**Comment by clsid2** [comment]
Fixed
