### ISSUE TITLE
Problem with dual audio movies

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2645]
Initially status bar shows nothing about audio. Once I switch the audio track, then it works. Plus status bar speaker icon indicates no track.

And if I don't close the player and open a different video with single audio track, and then play any video with multi audio track then also everything works fine.

https://github.com/clsid2/mpc-hc/assets/98865389/d1798c3c-f06c-444f-b81b-d2a194c8e0fe

**Comment by clsid2** [comment]
Try 2.1.6.42

**Comment by bibsp** [comment]
Fixed.
