### ISSUE TITLE
mp3 is detected as pcm. Is it correct?

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2648]
![Screenshot (48)](https://github.com/clsid2/mpc-hc/assets/98865389/dc6a727b-004c-4780-8df3-50213bf26ad8)
General
Complete name                  : C:\Users\*****\Downloads\01 Sunn Le Zara - 1921 (Arnab Dutta) 320Kbps.mp3
Format                         : MPEG Audio
File size                      : 10.6 MiB
Duration                       : 4 min 37 s
Overall bit rate               : 320 kb/s
Album                          : 1921 - PagalWorld.com
Album/Sorted by                : PagalWorld.La
Album/Performer                : Arnab Dutta
Album/Performer/Sort           : PagalWorld.La
Track name                     : Sunn Le Zara - PagalWorld.La
Track_More                     : PagalWorld.La
Track name/Sorted by           : PagalWorld.La
Grouping                       : PagalWorld.La
Original/Album                 : PagalWorld.La
Performer                      : Arnab Dutta - PagalWorld.La
Performer/Sorted by            : PagalWorld.La
Performer/Url                  : PagalWorld.La
Original/Performer             : Arnab Dutta
Composer                       : Harish Sagane
Composer/Sorted by             : PagalWorld.La
Lyricist                       : PagalWorld.La
Original/Lyricist              : PagalWorld.La
Conductor                      : PagalWorld.La
Encoded by                     : PagalWorld.La
Remixed by                     : PagalWorld.La
Publisher                      : PagalWorld.La
Genre                          : Bollywood
Podcast category               : PagalWorld.La
Released date                  : PagalWorld.La
Recorded date                  : 2018
Writing library                : LAME3.99.5UUUîFÒDW
ISRC                           : PagalWorld.La
Service name                   : PagalWorld.La
Service/Url                    : PagalWorld.La
Cover                          : Yes
Cover type                     : Cover (front)
Cover MIME                     : image/jpeg
Initial key                    : PagalWorld.La
Official audio file webpage    : PagalWorld.La
Official audio source webpage  : PagalWorld.La
Commercial information         : PagalWorld.La

Audio
Format                         : MPEG Audio
Format version                 : Version 1
Format profile                 : Layer 3
Format settings                : Joint stereo
Duration                       : 4 min 37 s
Bit rate mode                  : Constant
Bit rate                       : 320 kb/s
Channel(s)                     : 2 channels
Sampling rate                  : 44.1 kHz
Frame rate                     : 38.281 FPS (1152 SPF)
Compression mode               : Lossy
Stream size                    : 10.6 MiB (100%)
Writing library                : LAME3.99.5UUUîFÒDW

Image
Format                         : JPEG
Width                          : 500 pixels
Height                         : 500 pixels
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Compression mode               : Lossy
Stream size                    : 43.0 KiB (0%)

**Comment by clsid2** [comment]
Fixed
