### ISSUE TITLE
MPCVR failed to load 

### ISSUE THREAD

**Issue by DeathVerse** [clsid2/mpc-hc#2649]
![QQ截图20240307204209](https://github.com/clsid2/mpc-hc/assets/45030833/ac7e7141-e5b3-4759-8a1d-b9821563f08f)
When I enable MPC, it will prompt loading failure. I have reinstalled different versions and still see this issue. How can I solve this problem? Thank you for your help

**Comment by bibsp** [comment]
Did you delete the files of MPCVR after installation?

**Comment by clsid2** [comment]
Do not delete or move the files after running registration command.

**Comment by akzov** [comment]
what files, what registration command? Didn't it used to work after install?
