### ISSUE TITLE
How To Disable Auto Maximize / Bring To Front?

### ISSUE THREAD

**Issue by 0-Satanael** [clsid2/mpc-hc#265]
Steps to reproduce:
while MPC is playing a file and it is background or minimized:
open a new file or
add a file to the playlist or
after a file finished playing the next file on the list will make MPC Always come to the front on its own any fix for this please it is really annoying when you play Audio files only.

**Comment by adipose** [comment]
Can you upload your settings?  I do not see this behavior.

You mention the next item in the playlist is enough to trigger it, but for me it just remains minimized.

You mentioned adding an item to the playlist.  How did you do this while it was minimized?

**Comment by clsid2** [comment]
Add through Explorer context menu
Options > Player > Formats

Next item does not trigger focus here either.

**Comment by adipose** [comment]
It's caused by this code in mplayerc.cpp:

![image](https://user-images.githubusercontent.com/3324395/74872979-1cbf3b00-5313-11ea-8a68-807dff3335b3.png)

It could be disabled with an advanced option if we wanted.

**Comment by 0-Satanael** [comment]
sorry i was just a little bit confused i was able to reproduce it by using the following steps
while MPC is minimized and if you right click on an item "add to MPC-HC Playlist" also if you opened an item will bring MPC to the front and steal focus.
how do i upload my MPC settings?
i'm using windows 10 v1909 pro here

**Comment by adipose** [comment]
If that's how you are doing it, I can already reproduce it, so no need to upload.

**Comment by adipose** [comment]
Here is a test build:

https://mega.nz/#!0EB1XSbT!uQMgYXbQ5oDbqJV216ayHhv2oOvdrUDNjjbdP_zT-Wk

Note the advanced option:

![image](https://user-images.githubusercontent.com/3324395/74904646-1fe11800-5361-11ea-9a05-e53bc47d1393.png)

**Comment by 0-Satanael** [comment]
> Here is a test build:
> 
> https://mega.nz/#!0EB1XSbT!uQMgYXbQ5oDbqJV216ayHhv2oOvdrUDNjjbdP_zT-Wk
> 
> Note the advanced option:
> 
> ![image](https://user-images.githubusercontent.com/3324395/74904646-1fe11800-5361-11ea-9a05-e53bc47d1393.png)

Working Great Thank You!
