### ISSUE TITLE
Black screen when playing specific streaming video (by providing url)

### ISSUE THREAD

**Issue by kaixinol** [clsid2/mpc-hc#2652]
REMOVED

**Comment by clsid2** [comment]
I copy link of video above and play that http stream from github with MPC-HC and everything works fine.

Press Ctrl+J to show renderer debug overlay. Make screenshot.

**Comment by kaixinol** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/100816732/ee4e685f-2234-4874-a535-6878ba635f5f)
![image](https://github.com/clsid2/mpc-hc/assets/100816732/f4c0ddb6-d8fe-404f-ba1c-7a08e840141b)

**Comment by clsid2** [comment]
Looks like dexuming failure. Probably an issue with the webserver. Maybe it doesn't allow random file access,

Test if it works with the github link of your video.

**Comment by kaixinol** [comment]
> Looks like dexuming failure. Probably an issue with the webserver. Maybe it doesn't allow random file access,
> 
> Test if it works with the github link of your video.

I found that when the incoming format is flv, it is fine, but not when it is mp4.

**Comment by kaixinol** [comment]
> Looks like dexuming failure. Probably an issue with the webserver. Maybe it doesn't allow random file access,
> 
> Test if it works with the github link of your video.

I'm afraid not. I'm in China, China has GFW blocking access to github, and mpc-hc has no proxy function.

**Comment by kaixinol** [comment]
And webm also seems to be always in a black screen state

**Comment by clsid2** [comment]
Http server must support range requests.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
