### ISSUE TITLE
A performance issue with libass

### ISSUE THREAD

**Issue by NBruderman** [clsid2/mpc-hc#2654]
I've been trying libass for a while now, with no apparent issues.
However, today I found randomly a weird lag when a rolling rainbow subtitles appeared on screen.
This issue doesn't occur with the internal subtitles renderer without libass, nor with libass while using mpv.
I added the sample below for you to try yourself.

[Sample](https://mega.nz/file/iFdiSSyQ#7K3Yt0o3B24txrt7VnjnIqoMoeoBovLKCt7AUzHHyik)

**Comment by clsid2** [comment]
Plays fine here.

**Comment by NBruderman** [comment]
Hmmm... I have rather strong hardware, and it works fine with the internal subtitle renderer, so it's weird...
But I guess it is a hardware issue

**Comment by clsid2** [comment]
Oh, libass was turned off here I see now.

But anyway, I can't fix it.

**Comment by NBruderman** [comment]
Thanks for the response.

**Comment by NBruderman** [comment]
I thought it was something regarding the optimizations of libass in mpc-hc.
Do you think it's a core libass issue?

**Comment by clsid2** [comment]
We already use all available optimizations.

It plays without stuttering here even with libass.
CPU usage is similar to VLC which also uses libass.
