### ISSUE TITLE
Remember file position does not work when playing audiobooks

### ISSUE THREAD

**Issue by Araeos** [clsid2/mpc-hc#2656]
The remember file position does not open audio files and audiobooks at the last position.
The registry key `FilePosition` remains 0 and the goto command (`ctrl + g`) does not show any frame number as seen below, since the only image is the embedded cover image (which is not even listed as a video stream in the mp4 container).
![image](https://github.com/clsid2/mpc-hc/assets/6041246/8c9f5e71-44be-4980-b88a-1cb3704a7515)

I would expect mpc to remember the last position regardless of the available frames since the player lists audio formats in the file extensions list (options->Formats).

**Comment by Araeos** [comment]
To be clear, the remember position feature does work in the video files I tested.

**Comment by clsid2** [comment]
Options > Advanced > RememberPosForAudioFiles

**Comment by Araeos** [comment]
It works and I obviously assumed incorrectly a connection between frames and `FilePosition`.
Thank you very much. It was set to False, even though I'm pretty sure to never have touched this.

**Comment by NBruderman** [comment]
It's set to false by default
