### ISSUE TITLE
ASS Style Editing missing with libass turned on

### ISSUE THREAD

**Issue by saberblaze** [clsid2/mpc-hc#2657]
Apologies if this has already been addressed, I was not able to find reference to it by searching the issues.

When libass is turned on, the styles options box that lets one modify all the styles used by the ass subtitles is replaced with one that one lists a single default style, however it is non-functional. If an external ass file is loaded, the styles options box listing all the styles used is back to normal, however any changes made in it are non-functional as well. 

Since libass support is new, is style customization potentially coming back in the future or is this the intended behavior? In other words, not possible with this implementation of libass? Previously I used xysubfilter with libass https://github.com/Masaiki/xy-VSFilter/releases
which supports modifying the styles from the tray icon.

**Comment by clsid2** [comment]
Editing styles for libass is not supported (yet).

**Comment by saberblaze** [comment]
Thank you for clarifying, at least there is chance for it to be implemented in the future.
