### ISSUE TITLE
Remember file position doesn't work 

### ISSUE THREAD

**Issue by FabianLoRs** [clsid2/mpc-hc#2659]
Hello everyone, so remember file position doesn't work 

Video demo:

https://streamable.com/erf3ax

Cheers.

**Comment by clsid2** [comment]
If you press STOP, then remembered position is reset. You should just close the player or move to next file. Pressing STOP is unnecessary action.

**Comment by FabianLoRs** [comment]
Hello, thanks for your answer, I noticed that it doesn't detect some videos:

https://github.com/clsid2/mpc-hc/assets/122753033/f239e0cc-1147-4806-99b7-9836c6175263

**Comment by clsid2** [comment]
Options > Advanced > RememberPosForLongerThan
