### ISSUE TITLE
Case- and diacritics- insensitive filter for shortcuts

### ISSUE THREAD

**Issue by stdedos** [clsid2/mpc-hc#266]
I would expect that "Mute" (Σίγαση in Greek) would come by any of the following filtering strings:
* σι
* Σι
* σί

However, none of that works (only Σί)

**Comment by adipose** [comment]
How does this test build do?

https://mega.nz/#!gUgXBSaJ!pjjslDdcwQPrhK9RApEsepHDx55XI0o7uVqKkZgH7hA

**Comment by stdedos** [comment]
I am pretty sure that I have had a comment added. Was that removed?

**Comment by adipose** [comment]
I didn't get any notification that you added one, which I would have, if you posted it.  Maybe forgot to click "comment"?

**Comment by stdedos** [comment]
It doesn't fully work:

* σι
![image](https://user-images.githubusercontent.com/133706/74106739-c6633700-4b71-11ea-90ab-8d01dee28bda.png)
* Σι
![image](https://user-images.githubusercontent.com/133706/74106744-cd8a4500-4b71-11ea-8635-6760411a4632.png)
* σί
![image](https://user-images.githubusercontent.com/133706/74106746-d549e980-4b71-11ea-8178-37cc09b8bcf7.png)
* Σί
![image](https://user-images.githubusercontent.com/133706/74106756-e09d1500-4b71-11ea-9e61-5cfca3bbf20d.png)

**Comment by adipose** [comment]
Another test build: https://mega.nz/#!RAI1HSxQ!ASbCd20bqQHOo63wFLYSQj6fsykz33gLF_8635rCU9o

The lower casing was not working for other locales, but I think I have fixed that.

**Comment by stdedos** [comment]
Yep, now it works 👍
