### ISSUE TITLE
2 minor bugs

### ISSUE THREAD

**Issue by Rikk** [clsid2/mpc-hc#2660]
Since 2.1.5:
Cc @adipose
* Empty column after Value column:
![empty-column](https://github.com/clsid2/mpc-hc/assets/2916485/fe4529b2-02af-4eec-9cd8-84ecbae88038)

Since 2.1.7:
* Section [PlaylistHistory] is added to config (ini) even when history is disabled. Doesn't happen on 2.1.6.

**Comment by clsid2** [comment]
The empty column was added to fix a weird resizing issue.

PlaylistHistory bug should be fixed now.
