### ISSUE TITLE
External Filters No Longer Work

### ISSUE THREAD

**Issue by USSWashington** [clsid2/mpc-hc#2662]
I am no longer able to add external filters, I used to be able to add LAV (Splitter/Splitter Source, Audio, and Video) filters and set them to prefer. After the latest update -Mar 11th- the filters are gone, and I am not able to add them back.
![image](https://github.com/clsid2/mpc-hc/assets/75540320/c34d09fe-2056-4e91-985f-ef294cb326d3)
Also, the filter menu has been reduced drastically, I used to be able to see a lot more filters than what is available right now.

**Comment by clsid2** [comment]
Already fixed in 2.1.7.2

Adding LAV Filters is pointless anyway. MPC-HC comes bundled with the very latest LAV Filters.

**Comment by USSWashington** [comment]
Thank you!
