### ISSUE TITLE
Subtitle: ttml/stpp  support

### ISSUE THREAD

**Issue by 3052** [clsid2/mpc-hc#2665]
I have the below file, the subtitles are not recognized by MPC-HC

~~~
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'out.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.16.100
  Duration: 01:38:48.75, start: 0.000000, bitrate: 3957 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(progressive), 1200x720 [SAR 1:1 DAR 5:3], 3822 kb/s, 24 fps, 24 tbr, 19200 tbn (default)
    Metadata:
      handler_name    : USP Video Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
  Stream #0:1[0x2](zho): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : USP Sound Handler
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](eng): Subtitle: ttml (stpp / 0x70707473), 1 kb/s (default)
    Metadata:
      handler_name    : USP Subtitle Handler
~~~

**Comment by clsid2** [comment]
Unsupported format.

**Comment by 3052** [comment]
as a workaround, seems to be supported by VLC:

https://videolan.org

**Comment by 3052** [comment]
yeah, seems like support for TTML is pretty crappy at this time, missing from FFmpeg and MPV. as a workaround, it seems WebVTT is pretty common with better support:

- https://ffmpeg.org/ffmpeg-all.html#Subtitle-Formats
- https://wikipedia.org/wiki/WebVTT

**Comment by clsid2** [comment]
If you are creating subtitles yourself, then just use SRT.

**Comment by 3052** [comment]
no. WebVTT is standardized:

https://www.w3.org/TR/webvtt1/

and used by public sites such as:

https://www.amcplus.com
https://www.paramountplus.com/
https://www.peacocktv.com/

SRT is not standardized

**Comment by clsid2** [comment]
If you want something that is properly supported by players use SRT or ASS.

If you want to be stupid and stubborn, go use W3 and ISO standards used by media companies that players do not give a fuck about.
