### ISSUE TITLE
updated Polish language for mpc hc 2.1.6

### ISSUE THREAD

**Issue by Lukjan41** [clsid2/mpc-hc#2666]
I am sending updated Polish language for mpc hc 2.1.6, please add to newer versions,
[polish update.zip](https://github.com/clsid2/mpc-hc/files/14584277/polish.update.zip)

**Comment by clsid2** [comment]
Translations are done using Transifex:
https://github.com/clsid2/mpc-hc/issues/215

**Comment by Lukjan41** [comment]
Please accept me as a Polish translator, ljanik28,
