### ISSUE TITLE
Request shortcut key to open file location

### ISSUE THREAD

**Issue by DRSDavidSoft** [clsid2/mpc-hc#267]
Hi there,

Is it possible to add a shortcut key that acts the same way as double-clicking on Properties → Clip → File location? I believe it should call [`CPPageFileInfoClip::OnDoubleClickLocation()`](https://github.com/clsid2/mpc-hc/blob/d2d742e6104611a02a9fedb73af5e8faef464076/src/mpc-hc/PPageFileInfoClip.cpp#L185-L194), or maybe even directly `ExploreToFile(path)`.

Maybe a default value of `Ctrl+SHIFT+F10` can also be used for this Key entry.

Thank you for maintaining MPC-HC 😄

**Comment by clsid2** [comment]
Added

**Comment by DRSDavidSoft** [comment]
Thanks!
