### ISSUE TITLE
Version 2.1.7 External Filter "AviSynth Filter" gone ?

### ISSUE THREAD

**Issue by Joachim-Otahal** [clsid2/mpc-hc#2670]
I instantly noticed 'cause without it SVP does not kick in for the 120 fps conversion.
Back to 2.1.6: Works again, no change to config, just swap back the executables.
In 2.1.6 this is listed:
![image](https://github.com/clsid2/mpc-hc/assets/10100281/7e03a5c8-083c-4b25-97a0-4fea21277628)

missing in 2.1.7:
![image](https://github.com/clsid2/mpc-hc/assets/10100281/cbae1e3c-b900-4cb9-b55c-5e7c70590f1d)

The list in "Add Filter" in 2.1.6:
![image](https://github.com/clsid2/mpc-hc/assets/10100281/2c91ea90-16f5-4ffb-a578-b5e39febd6b0)

Which is a bit short in 2.1.7:
![image](https://github.com/clsid2/mpc-hc/assets/10100281/9071901c-a235-4731-8ead-c40c8f4a5760)

**Comment by clsid2** [comment]
Get 2.1.7.2
