### ISSUE TITLE
Saving playlist position not working when launching directly

### ISSUE THREAD

**Issue by nyakze** [clsid2/mpc-hc#2674]
Not sure if that is how it was intended in #2476 

**Scenario 1 (working) - triggering by playlist**:
1. Launch MPC-HC by double-clicking a playlist file or use Open File/URL inside MPC-HC;
2. Change an episode in the playlist;
3. Close player and repeat 1.
_Result_: SUCCESS the latest episode you were on is loaded.

**Scenario 2 (not working)** - triggering my MPC-HC:
1. Playlist was already loaded and remembered by MPC-HC (scenario 1);
2. Launch MPC-HC directly or via shortcut (default and preferred launching pattern by me);
3. Change an episode and close the player;
_Now let's say you went to watch something else, and MPC-HC has unloaded your playlist_
4. Launch MPC-HC by double-clicking that same playlist file or use Open File/URL inside MPC-HC.
_Result_: FAIL an episode, that you were last on when launching by scenario 1 is loaded, scenario 2 episode is not retained.

**Current workaround:**
Always launch MPC-HC via playlist.

**Did it work before:**
Untested, most likely not.

**Comment by clsid2** [comment]
Works fine for me.

**Comment by nyakze** [comment]
> Works fine for me.

That's very strange, I can reproduce it in 100% cases using the test method I've described above. The files in the playlists I tested all pointed to a remote locations though (http). That's fine, I'll just start mpc by triggering a playlist for now instead.

**Comment by clsid2** [comment]
Then you need to explain more clearly what you are doing.

If I launch a different file the playlist position is correctly updated when closing current playing file.

Upload your playlist file, then I can test with that.

You can see saved position in the Registry:
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\PlaylistHistory

**Comment by nyakze** [comment]
> Then you need to explain more clearly what you are doing.

I'll try a more detailed reproduction.

1. Double-click an m3u playlist;
2. Remember episode number you're on (you can change it from 1st, doesn't matter) and close MPC-HC;
3. Open MPC-HC directly from .exe or shortcut;
4. Make sure playlist is still loaded by pressing Ctrl+7 (open playlist);
5. Press Play;
6. Go to Next Episode;
7. Close MPC-HC;
8. Double-click an m3u playlist (same as in point 1)

**What should happen:**
Episode should be the same you were on when you closed MPC-HC on point 7.

**What happens:**
Playlist is on the episode you were on when you closed MPC-HC on point 2.



> Upload your playlist file, then I can test with that.

I'm sorry, the playlist point to files on my local network, they not gonna work for you.

**Comment by clsid2** [comment]
Now I understand.

When reopening the player the playlist (default.mpcpl) is not marked as external playlist that it was imported from.

**Comment by adipose** [comment]
I can believe this bug.  I suppose we could save the current Playlist path as a setting.

**Comment by NBruderman** [comment]
@adipose was this solved in https://github.com/clsid2/mpc-hc/pull/2812 ?

**Comment by adipose** [comment]
Yes, can close.
