### ISSUE TITLE
Cannot render certain MP4-files beginning from version 2.1.0

### ISSUE THREAD

**Issue by Plasma-Surge-Mayhem** [clsid2/mpc-hc#2675]
MPC-HC 2.1.0 and all later versions refuse to play certain 1920x1080 MP4-videos I shot with my Nokia 7 Plus phone back in 2018. I can see the error message "Cannot render the file" at the bottom of the player and nothing happens.
Later I changed the camera resolution to 3840x2160 and those videos play just fine (also from 2018).

MPC-HC 2.0.0 and all other media players I tried are able to render the files.

![kuva](https://github.com/clsid2/mpc-hc/assets/81039841/b2722031-fcc5-4007-af06-2e4d13155b84)

**Comment by NBruderman** [comment]
Can you provide a sample from the relevant video?

**Comment by clsid2** [comment]
You need to upload an example file.
https://www.sendspace.com (or some other file host)

**Comment by Plasma-Surge-Mayhem** [comment]
Here's a sample video:

https://www.sendspace.com/file/3sc5g2

**Comment by clsid2** [comment]
FFmpeg gives error that file uses an unsupported MP4 feature:
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000000000574040] explicit position is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
```
Explicit position is referring to speaker position metadata.

Problem started with this FFmpeg commit:
http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=d7e864366be2c4807d6d0796177051ad32c6378d

@nevcairiel
Anything you can do? Such as just ignore unsupported layouts in `mov_read_chnl()`.

**Comment by NBruderman** [comment]
Does the issue still occurs on the current updated ffmpeg branch?

**Comment by Nevcairiel** [comment]
Works fine for me with the latest version.

**Comment by NBruderman** [comment]
> Works fine for me with the latest version.

Latest version of MPCHC or ffmpeg? Because I think the ffmpeg fork is outdated by around... 5 months?

**Comment by clsid2** [comment]
Will be solved in next MPC-HC release.
