### ISSUE TITLE
Replay video in case of separated looped mp3 + mp4

### ISSUE THREAD

**Issue by BiosNod** [clsid2/mpc-hc#2676]
Hello, I have a 2 separated files: **test.mp4** (without any audio channel) and **test.mp3.** When I play test.mp4 MPC-HC will search separated audio and found it in test.mp3 and play both, but if mp3 have 60 sec duration and video have 10 sec duration - after 10 sec MPC-HC stop playing video and show the last video frame as a static image while mp3 still playing next 50 sec.

Is it possible to force MPC-HC replay video channel in case of audio channel has a large length than video (replay video until end of separated audio channel)? It will be very helpful for the looped musical videos where audio always have a different duration

**Comment by clsid2** [comment]
No.
