### ISSUE TITLE
Lack of top button during full screen playback, causing inconvenience

### ISSUE THREAD

**Issue by op200** [clsid2/mpc-hc#2678]
![Snipaste_2024-03-19_19-05-19](https://github.com/clsid2/mpc-hc/assets/112297583/055a0253-8ce2-486a-bc49-6735aab32af2)
When playing full screen on MPC-BE, there is a button at the top for one handed mouse operation, but I did not find this function in MPC-HC, which is necessary for one handed mouse operation

**Comment by clsid2** [comment]
You can double-click to exit fullscreen.

**Comment by op200** [comment]
> You can double-click to exit fullscreen.

Double clicking can indeed solve some problems, but it cannot solve everyone's needs
