### ISSUE TITLE
Subtitle Spacing -1

### ISSUE THREAD

**Issue by dmsa2** [clsid2/mpc-hc#2679]
I miss being able to place the spacing of the subtitle in -1, the subtitle was perfect, would it be able to have the option to leave the subtitle with -1?
I use the Arial Rounded MT source and in spacing -1 is perfect for me.

**Comment by clsid2** [comment]
@adipose
It seems that the control does not allow typing in `-` for negative value.

**Comment by dmsa2** [comment]
> @adipose It seems that the control does not allow typing in `-` for negative value.

Yes, that's right, however, a while ago it was allowed to put negative values. Would it be possible to return with this permission?

**Comment by adipose** [comment]
I changed it to be a floatedit so it prevented invalid chars.

https://github.com/clsid2/mpc-hc/blob/develop/src/mpc-hc/FloatEdit.cpp

Seems "-" needs to be added here.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2696
