### ISSUE TITLE
SVP Render Chain No Longer Supported by latest MPC-HC Build

### ISSUE THREAD

**Issue by InquisitorDavid** [clsid2/mpc-hc#2681]
Due to the changes to displaying External Filters, the latest build of MPC-HC no longer seems to support setups like for Smooth Video Project due to not allowing the FFDshow Raw Video Filter or AVSF to allow passthrough of the decoded video for processing. 

What options do we have to continue using MPC-HC with this setup?

**Comment by clsid2** [comment]
Get 2.1.7.2
