### ISSUE TITLE
"Save image" doesn't include the subtitles.

### ISSUE THREAD

**Issue by TheArgentinian** [clsid2/mpc-hc#2682]
Pause a video and take a screenshot (Alt + i). If you have subtitles enabled, they are not included in the image.

This wasn't the case in previous versions.

**Comment by clsid2** [comment]
PGS subtitles? Because that is only thing for which there have been a change recently.

**Comment by TheArgentinian** [comment]
> PGS subtitles? Because that is only thing for which there have been a change recently.

Embedded subrip. UTF-8

**Comment by clsid2** [comment]
Working fine for me.
There is a checkbox for including subtitles in the SaveImage dialog.

If you are using MadVR, then you can configure screenshot settings in MadVR options.
