### ISSUE TITLE
Can't use ffdshow RAW Audio Processor some time after v2.0.0.16

### ISSUE THREAD

**Issue by ludovids** [clsid2/mpc-hc#2688]
Updating K-Lite Codec Pack 17.4.5 to 18.2.0 broke ffdshow RAW Audio Processor for my use. This updated MPC-HC 2.0.0.16 to 2.1.7.0. Reverting back to earlier version of K-Lite fixed the problem.

I saw a commit comment in a newer release of MPC-HC mention something about fixing a bug related to External Filters settings. If I remember correctly, a "return false" statement was added. So I think there may still be a related bug that is causing the problem I saw.

FYI: I am using ffdshow RAW Audio Processor to convert DTS-HD, EAC3, and Dolby TrueHD to AC3, so I can send the audio from my nVidia 3080 to my A/V receiver via S/PDIF optical. The TV and 3080 have HDMI 2.1 ports, but the A/V receiver has HDMI 1.3. It appears that the nVidia/Win10 HDMI audio driver does not support HDMI 1.3, at least not when another port is connected to an HDMI 2.1 component, as with my 3080 to TV connection. Hence the need to use S/PDIF for the audio. For the second HDMI connection from the 3080, I used a DP 1.4 to HDMI 2.1 Adapter.

**Comment by clsid2** [comment]
Update to 18.2.4

**Comment by ludovids** [comment]
Updating to K-Lite Codec Pack 18.2.4 did not fix the problem for me. I did so before submitting this bug report, but forgot that detail somehow.

**Comment by clsid2** [comment]
Re-add it as a preferred external filter

**Comment by ludovids** [comment]
I tried that, but did not help. Think I tried "preferred", but not sure. Would that make a difference if there aren't any other external filters?
