### ISSUE TITLE
Pauses on some MKV files.

### ISSUE THREAD

**Issue by Hueristic** [clsid2/mpc-hc#2690]
Pauses every few seconds on random mkv files.
PM me if you want a sample file.

**Comment by clsid2** [comment]
Not a bug in the player.

**Comment by Hueristic** [comment]
Why does it not happen in vlc p,layer?

**Comment by clsid2** [comment]
How the hell should I know what is wrong with your system? You have provided zero information.

Tell me your CPU and GPU. Which audio and video renderer you have selected. MediaInfo of the files that gives the problem.

**Comment by clsid2** [comment]
And if you manually installed LAV Filters 0.79 and forced that as external filters, then that is the cause.
