### ISSUE TITLE
HDR content

### ISSUE THREAD

**Issue by ags1234** [clsid2/mpc-hc#2695]
MPC-HC does not correctly show colors in HDR movies with the included LAV filters.
But even though MPC-BE is about 10 MiB smaller in size on disk, the same movie shows correctly.
Both with the default settings, no other codecs installed in the system.

**Comment by NBruderman** [comment]
Switch the video renderes to MPCVR or MadVR to watch HDR content. HDR content works fine with either of those, and MPCVR also supports Dolby Vision content

**Comment by ags1234** [comment]
@NBruderman
Hey, thanks! I switched to MPC video renderer and the movie looks good.
I like MPC-HC. It also has subtitle download, which MPC-BE does not have.

**Comment by NBruderman** [comment]
No problems! Glad it works fine now. I would also suggest switching in LAV the hardware decoder to D3D11 for optimal experience with MPCVR

**Comment by ags1234** [comment]
Actually, I still have a problem.
I was using both players decompressed from zip archive. In that version I switched MPC-HC to MPC VR and it worked.
Then I downloaded MPC-HC.2.1.7.2.x86.exe and installed it. And after switching to MPC VR, when playing video I see this warning:

![2024-03-30_152027](https://github.com/clsid2/mpc-hc/assets/21011513/ed23b549-a966-4161-8e43-73ea40759fd1)

**Comment by NBruderman** [comment]
Remove the player and everything related and just install the K-lite codec package, and update it through their releases. It contains everything you need (including MPCVR), and gets updates frequently
________________________________

**Comment by ags1234** [comment]
Okay, thanks.
But the problem still remains: MPC-HC should be able to play HDR content out of the box.
Why is MPC VR not included and enabled by default in MPC-HC if it is more capable?

**Comment by NBruderman** [comment]
It does if it's installed via K-lite.
MPCVR is not included in vanilla MPC HC, so it can't be picked by default.
Why isn't it being included? You'll have to ask the developer.

________________________________
