### ISSUE TITLE
little space for text, in the new test version

### ISSUE THREAD

**Issue by Lukjan41** [clsid2/mpc-hc#2697]
in the new test version, there is no space for Polish text, marked in red
![setting](https://github.com/clsid2/mpc-hc/assets/163265642/5d6492bd-72d9-4cbe-8b9d-1dd96096249a)
I am a translator into Polish, nick ljanik28

**Comment by adipose** [comment]
Would it fit if it went to the border?

**Comment by Lukjan41** [comment]
yes, you need to increase the text space

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2699

Looks ok now.

Btw it only seemed to affect classic theme.  Maybe the theming does some smart resizing.

**Comment by Lukjan41** [comment]
Will it be fixed in the new test version?

**Comment by clsid2** [comment]
Stop asking such questions. Builds are available when then become available, and I do NOT care all about minor translation issues.

**Comment by Lukjan41** [comment]
good

**Comment by Lukjan41** [comment]
@adipose pleasse fix
![1](https://github.com/clsid2/mpc-hc/assets/163265642/a7484dda-3b2e-4fd2-8efe-22a12c1bb5ad)

**Comment by adipose** [comment]
> @adipose pleasse fix 

Will take a look.

**Comment by Lukjan41** [comment]
thank

**Comment by adipose** [comment]
I simply don't have enough space.  In Chinese traditional the opposite problem is the case.

![image](https://github.com/clsid2/mpc-hc/assets/3324395/d7319cb4-6659-47af-95c7-1e0b75633f52)

**Comment by adipose** [comment]
I added a patch for dynamic layouts which solves the problem for Polish and Chinese.  It should make translations easier to fit in the future without manual changes.

https://github.com/clsid2/mpc-hc/pull/2717

**Comment by Lukjan41** [comment]
ok, thank

**Comment by Lukjan41** [comment]
@adipose pleasse fix
![1](https://github.com/clsid2/mpc-hc/assets/163265642/8f709979-8354-44fe-9f33-32dab1709d26)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2727

I should mention, it's perhaps a mistake to translate "MPC Audio Renderer."  That's kind of a "brand" name and not a description.  SaneAR is also an MPC audio renderer, and translating it may cause confusion about what MPCAR really is (as if it's the "official" way to render audio, which it is not).

For example, in Russian it is done like this (not all translations follow suit, though):

![image](https://github.com/clsid2/mpc-hc/assets/3324395/e705c9f5-08f0-4648-b2cd-5cf54c050cf5)

@clsid2, what do you think about renaming this to "MPCAR" for buttons, etc.?

**Comment by clsid2** [comment]
"MPCAR" abbreviation might confuse people who don't know it very well.

But I agree that names of filters should preferably not be translated.

**Comment by Lukjan41** [comment]
thank

**Comment by Lukjan41** [comment]
@adipose pleasse fix
![Bez tytułu](https://github.com/clsid2/mpc-hc/assets/163265642/b798c7bf-d539-4333-abfa-0944290bdc87)

**Comment by adipose** [comment]
Hi.  Please don't add new requests to old closed tickets.  I get a notification but it is hard for me to find later.

Enter a new request.  It can have multiple GUI issues to address.
