### ISSUE TITLE
Player -> Key - filtering(with different case) working only for English.

### ISSUE THREAD

**Issue by Aleksoid1978** [clsid2/mpc-hc#270]
CString::MakeLower() working only for English texts.
Solution - use CharLowerBuffW().

**Comment by clsid2** [comment]
@adipose

**Comment by adipose** [comment]
@Aleksoid1978 

This build uses the locale of the ui language (another bug submitted similar to yours):

https://mega.nz/#!RAI1HSxQ!ASbCd20bqQHOo63wFLYSQj6fsykz33gLF_8635rCU9o

If this is working, we can close this issue.

**Comment by Aleksoid1978** [comment]
Working good.
