### ISSUE TITLE
subtitles moving up above the time bar

### ISSUE THREAD

**Issue by Lukjan41** [clsid2/mpc-hc#2705]
Is it possible to change the subtitles to move up when the time bar is?
![sub](https://github.com/clsid2/mpc-hc/assets/163265642/2c3e3cda-9384-43b5-9bef-4a68f89680d8)
If it can't be done, then no.

**Comment by clsid2** [comment]
Reset settings. The problem is 99% sure user error.

**Comment by Lukjan41** [comment]
@adipose is it possible to change it so that the subtitles appear above the time bar when the time bar appears when you hover your mouse over it?
