### ISSUE TITLE
Color Correction

### ISSUE THREAD

**Issue by Mortycio** [clsid2/mpc-hc#2706]
Well, I don't even need to explain the problem... it's clearly visible from the attached screenshot. Why is the image completely different with the MPC-HC program? I don't like it, I want the colors of the Windows player but without giving up your program since it's the only one that allows me to zoom on my 32:9 monitor.

EDIT: Although I still prefer the colors of the official Windows program, I noticed that some scenes are completely off like in the third image... I have no idea why. So, I'll try to get used to the colors of MPC-HC since it doesn't have the issues of the Windows media player.

P.S. Without having to disable HDR settings, is there a way to simply tone down the colors? I think it's all about the blacks.

![hp](https://github.com/clsid2/mpc-hc/assets/113641947/a1b3db1b-d919-4bee-9554-39a082754e55)
![opp1](https://github.com/clsid2/mpc-hc/assets/113641947/53de3c66-cb89-42bf-be8f-18b708a55192)
![opp2](https://github.com/clsid2/mpc-hc/assets/113641947/5b51874e-afe4-4d15-8a4d-7f19db898673)

**Comment by NBruderman** [comment]
Link doesn't work. However, it's probably a HDR video. Switch to MPC video rendered (or MadVR) and the colors will be fine.

Btw, reading the readme of the repository, or installing it via K-lite codec pack, would've probably be a quicker way to find the fix.

**Comment by adipose** [comment]
@clsid2 

Maybe a sticky for HDR / color correction. It comes up often.

**Comment by clsid2** [comment]
HDR is mentioned in the readme and release notes already.

There can only be two stickies.

**Comment by Mortycio** [comment]
(I updated the post adding some additional information, with the attachments uploaded correctly, and with a new request)

**Comment by clsid2** [comment]
If the video is HDR then you need to use either MPC Video Renderer or Madvr.
MPC-HC options > Playback > Output

If the video is not HDR, but HDR is enabled by default in Windows, then use the HDR Calibration Tool to improve colors. You can find it in Window Store.

**Comment by Mortycio** [comment]
> If the video is HDR then you need to use either MPC Video Renderer or Madvr. MPC-HC options > Playback > Output
> 
> If the video is not HDR, but HDR is enabled by default in Windows, then use the HDR Calibration Tool to improve colors. You can find it in Window Store.

I'm already using MPC Video Renderer output, and HDR is already enabled and calibrated in Windows settings. Unfortunately, I can't fix just the blacks, since the rest of the colors are fine... they're just a bit too dark, as if there's too much contrast, you know (I'm not an expert in these things). 
If there's no way to fix it, then we can close the post, and I thank you in advance.

**Comment by NBruderman** [comment]
> > If the video is HDR then you need to use either MPC Video Renderer or Madvr. MPC-HC options > Playback > Output
> > 
> > If the video is not HDR, but HDR is enabled by default in Windows, then use the HDR Calibration Tool to improve colors. You can find it in Window Store.
> 
> I'm already using MPC Video Renderer output, and HDR is already enabled and calibrated in Windows settings. Unfortunately, I can't fix just the blacks, since the rest of the colors are fine... they're just a bit too dark, as if there's too much contrast, you know (I'm not an expert in these things). 
> If there's no way to fix it, then we can close the post, and I thank you in advance.

I mean, you can also try MadVR, which has a bunch of tuning settings... But I can't promise anything

**Comment by clsid2** [comment]
Is your monitor HDR? Because otherwise it does not make sense to enable HDR in Windows.

If MPC Video Renderer does HDR passthrough, then your monitor is doing the color tonemapping. Check if your monitor provides any settings to adjust how it does that.
Otherwise disable passthrough to let the renderer do tonemapping.

Madvr has more advanced tonemapping settings. It for example has a "target nits" setting that has an effect on the brightness.

**Comment by Mortycio** [comment]
> Is your monitor HDR? Because otherwise it does not make sense to enable HDR in Windows.
> 
> If MPC Video Renderer does HDR passthrough, then your monitor is doing the color tonemapping. Check if your monitor provides any settings to adjust how it does that. Otherwise disable passthrough to let the renderer do tonemapping.
> 
> Madvr has more advanced tonemapping settings. It for example has a "target nits" setting that has an effect on the brightness.

I think so... it's the Samsung Odyssey OLED G9 (S49CG934).. I'll try with the madVR and I'll let you know.

**Comment by Mortycio** [comment]
I tried madVR, and it doesn't seem to change much... there's no setting that allows me to adjust the contrast or brightness. Moreover, now the movie is stuttering in some scenes, and for everything else, it seems to run with low FPS.

**Comment by adipose** [comment]
> I tried madVR, and it doesn't seem to change much... there's no setting that allows me to adjust the contrast or brightness. Moreover, now the movie is stuttering in some scenes, and for everything else, it seems to run with low FPS.

S49CG934 has HDR tone mapping.  Report back whether that's currently enabled.

https://www.displayspecifications.com/en/model/d196344a

**Comment by Mortycio** [comment]
> > I tried madVR, and it doesn't seem to change much... there's no setting that allows me to adjust the contrast or brightness. Moreover, now the movie is stuttering in some scenes, and for everything else, it seems to run with low FPS.
> 
> S49CG934 has HDR tone mapping. Report back whether that's currently enabled.
> 
> https://www.displayspecifications.com/en/model/d196344a

Yep
![Screenshot 2024-04-03 201841](https://github.com/clsid2/mpc-hc/assets/113641947/a20b074b-c9dc-4cfe-99f9-a57d8c1d033f)

**Comment by adipose** [comment]
I'm talking about on the monitor itself.  Something like this:

https://us.community.samsung.com/t5/QLED-and-The-Frame/75-quot-Samsung-QN90C-TV-Tone-Mapping-is-completely-grayed-out/td-p/2702203?lightbox-message-images-2702209=1097449i86E54BE258B84B92

**Comment by adipose** [comment]
In the manual it has the setting under Picture.

![image](https://github.com/clsid2/mpc-hc/assets/3324395/7f5a0e2f-8bfa-4bae-9738-3c3444efe412)

![image](https://github.com/clsid2/mpc-hc/assets/3324395/a50c77d9-6272-4242-a6b1-47fea262c15e)

**Comment by Mortycio** [comment]
> I'm talking about on the monitor itself. Something like this:
> 
> https://us.community.samsung.com/t5/QLED-and-The-Frame/75-quot-Samsung-QN90C-TV-Tone-Mapping-is-completely-grayed-out/td-p/2702203?lightbox-message-images-2702209=1097449i86E54BE258B84B92

Oh, yes it's enabled

**Comment by adipose** [comment]
https://screenresolutiontest.com/tone-mapping/

Your monitor seems to have a brightness of 1000 nits.  Can you share a video file that is causing the problem?

**Comment by Mortycio** [comment]
> https://screenresolutiontest.com/tone-mapping/
> 
> Your monitor seems to have a brightness of 1000 nits. Can you share a video file that is causing the problem?

Actually, I'm not having any 'problem'. I just wanted to know if there is a way, a filter, or a shader that reduces the contrast (or the blacks) in order to make the colors a bit more similar to those shown using Windows 'Movies & TV'.

**Comment by adipose** [comment]
> Actually, I'm not having any 'problem'. I just wanted to know if there is a way, a filter, or a shader that reduces the contrast (or the blacks) in order to make the colors a bit more similar to those shown using Windows 'Movies & TV'.

If you use EVR-CP does it look the same as Windows 'Movies & TV'?

**Comment by adipose** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/3324395/18f8c530-43b5-47b1-975e-2f617e5391c3)

**Comment by Mortycio** [comment]
> > Actually, I'm not having any 'problem'. I just wanted to know if there is a way, a filter, or a shader that reduces the contrast (or the blacks) in order to make the colors a bit more similar to those shown using Windows 'Movies & TV'.
> 
> If you use EVR-CP does it look the same as Windows 'Movies & TV'?



> > Actually, I'm not having any 'problem'. I just wanted to know if there is a way, a filter, or a shader that reduces the contrast (or the blacks) in order to make the colors a bit more similar to those shown using Windows 'Movies & TV'.
> 
> If you use EVR-CP does it look the same as Windows 'Movies & TV'?

With EVR-CP, on the contrary, there's too little contrast. But I believe I've still solved the issue, and now madVR is similar (if not the same) as Windows 'Movies & TV'.

P.S. I tinkered with video settings and HDR settings on my monitor, NVIDIA control panel, and Windows for a couple of hours. Now, looking back at the screenshots attached to the first post where I showed the differences between the two programs, I can clearly see that the quality and colors of Windows 'Movies & TV' were definitely inferior to your program.. so yeah, the issue wasn't with the program but with the color and HDR settings of all three components listed above.
And to think that until now I had all these settings messed up... and who knows if they're right now! Anyway, thanks to everyone for your patience and availability.
