### ISSUE TITLE
Playlist focus prevents hotkeys

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#2709]
```
BOOL CPlayerPlaylistBar::PreTranslateMessage(MSG* pMsg)
{
    if (IsWindow(pMsg->hwnd) && IsVisible() && pMsg->message >= WM_KEYFIRST && pMsg->message <= WM_KEYLAST) {
        if (IsDialogMessage(pMsg)) {
            return TRUE;
        }
    }

    return __super::PreTranslateMessage(pMsg);
}
```

Thanks to the `IsDialogMessage`, shortcut keys don't work when playlist has focus.  I never noticed this before, so it's probably not a big deal.  I thought I'd mention it in case it wasn't ideal.

**Comment by clsid2** [comment]
I think that is for stuff like `Del` which have it own handling in playlist versus in player.

**Comment by NBruderman** [comment]
Is there a way to identify commands with different handling for different window (like `Del`) from commands that behave the same everywhere, like shuffle?

**Comment by adipose** [comment]
> I think that is for stuff like `Del` which have it own handling in playlist versus in player.

https://stackoverflow.com/questions/4387863/question-about-isdialogmessage-in-win32

Tabbing between controls in a dialog supposedly is another reason.

**Comment by clsid2** [comment]
Perhaps redirect unhandled key events back to main window?

**Comment by adipose** [comment]
> Is there a way to identify commands with different handling for different window (like `Del`) from commands that behave the same everywhere, like shuffle?

IsDialogMesssge filters everything it needs to enable dialog behavior.  But it traps things like ctrl and I think that interferes with hotkeys.

Possibly we could prefilter some messages, and as long as the desired behavior doesn't change, it would be acceptable.

**Comment by adipose** [comment]
> Perhaps redirect unhandled key events back to main window?

Problem is IsDialogMesssge actually processes the event.  Not sure but maybe just we don't return TRUE and it might work...

**Comment by clsid2** [comment]
Keys presses seem to get processed by `PlayerPlaylistBar::OnLvnKeyDown`

Only issue is that Ctrl/Alt/Shift are also triggering keypress. So that will complicate forwarding a combination of keypresses.

Maybe ignore the modifiers. Forward other unhandled keys to a function that checks if any modifiers are currently pressed, and then process that combination in mainframe?

**Comment by adipose** [comment]
Below is code from https://github.com/wine-mirror/wine/blob/master/dlls/user32/dialog.c

It may be useful in understanding it.  There is a portion that checks if it's an accelerator.  Perhaps...we could check if the parent window has a registered accelerator and filter that out.

```
BOOL WINAPI IsDialogMessageW( HWND hwndDlg, LPMSG msg )
{
    INT dlgCode;

    if (!IsWindow( hwndDlg ))
        return FALSE;

    if (NtUserCallMsgFilter( msg, MSGF_DIALOGBOX )) return TRUE;

    hwndDlg = WIN_GetFullHandle( hwndDlg );
    if (is_desktop_window(hwndDlg)) return FALSE;
    if ((hwndDlg != msg->hwnd) && !IsChild( hwndDlg, msg->hwnd )) return FALSE;

    hwndDlg = DIALOG_FindMsgDestination(hwndDlg);

    switch(msg->message)
    {
    case WM_KEYDOWN:
        dlgCode = SendMessageW( msg->hwnd, WM_GETDLGCODE, msg->wParam, (LPARAM)msg );
        if (dlgCode & (DLGC_WANTMESSAGE)) break;

        switch(msg->wParam)
        {
        case VK_TAB:
            if (!(dlgCode & DLGC_WANTTAB))
            {
                BOOL fIsDialog = !WIN_IsCurrentProcess( hwndDlg ) ||
                    NtUserGetDialogInfo( hwndDlg ) != NULL;

                /* I am not sure under which circumstances the TAB is handled
                 * each way.  All I do know is that it does not always simply
                 * send WM_NEXTDLGCTL.  (Personally I have never yet seen it
                 * do so but I presume someone has)
                 */
                if (fIsDialog)
                    SendMessageW( hwndDlg, WM_NEXTDLGCTL, (NtUserGetKeyState(VK_SHIFT) & 0x8000), 0 );
                else
                {
                    /* It would appear that GetNextDlgTabItem can handle being
                     * passed hwndDlg rather than NULL but that is undocumented
                     * so let's do it properly
                     */
                    HWND hwndFocus = GetFocus();
                    HWND hwndNext = GetNextDlgTabItem (hwndDlg,
                            hwndFocus == hwndDlg ? NULL : hwndFocus,
                            NtUserGetKeyState (VK_SHIFT) & 0x8000);
                    if (hwndNext)
                    {
                        dlgCode = SendMessageW (hwndNext, WM_GETDLGCODE,
                                msg->wParam, (LPARAM)msg);
                        if (dlgCode & DLGC_HASSETSEL)
                        {
                            INT maxlen = 1 + SendMessageW (hwndNext, WM_GETTEXTLENGTH, 0, 0);
                            WCHAR *buffer = HeapAlloc (GetProcessHeap(), 0, maxlen * sizeof(WCHAR));
                            if (buffer)
                            {
                                INT length;
                                SendMessageW (hwndNext, WM_GETTEXT, maxlen, (LPARAM) buffer);
                                length = lstrlenW (buffer);
                                HeapFree (GetProcessHeap(), 0, buffer);
                                SendMessageW (hwndNext, EM_SETSEL, 0, length);
                            }
                        }
                        NtUserSetFocus( hwndNext );
                        DIALOG_FixChildrenOnChangeFocus (hwndDlg, hwndNext);
                    }
                    else
                        return FALSE;
                }
                return TRUE;
            }
            break;

        case VK_RIGHT:
        case VK_DOWN:
        case VK_LEFT:
        case VK_UP:
            if (!(dlgCode & DLGC_WANTARROWS))
            {
                BOOL fPrevious = (msg->wParam == VK_LEFT || msg->wParam == VK_UP);
                HWND hwndNext = GetNextDlgGroupItem( hwndDlg, msg->hwnd, fPrevious );
                if (hwndNext && SendMessageW( hwndNext, WM_GETDLGCODE, msg->wParam, (LPARAM)msg ) == (DLGC_BUTTON | DLGC_RADIOBUTTON))
                {
                    NtUserSetFocus( hwndNext );
                    if ((GetWindowLongW( hwndNext, GWL_STYLE ) & BS_TYPEMASK) == BS_AUTORADIOBUTTON &&
                        SendMessageW( hwndNext, BM_GETCHECK, 0, 0 ) != BST_CHECKED)
                        SendMessageW( hwndNext, BM_CLICK, 1, 0 );
                }
                else
                    SendMessageW( hwndDlg, WM_NEXTDLGCTL, (WPARAM)hwndNext, 1 );
                return TRUE;
            }
            break;

        case VK_CANCEL:
        case VK_ESCAPE:
            SendMessageW( hwndDlg, WM_COMMAND, IDCANCEL, (LPARAM)GetDlgItem( hwndDlg, IDCANCEL ) );
            return TRUE;

        case VK_EXECUTE:
        case VK_RETURN:
            {
                DWORD dw;
                HWND hwndFocus = GetFocus();
                if (IsChild( hwndDlg, hwndFocus ) &&
                    (SendMessageW( hwndFocus, WM_GETDLGCODE, 0, 0 ) & DLGC_DEFPUSHBUTTON))
                {
                    SendMessageW( hwndDlg, WM_COMMAND, MAKEWPARAM( GetDlgCtrlID( hwndFocus ), BN_CLICKED ), (LPARAM)hwndFocus );
                }
                else if (DC_HASDEFID == HIWORD(dw = SendMessageW (hwndDlg, DM_GETDEFID, 0, 0)))
                {
                    HWND hwndDef = DIALOG_IdToHwnd(hwndDlg, LOWORD(dw));
                    if (!hwndDef || IsWindowEnabled(hwndDef))
                        SendMessageW( hwndDlg, WM_COMMAND, MAKEWPARAM( LOWORD(dw), BN_CLICKED ), (LPARAM)hwndDef);
                }
                else
                {
                    SendMessageW( hwndDlg, WM_COMMAND, IDOK, (LPARAM)GetDlgItem( hwndDlg, IDOK ) );
                }
            }
            return TRUE;
        }
        break;

    case WM_CHAR:
        /* FIXME Under what circumstances does WM_GETDLGCODE get sent?
         * It does NOT get sent in the test program I have
         */
        dlgCode = SendMessageW( msg->hwnd, WM_GETDLGCODE, msg->wParam, (LPARAM)msg );
        if (dlgCode & (DLGC_WANTCHARS|DLGC_WANTMESSAGE)) break;
        if (msg->wParam == '\t' && (dlgCode & DLGC_WANTTAB)) break;
        /* drop through */

    case WM_SYSCHAR:
        if (DIALOG_IsAccelerator( WIN_GetFullHandle(msg->hwnd), hwndDlg, msg->wParam ))
        {
            /* don't translate or dispatch */
            return TRUE;
        }
        break;
    }

    TranslateMessage( msg );
    DispatchMessageW( msg );
    return TRUE;
}
```

**Comment by adipose** [comment]
https://devblogs.microsoft.com/oldnewthing/20160818-00/?p=94115

Maybe this is the solution.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2713

So I have it check the parent accelerators which seems to be working correctly.  As there are no accelerators on the playlistbar, we don't need to check for that.  But all other keys are still falling through.

If a shortcut like "Del" exists, though, it probably causes problems.  Needs testing.

**Comment by clsid2** [comment]
Del is used for deleting current file. While in playlist window it only removes selected entries from playlist.

**Comment by adipose** [comment]
> Del is used for deleting current file. While in playlist window it only removes selected entries from playlist.

Yes, I confirmed it misbehaves currently.

**Comment by adipose** [comment]
I added code now to only check CTRL/SHIFT/ALT shortcuts.  That should avoid simple stuff getting lost, DEL for example.

**Comment by clsid2** [comment]
What about typing text, like changing a title. Does shift still work then for capital letter?

**Comment by adipose** [comment]
Good question.  I was just removing SHIFT because I wasn't sure about things like that.  I'll test.

**Comment by adipose** [comment]
It causes issues to do it with SHIFT.  Also CTRL+ has various edit keystrokes.  I've limited it to CTRL+ALT+key only now.

**Comment by adipose** [comment]
Maybe ALT+SHIFT is also ok.  ALT+key maybe also uncommon. So maybe just check for ALT and let it through?

**Comment by adipose** [comment]
ALT+menu shortcut still works as they are not trapped by `IsDialogMessage`. 

There is an existing "problem" that a shortcut conflicting with the top-menu accelerator overrides it (regardless of playlist focus).  But as that may be useful to some people, we can leave it alone.

**Comment by clsid2** [comment]
Ctrl itself is also used for text actions like copy and paste.

Not really sure if there is any proper solution.

**Comment by adipose** [comment]
> Ctrl itself is also used for text actions like copy and paste.
> 
> Not really sure if there is any proper solution.

What I did now is only allow shortcuts that involve the ALT key.  As far as I know, there's no problem that can be caused by that.  IsDialogMessage doesn't process ALT+char at all, that I can see.  This means ALT+SHIFT+x or ALT+CTRL+x or ALT+key would all be possible shortcuts.  As I mentioned, even today, ALT+V can be made a shortcut which messes up opening the View menu, but that's today's behavior whether focused on playlist or not.
