### ISSUE TITLE
Open DVD via Network, history not works.

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#2714]
For example, open a dvd via Open DVD/BD which located in `\\[host]\[share]\VIDEO_TS`, the entry in history will show `[host]\[share]\VIDEO_TS`.
Then close file and reopen. Got file not found error.
BDMV folder works well. Only DVD folder are effected.
![image](https://github.com/clsid2/mpc-hc/assets/41434272/d4313159-431c-42df-816b-18a7601eaa01)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2920
