### ISSUE TITLE
OpenSubtitles

### ISSUE THREAD

**Issue by Lackeinthestates** [clsid2/mpc-hc#2716]
MPC-HC  connecting to Opensubtitles.**_com_** instead of Opensubtitles.**_org_**
Can you let me know how to change it back?

**Comment by clsid2** [comment]
You can't.

**Comment by Lackeinthestates** [comment]
Thank you. I’ll swap program so I can use OpenSubtitles.org. appreciate all the hard work y’all done with the player. Hate to see it go. Thanks for you all continuing work to keep an excellent program going.Lacke WestmanOn 4/4/24 at 7:26 PM, clsid2 wrote:
                
            
            
                
                    From: "clsid2" ***@***.***>Date: April 4, 2024To: "clsid2/mpc-hc" ***@***.***>Cc: "Author" ***@***.***>,"Lackeinthestates" ***@***.***>Subject: Re: [clsid2/mpc-hc] OpenSubtitles (Issue #2716)
                
                
Closed #2716 as completed.
