### ISSUE TITLE
For the consistent

### ISSUE THREAD

**Issue by tsubasanouta** [clsid2/mpc-hc#2718]
![WS000006](https://github.com/clsid2/mpc-hc/assets/129067724/8859aac9-af2a-4c57-8c5c-ea5d9a838879)

**Comment by adipose** [comment]
` EDITTEXT        IDC_EDIT4,130,129,40,14,ES_CENTER | ES_AUTOHSCROLL | ES_NUMBER `

I think this needs to be changed to 42.

**Comment by tsubasanouta** [comment]
Could you change to 42 when you have time?

**Comment by adipose** [comment]
At some point.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2723
