### ISSUE TITLE
Subtitles are out of sync on Intel Graphic Cards

### ISSUE THREAD

**Issue by danielpc2013** [clsid2/mpc-hc#2719]
I've started using the player on a Surface Pro 9 (The i7 model that has an Intel Iris Xe graphics card) and noticed that the subtitles are out of sync and other players play them fine. I never had any of this issues on my other computers. When I changed the rendering settings to "Video Mixing Rendering 9 (renderless)" that fixed the issue but created other issues like a pink frame flashing at the start of the video.

**Comment by clsid2** [comment]
Use MPC Video Renderer. That uses DirectX 11.

New Intel drivers use d3d9on12 layer for DirectX9 which is buggy. So Intel fault, I can not fix it.
