### ISSUE TITLE
Consider having the dark theme as the default.

### ISSUE THREAD

**Issue by epigramx** [clsid2/mpc-hc#272]
It's pretty cool :-)

**Comment by adipose** [comment]
I noticed that K-lite is already making it the default in their installer.

I am pretty conservative, though, and don't want to "rock the boat" for those that are already happy with the classic theme (one might say, the source of the term "Classic" in the title of MPC-HC).  I personally think Windows Classic UI hasn't aged too well but I do prefer this application anyway.

If @clsid2 wants to make it the default, I'll be able to do it pretty easily.

**Comment by clsid2** [comment]
K-Lite also uses the W10 theme setting as default

**Comment by epigramx** [comment]
I mainly implied that most people may not notice it exists. I didn't notice it exists until last week and when I told another user he had no clue either. 
@clsid2 it's a great idea to turn it on by default for those that already use dark theme in windows 10 anyway (they will obviously want it anyway).

**Comment by clsid2** [comment]
It already defaults to dark theme when using the standard W10 dark theme.

**Comment by epigramx** [comment]
Yep, that's great, I consider this more than solved.
