### ISSUE TITLE
Normalize resets when skipping back

### ISSUE THREAD

**Issue by JNavas2** [clsid2/mpc-hc#2720]
With Normalize enabled with Max Amplification 400% and Regain Volume _not_ enabled, if I Skip Back (e.g., because I missed something), Normalize resets to Max, which can be unpleasant.
While I think it makes sense to reset when loading a _different_ file, I don't think it should reset when skipping in the _same_ file.
(I'd prefer not to lower Max Amplification because I have some files that need a higher value.)

Thank you for MPC-HC!

MPC-HC 2.2.0
OS Name	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045

<img width="577" alt="mpc-hc64_g67cIDHduQ" src="https://github.com/clsid2/mpc-hc/assets/14850792/b85a32d1-b9e3-4e27-b3d6-8f1ab660791d">

**Comment by clsid2** [comment]
Regain has NOTHING to do with this. It simply resets the algorithm on seek.

I need a good sample file to analyze problem. And timestamps to seek from and to.

**Comment by JNavas2** [comment]
Thank you.
I understand that Regain has nothing to do with my issue. I confirmed the setting for your information.
To make it as easy for you as possible I'll create a synthetic video file that reproduces the problem.
That might take me a couple of days due to my current heavy schedule.
When I have it, I'll update this Issue.

**Comment by NBruderman** [comment]
> Thank you.
> I understand that Regain has nothing to do with my issue. I confirmed the setting for your information.
> To make it as easy for you as possible I'll create a synthetic video file that reproduces the problem.
> That might take me a couple of days due to my current heavy schedule.
> When I have it, I'll update this Issue.

@JNavas2 any news regarding the sample file?

**Comment by JNavas2** [comment]
Thanks for the reminder.
Attached is a public domain audio file that demonstrates the problem here.
I'm listening with Sony WF-1000XM4 earbuds over Bluetooth.
When I start playing with the audio quite loud, the volume gets automatically reduced as I play it.
Then if I jump back with the left arrow or to near the beginning from near the end,
the audio is suddenly as loud again as when I started playing.
[gettysburg_johng_librivox.zip](https://github.com/clsid2/mpc-hc/files/15477261/gettysburg_johng_librivox.zip)

<img width="577" alt="mpc-hc64_WpmYSlDYQM" src="https://github.com/clsid2/mpc-hc/assets/14850792/e8eb4d86-b170-4f89-9b36-05aff9826dc3">

**Comment by clsid2** [comment]
Try 2.2.1.48

**Comment by JNavas2** [comment]
Unfortunately, the problem is **not** fixed.
I was watching a long video in 2.2.1.48, and jumped back to review something, and the audio was much louder.

**Comment by clsid2** [comment]
I am unable to reproduce the problem with the given sample. Give timestamp from where you seek and where to.

**Comment by NBruderman** [comment]
> Unfortunately, the problem is **not** fixed.
> I was watching a long video in 2.2.1.48, and jumped back to review something, and the audio was much louder.

How did you jump back? With the arrow keys, or with the mouse? Because in the original issue it refers to the arrow keys, the behavior might be different with a large skip with the mouse on the timeline

**Comment by clsid2** [comment]
That does not matter. A seek is a seek.

**Comment by JNavas2** [comment]
@NBruderman 
> How did you jump back? With the arrow keys, or with the mouse?

I usually jump back with the left arrow key, but I also see the issue when I jump back with a mouse.


@clsid2 
> I am unable to reproduce the problem with the given sample. Give timestamp from where you seek and where to.

Last night when I was about halfway through watching an episode of Beacon 23 (TV series) in MPC-HC 2.2.1.48 (on Windows 10) using Sony WF-1000XM4 Bluetooth earphones, I pressed the left arrow key to jump back and replay something interesting, and the volume jumped up roughly 6 dB. As I continued listening, the volume went back down to what it had been before I jumped back.

How about giving me a build that logs any changes to audio gain? That might nail down the issue.

**Comment by JNavas2** [comment]
I reproduced the problem as described in my last Comment, this time recording the audio output with Audacity, which is attached to this Comment. Halfway through the clip (which is trimmed from the end of a much longer recording) I used the left arrow to jump back for replay. Note how much louder the replay is compared to the first time through.
[sample.zip](https://github.com/user-attachments/files/15525938/sample.zip)

**Comment by JNavas2** [comment]
p.s. Here is an audio only file that reproduces the problem for me, matching the sample in my last Comment when I press the left arrow to jump back.
UPDATE: Play from the beginning with my audio settings, press left arrow at about 2:15. _(The time scale is not correct.)_
[Beacon 23 S02E05.zip](https://github.com/user-attachments/files/15526372/Beacon.23.S02E05.zip)

**Comment by JNavas2** [comment]
**ADDITIONAL INFO**: I do **not** see this audio gain problem when playing through the laptop speakers, just when playing through my Sony WF-1000XM4 Bluetooth earphones.

**Comment by JNavas2** [comment]
Is there anything more I could do to help on this?

**Comment by clsid2** [comment]
It should be fixed in latest build, and if not you are out of luck, because I am not going to make any further changes.

**Comment by JNavas2** [comment]
> It should be fixed in latest build, and if not you are out of luck, because I am not going to make any further changes.

I assume you're referring to development build 2.2.1.72, but I didn't see download links.

**Comment by clsid2** [comment]
click on "assets" to expand download links

**Comment by JNavas2** [comment]
Thanks. 
On my sample, 2.2.1.72 till jumps up, but only about 7dB.
On a previous version it had jumped up about 14dB.
So, not perfect, but major improvement.
Thank you.

**Comment by JNavas2** [comment]
UPDATE: I've now played some real videos,
and was not able to reproduce the problem,
so I hereby pronounce it FIXED in 2.2.1.72.
Thank you! 👍 👏
