### ISSUE TITLE
Subtitles cause video to freeze

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#2724]
The file freezes between **00:32 - 01:57** when the opening song starts playing, MPC-HC locks up completely, when I turn off subtitles before I play that part it doesn't occur. Nor does it freeze with the same subtitles in the remainder of the episode after that specific part.

I have not seen any errors/crashes in the Event viewer.

File: [So I'm a Spider, So What - S01E02 [BDRip 1920x1080 x264 10bit AAC-FLAC] [Dual-Audio]_Track05.txt](https://github.com/clsid2/mpc-hc/files/14910200/So.I.m.a.Spider.So.What.-.S01E02.BDRip.1920x1080.x264.10bit.AAC-FLAC.Dual-Audio._Track05.txt)

.ass-file changed to .txt in order for it to upload on Github.

> MPC-HC (64-bit)
> ---------------
> 
> Build information:
>     Version:            2.2.0 (e49bb93ad-dirty)
>     Build date:         Apr  1 2024
> 
> LAV Filters:
>     LAV Splitter:       0.79.1.0
>     LAV Video:          0.79.1.0
>     LAV Audio:          0.79.1.0
>     FFmpeg compiler:    MinGW-w64 GCC 13.2.0
> 
> Operating system:
>     Name:               Windows 11 (Build 23H2)
>     Version:            10.0.22631 (64-bit)
> 
> Hardware:
>     CPU:                13th Gen Intel(R) Core(TM) i9-13900K
>     GPU:                NVIDIA GeForce RTX 4090 (driver version: 31.0.15.5123)
>     Monitor:            \\.\DISPLAY1 - Generic PnP Monitor [3440x1440 32-bit 96 DPI] - [Current]
> 
> Text:
>     Scale Factor:       1.000000
>     Ansi Codepage:      1252
>

**Comment by clsid2** [comment]
I don't get any freezes or crash.

You can get a bit better performance with libass.
Options > Subtitles > Default style > Use libass for ASS/SSA

Set maximum texture resolution to 1080p to further improve performance.
