### ISSUE TITLE
Cannot get HD or UHD 10-bit video to mirror if it is fully 16:9

### ISSUE THREAD

**Issue by ramicio** [clsid2/mpc-hc#2726]
Via pressing Alt+numkeypad6 (or going to the option in the pan and scan menu), I am unable to get the image to flip horizontally if the video is 10 bits and full HD or UHD resolution (1920x1080 or 3840x2160). If video is 720x480 and 16:9 and 10 bits, it flips. If video is 1920x1078 it flips. Et cetera with 3840x2158 and lower vertical resolution. These are all 10-bit HEVC files. If I play something 1920x1080 that's plain old 8-bit h.264, it flips. Flipping the image vertically (Alt+numkeypad2) works no matter the resolution. SDR or HDR, doesn't matter. Also, subtitles (SRT) do not flip in either direction with the internal subtitle renderer.

I'm not a programmer, so I have no idea what any of the stuff even means in the contributing guidelines.

**Comment by clsid2** [comment]
It affects just video, not subtitles. I am not interested in supporting flipping subs.

I can't fix your problem.

**Comment by ramicio** [comment]
Okay, so what about the issue of certain videos not flipping?

**Comment by clsid2** [comment]
The code does not care about resolution or AR when flipping. So if it doesn't work only in one specific situation, hen there is nothing I can do to fix it. I also do not have UHD screen to test.

MadVR does not support mirroring.

**Comment by ramicio** [comment]
I am actually using the MPC video renderer. I have the newest version of both MPC-HC and the renderer. Obviously something in the code is caring about those full resolutions at that color depth. Setting the video decoder output to basically dither down to 8 bits also doesn't change the outcome. One shouldn't need a UHD screen to test this, as I mentioned it's both full HD res and full UHD res.

**Comment by clsid2** [comment]
Not a bug in the player.

Either bug in MPCVR or a graphics driver bug.
