### ISSUE TITLE
Keymap to increase playback speed

### ISSUE THREAD

**Issue by slrgt** [clsid2/mpc-hc#2729]
Hi, sorry about the last post I wasn't clear. It would be great to be able to press a keyboard shorcut that we can customize to increase the playback speed of videos.

Thanks for the amazing work you do on this project!

**Comment by clsid2** [comment]
There already is buttons and keymap for it.
You can adjust speed step in options.

I WILL NOT ADD SHORTCUTS FOR SPECIFIC SPEEDS.
