### ISSUE TITLE
Polish translation again

### ISSUE THREAD

**Issue by lunter2** [clsid2/mpc-hc#2730]
In version 2.2.1 the problem is back!
Still trailing space after clean install when using local mpc-hc64.ini file.

Unnecessary space at the end:

"Przeskaluj do formatu 16:9 TV " -> "Przeskaluj do formatu 16:9 TV"

![293704516-98f76bc6-3114-469c-9a78-94226ee07685](https://github.com/clsid2/mpc-hc/assets/11587779/ec0df5ed-cb92-4c1c-a73c-c3689b855bfb)

**Comment by clsid2** [comment]
@lukjan41

**Comment by Lukjan41** [comment]
I improved
