### ISSUE TITLE
Subtitle delay value reset to 0ms when resuming playback

### ISSUE THREAD

**Issue by koitsu** [clsid2/mpc-hc#2731]
This bug is a little tricky to describe, but I'll give it a shot.  At least it's 100% reproducible.

This issue happens after MPC-HC playback is paused for a long time and then resumed (e.g. after 15-20 minutes).  When resuming, the still image goes black for a second or two, then the video playback resumes (this is normal).

**However, if subtitle delays are in use (ex. hit F1 to adjust subtitle delay to -4500ms), when resuming playback, the subtitle delay resets to 0ms.**

This issue **does not** happen if you pause a video, wait a few seconds, then resume it.  It only happens when the video has been paused for a long time.

Happens regardless of windowed mode or full-screen mode, and regardless of film or subtitle type (embedded .mkv/mks or external .srt).

Technical specifics that might help:

* OS: Windows 10 Pro 22H2 Build 19045.4046
* GPU: EVGA RTX 2060 Super SC Ultra Black Gaming 08G-P4-3065-KR
  - NVIDIA driver version: 552.12
* mpc-hc-clsid version: 2.2.0
* MPC-HC settings:
  * Playback > Output
    - Enhanced Video Renderer (custom presenter)
    - Internal Subtitle Renderer
    - Only EVR settings/checkboxes enabled is Alternative Vsync

If you need more details, or my mpc-hc64.ini, let me know.  Happy to help test/troubleshoot/debug!

**Comment by clsid2** [comment]
Options > Advanced > ReloadAfterLongPause
It reloads after sleep/hibernate because that can help prevent problems caused by driver bugs.

It currently does not yet remember applied delays when reloading.

**Comment by koitsu** [comment]
By "sleep/hibernate" do you mean the entire system, the display, or the GPU?

I ask because I have all system sleep/hibernate features disabled.  Display sleep I **do** have enabled, but that doesn't seem to affect the issue (tested this several times).

If it's some kind of GPU sleep, do you know where in NVIDIA's settings this might be?  Wonderfully annoying "driver features" these days...

**Comment by koitsu** [comment]
OK, seems this is an MPC-HC thing.  The tooltip says a value of `-1` can be used, however the input field will not accept `-` as a character (separate bug?).  Should I try a value of `0` instead?

**Comment by clsid2** [comment]
There is buttons at end of field to adjust value.

Default value is 0.

**Comment by koitsu** [comment]
Mine had a value of 30 somehow, but I've set it to the default (0) for now.  Thank you so much!

**Comment by clsid2** [comment]
Default was different value in past.
