### ISSUE TITLE
Subtitle text size hotkeys don't work

### ISSUE THREAD

**Issue by voidfiction** [clsid2/mpc-hc#2735]
Thank you for the best media player.

Several versions ago, the hotkeys “Increase subtitle text size” and “Decrease subtitle text size” stopped working. When pressed, the size does not change. Using the default subtitle style, reloading subtitles does not help. The behavior is the same when playing any videos.

I use 2.2.1 x64 on Win10 22h2

<img width="326" alt="Snag_a96e561" src="https://github.com/clsid2/mpc-hc/assets/108583358/6a739049-8678-42ac-b713-5a0046719b60">

**Comment by clsid2** [comment]
Disable the libass option if you want resize.

**Comment by adipose** [comment]
Maybe a good "missing feature" hover candidate.

**Comment by clsid2** [comment]
I should probably add a message prompt to the code when using the keys in unsupported situation. Which also includes image based formats such as PGS.

Or make it compatible with libass. Dunno if that is easily doable.

**Comment by adipose** [comment]
With so many entry points, and no clear way to show it's a keystroke, it's a lot of work.

I can't recall if it even triggers if the menu item is disabled.  But if so, maybe a generic routine could be made "file -> xxx not currently enabled."

In this case perhaps libass can be made to work.

**Comment by clsid2** [comment]
I have added error message.

**Comment by voidfiction** [comment]
Thanks disabling libass option and restarting the player helped me.
