### ISSUE TITLE
[DrDump] [Crash] mpcvideorenderer64!memcpy

### ISSUE THREAD

**Issue by Alhaitham** [clsid2/mpc-hc#2737]
When trying to start capture video with laptop internal camera (ctrl+v) with MPCVideoRenderer

https://drdump.com/UploadedReport.aspx?DumpID=128389520

**Comment by clsid2** [comment]
@Aleksoid1978

**Comment by Aleksoid1978** [comment]
What am I, how can I help in this situation. Well, try to reproduce it and look in the debugger.

**Comment by clsid2** [comment]
Input is 1536x576. Memcpy crashes exactly after 288 lines of data. So video is probably interlaced.

@Alhaitham
MPC-HC Options > Advanced > CaptureDeinterlace = True

The data size could probably be used to determine if source is interlaced. Capture MediaType uses VideoInfoHeader (v1) which doesn't contain explicit interlaced flag.

**Comment by Alhaitham** [comment]
@clsid2 still crashes

https://drdump.com/UploadedReport.aspx?DumpID=128393516

====

Related crash dump after playing an old video (personal, can't upload it) that was made by the capture feature with EVR-custom

https://drdump.com/UploadedReport.aspx?DumpID=128393409

Just captured a video with EVR-custom but it played messed up with green

https://files.catbox.moe/faq3h5.avi

Both captured with EVR-custom and played with MPCVR

**Comment by clsid2** [comment]
That second crash still shows MPCVR, so it could not be made with EVR.

**Comment by Alhaitham** [comment]
@clsid2

The personal video is from 2014 so not sure what renderer was used

**Comment by Alhaitham** [comment]
@clsid2

Unchecking "Use Direct 3D 11" in the renderer setting fixes everything

**Comment by clsid2** [comment]
Press Ctrl+J to show renderer debug overlay. Make a screenshot for me.

Try if this build works with Direct3D11:
[MpcVideoRenderer64_interlacefix1.zip](https://github.com/clsid2/mpc-hc/files/14967659/MpcVideoRenderer64_interlacefix1.zip)

**Comment by Alhaitham** [comment]
Same with that build, it crashes to this issue https://github.com/clsid2/mpc-hc/issues/1110

With Direct3D11:

![Clipboard_04-13-2024_03](https://github.com/clsid2/mpc-hc/assets/7531458/9eeffae0-f301-453c-852b-68a8e7f9ff77)

Without Direct3D11:

![Clipboard_04-13-2024_04](https://github.com/clsid2/mpc-hc/assets/7531458/6cca8b7d-39c1-4469-a977-cfcd563a4f3c)

**Comment by clsid2** [comment]
I am just going to block MPCVR from being used for capture and force EVR-CP instead.
Unless MPCVR developers show any interest in fixing this.

If captured files are messed up, I suggest you use a better capture tool such as VirtualDub.

**Comment by Aleksoid1978** [comment]
I don't have camera with 1536x576 interlace mode support.
But other mode - all is good, test in MPC-BE/MPC-HC.

**Comment by Aleksoid1978** [comment]
> The data size could probably be used to determine if source is interlaced. Capture MediaType uses VideoInfoHeader (v1) which doesn't contain explicit interlaced flag.

MPC VR use AM_SAMPLE2_PROPERTIES::dwTypeSpecificFlags from input IMediaSample to detect interlaced content.

**Comment by clsid2** [comment]
That only gets used when MediaType format is VIDEOINFOHEADER2. The problem occurs when upstream filters uses older VIDEOINFOHEADER, which doesn't have interlaced flag.

Perhaps let renderer fallback to DX9 when upstream filter uses VIDEOINFOHEADER?

**Comment by Aleksoid1978** [comment]
The problem is not that it is interlaced or not, there is absolutely no difference when copying data.

**Comment by clsid2** [comment]
![mpcvr_crash_info](https://github.com/clsid2/mpc-hc/assets/4704996/a6d49a2b-ae72-4faa-a7a9-533d0cad082c)
`m_srcWidth=1536`
`m_srcRecWidth=768`
That could explain the problem I think. The correct value must be 768. So that is why it stopped halfway through copying data because it uses 1536 for the texture.

(this was for crash dump for crash with a captured file)

**Comment by Aleksoid1978** [comment]
m_srcWidth get from input header, from BITMAPINFOHEADER.
https://github.com/Aleksoid1978/VideoRenderer/blob/master/Source/DX11VideoProcessor.cpp#L1615

**Comment by Aleksoid1978** [comment]
Check **CMpcVideoRenderer::SetMediaType()** and **CalcImageSize()**, is input pin accept new media type ?
If accept but crash - i don't know what's wrong.
When input pin accept new media type - it must use width/height for output data from it.
As here is crash - filter don't do it, it's bad.

**Comment by Aleksoid1978** [comment]
Confirm crash, I was able to get it at 800x600.
But - it doesn’t crash in MPC-BE, only in MPC-HC.

I think Smart Tee accept new media type but don't handle it.
Where is nothing to do in MPC-VR, just don't use.

**Comment by clsid2** [comment]
Smart Tee is needed to capture to file and preview at same time.

So it is happening because of size change?

**Comment by Aleksoid1978** [comment]
[MpcVideoRenderer-0.8.0.2223_git2024.04.08-5c5a2af.zip](https://github.com/clsid2/mpc-hc/files/14969233/MpcVideoRenderer-0.8.0.2223_git2024.04.08-5c5a2af.zip)

**Comment by NBruderman** [comment]
> [MpcVideoRenderer-0.8.0.2223_git2024.04.08-5c5a2af.zip](https://github.com/clsid2/mpc-hc/files/14969233/MpcVideoRenderer-0.8.0.2223_git2024.04.08-5c5a2af.zip)
> 

@Alhaitham can you test with this build?

**Comment by Alhaitham** [comment]
No crash with it

But it shows green video in the capture preview and the video produced

Just like playing this video https://files.catbox.moe/faq3h5.avi and the screenshot is here https://github.com/clsid2/mpc-hc/issues/2737#issuecomment-2053670331
