### ISSUE TITLE
How to increase Buffer cache in MPC-HC

### ISSUE THREAD

**Issue by personalrepos2002** [clsid2/mpc-hc#2738]
How can I increase the buffer cache in MPC? I tried two methods, but those are already outdated guides. Can you guys help me with this? Thank you

**Comment by clsid2** [comment]
Queue options in splitter

**Comment by personalrepos2002** [comment]
> Queue options in splitter

its not working https://ibb.co/7JZjSjY

**Comment by clsid2** [comment]
The buffer information that you are looking at is irrelevant.
