### ISSUE TITLE
Use default MS GS Synthesizer for midi files in Windows

### ISSUE THREAD

**Issue by BillDonaldsonSr** [clsid2/mpc-hc#2745]
I really like that MPC-HC plays midis. I use it often for that among other media. The default for synthesis in Windows is the MS GS Wavetable synth. It is very old. I had a midi file that had a quirk in the middle of play and solved the problem by installing the Coolsoft VirtualMIDI Synth and disabling the MS GS Wavetable Synth. This works for most midi players, but even though I have disabled the MS Synth and set the Coolsoft as the default, it seems that MPC-HC  uses the MS Synth anyway. I have looked at a way of setting this in the V2.2.1 version, but it appears not to be capable. Is there a way I can force use of the Coolsoft Synth without the need to add this to the burden of improvements?

**Comment by NBruderman** [comment]
So, basically, the issue is that you can switch to another midi engine, and the current old one can't be changed to a more modern one?

**Comment by clsid2** [comment]
MPC-HC uses the standard MIDI DirectShow filters from Windows. There are no configuration settings for it.

Afaik, the CoolSoft tool should work.
