### ISSUE TITLE
Autochange fullscreen mode not recognizing framerates

### ISSUE THREAD

**Issue by AlreadyFree** [clsid2/mpc-hc#2748]
I've set up multiple custom framerate settings in NVidia control panel to be used MPC-HC's autochange fullscreen monitor mode on a G-Sync monitor but MPC-HC only recognizes about half of them. Is there a way to force custom framerates into the settings?

**Comment by clsid2** [comment]
If they are not recognized then there must be something wrong with them.

I can not help you.

**Comment by AlreadyFree** [comment]
They are valid framerates in the NVIDIA control panel. One is 59hz which is recognized by MPC-HC in lower resolutions but not my native screen resolution of 3440x1440.
