### ISSUE TITLE
Fragmented MP4 takes a long time to load and isn't correct length

### ISSUE THREAD

**Issue by Lordmau5** [clsid2/mpc-hc#2749]
So the recording / streaming software OBS Studio has implemented support for Fragmented MP4 and MOV recording.

These containers are a good alternative to MKV because more players / editors support it out of the box, and vastly better than plain MP4 / MOV containers because if the encoder crashes the entire file will be corrupted (and potentially also not recoverable)

I've been recording in Fragmented MP4 ever since it got added as an option.

However, trying to play back the file in MPC-HC (or any player by that matter) means it has to seek through the entire file first from what I can tell, which means a, say, 5 hour file takes about 30 seconds to open when it's store on an HDD.

Additionally, the length seems to not be correct - it sometimes shows 1:30h, other times 2h, etc.

VLC handles the length correctly, but it also struggles with loading the file in a fast manner.

Here's a small recording of the time it takes for it to load in both MPC and VLC for comparison:
https://www.youtube.com/watch?v=Bc2SVNxawbI

I'm not sure if this is something that's fixable or just inherently an issue with the container format - For now I'll probably just stick to remuxing the files to normal MP4 after I'm done recording, but if there's a chance to skip this extra step that'd be neat.

**Comment by clsid2** [comment]
That is the result of your own choice of format. The fragmented file must be lacking proper metadata for duration and seeking. You should remux.

**Comment by Lordmau5** [comment]
Okay I'll do that in that case

Thought I'd report it either way to maybe bring attention to this in case it might've been fixable.

On another note though - what about the incorrect length? Is that something that's fixable at least?

**Comment by clsid2** [comment]
It is a demuxer issue. So you are in wrong place here. You need to submit bug report to FFmpeg.

**Comment by Lordmau5** [comment]
Alright I'll report it to FFmpeg then, thank you 😁

**Comment by Aleksoid1978** [comment]
Can you upload one of problem files ?

**Comment by Lordmau5** [comment]
> Can you upload one of problem files ?

I've remuxed the remaining files yesterday and deleted the fragmented ones, but I can record a new one next stream and upload it if you want to take a look at it

I also wanted to see if I can manually remux a normal MP4 to a fragmented one with the muxing flags that I've found on a few stackoverflow posts.
Maybe OBS is missing one of them and as such it is not resulting in a good fragmented file?

Checking the OBS code they seem to be using these movflags if a user selects a fragmented format in the settings
`movflags=frag_keyframe+empty_moov+delay_moov`

**Comment by Lordmau5** [comment]
@Aleksoid1978 

Okay I've remuxed a normal MP4 back to a fragmented MP4 with these movflags
`-movflags +frag_keyframe+separate_moof+omit_tfhd_offset+empty_moov`

Video is about 5h long, and has a size of 17.5GB

Trying to play it back from my NVMe SSD still takes a few seconds for it to even start, while on the HDD it takes about 30 seconds.

The file is here in case you want to download it and check it out:
https://cloud.lordmau5.com/s/3N7zH5zyNf8r5no

I assume the bigger issue isn't the *length* of the video, but rather the *size* of the file as it has to seek through everything first before being able to play it back.

In this case, I am not sure if support for "rolling playback" could be added, where it will already start playing the video right at the start, and keep going through the file while updating the length and such.
Not sure about seeking during that process though... Might have to start from that point and find the closest keyframe or something?

**Comment by Aleksoid1978** [comment]
A long-duration file consisting of simply a huge number of small “fragments”, when opened, all these fragments must be read and processed - that’s why it takes such a long time.
Advice - don't record it like that :)

**Comment by Lordmau5** [comment]
> Advice - don't record it like that :)

Well, how else should I record long-form content such as livestreams?
Back to MKV and having to remux it because most video editors (and also some other programs) can't work well with them?

OBS did set Fragmented MP4 as the default a while back (and I think they reverted it back to MP4 for the time being, I don't know why) so this has implications for a lot of people in the future if they also run into this issue.

(Not trying to sound like a douche btw, genuinely curious 😄 )

**Comment by clsid2** [comment]
DaVinci Resolve supports MKV.

**Comment by Lordmau5** [comment]
> DaVinci Resolve supports MKV.

Not perfectly. It still has issues generating waveforms for the audio tracks as well as has some hiccups in a few spots.

MP4 (and by extension Fragmented MP4) work fine however
