### ISSUE TITLE
[Bug] Renderer Settings grayed, "display time" feature not available through menus

### ISSUE THREAD

**Issue by BoomerangAide** [clsid2/mpc-hc#2754]
Version 2.2.0
Renderer Settings in the right-click context menu is grayed and cannot develop into other options (may be because using MPC Video Renderer).
This cause the entry to show time not being available through the menus.
But the feature is not lost or broken, since it can be accessed through the shortcut key for "OSD: Display Current Time".

Possible fixes:
- moving the "display time" feature in another menu
- preventing the entire submenu of Renderer Settings to get disabled.
- Other solutions?

Thanks in advance for looking into this.

**Comment by clsid2** [comment]
That menu is only available when using EVR-CP/Sync/VMR9. It is not relevant for any other renderers. I am not making any changes just for OSD stuff that already has key combos.

OSD option is available on User Interface page in settings.
