### ISSUE TITLE
No OSD volume indicator

### ISSUE THREAD

**Issue by Drudicta** [clsid2/mpc-hc#2757]
I'm running 2.1.4 and when I use the scroll wheel to change my volume it does not show a percentage on the video. I have "Show OSD" on, and it's shown it before. I get the teeny tiny percentage bar on the volume slider it's self if I use the mouse to slide it back and forth, but I want to be able to do it in increments of 5% and not have to guess the amount.

**Comment by clsid2** [comment]
Works fine for me.

**Comment by diminian** [comment]
@Drudicta hello! 
Try changing 'Video DirectShow' option in the 'Output' settings.
I've set it to 'madVR' and after I restarted MPC I got the OSD back.
