### ISSUE TITLE
Increased speed of playing some of audio-tracks

### ISSUE THREAD

**Issue by rafael-abelyar** [clsid2/mpc-hc#2758]
After switching to some audio-track sound starts play at increased rate.
Issue possibly can appear "Stereo" sound or for some other reason.
See example attached. 

https://github.com/clsid2/mpc-hc/assets/77679801/e1ba13eb-3cde-4ef8-aebb-54f232592852

**Comment by clsid2** [comment]
Then there is a bug in your sound driver.

Enable mixer in the audio decoder.

**Comment by rafael-abelyar** [comment]
> Then there is a bug in your sound driver.
> 
> Enable mixer in the audio decoder.
Could you give an instruction in more detail?

**Comment by clsid2** [comment]
Options > Internal Filters > Audio Decoder > Mixer

**Comment by rafael-abelyar** [comment]
I have no problem in other players e.g. Daum Pot Player.

**Comment by rafael-abelyar** [comment]
> Options > Internal Filters > Audio Decoder > Mixer
Filling this check-box resolved my problem:


![Проблема ускоренного проигрывания дорожек в MPC-HC - поставить галку](https://github.com/clsid2/mpc-hc/assets/77679801/49a72c6d-837f-4405-93dd-136b76699bcf)
