### ISSUE TITLE
VMR7 crash on second monitor

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#2762]
Trying to play a video in windowed mode using VMR7

`m_pVW->put_Owner((OAHWND)m_pVideoWnd->m_hWnd);`

![image](https://github.com/clsid2/mpc-hc/assets/3324395/a79e79c3-8783-4afa-95f2-459bd1917d17)

Maybe we can drop VMR7?

**Comment by clsid2** [comment]
Looks like `m_pVideoWnd` is null?

No issue here with second screen.

**Comment by adipose** [comment]
It was not null is the strange part.

**Comment by adipose** [comment]
I have a usb screen, it may cause issues.  It doesn't use the main video card.
