### ISSUE TITLE
Properties window anchors on MediaInfo

### ISSUE THREAD

**Issue by Dendraspis** [clsid2/mpc-hc#2765]
Hello,

when resizing the MediaInfo Properties window to get a better overview, this happens:

![image](https://github.com/clsid2/mpc-hc/assets/50659978/c527f69c-f8e4-439b-a026-3f47a672756a)

Couldn't find an existing issue about that...
Thanks.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2770

**Comment by Dendraspis** [comment]
Thank you.

**Comment by Dendraspis** [comment]
Just a little feedback .. both issues gone  🥳 

Thank you!

![image](https://github.com/clsid2/mpc-hc/assets/50659978/0cd7dbdd-35ee-4bcf-af56-868fe9027e5f)

**Comment by bibsp** [comment]
In MediaInfo tab `Save As` and `Close` buttons are placed at weird position. Why? I just noticed it during testing.

**Comment by adipose** [comment]
> In MediaInfo tab `Save As` and `Close` buttons are placed at weird position. Why? I just noticed it during testing.

It was previously centered when not resized.  I kept it there.  The save as was previously in the bottom right.

When resizing it keeps them there because alternative looks worse.
