### ISSUE TITLE
Details on Properties window in German

### ISSUE THREAD

**Issue by Dendraspis** [clsid2/mpc-hc#2766]
Hello,

on the Properties window there are 2 issues when using German translation:

1. There is a `&` before `Details`
2. `(&)Details` is shortened by `&Det...`. It would be nice if it won't be shortened at all, because there is enough space.

Thank you.

**Comment by adipose** [comment]
Can it say `Einzelheiten` ?

**Comment by adipose** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/3324395/9646e704-fae4-405d-b0c3-a949e99df012)

I updated it in latest translation merge.

**Comment by Dendraspis** [comment]
`Details` would also be great, but not `&Details`.  😅

**Comment by Dendraspis** [comment]
Oh, seems like I forgot to paste the screenshot in  🙄 

This is how it looked before:

<img width=600 src=https://github.com/clsid2/mpc-hc/assets/50659978/09bbf073-0154-485b-b773-1321ee15ad18>

**Comment by adipose** [comment]
Yes, I was able to reproduce it on my end.  The translation is old and wrong.  If you want to help, you could update the strings yourself in Transifex.

https://github.com/clsid2/mpc-hc/issues/215

**Comment by Dendraspis** [comment]
If I would already have a Transifex account I would have definitely done it instead of posting this issue. But also because of the shortening I was not sure if that would solve the whole problem.
When I have some time I will see if I can help with the missing translations...

Thanks for fixing it.  👍 
So I guess I can close this now....

**Comment by adipose** [comment]
I don't know why it shortened, really.  It must have a problem measuring it when there's an ampersand.  It may be a bug because it didn't treat the ampersand as a control char, at least in dark mode.

**Comment by Dendraspis** [comment]
Maybe related to #2765 ? Or my OS and settings.

Very strange, but not such a big deal and maybe it's already fixed by removing the `&`, so I leave it closed.

Thanks.

**Comment by adipose** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/3324395/00c5ba63-3d6f-43e1-b08c-7d35324d40cc)

Before it was resizable, it worked and the & caused an accelerator to show up.  Although it doesn't work (alt+D).

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2769

Fixed here.  The ampersand being drawn caused the title to get cut off.

**Comment by Dendraspis** [comment]
Interesting and annoying.  😕

Thank you very much for fixing it. 👍
