### ISSUE TITLE
OSD needs small improvement

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2771]
[Should be fixed] It is now pixelated. Previous one was smooth.

[Extra] And the border looks ugly. Previously there was no border, and that looks much better in my opinion.
Old vs New:
![Screenshot (62)](https://github.com/clsid2/mpc-hc/assets/98865389/6033da9e-96b7-45c4-920c-c488ee48dae5)
![Screenshot (63)](https://github.com/clsid2/mpc-hc/assets/98865389/f530c37c-b645-46ae-8581-1c07941acb7a)

Question: Can I make it transparent like mpcbe? Is there any setting?

**Comment by clsid2** [comment]
Border will stay.
Transparent option maybe in future.

BE has same pixelation issues.

**Comment by bibsp** [comment]
> Border will stay.

Okay, No problem.


> BE has same pixelation issues.

At least try to improve it in future (If possible).

**Comment by clsid2** [comment]
@adipose
In `COSD::CreateFontInternal()` it uses:
lf.lfQuality = ANTIALIASED_QUALITY;

It looks better here with CLEARTYPE_QUALITY. But subtitle renderer uses ANTIALIASED_QUALITY as well, and that has no issues with quality.
Weird thing as well is that there is visual difference between light and dark theme. In dark theme text looks a bit thicker.

**Comment by adipose** [comment]
Which OSD font do you have set in settings?

**Comment by clsid2** [comment]
Segoe UI

**Comment by bibsp** [comment]
1. OSD disappears if I toggle full screen.
2. Launch player, don't open any file. Then change volume. OSD will not show. Mpcbe can show OSD in this situation.

**Comment by clsid2** [comment]
OSD works normally here in fullscreen.

I do get random stuck blackcreen when exiting EVR-CP d3d exclusive fullscreen.

**Comment by bibsp** [comment]
Yes, OSD works in full screen. Try this:

Play video in window mode.
Change volume. Double click to go to full screen.
The OSD will disappear.
Maybe you don't use mouse left up delay, that's why you can't reproduce. I use 250ms delay.
You can do the opposite. From full screen to window mode. It will disappear. Once the window is changed it works fine. During the transition it disappears.

**Comment by clsid2** [comment]
Disappearing during transition is not important.

**Comment by adipose** [comment]
> @adipose In `COSD::CreateFontInternal()` it uses: lf.lfQuality = ANTIALIASED_QUALITY;
> 
> It looks better here with CLEARTYPE_QUALITY. But subtitle renderer uses ANTIALIASED_QUALITY as well, and that has no issues with quality. Weird thing as well is that there is visual difference between light and dark theme. In dark theme text looks a bit thicker.

I think RTS uses its own renderer based on the extracted truetype path, no?  I'm not entirely sure it's even trying to do cleartype or truetype hinting.

But that is interesting, because we could potentially reuse that RTS code to render the OSD, if it's preferred.

**Comment by adipose** [comment]
Re: the thicker white font, I can confirm.  It may be related to this issue:

https://stackoverflow.com/questions/14477265/css-white-text-on-black-background-looks-bolder

The white font is about 1 pixel larger all around.

![image](https://github.com/clsid2/mpc-hc/assets/3324395/a6ea260f-d970-495d-9006-ffc39b00059b)

**Comment by adipose** [comment]
It's a much more subtle difference with cleartype.  "Antialiased" is probably almost never the right choice, since CRTs basically died completely by 2014.  I suspect RTS wouldn't work differently since it's just capturing the TT path, but I guess we could test it.

![image](https://github.com/clsid2/mpc-hc/assets/3324395/ff2a0790-9452-4ca6-8743-f1d9045dc936)

**Comment by clsid2** [comment]
I have pushed the cleartype change
