### ISSUE TITLE
Unidentified audio stream

### ISSUE THREAD

**Issue by AntonieS** [clsid2/mpc-hc#2781]
Can't play audiostream with [0xffff] in header
Audio: 0xffff 48000Hz stereo 2304kbps [A: German [ger] (s302m, 48000 Hz, stereo, s20, 2304 kb/s)]

Noise in speakers.

Thanks in Advance.

**Comment by clsid2** [comment]
Unsupported audio format.

**Comment by AntonieS** [comment]
Ok. What the format it is?

**Comment by clsid2** [comment]
Probably Dolby E inside s302m wrapper.
