### ISSUE TITLE
MPC-HC freezing when watching YouTube video using yt-dlp with D3D Fullscreen enabled 

### ISSUE THREAD

**Issue by Salah242222** [clsid2/mpc-hc#2782]
MPC-HC freezing when watching YouTube video using yt-dlp with D3D Fullscreen enabled

**Comment by clsid2** [comment]
Then do not use D3D Fullscreen. It is pointless feature and I am very tempted to remove it.

**Comment by Salah242222** [comment]
No please don't remove it, i use it because I'm using Bluesky Frame Rate Converter and when i set the frames to more than 75fps without it the video lag (for 2k 60fps) , after enabling the problem goes away

**Comment by clsid2** [comment]
Does it freeze without using Bluesky?

**Comment by Salah242222** [comment]
Now i tested, yes disabling bluesky didn't solve the problem, the freezing happens only when going to full-screen mode

**Comment by Salah242222** [comment]
and seeking through YouTube video cause freezing and that's in both full-screen and windowed mode

**Comment by clsid2** [comment]
Works normally here.

**Comment by Salah242222** [comment]
MPC-HC (64-bit)
---------------

Build information:
    Version:            2.2.1 (30fc3853b)
    Build date:         Apr 10 2024

LAV Filters:
    LAV Splitter:       0.79.2.0
    LAV Video:          0.79.2.0
    LAV Audio:          0.79.2.0
    FFmpeg compiler:    MinGW-w64 GCC 13.2.0

Operating system:
    Name:               Windows 10 (Build 22H2)
    Version:            10.0.19045 (64-bit)

Hardware:
    CPU:                AMD Ryzen 7 4800H with Radeon Graphics
    GPU:                NVIDIA GeForce GTX 1650 (driver version: 31.0.15.5212)
    Monitor:            \\.\DISPLAY1 - Generic PnP Monitor [1920x1080 32-bit 96 DPI] - [Current]

Text:
    Scale Factor:       1.000000
    Ansi Codepage:      1252
