### ISSUE TITLE
VLC can play this file, but HPC cannot play it. May I ask where the problem is?

### ISSUE THREAD

**Issue by 675535** [clsid2/mpc-hc#2791]
I am not used to using other players. I have been using MPC for many years, but when I recommended MPC to someone else, they told me that this WMV file cannot be played. It was sent to me by a netizen, and I am not sure why. Can you help me find the reason?

VLC can play this file. I have re uploaded the WMV file to Google Cloud Drive. 

https://drive.google.com/file/d/1DlcfpVzBKccIUWfqch5yWQyuHoFEVIyi/view?usp=sharing

Thank you for your help!

**Comment by clsid2** [comment]
For problem with internal codecs you can go here:
https://github.com/Nevcairiel/LAVFilters/issues

**Comment by 675535** [comment]
> For problem with internal codecs you can go here: https://github.com/Nevcairiel/LAVFilters/issues

Thank you very much!
