### ISSUE TITLE
Language code pt-PT not working for subtitles from opensubtitles.com

### ISSUE THREAD

**Issue by zybexXL** [clsid2/mpc-hc#2792]
Opensubtitles.com uses 4-letter language codes for some languages, such as "pt-PT" for Portuguese. This is not working on MPC-HC, so it's currently not possible to fetch PT subtitles. It's likely that the hyphen in "pt-pt" is being ignored/removed. Their old API used "POR", but that no longer works.

Here is their list of supported language codes:
https://api.opensubtitles.com/api/v1/infos/languages

**Comment by clsid2** [comment]
"por" works fine here.

MPC-HC only supports 2/3 letter ISO codes (pt/por). Do NOT use "pt-PT". They are internally converted to relevant code for opensubtitles.

**Comment by zybexXL** [comment]
I updated to 2.2.1.32 (dc74f31d9) and now "POR" does indeed work. Thank you.
Version 2.1.4 did not work.
