### ISSUE TITLE
"Added option to always show time in OSD"

### ISSUE THREAD

**Issue by JasioNiezdara** [clsid2/mpc-hc#2794]
I'm sorry to say, but I don't like this change.

I was extremely used to this function resetting every time I closed the player. I often use it briefly, either during end credits or when seeking through the video. But now I have to remember to turn it off, and usually I don't. Sometimes I open a video, press the "Display Current Time" key to turn on the feature, but it was already on and turns off instead. It's confusing.

Is it possible to somehow force the old behavior? Or could you add a separate toggle for that?
It would be best if pressing the "Display Current Time" key didn't affect the option in the menu. Like if I uncheck that option, pressing they key shouldn't check it (and vice versa), it should only be temporary until I close the player.

I would be grateful if you could tweak this change.

**Comment by clsid2** [comment]
Just press Ctrl+I to turn it off.

I am not adding more options.
