### ISSUE TITLE
Doesn't remember maximized state with options enabled

### ISSUE THREAD

**Issue by Labhatorian** [clsid2/mpc-hc#2795]
### Description
MPC-HC has the following options enabled:
- Remember File position
- Remember DVD position
- Remember last window position
- Remember last window size

The window remembers its position and size but does not remember that it was maximized before closing the video and reopening it.

**Expected Behavior:**
The window should reopen maximized if it was maximized when it was last closed.

**Actual Behavior:**
The window reopens in an unmaximized state, retaining the position and size it had when it was unmaximized, even though it was maximized when closed.

### Steps to Reproduce
1. Open MPC-HC.
2. Enable the options listed in the Description.
3. Open a video.
4. Maximize the video window.
5. Close the video and then open it again.

### Environment
- Operating System: Windows 11 23H2
- MPC-HC Version: 2.2.1

**Comment by clsid2** [comment]
Works here.

**Comment by Labhatorian** [comment]
Reinstalling with the 'delete all user settings' option enabled miraculously fixed the issue, even though I freshly installed it.
In hindsight, this is something I should have tried initially lol
