### ISSUE TITLE
Compilation error since 1.8.1

### ISSUE THREAD

**Issue by BMitrovic17** [clsid2/mpc-hc#28]
I was able to build `1.7.18` just fine but with addition of `libaom` this is not the case anymore.

command that i'm running is `build.bat build x64 7z`

mpc-hc_errors_Release_x64.log:
```
09:58:16.995    33>EXEC : error : aom >= 0.1.0 not found using pkg-config [g:\devel\mpc-hc\src\thirdparty\LAVFilters\LAVFilters.vcxproj]
09:58:17.079    33>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: The command "build_lavfilters.bat Build x64 Release Silent Nocolors" exited with code 1. [g:\devel\mpc-hc\src\thirdparty\LAVFilters\LAVFilters.vcxproj]
```

looking around for the same error i've discovered that the issue is because of order of the building but i can't provide a patch being that i don't know how to fix this.

https://github.com/rdp/ffmpeg-windows-build-helpers/pull/330

**Comment by clsid2** [comment]
Works fine for me. Your MinGW installation might be missing pkg-config.

**Comment by vBm** [comment]
@clsid2 I've tried it myself as well, and the same issue i see.
I'm using official [toolchain/env.](https://github.com/clsid2/mpc-hc/blob/develop/docs/Compilation.md#part-b-preparing-the-gcc-environment)

```
vBm@baSTARdo MSYS ~
# pacman -Ssq pkg-config
mingw-w64-i686-pkg-config
mingw-w64-x86_64-pkg-config
pkg-config
```

**Comment by clsid2** [comment]
Also add the msys and mingw bin folders to %path%.

**Comment by vBm** [comment]
> Also add the msys and mingw bin folders to %path%.

That's done via `build.user.bat` yet still doesn't work.

If i'm not mistaken it seems like [pkg-config.sh](https://github.com/clsid2/mpc-hc/blob/2de64f4e2d866a50a23c5955035b6861e23804e9/src/thirdparty/LAVFilters/build_ffmpeg.sh#L94) wasn't commited.

**Comment by BMitrovic17** [comment]
Thanks @vBm . I was running the `git submodule update --init --recursive` to pull the latest changes and compile was failing. After doing commands in order you said it's working again.
Thanks again.
