### ISSUE TITLE
Losing queue 

### ISSUE THREAD

**Issue by CyrCom** [clsid2/mpc-hc#2809]
Hello,

Windows 10 / 2.2.1.39 / Settings attached
It's been many versions (sorry don't know the start) which makes me lose my queue list when a file ends. 'Read next file in repertory' is selected in the options. It does read next file in repository but I'm pretty you would want the next file in queue to be played if there is any ? 
Thanks for your amazing job.
I hope I'm not dumb on this and you can help.

[mpc-hc-settings.zip](https://github.com/clsid2/mpc-hc/files/15462046/mpc-hc-settings.zip)

**Comment by clsid2** [comment]
You need to explain better what goes wrong.

Here is properly continues with playlist.

**Comment by xLn2** [comment]
Settings are:
![resim](https://github.com/clsid2/mpc-hc/assets/3073922/3b54829b-1bcd-4149-b331-8b946d91f88c)

Steps:

1. Add a bunch of media files (I added 17 ordered mp3 files to playlist on same folder, filename structure is 01. aa 02. bb 03. cc etc.)
2. Randomize (Playlist)
3. Open last media file on playlist (i.e "10. ABC DE"on the playlist and jump about 90%
4. After media ends Playlist queue clearing itself and play "11. CVB BN"

Comment:
I do not know how this function supposed to work but I think there are 2 logical option
1. Respect to "Repeat Playlist" and do not play next file on the folder --except playlist items.
2. Respect to "Play next file on the folder" and when next file is not yet been in playlist, add it to playlist queue

But clearing playlist is probably main issue that should not happen IMO.

**Comment by clsid2** [comment]
Here it does not jump to next file in folder until playlist has ended.

I could change it to always ignore this after playback action when playlist has multiple entries, but I am not sure if anyone uses current behavior.

**Comment by CyrCom** [comment]
Sorry for the delay,
Thank you @xLn2 for adding resource. However my Repeat Mode setting is on 'File'.
(play 1 time, after playback: play next in folder)
This is precisely when the bug occurs. (doesn't otherwise)

I should not change my settings to Repeat Mode 'playlist' because I want my playlist to continue and sometimes repeat a specific media. I also need the read next file in folder if only one file is played.
I hope you can reproduce, if no one can, apologies. 
![issue 2809 mpc-hc_001](https://github.com/clsid2/mpc-hc/assets/8659935/6d2e985e-084e-4e44-b069-780220868ab2)
