### ISSUE TITLE
Downtime in audio when seeking with bitstreaming enabled

### ISSUE THREAD

**Issue by ecruz1986** [clsid2/mpc-hc#2818]
I'm playing a Dolby Atmos TrueHD file with bitstreaming enabled to my receiver connected via HDMI.

When I seek through the timeline of the file while it is playing, there is a downtime in audio playback, it stays mute for about 2 seconds before it starts playing again from the new timeline position.

For comparison, VLC's audio downtime when seeking under the same conditions is much lower than MPC-HC's, so we can be sure there is room for improvement here so that users get a more seamless experience while seeking.

**Comment by clsid2** [comment]
I can not help you.
For issues with internal filters go to LAV Filters project.
