### ISSUE TITLE
Certian  UHD and high framerate videos stutters

### ISSUE THREAD

**Issue by Feejus** [clsid2/mpc-hc#2821]
I hope someone can just confirm my findings. I have noticed that some of the high res videos with both UHD (3860 x 2160) with high Framerate in my case it is 60fps runs stuttery. When using VLC it is all smooth. This applies to random video files. 

My hardware is as you can see quite capable to run this smoothly. 

Processor  12th Gen Intel(R) Core(TM) i7-1260P   2.10 GHz
Installed RAM  64.0 GB (63.6 GB usable)

Looking at the information about video here is some data about just one example where i see this. Is this expected behaivor? Has anyone else seen this? 

Format                         : MPEG-4
Format profile                 : Base Media
Codec ID                       : isom (isom/iso2/avc1/mp41)
File size                      : 632 MiB
Duration                       : 8 min 52 s
Overall bit rate               : 9 963 kb/s
Frame rate                     : 59.940 FPS
Writing application            : Lavf60.3.100

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L4.2
Format settings                : CABAC / 4 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 4 frames
Codec ID                       : avc1
Codec ID/Info                  : Advanced Video Coding
Duration                       : 8 min 52 s
Bit rate                       : 9 694 kb/s
Maximum bit rate               : 9 827 kb/s
Width                          : 3 840 pixels
Height                         : 2 160 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 59.940 (59940/1000) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.019
Stream size                    : 615 MiB (97%)
Writing library                : x264 core 164
Encoding settings              : cabac=1 / ref=1 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=8 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=239 / keyint_min=59 / scenecut=0 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=22.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=9827 / vbv_bufsize=19654 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Color range                    : Limited
Color primaries                : BT.709
Transfer characteristics       : BT.709
Matrix coefficients            : BT.709
Codec configuration box        : avcC

Audio
ID                             : 2
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Codec ID                       : mp4a-40-2
Duration                       : 8 min 52 s
Source duration                : 8 min 52 s
Bit rate mode                  : Constant
Bit rate                       : 256 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 46.875 FPS (1024 SPF)
Compression mode               : Lossy
Stream size                    : 16.2 MiB (3%)
Source stream size             : 16.2 MiB (3%)
Default                        : Yes
Alternate group                : 1

Is there anything I am missing? Maybe a setting i need to change? I am just looking for advice and guidence and to understand if this is expected behaivor.

**Comment by clsid2** [comment]
Change video renderer to: MPC Video Renderer
Change hardware decoder in internal video decoder to D3D11

**Comment by Feejus** [comment]
Thank you! I check it out.
