### ISSUE TITLE
Open Directory, Save Image and Save Thumbnails dialog boxes have several issues

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2824]
MPC-HC (64-bit)
---------------

Build information:
    Version:            2.2.1.55 (da42c4d6b)
    Build date:         Jun  1 2024

Operating system:
    Name:               Windows 10 (Build 22H2)
    Version:            10.0.19045 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    GPU:                Intel(R) HD Graphics 630 (driver version: 31.0.101.2128)
    Monitor:            \\.\DISPLAY1 - Generic PnP Monitor [1920x1080 32-bit **120 DPI**] - [Current]

Text:
    Scale Factor:       1.000000
    Ansi Codepage:      1254
_________

1. File > Open Directory
Theming control is missing here. (Modern Dark theme)
![resim](https://github.com/clsid2/mpc-hc/assets/3073922/9c600af9-0913-4702-93a4-6649c16fc1bb)

2. File > Save Image and Save Thumbnails
`Quality (%)` dissappears while changing image format to BMP/PNG and back to JPG
![mpc-hc64_YOqLdXbezM](https://github.com/clsid2/mpc-hc/assets/3073922/d6202ba6-21bb-45b2-8149-384c590cfce9)
![mpc-hc64_smvDq0UAHa](https://github.com/clsid2/mpc-hc/assets/3073922/19205eab-5911-4fb2-a593-6f016f4e0830)

Changing image format doesn't change file name extension. For example you change it to PNG but filename is staying as "file_snapshoot_11111.jpg" --`Saving subtitles' dialogbox` nicely handles changing formats and filenames.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/52 may be relevant.

I can't recall if the checkbox was themable.  I can check.

**Comment by xLn2** [comment]
> 52 may be relevant.

I don't know about code but description might be badly written or maintainer didn't have time to check it yet. Current behavior of saving image is only consider selected image format so visible filename is not important. But it might confuse users and take people's time to edit it manually to intercept the idea of _"filename.jpg.png" or correct file extension but wrong file format cases_.

> I can't recall if the checkbox was themable. I can check.

https://github.com/clsid2/mpc-hc/issues/2531 Similar issue is here, maybe helps.

**Comment by adipose** [comment]
Issue number 1:
https://github.com/clsid2/mpc-hc/pull/2826

**Comment by adipose** [comment]
Issue number 2 fixed as well. By setting the extension to match the starting filename, the dialog is smart enough to recognize which part is the extension, even when changing it.  The same behavior never works when the dialog is started without an extension, even if you add one.

**Comment by adipose** [comment]
@clsid2 , can you reproduce the disappearing text on the save dialog?  I cannot.  Maybe something in Turkish Windows localization.

@xLn2 , I have never been able to reproduce this.  Do you have any other machines that it happens on?

**Comment by xLn2** [comment]
Recently I just access single machine, I have a suspect it may be related to some Windows performance/quality settings. I will try it when I find those settings were.

If I resize dialog "Quality (%):" come back, or If I set sub renderer to None and try again to `Save Image` the text doesn't disappear. But for `Save thumbnails` this case still happens.

Asked a friend to check it, response is: "quality" string didn't initialize when dialog box first apearing, later on there is no issue about initializing but swapping between other formats to JPG has issue.

![resim](https://github.com/clsid2/mpc-hc/assets/3073922/8c0fd1e7-a7b5-48dd-b50c-13d0b692d8cc)

**Comment by xLn2** [comment]
Windows performance/quality settings didn't have effect on my end.

Friends' system spec who reproduce same behavior.

MPC-HC (64-bit)
---------------

Build information:
    Version:            2.1.3 (0cad76c96) and also 2.2.1.72 (5697b96fa)
    Compiler:           MSVC v19.29.30152
    Build date:         Dec 13 2023

LAV Filters:
    LAV Splitter:       0.78.0.1
    LAV Video:          0.78.0.1
    LAV Audio:          0.78.0.1
    FFmpeg compiler:    MinGW-w64 GCC 13.2.0

Operating system:
    Name:               Windows 10 (Build 22H2)
    Version:            10.0.19045 (64-bit)

Hardware:
    CPU:                AMD Ryzen 7 3800X 8-Core Processor
    GPU1:               NVIDIA GeForce RTX 2070 (driver version: 32.0.15.5585)
    GPU2:               NVIDIA GeForce RTX 2070 (driver version: 32.0.15.5585)

 Monitor:            \.\DISPLAY1 - Generic PnP Monitor [1920x1080 32-bit 96 DPI] - [Şimdiki]
    Monitor:            \.\DISPLAY2 - Generic PnP Monitor [1920x1080 32-bit 96 DPI]

Text:
    Scale Factor:       1.000000
    Ansi Codepage:      1254

**Comment by adipose** [comment]
Your friend also using Turkish localization?

If you can test English localization or use a VM, might be worth it.

I never reproduced but I can try some additional settings and machines.

**Comment by xLn2** [comment]
> Your friend also using Turkish localization?

Yes, probably used Turkish language pack from MS lang settings or some MS Store like I did. And high probably installed regional settings to Turkish even first installment display language was English.

> If you can test English localization or use a VM, might be worth it.

I tried English as system language, but issue still happens, our common point is Win10 versions and ANSI codepage. I don't have VM and .iso files to try. 

![resim](https://github.com/clsid2/mpc-hc/assets/3073922/58f56cfe-5b94-4203-bb39-7fa73862cf85)

**Comment by clsid2** [comment]
![draw_artifact](https://github.com/clsid2/mpc-hc/assets/4704996/99045c8d-954c-4693-9d1d-d4dd8be74ed7)
After switching from JPG to BMP, you see the "e" from "bmp image" or leftover of "jpg image".

Maybe just always put "Include subtitles" checkbox in same location?

The quality % box can be much smaller and on same line. Don't show "xxx image" but only "quality %"?

**Comment by adipose** [comment]
I reproduced the issue on VMWare.  It happens to be 21H2.

No need for localization tests now.  Not sure why it affects my VM but not my workstation.

**Comment by adipose** [comment]
I have a fix for it now. I'll submit it later.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2829

Weirdly enough, forcing the redraw fixes the problem, but so does doing random things like looking for child windows that aren't there.  I think this should probably also fix @clsid2 's issue but I'm not sure.

It seems that just introducing a small delay after the checkboxes are re-enabled may be enough, so it's difficult to say how well the fix will work, but hopefully it works for both of your cases.

**Comment by clsid2** [comment]
The leftover "e" is still there. It disappears when I move the mouse over the "include subtitles" checkbox.

**Comment by clsid2** [comment]
Using a second `StartVisualGroup` seems to fix the issue.
