### ISSUE TITLE
ToDo: forward UA/referrer from yt-dlp output to LAV Splitter

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2825]
LAV Splitter Source has new interface to open URL with these parameters:
https://github.com/Nevcairiel/LAVFilters/blob/master/include/IURLSourceFilterLAV.h

- Check if yt-dlp output contains UA or referrer data
- Add function to graph builder to set that data
- Check if LAV supports the interface (could also be done based on version)
- Call the new LoadURL function instead of using generic instance of the source filter (if UA/referrer non-empty)

**Comment by ale5000-git** [comment]
Is there any disadvantages to always call LoadURL regardless (if supported)?

**Comment by ale5000-git** [comment]
It could set the MPC-HC User-Agent or to be more compatible simulate a browser.
There may be streaming that need it even if they aren't passing through yt-dlp.

**Comment by xinghongzhou** [comment]
👍

**Comment by xinghongzhou** [comment]
Currently vlc, mpv and potplayer already support this feature, so I hope that our wonderful mpc-hc will have this feature soon too 😜 Thanks a lot to the people who keep on developing the mpc project, you guys are great! 👍

**Comment by clsid2** [comment]
Initial implementation is done.

Might need to store useragent in history as well and save it to MPCPL playlist file. Edit: it should run yt-dlp again in those situations, so probably not needed.

Test URL taken from a closed issue:
https://vk.com/video-24440848_456240559

**Comment by xinghongzhou** [comment]
It is necessary to store the useragent in the history and save it to the MPCPL playlist file, so that the next time you open the player you can continue to play the video that was not played last time.

**Comment by bibsp** [comment]
https://www.zee5.com/movies/details/abby-sen/0-0-abbysen

2..3.3.27
failed to render.

**Comment by clsid2** [comment]
yt-dlp itself gives error, so not fault of player!

**Comment by bibsp** [comment]
yt-dlp can download here.

**Comment by clsid2** [comment]
Latest nightly yt-dlp clearly gives an error here, so end of discussion!
