### ISSUE TITLE
The specified video resolution or height doesn't work for vertical video shot on a cell phone

### ISSUE THREAD

**Issue by xinghongzhou** [clsid2/mpc-hc#2827]
The specified video resolution or height doesn't work for vertical video shot on a cell phone
![image](https://github.com/clsid2/mpc-hc/assets/172034845/0af2f3c9-e4fd-4c4f-b4c8-cd03e80a36de)

**Expected results**
For example, I want to watch 1440p 60fps
Sample video
https://www.youtube.com/watch?v=y6oMutwJQCw

**Actual effect**
![image](https://github.com/clsid2/mpc-hc/assets/172034845/d226fabe-4fc8-4aff-a046-f0d913b3930c)

This problem may also exist for general videos, and further testing is needed to determine.

**Comment by bibsp** [comment]
If developers agree to this, replace ydl max height with **ydl max resolution**.

Resolution will be calculated as the smallest dimension of the video. Then it will properly work for both horizontal and vertical video.

**Comment by xinghongzhou** [comment]
If the set video resolution can be adapted to both horizontal and vertical video, it will be a very cool video viewing experience for users 😜.

**Comment by clsid2** [comment]
fixed

**Comment by xinghongzhou** [comment]
Very good, thank you 👍
