### ISSUE TITLE
Hide mouse cursor completely when playing video fullscreen

### ISSUE THREAD

**Issue by djhazardous** [clsid2/mpc-hc#2828]
Hello, 

I have a PC in my bedroom and when I leave the mouse on my mattress it will make the the cursor move intermittently.

The cursor is only hidden when the mouse is kept still, would it be possible to permanently hide it in full-screen mode until you either double-click or ALT+F1? Unless I am missing something, I can't find an option for this.

Thank you.

**Comment by clsid2** [comment]
Reduce mouse sensitivity in Windows settings.

I am NOT adding options for this.

**Comment by djhazardous** [comment]
Booooooooooo.

> Reduce mouse sensitivity in Windows settings.
> 
> I am NOT adding options for this.

How is that even remotely a solution?
