### ISSUE TITLE
MPC-HC crashes when opening H.264 10bit (high10 profile) MKVs

### ISSUE THREAD

**Issue by SoraKagami** [clsid2/mpc-hc#2832]
### MKVs encoded in `H.264 10bit` with an encoder profile of `high10`  when opened with `MPC-HC v2.2.1` and earlier will crash and remain "in memory" if closed via the windows "X" button until manually terminated using Window's Task Manager.

These same crash inducing MKVs open fine with the old "original" `MPC-HC v1.7.6` installed as part of the old `Combined community Codec Pack v2014-07-13` (external codecs).

#### Steps to reproduce theses crashes using Handbrake
1. Find a video to re-encode using Handbrake.
(_The sample source videos tested were not 10-bit_).
2. Set the Format to `MKV`, Video Encoder to `H.264 10-bit (x264)`, Encoder Profile to `high10`
![Handbrake Format Settings](https://github.com/clsid2/mpc-hc/assets/92629962/cfb0ff53-7fe0-4243-b7f9-f718cc1356ca)
![Handbrake Encoding Settings](https://github.com/clsid2/mpc-hc/assets/92629962/55668638-2647-4f9e-816f-96faa9b082cc)
3. Encode the video
4. Playback the video using MPC-HC v2.2.1 or earlier.

#### Actual Results
`MPC-HC v2.2.1` will crash, while `MPC-HC v1.7.6` with external codecs installed will not crash.
MPC-HC can still be closed using the windows "X" button, however it will remain in memory and prevent other instances of MPC-HC from playing videos until terminated with Windows Task Manager.

#### Expected Results
Both versions of HPC-HC should be able to play H.264 MKVs with an encoding profile of `high10`.
Closing MPC-HC should result in the program cleanly exiting and terminating.

**Comment by clsid2** [comment]
Give link to DrDump crash report.

Remove old CCCP.
Re-install MPC-HC.
Reset settings: Options > Miscellaneous > Reset

**Comment by SoraKagami** [comment]
Thank you @clsid2 .
Removing the old CCCP + resetting the settings fixed it. H.264 10-bit (high10) videos now play without crashing.
