### ISSUE TITLE
In version 2.3.1, OSD not displayed when player is running in `D3D Fullscreen` mode.

### ISSUE THREAD

**Issue by DRON-666** [clsid2/mpc-hc#2834]
When using the `Sync` or `EVR` renderer with `D3D Fullscreen` option enabled and launching player with `/fullscreen` switch (or `Launch files in fullscreen` option) OSD does not appear until you cycle fullscreen off and on or jump to `Next`/`Previous` file.

**Comment by adipose** [comment]
Oddly, I cannot reproduce this.  My D3D OSD is working with EVRCP.

I seem to be experiencing another issue, that Sync renderer cannot enter D3D FS while the video is paused, without issue.  Specifically, it stays black, I cannot click on anything, and it will not close or respond to any input.

And finally, I am experiencing that "Pause" does not always show up on the OSD, but "Play" always does.  Again, I think this affects Sync only, but I'm not 100% sure.

**Comment by adipose** [comment]
MPC-BE does not support D3D FS for Sync Renderer, it seems.  But MPC-HC did support Sync Renderer  / D3D FS / OSD in prior versions.  So it may be a problem with the new OSD or supporting code.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2855

This fixes some of the bugs.  Are you using EVR or EVR-CP?

**Comment by adipose** [comment]
@DRON-666 , can you try this build:

https://mega.nz/file/JZJhRKQb#zXvmKtg7Bih6eabBdTuHuFHlrDGB582ag1qzavOaQCg

It should only affect Sync renderer, but go ahead and test both just in case.

**Comment by DRON-666** [comment]
I am using `EVR-CP` (`EVR` don't support `D3D Fullscreen`). It turns out that this bug only show up if `FullscreenSeparateControls` option is disabled. In old versions OSD working regardless of this option but now option should be enabled (this is the default value and I think that's why you couldn't reproduce this bug).

You can just close this issue.

**Comment by adipose** [comment]
Ah, thanks for the details.  I'll check it out.

**Comment by adipose** [comment]
I'm experiencing a weird problem.  It seems like the `FullscreenSeparateControls` switch behavior is actually reversed when calling from command line.  Can you confirm?

**Comment by adipose** [comment]
@clsid2 

It seems like going fullscreen from command line is not even enabled when `FullscreenSeparateControls` is enabled.  I'm not sure if we should just temporarily allow FS while ignoring `FullscreenSeparateControls` or fix it to support it?

Anyway, I could not reproduce this issue.  I already have `FullscreenSeparateControls` disabled.  Otherwise, it wouldn't have even gone fullscreen.  But I did confirm that Sync was behaving pretty weird.

Recommend close and wait for next report after the Sync renderer changes.

**Comment by DRON-666** [comment]
In fact I don't know what `FullscreenSeparateControls` actually does or why it was disabled in the first place.
For me this bug is "fixed".

**Comment by adipose** [comment]
> In fact I don't know what `FullscreenSeparateControls` actually does or why it was disabled in the first place.
> 
> For me this bug is "fixed".

If you have two screens, it lets you keep the mpc window on the other screen while the video plays fullscreen on your designated full screen monitor. This way you can use the menus and stuff without covering the video.

**Comment by DRON-666** [comment]
After updating to `2.3.1` the `OSD` does not work at all, regardless of `FullscreenSeparateControls` option.

**Comment by adipose** [comment]
> After updating to `2.3.1` the `OSD` does not work at all, regardless of `FullscreenSeparateControls` option.

You mean with the command line switch only?

**Comment by adipose** [comment]
It works for me regardless of how the option is set. Can you upload your settings please?

**Comment by DRON-666** [comment]
And after an hour of "bisecting" this time `EnableWorkerThreadForOpening=0` wins this shameful race.
Minimal reproducer:
```
[Settings]
LaunchFullScreen=1
UpdaterAutoCheck=0
D3DFullScreen=1
EnableWorkerThreadForOpening=0
```
and execute `mpc-hc64.exe file.mp4` command.

**Comment by adipose** [comment]
Oh interesting.  You have launch in fs enabled.

So it doesn't require the ```/fullscreen```?

**Comment by DRON-666** [comment]
In my tests, `LaunchFullScreen=1` + `mpc-hc64.exe file.mp4` is identical to `LaunchFullScreen=0` + `mpc-hc64.exe /fullscreen file.mp4`.

**Comment by adipose** [comment]
Ok. At least that is consistent.

Can you paste your config from about?  Also whatever other info you have.

Which renderer are you using?

**Comment by DRON-666** [comment]
>Can you paste your config from about? Also whatever other info you have.

What info and what config are you interested in?

**Comment by adipose** [comment]
In the about menu you can capture your machine info.

Resolution of the video.

I will look later.  Any info to reproduce is helpful.

**Comment by adipose** [comment]
I can reproduce it now.  The culprit is:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/815713f3-ef59-4fdf-babe-228eb6286d2a)

Can you share why you disable this option?

**Comment by adipose** [comment]
I solved it now.  I don't really see why the advanced option mattered at all.

However, I did find the bug causing this to happen on first run:

https://github.com/clsid2/mpc-hc/pull/2866
