### ISSUE TITLE
Can't open more than 15 MP3 files at once.

### ISSUE THREAD

**Issue by TheDeeGee** [clsid2/mpc-hc#2837]
I always open MP3 files via the Windows Explorer, but for some reason it's limited to 15 files at once.

Is there a way to lift this restriction?

WMP from Windows 10 doesn't have a limit either.

**Comment by clsid2** [comment]
It is a limitation of Windows. There are registry tweaks to increase it.
https://www.tenforums.com/tutorials/94513-fix-context-menu-items-missing-when-more-than-15-selected-windows.html
