### ISSUE TITLE
AVS3 support

### ISSUE THREAD

**Issue by thezoggy** [clsid2/mpc-hc#2844]
I see AVS2 stuff mentioned, but trying out an AVS3 file it does not look like it works. Looks like ffmpeg did add support awhile ago for avs2/avs3 in mkv files.

Googling I see there is a custom version of mpc-hc/vlan that supports avs3:
https://github.com/xatabhk/FFmpeg-avs2-avs3/releases

Is it just fallout from missing id for avs3 so it gets detected and lav loaded correctly?

**Comment by clsid2** [comment]
Not supported by LAV Filters.

I have no interest in these crappy Chinese formats.
