### ISSUE TITLE
COSD::CreateFontInternal() crash

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2845]
`wcscpy_s(lf.lfFaceName, LF_FACESIZE, m_OSD_Font);`

This triggers crash when `m_OSD_Font` is too long. Example: "Segoe UI Variable Display Semibold"
https://drdump.com/DumpGroup.aspx?DumpGroupID=2648675

@adipose
I am not sure what to best approach is to fix this. My first though would be to just filter out too long font names in `CPPageTheme::OnInitDialog()`. What do you think?
I wonder what the proper facename for this long font name is. Perhaps truncation would work?

The font list of my system does not contain any too long names.

**Comment by adipose** [comment]
According to here, simply truncating to 31 chars probably will select the right font:

https://ask.embedded-wizard.de/4877/font-name-limitation-to-32-characters

The error is actually a pretty picky error. There's no buffer overrun, it's just the function's job to let you know that the destination won't be big enough for the string you want to copy. So it would be totally fine to just trap the error and ignore it, if you don't care about the truncation.

With wcsncpy_s, you can set the max to copy to 31, so it won't complain.  It still null terminates the string.

https://github.com/clsid2/mpc-hc/pull/2846
