### ISSUE TITLE
Hardware controls no longer work

### ISSUE THREAD

**Issue by JohnDaleDalton** [clsid2/mpc-hc#2848]
My keyboard has buttons for play/pause, next track and previous track.  These used to work for MPC+HC up to version  but now don't work with version 2.3.0.  These are very useful when playing audio since the application doesn't have to have the focus in order to play/pause.  Please rectify.

**Comment by clsid2** [comment]
options > player > keys > global media keys

**Comment by JohnDaleDalton** [comment]
I stand corrected.  For some reason I managed to have two MPC+HC windows open at the same time.  Once closed and reopened the controls work again Mia maxima culpa.  

I still don't understand why sometimes I manage to have multiple windows open although I have it selected to reuse the same window.

**Comment by clsid2** [comment]
That can happen if you start a new instance of the player by clicking on its exe/shortcut. Re-using only happens if you directly open a file.
