### ISSUE TITLE
[VT False Positive Detection] Win.MxResIcn.Heur.Gen [Fixed]

### ISSUE THREAD

**Issue by Valijon** [clsid2/mpc-hc#2849]
Hi. VirusTotal scans "MPC-HC.2.3.0.x64.exe" and detects "Win.MxResIcn.Heur.Gen" virus.
But "MPC-HC.2.3.0.x86.exe" [is virus free](https://www.virustotal.com/gui/file/16913aaa2e78cbb08aae6425415f1837fbd78248d7f39a292cfaaab3a499f721).

**Afected version:**
MPC version: 2.3.0 x64 exe

**Source:**
https://www.virustotal.com/gui/file/e4b14e3e677d8a1203603bfdad57ad39d68dec9eb44d548c9baa72a4e02c708a

**Comment by clsid2** [comment]
So you are claiming that the other 73 scanners which say it is clean, are wrong? Use your brain.

Some of the scanners on VT are notoriously bad and have a shitload of incorrect detections.

Lesson number 1 when using VT is that when just 1 or 2 scanners detect something, it is almost certainly a false positive.
"Heur" means heuristic and "Gen" means generic. So not even a real detection, but "possible" suspicious code. Not weird for an installer.

Edit 24-6:
Still zero response from MaxSecure after contacting them a week ago and a second time later.
The same false positive has affected several other software products as well, such as 7-zip / Steam / OBS / Brave browser.
It is detecting even our translation DLLs, which contain just strings, and not even any executable code. So it seems a buggy detection related to resources (the Res in MxResIcn).

Edit 27-6:
Finally fixed

**Comment by Ahebah** [comment]
> So you are claiming that the other 73 scanners which say it is clean, are wrong? Use your brain.
> 
> Lesson number 1 when using VT is that when just 1 or 2 scanners detect something, it is almost certainly a false positive. "Heur" means heuristic and "Gen" means generic. So not even a real detection, but "possible" suspicious code. Not weird for an installer.

I mean I know your software doesn't have anything malicious in it, but found this post just through browsing around. The guy posting is just paranoid and I don't fully agree with your statement.

"Lesson number 1 when using VT is that when just 1 or 2 scanners detect something, it is almost certainly a false positive."

Totally wrong, a crypter could be used so no AV DB could detect it. That's highly unlikely in most cases but it's a bit wrong to slate him for it. Be better.

**Comment by HoverCatz** [comment]
> Use your brain.

Dude this is wild.
