### ISSUE TITLE
Replay black screen

### ISSUE THREAD

**Issue by Sagmrth8** [clsid2/mpc-hc#2856]
When file reaches the end and replays, it the footage becomes black, I need to close the file and open it again to show up

**Comment by clsid2** [comment]
Recent generation Intel GPUs do not have hardware DirectX9 support. They use d3d9on12 compatibility layer to translate DX9 into DX12. That has several bugs.

To solve this problem you need to use MPC Video Renderer (MPCVR). This renderer uses DirectX 11.
MPCVR is included in the [latest version](https://github.com/clsid2/mpc-hc/releases) of MPC-HC.
You can enable it here:
MPC-HC options > Playback > Output > Video renderer

In LAV Video decoder settings, change hardware decoder to D3D11.
MPC-HC options > Internal Filters > Video decoder (button at bottom of page)
