### ISSUE TITLE
MPC goes to background when minimized in Windows 11

### ISSUE THREAD

**Issue by urmomuwusus** [clsid2/mpc-hc#2857]
Upon minimization, the program goes to the background and is inaccessible.  I have to go to task manager to end the program, rerun it and make sure I don't minimize it.

**Comment by ArcticGems** [comment]
I don't have this problem and I use MPC-HC (64-bit) 2.3.0.18 (38208135c) on Windows 11.

Enable tray icon until this is diagnosed: Options...->Player->Other

**Comment by clsid2** [comment]
Nobody else has reported such issues.

**Comment by adipose** [comment]
Maybe you have a taskbar on another screen?

Check the notification area as mentioned.

**Comment by adipose** [comment]
Also if you can record a short video of it happening with animations enabled it might be useful.
