### ISSUE TITLE
Extract video frames option

### ISSUE THREAD

**Issue by wdsongama** [clsid2/mpc-hc#2858]
I'd love if you could implement an option to extract all the frames from a video as they're being shown on MPC-HC. That would be very useful for me because MPC Video Renderer is the best I've seen when it comes to HDR tonemapping, and there's currently no frame extraction command (afaik) that supports exporting frames in HDR, or converting them to SDR when exporting. I could convert the whole video to SDR first, but getting a very good result takes a lot of processing time, even with a software like Hybrid, for example. I train AI super-resolution models, so I need the frames in SDR since no architeture supports HDR images as well. I also do not own an HDR-capable monitor lol, so your help would be very much appreciated.

**Comment by clsid2** [comment]
Such tasks are a job for AviSynth/VapourSynth.
