### ISSUE TITLE
FullscreenSeparateControls disables /fullscreen command-line switch

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#2859]
If we are going to leave this as-is we might want a note on the advanced option and command-line notes.

Ideally it would just work.  If I remove the code that disables it, it just goes FS normally, without separate controls.  Perhaps that is preferred compared to silently failing?

**Comment by clsid2** [comment]
That is a bug. It should not prevent fullscreen.

FullscreenSeparateControls should not do anything when fullscreen monitor is same as main monitor.
And when it is different monitor, it should create fullscreen window and separate main controls window.

**Comment by adipose** [comment]
10-4, I'll look at it.

**Comment by adipose** [comment]
FullscreenSeparateControls

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2860
