### ISSUE TITLE
"Limit video proportions on resize" shouldn't apply to audio files

### ISSUE THREAD

**Issue by thericle** [clsid2/mpc-hc#2861]
Previously, that setting only applied to video files, and even if it was enabled, you were still able to freely resize windows with audio files. After a recent update, it's not possible anymore.

I think it isn't useful because audio doesn't even have a ratio to maintain.

My use case is this: many times I listen to long audio recordings while studying. It's useful for the time bar to be as long as possible because that way it's easier to find the correct timestamp, but the height of the window can be as small as possible so I can see my notes.
As it is now, to do this with that setting enabled (which is useful for video files), the program's window must unnecessarily fill the screen.

My version: 2.3.0

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2868

I agree with you.  This patch will disable it for audio-only, with a caveat.  If you have cover-art enabled, and the audio has cover-art, it will honor proportions.  If you want to avoid this you can disable cover-art.
