### ISSUE TITLE
Unable to find audio track

### ISSUE THREAD

**Issue by hyyman** [clsid2/mpc-hc#2863]
Hello,

when I want to see some videos on MPC-HC I only find one audio track when there are several.
I've been able to verify this using other software, if anyone has a solution please let me know.

thanks in advance

**Comment by clsid2** [comment]
I assume you are talking about .mkv files?

Download MkvToolNix utility. Use that to set the audio tracks as enabled. They are currently set as disabled (hidden).

Other software such as VLC does not properly follow the Matroska specification. So it is in fact, that other software is "broken". This whole situation is fault of persons who created the files with incorrect flags.
