### ISSUE TITLE
Screenshot Feature

### ISSUE THREAD

**Issue by AverageUnknown** [clsid2/mpc-hc#287]
Add the option to take screenshots in either DAR or the Default that it is now which is SAR

**Comment by adipose** [comment]
Can you try this build and see if it at least does DAR correctly?

https://mega.nz/file/1M5zkCKB#cskJAyWe6RjkCDOKdg1_tlgwUvoicExcRR7Ts6vJHOw

**Comment by AverageUnknown** [comment]
@adipose no it does not work, just downloaded and tested now.

**Comment by adipose** [comment]
Thanks.  Do you have a video / screenshot output you can give me to compare and test against?

**Comment by adipose** [comment]
I used the sample file from here: https://forum.videohelp.com/attachments/4623-1291854069/720x576dar16x9.avi

Using the new build, the saved image is:

![720x576dar16x9 avi_snapshot_00 02 205](https://user-images.githubusercontent.com/3324395/81359589-6e63a000-908e-11ea-99d0-3100c3ba9a89.jpg)

Using previous builds of mpc-hc, it looks like this:

![720x576dar16x9 avi_snapshot_00 01 436](https://user-images.githubusercontent.com/3324395/81359591-6efc3680-908e-11ea-9240-ab85d1efe1af.jpg)

So it seems to me it's correcting for DAR.

Note that when using MadVR, it used DAR already, but EVR is now working, as well.

**Comment by clsid2** [comment]
It works with plain EVR, but not with EVR-CP.

**Comment by adipose** [comment]
In EVR-CP, I cannot change this setting, so it's displayed wrong while playing:

![image](https://user-images.githubusercontent.com/3324395/81484148-51e37700-91f8-11ea-80ca-7fc19ea0d25d.png)

With regular EVR I can change this and it corrects for the AR.

**Comment by adipose** [comment]
Well, never mind. After trying again, it let me.  And it does export wrong.

**Comment by adipose** [comment]
Maybe I had it backwards.  But I can't get regular EVR to adjust for the AR, now.

**Comment by clsid2** [comment]
A common situation is that the file container specifies a Display AR (DAR) which is different from the Stream AR (SAR) of the encoded video bitstream. In that case the decoded video is stretched to DAR by the video renderer.

That menu allows overriding the AR. Default behavior is using DAR. Screenshots are currently taken with SAR.

Possibility would be to implement GetCurrentImage function:
https://sourceforge.net/p/mpcbe/code/HEAD/tree/trunk/src/filters/renderer/VideoRenderers/EVRAllocatorPresenter.cpp#l1250

**Comment by adipose** [comment]
Yes, actually I was just importing that. The whole patch is going to be an import of mpc-be code.

**Comment by adipose** [comment]
Sadly, the code path doesn't seem to enter that function.  Instead it uses GetCurrentFrame() from MainFrm. This appears to be the case for mpc-be as well.  However, the GetDIB function in mpc-be differs substantially, and corrects for AR.

**Comment by adipose** [comment]
So, after some testing, it seems mpc-be is doing a better job here before the screenshot is even taken.  By default it honors the DAR, but mpc-hc is not (both using EVR-CP).  So perhaps something implemented in mpc-be EVR-CP that is missing in mpc-hc.  See screenshots below:

![image](https://user-images.githubusercontent.com/3324395/81506079-ce359300-92a8-11ea-978c-d4014c0be5c0.png)


![image](https://user-images.githubusercontent.com/3324395/81506095-e7d6da80-92a8-11ea-8719-999486a4461e.png)

**Comment by clsid2** [comment]
MPC-HC correctly displays it as a square here with DAR selected and EVR(-CP).

**Comment by adipose** [comment]
That's a relief. Now I wonder why mine is not working.

**Comment by adipose** [comment]
Problem was in debug lite mode.  In regular debug mode, it works fine.  I'm not sure that debug lite is supposed to work differently provided a recent build of debug has been done?

**Comment by adipose** [comment]
Here's a new test build.

https://mega.nz/file/9UIAjKwJ#49DuQG76vvHshzLhX-UQ2z325Ji_J37jReZoWmqUdVs

**Comment by AverageUnknown** [comment]
it works!

**Comment by AverageUnknown** [comment]
@clsid2 with this be merged to master later on?

**Comment by clsid2** [comment]
I just merged it a few minutes ago. We use develop branch.
