### ISSUE TITLE
Video freezes on input with madvr

### ISSUE THREAD

**Issue by PuffaloBuffalo** [clsid2/mpc-hc#2871]
Whenever I am using madvr as the renderer, upon opening capture device the display window will be black. I can fix this by pausing and resuming. Also, whenever the signal is lost (during resolution/timing changes), the display will freeze the frame before it picks up the input again. Pausing and resuming fixes this as well. I do not have this issue with mpc video renderer.

I am currently using Windows 11 and an AMD RX 6600 xt graphics card.

**Comment by clsid2** [comment]
I can not help you with MadVR problems.

Here is MadVR own bug tracker:
http://bugs.madshi.net/view_all_bug_page.php

@adipose
Are you able to reproduce this?

**Comment by adipose** [comment]
Will test it soon.

**Comment by adipose** [comment]
I was unable to reproduce it.  I'm using madvr 0.92.17 and a DVB capture card.

**Comment by clsid2** [comment]
Probably just buggy madvr behavior.

Maybe only happens with specific madvr settings such as "delay playback until queue is full" or presenting several frames in advance.

@PuffaloBuffalo
Try with madvr settings reset to default.

**Comment by PuffaloBuffalo** [comment]
I reset the settings and the issue persists. I also tried uninstalling and reinstalling mpc-hc and madvr. I posted on the madvr bug tracker and the dev responded that madvr doesn't support capture cards

I'm using madvr 0.92.17 and a datapath vision capture card

**Comment by adipose** [comment]
> the dev responded that madvr doesn't support capture cards

Perhaps a misunderstanding.  You are not using madvr for the capture card itself.  Anyway, if you can find an older build of MPC-HC that works, perhaps we can identify an issue.

I could not reproduce after several attempts.
