### ISSUE TITLE
feature request: pause while dragging seekbar

### ISSUE THREAD

**Issue by manassm** [clsid2/mpc-hc#2873]
First of all, thank you for your generous work. This has been very useful tool for me.
I wished that the video would pause temporarily while clicking on the seekbar and starts playing again once I release the seekbar (similar to youtube), since dragging the seekbar while video is playing causes annoying haulting noises. 

Thank you for your consideration.

**Comment by adipose** [comment]
Edit: reread it. I get it now.

I can look at an advanced option.  I have experienced the problem myself.

My approach is to hit the spacebar before clicking.

**Comment by manassm** [comment]
Thank you for the help. 
Do you have any estimate of when the next .exe will be released with this build?
(I am not familiar with git/programming, so I apologize if I make little sense.)
Also, would the feature needed to be turned on in the specific setting page?

**Comment by clsid2** [comment]
it is ready when it is ready
