### ISSUE TITLE
Favourite Bookmark - Wrong audio track selected

### ISSUE THREAD

**Issue by Tlentlen** [clsid2/mpc-hc#2876]
Hi,
to reproduce the issue (in my case) this is the sequence.

- Drag a video file (.mkv, 1920*1080, VC-1, 4 audio tracks, 13 sub tracks)
- Select the x Audio track (say number 3)
- After a while create a Fav bookmark on the current position
- Close the player
- Reopen the player
- Select the Favourite bookmark created earlier
- The Audio track selected is always Number 1 (Not 3 as it was at the moment of bookmark creation)

**Comment by clsid2** [comment]
Track selection is not yet remembered for bluray.

In the settings of the internal splitter you can configure your preferred languages. With that you can make it select the desired track automatically in most cases.

**Comment by Tlentlen** [comment]
Sorry,
I just corrected my post.
It was not a bluray I was referring to but a standard .mkv file.

ps.
Remembering track selection for BD would be nice too.

**Comment by clsid2** [comment]
Options > Player > History

**Comment by Tlentlen** [comment]
Mmm, ok but I don't see any option regarding remembering audio track?

https://images4.imagebam.com/eb/91/95/MEUAPAX_o.png

**EDIT:**
Ok, solved.
It seens the functionality were not perfectly functioning
because I overwrite the files in the same (old version) directory.

I downloaded and decompressed in a brand new directory and now it seems to work.
(a bit of a strange behaviour).

Thank you for your support
