### ISSUE TITLE
Fallback Default OSD Font

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2880]
If the currently used OSD Font is updated or deleted at system level, MPCHC reverts to the first font in the dropdown menu. It may make more sense to return to the first default value (i.e Segoe UI), as the font in the first row (alphabetical order) may not be a useful font.

Steps:

- Use OSD font, i.e "Zilla Slab"
- Update or remove the font on system
- MPC-HC fallback ~~first~~ font ~~at OSD Font dropdown menu.~~

![resim](https://github.com/clsid2/mpc-hc/assets/3073922/e718532d-7231-4b6f-a4eb-5691a7ef9925)

Probably it doesn't fallback to first font because it looks different. I can't track it.
![mpc-hc64_z5n1ag9SGc](https://github.com/clsid2/mpc-hc/assets/3073922/561a5fba-265a-4099-b908-c630adc66be2)
![mpc-hc64_s5olha7XGX](https://github.com/clsid2/mpc-hc/assets/3073922/fb2eef2c-6ea1-4ba5-9d3e-aabfeb0ab918)

Sample ani.... font.
![mpc-hc64_x2k9k9GK89](https://github.com/clsid2/mpc-hc/assets/3073922/3668068e-5313-4865-9031-fd05093439da)

[Sample font.zip](https://github.com/user-attachments/files/16006620/Sample.font.zip)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2881

**Comment by xLn2** [comment]
It looks like it's trying to use parts of the "Zilla Slab" font or something similar. In the option page it seems it fallbacked to the default setting, but since the setting may not have been applied, I can make a few settings changes and apply them and Segoe UI is now used.

![mpc-hc64_QeOnMmZxC1](https://github.com/clsid2/mpc-hc/assets/3073922/1eefd62a-77b7-4e72-b7df-440720ac8e78)

![mpc-hc64_joA9Len0go](https://github.com/clsid2/mpc-hc/assets/3073922/979fd8de-415b-4c84-8b40-1bd04418e542)

![mpc-hc64_7CzuS4AlU2](https://github.com/clsid2/mpc-hc/assets/3073922/fae599bf-eb31-4f4d-810a-5965fda33163)

[Zilla_Slab(1).zip](https://github.com/user-attachments/files/16054312/Zilla_Slab.1.zip)

**Comment by adipose** [comment]
Right.  I updated the settings page.  I didn't put anything in place to correct it in real time.
