### ISSUE TITLE
Media Info doesn't scale

### ISSUE THREAD

**Issue by HommerDK** [clsid2/mpc-hc#2883]
The **MediaInfo** tab under File -> Properties doesn't scale when resizing the Properties window.
(The Details and Clip tabs _do_ scale)

![MediaInfo_scaling](https://github.com/clsid2/mpc-hc/assets/139130017/5c9c0165-c4c4-4721-89e0-d8e6de9aae44)

**Comment by clsid2** [comment]
Update to latest version.
