### ISSUE TITLE
[BUG] Japanese filename is considered worm

### ISSUE THREAD

**Issue by Kochise** [clsid2/mpc-hc#2889]
Hi, using yt-dlp to download playlists and videos, I've encountered a strange behavior here :

https://www.youtube.com/watch?v=9I4EKXmeEEs (09 - JAPANESE シティポップ‏‏‎‏‏‎ ‎City Pop⧸Funk Compilation‏‏‎‏‏‎ ‎B.0-9I4EKXmeEEs.m4a)

When trying to open the file with MPC-HC (64 bits) 2.1.6 (4a9c40908) I get :

![capture_20240629_204121_001](https://github.com/clsid2/mpc-hc/assets/23077417/d84f2f98-b855-4b2a-89a7-ac53c5ee047b)

You can try other videos from the channel as well, some are ok, some are blocked.

Regards.

**Comment by clsid2** [comment]
Edit: that message is coming from Total Commander.

**Comment by Kochise** [comment]
Thank you for narrowing down the issue.
