### ISSUE TITLE
Is there any way to differentiate the Spanish subtitles from the Latin Spanish subtitles?

### ISSUE THREAD

**Issue by Vorffeed** [clsid2/mpc-hc#2890]
Well ^_^
Is there any way for mpc-hc to differentiate subtitles by region code?
I'm tired of having to remix all the videos to put the subtitles in Castilian Spanish if the Latin Spanish is in front of the Castilian Spanish subtitles for it to detect them >< 

since some time ago I use lav-filter with this code for audio and subtitles *:spa|f,spa:spa|d,spa:off,jpn:spa,jpn:und,jpn:jpn:jpn,jpn:jpn:on,:spa,:jpn,und:und:spa,und:lat,jap:lat,lat:off,*:*|df 
but this code makes that if the latin is above the spanish, it takes the latin because it doesn't differentiate which is which, and if I change it to es-ES it keeps doing the same even if the spanish has that region code and the latin has the code es-419.
and I always have to remux the videos to change the latin sub from spanish to tag latino.

**Comment by clsid2** [comment]
Your settings include stuff like "jpn:jpn:on" which is incorrect. There is no "on" tag, plus the second colon is wrong.

Fix and simplify. Then add edge cases later.

You can see the three letter language codes of the track here:
Menu > Play > Filters > LAV Splitter Source

**Comment by Vorffeed** [comment]
I have corrected it, but we are still in the same, without being able to use the region tag code es-es, es-419, in,hi, etc... it is impossible, I have also been trying as it says in the lav-filtter *:eng@word commands but it is totally impossible because everyone names the subtitle tracks as they want, but respecting the region code.
I think I'm going to give up, I've been all afternoon without getting it to work well this way, to get the main audio in Spanish to show forced subtitles in Spanish, if there are not in Latin, and if there are not it doesn't show subtitles, if there is no audio in Spanish and there is Japanese it shows the complete ones in Spanish not the forced ones and if there are not the complete ones in Latin and not the forced ones, but of course if each one renames as he wants it's impossible.
 In the end I'm going to have to keep remixing everything to put the labels and get the configuration right.

**Comment by clsid2** [comment]
LAV Splitter does not support the extended region language tags (BCP47).
