### ISSUE TITLE
launch in fullscreen bug

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2891]
@adipose
Regression due to recent changes.

Toolbar does not auto-hide.
Video does not show until moving mouse down to toolbar and then away to make it hide.

**Comment by adipose** [comment]
D3D or regular FS?  Second screen or same screen?

**Comment by clsid2** [comment]
regular on main monitor.
happens with all renderers.

**Comment by adipose** [comment]
Can't reproduce with MPC-VR. FS settings:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/3e8818e9-a1fe-4778-a228-d0384f78dddc)

Edit, I see it was "launch in fs."

**Comment by adipose** [comment]
After testing again, I still couldn't reproduce, even with /fullscreen flag.  MPC-VR was my VR.

**Comment by clsid2** [comment]
FullScreenSeparateControls = True
I haven't tested in debugger yet.

**Comment by adipose** [comment]
I found something, with EVR-CP and FSSC=True.  What happened is the toolbar didn't show, and didn't show even when I moused over.  Kind of the opposite of your description but buggy nonetheless.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/commit/9090b3bddebfd27edab0f5b0c0e7e675159ebe9d

It seems related to this commit, which fixed the problem with /fullscreen not working at all when FSSC=True.

**Comment by clsid2** [comment]
`m_fStartInFullscreen` is used when fullscreen in a separate window (dedicated fs window). So should be renamed to `m_fStartInFullscreenSeparate` or something similar.

https://github.com/clsid2/mpc-hc/commit/9090b3bddebfd27edab0f5b0c0e7e675159ebe9d needs to be adapted to check in FSSC branch if current monitor is same as fullscreen monitor. If same monitor then use `ToggleFullscreen` (like when FSSC disabled), and if different set `m_fStartInFullscreen=true`. I think that would do it.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2892

Yes, I came to a similar conclusion.  See if this patch works for you.

Problem was trying to launch FSSC when it wouldn't apply.

**Comment by adipose** [comment]
Rename would be a good idea, it does appear it refers to separate FS window only.
