### ISSUE TITLE
slave commands open new instance regardless of user setting in 2.3.1, files are loaded twice

### ISSUE THREAD

**Issue by hadu-boired** [clsid2/mpc-hc#2895]
for example a scripted environment that runs a single instance with option `/slave "hwnd"`, to receive copydata structures such as custom OSD message from that handle. new files would continue loading in that instance, in 2.3.1 this gets replicated to a new instance and the slave, simultaneously loading it twice.

**Comment by clsid2** [comment]
How can it open a new instance if you are sending a window message to an existing instance?

If you are running the exe a second time to send a message, that would technically be wrong use of the API. Although that still works fine here as well. A recent change in the code was to use a 5 seconds timeout when send a window message. Perhaps there is a delay when closing the currently running file?

Here is how to use slave API:
https://github.com/clsid2/mpc-hc/blob/develop/src/mpc-hc/MpcApi.h

**Comment by hadu-boired** [comment]
i explained that poorly, what i mean is a resident application which manages a single slave instance, send messages or relaunch it if need be, no file operations are taking place at that point. then it runs the exe again to open new files, just never had to implement `CMD_OPENFILE` if the CLI already respects single instance.

but you are onto something now that i look at it, the double loading only happens if i send a window message just before running shell commands. guess my options are either to use the api, or do never send a message within 5s of such executions. the former is problematic when relying on a third party URL extractor to launch mpc, the latter is not ideal for ux.

**Comment by clsid2** [comment]
Once you launched the exe as a slave you should control it with window messages only.

Running exe with slave parameter a second time will now always create a new instance. I changed that to allow multiple slave instances.

If you want to open a new file from command line, while an instance is running, then you should omit slave parameter. But correct way is to use window messages. That to avoid doing multiple things simultaneously.

**Comment by hadu-boired** [comment]
> Running exe with slave parameter a second time

would defeat the purpose of single instance, the issue here is it limits what we can do with that instance now. my goal is just to have some ui feedback when a new file is loading, which could take some time for streaming endpoints.

**Comment by clsid2** [comment]
You can query state with the API.
