### ISSUE TITLE
Your language pack will not work with this version.

### ISSUE THREAD

**Issue by jochenwuerfel** [clsid2/mpc-hc#2896]
Hi,
downloaded the latest version yesterday and noticed today that the UI was in English.
Changed it in the options and got this error:

![lang](https://github.com/clsid2/mpc-hc/assets/101515602/9a018319-a4a2-4ce0-84bf-74558098e5bc)

/edit stats

MPC-HC (64-bit)
---------------

Build information:
    Version:            2.3.2 (605081abb)
    Build date:         Jul  1 2024

LAV Filters:
    LAV Splitter:       0.79.2.18
    LAV Video:          0.79.2.18
    LAV Audio:          0.79.2.18
    FFmpeg compiler:    MinGW-w64 GCC 13.3.0

Operating system:
    Name:               Windows 10 (Build 22H2)
    Version:            10.0.19045 (64-bit)

Hardware:
    CPU:                AMD Ryzen 5 3600 6-Core Processor
    GPU1:               NVIDIA GeForce GTX 1080 Ti (driver version: 31.0.15.5244)
    GPU2:               NVIDIA GeForce GTX 1080 Ti (driver version: 31.0.15.5244)
    Monitor:            \\.\DISPLAY1 - S2721HS (DP) [1920x1080 32-bit 96 DPI]
    Monitor:            \\.\DISPLAY2 - S2721HS (HDMI) [1920x1080 32-bit 96 DPI] - [Current]

Text:
    Scale Factor:       1.000000
    Ansi Codepage:      1252

**Comment by MarGeb1** [comment]
I can confirm this for my devices (Windows with German language).

**Comment by jochenwuerfel** [comment]
Check most of the other languages, the same - only English working.

**Comment by xLn2** [comment]
Did you check recent issues? https://github.com/clsid2/mpc-hc/issues/2893#issuecomment-2200937022
2.3.2.1 should be fine.

**Comment by jochenwuerfel** [comment]
Oh, didn't checked the closed issues.
2.3.2.1 is working correctly 👍
