### ISSUE TITLE
Seeking video, showing Play OSD

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2897]
Version 2.3.2
Please don't say it is intentional. It is annoying.

https://github.com/clsid2/mpc-hc/assets/98865389/f24ff005-7f09-456a-83e5-e1ffb2924bc2

**Comment by NBruderman** [comment]
I think this happened because of the recent change that pause the video on seek. So probably the OSD takes it as an intentional pause, and then show the "Play" message when it gets resumed. I don't think this is the intended behavior.

**Comment by adipose** [comment]
Hmm, unintended consequence.  Change this:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/c7673e4f-f35f-43b5-b716-1e57d92bc3c1)

**Comment by NBruderman** [comment]
> Hmm, unintended consequence.  Change this:
> 
> ![image](https://github.com/clsid2/mpc-hc/assets/3324395/c7673e4f-f35f-43b5-b716-1e57d92bc3c1)
> 
> 

Is this fixable without Disabling the pause on seek?

**Comment by clsid2** [comment]
Fixed

**Comment by adipose** [comment]
> > Hmm, unintended consequence.  Change this:
> > ![image](https://private-user-images.githubusercontent.com/3324395/345154918-c7673e4f-f35f-43b5-b716-1e57d92bc3c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NDY3OTIsIm5iZiI6MTcxOTk0NjQ5MiwicGF0aCI6Ii8zMzI0Mzk1LzM0NTE1NDkxOC1jNzY3M2U0Zi1mMzVmLTQzYjUtYjcxNi0xZTU3ZDkyYmMzYzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMTg1NDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTg5ZDA3ODBhMDhiMDM0YmU2NjhlMmI0NDA2ZmZiZmY0NjVlMDlkY2E0ZWUyNDMzZmM5OTc1NzFhODljMWFmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BNWS8bNuwI5a_IONxpSAa6viOAlYCviaiHieqKzFIFU)
> 
> Is this fixable without Disabling the pause on seek?

It is theoretically fixable; however the routines that pause and play automatically update the OSD.

**Comment by adipose** [comment]
Looks like it's fixed.  I wasn't sure if it was safe to call `MediaControl` directly.

**Comment by bibsp** [comment]
Another issue related to this.
Look at the Play/Pause buttons.
Disable `PauseWhileDraggingSeekbar` fixes the issue.

https://github.com/user-attachments/assets/0cd713c9-eb29-42f1-9674-35d34b3a1d98

**Comment by clsid2** [comment]
That is a consequence of the option and can not be fixed. There is no way to tell the difference between a click and the start of a potential drag. It pauses as long as the button is pressed down.

**Comment by bibsp** [comment]
Add a 250ms timer.
If we click and hold the mouse for 250ms then it will consider this click as start of drag. Then after 250ms it will pause the playback and toolbar button will indicate pause.

Otherwise normal click will be normal click. Toolbar button will not indicate pause for a fraction of second.

If this is logical and possible, please implement it. It's not urgent. Whenever you have some time.
