### ISSUE TITLE
Certain video causing MPC-HC to crash on load

### ISSUE THREAD

**Issue by vermian** [clsid2/mpc-hc#2899]
Here is the error:
![mpc-hc error](https://github.com/clsid2/mpc-hc/assets/17242410/77e5a1af-40de-4324-b914-a24bf8d339ac)

Here is the video that causes the crash:
[webm_page_bg_english.webm](https://github.com/clsid2/mpc-hc/assets/17242410/a4beec89-e95a-420b-8a6c-76d5f67a915a)

Using Windows 10 x64. MPC-HC v2.3.2 x64. It should be using the internal filters according to my settings. I don't have any external filters added in MPC-HC. Happens with both EVR-CP renderer as well as madVR. Tried remuxing the webm video into an mkv container and same error occurs. Never seen this error before except with another variant of this video (Steam store background).

 Tried with MPC-BE using its internal filters and it plays fine there.

Edit: seems like the issue happens when UseSeekPreview=1 which you can change in Options -> Player -> User Interface -> Seekbar -> Hover type -> Video Preview.

**Comment by bibsp** [comment]
Video plays here. BUT, with AMD GPU video has glitch when using EVR-CP. MPC-VR fine.
*Nvidia all fine.*
This is the result of AMD:
![Screenshot (293)](https://github.com/clsid2/mpc-hc/assets/98865389/4e531106-725f-4e8f-9b16-fe150d2a6ef9)
![Screenshot (294)](https://github.com/clsid2/mpc-hc/assets/98865389/b4105320-753b-48b6-86ab-3fcae241a96c)

**Comment by vermian** [comment]
Hmm, I tried again with a default settings .ini and it does seem to work fine in EVR-CP, madVR, and MPC Renderer using a Radeon GPU. I'll try to narrow down the issue to see if it's a bug or something else weird with my settings. Thanks.

**Comment by vermian** [comment]
Looks like the culprit was UseSeekPreview=1 which you can change in Options -> Player -> User Interface -> Seekbar -> Hover type -> Video Preview. Seems like an MPC-HC bug to me.

**Comment by clsid2** [comment]
Seek preview uses EVR-CP.

File plays fine here with EVR-CP, and I can not fix AMD bugs.

Looks like some kind of chroma scaling issue. Possibly due to the uneven height.
