### ISSUE TITLE
"Mirror" and "Flip Vertically" don't work with MadVR

### ISSUE THREAD

**Issue by in4u** [clsid2/mpc-hc#290]
The options `PnS Rotate Y-` and `PnS Rotate X-` used to work well with `MadVR` as renderer until a recent update where they were included in the menu and renamed as `Mirror` and `Flip Vertically` respectively.

These options work fine with `Enhanced Video Renderer (custom presenter)` as renderer. But if `MadVR` is used then neither the keyboard shortcuts nor the relevant `Pan & Scan` menu options `Mirror` and `Flip Vertically` have any effect.

**Comment by clsid2** [comment]
There is no functional change due to the menu addition. Previously madVR also only supported rotation.

**Comment by in4u** [comment]
On one of my systems I must have switched over to EVR and assumed that it was MadVR playing well with rotate options until now.

Thanks for letting me know. I will stick to EVR only.
