### ISSUE TITLE
theming glitch with playlist scrollbar

### ISSUE THREAD

**Issue by BAXSD** [clsid2/mpc-hc#2903]
I opened a folder with music videos to play. There are about 180 videos. When I try to navigate/scroll through the entire playlist it stops way before I get to the last video in the playlist. Is there a limit on how many files you can navigate/scroll through the playlist or is it a bug? Anyway I hope you can address and fix this issue?

Second. Have you ever thought about adding a search function for playlist? It would be nice to search for the video you want to play but dont want to scroll through the entire playlist. Specially when there are a lot of videos.

Thanks in advance :)

**Comment by clsid2** [comment]
There are no plans for adding new functionality.

No issue with scrolling large playlist to end here.

@adipose
I did notice a small issue with focus. If focus is on player, and you click on playlist scrollbar, then playlist does not get focus, so mouse scrollwheel does not work. Clicking on a playlist entry does give proper focus.

I also noticed a glitch with modern theme. Start player with playlist hidden. Then show playlist. Then use scrollbar. It shows classic style scrollbar intermittently. Best visible with dark theme.

**Comment by BAXSD** [comment]
@clsid2 
Thanks for the quick reply.

To the issue im having. How many files in your playlist have you tested with? More than mine? I can only navigate to the 129th file then it stops and I cant go further. 

Second. Can you scroll with the mouse wheel through the playlist? Does not work for me.

Is there a setting related to this issue and why does it not work for me but for you? It is strange. Im not sure what I can do about this.

EDIT:
This happens when you go via "Navigate" tab then "Playlist". When I activate Playlist via "Show" tab setting then it shows the playlist above the Seekbar. From there it works but not from the previous way mentioned. Is this they way it works?

**Comment by clsid2** [comment]
You can drag the playlist to the position you want. Even outside of player.

Navigate menu is unrelated to playlist, so I don't know what you are doing.

Click inside playlist window if you want to use scrollwheel.

**Comment by BAXSD** [comment]
``

> You can drag the playlist to the position you want. Even outside of player.
> 
> Navigate menu is unrelated to playlist, so I don't know what you are doing.
> 
> Click inside playlist window if you want to use scrollwheel.

Sorry I have misunderstood where to use the playlists feature. I get it now. I close this as solved. Thanks a lot :)

**Comment by xLn2** [comment]
Maybe these are focus related issues:

1. On Playlist scrollbar M Wheel usage also lead to Volume control (Just happens on Modern Dark theme)

2. M Wheel usage while editing Playlist item name also control volume. (Happens all case)

**Comment by adipose** [comment]
> I also noticed a glitch with modern theme. Start player with playlist hidden. Then show playlist. Then use scrollbar. It shows classic style scrollbar intermittently. Best visible with dark theme.

I couldn't reproduce in windows 10.  Was it 7?

**Comment by clsid2** [comment]
Yes W7. Might take a few tries.

**Comment by adipose** [comment]
I found it's only happening when it's (initially) not visible and is docked.  I'm not sure why it only affects win7, but it seems to have to do with the initial scrollbar hide region happening before the window is actually rendered.  Try this:

https://github.com/clsid2/mpc-hc/pull/2919
