### ISSUE TITLE
[Feature Request] Pausing the video sounds while holding buttons to seek

### ISSUE THREAD

**Issue by NBruderman** [clsid2/mpc-hc#2906]
In https://github.com/clsid2/mpc-hc/pull/2882 pausing while seeking in the timeline was implemented.
My request is basically the same behavior, while holding the arrow buttons to seek, as it's still play sound while seeking. 
I think the logic supposed to be - If you keep the key pressed long enough for more than one jump, 
the video should be paused until the key is released. 

I think this function is a really nice addition, and it will be great to have it for the other seek method as well

**Comment by clsid2** [comment]
Not possible since there is no action on key release.
