### ISSUE TITLE
Youtube videos in a playlist do not resume when MPC-HC is restarted

### ISSUE THREAD

**Issue by markclowes** [clsid2/mpc-hc#2907]
When using the Options "Remember last playlist" and "Remember File position", opening MPC-HC and clicking play will resume playing the file that was last open at the last position within the playlist.

If the video that is playing within the playlist when MPC-HC quits is a youtube url (and presumably any other site supported by yt-dlp), when MPC-HC is restarted instead of the youtube video playing, the playlist restarts from the first video.

**Comment by clsid2** [comment]
Fixed
