### ISSUE TITLE
Generating a huge playlist is slow

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#291]
https://trac.mpc-hc.org/ticket/6703

Adding a large amount of files to a new playlist can be slow. I suspect it is because the playlist file is written to disk after each addition. So a possible solution would be to delay that action.

**Comment by adipose** [comment]
What's the method of adding to the playlist in this case?

**Comment by adipose** [comment]
First thing I noticed is all these entries get added to Navigate/Playlist/...

After about 5000 entries the AppendMenu call starts to fail.  But even adding 5k entries to a submenu probably isn't terribly efficient.

![image](https://user-images.githubusercontent.com/3324395/75732537-92c68900-5ca7-11ea-9a4b-3e1be43016c8.png)

Second thing is every dynamic entry has the theme applied, if it's turned on--could add up for thousands of entries.

**Comment by adipose** [comment]
Well, it didn't seem to make much difference when I removed it.  But I ran an mpcpl playlist with 10k entries, and it only took 6 seconds (SSD).

Not quite sure what the bug was referencing in terms of performance.

**Comment by clsid2** [comment]
The issue the user has is only with the initial creation of the playlist. Loading a saved mpcpl file is done within a few seconds.

Right click on folder > Add to MPC-HC playlist

User mentioned a lot of HDD activity, and has quite a large drive with 16TB.

**Comment by adipose** [comment]
@clsid2 

I did some profiling, and the majority of time is spent running GetContentType on each individual file.  Maybe an optimization to do a more limited version of that?  It mostly needs to run it to determine if it's another playlist or if there is a redirect.

**Comment by clsid2** [comment]
Good find. I improved this function to avoid doing a file read.

**Comment by adipose** [comment]
Nice.  It may also be worth limiting the playlist added to the Navigate/Playlist submenu to a sane max, like 512.  In my testing it fails at ~5000 entries, which is far more than someone could reasonably scroll through in a menu.

The AppendMenu returns FALSE, but GetLastError() returns zero, so it's just some undocumented limit or a dynamic memory limitation that we should avoid.

This is the closest I could find to an answer about that:

https://microsoft.public.vc.mfc.narkive.com/5362ECBJ/why-appendmenu-fails

**Comment by clsid2** [comment]
Good idea. Even 512 is a large amount for a menu. A smaller maximum would be fine with me as well.

**Comment by adipose** [comment]
OK, here's a quick patch for that:

https://github.com/clsid2/mpc-hc/pull/302
