### ISSUE TITLE
Automatic subtitle download for streams

### ISSUE THREAD

**Issue by nyakze** [clsid2/mpc-hc#2910]
It seems that currently automatic subtitles download doesn't work for remote (http) files. When I press D, it shows "Online subtitle search completed, no subtitles found". If I enter a series name and season + episode number manually, it shows me the list and I can download it manually and then it works. But not the auto option.

Unfortunately I couldn't find any log file which would be helpful to pinpointing the issue (i.e. is it the filename it doesn't like, or just that fact that it's the file has a http in path)

I'm using a local torrserver if that's relevant.

Example file from playlist:
```
#EXTM3U
#EXTINF:0,Star Trek Deep Space Nine S03E25 Facets.mkv
http://localhost:8090/stream/Star%20Trek%20Deep%20Space%20Nine%20S03E25%20Facets.mkv?link=[ID_REMOVED]&index=25&play

```

**Comment by clsid2** [comment]
I am not adding that.
I am not discussing it further.
Playlist local network content in such a way is stupid.
