### ISSUE TITLE
Player not responding with this YouTube video

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2913]
https://youtu.be/SjfSR2NNSD8

I can download, but can't stream.

**Comment by NBruderman** [comment]
Can confirm it happens on my end as well

also couldn't open this vid
https://www.youtube.com/watch?v=4hSiQHPbsbE

Edit: I also noticed that after the program crashed and closed, the yt-dlp process keeps running in the background, and won't stop until manually terminated from task manager. Also, multiple processes can keep piling up after every attempt.

**Comment by bibsp** [comment]
> Edit: I also noticed that after the program crashed and closed, the yt-dlp process keeps running in the background, and won't stop until manually terminated from task manager.

Exactly. I didn't mention that because, as I forcefully terminating MPC-HC process, so I thought it's normal that yt-dlp process is still running in background.

**Comment by clsid2** [comment]
Try with 2.3.2.19

**Comment by bibsp** [comment]
I'm already on it.
Also latest daily yt-dlp development build.

**Comment by clsid2** [comment]
Looks like bug in yt-dlp.

yt-dlp hangs when user account does not have write access in the working directory.

To reproduce: put MPC-HC in a folder where a regular user account has write access, then change folder permissions, where "authenticated users" has "write" set to deny.
(program files is a protected folder where regular users already do not have write access by default)

**Comment by NBruderman** [comment]
So how do some videos do load? What's the difference?

**Comment by clsid2** [comment]
You have to ask yt-dlp developers why it tries to write to working dir instead op temp dir.

**Comment by bibsp** [comment]
My yt-dlp is not in MPC-HC folder. It is in download folder.

**Comment by clsid2** [comment]
Working dir is that of the calling app.

Explicitly adding `-P temp:"%temp%"` seems to work.

But it should really use the default Windows temp folder when running in simulation or json-extraction mode.
