### ISSUE TITLE
MPC Video Renderer broken for 10bit H265 video

### ISSUE THREAD

**Issue by OcDun** [clsid2/mpc-hc#2917]
While playing back video from my DJI Action 3 camera, I noticed that the 10bit HDR video was really fuzzy, as if interlaced or upscaled from 720p to 4K. Regular H265 video, 8 bit color, played just fine.

I switched back to the Enhanced Video Renderer and the problem disappeared.

To confirm the issue, I saved a JPG via the Save Image function, and the JPG was saved correctly with both renderers
![DJI_20240710162057_0077_D MP4_snapshot_00 03 818](https://github.com/user-attachments/assets/f20d2dc6-5a1a-407a-a524-c8062c56740b)

Unfortunately, I deleted the videos in question, and cannot provide a screen grab of how the MPC HC window video looked.

**Comment by clsid2** [comment]
Report bug to your graphics driver vendor.

Read the FAQ for solution.

**Comment by OcDun** [comment]
So what you're saying it's nVidia's fault for MPC Video Renderer not rendering video correctly?

The issue seems to be fixed after driver update (Studio Driver, RTX 3070 Ti) and MPC HC update to latest version (2.3.3).

**Comment by clsid2** [comment]
Yes, if you are talking about poor quality when downscaling, that was NVIDIA fault.
