### ISSUE TITLE
Saving images when Windows HDR is enabled - wrong colors

### ISSUE THREAD

**Issue by RieGo** [clsid2/mpc-hc#2923]
When you work with windows HDR mode enabled and try to save a (SDR) image from a video, its colors are washed out. when you disable HDR mode they look fine.
the result should always be the same IMHO.
I'm using MPC Video Renderer with RTX HDR disabled.

HDR mode:
![HDR](https://github.com/user-attachments/assets/f2c10ede-94ef-4b8e-9d47-4683f9261cbf)
SDR mode:
![SDR](https://github.com/user-attachments/assets/a6001702-1f00-4d7f-a3ec-13c417afaad4)

**Comment by clsid2** [comment]
Wrong place. Report it here:
https://github.com/Aleksoid1978/VideoRenderer/issues
