### ISSUE TITLE
When playing WMV, audio indicator in bottom-right indicates no audio track present

### ISSUE THREAD

**Issue by nomakewan** [clsid2/mpc-hc#2924]
When playing a WMV that contains both audio and video, everything seems to work normally (including seek and volume controls), but the indicator in the bottom-right of the MPC-HC window which indicates the none/mono/stereo status of the media file's audio track incorrectly indicates that the file has no audio track. Please see screenshot.

![wmvnoaudio](https://github.com/user-attachments/assets/92226497-a83d-42b9-85c9-75734f1de6e6)

I'm not sure if this is related to #2640 but I didn't see anyone mention this issue explicitly, so I'm putting it here.

EDIT: This is 2.3.2, by the way.

Thank you!

**Comment by clsid2** [comment]
What is shown here:
Menu > Play > Filters

A download link for that video would be useful.
https://www.sendspace.com

**Comment by nomakewan** [comment]
Here is what is shown in Menu > Play > Filters:
```
Filters currently loaded:
  - MPC Video Renderer
  - Default DirectSound Device
  - WMVideo Decoder DMO
  - WMAudio Decoder DMO
  - WM ASF Reader
```
And here is the [test file](https://files.catbox.moe/mevis8.wmv).

**Comment by clsid2** [comment]
Enable the internal audio switcher.

**Comment by nomakewan** [comment]
That certainly does make the stereo indicator reappear, yes, but I don't use the internal audio switcher. This also was not a problem in the older MPC-HC builds with the internal switcher disabled.

EDIT: Just tested 1.7.10 just to be sure I wasn't remembering wrong, and yes, the stereo indicator appears even with the internal audio switcher disabled.

![1710indicator](https://github.com/user-attachments/assets/9c3e6ed9-5c33-431b-a5d9-811ea9eb9511)

**Comment by clsid2** [comment]
Enabling it does no harm. Even if you don't actively "use" it.

**Comment by nomakewan** [comment]
But again, don't you think there may be a bug here if 1.7.10 displays the correct indicator with the internal switcher disabled, but 2.3.2 does not?

**Comment by clsid2** [comment]
Yes yes yes I will look into that.

But don't be stubborn and just enable the switcher to get it fixed instantly right now.

**Comment by nomakewan** [comment]
Can confirm that 2.3.3 fixed this issue with both WMV files and yt-dlp streams. Thank you very much!
