### ISSUE TITLE
Hello! Thank you very much for providing the Mpc player!

### ISSUE THREAD

**Issue by xinghongzhou** [clsid2/mpc-hc#2926]
Greetings! Thank you very much for the Mpc player!

The following stream never plays not sure what is the reason?

https://cdn3.turboviplay.com/data1/668fea967b9dd/668fea967b9dd720.m3u8

However, strangely enough in PotPlayer can play it!
PotPlayer
![image](https://github.com/user-attachments/assets/39f3489d-1726-4a7d-b831-78d08f62b9d0)
MPC
![image](https://github.com/user-attachments/assets/f0fe0701-5052-4f84-ba00-64850ff48204)

Hello! Is there any way to solve this problem in MPC player? Looking forward to it very much!

There are probably a lot of people out there who are experiencing this problem with MPC like I am, but they just don't want to take the time to report it or they just give up on MPC and move on to a different player.

Take a look at another streaming link that has the same problem:
https://cdn.turboviplay.com/data1/66907e1515bb9/66907e1515bb91080.m3u8

**Comment by xinghongzhou** [comment]
Take a look at another streaming link that has the same problem:
https://cdn.turboviplay.com/data1/66907e1515bb9/66907e1515bb91080.m3u8

**Comment by clsid2** [comment]
Broken links.

Do not bother posting new ones, because I do not care, and not going to fix it.

Go use potplayer.
