### ISSUE TITLE
Problem with MKV segment linking aka ordered chapters

### ISSUE THREAD

**Issue by nike34** [clsid2/mpc-hc#293]
MPC-HC crashes when an MKV gets into a segmented linking part (When a series has a file each for the intro and outro and plays between episodes)
I'm currently in the latest build MPC-HC 1.9.1 x64

![Screenshot_2](https://user-images.githubusercontent.com/61634614/75614530-721bf900-5b18-11ea-8fe1-d552e54bc2d0.png)

**Comment by clsid2** [comment]
Please give a link to a file that crashes. A torrent is fine.

**Comment by nike34** [comment]
https://nyaa.si/view/1115414

**Comment by clsid2** [comment]
@Nevcairiel

**Comment by nike34** [comment]
It appears that the file was faulty because other mkv's of the same kind play perfectly, i'm not sure if it was the format of 10bits or the uploaders fault, in any case I found other site to download from so it doesn't matter. Thanks anyway!
