### ISSUE TITLE
Always on top, no focused and seek Video preview while Playlist window on cause glitch

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2931]
Steps:
*Set Always on top / While video playing
*Set Playlist panel to window mode
*Focus another application
*Seek video preview
*once preview windows close by hover left from seekbar, you can not see Video preview again.

GIF: https://imgur.com/a/5wvmtjG

**Comment by adipose** [comment]
I'm unable to reproduce.  Can you upload your settings and remind me of the environment?

**Comment by xLn2** [comment]
[mpc-hc-settings.zip](https://github.com/user-attachments/files/16618688/mpc-hc-settings.zip)

```
Build information:
    Version:            2.3.4.19 (e6a147ed6-dirty) (patch419) (develop@a91c9d4)
    Build date:         Aug  8 2024

LAV Filters:
    LAV Splitter:       0.79.2.18
    LAV Video:          0.79.2.18
    LAV Audio:          0.79.2.18
    FFmpeg compiler:    

Operating system:
    Name:               Windows 10 (Build 22H2)
    Version:            10.0.19045 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    GPU:                Intel(R) HD Graphics 630 (driver version: 31.0.101.2128)
    Monitor:            \\.\DISPLAY1 - Generic PnP Monitor [1920x1080 32-bit 120 DPI] - [Current]
```


Always On Top set Mpc-hc, Playlist Panel in Float mode
I focus another app like notepad, firefox
Seek first time has no issue but when mouse leaves from seekbar it somehow change window layer level.

![firefox_kR1udnUW2B](https://github.com/user-attachments/assets/30915e8d-c8f7-48de-884d-af577f8fc5a2)

Also see this weird case: when I tried open Settings, there is Playlist floating panel topmost level and overlap settings. But I didn't reproduce it again.

**Comment by adipose** [comment]
I cannot reproduce, but I do see that your playlist has fallen behind which isn't supposed to happen.  Do you have any other "always on top" applications or something like that?

Can you try on a different machine and see if you can reproduce again?

**Comment by adipose** [comment]
Never mind, I can do it now, I just needed the video to be playing.

**Comment by xLn2** [comment]
https://github.com/clsid2/mpc-hc/issues/2991 probably similar issue.

When Mpc-hc window positioned some part over Windows taskbar, seekbar hover also cause Windows taskbar blink.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/3001
