### ISSUE TITLE
upscaling with MPC Video Render

### ISSUE THREAD

**Issue by 1AGRESSOR** [clsid2/mpc-hc#2934]
i searched for few days all over the net how to enable upscaling in a as much as possible native way, without madvr and other stuff

is this supported and i just didn't find how to do it ?

720p movie that i watch on 4k tv from usb flash looks at least 1080p+ some even 4k but on my pc 1440p screen look like 720p

**Comment by NBruderman** [comment]
Upscaling is done by algorithms. There is no "native" upscaling. Even on TVs, there are algorithms under the hood for that.

**Comment by clsid2** [comment]
Nothing can turn your 720p quality video into crispy high quality 4k. Not even Madvr or any fancy AI powered bullshit. Go sit at same distance from your TV as your Monitor...

All renderers can scale/resize your video to screen size. The algorithm determines how good the result it. But there is no magic.
