### ISSUE TITLE
Several context menus theming issues

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2937]
1. Subresync (after separators, there is big gap)

![mpc-hc64_iuvKbIGtvE](https://github.com/user-attachments/assets/e50d41e4-b61a-45ec-b4a3-2f0fa21dcc78)

2. Options > Subtitles > Misc 

![PA4ui1Jvt9](https://github.com/user-attachments/assets/0a89977d-e1d8-476d-b854-e5b4cbbf76c6)

3. Editboxes

![chrome_PIqzVvKvyI](https://github.com/user-attachments/assets/3c089d00-6db8-4214-bcbf-411af8b45e2e)

**Comment by adipose** [comment]
Where are the editboxes from?

**Comment by xLn2** [comment]
> Where are the editboxes from?

Dialog boxes accessed via MPCHC menu, Options (editboxes) and probably any other places, `Edit` class also effected.

![mpc-hc64_go8kZErbxQ](https://github.com/user-attachments/assets/6ee0e1df-85e9-4023-b81e-930a35a9cb4a)
![mpc-hc64_4DEngGmqRG](https://github.com/user-attachments/assets/638f84b2-57e3-469f-9119-3250f4457de9)
![mpc-hc64_PdGQ7RLXkS](https://github.com/user-attachments/assets/b184fb77-fc08-4526-80fb-9aea3508450b)

**Comment by adipose** [comment]
Should be fixed in https://github.com/clsid2/mpc-hc/pull/2963

**Comment by xLn2** [comment]
2.3.4.19 (patch419)
**Editable Comboboxes**: `Open File/Url`  , `Options>Shaders` , `Add Favorites` doesn't apply right click menu theme.
Navigate > Go To > Time editbox may have custom class so it doesn't apply right click theme.
Playlist, Subresync, Options > Fullscreen inline edits right click menus

**Comment by adipose** [comment]
> 2.3.4.19 (patch419) **Editable Comboboxes**: `Open File/Url` , `Options>Shaders` , `Add Favorites` doesn't apply right click menu theme. Navigate > Go To > Time editbox may have custom class so it doesn't apply right click theme. Playlist, Subresync, Options > Fullscreen inline edits right click menus

https://github.com/clsid2/mpc-hc/pull/2984
