### ISSUE TITLE
[yt-dlp] can't play a specific video, even though yt-dlp can download it

### ISSUE THREAD

**Issue by Yoksven** [clsid2/mpc-hc#2939]
Video in question: https://www.youtube.com/watch?v=9AZRPItAsfA

I get an error `Requested format is not available. Use --list-formats for a list of available formats` on any `YDLVideoFormat` setting (0-8). Yt-dlp lists that there are formats available, but when I try to add a specific available format (-f 609+140-drc, for example) in `YDLCommandLine`, it is seemingly ignored and I just get the error, even though the video and audio can be downloaded with yt-dlp with these format arguments.

**Comment by clsid2** [comment]
Works fine here.

You need to put ffmpeg.exe in same folder as yt-dlp. That is needed for some formats.
