### ISSUE TITLE
MPC-HC not associating itself with certain extensions

### ISSUE THREAD

**Issue by drguildo** [clsid2/mpc-hc#294]
After doing the following: `View → Options → Formats → Run as administrator → Associate with all formats → Apply` as well as setting MPC-HC as the default video player in the "Default apps", MPC-HC seems to only set itself as the default player for some file types.

If I got to "Default apps" again and click on "Set defaults by app" a bunch of supported file extensions aren't handled:

![image](https://user-images.githubusercontent.com/9282/75616283-14eb6c00-5b47-11ea-8e66-7eb3ab0f6e40.png)

I'm running Windows 10 1909.

**Comment by clsid2** [comment]
That is because those extensions are not registered as a known video extension in Windows. However, when you attempt to play such a file you should get a prompt asking you which application you want to use, and MPC-HC should be in the list to choose from.

**Comment by clsid2** [comment]
And before you ask, it is not possible for MPC-HC (or any other app) to force itself as a default.

**Comment by drguildo** [comment]
Thanks for the clarification. It wouldn't be so bad if Microsoft had an easy way to set an app as the handler for all the file types it supports. I seem to remember you could do that in Windows 7 but it looks like they removed it from Windows 10. Thanks Microsoft.

**Comment by clsid2** [comment]
It can be done through the classic control panel:
`control.exe /name Microsoft.DefaultPrograms /page pageDefaultProgram`

**Comment by drguildo** [comment]
That just loads the crappy new Windows 10 "Default apps" settings for me.
