### ISSUE TITLE
video frezzing and crash this is the error

### ISSUE THREAD

**Issue by Nbisbo** [clsid2/mpc-hc#2944]
Exception: ACCESS VIOLATION Crashing module: C:\Program Files (x86)\K-Lite Codec Pack\MPC-HC64\mpc-hc64.exe Offset: 0x3509C6, Codebase: 0x7FF65BB20000 The thread 17988 tried to read memory at address 0xA43F36B9

**Comment by clsid2** [comment]
What kind of file are you playing?
What are you doing when the crash happened?
Are you able to reproduce the crash?

**Comment by Nbisbo** [comment]
.mkv h.264 always at the same part of the video

**Comment by clsid2** [comment]
Give a link to that specific video. And timestamp at which it crashes.
