### ISSUE TITLE
Multiple Subtitle Problem (.SMI)

### ISSUE THREAD

**Issue by DnzhnAlty** [clsid2/mpc-hc#2946]
Hello, sometimes when i downloaded videos from youtube, I saw ".smi" type subtitle. I read your past issues situation about ".smi" support. Probably you added after ".smi" support for mpc-hc. But video player can't seperate languages situation for ".smi" subtitles.  Always shows all languages on subtitle area. 
Have a nice day .

![resim](https://github.com/user-attachments/assets/a67329f7-e4f6-4f99-a3ab-f43815859136)

**Comment by clsid2** [comment]
Convert to SRT:
https://subtitletools.com/convert-to-srt-online
