### ISSUE TITLE
Make it possible to convert m3u8 and mpd

### ISSUE THREAD

**Issue by autistukral** [clsid2/mpc-hc#2951]
If you have time, could you please also try to make converting m3u8 and mpd files into mp4 etc. with yt-dlp?
I know it works with yt-dlp-gui so it is possible.

Thanks in advance!

**Comment by clsid2** [comment]
It already has download ability.
It already provides setting to specify yt-dlp command line parameters.

You need to put ffmpeg.exe in same folder as yt-dlp and figure it out yourself.
