### ISSUE TITLE
AAC LC no sound

### ISSUE THREAD

**Issue by PanosPav** [clsid2/mpc-hc#2952]
Audio
ID                             : 2
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Codec ID                       : A_AAC-2
Duration                       : 2 h 6 min
Bit rate                       : 448 kb/s
Channel(s)                     : 6 channels
Channel layout                 : C L R Ls Rs LFE
Sampling rate                  : 48.0 kHz
Frame rate                     : 46.875 FPS (1024 SPF)
Compression mode               : Lossy
Delay relative to video        : 20 ms
Stream size                    : 405 MiB (8%)
Language                       : English
Default                        : Yes
Forced                         : 
Is there anything I can do to get sound using MPC HC ;

**Comment by NBruderman** [comment]
Can you post the file in question, or any other sample that has this issue?

**Comment by PanosPav** [comment]
All samples are mkv files and the uppload is not supported by this page !

**Comment by NBruderman** [comment]
> All samples are mkv files and the uppload is not supported by this page !

You know google drive, mega, etc. exist...

**Comment by PanosPav** [comment]
Correct...

**Comment by PanosPav** [comment]
https://drive.google.com/file/d/1csRFyfpoVvvCCaWz6_OWTuoX5-CgWQKx/view?usp=drive_link
Please take under consideration that I need the 6.1 aac set up.

**Comment by clsid2** [comment]
You need to set file to public, otherwise I can not download it.

**Comment by PanosPav** [comment]
https://drive.google.com/file/d/1csRFyfpoVvvCCaWz6_OWTuoX5-CgWQKx/view?usp=sharing
Done.

**Comment by clsid2** [comment]
No issue with playback here.

Update to latest version and reset the settings.
Options > Miscellaneous > Reset

**Comment by PanosPav** [comment]
I am on the latest always...I'll do it.
________________________________

**Comment by PanosPav** [comment]
Choosing madvr output is the problem, when I choose mpc renderer the sound is working.
Thank you.
________________________________

**Comment by clsid2** [comment]
madvr should not have any effect on sound.

Maybe you have weak hardware or some kind of driver issue. I can not help you with that.

**Comment by PanosPav** [comment]
RTX 3080 is power enough, maybe the drivers I will ask also madshi.
Nevertheless,
Thank you.
________________________________

**Comment by clsid2** [comment]
He can not help you either.

It is problem specific to your system. Maybe insufficient power supply or some other hardware issue.

**Comment by PanosPav** [comment]
I really appreciate your help.
Madshi already replied that is working fine to his system using MPC HC  version (2.0.0).
He send me a valid copy of the latest madvr test build.
My system is :
Ryzen 7 3800x,
Asus b550f
Patriot 2 x16
RTX 3080 MSI gaming trio Z
Seagate Fireacuda 530
Seagate Barracuda x 3
Corsair HX1000
I believe it is powerful enough.
I will try the old version of MPC HC as I am pretty confident that in the past I could play these video files.
Thanks again.
________________________________

**Comment by PanosPav** [comment]
Finally you were both right, my settings back up was corrupted.
Everything is fine now.

Thanks.
________________________________
