### ISSUE TITLE
OSD does not get cleared in EVR-CP D3D fullscreen

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2957]
OSD messages display and update correctly, but do not get hidden after they timeout.

**Comment by clsid2** [comment]
Fixed in [5594e20](https://github.com/clsid2/mpc-hc/commit/5594e20d09967e1292104a6a9e1003f646e2cd19)

@adipose
I still think it is weird that we need to use VMR bitmap interface instead of EVR. There is probably a bug hidden somewhere.

**Comment by adipose** [comment]
You can checkout https://github.com/adipose/mpc-hc/commit/8d4a0a2bf6a57905845095c37956fe1d2d853a66 to see if you can get it working.
