### ISSUE TITLE
Reading .mpcpl playlist from file does not read video duration correctly

### ISSUE THREAD

**Issue by mkierc** [clsid2/mpc-hc#2959]
Steps to reproduce:
1. Have a .mpcpl format playlist with duration of the files baked in:
```
MPCPLAYLIST
1,type,0
1,time,00:21:02
1,filename,Whose.Line.Is.It.Anyway.US.S16E17.1080p.WEB.h264-BAE.mkv
2,type,0
2,time,00:21:02
2,filename,Whose.Line.Is.It.Anyway.US.S16E18.1080p.WEB.h264-BAE.mkv
3,type,0
3,time,00:21:02
3,filename,Whose.Line.Is.It.Anyway.US.S16E19.1080p.WEB.h264-BAE.mkv
```
2. Open the playlist in MPC-HC
3. The playlist view does not show duration of the files in the playlist, apart from the one that's currently playing:

![image](https://github.com/user-attachments/assets/bc535356-3114-47ec-926e-f0d8002b7c2a)

---
Here's my idea for a fix (I'm not a C++ dev, so I'm not sure how to correctly parse the time, therefore I'm a little bit scared to make my own PR):

I've noticed, that here in the `ParseMPCPlayList` function a `time` branch is missing:
https://github.com/clsid2/mpc-hc/blob/5ef321d50bb6233229290f65c7645c14dbbabb72/src/mpc-hc/PlayerPlaylistBar.cpp#L831-L841

based on `CPlaylistItem` definition from here:

https://github.com/clsid2/mpc-hc/blob/5ef321d50bb6233229290f65c7645c14dbbabb72/src/mpc-hc/Playlist.h#L28-L44

the `m_duration` field should be filled out with parsed value of `time`, I imagine something like:

```
 } else if (key == _T("time")) {
                pli[i].m_duration = ParseTime(value);
            } 
```

There seems to be a ParseTime method implemented here, which might be of help:

https://github.com/clsid2/mpc-hc/blob/e6a6ef1f2060e83155dc475adc3317a84e7d762c/src/mpc-hc/PlayerSubresyncBar.cpp#L761-L788

**Comment by clsid2** [comment]
MPC-HC does not save a `time` entry. It seems you invented it yourself. If not, which application created that playlist file?

**Comment by mkierc** [comment]
Seems that I was basing the .mpcpl format off a custom script which is not official format spec:
https://soslangm.github.io/Portfolio/playlist.html

**Comment by clsid2** [comment]
I have added a duration parameter. Its value is in milliseconds.
