### ISSUE TITLE
can be add 25% zoom hotkey?

### ISSUE THREAD

**Issue by anime5167** [clsid2/mpc-hc#296]
can be add 25% zoom hotkey for 4K video @ 1080p monitor to show 50% windows?

**Comment by clsid2** [comment]
Options > Playback > Zoom & Alignment > Auto fit factor

Then you can use Alt+4 to resize.

**Comment by anime5167** [comment]
> Options > Playback > Zoom & Alignment > Auto fit factor
> 
> Then you can use Alt+4 to resize.

1080P Alt+1 = real 50% screen
scale 0,0,1920,1080 -> 0,0,960,540 (ALT+J) =2

4K 50% Auto fit factor is not real 50% screen
50% scale 0,0,3840,1920 -> 0,0,906,453 (ALT+J) =4.2384 != 4(25%)
50% scale 0,0,3840,2160 -> 0,0,805,453 (ALT+J) =4.7682 != 4(25%)

i think this scaling algorithm is not equal (zoom50%/zoom100%/zoom200% algorithm )

**Comment by clsid2** [comment]
The 50% size applies to the whole player window, not just the video part.

Another way to do it right now is to manually resize to 960x540 and then enable the option to remember window size.

A 25% option may get added in the future.

**Comment by anime5167** [comment]
plz add 25% in future
thx. :-D

**Comment by clsid2** [comment]
Has been added.
