### ISSUE TITLE
Jumping leads to disconnection video frames on VP9 Online stream

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2960]
https://www.youtube.com/watch?v=Dda5EZAl_DQ

![mpc-hc64_J0hWT8ZQtP](https://github.com/user-attachments/assets/7670a598-2911-4fe7-99f7-be50336cf917)

```
Video: VP90 1920x1080 29.97fps 320kbps [V: ISO Media file produced by Google Inc. Created on: 07/29/2024. (vp9 profile 0, yuv420p, 1920x1080, 320 kb/s)]
Audio: AAC 44100Hz stereo 128kbps [A: ISO Media file produced by Google Inc. [eng] (aac lc, 44100 Hz, stereo, 128 kb/s)]
```

**Mpchc = 2.3.3**
**YDLVideoFormat = 3**
**Hide Windowed Controls = Enabled**
Filters currently loaded:
  - SaneAR Audio Renderer
  - MPC Video Renderer
  - Audio Switcher
  - LAV Video Decoder (internal)
  - LAV Audio Decoder (internal)
  - LAV Splitter Source (internal)
  - LAV Splitter Source (internal)
_____

When I jump to a later point in the video, the video frame is not accessible. When this happens, either the last frame remains fixed or playback continues with a black frame. When I downloaded same video via YDL, there is no issue.

**Comment by clsid2** [comment]
Not a player issue.
LAV Splitter fails to download segments after the seek.
Likely a new throttling or blocking protection by Youtube.

I can not help you.

**Comment by adipose** [comment]
This did not seem to affect latest yt-dlp.
