### ISSUE TITLE
Volume % cannot be seen on the video window

### ISSUE THREAD

**Issue by HandsomeTopKhi** [clsid2/mpc-hc#2964]
If you are using the player on the full screen or as a minimal preset view and use your mouse scroll wheel to increase or decrease the voulme it shows now show in the video windows. You always have to either exit the full screen or shift to the normal preset view to see the volume bar with the percentage. Before it used to show the percentage on the screen itself. Please bring it back.

Thanks..

**Comment by clsid2** [comment]
options > player > user interface > show osd

**Comment by HandsomeTopKhi** [comment]
> options > player > user interface > show osd

Oh thank you I never knew that option was there. Previously it always used to work as a default option for me. Nice to know it's still there :)

Thank you for the amazing work you guys put in.
