### ISSUE TITLE
MediaInfo Save As is not following the corresponding file location

### ISSUE THREAD

**Issue by BurnerTom** [clsid2/mpc-hc#2969]
When I open the video file "video.mkv" e.g. from the location "D:\Videos\" and in MPC-HC I click on Properties in the File menu and click on the MediaInfo tab, where I choose Save As, then Explorer opens with a preset path to the place from where I started MPC-HC or to the location , where I saved the previous export, if it still exists, but not to the location of the file to which this export belongs.

Can you please change / fix it?

Well thank you.

**Comment by clsid2** [comment]
Everybody wants something different.

Nobody has complained about it before, so I am not wasting my time on it.

**Comment by clsid2** [comment]
Just do Ctrl+A to select all text Ctrl+C to copy, and Ctrl+V to paste.

**Comment by adipose** [comment]
> When I open the video file "video.mkv" e.g. from the location "D:\Videos\" and in MPC-HC I click on Properties in the File menu and click on the MediaInfo tab, where I choose Save As, then Explorer opens with a preset path to the place from where I started MPC-HC or to the location , where I saved the previous export, if it still exists, but not to the location of the file to which this export belongs.
> 
> 
> 
> Can you please change / fix it?
> 
> 
> 
> Well thank you.

Probably a mediainfo "bug."  Windows save-as dialogs have a behavior of remembering a previously used location. It's usually by application.  The behavior can be altered, but it sounds like mediainfo is defaulting to the current environment folder (mpchc launching folder).

**Comment by adipose** [comment]
https://github.com/MediaArea/MediaInfo/issues/444

**Comment by BurnerTom** [comment]
> adipose

That's exactly it.
But now I'm a bit confused as to what this means in terms of MPC-HC.
Are you going to alter / override this behavior or do you consider this ticket closed for good?

Thank you.

**Comment by adipose** [comment]
I will take a look and see if a PR is possible for mediainfo.

Not sure if override is possible from our end.

**Comment by clsid2** [comment]
MediaInfo is not involved in that save dialog.

**Comment by BurnerTom** [comment]
> MediaInfo is not involved in that save dialog.

So that means that's a MPC-HC bug, correct?

**Comment by clsid2** [comment]
No it is NOT a bug. It uses the standard behavior of file save dialog, and that is use last used location.

**Comment by BurnerTom** [comment]
> No it is NOT a bug. It uses the standard behavior of file save dialog, and that is use last used location.

I can agree with you that it is not a bug from the MPC-HC code point of view, but it is a bug from the UI point of view.

I will give an example.
I'm sure you know [Subtitle Edit](https://www.nikse.dk/subtitleedit).
When I open video file A in this program and export subtitles from it,
it opens the location of video A by default.

When I subsequently open video B from another location and export the subtitles from it,
the location of video B opens, since the subtitles belong to this video, not to the previous video A.

This is required and, in my opinion, the only correct behavior.

Since the MediaInfo export from MPC-HC does not work like this,
from the user's point of view it is the fault of the MPC-HC itself.

But I don't want to argue here.
I would like to ask you to modify this behavior if you find the time.

Thank you.

**Comment by adipose** [comment]
If it behaves differently from other Explorer dialogs in mpchc I will try to align it.

What this means practically is it will use the last location where save-as occurred in mpchc.

I have made this improvement to multiple other save dialogs.

**Comment by clsid2** [comment]
Why are you saving the info in first place? Because there are easier solutions to get the info when needed.

If you install K-Lite, it can add MediaInfo directly in right-click context menu for easy access. And Icaros propertyhandler can show video info (codec/resolution/etc) directly in Explorer.

**Comment by adipose** [comment]
The saveas appears to simply rename the video name to the txt name, but provides no path, causing it to save in the default windows location (as @clsid2 said, that is by default the _last used location_ within explorer dialogs).

I have altered the behavior of most of the save/open dialogs in mpchc to behave more consistently.  But the preferred behavior might be either of the following two:

1. The location of the video.  This is easy to achieve because it only requires _removing_ code that deliberately enables the behavior it currently has (the code removes the folder from the path).
2. The last location where mediainfo was saved.  This might be a useful option, although personally I would find `#1` more valuable.  I have implemented this before for some common dialogs so that the open dialog uses the last opened location, for example.  This requires storing a setting in the registry so it is slightly harder.

@clsid2 , I can do the first unless you know there was a preference to have the existing behavior.  In the past I really did not like this behavior, because it led to weird things like: it wanted to save a thumbnail in the last place I had opened a DVD, even though I wasn't currently playing that DVD.

**Comment by clsid2** [comment]
Using video location would be fine. And existing behavior for URLs.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/3084

**Comment by BurnerTom** [comment]
> The saveas appears to simply rename the video name to the txt name, but provides no path, causing it to save in the default windows location (as @clsid2 said, that is by default the _last used location_ within explorer dialogs).
> 
> I have altered the behavior of most of the save/open dialogs in mpchc to behave more consistently. But the preferred behavior might be either of the following two:
> 
> 1. The location of the video.  This is easy to achieve because it only requires _removing_ code that deliberately enables the behavior it currently has (the code removes the folder from the path).
> 2. The last location where mediainfo was saved.  This might be a useful option, although personally I would find `#1` more valuable.  I have implemented this before for some common dialogs so that the open dialog uses the last opened location, for example.  This requires storing a setting in the registry so it is slightly harder.
> 
> @clsid2 , I can do the first unless you know there was a preference to have the existing behavior. In the past I really did not like this behavior, because it led to weird things like: it wanted to save a thumbnail in the last place I had opened a DVD, even though I wasn't currently playing that DVD.

Thanks a lot for you understanding and effort.
I just realized that the same bug / behavior is affecting the File - Same Image (Alt + I) MPC-HC feature.
Can you change this behavior as well?
Thanks a lot

**Comment by clsid2** [comment]
NO. The behavior of save image is intentional.
