### ISSUE TITLE
No audio with live .m3u8 streams...

### ISSUE THREAD

**Issue by Phar-Lap** [clsid2/mpc-hc#297]
Using the following URL as an example:

http://kitdigitaioslive-i.akamaihd.net/hls/live/219671/skyracing_live_mob/ssr_low@219671-audio.m3u8

The last version to produce audio was Media Player Classic Home Cinema 1.7.10.

All versions after 1.7.10 have no audio and show an icon with a x in the lower right:

![No Audio with Muted Icon](https://user-images.githubusercontent.com/61812089/75941228-3485ea00-5ee3-11ea-8f06-06e0bd182369.png)

**Comment by clsid2** [comment]
Link is not working.

Issues with internal codecs should be reported here:
https://github.com/Nevcairiel/LAVFilters

**Comment by Phar-Lap** [comment]
The link works, but probably only in Australia.
Try through a VPN set for Australia.
All my .m3u8 links are probably region locked to Australia and they all suffer from this audio problem.

Is there a way to extract the required filter from Media Player Classic Home Cinema 1.7.10 and use it with Media Player Classic Home Cinema 1.9.1.

**Comment by clsid2** [comment]
Options > Internal Filters > Splitter > Set "Stream Analysis Duration" to 2000 ms
