### ISSUE TITLE
ConfirmFileDelete setting not remembered correctly [Fixed][Workaround]

### ISSUE THREAD

**Issue by HKFam343** [clsid2/mpc-hc#2970]
When changing the setting: View > Options > Advanced > ConfirmFileDelete
Default is set to True.
If I changed this to False and apply things work as expected until I open the application again.
If I set this from 1 to 0 in the RegEdit: Computer\HKEY_CURRENT_USER\SOFTWARE\MPC-HC\MPC-HC\Settings
MPC still ignores this and I get prompted each time I try to move things to the recycling bin with a shortcut.

Using Windows 10 and I'm on version: v2.4.3 (0ac7be66d)
This behavior started for me after a recent update, not sure which version I was on but I haven't had this before in the last 5+ years.

**Comment by clsid2** [comment]
Fixed.

As a temporary workaround you can also set `PauseWhileDraggingSeekbar` to false. Due to a typo it is currently reading that value.
