### ISSUE TITLE
Add .avs filetype to Open Dialog Media Types Filter

### ISSUE THREAD

**Issue by Tlentlen** [clsid2/mpc-hc#2973]
Hi,
I often use MPC to test .avs script.
Actually the .avs filetype is not in the "Recognized" types, so everytime I have set filter to *all and the open the .avs script.

Could the filetype .avs be added to the open dialogs so it's recognized by default?

Thank you

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2997
