### ISSUE TITLE
PQ to SDR post-processing not getting enabled/disabled when switching to fullscreen and back

### ISSUE THREAD

**Issue by ACertainCoder** [clsid2/mpc-hc#2978]
Hi there, I noticed the following issue: when starting playback of an HDR video on a SDR display and then switching to fullscreen on a HDR monitor __without moving MPC-HC to that other monitor first__, causes the "PQ to SDR" post-processing to still apply. The HDR processing switches correctly to "passthrough". The same thing happens also when launching MPC-HC on an HDR monitor and then switching to fullscreen on a SDR monitor, but backwards: the "PQ to SDR" post-processing does not get applied.

Statistics on SDR monitor:
![grafik](https://github.com/user-attachments/assets/f7a4b43b-562a-4e9e-b85b-55b5877d4dd3)

Statistics on HDR monitor after switching to fullscreen while keeping player controls on SDR monitor:
![grafik](https://github.com/user-attachments/assets/2862559c-bfb2-4cc1-9d15-f3885c1e9f5e)

Setup details:

Monitor 1: SDR
Monitor 2: HDR (1,000 nits)
Fullscreen separate controls: enabled
Fullscreen output device: monitor 2
Fullscreen action id: 830/831 (both affected)

MPC Video Renderer config:
![grafik](https://github.com/user-attachments/assets/595c9566-9714-4ee1-b7a5-11771537ff17)

**Comment by clsid2** [comment]
Report here:
https://github.com/Aleksoid1978/VideoRenderer/issues

Reinitialize device when changing display option might help.

**Comment by ACertainCoder** [comment]
Sadly, the reinitialize option doesn't help. I will report the issue over there, thanks.
