### ISSUE TITLE
Add support of cookies arguments commands of yt-dlp "--cookies-from-browser firefox" to play restircted videos of twitter

### ISSUE THREAD

**Issue by trimechee** [clsid2/mpc-hc#2980]
Hello, yesterday i tried to play twitter videos because videos on twitter are very heavy and lag freeze even lowest quality in my old laptop, i tried with Mpc-hc, Mpc-be, smplayer, potplayer with 3DYD Youtube Source plugin, qmplay2...all these players fails to pay twitter videos and have message that i should add cookies commands like --cookies-from-browser firefox....

i am not expert, i tired to add --cookies-from-browser firefox to the yt-dlp engines of these media players but no video playback :(

my idea please is that media player allows to support or add cookies yt-dlp commands arguments --cookies-from-browser firefox --cookies-from-browser chrome --cookies-from-browser r3dfox ........to video stream detected so we can avoid possible bugs and we could playback restirctid videos of twitter in vlc or potplayer or smplayer...thank you very much!

**Comment by clsid2** [comment]
Use config file for such settings:
https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#configuration

If you want to use advanced parameters then I suggest you download the content you want with yt-dlp directly, and then watch downloaded content with MPC-HC.

I AM NOT ADDING ANY MORE OPTIONS OR FUNCTIONALITY FOR YT-DLP !!!
