### ISSUE TITLE
DVD does not redraw in static "extras" title

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#2985]
May be related to other issues we've had with the title menu.

1. The video does not redraw at all unless activated by a mouse-over of an interactive element.  In the case of toolbars which are auto-hidden, they leave remnants behind. 
2. If the window is minimized and restored, the screen is black.
3. Problem is the same in MPC-BE.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/611

I found this thread.  The issue goes away if you use MPC-VR.

**Comment by xLn2** [comment]
Before the major LAV Filters update (0.79+), when using SaneAR, even play/pause and jump forward would make the sync offset spike cause the film unwatchable. SaneAR doesn't work well on my end for DVDs. There is no major problem felt right now, but minor sync loss may occur.
For some time I have been using MPC-VR, I tested also EVR and EVR (C-P) they all behave the same.

Tried both NVIDIA and Intel graphic and d9/d11
```
MPC-HC (64-bit)
---------------

Build information:
    Version:            2.3.4 (0ac7be66d)
    Build date:         Aug  6 2024

LAV Filters:
    LAV Splitter:       0.79.2.18
    LAV Video:          0.79.2.18
    LAV Audio:          0.79.2.18
    FFmpeg compiler:    MinGW-w64 GCC 13.3.0

Operating system:
    Name:               Windows 10 (Build 22H2)
    Version:            10.0.19045 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    GPU:                NVIDIA GeForce GTX 1050 Ti (driver version: 32.0.15.5599)
    GPU:                Intel(R) HD Graphics 630 (driver version: 31.0.101.2128)
    Monitor:            \\.\DISPLAY1 - Generic PnP Monitor [1920x1080 32-bit 120 DPI] - [Current]
```

Edit:
- Windows > Graphic settings > Hardware accelerated GPU timing [Disabled - Restarted Computer] (Not sure it has any effect)
- Reset MPC-VR settings to Default
Solved the issue.

**Comment by NBruderman** [comment]
@xLn2 so can this be closed?

**Comment by xLn2** [comment]
If the developers have no plans to make improvements to EVR-CP, the issue can be closed (unless any other issue found by devs). The issue is not recurring in my usage conditions.

**Comment by adipose** [comment]
This issue I can reproduce and we can keep it open.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/3012

I found that MPC-VR started having the same issue. I'm not sure what is the situation where it affects MPC-VR sometimes but othertimes not.  It may be connected to MPC-AR use.

This seems to fix the issue for all renderers.
