### ISSUE TITLE
Playlist does not skip to next available file

### ISSUE THREAD

**Issue by orzcode** [clsid2/mpc-hc#2986]
Previously in the old MPC-HC, if you load a playlist, and some of the files in the playlist no longer existed, MPC-HC would skip to the next file in the playlist, and if that was not found, the next, and the next, until it found a playable file or reached the end of the playlist.

However, in this version of MPC-HC it only seems to skip ahead 5 files at a time, then it stops, and needs to be manually 'skipped' to the next file, upon which it will repeat the behavior.

This is pain for large playlists which gradually have items removed over time (i.e., a playlist of several seasons of TV shows where the videos get deleted after viewing).

Can this please be rectified to the old behavior? I wonder if it was maybe intentional as a safeguard or something.

**Comment by clsid2** [comment]
It is intentional and will not be changed and there will not be options for it.

Fix your fucking playlists.

MPC-HC even offers file delete ability.
