### ISSUE TITLE
yt-dlp --proxy argument for open-action

### ISSUE THREAD

**Issue by SailorMax** [clsid2/mpc-hc#2988]
Currently we have setting YDLCommandLine but it doesn't uses on open URL action (-J). In result we can't use proxy for open URL. Only for download. But "Save As" works only after "Open" :)

Can you add setting to setup additional yt-dlp arguments for "open URL"-action?

**Comment by clsid2** [comment]
Try using configuration file for yt-dlp.

If that does not work, then you are out of luck, because I am not adding any more options.
