### ISSUE TITLE
About Localization

### ISSUE THREAD

**Issue by NightSharp** [clsid2/mpc-hc#299]
Strings "Play with MPC-HC64" and "Add to MPC Playlist" in the Explorer's RightMenu
are not able to be localized correctly.
Now I use zh-cn, but these strings are still in English.

**Comment by adipose** [comment]
For lack of a better solution, change the following key:

Computer\HKEY_CLASSES_ROOT\Directory\shell\mplayerc.enqueue

(Default):
@"C:\Program Files (x86)\K-Lite Codec Pack\MPC-HC\Lang\mpcresources.zh_CN.dll",-33161

You can copy the right path from the "Icon" key, since it is likely different depending on 64 bit or using K-Lite vs. mpc-hc vanilla.

**Comment by adipose** [comment]
Ignore my previous comment.

You just need to visit the formats page, run as administrator, and uncheck and check the boxes at the bottom. Example for spanish:

![image](https://user-images.githubusercontent.com/3324395/76137745-17414080-5ff5-11ea-95f5-0586b36d02bf.png)

This will put the right string in the registry.

**Comment by NightSharp** [comment]
Well, this action only take effect for directory context menu.
When I right click any single video file, the context menu still show "Play with MPC-HC64" and "Add to MPC Playlist",not in my language.
I've checked mpcresources.zh_CN.dll and mpc-hc64.exe with localization tool,
but find nothing same as "Play with MPC-HC64", just "Play with MPC-HC" in mpc-hc64.exe



At 2020-03-07 13:54:59, "adipose" <notifications@github.com> wrote:

Ignore my previous comment.

You just need to visit the formats page, run as administrator, and check the boxes at the bottom. Example for spanish:

This will put the right string in the registry.

**Comment by adipose** [comment]
For files, you have to check the box on each extension.  Also if you are seeing MPC-HC vs MPC-HC64, you may have two versions on your system.

Here is what I was able to achieve by checking boxes for AVI and directory, in administrator mode, using Chinese (Simplified):

![image](https://user-images.githubusercontent.com/3324395/77234207-c6d7f000-6b69-11ea-8c2f-86729e392607.png)

![image](https://user-images.githubusercontent.com/3324395/77234223-dc4d1a00-6b69-11ea-894f-f3590f2904cc.png)

![image](https://user-images.githubusercontent.com/3324395/77234232-e5d68200-6b69-11ea-8a01-05543f12286a.png)

**Comment by adipose** [comment]
Oh, and one other comment.  If another file has associated with the extension, it doesn't seem to work anymore.  Please go into default associations and update it.

![image](https://user-images.githubusercontent.com/3324395/77235683-399a9880-6b75-11ea-849a-97e62ab484b4.png)

**Comment by NightSharp** [comment]
Well, I've found that this was caused by My K-Lite....
When I was installing K-Lite, I chose to let K-Lite create associations for my default video player(that is MPC-HC).
So K-Lite added the context menu items into registry which overwrote those created by MPC-HC itself.


At last I reinstalled K-Lite freshly without letting it deal with associations related to any players, and it worked.


Thanks so much!










At 2020-03-22 04:09:55, "adipose" <notifications@github.com> wrote:

Oh, and one other comment. If another file has associated with the extension, it doesn't seem to work anymore. Please go into default associations and update it.
