### ISSUE TITLE
Window doesn't adjust size to match cover art

### ISSUE THREAD

**Issue by azure-06** [clsid2/mpc-hc#2990]
The cover art for this specific file is 600x600, and in earlier versions it was displayed 1:1, but now the window size stays the same as the size of the logo image that shows before the file loads
| 2.3.4 | 2.3.3 |
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/eac72e8a-a2e2-4917-acc8-5d7bed73cc70) | ![image](https://github.com/user-attachments/assets/014546f6-25cb-472c-90ef-4df231e8d800) |

**Comment by clsid2** [comment]
Fixed
