### ISSUE TITLE
DVD mode related issues

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2995]
1. DVD title

Opening DVD should try to gather DVD folder name as Title [Folder name/VIDEO_TS.IFO] if foldername contains "VOLUME" also try to get upper folder name
Title: DVD - Folder name {- Volume N}
(MPC-BE has similar DVD parsing)

2. Playlist shows previously opened media item, might be related # 1

3. Seek video preview has issue that it doesn't find preview on first seek try. But it has no problem hovering through on seekbar. (Maybe large chunks or indexing related things)

4. While DVD mode, open file location doesn't work.

5. Save Thumbnails is not possible even on local (non-disc) DVD

6. Status bar shows wrong ~resolution and~ fps. (Interlaced related)

![resim](https://github.com/user-attachments/assets/f17c7d0e-9cdc-417e-8684-b39ca8a517c4)

7. Temporarily apply `Assume square pixels (SAR)` if necessary

Without: Assume square pixels (SAR) and Zoom: 100%
![resim](https://github.com/user-attachments/assets/d95ae552-0630-492d-bd65-299b2a94903a)
With: Assume square pixels (SAR) and Zoom: 100%
![resim](https://github.com/user-attachments/assets/87d82738-6486-4e14-b9f2-9a308bea259e)

8. DVD always loop itself after playing ends. If looping intentional, after playback options should be disabled.

9. Information bar

![resim](https://github.com/user-attachments/assets/3db663e5-9647-4866-b69b-31c1f84b097d)

Volume: 1, Titlee: 2/4, Chapter: 2/17
Angle: 1,

10. Skip forward/backward OSD message

![resim](https://github.com/user-attachments/assets/ef4b3a2a-5c80-4ebc-99da-03d3be49734f)

Zero hours can be trimmed and making it similar to regular skip forward/backward might be good.
`TimeElapsed / TotalTime -double space- "Chapter name" (x/totalN)`

**Comment by v0lt** [comment]
DVD-Video opens in a special interactive mode with its own capabilities and limitations.

If you really want to solve some of the problems (preview, thumbnails, etc.), then open VTS_0x_0.IFO instead of the entire disc. In this case, the "file" mode will be used.
VTS_0x_0.IFO, which corresponds to a movie, is easy to determine by the largest size of the subsequent VOB files.
