### ISSUE TITLE
MPC-HC not redirect bass on 5.1  wassapi exclusive mode

### ISSUE THREAD

**Issue by digi340** [clsid2/mpc-hc#30]
Hy to all.I use MPC-HC .The problem is with wassapi sound output on VIA 1705S soundboard.When use wasapi exclusive mode bit perfect the bass is not redirected to subwoofer on 5.1 speaker configuration.

**Comment by clsid2** [comment]
Menu > Play > Filters > LAV Audio decoder
On its status tab you can see its input and output details.

**Comment by digi340** [comment]
Source is mp3, aac+, ogg, opus - input 2 channel , output 2 channel , speaker configuration 5.1. Other player like MPC-BE, Jet Audio, J River, Pot Player if sourse is 2 channel and speaker configuration is 5.1 emulate 2 channel from source to 5.1 channel  and redirect bass to subwoofer .The problem  is MPC-HC emulate from 2 channel to 5.1 but not redirect bass to subwoofer.On subwoofer is silence.

**Comment by clsid2** [comment]
Stereo input does not contain a subwoofer channel. The audio decoder does not upmix (it only adds silent channels) and that feature is also not planned by its developer. If you want proper surround sound you need to play a surround audio track.

Audio drivers often provide an upmix option. Common names used for that are "speaker fill" and "DTS connect". Receivers can also upmix.

**Comment by clsid2** [comment]
Then don't use wasapi exclusive mode. It doesn't give better quality.
