### ISSUE TITLE
Toolbar image is Broken...

### ISSUE THREAD

**Issue by Phar-Lap** [clsid2/mpc-hc#300]
My favourite toolbar image no longer works.
I have tested it in Media Player Classic Home Cinema 1.9.1 only.
gem_black_24 (small) works.
gem_black_32 (big) does not work.

mpc_toolbar_Gem_Black_by_Xyteton.zip/gem_black_32 (big)/toolbar.png

Also, it would be nice to be able to user our own toolbar.png with the new Dark Theme.

![mpc_toolbar_Gem_Black_by_Xyteton](https://user-images.githubusercontent.com/61812089/76024875-f68ad380-5f7f-11ea-91f2-90ff329af1ce.png)

**Comment by clsid2** [comment]
Custom toolbar file is loaded using these filenames:
toolbar.png (normal theme / grayscale buttons)
toolbar_dark.png (dark theme / grayscale)
color_toolbar.png (normal theme / colored buttons)
color_toolbar_dark.png (dark theme / colored buttons)
