### ISSUE TITLE
MPC HC switches to default (old) theme upon opening file (see attatched images)

### ISSUE THREAD

**Issue by Wendi-bnkywuv** [clsid2/mpc-hc#3007]
I'm noticing that the 64 version of MPC HC will open in the old theme if the file is opened other than the pinned player on my taskbar. That is, I have to right click on the taskbar icon and bring it up manually, but if I double click on the file itself, it will switch to the old version of MPC HC. There is also no "use modern theme" selection in the options menu for said method. Quite confused!

![Screenshot 2024-08-17 192915](https://github.com/user-attachments/assets/d370da98-8392-4498-b0ea-80b3e85227c8)
![Screenshot 2024-08-17 193019](https://github.com/user-attachments/assets/7bceca5c-8a17-4556-b77d-cf38aae5a583)
![Screenshot 2024-08-17 193057](https://github.com/user-attachments/assets/a17eb912-9492-40ef-a8de-43e972c440fb)
![Screenshot 2024-08-17 193114](https://github.com/user-attachments/assets/d449264b-d644-446b-8d56-81d0891c0473)

**Comment by clsid2** [comment]
You obviously have two different versions of the player installed.

Uninstall everything and only install latest version.

**Comment by Wendi-bnkywuv** [comment]
I've tried uninstalling the old version through the add/remove programs,
but I'm still getting the issue. Not sure if it's installed in another
directory.
