### ISSUE TITLE
Youtube-dl zipped version is ignored by MPC-HC

### ISSUE THREAD

**Issue by ThePirate42** [clsid2/mpc-hc#301]
Due to a youtube-dl bug ([https://github.com/ytdl-org/youtube-dl/issues/10766](url)) I need to use the zipped version of youtube-dl, and because of this I've created a batch file called youtube-dl.bat with this content:
`@ECHO OFF
python C:\Path\youtube-dl %*`,
but mpc-hc ignores it. Does a solution exist?

**Comment by clsid2** [comment]
MPC-HC only works with the .exe version.
