### ISSUE TITLE
Auto-hiding panels cause false focus after hiding

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#3016]
Steps:

- Enable > Hide Windowed Controls
- Focus > Desktop or any other app
- Hover MPC-HC Panels (Subresync/Playlist)
- False focus occurs when panels are auto hidden.

![explorer_F5MYqfk8vu](https://github.com/user-attachments/assets/d29dc477-72ba-4648-acf4-504d806ea0b9)

**Comment by clsid2** [comment]
I don't mind if this one gets marked as "won't fix".

**Comment by adipose** [comment]
Yeah seems pretty minor to me.  It is interesting how it doesn't actually come to foreground but the titlebar changes.  Maybe a windows bug.

**Comment by xLn2** [comment]
Yes, I mentioned because a problem that seems very trivial can reveal something more important that lies deep down but there are no negative effects so far. Might be childwindow related thing that assume if window is hiding it is active.

**Comment by adipose** [comment]
Looks like it was caused by the restorefocus thing I added.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/3022

Easily fixed.  The purpose of this function was to restore focus when a hidden toolbar had taken it.  If the app has no focus then there is no need to restore it.  SetFocus() when the app is not foreground seems to have no impact except lying to the titlebar.
