### ISSUE TITLE
Vertical lines in subtitles download when resizing columns

### ISSUE THREAD

**Issue by irwir** [clsid2/mpc-hc#3029]
Build 2.3.4.29 in Windows 11.
Start an .avi movie.
Open Download subtitles... from the menu.
Wait for the file list to get filled
Grab, drag and release dividers in column headers.
See vertical black lines going from the header down to the bottom of the the list.

**Comment by ArcticGems** [comment]
Could you post a screenshot?

**Comment by irwir** [comment]
![sub_dialog](https://github.com/user-attachments/assets/29b9603f-3a15-4d8b-a7ff-7756df1cfc79)

**Comment by adipose** [comment]
Hmm that's classic view which is probably using customdraw or something. I can take a look at some point.

**Comment by adipose** [comment]
Can you post the output of Help/About/Copy to Clipboard?

**Comment by irwir** [comment]
Build information:
    Version:            2.3.4.38 (62b715043)

Operating system:
    Name:               Windows 11 (Build 23H2)
    Version:            10.0.22631 (64-bit)

Hardware:
    CPU:                12th Gen Intel(R) Core(TM) i5-12600
    GPU:                Intel(R) UHD Graphics 770 (driver version: 32.0.101.5972)
    Monitor:            \\.\DISPLAY2 - Philips 278B1 (27inch Wide LCD MONITOR ) [3840x2160 32-bit 192 DPI] - [Current]

**Comment by adipose** [comment]
Did you not get the `Text` section in the About?

**Comment by irwir** [comment]
Scaling is 1. Code page change has no effect.

By the way, with a bit of trying it was possible to get the lines with empty list too.

I used to see  black line only on the side being dragged, while in this dialog both sides of the resized column are shown as black lines.

**Comment by adipose** [comment]
By the way I never reproduced this.  Did you ever test in the dark theme?  It uses a different custom paint.

The classic is using owner draw which doesn't control the cell borders, if I recall correctly.

**Comment by irwir** [comment]
Never tried it with a dark theme.
Still can reproduce in 2.3.6 - with an empty list too.

Try to play with column resizing (the handle to grab on the right side in the table header).
1. Open movie and stop it
2. Open subtitles download dialog and wait until done (even if nothing was found).
The order of columns for playing is this: `Title(s)`, `Score`, `Disc`
3. Resize `Title(s)` - grab and drag to the sides; there is one black line.
4. Drop and grab the same handle again, drag - now there are two black lines.
5. Drop, grab `Disc` handle - now there are two black lines; one on the right side of `Disc`, but another on the right side of `Title(s)`.
... and so on.
These second lines sometimes remain after dropping handles.

**Comment by adipose** [comment]
I tried a lot of things but nothing reproduced it.  Can you try some different dpi settings, animation settings, etc.?

**Comment by irwir** [comment]
Tried a lot of what things, and where it differs from the pictures?

It is 200% scaling,  `Enable Peek` and `Smooth edges of screen fonts` are on, all the rest was off.
What is known, eMule uses `CListCtrl` and does not have the issue; and shows one column border while resizing - never two.

**Comment by adipose** [comment]
I have never seen the artifact at any resolution or dpi scaling, is what I meant.

**Comment by adipose** [comment]
> Tried a lot of what things, and where it differs from the pictures?
> 
> It is 200% scaling, `Enable Peek` and `Smooth edges of screen fonts` are on, all the rest was off. What is known, eMule uses `CListCtrl` and does not have the issue; and shows one column border while resizing - never two.

Thank you, I was able to reproduce it.  It is caused by you disabling "show window contents while dragging."  This setting means that the cells are not redrawn while dragging, which seems to be leaving behind the artifact of the resizing box that is drawn extraneously by windows to simulate the resizing window.  

It affects modern them as well.  I will do some research about how custom draw code is meant to handle this setting being disabled.  It is very rare for this setting to be disabled these days, which was first enabled by default in Windows 95, almost 30 years ago.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/3136

**Comment by irwir** [comment]
The `rare` settings are trivial: best performance (no frills) plus two really useful features.

> This setting means that the cells are not redrawn while dragging, which seems to be leaving behind the artifact of the resizing box that is drawn extraneously by windows to simulate the resizing window.

This does not quite explain why there were two black lines, one in the previous place of dragging and in wrong column too.
Information is scarse, but it seems that "end track" event (end of dragging) was not properly handled.

FYI, the latest Canary Windows in VirtualBox shows no black vertical lines at all - with exactly the same settings (.ini file), except, unrelated to list controls, renderer had to be changed.

**Comment by adipose** [comment]
> The `rare` settings are trivial: best performance (no frills) plus two really useful features.
> 
> 
> 
> > This setting means that the cells are not redrawn while dragging, which seems to be leaving behind the artifact of the resizing box that is drawn extraneously by windows to simulate the resizing window.
> 
> 
> 
> This does not quite explain why there were two black lines, one in the previous place of dragging and in wrong column too.
> 
> Information is scarse, but it seems that "end track" event (end of dragging) was not properly handled.
> 
> 
> 
> FYI, the latest Canary Windows in VirtualBox shows no black vertical lines at all - with exactly the same settings (.ini file), except, unrelated to list controls, renderer had to be changed.

I was wrong.  The inverted resize box was being drawn but not reinverted.  This was caused by the "end track" notify being marked as already processed.

And pResult doesn't fix it.  That's the "result" which is ignored for that event type.  The return value allows you have indicate you didn't process the message.

**Comment by irwir** [comment]
Unfinished processing of dragging as an explanation is reasonable.
However, as somebody explained, black line is a visualizer where the column boundary would be if dropped at the moment; not a resize box.

**Comment by adipose** [comment]
>Unfinished processing of dragging as an explanation is reasonable.

I know, that's how I fixed it :)

>However, as somebody explained, black line is a visualizer where the column boundary would be if dropped at the moment; not a resize box.

Yes, it's true, the common controls animation is a single vertical line for resizing a column in "no contents" mode.  It's a resize "line" if that makes you feel better ;)
