### ISSUE TITLE
Subtitle default style issue?

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#3031]
My settings:
![Screenshot (321)](https://github.com/user-attachments/assets/c858c105-5280-4be2-a967-08578c25de5d)
The new options are confusing and I think they are not working correctly.
![Screenshot (317)](https://github.com/user-attachments/assets/6efd0fc6-7225-4a37-aae5-ce57a070f9fb)
![Screenshot (318)](https://github.com/user-attachments/assets/8c19f50e-ae29-42f3-b27c-960f17df5604)
![Screenshot (319)](https://github.com/user-attachments/assets/38d70ead-b752-41c8-87f7-9b778aa81873)

I used to use default style to force ass/ssa subtitle to use my style, not its own style. Now things are kind of broken.
And secondly, Override default style or Override embedded style? Which one is correct?

**Comment by NBruderman** [comment]
You need override embedded style, that's the way you can override subtitles with embedded styles.
Also, the next release will have overhaul of these settings.

**Comment by bibsp** [comment]
Subtitle is very small in 2nd pic.
**Clsid/adipose** is that correct? I don't think so.

**Comment by clsid2** [comment]
Give link to the video.

**Comment by bibsp** [comment]
https://fastilinks.fun/view/epPfAjHjbN

In previous version (Default style enabled) I used to get same result as last pic.

Means, Old version Default style enabled = Version 2.3.4.36 Override all styles enabled.

**Comment by clsid2** [comment]
Should be fixed in .38
