### ISSUE TITLE
Keyboard and Mouse Malfuction During Assigning Hotkeys

### ISSUE THREAD

**Issue by gitman-user** [clsid2/mpc-hc#3032]
While I was assigning hotkeys that had 2 inputs, which were ctrl + scroll wheel, I suddenly I couldn't type out anything else. Then I tried typing out words outside of the program, and nothing. Right click on the player wasn't bringing up the menu either. When I opened a new browser tab, typing did nothing in the URL bar either but pressing D (instead of ctrl + d) would automatically save the page as a favourite and open the favourites page, and the scroll wheel would zoom in and out (instead of ctrl + scroll wheel). 

I was able to fix these issues by restarting my PC but having it mess with my mouse and keyboard is a bit concerning and I hope it gets fixed.

Thanks.

**Comment by gitman-user** [comment]
Could I please at least have a some information on whether you've heard cases like these before? Would you say that this is an issue that happened while using the software but caused by something Windows related maybe?

**Comment by clsid2** [comment]
Issue on your side
