### ISSUE TITLE
Add Configurable Millisecond Option for Seeking

### ISSUE THREAD

**Issue by gitman-user** [clsid2/mpc-hc#3033]
Hi, 

Would it be possible to adjust the seeking on a video to be configurable up to frame by frame? I know there are already option for small jumps which is great, but an option for seeking as well would be great instead of having it only be second by second. 

Thanks.

**Comment by clsid2** [comment]
Why do people keep asking for features that are already present for two decades???

There literally is a button for frame stepping.

**Comment by gitman-user** [comment]
I understand, and it's very useful. I'm just saying that maybe it would hurt to add such options when seeking when dragging the mouse but if it's not doable, I understand.

**Comment by clsid2** [comment]
Hold Shift while clicking seekbar
