### ISSUE TITLE
Remember last window position and size

### ISSUE THREAD

**Issue by KiwiSorbet** [clsid2/mpc-hc#3036]
I've been recently a bit annoyed by how opening a file from my file manager (which I usually have on a secondary vertical monitor) launches the player on the same monitor as the file manager. While the size of the window can be sort of changed in the settings to fit that of the monitor edges or the video frame itself, it seems there is no way to for the player to be launched in the same window size and monitor that it was last exited in. Is there a way to do this that I'm unaware of? If not, it would be nice if this kind of feature could be added

**Comment by clsid2** [comment]
Those options are literally on the very first page in the options...

**Comment by KiwiSorbet** [comment]
Oops, I guess I should stop setting up my things at 3 AM Dx

**Comment by Suncatcher** [comment]
> Those options are literally on the very first page in the options...

it is true, but I wasn't able to find them quickly as well, I was searching them in UI section, not in the root settings node. Maybe it's worth rethinking the settings and move them to UI?
![image](https://github.com/user-attachments/assets/aecc7411-a338-4549-b0b2-e306ffef9986)

**Comment by KiwiSorbet** [comment]
I agree. The reason this issue came up is that I couldn't figure out that those nodes actually contained settings themselves.
