### ISSUE TITLE
Is the info good enough?

### ISSUE THREAD

**Issue by gaunterodimm11** [clsid2/mpc-hc#3037]
![456385256_1907281856443790_7695821891758097977_n](https://github.com/user-attachments/assets/289146dc-9321-440f-a0c2-1fee926a94e3)
So i watch some movie with DV supported in LG C4 as my monitor. But when i play in full screen, the TV switch picture mode to HDR instead Dolby Vision.

Then i use another app like Energy Media Player which not switch picture mode automatically when full screen, that mean i watching with Dolby Vision picture mode.

But if i compare, the HDR quality and color there is like no difference, it's like HDR = Dolby Vision, but idk if using a comparison based on data.

Then I open debug renderer shows in picture, is the info good enough or there is option in setting need to change?

**Comment by clsid2** [comment]
The renderer converts DV to HDR metadata.
