### ISSUE TITLE
Flickering problem on full screen when the bottom control bar is displayed

### ISSUE THREAD

**Issue by Vorffeed** [clsid2/mpc-hc#3038]
Good I have recently updated to the latest version and I've been noticing that when I'm in full screen and I scroll down with the mouse to get the drop down control bar, every x times randomly the image flickers and it seems as if some filter is activated or deactivated making the colours get very bright, anyone knows what it can be, because that did not happen before and I'm dragging the same settings I had before.
I use the classic mode skin of the player

**Comment by clsid2** [comment]
If the video colors change then it is probably related to HDR.

It is a bug in Windows/graphics driver and I can not help you with it.

**Comment by Vorffeed** [comment]
But I don't have hdr on windows, at most the one that comes with madvr, and as I said, I didn't do that before.

**Comment by clsid2** [comment]
Does it only happen with HDR video or with any video?
Does it also happen with a different video renderer?
Press Ctrl+J to show Madvr debug overlay, and check if anything changes in the debug output when problem occurs.

Test older (development) builds and tell me when problem started:
https://github.com/clsid2/mpc-hc/releases

**Comment by Vorffeed** [comment]
The only variation when the colour flickers is when the floating menu comes up under the fullscreen playback controls change d3d11 fullscreen windowed (10) to windowed (10) and windowed (8) and back to fullscreen windowed (10). 
and it does it with any video with madvr if i change the render it doesn't do it.

**Comment by clsid2** [comment]
I can not help with bugs in Madvr.
