### ISSUE TITLE
(Bug) File Orders Other Than "by Name" Are Ignored

### ISSUE THREAD

**Issue by ars4l4n** [clsid2/mpc-hc#3039]
When I set the files in my folder to be sorted by size rather than name in the explorer and then open a file in MPC-HC and go to the next file within the program it will still go to the file that is next name-wise, rather than size-wise.

Same issue when trying to sort by date. MPC-HC will always act as if the files were sorted by name.

Windows 10 (Build 22H2)
MPC-HC 2.3.4.17

**Comment by clsid2** [comment]
The view order setting in Explorer only affects Explorer.

It does not affect other applications, and there is zero reason for that as well.

MPC-HC only sorts by name and that is not going to change.
