### ISSUE TITLE
Using yt-dlp parameter -P breaks support for youtube-dl

### ISSUE THREAD

**Issue by hurda** [clsid2/mpc-hc#3040]
Commit 13cc5ab1fb481c57f07a4782ca155615e065f63a breaks support of [youtube-dl (nightly)](https://github.com/ytdl-org/ytdl-nightly), as it seems the -P parameter is exclusive to yt-dlp.

Noticed it as I had to switch to youtube-dl for a particular streaming-site, and the changes necessary for that site haven't reached yt-dlp yet.

**Comment by clsid2** [comment]
Fixed.
