### ISSUE TITLE
Enhance File Delete to include external subtitle and audio files

### ISSUE THREAD

**Issue by xypha** [clsid2/mpc-hc#3045]
Version: 2.3.5

Example file structure:
```
\folder1\subs\example_file.jpn.vtt
\folder1\example_file.mp4
\folder1\example_file.m4a
\folder1\example_file.en.vtt
```
Current Behaviour:
* Play `example_file.mp4`.
* Audio and subtitle files are loaded along with the video file (see screenshot below).
* Press `File Delete` keyboard shortcut.
* `example_file.mp4` is deleted (sent to recycle bin), but other files are untouched.

![mpc-hc issue](https://github.com/user-attachments/assets/3b58aa66-8bfa-4594-9703-35c381447cf7)

Expected Behaviour:
* Play `example_file.mp4`.
* Audio and subtitle files are loaded along with the video file.
* Press `File Delete` keyboard shortcut.
* All files in `Example file structure` are deleted (sent to recycle bin), i.e., all loaded audio and subtitle files are deleted along with the video file.

Bonus enhancement:
* add File Delete to context menu under `After Playback` or `Play`

**Comment by clsid2** [comment]
Deleting audio dubs will not be implemented. Some dumb people use very generic file names.

**Comment by NBruderman** [comment]
Maybe a prompt can show up? like "do you want to delete only the file, or related files as well?",
which can show the names of the files in the structure? so people won't complain if the files are gone

**Comment by xypha** [comment]
> Deleting audio dubs will not be implemented. Some dumb people use very generic file names.

@clsid2 
* A solution to this could be to provide the user the option to enable file delete for audio with default set to 'Off/Do not delete'.
* What are your thoughts on subtitle deletion and adding file delete to context menu?

**Comment by clsid2** [comment]
I am not adding a new option.

**Comment by adipose** [comment]
I'm not excited about deleting associated files automatically.  My concern is that mpc-hc makes an effort to identify files that are assosciated, but the effect of this is at worst that you have some files that aren't related.  Introducing delete to that situation makes those guesses a lot more significant.

If it were done, it should probably loop through possible candidates for deletion and then ask for each one, "delete it?"

**Comment by xLn2** [comment]
Although I am not sure of its applicability, I can summarize the author's intention and possible use case scenario as follows.

- It makes more sense to check only the loaded files, as it would be futile to try to detect possible similar filenames.
- There can be several subs and dubs loaded for a file but users probably want/use latest active ones and maybe only wants to delete latest ones or ALL. [Default AutoSelectAll] // Should all loaded items be checkmarked as default? or some advanced settings for that?
- Move to Recycle bin message prompt may have listbox with checkbox for select loaded items like Subtitle Downloader or RARFileSource dialogbox. 

Dub
___
1. Filename | Filepath
2. Filename | Filepath

Sub
___
1. Filename | Filepath
2. Filename | Filepath

**Comment by adipose** [comment]
Even if loaded, it could be unrelated file. Maybe I am too careful but not seems possible to have unintended deletes.

**Comment by clsid2** [comment]
I have pushed a commit that skips saving of downloaded sub during file close when deleting the video.

**Comment by adipose** [comment]
> I have pushed a commit that skips saving of downloaded sub during file close when deleting the video.

That seems reasonable.
