### ISSUE TITLE
2.3.5 video freezing on HEVC video playback (audio continues)

### ISSUE THREAD

**Issue by JNavas2** [clsid2/mpc-hc#3046]
Preliminary report:
In playing a 45 min 1080p HEVC file using the MPC Video Renderer in 2.3.5 on Windows 10,
twice the video froze while the audio kept playing.
When closing 2.3.5 I got a Filter Graph timeout error.
I uninstalled 2.3.5, reinstalled 2.3.4, and the video played without freezing.
I have not investigated this thoroughly, so I don't know how reproducible it is.
How would you like me to proceed?

**Comment by JNavas2** [comment]
I was able to readily reproduce the issue simply by playing the video file, and then jumping forward and back a few times by clicking on the timeline with my mouse. I created a full dump. I got the same error (below) when I closed it.
I have both the video file and dump on Google Drive if you give me a private way to share the link with you. 
(My email address is in my GitHub profile.)

<img width="354" alt="mpc-hc64_G5N4GlMz6u" src="https://github.com/user-attachments/assets/64e913e4-ba9b-4b0e-88e8-513ff97a48b9">

**Comment by JNavas2** [comment]
Thank you, but as I initially wrote, I'm using MPC Video Renderer, not madVR.
Regardless, what works with 2.3.4 should still work with 2.3.5, no?

**Comment by JNavas2** [comment]
I tried upgrading to 2.3.5.4, but while it will launch and run, no GUI appears, making it unusable.

**Comment by JNavas2** [comment]
> Is any of the following software installed on your system? Trusteer Rapport Asus GamerOSD Asus GPU Tweak OSD Nahimic Audio LoiLoGameRecorder

No, none of those are installed on my system, which is a Lenovo ThinkPad.
* Audio is Realtek.
* Display adapters are Intel HD 530 and NVIDIA 940MX.

All drivers are standard except that I use Intel reference drivers for Wi-Fi and Bluetooth.

**Comment by xLn2** [comment]
I guess 32cdf8cf9631ba885d5ccf368b110bf11a95d976 might lead to this issue since https://github.com/Nevcairiel/LAVFilters/commit/2bf67eb3156220f9f01a2f03646188280acad270 this may have been caused by the updated FFmpeg upstream in anticipation/intent to resolve some HEVC issues in LAV Filters.

**Comment by JNavas2** [comment]
2.3.5.6:
* fixes the loading problem
* appears to fix the HEVC video problem

I'll run more tests shortly, but for now I consider this issue closed.
Thank you!

**Comment by JNavas2** [comment]
Be that as it may, I did a binary compare to the lavfilters folder from 2.3.4, and all of the files other than the manifest were different.

**Comment by JNavas2** [comment]
> You said the problem was with 2.3.5

The problem is indeed with 2.3.5.
Comparison of 2.3.5.6 to both 2.3.4 and 2.3.5:

<img width="680" alt="WinMergeU_L1gZoM38W4" src="https://github.com/user-attachments/assets/bcdd50d2-e65f-48a9-8bd7-8663c09a8bdd">

<img width="680" alt="VpzmQ3iUzN" src="https://github.com/user-attachments/assets/098a36ef-955e-4b4b-8471-9e92ec24bfdb">
