### ISSUE TITLE
Strange new gap on the Control Bar in the recent 2.3.5 update

### ISSUE THREAD

**Issue by dftf-stu** [clsid2/mpc-hc#3047]
I like the MPC-HC interface to be as compact as possible, so I like to resize the player
to the lowest width and height I can (while still seeing all the controls / info I'd like).

As of the recent 2.3.5 release, the minimum-width seems to have increased however,
though only when using the "modern" themes:

![MPC-HC_UIBug](https://github.com/user-attachments/assets/eab04151-8a7d-4a29-84c2-314fc6cf1e1e)

A new gap has been added on the _Control Bar_ between the "go to next chapter"(?) button
and the "mute" button, meaning the minimum-width I can resize down-to has increased.

I've reverted back to 2.3.4 on my system, but is this something that could be fixed for 2.3.6?

Thanks

**Comment by clsid2** [comment]
No.

**Comment by dftf-stu** [comment]
@clsid2 Okay, thanks for the reply!  Not sure why the gap was added as it serves no-purpose, given no new toolbar buttons have been added or anything, but I'll just stick on 2.3.4 and turn off the update notifications.  Have a good day!

**Comment by clsid2** [comment]
Fixed
