### ISSUE TITLE
Non-default settings for right mouse button are not saved after player restart

### ISSUE THREAD

**Issue by vsemozhetbyt** [clsid2/mpc-hc#3048]
This is not a complaint about new mouse settings or a new feature request. I know these are prohibited, and I am sorry I am the one whose abuse was one of the causes.

I hope this is a bona fide bug report.

Windows 10, MPC 2.3.4.40 (32cdf8cf9)

If I select a "Jump Backward (medium)" for right mouse button, the effect is preserved during the current session, also `HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\Mouse\ButtonRight` registry key is changed to 901 id. However, after application restart, the default settings are restored, the mouse settings dialog shows default settings (menu) despite registry key is still 901 (see a screenshot).

![1](https://github.com/user-attachments/assets/c14d8ee8-b3c3-4b56-8555-d1251bdc7cf8)

After the player is closed second time, the registry key is also restored to default 950 id (menu).

I am sorry if I am missing something.

**Comment by clsid2** [comment]
Fixed
