### ISSUE TITLE
problem with switch picture mode automatically

### ISSUE THREAD

**Issue by gaunterodimm11** [clsid2/mpc-hc#3052]
in version 2.3.4, when I insert a movie by dragging, mpc will immediately go full screen and return to windowed like a bug.

but for me this is a good bug because my TV will change the picture mode to HDR automatically, and when I hover mouse to the bottom of the control or pause the movie, the picture mode will not change automatically, so it remains HDR.

in the latest version, the bug may have been fixed? so when I insert the movie, mpc does not immediately go full screen, but only windowed, when I change it to full screen, as usual the picture mode will change to HDR, but when I pause or hover the mouse to the bottom of the control, the picture mode changes to Dolby Vision, Its like I exit the full screen.

or maybe this is problem with new setting?

**Comment by gaunterodimm11** [comment]
never mind it fixed

**Comment by clsid2** [comment]
Not a bug. The player also was not switching to fullscreen and back.

You can find an option in setting of MPC Video Renderer to turn on Windows HDR. That switching your display into HDR mode.
