### ISSUE TITLE
Jump Forward/Backward (Short) in wheel's menu

### ISSUE THREAD

**Issue by darnabar** [clsid2/mpc-hc#3054]
Dear clsid2:

Could you add the Jump Forward/Backward (Short) option in wheel's menu, please? I guess it will be easy for you to do so, and I really, REALLY need it for my job. I work as a dubbing translator, and the 3 options (short/mediuem/large) were very useful for me.

I hope it doesn't bother you.

Thank you very much in advance.

David

**Comment by clsid2** [comment]
Click on the three dots (...) in bottom of list.
