### ISSUE TITLE
"Store setting in .ini file" issue

### ISSUE THREAD

**Issue by Just3dnane** [clsid2/mpc-hc#3055]
I reinastalled MPC-HC and I wanted to replace the .ini to access to my "recent file" list, but unfortunately I can't enable it, why?

**Comment by clsid2** [comment]
INI file is for portable use. Your use is not portable.

Programs file is a protected folder without write access for unelevated processes.

Follow these instructions and follow them EXACTLY:
1. Make a temporary copy of mpc-hc64.exe in another folder
2. Put the ini file in that folder
3. Run mpc-hc and UNcheck the option to use INI
4. That moves settings into the registry
5. Delete the temporary copy of mpc-hc
6. Go to `Options > Miscellaneous > Export` to backup your settings as a .reg file. You can double-click a .reg file to restore settings.
