### ISSUE TITLE
Frame step for Wheel Left/Right

### ISSUE THREAD

**Issue by silverqx** [clsid2/mpc-hc#3056]
The new Mouse Options doesn't allow to set Frame Step for Wheel Left/Right, I used it this way, would be possible to add these commands? Thx

**Comment by clsid2** [comment]
Click on the three dots (...) at bottom of list

**Comment by silverqx** [comment]
I didn't notice it, these three dots are almost invisible, some lists are using `<...>` for this to be better visible.

Thx
