### ISSUE TITLE
ToDo: switch to IMFVideoMixerBitmap OSD mode in fullscreen when using MPCVR

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#3057]
Use IMFVideoMixerBitmap (bitmap draw) instead of the default GDI draw mode in fullscreen.
Edit: DONE

This might help with HDR issues where showing player GUI elements causes color changes or display mode changes.

Also use the exclusive mode seekbar? Preferably we should detect if fullscreen display is running in HDR mode.
Edit: Added code to detect MPCVR exclusive mode. Seekbar is not working yet.

**Comment by clsid2** [comment]
Seekbar now also working in exclusive mode.

Separate fullscreen is broken when MPCVR uses exclusive mode. MPCRV gives S_PRESENT_OCCLUDED error
https://learn.microsoft.com/en-us/windows/win32/direct3d9/device-state-return-codes
Clicking on player toolbar also stops working.

**Comment by Aleksoid1978** [comment]
Separate fullscreen for MPC VR Exclusive fullscreen is working in MPC-BE.

**Comment by clsid2** [comment]
It is still a work in progress.

**Comment by clsid2** [comment]
I got it working by using `SetD3DFullscreen`.

**Comment by clsid2** [comment]
@Aleksoid1978 
I have a question regarding these lines in MPCVR debug output:
`Blocking call SystemParametersInfoA function during initialization VP`

Do you know which specific `uiAction` values cause a problem during VP init?
It seems weird to me to blindly block all calls when most of them should be harmless.

As a test I disabled the block and I did not see any issues.

**Comment by Aleksoid1978** [comment]
In short - this is how it should be. If you don't block it - it could be bad.
