### ISSUE TITLE
Dark Theme has some flickering...

### ISSUE THREAD

**Issue by Phar-Lap** [clsid2/mpc-hc#306]
Using Media Player Classic Home Cinema 1.9.1:

Click [File -> Open File/URL...] or [Ctrl+O].
The Open: or Dub: input fields blink when hovering the mouse pointer over them.

It blinks because the input field is temporarily changing colour to the same colour as when you hover over Browse..., OK or Cancel.

Mouse is steady
![Mouse is steady](https://user-images.githubusercontent.com/61812089/76174383-111cb100-61fb-11ea-9c09-ea62002fbf1a.png)

Mouse is moving
![Mouse is moving](https://user-images.githubusercontent.com/61812089/76174394-1bd74600-61fb-11ea-936c-7b94730e4087.png)

**Comment by adipose** [comment]
I see some flicker.  It is due to the single pixel of focus that is allowed before it starts to hover over the text area.  I'll take a look.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/311
