### ISSUE TITLE
ToDo: change hover type dropdown into a checkbox "video preview"

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#3062]
Some people are currently struggling to find the video preview option. Better to make it into a checkbox so it is more obvious.

**Comment by adipose** [comment]
What if we just made it the default?

**Comment by clsid2** [comment]
For a few users the preview graph causes a delay when closing the file. I want to investigate that further before enabling it by default.

**Comment by adipose** [comment]
Maybe the word "hover" could be replaced with "preview," and the dropdown could say "video/seek time."  Not sure if that's an improvement.

**Comment by clsid2** [comment]
```
[ ] Show video preview
[ ] Show time     [Dropdown: Below/Above seekbar]
```

When checking `Show video video` grey out and check `show time` (as preview always includes time). If both unchecked then grey out the dropdown.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/3095
