### ISSUE TITLE
Brightness bug

### ISSUE THREAD

**Issue by Frankeinst** [clsid2/mpc-hc#3067]
When dark scenes and brighter scenes happens right after the other sometimes the video change the brightness up or down too much very quickly. Maybe if I record will be easily to understand.

**Comment by clsid2** [comment]
The player does not do any dynamic/automatic adjustment of brightness.

Your graphics driver or Windows is doing that.

https://www.intel.com/content/www/us/en/support/articles/000039392/graphics.html
https://www.tenforums.com/tutorials/70157-enable-disable-adaptive-brightness-windows-10-a.html
