### ISSUE TITLE
Can't open Tiktok videos

### ISSUE THREAD

**Issue by ObjectInSpace** [clsid2/mpc-hc#3069]
I can download videos from tiktok with yt-dlp by simply passing yt-dlp the URL of the video. However this does not work when I paste the URL in the open file dialog of MPC-HC. Other sites (E.G. youtube) work as expected.

**Comment by clsid2** [comment]
Extracted urls give error 403 access denied.

This will not be fixed. I am not interested in any further discussion.

Download the video before play.
