### ISSUE TITLE
ToDo: Add more functionality for MPC Video Renderer

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#307]
- Rotation
- OSD
- Shaders
- Ctrl+J to show statistics overlay

**Comment by Aleksoid1978** [comment]
In MPC Video Renderer implemented support for IMFVideoMixerBitmap, MPC-HC can draw OSD via it.

**Comment by adipose** [comment]
Most of this would be pretty easy to port from mpc-be.  I've looked at the code quite a bit while working on DAR.  However, the base implementation for the AP needs updating, which affects all the other renderers.  I don't see a problem, but we might get some of these features upgraded for other renderers as well.

**Comment by clsid2** [comment]
Yes, this open issue has the highest priority right now. I see MPCVR as a potential default renderer in the future.

**Comment by adipose** [comment]
@clsid2 , what deficiencies are there in the OSD?  It seems to work for me at the moment.

**Comment by clsid2** [comment]
It didn't work originally. Some of your recent code merges made it work.
