### ISSUE TITLE
MS Smart App

### ISSUE THREAD

**Issue by GaryTK** [clsid2/mpc-hc#3070]
It is Blocking this app,MPC-HC-2.3.5  X64 even though I have been using it for years.
![MPC-HC 2 3 5 x64](https://github.com/user-attachments/assets/56259d64-e7cb-4202-bf64-d06218f13d42)

**Comment by GaryTK** [comment]
It seems that if you don't get it from MS's Store you can't use it.

**Comment by clsid2** [comment]
Windows Settings > Privacy & security > Windows Security > App & browser control > Smart App Control settings > Off

MPC-HC isn't present in the Windows Store and never will be. Anything you see in there that claims to be MPC is fake.
