### ISSUE TITLE
Unable to disable pause/play with left mouse click

### ISSUE THREAD

**Issue by Petarkco** [clsid2/mpc-hc#3071]
In the recent version(s) I have not been able to disable pausing/playing of media via left mouse click.
I usually am able to disable it via the Keys menu in Options, but it does not appear:
![image](https://github.com/user-attachments/assets/22cacaca-cb06-4d67-917d-b68309022512)

MPC-HC (64-bit)
---------------

Build information:
    Version:            2.3.5 (53e45e3b4)
    Build date:         Sep  2 2024

LAV Filters:
    LAV Splitter:       0.79.2.19
    LAV Video:          0.79.2.19
    LAV Audio:          0.79.2.19
    FFmpeg compiler:    MinGW-w64 GCC 13.3.0

Operating system:
    Name:               Windows 11 (Build 23H2)
    Version:            10.0.22631 (64-bit)

Hardware:
    CPU:                AMD Ryzen 9 5950X 16-Core Processor
    GPU1:               NVIDIA GeForce RTX 3080 Ti (driver version: 32.0.15.6109)
    GPU2:               NVIDIA GeForce RTX 3080 Ti (driver version: 32.0.15.6109)
    GPU3:               NVIDIA GeForce RTX 3080 Ti (driver version: 32.0.15.6109)
    Monitor:            \\.\DISPLAY1 - XB271HU(DP) [2560x1440 32-bit 96 DPI]
    Monitor:            \\.\DISPLAY2 - XB271HU(DP) [2560x1440 32-bit 96 DPI] - [Current]
    Monitor:            \\.\DISPLAY3 - Dell U2713H(DP) [2560x1440 32-bit 96 DPI]

Text:
    Scale Factor:       1.000000
    Ansi Codepage:      1252

**Comment by bibsp** [comment]
Can't you see separate mouse page in settings? All mouse settings are moved there.
Read 2.3.5 changelogs.
