### ISSUE TITLE
Gray block noise when scrolling.

### ISSUE THREAD

**Issue by maidmaidmaid** [clsid2/mpc-hc#3073]
Hi
Starting with MPC-HC.2.3.4, gray block noise has appeared when scrolling.
The same issue can be reproduced with MPC-HC.2.3.5.

I have now reverted back to MPC-HC.2.3.3 and the problem is no longer reoccurring.
I tried changing the DirectShow video but it did not improve the situation.

Do you know the cause?

The video source is MPEG2.
1440x1080 MPEG2 MP@HL 16:9 625line Interlace 29.97fps 20000.00kb/s CBR
AAC 48.00kHz 2.0ch(2/0 L+R) LC 144.00kb/s

Operating System: Windows 10 Pro 64-bit (10.0, Build 19045)
Processor: AMD Ryzen 7 5700G with Radeon Graphics
DirectX Version: DirectX 12

Please let me know if there is any other information you need.

Best regret,

**Comment by clsid2** [comment]
Need a sample file.

**Comment by clsid2** [comment]
Problems with the internal codecs can be reported here:
https://github.com/Nevcairiel/LAVFilters/issues

Report must include a sample file, because developer need to be able to reproduce a problem in order to be able to fix it.
