### ISSUE TITLE
Reload video shortcut/button?

### ISSUE THREAD

**Issue by OutshineIssue** [clsid2/mpc-hc#3074]
I have a pair of Bluetooth headphones that automatically turn off after 15 minutes of inactivity. When I'm watching something on MPC-HC and pause for a while, the headphones shut off. When I turn them back on, there's no sound in MPC-HC, and I have to close and reopen the video to get the audio back. I was wondering if there's a simpler solution, like a shortcut to reload the video. I did find an option to reload just the subtitles under options > keys but not the video.

**Comment by clsid2** [comment]
Ctrl+E
