### ISSUE TITLE
Playing subtitles on an audio file?

### ISSUE THREAD

**Issue by BMS1011** [clsid2/mpc-hc#3075]
Trying to figure out how or if it's possible to play an audio file (.wav or .mp3) and have MPC-HC display an accompanying subtitle file (.srt or .vtt)
Is there some setting that needs to be changed or plugin that allows this?
Currently the option to select a subtitle to load is greyed out when playing an audio file.

**Comment by clsid2** [comment]
Not possible.

**Comment by vivadavid** [comment]
Hi, @clsid2 ,

You said it's not possible, but if it became feasible in the future, this feature would be very useful. My case scenario is that I apply Whisper on some of my podcasts to obtain the transcriptions as SRT files.

Thanks in advance.
