### ISSUE TITLE
Tonzeitstreckung/Codec Problems

### ISSUE THREAD

**Issue by tassulisko** [clsid2/mpc-hc#3076]
after working for quite some days all of a sudden MPHC didn't want to play anything at all anymore all of a sudden. I was away from the PC and then 30 minutes later I came back and had the issue. And no, my PC was running the whole time, not going into standby or anything.

Allegedly "codec error" - I re-installed the latest K-Lited-Codec Pack which sadly meant it automatically deinstalled MPHC.

However after that I re-installed MPHC and now everything works fine with just one issue and I don't know how  this ... came about all of a sudden. When I want to slow down anything the Tonzeitstreckung is active (I don't have the english word) - means only the speed is slowed down, not the pitch at the same time and that sucks.

and it doesn't make any sense because previously it all worked fine. Am I just too dumb to find the right setting for this? I don't have a clue where I can deactivate it so that it's slowing down normally again as you'd expect it..... =/

**Comment by tassulisko** [comment]
okay seems like I solved the issue manually:

1) the codec error was from the Hard Drive deactivating/having an error

2) to get speed and pitch down you need to set "system standard" in audio settings.

Sorry for the inconvenience

**Comment by clsid2** [comment]
MPC-HC is included with K-Lite so you don't need to install it separately.

For audio pitch correction you need to use SaneAR or MPC Audio Renderer.
