### ISSUE TITLE
ToDo: A-B repeat

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#308]
One hotkey to control this functionality.

First press enables the repeat and sets position for A. B now equals 0, which means jump back to A at end of file.
Second press sets position for B.
Third press resets values and disables the repeat.

Positions could optionally be drawn on timeline similar to chapter marks, but with different color (red).

**Comment by kato80** [comment]
I think 2 hotkeys' way is better than 1 hotkey's way.

First hotkey (e.g. '[') sets position for A only, and then,
Second hotkey (e.g. ']') sets position for B, independently.
Each positions can be reset again and again.

If this way, it is easy to readjust the repeating range.

**Comment by adipose** [comment]
Downside: if you hit B before A, what does B do?  Do you have to hit both A & B to reset things?  If there is only one mark, is it the mark for A or for B?

We could use different colors for the last problem.

**Comment by clsid2** [comment]
In that case, the repeat will enable if either key is pressed (A or B becomes non-zero). If B is pressed first then A is still 0, which means seek back to beginning.
Resetting would then require two key presses, unless one of the values is already/still zero. I don't want a third hotkey for reset, as we already have many hotkey functions (and few keys to map to).

**Comment by clsid2** [comment]
https://github.com/clsid2/mpc-hc/pull/317
