### ISSUE TITLE
Subtitles are pixelated when playing 4K videos

### ISSUE THREAD

**Issue by glitch191** [clsid2/mpc-hc#3082]
When I play 4K videos, subtitles are pixelated.

![image](https://github.com/user-attachments/assets/38264559-495e-4bc8-b5e1-4c5fccf91762)

As for 1080p videos, subtitles are smooth.

![image](https://github.com/user-attachments/assets/825a4d9b-9df9-4eb9-a2e7-d2c4b55a9476)

**Comment by clsid2** [comment]
Which subtitle format?

I suspect it is an image based format (vobsub/PGS), in which case it is normal and can not be fixed.

For text-based subtitles:
Options > Subtitles > Maximum texture resolution

**Comment by adipose** [comment]
Maybe worth looking at a smoother of PGS.  It used to have the wrong size and I think I added a simple scaler.

**Comment by adipose** [comment]
The commit I was thinking of was https://github.com/clsid2/mpc-hc/commit/19f809df2c1aa81481246481e69fc79ba32eb0fd.  This was specifically to allow thumbnails to render PGS subs (which are resized using a bicubic algorithm).

@glitch191, were those thumbnails or just screenshots?
