### ISSUE TITLE
RAM leak-ish issue on continuous playback

### ISSUE THREAD

**Issue by harry2000s** [clsid2/mpc-hc#3086]
I was watching a series drama recently, and it seems the more episodes I play, the more "submitted" RAM it takes.
It occurs multiple times. Eventually the "submitted" is so huge, it would take up all the spaces in C: and crashes other Applications.
![QQ截图20240919232503](https://github.com/user-attachments/assets/620c4ba9-d7b0-45b8-89dc-621c2e1fb144)
![QQ截图20240919233211](https://github.com/user-attachments/assets/48019a4a-c216-4d99-b061-892ba25a2c13)
I have seen this number goes up to 45GiB. The DRAM usage is completely normal.
It seems when I push the next video button, MPC tries to "preload" it in the virtual memory. But the videos I'm watching is only ~700MiB per. And it takes up about 6GiB in "submitted". It doesn't clean itself and just accumulates. MPC itself didn't crash so it confused me for days.
I was on version 2.2.1, upgraded to 2.3.5 and it still behaves the same.

**Comment by clsid2** [comment]
Works fine for me.
You are only one with this problem.
I can not read Chinese.

**Comment by harry2000s** [comment]
> Works fine for me. You are only one with this problem. I can not read Chinese.

That is 25 Gigabytes, 238 Megabytes and 4 Kilobytes "submitted" for playing a FHD24p video.
[
![20240920005512](https://github.com/user-attachments/assets/7ed15514-8a33-4f21-957e-ca03f1e80027)
](url)
Even a 87GiB 70Mbps movie takes only ~5GiB of RAM. Something **IS** up. And it is reproducible.
I believe I described this issue in English. And you decided to turn it down because my perfmon screenshot has some text in Chinese.
Fine. Either you are bad at collecting garbages, or you are bad in reading numbers.

**Comment by clsid2** [comment]
The numbers on YOUR system are meaningless.

I can not reproduce any leaks. Debugger shows no leaks.

It is a problem on YOUR system, likely caused by third party software.
