### ISSUE TITLE
720p video artifacts/jagginess on MPC Renderer compared to MadVR 206b

### ISSUE THREAD

**Issue by USSWashington** [clsid2/mpc-hc#3088]
Frame example 22183 on The Bear S1 Ep1 has some wired lines and artifacts when using the MPC Renderer compared to MadVR 206b build.
Especially around straight lines, e.g. collar and head-band
MPC is on the latest version: 2.3.5.27
![image](https://github.com/user-attachments/assets/c0806ebf-e91a-49e5-a856-03432ec0ae4b)
^MadVR

![image](https://github.com/user-attachments/assets/f87c5acb-6afb-4f13-8d68-408427bef263)
^MPC Renderer

The video is 720p, the display is 768p.
Please note that MadVR is on its default settings (Bilinear)

**Comment by clsid2** [comment]
Disable the DXVA2/D3D11 video processor and then go complain to your graphics driver vendor that their scaler sucks.

**Comment by USSWashington** [comment]
Which video processor would you suggest instead of the DXVA2/D3D11?

**Comment by clsid2** [comment]
Jinc2m shader
