### ISSUE TITLE
Custom playback rate speed filter

### ISSUE THREAD

**Issue by JimmyBad2** [clsid2/mpc-hc#3093]
Is there a filter that I can use to make the playback rate speed to be exactly the one I want?

I know that I can change it in settings but it only allows me to change it incremental steps. Meanwhile, what I'm looking for is setting up a specific playback speed like you can do in browsers with the document.queryselector('video').playbackrate command.

Is it possible?

**Comment by clsid2** [comment]
Menu > Play > playback rate

There are some predefined values there.

No additional values will be added. Nor any other additional functionality.
