### ISSUE TITLE
Problems playing videos that have just one image as the video stream

### ISSUE THREAD

**Issue by lkintact** [clsid2/mpc-hc#3094]
Try opening this file - [out.mp4](https://github.com/user-attachments/assets/cd8335db-8c25-44eb-8dd2-56ea52bab637) - with MPC-HC.

There are two problems:
1. The video picture (which is just one image) is not shown. It only appears after I click on "Stop" and then on "Play".
2.  Video playback isn't repeated (make sure repeating is enabled at "View -> Options -> Playback").

OS: Windows 10 Home,
MPC-HC: 2.3.5.19 (d56906bf5).

**Comment by clsid2** [comment]
You should embed the image as a cover image in the container rather than as a video track.

I consider the file broken. I will not and can not fix it. You can submit issue to LAV Filters, but you will probably get same answer there.

**Comment by lkintact** [comment]
Got it, thanks.
