### ISSUE TITLE
Some subtitles render in the wrong font

### ISSUE THREAD

**Issue by KogucikPL** [clsid2/mpc-hc#3099]
Program version: 2.3.5.27

Default settings, nothing changed.

When playing a video with libass enabled, some subtitles render in the default style:

![kakegurui1incorrect](https://github.com/user-attachments/assets/e25988a0-6d1d-4425-ad0f-6b8f7f5c7eb4)

When libass is disabled, the correct style is rendered:

![kakegurui1correct](https://github.com/user-attachments/assets/9dfbe247-4bf5-4e02-9af6-103305e61cbf)

The problem is that with libass disabled there are massive frame drops at some points, and with libass enabled some fonts are not rendered correctly. Is there any way to make the video playback smooth and fonts render correctly? Currently I have to turn libass on and off regularly to be able to watch it "correctly". I'm not advanced in this stuff, but I can do something. Thank you in advance for your help.

**Comment by clsid2** [comment]
Need link to the video file.

**Comment by KogucikPL** [comment]
I found out what the error is. After many attempts, I am 100% sure that the problem is in the font file. The muxed file in mkv contained several types of the same font, which is probably why MPC could not find one specific font. When I replaced the font with a "stand-alone" one, it rendered correctly. Anyway, here's the link to the video:

https://cdn.discordapp.com/attachments/1056817159881371768/1291000054018084917/Kakegurui_-_S01E01_-_The_Woman_Called_Yumeko_Jabami.mkv?ex=66fe80fe&is=66fd2f7e&hm=d5bae7b7f9235dc0f9b81903638285708ce643b25c515ffbb2d5d358de5159e6&

**Comment by clsid2** [comment]
If it works without libass enabled, then it isn't a problem in the player itself.

Libass has its own font selection code. You can report issues here:
https://github.com/libass/libass/issues

Here it renders correctly, but you seem to be using a different sub, as the translation differs.
