### ISSUE TITLE
Showing the subtitle is delayed by 1 second

### ISSUE THREAD

**Issue by dmak** [clsid2/mpc-hc#31]
I have created [this special video](https://www.dropbox.com/s/6xib95vod2cawxq/demo_shrink_2018-09-24.mkv?dl=0) in the following way:
* Video track lasting for 10 seconds is muxed as is, without any stretch (see below) applied.
* Two audio tracks originally lasting for 20 seconds are muxed with stretch 1/2 applied, hence should be played two times quicker and as a result, match the video.
* One subtitle track, originally designed for 20 seconds is muxed with stretch 1/2 applied, hence should also be in sync with the video.

First original SRT subtitle entry:
```
1
00:00:00,001 --> 00:00:02,000
1...
```

Actual behaviour:
* When MPC starts playing the file, all subtitles are approximately 1 second delayed.

Expected:
* The subtitle ''1...'' is displayed in the period [0..1] seconds of playback, the subtitle ''2...'' is displayed in the period [1..2] seconds, and so on.

Extra information:
* I have checked that [MX Player v1.9.16 for Android](https://play.google.com/store/apps/details?id=com.mxtech.videoplayer.ad) is playing this file as I expect.
* "Stretch by" ratio can be set [ on this dialog of MKVToolNix GUI](https://windows-cdn.softpedia.com/screenshots/mkvtoolnix_1.png) and is equivalent to **--sync TID:delay,a/b** option of [ mkvmerge](https://linux.die.net/man/1/mkvmerge)
* Problem exists on Windows 7 x64, Media Player Classic v1.7.13.112, LAV Splitter v0.70.2.80.
* Problem exists on Windows 7 x64, [Media Player Classic v1.8.2](https://github.com/clsid2/mpc-hc/releases/tag/1.8.2), LAV Splitter v0.70.0.13.

P.S. I've tried to post the issue to the [official bug tracker](https://trac.mpc-hc.org/newticket) but I was blocked by the Cloudflare guard with the message `Sorry, you have been blocked. You are unable to access mpc-hc.org`, so I posted it here.

**Comment by clsid2** [comment]
This isn't a bug. The subtitle timestamps are just slightly wrong.

Extracted sub is like this:
```
1
00:00:00,001 --> 00:00:01,001
1...

2
00:00:01,001 --> 00:00:02,001
2...
```

The video is just 1 fps. So first frame has timestamp 0.000, second 1.000, etcetera. Subtitles start one milisecond later, which in this case means a frame later (1 second). You can fix it by letting the subs start at exactly 0.000. The weird end times might be due to a rounding error in MkvToolNix.

**Comment by dmak** [comment]
Thanks for reply. Correcting the start ms in SRT to `.000` had solved the problem. However I wonder would it be more logical to round the time of the subtitle frame (and not cell it)?

Also excuses for offtopic, I would be also interested about how to generate 25 FPS video from images using `ffmpeg`? Perhaps you can give  a hint. I've tried `ffmpeg -framerate 1 -i image_%d.png -r 25 -vcodec libx264 demo.mkv` but that produces 1 FPS video.

**Comment by clsid2** [comment]
For rounding issue you need to go to MkvToolNix.

Try `-framerate 25` instead of `-framerate 1 -r 25`

**Comment by dmak** [comment]
I have created mkvmerge [issue #2394](https://gitlab.com/mbunkus/mkvtoolnix/issues/2394).

Also thanks for the hint with `ffmeg`. Now video is 25 fps:
```
Input #0, image2, from 'image_%d.png':
  Duration: 00:00:00.40, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: png, rgb48be(pc), 400x400, 25 fps, 25 tbr, 25 tbn, 25 tbc
```
but the 10 input images are now played with 25 fps, thus all video is played in 10/25 seconds, while I need 10 seconds video. In other words, there is no image "duplication" (see [this post](https://askubuntu.com/a/1012470/164142)).
