### ISSUE TITLE
audio cover art keeps auto setting to 16 9 widescreen

### ISSUE THREAD

**Issue by kamikazilucas** [clsid2/mpc-hc#3100]
whenever i listen to music it has black bars on the left and right cause it keeps setting to 16 9 when the cover art is square, how do i make it so it automatically goes to what the size of the cover art is

**Comment by clsid2** [comment]
Works fine for me.

You might have enabled option to remember window size.

**Comment by kamikazilucas** [comment]
no i havent, when i do thats when it works somewhat but dosent change along with the image

**Comment by kamikazilucas** [comment]
![image](https://github.com/user-attachments/assets/997e7919-5506-4c1d-bb6f-13895bd49d78)
everytime i open it looks like this
