### ISSUE TITLE
How to Save Settings when Downloading New Version?

### ISSUE THREAD

**Issue by gitman-user** [clsid2/mpc-hc#3101]
Hi,

I just wanted to know how I can save my configuration settings every time I download a new version since my previous settings got wiped. 

Thanks.

**Comment by clsid2** [comment]
You can install new version on top of existing one. You do not need to uninstall.

**Comment by gitman-user** [comment]
> You can install new version on top of existing one. You do not need to uninstall.

I never uninstalled it though, I installed the new version and settings were automatically lost.

**Comment by clsid2** [comment]
options > miscellaneous > export

**Comment by ghost** [comment]
So how do I import my settings back? There is only an export button there, no import button.

![Image](https://github.com/user-attachments/assets/b3efac2a-85a2-4f35-9069-695669bb3460)

**Comment by clsid2** [comment]
Double-click on the .reg files.
