### ISSUE TITLE
MPC not using GPU video Decode

### ISSUE THREAD

**Issue by the-marox** [clsid2/mpc-hc#3107]
Hi, I have just upgraded to the latest version of MPC but I noticed all videos start stuttering.
![screen](https://github.com/user-attachments/assets/08eee819-b6f2-428b-9a9e-051209da0e41)
in the screenshot I have attached you can see there is no GPU VIdeo Decode activity even if on lav filters I have checked the RTX3060 and the number of dropped frames is high
GPU power consumption is below 40W 

Do you have the same issues?

**Comment by clsid2** [comment]
menu > play > filters > lav video decoder

**Comment by the-marox** [comment]
I tried with every setting but hardware acceleration doesn't start 
![image](https://github.com/user-attachments/assets/a8933f5b-067d-4bd7-ac56-f2bc1673fe8b)

**Comment by the-marox** [comment]
> I tried with every setting but hardware acceleration doesn't start ![image](https://private-user-images.githubusercontent.com/62152152/373950456-a8933f5b-067d-4bd7-ac56-f2bc1673fe8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjI1NDgsIm5iZiI6MTcyODIyMjI0OCwicGF0aCI6Ii82MjE1MjE1Mi8zNzM5NTA0NTYtYTg5MzNmNWItMDY3ZC00YmQ3LWFjNTYtZjJiYzE2NzNmZThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDEzNDQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNWY5MTUyODA1MjFiZjQzYTg0OGI3ODVlY2RhODk4MGJjOTk4NmFmNjM1ZGNiOWY4YzE0NDk2NWZlNGE3MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6hX4rwb7jOz9kL1ebTEvmMvF__sUf-ewy95vAtILWJI)

It depends on he type of the file. The one I showed in the screenshot is not accelerated, other ones yes

**Comment by the-marox** [comment]
It is related with x265 files really strange behaviour

**Comment by clsid2** [comment]
MediaInfo can show you file details.

It is likely an unsupported variant of HEVC.

**Comment by the-marox** [comment]
![image](https://github.com/user-attachments/assets/99b25b94-55f9-4cd8-a6ca-4293ecf9544b)
this are details

**Comment by the-marox** [comment]
![image](https://github.com/user-attachments/assets/d0b809b5-4a2b-4041-910f-8c0cb13ed3a3)

**Comment by clsid2** [comment]
Make a short test recording of a few seconds.
Upload the file to https://www.sendspace.com or Dropbox or Google drive.
Open new issue here:
https://github.com/Nevcairiel/LAVFilters/issues

**Comment by the-marox** [comment]
> Make a short test recording of a few seconds. Upload the file to https://www.sendspace.com or Dropbox or Google drive. Open new issue here: https://github.com/Nevcairiel/LAVFilters/issues

done thank you
https://github.com/Nevcairiel/LAVFilters/issues/617

**Comment by the-marox** [comment]
Solved was a BIOS-related problem from Lenovo. I rollback to a previous version
