### ISSUE TITLE
No sound at starting for 1 second. Windows 11 24h2

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#3109]
This problem only occurs with headphones.
If I play with laptop speaker everything is fine.
Changing audio renderer doesn't help.

This laptop was on windows 10. After clean installation of windows 11 24h2, this is happening. So I can't confirm whether it is 24h2 related or any version of windows 11 related on this specific laptop.

After spending hours I found that, if windows sound settings page is kept open in background then audio comes immediately.
![Screenshot (3)](https://github.com/user-attachments/assets/36d38534-5d2a-42c9-9ccb-dd4a679e9d73)

No issue if this page is opened. This is very weird. And most importantly web browsers have no issue. Problem is only with mpchc/be.

**Comment by clsid2** [comment]
Not fault of player. I can not help you.

**Comment by clsid2** [comment]
Windows bug:
https://answers.microsoft.com/en-us/windows/forum/all/delay-in-windows-11-24h2-volume-slider/9a0cc736-3e33-4792-8241-5d1cf9721be6
https://answers.microsoft.com/en-us/windows/forum/all/windows-11-causing-audio-delay-on-applications/26413f41-bf3d-4d31-9322-f53dfe78c07e
https://answers.microsoft.com/en-us/windows/forum/all/windows-11-24h2-usb-audio-issues-timing-out/a8d540c9-7b5e-4dd7-85bb-d0d789855ea4
