### ISSUE TITLE
Possible to download all videos in a playlist?

### ISSUE THREAD

**Issue by mckealty** [clsid2/mpc-hc#3111]
I could have sworn I was able to do this in the past, I have a directory with like 200 documentaries that I wouldn't have done one by one.  

Is it possible?

**Comment by clsid2** [comment]
You can easily do that with yt-dlp if you spend 5 minutes reading its documentation.

**Comment by mckealty** [comment]
I posted here at the mpc-hc git repo because I was wondering if it could be done in mpc-hc.

**Comment by clsid2** [comment]
This is a player, not a fucking front-end for all yt-dlp functionality. There are plenty of GUIs for it if you are too lazy/stupid to read documentation or use command-line.
