### ISSUE TITLE
Subtitles are not shown at correct time after skipping forward to then next video in full screen mode (2.3.6)

### ISSUE THREAD

**Issue by theNorNi** [clsid2/mpc-hc#3112]
Happens with release 2.3.6

Displaying subtitles goes wrong after skipping forward to the next video in full screen mode.
It works fine in windowed mode, but skipping forward in full screen mode breaks it.
Switching back to windowed mode and skipping backward/forward will not fix the problem.
Changing the playback position will cause to "display" the first few subtitle entries from the beginning every time.

**Comment by clsid2** [comment]
Options > Player > User Interface > uncheck "Show OSD"

Does that fix the issue?
Problem with stuck OSD has already been fixed for next release.

**Comment by theNorNi** [comment]
OK. It works this way.
Thanks.
