### ISSUE TITLE
Video playback suffering seemingly out of nowhere

### ISSUE THREAD

**Issue by IokKujan** [clsid2/mpc-hc#3113]
On two .mkv videos I've watched at around the 15-16 minute mark the video framerates drop dramatically to become very choppy. The audio is fine, and once I closed and reopened the video the framerate was back to normal. If before closing I rewind to a previous point in the video the framerate stays choppy.

**Comment by clsid2** [comment]
I need a link to that file.

**Comment by IokKujan** [comment]
It was this current release, 2.3.6 of MPC-HC. Apologies if that isn't what you meant.

**Comment by clsid2** [comment]
I need a link to download the .mkv video

**Comment by IokKujan** [comment]
https://mega.nz/file/Fos2HR4b#ValOVawaWXzgxTQNlV_8PcHrwgf9XZQ-YyDWoIsP1-0 

Sorry, here you go.

**Comment by clsid2** [comment]
Plays fine here. I can not help you.
