### ISSUE TITLE
OSD error: The information now remains until the timeline is selected with the mouse

### ISSUE THREAD

**Issue by Mae72DE** [clsid2/mpc-hc#3114]
MPC-HC (64-bit)
---------------

Build information:
    Version:            2.3.6 (98f0f2ec2)
    Build date:         Oct  5 2024

LAV Filters:
    LAV Splitter:       0.79.2.20
    LAV Video:          0.79.2.20
    LAV Audio:          0.79.2.20
    FFmpeg compiler:    MinGW-w64 GCC 13.3.0

Operating system:
    Name:               Windows 11 (Build 23H2)
    Version:            10.0.22631 (64-bit)

Hardware:
    CPU:                AMD Ryzen 3 3200G with Radeon Vega Graphics
    GPU1:               AMD Radeon(TM) Vega 8 Graphics (driver version: 31.0.12027.9001)
    GPU2:               AMD Radeon(TM) Vega 8 Graphics (driver version: 31.0.12027.9001)
    Monitor:            \\.\DISPLAY1 - Generic PnP Monitor [2560x1440 32-bit 96 DPI] - [Working]
    Monitor:            \\.\DISPLAY2 - Generic PnP Monitor [1920x1080 32-bit 96 DPI] - [MPC out]

Text:
    Scale Factor:       1.000000
    Ansi Codepage:      1252

OSD error: The information now remains until the timeline is selected with the mouse
---
Where can I find the OSD timeout and what should be displayed?

I don't like the "pause" information - because I can both hear and see that the video is paused.

Instead, I want to see the file name in the OSD. But I haven't found any OSD settings in the options where I can set the timeout and what information should be displayed:

My OSD table:

Time change: "$Time" (5 sec.), file name (5 sec.).

Pause: "Pause" (2 sec.), file name (no timeout).
Playback: "Playing" (2 sec), filename (2 sec)

Mouse movement: filename (5 sec), time (5 sec)

And I think a "Show Info" command would be useful: Shows various OSD information:

Info:
TimeOut: -1 (Show OSD while button is held down)

TimeOut: 0 (currently no information available)

TimeOut > 0 - Shows the information x seconds after button is released.

And a Custom-Format will be fine:

1st line: filename (scroll if too long: oscillate|continuous)

2nd line: remaining playing time, total playing time.

3rd line: Playback status/speed factor

4th line: Video streams (format info)

5th line: Audio streams (number; language, short codec, channels)

6th line: Subtitle streams (number; language, type)

**Comment by clsid2** [comment]
Stuck OSD has already been fixed for next release.

You can disable OSD in the options.
