### ISSUE TITLE
MP4 file with IPCM audio track cannot be rendered

### ISSUE THREAD

**Issue by UberJaeger** [clsid2/mpc-hc#3115]
I came across a file that cannot be rendered by MPC-HC latest version:

    Version:            2.3.6 (98f0f2ec2)
    Build date:         Oct  5 2024

This is the file (music video): https://drive.google.com/file/d/1DScmWB3K-zCc82pM4UlsLgqEK3v7IsC9/view

Video/Audio Information:
![image](https://github.com/user-attachments/assets/f523d6c8-a72b-4226-befa-151bcbbe9955)
![image](https://github.com/user-attachments/assets/55664718-cbe3-4e33-b095-4fc7165af733)

**Comment by clsid2** [comment]
Report at LAV Filters issue tracker:
https://github.com/Nevcairiel/LAVFilters/issues
