### ISSUE TITLE
(2.3.6) Issue with embedded subtitles in mkv files

### ISSUE THREAD

**Issue by mischiamnesiac** [clsid2/mpc-hc#3116]
Afer upgrading to version 2.3.6, embedded subtitles in mkv files are played backwards in time. The last subtitle line of the file is displayed first (at the beginning), then the second to last and so on. The issue disappeared after downgrading to version 2.3.5.

**Comment by clsid2** [comment]
try 2.3.6.11

**Comment by mischiamnesiac** [comment]
That fixed it. Thanks for the quick reply.

**Comment by mischiamnesiac** [comment]
Version 2.3.6.11 only works for the first video that is played back in a session. Switching to another file still shows the above mentioned issue. The only workaround is to close and reopen the program.

**Comment by clsid2** [comment]
Does disabling the OSD fix your problem?

**Comment by mischiamnesiac** [comment]
Yes, it does, but why is that?

**Comment by clsid2** [comment]
Try 2.3.6.21

**Comment by mischiamnesiac** [comment]
As far as I can tell it works now with the OSD enabled. Thanks again for the quick fix!
