### ISSUE TITLE
mpc-hc playing 2 aduio track at the same time.

### ISSUE THREAD

**Issue by mightyhuhn** [clsid2/mpc-hc#3119]
mpc-hc is set to default disable the audio switcher 2.3.6.11 is used. this issue happens with older versions too.

how to reproduce.
have an video file named bug.mkv and bug.acc in the same folder. it will play the audio from bug.mkv and from bug.acc at the same time not making it just an option to load external audio.

in case the codec matters it was acc h265 and just acc.

don't be me don't press enter after writing the title.

**Comment by clsid2** [comment]
uhmm...
options > playback > auto-load audio files

**Comment by mightyhuhn** [comment]
i know that. the issue is that they are played not that they are loaded.

there was a reason i disabled the audio switcher which allows them to load too but only plays one track.

**Comment by clsid2** [comment]
Then don't disable the audio switcher.
