### ISSUE TITLE
Integrate features from JanWillem32

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#312]
I got a request on doom9 to look at this fork:

https://forum.doom9.org/showthread.php?t=161047&highlight=janwillem&page=86

Perhaps the MPC VR could integrate features from this fork?  I don't know much about it at the moment.

**Comment by clsid2** [comment]
He did a rewrite of the internal video renderers (EVR-CP). MPC VR is a totally new external renderer (see: https://github.com/Aleksoid1978/VideoRenderer).
I don't see how his work is useful as there is no clean path from the original code to his new code. I don't even know what it may improve and what it may break. It the requesting user has an actual issue, then he should make a bug report.

**Comment by adipose** [comment]
Thanks for the info, I will close this issue then.

**Comment by adipose** [comment]
@clsid2 

FYI the feature the user was asking for was:

"I'm most interested in the added resizers"

Not sure what all the resizers were, but maybe they could be added as features for the MPCVR.
