### ISSUE TITLE
2.3.6 problem with OSD

### ISSUE THREAD

**Issue by krial** [clsid2/mpc-hc#3120]
2.3.6 There is a problem with OSD.
In full screen mode OSDTransparency does not work.
Windowed mode correct.

Sometimes OSD in windowed mode does not disappear. Remains on the screen.
Rolling back to 2.3.5 solves the problem.

**Comment by clsid2** [comment]
OSD being stuck is fixed in 2.3.6.21

The lack of transparancy is an intentional compromise to enhance HDR compatibility. That will not be fixed.
