### ISSUE TITLE
V2.3.6 seems to introduce a regression, causing a crash while playing a file.

### ISSUE THREAD

**Issue by mega-optimus** [clsid2/mpc-hc#3124]
Operating System: Win7
GPU: Intel [Ivy Bridge] HD Graphics

Download this video to local disk as MP4, then v2.3.6 crashes (even after disabling hardware acceleration) within first 6 minutes, while 2.3.5 doesn't. 

https://www.heimaotv.vip/vodplay-323286-1-1.html

**Comment by clsid2** [comment]
I can not read that Chinese crap.

I do not care. Leave me alone. Fix it yourself.
