### ISSUE TITLE
Thumbnails have wrong aspect ratio

### ISSUE THREAD

**Issue by bottleblue** [clsid2/mpc-hc#3127]
When using 'Save Thumbnails' the image has the wrong aspect ratio. The result changes depending on what aspect ratio the video was on when generating the thumbnails but they're all incorrect.

The video I tested is 1920 x 816 (2:35:1). When I set the aspect ratio to DAR, SAR, or 235:100 the video looks right but the thumbnails don't. If I set it to 5:4 the thumbnails almost look correct but still off. The other AR settings look very squished.

Any idea why? Using version 2.3.6.21 and Win10 22H2

**Comment by clsid2** [comment]
Works fine here. I do not know what is wrong.
Nobody else has complained about this, so I am not spending any time on it.

**Comment by bottleblue** [comment]
Fair enough. Just thought I'd mention it. If anyone else has a similar problem maybe they can chime in.

**Comment by adipose** [comment]
> When using 'Save Thumbnails' the image has the wrong aspect ratio. The result changes depending on what aspect ratio the video was on when generating the thumbnails but they're all incorrect.
> 
> The video I tested is 1920 x 816 (2:35:1). When I set the aspect ratio to DAR, SAR, or 235:100 the video looks right but the thumbnails don't. If I set it to 5:4 the thumbnails almost look correct but still off. The other AR settings look very squished.
> 
> Any idea why? Using version 2.3.6.21 and Win10 22H2

Upload your video and I will see what causes it.

**Comment by bottleblue** [comment]
Where's a good site to upload it? It's a 30GB movie I'll have to cut like a 1 min. file or something

**Comment by adipose** [comment]
mega.nz or if you can cut it, just about anywhere.

**Comment by clsid2** [comment]
You can cut with MkvToolNix

**Comment by bottleblue** [comment]
After going back and testing again I think I figured out the problem, or at least what fixes it. I tested this with the MPC folder I've been using for a long time and a new extracted MPC folder with default settings and it happens on both. 

MPC's Video Frame is set to Touch Window From Inside by default. On this setting the thumbnails will change based on the window/fullscreen size and aspect ratio MPC is in. 

Here are some screenshots. MPC's aspect ratio is set to DAR for all:

This is how the picture looks when playing fullscreen and set to Touch Window From Inside. It looks correct.
![MI fullscreen, Touch Window From Inside image](https://github.com/user-attachments/assets/60c119af-ad9c-40d8-89f9-a9bf7ede503c)

This is how the thumbnails look when created in fullscreen, Touch Window From Inside. It's incorrect.
![MI Fullscreen, Touch Window From Inside](https://github.com/user-attachments/assets/91ef9bda-02f5-44fb-8c91-dbbcfcdfb0da)

Windowed size and set to Touch Window From Inside. 
![MI windowed, Touch Window From Inside 1, size of player when saving thumbnails](https://github.com/user-attachments/assets/c69296cf-fb5c-46ca-a508-5a05d7df852c)

How the thumbnails look
![MI windowed, Touch Window From Inside 1](https://github.com/user-attachments/assets/fee693f0-1a9f-41ed-8633-af00f07432d6)


Different window size, Touch Window From Inside
![MI windowed, Touch Window From Inside 2, size of player when saving thumbnails](https://github.com/user-attachments/assets/4f3a2c72-2d36-42af-a21d-3c82950f0f59)

Different thumbnail result
![MI windowed, Touch Window From Inside 2](https://github.com/user-attachments/assets/7bfe44a4-44a3-4473-b529-07bc71acb710)

Windowed, Touch Window From Inside
![Assassins 1995 mkv_thumbs](https://github.com/user-attachments/assets/fb1ad88a-7ba5-4abf-a86f-22bf99150b12)

Now when this movie is fullscreen, Touch Window From Inside, the thumbnails have the correct AR
![Assassins fullscreen, touch window from inside](https://github.com/user-attachments/assets/36e882e6-e497-4ca9-8310-3b2aea199862)

I noticed when this movie is fullscreen there were no black bars. I wondered if that had something to do with it so I changed the Video Frame setting to Stretch to Window and that fixed it. All the thumbnails came out correctly, no matter the aspect ratio MPC was in or if it was fullscreen or windowed.

Fullscreen, Stretched to Window, how it looks when playing
![MI Fullscreen, Stretched To Window image](https://github.com/user-attachments/assets/d0720326-e98a-4049-b2e3-75df2129100b)

Fullscreen, Stretched to Window, saved thumbnails
![MI Fullscreen, Stretched To Window](https://github.com/user-attachments/assets/6430982a-d90c-40d9-b769-fcc16bb01779)

Windowed size, Stretch to Window
![MI windowed, Stretch to windows 1, size of player when saving thumbnails](https://github.com/user-attachments/assets/c44dd383-d9ed-490a-a293-b0e7b50ba8c1)

Windowed size, Stretch to Window thumbnails
![MI windowed, Stretch to windows 1](https://github.com/user-attachments/assets/9a109f00-6f73-4663-a88d-37b0b4b90ecd)

I tested this with a dozen other movies and the thumbnails all came out right when set to Stretch to Window. So if Save Thumbnails could be preset using the Stretch to Window setting that could fix the problem?

I've uploaded some short files of these movies so others can test it. I hope it's not just me with this problem.

https://www.mediafire.com/file/dq0thhp21g518t1/mi-00.06.54.331-00.07.25.695.7z/file

https://www.mediafire.com/file/x8q210rydikruc7/A1995-00.21.22.281-00.21.42.301.7z/file

**Comment by clsid2** [comment]
Thumbs should ideally follow video DAR and ignore window size and AR overrides completely.

**Comment by bottleblue** [comment]
Were you able to recreate this problem?

**Comment by adipose** [comment]
I didn't test yet. But it sounds like a possible bug.

**Comment by clsid2** [comment]
No, not with the standard renderers.

I can reproduce it with Madvr. But that is as expected because that has its own settings for screenshots. Adjust that to use 100% scale and your problem is fixed.

**Comment by bottleblue** [comment]
Ah yes that was it. Screenshots are all normal now. Wonder why the madvr setting wasn't on 100% by default. But problem solved thank you very much!
