### ISSUE TITLE
How to enable portable mode and save the settings to a .ini file?

### ISSUE THREAD

**Issue by cvlot** [clsid2/mpc-hc#3128]
I searched around but couldn't find it. I remember that the old version settings seemed to be able to be saved to .ini files.

**Comment by clsid2** [comment]
The option is in the same place it has always been in the past 20 years.

Did you install it, or did you create file associations? Because then it is by definition no longer portable, and storing settings in INI is completely pointless and inefficient.

**Comment by cvlot** [comment]
Sorry, found it
