### ISSUE TITLE
Open device... Broken?

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#3130]
Status bar message: Can't create video capture filter

**Comment by Nekroz88** [comment]
You need to config a few things first, for this to work.
This is a known issue that someone else post in other forums.

Refer to this: https://codecs.forumotion.net/t2383-capture-error

The only way, _for dev_, to fix this, is by changing default settings in the installation, I think.
But there would be a lot of devices so that would be a hassle, so better write this somewhere and let user config/fix this by their own.

**Comment by bibsp** [comment]
All these posts are form 2016. But I remember very well MPC-HC worked fine in recent times. This bug is recently introduced. I've not checked all the previous versions one by one. So can't say in which version it got broken.

It should work without any config just like before.

**Comment by clsid2** [comment]
Nothing has changed in that part of the code.

So test older version first.

And you do need to configure Capture page in settings.

**Comment by adipose** [comment]
> All these posts are form 2016. But I remember very well MPC-HC worked fine in recent times. This bug is recently introduced. I've not checked all the previous versions one by one. So can't say in which version it got broken.
> 
> 
> 
> It should work without any config just like before.

What device type do you have?

**Comment by bibsp** [comment]
Laptop webcam.

And I found the issue after trying several builds. Actually the problem was always there in mpchc.
Reset settings/fresh installation of mpchc has this problem. But once you just open `Options>Capture` and close the page, then the function works correctly. Watch this small video if you don't understand my words.
https://drive.google.com/file/d/1qRoDm01a-sQ4uqMJ_uCXlIzAwxr8JnCK/view?usp=sharing

Because this is newly installed win11 as well as mpchc. On this new system first time I accessed the `Open device...` and got this error. So I thought this bug is new.

And mpcbe works correctly without this workaround.

**Comment by adipose** [comment]
What is probably happening is that, if you have not previously saved the settings, mpchc does not have a device selected.

Furthermore, if your device changes or windows id changes, it needs to reselect.

I can look at this and have it choose the default before opening device. Possibly it can retry or popup the settings if an error occurs.

**Comment by bibsp** [comment]
But with default installation, capture page shows the device is selected. If you see the recording, I have not selected that manually. I only opened capture page and closed it.

So basically the player wrongly shows the device is selected, but actually it is not selected until I open the setting.

**Comment by adipose** [comment]
I see the issue. But you are possibly incorrectly interpreting the settings page. It is showing the options available and defaulting to the first one.

The confusion is the player doesn't allow the user to select "nothing" but without going through that page, cannot decide what the default is.

Probably the correct approach is simply to disable the device until it has been set up by the user the first time. UI-wise, it ideally would show no selection in the settings page to reflect current state.

**Comment by NBruderman** [comment]
> I see the issue. But you are possibly incorrectly interpreting the settings page. It is showing the options available and defaulting to the first one.
> 
> The confusion is the player doesn't allow the user to select "nothing" but without going through that page, cannot decide what the default is.
> 
> Probably the correct approach is simply to disable the device until it has been set up by the user the first time. UI-wise, it ideally would show no selection in the settings page to reflect current state.

Is this difficult to implement?

**Comment by clsid2** [comment]
Stop with these kind of comments. They are very annoying. I don't need your help managing things. I don't like to get pushed to do things. Next time it will result in a ban since this isn't the first time I get annoyed. We spend our time when we want to and on things we find most important.

It now opens settings if device is not configured yet.
