### ISSUE TITLE
(Dark Mode) Progress Bar Enquiry

### ISSUE THREAD

**Issue by Just3dnane** [clsid2/mpc-hc#3133]
Is there any way I can change the Progress Bar in the Dark Mode and turn it like the Light Mode one?

I simply don't like the Modern Seekbar

**Comment by clsid2** [comment]
No.

**Comment by adipose** [comment]
> Is there any way I can change the Progress Bar in the Dark Mode and turn it like the Light Mode one?
> 
> I simply don't like the Modern Seekbar

In modern theme you get modern seekbar.  Only in classic mode do you get the old one.  Classic mode uses default win32 controls that date to windows 95 and happens to be light colored, but that is not the "Light Mode."

Modern theme:
1. Light with modern seekbar
2. Dark with modern seekbar
Classic mode
1. Light (and ugly)
