### ISSUE TITLE
On Screen Displays in top left corner of player not updating

### ISSUE THREAD

**Issue by xXGhosToastXx** [clsid2/mpc-hc#3134]
Ever since the update to version 2.3.6 all the On Screen Displays, like volume, timestamp when skipping and new file title, keep staying in the top left corner indefinitely. It is always the last change made that stays there, the time stamp also does not progress along with the video.

They disappear when hovering the mouse over the bottom of the player as soon as the seekbar appears though, so I at least have found a work around

**Comment by clsid2** [comment]
Use 2.3.6.21
