### ISSUE TITLE
Content will skip to end and not play when resuming from standby

### ISSUE THREAD

**Issue by hojnikb** [clsid2/mpc-hc#3135]
So i have this recurring issue when playing content from my SMB share. I keep a few files open, but when i put the PC into standby and resume it, it won't play anymore and just go to the end.

Is this a known issue or is this by design? The same thing happens when i pull network for a second and bring it back.

**Comment by clsid2** [comment]
Disconnecting network likely invalidates the file handle, causing further access to fail. There is nothing I can do about that.

You can press Ctrl+E to reload the file.

To reload automatically after sleep:
Options > Advanced > ReloadAfterLongPause
