### ISSUE TITLE
Thumbnail issue

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#3140]
![video_20220826_165818 mp4_thumbs](https://github.com/user-attachments/assets/5ffdc936-5206-4ff8-9d19-dfb79a1a8aab)
`MPC-HC (64-bit)
---------------

Build information:
    Version:            2.3.6.21 (4cfbe6c9f)
    Build date:         Oct 13 2024

LAV Filters:
    LAV Splitter:       0.79.2.20
    LAV Video:          0.79.2.20
    LAV Audio:          0.79.2.20
    FFmpeg compiler:    MinGW-w64 GCC 13.3.0

Operating system:
    Name:               Windows 11
    Version:            10.0.26100 (64-bit)

Hardware:
    CPU:                AMD Ryzen 5 5600H with Radeon Graphics
    GPU:                NVIDIA GeForce RTX 3050 Laptop GPU (driver version: 32.0.15.6603)
    Monitor:            \\.\DISPLAY1 - Generic PnP Monitor [1920x1080 32-bit 120 DPI] - [Current]

Text:
    Scale Factor:       1.000000
    Ansi Codepage:      1252
`

I myself can not reproduce this on different system. Any idea?

**Comment by clsid2** [comment]
Try 2.3.6.36

**Comment by bibsp** [comment]
> Try 2.3.6.36

Fixed.

**Comment by bibsp** [comment]
Sorry. Only dark theme is fixed.

Light theme has still the exact same issue.

**Comment by clsid2** [comment]
I can not reproduce.

Those white backgrounds are drawn using the subtitle renderer. Same as timestamps. Maybe you have unusual subtitle settings.

**Comment by bibsp** [comment]
![Screenshot (12)](https://github.com/user-attachments/assets/846f99a9-7c55-4007-8093-d9fbb46b5288)
![Screenshot (13)](https://github.com/user-attachments/assets/8f1d1afc-d0b4-44f4-9a2d-5362274f659b)
Sub renderer is internal default. This video has no sub. All kinds of videos are affected **in this particular system.**

With the same settings everything is fine on different system. The only different thing is that has 768p 60Hz display and this one is 1080p 144Hz.

**Comment by clsid2** [comment]
It generates a subtitle to create the backgrounds and write the timestamps on the screenshot, plus the text at the top.

The subtitles of the file itself are irrelevant.

**Comment by bibsp** [comment]
Can you reproduce this in your system?
In past there were no issues I remember very well.
If you think, any recent time changes might cause this issue, then tell me. I will try older versions and reset settings.

Otherwise I'm not doing. After resetting, configure all the settings is a big headache. Because export settings and restore settings did not work last time i tried.

**Comment by clsid2** [comment]
No, it works fine here even with your exact subtitle settings.

You can backup settings by making an export of this registry key:
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC

**Comment by bibsp** [comment]
Version 2.3.4 was fine.

After that it is broken. I've not tested in between development builds. So can't tell you the exact build.

**Comment by clsid2** [comment]
It is caused by the override styles option.
Will fix it later.
