### ISSUE TITLE
OSD: Show current playback rate/speed?

### ISSUE THREAD

**Issue by Gittyperson** [clsid2/mpc-hc#3141]
Hello and thanks for your brilliant work.

Tried to find a way to display the current (altered) rate on screen, but failed. Sorry if I missed it. The only way to display it, seems to be to just change it and the info will show up for a few seconds.

If not possible, may I suggest to include it in the "OSD: Display Current Time"/CTRL + I info? No need to show anything if rate is 1.00, but if it's changed, the current rate could be displayed next to the time.

I know the Play menu can be of use, but it's not convenient and does not include custom Speed steps.

Thanks

**Comment by clsid2** [comment]
There is option to show it in status bar.

THERE WILL BE NO NEW OPTIONS
