### ISSUE TITLE
timeout when closing preview filter graph with latest AMD drivers

### ISSUE THREAD

**Issue by Nemo1985** [clsid2/mpc-hc#3143]
Hello, I'm experiecing this issue when I start any video with the 24.9.1 and 24.10.1.
While MPC-HC (v2.3.6) works fine with version 24.8.1 and older.
Some specs information:
Cpu: Ryzen 5700x
SO: Windows 10 ltsc 64 bit fully updated
Mpc-hc: 2.3.6

**Comment by clsid2** [comment]
You need to report it to AMD.
https://www.amd.com/en/resources/support-articles/faqs/AMDBRT.html
