### ISSUE TITLE
RTX HDR - Washed out colors

### ISSUE THREAD

**Issue by kelayz** [clsid2/mpc-hc#3147]
Hello,

I am using MPC-HC with the MPC video renderer, I decided to go down this rabbit hole to watch some movies with RTX HDR since they updated to allow to set the points properly for your monitor.

After getting it to work using your build, the colors are washed out. It's like a grey filter over the video. I use RTX HDR for gaming, and youtube content and have the proper points set in it for my monitor config, it looks amazing when working properly.

I have scoured through multiple threads, forums, etc, Trying a number of different options under LAV, and the video renderer itself with no luck. Even restarting windows, reinstalling fresh, disabling rtx hdr re-enabling ETC. It is just very washed out and the peak brightness (mine is 1000) is basically non existent. 

![image](https://github.com/user-attachments/assets/84a36374-4291-420f-a54b-d0443a11de31)
![image](https://github.com/user-attachments/assets/cfab9c47-201e-4296-a665-501336f29ced)

Any help would be appreciated.

**Comment by kelayz** [comment]
After another PC restart - it is now no longer working.. i am really unsure of what is happening.
![image](https://github.com/user-attachments/assets/b1f4ac22-b248-4271-943d-83e28c0abca6)

**Comment by clsid2** [comment]
You need to enable the global settings in the NVIDIA settings app, not use application filters.

**Comment by kelayz** [comment]
Not at my pc right now, but it is enabled under global settings, that's how I use it for my browser and my games. 

The only way I was even able to get rtx hdr to do something was manually adding mpc-hc as a program and using the filter. Without that it doesn't even show that its "on and active " in the nvidia control, and by looking at it and comparing to videos on my browser it is definitely not enabled.

**Comment by clsid2** [comment]
Press Ctrl+J for debug OSD and make screenshot of the video.

**Comment by kelayz** [comment]
> Press Ctrl+J for debug OSD and make screenshot of the video.

Will do once I'm home in about 7 hours lol. I'll remove mpc hc from the nvidia app and reset settings to default in mpc hc as well and do a restart and I'll change the output to mpc renderer.

**Comment by kelayz** [comment]
showing that its on global
![image](https://github.com/user-attachments/assets/9dfe6c0e-e2d4-4bad-bda0-1318f86261ce)
showing its active
![image](https://github.com/user-attachments/assets/f54bcb43-33c6-4ce4-a61a-1396642a3e63)
showing inactive - with renderer output - default LAV
![image](https://github.com/user-attachments/assets/920b7d8d-7996-4a90-a0bc-980625c42ccd)
inactive with mpc output - d3d11 lav
![image](https://github.com/user-attachments/assets/5debf1d7-f466-4bfd-8c0b-d2cba5d58765)


![image](https://github.com/user-attachments/assets/240fc064-29b9-401a-be4e-1df8f7726b98)
![image](https://github.com/user-attachments/assets/0c6e0d0c-8492-42a5-8f6e-7426fd650066)

Monitor is Alienware DWF - oled 1000nits 165hz. Currently using 8 bit color space, can set to 10bit with custom resolution if needed. 
(edit to move sentences so pictures make sense)

**Comment by clsid2** [comment]
That video is already HDR. If passthrough does not work properly, it is monitor/driver/windows issue. Try 10-bit output to monitor.

RTX HDR is for inverse tonemapping SDR videos.

**Comment by kelayz** [comment]
Got it, I was testing multiple video files that were not labeled "HDR" and was still having the issue. Seems they do have HDR in the video, I assume where it says (color rgb 8-bit hdr10:on) means its encoded already into it?

i just downloaded a random 720p youtube video and rtx hdr does indeed activate.

**Comment by clsid2** [comment]
`hdr10: on` means Windows HDR is enabled.

The `input format` shows if the video is HDR. Easily recognized by the `PQ` transfer function.

**Comment by freakedenough** [comment]
i have the very same issue and this thread does not solve it unfortunately. so i add this trash comment to get devs attention.
