### ISSUE TITLE
Problem with MPC VR HDR options

### ISSUE THREAD

**Issue by Rumzeiss** [clsid2/mpc-hc#3148]
There is a problem with Windows  HDR options in MPC Video Renderer. The only option that is half working is "Allow turn on/off". It turns on HDR when you start the video, but does not turn it off when you pause and return to desktop for example, unless you close MPC-HC . All other options from the Windows HDR menu are NOT working, confirmed on Windows 10 and 11, on AMD and Nvidia graphics cards. Note that "Convert so SDR" is unchecked, "Passthrough to display" and "Prefer Dolby Vision" are checked.

**Comment by clsid2** [comment]
That is exactly how it is supposed to work. It only turns off when closing file.

"Convert so SDR" is only relevant when passthough is not possible and should be kept checked always.

**Comment by Rumzeiss** [comment]
> That is exactly how it is supposed to work. It only turns off when closing file.
> 
> "Convert so SDR" is only relevant when passthough is not possible and should be kept checked always.

HI, thank you for the reply..
I think you didn't read carefully or misunderstand what i have meant. 
1. It is not supposed to turn off HDR only when you close the file, but also when you pause it .  I have used it that way in previous versions months ago and it worked ! Now only in madVR.
2. Convert to SDR is irrelevant to the issue. Display is HDR Pro compatible TV used for monitor, watching only HDR content.
3. The only option from Windows HDR menu that works is "Allow turn on" . Fullscreen and turn off functions are not working !

**Comment by clsid2** [comment]
"Turn off" in the dropdown means not turning off after having turned it on. It always does that. It means the renderer can turn off Windows HDR when opening a SDR video.
