### ISSUE TITLE
Execution conflict if HandBrrake 1.5.1 is loaded in any state.

### ISSUE THREAD

**Issue by markeby** [clsid2/mpc-hc#3150]
When HandBrake is loaded, not even re-rendering content, launching MPC-HC hangs and minutes later starts the video.  In this state, HEVC content only plays sound and no video.  There is no issue if HandBrake is not loaded.  This was discovered in Windows 11 Pro 23H2, HandBrake version 1.5.1 (2022011000), and MPC-HC version 2.3.7 (c8eb473f7).

If someone is looking into this and cannot duplicate, contact me and I can work with you to isolate the conflict.

**Comment by clsid2** [comment]
Tell your GPU vendor to fix their driver.
