### ISSUE TITLE
[V2.3.7] Mouse click settings reverts to Play/Pause after restart (after selecting Fullscreen)

### ISSUE THREAD

**Issue by LeoKeogh** [clsid2/mpc-hc#3151]
Hello,

There is minor issue with mouse settings: the app refuses to keep the Fullscreen action on mouse click after restart.
**Setup**
![image](https://github.com/user-attachments/assets/c48f1b2f-f46a-450b-8918-5113702d4e5a)
**After restart**
![image](https://github.com/user-attachments/assets/d07967c1-0b73-45b8-a335-62508d5af4e9)

Thanks for your great app

Regards

**Comment by clsid2** [comment]
Fixed
