### ISSUE TITLE
Subtitles don't display when loading the next file via skip forward

### ISSUE THREAD

**Issue by KevivL** [clsid2/mpc-hc#3152]
This happens after you open a file with subtitles - they display fine. If you view it for a few minutes and then load the next file in folder via skip forward, the next file simply doesn't render the subtitles. The settings aren't changing, they simply don't render even if you enable/disable etc.

The weirder part is if you load a file and immediately skip forward to the next, the subtitles work fine. This error only happens after having the first file play for a few minutes. So far the only workaround is to re-launch a new player per file.

MPC-HC (64-bit)
---------------

Build information:
    Version:            2.3.6 (98f0f2ec2)
    Build date:         Oct  5 2024

LAV Filters:
    LAV Splitter:       0.79.2.20
    LAV Video:          0.79.2.20
    LAV Audio:          0.79.2.20
    FFmpeg compiler:    MinGW-w64 GCC 13.3.0

Operating system:
    Name:               Windows 11 (Build 22H2)
    Version:            10.0.22621 (64-bit)

Hardware:
    CPU:                AMD Ryzen 7 7735HS with Radeon Graphics
    GPU:                AMD Radeon(TM) Graphics (driver version: 32.0.12011.1036)
    Monitor:            \\.\DISPLAY1 - Generic PnP Monitor [1920x1200 32-bit 120 DPI] - [Current]

Text:
    Scale Factor:       1.000000
    Ansi Codepage:      1252

**Comment by clsid2** [comment]
Update to 2.3.7

**Comment by KevivL** [comment]
Ah. That fixed it. Thank you.
