### ISSUE TITLE
Autohotkey and fullscreen

### ISSUE THREAD

**Issue by djsolidsnake86** [clsid2/mpc-hc#3158]
i have a autohotkey automation with also this parameter SendMessage, 0x111, 830,,, ahk_class MediaPlayerClassicW
the problem is that if the player is already in fullscreen with this command the player go in window
is possible create a command that set the player only in fullcreen even if is already in fullscreen?

**Comment by clsid2** [comment]
No.

You can use autohotkey code to check if the window is already fullscreen.
WinGet -> style generally has WS_CAPTION in windowed and not in fullscreen.

For help with autohotkey you need to ask on their forum. I do not provide help for it.
