### ISSUE TITLE
Audio thumbnail not updated

### ISSUE THREAD

**Issue by Kochise** [clsid2/mpc-hc#316]
When playing audio files (mp3, m4a, ...) MPC-HC displays the JPG thumbnail (if present in the same folder).

However when switching to the next audio file (if present and settings allows it) the corresponding thumbnail (if present) is not displayed, the first thumbnail displayed remains on screen.

**Comment by clsid2** [comment]
Does second file have embedded thumbnail? Or is second file located in different folder?

**Comment by Kochise** [comment]
Nope, used youtube-dl to download M4A files with their respective JPG thumbnail, inside the same folder. When you start playing the first file in the folder, the JPG thumbnail file (not the embedded thumbnail inside the M4A) is displayed. But when MPC-HC switch to the next M4A file, the next JPG thumbnail is not displayed, it remains on the first one.

https://github.com/Kochise/youtube-dl_portable -> run youtube-dl_playlist_m4a.bat

However if the next file is a video, the video plays no problem, but when it switches back to an audio file, only the first audio file's JPG thumbnail is displayed.

**Comment by adipose** [comment]
I can confirm the behavior. The code is designed to have one coverart per folder, as is often the case with mp3 album rips.  It won't check until the folder or author has changed.

**Comment by Kochise** [comment]
Ok then, but as I often rip music youtube channels, each rip comes with its own JPG thumbnail, hence I expected to have the right thumbnail with the right music. So maybe that's a natural evolution of how media are played. Hence adding a checkbox in the 'Playback' page of the options shall makes it.

https://www.youtube.com/channel/UCRIMQm0oyhz9MjlqJZJVxog/videos

I leave that here so you can get an idea...

**Comment by adipose** [comment]
I made a test build to use per-file coverart if it exists, and to switch the cover each file.  Basically the art has to have the same filename (minus extension), and it will always check for other art.  Otherwise, it treats it as album coverart, and won't change unless the author or folder changes.

https://mega.nz/#!MFhD0TpJ!ljmx8jXTl296Z7wCoTx1w3qLgYjOx2DWfENPBnKqn6E

**Comment by Kochise** [comment]
It works, thanks :)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/320

**Comment by Kochise** [comment]
#541

**Comment by Kochise** [comment]
#571
