### ISSUE TITLE
How to capture HDR photo from MPC-HC

### ISSUE THREAD

**Issue by oliverance** [clsid2/mpc-hc#3164]
when watching HDR movies, my screenshots from MPC-HC don't reflect the HDR color and appear washed out and flat when compared to the video. I'm currently using the MPC-VR.

**Comment by clsid2** [comment]
By disabling HDR passthrough in the renderer.

**Comment by LeonNamowitz** [comment]
So to take a screenshot while watching HDR movies I have to pause, go into the renderer settings, disable passthrough, close the settings, take a screenshot, and then go back in and enable HDR again to continue watching? 

Is there any way to make this less of a pain each time? Maybe some way to hotkey HDR passthrough?

**Comment by clsid2** [comment]
In next release the renderer will do that automatically. The renderer was recently adapted to do that.

**Comment by LeonNamowitz** [comment]
That truly sounds amazing. Thanks a lot!
