### ISSUE TITLE
whole program instantly crashes when spam clicking a video

### ISSUE THREAD

**Issue by h4vok-git** [clsid2/mpc-hc#3166]
I have a playlist with 3000 nvidia shadowplay clips each clip averaging around 100mb and the folder is 265GB in size I usually have the entire folder open in the playlist menu but sometimes when clicking on one of the videos in the playlist menu it doesn't instantly load so i double click on the selected entry again which can cause the entire program to freeze and then instantly crash. This can also be duplicated by spam clicking on an entry in the playlist. 

NOTE: Nvidia Shadowplay uses NVENC i'm not sure if this is the cause of the issues. 

Version: 2.3.7
Windows 10 22H2

system specifications: 
ryzen 2700x
32GB RAM
Rtx 3060ti

the drive the clips are stored on is a 1tb 7200rpm harddrive with only 70gb of free space left.

**Comment by clsid2** [comment]
It doesn't crash. It self terminates the process for safety to prevent a bad state and hanging process.

It is not easy to fix. In fact, it may not get fixed at all.

The biggest issue is your own actions and those are easy to fix.

**Comment by clsid2** [comment]
Options > Playback > Uncheck "use worker thread to construct the filter graph"

**Comment by clsid2** [comment]
Try 2.3.7.20 development build
