### ISSUE TITLE
Volume OSD Slow to Update/Show up

### ISSUE THREAD

**Issue by haitham506** [clsid2/mpc-hc#3168]
Hello,

Volume OSD is Slow to Update/Show up it doesn't show up immediately.

It also takes too long to auto hide, Can we have the option to set the Auto Hide Time?

Thank you :)

https://github.com/user-attachments/assets/49bc4651-1a7f-4c48-aca1-2bd122c7a4a3

**Comment by clsid2** [comment]
You are using Madvr. That draws the OSD by itself. Delay is caused by Madvr and it settings, such as large frame queues.

Time can not be adjusted. It is 3 sec.
