### ISSUE TITLE
Slow seeking when external audio is loaded

### ISSUE THREAD

**Issue by zinalili** [clsid2/mpc-hc#3171]
Seeking is fine until I tick "Auto-load audio tracks" in "Playback" settings. There are two external audio tracks in DTS, which cause slowness. I'm not playing them with the video, they're just loaded. And it seems that seeking is applied to them as well causing freezes.

**Comment by clsid2** [comment]
Uncheck the option or rename the unwanted files to prevent them from loading.

Seeking applies to all files in the filter graph. If seeking a raw dts file is slow that is due to the lack of a proper container format for the audio stream.
