### ISSUE TITLE
The position of subtitles differs depending on whether they are one or two lines long.

### ISSUE THREAD

**Issue by TB54** [clsid2/mpc-hc#3175]
Hello (and thanks for this awesome freeware !),

I've noticed an oddity concerning the position of subtitles: when the subtitle is two lines long, it's positioned higher than when the subtitle is only one line long. 

https://i.imgur.com/2ikQRuU.png

In theaters, it's usually the opposite (one-line subtitles are positioned at the middle position of the two line ones, or at the bottom position of the second line).
Here are the current settings of my software (2.3.7) :

https://i.imgur.com/CEpQgwb.png

I have this problem whether the subtitles are nested (mkv) or separated. These are srt subtitles. And I have this on all my video files.

I don't know if anyone else has this problem?

**Comment by clsid2** [comment]
It is due to `opaque box` setting.

**Comment by clsid2** [comment]
Fixed

**Comment by TB54** [comment]
Thanks!
