### ISSUE TITLE
Double clicking issue with leaving fullscreen

### ISSUE THREAD

**Issue by itsleemcguire** [clsid2/mpc-hc#3180]
Set mouse clicks - 
single = play/oause
Double click = enter/exit fullscreen.

Now when trying to double click sometimes it just unpauses the video, or doesnt work at all. I've tried to click about 12 times to exit fullscreen and exded up having to CTRL ALT DEL to get out of the video. Its like the milliseconds its loooking for a double click are too short so its just reading two fast single clicks

**Comment by clsid2** [comment]
It uses the standard double-click time of Windows.

**Comment by clsid2** [comment]
You can press Esc or F11 to exit fullscreen

**Comment by itsleemcguire** [comment]
I dont have this issue on Youtube, Plex or VLC which all have the exact same double click behavior so something is wrong with it

**Comment by clsid2** [comment]
You seem to be the only one with the problem, so there is nothing I can do.

**Comment by clsid2** [comment]
Try if changing the video renderer makes any difference.
