### ISSUE TITLE
MadVR filter output, it's impossible to rotate the video along the Y-axis in the MPC software. 

### ISSUE THREAD

**Issue by douying2334** [clsid2/mpc-hc#3181]
After enabling the MadVR filter output, it's impossible to rotate the video along the Y-axis in the MPC software. However, after enabling the AVR filter output, the "Rotate" option below MPC shows a green checkmark instead of a cross, indicating that rotation should be possible. Is this a bug? Switching to the EVR (Enhanced Video Renderer) recommended filter enables the video to be rotated along the Y-axis.

**Comment by clsid2** [comment]
Madvr does not support mirroring. Only rotate.

Recommended renderer is MPC Video Renderer.
