### ISSUE TITLE
can't  remember the playback position of files.

### ISSUE THREAD

**Issue by douying2334** [clsid2/mpc-hc#3182]
Of course, the option of remembering the playback position has been clearly checked.，I've tried the latest version of MPC, and neither the old versions can remember the playback position of files. Is it a bug? I've changed the directories to many disks, including Disk C and non-C disks, but it didn't work at all. The installation method is to download the compressed package you sent and then decompress it to other disks. When I open a video, play it halfway and then exit, when I reopen it, it still starts playing from the beginning and simply can't remember the playback position at all.

**Comment by clsid2** [comment]
Do not store settings in INI file when that file does not have write access.

It also does not remember for very shorts videos. You can adjust that in advanced settings.
