### ISSUE TITLE
Dolby Vision Fullscreen problem

### ISSUE THREAD

**Issue by mok73125** [clsid2/mpc-hc#3185]
Hello when i enter a movie in fullscreen the movie switches from dolby to hdr10 and then switches back to dolby after some seconds and then again to hdr10 after some seconds and loops like that but if its windowed dolby vision works but once you enter fullscreen it breaks.

**Comment by clsid2** [comment]
It does not support Dolby Vision output. Only HDR10. This is how it works, and it will also not be supported in the future.

In windowed mode the output is controlled by Windows.

https://answers.microsoft.com/en-us/windows/forum/all/windows-11-use-dolby-vision-mode-check-box-is/9197b045-fda3-40bf-8ba9-9956bf9f3f91
Check if your monitor has option to disable Dolby Vision.

**Comment by clsid2** [comment]
https://www.reddit.com/r/OLED_Gaming/comments/1af37kj/awf3225qf_how_to_turn_off_dolby_vision/
