### ISSUE TITLE
videolan git address has been changed

### ISSUE THREAD

**Issue by YMahmoudnia** [clsid2/mpc-hc#319]
Hello
libudfread in LAVFilters address has been changed to code.videolan.org but your GIT file not changed and I had problem during cloning the MPC.

`loning into 'C:/Users/xxx/LAVFilters/libbluray/contrib/libudfread'...
fatal: remote error: access denied or repository not exported: /libudfread.git
fatal: clone of 'git://git.videolan.org/libudfread.git' into submodule path 'C:/Users/xxx/LAVFilters/libbluray/contrib/libudfread' failed
Failed to clone 'contrib/libudfread'. Retry scheduled
Cloning into 'C:/Users/xxx/LAVFilters/libbluray/contrib/libudfread'...
fatal: remote error: access denied or repository not exported: /libudfread.git
fatal: clone of 'git://git.videolan.org/libudfread.git' into submodule path 'C:/Users/xxx/LAVFilters/libbluray/contrib/libudfread' failed
Failed to clone 'contrib/libudfread' a second time, aborting
Submodule path 'qsdecoder': checked out 'd1c57d8388dc68a8925ef4c6416371fb900d1192'
Failed to recurse into submodule path 'libbluray'`

Could you update the Git installer file ?

Thank you.

**Comment by clsid2** [comment]
@nevcairiel

**Comment by bfoos** [comment]
I actually noticed this about a month ago iirc. MPC-HC still compiles and I didn't notice any impaired functionality but I imagine there might be issues that I just lack the files to play and discover. It should be fixed.

**Comment by YMahmoudnia** [comment]
Today I also tried to clone the new version, 1.9.2.0 but url not changed yet.
I use Git Desktop fromgit-scm and use 

`git clone --recursive https://github.com/clsid2/mpc-hc.git`.

Regardless of this case, If I want to clone that dependency separately, What the structure should it has in LAVFilters folder ?

Thank you.

**Comment by clsid2** [comment]
You can manually fix the url yourself by modifying the .gitmodules file in libbluray folder.

**Comment by bfoos** [comment]
> 
> 
> You can manually fix the url yourself by modifying the .gitmodules file in libbluray folder.

And how does this help while cloning? Also what are the potential downfalls of this error if any at all?

**Comment by clsid2** [comment]
Let Git update submodules again after you fix the url, and it should import the missing libudfread files.

You can compile the player without it. This stuff is part of the LAV Filters that are used as internal codecs.

**Comment by bfoos** [comment]
> 
> 
> Let Git update submodules again after you fix the url, and it should import the missing libudfread files.
> 
> You can compile the player without it. This stuff is part of the LAV Filters that are used as internal codecs.

I'm aware that libudfread is part of LAV and that MPC-HC compiles (LAV included) without fixing the issue. Are there any pitfalls to NOT fixing the error?

So the correct course of action to fix is then...

- Browse to ***SourceLocation***\mpc-hc\src\thirdparty\LAVFilters\src\libbluray
- Open .gitmodules in a text editor 
- Replace git://git.videolan.org/libudfread.git with git://code.videolan.org/libudfread.git
- Then run `git submodule update --init --recursive` from inside the mpc-hc directory

?

**Comment by clsid2** [comment]
Yes, that should do it.

It is required only for the libbluray part of LAV Filters. So if the rest compiles, that is the only thing that won't work.

**Comment by bfoos** [comment]
Ok that didn't work, it's still trying to grab from git://git.videolan.org/libudfread.git @Nevcairiel is gonna have to do it when he unbusy's himself.

**Comment by bfoos** [comment]
I got it to checkout the libudfread module by editing the URL in the config file located in `\mpc-hc\.git\modules\LAVFilters\modules\libbluray` to `https://code.videolan.org/videolan/libudfread.git`

```
bfoos@bfoos-laptop MINGW64 /e/source/repos/mpc-hc (develop)
$ git submodule update --init --recursive
Cloning into 'E:/source/repos/mpc-hc/src/thirdparty/LAVFilters/src/libbluray/contrib/libudfread'...
Submodule path 'src/thirdparty/LAVFilters/src/libbluray/contrib/libudfread': checked out '131629921cc756c38eaf3e2d6b69ba2db690b199'

```
