### ISSUE TITLE
Problems with MPC-HC when playing 8K videos

### ISSUE THREAD

**Issue by louissgd** [clsid2/mpc-hc#3192]
My PC configuration: i9 12900KF+RTX3070
System: WIN11 23H2 22631.2715
Graphics card driver: 551.61

When playing 8K HEVC-encoded videos (MP4 or MKV are the same)
MPC-HC+MPCVR+LAVFilters
The 32-bit player cannot play the image, the screen is black, and the audio plays normally
The 64-bit player cannot play the file, the screen is black, and the audio does not play
POT(64-bit)+MPCVR+LAVFilters
Perfect playback
MPC-HC+MADVR+LAVFilters
The 32-bit player crashes (with crash report attached)
The 64-bit player plays perfectly

When playing 8K VP9-encoded videos
MPC-HC+MPCVR+LAVFilters
The 32-bit player cannot hardware decode, The picture and sound are normal
The 64-bit player plays perfectly
MPC-HC+MADVR+LAVFilters
The 32-bit player is seriously stuck
The 64-bit player plays perfectly

When playing 8K AV1-encoded videos
MPC-HC+MPCVR+LAVFilters
The 32-bit player has compatibility issues, it is seriously stuck and crashes occasionally
The 64-bit player plays perfectly
MPC-HC+MADVR+LAVFilters
The 32-bit player crashes
The 64-bit player plays perfectly

[madVR - crash report.txt](https://github.com/user-attachments/files/17964464/madVR.-.crash.report.txt)
My most commonly used solution is MPC-HC+MPCVR+LAVFilters
How can I solve this?

**Comment by v0lt** [comment]
There is nothing you can do for a 32-bit player.

**Comment by clsid2** [comment]
Use d3d11 decoding.
Disable video processor in MPCVR if your hardware is too slow to process 8k that way.

Otherwise stop playing 8k demo files, as using 8k is completely utterly pointless.
