### ISSUE TITLE
Autozoom (200%) does not work as expected

### ISSUE THREAD

**Issue by radpopl** [clsid2/mpc-hc#3199]
Autozoom doesn't work as expected (or I have the wrong expectations).

After selecting the option as in the picture, I expected that every video played would be zoomed in twice. However, this does not happen and I always have to press Alt+3 to get to 200% zoom.

![zoom200](https://github.com/user-attachments/assets/1002403b-faff-44dd-bb0d-0d7b8d9a4be1)

Is this a bug?

**Comment by clsid2** [comment]
No it is working perfectly.

You probably enabled the option to remember window size.

If you don't understand why you can't have both at same time, then you are stupid.
