### ISSUE TITLE
Video color desaturation on MPC-HC's default DirectShow Video [Enhanced Video Renderer (custom presenter)] on device with AMD Integrated GPU

### ISSUE THREAD

**Issue by etherealxx** [clsid2/mpc-hc#3202]
So the problem first arose when i noticed that my recordings aren't as saturated (or is it a contrast problem) as the actual thing on my screen. I then compare it to VLC media player, and here are, from left to right, the actual software (Godot), then VLC, then MPC-HC, both uses default video settings.
![image](https://github.com/user-attachments/assets/3fc4da90-479b-4d22-8419-9f0a3404e7ec)

So i checked the Options > Playback > Output > DirectShow Video settings and it was set to `Enhanced Video Renderer (custom presenter)`, which i suppose is the default. So after some testing, the same desaturated looks happens on both `Enhanced Video Renderer (custom presenter)` and `Sync Renderer`. Meanwhile the `MPC Video Renderer` and `Enhanced Video Renderer` (not the custom presenter one) looks fine. The same desaturated looks could be replicated when using MPC Video Renderer and setting the `Use Direct3D 11` to off.

After some searching, i don't know if this is right or not, but it could be the Pixel Format setting needs to be set to `RGB 4:4:4 Full RGB` on Radeon Software. However, said setting is not available when using AMD Integrated Graphics (only on dedicated GPU).

**So whats the problem?** The problem is that since Enhanced Video Renderer (custom presenter) is the default renderer, user don't know if it's the renderer's fault, if MPC-HC is their only media player (i thought this was OBS issue). VLC had it right on their default renderer. Maybe implement a fallback when it detects AMD integrated graphics or something?
Honestly idk if this is the renderer issue or AMD issue, either way, you decide.

Here are some probably useful screenshots

Enhanced Video Renderer (custom presenter)
![image](https://github.com/user-attachments/assets/7a891753-2a68-4c98-a43c-2d09e5bbcdcd)

MPC Video Renderer
![image](https://github.com/user-attachments/assets/bae56de1-cf5a-4677-a6b2-023bfc337845)

For now, for me, using the MPC Video Renderer fixed the issue. But new users could probably get the same issue without knowing the solution.

**Comment by clsid2** [comment]
It is a driver bug. Report it to AMD.

**Comment by clsid2** [comment]
This might help with EVR-CP:
Menu > Play > Renderer settings > Output range

**Comment by clsid2** [comment]
Does it only happen with screen recordings? (which are full range)
Does disabling hardware decoding in the video decoder settings, also fix it?

Then it is driver bug where the hardware decoder incorrectly flag the video as limited range. These details are useful to mention in case you make AMD bug report.

**Comment by giwrgosmant** [comment]
> For now, for me, using the MPC Video Renderer fixed the issue. But new users could probably get the same issue without knowing the solution.

Same issue here with AMD 6700XT.
I was going crazy, I switched to MPC Video Renderer and the issue seems fixed. I then looked here to see if any other have similar issue and found your report.
