### ISSUE TITLE
Sub position issue

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#3204]
https://github.com/user-attachments/assets/c2f488c3-869f-4830-8de8-c72cfb8e1017

I extracted the sub to upload here then found it works fine if I play with other movie as external sub.
Giving Sub file if you can reproduce.
[Dia.2020.UNCUT.1080p.WEB.DL.Hindi.Dual.DD.2.0.x264.ESubs_track4_[eng].zip](https://github.com/user-attachments/files/18052614/Dia.2020.UNCUT.1080p.WEB.DL.Hindi.Dual.DD.2.0.x264.ESubs_track4_.eng.zip)

If file is needed I will upload that soon.

**Comment by bibsp** [comment]
https://drive.google.com/file/d/1OKYyuT0oKxTdjC77Mx2EeIkhNCOQ10zP/view?usp=sharing

Mpcbe, vlc all have same issue.

**Comment by clsid2** [comment]
It is not a bug. It's timestamp overlaps with that of previous subtitle.
