### ISSUE TITLE
Up/downscaling algorithms

### ISSUE THREAD

**Issue by toconquer** [clsid2/mpc-hc#3205]
Hello! What are the highest quality options for Chroma Upscaling, Upscaling, and Downscaling?
I'm currently set to Catmull, Catmull, and Hamming for these respectively. Are these the best options? Sorry, I'm unable to find any documentation on what these are.

**Comment by clsid2** [comment]
Bottom choices are best.

Shaders are only used for scaling when video processor is disabled.
