### ISSUE TITLE
Cant load bit larger file named subtitles

### ISSUE THREAD

**Issue by jakariyaa** [clsid2/mpc-hc#3206]
This player cant load a bit larger named subtitle file (68 characters). Neither it shows the video title with same amount of character counts. If I manually rename the subtitle file, then it loads fine.

MPC-HC (64-bit)
---------------

Build information:
    Version:            2.3.8 (b56e1922f)
    Build date:         Nov 26 2024

LAV Filters:
    LAV Splitter:       0.79.2.20
    LAV Video:          0.79.2.20
    LAV Audio:          0.79.2.20
    FFmpeg compiler:    MinGW-w64 GCC 13.3.0

Operating system:
    Name:               Windows 10 (Build 21H2)
    Version:            10.0.19044 (64-bit)

Hardware:
    CPU:                AMD Ryzen 5 2600 Six-Core Processor
    GPU:                Radeon RX 580 Series (driver version: 31.0.21921.1000)
    Monitor:            \\.\DISPLAY1 - ViewSonic VA2215-FHD [1920x1080 32-bit 96 DPI] - [Current]

Text:
    Scale Factor:       1.000000
    Ansi Codepage:      1252

**Comment by clsid2** [comment]
I need the filename of both subtitle and video file, including the full path.

**Comment by jakariyaa** [comment]
> I need the filename of both subtitle and video file, including the full path.

Video File Name: `004 Day 7 - Lucy's Infinite Bookshelf and Jamies LazyColumn.mp4`
Subtitle File Name: `004 Day 7 - Lucy's Infinite Bookshelf and Jamies LazyColumn_en.srt`

The Path Where Both Files Are: `D:\Downloads\Udemy - The Complete Android 14 Kotlin Development Masterclass\Udemy - The Complete Android 14 & Kotlin Development Masterclass\07 - Day 7 - Shopping List App - Learning Loads of UI Features`

**Comment by clsid2** [comment]
It is exceeding MAX_PATH which is 260 characters.
