### ISSUE TITLE
UI performance in Windows 11

### ISSUE THREAD

**Issue by swarthyplacebo** [clsid2/mpc-hc#3207]
Hello, 

After updating to Windows 11 I've found the MPC-HC program to run very slowly. It isn't losing frames or not playing videos, but menus in "Options", for example, can some takes take several seconds to load. And when they do load, they load like a dot-matrix printer printing out the options in the menu.

The player takes much longer to load a video, in general, in Windows 11 than Windows 10. Sometimes when moving from one place in the video to another causes the little "blue circle" and I if I click on the video it says, "Program Is Not Responding"

I've searched dozens of sites for solutions to the program interface lag/slowness, but haven't found anything. Everything I've found is about "lagging video" or "adjusting the madvc codec" ...

The program lags, literally, when I'm resizing the window with my mouse cursor.

I'm not complaining ... I'm just trying to give examples to get to the root of the problem.

I love this product and it worked flawlessly in Win 10.

Is there a setting I missed? I've uninstalled and reinstalled 3 times, trying different settings. I can use OBS to take a video if that would be helpful, but hopefully I'm not the only person experiencing this issue.

For reference, my machine is an I7-12700k, 32GB RAM, AMD RTX 7800 XT so plenty of CPU, RAM, and GPU processing power.

I appreciate your help!

**Comment by clsid2** [comment]
The problem is specific to your system, and unrelated to the player. I can not help you.

Update your graphics driver.

**Comment by clsid2** [comment]
Test older versions such as 2.3.0 and 2.2.0

**Comment by clsid2** [comment]
https://superuser.com/questions/1355235/windows-gui-drawing-slows-down-with-uptime

**Comment by swarthyplacebo** [comment]
> Test older versions such as 2.3.0 and 2.2.0

v2.3.0 does not have the UI drawing issues mentioned in the super.com link. I can test newer versions up until the latest to see where it occurred, if that would be helpful. Is this something that needs to be fixed by windows or in MPC-HC or a bit of both?

Thanks for the response and link, btw.

**Comment by clsid2** [comment]
Yes, test versions between 2.3.0 and 2.3.8. Start with 2.3.5 and 2.3.6.

Do you have any of these apps installed? Trusteer Rapport, Asus GamerOSD, ASUS GPU TWEAK, or Nahimic Audio.

**Comment by swarthyplacebo** [comment]
> Yes, test versions between 2.3.0 and 2.3.8. Start with 2.3.5 and 2.3.6.
> 
> Do you have any of these apps installed? Trusteer Rapport, Asus GamerOSD, ASUS GPU TWEAK, or Nahimic Audio.

None of the above applications are installed. I do not have any ASUS products in my system or installed. Nahimic Audio, I believe is related to Realtek and I'm using SoundBlaster; no realtek audio software or drivers are installed on my machine. I do not know what Trusteer Repport is, it is not installed.

The issue introduces itself in v2.3.6.21.

v2.3.6 has no issues with UI draw.

**Comment by clsid2** [comment]
And an app called Sizer? (hook64.dll)

**Comment by swarthyplacebo** [comment]
> And an app called Sizer? (hook64.dll)

I do have Sizer installed, yes.

**Comment by clsid2** [comment]
That is the cause then. It is on a dll blocklist used by MPC-HC for stuff that appeared in crash dumps.

**Comment by swarthyplacebo** [comment]
> That is the cause then. It is on a dll blocklist used by MPC-HC for stuff that appeared in crash dumps.

Is it dangerous or just caused issues with MPC-HC? If not dangerous, is it just a question as to whether I stay with outdated MPC-HC OR remove Sizer and update to latest?

Thanks for the help here!

**Comment by clsid2** [comment]
It blocks some third party stuff that hooks into the player code and can potentially cause instability.

The blocklist will be disabled in next release.

But Sizer could probably use some modifications as well to not mess with MPC-HC's windows. The player does its own sizing.

**Comment by swarthyplacebo** [comment]
Thank you very much for your help and working through this with me. I will stay on 2.3.6 until the next release.
