### ISSUE TITLE
Can't crop black bars using MadVR

### ISSUE THREAD

**Issue by cafevincent** [clsid2/mpc-hc#3209]
I have MPC-HC set to use MadVR, and MadVR is set to "automatically detect hard coded black bars" and "crop black bars", but I still can't get the same zoom in behavior (touch window from outside) that I get with a video without black bars. The black bars remain. The "notify media player about cropped black bars" does not help either. Using MadVR's "always shift the image" option does align the image to top or bottom, so detection clearly works but it's not really being cropped, or the cropping is not delivered because I can't zoom in via "touch window from outside".

**Comment by clsid2** [comment]
This is wrong place for Madvr help.

Black bar detection does not work when using D3D11 native hardware decoding. Change to copyback.
