### ISSUE TITLE
Audio tracks is not displayed.

### ISSUE THREAD

**Issue by 8DL9** [clsid2/mpc-hc#3210]
Hello.
Audio tracks is not displayed:
![Audio Tracks](https://github.com/user-attachments/assets/cc7a98a8-06f2-437d-bf32-fbb85c5a5e68)
https://pasteboard.co/upW3ZF6e4YXL.png

Checked MPC-HC.2.3.8 and 2.3.7.x64
MediaInfo File:

`General
Unique ID                                : 298095005566926948080780981895751073722 (0xE043027EEF28D3E3A2FC94E4BE00FFBA)
Complete name                            : D:\1.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 4.43 GiB
Duration                                 : 1 h 32 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 6 838 kb/s
Frame rate                               : 25.000 FPS
Encoded date                             : 2024-12-13 08:38:18 UTC
Writing application                      : mkvmerge v78.0 ('Running') 64-bit
Writing library                          : libebml v1.4.4 + libmatroska v1.7.1

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L4
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 3 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 1 h 32 min
Bit rate mode                            : Variable
Bit rate                                 : 5 000 kb/s
Maximum bit rate                         : 7 500 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.096
Stream size                              : 3.18 GiB (72%)
Writing library                          : x264 core 148 r2741 5dc16ae
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x1:0x111 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / stitchable=1 / constrained_intra=0 / bframes=2 / b_pyramid=0 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=126 / scenecut=0 / intra_refresh=0 / rc_lookahead=50 / rc=2pass / mbtree=1 / bitrate=5000 / ratetol=1.0 / qcomp=0.50 / qpmin=6 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=7500 / vbv_bufsize=10000 / nal_hrd=vbr / filler=0 / ip_ratio=1.40 / aq=1:1.00
Default                                  : Yes
Forced                                   : No

Audio #1
ID                                       : 2
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 1 h 32 min
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 424 MiB (9%)
Title                                    : Dub [Movie Dubbing]
Language                                 : Russian
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No
Dialog Normalization                     : -28 dB
compr                                    : -0.28 dB
dialnorm_Average                         : -28 dB
dialnorm_Minimum                         : -28 dB
dialnorm_Maximum                         : -28 dB

Audio #2
ID                                       : 3
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 1 h 32 min
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 424 MiB (9%)
Title                                    : Dub [Postmodern]
Language                                 : Ukrainian
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No
Dialog Normalization                     : -25 dB
compr                                    : -0.28 dB
dialnorm_Average                         : -25 dB
dialnorm_Minimum                         : -25 dB
dialnorm_Maximum                         : -25 dB

Audio #3
ID                                       : 4
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 1 h 32 min
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 424 MiB (9%)
Title                                    : Original
Language                                 : Polish
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No
Dialog Normalization                     : -27 dB
compr                                    : -0.28 dB
dialnorm_Average                         : -27 dB
dialnorm_Minimum                         : -27 dB
dialnorm_Maximum                         : -27 dB

Text #1
ID                                       : 5
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 24 min
Bit rate                                 : 1 b/s
Frame rate                               : 0.004 FPS
Count of elements                        : 22
Stream size                              : 830 Bytes (0%)
Title                                    : Forced
Language                                 : Russian
Default                                  : Yes
Forced                                   : No

Text #2
ID                                       : 6
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 30 min
Bit rate                                 : 88 b/s
Frame rate                               : 0.234 FPS
Count of elements                        : 1273
Stream size                              : 58.6 KiB (0%)
Title                                    : Full [Netflix]
Language                                 : Russian
Default                                  : No
Forced                                   : No

Text #3
ID                                       : 7
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 27 min
Bit rate                                 : 104 b/s
Frame rate                               : 0.239 FPS
Count of elements                        : 1248
Stream size                              : 66.8 KiB (0%)
Title                                    : Full [Movie Dubbing]
Language                                 : Russian
Default                                  : No
Forced                                   : No

Text #4
ID                                       : 8
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 24 min
Bit rate                                 : 1 b/s
Frame rate                               : 0.004 FPS
Count of elements                        : 18
Stream size                              : 731 Bytes (0%)
Title                                    : Forced
Language                                 : Ukrainian
Default                                  : No
Forced                                   : No

Text #5
ID                                       : 9
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 30 min
Bit rate                                 : 83 b/s
Frame rate                               : 0.234 FPS
Count of elements                        : 1272
Stream size                              : 55.7 KiB (0%)
Title                                    : Full [Netflix]
Language                                 : Ukrainian
Default                                  : No
Forced                                   : No

Text #6
ID                                       : 10
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 27 min
Bit rate                                 : 105 b/s
Frame rate                               : 0.242 FPS
Count of elements                        : 1263
Stream size                              : 67.5 KiB (0%)
Title                                    : Full [Postmodern]
Language                                 : Ukrainian
Default                                  : No
Forced                                   : No

Text #7
ID                                       : 11
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 27 min
Bit rate                                 : 70 b/s
Frame rate                               : 0.275 FPS
Count of elements                        : 1442
Stream size                              : 45.0 KiB (0%)
Title                                    : SDH
Language                                 : Polish
Default                                  : No
Forced                                   : No`

**Comment by clsid2** [comment]
The track is flagged as disabled.

You can fix the file with the header editor of MkvToolNix.
