### ISSUE TITLE
Codec Error Displayed When Playing Video with Subtitles

### ISSUE THREAD

**Issue by heelee912** [clsid2/mpc-hc#3214]
``
File Source (Async.)::Output

Media Type 0:
--------------------------
Unknown

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Stream {E436EB83-524F-11CE-9F53-0020AF0BA770}
subtype: MEDIASUBTYPE_MPEG1Audio {E436EB87-524F-11CE-9F53-0020AF0BA770}
formattype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 0

Media Type 1:
--------------------------
Unknown

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Stream {E436EB83-524F-11CE-9F53-0020AF0BA770}
subtype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
formattype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 0
``

Hello,

I've encountered a persistent issue where a codec error is displayed whenever I attempt to play a video file along with a subtitle file, regardless of the subtitle renderer, video renderer, or LAV filter settings being used. This issue specifically occurs with MKV video files paired with SMI subtitle files. The error consistently appears under these conditions. Interestingly, this issue does not occur when playing the video files alone, without any subtitle files. Additionally, if the warning is ignored, the video and subtitles play normally. However, the problem arises when proceeding to the next file, even though the initial playback encounters no issues.

Could you please look into this issue? Any guidance on how to resolve or work around this error would be greatly appreciated.

Thank you for your assistance!

**Comment by clsid2** [comment]
Do not open the .smi file (or any other subtitle file). It will be loaded automatically when you open the video (if the subtitle is named correctly, same as video).

You are getting that error because it is trying to play it as a video.

**Comment by heelee912** [comment]
Ah, I see! The issue occurred because the .smi file was being opened as the next file in the folder. After selecting only the video files to open, I confirmed that the playlist is formed correctly, and everything plays as expected. Thank you for the clarification!

It would be great if there were an option in the settings under the Playback tab to "Add only video files in the folder to the playlist". I personally prefer using this MPC-HC fork over MPC-BE, and I’d love to keep using this version.

Thank you again for your help!

**Comment by clsid2** [comment]
Options > Player > Formats > Real Script > remove .smi extension
Then it will no longer be recognized as video extension.

**Comment by heelee912** [comment]
It worked perfectly! The issue is completely resolved now. You are a genius!
Thank you so much for your help and for taking the time to provide such a clear solution. I really appreciate it!

**Comment by astonaevastonaev-dot** [comment]
File Source (Async.)::Output

Media Type 0:
--------------------------
Unknown

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Stream {E436EB83-524F-11CE-9F53-0020AF0BA770}
subtype: Unknown GUID Name {08E22ADA-B715-45ED-9D20-7B87750301D4}
formattype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 0


Media Type 1:
--------------------------
Unknown

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Stream {E436EB83-524F-11CE-9F53-0020AF0BA770}
subtype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
formattype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 0

**Comment by astonaevastonaev-dot** [comment]
File Source (Async.)::Output

Media Type 0:
--------------------------
Unknown

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Stream {E436EB83-524F-11CE-9F53-0020AF0BA770}
subtype: Unknown GUID Name {08E22ADA-B715-45ED-9D20-7B87750301D4}
formattype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 0


Media Type 1:
--------------------------
Unknown

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Stream {E436EB83-524F-11CE-9F53-0020AF0BA770}
subtype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
formattype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 0

**Comment by clsid2** [comment]
Are you too stupid to make a proper bug report?

Given the total lack of information it is probably a broken file.
