### ISSUE TITLE
MKV file: Comment is displayed for Description

### ISSUE THREAD

**Issue by Feathered-Serpent** [clsid2/mpc-hc#3218]
When the video file has tags like Description and Comments and others, I would say, MPC-HC is using the wrong field for displaying the Description as the information below the video.

As you can see in this picture, MediaInfo states a Description which describes the video, and a Comment (where the downloader placed the URL into it, but could be anything).
![mpchc jpg](https://github.com/user-attachments/assets/5ab9febe-0d93-4b10-968f-4b8ebb8e25bb)

I would think, that, when the Information bar says "Description" it also should display the Description tag, not the Comment tag.

**Comment by clsid2** [comment]
It uses whatever the splitter provides as value for the description.

You can submit request to LAV Filters project.
