### ISSUE TITLE
Playback rate : 4x is the maximum

### ISSUE THREAD

**Issue by StarhuGitHub** [clsid2/mpc-hc#3226]
Hello,

The program doesn't react to 6x or 8x playback rates, no matter if I use the menu, or key combination.

**Comment by clsid2** [comment]
The player supports more higher rates.

It is the DirectSound audio renderer that has the limitation. Change renderer to SaneAR.

**Comment by StarhuGitHub** [comment]
> The player supports more higher rates.
> 
> It is the DirectSound audio renderer that has the limitation. Change renderer to SaneAR.

Hello,
Thank you for the answer.

I tried it. Have a look at the video: https://app.screencast.com/meHs697Z8lNli  , it shows that with SaneAR it does the same, both with menu commands and key combination (Ctrl+Up)

**Comment by clsid2** [comment]
Change video renderer to EVR-CP.
