### ISSUE TITLE
WEBMs that dynamically change resolution during playback will crash upon opening in MPC-HC

### ISSUE THREAD

**Issue by StickyChannel92** [clsid2/mpc-hc#3227]
WEBMs that change resolution as they play (dubbed "bouncy webms") crash the video player upon playing that section. This error message shows up as well:
![image](https://github.com/user-attachments/assets/be36d770-3de4-4a29-a0f0-88fe33e2875f)
![image](https://github.com/user-attachments/assets/dafc01d0-6aa2-465d-970b-8949f6893444)

If the user feeds into the bouncy section from the non-bouncy section, MPC-HC stops responding.

**Comment by clsid2** [comment]
Need a sample file.

**Comment by StickyChannel92** [comment]
Here are two sample memes from Discord (flashing lights on Brain Power, but I uploaded it anyways for demonstration purposes).
[[Bouncy WEBM] Saul Goodman Bouncy.webm](https://github.com/user-attachments/assets/45a98e13-d21e-42f8-b6e8-8a6246ddf414)
[751 (aaaaa) [Bouncy WEBM] Brain Power.webm](https://github.com/user-attachments/assets/de158cae-d554-44f1-96ae-386782f53748)

**Comment by clsid2** [comment]
Both play without issue here.

**Comment by StickyChannel92** [comment]
![image](https://github.com/user-attachments/assets/99e21aa2-733f-442c-a96f-fdd211b96e83)
provided by K-Lite Codec Pack

windows 10 pro
nvidia geforce rtx 3060
intel xeon e5 1620v3
32gb ram

**Comment by StickyChannel92** [comment]
Found out what the problem is! AviSynth was causing it.
