### ISSUE TITLE
GUI regressions related to dark theme

### ISSUE THREAD

**Issue by Phar-Lap** [clsid2/mpc-hc#323]
Using Media Player Classic Home Cinema 1.9.2:

Click [File -> Open File/URL...] or [Ctrl+O].
Paste a URL in the Open: field and highlight it (the blinking is easily seen when the Open: field contains some text)
The Open: or Dub: input fields blink when hovering the mouse pointer over them.

**Comment by bfoos** [comment]
Confirmed, though it is very minor and hardly an inconvenience.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/329
