### ISSUE TITLE
Is there a way to play a YouTube playlist on MPC-HC?

### ISSUE THREAD

**Issue by Aimad-LQ** [clsid2/mpc-hc#3231]
Is there a way to play a YouTube playlist on MPC-HC?

**Comment by clsid2** [comment]
Copy youtube url of a playlist.
When pasting in MPC-HC remove the `v=` parameter.

`https://www.youtube.com/watch?v=XXXXX&list=XXXXX` -> `https://www.youtube.com/watch?list=XXXXX`

Long list takes time to process.

**Comment by Aimad-LQ** [comment]
Thank you,
But this method doesn't work with playlists that YouTube automatically creates?

**Comment by clsid2** [comment]
No.
