### ISSUE TITLE
Unable to open up videos via URL links

### ISSUE THREAD

**Issue by Blue-Ike** [clsid2/mpc-hc#3236]
I'm now having issues with trying to get videos to play from youtube links via MPC-HC Menu>File>Open File/URL... and pasting a video url link. It was working for me fine this whole time but now for some reason it won't work at all. I had downloaded a K-Lite Codec Pack that was released on the 27th (Mega). Though I usually use (Full) version. I downgraded back to the recent 18.7.5 release (Full) version this time but I'm still getting this issue.

MPC-HC (64-bit)
---------------

Build information:
    Version:            2.3.9 (cde2a82a9)
    Build date:         Dec 18 2024

LAV Filters:
    LAV Splitter:       0.79.2.20
    LAV Video:          0.79.2.20
    LAV Audio:          0.79.2.20
    FFmpeg compiler:    MinGW-w64 GCC 13.3.0

Operating system:
    Name:               Windows 10 (Build 22H2)
    Version:            10.0.19045 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
    GPU:                Intel(R) UHD Graphics 630 (driver version: 25.20.100.6446)
    Monitor:            \\.\DISPLAY1 - Generic PnP Monitor [3840x2160 32-bit 288 DPI] - [Current]

Text:
    Scale Factor:       1.000000
    Ansi Codepage:      1252

**Comment by clsid2** [comment]
You need to install/update yt-dlp.exe

**Comment by Blue-Ike** [comment]
> You need to install/update yt-dlp.exe

Thanks. Looks like I'm going to have to wait until next update release.
