### ISSUE TITLE
LAV video decoder page: Active Decoder always says <inactive>

### ISSUE THREAD

**Issue by MD-78** [clsid2/mpc-hc#324]
MPC-HC 1.9.2 x64

1. play video
2. go to LAV video decoder settings page

Result: "Active Decoder" = inactive
Expected: "Active Decoder" = NVIDIA CUVID

Same with other H/W decoders (DXVA ...)

___________________
Windows 8.1 Pro
Nvidia Gefore GTX 750 Ti (driver 445.75)

**Comment by clsid2** [comment]
Inactive means exactly that. You are accessing a new inactive instance of the filter.

You can access the active filter instance through:
Menu > Play > Filters

**Comment by MD-78** [comment]
In some older version this was not the case if I remember correctly. IMO when there is a video playing it would make sense to display anything other than "inactive".

**Comment by clsid2** [comment]
No, it has always been this way and that isn't going to change either.

The player shows [H/W] in its status bar when hardware acceleration is active, so there is no need to look at the options.
