### ISSUE TITLE
Remove the autoscrolling in Pin Info

### ISSUE THREAD

**Issue by CrendKing** [clsid2/mpc-hc#325]
When a pin info has more than a pageful of content, instead of showing the content in the box, it seems to show in autoscrolling manner. When there's a lot of content (e.g. LAV Video decoder output pin), it takes like 10 seconds to be interacted, even though the first one is usually what we care. Is there any good reason for this? MPC-BE does not have this. [Illustration](https://streamable.com/5d79l)

It looks like the code is incrementally adding line by line to the edit https://github.com/clsid2/mpc-hc/blob/develop/src/filters/PinInfoWnd.cpp#L254 . I suggest build up the string then set text to the edit as whole.

**Comment by clsid2** [comment]
Fixed.

**Comment by adipose** [comment]
The method used for appending text to this window is an old win32 trick.  Set the selection to the very end of the textedit, and replace that selection with the new line of text.  Unfortunately the result is that the selection keeps moving to the end, which by default scrolls the edit.

In the code it restores the selection to the beginning when done--so there was no intention to have it scroll at all, but rather it's an artifact of that win32 trick.

Storing it all in a string might work, but for some reason that's an unpopular method (perhaps limitations on setting large amounts of text at once).

I solved this by preventing the redraw until it is done and the selection is back at the top.
