### ISSUE TITLE
About Transifex

### ISSUE THREAD

**Issue by NightSharp** [clsid2/mpc-hc#326]
I've sent a request to join translation team on transifex for my language.
But I've waited so many days and still don't receive a reply.
I just want to suppliment translations for my language.

**Comment by bfoos** [comment]
> 
> I've sent a request to join translation team on transifex for my language.
> But I've waited so many days and still don't receive a reply.
> I just want to suppliment translations for my language.

You should've posted it the current issue that is dedicated to Transifex. https://github.com/clsid2/mpc-hc/issues/215

Tagging @adipose so he'll more likely see this.

**Comment by clsid2** [comment]
Just be patient. He might be busy with other things.

**Comment by adipose** [comment]
> 
> 
> I've sent a request to join translation team on transifex for my language.
> But I've waited so many days and still don't receive a reply.
> I just want to suppliment translations for my language.

You should be able to translate now.

**Comment by NightSharp** [comment]
Thanks a lot
















At 2020-03-28 08:33:18, "adipose" <notifications@github.com> wrote:

I've sent a request to join translation team on transifex for my language.
But I've waited so many days and still don't receive a reply.
I just want to suppliment translations for my language.

You should be able to translate now.
