### ISSUE TITLE
[request] [command-line] play from n-th entry on mpcpl file.

### ISSUE THREAD

**Issue by i-false** [clsid2/mpc-hc#330]
**From the command line, a way to load and play an mpcpl playlist file from the n-th entry on it.**

something like,

`mpc-hc64_nvo.exe pl.mpcpl 35`
or maybe as a `/pi` (playlist index/item) switch?
`mpc-hc64_nvo.exe pl.mpcpl /pi 35`

**Comment by clsid2** [comment]
Why not just load the corresponding file directly?

**Comment by adipose** [comment]
I think they want it to continue from that point?

**Comment by i-false** [comment]
What I'm suggesting is the ability to start the playlist from a specific entry on it. Making it able to navigate from that point on. Like, if I start from 35, if need be, able to jump to 34 or 36 with the "Navigate->Next" or "Navigate->Previous".

**Comment by clsid2** [comment]
I understand what you want. I want to know why you want to do it this way. Can you describe how you would use this in practice?

New features are very low priority, certainly if is only useful for a small part of the user base.

**Comment by i-false** [comment]
True, I was thinking the same after making the suggestion. Not a lot of people will use it. As for me, this feature was something that I wish MPC had because I was making a little video manager/explorer to practice programming . I can launch videos directly ofcourse, but I thought it would be cool to generate a playlist from the search result and depending on what result I choose, play from the right part on the playlist. 

Maybe there is another way to do what I want! If you think this feature is not worth adding, its alright! I just thought this was worth bringing up here.

**Comment by adipose** [comment]
If you generate the playlist programmatically, you could rotate the sort so the nth item was first.

**Comment by i-false** [comment]
omg thank you! I should have checked this before! I thought I wont be able to do "Navigate->Previous" because of starting from the first entry.

**Comment by clsid2** [comment]
Navigate->Previous/Next also work for first/last entry.
