### ISSUE TITLE
Saving extensions video format in (save image)

### ISSUE THREAD

**Issue by AdiOpi** [clsid2/mpc-hc#336]
Is it possible to add options saveimagevideoformat (yes, no)
I use the save image feature a lot and I miss this feature.

![1](https://user-images.githubusercontent.com/58853121/77891064-b3670c00-7270-11ea-878b-e55538aacfb4.jpg)

Regards

**Comment by clsid2** [comment]
I don't understand what you mean.

It already includes the file extension it the name.
video.mp4.jpg

**Comment by AdiOpi** [comment]
To save a file without a video extension name.

video.mp4.jpg  - bad

video.jpg  - good

**Comment by adipose** [comment]
@clsid2 , I think I can do this, but I'd rather avoid the Advanced option, if possible.  Can it just be the default, or do we want to keep the old behavior around?

**Comment by clsid2** [comment]
Changing default behavior would probably result in complaints. Best to add advanced option.
