### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by sfmict** [clsid2/mpc-hc#337]
```
MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.2 (a1527b29b)
    Compiler:           MSVC v19.16.27035
    Build date:         Mar 23 2020 11:32:03

LAV Filters:
    LAV Splitter:       0.74.1.34
    LAV Video:          0.74.1.34
    LAV Audio:          0.74.1.34
    FFmpeg compiler:    MinGW-w64 GCC 9.2.0

Operating system:
    Name:               Windows NT 10.0 (build 17763)
    Version:            10.0 (64-bit)
```
If you switch to next or previous file (PageUp or PageDown), sound disappears.

**Comment by clsid2** [comment]
This is likely the fault of Windows or your sound driver.

Windows Control Panel > Sound > Speakers > Properties > Advanced > disable the Exclusive Mode options

**Comment by sfmict** [comment]
Disconnected, did not help :(.

**Comment by sfmict** [comment]
```
MPC-HC (64-bit)
---------------

Build information:
    Version:            1.8.8 (82efc58f7)
    Compiler:           MSVC v19.16.27034
    Build date:         Oct  3 2019 10:51:21

LAV Filters:
    LAV Splitter:       0.74.1.24
    LAV Video:          0.74.1.24
    LAV Audio:          0.74.1.24
    FFmpeg compiler:    MinGW-w64 GCC 8.3.0

Operating system:
    Name:               Windows NT 10.0 (build 17763)
    Version:            10.0 (64-bit)
```
Everything works

**Comment by sfmict** [comment]
Hmmm, works from any other folders except the one in which the player has always been. Error due to update?

**Comment by clsid2** [comment]
Everything works for me, so I need more details about the conditions in which the problem occurs.

Do you mean it only happens for files that you have already played? Do you have "Remember File Position" enabled?

**Comment by sfmict** [comment]
I don’t know what the problem is, but I renamed the folder the player was in and everything worked. Sorry for disturbing you.

**Comment by clsid2** [comment]
Maybe your virus scanner was causing problems. Avast had a false positive detection when latest version was released.
