### ISSUE TITLE
OSD Volume Percentage

### ISSUE THREAD

**Issue by SirGryphin** [clsid2/mpc-hc#339]
Hi, I've not used MPC-HC in a while but I remember when you enabled OSD and changed volume it would show up on screen.

No matter what I try I can seem to get it to work, is this feature still available or I'm I thinking for the Original MPC-HC?

I running latest version of MPC-HC that came with K-Lite Codec on Windows 10.

**Update:** So I was trying to view OSD Volume on .mp3 file (audiobook) nothing shows up, Just tried a video file .mkv and it works on that. Is there anyway to get it to work on .mp3 file?

**Comment by clsid2** [comment]
OSD only works when playing video.
