### ISSUE TITLE
MPC-HC resetting "After Playback" state

### ISSUE THREAD

**Issue by passat1** [clsid2/mpc-hc#342]
As described here http://codecs.forumotion.net/t3275-mpc-hc-after-playback-bug, MPC-HC is resetting manually set "After Playback" state to default after adding any new file to playlist with Explorer context menu.

So if "After Playback" is manually set to "Shutdown" (or anything else), after adding new file to playlist it resets state to "Do Nothing".
So every time some file is added to playlist, it must be manually set again.

**Comment by passat1** [comment]
Can anyone, please, respond to this, after more than two weeks?
Confirm or deny, and at last mark it as "bug", as it can be reproduced very easy, and is obvious bug which is present for very long time.
Thanks

**Comment by passat1** [comment]
Thanks!

**Comment by adipose** [comment]
@passat1 

I could not reproduce this on latest sources.  There is no "shutdown" option, but maybe you mean "close" or "exit"?  

Can you confirm it is still an issue, and walk me through making it happen?

**Comment by passat1** [comment]
I don't know what you are you doing, but problem still exists.
1. Start playback of any video
2. Right click on video surface -> After Playback -> Shutdown (or anything else)
3. In Explorer Right click any other video file -> "Add to MPC-HC playlist"

Check again option set in step 2.

**Comment by clsid2** [comment]
@adipose
There are two 'after playback" settings. One in the options, which is remembered and applies to all files/playlists. And one in the context menu, which only applies to the currently playing file/playlist.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/505/files

Kind of a weird setting--it stores the setting itself in the commandline switches.  So you might say this was intentional.  The ability to change it contradicts that, though, so if it isn't changed on the commandline, it should now be preserved.

**Comment by passat1** [comment]
Tested and problem solved.
Thanks
