### ISSUE TITLE
Add support for application/font-sfnt MIME type

### ISSUE THREAD

**Issue by doroshenko** [clsid2/mpc-hc#345]
Current MPC-HC behavior is to display subtitles without applying the matching font, if the font file has been muxed into the Matroska container with application/font-sfnt MIME type. 

application/font-sfnt is a deprecated, but still supported MIME type for fonts according to [IANA Media Types page](https://www.iana.org/assignments/media-types/media-types.xhtml). It is used by default in MKV files created with certain MKVToolnix versions, and these files are being displayed properly by other media players. 

Tested on MPC-HC 1.9.2.

**Comment by clsid2** [comment]
Sample file?

It should already support that MIME type.

**Comment by doroshenko** [comment]
Sample file (24 MB):
https://www.dropbox.com/s/et3ugeyfnqew1y4/?dl=1

MPC-HC screenshot:
https://www.dropbox.com/s/f26j0sndklvu00p/?dl=1

mpv screenshot:
https://www.dropbox.com/s/5wr9wt6aklaiwsw/?dl=1

**Comment by clsid2** [comment]
Font is used correctly here. Same as in mpv screenshot.

**Comment by doroshenko** [comment]
The issue was on my end - I've been using an outdated version of LAV filters. Switching to the one included with the latest MPC-HC has resolved the problem.
