### ISSUE TITLE
Blinking glitch

### ISSUE THREAD

**Issue by robesasu** [clsid2/mpc-hc#346]
Hello,

I have this glitch that appears roughly in the same area, not always on all videos, but only with mpc. Same videos have no issues on vlc.

![glitch pic](https://user-images.githubusercontent.com/22528910/78394798-96be3180-75ec-11ea-96e1-2685423e089a.jpg)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22528910/78395107-2c59c100-75ed-11ea-91d3-1a733a6dbf5d.gif)

I don't know what's causing it, I've tried changing settings at random with no luck. I'm on 1.9.2 but it did happen before that.

Any ideas?

**Comment by clsid2** [comment]
I have never seen this glitch before.

Is it always in the exact same spot?
Does it also happen if you don't watch in full screen, but in a small window?

It is very likely caused by something outside of the player.

**Comment by robesasu** [comment]
Yes, doesn't matter if it's full screen or windowed, it only happens when played with mpc and at that spot.

It seems to happen only to h265 files though, but not to all of them. I've tried a playing a few h264, but it didn't appear there.

**Comment by clsid2** [comment]
Same spot in the video, or same spot on the screen? Assuming it is in the video, does the size of the glitch scale if you play at half size versus full size?

Disable hardware acceleration in the video decoder settings. Maybe that makes a difference.

Which GPU and driver do you have?

Can you give a link to this video? Then I can test if it also happens on my system.

**Comment by robesasu** [comment]
Spot on the video. If I move the window around, it goes with it. If I zoom in or out, it also scales with it. If I pause the video with it, it stays.

Disabling hardware acceleration didn't make it go away. Nevermind my previous comment about h264, got it on one too.

I'm on windows 10, up to date. My laptop is fairly old, but drivers are current. It has both an intel hd 4000 & a nvidia geforce gtx 675m.

Here's a vid where I get the glitch: https://www105.zippyshare.com/v/REfiyTgB/file.html

**Comment by clsid2** [comment]
No glitch here with that file.

Maybe changing which GPU is used will help.
https://www.tenforums.com/tutorials/103965-set-preferred-gpu-apps-windows-10-a.html

**Comment by robesasu** [comment]
That actually did it!

It used intel by default, so I switched to nvidia and it was gone. Though then I got vsync issues, but going with madvr fixed that too.

Thanks for your help.

*edit* Actually, I don't need to change the gpu. Also works with the intel one if I use madvr.

**Comment by clsid2** [comment]
Another thing that you can test is to go into the Intel driver control panel and disable all video "enhancements". Some are enabled by default and actually do more harm than good. Names to look for are: Skin Tone Enhancement, Auto Contrast Enhancement, Noise Reduction.

madVR bypasses that driver processing (and VLC also) so that is why those don't suffer from the problem.

**Comment by robesasu** [comment]
That could be it. I turned off all the settings I could find, and while the glitch was still there, it moved _elsewhere_.

For the time being, I'll stay with madvr.

Thanks for your help.
