### ISSUE TITLE
.pls

### ISSUE THREAD

**Issue by Anonymous-any** [clsid2/mpc-hc#347]
Hi I've see from this version (maybe the before one), "Playlist-file.pls" wouldn't open the content to be read now...

Br

**Comment by briantexts** [comment]
The regression is in 1.9.2, I tested previous versions and they are able to read .pls files.

Someone familiar with the repo might be able to [pinpoint the exact commit between the versions where the regression occurred.](https://github.com/clsid2/mpc-hc/compare/clsid2:1.9.1...1.9.2)

**Comment by Anonymous-any** [comment]
Cool to hear I was not wrong because you can confirm it and identify from where that began to happen.

Regard

**Comment by clsid2** [comment]
Fixed
