### ISSUE TITLE
Prevent multiple uses of the same keys

### ISSUE THREAD

**Issue by mikhaelkh** [clsid2/mpc-hc#350]
I had `[` and `]` already assigned, and version 1.9.2 added them for A-B repeat without checking.

1. Add new keys only if they are not already assigned
2. Mark multiple uses of keys like in MPC-BE

**Comment by adipose** [comment]
1. See: https://github.com/clsid2/mpc-hc/pull/517

**Comment by adipose** [comment]
2. See https://github.com/clsid2/mpc-hc/pull/563
