### ISSUE TITLE
Downloading subtitles for series downloads incorrect episode subtitles

### ISSUE THREAD

**Issue by mak1nt0sh** [clsid2/mpc-hc#351]
![subBug2](https://user-images.githubusercontent.com/33786477/78763880-6977d780-798e-11ea-93da-98de30c9ef77.png)

![subBug](https://user-images.githubusercontent.com/33786477/78763920-798fb700-798e-11ea-8fa2-d0a9dd9d2043.png)

## Steps to reproduce
File -> Download subtitles -> Hover over subtitle

### Actual behavior
List shows name for the subtitles I'm searching for. Actual file is subtitles for completely different episode. If downloaded, subtitles are for different episode as identified in hover over pop up.

### Device information
MPC-HC (64-bit)
Build information:
    Version:            1.9.2 (a1527b29b)
    Compiler:           MSVC v19.16.27035
    Build date:         Mar 23 2020 11:32:03
Operating system:
    Name:               Windows NT 10.0 (build 18363)
    Version:            10.0 (64-bit)

**Comment by clsid2** [comment]
Fixed
