### ISSUE TITLE
i get this really creepy error pop ups

### ISSUE THREAD

**Issue by rakshith111** [clsid2/mpc-hc#353]
![Screenshot_35](https://user-images.githubusercontent.com/36219488/78936838-f6c14600-7acc-11ea-8d9a-e5c77b60c5b7.png)
![Screenshot_36](https://user-images.githubusercontent.com/36219488/78936843-f7f27300-7acc-11ea-9371-faa1e0403477.png)
this happens often 
telling me to login or reset 
every time a new username and what i think a server name shows up 
is this something i have to be worried about

**Comment by clsid2** [comment]
Disable the automatic subtitle download option.

The OpenSubtitles server is currently being overloaded now that many people are staying at home. Subtitle download only works when you configure a login for opensubtitles.org
