### ISSUE TITLE
[request]Please support WEBVTT format in Matroska(mkv) file

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#354]
Please support WEBVTT format in Matroska(mkv) file.
The example of this format:
```text
Text #1
ID                             : 1
Format                         : S_TEXT/WEBVTT
Codec ID                       : S_TEXT/WEBVTT
Duration                       : 3 min 27 s
Bit rate                       : 62 b/s
Count of elements              : 36
Stream size                    : 1.59 KiB (0%)
Language                       : Polish
Default                        : No
Forced                         : No
```

**Comment by adipose** [comment]
I added VTT support before, but no one ever tested it.  However, it may not work from a container.

**Comment by adipose** [comment]
Can you send me an MKV with VTT for testing?

**Comment by lifegpc** [comment]
https://1drv.ms/u/s!Aoq8mAMlVv8Ukjbg0jTj0DjEPgDt?e=W92smX
@adipose

**Comment by clsid2** [comment]
LAV Splitter does not (yet) support embedded WebVTT.

**Comment by clsid2** [comment]
Implemented in 1.9.10.30

**Comment by ale5000-git** [comment]
Ref: https://github.com/Nevcairiel/LAVFilters/issues/80
Ref: https://github.com/Nevcairiel/LAVFilters/issues/400
Ref: https://github.com/clsid2/mpc-hc/issues/813

@clsid2: Could you please support both naming? `D_WEBVTT/SUBTITLES` and `S_TEXT/WEBVTT`.

Sample: https://trac.ffmpeg.org/raw-attachment/ticket/5641/cut-vtt.mkv
More info: https://trac.ffmpeg.org/ticket/5641

**Comment by clsid2** [comment]
That is an FFmpeg issue. That is not up to me to fix.

**Comment by 54m4d** [comment]
@ale5000-git @clsid2 

This is working for me, am i missing something?

![Capture 20_03_2021_00_33_52](https://user-images.githubusercontent.com/52612348/111851671-6ca47300-8914-11eb-84f8-6c01614400dd.png)

**Comment by clsid2** [comment]
That file contains two subtitle tracks. The second one is not yet recognized. That needs to be fixed in FFmpeg.

**Comment by 54m4d** [comment]
Normally the available subtitiles would be listed under `Subtitle Track` but indeed this one is not recognized

![Capture 20_03_2021_01_01_55](https://user-images.githubusercontent.com/52612348/111852740-6912eb00-8918-11eb-8cf8-adf9f6c23eda.png)

**Comment by ale5000-git** [comment]
@fosam: Try this sample => [8BIT-001_S_TEXT.zip](https://github.com/clsid2/mpc-hc/files/6175127/8BIT-001_S_TEXT.zip)

**Comment by 54m4d** [comment]
I tried it and `Subtitle Track` is greyed out which means the subtiltle is not enabled/active.

I have never encountered an issue like this before, maybe the subtitle was not embedded correctly or something? how did you embed the subtitle on this one? what is the origin of this video?

**Comment by ale5000-git** [comment]
The file was found over the internet but it is the same if you create it with MKVToolNix.

D_WEBVTT/SUBTITLES is for WebM files (supported).
S_TEXT/WEBVTT is for mkv files (not supported).

**Comment by 54m4d** [comment]
Works on other players however.

**Comment by ale5000-git** [comment]
Probably they have specific support for it hardcoded in the app itself.

@clsid2
Isn't possible to change the splitter to spoof `S_TEXT/WEBVTT` as `D_WEBVTT/SUBTITLES` to use the latter code?

**Comment by clsid2** [comment]
It needs to be fixed in FFmpeg. Period.
