### ISSUE TITLE
Old x264 / h264 decoding bug back?

### ISSUE THREAD

**Issue by Joachim-Otahal** [clsid2/mpc-hc#355]
A example frame result (youtube uploaded shows same result, caught same bug?:
https://joumxyzptlk.de/tmp/decode_x264_error.png

Video to test with:
https://joumxyzptlk.de/tmp/2020-04-03_Bernhausen_8_Stunden_in_anderthalb_Minuten_1300_bis_2100_Uhr.Dark-Exposition_Version.xvid.crf19.aac384.filter.mkv

Source video to encode:
https://joumxyzptlk.de/tmp/2020-04-03_Bernhausen_8_Stunden_in_anderthalb_Minuten_1300_bis_2100_Uhr.Dark-Exposition_Version.xvid.avi

Encoding command line:
c:\prog\ffmpeg\bin\ffmpeg.exe -hide_banner -loglevel error -stats -n -i "D:\tmp\2020-04-03_Bernhausen_8_Stunden_in_anderthalb_Minuten_1300_bis_2100_Uhr.Dark-Exposition_Version.xvid.avi" -max_muxing_queue_size 1024 -acodec aac -b:a 384k -c:s copy -map_metadata 0 -vf hqdn3d=3:1:3:1 -vcodec libx264 -preset:v veryslow -tune:v Film -crf 19 "D:\tmp\2020-04-03_Bernhausen_8_Stunden_in_anderthalb_Minuten_1300_bis_2100_Uhr.Dark-Exposition_Version.xvid.crf19.aac384.filter.mkv"
Tested with: ffmpeg-20200220-56df829-win64-static.zip and ffmpeg-20200403-52523b6-win64-static.zip

Video is fine with avidemux and ffplay,
vlc 3.0.8 does the same playback error, probably sharing the same reappearing h264 library decoding bug.

Version Info:
MPC-HC (64-bit)
---------------
Build information:
    Version:            1.9.2 (a1527b29b)
    Compiler:           MSVC v19.16.27035
    Build date:         Mar 23 2020 11:32:03
LAV Filters:
    LAV Splitter:       0.74.1.34
    LAV Video:          0.74.1.34
    LAV Audio:          0.74.1.34
    FFmpeg compiler:    MinGW-w64 GCC 9.2.0
Operating system:
    Name:               Windows NT 10.0 (build 18363)
    Version:            10.0 (64-bit)
Hardware:
    CPU:                AMD Ryzen 9 3900X 12-Core Processor
    GPU:                NVIDIA TITAN RTX (driver version: 26.21.14.4219)

**Comment by clsid2** [comment]
It decodes correctly with hardware acceleration disabled.

For issues with internal codecs you need to go here:
https://github.com/Nevcairiel/LAVFilters

**Comment by Joachim-Otahal** [comment]
Confirmed. Thank you for that fast reply!
