### ISSUE TITLE
Auto-zoom settings partially broken

### ISSUE THREAD

**Issue by S-h-a-d-e-r** [clsid2/mpc-hc#356]
MPC-HC v1.92.

Options -> Playback -> Zoom and Alignment -> Check to enable "Auto-zoom" -> select from drop-down menu zoom factor "Auto-fit" -> OK.

Test by playing some videofile. Auto-fit (by default to 75% of the screen size) does NOT work.

Select the zoom factor "200%", instead of "Auto-fit". Voilla, it works as if "Auto-fit" was selected ;-)

By the way, the player is set to "Store settings in .ini file" - maybe it is interconnected somehow, maybe not.

**Comment by clsid2** [comment]
This has already been fixed for next release.
