### ISSUE TITLE
Audio too quiet on certain files

### ISSUE THREAD

**Issue by lucellent** [clsid2/mpc-hc#357]
I just updated to the latest version but the audio of some particular files seems to be low. I opened them in another player and they sound fine. Really don't know what the issue is, I use the gain option for the audio but don't want to because it makes the audio sound distorted.

**Comment by clsid2** [comment]
Options > internal filters > audio decoder > enable mixing to Stereo and set Center mix level to 1.00

If that is not enough, enable Normalize
options > internal filters > audio switcher

**Comment by lucellent** [comment]
Don't mind me for opening this issue again but this doesn't solve it really. Not only the mixing to stereo didn't change anything, but I actually need 5.1 and 7.1 sometimes.
Also, as I mentioned before, using the Normalize function gives the audio distortion.

I'm forced to use Windows 10's built in player in order to playback videos with normal audio levels.

**Comment by clsid2** [comment]
If you think the audio is decoded wrong you need to go here and provide a sample file:
https://github.com/Nevcairiel/LAVFilters
