### ISSUE TITLE
Chromecast support?

### ISSUE THREAD

**Issue by max1c** [clsid2/mpc-hc#359]
I have just found out that MPC-HC is still being developed here. I am very happy about it because I can finally update my 3+ year old version of the player. Now I am wondering if Chromecast support is planned? If not, then could this possibly be considered?

**Comment by adipose** [comment]
Not much is being planned.  Chromecast support is possible, but after looking into it, it seems VLC created their own implementation.  I'm not sure if the SDK even intends to support Windows properly.

The VLC code could maybe be ported with some work.  I personally am not a big fan of Chromecast, though, as the whole thing is proprietary, and there are open standards that do the same thing.  But it is the main streaming standard out there.

**Comment by max1c** [comment]
Yea, it's understandable. Chromecast is just very popular and easy to use. It would definitely be easier casting from MPC than opening a browser and casting desktop with MPC open and playing.

What do you mean by other standards that do the same thing? Would this involve other hardware like Roku?

**Comment by adipose** [comment]
Miracast

**Comment by FightingForFun** [comment]
From MPC-HC to TV (with Chromecast)... it would be great.
