### ISSUE TITLE
[Request] Interface problem: why you can't add a key shortcut to "Organize Favorities" ?

### ISSUE THREAD

**Issue by chrixxxx** [clsid2/mpc-hc#363]
I love the player, it supports MadVR as renderer (the best!), you can apply shaders too (and above everything) ..  the player is light and fast... but very powerful; so it's my favorite choice between all existing players nowadays.

That said...  the interface is quite obsolete and it would require a sort of massive renewal.. 

I used alot Potplayer in the past, before it became an adware shite..  and I have to admit it was CENTURIES ahead, interface wise (it's the ONLY reason why I miss potplayer, for the rest I prefer MPC-HC)

I hope MPC-HC interface  it will improve in the future, but at the moment there's one thing I can't understand: I use favorites a lot.. so .. why you can assign/reassign a keyboard shortcut to add a favorite.. but  you can't have a key assigned to the "Organize Favorities" option (you have to select from menu) ???? Please, give the users this possibility: it's a completely nonsense not having it !!!!

**Comment by clsid2** [comment]
There won't be any big changes to the interface. Many people actually like it. You can enable Dark Theme option and it will look a bit more modern. The buttons can be customized as well with a toolbar image file.

**Comment by chrixxxx** [comment]
> There won't be any big changes to the interface. Many people actually like it. You can enable Dark Theme option and it will look a bit more modern. The buttons can be customized as well with a toolbar image file.

I didn't mean MPC-HC have to implement fancy themes or buttons.. 

When I expressed my desider to see it improved I meant the usability and practicability and comfort and thoroughness of its interface.

With PotPlayer I had EVERY function of the application available associated to the right mouse button with menus AND I could assign a custom key to EVERY function of the application too, submenus included! But I don't need any customization at all, since by default PotPlayer has very practical and easy to remember shortcuts for everything!!!

No need to open options or extra panels, with the press of a single key (the S key, it's default for it) I could change shaders in realtime without opening a single panel!!! And that was amazing since I use them a lot..  changing them depending on the video I'm watching..  With MPC-HC I have to open an extra panel and doing a lot of unpractical and useless operation to activate them.

See the video I'm attaching to this post to understand what I mean.. (cyan letters on the left botton area are keystrokes) : I press S and I have a little and practical menu on screen specifically for activating and adding SHADERS, pre, post.. EVERYTHING in a practical and very useful menu.

And I need only to press the shortcut  H  to access a specific little sub-menu for bookmarks (favorities in MPC-HC) where I can easily do every operation I need without fuss or unnecessary steps, like I have to do every time when using MPC-HC.

See the video.. the interface of Pot Player is AMAZING and very far ahead every other player I tested... and not for silly things like  fancy theme or buttons... but for its usability and completeness and practicability.

I hope you will see the video to understand what I mean.

Anyway.. **you didn't answer my question**: why with MPC-HC I cannot even associate a shortcut key to the menu function "Organize favorities" (to delete or organize them) ???? With shaders it is one the function that I use the most ... and I can't even assign a shortcut to open its (not very optimal to use - see the potplayer video when I press the H shortcut key) panel.

I hope my suggestions will be taken into account..

I'm not writing this to criticize or complain, but in the hope to see improvements in the usability of MPC-HC, that is my default video player nowadays.


[ScreenCapture of me using Potplayer.zip](https://github.com/clsid2/mpc-hc/files/4496357/ScreenCapture.of.me.using.Potplayer.zip)

**Comment by clsid2** [comment]
I am not going to add shortcuts for all menu items, or any other new features. I have a million other more important things to do, and little time and motivation to do them.

Adding shortcuts is not difficult, so other developers can join and implement it. I want more people to contribute as that also motivates me and everyone else that have already submitted patches.

**Comment by clsid2** [comment]
Shortcut entry has been added.
