### ISSUE TITLE
Internal subtitle renderer "blinking" with PGS subtitles

### ISSUE THREAD

**Issue by mirkosp** [clsid2/mpc-hc#365]
As per issue subject, and well shown in the attached test mkv, PGS subtitles rendered with the internal subtitles renderer blink.
Using an external renderer such as xysubfilter will work fine, as well using the internal subtitle renderer in MPC 1.7.8.162 (CCCP Build), so I assume this is a regression of sort.
[autodistruzione.zip](https://github.com/clsid2/mpc-hc/files/4498044/autodistruzione.zip)

**Comment by clsid2** [comment]
Workaround:
Options > Subtitles > Sub pictures to buffer = 0

**Comment by adipose** [comment]
I see it on EVR-CP but not MPCVR.  Didn't test others.

**Comment by adipose** [comment]
Just for the record the blinking is there in mpc-be, too.

**Comment by clsid2** [comment]
I suspect it is a rounding error in the start/end times of the buffered subs, which causes a 'gap' where a single frame has no sub displayed.

**Comment by adipose** [comment]
I agree.  I know there are some weird hacks in PGS to make sure frames don't get missed when it's on a frame boundary.  Perhaps the rounding rules break when there are animated frames close together.

**Comment by adipose** [comment]
@clsid2 

Go ahead and review this PR: https://github.com/clsid2/mpc-hc/pull/588

I've ported the code from CSubPicQueueNoThread::SetFPS to CSubPicQueue::SetFPS that sets the frame duration to 1 unit.  I suspect this will affect performance somewhat, but it's unclear to me why this code is only used in the "nothread" version.  Now that it exists in both variants, neither blinks.  This is essentially the cause of the workaround (queue = 0) working better.

**Comment by adipose** [comment]
It's broken the queue, I see now.

**Comment by adipose** [comment]
In debug mode, the queue falls behind--but it seems it was fine in release mode.  I now updated the code to divide by 1.01, and arbitrary number to make sure the frame time it targets isn't exactly as long as a frame, to make sure the subpic always gets rendered on every frame it could fall on.  Seems to work pretty well so far.

**Comment by clsid2** [comment]
Fixed
