### ISSUE TITLE
full window size bugs

### ISSUE THREAD

**Issue by motfis** [clsid2/mpc-hc#376]
Is it possible to 'freeze' the windows size when we use MPC in maximized window (red circle on the image below - not full screen)? Sometimes I accidentally click and drag on the viewing part, and the MPC becomes small window where we can move it around.

I think when MPC is in maximized window, we should not be able to move it, except if we click and drag the window on the top area (yellow part), like any windows app, e.g. explorer, notepad, or MS office.

![image](https://user-images.githubusercontent.com/8572695/80891582-3ee71900-8cc5-11ea-9414-113837011e10.png)

**Comment by adipose** [comment]
Where are you clicking and dragging?

**Comment by motfis** [comment]
On the viewing area. In the figure above : in the black area with MPC logo.
Thanks for checking.

**Comment by adipose** [comment]
I see what you are talking about.  In general, if nothing is playing, you can drag the window around using the playback/logo area.  This gives you the same capability as dragging the titlebar, which means...you could drag it out of full screen.

I have never used the "feature" above myself but it appears inherent to the application and may have a few people taking advantage of it.

@clsid2, is this feature worth preserving or should an advanced feature be added to disable it?  Or maybe it should only be disabled in "maximize" mode, which wouldn't require an advanced option?

**Comment by motfis** [comment]
I am sorry if i was not clear. This "bug" I mean is when we have something played in maximized window. So, as you mentioned : I think this click and drag should be disabled in maximized window (not full screen).

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/389

I think this change makes sense.  There is already logic to prevent dragging from the logo area in fullscreen.  This extends it to maximized windows as well.  Given that even an almost imperceptible drag moves the window and exits maximized mode, I think it's more intuitive to leave a maximized window alone unless they drag from the titlebar (a valid method in more recent windows versions for exiting maximized mode).

**Comment by clsid2** [comment]
Patch applied.
