### ISSUE TITLE
Windows resume play bug on Windows 10

### ISSUE THREAD

**Issue by MrMyth** [clsid2/mpc-hc#384]
There is the following bug:
Win 10 x64 player of the same bit, stable release. The melody is on pause. If you go to the OS notification center at the bottom of the screen at this time and clamp the LCM on the notification, the melody will be removed from the pause. Both BE and HC suffer from this. Is there a cure?

**Comment by clsid2** [comment]
It is the fault of Windows.

This should help:
MPC-HC Options > Player > Keys > uncheck "Global Media Keys"
