### ISSUE TITLE
madVR question (mpc-hc*.exe: unauthorized connection attempt!)

### ISSUE THREAD

**Issue by THEtomaso** [clsid2/mpc-hc#385]
After having installed, and set madVR as the default video renderer, MPC-HC will try to connect to `104.18.21.226` (Cloudflare), upon playing the first video file afterwards.
What the reason for this?

There's actually one report at Black Hat Directory, which reports this IP as a "Malicious bot":
`https://blackhat.directory/ip/104.18.21.226`
Not saying that this is the case, but it would be nice to know what's going on, regardlessly.

**Comment by clsid2** [comment]
You probably have enabled the option to automatically search for subtitles. Then it connects to OpenSubtitles server, with may use Cloudflare as a proxy. Cloudflare isn't malicious.

You can disable the option here:
MPC-HC options > Subtitles > Misc

**Comment by THEtomaso** [comment]
> You probably have enabled the option to automatically search for subtitles.

Nope.

**Comment by clsid2** [comment]
Or the automatic update check, which connects to Github.

Those are tho only two things it connects to the Internet for.

**Comment by THEtomaso** [comment]
> Or the automatic update check

No, I've got that option disabled too.
That's why I'm puzzled by this connection attempt.
I've just reproduced the issue on another computer too.

**Comment by clsid2** [comment]
https://ipinfo.io/104.18.21.226
Could be connection to Globalsign for verification of digital signature of a file. If so, that is done by madVR because my MPC-HC builds aren't digitally signed.

**Comment by THEtomaso** [comment]
> If so, that is done by madVR

I would expect such an verification attempt to be made by **madHcCtrl.exe** though, and not by **mpc-hc64.exe**, which is the case here.
It only occurs with the first video file being played, when madVR is used as the video renderer.
After having permanently allowed **madHcCtrl.exe** to run in Windows, the behaviour stops.
