### ISSUE TITLE
Subtitles fall out of sync when video playback speed is increased.

### ISSUE THREAD

**Issue by mkruer** [clsid2/mpc-hc#388]
Watching a video (mkv) at 1.2x speed, I noticed that the subtitles (srt) are still displaying at 1x making the subs fall out of sync 

Video: MPEG4 Video (H264) 1280x720 29.97fps [V: h264 high L3.1, yuv420p, 1280x720 [default]]
Audio: DD+ 48000Hz stereo 3072kbps [A: English [eng] (eac3, 48000 Hz, 2 channels) [default]]
Subtitle: UTF-8 [S: English [eng] (subrip)]
Subtitle: UTF-8 [S: SDH [eng] (subrip)]
Subtitle: UTF-8 [S: No subtitles]

Format                         : Matroska
Format version                 : Version 4
File size                      : 3.73 GiB
Duration                       : 1 h 28 min
Overall bit rate               : 6 061 kb/s
Encoded date                   : UTC 2020-04-16 01:01:48
Writing application            : mkvmerge v19.0.0 ('Brave Captain') 64-bit
Writing library                : libebml v1.3.5 + libmatroska v1.4.8
Cover                          : Yes
Attachments                    : small_cover.jpg / cover.jpg / cover_land.jpg / small_cover_land.jpg

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L3.1
Format settings                : CABAC / 4 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 4 frames
Codec ID                       : V_MPEG4/ISO/AVC
Duration                       : 1 h 28 min
Bit rate mode                  : Constant
Bit rate                       : 6 000 kb/s
Width                          : 1 280 pixels
Height                         : 720 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 29.970 (30000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.217
Stream size                    : 3.59 GiB (96%)
Default                        : Yes
Forced                         : No
Color range                    : Limited
Color primaries                : BT.709
Transfer characteristics       : BT.709
Matrix coefficients            : BT.709

Audio
ID                             : 2
Format                         : E-AC-3
Format/Info                    : Enhanced AC-3
Commercial name                : Dolby Digital Plus
Codec ID                       : A_EAC3
Duration                       : 1 h 28 min
Bit rate mode                  : Constant
Bit rate                       : 224 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Compression mode               : Lossy
Stream size                    : 141 MiB (4%)
Language                       : English
Service kind                   : Complete Main
Default                        : Yes
Forced                         : No

Text #1
ID                             : 3
Format                         : UTF-8
Codec ID                       : S_TEXT/UTF8
Codec ID/Info                  : UTF-8 Plain Text
Duration                       : 1 h 27 min
Bit rate                       : 77 b/s
Count of elements              : 1552
Stream size                    : 49.9 KiB (0%)
Language                       : English
Default                        : No
Forced                         : No

Text #2
ID                             : 4
Format                         : UTF-8
Codec ID                       : S_TEXT/UTF8
Codec ID/Info                  : UTF-8 Plain Text
Duration                       : 1 h 28 min
Bit rate                       : 80 b/s
Count of elements              : 1686
Stream size                    : 51.8 KiB (0%)
Title                          : SDH
Language                       : English
Default                        : No
Forced                         : No

**Comment by THEtomaso** [comment]
It has already been fixed:
https://github.com/clsid2/mpc-hc/issues/177/
