### ISSUE TITLE
MPC-HC still doesn't take screenshots at target resolution instead of source, resulting in screenshots with an incorrect aspect ratio.

### ISSUE THREAD

**Issue by Riotous** [clsid2/mpc-hc#39]
Here's the original ticket that documents this issue.  This is especially a problem when taking screenshots of DVDR sources like VOB files which get stretched out beyond the original aspect ratio when you take a screenshot. VLC and mpv do not have this behavior when taking screenshots of the same files and it's time MPC-HC also meets this standard. 

https://trac.mpc-hc.org/ticket/46

It might be too late to fix this at this point but now that this project is on github, perhaps somebody out there can finally submit a pull request that fixes this.

**Comment by clsid2** [comment]
Use Madvr as video renderer. That provides options to customize at which size the screenshot is made. For example 100% view size, or even at fullscreen size.

**Comment by Riotous** [comment]
@clsid2 That's a good workaround but hopefully somebody will fix this for people that just want MPC-HC to take proper screenshots out of the box.
