### ISSUE TITLE
Improve subtitle search

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#391]
1) The subtitle search on OpenSubtitles is done using file hash value by default. There are cases where this returns no results, but a manual search using filename has results that can even have exact filename matches. We should perhaps always search using filename if hash search has no results. Automatic download should then only be done with exact file name match.

2) Exclusion list for subtitle search. Add option to specify a comma-separated list of strings. If any of those strings is found in filename, then automatic search is skipped. Could be used to exclude files that are private or for which there are probably no subtitles anyway. Stuff like xxx content.

**Comment by adipose** [comment]
@clsid2 

I was looking at #2.  Is this perhaps already implemented?

`strAutoDownloadSubtitlesExclude`

![image](https://user-images.githubusercontent.com/3324395/89594539-f0d33b80-d806-11ea-9c50-db42f7d417db.png)
