### ISSUE TITLE
MPC-HC Android version

### ISSUE THREAD

**Issue by 564gvPAK7z9jZQx** [clsid2/mpc-hc#392]
Hello,

is it possible to create a MPC-HC Android version?

**Comment by adipose** [comment]
It is possible but unlikely as the interface is all written in MFC which targets the Windows desktop OS.  The whole UI would have to be rewritten.  But on top of that, many other parts of the Windows API are used for the audio/video support.

**Comment by clsid2** [comment]
MPC-HC is for Windows only. It is build on technologies that are only available on Windows: MFC/DirectX/DXVA/DirectShow/DirectSound/etc.

Supporting another OS would basically mean: write a whole new player from ground up. That is never going to happen. There are already plenty of players for Linux/Mac/Android/etc that use FFmpeg codecs.
