### ISSUE TITLE
Playing DVD directory un-maximises window

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#393]
If I start MPC-HC with the window maximised, and then open a directory containing a DVD backup, the window size is restored. The same occurs when right-clicking a folder in explorer and selecting 'Play with MPC-HC', using File... Open DVD, File... Open Directory, or File... Recent Files. It does not occur when opening a directory containing normal video files (eg *.mp4)

I can source a DVD device to test this if it would help?

**Comment by adipose** [comment]
I could not reproduce this one.

1. Open player on second screen
2. Play video
3. Fullscreen video and pause
4. Right-click dvd folder, play with MPC-HC
5. Plays in full screen

Also:

1. Open player on second screen
2. Play video
3. Maximize player
4. Right-click dvd folder, play with MPC-HC
5. Plays maximized

Can you upload your settings?  Also a video of all the steps would help.

**Comment by ghost** [comment]
Reproduced these steps. The first example, using full-screen, works fine. The second example, does not. The window starts out maximised as per the instructions (step 3), I right-click the folder, select "Play with MPC-HC" (step 4) and the MPC-HC window restores to its previous size.
If I resize the un-maximised window to take up the full screen, it will restore to that size - but it is clear that the issue still occurs as the maximise/restore button changes to the maximise button.

The behaviour is the same when using a single display (just skip step 1)

Another method to reproduce:

1. Start MPC-HC
2. Maximise
3. Exit MPC-HC
4. Start MPC-HC. Note that it retains its maximised state. Repeat steps 3 and 4 to your satisfaction.
5. Right-click DVD backup folder, select "Play with MPC-HC"
6. Note that window has restored to non-maximised state.
Alternately

Repeat steps 1-4 above
5. Right-click any non-DVD file, select "Play with MPC-HC"
6. Note that window has retained its maximised state.

Settings attached.

[mpc-hc-settings-github.zip](https://github.com/clsid2/mpc-hc/files/5108351/mpc-hc-settings-github.zip)

**Comment by adipose** [comment]
Using your settings, I still could not reproduce it.

In wonder if you have something third party (mouse related, maybe?) that is causing this.  For example double clicking can restore the player--not sure how this could happen but an idea.  Can you make this happen on a VM or other machine?

@clsid2 , the only thing that's weird behavior here is not being able to fullscreen without media.  The player can remember it's fullscreened when opening without media, but you can't set it manually.  Seems inconsistent.

**Comment by clsid2** [comment]
I was able to reproduce it.

1. Enable remember last window position & size
2. Maximize and close
3. Start player (should open maximized)
4. Drag video_ts folder onto the player

If I uncheck auto-zoom in the options, then player stays maximized.

Allowing fullscreen without media would be fine I guess. I am not sure if there is any good reason why this was disallowed.

**Comment by adipose** [comment]
Maybe because my screen is 1920x I didn't observe the zoom.

**Comment by clsid2** [comment]
I am also 1920x1200. But DVD is smaller res so auto-zoom 100% should give small window for you too?

**Comment by adipose** [comment]
Yeah you are right, should have been 480p.

I didn't check his settings but I would assume it had the restore setting set. I will check again.

**Comment by adipose** [comment]
So, I checked, and I have that setting enabled, but I still don't observe a restore when playing a DVD.  I'm using the settings uploaded by @xcasxcursex , so I am not sure why it doesn't happen to me.

**Comment by clsid2** [comment]
I was using pretty much default settings. On Windows 7. Maybe that is relevant.

**Comment by ghost** [comment]
Win10 1909 here FWIW.

**Comment by adipose** [comment]
So is the preferred behavior to not auto zoom if the player is already full screen?

Probably that can be implemented, though I am unclear why it doesn't pose a problem for me.

**Comment by clsid2** [comment]
Yes, probably better to not auto-zoom when window is in maximized state. I am talking about maximized, not fullscreen. I think you tried to reproduce it with fullscreen?

**Comment by adipose** [comment]
Genius...I was using fullscreen and not maximized. I'll test again.

I myself would never use it in maximized mode.  Just seems like a dollar short of fullscreen, but I guess there are reasons for it...

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/828

**Comment by ghost** [comment]
Fantastic, thanks mate!

Is there a CI build or something you'd like me to test?

Otherwise I'll get out of your way and look forward to the next release :)

**Comment by adipose** [comment]
No problem. If I do another test build later I can link it. This one is too small to bother just now.
