### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by parkercz** [clsid2/mpc-hc#395]
I have one issue as of late. When watching something in fullscreen and press keyboard shortcut to next file MPC HC sometime it is stuck at black screen. I cant close mpc hc. I can access taskbar or press ctrl+alt+del to get to Task manager but it is hidden under black screen. I can close all opened software but no mpc-hc. Only restart pc help. Using windows 10 , nvidia 1060. Installed madvr filter.

**Comment by clsid2** [comment]
This might be bug in the nvidia driver or in madVR.

No player response to pressing Esc, F11, or Alt+F4?

**Comment by parkercz** [comment]
No it not react to anything. I try Esc , F11 , Alt+4 , my keyboard shortcut to go off and on fullscreen. If i press ctrl+alt+del it get me to another screen where i can choose start task manager or shutdown/restart pc. I try it close from task manager but i cant see what i am doin becauese of black screen. Only thing i can see is taskbar (it is set to hide and when i press windows key it shows.) I try alt+tab to another application and i can see my opened application and i can close them except for mpc hc. I will try disable madvr filter for some time and report back.
