### ISSUE TITLE
Title and Author text is missing or cut off when playing CD Audio.

### ISSUE THREAD

**Issue by Khronikos** [clsid2/mpc-hc#396]
Hello, with the newest K-lite, and going back a while, this is a confirmed issue that needs to be fixed some day. Confirmed on forums by Admin. Said he will get to it when he has time.

**Comment by Aleksoid1978** [comment]
Upload .iso for testing.

**Comment by clsid2** [comment]
Not needed. I have been able to reproduce it.

**Comment by clsid2** [comment]
Fixed
