### ISSUE TITLE
Default audio renderer has a very low volume

### ISSUE THREAD

**Issue by wangqr** [clsid2/mpc-hc#397]
I'm using MPC-HC 1.9.2 on Windows 10. The audio is barely audible even if system volume and MPC-HC volume both set to 100. After messing around with the settings, I found that if I set `Playback -> Output -> Audio Renderer` to `Default WaveOut Device (00200000)`, the volume is slightly lower than the system included "Movies & TV" app, but usable. With the default choise `System Default`, MPC-HC has a very low volume.

**Comment by wangqr** [comment]
Not reliably reproducible.

**Comment by clsid2** [comment]
Click on the Windows volume icon during playback. Then click on Mixer, and it should show volume option for all active applications. There the volume is probably set lower than the system master volume (which is used as maximum).

Another way to fix it:
Codec Tweak Tool > Fixes > Reset Windows Audio Mixer volume settings
http://codecguide.com/download_other.htm#codectweaktool

**Comment by wangqr** [comment]
> Then click on Mixer, and it should show volume option for all active applications. There the volume is probably set lower than the system master volume (which is used as maximum).

It indeed is lower than other applications.

I found that if the `Audio Renderer` is set to `Default WaveOut Device`, then MPC-HC will set the per-application volume in Volume Mixer to the in-app volume value:
![img](https://user-images.githubusercontent.com/8182182/82128239-98e8e380-9787-11ea-9792-bb974afcc742.png)

But if the `Audio Renderer` is set to `System Default`, then they can be set independently. Somehow the per-application volume in Volume Mixer for MPC-HC is lowered, causing MPC-HC always have a low volume with `System Default` even if system-wide volume and in-app volume are both 100%. After I switched to WaveOut, set the volume to max, it returned to normal.

So the issue is that, MPC-HC should have a consistent behavior when changing in-app volume. Either it doesn't change Volume Mixer at all, or it always sync the in-app and Volume Mixer volume. In case making the behavior consistent is not achievable with different audio renderers, it should reset the Volume Mixer to max when changing audio renderer.

**Comment by clsid2** [comment]
System Default uses DirectSound audio interface, where each application has its own volume level. WaveOut uses master volume level.

This is not a bug in the player. Windows is responsible for this behavior.

**Comment by wangqr** [comment]
> Windows is responsible for this behavior.

Now I understand that this is Windows' behavior. Is it possible to reset the Volume Mixer to max when changing audio renderer (or upon MPC-HC start)? That will give less confusion to user. This is not an important feature though, because users won't change Audio Renderer frequently.

If MPC-HC has no plan changing this behavior, feel free to close this issue.
