### ISSUE TITLE
Unable to play any video after upgrading to Windows 10 Enterprise LTSC 2019.

### ISSUE THREAD

**Issue by zhangbao** [clsid2/mpc-hc#40]
![snap3](https://user-images.githubusercontent.com/91475/47255830-11eb6080-d4a9-11e8-95b6-bd4af2a91171.jpg)

Unable to play any video after upgrading to Windows 10 Enterprise LTSC 2019.

**Comment by clsid2** [comment]
EVR is missing from your system. You need to install the "Media Feature Pack" that Microsoft provides for "N" editions of Windows.

Or install an alternative video renderer like Madvr.
