### ISSUE TITLE
DVB Channels do not scroll automatically to show the active channel, when resolution change would hide it

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#403]
The window scroll position no longer is within the viewable area.  It should scroll to the selected channel.

**Comment by adipose** [comment]
@moonlightz, I entered an issue for this.

**Comment by moonlightz** [comment]
Great!

**Comment by moonlightz** [comment]
Like I wrote, maybe when the channels list changes it's height, listbox would be forced to show the new selected channel.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/408

Sadly, EnsureVisible doesn't exist for CListBox, so I had to implement it.
