### ISSUE TITLE
Menu entry for setting specific playback rates

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#409]
The current way of setting rate is not very flexible. So add a menu with a few useful values to choose from.

Menu > Play > Playback rate

Some suggested values:
25% 50% 80% 90% 100% 110% 120% 150% 200% 400%

It could also include target values 24fps and 25fps. Then rate is calculated based on framerate coming out of source filter. Example: 25 (target) / 23.976 (source) = 1.0427

**Comment by cat-os** [comment]
Everything looks good, but 80% and 150% are ideal for me if I choose some.

**Comment by awebeer256** [comment]
We currently have multipliers of 1/8, 1/4, 1/2, 1, 2, and 4. If it were up to me, I'd just add 3/4, 1.25, and 1.5 to that list. If someone wanted even more, I'd also add 1.75, 3, 6, and 8.

**Comment by adipose** [comment]
@clsid2 This could be closed.
