### ISSUE TITLE
Black Screen and not responding

### ISSUE THREAD

**Issue by donizetti94** [clsid2/mpc-hc#412]
If I leave a video paused for a certain period of time, the program screen goes black (not the computer screen)  and it doesn't respond anymore, I have to ** finish the task ** using the task manager, if I don't, the program won't reproduce or respond to any command on the program screen. Is this happening to anyone ?

**Comment by Dendraspis** [comment]
Today I had v1.9.2 paused for about 3½ hours and then watched to end - without issues.

What do you mean by "*certain period of time*"? 1 hour? 1 day?

Where is the video file located? Local or on a network drive?

**Comment by donizetti94** [comment]
> Today I had v1.9.2 paused for about 3½ hours and then watched to end - without issues.
> 
> What do you mean by "_certain period of time_"? 1 hour? 1 day?
> 
> Where is the video file located? Local or on a network drive?

The version I have is the v1.9.3. Answering the questions:

"What do you mean by "_certain period of time_"? 1 hour? 1 day?"

- Hummm that depends, usually it happens after I leave it paused for the time that I do some housework or other activity, so usually 1 hour, maybe more. I can´t say precisely because I never timed the issue, is something that bothers me but is not something urgent afterwall the problem freezes only the program and not the windows, to resolve the problem I just have to end the task, and play the file again, however it´s really bothersome when it happens.

"Where is the video file located? Local or on a network drive?"

- Local

**Comment by Dendraspis** [comment]
Hmm, I tried v1.9.3 now and it works without issues after 1½h of pause and resuming the movie from a network drive.
Maybe it has to do something with the settings, either MPC-HC or Windows.  🤔 

Looks like the Dev's have to take over..

**Comment by clsid2** [comment]
Video playback can break if Windows goes into sleep/hibernate mode.

If it occurs with a normal pause, then it is most likely Windows or your graphics driver at fault. It works fine for me, so there is nothing I can fix.
