### ISSUE TITLE
1.9.3 x64 does not open next file

### ISSUE THREAD

**Issue by Tsuchimikado** [clsid2/mpc-hc#414]
Windows 7 x64 MPC-HC 1.9.3 x64
after update it does not open next file in playlist or next file in folder
it just pauses at the end of file and do nothing
double clicking files in current playlist does nothing
dragging another file into player window only changes current playlist
reinstalling with default settings did not changed anything

only after manually closing current file it is possible to play next file

x86 version works fine

**Comment by Dendraspis** [comment]
Just for reference:
Tested it a minute ago and it works fine. The next file in playlist is played automatically and using shortcuts for next/previous files works, too. When there is only one file then this one is repeated. 🤔  

*MPC-HC v1.9.3 x64 on Windows 10*

**Comment by clsid2** [comment]
I am also not able to reproduce this problem.

**Comment by clsid2** [comment]
Does 1.9.2 x64 work ok?

**Comment by Tsuchimikado** [comment]
installed 1.9.2 x64 now and it works ok
issue appeared in 1.9.3 x64

looks like something wrong with internal LAV Video Filter or MPC-HC's interface language
tried adding locally installed LAV Video Decoder 0.74.1 into External Filters as preferred filter and playing next file worked ok
BUT when I changed interface language to english and **after restarting** MPC-HC playing next file stopped working
more mysterious fact is that when interface language changed to japanese playing next file works even if external LAV Video Decoder is unchecked and not used (removing filter makes playing next file impossible again)
![2020-05-27_08h37_15](https://user-images.githubusercontent.com/51411871/82961137-69dc3880-9ff7-11ea-8cf7-02bfcf2b9f41.png)
![2020-05-27_08h41_53](https://user-images.githubusercontent.com/51411871/82961161-7c567200-9ff7-11ea-8325-2fcff1c3be67.png)

**Comment by jewshawn2** [comment]
> Windows 7 x64 MPC-HC 1.9.3 x64
> after update it does not open next file in playlist or next file in folder
> it just pauses at the end of file and do nothing
> double clicking files in current playlist does nothing
> dragging another file into player window only changes current playlist
> reinstalling with default settings did not changed anything
> 
> only after manually closing current file it is possible to play next file
> 


I am having the same problem but I'm on Windows 8.1 x64 MPC-HC 1.9.3 x64

Was working fine 1.9.2 x64

**Comment by clsid2** [comment]
Try these versions:
https://www.sendspace.com/file/d6hlju

**Comment by Tsuchimikado** [comment]
all three versions are ok
I can jump to previous/next file in playlist

**Comment by clsid2** [comment]
I think I have found the cause (uninitialized variable). Try this build:
https://www.sendspace.com/file/a8uq2k

**Comment by Tsuchimikado** [comment]
This build solved the issue. Thank you
