### ISSUE TITLE
Subtitles search can't find OpenSubtitles sub

### ISSUE THREAD

**Issue by trono6** [clsid2/mpc-hc#415]
I tried to search subtitles on a lot of file on my pc (pressing D on my keyboard) but I have never OpenSubtitles sub among the results (if i choose it as the only provider i don't receive any result).
With other media player (MPC-BE for examples) I don't have these problems, so I don't think it's a provider issue.

I can't say if it is only with the last release since i came directly from last official MPC-HC release (1.7.13), with a clean installation obviously

**Comment by clsid2** [comment]
Subtitle search/download using OpenSubtitles now requires a login. You can create a free account on opensubtitles.org website. After that, you can configure it here: MPC-HC options > Subtitles > Misc > Right-click on OpenSubtitles > Setup
