### ISSUE TITLE
EVR-CP rotate bug with DAR

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#416]
Playing a file with EVR-CP that has a different aspect ratio, and rotating it clips off some of the video.

This doesn't appear to be a regression, as it's been there for some time.

![image](https://user-images.githubusercontent.com/3324395/82925152-35eb0f80-9f32-11ea-8a42-f731b9d1df01.png)

After Alt+Num3:

![image](https://user-images.githubusercontent.com/3324395/82925183-3edbe100-9f32-11ea-9067-75d6e5fc5796.png)

**Comment by clsid2** [comment]
When rotating manually, window size does not change. In case of automatic rotation (due to file metadata) the width/height are swapped. Doing that in manual case (if module 90 rotation) would be a useful improvement as well.

**Comment by adipose** [comment]
madVR and MPCVR are handling it fine, in my latest code.  They behave differently.  One resizes the window and the other just makes it taller, but both rotate correctly.  So this is likely in the setvideoangle code.

We can leave this here as a reminder.

**Comment by adipose** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/3324395/39e54823-e12f-4721-86e8-845ad9f44c52)

As of today, EVR-CP seems to have different behavior.  It does not resize the window, but it does not clip it off, either.

MPCVR seems to work the same as EVR-CP.  MADVR still has the funny resizing.

I think this and #911 can be closed, then?
