### ISSUE TITLE
[request] release file lock when stopped

### ISSUE THREAD

**Issue by wadawada** [clsid2/mpc-hc#418]
I can't delete a media file even if I stopped the playback. I'll have to close mpc or play another file in order to delete the file.
Can you release the file lock when the file is stopped playing in future versions? It is possible to delete a media file when it's stopped in other media players (eg vlc)
Thanks.

**Comment by clsid2** [comment]
You can press Ctrl+C to close the file. Stopping playback does not close the filter graph.
