### ISSUE TITLE
Incorrect subtitle symbols for Serbian Cyrillic

### ISSUE THREAD

**Issue by K0stov** [clsid2/mpc-hc#419]
The Cyrillic alphabet has some signs that vary across languages, mostly in the case of cursive/italic forms (more details about this [here](https://en.wikipedia.org/wiki/Serbian_Cyrillic_alphabet?oldformat=true#Differences_from_other_Cyrillic_alphabets)). Here’s a chart:

![Image](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Cyrillic_cursive.png/283px-Cyrillic_cursive.png)

In MPC-HC, while using the [Noto](https://www.google.com/get/noto/) font (which supports several versions of these letters depending on the system language and/or language codes), these letters are always displayed the Russian way, even with the system language set to Serbian. Here’s an example, where letters in cyan represent the way characters should appear while ones in white show them how they appear in MPC-HC:

![Img](http://u.cubeupload.com/SashaRed/mpchcsubs.png)

Is there any way to force them to appear as Serbian, or will MPC-HC require special support for it?

**Comment by clsid2** [comment]
Options > Subtitles > Default Style
The dropdown below the font is for character encoding.

**Comment by K0stov** [comment]
I’ve experimented with that, and I don’t believe encoding has anything to do with it. This issue is about different variations of the same characters, but _based on different languages_.

I’ll try to make this clearer. On the image below, on the left, you see characters as they appear in MPC-HC (Russian characters). On the right, you see characters as they should appear in Serbian:

![pic](https://user-images.githubusercontent.com/26684396/83034430-88165880-a038-11ea-99d2-0f4b6f2df111.png)

Now, see the video screenshot again. The white text is how it appears in MPC-HC: the Cyrillic characters themselves show up just fine, but variations across different languages don’t (see the colored chart above—they appear as Russian instead of Serbian characters). Even setting the name of the subtitle track to “sr-rs” at the end does nothing.

Under the condition that the font itself supports it, is there any way to force the letters to appear as their Serbian counterparts?

**Comment by clsid2** [comment]
The encoding option is that only thing affects character set of the font. Default value uses the character set that matches current system locale.

There is not anything I can do to help you with this. Maybe they can help you here:
https://github.com/googlefonts/noto-fonts/issues

**Comment by K0stov** [comment]
The issue’s not specific to Noto. Several other fonts have support for both character sets (Segoe UI, Calibri…), which successfully change in other applications depending on the system language and/or application language.

I do believe this matter is solvable. Something like this is easy to change in, say, HTML: you can use the `<html lang=` parameter and change its value to _sr-rs_, at which point all Cyrillic italic glyphs on the page will appear as Serbian. Seeing that MPC-HC already supports various character encodings for subtitles, I’m guessing something similar can be implemented in order to change character **glyphs** between different languages?

**Comment by clsid2** [comment]
There is no language parameter in the Windows font APIs that MPC-HC uses.

@adipose, do you have any idea?

**Comment by adipose** [comment]
Cursory research makes me think this capability is limited to direct2d and excluded from GDI and earlier windows APIs, which are used pretty frequently in the custom draw code (not just dark theme but other elements of mpc-hc).

Possibly it could be swapped out for direct2d.  I've thought about it before, but it seems a bit ugly.

@Nemrtvi, you gave subtitles as an example of the problem.  What about the UI--is that less of an issue for you?

**Comment by adipose** [comment]
I've done further testing with this, after researching.  It seems libass added support for a language script info property in 0.10.0.

Here is a test done using a simple ssa file, with "Language: ru":

![image](https://user-images.githubusercontent.com/3324395/83994539-95222a00-a90b-11ea-91f3-c4d872027bec.png)

Here is the exact same file with "Language: sr":

![image](https://user-images.githubusercontent.com/3324395/83994509-7f146980-a90b-11ea-9afb-1d4a9707a614.png)

This is done using the libass fork of mpc-hc which is still experimental.  However, after this test I'm sure that both SRT and SSA/ASS subs can work properly with Serbian cyrillic (some additional work required to have a language option for SRT).

The built-in renderer uses GDI which I don't believe supports the language property in Opentype.  It likely never will.  But if we replace it with libass, your feature can work.

Here's the subtitle test file I made:

```text
[Script Info]
; This is a Sub Station Alpha v4 script.
; For Sub Station Alpha info and downloads,
; go to http://www.eswat.demon.co.uk/
Title: Neon Genesis Evangelion - Episode 26 (neutral Spanish)
Original Script: RoRo
Script Updated By: version 2.8.01
ScriptType: v4.00
Collisions: Normal
PlayResY: 600
PlayDepth: 0
Timer: 100,0000
Language: ru
 
[V4 Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, TertiaryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding
Style: DefaultVCD, Calibri,28,11861244,11861244,11861244,-2147483640,-1,0,1,1,2,2,30,30,30,0,0
 
[Events]
Format: Marked, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: Marked=0,0:00:01.18,0:00:06.85,DefaultVCD, NTP,0000,0000,0000,,{\pos(400,570)}бгдпт бгдпт бгдпт бгдпт бгдпт бгдпт
```

**Comment by K0stov** [comment]
@adipose, nice work! Where can I find this fork?

> @Nemrtvi, you gave subtitles as an example of the problem. What about the UI--is that less of an issue for you?

Yes, the UI is far less of an issue. The main interface mostly consists of non-italic characters, and even while there is a difference in the case of the lowercase letter б, Serbian users can read it just fine. Italics are the elephant in this room.

**Comment by clsid2** [comment]
The libass branch is still a work in progress. It is not yet available.

**Comment by adipose** [comment]
@Nemrtvi 
I made a test build you can try out.  This is an experimental branch, but you can see how it works for you.

https://mega.nz/file/FJoQQYDY#RJoFWI4m4fB86zpi9W9_9_Tmf5tv8doNkHfm9y1O80E

**Comment by K0stov** [comment]
Interesting. Your subtitle file above works fine, but mine always has the Russian symbols (whereas, for example, in VLC, they render in Serbian as expected):

```
[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1280
PlayResY: 640
Language: sr

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Noto Sans Disp SemBd,45,&H00FFFFFF,&H000000FF,&H20000000,&H00000000,0,0,0,0,100,100,0,0,3,0.5,0,1,400,10,20,1
Style: Export,Noto Sans Disp SemBd,18,&H00FFFFFF,&H000000FF,&H20000000,&H00000000,0,0,0,0,100,100,0,0,3,0.5,0,1,120,10,30,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:14.50,0:00:17.50,Default,,0,0,0,,{\i1}Чудна је била 1647. година,{\i0}
Dialogue: 0,0:00:18.40,0:00:20.70,Default,,0,0,0,,{\i1}јер различити су знаци\Nна небу и земљи{\i1}
Dialogue: 0,0:00:21.35,0:00:24.75,Default,,0,0,0,,{\i1}навештали необичне догађаје\Nи погибли.{\i0}
Dialogue: 0,0:00:25.75,0:00:30.30,Default,,0,0,0,,{\i1}Лети је била помрчина сунца,\Nзатим се појавила на небу репатица,{\i0}
Dialogue: 0,0:00:30.85,0:00:32.80,Default,,0,0,0,,{\i1}а годишња су се доба помешала тако{\i0}
Dialogue: 0,0:00:32.90,0:00:35.00,Default,,0,0,0,,{\i1}да то ни најстарији\Nнису памтили.{\i0}
Dialogue: 0,0:00:36.45,0:00:41.00,Default,,0,0,0,,{\i1}Сви су у Русији мисли и погледе\Nуправљали према Дивљем пољу,{\i0}
Dialogue: 0,0:00:41.55,0:00:47.50,Default,,0,0,0,,{\i1}које се протезало од обале Дњепра\Nсве до татарског Крима,{\i0}
Dialogue: 0,0:00:47.95,0:00:50.45,Default,,0,0,0,,{\i1}откуд се могла појавити опасност.{\i0}
```

**Comment by adipose** [comment]
Right now it only works when using libass renderer.  You may need to check the box.

Also the opentype language will set the language hint used in SRT subtitles.

![image](https://user-images.githubusercontent.com/3324395/85035481-15c8fd80-b138-11ea-811d-3ab7dec5550d.png)

**Comment by K0stov** [comment]
Nice to see it works with SRT. When used with libass, though, with or without "Language: sr" in the file itself, it still displays as Russian.

**Comment by adipose** [comment]
Try changing the style name from Default to anything else.  There appears to be some bug where default is not overridden when using SSA.

**Comment by K0stov** [comment]
The results are still not as expected. Here's my file.

```
[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1280
PlayResY: 640
Language: sr

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Defic,Noto Sans Disp SemBd,45,&H00FFFFFF,&H000000FF,&H20000000,&H00000000,0,0,0,0,100,100,0,0,3,0.5,0,1,400,10,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:14.50,0:00:17.50,Defic,,0,0,0,,{\i1}Чудна је била 1647. година,{\i0}
Dialogue: 0,0:00:18.40,0:00:20.70,Defic,,0,0,0,,{\i1}јер различити су знаци\Nна небу и земљи{\i1}
Dialogue: 0,0:00:21.35,0:00:24.75,Defic,,0,0,0,,{\i1}навештали необичне догађаје\Nи погибли.{\i0}
Dialogue: 0,0:00:25.75,0:00:30.30,Defic,,0,0,0,,{\i1}Лети је била помрчина сунца,\Nзатим се појавила на небу репатица,{\i0}
Dialogue: 0,0:00:30.85,0:00:32.80,Defic,,0,0,0,,{\i1}а годишња су се доба помешала тако{\i0}
Dialogue: 0,0:00:32.90,0:00:35.00,Defic,,0,0,0,,{\i1}да то ни најстарији\Nнису памтили.{\i0}
Dialogue: 0,0:00:36.45,0:00:41.00,Defic,,0,0,0,,{\i1}Сви су у Русији мисли и погледе\Nуправљали према Дивљем пољу,{\i0}
Dialogue: 0,0:00:41.55,0:00:47.50,Defic,,0,0,0,,{\i1}које се протезало од обале Дњепра\Nсве до татарског Крима,{\i0}
Dialogue: 0,0:00:47.95,0:00:50.45,Defic,,0,0,0,,{\i1}откуд се могла појавити опасност.{\i0}
```

**Comment by adipose** [comment]
I had to change your file a bit, but see if my results look better than yours.  In particular, I used Calibri as it's a newer Microsoft font known to support opentype languages.  I also renamed the default style per my earlier comment.

![image](https://user-images.githubusercontent.com/3324395/85142778-b59c8f00-b1fd-11ea-85b2-3c8ab494c29e.png)

**Comment by adipose** [comment]
I fixed an issue with the default style.  Maybe it fixes the other issue for you, too.

https://mega.nz/file/EZZzACQT#vpfeyUPNbTqIz67WpSNCXzL8ZUW3F45y7ketuJ3vn50

**Comment by K0stov** [comment]
Everything works splendidly now. Great job.

**Comment by adipose** [comment]
Great, thank you. Since this issue is closed I won't be returning to this thread again, but for now you can use this test build.  If you find issues you can report them as a problem with the libass fork.

**Comment by K0stov** [comment]
@adipose How's merging libass into the main project coming along?

**Comment by clsid2** [comment]
It does not yet work good enough to get used.

**Comment by Susexe** [comment]
Did anything change in the meantime? Are there any newer libass builds with bugs fixed?

**Comment by K0stov** [comment]
@clsid2 Any update? I'm just as curious as Susexe.

**Comment by clsid2** [comment]
No updates. No changes. And I do not have any plans to work on this either in coming months.

**Comment by adipose** [comment]
I have not taken a look at this since my prior update.  At that time, it was working well enough to show subtitles in my samples, but some things may have broken since then.  I'm pretty busy at the moment but I'll get back to it eventually.

**Comment by clsid2** [comment]
Improvements can probably be ported from:
https://github.com/Masaiki/xy-VSFilter

**Comment by adipose** [comment]
New test builds here: https://github.com/clsid2/mpc-hc/pull/2163
