### ISSUE TITLE
Remember last window positions of previously opened instances

### ISSUE THREAD

**Issue by iG8R** [clsid2/mpc-hc#42]
Hi.
Is it possible to remember last window positions of previously opened instances of MPC-HC?
Very often it needs to open several windows in their certain positions and it's very inconvenient to rearrange them every time.

**Comment by clsid2** [comment]
Make multiple copies of MPC-HC and enable the option to store settings in INI file. Then each copy has its own settings.

**Comment by iG8R** [comment]
I already do it. But it is very inconvenient due to Windows can associate any type of video files only with one copy and every time select from the list of 8 copies of MPC-HC which have absolutely identical names - it's quite a work.

**Comment by clsid2** [comment]
You can add entries to Explorer context menu:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\mpc1]
@="MPC-HC 1"

[HKEY_CLASSES_ROOT\*\shell\mpc1\Command]
@="\"C:\\mpc1\\mpc-hc64.exe\" \"%1\""

[HKEY_CLASSES_ROOT\*\shell\mpc2]
@="MPC-HC 2"

[HKEY_CLASSES_ROOT\*\shell\mpc2\Command]
@="\"C:\\mpc2\\mpc-hc64.exe\" \"%1\""
```

**Comment by iG8R** [comment]
Yes, it pretty much solves some problems, but it still requires:
Right Click - > Open with -> um... what copy of MPC-HC do I need to open?... lets see - 2 visible, Ok, so it would be 3rd, Oh! stop! maybe I have another copy which is minimized? lets see... Task Bar is autohided... (Pressing Win-key or moving mouse down) Exactly! Two copies are minimized -> so, it would be 5th copy! Hooray!

Or, with native support in MPC-HC:
Double Left-click (that's all).
