### ISSUE TITLE
Audio Exclusive mode not engaging

### ISSUE THREAD

**Issue by BreakPoints** [clsid2/mpc-hc#423]
When checking the "Exclusive" checkbox under Audio Renderer, audio sources outside of MPC-HC are still mixed and outputted by Windows. I have an external DAC which has an indicator light for different input sample frequencies and should change to indicate it is being sent 48KHz when in exclusive mode (when watching videos with 48KHz sound, of course) but it does not. Selecting "System Default" or my specific output device does not fix the issue.

I am on Windows 10 1909 and am running MPC-HC 1.9.3

**Comment by clsid2** [comment]
Exclusive mode might be disabled here:
Windows Control Panel > Sound > Speakers > Properties > Advanced

**Comment by BreakPoints** [comment]
> Exclusive mode might be disabled here:
> Windows Control Panel > Sound > Speakers > Properties > Advanced

It's not disabled, I use exclusive mode with my music software and it works fine there. Double checked to be sure and it's enabled along with give priority

**Comment by Karma-Tron** [comment]
Exclusive mode doesn't work with me either. Exclusive mode is enabled in the Windows sound options and it does work with Foobar2000 and Potplayer.

**Comment by clsid2** [comment]
Make sure that the internal audio renderer is selected here:
Options > Playback > Output > Audio Renderer

**Comment by BreakPoints** [comment]
Ah, only the internal audio renderer supports exclusive mode.

After swapping to the internal audio renderer, exclusive mode does trigger but it does not match the sample rate to the source file. Is this a bug or was enforcing the output sample rate never added to the internal audio renderer?

**Comment by clsid2** [comment]
Afaik it only resamples if the driver does not support the original sample rate.

**Comment by BreakPoints** [comment]
> Afaik it only resamples if the driver does not support the original sample rate.

My driver does support the files sample rate but it does not switch to that sample rate. For example 44.1Khz. In exclusive mode I've not seen my DAC swap sample rate once no matter what file I throw at it.

Should I open a separate issue?

**Comment by clsid2** [comment]
You can open another issue.
