### ISSUE TITLE
Can't move window when window is maximized

### ISSUE THREAD

**Issue by GundolfEngelbert** [clsid2/mpc-hc#427]
Hi,
moving the mpc window isn't possible by clicking in the playback part, it only works by using the top bar. This only happens in maximized windowed mode and it's only in 1.9.3, 1.9.2 is working fine.

**Comment by clsid2** [comment]
This was an intentional change.

**Comment by GundolfEngelbert** [comment]
Ah okay,
thanks for clarifying. Could there be an option to activate/deactivate the behaviour? I always liked to move the window like this. It's one of the big reasons I'm using MPC.

**Comment by adipose** [comment]
The reason for the change is even a miniscule drag unmaximizes the window in windows 10. It could be an advanced option.

**Comment by clsid2** [comment]
Or perhaps require a certain minimum amount of drag distance when maximized. Small distance -> simply ignore.
@GundolfEngelbert, I assume you to want to drag window from one screen to another?

**Comment by adipose** [comment]
That might work. It might be tricky as the drag event is either trapped or passed on to windows. Not sure if you can pass it on mid way, but we could trap it until past the threshold and then treat it normally.

**Comment by GundolfEngelbert** [comment]
@clsid2 Yes, exactly, on a multiple monitor setup it was always very comfortable to just drag the window around and not think about the mouse position (as it is/was the only player with this behaviour). And I never accidentally dragged the window so that it became smaller, was it a huge problem so that it required a fix?

A advanced option would be, at least for me, the best solution for this problem.

**Comment by clsid2** [comment]
The drag distance workaround would also make it work again for you, without the need for a new option. It would only ignore short accidental drags.

**Comment by motfis** [comment]
> 
> 
> The reason for the change is even a miniscule drag unmaximizes the window in windows 10. It could be an advanced option.

First, Thanks for implementing the change in the current version. In my case, I use touch screen device, and the unmaximize window by accidentally touch the player was very annoying. I think either drag distance (maybe not too short)/advanced options is good.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/435

This will start dragging after 30 pixels.  If dragging screen to screen you'd hardly notice it, I think.
