### ISSUE TITLE
Fix PGS subtitle aspect ratio

### ISSUE THREAD

**Issue by bpaczkowski** [clsid2/mpc-hc#43]
This only happens when using Internal Subtitle Renderer, madVR and PGS subtitles AFAIK. When the video doesn't fill the whole screen and madVR is configured to move the subtitles into active video area, the subtitles appear squished horizontally.

Move subtitles into active video area OFF:
![mpc-hc64_2018-11-06_19-55-47](https://user-images.githubusercontent.com/1371800/48086861-25632f00-e1fe-11e8-8540-b7beae2b27aa.png)
Move subtitles into active video area ON:
![mpc-hc64_2018-11-06_19-56-01](https://user-images.githubusercontent.com/1371800/48086862-25fbc580-e1fe-11e8-8460-351e4af92bc0.png)

Thanks for keeping this project alive!

**Comment by clsid2** [comment]
Madvr should be scaling them in that case.

**Comment by bpaczkowski** [comment]
madVR works fine with other subtitle renderers, eg. XySubFilter. Is it really the fault of madVR?

**Comment by clsid2** [comment]
Yes. It had bugs with XySubFilter in the past as well.

**Comment by bpaczkowski** [comment]
Very well, I will report it there. Thank you.
