### ISSUE TITLE
"Screenshots are now taken at display aspect ratio" doesn't work

### ISSUE THREAD

**Issue by lkintact** [clsid2/mpc-hc#431]
The "Screenshots are now taken at display aspect ratio" feature announced on https://github.com/clsid2/mpc-hc/releases/tag/1.9.3 doesn't work for me for some reason. To make sure it doesn't have to do with the settings I uninstalled MPC-HC with choosing "Yes" on "Do you also want to delete MPC-HC settings?" and reinstalled it. Then:
1. Opened a video, it started playing
2. Pressed Alt+i, saved the snapshot
3. Changed the "View > Video Frame > Aspect Ratio" value from "Default" to "4:3"; the frame dimensions changed correspondingly
4. Repeated step 2
5. Repeated step 3 to change the value to "235:100"
6. Repeated step 2 again.

All the three *.jpg images MPC-HC created had the same dimensions.
I tried it with two video streams, "VP90 1280x720 30fps [V: English [eng] (vp9 profile 0, yuv420p, 1280x720)" and "MPEG4 Video (H264) 1280x720 29.97fps 1041kbps [V: h264 main L3.1, yuv420p, 1280x720, 1041 kb/s]" (info taken from "File > Properties > Details") and three rendererers (View > Options > Playback > Output > DirectShow Video): the default "Enhanced Video Renderer (custom presenter)", "Sync Renderer" and "Video Mixing Renderer 9 (renderless)".

MPC-HC: 1.9.3 (https://github.com/clsid2/mpc-hc/releases/download/1.9.3/MPC-HC.1.9.3.x86.exe)
Windows: 10 Home 1803.

**Comment by clsid2** [comment]
The fix mentioned is to make screenshot at Display Aspect Ratio, which corresponds to the "Default" choice in that menu. Previously it would do it at SAR, which isn't what people wanted.

Using the overridden AR would be a feature request.
@adipose

**Comment by adipose** [comment]
Agreed. DAR used is the DAR from the video, not the override. That DAR is assumed to be "correct."

**Comment by lkintact** [comment]
I see, thank you guys for explaining this.

**Comment by clsid2** [comment]
Do you actually have a real need for screenshots at custom AR? Otherwise I will close this.

**Comment by lkintact** [comment]
I think it would be a useful feature to have - I had several situations with videos encoded with some old codecs (mostly those were *.avi files) that MPC-HC detected aspect ratio incorrectly for, so getting snapshots with correct dimensions additionally required processing in an image editor.

**Comment by nobananasforyou** [comment]
It is useful for anamorphic encodes. This feature has been implemented in MPC-BE.

**Comment by clsid2** [comment]
Anamorphic encodes should normally have a DAR specified in their container that makes it display correctly. If not, your files are actually kind of broken.
In the past MPC-HC would take screenshots at the encoded AR of the video, but that was fixed recently to use DAR instead.

**Comment by nobananasforyou** [comment]
MPC-BE has this really useful feature called "Keep aspect ratio" that you can toggle on/off between dar and encoded ar and take screenshots freely. MPC-HC doesn't allow you to take screenshots at DAR but only at the original resolution. For example, 720x480 16:9 (MPC-HC, MPC-BE) > 853x480 (MPC-HC nope, MPC-BE yes).

![](https://i.imgur.com/Qi9GoFm.png)

**Comment by clsid2** [comment]
720x480 isn't 16:9, 853x480 is.

MPC-HC now takes screenshots at DAR (853x480 in your example). For what purpose do you need screenshot at encoded size?

**Comment by nobananasforyou** [comment]
1. 720x480 isn't 16:9, 853x480 is <- it's dar for the anime source I have.  Screenshots taken at 720x480 look squashed compared to 853x480.
2. MPC-HC now takes screenshots at DAR (853x480 in your example) <- Great. The latest build fixes this issue. Thank you!

Here's a comparison:
https://slow.pics/c/nmGH2Cpk

**Comment by butterw** [comment]
Windows can be used to take WYSIWYG output screenshots and it works will all players.
https://forum.doom9.org/showthread.php?p=1931990#post1931990
