### ISSUE TITLE
Internal chapter menu bug

### ISSUE THREAD

**Issue by hubblec4** [clsid2/mpc-hc#433]
Hi clsid

I found a bug in the internal chapter menu.
In LAV-Splitter menu (tray-icon) it shows all chapters correctly.
![LAV](https://user-images.githubusercontent.com/25957077/83634163-5e15e680-a5a2-11ea-89b3-12bd62811878.png)

Here is the internal chapter menu, and you see, chapter 1 and 3 are swapped. In the first episode occurs chapter 1 twice and in the last episode is chapter 1 missing)
![MPC-HC 1](https://user-images.githubusercontent.com/25957077/83634310-99181a00-a5a2-11ea-9457-cb066eec9dcd.png)

And when I start the menu-mkv outside of the folder the chapters are totally mixed and placed wrong to the episodes. But in LAV-Splitter is all correct.
![MPC-HC 2](https://user-images.githubusercontent.com/25957077/83634402-cb297c00-a5a2-11ea-97fb-d393c814fb9b.png)

Here the main menu mkv
[S03E00 - main-menu.zip](https://github.com/clsid2/mpc-hc/files/4723101/S03E00.-.main-menu.zip)

**Comment by Syst3mSh0ck** [comment]
What version of Windows are you using?

**Comment by hubblec4** [comment]
Windows7 Pro 64bit

**Comment by clsid2** [comment]
MPC-HC is sorting the list based on the start time. I can't just change that without breaking stuff. The code is not compatible with videos that contain multiple editions.

**Comment by adipose** [comment]
@clsid2 curious what would break if it weren't sorted by time.

What if there were two menus, one by time and one by sequence?  Seems kind of ugly but it would solve this issue.

**Comment by clsid2** [comment]
For example the code that marks the active title in the menu needs a sorted list to find the correct one. That could of course be changed to a less efficient search of unsorted list. But all uses of the chapter list need to be checked to avoid breaking anything. It was never designed for a multi-file situation.

**Comment by clsid2** [comment]
Fixed

**Comment by hubblec4** [comment]
cool :-)
