### ISSUE TITLE
MIT Open Courseware video does not play in mpc-hc

### ISSUE THREAD

**Issue by rzumer** [clsid2/mpc-hc#434]
Sample: http://www.archive.org/download/MIT6.002S07/mit-6.002-lec2-09sep2003-220k.mp4

Playback works in mpv, but not in mpc-hc 1.9.3.

**Comment by clsid2** [comment]
Menu > Play > Video track > select first one

The embedded MJPEG thumbnail is mistakenly detected as a video track and being selected by default.

**Comment by clsid2** [comment]
@nevcairiel

**Comment by clsid2** [comment]
This has been fixed in LAV Filters. That fix will be included in next release of MPC-HC.
