### ISSUE TITLE
Can't switch to a different media file on v1.9.3

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [clsid2/mpc-hc#436]
I can't skip files (either in a playlist or in a folder) from GUI, with keyboard shortcuts, or with Mouse4/Mouse5 on 1.9.3. The buttons in GUI appear to be active, but they don't do anything. I can't play next/previous file in a playlist by selecting it manually either (although the file is being highlighted in red).
I also can't open any media files from Windows Explorer while another file is playing in MPC-HC - it just keeps playing the same file until I close it.
This happens both after updating to 1.9.3 from a previous version, or when installing 1.9.3 after uninstalling previous version along along with its settings.
The issue immediately disappears when I roll back to 1.9.2 or earlier.
Windows 8.1 x64

**Comment by clsid2** [comment]
This is already fixed for next release.

**Comment by nbmrjuhneibkr** [comment]
Oh, I see it now. Originally I only used the word "skip" when looking for a similar issue, and couldn't find it.
Still, it's weird that v.1.9.3 wasn't pulled or replaced with a hotfix after such a major issue was found.

**Comment by adipose** [comment]
Looks like I broke it when fixing the error dialog problem.  @clsid2, should a 1.9.3.1 be built?

**Comment by clsid2** [comment]
I might make a new build this weekend or next week.

**Comment by clsid2** [comment]
1.9.4 is available
