### ISSUE TITLE
Can fix "Show windows side by side" in minimal presets?

### ISSUE THREAD

**Issue by ShareFix** [clsid2/mpc-hc#437]
Hi :)
1. First open mpc-hc and click View > Presets > Minimal
2. Now right click on the windows 7 down bar and select "show windows side by side" or "Show windows stacked" or "Cascade mode". 
![Show Windows Side by Side](https://user-images.githubusercontent.com/66454186/83834101-cf15e500-a6ed-11ea-96b1-ca14214f636d.png)

**Not want work with minimal presets**, suggestion is to make this work. it's possible please?

I use 
Windows 7 32 bits. 
Mpc-hc v1.9.3 and v1.7.13 32-bit

**Comment by clsid2** [comment]
That function only works when the window has borders. We can't fix that.

**Comment by adipose** [comment]
Not possible.  Windows performs this function but ignores the non-bordered windows.
