### ISSUE TITLE
CoverArt improvements: false positive matches

### ISSUE THREAD

**Issue by Michamel** [clsid2/mpc-hc#438]
Hi there,

Since version 1.8.5 with 'CoverArt improvements. Prefer image with same filename. Reduced chance of false positive matches.' the MPC-HC show me wrong JPGs while I play my music.
If I start playing an album, which contains JPG files named...

Artist - Album - Back.jpg
Artist - Album - Front.jpg

...then I get following situation:

[http://www.michamel.eu/bilder/mphc_hc.jpg](url)

MPC-HC v1.8.4 and lower: JPGs with ...Front.jpg will be loaded
MPC-HC v1.8.5 and higher: the first JPGs in the albums folder will be loaded

What is the technical back ground?
Thx!
Michael

**Comment by clsid2** [comment]
If you use "front.jpg" then it should load fine with newer versions.

The 'fix' in 1.8.5 was to ignore long filenames that contain the substrings "front"/"cover"/"folder", as those could be false positives when playing music from a non-album folder.

I will see if I can improve it to allow your naming scheme.

**Comment by clsid2** [comment]
Try with 1.9.4

**Comment by Michamel** [comment]
Perfect!
It works.
Many Thx. Michael
