### ISSUE TITLE
More resizers for EVR (CP)

### ISSUE THREAD

**Issue by voodoo84** [clsid2/mpc-hc#439]
Any chance to implement additional resizers for EVR Custom Presenter?
At least Lancosz3, which is available in MPC-BE, madVR etc.

This way, there won't be a need to install aditional renderers or switch players when better resizer is needed.

**Comment by clsid2** [comment]
No. I recommend using madVR or MPCVR, as those also offer HDR support.

**Comment by clsid2** [comment]
But if someone else implements it, I will gladly accept patch.

**Comment by voodoo84** [comment]
I've located the place where the resizing choice applies (`DX9RenderingEngine.cpp`, methods `TextureResizeBilinear()`, `TextureResizeBicubic1pass()` etc), but the resizing is done via actual DirectX API calls instead of shader snippets. There will also be work on the GUI side because DX9 resizing options are hard-coded in the dialog and not load dynamically (e.g. from a list of files)...

So I guess I'll switch to MPCVR, it's not bloated as madVR and offers me just what I need, thanks for the suggestion!
