### ISSUE TITLE
Disable pause on mouse click

### ISSUE THREAD

**Issue by getreadyforme** [clsid2/mpc-hc#44]
Is there an option to disable video pause on left mouse click?
Thanks.

**Comment by clsid2** [comment]
Options > Player > Keys > Play/Pause

Set mouse actions to NONE.

**Comment by TheOne320** [comment]
![mouseaction](https://user-images.githubusercontent.com/7705568/48573618-13c00c80-e90d-11e8-80cd-351e49c13cf4.PNG)
Here.

**Comment by getreadyforme** [comment]
:-)  this is embarrassing.  Thank you!
