### ISSUE TITLE
Access Violation on close

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#441]
Sometimes, when I close player, I get Access Violated error (see image below). In addition to this error application freezes and I have to use Task Manager to kill it. I was unable to reproduce it in any way as it seems to happen randomly. If I'm not mistaken this issue started to happen with version 1.9.2 but it still occurs with 1.9.4.

![Screenshot 2020-06-06-16-35-48](https://user-images.githubusercontent.com/40495747/83945602-7ab95500-a814-11ea-8503-da2d8b72f8f5.png)

**Comment by adipose** [comment]
@clsid2 

In debug mode, I sometimes get an error deleting the imagelist when closing mpc-hc too quickly after opening.  It's in the windows MFC code.  This sounds kind of similar.

However, it is a weird error that doesn't make any sense, and I've never seen it happen in a release build, so I've just ignored it.  It's been happening longer than 1.9.2.

@eggpa , any other clues?  Does it happen if you close quickly, or just randomly?

**Comment by clsid2** [comment]
I fixed a crash bug yesterday that might be same as this one.

Here is a test build:
https://www.sendspace.com/file/vjjudy
Also copy the CrashReporter folder. That will give better crash details.

**Comment by ghost** [comment]
@adipose no other clues I'm afraid. I have tried to open and close quickly, or open, seek, and close, but could not reproduce this issue after a dozen or two attempts.

@clsid2 since I have no reliable way to reproduce this I will keep using this version and report if anything happens. Should I update to newer build if it get released while I'm using test build or keep using the test build?

**Comment by clsid2** [comment]
If you think the problem is fixed, then you can switch to newer version once available, as those will have the fix included.

**Comment by ghost** [comment]
I have been messing with videos a lot for the past 2 days and had no errors on close so most likely this is fixed.
