### ISSUE TITLE
[DrDump] MPC-HC crashed because of fault in AMD graphics driver

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#444]
This page opened because MPC-HC crashed due to a fault in an AMD/ATI graphics driver component. If this problem happens often then try the potential solutions below.

**Solution 1:**

Did the crash occur directly after resuming playback when waking up your computer from sleep/hibernation?

MPC-HC options > Advanced > ReloadAfterLongPause = 15

**Solution 2:**

Change the video renderer.

MPC-HC options > Playback > Output

The recommended choice for modern systems is: MPC Video Renderer

When using this renderer on Windows 10/11, you should also adjust the hardware decoder:
MPC-HC options > Internal Filters > Video decoder > set "Hardware decoder" to "D3D11"

If you have an AMD Vega (or older) GPU, then you might also want to try using D3D9. To do that uncheck "Use Direct3D 11" in the settings of MPC Video Renderer, and set the hardware decoder in the internal video decoder to "DXVA2 native".

**Solution 3:**

Install a different version of the AMD graphics driver.
https://www.amd.com/en/support

**Solution 4:**

Disable hardware accelerated decoding. This can help to avoid bugs in the graphics driver.
MPC-HC options > Internal Filters > Video decoder > set "Hardware decoder" to "None"

**Feedback:**

If you need help or want to discuss driver issues, then please open a new issue for that.

**Comment by fawaf** [comment]
latest driver still crashes
```
MPC-HC (Nightly, 64-bit)
------------------------

Build information:
    Version:            1.9.14.28 (6fa8319df)
    Compiler:           MSVC v19.26.28806
    Build date:         Jul 31 2021

LAV Filters:
    LAV Splitter:       0.75.1.0
    LAV Video:          0.75.1.0
    LAV Audio:          0.75.1.0
    FFmpeg compiler:    MinGW-w64 GCC 10.3.0

Operating system:
    Name:               Windows NT 10.0 (build 19044)
    Version:            10.0 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    GPU1:               Radeon RX 580 Series (driver version: 27.20.22021.1002)
    GPU2:               Radeon RX 580 Series (driver version: 27.20.22021.1002)
```

**Comment by Hoernchen** [comment]
This is happening with the 21.12.1 driver - but the issue in my case is not related to hw decoding, that setting does not matter, it's the MPC Video Renderer 0.5.4.1723 that is causing the issue, evr custom pres with and without hw decoding works fine.

**Comment by clsid2** [comment]
Your problem is probably related to DXVA2/D3D11 scaling/processing (not decoding!) done by the video renderer. It is bug in the new driver. EVR-CP does not use that and is thus not affected.

**Comment by Hoernchen** [comment]
It appears to only happen with (HVC1) 4k HDR files (for example todays episodes of expanse, wheel of time, mzabi), the previous 21.11.3 driver is fine. Default video settings. 4k sdr is apparently not affected.

**Comment by Hoernchen** [comment]
Also affects 22.2.1...

**Comment by clsid2** [comment]
Try the 1.9.18.50 development build and also update MPCVR.

**Comment by Hoernchen** [comment]
I've just tried that, and it does not switch to HDR mode automatically - as soon as I turn on the windows HDR mode it still crashes :(

**Comment by Hoernchen** [comment]
Ooh I see, if I just start MPC by opening the file MPC is in the windowed mode, and in this case manually tuning on HDR crashes it - but as long as I enable "use exclusive fullscreen" in the MPCVR settings the manual switch to fullscreen sucessfully enables HDR10 as well. The problem is: I don't see any controls (seek bar and so on) and no mouse cursor, and I'm also having trouble getting out of fullscreen, only pressing escape works, and then everything appears to get stuck for a few seconds. But it looks like progress!

**Comment by AGA2020** [comment]
Experiencing this issue with a rtx 4060 with amd cpu
