### ISSUE TITLE
[DrDump] MPC-HC crashed because of fault in Intel graphics driver

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#445]
This page opened because MPC-HC crashed due to a fault in an Intel graphics driver component. If this problem happens often then try the solutions below.

**Solution 1:**

Did the crash occur directly after resuming playback when waking up your computer from sleep/hibernation?

MPC-HC options > Advanced > ReloadAfterLongPause = 15

**Solution 2:**

Change the video renderer.

MPC-HC options > Playback > Output

The recommended choice for modern systems is: MPC Video Renderer

When using this renderer on Windows 10/11, you should also adjust the hardware decoder:
MPC-HC options > Internal Filters > Video decoder > set "Hardware decoder" to "D3D11"

**Solution 3:**

Disable unwanted video processing in the Intel graphics control panel.

The Intel driver settings have some options for video post-processing. These options are often enabled by default. They are known to cause playback and stability problems and are also useless for improving video quality.

It is recommended to disable these options: _Contrast Enhancement_ and _Skin Tone Enhancement_.

![intel_driver_settings](https://user-images.githubusercontent.com/4704996/131339797-959ad3a2-1f1d-44bd-bef5-c418997d1490.png)

**Solution 4:**

Install a newer version of the Intel graphics driver.
https://downloadcenter.intel.com/product/80939/Graphics

**Solution 5:**

Disable hardware accelerated decoding (as a test). This can help to avoid bugs in the graphics driver.
MPC-HC options > Internal Filters > Video decoder > set "Hardware decoder" to "None"
If this does not help, then you can re-enable it.

Note: If you have a 5th generation (Broadwell) Intel GPU, then you can also try to only uncheck HEVC. Broadwell only has slow partially accelerated hardware decoding for this video format. It is better to use software decoding in that case. You can keep hardware decoding enabled for H.264.

**Feedback:**

If you need help or want to discuss driver issues, then please open a new issue for that.

**Comment by FinnRaze** [comment]
(Broadwell) Intel GPU's D3D11 hardware decoding works with HEVC on Windows8.1 without crash,but always crash on Windows10.DXVA2 doesn't crash,but outputs wrong color
