### ISSUE TITLE
[DrDump] MPC-HC crashed because of fault in NVIDIA graphics driver

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#446]
This page opened because MPC-HC crashed due to a fault in a NVIDIA graphics driver component.

If this problem happens often then try the potential solutions below.

**Solution 1:**

Did the crash occur directly after resuming playback when waking up your computer from sleep/hibernation?

MPC-HC options > Advanced > ReloadAfterLongPause = 15

**Solution 2:**

Change the video renderer.

MPC-HC options > Playback > Output

The recommended choice for modern systems is: MPC Video Renderer

When using this renderer on Windows 10/11, you should also adjust the hardware decoder:
MPC-HC options > Internal Filters > Video decoder > set "Hardware decoder" to "D3D11"

**Solution 3:**

Install a different version of the NVIDIA graphics driver.
https://www.geforce.com/drivers

During installation of the driver, choose to do a "clean install", so it will reset to its default settings.

**Solution 4:**

Disable hardware accelerated decoding. This can help to avoid bugs in the graphics driver.
MPC-HC options > Internal Filters > Video decoder > set "Hardware decoder" to "None"

This is mostly a suggestion for very old systems.

**Feedback:**

If you need help or want to discuss driver issues, then please open a new issue for that.

**Comment by Flee-blue** [comment]
mkv

**Comment by janos666** [comment]
This happened after Win11 HDR was activated (by a game) before I started to play an SDR movie and then I disabled Win11 HDR while the movie was paused.
