### ISSUE TITLE
Crash Reporter (Request)

### ISSUE THREAD

**Issue by THEtomaso** [clsid2/mpc-hc#447]
Short of deleting the 'CrashReporter' folder, how do I actually disable it?

--

**EDIT:
Request:** Enable/Disable toggle under 'Advanced' options.

**Comment by clsid2** [comment]
You can safely delete the folder to disable it.

**Comment by THEtomaso** [comment]
Yeah, I assumed that much.
I think that a simple toggle under 'Advanced' would provide a more elegant solution though. :)

**Comment by clsid2** [comment]
Added option.
