### ISSUE TITLE
Gestures for MPC on tablets&touch screens

### ISSUE THREAD

**Issue by rd1** [clsid2/mpc-hc#449]
Hello all, adding gestures as input to control various features of mpc, would that be possible?

example: 
horizontal slide: forward or rev
vertical: volume+/-
double-tap on the left of the screen in the 1/4 of mpc size: prev file
double-tap on the right 4/4: next file

It would be super useful in fullscreen mode on touch enabled devices.

ty

**Comment by clsid2** [comment]
There are no developers available that are interested in implementing this.
