### ISSUE TITLE
Feature request: call youtube-dl with configurable user/pass, or allow passing arbitrary parameters + save YT video from MPC-HC

### ISSUE THREAD

**Issue by Vagmer** [clsid2/mpc-hc#45]
Firstly, thanks for your work on keeping this project alive. Much appreciated!

If you try to open a private video or playlist (consider that _you_ can access it yourself, using your YouTube account) with MPC-HC, you will get this message: "ERROR: This playlist is private, use --username or --netrc to access it.". Trivial to do so otherwise, externally, but I didn't find a way to make MPC-HC pass it, so an option to pass username and password should be added, or an option to **pass custom extra parameters** altogether . Should probably just add the latter (or maybe both possibly) since I see youtube-dl can accept many options that could be vital for some user in the same vein, such as more authentication options or even specific --video-password for a few non-YT sites, not to mention that the other non-auth stuff params can be useful as well. Thinking of it, this in turn means there should be a new command line switch for MPC-HC itself, to pass extra arguments to youtube-dl in this call (possibly replacing the ones in settings?), so it can be done when you open a remote file from a command-line/shortcut, and so you can even control the parameters used per-file. A user having different passwords for non-YT sites could also be a thing. I don't know how feasible as of right now it would be to have MPC-HC itself by default prompt for a username and password when necessary, with a dialog. Might require collaboration with youtube-dl dev if it's something you want to bother with at all.
Relatedly, you could allow all such youtube-dl configuration I mention here to be loaded from a new text file (e.g. something similar to a .ini or .cfg file) in the MPC-HC directory, in which the user could add an arbitrary amount of any global and per-site/domain/even video specific youtube-dl options himself, not just passwords. There might be a domain match or regex string given to match the whole video URL to a specific settings set.

I guess it's worth noting it is a sort of security risk in that a user doing this exposes his (or the one that is used, anyway) Google/whatever account password in plaintext in settings storage or visibly in the MPC-HC settings dialog (unless you specially implement a workaround here like store it encrypted and not visible in the dialog once saved) and so the account is potentially vulnerable provided another person can already locally or remotely access his computer, but that's the user's own choice... I would use this feature. If it's not implemented by the user editing or creating a text file manually approach (in which case the risk should be immediately obvious) and no encryption is used then it might or might not be a thing worth including a warning about, though.
Apparently you can pass --username without passing --password as well to make youtube-dl ask for it interactively, so that might also be a usable thing, though a "remember" feature would still be needed all the same.

Of course, the only trivial/non-sidetracking and very-quick-to-add feature I've mentioned above is a basic extra-parameters-to-pass-to-youtube-dl-by-default new option and extra-parameters-to-pass-to-youtube-dl new command line switch, so I'd understand if you simply only add those, or only those at first. It'd probably be smart and still easy to make those two options able to replace the entire parameter string MPC-HC passes instead (using a replacement string to be swapped with the URL provided to MPC-HC, in the default-option), in case the built-in one might interfere with some possible customization options that could come after, it such as the desired video quality/format to use or something. 

By the way, could the "File->Save a Copy..." function be expanded to still be available while a youtube-dl video is opened, and be used to... save or download the video using youtube-dl? Could be a pretty useful shortcut.

Thanks for reading.

**Comment by clsid2** [comment]
I am not implementing any new functionality. Others will have to contribute patches.

**Comment by Vagmer** [comment]
All right. Still, thank you for replying.

**Comment by clsid2** [comment]
The ability to download using "Save a copy" has been added.

**Comment by clsid2** [comment]
This describes how you can supply login credentials to YDL:
https://github.com/rg3/youtube-dl#configuration
(section: "Authentication with .netrc file")
