### ISSUE TITLE
[Request] Save A-B loop marks on favorites

### ISSUE THREAD

**Issue by Mystqr4** [clsid2/mpc-hc#450]
It would be great if we could have the option to have our variables such as [ A - B ] Marks be remembered for that particular file when we add it to favorites.

Thanks for the great work on this great player and taking up development.

**Comment by bombapapa** [comment]
sorry me noob but this request is already working?
other thing I've also observed doesn't work that when I press altgr+[ or altgr+] for add mark A or B

**Comment by ShareFix** [comment]
I also need this :(

**Comment by cw2** [comment]
I have almost completed the implementation, but I have one question: what is the desired behavior of current/start position in regards to A-B repeat marks? I mean in my current version it is possible to store both current position (the existing checkbox **Remember position**) and A-B marks (via a new checkbox **Remember A-B repeat marks**), so after loading the playback starts at start position and A-B marks are set - I guess it would be better to rather start playback from the A mark (if set)? So basically the A mark becomes the start position (?)

**Comment by cw2** [comment]
Or perhaps better yet both checkboxes should be exclusive so it would be possible to check either **Remember position** or **Remember A-B repeat marks**, i.e. checking one will automatically uncheck the other (?) Then the start position and A mark is basically the same...

**Comment by clsid2** [comment]
You can allow to remember both. When opening use `MAX(stored_position, A)` as start position.
