### ISSUE TITLE
[DrDump] MPC-HC crashed due to a fault in LAV Filters

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#454]
**You should update to the latest version of MPC-HC**
https://github.com/clsid2/mpc-hc/releases

If you are using an external copy of LAV Filters, then you should update that as well. I strongly recommend to use the internal LAV Filters. Enable everything here:
Options > Internal Filters

If you are already using the latest version, and you can reproduce this crash with a specific file, then please send me a link to that file.
clsid2@users.sourceforge.net
You can send torrent link. Or upload file to for example Dropbox, Google Drive, or a file hosting site like sendspace.com

**Comment by alamgircsejnu** [comment]
http://172.16.50.9/SAM-FTP-1/English%20%26%20Foreign%20TV%20Series/Black%20Sails%20%28TV%20Series%202014%E2%80%93%20%29%20720p/Season%203/

The crash happened for the S03E05.

**Comment by clsid2** [comment]
That is a local IP address. I can't access it. Please upload the file to Dropbox, Google Drive, or somewhere else.

**Comment by adam-koebel** [comment]
I've gotten this crash on two different files, both of them are 4k 60fps videos created with youtube-dl. If you pull the highest quality versions of these files with youtube-dl you will have what I have:
https://www.youtube.com/watch?v=mihNKL6rfF4
https://www.youtube.com/watch?v=kfjDyr8kc_c
The files are 4k60fps VP9 with opus audio in a mkv container.

Both crashes happened after watching for approx 8 minutes. Reloading the files and scrubbing to the section where it crashed was not repeatable. Seems you have to watch for a while.

Hope this helps.

MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.8 (6281da8a8)
    Compiler:           MSVC v19.26.28806
    Build date:         Oct 24 2020

LAV Filters:
    LAV Splitter:       0.74.1.75
    LAV Video:          0.74.1.75
    LAV Audio:          0.74.1.75
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 10.0 (build 19041)
    Version:            10.0 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    GPU:                NVIDIA GeForce RTX 3080 (driver version: 27.21.14.5709)
