### ISSUE TITLE
[DrDump] MPC-HC crashes due to ffdshow

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#459]
MPC-HC has crashed due to a bug in ffdshow.

### Recommended solution

It is recommended to uninstall ffdshow. You don't need it for playback. The internal codecs of MPC-HC are much better.

If you use any of the processing filters in ffdshow, then there are good alternatives for almost all of them! For example:

Volume normalization: MPC-HC options > Internal Filters > Audio Switcher > Volume normalization
Color controls: MPC-HC options > Miscellanous > Color Controls
Avisynth: [Avisynth Filter](https://github.com/CrendKing/avisynth_filter). Tip: if you are using SVP, then that filter is also included in its installer and you should install SVP without ffdshow (which is redundant and obsolete).

### Alternative solution

**Latest version of ffdshow:**

In case you are using an old version. You can find latest version here:
[32-bit rev4533 (20140929)](https://sourceforge.net/projects/ffdshow-tryout/files/SVN%20builds%20by%20clsid/generic%20builds/ffdshow_rev4533_20140929_clsid.exe/download)
[64-bit rev4533 (20140929)](https://sourceforge.net/projects/ffdshow-tryout/files/SVN%20builds%20by%20clsid/64-bit%20builds/ffdshow_rev4533_20140929_clsid_x64.exe/download)

Uninstall your current version first!

**TIP: use ffdshow processing filters only**

The decoding functionality of ffdshow is old and inferior. If you only use ffdshow because of its extra processing functionality, then it is recommended to use its processing filters instead of its decoders.

During installation of ffdshow, disable the decoders and also the VFW interface. Only enable **raw video processor** and **raw audio processor**.

To use these filters:
MPC-HC options > External Filters > Add Filter > ffdshow raw video filter > Prefer
MPC-HC options > External Filters > Add Filter > ffdshow audio processor > Prefer

**Comment by MEMO460** [comment]
yo, clsid2 please I'm new here I just want to help me ... that I want to know how I can build mpc-hc from source code using visual studio...... I hope you answer ..... thank you.

**Comment by lifegpc** [comment]
@MEMO460 You can see here : https://github.com/clsid2/mpc-hc/blob/develop/docs/Compilation.md

**Comment by MEMO460** [comment]
@lifegpc Thanks a lot bro.
