### ISSUE TITLE
Handle leak with CreateProcess

### ISSUE THREAD

**Issue by AtlasHackert** [clsid2/mpc-hc#46]
In commit 0d5ddc8d3d701a52948b6bbf356f8b55bd263539, src/mpc-hc/MainFrm.cpp, line 17237. CreateProcess returns two handles in the PROCESS_INFORMATION structure (hProcess and hThread) that need to be closed; right now, they are leaking when the DownloadWithYoutubeDL-function returns.

**Comment by clsid2** [comment]
Fixed. Thanks!
