### ISSUE TITLE
Playback Speed Audio Pitch Fix so it works like on YouTube?

### ISSUE THREAD

**Issue by hl24a3** [clsid2/mpc-hc#460]
Hi, first of all thank you for keeping this amazing media player ALIVE in my opinion the best media player on the market.

I'd like to put an idea or request, would you consider making playback speed in the same way like on YouTube where watching a video on higher speed it fixes the voice pitch (I think is pitch) anyway I mean getting rid of the chip and dale like voice? this would be like the most amazing addition.

Thank you

**Comment by clsid2** [comment]
The internal audio renderer has pitch correction.

Options > playback > output

**Comment by ToxicSmurf** [comment]
I have the same issue and cannot find the internal audio renderer option or any audio renderer with pitch correction of any kind.
