### ISSUE TITLE
[Request] Improved drag and drop interactivity with file explorer for better convenience

### ISSUE THREAD

**Issue by andrewz1986** [clsid2/mpc-hc#468]
Hi. First of all, thanks for putting together and maintaining the best video player around. I was surprised to find out that even A-B playback was added in the last few years, which was the only feature MPC did not have, but competition did.

But let's get to the point of this post. **I'd like to propose improved files drag and (mainly) drop mechanism to make interactivity between MPC and file explorer more convenient**. 

When dragging files from file explorer and dropping them onto MPC window, what you can do in the current version is to put these files to the queue, while playback of the first file starts immediately – the problem* is that when you play something beforehand, it is skipped and erased from the queue. When you hold Control key when dropping the files, you enqueue these files to the file that is already present in the queue – described problem* is solved (although the tooltip now says "Copy" instead of "Move", which is not describing well what is really happening). 

The persisting issue is that **it is impossible or difficult to press Control on tablet devices and that there is at least one more case when drag and drop could be useful – when you want to play a video, but you have an audio track (or eventually a subtitle track) in an external file**, which is exactly what led me to compose this post. As far as I know, the easiest (and probably the only) way to do it is to use this pretty user unfriendly Ctrl+O pop-up window (in case of external subtitles, playing the video first and dropping subtitle file onto it), which does not even accept dropping:

![ctrlo](https://user-images.githubusercontent.com/40487872/84892760-74419d80-b09e-11ea-944a-da4b7c333337.png)

When dropping files onto MPC window, **I propose to split the window into three various dropable areas**. Depending on circumstances (Is there something already playing? What files are dragged?) and the dropable area you decide to drop the file(s) into, different action would take place, namely these [notes in brackets]:

"Play eligible files in sequence" [the way it works now implicitly]
"Enqueue eligible files" [the way it works now when you hold Control key]
"Play eligible files in sync" [eligible files would play simultaneously, e.g. video and audio, both in it's own "external" file, thus replicating inconvenient Ctrl+O pop-up window]

Images are worth a thousand words (two scenarios depicted):

![Play eligible files in sequence](https://user-images.githubusercontent.com/40487872/84892758-73107080-b09e-11ea-94e4-19ce78c548b0.png)

![Play eligible files in sync v2](https://user-images.githubusercontent.com/40487872/84893435-853ede80-b09f-11ea-9d4e-63eda2e5f1e5.png)

Unfortunately, I'm not a programmer, but I'm willing to make reasonable financial donation. Where am I supposed to make it? I'm a little bit confused.

Thanks.

**Comment by clsid2** [comment]
If you give the audio dub file the same name as the video file, then it will be loaded automatically. Same for subtitles.

The Copy/Move tooltips are standard names/actions from windows. That can't be changed.

If you want to enqueue on a tablet, make the playlist visible, and drop onto that. Or do the equivalent of a right-click on the selection in Explorer and choose "Add to MPC-HC playlist" in the context menu.
MPC-HC options > Player > Format > Explorer Context menu

I don't like the drop zone idea.

**Comment by andrewz1986** [comment]
Thanks for your suggestions. The reason I need an advanced video player like MPC is that I like to play Blu-ray movies with audio tracks from DVDs: certain movies were released only on DVD in my country, so I own Czech DVDs and Blu-rays from abroad without Czech support as well (I know I could make MKVs with all languages inside, but I prefer to have movies stored on pressed optical discs). Thus I cannot put video and audio into the same directory (and solve the issue by giving it the same name).

The thing is that MPC is made with mouse and keyboard in mind. When you have none available to you, using it is getting pretty difficult. You suggest to use MPC playlist, but look at the tiny closing button. That sums my words pretty well.

![tinybutton](https://user-images.githubusercontent.com/40487872/84913220-95b08280-b0ba-11ea-862f-ca4b5c9217ad.png)
