### ISSUE TITLE
"URL Decode" URLs for use in title

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#470]
When playing a streaming url directly (NOT passing from youtube-dl) MPC-HC use the filename part of the streaming url to set the title, but the problem is that it doesn't "URL Decode" it so the title may end up like this: My%20sample%20video

**Comment by adipose** [comment]
@ale5000-git Do you have an example url I can test with?

**Comment by lifegpc** [comment]
@adipose https://kanahanazawa.com/v/%e3%80%90MV%e3%80%91%e4%bf%9d%e5%8a%a0%e5%88%a9%e4%ba%9a%e5%a6%96%e7%8e%8bAZIS%e8%a7%86%e9%a2%91%e5%90%88%e8%be%91(AV170001,BV17x411w7KC)/1.%d0%a5%d0%be%d0%bf(P1,279786).mkv
Here is.

**Comment by adipose** [comment]
Does this look right?

![image](https://user-images.githubusercontent.com/3324395/91209814-24480e00-e6c1-11ea-8c73-9298a76c0ef3.png)

**Comment by clsid2** [comment]
It should be:
1.Хоп(P1,279786).mkv

The escaped values should be decoded as UTF-8.
https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_in_a_URI

**Comment by ale5000-git** [comment]
@adipose: You can test decoding here => https://meyerweb.com/eric/tools/dencoder/

The full link of lifegpc after decoding became: https://kanahanazawa.com/v/【MV】保加利亚妖王AZIS视频合辑(AV170001,BV17x411w7KC)/1.Хоп(P1,279786).mkv

**PS:** While you are at it, it may also be nice to display the url decoded in "Location" under File => Properties => Clip.

**Comment by adipose** [comment]
Thanks, I noticed since I last posted it was a utf-8 encoded url-encoded string.  

![image](https://user-images.githubusercontent.com/3324395/91233832-e1009600-e6e6-11ea-83d5-63f90e06aede.png)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/591

The location (and filename in the property dialogs) will now be decoded as well.

**Comment by ale5000-git** [comment]
@adipose: Thanks, it seems to work perfectly in most places but it miss the recent files list where it is still encoded.

**PS:** Currently I don't have time to test it but does someone have verified if the subtitle search by name works correctly in this case?

**Comment by clsid2** [comment]
Long names in recent files list should also be shortened. There already is a function for that used elsewhere.

**Comment by adipose** [comment]
I'll take a look at this soon.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/612
