### ISSUE TITLE
playback broken on large rar-sets

### ISSUE THREAD

**Issue by prssrp** [clsid2/mpc-hc#471]
playback using mpc-hc x64 on large rar-set (~15gb) 
1.9.4.21 (daeb8bf8d) working
1.9.4.25 (072be99b8) broken
1.9.4.34 (dd8c29268) broken

releases >1.9.4.21 seemingly try to read the whole rar-set before beginning playback,
thereby needlessly filling ram and getting completely unresponsive.
in my opinion the most likely culprit is commit
bb97191d3e3b14cde6f056071b7cd5af2ad2043c

cheers and thanks for all your continued work on mpc-hc!

**Comment by clsid2** [comment]
Should be fixed in 1.9.5
