### ISSUE TITLE
Feature request: Use Youtube chapter info

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#472]
youtube-dl can already extract json, so it is just a matter of parsing and using it

Example:
`youtube-dl --write-info-json https://www.youtube.com/watch?v=BvyQ70PVI4s`

Info:
https://www.reddit.com/r/youtubedl/comments/g67psv/youtube_chapters_download/

**Comment by clsid2** [comment]
I am not going to implement this.
