### ISSUE TITLE
"Wheel Right/Left" does not work while mouse is over UI

### ISSUE THREAD

**Issue by b9AcE** [clsid2/mpc-hc#473]
I have set the recently added "Wheel Right" and "Wheel Left" to "Jump Forward (medium)" and "Jump Backward (medium)" under "Options"→"Player"→"Keys", which works fine while the mouse pointer is over the video area itself, but not if it is over the title bar/menu/seek bar/controls/etc.
The default keys "Right Arrow" and "Left Arrow" work over all those areas and it seems reasonable that "Wheel Right/Left" should work there too.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/477

This fixes it for messages over the main window (menu, playbar).  The playlist still seems to trap them.

HWHEEL is treated differently by windows than WHEEL, and thus the same behavior takes some work.  All the wheel messages are sent to one window, but the HWHEEL messages can be sent to wherever the moue is hovering.
