### ISSUE TITLE
drag and drop not working

### ISSUE THREAD

**Issue by MichelR-be** [clsid2/mpc-hc#474]
When you drag and drop a video it doesn't want to accept it. :(

**Comment by clsid2** [comment]
Drag&drop doesn't work if you run the player as administrator through compatibility settings.

Otherwise, I don't know what is wrong with your system. It is not a bug in the player.

**Comment by MichelR-be** [comment]
ok, thanks, didn't know that. But if I don't open it as "administrator through compatibility settings" it doesn't remember where the played movie was nor does it remember any changed settings :(

**Comment by clsid2** [comment]
Disable the option to store settings in INI file. That doesn't when installed in program files, as that is a protected folder which requires admin for making changes.

**Comment by MichelR-be** [comment]
I like to backup and sync the ini-file settings with other computers. So maybe you could add a changeable path for the ini-file ;)
Also, now when not starting it under administrator to allow drag and drop, it doesn't remember the file position and even uses the previous file position from starting it under administrator :(

**Comment by clsid2** [comment]
Settings are stored in Registry key:
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC
This can also be exported and imported.

But if you really want to use INI file you need to manually adjust the file permissions of the file.
Right-click > Properties > Security > Edit > Give "users" group full access

Then everything will work properly.

**Comment by ale5000-git** [comment]
Why not using C:\ProgramData\KLCP for ini files?
