### ISSUE TITLE
[Request] Improve network throughput while buffering frames.

### ISSUE THREAD

**Issue by Osjur** [clsid2/mpc-hc#475]
I don't know if this is related to MPC-HC or to Lavfilters but would it be possible to increase network throughput while playing files from network drives across WAN. 

If I just copy the media file from my NAS (SMB share) over VPN, I get around 35-45mbits transfer rates which would be mostly enough for 4k playback but when I open the file directly in MPC-HC, it buffers the file at rates of max 17mbits, which looks like the max throughput one can get with standard 65kbit buffer x latency of around 30ms with no tcp window auto-tuning enabled on windows.

**Comment by clsid2** [comment]
You need to ask LAV Filters developer.
