### ISSUE TITLE
Feature request: Auto Updater

### ISSUE THREAD

**Issue by TheMCSpacePro** [clsid2/mpc-hc#476]
So, I had an idea. How about, instead of sending us to the downloads page for new updates, why not instead add an auto updater? It would just download the installer and auto run it without sending the user to the downloads page.

**Comment by ageekhere** [comment]
Would be a nice feature

**Comment by clsid2** [comment]
There will NOT be such functionality.

I don't want to spend time to implement it.
I don't want to spend time to maintain it.
It has file hosting requirements.
It is a potential security hole.
It results in even more idiots who never read changelogs and then come asking for features that already fucking exist.
