### ISSUE TITLE
Subtitle line is not displayed when seeked to it

### ISSUE THREAD

**Issue by Sa-ghosts** [clsid2/mpc-hc#483]
Okay this a weird issue for sure and can't reproduce on every video.

File used for testing:
Deleted link.

How to reproduce:
1- Insure you have fast seeking enabled (options --> tweaks --> Fast seek 'nearest keyframe')
2- Open the video and move the timeline to 4:12 (in the included video)

Expected behaviour:
you would jump to a subtitle line and it would be displayed with no problem.

What actually happen:
the subtitle line would NOT be shown and you have to either press the left arrow key to go back to the previous line or press ctrl + left arrow to go back one frame and the sutitle line would appear.

Additional information:
- Can't reproduce the issue with mpc-be.
- I can't reproduce the issue if I pass the video to mkvtoolnix and start multiplexing it without changing anything (obviously I'm talking about the output video not the original).
- I tried 3 subtitle renders (internal, xysubfilter, Assfiltermod) and I can reproduce the issue with all 3 of them.

**Comment by clsid2** [comment]
This is not a bug.

The subtitle data for that line is located in a position before the point where you are seeking to.

Remuxing fixes it because that adds CuePoint information that the splitter can use to find the relevant data. So fault is in the file itself.

**Comment by Sa-ghosts** [comment]
But how come MPC-BE can deal with it just fine?
also VLC and mpv don't have a problem handling it.

it's not just that one line and it's not just this one file and ofc not the only group .. but this anime from this group is unique because MPC-BE can handle it without remuxing (mpv never had a problem with this type of problems).

**Comment by clsid2** [comment]
This is simply how it works. Go complain to LAV Filters if you don't like it.

**Comment by Sa-ghosts** [comment]
it's not complaining, I just thought because mpc-hc couldn't handle it and mpc-be, vlc and mpv could .. there must be a problem with mpc.

but it seems yes you're right about LAV filter, becuase when I setup mpc-be to use LAV Splitter Source I can reproduce the issue.
