### ISSUE TITLE
Half screen window blank screen

### ISSUE THREAD

**Issue by viewtheard** [clsid2/mpc-hc#485]
in all vesion:
When the vertical second monitor drags the player to the horizontal home screen, a malfunction occurs.
correct:
![2020620-152154](https://user-images.githubusercontent.com/8788679/85259546-d71aa680-b49b-11ea-9be7-74855f9a6828.jpg)
incorrect:
![2020620-152047](https://user-images.githubusercontent.com/8788679/85259559-daae2d80-b49b-11ea-8091-8e48f4ae538a.jpg)

**Comment by clsid2** [comment]
Does it only happen with 10-bit output?

**Comment by viewtheard** [comment]
Now uncheck "10-bit output" and it can't return to normal display, it can only open video files from the folder in the main display and display normally.

**Comment by clsid2** [comment]
This setting may help:
Options > Playback > Output > Reinitialize when changing display

**Comment by viewtheard** [comment]
Thanks a lot, it works
