### ISSUE TITLE
Video is polluted with labels in fullscreen mode

### ISSUE THREAD

**Issue by EdMalashkin** [clsid2/mpc-hc#486]
I need to get clean video to broadcast it in fullscreen mode so I am trying to get rid of all the labels, bars and controls over it. I set "Hide controls in fullscreen" to "Never show" and unchecked everything in View context menu. But the issue is that I am still getting a file name or "Play" and "Pause" labels in the left top corner.

![image](https://user-images.githubusercontent.com/27769158/85624168-261a3480-b672-11ea-9a4b-b76f3e76f96a.png)

**Comment by clsid2** [comment]
That is the On-screen display.

Options > Player > Show OSD
