### ISSUE TITLE
When i saveimage (f5 by default) on a mkv file, the image saves without the subtitles

### ISSUE THREAD

**Issue by omi-l** [clsid2/mpc-hc#487]
Hello, first of all, i really appreciate your motivation to keep  this mediaplayer alive, i have been using thos for years :)
I was trying to saveimage on a mkv file but the image saves without the substitles, do i need to do a change on the config?
![ricarod  Steins Gate 01 1080p BD-Rip h264 FLAC mkv_snapshot_07 20 304](https://user-images.githubusercontent.com/67396777/85636625-07ef0d00-b64f-11ea-8501-ea3cd79bb5cf.jpg)

**Comment by Skibicki** [comment]
This depends on the combination of Video Renderer and Subtitle Renderer.

**Comment by clsid2** [comment]
Update to latest version (1.9.5)
Options > Advanced > SnapshotSubtitles

It only works with the internal subtitle renderer
Options > Playback > Output

If you use madVR as video renderer, then you need to look in madVR settings for snapshot options.
