### ISSUE TITLE
Drag Video Frame To Exit Full Screen(Resized only fullscreen)

### ISSUE THREAD

**Issue by dewdkorn6969** [clsid2/mpc-hc#488]
On MPC 1.9.2 (64bit) and earlier i was able to click and drag from middle of a video to the top of the screen to maximize the video on that screen (after unbinding the pause/play from left click) and when i needed to bring it out of the maximized state i can also click and drag the video to restore it back to its normal size and move it around. now on 1.9.3 and above something changed where the drag to top of screen still works to maximize but i cant bring it out of the maximized state by dragging the video any more unless i turn on the title bar and drag from the title bar. i typically have the player setup with frame only with just seekbar and status turned on. i tried messing with various advanced options and tweaks and went over every setting nothing gets that function to work again other than downgrading back to 1.9.2

im running windows 10 with an amd rx580 gpu not sure what other info might help

**Comment by clsid2** [comment]
The behavior was changed to ignore accidental drags. If you drag mouse a distance of at least 10% of screen size, then it will work as before.

You can also double-click on title bar to restore to un-maximized window.
