### ISSUE TITLE
BlockVSFilter=True prevents BT.2020

### ISSUE THREAD

**Issue by anmiettu** [clsid2/mpc-hc#494]
I have double language family so I need two set of subtitles.

I order to get HDR works (with MadVR) I need to set BlockVSFilter=True to get BT.2020 color spaces loaded.
Whenever I set BlockVSFilter=False MPC-HC (1.9.5.6) gets BT.709 loaded.

**Comment by clsid2** [comment]
That is not a bug in the player.

madVR currently needs a direct connection to the video decoder to properly handle the HDR metadata. That is something that need to be improved on madVR side.

**Comment by anmiettu** [comment]
Is there workaround to get HDR working with VSFilter?

**Comment by clsid2** [comment]
No.

**Comment by anmiettu** [comment]
Another rendered?

**Comment by clsid2** [comment]
That will give the same problem. I can't help you.

**Comment by anmiettu** [comment]
Hi,

I did some testing last night. It looks like that all external subtitle renders fall back to BT.709. Only internal subtitle render enables BT.2020. This understandable based on your explanation.

Would you like to be the 1st person on earth which has created media player supporting two set of subtitles handled by internal render? Based on my limited knowledge to my eyes this would be the only solution to get two set of subtitles to work with BT.2020. Also two set of subtitles would be very handy - also as a general feature - if taken care of media player itself without play with external + internal renders. There quite amount of double language families out there.

There is none media player available on the market to support double subtitles internally.

Br,
.Antti

**Comment by clsid2** [comment]
That isn't easy to implement. Since I don't need such functionality myself, it is not something I will be doing. Another developer will need to volunteer to do it. There are too many requests and too little developers.

**Comment by anmiettu** [comment]
Could you get in touch me privately: antti.miettunen@pp.inet.fi

**Comment by anmiettu** [comment]
clsid2: could you provide contact of some developer(s) working with mpc-hc. I would like get in touch with him/her to discuss possibility to implement such a feature. (antti.miettunen@pp.inet.fi)

.Antti

**Comment by clsid2** [comment]
I have already said that I am not interested in implementing this. There is nobody that you can contact. This is the only place where you can make a proposition. Put a big bounty on it and hope a new developer joins.
