### ISSUE TITLE
[feature request] speed controller

### ISSUE THREAD

**Issue by wadawada** [clsid2/mpc-hc#496]
Add a speed slider(and/or shortcuts) which stretches time without scaling the speed (like YouTube speed control with a slider)
Thanks

**Comment by clsid2** [comment]
It already has the ability to adjust video speed. When using the internal audio renderer, pitch correction is applied to the audio.

There already is another open issue/request for adding a menu with specific speed settings.

**Comment by wadawada** [comment]
Thanks, Ctrl+up/down/R for speed control

https://github.com/clsid2/mpc-hc/issues/49#issuecomment-445555408
Options > Playback > Output > Audio Renderer > Internal Audio Renderer
https://github.com/clsid2/mpc-hc/issues/211#issuecomment-570767339
Options > playback > Speed step

I think the above 2 options can be default for new install

https://github.com/clsid2/mpc-hc/issues/369
