### ISSUE TITLE
trac issue #5595

### ISSUE THREAD

**Issue by Stanzilla** [clsid2/mpc-hc#5]
Trac seems broken, I can't respond there. (https://trac.mpc-hc.org/ticket/5595)

Anyway, my LAN adapter is not allowed to go to sleep and the issue still happens if I access the network drive before trying to resume the video. I fully believe this is a Windows only issue.

**Comment by clsid2** [comment]
Sorry, but that is not something that can be fixed in MPC-HC. The file handling does not even occur in MPC-HC, but in either the "LAV Splitter Source" or "File Source (Async.)" DirectShow filters. The latter being a standard filter from Microsoft.
