### ISSUE TITLE
[request] remembering window position for 2 different monitors

### ISSUE THREAD

**Issue by Obi-Shinobi** [clsid2/mpc-hc#500]
So we already have the option to open more than one player at a time but they all open in the same monitor.  Anyway we can have an option to remember last window position for two different monitors?  I know this is a weird request.  I tried cloning the two monitors and that actually worked but when I'm not playing video I like to use them for discord and PC monitoring and dont really want two of any program showing on two monitors, seems more pointless than my request.

I'm wanting to play the same vid on both players/monitors if that helps.  Just a nerdy thing I'm trying with voiceattack.

If we already have that option somewhere I'm not seeing it.

thanks

**Comment by clsid2** [comment]
Remember position works on multiple screens when extending the desktop.

Remembering for multiple player instances will not be implemented.
