### ISSUE TITLE
Minor display issue in Options>Advanced (with a long Value string: youtube-dl)

### ISSUE THREAD

**Issue by butterw** [clsid2/mpc-hc#501]
Name Column should not be completely shrunk. 
youtube-dl cmd:  --write-thumbnail -o "b:\Videos\%(uploader)s_%(resolution)s_%(id)s_%(title)s.%(ext)s"

![mpc-hc_options advanced](https://user-images.githubusercontent.com/408915/85918428-0138e380-b863-11ea-8bf8-5877659e6e3c.png)

Edit: The issue was with installed v1.9.3 x64, persists after update to v1.9.6 x64 + reset reg settings.  
With portable v1.9.3 and v1.9.6 x32 the issue isn't as bad (the Name column is only partially shrunk after resize).

**Comment by clsid2** [comment]
Fixed
