### ISSUE TITLE
Disable/Enable Shaders (Hotkey: Ctrl+P)

### ISSUE THREAD

**Issue by butterw** [clsid2/mpc-hc#502]
Request: add a tick in Shaders contextual menu to enable/disable user pixel shaders output. Associate a hotkey to it (MPC-BE uses Ctrl+P).   

The current workaround is to create an empty " Disable" Shader Preset + Menu. However, you lose your current unsaved shader chain when you do this and you can't associate a hotkey to it.

![MPC-HC_Shaders Presets](https://user-images.githubusercontent.com/408915/85919147-0b5de080-b869-11ea-9e35-1a1d4f9911ad.jpg)

**Comment by demolitioner** [comment]
Old MPC-HC, not from CLSID, as I remember had this feature already (ctrl+p enable/disable shaders), and I was used it actively. I don't know why CLSID removed this useful feature, making the program less convenient and slower to use.

**Comment by clsid2** [comment]
I did not remove it. It must have been removed in original MPC-HC when shader preset functionality was added.

**Comment by butterw** [comment]
It would require introducing a toggle parameter between "Shader Preset" and "Passthrough" and binding it to Ctrl-P.

A hotkey to disable shaders is useful because shader settings are persistent between runs. Being able to know what processing is performed and being able to disable it instantly is a key feature of mpc vs other players such as vlc, mpv, where you have to wade through configuration tabs or configuration files. 

It's also useful for adjusting shader parameters visually by quickly toggling on/off the shader (this doesn't work great if you need to go through a menu). As a workaround [a splitscreen approach](https://forum.doom9.org/showthread.php?p=1925162#post1925162) can work for most shaders , but it doesn't work for a subtle sharpening filter for instance.

**Comment by butterw** [comment]
I've tested the implementation in MPC-HC.1.9.8.26.x64 Nov7 Nightly Portable:
- It has pre-resize shader shortcut: CTRL-P, post-resize shader shortcut: CTRL-ALT-P. 
- No related setting is saved in the mpc ini file >> shaders are always enabled on startup.
- Menu entries are greyed out if no shader is present in the corresponding chain.

Issues (updated): 
1) Initial State should be set to "enable shaders" to reflect what's actually happening. Menu entry should be ticked on startup. Using the shortcut would then directly disable. To disable shaders with the current implementation you have to go through enable first which doesn't make sense.
 
2) Having a single shortcut (Enable Shaders) to control both chains would be simpler. I've tried rebinding post-resize enable to CTRL-P, but in this case only the pre-resize enable gets applied.
It should be possible to define a single shortcut that triggers enable for both pre and post-resize shaders. Either expose only this command in the menu or add an extra shortcut command (and don't show it in the menu). 
I don't know of any real use case where it is useful to control pre-resize and post-resize separately. 

- 1+2: Currently if you have pre and post-resize shaders and you want to disable them you would have to go through CTRL-P, CTRL-P, CTRL-ALT-P, CTRL-ALT-P with corresponding OSD messages !

**Comment by butterw** [comment]
As of latest Build, the issues I mentionned remain. 
    Version:            1.9.8.38 (fb6eea759-dirty) (patch157) (develop@a91c9d4), Nov 17 2020

It's not clear to me why Enable Shaders state isn't set on startup.
