### ISSUE TITLE
[Feature Request] Scroll to Seek

### ISSUE THREAD

**Issue by Bradley-Schneider** [clsid2/mpc-hc#503]
VLC has a useful feature that allows you to seek through the currently open file with the scroll wheel (forwards and backwards) when hovering over the seek bar. This is advantageous if you primarily use a mouse in an HTPC set-up, since it's hard to skip through a video slowly without using the keyboard.

Certainly low priority, but it's a handy feature!

**Comment by zoidbergthepopularone** [comment]
If we are already considering taking inspiration from other players, then PotPlayer has the nice feature of allowing key modifiers (SHIFT, ALT, CTRL, +combinations) along with MouseWheel to change the seek distance. MPC-HC can do that for key combos but not for mouse wheel because it does not allow modifiers to be used with mouse controls.

**Comment by clsid2** [comment]
You can drag the seekbar with the mouse.

Scroll wheel is already used for volume. Giving it more functionality is not something we are going to invest time in right now.

**Comment by clsid2** [comment]
Maybe allow use Ctrl+MouseWheel.

**Comment by adipose** [comment]
Interesting because the seekbar is actually a scrollbar in disguise, I think.  But by default scrollwheel doesn't pass to a horizontal scrollbar if there are vertical scroll bars anywhere.  And MPC-HC actually traps the scroll to change volume.  It could be a bit messy!

**Comment by clsid2** [comment]
Ctrl+MouseWheel already works for seeking in current builds. I added that hotkey after the mouse modifier enhancement.

I tried with mouse pointer above seekbar, and it still works.

**Comment by agiz10** [comment]
Where can i set this feature: Ctrl+MouseWheel for seeking?
Can not seem to find it and it does not seem to be working by default. ty.
