### ISSUE TITLE
Version 1.9.6 (and at least its predecessor) thinking of itself as 1.8.7

### ISSUE THREAD

**Issue by ffffennek** [clsid2/mpc-hc#508]
Copied from "Help" > "About":

> MPC-HC (64-bit)
> ---------------
> Build information:
>    **Version:            1.8.7 (1cec1bbe9)**
>     Compiler:           MSVC v19.16.27032.01
>     Build date:         Jul 17 2019 12:21:47

This leads to 'available update' announcements every X days (X being whatever number is set in options for days between checks).

**Comment by clsid2** [comment]
The problem in on your end. You might have both x86 and x64 build installed.
