### ISSUE TITLE
[Request] Change installer behavior for shortcut creation in the start menu

### ISSUE THREAD

**Issue by p-monteiro** [clsid2/mpc-hc#511]
In Windows 10 with a more streamlined apps list, there should not be a need to create a start menu folder for the shortcut.
Instead, it should be placed directly in the apps list (without a folder).

About the "Uninstall" shortcut: every supported Windows version has a place to uninstall applications, especially since Windows 10 where you can click the icon with secondary click button and choose "Uninstall", so there should not be a need for it. Windows 10 already hides this from the apps list.

About the "MPC-HC on the web" shortcut: I think this should be ditched since I sincerely doubt anyone is using it. Also, it can be placed on the "About" dialogue of the player.

**Comment by ale5000-git** [comment]
Personally I use Open-Shell to bring back the functional start menu and I would like to have all shortcuts available forever.

**Comment by clsid2** [comment]
Modern versions of Windows will automatically hide uninstall shortcuts to avoid clutter. But it still appears in Start menu search results, which is useful.

**Comment by p-monteiro** [comment]
@ale5000-git I understand that, but how many times since you use MPC did you actually used the uninstall shortcut or the "on the web" one.

@clsid2 That is good reasoning indeed. But then the folder still clutters the apps list unnecessarily.

**Comment by ale5000-git** [comment]
@pedroemonteiro: Using the uninstall shortcut you aren't limited to 1 uninstallation at time, so it is very usefull to uninstall various programs concurrently, since I'm a programmer I use these often.
About the "on the web" I don't have it, what do you mean exactly?

**Comment by p-monteiro** [comment]
@ale5000-git I guess there is a use case for the uninstaller icon, although I bet very uncommon. Could be an option during the installation to create that shortcut or not.

About the "on the web" I'm referring to this:
![image](https://user-images.githubusercontent.com/27056844/91643983-e1bf6200-ea2f-11ea-9583-551880a4a11a.png)
![image](https://user-images.githubusercontent.com/27056844/91643997-fef43080-ea2f-11ea-8480-22637d9cbaa8.png)
