### ISSUE TITLE
[Request] When changing the video playback rate, external subtitles downloaded automatically via online search/DL still show delay

### ISSUE THREAD

**Issue by Uberlime** [clsid2/mpc-hc#512]
Hi, 1st, greatly appreciated the change made in 1.9.3 : _matching subtitles speed for external subtitles with altered playback speed_🥇 , only caveat is, it doesn't apply (yet :) to those automatically downloaded using the online search module... I hope it's possible in the future to add this feat.
Best regards.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/commit/e97ec26ae1aa5b1eb0fd76677832523e8733a5f3

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/619
