### ISSUE TITLE
Language localisation issue

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#515]
![image](https://user-images.githubusercontent.com/41434272/86425574-1f498c80-bd18-11ea-8ccc-06a3849b1ef2.png)
![image](https://user-images.githubusercontent.com/41434272/86425693-69327280-bd18-11ea-80f4-2c2c44b26b05.png)
Menu strings are English but I am use zh_CN.
It may some bugs in #509  .
I use 1.9.6.14.

**Comment by lifegpc** [comment]
I revert repo to [3f4a491](https://github.com/clsid2/mpc-hc/commit/3f4a491b8993437593fcbd3218177ed1f73f550b), it works fine. 
I am sure some bugs occurs in #509 .
![image](https://user-images.githubusercontent.com/41434272/86426641-bf081a00-bd1a-11ea-98a7-cee3c68cbf2f.png)

**Comment by lifegpc** [comment]
All msgctxt with "POPUP" was removed in mpc-hc.zh_CN.menus.po.

**Comment by adipose** [comment]
Thanks, I will review it.

**Comment by clsid2** [comment]
Looks like the contents of *.string.po somehow also ended up in *.menus.po

**Comment by adipose** [comment]
I see the problem, typo in the code.
