### ISSUE TITLE
Subtitle downloading bug in recent versions

### ISSUE THREAD

**Issue by gsapient** [clsid2/mpc-hc#518]
In recent versions, subtitle downloading for a file inside a rar shoots CPU usage through the roof for five minutes or more, until it self-aborts. The bug is in all 1.9.x versions. Version 1.8.8 doesn't have the problem.
Windows 10 x64 and x64 version of the app

**Comment by clsid2** [comment]
Give an example of a publicly available file that triggers the problem.

**Comment by gsapient** [comment]
I don't have a publicly available example, but it happens with all rar files for me, to one extent or another. I think it is worse the bigger the video file is. I have only tried multi-volume rars

**Comment by clsid2** [comment]
@adipose
Hash function for subtitle search reads a bit of data from beginning and end of file.

**Comment by clsid2** [comment]
Are you able to reproduce the bug with this version?
https://github.com/clsid2/mpc-hc/releases/download/1.9.6.7/MPC-HC.1.9.6.21.x64.zip

**Comment by gsapient** [comment]
Sorry for the delayed response. Yes the problem is still there.

**Comment by clsid2** [comment]
Send me a sample. If you can download it, then I should be able to as well. You can mail me torrent or nzb link where you got it from. I don't care if it is nsfw.

clsid2@users.sourceforge.net

**Comment by clsid2** [comment]
Fixed
