### ISSUE TITLE
[Low-Priority Req.] Make Subtitles dragable.

### ISSUE THREAD

**Issue by Uka-Uka** [clsid2/mpc-hc#519]
Hi, there!

I know that MPC-HC allows you to tinker with subtitles position, however, I see that it would come in handy if we can drag the subtitle with the cursor across the screen.

I suggest that the position of the subtitle should be locked across the X-axis while being freely moveable across the Y-axis.

**Comment by Uka-Uka** [comment]
Hey! why did this get closed?

**Comment by Uka-Uka** [comment]
@clsid2 May you reopen this issue, please?

**Comment by clsid2** [comment]
No. Subtitles can not be made draggable.
