### ISSUE TITLE
[Feature Request] Play next file in the folder before move the file to recycle bin

### ISSUE THREAD

**Issue by MaxSteven** [clsid2/mpc-hc#520]
The new features assign  "move to the recycle bin" to delete key is awesome.
But I think if there is an option in preference that we can select to play next file in the folder before deleting it,
It will be much more awesome.
This feature is great when you have 500 videos and need to filter which one to keep and which to delete just with MPC.
I hope you can consider it.
Thank you very much!

**Comment by clsid2** [comment]
If you add files to the playlist, then it already moves to next one after deletion. Simply select all files and drag them onto the player to quickly make a playlist.

Moving to next file in folder might be added later.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/620
