### ISSUE TITLE
H264 codec error

### ISSUE THREAD

**Issue by xcellor8** [clsid2/mpc-hc#521]
Some H264 encoded has a playback issue after seeking seeking forward or backward.
Version 1.9.5 works fine.

Video: MPEG4 Video (H264) 1280x720 23.976fps [V: English [eng] (h264 high 4:4:4 predictive L5.0, yuv444p10le, 1280x720) [default]]
![mkv_snapshot_00 49 500](https://user-images.githubusercontent.com/67846752/86523446-d2c39580-be6c-11ea-8eec-f32f0299e864.jpg)

**Comment by Aleksoid1978** [comment]
It's "bug" in ffmpeg.

**Comment by clsid2** [comment]
Do you have a link to an example video?

**Comment by xcellor8** [comment]
Video file can be found here:
https://www.dropbox.com/s/a9i9xljtxzckrrm/E591FB70.mkv?dl=0

**Comment by clsid2** [comment]
@nevcairiel

Might be a bug in the "x264_build" workaround in LAV Video. I tested and it seems that the av_opt_set_int() call doesn't have any effect, even when forcing a specific value.

**Comment by Aleksoid1978** [comment]
> 
> 
> @Nevcairiel
> 
> Might be a bug in the "x264_build" workaround in LAV Video. I tested and it seems that the av_opt_set_int() call doesn't have any effect, even when forcing a specific value.

Confirm.

**Comment by Nevcairiel** [comment]
The av_opt_set_int works fine. Its figuring out which value should be set that doesnt seem to work anymore.

**Comment by clsid2** [comment]
Fixed in latest LAV Filters.

It does however still gives corrupt video when resuming playback from a remembered position. Perhaps the x264 version data can be gathered during probing in the splitter?

**Comment by Nevcairiel** [comment]
Or perhaps people can re-encode their broken videos and we're done with this. :)
