### ISSUE TITLE
[Request] Play small files from memory

### ISSUE THREAD

**Issue by zoidbergthepopularone** [clsid2/mpc-hc#524]
Would it be feasible to add an option to load small files (with a configurable option on what "small" means exactly) into RAM completely, then close the original file and start the playback from the memory? Currently, if a file is being played, it's locked for non-read file operations, which can be quite annoying - e.g. I create an audio file, start playing it to make sure it plays fine, and I would love to edit its tags while playing, but can't because writing to that file is prohibited. Or I might start playing a sound file, decide that I like it but that I want it in another directory, but I can't move it without stopping the playback. Etc.

**Comment by clsid2** [comment]
That would need to be supported by the internal codecs, and that is not going to happen.
