### ISSUE TITLE
Requests:

### ISSUE THREAD

**Issue by LucianAndries** [clsid2/mpc-hc#525]
Hello!

May I have a few requests, please?

1. One would be to manually load subtitles by dragging and dropping. Yes, this works, but only for SRT files... Please make it work with all subtitle types, SRT, SUB, SSA, ASS, TXT, etc.
Dropping other types just replaces the video in the player. :(

2. Another one would be to always show the movie name/filename of the file, when making the controls show up in full screen. Sometimes I forget the name of what I'm watching, I hate exiting full screen and going to the TV to read the file...
Make it show exactly like when you first play the video.

3. I don't know if this is an issue, but the OSD is very dark. The Volume OSD numbers for example, are in a black box, and the number color is a gray instead of white.... In other words, it's unreadable. Is there a way to customize the OSD, color, size, what to show, etc? That would be a blessing! If not, then please make it more readable.
I do not use the dark theme...

4. The Download Subtitle window has a bug? Not all subtitles have the box where you check for download..... Despite showing it has the most downloads. Same server though.

5. In the Audio Decoder settings, can you please make this setting (Fallback to PCM, if Bitstreaming is not supported) be disabable? Anything I try, it just re-enables itself. Why is it even there, if we don't have the choice of not using it?...

Make it more TV friendly, even if it's running/playing on the PC...

Thank you for your time and hard work!

**Comment by clsid2** [comment]
1. Drag&drop works fine for .ass as well. You must enable the internal subtitle renderer!
Note to self: show error when people drag&drop with external renderer.
2. You can press N to show filename with OSD
3. There are some OSD font options here: Options > Tweaks
There will not be any more options, unless someone volunteers to implement it.
4. Make a screenshot
5. That will be fixed.

**Comment by LucianAndries** [comment]
Hey!

1. It is using the internal subtitle renderer. Try dropping a .sub file into a movie...
2. Can't, I'm in bed with just a mouse. That's why I said make it TV friendly...
3. I know about the OSD font. But what about the dark color? What about the black box? I know it's hard keeping up with every request. But maybe the community would like to contribute with a new OSD? A plugin even, that can be simply loaded like madvr, etc?
4. Ok, I added screenshot.
5. Thank you.

![No Box](https://user-images.githubusercontent.com/59364663/86836985-f5d98980-c0a6-11ea-836f-39c09abcf28a.png)

**Comment by clsid2** [comment]
1. Can you attach that .sub file? Then I can check why it fails to load.
2. Maybe I will add filename in status bar when in full screen. But it's low priority for me. To much stuff to do.
3. Others can always contribute improvements. But you can forget about plugin support or anything else complex. if you are using madVR, then the OSD is drawn by madVR, so you have to complain there. The OSD that MPC-HC uses for the other renderers has a light font.
4. I search for that same file and I get same two results both with working checkboxes.
@adipose, any idea what may cause this GUI glitch?
5. Fixed.

**Comment by Uka-Uka** [comment]
I believe it doesn't have the check box because it's already loaded

**Comment by LucianAndries** [comment]
Hey.

1. I just discovered they don't work at all, even if same filename as movie. None of them. Loading them manually replaces the movie, saying "cannot render the file"...
But but, they used to work.......... And I swear it uses the internal sub renderer. :(
I'm using:
MPC-HC (64-bit)
---------------
Build information:
    Version:            1.9.6 (0bd59bea7)
    Compiler:           MSVC v19.26.28806
    Build date:         Jun 25 2020
LAV Filters:
    LAV Splitter:       0.74.1.60
    LAV Video:          0.74.1.60
    LAV Audio:          0.74.1.60
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0
Operating system:
    Name:               Windows NT 10.0 (build 19041)
    Version:            10.0 (64-bit)
Hardware:
    CPU:                AMD Ryzen 7 2700X Eight-Core Processor
    GPU:                NVIDIA GeForce GTX 1080 Ti (driver version: 27.21.14.5148)

2. Thank you. Pff, non of it was urgent anyway. It was something for when you got bored. :p
3. I said plugins, coz i remember the old version used to have them. And I did have a plugin OSD. If only I could find that, but I don't even remember what it was called, early 2000s... I call "plugin" something external as madvr. But that's complex shit that needs an installer. It's so complex I HAVE NO CLUE how to change anything without breaking it... LoL
Someone recommended it for HTPCs... Should I really use it? :|
4. Umm, @Uka-Uka is right. The file was preloaded without even popping up the sub downloader. Now, if it could do that on its own for all of them..... Yeah, I'm a dumbass. I checked the loaded subtitle, and it said "podnapisi".
Ok instead, can you please move the "file -> subtitles" to "subtitle tracks"? Pretty please? It's kinda hard to press the shortcut keys from bed. It's not urgent either, but keep it in mind...

Well, thank you so far.

**Comment by LucianAndries** [comment]
1. I ran MPC as admin, still no. I removed the settings .ini file, still no. It has something about .sub files...
Here's a random not working sub, which I bet it'll work for you.

[Naruto - The Movie 3.zip](https://github.com/clsid2/mpc-hc/files/4892933/Naruto.-.The.Movie.3.zip)

**Comment by clsid2** [comment]
1 Fixed
3 There has never been a plugin for OSD. Nor would that be possible without major changes in the player. So not going to happen. It is possible to control the player through its web interface, and there are apps for Android that use that for remote control.
4 You enabled the option to automatically download subtitles. So it does exactly that when it found a good match.
Moving menu items is not going to happen. That would result in a million people asking why the option is no longer available. And no, people don't read changelogs (that mention moved stuff).

**Comment by LucianAndries** [comment]
1. There was an issue?? What was it?
3. Yes there has. But it was for the original MPC I think, not for MPC-HC. I remember something about an external/third party osd... Eh, whatever.
4. I see that now. Didn't know about it, or maybe I forgot... Yes, but it only works if there is a sub for this file name...
4.1 Which reminds me, is there a way to make the downloader show the sub's actual file name, instead of the movie currently playing? That way you know which one is better.
4.2 Then......I guess being in 2 places, is a no go too?

Thank you.

**Comment by clsid2** [comment]
1 The relevant parser wasn't tried for the sub extension.
3 You are confused with something else. Maybe the Logitech LCD keyboard support. Ancient versions did not have OSD at all.
4 No. File menu is for opening/adding stuff. The play menu is for the existing tracks.

**Comment by LucianAndries** [comment]
> 3 You are confused with something else. Maybe the Logitech LCD keyboard support. Ancient versions did not have OSD at all.

Nah, I know about that. There are some remaints about it, on doom9 and eventghost forums...
Doesn't matter now.

Thank you for the other fixes, though.

PS: Should I use madvr? Does it really DO anything?

**Comment by LucianAndries** [comment]
@clsid2 Hey!
How about this idea? Make the Subtitle Track list, scrollable with the mouse wheel.

I downloaded a movie that had a tone of subtitles for each country. I couldn't find my country so I had to scroll by pressing those tiny arrows....
Wouldn't it be better and easier to scroll this kind of stuff with the wheel?

Thanks!

**Comment by clsid2** [comment]
Menu is controlled by mouse pointer. I am not interested in complicating things with scroll wheel.

You can set preferred language(s) in the options. Then the desired track will be selected automatically.

This is an alternative for madVR that uses the standard OSD:
https://github.com/Aleksoid1978/VideoRenderer/releases

If you need HDR video playback capability then madVR or MPCVR is required. Otherwise you can also use the standard internal renderer (EVR-CP).

**Comment by LucianAndries** [comment]
> Menu is controlled by mouse pointer. I am not interested in complicating things with scroll wheel.
> 
> You can set preferred language(s) in the options. Then the desired track will be selected automatically.
> 
> This is an alternative for madVR that uses the standard OSD:
> https://github.com/Aleksoid1978/VideoRenderer/releases
> 
> If you need HDR video playback capability then madVR or MPCVR is required. Otherwise you can also use the standard internal renderer (EVR-CP).

I know how to set default dub and sub. But it did not take it auto, and it's not forced either. I haven't seen this before. Want a sample?
So yeah, scrolling by clicking is....

Oh, so madvr, etc are more for hdr video... Well, I don't have an hdr tv, lol. So I'm using it for nothing... If it's codec quality, the gpu is helping with that, right?
