### ISSUE TITLE
Calling youtube-dl asynchronously

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#528]
MPC-HC 1.9.6.21
When "Calling youtube-dl" all the interface freeze, it would be better to load it asynchronously.

Try to open in MPC-HC this: https://www.youtube.com/watch?v=c2mM5U-Z2u4&list=PL08MW4hWrm0Lrq8Y2mLHY7DEySlXDpDw0&index=2&t=0s

**Comment by clsid2** [comment]
I don't have time or interest for working on the youtube-dl functionality right now.

**Comment by ale5000-git** [comment]
It is important to keep track of bugs, but I don't expect it to be fixed in short time :)
