### ISSUE TITLE
[Request/Help] Set SWF background color

### ISSUE THREAD

**Issue by fullklax** [clsid2/mpc-hc#529]
Hi, first of all thanks for keeping this project alive. I was holding on the old 1.7.13 installer for the past few years because I saw devs stopped work on the original. Hadn't checked in a while, so I was surprised and glad to find out just now that a branch was still active. But I digress.

_- This is just some background to my issue, you can skip if you want:_
> I was looking online for a way to change the background color when playing Shockwave Flash files (default: black). The original issue tracker is down, so the couple posts I found about this are 404. And I failed to find where I can change it in-app, if it the feature exists.
> 
> I have a lot of old cartoons exported in SWF format (as well as interactive apps) that I've done in the past. However most of them don't have a solid background object. They're instead using the background value that I had set in Flash, which was white. Flash players used to see and use that value as a background, but MPC-HC doesn't appear to use it.
> 
> Since most of these cartoons are just lines without a background, you can imagine it doesn't look nice. And I don't have the .fla files anymore so I can't just go fix those myself. Because afaik, SWFs aren't editable. Well you can decompile them with some tools but it's a hassle to put them back together, that I'm not willing to go through (it's also not just about my cartoons, it's not an uncommon practice and I have a couple files not by me that also suffer from this).
> 
> Here's one with colored lines (so the content is visible) as an example: https://i.imgur.com/wGdcqo7.png It also showcases an object with a filling color that used to blend with the bg.
> 
> MPC-HC is wonderful in that it plays pretty much everthing on my PC, including SWFs. And it plays those quite well at that, had me really surprised when I found out not only it supported SWFs, but it has like, complete ActionScript support, buttons work and everything. I expected it to just play the SWF's timeline in one go, to ignore the code and nested clips and all that inside, but nope.

**Summary**: MPC-HC treats an SWF's transparent background as a transparent background, but doesn't use the background color value embeded within the SWF. With clips that rely on it, it breaks appearance.

So I wonder, is it already possible to change that background color? If not, I would humbly ask it to be added as a feature. Or even better, for MPC-HC to use the background color value already present within the SWF.

Thank you for reading, and here's hoping you consider my request.

_(sorry for writing a book, I have a really hard time keeping things formal...)_

**Comment by clsid2** [comment]
Attach a sample file that currently renders wrong. If you have one that uses a different color than black or white, attach that as well.

**Comment by lifegpc** [comment]
Here is a sample file which have this issue.
[动态书写文字.zip](https://github.com/clsid2/mpc-hc/files/4897008/default.zip)(Include swf and origin fla file.)
![image](https://user-images.githubusercontent.com/41434272/87044506-3103c600-c229-11ea-8486-313089ffffde.png)
Use flash player
![image](https://user-images.githubusercontent.com/41434272/87044619-614b6480-c229-11ea-90aa-1bce6e093472.png)
Use mpc-hc

**Comment by clsid2** [comment]
Fixed

**Comment by fullklax** [comment]
Oh wow that was quick, I'm just back from work sorry.

Can't wait to try it out, many thanks!
