### ISSUE TITLE
[Feature Request] Have playback speed save instead of resetting on exit

### ISSUE THREAD

**Issue by Aleonz00** [clsid2/mpc-hc#531]
I set it to 1.05x, exited MPC-HC, opened another video and it's back to 1.00x

It would be a great QOL improvement to have it save.

Thank you.

**Comment by clsid2** [comment]
It is supposed to reset at exit. That will not be changed.

If you play next file without closing, then speed is remembered.

**Comment by Aleonz00** [comment]
I completely understand why that wouldn't be good to have as a default setting. But what about having it as an option in the settings? Maybe "Remember Playback Speed" under Playback -> History. There's already seven options to remember other things there. 

Thank you for your time.
