### ISSUE TITLE
Thumbs bug

### ISSUE THREAD

**Issue by skot013** [clsid2/mpc-hc#532]
Incomplete display：
@clsid2 
![1](https://user-images.githubusercontent.com/43721178/87237561-6592a000-c42a-11ea-851d-a26de7d4edb8.jpg)

**Comment by clsid2** [comment]
Give link to that video file.

**Comment by skot013** [comment]
[bandicam 2020-07-13 06-03-23-613.zip](https://github.com/clsid2/mpc-hc/files/4909668/bandicam.2020-07-13.06-03-23-613.zip)
Not every time errors, the success rate is 80%. Many videos have errors. It's not just this one，The larger the video file (720p, 1080p, ), the greater the probability of error. Suggest to change to progress bar mode! Movie 4.36gb! Unable to upload. It may also be related to the performance of the computer. My friend's computer doesn't have this problem! He has a good computer, you can watch my video! No text, a blank, if your computer CPU, GPU is the best! Even for you! You still can't test it for errors

**Comment by clsid2** [comment]
Are the mistakes random, or are they always in the same place? So if you make thumbs two times for same movie file, are the images identical?

Try resetting settings:
Options > Miscellaneous > Reset

Right now I am not able to reproduce the problem. So I can't fix it.

**Comment by skot013** [comment]
Errors are random，Reset useless，clsid2 、Have you never been in this situation？ This mistake has been bothering me for years，If the first time fails, then the second time is also a failure（3.4.5.6 Times），Only by closing and re opening the player can succeed

**Comment by clsid2** [comment]
You are the only one with this problem. I don't know what is wrong, so I can't fix it.

**Comment by skot013** [comment]
I'll upload the movie later

**Comment by skot013** [comment]
I uploaded the movie，https://dropmefiles.com/a5gSX

**Comment by skot013** [comment]
@clsid2  I uploaded the movie ，I hope you can detect errors(download link:https://dropmefiles.com/9xETz)
thumbs The text style and logo are not the same as before

**Comment by clsid2** [comment]
![不可思议的融化人  The Incredible Melting Man BDrip 720P 1977 mkv_thumbs](https://user-images.githubusercontent.com/4704996/87672019-94827c00-c772-11ea-884f-ef7798b37f65.jpg)
Works normal here.

In your thumbs it looks like there are subtitles. Is that correct? Can you also include that subtitle file?

What filters are shown here? Menu > Play > Filters

**Comment by skot013** [comment]
I use madvr draw subtitles @clsid2  I use EVR There will be more thumbs errors，Only madvr reduces thumb errors!potplayer and MPC-BE thumbs no problem(Potplayer thumb success rate is 100%,MPC BE thumb success rate is 90%)!But I don't like those two Player style，MPC HC was the first player I used，Maybe your computer can't detect the error，Errors can be seen clearly only on old computers

**Comment by clsid2** [comment]
I can't fix this if I can not reproduce it.

It should not matter if your computer is old or slow.
