### ISSUE TITLE
Reported Frame Rate is incorrect when playing variable frame rate HEVC content 

### ISSUE THREAD

**Issue by warp16** [clsid2/mpc-hc#534]
MPC-HC 1.9.6 64-bit / Windows 10 x64 1909

When playing variable frame rate video, both the Statistics and CTRL+J reports weird values (hundreds or thousands) that does not update in real time like 'regular' non-variable frame rate video.

Also, there are inconsistencies in reporting in Properties>Details (reports 120fps) and Properties>MediaInfo (reports 29.970 FPS / 1.737 FPS Minimum / 40.053 FPS Maximum)

**Comment by clsid2** [comment]
MediaInfo only parses a small part of the file, so it can only estimate the framerate.
The info in properties comes from the mediatypes of the filter graph. They is no way it can display anything meaningful for VFR video.

Provide a sample file, and I can check is something is wrong with the stats. It is a calculated average, so for individual frames you have to look at the frame duration value.

**Comment by warp16** [comment]
Sorry for the delay. Video has been uploaded to the below URL.

[Video](https://mega.nz/file/M6IAFYSJ#oKp6Md6YasTtu_7NThCRz0sRCahccdAHFIMFTpNQXDc)

**Comment by clsid2** [comment]
As a temporary workaround you can change the video renderer to for example Sync Renderer.
Options > Playback > Output

**Comment by bibsp** [comment]
#2478 This is the same issue. And it is fixed.

> Sorry for the delay. Video has been uploaded to the below URL.
> 
> [Video](https://mega.nz/file/M6IAFYSJ#oKp6Md6YasTtu_7NThCRz0sRCahccdAHFIMFTpNQXDc)

I have tested with this sample also. It now reports correct fps. You can close the issue.
