### ISSUE TITLE
show buffering status while streaming/loading

### ISSUE THREAD

**Issue by wadawada** [clsid2/mpc-hc#537]
In vlc, a yellow bar will be shown when some content is being downloaded (it happens when you jump around at different time on the time toolbar)
I am wondering if a yellow progress bar or loaded percentage can be shown on mpc while streaming.
Currently, nothing will be shown while streaming is being loaded. I would really prefer some kinda prediction about what progress I'm at while I'm waiting for streaming

**Comment by clsid2** [comment]
The player can display buffering status when the source filter support that. The internal codecs (LAV Filters) does not support that. And it is unlikely that it will be added.
