### ISSUE TITLE
MPC-HC crashes when changing monitor (or when monitor is disconnected)

### ISSUE THREAD

**Issue by CodenameGreyFox** [clsid2/mpc-hc#538]
If I drag the window from one monitor to the other, it crashes. Same if I turn off the monitor or change which monitors are turned on.

This is the dump that is generated:
https://drdump.com/UploadedReport.aspx?DumpID=49059878

Running W10 LTSC, AMD Ryzen 5 3600X and RX 5700 XT.

**Comment by clsid2** [comment]
The crash happens in madVR.

@madshi

**Comment by madshi** [comment]
Yes, looks like a crash in madVR. Sadly, not enough information to be helpful. Maybe a different madVR build, e.g. this newer test build:

http://madshi.net/madVRhdrMeasure112.zip  (overwrite files of official madVR build)

Not sure if that will help, though.

**Comment by CodenameGreyFox** [comment]
Thank you for the replies. I tried that version you posted and here's the bug report (or at least part of it, but I think I got the important parts).

https://imgur.com/a/kyvbCOw

Is there any other info I can provide to help?

**Comment by madshi** [comment]
Thanks for the bug report. I'm planning to release a new build soon. Not fully sure if it will fix the problem, but I'll let you know when it's available.

**Comment by clsid2** [comment]
@madshi
Please don't forget about this crash, now that you are working on new madvr test builds.

https://drdump.com/Problem.aspx?ProblemID=587192&Login=guest (0.92.17)
https://drdump.com/Problem.aspx?ProblemID=587858&Login=guest (test build?)

Another crash issue:
https://drdump.com/Problem.aspx?ProblemID=587572&Login=guest
Here a WM_ACTIVATE message is coming from madvr while the player is shutting down and window is already destroyed. Remaining active threads are just madhcnet64.dll, so maybe related to your code to restore display mode? I will add a fix for this in MPC-HC to ignore the message, but it could maybe happen with other players as well.
