### ISSUE TITLE
MPC-HC crashes when you try streaming it to Discord

### ISSUE THREAD

**Issue by In1quity** [clsid2/mpc-hc#539]
Sometimes from the very beginning of the stream, and sometimes when you try to press one of the control buttons.
# How to repeat
1. Open video in MPC-HC
2. Open Discord
3. Start stream MPC-HC to Discord channel

**Comment by clsid2** [comment]
It is the fault of Discord. There is nothing I can do about it.

This may solve the crash:
Discord settings > Voice & Video > disable "Use our latest technology to capture your screen"

**Comment by In1quity** [comment]
It's pity, because the VLC player has no problem with this :( I will try to disable 'latest technology', thanks.

**Comment by clsid2** [comment]
Submit a bug report to Discord so they can fix their crappy software.

Give them this link with crash details:
https://drdump.com/Problem.aspx?ProblemID=587198
