### ISSUE TITLE
Timer resolution always set to 1ms for no reason

### ISSUE THREAD

**Issue by lastmetroid** [clsid2/mpc-hc#540]
MPC always sets a timer resolution to 1ms for no reason, also when video is paused or even stopped. This causes unnecessary battery drain on laptops.

**Comment by clsid2** [comment]
That isn't going to be changed.

Close the player if you are going to pause for a long time. It has an option to remember file position, so you can easily continue playback later.

**Comment by lastmetroid** [comment]
This is BAD behavior especially for laptops. It is obviously badly programmed and needs to be optimised. Why isnt it properly reset the timer when paused or even after STOPPED. Even a timer resolution of 1ms is NOT NECESSARY. VLC for example uses just 6ms even while playing.

**Comment by clsid2** [comment]
You are free to submit a patch if you think you can improve something. You will discover it is non-trivial.

I think many will disagree with you about low resolution being unnecessary.

**Comment by lastmetroid** [comment]
It is not trivial to set the timer back to idle if you pause/stop?

**Comment by clsid2** [comment]
Look at the code and you will find your answer.
