### ISSUE TITLE
Subtitle settings in HDR with madvr

### ISSUE THREAD

**Issue by bjorn-persson** [clsid2/mpc-hc#543]
Hi,

When using the latest versions of this mpc-hc build and madvr I cannot change subtitle settings for HDR content. The subtitles are extremely bright and so changing either color or transparency would be great, but for some reason this doesn't work. It does work in MPC-BE, but I don't like that player; it's very buggy. This makes me think this is an MPC-HC issue and not a madvr issue.

If anything could be done about this or if anyone has recommendations, that would be great.

Just noticed that it seems that I can change settings, but every time I open up a new file, without changing HDR mode on the screen, the subtitles reset to default brightness.

**Comment by clsid2** [comment]
madVR is responsible for tonemapping the subtitles in case of HDR video.
