### ISSUE TITLE
Subtitle Track->Reload is not works when use .sup subtitle.

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#544]
When load .sup subtitle. Subtitle Track->Reload is not works.
![image](https://user-images.githubusercontent.com/41434272/88175112-f7cf4b00-cc57-11ea-90d6-c7aeb4ba0eca.png)

**Comment by clsid2** [comment]
Why do you think it isn't working?
Why do you need to reload the file? This function is normally only used when editing text-based subtitles during playback.

**Comment by lifegpc** [comment]
Hmm. I modify the ass file and convert it to .sup file.
After reload it , I can't see the new content I added.

**Comment by clsid2** [comment]
Reload has not been implemented for PGS subtitles.

Enable the option to remember file position. Then you can press Ctrl+E to reload everything.
