### ISSUE TITLE
[Bug] Mpc-hc started with command-line argument "/fullscreen" + video (and "d3d fullscreen" enabled) cannot enter fullscreen second time.

### ISSUE THREAD

**Issue by demolitioner** [clsid2/mpc-hc#546]
Try to start mpc-hc with "/fullscreen" argument ("evr (custom)" and "d3d fullscreen" must be enabled), only the first time it will start normally. Double press alt+enter and it will not start fullscreen. Instead, it will start in some buggy mode.

If mpc-hc started in a typical way, it has no problem with fullscreen.

Both on win7 x64 and win10 x64.

**Comment by demolitioner** [comment]
1. Run mpc-hc with a command-line parameter containing "/fullscreen" and video. The "d3d fullscreen" option must be enabled, any renderer that supports it must be enabled - "evr cp", "vmr9 renderless", "sync".
2. Double-click alt+enter to alternately exit and enter to full-screen mode a second time.
3. mpc-hc will not enter fullscreen mode a second time. Instead, it will create a empty window blocking the screen, without displaying the video.
4. if you run mpc-hc from the desktop shortcut and not from the command line, the bug will not be observed, and re-exit-enter to fullscreen via alt+enter will work fine.

In the test version 1.9.7.44 from 4 sep 2020, the bug is still not fixed.

**Comment by demolitioner** [comment]
MPC-BE 1.5.7.6021 does not have this bug. It can reenter fullscreen any quantity of times when evr custom + exclusive fullscreen enabled.

**Comment by clsid2** [comment]
Try 1.9.20.46 development build.

**Comment by demolitioner** [comment]
I tested it. At first, switching back to full screen did not work, but at some point there was a "sound" of windows, and when the videos was opened again, switching back to full screen mode began to work for d3d. I will test more.

**Comment by demolitioner** [comment]
I tested it again. As it turned out, after restarting the computer, switching back to full-screen mode again does not show the video, but only the player's interface. Perhaps I should wait again for that windows "sound" at the beginning of some video playback, so that subsequent videos could switch back to fullscreen mode again.

**Comment by clsid2** [comment]
The Windows sound might be the graphics driver restarting after a crash. Maybe something is logged in the Windows Event Log.

I would really recommend to just disable D3D fullscreen. There is now an option to have separate controls even with normal fullscreen on another monitor.
