### ISSUE TITLE
option to customize status bar

### ISSUE THREAD

**Issue by wadawada** [clsid2/mpc-hc#547]
I'm trying to find a way to show playback speed on the status bar because it takes too much space to show the current rate and status on more than 1 bar
I don't need the rest of the statistics because I'm only altering the rate during playback

Can you allow users to add playback/frame rate on the status bar? thanks
example:
▶⏸️⏹️|⏮️
Playing[H/W]　30.29(1.50x)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/830
