### ISSUE TITLE
About translations

### ISSUE THREAD

**Issue by Felipefpl** [clsid2/mpc-hc#55]
Hi, sorry to use this to make a question but github has no system to exchange msgs, i wanna know where i go to translate mpc-hc to pt_BR? There is no info in the main page about that, i already went to transifex and put myself in the list to translate it but the page is inactive. If there is another way i'll put the translation here if you dont mind.

**Comment by Felipefpl** [comment]
Thanks for the replay clsid2, i'll admit i didnt download your version of mpc but i'm digging it. I translated/fixed all 4 files i found, i wish github allowed to organize them by date to make search less annoying though.

I have a request for you, below you can see a pic i took with mpc 1.7.13, as you can see in the left side a phrase cant be seem and in the right side phrases arent fully displayed because of how small the settings window is, please make it 30% or 40% larger so the words can be seem, remember that in other languages the translated words/phrases are bigger than in english. ;)

http://www.hostpic.org/images/1812260109370110.gif

[Pt-br.zip](https://github.com/clsid2/mpc-hc/files/2709009/Pt-br.zip)

**Comment by clsid2** [comment]
I am not going to change the Window size. If translations are too long, make them shorter. Use "CD" instead of "CD de Audio". Use "extensao" instead of "extensao de arquivo".

**Comment by Felipefpl** [comment]
ok, not much of a show-stop, you can submit the files anytime as you wish. ;)

**Comment by Felipefpl** [comment]
I noticed you still didnt submit the file, is there any problem with it? :|

**Comment by clsid2** [comment]
Each changed entry has a useless comment above it. Please remove those.
When increasing the length of a translation, check if there is enough space for it in the GUI. Mainly for things in the settings dialog.
Long translations are broken into multiple lines in your files. Please use single line like in original as it may break compilation.
