### ISSUE TITLE
Cannot search for subtitles.

### ISSUE THREAD

**Issue by bukakow** [clsid2/mpc-hc#550]
I have just updated my MPC-HC from official abandoned version to 1.9.6 and the searching does not work anymore.
No results at all.

**Comment by clsid2** [comment]
Subtitle search/download using OpenSubtitles now requires a login. You can create a free account on opensubtitles.org website. After that, you can configure it here: MPC-HC options > Subtitles > Misc > Right-click on OpenSubtitles > Setup
