### ISSUE TITLE
When mpc-hc is opening a video, open another video in the playlist will cause mpc-hc to crash.

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#553]
Crash Information:
![image](https://user-images.githubusercontent.com/41434272/88651277-19b74a80-d0fc-11ea-8f95-5d7ee0f8aa72.png)

**Comment by lifegpc** [comment]
More detailed crash information：
https://drdump.com/UploadedReport.aspx?DumpID=49306057

**Comment by lifegpc** [comment]
It seems works fine when I use version 1.9.6.36(014f54fb3).

**Comment by lifegpc** [comment]
It seems happens again.

**Comment by adipose** [comment]
Can you make a video of it happening?

**Comment by clsid2** [comment]
Give new DrDump link.

**Comment by lifegpc** [comment]
After kill mpc-hc (because of its no response), I can't see DrDump crashreporter works. ( I am sure I enable crashreport in settings.

**Comment by lifegpc** [comment]
It seems only  occured when disable Hardware decoder

**Comment by lifegpc** [comment]
~~Strange things happended. It no response but the status in windows are running.(I can not see no response on window title)~~ Now I can see no response on window title.
![image](https://user-images.githubusercontent.com/41434272/99671433-fc442d00-2aac-11eb-9695-cc2e6e846b6b.png)

**Comment by lifegpc** [comment]
Try made a [dump file](https://1drv.ms/u/s!Aoq8mAMlVv8UnV2vs3kWc8i5fplx?e=2EMAhn). But I think it is useless because when I open it in vs2019, it tell me it can not find exceptions.

**Comment by clsid2** [comment]
It hangs while waiting for a lock. Weird thing is that the thread that owns the lock no longer exits.

CGraphThread::OnClose -> CMainFrame::CloseMediaPrivate() -> CAutoLock cAutoLock(&m_csSubLock);

**Comment by clsid2** [comment]
PDB files:
https://www.sendspace.com/file/lgtfku
