### ISSUE TITLE
Struggling when playing video while the monitor is in portrait mode

### ISSUE THREAD

**Issue by Voidrays** [clsid2/mpc-hc#559]
Hi.

![Cap 2020-08-02 15-12-14-404](https://user-images.githubusercontent.com/38346753/89116748-a1bd9b80-d4d2-11ea-8852-2d5a7927f3d4.png)

For example, in the normal case, if my monitor has a resolution of 2560x1080 (Width, Height) and it is in Portrait mode (Vertical mode), it will be 1080x2560 (Width, Height).

After switching the resolution of the desktop to Portrait mode, all the videos on the MPC-HC are struggling.

For example, https://www.youtube.com/watch?v=w97bB1j-dcY

This video playback works well anytime, regardless of Portrait mode when playing through a web browser.
But if I plays the video file(downloaded) with MPC-HC, then video frames struggles and lagging. Of course in landscape mode, the video file playback doesn't have any struggle problem.

![Cap 2020-08-02 15-38-18-701](https://user-images.githubusercontent.com/38346753/89117123-47263e80-d4d6-11ea-9a65-ea3a164c0d01.png)

I tried to fix it up by changing DirectShow Video renderer to Default and EVR from EVR(custom). In result, it has no problem with frame issue but has problem with dxva, subtitle support since it doesn't support these things.

So here is problem summary.
Problem: Struggling when playing video while the monitor is in portrait mode.
Version: MPC-HC 64-bit 1.9.6
Video: Any video.
Video resolution: Resolution does not matter.
Video ratio: It doesn't matter whether it is width-long or height-long.
Other program try: Potplayer(EVR custom), has no problem for frames, subtitle, dxva...

What other options to I can try and can it be improved?
I don't know much of the technic advanced options, so I haven't changed anything except the renderer.

**Comment by clsid2** [comment]
In the setting of LAV Video decoder, try changing hardware acceleration from DXVA2 Native to DXVA2 Copyback.

**Comment by Voidrays** [comment]
> In the setting of LAV Video decoder, try changing hardware acceleration from DXVA2 Native to DXVA2 Copyback.

Thanks for the reply. But did not work.

**Comment by clsid2** [comment]
And with hardware decoder = NONE ?

**Comment by Voidrays** [comment]
> And with hardware decoder = NONE ?

Yes. That also does not work. However can't it be reproduced on your computer?

**Comment by clsid2** [comment]
Try with VSync enabled for EVR-CP. Press V.

**Comment by Voidrays** [comment]
> Try with VSync enabled for EVR-CP. Press V.

Good. Now it works great when Vsync disabled. Do you consider it as a bug or problem?

**Comment by clsid2** [comment]
It is not something I can fix. Bug is most likely in the driver. It works with and without VSync on my system. NVIDIA driver 442.74 here.
