### ISSUE TITLE
[Request/Info] silent installer

### ISSUE THREAD

**Issue by aureq** [clsid2/mpc-hc#56]
Hi @clsid2 

Thank you very much for the great work you've done on mpc-hc. Maybe a bit of information request and a feature request there.

I'm integrating mpc-hc into my Win10 ISO to make my life easier. I found a switch `/verysilent` ([link](https://www.manageengine.com/products/desktop-central/software-installation/silent_install_Media-Player-Classic-Home-1.7.8-(x86).html)) that seems to do the job but I can't find any reference to it into the code. I'm curious to understand if the installer has other useful switches I could leverage ?

Alternatively and as a feature request, would you have any interest in providing a customised and automated install like it's done with the [Firefox Installer](https://wiki.mozilla.org/Installer:Command_Line_Arguments)? It could be great to have the ability to tweak on mpc-hc is installed.

Thank you and Merry Christmas.

**Comment by clsid2** [comment]
The installer uses InnoSetup, so you can use these switches:
http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline

I have no interest in making any changes to the installer.

**Comment by aureq** [comment]
@clsid2 Thanks for the details. That's exactly what I was looking for.
