### ISSUE TITLE
[feature request] Use http_headers when playing video by youtube-dl.

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#564]
Some video/audio url returned by youtube-dl need to use http_headers to open it.  
Such as videos from bilibili.com .
![image](https://user-images.githubusercontent.com/41434272/89390308-172aa580-d739-11ea-9886-6788b9b2797d.png)

**Comment by clsid2** [comment]
For passing parameters to youtube-dl you can use a configuration file:
https://github.com/ytdl-org/youtube-dl/blob/master/README.md#configuration

If playback of an extracted url requires a certain user agent, then that must be implemented in LAV Splitter. There already is an open feature request for that.

**Comment by clsid2** [comment]
I have added a patch to use Mozilla Firefox user agent. The site above now works in MPC-HC.

**Comment by SlazE888** [comment]
> I have added a patch to use Mozilla Firefox user agent. The site above now works in MPC-HC.

Does LAV v0.74.1-77 and newer versions contain an innovation? Where I can download this patch?

**Comment by ale5000-git** [comment]
@SlazE888: If I'm not wrong the LAV inside K-Lite Codec Pack is modified to use another User-Agent.

**Comment by clsid2** [comment]
No, both use standard user-agent from FFmpeg. The patch to use custom user agent was removed long ago already because it caused problems.

**Comment by ale5000-git** [comment]
Why not use the same User-Agent of youtube-dl?
I guess it is the one that works on most sites: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3680.0 Safari/537.36`

**Comment by lifegpc** [comment]
Now I modify youtube-dl's source code and add a proxy to it :(
I can specify any headers on that http/https proxy.

**Comment by ale5000-git** [comment]
> The patch to use custom user agent was removed long ago already because it caused problems.
Hi,
do you remember what problems?
Maybe the problems no longer exist in 2021.
