### ISSUE TITLE
[Feature request] ASIO support

### ISSUE THREAD

**Issue by David-H-1** [clsid2/mpc-hc#565]
I am an audiophile and I am looking forward for a video player with exclusive output audio ASIO support. I Googled all around the web and have come up with no solutions.

All the modern DACs and high-end headphones use ASIO driver instead of the general driver. The normal audio output goes through the Windows Volume Mixer. But ASIO "talks" directly to the device driver, which significantly reduces audio latency.

I hope that there will be a video player that offers ASIO support, even if it is paid.

Please consider to devlelop this feature, if possible. (Or add it as a paid feature)

Thank you.

**Comment by clsid2** [comment]
The internal audio renderer supports WASAPI exclusive mode output, and can also bypass the Windows mixer to give bit-perfect output.

There exists a third party "DirectShow ASIO audio renderer" as well. You can waste your money on that.

**Comment by David-H-1** [comment]
> The internal audio renderer supports WASAPI exclusive mode output, and can also bypass the Windows mixer to give bit-perfect output.
> 
> There exists a third party "DirectShow ASIO audio renderer" as well. You can waste your money on that.

Why do you say "to waste my money on that"?

**Comment by clsid2** [comment]
Because you seem to expect that ASIO will improve things. There is a good chance it won't and that you will be disppointed. Are you actually having any issues right now?

WASAPI also has low latency.
