### ISSUE TITLE
[Feature request] Continue playback of previously played media

### ISSUE THREAD

**Issue by minhngoc25a** [clsid2/mpc-hc#569]
Could you add a button to continue playing the part I left off?

Example: 
![image](https://user-images.githubusercontent.com/33834488/89698967-449c6c80-d94e-11ea-8ce9-a86d1df138a8.png)

**Comment by clsid2** [comment]
That is already possible.
Options > Player > Remember File Position

Then open the player and simply press Play to open the last played file.

**Comment by minhngoc25a** [comment]
@clsid2 Ok, thanks for helping. I think you should set it as the default option in the next version.
