### ISSUE TITLE
[Feature request] webp static images

### ISSUE THREAD

**Issue by alidan** [clsid2/mpc-hc#571]
I download videos/music from youtube, I get the thumbnail and I get the music file. 
I have encountered a few where they saved as webp 
with jpg, what most of them saved as, there is no issue for the same file name's showing a small image isntead of a blank media player, however something tells me google will end up converting that to webp sooner or later. 

would it be pos

sible to get mpchc to display the webp while the associated file plays or is that something not possible? 

![chrome_2020-08-08_00-56-41](https://user-images.githubusercontent.com/2681758/89703630-0c773880-d912-11ea-8360-542247d85561.png)

its not a big difference, but is nice to have something to see when a file plays.

**Comment by clsid2** [comment]
There are no plans to support webp coverart.
