### ISSUE TITLE
[Feature request] Ability to send webhook at startup and changed of media playback state

### ISSUE THREAD

**Issue by MattL0** [clsid2/mpc-hc#572]
I currently poll the webapp like crazy... it would be nice to get the info we need in the form of a webhook, or with mqtt. 

- When the app start send idle 
- When the app start playing something send play
-  same for pause.
-When the app exit send idle or wtv you want ( with mqtt you can send a last will message ) .

Mpc-hc is inmy opinion the best video player. Having push notification would be very nice.

**Comment by clsid2** [comment]
There are plenty of developers who use the web interface. They should submit patches for improvements. I am not interested in working on it.
