### ISSUE TITLE
Better speed changing algorithm 

### ISSUE THREAD

**Issue by megapro17** [clsid2/mpc-hc#574]
The current algorithm sounds bad
It's done in mpv, so this shouldn't be too hard to port it https://github.com/mpv-player/mpv/pull/7865
Or it's needed to wait when that change will be in ffmpeg, and then it will appear in lav filters?

**Comment by megapro17** [comment]
Wait, actually in mpc-be it is sounds okay, maybe you can check that there?

**Comment by clsid2** [comment]
Options > Playback > Output > Audio Renderer > Internal Audio Renderer

That has audio pitch correction ability for when video speed is changed.

**Comment by megapro17** [comment]
yes, i selected this before opening issue.

**Comment by Kilohertz77** [comment]
The pitch correction on the Internal Audio Renderer started working after a restart.

**Comment by Mottie** [comment]
Can we get this to be the default setting?
