### ISSUE TITLE
File lock persistent after closing media file (Ctrl+C)

### ISSUE THREAD

**Issue by Wille-Helm** [clsid2/mpc-hc#575]
This issue is not present in MPC-HC x64 v1.9.4, but all versions after that (v1.9.7 to date).

If I open a file and close it (Ctrl+C or via menu), I cannot rename or move that file anymore. This worked flawlessly until v1.9.5.
The only way to do so is to close MPC-HC completely or load another file.
It does not matter on which source drive the media file resides (local/NTFS, NAS/EXT4).

I'm using Win10 1909 x64.

If you need any more information, please ask!

PS: Thanks for keeping up the good work with MPC-HC, my one and only media player. :)

**Comment by clsid2** [comment]
Fixed.
