### ISSUE TITLE
m3u8 infinite loading problem

### ISSUE THREAD

**Issue by wadawada** [clsid2/mpc-hc#576]
[test link](https://www.chifenghualvlvxingshe.com/20190623/WL3MAR1Y/index.m3u8) will work if I put it in [here](http://www.hlstester.com/new-hls-player/?url=https://www.chifenghualvlvxingshe.com/20190623/WL3MAR1Y/index.m3u8)

put the link in mpc and "opening..." will be flashing nonstop

I know I can use ctrl+c to stop it but I would like the see the stop button working too considering it is loading and there is no UI to stop it

**Comment by clsid2** [comment]
Fixed.
