### ISSUE TITLE
playing current file stops after "move to recycle bin" another file from playlist (1.9.7)

### ISSUE THREAD

**Issue by pnepus** [clsid2/mpc-hc#577]
after upgrade to 1.9.7 
strange behavior started

example 
playlist contains 3 files
file_1.mp4
file_2.mp4
file_3.mp4

file file_3.mp4 played

playlist opened (ctrl+7)

in playlist select file_1.mp4 and use "move to recycle bin"
 
after that
playing file_3.mp4 stopped 
and started playing next file after deleted (file_2.mp4)

**Comment by adipose** [comment]
Maybe related to this?

https://github.com/clsid2/mpc-hc/pull/380

**Comment by clsid2** [comment]
I will look at this issue later this week.

**Comment by adipose** [comment]
OK, I will not work on it, then!

**Comment by clsid2** [comment]
Fixed
