### ISSUE TITLE
Feature request: add more encoder options

### ISSUE THREAD

**Issue by gbcat** [clsid2/mpc-hc#58]
I want to record some VHS videos through USB video captures. But there are only a few encoder options in current version, and also I cannot find a way to set the parameters (e.g. bitrate) of them. I hope you can add more encoders, such as x264 and NVENC.

**Comment by clsid2** [comment]
It supports DirectShow/DMO/VFW type encoders. For encoding H.264 you can use x264VFW codec.

Or you can capture using a lossless codec such as Lagarith, and then convert to another format later with a conversion tool of your own choice (such as Handbrake).
