### ISSUE TITLE
Subtitles not working after 1.9.6

### ISSUE THREAD

**Issue by CraigerHoneywell** [clsid2/mpc-hc#580]
Was running 1.9.2 with normal options for subtitles (enhanced video renderer (custom presenter), internal subtitle renderer) and subtitles work fine.  Upgraded to 1.9.6 and subtitles no longer work.  Option under PLAY is greyed-out.  "Load Subtitles" under file finds the file (.srt) but has no effect otherwise.  Went back and tried earlier releases; subtitle work through 1.9.5.  1.9.6 and 1.9.7 don't work, so something obviously changed.  All option settings were constant across all releases.  Tried various troubleshooting suggestions with no effect, so something is different.  Thought you should know.  I will run 1.9.5 until this is fixed.

**Comment by clsid2** [comment]
Try this version:
https://github.com/clsid2/mpc-hc/releases/download/1.9.6.7/MPC-HC.1.9.7.22.x64.zip

If that also does not work, then attach the .srt file here.

**Comment by cajhin** [comment]
r1.9.7 external subtitles work for me, with various tested videos.
(Note: had to activate menu > Subtitle Track > Enable; I usually never touch that, but that's anecdotal)

**Comment by CraigerHoneywell** [comment]
Sorry, 1.9.7.22 does not work either.  I have attached the .srt file.  It is not a single

video that does not work.  No videos with .srt external subtitles display them and the

play -> subtitle track option is greyed-out.  And this does not change if I load the subtitles

manually from the file menu while the video is loaded.

**Comment by CraigerHoneywell** [comment]
Thanks for the response.  I had another reply giving me a copy of 1.9.7.22 which did not work either so

I sent back the .srt file.  It was not just one video; no video with external subtitles displayed them.  And

of course, I can activate Subtitle Track because the option is grayed-out.  As I pointed out in the issue,

release through 1.9.5 do work on all videos and Subtitle Track is usable in the menu, as you would expect.

It seems that something was lost at the 1.9.6 release, which did not work correctly.

**Comment by clsid2** [comment]
It is working fine for me and others. I don't know what is wrong.

Try resetting settings:
Options > Miscellaneous > Reset

**Comment by CraigerHoneywell** [comment]
Did Miscellaneous -- Reset.  Did not affect the problem.  The fact that the Subtitle Track menu item is

grayed out would seem to mean it does not think there is a subtitle file.  Yet it is willing to do a Load Subtitle,

but afterwards Subtitle Track is still grayed out, so it would seem it still does not think it has subtitles.  I

understand what you are saying about it working for others, but then why does 1.9.5 and below work properly and

not 1.9.6 and above?  Something is apparently not being processed the same in the newer versions.   Is there a log file any place that might trace what it is doing?

**Comment by CraigerHoneywell** [comment]
Ok, I found the log option under Advanced Options and turned it on.  Triend 1.9.7.22 again

and it created a single entry in subtitles.log:


16:33:26.233 - OpenSubtitles::LogOut: () (Z:\github\clsid2\mpc-hc\src\mpc-hc\SubtitlesProvider.cpp:126)


Don't really know how to interpret this.  Hope it is useful.

**Comment by CraigerHoneywell** [comment]
Oh, and I thought I'd see what 1.9.5, which works, logs.  Well, it just added the same entry to the log.

So, I don't know how much help the log is, unless there are some other options we can set.

**Comment by clsid2** [comment]
There is no logging for subtitle loading.

Upload one of your .srt files here (or somewhere else). Then I can test with the exact same file as you.

**Comment by clsid2** [comment]
If I can reproduce the issue with a example file, then it will be fixed immediately.

**Comment by CraigerHoneywell** [comment]
I have sent an example file in response to two replies from clsid2.  Don't know if this is the same person each time, or if it is a group id.  Did they arrive with the replies?

**Comment by lifegpc** [comment]
@CraigerHoneywell  I can not see file on Github.

**Comment by clsid2** [comment]
You are replying per e-mail. E-mail attachments are not shown here. They are ignored by Github. Reply through the website.

**Comment by CraigerHoneywell** [comment]
OK.  Didn't know that.  By the way, keep in mind the following:

1.  No videos accompanied by .srt subtitle files display subtitles or the subtitle track option.

2.  I was able to run an api-monitor trace.  It did show the subtitle file is being opened and gets a

file handle.  What it does with the data?

3.  The subtitles and Subtitle Track option work correctly on:


a.  MPC-HC up to 1.9.5

b.  MPC-Black Edition

c.  VLC Media Player

So it would appear the file is good, but not being processed correctly.  Let me see if I can add the

sample file to the website.  

Thanks.

**Comment by CraigerHoneywell** [comment]
That's because I sent via the e-mail reply.  I just got a reply from CLSID2 saying GitHub ignores attachments

and I must place it on the website directly.  I shall try to do that asap.

**Comment by lifegpc** [comment]
@CraigerHoneywell  You can open https://github.com/clsid2/mpc-hc/issues/580 in your Browser and upload file through webpage. You may need compress your files as ZIP file.

**Comment by CraigerHoneywell** [comment]
[The Datsun_Nissan Z Cars Story.txt](https://github.com/clsid2/mpc-hc/files/5097376/The.Datsun_Nissan.Z.Cars.Story.txt)

**Comment by CraigerHoneywell** [comment]
OK, check now.  I had to rename it as a .txt file because GitHub wouldn't let me paste a .srt file.  Just rename it back.

.srt file are plain text anyway.  If it works for you this is very strange.  BTW, this is on Windows 10 2004, plus I have a Windows Insider version which is the next version, but it doesn't work there either.


Thanks

**Comment by lifegpc** [comment]
This is a WEBVTT file and not a srt file.
The internal WEBVTT may not work. (#354 )

**Comment by clsid2** [comment]
Rename it to .vtt and it will load.

I will fix it to also allow .txt and .srt extensions for WebVTT.

**Comment by CraigerHoneywell** [comment]
OK.  I saw the WEBVTT in the text, but of course don't know its significance.  I looked at issue #354.  The accompanying videos file is .mp4, it was not packaged as a .mkv file.  Also, that issue refers to the LAV splitter not handling embedded WEBVTT files, but this is of course an external file.  And of course there is the fact that MPC-HC did handle this file correctly until 1.9.6.  So maybe a change was made to 1.9.6 based on issue #354 that is causing this failure?  BTW the video came from YouTube.  I checked another which wasn't display subtitles and its .srt file is WEBVTT also, so this appears to be a common packaging


OK, armed with what you told me, I did a little research and found that WEBVTT and SRT files are quite similar, and WEBVTT files are like a superset of what SRT provides.  So I experimented a little bit.  I took the .srt file and removed the first 3 lines which were WEBVTT info.   Well, it still didn't display the subtitles, but the Subtitle Track Menu option was now enabled.  A little bit more research showed that SRT files need line numbers in front of the timestamps, whereas apparently WEBVTT files don't need them.  So I added line numbers to the first several captions....and it worked.  MPC-HC 1.9.7.22 does display the subtitles if the format is true SRT.    OK, so it used to handle WEBVTT files as SRT files until 1.9.6.  Any way to get this working again --- it would be a lot of work to edit a large WEBVTT file in this fashion to fix it, so is there any hope?


Thanks.  At least we know why it is being skipped and that it can work.

**Comment by CraigerHoneywell** [comment]
It did!  Renaming it to .vtt fixes the issue.  So MPC-HC actually can handle it if the file extension is correct.  So the packager should have used the right file extension in the first place.  That workaround and your suggested fixes are simple.  Thanks for looking at it and I learned a few things from the issue.
