### ISSUE TITLE
Audio out of sync on some mp4 files

### ISSUE THREAD

**Issue by damjang** [clsid2/mpc-hc#581]
I want to warn of a problem of audio out of sync on some mp4 files (e.g. downloaded from facebook). With mpc audio is out of sync, but if I try to play the same file with eg. vlc audio is synced. Here one test file: [test_audio_sync.mp4](http://www.damjan.net/tmp/test_audio_sync.mp4). Btw I'm on win7 x64...

**Comment by clsid2** [comment]
Audio seems in sync here.

**Comment by damjang** [comment]
Hm, I try again with x86 and x64 version but audio was always out of sync. Then I try to reset the mpc settings and now audio is in sync.
btw is there an option to use settings from ini file (portable version) and not from reg?

**Comment by clsid2** [comment]
Options > Player > Store settings in .ini file

This option does not work when installed in Program Files folder or other 'protected' Windows folders. Only when the folder is writable.
