### ISSUE TITLE
Force Max DTS-HD Rate always On

### ISSUE THREAD

**Issue by syffer72** [clsid2/mpc-hc#582]
Hello,

Since 1.9.7 the feature "Force Max DTS-HD Rate (not recommended)" available in Intern filters -> Audio Decoder,  is always enabled, even disabling it and saving don't make it happen.
I'm normaly bitstreaming every audio format to my amp but this feature breaks classic DTS bitstreaming, (no sound detected). DTS-HD is still working though.
Already tried a full parameters reset with no success.
Rollback to 1.9.6 solved the problem.
Under is 1.9.6 correct panel working, just for reference.

![Capture](https://user-images.githubusercontent.com/54261260/90441292-ff5c0580-e0d8-11ea-8475-af63fdbb8a73.PNG)

**Comment by clsid2** [comment]
Fixed
