### ISSUE TITLE
Two minor issues, I probably just need "HowTo" advice.

### ISSUE THREAD

**Issue by Catfisher122** [clsid2/mpc-hc#585]
I'm not seeing how to clear the Playlist after an album plays.  I 'drag & drop' the list of songs from its' folder onto the playlist or I open the folder through the Directory option. The songs play great, but how do you remove that list of songs to choose another folder?  In Winamp I would click on File, Select All, then select Remove.  All I seem to do here is delete the songs one at a time.  How should I remove the songs that finished playing?

Also, I notice the Playlist on shows the length of each song as it starts to play. The list of songs that have not played yet do not show how long they will be.  Is there a way to show the length of all songs on the list when they are added to the Playlist?

That would be very helpful in selecting the songs that will fill a time frame.

Thanks for all help.

**Comment by clsid2** [comment]
Menu > View > Playlist
You can right-click on the playlist to get a menu with clear option.
You can also just drag&drop a new selection onto the player window to create a new playlist. Tip: if you hold Ctrl while dropping, then files are appended to existing playlist.

It is not possible to get durations without opening the files.
