### ISSUE TITLE
Precomposed ellipsis and ANSI encoding

### ISSUE THREAD

**Issue by CrazyFrogSLO** [clsid2/mpc-hc#59]
If subtitles are encoded in ANSI format then Precomposed ellipsis (three dots as one character) is not always displayed. It works fine if subtitles are encoded in UTF-8 format. It also works in some other players like SMPlayer, VLC or old MPC. But some players, including yours, have some problems.

Example:

```
1
00:00:00,000 --> 00:01:00,000
A) Text … text
B) <i>Text …</i>
C) Text …
```
Precomposed ellipsis is displayed in case **A)** and **B)** if there is something after the ellipsis, but it's not displayed in **C)** case. [https://drive.google.com/file/d/0B8fWfubhb52fekZicUF3WDZhUGxIclZIVVdYZnJrNWxhMno0/view?usp=sharing](https://drive.google.com/file/d/0B8fWfubhb52fekZicUF3WDZhUGxIclZIVVdYZnJrNWxhMno0/view?usp=sharing)

I don't know what could cause this problem/bug? I tried different players, some have this problem, some don't. I have Win 10 Pro 1803 if this is somehow related.

**Comment by clsid2** [comment]
Unicode encoding is required for such characters to be displayed correctly in all cases.

**Comment by clsid2** [comment]
I have checked old versions and it got broken by the move from Visual Studio 2013 to 2015/2017. The ellipsis character is now treated as a whitespace character, so it got trimmed off. I will apply a fix.
