### ISSUE TITLE
[Feature Request] Have "Goto Prev/Next Subtitle" Follow Current Playing State

### ISSUE THREAD

**Issue by MadokaAyukawa** [clsid2/mpc-hc#590]
Currently the "Goto Prev/Next Subtitle" function will automatically pause the video. It would be nice if it would follow the current playing state, so if the video were already paused, Goto Prev Subtitle will jump to the prior subtitle and stay paused, but if the video were playing, then it jumps back but stays playing. I use this feature when I need to re-read a subtitle for whatever reason when watching something, but the fact that it pauses the video makes it much less useful.

**Comment by MadokaAyukawa** [comment]
It appears that this feature doesn't work that well currently. When it does, it seems to go to the first subtitle, and for some files with internal subs, it doesn't seem to work at all.

**Comment by clsid2** [comment]
In case of internal subtitles only a small part of the whole subtitle stream is a available at a time. The Subresync functionality is designed for external subtitles.

**Comment by MadokaAyukawa** [comment]
Thank you for the explanation. I will stick to using external subtitles with this feature and would be happy if it could follow the currently playing state.

**Comment by clsid2** [comment]
Done

**Comment by MadokaAyukawa** [comment]
Thank you for implementing this. But in 1.9.15.20, going forward is ok, but going back only goes back to the most recent subtitle; you can't go further back, unless you skip by time, not by subtitle. This is with the video playing, it's as if since it's playing the currently displayed subtitle is always the most recent. If I pause the video, it works like before.

**Comment by clsid2** [comment]
That is the consequence of not pausing. If you want to go back further you must pause. This is the reason why it used to pause.

**Comment by MadokaAyukawa** [comment]
I see. Could there be a check such that if the Goto Prev Subtitle hotkey is pressed, it checks to see if the current time is within 1.5 seconds of the start of the current subtitle, and if so, it jumps to the previous subtitle. This should also work if the video is paused.

If not, that's fine, but then the previous implementation where it automatically pauses the video is better, as, right now, you can't go back to a prior subtitle unless you pause it first, and that's an extra step from before.
