### ISSUE TITLE
MPCHC seems to be calling something even when paused that causes CPU voltage spikes.

### ISSUE THREAD

**Issue by code-issues-pull** [clsid2/mpc-hc#596]
Ryzen 3600, Window10 LTSC, NVIDIA GPU.

The issue described is while using EVR (custom presenter).

1. Open MPC normally from shortcut. Do nothing more. CPU behavior is normal. Voltage fluctuates down to 0.6v.

2. Play a video or simply just load a video in MPC and then pause it. Voltage will not drop below 1.2v. If I have my max voltage set to 1.23, it will remain pegged at maximum even while the video is paused.

Playing a video on Youtube in Firefox causes the same voltage spike behavior, the difference though with Youtube in Firefox is that when the video is paused, the voltage stops being pegged at the ceiling.

So MPC while paused is still doing something that is keeping the voltage high.

If MPC w/paused video is suspended (not killed) from task manager, the voltage then drops.

Using NULL renderer obviously means no video output and voltage does go up a little while playing an MP4 file, but at least the voltage fluctuates a bit.

Using Video Mixing Renderer 9 (which does not have DXVA support) causes voltage to spike during playback, which is mostly acceptable, AND on pause it allows voltage to drop.

So I'm assuming it's DXVA related?

I'm wondering if the paused behavior with EVR can be fixed so that it is no longer causing high CPU voltage. Reason being is that I'm also seeing a small number of other apps with this same behavior, where even though the app is not (technically) doing anything, it's keeping the voltage maxed out.

**Comment by code-issues-pull** [comment]
Something I just noticed, MP4 files do not seem to be affected with the pause voltage spike issue, no matter what renderer is used.

MKVs while paused will peg voltage to max.

So this seems less of a DXVA issue now since MKVs are still causing the spike with VMR9.

**Comment by clsid2** [comment]
DXVA2 works with all renderers if you use copyback mode. Only of native mode is restricted to compatible renderers.

Perhaps the issue is related to subtitles? Try with:
Options > Subtitles > Sub pictures to buffer = 0
That eliminates one running thread.

**Comment by Syst3mSh0ck** [comment]
It's power gating occurring on both the CPU and GPU ie shutting down / powering up parts of the logic in the name of power saving. Rather than looking at the container (MP4/MKV) you should look at the video codec/bitrate with MediaInfo instead. Higher voltage doesn't necessarily translate to higher power usage (wattage) unless there is extra current (volts x amps = watts).

**Comment by clsid2** [comment]
Pausing player does not mean it isn't doing anything. The GUI for example is actively waiting for user input. Letting threads sleep for longer periods would mean slower responsiveness.

Test if this helps reduce load:
Options > Advanced > TimeRefreshInterval = 500

**Comment by code-issues-pull** [comment]
I did the subtitles options change as well as TimeRefreshInterval, I experience the same issue. MKVs while paused keep CPU voltage pegged while MP4s do not.

And Syst3mSh0ck, while I do not have my killawatt currently plugged in, I do notice that there is a significant temperature increase when the voltage gets pegged like that on pause. So it does seem safe to assume more power is being consumed (more heat = more power). And this is while paused behavior, not playing. So I wouldn't think bitrate plays into that scenario too much. I honestly can't find a single mkv I have, no matter how small, how low in bitrate, that doesn't cause this behavior while paused.

Just a bit more info here.
DXVA2 Native + EVR + Paused MP4 = low cpu vcore
DXVA2 Native + EVR (custom) + Paused MP4 = high cpu vcore
DXVA2 Native + Sync Renderer + Paused MP4 = high cpu vcore
DXVA2 Native + VMR9 + Paused MP4 = low cpu vcore

**Comment by clsid2** [comment]
File extensions are meaningless. Look at video format: File > Properties

The custom renderers set the Windows Timer Resolution to lowest possible value. That by itself might already prevent ultra low power state. That isn't a bug and isn't going to be changed. If you want low power usage, simply don't leave multimedia applications running in a paused state.

**Comment by code-issues-pull** [comment]
Before opening:
Maximum timer interval: 15.625 ms
Minimum timer interval: 0.500 ms
Current timer interval: 0.999 ms

After opening and paused:
Maximum timer interval: 15.625 ms
Minimum timer interval: 0.500 ms
Current timer interval: 0.999 ms

Unless you mean something other than the clock resolution (using clockres64 released by MS to check)?

**Comment by code-issues-pull** [comment]
A short list of some properties of files that lock/don't lock: https://pastebin.com/1p3rEfds

Also happens with old avi's, Video: DivX 3 and  Xvid 6

DivX 3 and Xvid 6 follows the same pattern as pretty much most (if not all) H264 MPEG4 vids that I mentioned above.

It's just odd and inconsistent behavior. And I personally see it as a bug. If the voltage fluctuated based on load then it'd make sense. But something is pegging it to max when a cap is set. And without a cap set it stays much, much higher than normal.

I was partly hoping that if a solution was found for MPCHC, especially because there are instances where it doesn't max voltage, that whatever the issue was could be then be shown to other app developers to fix the voltage pegging with their apps as well. End result being a much healthier ecosystem of programs.

**Comment by clsid2** [comment]
It doesn't look like there is a specific file that triggers it. The amount of load of all running apps together is probably near the edge of a C-state transition of the CPU.

If the timer interval is already 1ms before starting the player, then another application might have already lowered it.

CPU power state and voltage is controlled by the BIOS and Windows. Applications have absolutely no control over this at all.

This is not a bug in the player and it is not possible to just magically fix it. The player architecture makes use of timers and that is simply how it works.

The player not only has options to remember last file playing, it can also remember the playback position. So there is no reason to leave it paused for long periods.

It is possible to customize the power profiles:
https://docs.microsoft.com/en-us/windows-hardware/customize/power-settings/configure-processor-power-management-options
