### ISSUE TITLE
[BUG] online subtitle search error 

### ISSUE THREAD

**Issue by Bulogan** [clsid2/mpc-hc#597]
OPENSUBTITLE
-----

While downloading a subtitle from opensubtitle return nothing. I am logged in and have proper registration in opensubtitle.

here is an example:

![image](https://user-images.githubusercontent.com/69257763/91380669-20022900-e858-11ea-9b4d-281d454f981b.png)

the bug does not happen if i type of paste the filename manually. notice that the query is the same.
![image](https://user-images.githubusercontent.com/69257763/91381070-0b726080-e859-11ea-9ea1-72aa042e8ae6.png)
 
~~PODNAPISI~~
-----

~~another bug is that the other provider react the opposite from above, podnapisi.~~ this seems to be fixed when doing a restart maybe a glitch happen but the above holds true.

**Comment by clsid2** [comment]
This is not a bug. The search on OpenSubtitles works with a file hash by default. That may sometimes give no results, while a filename search does give results. Current development builds already use filename search as a fallback when the hash search gives no results.

**Comment by Bulogan** [comment]
so how do i force it to use the file instead of the hash? I used the latest dev build but the fallback is not working for me as seen in my screenshot. i have to use the filename search to have a result, is it automatic or do i have some setting to turn on?

thanks

**Comment by clsid2** [comment]
@adipose
Log shows 15 results, but they aren't shown. Bug in the recent changes?

**Comment by adipose** [comment]
Yes, it showed the query result size when searching for an exact match.

https://github.com/clsid2/mpc-hc/pull/600

**Comment by adipose** [comment]
> 
> 
> so how do i force it to use the file instead of the hash? I used the latest dev build but the fallback is not working for me as seen in my screenshot. i have to use the filename search to have a result, is it automatic or do i have some setting to turn on?
> 
> thanks

It is using the filename after the hash fails.  But none of the results are exact, so you don't get an automatic match.
