### ISSUE TITLE
Crush while stream window in Discord

### ISSUE THREAD

**Issue by TheDarkDnKTv** [clsid2/mpc-hc#598]
When trying to enter fullscreen/change window size while streaming MPC windows in discord crushes player.

---------------

Build information:
    Version:            1.7.13 (e37826845)
    Compiler:           MSVC v19.00.24215.01
    Build date:         Jul 16 2017 18:47:17

LAV Filters:
    LAV Splitter:       0.70.2.1
    LAV Video:          0.70.2.1
    LAV Audio:          0.70.2.1
    FFmpeg compiler:    MinGW-w64 GCC 7.1.0

Operating system:
    Name:               Windows NT 6.1 (build 7601, Service Pack 1)
    Version:            6.1 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
    GPU:                Intel(R) HD Graphics 4600 (driver version: 10.18.14.5117)

**Comment by clsid2** [comment]
It is the fault of Discord.

This should solve the crash:
Discord settings > Voice & Video > disable "Use our latest technology to capture your screen"

You are using an old version of MPC-HC.
