### ISSUE TITLE
Seeking to next/last keyframe broken if keyframe >20s away

### ISSUE THREAD

**Issue by mkver** [clsid2/mpc-hc#6]
Hello,

my issue affects the 1.7.17 release version; I have seen that there has been [another commit](https://github.com/clsid2/mpc-hc/commit/32b10b66ee14b59ad08740db22164155cce2aa7e) dealing with seeking since then (in particular, the line " -#define MAX_FASTSEEK_INACCURACY 200000000LL", the only line that seems to contain an explicit reference to 20s, is gone), but I don't know if this has fixed the problem as I don't have a build with this commit, so I'll nevertheless state it here:

Seeking forward and backwards to the next/last keyframe (I mean the thing that is on Shift+Left/Right Arrow by default) is broken if the next/last keyframe is more than 20s away. It just doesn't seek forward at all if the next keyframe is more than 20s away; and if seeking backwards and the last keyframe being more than 20s away, it seeks 1ms backwards. And if I do this often enough (so that the last keyframe is only 20s away), it finally seeks to the keyframe that I wanted to reach.

Thanks for the continued effort you put into MPC-HC.

Greetings
mkver

**Comment by clsid2** [comment]
That has already been fixed for next release.
