### ISSUE TITLE
amd radeon adrenalin drivers stutter issue

### ISSUE THREAD

**Issue by lukjod** [clsid2/mpc-hc#60]
On amd drivers since 17.12 version when enhanced sync is turn on on global settings video is stuttering on mpchc playback no metter what setting is set on lav filters. When that setting is turn off all is ok. It doesnt concern other video players so is mpchc 100% related

**Comment by clsid2** [comment]
The fact that the issue does not exist is some other players does not mean the fault is in MPC-HC. Certainly not since it worked with older driver.

You should experiment with these settings:
MPC-HC menu > View > Renderer Settings > VSync

**Comment by alessiot89** [comment]
Be sure things like free-sync and adaptive v-sync are not enable on a MPC-HC profile or forced in the global profile. In the last case, you can create a MPC-HC profile and disable such settings.
