### ISSUE TITLE
Can anyone please help me to build this in PoP! OS? Thank you !!!!!

### ISSUE THREAD

**Issue by Kokkolis** [clsid2/mpc-hc#603]
Goodmorning all and apologies if this is a "strange" email amongst all you experts.. I am totally new to Linux but trying to learn. I love MPC-HC as I have installed it onto all my Windows computers. I am making my first steps onto Linux and trying hard to understand HOW to build the player from within Linux and cannot find simple instructions.

Has anyone from you got any simple instructions that a newbie can follow? I know how to open Terminal and how to copy and past commands, but that's about it...if anyone can help I'd be ever so grateful..

I have managed to download the building blocks from this repository onto "Download" folder of PoPOS, so what next? 

Thank you!!

**Comment by clsid2** [comment]
Linux is not supported.

https://github.com/clsid2/mpc-hc/blob/develop/docs/Compilation.md

**Comment by Kokkolis** [comment]
OK, thank you; I was under the impression that numerous Linux users have somehow installed MPC-HC onto their computers so I was trying to find a way too as I really love MPC.
Thank you for reading this.

    Στις Κυριακή, 30 Αυγούστου 2020, 3:41:48 μ.μ. GMT+1, ο χρήστης clsid2 <notifications@github.com> έγραψε:  
 
 


Linux is not supported.

https://github.com/clsid2/mpc-hc/blob/develop/docs/Compilation.md

**Comment by clsid2** [comment]
It may work with WINE. But don't expect good performance.
https://www.winehq.org/

For help you need to go elsewhere. I don't use Linux.
