### ISSUE TITLE
Where is 32 bit MPC ?

### ISSUE THREAD

**Issue by empleat** [clsid2/mpc-hc#605]
I downloaded 1.9.6 from here. But now it spam me with pop out window to update to 1.9.7. But i can't find here 32 bit version. I need 32 bit, coz MadVr works only with 32 version!

Thanks for help!

**Comment by lifegpc** [comment]
The file ends with x86 is 32 bit version.
https://github.com/clsid2/mpc-hc/releases/tag/1.9.7

**Comment by empleat** [comment]
Thanks, i guess i got linked by mpc to wrong site!
