### ISSUE TITLE
Can not play DVD with no menu.

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#607]
Open ```VIDEO_TS/VIDEO_TS.IFO``` is not work too. But open ```VIDEO_TS/VTS_01_0.IFO``` is work.
Example DVD file: https://1drv.ms/u/s!Aoq8mAMlVv8UmwHUjtvfPSxUxZ6c?e=1r6En1
![image](https://user-images.githubusercontent.com/41434272/92237803-93f0a100-eeea-11ea-98a6-910b55aadb41.png)

**Comment by clsid2** [comment]
Fixed
