### ISSUE TITLE
Click Apply is not effect in subtitles styles dialog.

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#608]
I load external ass subtitles.
![image](https://user-images.githubusercontent.com/41434272/92241600-0cf2f700-eef1-11ea-89de-dbfe4e773a36.png)

**Comment by adipose** [comment]
The settings forms only show the apply button when something has "changed."  Actually the code is kind of odd, and detects clicks and things to decide there "may" be changes.  I've looked at it before.

If the apply button isn't active, it should mean you didn't change anything.  But, I assume you did?

What did you change when it didn't let you apply?

**Comment by lifegpc** [comment]
I modify some style, and click apply, it not works.( I can't see the changes)
But if I click ok. It works.

**Comment by adipose** [comment]
Give a specific example (minimal). Better yet, a video of it failing.

**Comment by lifegpc** [comment]
Open a ass file. Change a style's font. And click apply. Then close window, can't see any change.

**Comment by lifegpc** [comment]
This video can show what I want to say.
[2020-11-17 14-44-04.zip](https://github.com/clsid2/mpc-hc/files/5551716/2020-11-17.14-44-04.zip)

**Comment by bibsp** [comment]
Ass subtitles come with its own font.
If you want to change it to default follow the steps.

Launch mpc hc. Press O on keyboard or right click, go to options.
Under subtitle go to default style. Now set your desired style hit apply.

Now open any video with ass subtitle file.
Right click>subtitle style> check ✔️ default style.

**Comment by clsid2** [comment]
Try 1.9.24.27

**Comment by adipose** [comment]
@clsid2 is this fixed?
