### ISSUE TITLE
Directx alert

### ISSUE THREAD

**Issue by nollinvoyd** [clsid2/mpc-hc#61]
Windows 10 1803, MPC-HC 1.8.4.6

When I load a file with MPC-HC, this happens

![mpc](https://user-images.githubusercontent.com/20844322/51219807-6d31c100-18e7-11e9-9b2d-b5308d8ff846.png)

When I close the message, the video start playing.

My Windows update is current, includibg Directx 12

thanks

**Comment by clsid2** [comment]
Actually, your DirectX install is not current. Some files are not included in a standard Windows install. They can be added with "DirectX web installer".

The required files are normally also included in the MPC-HC installer. But it seems that you are using a custom installer from free-codecs website, which is missing those files.

**Comment by nollinvoyd** [comment]
From now on I'll download from here

thanks
