### ISSUE TITLE
1.9.7.44, youtube-dl = "Failed to render the file"

### ISSUE THREAD

**Issue by Tharn** [clsid2/mpc-hc#613]
This does not happen with all youtube links. Most of them play just fine. But I have one link here that refuses to play. By the way, inputting that link into youtube-dl.exe works just fine and immediately starts the download, and watching it on YT works fine too. This is some weirdness between MPC-HC and youtube-dl that I can't figure out.

`https://www.youtube.com/watch?v=ehkIJu1C3U0`

Using 1.9.7.44 x64 dev version, youtube-dl v. 06.09.20, FFMpeg 4.3.1 (I don't think this is used, but it's there)
The only YDL setting in MPC-HC I changed was maxHeight to 1080, but even at default 1440 I get the same result.

Good luck!

**Comment by clsid2** [comment]
The 1280x720 version of that video points to a non-working url. So that is why it is failing. The 640x360 version works ok.

MPC-HC only tries the best available version of the video (based on chosen settings). So I can't/won't fix this problem.

**Comment by Tharn** [comment]
I can watch it on YT / download it with youtube-dl at 720p60. MPC-HC is the only instance where the URL doesn't work. Surely that deserves a look?

**Comment by clsid2** [comment]
MPC-HC does not support the DASH manifest streams that YT uses. It uses a different 720p60 version.

I can't fix this right now. The url it selects is simply broken. I have already looked at it.
