### ISSUE TITLE
Can't change any settings in history category

### ISSUE THREAD

**Issue by nollinvoyd** [clsid2/mpc-hc#62]
No matter how the history settings are altered, all these settings revert back to what you see here when MPC_HC is restarted.

I'd like to have MPC-HC initially open to a size of my choosing if possible.

![mpc](https://user-images.githubusercontent.com/20844322/51502933-48c56100-1d8d-11e9-8836-9dfece810ced.png)

Thanks
_________________________
MPC-HC.1.8.4.x64, Window3s 10 1803

**Comment by clsid2** [comment]
Check if the installation folder contains a .ini file and remove that.

Also remove this Registry key:
HKEY_CURRENT_USER\Software\MPC-HC
