### ISSUE TITLE
MPC crashes when taking a lot of screencaps

### ISSUE THREAD

**Issue by egozi44** [clsid2/mpc-hc#633]
I'm using MPC-HC.1.9.7.34.x64, and each time I take a lot of screencap with the F5 key it sometimes showed the subtitles in black or removed part of them, so I assume it was done from the sub picture to buffer and set it to zero, then the subs worked fine but the player now crashes a lot instead and gave me this report
https://drdump.com/UploadedReport.aspx?DumpID=%7BDumpID%7D

What can be done to fix it?

**Comment by clsid2** [comment]
That link is incorrect. Copy the url of the page that opens. Don't click on the details link.

**Comment by egozi44** [comment]
This one maybe?
https://drdump.com/Problem.aspx?ProblemID=21&Login=guest

These are all the links that I got

**Comment by clsid2** [comment]
I mean the link in the address bar of your browser.

**Comment by egozi44** [comment]
That was what I've posted
One of these was the link that MPC opens for me

**Comment by clsid2** [comment]
Those are not crash reports from MPC-HC. I think that you are clicking on a link on the page that opens. Don't do that.

**Comment by egozi44** [comment]
It automatically opens that for me when there's a crash, I didn't saw any other report

**Comment by clsid2** [comment]
I am unable to trigger a crash, even when constantly tapping F5 key.

Does it happen with any file, or only a specific one?

**Comment by egozi44** [comment]
So far it happened to me 4 times in an MKV format from this video
https://nyaa.si/view/1283405

**Comment by egozi44** [comment]
Manged to do it again and it still sent me here
https://drdump.com/UploadedReport.aspx?DumpID=51188030

I watch that thing at full screen, and set the sub picture to buffer to zero and then start looking in some part of the video and press F5 nonstope

**Comment by egozi44** [comment]
Is there any other way for me to get a crash report so I can send it over?

**Comment by clsid2** [comment]
The link is good now. But that doesn't mean it is easy to fix.

Is there a specific time in this video where you get a higher chance of getting a crash?
How many presses of F5 do you estimate are needed on average to get a crash?
What is your screen resolution?
Do you are get crash with sub picture queue enabled, or only rendering issues?

**Comment by egozi44** [comment]
I'm not sure about specific time, but it tended to be happened somewhere in the middle and before the mid part, 
after that I just moved to other player.

I was able to recreate it easy though by moving really fast to different areas in the video and press F5 none stop till it crashed 

Something else that I've probably should've noted is that I also use CCCP 86 bit ver, but that is only 86 bit codec pack that not really interfere with the 64 bit ver you got in that MPC ver, 
And aside from CCCP I also uses DSFilterTweaker and set it to use merit codecs in the 32 codecs (over just using MS),

I don't have any 64 bit codec pack installed so the player shouldn't have any issue with that and does runs everything fine (aside old OGG format which CCCP run more smoother, which I wish this player could run fine as well so I could kiss CCCP goodbye) till I start taking screencaps

**Comment by clsid2** [comment]
CCCP uses the same codecs as MPC-HC. Both use LAV Filters. I have no issues with playing OGG files. If you have any samples that play badly, then maybe that can be fixed.

**Comment by egozi44** [comment]
> CCCP uses the same codecs as MPC-HC. Both use LAV Filters. I have no issues with playing OGG files. If you have any samples that play badly, then maybe that can be fixed.

I don't got from your comment if it's a good thing or bad thing?
Also CCCP used dated codecs and I only installed the 32 bit ver with the 32x codes, so by names sure, they uses the same codecs, by ver num though both the 86x and 64x uses different ones entirely and shouldn't touch one another due to being a on a different bits.

The only issue I've noticed in OGG was that they all Works but plays more slower when I compares them to the CCCP setup, it happened to me in every video I've tried so far.

Did you was able to recreate the crash so far?
did any of the things I've said above might be the cause of my issues?

**Comment by clsid2** [comment]
Yes, I know it uses a much older version. If you have a sample video that plays slower, then I can check if there is a problem.

I have been able to trigger the crash once. But I need to do it again with a debug build.

**Comment by clsid2** [comment]
Another related crash:
https://drdump.com/Problem.aspx?ProblemID=595825

**Comment by clsid2** [comment]
Looks related to changes made on Aug 31 2014:
https://github.com/clsid2/mpc-hc/commits/develop/src/Subtitles/Rasterizer.cpp

@adipose, could you also have a look at this crash? I am not sure how to fix.

**Comment by egozi44** [comment]
I've tested K-lite and got the same issue there too with MPC,

The current MPC I have from CCCP is

MPC-HC (CCCP Build)
-------------------

Build information:
    Version:            1.7.8.162 (ff72737) (blitzkrieg) (master@46ce9d6)
    Compiler:           MSVC 2013 Update 4 (SSE)
    Build date:         Oct 18 2015 21:47:45

LAV Filters:
    LAV Splitter:       0.65.0.5
    LAV Video:          0.65.0.5
    LAV Audio:          0.65.0.5
    FFmpeg compiler:    MinGW-w64 GCC 4.9.2


And it seem to work just fine,
Ahh I wonder if there's any hopes for me replacing that old codec build any time soon ._.

**Comment by clsid2** [comment]
The ability to include subtitles in the screenshot was added recently. Disabling that should minimize the chance of a crash.

Options > Advanced > SnapshotSubtitles

**Comment by egozi44** [comment]
What do you mean?
I could always take screenshots with subtitles since more than decade ago with MPC,

I will try disabling it though and see if it stop the crashes

**Comment by adipose** [comment]
I will take a look. The feature to capture subs was added recently. I am not sure how you did it previously, but maybe hard subs or some things. Or perhaps older code base somehow captured subs using different methods but I didn't think so.

**Comment by clsid2** [comment]
If you use VSFilter as subtitle renderer, then the screenshot will also have subtitles. But that means you loose DXVA hardware acceleration and subs will also be lower quality.

I don't know if the crash is directly related to the screenshot option. It might just increase the chance of the problem occurring, since similar crashes in DrDump occurred already before the option was added. The rasterizer code is very difficult to understand, so I have no idea when values are wrong. Or perhaps it is a threading issue. Does it re-render the subpic for the screenshot?

**Comment by clsid2** [comment]
Easiest way to reproduce is:
seek to middle of video
keep pressing F5 and at same time also press left and right arrow to seek back and forth

**Comment by egozi44** [comment]
It definitely was other codecs that allowed me to render subs, and you right, CCCP mostly uses XySubFilter but they've also used different things over the years and I've never followed as my knowledge in codecs is basically zero anyway, I just used what codecs packs like CCCP provided over the years and it worked. 


As for the crash issue, it look definitely like screenshot related issue to me, first of I'm always turn off the fast seek so it's not the seek that cause it imo, Only when sub picture to buffer is set to zero (which was like that in CCCP btw) and I press F5 a lot, I've noticed in the K-lite's MPC that the issue occur faster if I also stop the video with space key a lot as I press F5

**Comment by clsid2** [comment]
It indeed seems to be a threading issue, where CRenderedTextSubtitle::Render() is called from two threads simultaneously.

**Comment by clsid2** [comment]
The problem seems to be that CRenderedTextSubtitle::Render() is called from two threads and that messes up things. Instead of rendering twice, we should somehow cache the currently displayed subpic for use in screenshot.

**Comment by clsid2** [comment]
Try version 1.9.7.70
That should be more stable. It can however still crash if the subtitle that is rendered is being invalidated at same time due to a seek.

**Comment by adipose** [comment]
What about a render/invalidate mutex?  Would that be enough to prevent crashes?

**Comment by clsid2** [comment]
I have already added a lock to the render function. Now I haven't been able to trigger crash in the rasterization code anymore. Dealing with the invalidation is something I haven't looked at in depth. Feel free to take a look at it.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/641

This seemed to solve the issue for me.  It was already rare after your fixes, but now I think all the issues are gone.

**Comment by egozi44** [comment]
It was added for recent beta ver right?
if yes then I will take a look 👍

**Comment by clsid2** [comment]
Yes, try 1.9.7.74

**Comment by egozi44** [comment]
alright
