### ISSUE TITLE
Text not scaling correctly in 'Download subtitles' window

### ISSUE THREAD

**Issue by ProTofik** [clsid2/mpc-hc#635]
No big deal but I noticed one text line doesn't scale in 'download subtitles' window.
See attached screenshot.

I have 24" 3840x2160 monitor, so my Windows scaling is set to 200%. Looks like the text at the bottom of this window is scaled at 100% so it's tiny.

![mpc](https://user-images.githubusercontent.com/11578396/94267740-0249e180-ff34-11ea-9863-84c7295a1bd1.png)

**Comment by adipose** [comment]
How about in classic theme?

**Comment by adipose** [comment]
Just a random idea, is that window by any chance on a different screen than the player?

**Comment by ProTofik** [comment]
Good call, I forgot to mention.

1. I just checked white theme, it works fine so the issue is limited to dark theme only:

![white](https://user-images.githubusercontent.com/11578396/94343074-87ed9000-000d-11eb-808c-f2b6ee2f1369.png)

2. Yes, I have 2 monitor setup. Main monitor is 3840x2160 @ 200% scaling. 2nd monitor is 1280x1024 @ 100% scaling.
The issue I am describing here occurs when player is on monitor no.2 and 'download subtitles' window on monitor no. 1. 

While checking something I have also found another scaling bug. When player is on monitor no. 2, 'Settings' window is scaled to 200% no matter what monitor it's on.

![2 monitors (1)](https://user-images.githubusercontent.com/11578396/94343108-d3a03980-000d-11eb-9b69-2c31ea9e6590.jpg)
![2 monitors (2)](https://user-images.githubusercontent.com/11578396/94343111-d4d16680-000d-11eb-9c77-176a0e00f845.jpg)

**Comment by adipose** [comment]
For the second issue, I think it's unfixable with static dialog layouts.  One day maybe I'll make it dynamic...not anytime soon.  It honors the main window DPI and scales all the dimensions and fonts.  Can you confirm the same happens in classic mode?

Now, for the first issue, I think I already know what causes it.  Similar problem but more under my control.

**Comment by ProTofik** [comment]
Yes it happens with white theme as well.

Obviously I'm not a programmer so I don't understand all code behind it, but main window scales perfectly fine when moving between monitors so why settings/properties/subtitles windows can't?

**Comment by adipose** [comment]
It's not impossible to fix, but I believe all the dialog elements in the settings are using static sizes.  As a result, they follow the application's instructions to scale, but probably honor the main window's DPI settings.  There is an outstanding issue to use more advanced DPI scaling, but I don't know if that would help.

The subtitles window is using custom widgets which have some custom code to figure out the DPI scaling.  I could fix that pretty easily.  The main window also does manual scaling.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/646

This should fix the status bar issue, and some other things likely to be wrong when on a different screen.  As for the dialog elements, they appear to scale pretty well when using the V2 manifest, but as @clsid2 mentioned, some things end up being wrong.  I'll look into that later (it will only work on recent Windows 10, as well).

The dark theme uses a few static resources that might not scale automatically with V2 manifest, so I will have to decide how to handle that.
