### ISSUE TITLE
Crash in nvd3dumx.dll with certain video

### ISSUE THREAD

**Issue by MD-78** [clsid2/mpc-hc#636]
MPC-HC gives an error here with the attached (unpacked) MP4 file:

"An error has occured. MPC-HC will close now.

Exception:
[MPC-Crash.zip](https://github.com/clsid2/mpc-hc/files/5286582/MPC-Crash.zip)

INTDIVIDE BY ZERO

Crashing module:
C:\Windows\SYSTEM32\nvd3dumx.dll
Offsett: 0x703D663DE, Codebase: 0x7FF709940000"

Also the error message can't be closed all the time (sometimes I have to kill MPC via Taskmanager).

Culprit seems to be the width of the video (1088 pixels).

Window 8.1 Pro
Nvidia Geforce Driver 451.67
MPC-HC x64 1.9.7

**Comment by clsid2** [comment]
The crash is happening in NVIDIA driver. Try different version of the driver. I don't get any crash on my system with that video. Currently using driver 442.74.

**Comment by MD-78** [comment]
Ok, just tried Geforce 456.38 - same crash (with Nvidia CUVID HW output). With DXVA2 MPC-HC just hangs (without crash) ...

Screen resolution = 1920 x 1200 px

**Comment by clsid2** [comment]
Works perfectly fine here with same resolution.

I can't fix NVIDIA bugs.

**Comment by MD-78** [comment]
Bug got fixed in Geforce driver 460.79
