### ISSUE TITLE
Audio renderer will not swap device

### ISSUE THREAD

**Issue by Dr-Flay** [clsid2/mpc-hc#637]
When choosing a different audio output device nothing is changed.

My setup is with Voice Meeter primary virtual driver set as the system default. I use my media players on the AUX device.
If I select it in MPC it is still going out on the primary device.
![MPC-audio](https://user-images.githubusercontent.com/43873202/94357001-ead23c00-008c-11eb-8ad8-7010447adbe3.jpg)

**Comment by clsid2** [comment]
The selection on that settings page only has effect when you are using the internal audio renderer.

You can select the renderer here:
Options > Playback > Output

Changing device during payback has no effect until you reload the file (Ctrl+E).
