### ISSUE TITLE
Request - Speed change option for pitch-shift or not

### ISSUE THREAD

**Issue by David-W-B** [clsid2/mpc-hc#639]
I transcribe music as job, and MPC's previous behavior when changing speed was a pitch-shift, and this was great for perceiving bass lines, which would become more audible and faster, adn often easier to discern.
The last few versions have speed change still working, but it preserves pitch of music.
While this is great for movies and music, sometimes a pitch shift is desirable.
How about an option?
![image](https://user-images.githubusercontent.com/64195502/94362932-c2fbcc00-00be-11eb-9e5c-74fd3cbd2e49.png)

**Comment by clsid2** [comment]
Only the internal audio renderer has pitch correction. You can change to system default renderer if you want to disable it.

Options > Playback > Output

**Comment by David-W-B** [comment]
OK, so that did it! Thanks and good thing I installed with reset settings, so I discovered new behavior.
