### ISSUE TITLE
Jump Backward not working as intended

### ISSUE THREAD

**Issue by NR2014** [clsid2/mpc-hc#64]
Jump backward (Shift+left arrow) doesnt jump backward as forward does , instead it jumps only one frame back. Holding it for more than 2 seconds only jumps , but it jumps too much.

**Comment by clsid2** [comment]
Shift+Left is "seek to keyframe", not a normal jump.
You should use Left (jump 5 sec) or Alt+left (jump 20 sec).

Options > Player > Keys

**Comment by NR2014** [comment]
I had my keys keyframe to plain arrow keys .. there was a conflict , now changed them , working fine , thanks..

But as per my previous setting back jump was shift+left arrow , which it didnt work , wheras , shift+right arrow (frwd jump) worked fine.
