### ISSUE TITLE
Option to remove extra ".languagecode" from saved subtitle filenames

### ISSUE THREAD

**Issue by ALIENQuake** [clsid2/mpc-hc#640]
For each movie which I watch, each subtitle which I download, I have to save them to a USB stick and put into my TV. Using "CTRL+s", I got the "Save subtitle" dialog, and the subtitle filename has extra unnecessary ".languagecode" at the end of the filename.

So instead of:
`Blade Runner 2049.srt`
i got
`Blade Runner 2049.pl.srt`

It forces everyone to remove those extra ".languagecode" because otherwise, TV's won't load/recognize subtitles. It is painful and completely unnecessary and if you forgot to do it, you have to go back to your PC, rename it and then get back to TV.

**Comment by lifegpc** [comment]
#663 You can try this [test build](https://mega.nz/file/oxBmQZBR#8c1NyNZ7OHqBCAxnyrzcbvBXr7Gfk8uGIkvVHWh9U4o).

**Comment by lifegpc** [comment]
You need set Option->Advanced->AddLanguageCodeWhenSaveSubtitles to false.

**Comment by FreddyZar** [comment]
Does this also cater for the added .hi when Hearing Impaired subtitles are downloaded?

because sometimes when I save subtitles I see

instead of:
Blade Runner 2049.srt
i get
Blade Runner 2049.pl.hi.srt

**Comment by lifegpc** [comment]
@FreddyZar yea.

**Comment by lifegpc** [comment]
I also disable hi.

**Comment by ALIENQuake** [comment]
@lifegpc Fantastic, thank you!

**Comment by ALIENQuake** [comment]
@lifegpc Sorry for bringing this again. Somehow I can't see this option when I install "K-Lite Codec Pack (Standard)" even if the Contents here https://codecguide.com/features_standard.htm claims `Media Player Classic Homecinema [version 1.9.15.79]`

When I install MPC-HC from this repo, the option is available.

**Comment by clsid2** [comment]
MPC-HC options > Advanced > AddLanguageCodeWhenSaveSubtitles

It is really there, so you did not look well enough!

**Comment by ALIENQuake** [comment]
Ok, I've tested using clean install and it's there. No idea how I could miss it. Sorry.
