### ISSUE TITLE
Downloading subtitles doesn't work.

### ISSUE THREAD

**Issue by empleat** [clsid2/mpc-hc#643]
When i pressed d, subtitle menu didn't even open... So i downgraded to 1.7.13 for this (last stable build from mpc-hc devs). When i open "Download subtitles" using d, pop out window appears - that i need to login to opensubtitles.org. I tried to uncheck opensubtitles provider in setting. But now: it won't find anything! Where do i login in mpc-hc to download subtitles? I looked everywhere and google didn't find anything... I would use 1.9.7, if it didn't have that bug with hotkeys unbinding repeatedly.

Thanks!

**Comment by clsid2** [comment]
Use latest development version:
https://github.com/clsid2/mpc-hc/releases/tag/1.9.7.34

MPC-HC options > Subtitles > Misc > Right-click on OpenSubtitles > Setup

Create login on OpenSubtitles.org website
