### ISSUE TITLE
Sometimes videos don't autostart

### ISSUE THREAD

**Issue by doub** [clsid2/mpc-hc#644]
Since I updated to 1.9.7, from 1.7.11 on the old website, I noticed sometimes the videos don't auto-start when I open them. What makes it very annoying is that it doesn't happen all the time. It seems to happen more with 4K videos, which makes it worse as even when they auto start they take a couple seconds to load on my machine, so I never know whether it's slow to load or whether it's paused.

This never happened with 1.7.11 and older versions, with the exact same settings.

I'm happy to share any config I'm using, or even links to the files (which are very large) if that helps. I'm not sure what's relevant.

**Comment by clsid2** [comment]
What is shown here when this problem happens?
Menu > Play > Filters

I suspect it may be caused by your graphics driver. Update the driver if possible. Otherwise disable hardware acceleration in the video decoder settings.

**Comment by doub** [comment]
Filters currently loaded:
  - Default DirectSound Device
  - madVR
  - Audio Switcher
  - LAV Video Decoder (internal)
  - LAV Audio Decoder (internal)
  - LAV Splitter Source (internal)

This still works just fine with version 1.7.11 or a custom built 1.9.0.23 (c62b220df) and my current graphics driver, so this looks like a regression. I'll update my drivers, but I have a 5 year old GPU so I doubt there'll be anything new in there.

**Comment by clsid2** [comment]
It is a bug in madVR. I assume you are playing on a secondary monitor.

Similar topic:
https://github.com/clsid2/mpc-hc/issues/216

**Comment by doub** [comment]
Yes, I changed the monitor to secondary because it's HDR (the others are not) and every time I pressed alt-tab the window list popup would trigger a couple screen flickers (which happens any time a non-video & non-cursor pixel is on that screen). I also begrudgingly switched to madVR because that seems to be the only renderer that supports HDR and subtitles. And I previously built my own MPC-HC to always keep a very dark status bar visible to avoid the flickers, until I realized that the colours were wrong if I don't let that happen. That's when I switched to your builds.

So this is clearly a duplicate. And I understand the madVR bug is not your problem. But is there any chance the built-in renderer will ever get HDR support?

**Comment by clsid2** [comment]
You can use the "tone map HDR using pixel shaders" option in madVR to play HDR on any monitor. It will also avoid the flicker issues because Windows doesn't need to switch in and out of HDR mode.

An alternative for madVR is this:
https://github.com/Aleksoid1978/VideoRenderer
That might one day be used as a replacement for the internal EVR renderer.

**Comment by doub** [comment]
Tone mapping to an SDR signal defeats the purpose of having an HDR monitor. I'll give that VideoRenderer a try.

**Comment by clsid2** [comment]
That one also tone maps. And also less advanced than madVR.

**Comment by clsid2** [comment]
Disabling this madvr option might help: "delay playback start until render queue is full"
