### ISSUE TITLE
Loading dvd iso image doesnt load dvd navigator

### ISSUE THREAD

**Issue by hushkamala** [clsid2/mpc-hc#645]
If i load an dvd iso directly on media player classic, like drag and drop on the player window, it loads the source filter "File Source Async" and the needed decoders but not dvd navigator.

It plays a 30 seconds introduction and never gets past it even after the 30 seconds of video it loads.
Don't know if the problem is not loading dvd navigator, but since its missing, even it got past the intro it would be unable to navigate the menus.

I tried vlc and it skips the intro, goes right into dvd main menu and i am able to navigate the menus.

**Comment by clsid2** [comment]
Loading ISO fies directly is not supported. You must mount it as a disc first.
