### ISSUE TITLE
File Open Request

### ISSUE THREAD

**Issue by WaltP9999** [clsid2/mpc-hc#647]
Add a setting to leave the MPC window size and location static when opening a new file.
Currently, if the 100% setting is on, all files resize the window to the file's internal size.
If not set, the window opens extremely small (looks smaller than 360p).

Have this setting:
-- open the FIRST file at 100% (window can be resized at will).
-- open the SUBSEQUENT files in the window as currently set (irregardless of internal size).
-- leave the window location as is rather than centering it upon open.

Walt

**Comment by clsid2** [comment]
Options > Playback > Remember last window position and size

**Comment by WaltP9999** [comment]
Thank you. I expected it in **Playback** and I couldn't find it before.  Thanks for letting me know the setting at least existed so it wasn't hard to find.

The setting is actually in **Player** by the way.

I expected it in **Playback**and I couldn't find it before. The setting is actually in **Player** -- that's why I didn't see it before. Thanks for letting me know the setting at least existed so it wasn't hard to find.
