### ISSUE TITLE
MPC-HC not playing https streams?

### ISSUE THREAD

**Issue by MarGeb1** [clsid2/mpc-hc#649]
Hi,

http streams work fine but https streams don't. After some seconds MPC reports "file not found"?

Regards

Margeb

**Comment by lifegpc** [comment]
hmm, I think it works fine. Maybe you should provide the URL which is not works fine.

**Comment by MarGeb1** [comment]
https://derste247livede.akamaized.net/hls/live/658317-b/daserste_de/profile3/3.m3u8
https://swrbwhls-i.akamaihd.net/hls/live/667638/swrbwd/master_1216.m3u8

But maybe the URLs are geo-blocked.

I can play the streams with other players (VLC, MPC-BE) but sadly MPC-HC fails...

**Comment by clsid2** [comment]
It might be blocked due to the HTTP user agent used by LAV Splitter. The web server could be rejecting anything that isn't a browser.

I might add a custom user agent value one day. But I can't promise anything.

**Comment by clsid2** [comment]
It actually is GEO blocked. I tried with VPN and it works with German IP.
