### ISSUE TITLE
ToDo: add checkbox on audio renderer settings page

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#650]
Add a checkbox to enable use of the internal audio renderer. This to make it more obvious if it is actually enabled. Its state should correspond to the selection on the Output settings page.

**Comment by clsid2** [comment]
Checkbox has been added. But it does not yet allow to enable/disable the internal renderer. It only reflects the state on the output settings page.

**Comment by adipose** [comment]
Supposing that the checkbox is enabled.  What does it do when you uncheck the box?  It would need to choose an alternate audio renderer option, right?

**Comment by clsid2** [comment]
Yes, it should change renderer to system default. That would be most logical to do.

**Comment by clsid2** [comment]
There is also a bug in the WebVTT color parsing.

Sample:
```
WEBVTT

00:00:05.000 --> 00:00:06.480
<c.white>test</c>

00:00:07.920 --> 00:00:10.320
<c.white>test</c>

00:00:43.320 --> 00:00:45.960
<c.white>test</c>
<c.white>test</c>
```

**Comment by adipose** [comment]
This is done.
