### ISSUE TITLE
Linear subtitle correction

### ISSUE THREAD

**Issue by Irfy** [clsid2/mpc-hc#652]
I've never contributed to MPC-HC before, so I'm asking for directions on where to start to add "linear subtitle correction" support. (I also understand the project is not officially maintained any more, so I am not asking for the feature to simply "be implemented")

Background: subtitle shifting corrects fixed offsets where the relation between frame and subtitle at a given point in time is t_subtitle = t_frame + fixed_offset. However, subtitles with the relation t_subtitle = t_frame * stretch_factor + fixed_offset where stretch_factor is a real number close to 1 (e.g. 0.95 to stretch subtitles that play out faster than the video, or 1.05 to condense subtitles that play out slower than the video) cannot be meaningfully corrected with just a fixed_offset shift, and require constant adjustment throughout a video. A website exists to modify SRT subtitle files in this way, the feature is called linear correction: https://subshifter.bitsnbites.eu/

The idea is to allow some mechanic in the Subresync window to apply linear correction. In my opinion, a further context-menu option "2nd Current (F6)" or "Linear correct" etc. would be the most straight-forward and user-friendly to use. The user applies "Current" to one line then finds the appropriate frame and subtitle elsewhere and applies the new option which lets MPC-HC calculate the stretch_factor and fixed_offset based on trivial linear interpolation of the two points.

The stretch_factor could be added to the hotkey subsystem too, to allow, for example, Ctrl-scroll or Ctrl-F1/F2 to increase/decrease it, similar to how the fixed_offset can be controlled.

**Comment by clsid2** [comment]
Start by learning how to compile
https://github.com/clsid2/mpc-hc/blob/develop/docs/Compilation.md

If stretch factor is most of the time for correcting "PAL->NTSC" (or vice versa), then hotkeys for those two specific situations could be enough. How often is anything else needed?
