### ISSUE TITLE
Generate portrait video thumbnail forced to landscape

### ISSUE THREAD

**Issue by kinone3** [clsid2/mpc-hc#653]
Generate portrait video thumbnail forced to landscape

Function: File > Save Thumbnails
Version: v1.9.3 - v1.9.7 (1.9.2 is ok)
OS: Win 10 x64

**Comment by cw2** [comment]
"portrait" video means it was "portrait" originally or it was "landscape" and then rotated (±90°) in MPC-HC ?

**Comment by clsid2** [comment]
I assume landscape with 90 degree auto-rotate in metadata.

**Comment by cw2** [comment]
Hm... thumbnails for my sample landscape video with 90° rotation in metadata are generated in "portrait", but the image is upside down.

Any chance for @kinone3 to provide a (preferably small) video sample?
