### ISSUE TITLE
Is it possible remove or dilute the light horizontal line under the menu bar in dark mode?

### ISSUE THREAD

**Issue by techfisha** [clsid2/mpc-hc#654]
I used to use the player in windowed mode ,it does some interfering with the view.

![3](https://user-images.githubusercontent.com/72426766/95193553-8d658a00-0806-11eb-8d73-ff52931a174f.png)

**Comment by JorgeR81** [comment]
Yes, that bothers me too.
What I do is to select the option to "Hide Menu", in "View".
The menu options will become available on mouse right click, and you will increase the picture area, in windowed mode.

And now, under "View", you will have other options that will give you even more picture area: "Frame Only", "Hide borders".
But you can't see all options at once, so you will have to cycle through them until you have the option to show the menu, and start all over again.
It's a bit confusing, but you only have to set it up once.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/670

![image](https://user-images.githubusercontent.com/3324395/96197929-2e8bc900-0f08-11eb-8807-6d9928cc1f4e.png)

**Comment by techfisha** [comment]
Thanks, That looks much better.  And Is that necessary  display underline under the menu,It looks a little dated style.

**Comment by adipose** [comment]
Probably I was holding ALT to take a screenshot. Alt accelerators normally underline when alt is held down. It's helpful to know the shortcut.

**Comment by techfisha** [comment]
Oh i see . Sorry I didn't know about this feature before，It's reasonable.
