### ISSUE TITLE
How to fix grey scale

### ISSUE THREAD

**Issue by abasem098** [clsid2/mpc-hc#655]
![IMG_20201007_122055](https://user-images.githubusercontent.com/72516723/95361519-2068f780-08cd-11eb-825f-07882bd9e99b.jpg)
How to fix the color problem,i was using version 1.7 it was working fine until suddenly i had this problem then i turned to version 1.9.7 still no difference help plz tge left pic is from mpc the right one is from vlc just to show the difference

**Comment by clsid2** [comment]
To have correct colors for HDR video you need to install and use one of these two renderers:
[MPC Video Renderer](https://github.com/Aleksoid1978/VideoRenderer)
[madVR](https://forum.doom9.org/showthread.php?t=146228)

**Comment by abasem098** [comment]
Hello,thanks for your reply but i am not sure if the video is hdr can i
have more details?

**Comment by abasem098** [comment]
I installed the mpc video render but i still have the same problem

**Comment by clsid2** [comment]
You need to select that renderer here:
MPC-HC options > Playback  > Output

Also check the color controls here:
MPC-HC options > Miscellaneous

**Comment by abasem098** [comment]
I will try

**Comment by abasem098** [comment]
Thanks for the solution it worked, although the mpc renderer didn't work
for me but thank god madrvr did the job
