### ISSUE TITLE
MpcApi.h: issue getting subtitle information when opening DVD folder

### ISSUE THREAD

**Issue by DMU-debug** [clsid2/mpc-hc#659]
Hi.
When I try to get subtitle information by command CMD_GETSUBTITLETRACKS I always get "-1"
// Ask for a list of the subtitles tracks of the file
// return a CMD_LISTSUBTITLETRACKS
CMD_GETSUBTITLETRACKS = 0xA0003000,
![image](https://user-images.githubusercontent.com/58528066/95733581-05aad000-0c8b-11eb-8af9-53e48a8fad05.png)
![image](https://user-images.githubusercontent.com/58528066/95735062-03497580-0c8d-11eb-8c87-b395123eda48.png)

**Comment by DMU-debug** [comment]
If I open .mkv, everything works fine.
![image](https://user-images.githubusercontent.com/58528066/95734002-97b2d880-0c8b-11eb-8dff-03d4590d0908.png)

**Comment by clsid2** [comment]
I don't have time to look at this. Since you are a developer, feel free to submit a fix.

**Comment by DMU-debug** [comment]
I would gladly help, but you greatly overestimate my abilities as a developer )))

**Comment by adipose** [comment]
Upload your source code and the video file.  Maybe I can test it.

**Comment by DMU-debug** [comment]
> Upload your source code and the video file. Maybe I can test it.

If you still want to fix the protocol, then using [this application](https://drive.google.com/file/d/1uFnGh4TCyyoZhXrulyI9HVy3eGL1Bk9r/view?usp=sharing) you can control the responses from the MPC-HC. Write if you need any more of my help.
PS: The mpc-hc64.exe must be installed in the default folder.

**Comment by cw2** [comment]
If I understand it correctly, the problem here is that CMD_GETSUBTITLETRACKS does not handle DVD subtitles - so the command needs to be extended to enumerate DVD subtitles like it is done for the submenu:
https://github.com/clsid2/mpc-hc/blob/301ba71da23f2921b5573f941f6ffa9477335c1c/src/mpc-hc/MainFrm.cpp#L14640-L14719
...and add them to the result.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2437

I think this does the trick.
