### ISSUE TITLE
AC3 Play on Windows 10

### ISSUE THREAD

**Issue by alfix0** [clsid2/mpc-hc#66]
I´m playing files on a PC with stereo environment.

MKV files with AC3 files 2.0 or 5.1 play ok with Windows 10, but AC3 files of DVD don't play fine, it seems that some channels are losing on play, only music not dialogs.

On Windows 7 all's ok.

**Comment by clsid2** [comment]
For problems with the internal codecs you should report here:
https://github.com/Nevcairiel/LAVFilters/issues

You could try enabling the mixer in the audio decoder settings.
