### ISSUE TITLE
Use System Media Transport Controls on Windows 10

### ISSUE THREAD

**Issue by Crayon2000** [clsid2/mpc-hc#660]
Hello, it would be really nice if _Media Player Classic - Home Cinema_ would support System Media Transport Controls on Windows 10. Windows provides a built-in interface that shows the user information about the currently playing media such as the title of a song or video:
![image](https://user-images.githubusercontent.com/11451841/95762231-6a5e2e80-0c7b-11eb-81b6-8272d06400a9.png)

Currently when changing the volume with my keyboard while watching a video in mpc-hc I see the the title of the last YouTube video I have stopped in Firefox or Chrome instead of the one I'm watching.

Here is the doc about the C++ interface:
* https://docs.microsoft.com/en-us/previous-versions/windows/desktop/mediatransport/media-transport-controls-portal

Maybe this C# doc may also be useful:
* [SystemMediaTransportControls Class](https://docs.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrols?view=winrt-19041)
* [Sample](https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/systemmediatransportcontrols)
* [Integrate with the System Media Transport Controls](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/integrate-with-systemmediatransportcontrols)

Implementation in Firefox:
* [WindowsSMTCProvider.cpp](https://searchfox.org/mozilla-central/source/widget/windows/WindowsSMTCProvider.cpp)
* [WindowsSMTCProvider.h](https://searchfox.org/mozilla-central/source/widget/windows/WindowsSMTCProvider.h)

**Comment by clsid2** [comment]
I am not interested in implementing this.

**Comment by Epyxoid** [comment]
> Currently when changing the volume with my keyboard while watching a video in mpc-hc I see the the title of the last YouTube video I have stopped in Firefox or Chrome instead of the one I'm watching.

I literally thought the same! Except I didn't know what does this feature called 😅 It'd absolutely make the player more vivid, more recent, more up-to-date. I know it is, @clsid2, but a lot of people don't. But if they saw even this feature is on spot, they'd know instantly, that this player is a thing!

**Comment by clsid2** [comment]
Any developer that is interested in this can submit a patch.

I am not interested. Period.

**Comment by Crayon2000** [comment]
I have just tried the 1.9.16.51 development build and the feature seems to be working just fine. Thanks to @lifegpc and @clsid2 for your work on this feature 👍
