### ISSUE TITLE
Wmv files do not support fast seek

### ISSUE THREAD

**Issue by sudongg** [clsid2/mpc-hc#662]
Hi, @clsid2 
Can wmv support fast seek?  At present, the seek is very slow, sometimes it takes a second or two.

**Comment by clsid2** [comment]
It is impossible to seek fast when the file is missing the seek index. That is a common problem with wmv files.

You can fix your files with [AsfBin](https://www.videohelp.com/software/AsfBin) tool.

**Comment by clsid2** [comment]
Enable the internal WMV source filter and decoders (those use FFmpeg code). By default it uses the filters from Microsoft for Windows Media.

**Comment by sudongg** [comment]
@clsid2 
The internal WMV source filter and decoders have been enabled, but it cannot be fast seek.
![wmv](https://user-images.githubusercontent.com/7007181/96060132-44769b00-0ec2-11eb-9f81-4ba1e77f20ec.png)

**Comment by JorgeR81** [comment]
Funny, I have some WMV files, with long seek times (about 2 or 3 seconds) in Potplayer, and I have to use MPC-HC, where the seek times are much better (less than a second).
(seek times in others files, are almost instantaneous, in both players).

But I have a Potplayer (64 bits) version that is previous to 1.7. (the exact one previous to 1.7).
And I have the a 1.9.0 version of MPC-HC, that came with K-Lite Codec Pack. 
(don't know if that makes any difference).

**Comment by sudongg** [comment]
Hi, @JorgeR81 
I would like to know whether mpc-hc can fast seek wmv files (keyframe seek). The biggest reason I use Potplayer is that it can fast seek almost all videos.
I use LAV Filter on Potplayer. Potplayer can still fast seek wmv files when using LAV Filter. I don't think there will be much difference between the two when keyframe seek is turned off.

**Comment by clsid2** [comment]
It can fast seek only if the file has a seek index with keyframe information. WMV files often do not have that. You can use the Asfbin tool I mentioned in my first comment to 'fix' your files. But even then WMV has slower seeking that most other formats.

**Comment by sudongg** [comment]
@clsid2 
I have used Asfbin and there is no change.

Please try to use Potplayer to see if you can perform keyframe seek on wmv（You may need to open keyframe seek）. For wmv files, the effect is very obvious after enabling keyframe seek.

I am also currently making a uwp player application. I use the av_seek_frame and avformat_seek_file provided by ffmpeg and realize a keyframe seek. Except for files in mpeg format without key frames,  other files can be keyframe seek,  including all wmv files.

I see that MPC-HC achieves key frame search by acquiring all key frames when reading files, which will slow down the file loading speed.
Is it possible to implement keyframe seek in another way, such as using ffmpeg to obtain keyframes during seek.

**Comment by JorgeR81** [comment]
I've also been using mostly Potplayer. But I have a few other players installed, because they work better in specific files.
Most WMV3 files I have available are good quality and have good seek times, on all players.
I did a few tests on some "more compressed" ones, with lower quality.

PotPlayer (64 bits, version 1.6.63891) tends to have the worst seek times. And sometimes, instead of freezing, the picture "jumps"a few times, before starting to play again.
In MPC 1.9.0 (with K-lite codec pack) seek times are also noticeable, but tend to be better. They are generality acceptable.
In MPV 0.32.0 (stable release) there are almost no noticeable seek times.

I did the tests with the players pretty much in the default "out of the box" configuration.
Keyframe seek does not seem to make a noticeable difference.

**Comment by sudongg** [comment]
@JorgeR81 
I don't know why you think that keyframe seek is not significantly different from non-keyframe seek. How can it be called fast seek if there is no obvious difference.

**Comment by JorgeR81** [comment]
I meant that keyframe seek did not seem to made a noticeable difference, on the WMV files I tested.
These files are very old, so there is probably something else wrong with them, not related to keyframes.

**Comment by sudongg** [comment]
@JorgeR81 
The file in wmv3 format is relatively old, and the bit rate and resolution are relatively low.

The wmv files that can be found now are in VC-1 format, and the resolution is generally 1920×1080.

Use potplayer to play video in 1080 VC-1 format, when you turn off the key frame seek, drag the progress bar or use the mouse wheel to seek, the seek will become very slow, the interval is about 0.5 to 2 seconds, after the key frame seek is turned on, the interval is about 0.1 to 0.2 second.

**Comment by JorgeR81** [comment]
These are 720 VC-1. I'm not sure I have anything in 1080 VC-1.
Also, in Potplayer, I changed the Video Renderer from"Auto select" to "Madshi Video Render", and I had great improvements. 
There are practically no seek times in these files, now. But, looking very closely, there seems to be a very slight increase in playback speed for about a second, that replaced the picture "jumps".

**Comment by sudongg** [comment]
@JorgeR81 
Potplayer uses EVR rendering when using "Auto select". Madshi Video Render is indeed better than EVR rendering,  and I can feel a small improvement.
But, what really works is keyframe seek.

**Comment by clsid2** [comment]
Seek to keyframe only works when the source filter provides keyframe information (IKeyFrameInfo interface). Neither the Microsoft splitter, nor LAV Splitter provides that for WMV. Go complain to them.

I don't give a flying fuck about what Potplayer malware does.

The video renderer is completely unrelated to seeking.

**Comment by sudongg** [comment]
@clsid2 
Although you don't like Potplayer, Potplayer can support keyframe seek for almost all formats, and its keyframe seek does not require special filter support.

Not only Potplayer, MPV is faster and better in keyframe seek, it also has a very fast file reading speed.

At present, the key frame seek of MPC-HC needs to rely on the LAV splitter. If the LAV splitter does not support the key frame seek, the key frame will not be supported.
The key frame seek implemented by the LAV splitter needs to obtain the key frame when reading the file, which will seriously affect the reading speed. 
That's why I came here to ask. But it seems that you just want to leave the problem as it is to the LAV team.
 
In fact, the use of video render has an impact on seek, but it has little impact. Jorger81 mentioned it later. I specially tested it and found that mad render is a little faster than EVR rendering. You can test it yourself.

**Comment by clsid2** [comment]
Keyframe information is not obtained by reading the whole file. Most file formats contain a seek index that contains that information. That is why seeking can be super fast even with a 50 gigabyte big MKV file.

MPC-HC does not depend on LAV Splitter. Keyframe seek works with any DirectShow source filter that uses the standard IKeyFrameInfo interface. LAV only exposes keyframe data for AVI/MP4/MKV. If you want it for something else, go make a request there. LAV uses FFmpeg just like MPV does, so it can have same file decoding capabilities.

The renderer does not have any effect at all on seek speed. It only has effect on how fast a frame gets displayed after it has been decoded. You are suffering from placebo effect.

**Comment by sudongg** [comment]
@clsid2 
My own project is based on Media Foundation and does not need to obtain the seek index. I only use FFmpeg to obtain the next key frame during seek. The seek speed is faster than MPV.

If the same file (MPC-HC support Keyframe seek) MPC-HC needs 3 seconds, Potplayer only needs 2 seconds or faster, MPV almost does not need to wait.

At present, MPC-HC depend on LAV Splitter. I don't know where the other source filters you mentioned are available, unless you add a large number of non-LAV built-in Splitter like MPC-BE.

@JorgeR81 Tell clsid2 that the mad renderer is not a placebo (:-D).

**Comment by clsid2** [comment]
MPC-HC opens files in less than a second here.

FFmpeg reads and uses the seek index.

MPV also uses FFmpeg, so you could make seeking just as fast as your project by tweaking things such as reducing buffer sizes.

If you think you can improve MPC-HC, I suggest you submit a patch.

I am not saying madvr is bad. MPC-HC was the first player to support it. I was talking purely about seek speed.

**Comment by sudongg** [comment]
@clsid2 
MPC-HC can open files faster, because MPC-HC is slower to open files in the DirectShow player I use.
It is forbidden to get the seek index when reading the file. This will make the file open one-third faster, which is equivalent to Potplayer.

If you implement keyframe seek without depend on filters (ues FFmpeg), you can increase the file reading speed and support more format keyframe seek.

MPC-HC is too complicated for me. I have no ability to improve MPC-HC by submitting patches. 

You can talk to JorgeR81 about mad renderer. I'm just publishing the results of my test. I've been using mad renderer all the time. No matter whether it has an impact on seek or not, I will still use it.

**Comment by sudongg** [comment]
@clsid2 
Sorry, I said earlier that potplayer can keyframes seek for wmv files when using LAV Splitter Source. It is wrong.
I found that no matter how it is set, potplayer cannot use LAV Splitter Source for wmv files, but uses Built-in ASF/WMV Source.
It seems that to solve this issues, I can only go to the LAV filter developers for help.
