### ISSUE TITLE
[Feature Request] HDR to SDR conversion

### ISSUE THREAD

**Issue by bobdig** [clsid2/mpc-hc#666]
I noticed that VLC is doing some automatic HDR to SDR conversion. I really would like to see that on MPC-HC too.

**Comment by clsid2** [comment]
You can get that functionality by installing this video renderer and selecting it in the output options of MPC-HC.

https://github.com/Aleksoid1978/VideoRenderer/releases

There are no plans yet to have the functionality in the internal renderers.

**Comment by bobdig** [comment]
Hey @clsid2 
So I installed it, but it is not doing it. Also I found no option for that. 
To be clear, on an SDR Monitor like mine, HDR content looks to bright and overblown. 
VLC corrected this, I changed nothing. 

![Capture](https://user-images.githubusercontent.com/46788742/96026473-d2b53780-0e56-11eb-83e7-651ca9efdcde.PNG)

**Comment by Aleksoid1978** [comment]
Enable statistics in options and upload screenshot.

**Comment by clsid2** [comment]
To have working HDR you need to use LAV Splitter, LAV Video decoder, and the internal subtitle renderer.
MPC-HC Menu > Play > Filters

You can not use filters such as ffdshow video decoder/processor or (xy)VSFilter.

**Comment by bobdig** [comment]
Thanks @clsid2  I had ffdshow raw video filter enabled for SVP!
Now it is getting complicated... No "HDR" with the old SVP.

**Comment by bobdig** [comment]
One question is left, why is this functionality (HDR) not in the normal package and only in an older version(?) of the MPC-Video-Renderer included?

**Comment by clsid2** [comment]
Correct, HDR is not possible with SVP+ffdshow. SVP needs to develop a new processing filter that supported forwarding the HDR metadata. Afaik they are already working on something.

The standard included renderers do not support HDR, and they never have before either. MPC Video Renderer is not old, it is a newly developed filter. It may get included in the future.

**Comment by clsid2** [comment]
@Aleksoid1978
Perhaps a good idea to display the name of the upstream filter in the statistics OSD? Short name can be used for commonly used filters (LAV/ffdshow/VSFilter).

**Comment by bobdig** [comment]
> 
>MPC Video Renderer is not old, it is a newly developed filter. It may get included in the future.

I meant that the included MPC Video Renderer is at a newer version then this special version I guess.

**Comment by clsid2** [comment]
Newer version is a development build.
