### ISSUE TITLE
[Feature Request] "Stereo" or "Mono Left" or "Mono Right" selecting

### ISSUE THREAD

**Issue by kato80** [clsid2/mpc-hc#667]
Some videos have multi-lingual voices, but the trouble is that the left voice is Japanese, and the right voice is English, without using multi-language channels system.
Such video is annoyed me when watching.

So I want to add the "Stereo" or "Mono Left" or "Mono Right" selecting feature.

 1. Stereo
 2. Left voice only (Right voice cutting)
 3. Right voice only (Left voice cutting)
 4. Left & Right voice swapping (really need this?)

Thank you.

**Comment by lifegpc** [comment]
Options -> Audio Switcher  -> Enable build-in audio switcher filter
Options -> Audio Switcher  -> Enable custom channel mapping
Then you can choose something you need.
![image](https://user-images.githubusercontent.com/41434272/96126246-a7018280-0f26-11eb-8673-d39d68e86c4a.png)

**Comment by clsid2** [comment]
These are often VCD files, right?
In that case you can also disable the internal MPEG PS source filter and MP1 audio decoder. Then it will use filters from Microsoft for those formats. The Microsoft mpeg audio decoder provides the mono channel audio options.
The active filters can be accessed through: Menu > Play > Filters

**Comment by kato80** [comment]
> These are often VCD files, right?
> In that case you can also disable the internal MPEG PS source filter and MP1 audio decoder. Then it will use filters from Microsoft for those formats. The Microsoft mpeg audio decoder provides the mono channel audio options.
> The active filters can be accessed through: Menu > Play > Filters

No, It happens at ".ts" files made by my TV recorder.
The active filters are this.

![MPC-HC--menu-filter-201016-clip](https://user-images.githubusercontent.com/56183692/96338811-80c91780-10cb-11eb-9ff8-1c331273494b.png)

**Comment by kato80** [comment]
> Options -> Audio Switcher -> Enable build-in audio switcher filter
> Options -> Audio Switcher -> Enable custom channel mapping
> Then you can choose something you need.

When I set it as shown in the picture, then choosed the voice as I wanted.
Thank you.

![MPC-HC--option-filter-audio-モノ化-201016](https://user-images.githubusercontent.com/56183692/96338869-d0a7de80-10cb-11eb-991c-bf62e57adeee.png)
