### ISSUE TITLE
Using mouse wheel + Crtl, Alt, Shift

### ISSUE THREAD

**Issue by JorgeR81** [clsid2/mpc-hc#669]
Hi,

The option to have a different mouse action on fullscreen mode is very nice. 
I've never seen that on another player, out of the box.

But is that a way to set combinations of mouse wheel with Crtl, Alt, and Shift?

I use the mouse wheel for everything: volume, frame-steps, increase/decrease rate, different jump intervals, adjust picture width (in case I have to make a small correction to an aspect ratio), and so on ...
MPC-HC plays everything I throw at it flawlessly. I'd like to use it more, but I miss all my custom shortcuts that I've set up in other players.

Thanks

**Comment by adipose** [comment]
Do you actually use ALT+mouse wheel? Or just shift/ctrl?

**Comment by JorgeR81** [comment]
I'm a hopeless case ...  I will take what you can give me ... 

Wheel ------ volume 

Ctrl + Wheel ------- jump forward and backwards 5 seconds
Shift + Wheel ------ jump forward and backwards 30 seconds
Alt + Wheel  ------- frame step forward and backwards

Ctrl + Shift + Wheel -------- increase and decrease playback speed
( Ctrl + Shift + Left click ---- set normal speed )

Ctrl + Alt + Wheel ---------- adjust picture width (1)
( Ctrl + Alt + Left click ------ reset width ) 
  
Shift + Alt + Wheel ---------- zoom in and out (2)
( Shift + Alt + Left click ------ reset zoom  (3) ) 

Ctrl + Shift +Alt + Wheel  ------- (well, I'm not there yet, ... but Potplayer would let me do it ...)


-------------------
(1) Actually MPC-HC feels so much better doing this than Potplayer !!!
MPC-HC changes picture width in larger intervals, and this allows me to do all the corrections I need, with a single "finger movement".

(2) I have a 27 inch monitor and some old SD videos, look better if I zoom out a little. 

(3) which is actually the same reset panscan command as "reset width", but this is better for muscle memory ...

**Comment by JorgeR81** [comment]
In Potplayer is very tedious to do all this customization. 

But since MPC-HC's shortcut menu is similar to an excel sheet, it could be very easy for the user to do all the combinations.

At first, I thought this is what the table was for...
I thought I could put Ctrl in the Key column and it would combine with the mouse actions available in the mouse column.

**Comment by adipose** [comment]
https://mega.nz/file/5d4wiASJ#chkk14nOnSvontB5hA75bQBU5v9NLyWg6O9H0go4MuI

Try this out.  What I did was allow it to "share" the virtual keys with the key shortcut.  It's maybe a little sloppy, but it only takes effect if you select a special option in the drop down to include "modifiers".  Right now it will fail to recognize regular shortcuts if you are holding down a modifier, to prevent multiple matches, but I could make it fall back.

@clsid2 , your thoughts on this.  It's a bit of a hack but I think it's simpler than adding modifier options to the table.

Use a key you don't care about to set the modifiers:

![image](https://user-images.githubusercontent.com/3324395/96209637-f2b32c80-0f24-11eb-8095-d3360432d047.png)

**Comment by clsid2** [comment]
Using the same modifier from the key for the mouse action does not feel like a good idea. That will have flexibility issues and maybe not be very obvious in terms of user friendliness.

Can't be just add a few more entries to the dropdown? Ctrl/Shift + Left Up/Right Up/Wheel Left/Wheel Right/Wheel Up/Wheel Down. That is 12 extra possibilities, 6 increase/decrease actions. That should be enough to provide a good amount of extra flexibility.

**Comment by JorgeR81** [comment]
Hey guys, no hurries! Take your time to do this right!
If you could implement this, I think it would be great for the future of MPC-HC.
A lot of Potplayer users are not happy with this software anymore.

**Comment by JorgeR81** [comment]
Potplayer is still my default player. I think It’s the only player that compares to MPC-HC, in terms of stability and features. But it’s also the oldest player version I’m using. 
It’s still free, but since the developer was bought by another company, it’s full of adware. 
I’m actually using the very last version before 1.7, in which the new owner reorganized the interface, at the beginning of 2017.

**Comment by JorgeR81** [comment]
I’ve also tried VLC, extensively.
It allows my shortcuts. But wheel customization can be a nightmare in VLC. It has a clever system where you press your shortcuts; and VLC “records” your key strokes, so that they can be assigned to a command. But, like 99% of the time, it fails to register mouse wheel movement, so It took me days to set up the shortcuts, for the (few) functions that are available. 

VLC has a lot of powerful features. It plays everything. But I rarely use it, because, inexplicability, lacks some very basic features, that people have been asking for years. I never talked to the developers, but just by reading the forum, it feels they have very little time to work on it. 
It does not support pause on click, you have to use a third-party plugin for that. 
It does not have frame step back (just frame step forward). 
It does not have the pan scan commands I talked above (for zooming out, and stretching the picture during normal playback).
It does not have a black theme, so you have to use a skin.
And if you use a skin, it takes about about 3 or 4 extra seconds to open. 
Also, if you use a skin, you lose one of my favorite things about VLC: choosing the buttons you have in the toolbar!
And some features like AB repeat, only work with the original interface buttons. You cannot set hotkeys for them. So, you lose this feature if you have a skin (because skins don’t usually have the AB repeat button).
And so son ...

**Comment by JorgeR81** [comment]
In Potplayer, I've tried several right mouse button combinations, but they never felt natural to use. Maybe it’s because I’m too used to “right click” to open the context menu, instead of performing a direct action.

I don’t like to do horizontal scrolling with the mouse wheel (Wheel Left/Wheel Right). It’s very hard to find a mouse with a good quality wheel, that gives you a good feedback. It’s very clunky, too slow (or too easy to over scroll), and not comfortable to use. I actuality prefer to use the arrow keys on the keyboard, instead. 

So, if you are thinking about adding extra possibilities to the list, could they be the ones below.

These might seem to be a lot of options, but with MPC-HC's list method, It would still be faster for the user, to set it up, compared to Potplayer. And infinitely better than VLC's way.

Ctrl + Wheel Up
Shift + Wheel Up
Alt + Wheel Up

Ctrl + Wheel Down
Shift + Wheel Down
Alt + Wheel Down

Ctrl + Shift + Wheel Up
Ctrl + Alt + Wheel Up
Shift + Alt + Wheel Up

Ctrl + Shift + Wheel Down 
Ctrl + Alt + Wheel Down 
Shift + Alt + Wheel Down

Ctrl + Left up
Shift + Left up
Alt + Left up

Ctrl + Shift + Left up
Ctrl + Alt + Left up
Shift + Alt + Left up

**Comment by adipose** [comment]
> 
> 
> Using the same modifier from the key for the mouse action does not feel like a good idea. That will have flexibility issues and maybe not be very obvious in terms of user friendliness.
> 
> Can't be just add a few more entries to the dropdown? Ctrl/Shift + Left Up/Right Up/Wheel Left/Wheel Right/Wheel Up/Wheel Down. That is 12 extra possibilities, 6 increase/decrease actions. That should be enough to provide a good amount of extra flexibility.

Yeah, I agree.  You have to choose a different option in the dropdown to enable it, though, so I thought it was fairly safe and more of an "undocumented" behavior, though I could add a tooltip.

At first I was doing it the way you suggested, but it felt unnecessarily limiting.  Like ctrl+wheel but not ctrl+shift+wheel.  And ctrl+left but not alt+left, etc.  The rules would have to be hard coded for each type of action.

Probably I could add another column for virtual keys for mouse without too much effort.  That feels like the "best" solution but I was trying for a shortcut.

**Comment by MadokaAyukawa** [comment]
The new developmental build (96) prevents saving of mouse functions for fullscreen mode in the options. Admin mode doesn't help, nor does clicking Apply then Ok. They work of the current session only.

**Comment by clsid2** [comment]
Fixed saving the new options.

**Comment by adipose** [comment]
@clsid2 , looks like the change you made is better, using unsigned.  But I'm curious why it worked for me just fine.  I used the same codes that were previously used for the virtual key code.  Now the virtual "key" code has a different scanf type than the "mouse" virt code.  Is that one wrong, too, but it just happens to work?

Confused...

**Comment by clsid2** [comment]
In case of fVirt an extra cast is used. Maybe that is why that one works.

**Comment by MadokaAyukawa** [comment]
After making Ctrl+Mouse Wheel for large jump, I cannot change it to just the mouse wheel without the modifier. To use the wheel I seem to have to have it as Ctrl+Mouse Wheel.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/692/files

This should fix it.  It should also work for any keys that had been changed.  However, for now you should reset that key.
