### ISSUE TITLE
Global stutter on loading most content

### ISSUE THREAD

**Issue by asknask** [clsid2/mpc-hc#67]
I've been facing this issue for years now. Finally decided to do something about it. I searched for an updated version of the beloved MPCHC and found this repo. I thought that by updating to this new version, the issue might resolve itself. It hasn't.

So this is a very weird issue. Let me try to explain it.

On a fresh system startup (Core i5-4670K @ 4.5Ghz, 16GB 1600Mhz, Radeon RX480, Content on HDD) everything is fine. Videos load almost instantly, seeking is smooth. However, sometimes (every time basically), usually after I've opened another big application (a game for instance) and closed it, this issue starts to happen.

The issue? A 2-3 second time window on file opening where my computer turns into a slide-show while the video loads. Everything turns into a slideshow - including the mouse movement or any other apps running in the background. I've tried this with various files. Seeking also becomes very sluggish (bigger delay in response to movement of seekbar).

The only way to fix the issue is by using **Old Video Renderer** but that doesn't display video for many formats and doesn't support most advanced features.

I'm currently using a fresh installation of version 1.8.4. I have not modified any settings.

If any info is required (system related), do let me know. Here's a sample MediaInfo from one of the files I was playing:

```
General
Complete name                  : F:\Aloha (2015) [1080p]\Aloha.2015.1080p.BluRay.x264.YIFY.mp4
Format                         : MPEG-4
Format profile                 : Base Media
Codec ID                       : isom (isom/avc1)
File size                      : 1.64 GiB
Duration                       : 1 h 44 min
Overall bit rate mode          : Variable
Overall bit rate               : 2 247 kb/s
Encoded date                   : UTC 2015-08-08 06:36:42
Tagged date                    : UTC 2015-08-08 06:36:42

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L4.1
Format settings                : CABAC / 4 Ref Frames
Format settings, CABAC         : Yes
Format settings, ReFrames      : 4 frames
Codec ID                       : avc1
Codec ID/Info                  : Advanced Video Coding
Duration                       : 1 h 44 min
Bit rate                       : 2 151 kb/s
Maximum bit rate               : 13.4 Mb/s
Width                          : 1 920 pixels
Height                         : 1 040 pixels
Display aspect ratio           : 1.85:1
Frame rate mode                : Constant
Frame rate                     : 23.976 (24000/1001) FPS
Original frame rate            : 23.976 (23976/1000) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.045
Stream size                    : 1.57 GiB (96%)
Writing library                : x264 core 123 r2189 35cf912
Encoding settings              : cabac=1 / ref=4 / deblock=1:-1:-1 / analyse=0x3:0x133 / me=umh / subme=9 / psy=1 / psy_rd=1.00:0.15 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-3 / threads=48 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=2pass / mbtree=1 / bitrate=2151 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=31250 / vbv_bufsize=31250 / nal_hrd=none / ip_ratio=1.40 / aq=1:1.00
Encoded date                   : UTC 2015-08-08 06:36:42
Tagged date                    : UTC 2015-08-08 06:36:51
Color range                    : Limited
Color primaries                : BT.709
Matrix coefficients            : BT.709
Codec configuration box        : avcC

Audio
ID                             : 2
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Codec ID                       : mp4a-40-2
Duration                       : 1 h 44 min
Bit rate mode                  : Variable
Bit rate                       : 93.7 kb/s
Maximum bit rate               : 102 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 46.875 FPS (1024 SPF)
Compression mode               : Lossy
Stream size                    : 70.2 MiB (4%)
Language                       : English
Encoded date                   : UTC 2015-08-08 06:36:51
Tagged date                    : UTC 2015-08-08 06:36:51
```

**Comment by clsid2** [comment]
Not the fault of MPC-HC. Probably a problem with your graphics driver. Update that. Disabling hardware decoding in the video decoder settings might help avoid the problem.

**Comment by asknask** [comment]
> Not the fault of MPC-HC. Probably a problem with your graphics driver. Update that. Disabling hardware decoding in the video decoder settings might help avoid the problem.

Using the latest version available from AMD. I've had this issue on a dozen different versions. I'll try your workaround today once the issue starts happening (fresh boot right now, smooth performance).

**Comment by asknask** [comment]
> Not the fault of MPC-HC. Probably a problem with your graphics driver. Update that. Disabling hardware decoding in the video decoder settings might help avoid the problem.

What exact option do I need to check/uncheck? I don't see anything like 'Hardware decoding'. Current DirectShow plugin is Enhanced Video Renderer (Custom Presenter). Like I said, haven't changed any options.

**Comment by clsid2** [comment]
Menu > Play > Filters > LAV Video Decoder

**Comment by asknask** [comment]
> Not the fault of MPC-HC. Probably a problem with your graphics driver. Update that. Disabling hardware decoding in the video decoder settings might help avoid the problem.

Same thing when playing a new video (or re-opening any video). If I set the decoder to D3D11, the seeking delay is fixed. The seeking delay is also fixed if I set the decoder to none. The other problem remains though, in all cases.

**Comment by clsid2** [comment]
D3D11 requires Windows 8 or newer. MPC-HC shows "H/W" in its status bar when hardware decoding is active.

There seems to be some kind of performance problem with your graphics hardware. I don't know what so I am not really able to help and this problem isn't caused by MPC-HC. With a tool such as GPU-Z you can monitor the clockspeed and memory usage. Maybe that gives you any clues.
