### ISSUE TITLE
Deleting file no longer works

### ISSUE THREAD

**Issue by Shajirr** [clsid2/mpc-hc#672]
Starting from version 1.9.5 (64-bit), shortcut to delete the current file no longer works.

Attempting to use it results in a Windows error "file is open in MPC-HC. Close the file and try again"

I checked task manager and there is only one instance of MPC-HC, so its not that multiple instances have locked the file.

No configuration settings were changed before/after deleting files stopped working.

System: Win 7 x64 SP1

_________________

Tested more versions:
- deleting a file doesn't work in 1.9.7, 1.9.6 and 1.9.5
- it does work in 1.9.4

**Comment by clsid2** [comment]
Should work with [1.9.7.74](https://github.com/clsid2/mpc-hc/releases/tag/1.9.7.34)
