### ISSUE TITLE
On top, While playing - not properly working [fixed madVR]

### ISSUE THREAD

**Issue by crisc2000** [clsid2/mpc-hc#674]
Tested version MPC-HC 1.9.7.74, but the bug is much older, I had similar problems to versions 2-3 years ago. Windows 7 x64.

Menu => View => On top => "While playing" is enabled.
Close the program. Click a video file. Even the video is playing when clicking outside the MPC-HC window seems to be not "On top".
Activate the MPC-HC window again. Click "Pause", now click "Play". Click outside MPC-HC window, now the window remain "On top". Correct functioning now.

Seems "While playing" is detected only after the Play button is clicked not from the start.

**Comment by clsid2** [comment]
It works fine here when opening a file through Explorer. I can't fix it if I can't reproduce it.

**Comment by crisc2000** [comment]
I have used Total Commander. But after your post I also checked Explorer. Same problem.
Did you tested in Windows 7? 

I have attached my mpc-hc64.ini to the post, maybe it has something to do with my settings of MPC-HC. I use MadVR
[mpc-hc64.zip](https://github.com/clsid2/mpc-hc/files/5417435/mpc-hc64.zip)

**Comment by clsid2** [comment]
No issues here with your ini on Windows 7.
Test if it also happens with a different video renderer.

**Comment by crisc2000** [comment]
I tested the render. Seems the madVR is the problem.
Then I went to madVR instalatiion directory and clicked this file "restore default settings.bat" . Now the "On top while playing" is working normal.
Weird ... no idea what was the cause.

**Comment by clsid2** [comment]
It is caused by the "delay playback start until render queue is full" option in madVR.
