### ISSUE TITLE
Crash when using MPC renderer/Enhanced renderer

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#676]
Seems like DXVA2 is a problem. Here's a screenshot
https://i.imgur.com/URSBq7v.png

**Comment by clsid2** [comment]
That file is a component from Windows. I can't fix that.

Updating your graphics driver may help to avoid the problem. Otherwise disable hardware decoding in the settings of the internal video decoder.

**Comment by ghost** [comment]
Thanks. I've suspected my GPU driver, i've talked with AMD, i will show your comment as more proof that something is off.

**Comment by clsid2** [comment]
Also check for damaged Windows files.
https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system

**Comment by ghost** [comment]
Thanks. I've already checked with sfc /scannow and DISM Repair. I even
repaired windows.

pon., 19 paź 2020 o 13:37 clsid2 <notifications@github.com> napisał(a):
