### ISSUE TITLE
Dark theme: MPC audio renderer display

### ISSUE THREAD

**Issue by dinataspace** [clsid2/mpc-hc#679]
Since this filter was added till the current development build (MPC-HC 1.9.7.96), the MPC audio renderer still doesn't display properly in the now playing filter list and in its properies settings.

![Capture](https://user-images.githubusercontent.com/73114258/96451175-644eeb80-1241-11eb-98a5-f1777e066cda.PNG)

![Capture1](https://user-images.githubusercontent.com/73114258/96451438-c6a7ec00-1241-11eb-87bb-b7ad1d1e1142.PNG)

**Comment by adipose** [comment]
I confirmed this, I suspect it has to do with the property sheet coming from an external library.  So far I don't see any obvious flaw in the code, and it works with other sheets, but I'll keep looking.

**Comment by clsid2** [comment]
Fixed
