### ISSUE TITLE
nothing but audio noise/distortion after long pause

### ISSUE THREAD

**Issue by glc650** [clsid2/mpc-hc#68]
If I leave a video paused for several minutes or more (10+?) and resume I get nothing but noise/distortion for audio.  Switching audio tracks (assuming there is more than one) fixes it as does exiting and restarting the video.  I noticed my AVR shows PCM when this occurs (prior to pausing audio was DTS/DD (bit-streaming)).  Windows Pro 10 with latest mpc-hc and external lav decoder.

**Comment by clsid2** [comment]
When you pause, the audio decoder stops sending data. Your sound driver will then start sending silent audio instead. PCM = uncompressed audio. If this doesn't work properly then it is the fault of either driver or AVR.

**Comment by glc650** [comment]
According to the developer of LAV filters the audio renderer needs to properly implement bitstream pause bursts for this to work.  Does mpc-hc's audio renderer support this?

**Comment by clsid2** [comment]
I don't think it does.

You can press Ctrl+E to reload the video. Combine that with the option to remember playback position.

**Comment by glc650** [comment]
Is that a feature that can be added?
