### ISSUE TITLE
[Feature Request] Allow Shifting of Subtitles Up and Down

### ISSUE THREAD

**Issue by MadokaAyukawa** [clsid2/mpc-hc#682]
Currently one is able to shift the subtitle left and right, but not up and down. Sometimes, the video has the black bars included in the video file so that the "Position subtitles relative to the video frame" doesn't work as the bars are part of the video. It would be nice to be able to shift the subtitles up on the fly to get them within the video (or down to get them completely within the black bar).

**Comment by ltguillaume** [comment]
I am missing this feature most. I'm quite used to adjusting the vertical subtitles position all the time in Kodi: for example. some videos have quite a bit of text appearing on-screen and it's nice to have the subs in the black bar below (if aspect ratio allows for it), while most of the time I prefer it inside the video frame. Apart from that, I also found that quite a few videos have "hardcoded" black bars, like @MadokaAyukawa stated, and that may lead to the subs being positioned _partly_ in the video frame, which turns out to be extremely annoying, at least for me 😉

**Comment by clsid2** [comment]
There is no ability to shift subtitle position left/right, the options you saw in keys are for subresync time shift.

I am not interested in implementing options to move subtitle during playback. It is also not easy to do.

**Comment by ltguillaume** [comment]
Judging from what's in the MPC-BE source, wouldn't it amount to this? (apart from the hotkeys routine) 

src\SubPic\SubPicImpl.cpp
```cpp
STDMETHODIMP CSubPicImpl::GetSourceAndDest(RECT rcWindow, RECT rcVideo,
                      /*ADDING THIS LINE*/ CPoint ShiftPos, /*ADDING THIS LINE*/
                                           RECT* pRcSource, RECT* pRcDest,
                                           const double videoStretchFactor /*= 1.0*/,
                                           int xOffsetInPixels /*= 0*/) const
{

(...)

	rcTemp.OffsetRect(ShiftPos); // ADDING THIS
        *pRcDest = rcTemp;

        return S_OK;
}
```

src\SubPic\SubPicAllocatorPresenterImpl.cpp
```cpp
HRESULT CSubPicAllocatorPresenterImpl::AlphaBltSubPic(const CRect& windowRect,
(...)
const CRenderersSettings& r = GetRenderersSettings(); // ADDING THIS
if (SUCCEEDED(pSubPic->GetSourceAndDest(windowRect, videoRect, rcSource, r.SubpicShiftPos, rcDest, // ADDING r.SubpicShiftPos 
```

src\mpc-hc\MainFrm.cpp
```cpp
void CMainFrame::SetSubtitle(const SubtitleInput& subInput, bool skip_lcid /* = false */)
{
(...)

    CAppSettings& s = AfxGetAppSettings();
    s.m_RenderersSettings.SubpicShiftPos = {0, 0}; // ADDING THIS

(...)
}

void CMainFrame::OnSubtitlePos(UINT nID)
{
	if (m_pCAP) {
		CAppSettings& s = AfxGetAppSettings();
		switch (nID) {
			case ID_SUB_POS_UP:
				s.m_RenderersSettings.SubpicShiftPos.y--;
				break;
			case ID_SUB_POS_DOWN:
				s.m_RenderersSettings.SubpicShiftPos.y++;
				break;
			case ID_SUB_POS_LEFT:
				s.m_RenderersSettings.SubpicShiftPos.x--;
				break;
			case ID_SUB_POS_RIGHT:
				s.m_RenderersSettings.SubpicShiftPos.x++;
				break;
			case ID_SUB_POS_RESTORE:
				s.m_RenderersSettings.SubpicShiftPos.x = 0;
				s.m_RenderersSettings.SubpicShiftPos.y = 0;
				break;
		}

		if (GetMediaState() != State_Running) {
			m_pCAP->Paint(false);
		}
	}
}
```

**Comment by clsid2** [comment]
Added vertical shift.

**Comment by ltguillaume** [comment]
Fantastic, thank you so much! 😃
