### ISSUE TITLE
M3U labels

### ISSUE THREAD

**Issue by rutkas** [clsid2/mpc-hc#683]
When loading m3u playlist with extinf tags

> #EXTINF:0,Label Name
> http://stream.url

Label Name should be displayed in playlist according to m3u specs, but only part of stream.url address is displayed that is not informative for iptv playlists entries. 

maybe there is a special trick to get labels from m3u in mpc hc ?

**Comment by lifegpc** [comment]
Can you provide a example m3u playlist file?
It seems works fine on my PC.
![image](https://user-images.githubusercontent.com/41434272/96586207-42be3480-1313-11eb-88b4-d7732477c242.png)
![image](https://user-images.githubusercontent.com/41434272/96586217-45b92500-1313-11eb-9607-8273371dd62f.png)

**Comment by clsid2** [comment]
@rutkas
Try latest development build:
https://github.com/clsid2/mpc-hc/releases/tag/1.9.7.34
If that doesn't work correctly, upload example playlist file.

**Comment by rutkas** [comment]
![image](https://user-images.githubusercontent.com/14265370/96595727-a9802580-12f4-11eb-8bbe-b300e7fa4aeb.png)

> #EXTM3U url-tvg=http://Triolan.tv/App_Files/jtv.zip url-epg=http://Triolan.tv/stb/xmltv.xml m3uautoload=1 cache=0 deinterlace=1 tvg-shift=0 groups="Все каналы|HDTV|Детский|Музыка|Новости|Обще-развлекательный|Познавательный|Развлечение|Разное|Фильмы"
> #EXTINF:0 tvg-name="TV1000 Action CEE" channel-id="12135" tvg-logo="http://triolan.tv/get_channel_logo.ashx?img=635739502612860382.png&div=1" aspect-ratio=16:9 groups="Все каналы|Фильмы",TV1000 Action HD
> http://tv1.triolan.com.ua:8888/udp/238.0.1.14:1234
> #EXTINF:0 tvg-name="TV1000 CEE" channel-id="12138" tvg-logo="http://triolan.tv/get_channel_logo.ashx?img=637254008570468227.png&div=1" aspect-ratio=16:9 groups="Все каналы|Фильмы",TV1000 East HD
> http://tv1.triolan.com.ua:8888/udp/238.0.1.15:1234
> #EXTINF:0 tvg-name="TV1000 World Kino" channel-id="10040" tvg-logo="http://triolan.tv/get_channel_logo.ashx?img=636319893506463199.png&div=1" aspect-ratio=4:3 groups="Все каналы|Фильмы",TV1000 World Kino
> http://tv1.triolan.com.ua:8888/udp/238.0.1.9:1234
> #EXTINF:0 tvg-name="ViP Comedy CEE HD" channel-id="12134" tvg-logo="http://triolan.tv/get_channel_logo.ashx?img=636445983606641257.png&div=1" aspect-ratio=16:9 groups="Все каналы|Фильмы",ViP Comedy HD
> http://tv1.triolan.com.ua:8888/udp/238.0.1.100:1234

tested on 1.9.7.34

**Comment by rutkas** [comment]
lifegpc, thanks for sharing your m3u. When I removed all tags from #EXTM3U - labels appeared, but maybe it is some kind of bug, cause playlists with tags in #extm3u are working correctly in vlc

**Comment by lifegpc** [comment]
MPC-HC now just support very simple m3u file. It not support tags after ```#EXTINF```.
MPC-HC now just support ```#EXTINF:<duration>,[<title>]```

**Comment by rutkas** [comment]
I see, but it could just ignore ignore anything after #EXTM3U in its line without breaking #EXTINF working. Please note that I just removed text after #EXTM3U (#EXTINF were left as it was) and it started to work:

> #EXTM3U
> #EXTINF:0 tvg-name="TV1000 Action CEE" channel-id="12135" tvg-logo="http://triolan.tv/get_channel_logo.ashx?img=635739502612860382.png&div=1" aspect-ratio=16:9 groups="Все каналы|Фильмы",TV1000 Action HD
> http://tv1.triolan.com.ua:8888/udp/238.0.1.14:1234

**Comment by clsid2** [comment]
Latest version is 1.9.7.100 and that one handles the title correctly here for you example.

**Comment by rutkas** [comment]
Just tested 1.9.7.100 and it does not show track names if m3u is started with:

> #EXTM3U url-tvg=http://Triolan.tv/App_Files/jtv.zip url-epg=http://Triolan.tv/stb/xmltv.xml m3uautoload=1 cache=0 deinterlace=1 tvg-shift=0 groups="Все каналы|HDTV|Детский|Музыка|Новости|Обще-развлекательный|Познавательный|Развлечение|Разное|Фильмы"

Same beahivour as 1.9.7.34

**Comment by clsid2** [comment]
That is fixed in next build.
