### ISSUE TITLE
In Player/Keys, the "Mouse Fullscreen" entry get cleared on exit

### ISSUE THREAD

**Issue by BoomerangAide** [clsid2/mpc-hc#684]
Hello,

I'm currently using version 1.9.7.96, and I have an issue: 

In View/Options dialog, in Player/Keys part, the "Mouse Fullscreen" entries get cleared on exit for several lines: Next, Fullscreen, and Player Menu.
Those are merely using the same setting as "Mouse Windowed".

Strangely, other lines don't seem to be affected, like Play/Pause, Volume Up, Volume Down.

If that can help, I've updated from the 1.9.7 release version, and I'm using the "Store settings in .ini file" option.

edit: Didn't see version 100 back then. Now running this one and it's fixed indeed. Thanks.

**Comment by clsid2** [comment]
Was already fixed in 1.9.7.100
