### ISSUE TITLE
Feature request: A key to switch playback rate between normal and the last used

### ISSUE THREAD

**Issue by YandLiu** [clsid2/mpc-hc#685]
I like to watch videos in 2x speed, but sometimes to clearly hear people's talking, I have to temporarily change the speed back to 1x, and then change it to 2x again. In MPC-HC, I have to accelerate the speed step by step.
Are we able to make the key of resetting the playback rate to a key switching between normal and the last used rate? This is implemented in PotPlayer, I believe many people would like to have this feature as well.

Cheers.

**Comment by clsid2** [comment]
Latest development build has options in the menu to adjust playback speed:
Menu > Play > Playback Rate

If you switch between 1x and 2x, then you can simply use the toolbar buttons to speed up and slow down.

Extra key binding will not be added.
