### ISSUE TITLE
Cue Sheets?

### ISSUE THREAD

**Issue by B00ze64** [clsid2/mpc-hc#687]
Good day.

I installed VLC recently (just in case) and discovered it can read *.cue sheets, and adds the included tracks to the playlist. Any chance of MPC supporting those? I searched the issues for "cue" but it seems this was never discussed.

Thank you.
Best Regards,

**Comment by clsid2** [comment]
Cue files are not supported. I am not interested in implementing that. Someone else will have to do it.

I does support other types of playlists, like M3U.

**Comment by lifegpc** [comment]
I write a simple parser for cue sheet. More works need to do while opening audio file. (Such as read chapters info from cue sheet.)
[Test build](https://mega.nz/file/h9g22Cab#n1cd0hA7ydxdPC2oxNgfg-oFha_JHiLoZblqRrJS3Vg).

**Comment by lifegpc** [comment]
This [build](https://mega.nz/file/U8YADBob#O1snMAhk7wSItI2YEaT2f08x6BMtEVqC79OZbYsWFHg) support read chapters info from cue sheet.
