### ISSUE TITLE
Removal of advanced option "AllowInaccurateFastseek"

### ISSUE THREAD

**Issue by vlakoff** [clsid2/mpc-hc#69]
13d5bb4aa30f918c774a04c4675d5ac6ede83d93 introduced advanced option "AllowInaccurateFastseek" as an attempt to fix #16 (amongst a few other similar tickets).

This advanced option had failed at fixing the seeking issue. However, the issue has been properly fixed since then (https://github.com/clsid2/FFmpeg/commit/60d12a4e78891a3b3ce85f2b54182054ef6dc5e1) :)

Therefore, the advanced option "AllowInaccurateFastseek" is useless, and its removal should be considered, for simplifying the codebase and the "advanced settings" page.

**Comment by clsid2** [comment]
The option is for dealing with huge keyframe intervals. The bug was due to wrong timestamp for keyframe seek. Unrelated issues.
