### ISSUE TITLE
Middle mouse click event triggers two times

### ISSUE THREAD

**Issue by lastmetroid** [clsid2/mpc-hc#691]
Since latest Windows 10 20h2 or one of the last versions of MPC, I am an 1.9.7, middle mouse click to pause/start doesnt work anymore and causes a double event, starting and pausing again instantly.

Edit: seems this issue is somehow related to Windows 10 not MPC :/

**Comment by clsid2** [comment]
The default mouse action for play/pause is left-click with mouse.

I have changed the keybinding in my settings to use middle mouse and it worked correctly on Windows 7. So yes, probably Windows 10 bug.
