### ISSUE TITLE
Option for a single color (dark grey) seekbar

### ISSUE THREAD

**Issue by JorgeR81** [clsid2/mpc-hc#693]
I like to use MPC-HC in windowed mode, but maximized, and just with the seekbar visible. I like the options for a tall seekbar, because I can point and seek faster with the mouse. But I end up with a large, "bright", light grey area on the screen. I would like an option to have the same dark grey color across the whole seekbar. The blue line is more than enough to keep track of playback time.

This for me, this would be the best looking interface of all players. 
All I need is that seekbar ...

![mpc_single color seekbar](https://user-images.githubusercontent.com/72734038/96999003-64463880-152c-11eb-993c-488b6cfbd3ee.png)

**Comment by adipose** [comment]
Can't say I care for that look, myself.  But one day I may build an interface to control some/all of the colors manually.

**Comment by JorgeR81** [comment]
That would be very nice. I like all these customization options. 
But, for me it's almost perfect right now.
I like very simple and dark interfaces. The only thing I really need is the seekbar. The rest I can do with shortcuts.
Since the picture here (1920 x 808) has a wider aspect ratio than my display (1920 x 1080), this dark look can almost make me forget I'm not in fullscreen mode. That's what I like about it. 
But the increasingly large "light grey" area right below the picture can be distracting for me.

**Comment by clsid2** [comment]
There will not be an option for this right now. You will have to wait until maybe one day there will be theme customization. But that is very low priority.

**Comment by JorgeR81** [comment]
It's OK. I'll use fullscreen mode, and access the seekbar, just when I need it.
If one day there could be theme customization, that would be great, but I understand there are much higher priorities.
Thanks.
