### ISSUE TITLE
MPC-HC can not play last file in folder

### ISSUE THREAD

**Issue by DRON-666** [clsid2/mpc-hc#697]
Test environment: folder contains three video files (**A.mp4** **B.mp4** **C.mp4**).
Now open **B.mp4** and hit `Next File` button: **C.mp4** opened successfully.
Hit `Move to Recycle Bin` button: **C.mp4** successfully deleted.
Hit `Previous File` button: **B.mp4** opened successfully.
Hit `Move to Recycle Bin` button: **B.mp4** successfully deleted.
Now after you hit `Next File` or `Previous File` nothing happen and last file **A.mp4** inaccessible.

**Comment by butterw** [comment]
try reopening mpc-hc ?

I just learned mpc-hc had a "Move to Recycle Bin" hotkey.

**Comment by ghost** [comment]
I can verify that this bug occurs also in the latest version 1.9.10.
I tested it with the "Move to Recycle Bin" hotkey.
This case will already do with the following scenario:
1. Put 2 media files (video or audio, both work for this) in one folder
2. Play any file first, and delete it
3. Try to play the next file by hitting "Next File" or "Previous File" - this won't work neither with audio files nor with video ones

I tested the case with mp4- and mp3-files. I don't know if other formats also have this problem, but I think so.

**Comment by clsid2** [comment]
Fixed
