### ISSUE TITLE
HDR support

### ISSUE THREAD

**Issue by z826540272** [clsid2/mpc-hc#699]
please add hdr support
，i have hdr screen ，hdr movie was gray out.

**Comment by clsid2** [comment]
Install one of these video renderers for HDR support:
[MPC Video Renderer](https://github.com/Aleksoid1978/VideoRenderer/releases)
[madVR](https://forum.doom9.org/showthread.php?t=146228)

Once installed, you can select them here:
MPC-HC Options > Playback > Output

If this is too difficult, then install K-Lite Codec Pack, which does it for you.
