### ISSUE TITLE
OSD Font Setting

### ISSUE THREAD

**Issue by haccy** [clsid2/mpc-hc#70]
Default OSD Font is face name of system font.
https://github.com/clsid2/mpc-hc/blob/1.8.4/src/mpc-hc/AppSettings.cpp#L1414-L1416

But setting combo box labels are full names of fonts.
https://github.com/clsid2/mpc-hc/blob/1.8.4/src/mpc-hc/PPageTweaks.cpp#L79

So in some environment, setting combo box is not selected correctly.
(ex. FullName=Yu Gothic UI Regular, FaceName=Yu Gothic UI}

**Comment by clsid2** [comment]
LOGFONT doesn't provide a full name. I modified the combobox selection code to search for facename as substring if an exact match isn't found. That should solve it.

**Comment by haccy** [comment]
In my environment, there are multiple full names start with "Yu Gothic UI": "Yu Gothic UI Light","Yu Gothic UI Regular","Yu Gothic UI Semibold","Yu Gothic UI Semilight" in order.
So selecting as substring makes ambiguous result, I wonder.
The first item "Yu Gothic UI Light" will be selected, though regular font "Yu Gothic UI Regular" expected.

**Comment by haccy** [comment]
CFont::CreatePointFont API requests  "the typeface name of the font" as argument ,

**Comment by clsid2** [comment]
If you think you can improve the code, then make a patch. I am not spending more time on this issue.
