### ISSUE TITLE
Mouse seeking in timeline changed to worse in 1.9.8

### ISSUE THREAD

**Issue by DV2FOX** [clsid2/mpc-hc#701]
Back when this happened they gave out a solution that worked like a charm

https://github.com/clsid2/mpc-hc/issues/370

But it seems that somehow it's ms values got changed again in the 1.9.8 version.

Is there a way to fix it back to what it was?..Yeah i know i can go back to 1.9.7, but what about the new fixes of 1.9.8?...

**Comment by clsid2** [comment]
It updates every 200ms now instead of 100ms. I see no reason to change it back.

**Comment by DV2FOX** [comment]
I'd atleast like to know how to change such value for myself (From 200 to 100) so i can use the latest version of MPC-HC but with 100ms. I've been staying in 1.9.7 (The latest build with such ms) because of this but i also want to get all the fixes and updates etc... But i need the 100ms.

**Comment by DV2FOX** [comment]
Can i at least know what i should do to mod the file(s) that forced the 100ms updates myself, please?. I'd like to use the newest version with all the fixes etc but with the 100ms update thing
