### ISSUE TITLE
Audio Exclusive mode not enforcing sample rate

### ISSUE THREAD

**Issue by BreakPoints** [clsid2/mpc-hc#702]
When using the internal audio renderer and exclusive audio mode being set, the output sample rate of the source file is not enforced as so will be resampled to the currently set default in Windows. This removes one of the major reasons for using the exclusive mode, bit exact output to the DAC.

MPC-HC 1.9.8 - Windows 2004

**Comment by bacondither** [comment]
Works fine for me, output sample rate follows source sample rate. Win 1809

**Comment by clsid2** [comment]
You can see what the renderer is doing here:
Menu > Play > Filters > Internal Audio Renderer

**Comment by BreakPoints** [comment]
Ah, human error! Was playing files with non standard sample rates and read 41000Hz as 44100Hz. It was falling back to my default Windows setting, as it should.

Apologise!
