### ISSUE TITLE
latest MPC 1.9.8 broke streaming

### ISSUE THREAD

**Issue by motfis** [clsid2/mpc-hc#703]
After upgrading to the latest version, I cannot stream some of my radio channel.
e.g. http://pu.klikhost.com:7112

**Comment by clsid2** [comment]
Works fine here.

This is the correct URL:
http://pu.klikhost.com:7112/stream

The URL that you posted works as well if you put youtube-dl.exe in MPC-HC folder.

**Comment by motfis** [comment]
Thanks. Indeed it is working now with /stream. Also other 'broken' links.
On the previous version, also other player, it is working without /stream.
Any explanatin what changes?

**Comment by clsid2** [comment]
Their webserver might redirect it to a different url based on the useragent used by the player. There have been a useragent related change.

But you should just use the 'correct' url. The older one only worked because it (in most cases) redirected to correct one.
