### ISSUE TITLE
Web Interface: MPC-HC in the Browser playlist navigation buttons reversed

### ISSUE THREAD

**Issue by davidc1701** [clsid2/mpc-hc#704]
When the Web Interface is enabled, and using the "MPC-HC in the Browser" option and using a playlist, the navigation buttons to skip to the next file in the playlist, or go to the previous file are reversed from how they function on the actual player.

To reproduce:
1. Have Web Interface enabled in the options to listen on a port
1. Create or open any playlist with 3 or more videos in MPC-HC
1. Open the web interface in browser, and choose the "MPC-HC in the Browser" option
1. Pressing the Previous button will take you to the next item in the list, and pressing the Next button will take you to the previous item.

**Comment by lifegpc** [comment]
Fixed it. [Test build](https://mega.nz/file/BlRkGLoR#oeYanc6Scp-4vUr1FuKZbmZfygHsl-dH8Y6jTOFVe24)
