### ISSUE TITLE
[Request] A way to change settings for internal fonts with soft subtitle

### ISSUE THREAD

**Issue by BoomerangAide** [clsid2/mpc-hc#708]
Hello,

Recently, I was playing a video that use internal fonts from within the .mkv file, and I wanted to edit the font size.
The issue is that when clicking on the font name button to load the Font selection dialog, in that dialog that allow to choose a font and set the font size and it being italic/bold/others, the selected font appear blank, and the internal font doesn't appear in the list.
It is impossible to quit that dialog unless pressing Cancel or completely choosing another font.

I wish there was a way to change the font size despite it being an internal one.

I suppose (maybe mistakenly) that font loading is done through a function with the font parameters as a string parameter. So it may be possible to avoid using the dialog font and be able to set the font size directly by using a different string.

If that's so, could we have a way to access the font size and modify it for each font directly?

_Note: I know there are the "scale" boxes but it's not rendered the same way as with a font size change_

**Comment by clsid2** [comment]
The Font dialog only shows installed fonts. I don't know if your request is even possible. I am not interested in investigating it.

**Comment by adipose** [comment]
What if instead of scale option you had a point size adder option?  It would have to be global like the scale.

**Comment by clsid2** [comment]
I would like to avoid having too much extra options.

Maybe the point size could be adjusted based on the scale factor. For example:
To change font size 18 into size 24, use scale 134% (~24.12)
When "ScaleX!=100 and ScaleX==ScaleY" we calculate the adjusted point size and see if that value is close to a valid size. If so, use that point value and set scales to 100.

**Comment by adipose** [comment]
Maybe one checkbox to say "round to nearest point size" and then it would do exactly as you say (discrete point sizes).  Otherwise it can do the current behavior?

**Comment by clsid2** [comment]
I don't think that would even be needed. Common use of the scale factor is often with big factors or ScaleX!=ScaleY. If the adjusted size is within 0.5 points of a valid point size, then that discrete alue can safely be used without worrying about unintended behavior.

**Comment by adipose** [comment]
10-4, that sounds good.

**Comment by BoomerangAide** [comment]
I wonder if things are happening in  mpc-hc/src/filters/transform/VSFilter/StyleEditorDialog.cpp 
Sadly I cannot experiment myself, so I can only ask questions.

edit: Could someone with the ability to compile the project see if removing CF_FORCEFONTEXIST in the aforementioned file (and maybe CF_SCALABLEONLY too, if font dialog still can't be closed), could allow to input the internal font name manually, and see it work as intended?
