### ISSUE TITLE
Feature request: command line switch for temporary disabling Youtube-DL

### ISSUE THREAD

**Issue by dongjuanyong** [clsid2/mpc-hc#71]
Sometimes I use you-get with "-p" option to open some online videos with MPC-HC, because those videos could not be extracted by Youtube-DL. But if I leave the "UseYDL" in the advanced options to "Ture", MPC-HC tries to deal the video with Youtube-DL at first. After a while, the video starts to play but stops in about 10 seconds. When I turn "UseYDL" to "False", the video plays perfectly.
Since there are only a few videos I need to use you-get instead of Youtube-DL, I think it will be very convenience that there is a command line switch for temporary disabling Youtube-DL, other than turn on and off every time. 
Thank you.

**Comment by clsid2** [comment]
I am not adding a command line switch.

But if you have an example URL where playback stops, I may be able to fix that.

**Comment by dongjuanyong** [comment]
Well, here is the case.
The grabber I used was called "ykdl"(https://github.com/zhangn1985/ykdl), which was a fork of you-get with some modifications. I used ykdl to play videos on a chinese live stream site "douyu" (other grabbers like streamlive can't extract videos from douyu right now). The command line I used was like:
`ykdl -p "C:\Program Files\MPC-HC\mpc-hc64.exe" http://www.douyu.com/525207`
When "UseYDL" is "True", the player shows "Calling Youtube-DL" for a few seconds then starts to play. About 10 seconds later, the playback stops and won't resume. When "UseYDL" is "False", there are no problems with the playback.

**Comment by dongjuanyong** [comment]
I see that you have updated the internal blacklist of ydl and added "douyu.com". But the URL which passed to MPC-HC by ykdl is something like this:
`https://hdlsa.douyucdn.cn/live/57321rvD2JpscNsv_4000.flv?wsAuth=xxxxxxxxx`
Thus I think blocking "douyucdn.cn" may be a better choice.

**Comment by clsid2** [comment]
Fixed
