### ISSUE TITLE
Wrong charset in download subtitles dialog.

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#710]
![image](https://user-images.githubusercontent.com/41434272/97711454-11eeb400-1af8-11eb-9a4d-50f804b80c1a.png)

**Comment by lifegpc** [comment]
It seems BUG already occurs in XmlRpcClient. I am sure XmlRpcClient return wrong result.

**Comment by lifegpc** [comment]
Third party library ```XmlRpc4Win``` use [```HttpOpenRequestA```](https://github.com/drtimcooper/XmlRpc4Win/blob/9eea9412a2a8effc1bccffb22212d04747ef75ae/TimXmlRpc.cpp#L1498), it may broke Unicode chars.

**Comment by adipose** [comment]
![image](https://user-images.githubusercontent.com/3324395/99013991-93860f00-2506-11eb-91b0-aea35bc508ca.png)

I'm not sure this is a bug.  Opensubtitles is showing the same bad data.  Perhaps it got uploaded with improper encoding?

**Comment by adipose** [comment]
Ironically it was uploaded by MPC-HC 1.9.1...

**Comment by adipose** [comment]
Searching for one that looks good on opensubtitles:

![image](https://user-images.githubusercontent.com/3324395/99014764-39864900-2508-11eb-8b9d-3b03ba8b9d84.png)

**Comment by clsid2** [comment]
So download is actually working ok, but upload possibly wrong?

**Comment by adipose** [comment]
It's possible but I don't think so. The linked video in the subtitle entry also has weird chars.

**Comment by clsid2** [comment]
That filename is part of the uploaded metadata, so affected by same bug, I assume.

**Comment by lifegpc** [comment]
The video filename is ```打ち上げ花火、下から見るか？横から見るか？```

**Comment by adipose** [comment]
I meant there was a link on opensubtitles to the video stream and it had a similar name as the subs file.

**Comment by clsid2** [comment]
I am pretty sure the "watch online" stuff is an ad.

**Comment by adipose** [comment]
If you upload subs what happens? If utf didn't work on upload, I would think we would have more trouble.

**Comment by adipose** [comment]
I tried testing this out on opensubs, but they deleted my uploads because they were "screwing up" the main page.  I cannot confirm mpc-hc is breaking the title when uploading, but maybe if you can send me the video in question I can try uploading a sub that has a different lang tag to see if it works or breaks the title.

One thing is sure, MPC-HC has no problem showing the chinese text from a properly uploaded sub, so most of the information in this bug report is wrong.  If we can confirm an issue uploading a sub, maybe we should create a separate bug.

**Comment by lifegpc** [comment]
[the video file](https://1drv.ms/u/s!Aoq8mAMlVv8UnVFeOu0JyqoccbAK?e=JUxg9Y).

**Comment by adipose** [comment]
Here is the opensubs page for that video, I think:

https://www.opensubtitles.org/en/subtitles/8098581/uchiage-hanabi-shita-kara-miru-ka-yoko-kara-miru-ka-it

English: "Fireworks (2017)"

All the subs that come up for your video (when searching in mpc-hc) seem to be for other videos.  Interestingly, if I try to upload subtitles, it finds imdbid 0119250, which is an entirely different movie:

https://www.opensubtitles.org/en/search/sublanguageid-all/imdbid-0119250

This movie is also named "Fireworks (1997)" and has no relationship to this video.  So, sadly, opensubtitles matches the hash to your video with a movie of the same title, meaning someone screwed it up at some point and now the two are associated.

No matter what I do, it seems to reject every upload I offer.  I have noted a lot of deficiencies in the opensubs uploader, like unchecked exceptions all over and weird assumptions about how the title should match.  I forced it to go through, and it claimed to succeed, but I never found my sub on the site.

If it ever shows up, I will be able to see if the utf8 is ok, but from what I can see, it should be fine as long as opensubs understands the utf8 name, which it should.

**Comment by lifegpc** [comment]
There are 2 movies which have same title. This is released on 2017. Not 1997.

**Comment by adipose** [comment]
Yes this is exactly what I was saying.

**Comment by adipose** [comment]
When checking the movie hash for your video file, it actually returns IMDB id 0119250, which is the wrong movie (Fireworks 1997).  Someone must have identified the wrong title for that hash.

**Comment by clsid2** [comment]
@adipose
You have an account on their forum, right? Could you ask it they actually get (m)any uploads coming directly from MPC-HC? If they don't then it might be a good idea to just remove the upload functionality, given its current bad state.

**Comment by adipose** [comment]
@clsid2 

About this, they did indicate they would like us to keep uploading, but they don't have a testbed.  Suggested I create a dummy account and upload and then delete.  I'll see how it goes.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/852

**Comment by lifegpc** [comment]
looks like good.
