### ISSUE TITLE
Unable to control the volume of MIDI, cannot play two MIDI files at once

### ISSUE THREAD

**Issue by sykoram** [clsid2/mpc-hc#711]
Hi,

When MPC-HC plays a MIDI file, I am unable to control the volume nor mute it. The volume increases/decreases only in the volume bar and I can see the mute icon muting/unmuting, but it has no effect on the playing sound.

Moreover, when I try to play two MIDI files at once, I can hear only the first one. The second one can be heard only after completely closing the window of the first file.

**Comment by clsid2** [comment]
Playback of MIDI files does not use the normal audio renderer. It uses the Windows Midi output device instead. That apparently only supports one instance at a time.

I don't know if it is possible to improve this playback behavior. I don't have any time or interest for this.

**Comment by sykoram** [comment]
Ok, thank you for the clarification
