### ISSUE TITLE
Subs to be improved on these 2 cases + minor things

### ISSUE THREAD

**Issue by i2324561w2** [clsid2/mpc-hc#712]
On these 2 cases VLC is better, so I hope you can do something about it:
http://www.mediafire.com/file/atzgrrxcbwlxfi9/Fragtime%253B_at_second_10.mkv/file
http://www.mediafire.com/file/2scdzzip62kvahm/SteinsGate_03%253B_on_the_phone.mkv/file

Also when you use the Play key shortcut the speed is always restored to 1x, but if one wants to use another speed and then pause the file, pressing again the Play key should keep the previous speed in my opinion.
And the message appearing on top left after you use Play lasts maybe too long compared to other messages.

Thank you for everything.

**Comment by clsid2** [comment]
Speed remains unchanged here after pause/play. If playback has reached end, then it gets reset.

**Comment by i2324561w2** [comment]
> 
> 
> Speed remains unchanged here after pause/play. If playback has reached end, then it gets reset.

You are right, sorry.

**Comment by i2324561w2** [comment]
> 
> 
> Speed remains unchanged here after pause/play. If playback has reached end, then it gets reset.


> 
> 
> You are right, sorry.

Actually no! I have "Speed Step"=50%, I play a file, use the 1.5X speed, pause, play: the speed is at 1X instead of 1.5X!

**Comment by clsid2** [comment]
The missing subtitle lines in the first video use the font "Royal Brush". This is an OpenType font and it somehow fails to render properly. I don't know how to fix.

Below is simplified subtitle for reproducing it. In case anyone else want to try.
```
[Script Info]
ScriptType: v4.00+

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Amaranth,40,&H00FFFFFF,&H0300FFFF,&H00000000,&H02000000,0,0,0,0,100,100,0,0,1,4,0,2,200,200,60,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:20.00,Default,test,0,0,0,,{\fnRoyal Brush}Test
```
