### ISSUE TITLE
Native ARM64 build?

### ISSUE THREAD

**Issue by tringi** [clsid2/mpc-hc#714]
Please consider this low priority. The x86 version works perfectly well on my Windows ARM laptop.
Still, if feasible, compiling and providing native ARM64 build would be greatly appreciated.

**Comment by clsid2** [comment]
I am not interested in doing that. I also don't have any ARM hardware.

**Comment by ArminiusTux** [comment]
Dear @clsid2, any change in your interests concerning Windows on ARM?🤞

**Comment by clsid2** [comment]
NO!!!!!!
