### ISSUE TITLE
Save playlist position

### ISSUE THREAD

**Issue by Loceka** [clsid2/mpc-hc#715]
Hello,

It would be really nice to have an option to save the playlist position, either by saving manually saving the playlist (adding a "current position" in the playlist file) or automatically, using the same mechanism than video position saving (this solution would be better)

When watching multiple videos, one has to manually delete all watched videos and re-save the playlist with only the left overs.

**Comment by karmacat77** [comment]
Hi.  This functionality would be fabulous!  I don't use playlists for precisely this reason.  There's no point in making a playlist for say a tv series with many episodes if it doesn't remember where you're up to and just starts at episode 1 again each time.  Perhaps there's a technical reason why this functionality isn't easy to do in MPC, but in this age of streaming servcies you'd think there'd be a massive demand for it because users are so used to having it.  Thanks very much for continuing to develop MPC.

**Comment by clsid2** [comment]
If you enable the "Keep history of recently opened files" option, then it will already select the last played file in the current playlist when you re-open the player.

Making a playlist for a series is totally unnecessary. You can simply click on PageDown button to go to the next file in a folder. The player even has options to do that automatically at the end of a file.

**Comment by karmacat77** [comment]
I think playlists have several advantages of convenience.  The existing 'play next file' feature is not as convenient when you're swapping between many different series.  In that case, to continue viewing a series from its last position, the user needs to manually search for the most recently listed filename belonging to that series in the file history list.  That list can get very long and the filename may have even dropped off the list by then.  Compare that to clicking on a playlist shortcut.  Also 'play next file' sorts the source folder by filename only, so users can't as easily reorder the files as they can within a playlist or combine files from different folders and drives.  Is there a technical reason why file/position data cannot be saved for a playlist?

**Comment by clsid2** [comment]
Modifying the playlist file format to add extra stuff inside is a technical issue. Storing it externally is possible, but a lot of work. Plus there is the issue that some people don't want to remember position, so there needs to be an option.

I just don't care enough about this issue to spend my time on it.

**Comment by adipose** [comment]
@clsid2 , maybe we can close this one now.
