### ISSUE TITLE
Always-Subs

### ISSUE THREAD

**Issue by roysubs** [clsid2/mpc-hc#716]
For people that need subs, it would be have a simple mode that always automates subs. MPC-HC is by far the best player out there, and the simplicity of the interface is one of its biggest strengths, but for example, my girlfriend is partially deaf and so wants subtitles for every file. If the following is already implemented, please let me know, but I would imagine that could be so simply done via a setting called say **"Always try to force Subtitles"** (and with a language preference), which will then follow a simple process on opening every file if it is turned on:

**Step 1.** Try to use built in subtitles if available in the file, or an external file if present, and then always Enable subtitles and use the language preference as set.
**Step 2.** If no local subtitles are available, automatically download the first available subtitle from searching all sites (that matches the preferred language) and open that with the video. Again, make sure that the subtitles are then Enabled.
**Step 3.** If this mode is on, then the "D" shortcut key will act as a toggle, so: go to the next subtitle in the download list, download and use that, then "D" again to go to the next subtitle file and so on.

I'm hoping that something like this could be simple to implement, since the all of these components are already in place!

As an side question, many subtitles are out of sync (subtitles are not a perfect science and I've never found a way to align subtitles - sometimes you can use the options to push subtitles back or forward to try and match, but they often never align, staying in sync for 30-60 seconds then slowly falling out of sync again), hence why the above switch to just jump to  next available subtitle file  from available downloads would be so useful. But, in addition to that, are there smart ways to get subtitles to align, i.e. to stretch their time delay instead of just adjusting the time position of the file?

**Comment by MadokaAyukawa** [comment]
While I don't download subtitles, what you want in terms of automatic subtitle selection already exists. The the LAV Splitter Options, set the subtitle selection mode to advanced, then you can set your desired audio/subtitle preference there. I have it to select Forced English subs if the audio is English; otherwise if English audio, no subs; otherwise for any audio language other than English use English subs first, then Undermined subs. It's been working great so far. The only time it doesn't work is if the video has the wrong language code for the audio or subtitle stream.

You can set it to automatically search and download subs, in the Subs>Misc section, although I've never tried it.

If you just want English subs all the time, regardless of audio language, you should be able to set that up in the Playback options screen.

In terms of your side question, you would need to learn to retime/resync subs. I do this all the time when the subs don't match my video. I can add time to the subs to make them stay on screen a little longer to make them easier to read. It only takes a minute or so. MPC-HC can adjust the timing, but that's just a temporary solution.

**Comment by clsid2** [comment]
Automatic subtitle download: Options > Subtitles > Misc
Manual search: Press D
Preferred language for embedded/external subs: Options >Playback > Default track preference
The above can optionally override the track selection choice made by LAV Splitter. Or you can configure that in:
Options > Internal Filters > Splitter

For adjusting timing several subtitle editor tools exists. And even online websites for basic adjustments.

**Comment by roysubs** [comment]
I already had these settings for a long time and unfortunately, it does not work (subtitles are not automatic). I tested "The LAV Splitter Options, set the subtitle selection mode to advanced, then you can set your desired audio/subtitle preference there." and all other above options and none work. I've found the **LAV Splitter** menu (thanks) where you've said and tried all of the options in there, and all options under **Misc** but still no automatic loading.
 
The box displaying available subtitles pops up, but never once have I seen an automatic download. It just sits there displaying the available subtitles (can't it just pick the first one and load that and go? Because that is all that I do in 100% of cases anyway... tedious to do the same thing over and over ... and with what I describe above you get the best of both worlds, i.e. autoload, then hit D to toggle to the next subtitle and so on).

I've never seen Subtitles automatically downloaded (i.e. I open a file, and the subtitles "automatically" download and open). I don't mind pressing "D" to get additional subtitles if that one doesn't work (though it would be vastly preferable if pressing "D" would just pick the next subtitle in the available list and download/load it; that would make more sense as that's all we ever do anyway - the only reason to ever change a subtitle is because the one in use doesn't work and you want to find another that does work after all!). It seems a no-brainer to have a way to just grab the first file and load/play. 

But from reading the above, it sounds like you have automatic downloading, I would love to know how to do that. I have never seen: a) open file, b) MPC-HC automatically selects the first available subtitle, downloads it, opens it, and uses it. If there is something I'm missing here, I'd love to know (i.e. how can I stop the "Download Subtitles" box appearing when I start a film and just make it "automatically" download subtitles and start playing them?).

**Misc**
- Prefer forced and/or default subtitles tracks [checked]
- Prefer extrernal subtitles over embedded subtitles [checked]
- Ignore embedded subtitles [not checked]
Online search download
- Automatically search and download subtitles if none are found locally [checked] (but does not work)
- Prefer subtitles for hearing impaired [have tried both checked and unchecked]

**LAV Splitter**
- Subtitles (I have never filled in this in, but now I have put "eng,en" or "eng en", neither works.
- Enable Automatic Forced Subtitle Stream [checked]
- Demux sub-streams separately [checked]
- Prefer Audio Stream with the Highest Quality [checked]
All others unchecked, still no change, subtitles do not download automatically. 

Everything is there to make it all work seamlessly, MPC-HC just intelligently grabs the first available/matching subtitle and downloads it and uses it (then press "D", or whatever you prefer to switch to the next in the available list if that one doesn't work). It just seems a trivially simple (but also useful) to include the following behaviour.
- When a film is loaded, and the Subtitle dialogue ("D" screen) appears, just go ahead and pick the first match and load it.
- Then, instead of "D" bringing up the Subtitle dialogue, just make it toggle to the next in the list (i.e. pick next in the list, then download and load that). All I go in here for is to pick the next one in the list anyway, so automating that would be really nice).

I'm trying to think of scenarios where automatic download/load/use subtitles would not be wanted, but isn't that the point - if you want/need subtitles, you want them to just load, what is the point of showing an available list? Just load the first in the list. If that doesn't work, press "D" to go to the next in the list, and so on. The object, after all, is just to find a subtitle that works, so displaying the menu is redundant (but if people really want it, make "Ctrl-D" open that menu while "D" just switches to the next subtitle in the available list - I highly doubt anyone would use "Ctrl-D" though as what would be the point? After you get a subtitle that works, you just continue to watch the film after all - and if this *is* possible currently, I'd appreciate knowing how as I've never seen it, would be great to have that functionality, would make working with subtitles so much simpler).

**Comment by clsid2** [comment]
It downloads automatically if you enable that option AND if it finds an EXACT match. It uses a file hash to search for a subtitle that was made for exactly that file. It doesn't just randomly pick a non-exact search result because those are often wrong or have timing issues like you already noticed yourself. It already is as intelligent as it can be. If you want guaranteed good subtitles, download files that already include them. Good quality rips typically also include English subtitles.

Here is some documentation for the selection rules in LAV Splitter:
http://1f0.de/lav-splitter/lav-splitter-stream-selection/
You probably just need to use advanced mode with this `*:eng|h,*:eng,*:*|df`
That equals: hearing impaired English, normal English, otherwise whatever is set a default/forced

**Comment by roysubs** [comment]
Thanks for this, really appreciate it (didn't know that syntax for the LAV part, great to know). ah, it uses a hash, that makes sense, interesting.

I'm trying out all of your tips, and my example just now is a file called "The Incredibles (2018).mp4". I chose this because it specifically has no internal subtitles. I've used LAV splitter advanced mode with `*:eng|h,*:eng,*:*|df`, and the Subtitle window always appears. I do understand/appreciate the rationale for only loading a file if it's an exact hash file match (that makes sense), but that also means that auto-loading might only happen for 1 in 100 (or maybe 1000!) files. Now, for my test case today, there were some bad matches listed ("Incredibles 2004", "Mission Impossible Fallout 20018", "Lucy 2014" and "The Boss Baby 2017"), but 15 out of the 19 subtitles are for my film. Indeed, the first found subtitle in that list is "Incredibles 2004" and that is a bad match(!), but I *would* actually like MPC-HC to just go ahead and load that, as long as I can just jump to the next in the list with a simple shortcut key like "D". i.e. the scenario is:
- I load up my film with this setting / default behaviour enabled.
- MPC-HC intelligently just loads the first found subtitle (which happens to be wrong, for a different film!). A tooltip appears on the screen for 2 seconds saying **"19 Subtitle files found. Loading 1 of 19: name_of_file"**. 90+% of the time, this will be a good subtitle and I can just watch the film. Happy days, this is perfect...
- However, in case the subtitle is not a perfect match, I can then just press "D", not to open the Subtitle screen and pick a new one, but instead to go to the next found subtitle. A tooltip appears on the screen saying **"19 Subtitle files found. Loading 2 of 19: name_of_file"**. (i.e. when this option is enabled, "D" just acts as a switch to rotate through the found subtitles. In the 10% of cases that a perfect match is not found first time, I just hit "D" a few times until I hit the jackpot and get a perfect match and that's really nice / elegant functionality.

I think, for people that use Subtitles a lot as I do, this would be a really wonderful default behaviour, and hopefully quite a simple implementation? Either by adjusting the default behaviour, or a new **"Auto-load and rotate through found Subtitles"** option, but I think if this was the default behaviour, that could be quite nice (and if anyone wants to see the Subtitle dialogue, which I would not need 99% of the time, maybe map "Ctrl-D" to that or something, while pressing "D" just spins us through the available/found Subtitles from the list until we hit one that works for the film). What do you think?

**Comment by clsid2** [comment]
The settings in LAV Splitter only apply to embedded subtitles. The language settings in MPC-HC can be used for external subtitles.

If your video file is a commonly downloaded video, then there is relatively high change that a hash match is found. You should also avoid giving your files a "pretty" name after download. Or at least search for subtitles with the original name first, as that gives better results for non-hash matches. You can store the downloaded subtitle through File->Subtitles for later use.

You can already select and download multiple subtitles at once from the search window. You can then cycle through them with S or select them through play menu.

This player has several million users. I am not going to customize behavior for individuals.

**Comment by roysubs** [comment]
ok, good to know that LAV is just for embedded, thanks.

No problem if not wanted, it's basically just a change to the default behaviour to make it considerably more user friendly, i.e. it's really not about me, I was trying to lay out above why this would be useful for several million users. For example, take opening a file, when I associate .mkv with MPC-HC, and I double-click on a .mkv file, the behaviour of MPC-HC *could* be to open up a menu and get you to select a number of options, and then you have to confirm that before the film plays, *or* the behaviour could be to just play the film. That's great, the film just plays and that behaviour is ideal. Exactly the same with this. MPC-HC *could* open up a menu to let you select a subtitle file, making you confirm all of that before the subtitle loads, *or* it could just auto-download and use the first available subtitle and go with that (then let you toggle as required). Just as millions of users prefer a video to *just go ahead and play*, I suspect that several million users would prefer it to just download a subtitle and then let us toggle through the subtitles (just as I might skip forward or change the volume) ... just seems more natural (for all users, that's why I was trying to be as generic as possible in how I was proposing that).

But I understand that it's a change to default behaviour, i.e. a move from a) auto open and just use the first subtitle file found vs b) put a dialogue in front of the video that folks have to manage and muck about with. I suspect that 99% of all subtitle users would want behaviour "a)", but I don't have a means to poll them so I could be wrong, and it might even be as low as 98% of subtitle users that would prefer that behaviour! :-) . No problem if it's not on the radar, just felt worth asking about that as was curious, and hopefully / maybe something that could be considered in future. Either way, I greatly appreciate the info that you've given me.

I never knew the "S" option, thanks for that, this looks good. Ok, I'm looking at that option now, and I find that I have to select all 19 subtitles one by one - there is no "bulk select" checkbox at the top of that dialogue, might that be added so that I can just select all, then cycle through them with the "S" ?

**Comment by clsid2** [comment]
Downloading multiple by default will NEVER happen. OpenSubtitles already had major issues earlier this year due to too many downloads, requiring them to restrict downloads to users with a login. Plus people who want subs, want a correct one, not a shitload of random ones that might contain a good one.

I don't have time to implement a select all option. Too busy with more important things.

**Comment by roysubs** [comment]
Ah, that makes sense. If OpenSubtitles put a restriction down like that, absolutely, best to not hammer their servers.
In that case the "just open the first subtitle file found" is a better default behaviour and wouldn't hammer their servers. and I say that because I also want *correct subs*, but of course there's the kicker: *you don't know if a sub is a correct one until after you download it and check it* (some names are obviously wrong, but in my experience, about 95% from the found list will have the names that match the film, so you'd never lose much by getting one or two wrong names, you'd never get a pile of random ones, just the occasional mistake). That's why the default behaviour to just open the first sub might be a really good solution. Anyway, I thought this might be a nice generic "user experience" point but no problem, thanks for the tips and I'm sure you have other more important things to do - and it's really great that you picked up the project! Cheers.
