### ISSUE TITLE
Subtitles search regression in 1.9.8

### ISSUE THREAD

**Issue by simo1994** [clsid2/mpc-hc#717]
Hello,
After updating to 1.9.8 I've been noticing the following behavior, which I can't seem to disable.

Subtitles are first fetched by hash, then an imprecise filename search is done and the results are added to the already perfect hash results, making it extremely difficult to locate the correct result.

I think the correct behavior should be to search by filename only if there are no hash matches, as the filename results are extremely imprecise (wrong episodes).
Or at least there should be a way to differentiate the two types of results (the user may be interested only in hash matches).

Thank you

**Comment by clsid2** [comment]
Give me a link to an episode where you see this issue.

**Comment by adipose** [comment]
It is supposed to do the imprecise search only if the hash fails. Maybe the hash didn't actually work?

**Comment by clsid2** [comment]
Or the "good" result came from a different provider? Maybe the imprecise search should be done only if nothing gives a result?

**Comment by adipose** [comment]
That I possible, I suppose. That would take a bit of # a code refactor to fix.

**Comment by simo1994** [comment]
Hello, first of all thanks for the support.

I tried opening the "Subtitles" panel very quickly, and at first good results are returned, after a second or so, also imprecise results are returned, and they are indeed from a different provider. I'll attach some screenshots:

During search, 5 correct results:
![image](https://user-images.githubusercontent.com/17798979/97806692-3f08a700-1c5d-11eb-91dc-ebb5be67db17.png)

After search, 35 results, mostly non-relevant:
![image](https://user-images.githubusercontent.com/17798979/97806696-429c2e00-1c5d-11eb-8fa7-72ee48d30f75.png)

I think you should either (1) disable the imprecise search if at least 1 provider returns an hash match; (2) make it possible to "filter" the type of results like so:

![image](https://user-images.githubusercontent.com/17798979/97806814-cb1ace80-1c5d-11eb-9ec4-dc32c6ad727d.png)

Again, thank you for the awesome work you developers do!

**Comment by clsid2** [comment]
The imprecise search is done only for OpenSubtitles, when that does not return results. The results coming from podnapsi are completely independent from that behavior.

We could however maybe sort the list better so that hash matches are shown on top of list.

**Comment by simo1994** [comment]
Could the search results be filtered automatically so that the series+episode substring must be present in the result?
I'm starting to think that I "blamed" the change outlined in the latest release notes, whereas the problem might be somewhere else.

**Comment by adipose** [comment]
Can you upload the file that caused the issue?  Code for podnapisi is supposed to use a file hash.  I'm not sure how it controls the results if that hash doesn't exist in their db, though, because it also is passing year, season, and episode number if it can.
