### ISSUE TITLE
Can one over-install this fork over the original MPC-HC?

### ISSUE THREAD

**Issue by hldetf** [clsid2/mpc-hc#721]
I have been using the original MPC-HC for years even though it has been discontinued. I recently found this fork, but due to my lack of knowledge, I am not entirely sure if one can over-install this fork over the original release of MPC-HC(i.e. simply installing this fork without uninstalling the original version). While this is a rudimentary question, I would like to know how this kind scenario works. I am using the Windows x64 version of the original MPC-HC(installed via the exe file).

**Comment by clsid2** [comment]
Yes, the installer is still the same as the original.

This project is not really a fork but just a continuation of the original project.
