### ISSUE TITLE
MPC-HC v1.98 can't find any files if relative pathname is in use (playlists / .M3Ux)

### ISSUE THREAD

**Issue by Michamel** [clsid2/mpc-hc#724]
Hi together,

With the last release, the new MPC-HC can't handle playlists (.M3U) with relative pathnames:

> Folder1\Track1_Folder1.flac
> Folder1\Track2_Folder1.flac
> Folder2\Track1_Folder2.flac
> Folder2\Track2_Folder2.flac

![error_02](https://user-images.githubusercontent.com/65981135/97957754-1c38d880-1dac-11eb-809f-0b417d5aebee.jpg)

It seems, the versions with v1.98 and higher cannot open the folders and don't open the media file(s) and don't show any cover arts.
With the older MPC-HC versions -> no problems.

![error_01](https://user-images.githubusercontent.com/65981135/97957751-1ba04200-1dac-11eb-9de9-966c23b0e7f1.jpg)

Can you check this?
Thx. in adv.!

Michael

**Comment by lifegpc** [comment]
Interseting bug. You can use ```/``` to replace ```\``` , it will works.

**Comment by lifegpc** [comment]
@Michamel [Test build](https://mega.nz/file/plg3GSqZ#LTNSd7Exs8ot-6gzfgVQOf1WIvZF7C_MkTXkkCMbGCc)

**Comment by Michamel** [comment]
> 
> 
> @Michamel [Test build](https://mega.nz/file/plg3GSqZ#LTNSd7Exs8ot-6gzfgVQOf1WIvZF7C_MkTXkkCMbGCc)

Perfect - it works again!    :o)

**Comment by Vagmer** [comment]
Encountered the problem too, and went to look if it was reported -- can also confirm the regression and the fix. Just had this process (using x64 versions):

-Was playing my playlist on 1.9.7, received update notification and decided to update. Replaced my copy with 1.9.8.
-Tried to resume my listening and immediately noticed regression - playlist no longer worked (has relative paths to files). Funny coincidence.
-Decided to update to latest "development build" to see if it was already fixed there - confirmed it was (updated from 1.9.8 to 1.9.8.33, playlist works again).

Thanks for the quick fix! It should probably be mentioned somewhere (like in multiple releases notes as relevant) so people know.
