### ISSUE TITLE
Next / Previous Image in folder

### ISSUE THREAD

**Issue by demolitioner** [clsid2/mpc-hc#727]
MPC-HC can open images, like jpg. But it cannot make "Next / Previous Image in folder" with "skip back", "skip forward", pgup, pgdn buttons.
Add ability to do this.

**Comment by clsid2** [comment]
Skipping is intentionally limited to known audio/video formats by default. Because when playing such files you generally want to ignore images when skipping to next file.

But when an image is already open, we should indeed allow to skip to an image.

**Comment by clsid2** [comment]
When implementing, these helper functions should be implemented to simplify code in various places:
bool IsVideoFileExt(CString extension)
IsAudioFileExt/IsImageFileExt/IsPlaylistFileExt/IsAudioOrVideoFileExt

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2467
