### ISSUE TITLE
How to keep History but Script should not add content to history

### ISSUE THREAD

**Issue by Mae72DE** [clsid2/mpc-hc#729]
Script:
```
@echo off
 start "Video" "%ProgramFiles%MPC-HC\mpc-hc64.exe" "H:\xxx" /add "xxx" /randomize /volume 0 /play /viewpreset 1
```
But it will be nice that after closing the Player it will not store the xxx-folder in history and return to the old viewPreset. Has anyone a solution for that?

 **History**
 ☑ keep hstory of recetly opend files

Missing Option: /forgot

**Comment by clsid2** [comment]
Make a copy of the player folder and enable the option to store the settings in INI file. Then that copy will have settings that are separate and different from your normal copy of the player. Use that to watch your nature films ;)

You must make the copy in a user writable location because otherwise it can't write to the INI. Folders like ProgramFiles are system protected and require admin rights to modify.

**Comment by Mae72DE** [comment]
Thank You very much!
But please:  • where do I find info about the INI-File?
Is it just to call `mpc-hc64.ini` and then it will create by Programm-Settings automatic?
Is there a Doc to find here about this ini-file?

Can I give the INI-File already the parameter need to forget history?
Is there already an option to set pause time between showed JPEG-Pictures?

```
<!-- : CMD+Script: DEMO:  start MediaPlayerClassic Home Cinema in privat Mode
@echo off
 verify other 2>NUL
 setlocal enableExtensions disableDelayedExpansion
 if errorLevel 1 goTo:NoExt                        
 if not exist "%Public%\Programme\MPC-HC\mpc-hc64.exe" call:CopyMPC 
 start "Video" "%Public%\Programme\MPC-HC\mpc-hc64.exe" "H:\xxx" /add "%~1" /randomize /volume 0 /play /viewpreset 1
 exit /b 0
          
:CopyMPC
 xcopy "C:\Program Files\MPC-HC" "%Public%\Programme\MPC-HC" /S /I
 if exist "%Public%\Programme\MPC-HC\mpc-hc64.ini" goTo:EoF
 pushD "%Public%\Programme\MPC-HC"
 echo:; MPC-HC>mpc-hc64.ini
 echo:[Settings]>mpc-hc64.ini
 echo:KeepHistory=0>mpc-hc64.ini
 popD
goTo:EoF
 
:NoExt
 :: Sound-Char: echo:STRG+G in CMD-Terminal to File ::
 echo:
 echo:  SORRY: Script don't supported by your System.
 echo:  CMD-Extensions not aviable.
 echo:
 pause
exit /b 0
```

**Comment by clsid2** [comment]
It gets created automatically when you enable the option in the player settings. Once the INI files exists, all changes you make to the options of that instance are written to the INI file. So you just need to configure it once.

There is no option for pauses between images. It will also not be added. MPC-HC is not an image viewer. Use Irfanview instead.
