### ISSUE TITLE
[Regression] 1.9.8 Internal Subtitle Renderer flickers on animated subtitles

### ISSUE THREAD

**Issue by Revenent** [clsid2/mpc-hc#730]
Video with animated subtitles has heavy flickering when using the internal subtitle renderer in 1.9.8, but didn't in 1.9.7.

AssFilter rendering does not show the issue.

Test video with issue: https://drive.google.com/file/d/1Jx2YXxjNf0E8DlLotNyR4ywdfVahm0f1/view?usp=sharing

MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.8 (6281da8a8)
    Compiler:           MSVC v19.26.28806
    Build date:         Oct 24 2020

LAV Filters:
    LAV Splitter:       0.74.1.75
    LAV Video:          0.74.1.75
    LAV Audio:          0.74.1.75
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 10.0 (build 19041)
    Version:            10.0 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    GPU1:               NVIDIA GeForce GTX 1660 SUPER (driver version: 27.21.14.5655)
    GPU2:               NVIDIA GeForce GTX 1660 SUPER (driver version: 27.21.14.5655)
    GPU3:               NVIDIA GeForce GTX 1660 SUPER (driver version: 27.21.14.5655)

**Comment by clsid2** [comment]
As a workaround you can set SubPicture buffer to 0 in the subtitle options.

**Comment by Revenent** [comment]
Thanks, that seems to have removed the flickering in 1.9.8 for the internal renderer.  Are there any side effects with having no buffers?

**Comment by clsid2** [comment]
No, it should work just fine.

**Comment by adipose** [comment]
@clsid2 , any idea why this bug is back?  I thought we fixed it before.

**Comment by clsid2** [comment]
I haven't looked at this yet. Maybe there is another similar edge case we didn't fix yet.

**Comment by AkazaAkarinn** [comment]
Also getting this bug with 1.9.8, but setting the SubPicture buffer to 0 didn't make it go away. I switched back to 1.9.7 for now.

**Comment by clsid2** [comment]
This is probably fixed in 1.9.9.45 development build.
