### ISSUE TITLE
Playback position is not working when clicking numerous times

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#731]
![problembug](https://user-images.githubusercontent.com/71337477/98469131-df098780-21ab-11eb-86ff-887a8a4b14a4.gif)
The above image (sorry for no cursor) is causing MPC-HC to not playback the position after clicking it numerous times. I have to wait a few seconds and then click it again. I cannot click on the slider position after clicking the slider to go to the position of the video/audio.
Can you please provide a reason the slider is not working at all?
Thanks

**Comment by ghost** [comment]
Oh and by the way, I almost forgot to add the info for MPC-HC


MPC-HC (Nightly, 64-bit)
------------------------

Build information:
    Version:            1.9.8.26 (df5df0168-dirty)
    Compiler:           MSVC v19.26.28806
    Build date:         Nov  7 2020

LAV Filters:
    LAV Splitter:       0.74.1.87
    LAV Video:          0.74.1.87
    LAV Audio:          0.74.1.87
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 10.0 (build 19041)
    Version:            10.0 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    GPU:                AMD Radeon HD 7570M (driver version: 8.17.10.1404)

**Comment by clsid2** [comment]
What kind of files give this problem?

**Comment by ghost** [comment]
All files are causing this

**Comment by clsid2** [comment]
Reset settings:
Options > Miscellaneous > Reset

I don't know what is wrong with your computer.

**Comment by ghost** [comment]
After reset, unfortunately, no go.

**Comment by ghost** [comment]
![stillnotwork](https://user-images.githubusercontent.com/71337477/98601182-ac938380-22ac-11eb-84f1-bf699ef549d5.gif)

**Comment by clsid2** [comment]
I see no video in your gif. Are these audio files?

Upload one of those files to http://www.sendspace.com
Then I can test with exact same file.

**Comment by ghost** [comment]
https://www.sendspace.com/file/mkyjv5

**Comment by clsid2** [comment]
Seek works normally here for that file.

Look at:
Menu > Play > Filters

It should look like this:
Default DirectSound Device
Audio Switcher
LAV Audio Decoder (internal)
LAV Splitter Source (internal)

**Comment by ghost** [comment]
Filters currently loaded:
  - Default DirectSound Device
  - Audio Switcher
  - LAV Audio Decoder (internal)
  - LAV Splitter Source (internal)
What do you want me to do with this?

**Comment by clsid2** [comment]
I can't help you. It works for everybody else, and I don't know why it does not work for you.

**Comment by ghost** [comment]
I tried my best. Sorry! 😞

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
