### ISSUE TITLE
presentation glitch and video stutter

### ISSUE THREAD

**Issue by mustafa811811** [clsid2/mpc-hc#733]
whenever a movie is displayed in fullscreen and the seekbar is shown or right click menu is clicked there is a video stutter that looks like a frame drop but recorded under presentation glitch 

so any solution to this presentation glitch ?! thanks in advance

1080ti gpu and i5 8400 cpu with 16 g.b ram
4k 24 hz
mpc 1.9.8 64 bit and madvr
lav filters set for direct3d 11 and bitstreaming
windows 10 64 bit

**Comment by clsid2** [comment]
That is fault of the graphics driver.

This may help a little bit:
NVIDIA control panel > Manage 3D settings > Global Settings > Power Management Mode > Select Adaptive

You can also try disabling "fullscreen optimizations" in the Windows compatibility settings of the player.

**Comment by mustafa811811** [comment]
thanks for the replay .. i tried both methods and they didn't work .. 1st i set the power mode in the Nvidia control panel to maximum performance then restart and 2ndly checked the disable fullscreen optimization on the exe itself but still it wouldn't be fixed 

but anyway i noticed that this doesn't occur when the windows hdr is ON so does this give you any clues ?!

this issue persisted despite upgrading the display drivers every 2 weeks
