### ISSUE TITLE
[ Question: ] "FFmpeg + DirectShow" in MPC-HC ?

### ISSUE THREAD

**Issue by JorgeR81** [clsid2/mpc-hc#734]
I have no experience on the technical/development side of video players, but based on my user experience, DirectShow seems to cause problems playing some old wmv files.
The amount of affected files is very small. They are old files, with poor encoding anyway. This is more curiosity on my part.

I checked the "based framework", of the players I have installed, and it seems to be correlated, with these wmv problems.
https://en.wikipedia.org/wiki/Comparison_of_video_player_software

- **Potplayer** ( _DirectShow_ ) - Can't play some wmv1 files. On some (old) wmv3 files, seek is quite slow.
- **MPC-HC** ( _FFmpeg + DirectShow_ ) - ( version 1.9.0 ) - Can't play some (the same ones) wmv1 files. On some (old) wmv3 files, seek is a bit slow. But still much better than Potplayer. 
- **MPV** ( _FFmpeg_ ) - Plays all wmv1 files. Fast seek on all wmv3 files (no noticeable delays).
- **VLC** ( _libVLC + FFmpeg_ ) - Plays all wmv1 files. Fast seek on all wmv3 files (no noticeable delays).

Could this be related, or is just coincidence?

**Comment by clsid2** [comment]
MPC-HC uses the WMV decoder from Microsoft by default. You can enable the FFmpeg based decoder and splitter in the internal filter settings.

You can often improve playback of bad files a bit by fixing them with AsfBin.

**Comment by JorgeR81** [comment]
Changing the splitter solved both problems! Thanks.
