### ISSUE TITLE
After opening videos brightness and hue keep reset to +1

### ISSUE THREAD

**Issue by Arczi008TV** [clsid2/mpc-hc#735]
![image](https://user-images.githubusercontent.com/49120706/98575376-6bee3700-22b9-11eb-8306-0cfe105ab2df.png)

If u set all to 0, quit program, then launch it again its still 0.
But after open video its +1, on every video launch.
Happens only when output is: EVR or VMR9.

**Oh, on VMR9 its not possible to set it below +1 when video is opened** 

![image](https://user-images.githubusercontent.com/49120706/98576410-c76cf480-22ba-11eb-82d2-d8a9d2515a96.png)

**Comment by clsid2** [comment]
That is a bug in your graphics driver. It is giving an invalid range of possible values. Normal range is between -100 and +100.

**Comment by Arczi008TV** [comment]
downloaded MPC-HC 1.9.8.26 nightly version,  seems to be fixed

**Comment by clsid2** [comment]
Nothing was changed in the player for the color controls. Whatever broke it on your system has been fixed.
