### ISSUE TITLE
Black  washed-out

### ISSUE THREAD

**Issue by falthu** [clsid2/mpc-hc#736]
Hello everyone, i am currently using latest build.
Every video black looks washed out.Current output set to EVR.
I don't know exact when this problem occurred.But yesterday i find out when i try splash player.
How to fix it?

**Comment by clsid2** [comment]
You need to look in your graphics driver settings.

**Comment by falthu** [comment]
i dig into my amd driver, can't find anything.

**Comment by clsid2** [comment]
Update your driver to the latest version. In the driver installer there is an option to do a "factory reset" (clean install).

**Comment by falthu** [comment]
Just did it. No improvement. Madvr works fine.
Note-I did add mpc on amd game list to disable freesync for mpc because of tearing issue few months ago.But i removed it,

**Comment by clsid2** [comment]
You can try this setting:
Menu > View > Renderer Settings > Output Range

Are you outputting to a TV? Those have a luminance range setting.

**Comment by clsid2** [comment]
If you use a HDMI connection to your screen, then look in the display settings in AMD driver. There is something called "Pixel Format" which should be set to "RGB 4:4:4 (Full Range)". Names may differ a bit. This setting controls what the GPU outputs to your screen.

**Comment by falthu** [comment]
I am using a monitor.Render output is already selected to 0-255.
I also changed the pixel format setting ycbcr to rgb full range before i reinstall amd driver.I thought i somehow changed it ycbcr.
But after i reinstall i am shocked to see amd default setting is ycbcr. Why is that?
Btw problem still remain.

**Comment by clsid2** [comment]
I don't have AMD, so I don't know. But even with ycbcr it should be possible to get proper black levels.

I suggest asking AMD for support.

I am closing this since it is not fault of the player.

**Comment by lifegpc** [comment]
Maybe AMD drivers' BUG. Because its BUG, I disable Hardware decoder.

**Comment by falthu** [comment]
> 
> 
> Maybe AMD drivers' BUG. Because its BUG, I disable Hardware decoder.

I select none on decoder to use. No difference at all.
