### ISSUE TITLE
Subtitles on music files?

### ISSUE THREAD

**Issue by hl24a3** [clsid2/mpc-hc#737]
I don't know if there's maybe some option hidden in massive settings already available but if not can it be done?

**Comment by FreddyZar** [comment]
Subtitles are for movies, [lyrics](https://en.wikipedia.org/wiki/LRC_(file_format)) are for audio files. Seems there is a bit of software called [minilyrics that says it works with mpc hc](https://www.crintsoft.com/minilyrics/faq/players)

**Comment by butterw** [comment]
No hidden option: your input needs to be video for you to be able to display subtitles.

There are workarounds to transform your audio to video:
You can mux to mp4 with ffmpeg with a single picture frame (no overhead) and it can then plays in mpc-hc/be with subtitles. 
`ffmpeg -loop 0 -i "photo.jpg" -i "audio.m4a" -c:a copy -c:v libx264 -crf 16 -tune stillimage -t 60 -movflags faststart "out.mp4"
`
where t is duration in seconds.

Alternatively, you could load your audio file via an avisynth script.

**Comment by hl24a3** [comment]
interesting solution I'll try that

> No hidden option: your input needs to be video for you to be able to display subtitles.
> 
> There are workarounds to transform your audio to video:
> You can mux to mp4 with ffmpeg with a single picture frame (no overhead) and it can then plays in mpc-hc/be with subtitles.
> `ffmpeg -loop 0 -i "photo.jpg" -i "audio.m4a" -c:a copy -c:v libx264 -crf 16 -tune stillimage -t 60 -movflags faststart "out.mp4" `
> where t is duration in seconds.
> 
> Alternatively, you could load your audio file via an avisynth script.

**Comment by clsid2** [comment]
Subtitles and OSD only work when a file has video.

**Comment by hl24a3** [comment]
> No hidden option: your input needs to be video for you to be able to display subtitles.
> 
> There are workarounds to transform your audio to video:
> You can mux to mp4 with ffmpeg with a single picture frame (no overhead) and it can then plays in mpc-hc/be with subtitles.
> `ffmpeg -loop 0 -i "photo.jpg" -i "audio.m4a" -c:a copy -c:v libx264 -crf 16 -tune stillimage -t 60 -movflags faststart "out.mp4" `
> where t is duration in seconds.
> 
> Alternatively, you could load your audio file via an avisynth script.

I tried your solution it works mega fast BUT it only seems to work on 60 seconds I tried different options removin and adding and tweaking but I just cant get it to work on longer audio files.

It's not for music files really I should have stated that more clearly in my title. I have lectures on audio and they are long like some hours. How do I get it to work with this lengths?

**Comment by hrxn** [comment]
`-t 666666`

**Comment by hl24a3** [comment]
this is one of the first things I did try, I did try an exact number of seconds then 99999, but for whatever reason file is corrupted it wont play

**Comment by butterw** [comment]
-loop 0 is a hack, it isn't well supported. 
-loop 1 will generate a valid mkv. It requires some encoding and has a small overhead (ex:  5kbps @720p)  
You'll need to specify a framerate (-r 25, less means a smaller file). It has to work for your subtitles and seek ok. 
if you have multiple audio files, you can reuse the encoded video. You could also use a solid color background generated by ffmpeg.

ffmpeg -loop 1 -i "photo.jpg" -i "audio.m4a" -i "subs.srt" -c:a copy -c:s copy -c:v libx264 -crf 16 -tune stillimage -r 25 -shortest "out.mkv"

**Comment by hl24a3** [comment]
> -loop 0 is a hack, it isn't well supported.
> -loop 1 will generate a valid mkv. It requires some encoding and has a small overhead (ex: 5kbps @720p)
> You'll need to specify a framerate (-r 25, less means a smaller file). It has to work for your subtitles and seek ok.
> if you have multiple audio files, you can reuse the encoded video. You could also use a solid color background generated by ffmpeg.
> 
> ffmpeg -loop 1 -i "photo.jpg" -i "audio.m4a" -i "subs.srt" -c:a copy -c:s copy -c:v libx264 -crf 16 -tune stillimage -r 25 -shortest "out.mkv"

Thank you, this will really be very handy for what I need it
