### ISSUE TITLE
Subtitles from Opensubtitles not found

### ISSUE THREAD

**Issue by KaligulaCZ** [clsid2/mpc-hc#740]
Hi, since few days ago my MPC-HC cannot find any open subtitles. I have tried different movies, but none have worked. Only other site that it loads is podnadpisi (polish subtitles site). Have the current version 1.9.8.26, please see this screenshot https://ctrlv.cz/16to.
Thanks in advance
KaligulaCZ

**Comment by lifegpc** [comment]
It is [opensubtitles.org](https://www.opensubtitles.org/) problem.
You can see database connection error.
