### ISSUE TITLE
Build failed after upgrade VS2019 to 16.8.0

### ISSUE THREAD

**Issue by ageback** [clsid2/mpc-hc#741]
`严重性	代码	说明	项目	文件	行	禁止显示状态

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	BaseClasses	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	SubPic	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	AsyncReader	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	Subtitles	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 ";" (编译源文件 ..\h\vd2\system\source\registrymemory.cpp)	system	D:\GitHub\mpc-hc\src\thirdparty\VirtualDub\h\vd2\system\vdalloc.h	156	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符" (编译源文件 source\error_win32.cpp)	system	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 ";" (编译源文件 source\fileasync.cpp)	system	D:\GitHub\mpc-hc\src\thirdparty\VirtualDub\h\vd2\system\vdalloc.h	156	

错误	C3861	“allocate”: 找不到标识符 (编译源文件 source\fileasync.cpp)	system	D:\GitHub\mpc-hc\src\thirdparty\VirtualDub\h\vd2\system\VDRingBuffer.h	113	

错误	C2760	语法错误: 意外标记 "标识符"，应为 ";" (编译源文件 source\filestream.cpp)	system	D:\GitHub\mpc-hc\src\thirdparty\VirtualDub\h\vd2\system\vdalloc.h	156	

错误	C2760	语法错误: 意外标记 "标识符"，应为 ";" (编译源文件 source\file.cpp)	system	D:\GitHub\mpc-hc\src\thirdparty\VirtualDub\h\vd2\system\vdalloc.h	156	

错误	C3861	“assign”: 找不到标识符 (编译源文件 source\profile.cpp)	system	D:\GitHub\mpc-hc\src\thirdparty\VirtualDub\h\vd2\system\vdstl.h	1178	

错误	C2760	语法错误: 意外标记 "标识符"，应为 ";" (编译源文件 source\vdalloc.cpp)	system	D:\GitHub\mpc-hc\src\thirdparty\VirtualDub\h\vd2\system\vdalloc.h	156	

错误	C2760	语法错误: 意外标记 "标识符"，应为 ";" (编译源文件 source\zip.cpp)	system	D:\GitHub\mpc-hc\src\thirdparty\VirtualDub\h\vd2\system\vdalloc.h	156	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	BaseSplitter	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	BaseMuxer	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	Filters (Libraries\Filters)	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C4596	“EmfToWmfBits”: 成员声明中的非法限定名	Filters (Libraries\Filters)	D:\Program Files (x86)\Windows Kits\8.1\Include\um\GdiplusHeaders.h	900	

错误	C4596	“GetTrimming”: 成员声明中的非法限定名	Filters (Libraries\Filters)	D:\Program Files (x86)\Windows Kits\8.1\Include\um\GdiplusStringFormat.h	225	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	unrar	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	DeCSS	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符" (编译源文件 OutputPin.cpp)	RARFileSource	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符" (编译源文件 Mediatype.cpp)	RARFileSource	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符" (编译源文件 File.cpp)	RARFileSource	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符" (编译源文件 RFS.cpp)	RARFileSource	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2446	“!=”: 没有从“long”到“HANDLE”的转换	RARFileSource	D:\GitHub\mpc-hc\src\thirdparty\RARFileSource\OutputPin.cpp	296	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符" (编译源文件 Utils.cpp)	RARFileSource	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符" (编译源文件 zita-resampler\libs\resampler-table.cc)	zita-resampler	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符" (编译源文件 zita-resampler\libs\resampler.cc)	zita-resampler	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符" (编译源文件 zita-resampler\libs\vresampler.cc)	zita-resampler	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	sanear	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	LCDUI	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	CmdUI	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C4596	“EmfToWmfBits”: 成员声明中的非法限定名	LCDUI	D:\Program Files (x86)\Windows Kits\8.1\Include\um\GdiplusHeaders.h	900	

错误	C4596	“GetTrimming”: 成员声明中的非法限定名	LCDUI	D:\Program Files (x86)\Windows Kits\8.1\Include\um\GdiplusStringFormat.h	225	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	sizecbar	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	ResizableLib	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	TreePropSheet	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	SyncClock	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	VideoRenderers	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	BaseSource	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	BufferFilter	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	AVI2AC3Filter	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	DeCSSFilter	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 ";" (编译源文件 source\blt_uberblit.cpp)	Kasumi	D:\GitHub\mpc-hc\src\thirdparty\VirtualDub\h\vd2\system\vdalloc.h	156	

错误	C2760	语法错误: 意外标记 "标识符"，应为 ";" (编译源文件 source\resample.cpp)	Kasumi	D:\GitHub\mpc-hc\src\thirdparty\VirtualDub\h\vd2\system\vdalloc.h	156	

错误	C2760	语法错误: 意外标记 "标识符"，应为 ";" (编译源文件 source\triblt.cpp)	Kasumi	D:\GitHub\mpc-hc\src\thirdparty\VirtualDub\h\vd2\system\vdalloc.h	156	

错误	C2760	语法错误: 意外标记 "标识符"，应为 ";" (编译源文件 source\uberblit_gen.cpp)	Kasumi	D:\GitHub\mpc-hc\src\thirdparty\VirtualDub\h\vd2\system\vdalloc.h	156	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	DSUtil	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	DSMSplitter	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	DSMMuxer	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	StreamDriveThru	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	MatroskaMuxer	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	CDDAReader	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	CDXAReader	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	VTSReader	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	SubtitleSource	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C2760	语法错误: 意外标记 "标识符"，应为 "类型说明符"	mpc-hc	D:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h	229	

错误	C4596	“EmfToWmfBits”: 成员声明中的非法限定名	mpc-hc	D:\Program Files (x86)\Windows Kits\8.1\Include\um\GdiplusHeaders.h	900	

错误	C4596	“GetTrimming”: 成员声明中的非法限定名	mpc-hc	D:\Program Files (x86)\Windows Kits\8.1\Include\um\GdiplusStringFormat.h	225	

错误	C2440	“默认参数”: 无法从“const wchar_t [1]”转换为“BSTR”	mpc-hc	D:\Program Files (x86)\Windows Kits\8.1\Include\um\MsHTML.h	16561	

错误	C2440	“默认参数”: 无法从“const wchar_t [1]”转换为“BSTR”	mpc-hc	D:\Program Files (x86)\Windows Kits\8.1\Include\um\MsHTML.h	19961	

错误	C2440	“默认参数”: 无法从“const wchar_t [1]”转换为“BSTR”	mpc-hc	D:\Program Files (x86)\Windows Kits\8.1\Include\um\MsHTML.h	24887	

错误	C2440	“默认参数”: 无法从“const wchar_t [1]”转换为“BSTR”	mpc-hc	D:\Program Files (x86)\Windows Kits\8.1\Include\um\MsHTML.h	24886	

错误	C2440	“默认参数”: 无法从“const wchar_t [1]”转换为“BSTR”	mpc-hc	D:\Program Files (x86)\Windows Kits\8.1\Include\um\MsHTML.h	24891	

错误	C2440	“默认参数”: 无法从“const wchar_t [1]”转换为“BSTR”	mpc-hc	D:\Program Files (x86)\Windows Kits\8.1\Include\um\MsHTML.h	24890	

错误	C2440	“默认参数”: 无法从“const wchar_t [1]”转换为“BSTR”	mpc-hc	D:\Program Files (x86)\Windows Kits\8.1\Include\um\MsHTML.h	32229	

错误	C2440	“默认参数”: 无法从“const wchar_t [1]”转换为“BSTR”	mpc-hc	D:\Program Files (x86)\Windows Kits\8.1\Include\um\MsHTML.h	32360	

错误	C2440	“默认参数”: 无法从“const wchar_t [1]”转换为“BSTR”	mpc-hc	D:\Program Files (x86)\Windows Kits\8.1\Include\um\MsHTML.h	50130	

`

**Comment by clsid2** [comment]
Bug in VS 16.8

https://developercommunity.visualstudio.com/content/problem/1250023/error-c2760-syntax-error-unexpected-token-identifi.html
