### ISSUE TITLE
Lateral black bars where they shouldn't be

### ISSUE THREAD

**Issue by i2324561w2** [clsid2/mpc-hc#743]
With https://www.mediafire.com/file/9r92x4exp4pq2v2/The_Job.mkv/file there are black bars on left and right which they weren't present on previous versions (I'm sure at least on V1.7.13); on VLC they are only on top and bottom; I have "touch from inside" set as I always had (and I don't think I changed anything).
I hope you can fix it, thank you.

**Comment by butterw** [comment]
File is 4/3, when you display it fullscreen on 16/9 it will have lateral black bars. This is true in every player including VLC (likely you have a crop 16/9 applied, if this not the case).
To crop the top/bottom and lateral black bars in mpc, Apply Pan&Scan widescreen zoom.

**Comment by clsid2** [comment]
Numpad9 to zoom
