### ISSUE TITLE
If you load subtitles and open another file and capture a screen, you'll see the previous sub

### ISSUE THREAD

**Issue by i2324561w2** [clsid2/mpc-hc#746]
Open a video, load on it some .ass file, without closing MPC-HC open another video (even if it's on another folder!), take a snapshot when you know the previous file had a sub on screen: the previous sub (although never shown during playback) is captured on the image.

**Comment by clsid2** [comment]
I am not able to reproduce this with current development build.

**Comment by i2324561w2** [comment]
Indeed, it was fixed, sorry, you can close this.
