### ISSUE TITLE
Shader hw linear sampling

### ISSUE THREAD

**Issue by butterw** [clsid2/mpc-hc#748]
mpc shaders: LumaSharpen.hlsl and Sharpen complex 2.hlsl are based on hardware linear sampling. Blur shaders typically also use this optimization. 
The feature is not working for me (texture fetches use nearest neighbor (Point) sampling instead).
Could you confirm whether the feature is supported by mpc-hc ?

The following dx9 shader outputs a 100% solid color orange screen if the feature isn't working:
https://github.com/butterw/bShaders/blob/master/test_linearSampling/bSmooth_test.hlsl

**Comment by butterw** [comment]
- now reported not working (with latest build) on intel hd4400 igpu, nvidia gtx1070, and amd 2400G apu
- was not working for me in v1.9.6
- glsl version of the code runs fine in mpv.

https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-writing-shaders-9#samplers-and-texture-objects
I've tried forcing the sampler state in the shader hlsl code (same result):
sampler s0 = sampler_state { // sampler s0: register(s0);
    MinFilter = Linear;
    MagFilter = Linear;
    MipFilter = Linear; //Point;
    AddressU = Clamp; //Wrap;
    AddressV = Clamp; //Wrap;
};

There must be something in the mpc-hc code forcing the sampler Filters to Point instead of Linear or maybe there is just a texture sampler state definition missing ?
causing nearest neighbor sampling:  tex2D(s0, tex)==tex2D(s0, tex+float2(0.499, 0.499)

**Comment by adipose** [comment]
Does it work in MPC-BE?  Shaders in MPC-VR are handed off to the renderer, so MPC-HC shouldn't really have any control over that.

**Comment by butterw** [comment]
Same result in mpc-be. 
 
In mpc-hc:
I've tested with EVR-CP and MPC-VR dx9 and with VMR9-Renderless.
I've also tested with v1.7.13.x86. 
 
In the case of EVR-CP, if linear sampling isn't explicitly disabled in the mpc-hc code, either it's an option that can be enabled or the directshow components used simply don't support it.

**Comment by butterw** [comment]
in DX9RenderingEngine.cpp, D3DSAMP_MINFILTER and D3DSAMP_MAGFILTER aren't set to D3DTEXF_LINEAR:
SetSamplerState(0, D3DSAMP_MINFILTER, D3DTEXF_POINT);

**Comment by clsid2** [comment]
What is the expected result when it is working (with mode=10)?
Only smooth surfaces are colored orange?

The change must be done in CDX9RenderingEngine::TextureCopy()

I have not tested if this has a negative effect on shader performance.
If this is ever supported by MPC-HC, then ideally it would need to be supported by madVR and MPCVR as well.

**Comment by butterw** [comment]
> What is the expected result when it is working (with mode=10)?
> Only smooth surfaces are colored orange?

Yes. 
for testing this, the shader should be used pre-resize. 
If it is used post-resize, there should be no resize (input resolution = output resolution).
