### ISSUE TITLE
Mouse Ctrl, Alt, Shift modifiers odd behavior

### ISSUE THREAD

**Issue by JorgeR81** [clsid2/mpc-hc#749]
The new mouse modifiers I've set up had an odd behavior. I didn't get it at first, but I think I understand now:

When you set up a new windowed mouse modifier it does not work at first.
It just works after you set up the fullscreen mouse modifier, for the same command.

But then, the fs modifier is also in control of the windowed mouse actions.
_Eg.: even if you set a different mouse modifier for windowed mode, mpc still uses the fs one, in both modes._

The only control the windowed modifiers gives you, is the ability to completely disable the windowed actions, by deleting the windowed modifier for that command.

(I just tested with mouse wheel + modifiers, mostly in "PnS Inc Width" and "PnS Dec Width" commands).

**Note:**
I've also just noticed that a windowed mouse modifier (_eg.: Alt + mouse wheel, for frame steps_) works just with the mouse wheel (but not Alt + mouse wheel), if there is no mouse fullscreen shortcut for that command.

**PS:**
To be fair, I don't know any other player that allows you to control hotkey commands based on window state (maybe just mpv, with a lua script).
If for some reason this can´t be fixed, I wouldn't mind using the same modifiers for both windowed states.
_Eg. the windowed modifiers could be automatically filled, after I set up the fs modifier (or vice versa)_

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/750
