### ISSUE TITLE
XySubFilter showing up as **unavailable** even though it's installed.

### ISSUE THREAD

**Issue by kingColloid** [clsid2/mpc-hc#751]
I successfully installed XySubFilter (ver. 3.1.0.752) through the .bat install file, but when I try to select XySubFilter under the subtitle renderer setting it's still marked as **unavailable**. I'm wondering what I can do to fix this issue.

(MPC-HC ver. 1.9.8)
![Screenshot 2020-11-19 155817](https://user-images.githubusercontent.com/63098503/99637608-10256a00-2a80-11eb-92f4-1742cff61ce9.png)

**Comment by clsid2** [comment]
You must right-click on the .bat and run as administrator.

**Comment by kingColloid** [comment]
I did run the .bat file as administrator and it's still marked unavailable.

**Comment by clsid2** [comment]
Open a command prompt and run the .bat from there. Then you can see what it does and if there are errors.

Also make sure that you are using 64-bit version if you use 64-bit player.

I recommend using the Internal Subtitle Renderer instead of XySubFilter.

**Comment by kingColloid** [comment]
There are no errors that I could identify, and I'm using the 64-bit version for the 64-bit player.

I guess there is no helping it right now. If you recommend the Internal Subtitle Renderer above the XySubFilter then that's great. I assumed that XySubFilter is better than the Internal Subtitle Renderer, but I guess that's not necessarily the case. Thanks for the help!
