### ISSUE TITLE
CoverArtSizeLimit doesn't seem to work

### ISSUE THREAD

**Issue by lkintact** [clsid2/mpc-hc#752]
The `CoverArtSizeLimit` setting (View > Options > Advanced) doesn't seem to work.
For example, with the setting's default value, `600`, MPC-HC still loads and displays the cover image of ~~[this mp3 file](https://github.com/lkintact/FileHosting/blob/main/birds.mp3)~~, while the image is 1200x1200px.

MPC-HC version: 1.9.8,
OS: Windows 10 Home 1803.

**Comment by clsid2** [comment]
It means the maximum size of the displayed image. So with your example it will be displayed as 600x600px.

**Comment by lkintact** [comment]
Thanks for explaining this. Maybe to reduce ambiguity the tooltip description of the setting should be renamed to "Maximum _display_ size (NxNpx) of a cover-art loaded in the audio only mode."?
