### ISSUE TITLE
Debug Shaders 

### ISSUE THREAD

**Issue by butterw** [clsid2/mpc-hc#753]
The drop-down selector in Debug Shaders fails to display the name of the Shader if it is long.
![image](https://raw.githubusercontent.com/butterw/bShaders/master/img/mpc-hc_Debug_Shaders.png)

Workarounds are maximizing Debug_Shaders or installing mpc-hc in a location with a shorter path (ex: B:\mpc).

Proposed solution: only display folder/filename in the drop-down selector. 
Maybe add a tooltip with the full pathname. The full pathname always appears in the compilation output anyway.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/888
