### ISSUE TITLE
Recent files list: all elements are equal if you strip url parameters

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#756]
If the url parameters are stripped from recent files list, how you distinguish one url from another?
PS: Actually in the recent files list I think it could be better to display the "title" (if available) instead of the url.

See: 
![recent-files-list](https://user-images.githubusercontent.com/15793015/99888950-06069580-2c51-11eb-8b77-8a72147a4bc1.png)

**Comment by clsid2** [comment]
Yes, it does not look good in case of youtube links. Maybe stripping parameters should be done only for very long URLs.

**Comment by lifegpc** [comment]
Maybe add video title to recently list is better.

**Comment by clsid2** [comment]
Yes, for URLs that would better. You can make a patch for that if you have time.

**Comment by lifegpc** [comment]
Have a look in source code, It can only store file name in recently file list because it use ```CRecentFileAndURLList``` which is a subclass of ```CRecentFileList```.

**Comment by lifegpc** [comment]
I try to make a new class to support more info. Such as title and audio file location.

**Comment by lifegpc** [comment]
I think this is better.
![image](https://user-images.githubusercontent.com/41434272/99896726-4526fc00-2cce-11eb-8478-11fed37b52e7.png)

**Comment by lifegpc** [comment]
[test build](https://mega.nz/file/B1RBzIbS#7MAWaA494hC_vqYoP3MCI5J2uonmJe4y_CVS3Io0NT0)

**Comment by lifegpc** [comment]
@clsid2 
![image](https://user-images.githubusercontent.com/41434272/99905013-18dca100-2d09-11eb-8424-afc009725401.png)
Do u think 150 char limit is suitable?

**Comment by lifegpc** [comment]
If ok, I will submit it to the patch.

**Comment by clsid2** [comment]
I was thinking of a function like this:
ShortenURL(CString url, int targetLength)

If the input url is longer than targetLength, then strip of individual parameters until it is short enough. By default maybe 100 is good max length?

For example an URL with multiple parameters:
https://www.youtube.com/watch?v=OKW018foQmg&t=100&lastparam=justanexample

Here we could search from right-to-left for "&" to remove the last parameter. If there are no "&" found and it is still too long, then strip everything after the "?". For youtube URLs, this method should give useful and unique string, something like
https://www.youtube.com/watch?v=OKW018foQmg

And when displaying the URL behind a title (like in recent file list), then maybe it would be good idea to only show the domain name (URLGetHostName):
"Some Funny Cat Video (youtube.com)"

**Comment by lifegpc** [comment]
OK. I see.

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/99907332-39abf300-2d17-11eb-8151-30941fdf0f1d.png)
Like this?

**Comment by lifegpc** [comment]
new [test build](https://mega.nz/file/NsJm2bwa#mxNCxCkP6hTp6Phaka9BHkN5YJPi9LR77W4GzzmF5Q8)

**Comment by ale5000-git** [comment]
@lifegpc: Hi, is it possible to have a new test build?
I would like to test with other streamings and the one linked don't include the latest changes.

**Comment by clsid2** [comment]
Looks good.

In case of a very long title, I think it is best to omit the file/url behind it, and shorten it by showing the leftmost 150 chars (or 147 + "..."). Files are shortened by removing a piece from the middle, which obviously would be weird for a title.

**Comment by ale5000-git** [comment]
On streamings of vvvvid (handled by youtube-dl) the title include only episode name but the name of the anime is in the url, like this:
`https://www.vvvvid.it/show/NUMBER/ANIME-NAME/NUMBER/NUMBER/EPISODE-NAME`

Isn't possible to keep some parts of the url? The title in this case is short.

**Comment by clsid2** [comment]
It is difficult to show all useful information while also keeping the total width reasonable. How many characters is the full URL for videos on that site?

Maybe we should add advanced option: UseTitleInRecentFileList

UseTitleInRecentFileList enabled and has title:
use title (cut to max 100 chars) + hostname / filename without path
example: "This is a title of a cool video from the Internet (www.youtube.com)"
example: "This is title of a cool local video (localvideo.mp4)"

UseTitleInRecentFileList disabled or no title:
use URL (shortened to 150) or full filename (shortened to 150)

**Comment by ale5000-git** [comment]
The full url is 80 characters but the title of the anime is inside the first 48 characters of the url.
Instead the real title (which is the one of the episode) is 20 characters.

Isn't possible to have it like this?
`This is a title of a cool video from the Internet (www.youtube.com/watch?v=sggdfgdfgdfgdf)`
Title shortened to 100 + url shortened to 50 (with protocol stripped)?

**PS:** Also strip `www.` may help.

**Comment by lifegpc** [comment]
I think read epid and id from youtube-dl output will be a better way.
Such as ```S01E02.Video title (host name, video id)```.

**Comment by lifegpc** [comment]
I will do it when I have spare time.

**Comment by lifegpc** [comment]
> use URL (shortened to 150) or full filename (shortened to 150)

full filename cut on right side?

**Comment by clsid2** [comment]
Filename cut in middle like it is now, with part of the front and part of the back. URL should be cut from the back.

Using 100 for title and 50 for URL like ale500 suggested would be ok.

**Comment by lifegpc** [comment]
> Using 100 for title and 50 for URL like ale500 suggested would be ok.

For all urls? I think use more info youtube-dl provide will be better. For normal url, we can shorten URL as ale500 suggested. For ydl_source URL, we can simply display label name and add more info to label name when parsing youtube-dl's results.
Such as ```S01E02.(if exist)Video title (hostname, video id)```.

**Comment by lifegpc** [comment]
One more question, if after shorten URL, it is still too long, what should do for that URL. Should strip more parts?

**Comment by clsid2** [comment]
Don't do extra youtube parsing yet. Let first improve things for URLs in general.

If shortened URL is too long, then use hostname.

**Comment by lifegpc** [comment]
Okay.

**Comment by ale5000-git** [comment]
@lifegpc: My example is an url not by youtube but still handled by youtube-dl.
Like this:
`https://www.vvvvid.it/show/NUMBER/ANIME-NAME/NUMBER/NUMBER/EPISODE-NAME`

I could give the link privately if needed.

**Comment by lifegpc** [comment]
> @lifegpc: My example is an url not by youtube but still handled by youtube-dl.
> Like this:
> `https://www.vvvvid.it/show/NUMBER/ANIME-NAME/NUMBER/NUMBER/EPISODE-NAME`
> 
> I could give the link privately if needed.

I can build a test build to you. Hold on.

**Comment by lifegpc** [comment]
> Don't do extra youtube parsing yet. Let first improve things for URLs in general.

done.

**Comment by lifegpc** [comment]
@ale5000-git new [test build](https://mega.nz/file/g55lwYRT#AskvdIqudDx6uph-JGo0LGnO7tZMwTnW5yD3PdmYBTY).

**Comment by ale5000-git** [comment]
It seems to work perfectly:
![Immagine](https://user-images.githubusercontent.com/15793015/100001175-0626a280-2dc3-11eb-9574-f1f08576107b.png)

**Comment by lifegpc** [comment]
[new test build](https://mega.nz/file/goAVlSoK#J57WPG9p4aQ22jlpzXrKNLUnpfuY2mhiI4kpvRwzofs)

**Comment by lifegpc** [comment]
[This build](https://mega.nz/file/F9QhkSxY#jVGrFhqjYED9utPqKOW7bw18RZ5X_JEmSdOA9Rf-liE) fix crash when opening DVD (Because of my fault).

**Comment by lifegpc** [comment]
Now I parse more info from youtube-dl.
Format for videos: ```S<season_number>E<episode_number>. <Season name> - <title> (<shortend url>)```
if season name not exist, I will try use Series name to replace it.
![image](https://user-images.githubusercontent.com/41434272/100453482-f1654a00-30f5-11eb-863a-cf95ee439c58.png)
![image](https://user-images.githubusercontent.com/41434272/100453576-22457f00-30f6-11eb-911b-a98555dc773b.png)

**Comment by lifegpc** [comment]
@ale5000-git Can you test [this build](https://mega.nz/file/Yk5w3DKa#w4ui5I5jYLg8oCwUfG3CBLj_Gy9Q8nieQ9gibpYtgYQ) with ```vvvvid.it```?

**Comment by ale5000-git** [comment]
This is how it looks:
![screenshot-1](https://user-images.githubusercontent.com/15793015/100524851-d3fab380-31bb-11eb-99d8-86f0681c20e6.png)
![screenshot-2](https://user-images.githubusercontent.com/15793015/100524854-df4ddf00-31bb-11eb-82de-ce030fc020b3.png)

**Comment by ale5000-git** [comment]
@lifegpc: If you write me at ale5000 under gmail I can give more detailed info.

**Comment by ale5000-git** [comment]
@lifegpc: There are some things I don't understand.

1) If there is already S01E01 (in the title of MPC-HC app) why writing also Season 1? It is a repetition.
2) Why there isn't episode number in the recent file list?
3) Why the url in the title of MPC-HC app is different from the url in the recent file list (this one is correct)?

**PS:** Beside that it is working perfectly, thanks :)

See screenshot: 
![streaming-info](https://user-images.githubusercontent.com/15793015/100920244-1fbe9d00-34db-11eb-87bd-30e140ad406b.png)

**Comment by lifegpc** [comment]
1. I use season name, it may useful. Maybe I should also add series name.  
2.I will look at it.  
3.Now I read webpage_url for each video in playlist item, but it seems not good for this website.

**Comment by ale5000-git** [comment]
1) But S01 or Season 1 is the same or do you mean that it can contains also other informations?

**Comment by lifegpc** [comment]
Yea. Such as bangumi on bilibili.com, it has season name and series name. The season name is not something like ```Season 1```. 

> ![image](https://user-images.githubusercontent.com/41434272/100453482-f1654a00-30f5-11eb-863a-cf95ee439c58.png)
> ![image](https://user-images.githubusercontent.com/41434272/100453576-22457f00-30f6-11eb-911b-a98555dc773b.png)

You can see here. It is ```天使降临到我身边```.

**Comment by ale5000-git** [comment]
Isn't possible to just skip it if it start with "Season " to avoid duplicate info?

**Comment by lifegpc** [comment]
Yea. No problem. I will do it if I have spare time.

**Comment by ale5000-git** [comment]
Thanks, it isn't urgent.

**Comment by lifegpc** [comment]
@ale5000-git 
[test build](https://mega.nz/file/9t4XFYRB#EBKADNLNNnPGagszn0V6kEenAwklE-7mkoPaB9RdjN0)
1. Now if video has season number info and the season name is starts with season, season name will be ignored. I also add series name before season name.
2. Now if a link have multiply entries(means a playlist), I will display ```<series name> - <season name>```.
If it just have one entry, I will display it same as video title.
3. If a link have just one entry, I will not read webpage_url now.

**Comment by ale5000-git** [comment]
@lifegpc: I confirm that it works correctly in all cases.
