### ISSUE TITLE
Error while trying to open YouTube url

### ISSUE THREAD

**Issue by g-2-s** [clsid2/mpc-hc#761]
Need help: I get this error when I try to open YT links. youtube-dl.exe is updated to the latest version (v2020.11.21.1 as of writing) and is in right directory I think (C:\Program Files\MPC-HC). I recently reinstalled Windows 7 and it's the first time I'm having this problem, it worked flawlessly 2 days ago on my previous OS install.

![001](https://user-images.githubusercontent.com/54694327/99919072-08c9bf00-2d13-11eb-92f0-1827e66c9a8a.png)

EDIT: video and audio files work as intended if that's of any help.

**Comment by clsid2** [comment]
It works fine here. It is unlikely a bug in the player. And I can do nothing for you without the URL that fails.

**Comment by g-2-s** [comment]
> Windows exe requires Microsoft Visual C++ 2010 Redistributable Package (x86) and does not require Python that is already embedded into the binary.

I'm so dumb it's almost amazing.

**Comment by clsid2** [comment]
I will see if a better error can be shown when YDL fails to run.
