### ISSUE TITLE
Youtube videos won't play

### ISSUE THREAD

**Issue by ze0ss** [clsid2/mpc-hc#762]
Youtube videos won't play after pasting their URLs in the "Open File/URL" option in Play.
It throws an error, saying "Unable to extract JS player.....update youtube-dl...."

OS: Windows 10 x64 
MPC-HC version: 1.9.8.33

Screenshot of the exception dialogue:
![Screenshot 2020-11-23 103316](https://user-images.githubusercontent.com/56572179/99930738-2d0bb700-2d78-11eb-969e-440c9bcfd74c.png)

**Comment by lifegpc** [comment]
This is not related to MPC-HC. Please update your youtube-dl. If still not work , open an issue on [ytdl-org/youtube-dl](https://github.com/ytdl-org/youtube-dl).

**Comment by ze0ss** [comment]
I don't have a youtube-dl in the installation directory, and just 2 or 3 days ago, I was able to play youtube videos without any problems, I have no idea what happened now.

FYI I somehow fixed this issue, I downloaded the latest youtube-dl from their github and pasted it in MPC-HC directory, and now it plays all videos, just to mention, there was no youtube-dl exe in the directory before I manually put it there today.

Also, a question, what actually happens when I play a youtube videos using MPC-HC? does the player download the video somewhere on the Hard drive temporarily/permanently, or it just streams? 
Like, is anything actually downloaded on the drive somewhere on the PC? 
If yes, please give a directory location of the video(s) files.

**Comment by lifegpc** [comment]
> I don't have a youtube-dl in the installation directory

![image](https://user-images.githubusercontent.com/41434272/99953306-0f604100-2dbc-11eb-90f6-ae3025f4347f.png)
This command line may help you. It will display all youtube-dl.exe in current directory and the directories specifed in ```PATH```.

> does the player download the video somewhere on the Hard drive temporarily/permanently, or it just streams?

Just stream. If you want to save to files, use File -> Save a copy. You can specify download parameters by ```YDLCommandLine``` in advanced settings page.

**Comment by lifegpc** [comment]
For example, if you want to save all subtitles, set ```YDLCommandLine``` to ```--all-subs```.
If you want to add metadata to video file, add ``` --add-metadata``` to ```YDLCommandLine```.

**Comment by ze0ss** [comment]
>Just stream. If you want to save to files, use File -> Save a copy. You can specify download parameters by YDLCommandLine in advanced settings page.

Oh ok, thanks.
So no video, even temporarily, on the hard drive at all?
How does it exactly stream if absolutely nothing is downloaded? Just curious

**Comment by clsid2** [comment]
Streaming means it downloads segments into a temporary memory buffer.

**Comment by ze0ss** [comment]
Can you elaborate?
