### ISSUE TITLE
Reorder "Play With MPC-HC" on directory context menu above "Add to MPC-HC Playlist"

### ISSUE THREAD

**Issue by Prologh** [clsid2/mpc-hc#763]
Hi!
I'm using MPC-HC for a quite a few years and I have a fairly simple request. Have you noticed that actions for MPC-HC have different order when triggered from file or a directory? It would be nice to have them presented in the same, consistent order. Otherwise, I've noticed I sometimes tend to get confused and I press the wrong one. See screenshots:

File context menu:

![image](https://user-images.githubusercontent.com/19705370/100020351-fd909500-2ddf-11eb-9d77-48db847d570e.png)

And directory context menu:

![image](https://user-images.githubusercontent.com/19705370/100020369-02eddf80-2de0-11eb-9549-5187258fcf8f.png)

**Comment by clsid2** [comment]
Not possible. Explorer controls that order.

**Comment by Prologh** [comment]
Okay, thanks for letting me know. I dig into that.

**Comment by Prologh** [comment]
For anyone who will wonder in here in search for answer. I did manage to reorder those context menu entries with simple registry key rename.

1. Open registry editor and go to `HKEY_CLASSES_ROOT\Directory\shell`
2. You should see following keys `mplayerc64.enqueue` and `mplayerc64.play`.
3. Rename `mplayerc64.play` to something that will put it before the `mplayerc64.enqueue`. I added `a` before `play`:

![image](https://user-images.githubusercontent.com/19705370/100027568-54e93200-2ded-11eb-9fc2-39d6119430de.png)

Original answer that helped me with that:

https://superuser.com/questions/1423831/rearrange-the-order-of-programs-in-the-windows-open-with-context-menu
