### ISSUE TITLE
White Tooltip on dark skin subtitle download

### ISSUE THREAD

**Issue by FreddyZar** [clsid2/mpc-hc#764]
When using the dark skin and hovering over a subtitle it comes up with this white bar
![image](https://user-images.githubusercontent.com/32035834/100306952-421d5b80-2fad-11eb-98de-55e6ca5990b0.png)
Sometimes there is a log black bar and a shorter white bar
![image](https://user-images.githubusercontent.com/32035834/100307284-1c448680-2fae-11eb-97fa-ffcf6c2c34d4.png)
Seems this has to do with when there is multiple filenames associated with the same subtitle

On the normal skin it just comes up with a normal sized tooltip
![image](https://user-images.githubusercontent.com/32035834/100306981-56f9ef00-2fad-11eb-905f-ceb91221532a.png)
that expands into a list
![image](https://user-images.githubusercontent.com/32035834/100307452-8ceba300-2fae-11eb-856f-bfe3da16fcf9.png)

**Comment by adipose** [comment]
There's a second bug, here.  In classic mode (you can see it up there), it shows two kind of tooltips:

![image](https://user-images.githubusercontent.com/3324395/101103369-0cb0d900-357e-11eb-92b3-54b6786d130f.png)

One is multi-line and the other is single line.

**Comment by adipose** [comment]
I couldn't reproduce this one in the dark theme.  It always worked for me when I forced a multi-line tooltip, but if you upload the video in question I can test it out with real data.

https://github.com/clsid2/mpc-hc/pull/785

Here's a fix for the two types of tooltips.  The built-in tooltip for the window was being given data based on the List tooltip rules.  But only the list tooltip was being change to multi-line, creating two kinds of tooltips with different formats.  I introduced some code to fix that.

I also update the code for multi-line to work the way other list tooltips do.  Possibly, this might fix the issue you are seeing, as the themed tooltip might not get the text wrapping length the way it was being done.

**Comment by adipose** [comment]
After review I don't think the second part should have changed anything, unless a separate tooltip was requesting data.  So, what's most odd is not perhaps the two tooltips but the data being presented.  The code tries to join the titles with "\n" as a separator.  When I force such a text to show, it shows multi-line for me, but your screenshot is different.

Let's see how this build works for you.

https://mega.nz/file/IcARjIAS#_htqFos2ihpfOchTZ1HDYp_bUbX4luGcMDJy4cHTPqI

**Comment by FreddyZar** [comment]
Thanks @adipose, works perfectly now even with the multiline ones 👍
