### ISSUE TITLE
[Bug] Shaders aren't working with MPC video renderer

### ISSUE THREAD

**Issue by Droyk** [clsid2/mpc-hc#765]
they're working with all the other renders I've tried MADVR, EVR, HVR, VMR 
but with MPC they don't seem to show any effect at all the player is activating them but I can't see any effect of enabling them!
the previous versions also had the same issue! 

P.S. I have tried every shader that comes with the default player.

**Comment by clsid2** [comment]
MPCVR only supports post-resize shaders.

**Comment by Droyk** [comment]
Sorry for the late reply I'm only using post resize filters! 
![image](https://user-images.githubusercontent.com/15848350/100489320-90f7fc00-3139-11eb-84c9-d6bb21483ffd.png)

**Comment by clsid2** [comment]
Then I don't know what is wrong. It is not a bug in the player.

**Comment by Droyk** [comment]
How do we know that? are you telling me it's working fine for you? because I've tested this on 4 machines it's giving me the same result!

**Comment by clsid2** [comment]
Yes, it works fine for me and others.

Try installing MPC-HC + MPCVR using K-Lite Codec Pack (Standard). Then you have a guaranteed proper install.

**Comment by Droyk** [comment]
That fixed it!
