### ISSUE TITLE
The minimum Playback Rate should be be decreased

### ISSUE THREAD

**Issue by lkintact** [clsid2/mpc-hc#771]
Currently the minimum Playback Rate one can get by repeatedly pressing the "Decrease Rate" keyboard shortcut (View > Options > Keys) is `0.20x` when "Speed step" (View > Options > Playback) is set to `10%`. It's `0.15x` for `5%`, and `0.13x` for `1%` respectively.

This isn't slow enough for some videos, for example high frame rate car crash tests.

Perhaps the value should be decreased to `0.10x` for `10%` and `0.05x` for `5%`. Not sure about `1%`.

MPC-HC version: 1.9.8,
OS: Windows 10 Home 1803.

**Comment by clsid2** [comment]
There is frame stepping ability for inspecting video frame-by-frame.

**Comment by lkintact** [comment]
Yes, thanks, I'm aware of the ability, it's just watching and occasionally pausing is easier than repeatedly pressing "Frame-step".

**Comment by clsid2** [comment]
Minimum has been changed to 0.05x
Works with all speed step values.
