### ISSUE TITLE
Compilation doc not up2date?!

### ISSUE THREAD

**Issue by CBuntrock** [clsid2/mpc-hc#772]
Hi all,

I'd like to change some minor things, however I fail with compilation. Most libs compile fine but mpc-hc binary fails. If useful could also paste errors here, but maybe there is something obvious I could have forgotten? I really followed instructions as exact as possible. I used Release-Lite build config.

Would if be possible to verify if instructions are still correct? Being able to build is key for me in order to continue.

Thanks!
Best,
Chris

**Comment by clsid2** [comment]
Copy the errors.

It might be because of bugs in Visual Studio 2019 16.8
I am still using 16.6 myself, since newer versions aren't very stable.

**Comment by clsid2** [comment]
Has your problem been solved?

**Comment by CBuntrock** [comment]
Hi. Sorry for delay. I will install 16.6 first and try once again and report here.

UPDATE: I still get errors. You can see them below:
![image](https://user-images.githubusercontent.com/4046654/101364957-7513f900-38a3-11eb-9e24-44064246aafa.png)

**Comment by adipose** [comment]
I am using 16.7.6 without issue at the moment.

**Comment by adipose** [comment]
Looks like issues with yasm potentially.

**Comment by clsid2** [comment]
You need yasm.exe and put it somewhere in %PATH% (like c:\windows)

And version_rev.h issue may be because of Git installation.
git.exe must also be available in %PATH%

**Comment by v0lt** [comment]
I added YASM path to user and system PATH but that doesn't help.
I am trying to build the Lite version.

YASM is recalled if I call it from an arbitrary folder using cmd or powershell.

**Comment by v0lt** [comment]
I removed all checks at the beginning of the YASM.bat file and YASM started working!

**Comment by v0lt** [comment]
But update_version.bat still doesn't work.

**Comment by clsid2** [comment]
What error do you get with update_version.bat?

**Comment by adipose** [comment]
If building lite, doesn't full have to be built at least once?

**Comment by clsid2** [comment]
No, that should not be needed.

**Comment by v0lt** [comment]
`2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: The command "..\update_version.bat --quiet" exited with code 1.`

If I run "update_version.bat" from the command line then
`Not all build dependencies were found.`

I am building the Lite version.

**Comment by adipose** [comment]
Getting this on latest sources.

```
9>C:\dev\mpc-hc\src\yasm.targets(45,5): error MSB3721: The command "yasm.exe -X vc -f win64 -g cv8 -D HAVE_CPUNOP=0 -D WIN32=1 -D ARCH_X86_64=1 -D HAVE_ALIGNED_STACK=1 -D _CRT_SECURE_NO_DEPRECATE -D _CRT_NONSTDC_NO_DEPRECATE -D _CRT_SECURE_NO_WARNINGS -I "libass\libass" -o "C:\dev\mpc-hc\bin\obj\Debug_x64\libass\be_blur.obj" "C:\dev\mpc-hc\src\thirdparty\libass\libass\libass\x86\be_blur.asm"" exited with code 1.
```

**Comment by adipose** [comment]
Updated the props file to point to my yasm.exe, working now.

**Comment by clsid2** [comment]
Yes, or put yasm.exe somewhere in %PATH%.

I will check update script again later.

**Comment by clsid2** [comment]
I have added a fallback so build should now work even when Git is missing. It should now also work if MSYS is not installed.

**Comment by adipose** [comment]
I'm not sure why it had problems with yasm.  My yasm was previously in the msys folder (`c:\msys64\usr\bin\yasm.exe`).  Yet, my yasm.bat did not do anything interesting...except set the common path.

Perhaps the issue here is the common path no longer applies to yasm calls, requiring a global path which I previously didn't have.

**Comment by clsid2** [comment]
I removed the dependency on MSYS for calling yasm, but that means it need to be in %PATH%.

**Comment by v0lt** [comment]
Thank you.
Batch files now work correctly.

But I still have one last mistake.
```
Error	LNK1241	resource file libiconv.lib(libiconv.res) already specified	libfontconfig	...\mpc-hc\src\thirdparty\fontconfig\freetype2.lib(ftver.res)
Error	LNK1181	cannot open input file 'libfontconfig.lib'	libass	...\mpc-hc\src\thirdparty\libass\LINK
Error	LNK1104	cannot open file 'libass.lib'	mpc-hc	...\mpc-hc\src\mpc-hc\LINK
```
branch = develop, Debub Lite x64
Visual Studio 2017 15.9.30, Windows SDK 10.0.17763.0 (I changed in platform.props).

**Comment by clsid2** [comment]
Libass is not yet actively used. So as a workaround you can remove linking to libass.lib in MPC-HC project file.

I looks like libfontconfig needs a fix.

**Comment by clsid2** [comment]
Try again now. I made some changes.

Also test with USE_LIBASS=1 in mpc-hc_config.h

**Comment by v0lt** [comment]
```
#define USE_LIBASS 0

Error	LNK1241	resource file libiconv.lib(libiconv.res) already specified	libfontconfig	...\mpc-hc\src\thirdparty\fontconfig\freetype2.lib(ftver.res)
Error	LNK1181	cannot open input file 'libfontconfig.lib'	libass	...\mpc-hc\src\thirdparty\libass\LINK
```
```
#define USE_LIBASS 1

Error	LNK1241	resource file libiconv.lib(libiconv.res) already specified	libfontconfig	...\mpc-hc\src\thirdparty\fontconfig\freetype2.lib(ftver.res)
Error	LNK1181	cannot open input file 'libfontconfig.lib'	libass	...\mpc-hc\src\thirdparty\libass\LINK
Error	LNK1104	cannot open file 'libass.lib'	mpc-hc	...\mpc-hc\src\mpc-hc\LINK
```

**Comment by clsid2** [comment]
I have made another change that might have fixed this.
