### ISSUE TITLE
Wrong path in properties and missing title for a radio

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#774]
Open this in MPC-HC: http://www.memoryradio.de:5000/

It display errors but after the errors it works fine.

1) But if you go on File -> Properties -> Clip on "Location" you see "http:/"
2) It display title in recent files but not in the title of MPC-HC application.

**Comment by lifegpc** [comment]
The error because ```youtube-dl``` do not support this link. You can simply disable UseYDL in settings.
1. I will look at it.
2. Make sure enable ```Replace file name with title``` in settings.

**Comment by lifegpc** [comment]
In current code, ```www.memoryradio.de:5000``` was treated as file name, and treat something before it as location.
![image](https://user-images.githubusercontent.com/41434272/101026872-60d5b080-35b2-11eb-8e42-c818e5640f38.png)

**Comment by lifegpc** [comment]
@clsid2 Any ideas to deal with this situation?

**Comment by ale5000-git** [comment]
My opinion is that if the entire url is only a domain without path it should be displayed as is.

**Comment by lifegpc** [comment]
So file name: ```www.memoryradio.de:5000```
localtion: ```http://www.memoryradio.de:5000``` ?

**Comment by ale5000-git** [comment]
This seems fine for me but it is only my opinion.

**Comment by clsid2** [comment]
File -> Properties -> Clip -> "Location"

In case of an URL, it should just show the whole URL. Shortened if it is too long to display nicely.

**Comment by ale5000-git** [comment]
In case of youtube-dl stream in that place it will display the final url that can be used in a download manager, so personally I would prefer if it isn't shortened (currently it can be scrolled, selected and copied).

**Comment by clsid2** [comment]
Good point. Show entire URL.

I will take a look at the error message issue later. It should hide errors in case of a generic extractor for unsupported sites.

**Comment by lifegpc** [comment]
I think add a ```Use YDL``` checkbox to opendlg is a good idea.

**Comment by lifegpc** [comment]
```UrlDecodeWithUTF8``` now have a small bug, ```%3F``` will be decoded to ```?```, but it should be keeped. If it be decoded, the URL will change becuase ```?``` have special meaning.

**Comment by lifegpc** [comment]
It seems ```UrlUnescape``` do not support that. So I just remove UrlDecodeWithUTF8 for location now.

**Comment by ale5000-git** [comment]
It has low importance but probably these URLs:
`file:///c:/Users/IAM/Videos/My-video.mp4`
should be normalized to:
`c:\Users\IAM\Videos\My-video.mp4`

**Comment by lifegpc** [comment]
Maybe I can have a look tomarrow, it's time to sleep for me. 
[Test build](https://mega.nz/file/QkhClSrI#2h1KhiwpHbiegYw_5ytl3PdyMS7oWL7P0GAO3MyygXY)

**Comment by ale5000-git** [comment]
Now there is no longer the error and the location now works correctly but the title is wrong.

It currently do this:
1) You open the radio, the title of MPC-HC window only inlcude the url and not the title.
2) It get added to the recent file list with the title of the currently playing song.
3) Wait that the song change.
4) Reopen it from the recent file list, now in the title of MPC-HC window it appear the url with the title of the song that played the first time so it is now wrong.

In synthesis the recent file list don't support titles that change over the time.

**Comment by lifegpc** [comment]
That's because that title is read from file. When you open file in recent file list, the title will be send to the playlist, so it's have title(label). In case of URL, we will use label from playlist item whatever that settings enabled or disabled.

**Comment by lifegpc** [comment]
Now title in title bar and in playlist will update immediately. Title in recent file list will update when closing media.

**Comment by lifegpc** [comment]
> Now title in title bar and in playlist will update immediately. Title in recent file list will update when closing media.

[test build](https://mega.nz/file/95RkTbRa#DA7MDvRftNZlmAMHegAOEo15Ew-55cPUuPN0qODgjCk)

**Comment by ale5000-git** [comment]
Thanks, it improved but the part of "closing media" is unclear.

If I close media using "Close" in the file menu it works but if (without closing) I click on the same element in the recent file list I expect it to close the currently playing one and open it again but it isn't like this since the recent file list the entry isn't updated.

**Comment by lifegpc** [comment]
That's because you not close and open file.

**Comment by ale5000-git** [comment]
But I see "Opening..." so if it open again it should have closed it before otherwise that would be 2 video playing or I'm wrong?

**Comment by clsid2** [comment]
Any issues left with latest build?

**Comment by ale5000-git** [comment]
@clsid2: Unfortunately the "Unsupported URL" message appears again after updating to K-Lite Codec Pack 15.9.2, the other problems are fixed.

**Comment by clsid2** [comment]
That's weird. It should now skip the error message when it contains the string "ERROR: Unsupported URL". Is the message different in your case?

**Comment by ale5000-git** [comment]
It is the same: ![mpc-error](https://user-images.githubusercontent.com/15793015/101325908-d10f5b00-386c-11eb-91b8-0a0638fb07ee.png)

**Comment by ale5000-git** [comment]
In this test build of lifegpc it works fine: 1.9.8.58 (c6a0b9087) (patch18) (develop@ 779e6fe)
but in the official 1.9.8.65 it is broken.

**Comment by lifegpc** [comment]
hmm. That's because a very small bug in code. 
![image](https://user-images.githubusercontent.com/41434272/101343816-85d26800-38bf-11eb-8e30-31db3512b3d9.png)
Should be >= 0.
