### ISSUE TITLE
Minor issue with YouTube playlists

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#777]
When opening a YouTube playlists it should display the title of the playlist instead of the title of the first video in the recent file list.

Example: `https://www.youtube.com/watch?v=CcGktzTvTqU&list=RDgLQuK9gApxA&index=2`

**Comment by lifegpc** [comment]
It may need read more info from youtube-dl. I will look at it when I have spare time.

**Comment by lifegpc** [comment]
Now it will display ```uploader - playlist title``` first. [test build](https://mega.nz/file/wohEBLgY#NJHVklQ5tDpCRhSFNTJfIOEElriIz-wALcdeGZPuHGo)

**Comment by ale5000-git** [comment]
It works fine, thanks.

There is just a minor thing, in the uploader text on MPC-HC I get "by" (in English) instead on Youtube website I get "di" (in Italian).
Is it always in English or it is in English because I have the MPC-HC interface in English?

**Comment by lifegpc** [comment]
That's youtube-dl's behavior. I look its source code, it hardcode en in its source code. 
Use cookies may change this behavior.

**Comment by ale5000-git** [comment]
Is it possible to avoid the `&` stripping from urls in recent file list?
I'm not sure but probably `&` need to be doubled to tell to don't use it as menu shortcut.

**Edit:** Same problem with local videos that have `&` in filenames.

**Comment by clsid2** [comment]
Currently only the playlist itself is added to the recent files. I think it is probably desirable to also add the individual playlist entries to the recent files when they get played.

**Comment by lifegpc** [comment]
~~It seems open from playlist may not use ```void CMainFrame::OpenFile(OpenFileData* pOFD)```.~~ I find why.

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/101227170-ebf99800-36d1-11eb-88e4-162e3890356c.png)
Just modify it to true.

**Comment by clsid2** [comment]
> 
> 
> Is it possible to avoid the `&` stripping from urls in recent file list?
> I'm not sure but probably `&` need to be doubled to tell to don't use it as menu shortcut.
> 
> **Edit:** Same problem with local videos that have `&` in filenames.

This is not fixed yet.

**Comment by lifegpc** [comment]
I am not sure what should I do to fix it. (My poor English 😂

**Comment by lifegpc** [comment]
> I am not sure what should I do to fix it. (My poor English 😂

I think I know what you say. I should double & because & have special meanings in Menu.
