### ISSUE TITLE
WEBVTT file may have lines which have same content.

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#782]
The webvtt file: [学猫叫(cover)【花丸はれる／花寄女子寮】 .en.vtt.zip](https://github.com/clsid2/mpc-hc/files/5643419/cover.en.vtt.zip) 
![image](https://user-images.githubusercontent.com/41434272/101177844-3869b700-3683-11eb-9ebe-972c2188898b.png)
![image](https://user-images.githubusercontent.com/41434272/101177861-3ef82e80-3683-11eb-90fe-321e76dc36f6.png)

**Comment by clsid2** [comment]
It displays what the subtitle file instructs. I don't think it is our job to fix duplicates in a subtitle file.

How does Youtube handle this one?

**Comment by lifegpc** [comment]
Chrome handle it correctly.
![image](https://user-images.githubusercontent.com/41434272/101224189-f19eb000-36c8-11eb-9dac-b983c7b37466.png)

**Comment by lifegpc** [comment]
I find that's because they have same position style.
![image](https://user-images.githubusercontent.com/41434272/101224317-37f40f00-36c9-11eb-862c-7a746ae27c94.png)

**Comment by lifegpc** [comment]
Maybe we should add [these styles](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#Cue_settings) support

**Comment by clsid2** [comment]
Position style is identical too, so it must be displaying them on top of each other. Still seems like a broken subtitle to me.

**Comment by lifegpc** [comment]
I check other format subtitle on YouTube, format do not contain position style also have 2 same lines, I argee that it is a broken subtitle.
