### ISSUE TITLE
[BUG] Some streamings aren't seekable

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#783]
Some streamings of pornhub are not seekable and also they doesn't even start from the start but from the middle of the video.

If I take the final streaming url taken from MPC-HC properties and open it in VLC it is seekable so the problem isn't youtube-dl but the streaming handler of MPC-HC.
If you need the url for testing contact me privately.

**Comment by clsid2** [comment]
That bug in FFmpeg handling of HLS playlist. Not a bug in the player.
