### ISSUE TITLE
Some items in Audio Track SubMenu need to be shortened.

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#789]
I think shorten these URL is better. For Youtube-DL source audio track, maybe display audio info is better.
![image](https://user-images.githubusercontent.com/41434272/101320721-2f553180-389f-11eb-9741-e3bc3362e206.png)

**Comment by clsid2** [comment]
Yes, should be shortened. If better audio info is available that could be used as well.

**Comment by lifegpc** [comment]
If it return something like ```?.......................(very long parameters)```, shortened URL may be nothing=-=. What should I do in that case?

**Comment by ale5000-git** [comment]
What about display only domain (like youtube.com) and `id` parameter if exist (on YouYube exist)?
And output something like this: `youtube.com?id=fsdsdgsdg (0x704f 48000Hz stereo 3072kbps)`

It seems better in my opinion.

**Comment by clsid2** [comment]
How can it be empty? There should be something before the question mark.

**Comment by lifegpc** [comment]
Hmm. Such as /live/?.........

**Comment by lifegpc** [comment]
It strips the path, and the name will be ?........

**Comment by raliqala** [comment]
it should be able to  wrap the url and make the box a square

**Comment by adipose** [comment]
If a url is being displayed, it seems "wrong" to have the domain and path eliminated in favor of the query string.  At best, the query string contains some useful info but not the filename, and at worst it is a bunch of encoded data that is useless to the mpc-hc user.

If it's under 50 characters, or some such limit, maybe leave it alone.  Otherwise, you could apply the following rules:

http://domain.com/file.m4a?a=1&b=2  ==> http://domain.com/file.m4a  (remove the query string to make room)
http://domain.com/folder/?a=1&b=2   ==> http://domain.com/folder (remove the query string to make room)
http://domain.com/a/b/c/d/e/f/g/file.m4a ==> http://domain.com/../file.m4a (remove the url path to make room)
http://domain.com/a/b/c/d/e/f/g/file.m4a?a=1&b=2 ==> http://domain.com/../file.m4a (remove both to make room)

The example in the screenshot is interesting because it has a url encoded into the query string.  Maybe if the first item in the query string is a URL, we can use that instead of the "file.m4a" bit.

**Comment by lifegpc** [comment]
> The example in the screenshot is interesting because it has a url encoded into the query string. Maybe if the first item in the query string is a URL, we can use that instead of the "file.m4a" bit.

That is a reverse proxy. Because MPC-HC not support specify HTTP headers (in this case, is referer) when streaming.
The backend:
![image](https://user-images.githubusercontent.com/41434272/103719898-0e4e4080-5005-11eb-9f84-3bee2af8ff61.png)

**Comment by Alp1821** [comment]
Not only that, for some links it's showing wrong bitrate. For some links right.

![Screenshot (287)](https://user-images.githubusercontent.com/98865389/155930003-5b6b898b-c625-46b6-aa7e-e83830d2cc9c.png)

A 1080p video can not be 16kb/s

**Comment by adipose** [comment]
Can you provide a working example for this issue?

**Comment by bibsp** [comment]
It happens with any YouTube video. One thing I noticed, Lav splitter shows correct audio info. But audio track selection menu shows this kind of long url.

**Comment by xLn2** [comment]
> not related to this issue
> Yt-dlp is stalling while calling it when settings were default (YDLVideoFormat=0). Changing it to 1 solved stalling on my end.
> Some youtube videos have lag and frame sync problem at first 1% duration.

Audio track SubMenu gets expected track name when audio has valid bitrate value (0>)

If audio has 0 kbps there is long submenu track name which is mentioned.
Properties page shows: `Audio: AAC 44100Hz stereo 0kbps [A: ISO Media file produced by Google Inc. [eng] (aac lc, 44100 Hz, stereo, 0 kb/s)]`

**Comment by adipose** [comment]
OK, well here's something I worked up:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/ba0201f4-1efe-4cf7-b8a0-05b04708e800)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2458

**Comment by clsid2** [comment]
The URL is being shortened twice now.

Maybe just do it once and turn it into:
`domain.com - mediatype details`

**Comment by adipose** [comment]
> The URL is being shortened twice now.

Where is the other shorten happening?

**Comment by adipose** [comment]
I think I found it.

**Comment by adipose** [comment]
Well, I didn't find it yet.  `ShortenURL` exists but doesn't appear to be processing the the audio stream url.  Yet somehow when pulling it from the streaminfo, it only has the "videoplayback" section of the url.

**Comment by clsid2** [comment]
Probably `PathUtils::StripPathOrUrl()`

**Comment by bibsp** [comment]
> it only has the "videoplayback" section of the url.

Please remove it. It looks bad. 🥺

**Comment by adipose** [comment]
Here's the weird part.  LAVSplitter returns the following infos:

V: ISO Media file produced by Google Inc. (h264 high L4.0, yuv420p, 1920x1080, 0 kb/s)
A: ISO Media file produced by Google Inc. [eng] (aac lc, 44100 Hz, stereo, 0 kb/s)

The first is the same that shows in the Video Track menu.

![image](https://github.com/clsid2/mpc-hc/assets/3324395/e4bafac2-617c-4136-962b-97910276f74a)

But when building the audio menus, it's getting it from `CStreamSwitcherFilter::Info` which is returning the truncated path.

**Comment by adipose** [comment]
> Probably `PathUtils::StripPathOrUrl()`

Doesn't seem to be.

**Comment by adipose** [comment]
This is where it's being trimmed.

![image](https://github.com/clsid2/mpc-hc/assets/3324395/b6c150b7-c652-4c7b-a0d6-afe5c15a2939)

**Comment by bibsp** [comment]
It's not about 0 kb/s audio. See this is not 0 kb/s.

https://github.com/clsid2/mpc-hc/assets/98865389/172fda9a-12d7-4c2d-982b-dc11e6a70995

**Comment by adipose** [comment]
Well, the video stream mpc-hc shows also claims to be 0kbps, probably some error.

**Comment by adipose** [comment]
New PR to grab the Info (kbps is updated by the time of this call, btw) and prefer to filename with youtube urls.

https://github.com/clsid2/mpc-hc/pull/2464

![image](https://github.com/clsid2/mpc-hc/assets/3324395/0b7f1ccf-25a2-4cfb-bf10-6566a432e721)

![image](https://github.com/clsid2/mpc-hc/assets/3324395/4b10b2ca-d77f-4e38-96ad-df1a19e776df)

**Comment by adipose** [comment]
@clsid2 Can be closed?

**Comment by clsid2** [comment]
Problem may also occur for other streaming sites. Not just youtube.

Maybe if source is an URL and longer than X amount of characters, then just replace it with stream description, and use generic fallback "Online Audio Stream".

**Comment by adipose** [comment]
> Problem may also occur for other streaming sites. Not just youtube.
> 
> Maybe if source is an URL and longer than X amount of characters, then just replace it with stream description, and use generic fallback "Online Audio Stream".

https://github.com/clsid2/mpc-hc/pull/2477

**Comment by adipose** [comment]
I think this can be closed.
