### ISSUE TITLE
m3u files with youtube links do not work

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#791]
I am preparing a playlist in m3u files which contains `youtube`, `music.youtube` and `drive.google.com` links. 
The first problem I have counter with m3u files with `youtube.com` is file path seems wrong or it cannot trigger youtube dl. (Links directly works with _mpc-hc > open file/url_)

It is my example m3u file: [nekobin.com/nigucuwigo](https://nekobin.com/nigucuwigo)

1. `youtube.com` in m3u

`C:\Users\x\Desktop\https://www.youtube.com/watch?v=Qc0cyeCqeag` (m3u file located on desktop)
![mpchc 1](https://user-images.githubusercontent.com/3073922/101340542-f31ad480-3890-11eb-9d19-04da275785b9.jpg)

2. `music.youtube` in m3u files also does not work (which is normally works with _mpc-hc > open file/url_) 

> Note: Loading playlist make player freeze a bit due to calling youtube dl etc. 

3. `drive.google.com` in normally (_mpc-hc > open file/url_) and in m3u files does not work 
I am normal user so please do not judge me. I do not know about abilities of youtube dl or youtube dlc.  I have tested with `Tartube v2.3.008`. I just put it because of it seems also use youtube dl and can help.

![image](https://user-images.githubusercontent.com/3073922/101342307-6b829500-3893-11eb-88d3-fdf916dedc56.png)
![mpch3](https://user-images.githubusercontent.com/3073922/101342740-0bd8b980-3894-11eb-9731-1b04ae20d789.jpg)

4. Possible playlist bug
![mpchc2I](https://user-images.githubusercontent.com/3073922/101343577-40994080-3895-11eb-9ed7-27e661490f7d.jpg)

I just wanted if youtube dl is capable to process `drive.google.com` I will be glad to see implemented.❤ Thanks all, you put a lot of effort for this program🧠

**Comment by lifegpc** [comment]
1 - 2.That's because when opening file in playlist, MPC-HC will open it directly and do not send it to Youtube-dl.

**Comment by lifegpc** [comment]
3. Are you sure you use correct cookies, you should use [configure file](https://github.com/ytdl-org/youtube-dl#configuration) to let MPC-HC use correct cookies. (PS. I will add a addvanced settings for add user command line for process URL.?
I am not sure after configure it, it can works.... :(

**Comment by lifegpc** [comment]
for 1 -2 , you can make a ```.mpcpl``` file, and use follow formats:
```
MPCPLAYLIST
1,type,0
1,filename,https://www.youtube.com/watch?v=egefZBhBHgs
1,ydlSourceURL,https://www.youtube.com/watch?v=egefZBhBHgs
2,type,0
2,filename,another URI can send to Youtube-dl or any can not open's URL/file
2,ydlSourceURL,another URI can send to Youtube-dl
```

**Comment by xLn2** [comment]
> 1. Are you sure you use correct cookies, you should use [configure file](https://github.com/ytdl-org/youtube-dl#configuration) to let MPC-HC use correct cookies. (PS. I will add a addvanced settings for add user command line for process URL.?
>    I am not sure after configure it, it can works.... :(

I had no information about youtube dl cookies before you mention. It is a bit complicated for me sorry for that. Can you provide me example cookies file and basic instruction. Or I will wait you till add advanced settings to command line. Hope it works.



> for 1 -2 , you can make a `.mpcpl` file, and use follow formats:
> 
> ```
> MPCPLAYLIST
> 1,type,0
> 1,filename,https://www.youtube.com/watch?v=egefZBhBHgs
> 1,ydlSourceURL,https://www.youtube.com/watch?v=egefZBhBHgs
> 2,type,0
> 2,filename,another URI can send to Youtube-dl
> 2,ydlSourceURL,another URI can send to Youtube-dl
> ```

thank you for finding alternative way but I tested it on `MPC-BE` and `Vlc media` and bullet 1 is just works fine. I thought why it should not work on `mpc-hc`.

**Comment by lifegpc** [comment]
> I had no information about youtube dl cookies before you mention. It is a bit complicated for me sorry for that. Can you provide me example cookies file and basic instruction. Or I will wait you till add advanced settings to command line. Hope it works.

You can create a configure file and input ```--cookies your cookies file location``` to it. It will let youtube-dl use this cookies file by default.

**Comment by lifegpc** [comment]
> I thought why it should not work on mpc-hc.

MPC-HC use another key to store youtube-dl source url. Only when you use ctrl + E to reload video(this works for all build) or video url are failed to open(in the latest source code, but not included in latest test build), it will recall youtube-dl to get a new video url.

**Comment by clsid2** [comment]
When parsing the M3U file it could use the YDL Whitelist function to check if it is an URL that needs to be processed.

**Comment by clsid2** [comment]
https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-pass-cookies-to-youtube-dl

**Comment by lifegpc** [comment]
Process it when parsing M3U file or when open it in playlist? If process it when open it in playlist, what should we check it's need process?

**Comment by clsid2** [comment]
If `IsOnYDLWhitelist(url)` then set ydlSourceURL value.
The IsOnYDLWhitelist function currently only has small list of sites. But that can be expanded later with more popular sites.

It should then get processed once the entry is the playlist is opened.

**Comment by lifegpc** [comment]
So what should I add something to filename list? If we don't add something to filename list, once you right click that item, you will receive an error message.

**Comment by lifegpc** [comment]
I try to add a playlist item that only contains ydlSourceUrl by parsing new playlist file, and get error message when I right click that item. So I made a patch to check when parsing playlist file.

**Comment by lifegpc** [comment]
> So what should I add something to filename list? If we don't add something to filename list, once you right click that item, you will receive an error message.

![image](https://user-images.githubusercontent.com/41434272/101353678-f0d76b00-38ce-11eb-8300-658bec405ab4.png)
The error message. So we need add something to filename list or do some check on other side.

**Comment by clsid2** [comment]
Use same url as the filename?

**Comment by lifegpc** [comment]
Hmm. Sounds like good, if the first filename is equal to ydlSourceURL, then process that URL.

**Comment by xLn2** [comment]
I do not want to bother you again but there is some possible bug or mpc-hc structure restriction. 
When I tried to open M3U file on mpc-hc it freeze around 30 seconds and pick random  a video from youtube playlist and add it on playlist (other songs are ignored)

> #EXTM3U
> https://music.youtube.com/playlist?list=RDCLAK5uy_lm8KUIhp8pW4nMyNBWLpTq1UsKdXgfQo4
> #EXTINF:-1,Tom&Jerry
> https://drive.google.com/file/d/1xVApB6x5RHaA2mRW-gmqV797d4kBWo-2/view

I saved the playlist file to see what is happening.
![image](https://user-images.githubusercontent.com/3073922/101681385-1ef5b000-3a73-11eb-8bd7-5c7d7df00fa8.png)

* saved playlist as .mpcpl looks like:
> ﻿MPCPLAYLIST
> 1,type,0
> 1,label,Nelly - Dilemma (Official Music Video) ft. Kelly Rowland (youtube.com/watch?v=8WYHDfJDPDc)
> 1,filename,https://r5---sn-nv47ln7z.googlevideo.com/videoplayback?expire=1607563085&ei=7CLRX4bZOpSCgQeis7KICQ&ip=(I shortened it)
> 1,filename,https://r5---sn-nv47ln7z.googlevideo.com/videoplayback?expire=1607563085&ei=7CLRX4bZOpSCgQeis7KICQ&ip=(I shortened it)
> 1,ydlSourceURL,https://www.youtube.com/watch?v=8WYHDfJDPDc
> 2,type,0
> 2,label,Tom&Jerry
> 2,filename,https://drive.google.com/file/d/1xVApB6x5RHaA2mRW-gmqV797d4kBWo-2/view
> 2,ydlSourceURL,https://music.youtube.com/playlist?list=RDCLAK5uy_lm8KUIhp8pW4nMyNBWLpTq1UsKdXgfQo4

* saved playlist as M3U looks like:
> https://r6---sn-nv47lnl6.googlevideo.com/videoplayback?expire=1607564260&ei=hCfRX6XyD9fTgQfPlKzYBw&ip=(I shortened it)
> https://drive.google.com/file/d/1xVApB6x5RHaA2mRW-gmqV797d4kBWo-2/view

* When I tried to open the M3U file on MPV player playlist parsing automatically as
![image](https://user-images.githubusercontent.com/3073922/101680895-67609e00-3a72-11eb-8ac5-aae490e69c9e.png)


And google drive links are still not working for Mpc-hc for now I hope it will work after developer version. Thank you again.

**Comment by lifegpc** [comment]
Now we use a white list to check it is a ydl source url or not. The white list only have few entries now.

**Comment by clsid2** [comment]
I can confirm that only the first entry from the youtube playlist in your example gets added. That is a bug.

We can add "drive.google.com/file" to the whitelist.

But you are kind of abusing the M3U functionality. It should normally only contain direct links to actual media streams.

**Comment by lifegpc** [comment]
I prefer use regex in white list.

**Comment by xLn2** [comment]
I have looked mpv source code about youtube hook and found interesting. These can be evaluated by experienced eyes.

[ytdl_hook.lua](https://nekobin.com/birusilola)
```
local function parse_yt_playlist(url, json)
    -- return 0-based index to use with --playlist-start

    if not json.extractor or json.extractor ~= "youtube:playlist" then
        return nil
    end

    local query = url:match("%?.+")
    if not query then return nil end

    local args = {}
    for arg, param in query:gmatch("(%a+)=([^&?]+)") do
        if arg and param then
            args[arg] = param
        end
    end
```
```
if (not o.try_ytdl_first) then
    mp.add_hook("on_load", 10, function ()
        msg.verbose('ytdl:// hook')
        local url = mp.get_property("stream-open-filename", "")
        if not (url:find("ytdl://") == 1) then
            msg.verbose('not a ytdl:// url')
            return
        end
        run_ytdl_hook(url)
    end)
end
```
