### ISSUE TITLE
some strings shown on windows local language

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#796]
I am currently using `MPC-HC (Nightly, 64-bit)  Version: 1.9.8.65 (ee997206c).`  I accidentally discovered there is some strings only shown on windows locale language. You can address at `View > Pan & Scan`  3 strings above from `Edit`

In English settings there is some locale (turkish) strings
![image](https://user-images.githubusercontent.com/3073922/101388136-9808d200-38d0-11eb-8adc-de57617b914e.png)
Also German settings there is same.
![image](https://user-images.githubusercontent.com/3073922/101388219-b242b000-38d0-11eb-8f01-7bf2b2a25e32.png)

**Comment by clsid2** [comment]
Those entries are names of presets that are created on first run of the player. It uses whatever language is the default at that time.

I don't see any easy way to fix this.

You can change the names yourself by clicking on the "Edit..." option in the menu below them.
