### ISSUE TITLE
Wrong colors in hevc

### ISSUE THREAD

**Issue by qo4on** [clsid2/mpc-hc#797]
I opened this [plain `rgb(26,26,26)` hevc file](https://dl.dropboxusercontent.com/s/gyfqf2l93yecwdq/26_26_26.mp4) in Premiere Pro and a color picker showed exactly `(26,26,26)`. But `mpc-hc` renders different `25 - 26` colors at different points.
![image](https://user-images.githubusercontent.com/35609308/101396851-b630fb00-38ed-11eb-8f12-8f9b5174f5df.png)

**Comment by clsid2** [comment]
That is probably due to dithering being applied by the video renderer.

**Comment by qo4on** [comment]
Can I fix this and get true colors?

**Comment by clsid2** [comment]
Dithering improves the visual quality of the video, so disabling it would be unwise.
https://en.wikipedia.org/wiki/Dither

Look in the settings of the video renderer for option disable it.

**Comment by qo4on** [comment]
> Dithering improves the visual quality of the video, so disabling it would be unwise.

It depends on the purpose. Dithering also increases the amount of noise. It would be wise to keep the option for disabling it.
I've found 2 types of dithering, but I don't see the off button:

![image](https://user-images.githubusercontent.com/35609308/101481471-0e600f80-3977-11eb-812b-a00b674850f5.png)

I disabled dithering in madvr.

**Comment by clsid2** [comment]
LAV Video Decoder does not offer option to disable dithering. But it only dithers if it performs colorspace conversion. With madVR that should not happen. You are currently using EVR-CP as renderer in your screenshot, not madVR.

**Comment by qo4on** [comment]
I changed renderer to madVR and turned off dithering there. Now `mpc-hc` renders right colors. But for some reason it shows `inactive` decoder and I'm not sure how to fix this.

![image](https://user-images.githubusercontent.com/35609308/101503070-89372380-3993-11eb-9187-92c620171767.png)

**Comment by clsid2** [comment]
Inactive means exactly that. You are opening settings through Start menu, which is an inactive instance of the filter.

You can open settings of the active instance through the player menu:
Menu > Play > Filters

Dithering does not give visible noise. It helps improve quality. But it is your choice.

**Comment by qo4on** [comment]
> You can open settings of the active instance through the player menu:
> Menu > Play > Filters

Thank you for clarification. Why does `mpc-hc` show `Active Hardware Accelerator: <none>`? I see 31% GPU load in the `Task Manager` when video is playing.

![image](https://user-images.githubusercontent.com/35609308/101509452-986d9f80-399a-11eb-9732-eb11e6a0f8dd.png)

> Dithering does not give visible noise. It helps improve quality. But it is your choice.

You are right. But it's not good for video creation when you hope to see the colors you set. That's why `Premiere Pro` does not apply dithering.

**Comment by clsid2** [comment]
Your video uses HEVC 4:4:4 RExt profile. Hardware acceleration is not possible for that profile. You need to use Main profile and 4:2:0.
