### ISSUE TITLE
vivo.sx links fail to open with youtube-dl present

### ISSUE THREAD

**Issue by neodyne** [clsid2/mpc-hc#798]
Using MPC-HC 64-bit, 1.9.8 (6281da8a8), on Windows 10 x64.
Example link: https://vivo.sx/cf2137f496.
Site is [supported](https://ytdl-org.github.io/youtube-dl/supportedsites.html), file opens fine in mpv with youtube-dl, can be downloaded as well.

Looking at youtube-dl side of things, the output of `youtube-dl -F`,

`[Vivo] cf2137f496: Downloading webpage`
`WARNING: unable to extract filesize; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`
`[info] Available formats for cf2137f496:`
`format code  extension  resolution note`
`0 mp4  unknown `

the warning should not be the cause; it's [non-fatal](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/shared.py#L117), caused by [regex](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/shared.py#L116) that needs updating; even after the (trivial) fix for the regex the video does not play, & only in mpc-hc ("Calling youtube-dl" => "Unable to render file").
However, the resolution for the automatic format 0 is listed as unknown (video url is base64 decoded from html source, not really a way to know), which could be the problem if the mpc-hc ydl hook somehow depends on an explicitly listed resolution.

**Comment by lifegpc** [comment]
Have a quickly look, this website's video url seems needs valid cookies, but MPC-HC don't support it.

**Comment by lifegpc** [comment]
> Have a quickly look, this website's video url seems needs valid cookies, but MPC-HC don't support it.

Hmm. Seems not cookies problem.

**Comment by neodyne** [comment]
Hi, thanks for looking into this.

Is it really a cookies problem? youtube-dl -J dumps the json for the webpage, with an extracted directlink to video. This link can be played in mpc-hc without problems.

**Comment by lifegpc** [comment]
I see. It's bug in filterVideo.

**Comment by lifegpc** [comment]
It do not contain vcodec and acodec. I will try find a better way to parse it.

**Comment by clsid2** [comment]
Maybe if both vcodec and acodec are unknown, set to value "unknown" for both. Then in stream comparison code, let any known format be better than "unknown". Then this stream should get used, but only if nothing better (with more info) is available.

**Comment by clsid2** [comment]
I can make patch for this later today.

**Comment by lifegpc** [comment]
> I can make patch for this later today.

I already made it.

**Comment by lifegpc** [comment]
I should read youtube-dl [common comments](https://github.com/ytdl-org/youtube-dl/blob/e7eff914cd3ffd8bc2975100036fdac9829dd16d/youtube_dl/extractor/common.py#L88), it contains all vaild keys.

**Comment by clsid2** [comment]
The "format" value could be useful in this case.

**Comment by lifegpc** [comment]
add a new key or treated it as vcodec

**Comment by clsid2** [comment]
Store it as additional value in the struct.
