### ISSUE TITLE
Rogue connection attempts!

### ISSUE THREAD

**Issue by THEtomaso** [clsid2/mpc-hc#8]
Yes, I'm sure that you recognized the description, clsid2.
It's a duplicate of my report here:
`https://trac.mpc-hc.org/ticket/6067/`
I noticed that you elevated that ticket to "high priority" some time ago.

Any chance of you including a fix for this particular issue in your next release?
Preferably, MPC-HC shouldn't try to connect to the internet when no subtitle providers are selected.
And of course, no providers should be selected by default, thereby preventing any accidental connection attempts!

Thanks a lot for continuing the work on MPC-HC! :)

**Comment by clsid2** [comment]
Please don't duplicate things. It only makes me less motivated. Adjusting priority was part of a huge cleanup process on Trac. It doesn't imply that it will get addressed soon. It is just a minor annoyance.

**Comment by THEtomaso** [comment]
Thanks for having fixed this in v1.9.0! :+1:
