### ISSUE TITLE
Rotate not coherent back and forth

### ISSUE THREAD

**Issue by cdlvcdlv** [clsid2/mpc-hc#801]
The PnS Rotate X+, Y+ and Z+ work as expected (a small increment in the desired angle) but the corresponding minus commands reset the angle to 0, 90 or 180 (depending on the axis and the previous angle). This way, if you rotate a bit more than desired, you can't undo the movement. Or, like me, trying to show my kid how they did Fred Astaire's "dance on the wall and ceiling" from "Royal Wedding", you can't dynamically rotate in both directions when needed..

I clearly remembered this worked years ago, so I've traced it back and it seems to have been broken since 1.7.10.290 version from 2017-01-23 (1.7.10.276 from 2016-12-26 works just fine, as every previous version). You can check this on "MPC-HC Old versions" archived in:
https://www.videohelp.com/software/Media-Player-Classic-Home-Cinema/old-versions

**Comment by clsid2** [comment]
This is intentional and it is not going to be changed back.

99% of people are only interested in 90 degree rotation steps. Previously that could not be done easily.

**Comment by cdlvcdlv** [comment]
> This is intentional and it is not going to be changed back.
> 99% of people are only interested in 90 degree rotation steps. Previously that could not be done easily.

I see. It's not a bug, it's a feature. But why must be done at the cost of another one? They are not incompatible: a key for +, a key for -, a key for 90 step. There are more keys than enough.

It's the fault of the 1% (if I may believe your statistics) that 99% of people are only interested in 90 rotation steps?

And, from my point of view, is the other way round: getting 0-90-180 degrees is fair easy using + and - rotations, but right now it's impossible to go back to the rotation you need or follow a picture like I needed.

If this is not a bug report it can be for sure a feature request: a key for rotation decrements AND a key for 90x steps.

**Comment by clsid2** [comment]
Sorry, not going to happen.

**Comment by cdlvcdlv** [comment]
And you wouldn't let a merge to add the feature, I guess.

**Comment by clsid2** [comment]
Depends on the quality of the patch.
