### ISSUE TITLE
[Feature Request] Can we have a fresh install profile to be imported?

### ISSUE THREAD

**Issue by K0media** [clsid2/mpc-hc#802]
I know Codec Tweaking Tool already provides some back up options, but what about a settings export/import option in the end of the installer? "`Save and export installation settings to file`".

And when importing back in it would skip the installation settings that have to be next.

It would save a lot of time instead of having to set it up all over again?

Or can you skip all the installation options/settings and import custom settings from Codec Tweak Tool?

Please advise.

But I believe exporting settings for the installer would be just fine, if possible. There are lots of configurations to be set up, so a custom installation profile would be nice.

**Comment by butterw** [comment]
The uninstaller keeps registry settings by default, no ?

See https://github.com/clsid2/mpc-hc/issues/788#issuecomment-740548117 for how to export/import mpc-hc settings with ini file.

**Comment by clsid2** [comment]
You can export settings of K-Lite installer to config file by using `/unattended` command line switch.
