### ISSUE TITLE
[Feature Request] Frame rate interpolation

### ISSUE THREAD

**Issue by BrosephJ** [clsid2/mpc-hc#803]
Searched for this in here but found nothing. I'm requesting this feature because I would like to have smooth video playback without having to rely on other software (SVP). MPV has some settings related to this but even with them on I don't notice any difference, plus I believe MPV is preferred in Linux instead of Windows. MPC-HC is by far my favorite video player for Windows and I'd very much love to have this functionality. Gimme dat smooth 60+ FPS videos! 😃

**Comment by clsid2** [comment]
Not going to happen in MPC-HC itself. You need to use SVP or hope one of the supported video renderers adds this functionality.
