### ISSUE TITLE
Backup-Restore Settings / Forums

### ISSUE THREAD

**Issue by roysubs** [clsid2/mpc-hc#807]
Not an issue, just questions:

• What is the easiest way to backup all of settings and then restore them onto a new machine?

• Is there a forum somewhere that might be more appropriate for questions like this?

**Comment by clsid2** [comment]
The settings are stored in this Registry key:
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC
You can make an export of that using the Windows Registry Editor (regedit.exe)

This project does not have a forum. But there are several website with video related forums. For example forum.doom9.org or forum.videohelp.com

**Comment by roysubs** [comment]
Perfect, thanks.

```
reg export 'HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC' $env:TEMP\MPC-HC.reg
reg import $env:TEMP\MPC-HC.reg
```

**Comment by clsid2** [comment]
I also recommend deleting the reg key just before importing backup. That way you recreate identical situation as during export.
