### ISSUE TITLE
Collection of interface-related settings on the "Interface" page

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#810]
As [clsid2 thoughts](https://github.com/clsid2/mpc-hc/pull/806#issuecomment-748210641) are:
> Where do you want to add the option in the GUI?
> I was thinking:
> Options > Player > Other
> To make space there, the "Process priority above normal" setting could be moved to the advanced settings. That is not really a common option that most people should change anyway.

adipose [suggests](https://github.com/clsid2/mpc-hc/pull/806#issuecomment-748339396):

> Other may be a good place for it. For reference, mpc-be has it here:
> 
> ![image](https://user-images.githubusercontent.com/3324395/102664843-84fbca80-4138-11eb-9f64-faca00557e4f.png)
> 
> We don't have an interface section, but I imagine we could add one and include the dark theme there.
> 

I am thinking about seekbar preview where should locate and did not want  fuss in pull request part.

I need to mention something, maybe it is important in situation of accordance.
Some Seekbar and interface settings located in Tweaks, Advanced tabs and if seekbar previews willl located somewhere else it makes confussion.
 **My suggestion is collect all interface related settings in one page "_Interface_" in Player tab.** 

______

- **I tried to collect all of my findings about interface.** 

> View > Dark Theme _(adipose suggested)_
> Advanced > HideWindowedControls
> Advanced > DefaultToolbarSize (maybe)
> Advanced > UseLegacyToolbar
> Advanced > AllowInaccurateFastseek
> Advanced > ModernSeekbar
> Advanced > ModernSeekbarHeight
> Advanced > TimeRefreshInterval
> Advanced > ShowLangInStatusbar
> Tweaks > Fast Seek (on keyframe) __
> Tweaks > Show Chapter marks in seek bar
> Tweaks > Auto-hide the mouse pointer during playback in windowed mode
> Tweaks > Use enhanced taskbar features
> Tweaks > Show time tooltip: __
> Tweaks > OSD Font: __
Tweaks > ![image](https://user-images.githubusercontent.com/3073922/103000460-2b324080-453c-11eb-956c-3164bb877283.png)

> Player > Other > Show OSD
> Player > Other > Limit windows proportions on resize
> Player > Other > Snap to desktop edges

_______
Other findings
> Tweaks > Open previous/next file in folder on "Skip back/forward" when there is only one item in playlist
(its location also can move to "Playback" page or somewhere else)

> Advanced > LoopFolderOnPlayNextFile (I do not know usage of this maybe related Playback > Playback OR After Playback, after getting knowledge about it I am waiting)

> Player > Formats > RealPlayer stuff (basically unused and unnecessary things should removed)
adipose suggested that but I dont know which parts used and which parts are useless.
_____
Some of the settings mentioned above are could be only for advanced users so I am waiting your suggestions with regards. I hope we can get beautiful result.

_____
Changes may applied anytime on google [sheet](https://docs.google.com/spreadsheets/d/1kBOB38K1093kLyy5ofEHdrx6Grsh0fb9borBja8__R0/edit#gid=0), the last one:

![image](https://user-images.githubusercontent.com/3073922/102787327-f4c8ba00-43b1-11eb-8cb3-dc14c09a0b48.png)

**Comment by pras92** [comment]
Nice work, on gathering possible settings related to 'Interface'. I agree that an Interface Tab would be better with settings such as Seek preview, Dark theme and OSD. As for the location, a new sub menu under Options>Player could be created, between 'Logo' and 'Web Interface'. 

Or another idea would be to replace the current 'Web Interface' with 'Interface' tab, and with the new settings at top and current 'Web Interface' settings in the bottom.

**Comment by adipose** [comment]
Seems like some good ideas. How about you mock up the reorganization of the settings and maybe someone can work on it eventually. Also some things need removing like the RealPlayer stuff.

**Comment by xLn2** [comment]
I have tried something on google sheets, [this](https://docs.google.com/spreadsheets/d/1kBOB38K1093kLyy5ofEHdrx6Grsh0fb9borBja8__R0/edit?usp=sharing) is the address of the sheet you can preview and comment it.

**Comment by xLn2** [comment]
After the transition of modern theme moved to **_Settings > Theme_**, I had the opportunity to take a look it again.

`Options > Tweaks > Show time tooltip (and preview):` 
This has some logical incosistency. This option doesn't requied for `Options > Tweaks > Show preview on seek bar`. So I think there is two option to make things clear.
1. remove **_(and preview)_** text from `Options > Tweaks > Show time tooltip (and preview):` 
2. Make `Options > Tweaks > Show time tooltip (and preview):`  prerequied option for activate `Options > Tweaks > Show preview on seek bar`

Also another thing is disabling `Use modern theme` shouldn't let people to change `modern seek bar height:` and `modern theme color`

I revised my draft and [it looks like](https://docs.google.com/spreadsheets/d/1kBOB38K1093kLyy5ofEHdrx6Grsh0fb9borBja8__R0/edit?usp=sharing):
![image](https://github.com/clsid2/mpc-hc/assets/3073922/9c5dd887-4a76-479d-94d4-063cb04c54cf)

> devs removed	`Advanced > ModernSeekbar`
> I thought its unrelated to Interface	`Advanced > AllowInaccurateFastseek`
> I thought its unrelated to Interface, because its advanced setting that barely few people need change `Advanced > TimeRefreshInterval`
> I thought its unrelated to Interface `Tweaks > Fast Seek (on keyframe)`

- [x] Status bar crowded looking might be solved by every options have check box
Show on status bar:
✅ Lang ✅ FPS ✅ Video Info ✅ A-B Marks

- [ ] I put options name (mostly) as is but these are requires better naming and  extra information on tooltips.

**Comment by adipose** [comment]
Overall this looks great.

I'd like to see legacy toolbar disappear one day so maybe leave that in advanced.  Some other options maybe too advanced for here.

**Comment by xLn2** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/3073922/aad348fd-94d1-4334-98d9-97000cfbf9f9)
updated 11.12.2023 21:40

You can view on [google sheets](https://docs.google.com/spreadsheets/d/1kBOB38K1093kLyy5ofEHdrx6Grsh0fb9borBja8__R0/edit?usp=sharing).

added Language options 
~~Show time tooltip > "below seek bar" changed to "beside cursor" because it's function not actually related to seek bar, it follows cursor.~~
removed some options which are more related to advanced/tweak/fullscreen
added tooltips which I found usefull
~~I am not sure about including status bar options.~~

**Comment by butterw** [comment]
> * Status bar crowded looking might be solved by every options have check box

Show on status bar:
✅ Lang ✅ FPS ✅ Video Info ✅ A-B Marks ✅ (%)Progress

**Comment by adipose** [comment]
MPC-HC still has code to show percent complete on the status bar, but it seems the option to enable it disappeared at some point.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/commit/8ce98cb460f3d405e9cef6d133ceb0bfd0a442d9

Looks like no advanced option was added for it--I can add it to the theme page.

**Comment by clsid2** [comment]
It is in right-click menu of the timer.

**Comment by adipose** [comment]
I see it now.  Should remaining time and high precision be added to settings as well, then?

**Comment by clsid2** [comment]
If there is lots of space available on the new settings page.
Best to reserve some space as well for future options.

Maybe split options over two pages to ensure there is enough space?

These could maybe also be moved to a second interface page along with the Window behavior ones:
Player > History > Remember window size/position + pns zoom
Playback > zoom & alignment

**Comment by adipose** [comment]
Here's a preview:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/6a55fc1f-c0b9-4874-b7bc-ca0a7e92d8cf)

**Comment by clsid2** [comment]
I would suggest to name the page "User Interface".
The "User Interface" block better named "Theme".
Put language in its own block.

Status bar element "language"  -> "Track Language(s)" ?

**Comment by adipose** [comment]
> I would suggest to name the page "User Interface".

I was just noticing this, they should be swapped.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2440
