### ISSUE TITLE
Support for embedded .vtt subtitles in MKV

### ISSUE THREAD

**Issue by cpz3501** [clsid2/mpc-hc#813]
All subtitles downloaded from YouTube are in .vtt format, problem is they don't work in MPC-HC (they work in MPC-BE). Maybe I missed something, but so far I haven't been able to get it to work in MPC-HC.

**Comment by lifegpc** [comment]
That's because LAV Filter don't support it.

**Comment by clsid2** [comment]
MPC-HC only supports external .vtt subtitles.

**Comment by ale5000-git** [comment]
@cpz3501: It is the wrong place, the correct place is here: https://github.com/Nevcairiel/LAVFilters/issues/80

Sample file: https://trac.ffmpeg.org/raw-attachment/ticket/5641/cut-vtt.mkv
More info: https://trac.ffmpeg.org/ticket/5641
