### ISSUE TITLE
fullscreen always on top

### ISSUE THREAD

**Issue by mustafa811811** [clsid2/mpc-hc#814]
i have some recorded material that have a nasty big white logo that cause clouding and blooming on my led tv , so i made a frameless black photo and forced it to be always on top to cover the logo , but still it cannot beat the mpc-hc fullscreen always on top

this issue doesn't happen with vlc player

is there anyway to solve this ?!

i use mpc-hc 1.9.8 and madvr on windows 10

**Comment by clsid2** [comment]
I don't have solution for you.

**Comment by mustafa811811** [comment]
ok thanks anyway
