### ISSUE TITLE
[Question] Crop function?

### ISSUE THREAD

**Issue by Geobert** [clsid2/mpc-hc#815]
Is there a crop video function like in VLC? Let say I want to watch Buffy in 4:3 instead of the widescreen version by cropping to 4:3 keeping the center of the frame, is there a way to do it?

Thank you for keeping MPC-HC alive :)

**Comment by lifegpc** [comment]
You can use Pan & Scan menu (View -> Pan & Scan). You may need create a Preset.
![image](https://user-images.githubusercontent.com/41434272/102774132-5a727180-43c5-11eb-8361-8923bf6e99ec.png)

**Comment by clsid2** [comment]
You can do that by pressing Numpad9 to zoom in.

**Comment by Geobert** [comment]
Thanks for your answer!

I tried this, but can't get any thing correct :-/ It deforms the picture, I just want to crop, not shrink

**Comment by clsid2** [comment]
Increase/decrease size does not deform the picture. Maybe you were changing just the width/height.

**Comment by Geobert** [comment]
Yes I was, because what I want is basically putting black borders on the sides so I have only the center left, in a 4:3 ratio. Doesn't seems that Pan & scan can achieve that :(

**Comment by clsid2** [comment]
If you want to add black borders on the sides, without deforming the video, then you need to decrease size. That will also add black borders on the top/bottom.

If that is not want you want, then I suggest taking a screenshot of the original video. Then modify that image the way you want with an image editor (like Paint). Then attach both images so I can see what you mean.

**Comment by Geobert** [comment]
First, the original version:
![mpc-hc64_adp7kLroxX](https://user-images.githubusercontent.com/72570/102811660-9b668800-43bd-11eb-81d7-8999ffe7ddcd.jpg)

Then what I'm trying to achieve:
![vlc_3ymKvtJ248](https://user-images.githubusercontent.com/72570/102811692-a8837700-43bd-11eb-8037-c4f59b8c3425.jpg)

**Comment by clsid2** [comment]
Cropping like that is not possible within the player.

But you can do it with ffdshow.
Install only ffdshow video processor. Add it as a preferred external filter in MPC-HC settings.
There is a crop option in ffdshow.

**Comment by butterw** [comment]
Masking to AR can be done with a pixel shader in mpc-hc (ex: barMask.hlsl)
