### ISSUE TITLE
Download smaller than the streaming

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#819]
Opening a YouTube link will return a 1920x1080 video but "Save a Copy..." will download a 640x360 video.
Is it a bug?

**Comment by lifegpc** [comment]
You can set Advanced->YDLCommaneLine to ```-f bestvideo+bestaudio```, this will let youtube-dl choose best formats.

**Comment by ale5000-git** [comment]
Now I understand, 640x360 is the best format with audio/video combined, with "-f bestvideo+bestaudio" I get:
```
WARNING: You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
```

And at the end I get 2 separate files for video and audio.

Is there a way to just place required files without install them?

**Comment by ale5000-git** [comment]
I downloaded ffmpeg-release-essentials.7z and just placed ffmpeg.exe in the same folder of youtube-dl.exe and it seems to work, thanks.

**Comment by xLn2** [comment]
I did not know how to merge video and audio file automatically, so this topic enlightened me so I will explain this process for these people like me:

1. Go to [Windows FFmpeg page](https://github.com/GyanD/codexffmpeg/releases)

2. Download latest essentials_build.7z

3. Extract just \bin\ffmpeg.exe on same folder youtube-dl.exe.

![image](https://user-images.githubusercontent.com/3073922/103086364-83794900-45f5-11eb-8135-2149d01d9bee.png)

4. All done! 👍

**Comment by lifegpc** [comment]
You can delete that zip/7z file. It is useless.

**Comment by ale5000-git** [comment]
@lifegpc: Apparently `-f bestvideo+bestaudio` on videos from `xhamster.com` always result in `ERROR: requested format not available`.

Is there a way to have best quality that work on all sites?

**Comment by clsid2** [comment]
Just leave away `-f bestvideo+bestaudio`. It will already pick the best available stream by default. If you have ffmpeg.exe in folder it will download separate streams (and merge them) if those are better than best single file stream.

**Comment by ale5000-git** [comment]
I use `-f bestvideo+bestaudio` because otherwise on Youtube it will download low quality videos but in this other case it doesn't work.

**Comment by clsid2** [comment]
You can use this `bestvideo+bestaudio/best`
Then it uses `best ` as fallback if `bestvideo+bestaudio` gives no results

**Comment by ale5000-git** [comment]
Thanks, it works.

Now I'm using this:
`-f bestvideo+bestaudio/best --all-subs --embed-subs --write-thumbnail --exec pause`

It still remain the problem that it doesn't stop in the rare case of errors but better than nothing.
