### ISSUE TITLE
When opening BD by using Open Disc menu, MPC-HC crash. 

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#820]
It happened again.
![image](https://user-images.githubusercontent.com/41434272/103169205-aa917e00-4874-11eb-8d07-fba7e8767d41.png)

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/103169232-f3493700-4874-11eb-9553-cd627b8fd3b2.png)
In CMainFrame, it seems fine.
![image](https://user-images.githubusercontent.com/41434272/103169254-183daa00-4875-11eb-916d-89c4669aa7d3.png)
But in CPlayerPlaylistBar, seems get a unexpected pointer.

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/103169360-d4977000-4875-11eb-909a-dee8666e0620.png)
![image](https://user-images.githubusercontent.com/41434272/103169350-b762a180-4875-11eb-82ad-d2c8240945d3.png)
should be ```GetParentFrame()->GetParentFrame()```

**Comment by lifegpc** [comment]
> ![image](https://user-images.githubusercontent.com/41434272/103169360-d4977000-4875-11eb-909a-dee8666e0620.png)
> ![image](https://user-images.githubusercontent.com/41434272/103169350-b762a180-4875-11eb-82ad-d2c8240945d3.png)
> should be `GetParentFrame()->GetParentFrame()`

![image](https://user-images.githubusercontent.com/41434272/103169424-728b3a80-4876-11eb-9e55-24a19794fb7e.png)
Seems it happened randomly.

**Comment by lifegpc** [comment]
Seems works fine now with latest code. :( I don't know why it happened just now. And I can reproduce it with K-Lite Codec ver MPC-HC (1.9.8.86 (56abf1e40)). Maybe should use a more safe way🤔

**Comment by lifegpc** [comment]
> I can reproduce it with K-Lite Codec ver MPC-HC 

Seems works fine now. Amazing. :(

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/103169923-fb0bda00-487a-11eb-881a-7a73d0865deb.png)
Happened again. :( I am sure it happened randomly.

**Comment by clsid2** [comment]
Test with `m_pMainFrame->m_MPLSPlaylist` instead of the `GetParentFrame()` weirdness.

**Comment by lifegpc** [comment]
> Test with `m_pMainFrame->m_MPLSPlaylist` instead of the `GetParentFrame()` weirdness.

![image](https://user-images.githubusercontent.com/41434272/103198442-4d083a80-4923-11eb-8a52-dbce742ec8bc.png)
Looks like fine
