### ISSUE TITLE
Significant difference in sound level when changing audio tracks

### ISSUE THREAD

**Issue by Sopor** [clsid2/mpc-hc#821]
When i change audio track in a video the sound levels are different between the tracks, but only the first time i change track.
I will try to explain more detailed.

1. I start with a `2 channel aac 48000 Hz` audio track.
2. I change to a `5.1 channel eac3 48000 Hz 192 kb/s` audio track and i can now hear a significant lower sound level.
3. I change to a `5.1 channel eac3 48000 Hz 640 kb/s` audio track and suddenly the sound level is back as it was in step 1.
4. I change back to `5.1 channel eac3 48000 Hz 192 kb/s` audio track (step 2) and now the sound level is the same as in step 1 and 3.
5. If i go back to `2 channel aac 48000 Hz` and instead change to `5.1 channel eac3 48000 Hz 640 kb/s` audio track this audio track is now significant lower until i change to audio track `5.1 channel eac3 48000 Hz 192 kb/s`.

If i do the same in VLC, mpv and SMPlayer the audio tracks have the same sound level (there is a slightly difference between the audio tracks, but that is expected as they have different kb/s and channels).

I'm running Windows 10 and MPC-HC 1.9.8.92 (53a638bfc).
I have even tried MPC-HC 1.7.13 (e37826845), but it has the same behaviour.

**Comment by clsid2** [comment]
Enable the mixer in LAV Audio Decoder and set it to 5.1

The player and the audio decoder do not change the volume when changing tracks, so the fault is in the Windows sound mixer or your sound driver.

**Comment by Sopor** [comment]
Yes, that seems to solve the issue 👍
