### ISSUE TITLE
Regression when opening LAV settings if seek preview is enabled

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#824]
@adipose

The preview window causes an issue when opening LAV Filters settings from their tray icons. The settings window does not appear until you click on the MPC-HC window. Probably being related to the preview being set as TOPMOST.

I have committed a patch to create the preview window only when its option is enabled. It is probably a good idea to also create it on demand when the option is enabled, so a player restart is not needed. I haven't done that yet.

**Comment by adipose** [comment]
I haven't been able to reproduce this issue.  Even without the patch, when preview is enabled, the LAV Filters windows come up just fine.

What if the window is set to topmost only when shown?  It should be possible with setwindowlongptr to toggle that option on and off.  Not sure if it would cause a focus issue.

**Comment by clsid2** [comment]
Maybe it only happened with externally registered LAV.

I think I have fixed it.
