### ISSUE TITLE
Have two same playlist submenu.

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#825]
![image](https://user-images.githubusercontent.com/41434272/103455218-3e0bf880-4d26-11eb-88d1-2e8033602422.png)
![image](https://user-images.githubusercontent.com/41434272/103455224-4c5a1480-4d26-11eb-9b29-2f1c98c0100f.png)

**Comment by clsid2** [comment]
Maybe it is because you are playing a bluray file? Does it also happens without .mpls files in the playlist?

**Comment by lifegpc** [comment]
I can't reproduce it now, seems happened very randomly.
