### ISSUE TITLE
Question on Recent Files List with UseTitleInRecentFileList set to True

### ISSUE THREAD

**Issue by MadokaAyukawa** [clsid2/mpc-hc#826]
With the above setting, I get the following.

![Untitled](https://user-images.githubusercontent.com/44476321/103579678-9578a880-4e8d-11eb-9a4c-b429106fb21b.png)

It seems that it repeats the entire filename in the parentheses which makes the list really long unnecessarily. I'm not sure if this is because the files I have are lacking some metadata HC is looking for.

**Comment by lifegpc** [comment]
That is because file name is same as video title.

**Comment by lifegpc** [comment]
If file is a URL:
It will display in this format: `S01E01.<series name> <season name> - <video title> (<shortened URL>)`
If season number, episode number, series name and season name is not exists or empty, it will be ignored.
If shortened URL still too long, it will display Host Name only.
If video title is not exists, it will display shortened URL directly.
If file is a normal file:
It will display in follow 2 formats:
`<video title>(<file name>)`
`<file path>`
![image](https://user-images.githubusercontent.com/41434272/103592572-56e6fa80-4f2e-11eb-89a9-212cf8720cb7.png)

**Comment by lifegpc** [comment]
> With the above setting, I get the following.
> 
> ![Untitled](https://user-images.githubusercontent.com/44476321/103579678-9578a880-4e8d-11eb-9a4c-b429106fb21b.png)
> 
> It seems that it repeats the entire filename in the parentheses which makes the list really long unnecessarily. I'm not sure if this is because the files I have are lacking some metadata HC is looking for.

It seems it have label name is equal with file name. I will fixed it.

**Comment by lifegpc** [comment]
Now if label name is equal file name, that label name will be ignored. So it will display file path directly.

**Comment by lifegpc** [comment]
[test build](https://mega.nz/file/IlxHlC6L#sbBAhP3CyUk8Ka4RI65GAwqgjA783_FJ2Bua3BTRcTs)

**Comment by MadokaAyukawa** [comment]
I just tried the test build, and I still get the same display as before.

**Comment by lifegpc** [comment]
You need reopen that file. Old entries is not effect now.

**Comment by MadokaAyukawa** [comment]
So I Cleared the Recent Files List, opened both files again, closed HC, reopened HC, and I still get the same display as before.

**Comment by lifegpc** [comment]
Maybe another problem. Can u send the mediainfo of that video file.

**Comment by MadokaAyukawa** [comment]
```
General
Unique ID                      : 1118622590039941777361414916135383487 (0xD7705A104CE4B575F0B1F3A46AF1BF)
Complete name                  : Mr.Queen.E01.x264.540p-SiN.mkv
Format                         : Matroska
Format version                 : Version 4
File size                      : 536 MiB
Duration                       : 1 h 16 min
Overall bit rate               : 983 kb/s
Encoded date                   : UTC 2020-12-13 01:57:41
Writing application            : mkvmerge v51.0.0 ('I Wish') 64-bit
Writing library                : libebml v1.4.0 + libmatroska v1.6.2 / Lavf58.35.101

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L3.1
Format settings                : CABAC / 8 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 8 frames
Codec ID                       : V_MPEG4/ISO/AVC
Duration                       : 1 h 16 min
Bit rate                       : 917 kb/s
Width                          : 960 pixels
Height                         : 540 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 29.970 (30000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.059
Stream size                    : 500 MiB (93%)
Writing library                : x264 core 159 r2991 1771b55
Encoding settings              : cabac=1 / ref=8 / deblock=1:-1:-1 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.15 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-3 / threads=17 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=22.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Default                        : Yes
Forced                         : No

Audio
ID                             : 2
Format                         : AAC LC SBR
Format/Info                    : Advanced Audio Codec Low Complexity with Spectral Band Replication
Commercial name                : HE-AAC
Format settings                : NBC
Codec ID                       : A_AAC-5
Duration                       : 1 h 16 min
Bit rate                       : 64.0 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 23.438 FPS (2048 SPF)
Compression mode               : Lossy
Delay relative to video        : -105 ms
Stream size                    : 34.9 MiB (7%)
Writing library                : Lavc58.65.102 libfdk_aac
Language                       : Korean
Default                        : Yes
Forced                         : No
```

**Comment by lifegpc** [comment]
Can you send me that file? If it have copyright, you can send link to my email: g1710431395@gmail.com

**Comment by MadokaAyukawa** [comment]
It's a later file which does the same thing (I just checked), but the link is alive.

https://we.tl/t-CEDvGskT7H

**Comment by lifegpc** [comment]
I see the bug. I will fix it.

**Comment by lifegpc** [comment]
[test build](https://mega.nz/file/o4g3VYjB#0jh_KdsAvW_OE1Lc1QI6xCAro-9UVDIg46yGQ_UjKFw)

**Comment by MadokaAyukawa** [comment]
I got this after clearing the list, replaying the files, closing and reopening HC.

**Comment by MadokaAyukawa** [comment]
That seems to have fixed it.

**Comment by ale5000-git** [comment]
@lifegpc: The test build fixed it but aren't you just fixed the symptoms and not the cause?

If I remember correctly K-Lite Codec Pack 15.9.5 was OK but K-Lite Codec Pack 15.9.6 is broken so isn't possible that the recent title changes broke it?

**Comment by ale5000-git** [comment]
Open this link with the build included in K-Lite Codec Pack 15.9.6: `https://www.vvvvid.it/show/892/sword-art-online-alicization-war-of-underworld/1545/693801/nelle-terre-del-nord`.

Inside the recent files list the file appear correctly.
Now close and reopen the player, you will see that the url is duplicated in the recent file list.

**Comment by MadokaAyukawa** [comment]
This is just more of an observation. Most of the files I have that have the title of the movie in the metadata are named similarly to the file itself when I get them (I don't change the names). So I get a lot of repeated information with the "video title (file name)" format.

![Untitled](https://user-images.githubusercontent.com/44476321/103696953-0e423800-4f54-11eb-8859-a4dec7ede384.jpg)

In the first example, only the extension is added. In the second example, the title itself is enough.

**Comment by clsid2** [comment]
I will fix that by comparing only the first part of the filename and title to see if they are nearly the same.

**Comment by lifegpc** [comment]
> @lifegpc: The test build fixed it but aren't you just fixed the symptoms and not the cause?
> 
> If I remember correctly K-Lite Codec Pack 15.9.5 was OK but K-Lite Codec Pack 15.9.6 is broken so isn't possible that the recent title changes broke it?

I am sure this commit: 8cb0c13
