### ISSUE TITLE
Black screen when watching VP9 Youtube stream (AMD) until scrubbing

### ISSUE THREAD

**Issue by Riotous** [clsid2/mpc-hc#83]
Windows 10 64 bits, AMD graphics. MPC-HC 1.8.5 with LAV 0.74. Always happens with Software decoding and DXVA2. Also mostly but not always happens with DXVA2 (copy back).

1) Watch a VP9 Youtube stream with Opus audio using YDL or even a locally saved .webm download. Any Youtube link will do as long as it's VP9 with Opus. 
2) Video shows as a perfectly black screen (no image at all) while audio plays fine.  
3) Scrubbing anywhere else in the video brings playback back to normal. 

Not sure if this is an MPC-HC issue but they said to report playback issues here first.

**Comment by clsid2** [comment]
@nevcairiel

**Comment by Nevcairiel** [comment]
This sounds like a renderer issue to me, especially when it randomly happens.

**Comment by Riotous** [comment]
@Nevcairiel It consistently happens with software decoding and dvxa2.

**Comment by clsid2** [comment]
I am also seeing corrupted video with software decoding.

Sample link:
https://www.youtube.com/watch?v=Mgv88ZLi6LY

**Comment by Riotous** [comment]
@clsid2 My apologies, I could have sworn I opened this issue up in the LAV Filters page.

**Comment by Nevcairiel** [comment]
> I am also seeing corrupted video with software decoding.
> 
> Sample link:
> https://www.youtube.com/watch?v=Mgv88ZLi6LY

That video decodes just perfectly fine here using official 0.74 in software decoding.
Its a bad video to try to demonstrate problems however, since its full of effects that could be mistaken as wrong decoding.

**Comment by Nevcairiel** [comment]
As far as I can tell the problem only appears with MPC-HC and EVR-CP, not with any other renderer. Its likely not a LAV problem.

**Comment by clsid2** [comment]
The initial black screen is with EVR-CP only yes.

But the corruption happens with all renderers. A few frames are good. Then a couple with total corruption. Then a few good again. Etcetera. Decodes normally with DXVA (both native/cp). Keyframes are good. The corruption is non-deterministic and seems gone with 1 thread.

**Comment by Riotous** [comment]
I'm going to re-open so other people can see this issue and confirm what we are seeing, and because it looks like this might be a renderer issue. 

Here's a screencap of the behavior: https://files.catbox.moe/rlonvo.mkv

**Comment by Nevcairiel** [comment]
I found one bug that might explain the black screen issue on account of possibly bad timestamps, and I fixed it in https://files.1f0.de/lavf/nightly/LAVFilters-0.74.0-1.exe

But that bug would not account for corrupted decoding, nor have I been able to reproduce it at all.

**Comment by clsid2** [comment]
Black screen issue is fixed.

The corruption only happens when playing the stream. No problem with downloaded file. A seek is also needed to trigger it.

DebugView shows this:
[6672] LAVAudio.ax(tid 1fc0)   174206 : [vp9 @ 0000000005e576c0] Not all references are available

**Comment by Nevcairiel** [comment]
References missing happens on seeks, there is nothing that can really be done about that.

**Comment by clsid2** [comment]
The problem is different from such temporary corruption.

Seek to 04:57.000
1 thread:
Whole bunch of "Not all references are available". Video freezes until next keyframe. Then plays without problems.
2 threads:
No freeze, but a few frames of corruption. Just two "Not all references are available". Playback recovers properly.
8 threads:
Video keeps getting corrupted. No additional errors in debug log.

**Comment by Nevcairiel** [comment]
Is this really a new issue? I don't think the VP9 decoder changed in recent times.

**Comment by clsid2** [comment]
0.73.1-11 is first build with the problem.
With 0.73.1-6 the video recovers.

**Comment by Nevcairiel** [comment]
The corruption should also be fixed.

**Comment by clsid2** [comment]
Thanks for quick fix!
