### ISSUE TITLE
hotKeys filter user help

### ISSUE THREAD

**Issue by butterw** [clsid2/mpc-hc#831]
UI improvement
	
The hotkey filter isn't labelled and some of the keywords required aren't obvious. 
ex: Options > Player > Keys > type in: PnS

Proposition: add a tooltip or a texbox label with the less obvious, most useful hotkey command groups.
ex: jump, PnS, Alt, toggle, sub, osd, vol, dvd, shader

**Comment by clsid2** [comment]
A label "Search:" could be added in front of the textbox.

Most users have no clue what PnS means, so showing it as a suggestion won't solve anything.

**Comment by butterw** [comment]
I agree that the order of the keywords could be changed to be made more intuitive. 
However,
- the hotkey list is only available in this interface (no docs) 
- it's too long to be read without filtering 
- the best search keywords don't even appear in the menu !
-> So it's useful to provide the list IMO.

There should be enough room in the interface after the filter to display it:
[ _____________________ ] Search, ex: Alt, dvd, osd, sub, jump, vol, toggle, shader, PnS ...

Most users will never need to change default hotkeys for Pan&Scan. This list would help an intermediate user who wants to view/change hotkeys.

**Comment by butterw** [comment]
Looking at the interface, I think the way to go would be to add a tooltip to the existing Keys Label with suggested keywords:
![mpc-hc_O_Keys_Shader](https://user-images.githubusercontent.com/408915/103868155-ca247400-50c8-11eb-9133-086a8560033d.png)

**Comment by butterw** [comment]
Mpc-be has a "Filter:" label next to the search box, but it doesn't solve the issue (I'm not sure it helps at all tbh). 
jump, toggle, PnS, VidFrm aren't used in the menu and aren't obvious.

Filter: Alt, dvd, osd, sub, audio, vol, open, shader, toggle, jump, PnS, frm 
+VidFrm (Video Frame menu commands): vid or frm

**Comment by adipose** [comment]
Maybe a better idea is to have a descriptive text for hotkeys and what they do, and make it a tooltip.  Additionally, the filter could search the tooltips (maybe with a checkbox required, since it could be a slower search).

PnS are pretty cryptic, so any like that could have a help text added, whereas others wouldn't need one at all.

**Comment by clsid2** [comment]
Some of the items in the list should be given a better name. Then a tooltip would not be needed.
"PnS Left" -> "[Move video] Left"
"PnS Rotate X-" -> [Rotate] X axis - (flip)
"PnS Rotate Y-" -> [Rotate] Y axis - (mirror)
"PnS Rotate Z-" -> [Rotate] Z axis - (clockwise rotate)
"Jump Forward" -> "Jump/seek Forward"

"Pan & Scan" in the menu could maybe be given a better name. Something like "Move/Rotate".

**Comment by butterw** [comment]
+1 for Jump/seek: No reason not to change it.

- pns is actually used as a command-line switch
- panscan is a commonly used name for zoom-crop operations, ex: 4/3 with black bars to 16/9 
- Mirror is preferable to rotate for anything that isn't 90° flip. 
- Rotate is in the "Pan & Scan" Menu, which pns is the filter for
- All these commands share Reset PnS...

**Comment by adipose** [comment]
@clsid2 

Can we close this one?

**Comment by butterw** [comment]
I think renaming "Jump Forward" -> "Jump/seek Forward" should be considered. It makes it easier to understand/find the seek keys.
