### ISSUE TITLE
Starting mpc-hc 1.9.8.0 asks for admin permissions 

### ISSUE THREAD

**Issue by larsen0815** [clsid2/mpc-hc#832]
I have been using mpc-hc 1.7.8 from CCCP (Combined Community Codec Pack 64bit) and now replaced it with 1.9.8.0 from this project. When started, Windows (10, 20H2) asks for admin permissions which I find strange.

VirusTotal doesn't show detections for any major AV-engine. However, it's been scanned the first time only 8 hours ago, so this might not be accurate.
https://www.virustotal.com/gui/file/b8c7763388d40ce0e4f0a19ab1f4073b32e06fec02f2c10b27b81d96a3a23bec/detection

md5sum is 833c2a15f5b780e2b434ea67e933e47d

Is this to be expected? Why would it need admin privileges?

**Comment by clsid2** [comment]
I does not need admin privileges. Maybe you have accidentally set some compatibility mode. Right-click on its .exe > Properties > Compatibility.

**Comment by larsen0815** [comment]
No compatibility mode. Can you confirm the exe should have the aforementioned md5 sum?

**Comment by clsid2** [comment]
MD5 is correct. That date is the last scan time.

But this file is the installer. The installer does require admin permissions, and it always has. I though you were talking about the player itself. Once installed it does not need admin permissions.

**Comment by larsen0815** [comment]
Ah! I didn't recognize it as an installer. Thanks =)
