### ISSUE TITLE
[REQ] Error console

### ISSUE THREAD

**Issue by vedranvuk** [clsid2/mpc-hc#836]
Hi,

just throwing this out there. It'd be great if an error console docker existed outputting any details about various component errors such as subtitles, yt-download, etc. Having this would help with debugging. Especially useful would be to see streaming errors.

Thanks.

**Comment by clsid2** [comment]
There already is an internal logging function for subtitle search and youtube-dl processing. I am not interested in adding any new functionality.

Logging internal errors in "external" components such as LAV Filters is not possible.
