### ISSUE TITLE
Are AStyle and pre-commit.sh still used here?

### ISSUE THREAD

**Issue by kenny1983** [clsid2/mpc-hc#839]
I finally have my first patch ready to be committed and pushed, but am a bit confused re: the guidelines in `CONTRIBUTING.md`.

It seems as though that document hasn't been changed in 4 years, and also hasn't been followed properly in recent times, since running `contrib/run_astyle.bat` has created changes in 83 files that I didn't change myself.

The pre-commit hook also gives me many warnings about copyright information being out of date in all of the same files, so should I fix those issues or leave them be?

The pre-commit hook suggests I can simply "ignore this and commit anyway [using] `'git commit --no-verify'`", so I guess that's what everyone's been doing for the past 4 years (or not enabling the hook in the first place!). Should I do the same?

**Comment by clsid2** [comment]
They are not actively used at the moment. You can ignore them.
