### ISSUE TITLE
Remove swf support

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#840]
Now it's time to remove swf support.
![image](https://user-images.githubusercontent.com/41434272/104330136-a62dbc00-5528-11eb-92c8-d2d7d90930e2.png)

**Comment by ale5000-git** [comment]
Wht not keep it?
I have a lot of swf games (locally), and MPC-HC can seek them, it is the only one that can do it.

It would even be better if it was able to load the flash dll directly if it is near the player exe instead of require flash installation.

**Comment by ale5000-git** [comment]
To fix the date issue someone could look at the API used by the flash dll and hook the API for faking year 2020 before loading flash.

**Comment by clsid2** [comment]
There is no need to mess with dates. It is possible to whitelist websites and local files using mms.cfg. Then it will continue to work as normal.

I may remove it in the future. But not yet.
