### ISSUE TITLE
Problem whitelisting local SWF files

### ISSUE THREAD

**Issue by gwi2014** [clsid2/mpc-hc#842]
Hi,
in #840 you wrote, that it's possible to whitelist local SWF files via mms.cfg. So I created

- C:\Windows\System32\Macromed\Flash\mms.cfg
- C:\Windows\SysWOW64\Macromed\Flash\mms.cfg

with this content:

```
AutoUpdateDisable=1
SilentAutoUpdateEnable=0
EOLUninstallDisable=1
EnableAllowList=1
EnableInsecureAllowListLocalPathMatching=1
AllowListUrlPattern=file:*
```

Now it works with Internet Explorer but it still does not work with mpc. Am I missing something?

Thanks,
Guido

**Comment by ale5000-git** [comment]
Personally I prefer to use https://www.nirsoft.net/utils/run_as_date.html to run MPC-HC with a date of 2020, then all swf will run.

**Comment by clsid2** [comment]
You also need to update to latest version of Flash. I was using a version that was a few months old and local file playback didn't work until I updated.

You can reply to closed issues. No need to create new ones for same issue.

**Comment by ale5000-git** [comment]
@clsid2: I have tried the mms.cfg method also but while it work in IE it doesn't work in MPC-HC, it is the latest version.

Is there a trick to load Flash dll from the MPC-HC folder (so that can be easily used a patched one)?
I have tried with mpc-hc64.exe.local but it doesn't seems to work.

**Comment by gwi2014** [comment]
> You also need to update to latest version of Flash. I was using a version that was a few months old and local file playback didn't work until I updated.

I'm using version 32.0.0.465 which seems to be the latest one.
 
> You can reply to closed issues. No need to create new ones for same issue.

The other issue was about removing SWF support, so I created this one which is about whitelisting SWF files for mpc.

@clsid2: Would you mind reopening this issue, while it's not resolved? Other users may have the same problem and it's more easy to find when it's open.

Thanks,
Guido

**Comment by clsid2** [comment]
This isn't a bug in MPC.

If it doesn't work you need to go complain to Adobe. I can't fix their broken software.

You can also dump Flash completely and use an emulator such as [Ruffle](https://ruffle.rs/) instead.

**Comment by ale5000-git** [comment]
MPC-HC is nice because with seeking I can cheat on Flash games and go on the ending video :)

**PS:** Is it possible that it doesn't work because MPC-HC use pathes like `C:\folder\file` instead of `file:///c:/folder/file` ?

**Comment by gwi2014** [comment]
> This isn't a bug in MPC.

Hmm I agree with you because it worked till 11.01.2021. But obviously MPC does something differently then the Internet Explorer.

> If it doesn't work you need to go complain to Adobe.

I'm not sure if you're serious, but I don't think this would have any chance of success.

> I can't fix their broken software.

The question is whether one "only" need to get the configuration of Flash Player "right", or whether you really need to change any code for a fix.

> You can also dump Flash completely and use an emulator such as [Ruffle](https://ruffle.rs/) instead.

My wife is a teacher for little children in Kindergarden and she got used to using MPC for little SWF games. Ruffle unfortunately does not support AS3 so this is not an option.

I'd really like to hear other ideas for a fix and I think that would be easier if the ticket was reopened. But of course that's not my project, so that's your decision.

Thanks,
Guido

PS: @ale5000-git The setting EnableInsecureAllowListLocalPathMatching should work around the path problem according to the documentation.

**Comment by clsid2** [comment]
This works for me:
C:\Windows\SysWOW64\Macromed\Flash\mms.cfg
```
AutoUpdateDisable=1
EOLUninstallDisable=1
SilentAutoUpdateEnable=0
DisableDeviceFontEnumeration=1
AllowListPreview=1
TraceOutputEcho=1
EnableAllowList=1
EnableInsecureAllowListLocalPathMatching=1
AllowListRootMovieOnly=1
AllowListUrlPattern=file:*
```
You don't need to duplicate the file in system32, as that one does not get used at all!

Windows 7 + Flash 32.0.0.465
It did not work for me with older Flash 32.0.0.445, neither does it work on Windows 10, which uses its own install of 32.0.0.445

Otherwise find 32.0.0.363 as that does not contain the timestamp.

Or use this working Flash player from Adobe;
https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flashplayer_32_sa.exe

**Comment by ale5000-git** [comment]
The problem is that it doesn't work on MPC-HC on Windows 10 + Flash 32.0.0.445, but since it is working on IE on Windows 10 + Flash 32.0.0.445 I'm not sure what to think.

**Comment by clsid2** [comment]
IE uses the ActiveX control while MPC-HC uses the OLE control. Those are totally different.

**Comment by gwi2014** [comment]
@clsid2  Thanks for clarifying. I tried your settings above but it does not work on our Windows 10 with Flash 32.0.0.465.

The stand alone Flash Player you provided does work - so thank you very much for that. That is a good workaround for now.

Thanks again for your help,
Guido

**Comment by clsid2** [comment]
Taking Flash64_32_0_0_465.ocx from Windows 7 and registering that file on Windows 10 (with regsvr32.exe) also works for playback in MPC-HC.

**Comment by Stalkeork** [comment]
as Win 10 uses proprietary flash.ocx - you cant just install another one (older or newer), but you can patch it. 
I absolutely got drained up by this situation, cause I cant get one thing: where windows storing its flash file
i manually patched both in syswow64 and sys32 folders (macromed/flash), nothing happened and I was totally broke. but when I found https://github.com/darktohka/FlashPatch i noticed a thing: that programm cant patch it too, because.. it was used by some application
"wtf" is sounded in my mind and I restarted pc in safe mode, used that path and it worked like a charm! 
phew 
maaan

**Comment by JAK0723** [comment]
So what does the "Requires Adobe Flash Player for IE with killswitch patch" message mean, exactly? I tried both [FlashPatch](https://github.com/darktohka/FlashPatch) and [FlashPatcher](https://github.com/KuromeSan/FlashPatcher), but nothing seems to have changed. I have Windows 10, btw.

**Comment by clsid2** [comment]
The Flash plugin has an internal date check that makes it stop working completely after January 12th 2021. The patchers disable that date check.

**Comment by JAK0723** [comment]
Yeah, I gathered that, but I still get that "Requires Adobe Flash Player for IE with killswitch patch" message when I try to play SWF files. Am I doing something wrong?

**Comment by clsid2** [comment]
That message means that the plugin failed to load. Either not installed or not working properly.

Remove the plugin that came with Windows 10 and use
[Patched Flash plugin](https://www.sendspace.com/file/7cv5ws)

Or use this working Flash player from Adobe:
https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flashplayer_32_sa.exe

**Comment by JAK0723** [comment]
Wow, it works perfectly now, thanks a bunch!

**Comment by Mirrorman95** [comment]
> [Patched Flash plugin](https://www.sendspace.com/file/7cv5ws)

The sendspace link is dead.

**Comment by clsid2** [comment]
https://github.com/darktohka/FlashPatch
https://github.com/KuromeSan/FlashPatcher/releases
