### ISSUE TITLE
never find subtitles from OpenSubtitles

### ISSUE THREAD

**Issue by Ramonlaw** [clsid2/mpc-hc#843]
i think the api is wrong cause i cant find anything from OpenSubtitles but always find something from other sources

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/104396689-220a2180-5586-11eb-9c7b-05da51ae7eb9.png)
It works fine. You need login.

**Comment by clsid2** [comment]
Subtitle search/download using OpenSubtitles requires a login. You can create a free account on opensubtitles.org website. After that, you can configure it here: MPC-HC options > Subtitles > Misc > Right-click on OpenSubtitles > Setup

**Comment by Ramonlaw** [comment]
![Captura de Tela (34)_LI](https://user-images.githubusercontent.com/77369336/104403746-f5c7b400-5537-11eb-940e-d519c847cf2a.jpg)
![Captura de Tela (33)](https://user-images.githubusercontent.com/77369336/104403750-f7917780-5537-11eb-9f69-8289f1e4dbd5.png)


Im loged but still getting nothing

**Comment by Ramonlaw** [comment]
i also tryed to reset configs and relog but still not working

**Comment by clsid2** [comment]
It works here with that same filename.

Try with MPC-HC 1.9.8.115

**Comment by Ramonlaw** [comment]
![2021-01-13 (4)](https://user-images.githubusercontent.com/77369336/104505378-8a76f400-55c2-11eb-923e-06507d9fc251.png)


Im aready using this version

im not using VPN

**Comment by Ramonlaw** [comment]
![image](https://user-images.githubusercontent.com/77369336/104505603-eb9ec780-55c2-11eb-95fd-e8a205a3131c.png)
i can reach the open subtitles site

but still stuck on mpc

**Comment by alanxummp** [comment]
MPCHC 64bit  2.0.0 build Jan11 2023,  Opensubtitle keeps telling me wrong username/pass but I have checked like 3 times, and have logged into the website on browser successfully.  So what is going on

**Comment by clsid2** [comment]
Either you are doing something wrong, or you are being blocked, or their server is having issues.

It is working fine here, so I can not help you.
