### ISSUE TITLE
How can I save imported/downloaded subtitles into UTF-8 by default?

### ISSUE THREAD

**Issue by wellloaded** [clsid2/mpc-hc#845]
Say I'm playing a video and there are subtitles, if I select the function file/subtitles/save subtitles they are saves in this format:

ISO-8859 text, with CRLF line terminators

So I can i have MPC-HC saving subtitles automatically in UTF-8 instead?

Thanks!

**Comment by clsid2** [comment]
There is a text encoding setting on the bottom of the  save dialog.

By default it uses same encoding as the original file.
