### ISSUE TITLE
Paused full screen MPC window is still "On Top" with "While Playing" option Enabled

### ISSUE THREAD

**Issue by ni554n** [clsid2/mpc-hc#846]
> View > On Top > While Playing / While Playing Video > Enabled

### Expected:
Paused MPC window is not on top if we Alt + Tab to other windows.

### Actual:
Paused **Full screen** MPC window is still on top after switching to a new window.
No such issue with normal paused window mode.

### Build information:
    Version:            1.9.8.109 (d946964d6)
    Compiler:           MSVC v19.26.28806
    Build date:         Dec 28 2020

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1074
