### ISSUE TITLE
MPC-HC is unable to play an asx streaming

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#847]
MPC-HC is unable to play this streaming: `http://www.geekymedia.com/viewcvs/cgi/viewcvs.cgi/*checkout*/geekymedia_web/media/westwing.asx?rev=1.1.1.1&content-type=video/x-ms-asf`

Windows Media Player can play it correctly.

**Comment by lifegpc** [comment]
looks like it will call youtube-dl first.

**Comment by ale5000-git** [comment]
I have tried also with UseYDL=false but the problem remains.

**Comment by clsid2** [comment]
Open url with web browser and play the downloaded .asx file.

Fixing this is low priority. Such streams are slowly getting extinct.

**Comment by ale5000-git** [comment]
Thanks, I know that I can download and open it but it would be nice to fix it even if it isn't urgent.

**Comment by clsid2** [comment]
Fixed

**Comment by ale5000-git** [comment]
Thanks :)
