### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by vdb1975** [clsid2/mpc-hc#849]
Hi

The app freeze when I press "Next" button but audio and video continue normally.
Can't even quit the application

**Comment by clsid2** [comment]
Which version?

**Comment by vdb1975** [comment]
Latest

**Comment by clsid2** [comment]
It works fine for me and others. So you need to give more details about what kind of files trigger this problem. If I can't reproduce it, then it is impossible for me to provide a solution.

**Comment by vdb1975** [comment]
It does it reading a mp4 with hardware acceleration. Several videos in the
same file when I do next on the 5th, there is a freezing of UI and I have
to kill the app.

**Comment by clsid2** [comment]
When it freezes:

1. Open the Windows Task Manager (Ctrl+Shift+Esc)
2. Right-click on mpc-hc64.exe process and select "Create Dump File"
3. Zip (or rar/7z) the dump file.
4. Upload it somewhere for me. For example http://www.sendspace.com

Then I can check where in the code it freezes.

**Comment by vdb1975** [comment]
OK. Will do it
