### ISSUE TITLE
Feature request: Allow users to make YDL prefer streaming .mp4 extension videos to avoid VP9.

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#85]
VP9 is mandatory for 4K videos but for 1080p videos and below, telling MPC-HC to have a YDL maximum height of 1080 usually results in .webm (VP9) videos being streamed. There's no choice in the MPC-HC UI to prefer .mp4 (h264 and more recently, AV1) instead. This is already an option in Youtube-dl itself but we can't configure it within the MPC-HC UI. 

`# Download best mp4 format available or any other best if no mp4 available
$ youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'
`

To give users more choice, can we have an advanced option to prefer .mp4 extension videos when possible?

I think a lot of people (with slower PCs) still would prefer to play h264 Youtube videos and this option would give us the last bit of control needed to stream only those videos.

**Comment by lvqcl** [comment]
I suspect that you can write this option (-f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best') into %APPDATA%\youtube-dl\config.txt

**Comment by clsid2** [comment]
Config file does not work, because MPC-HC is the one choosing the stream from all available ones.

An option for preferred video format is on my ToDo list. But I can't promise it will be available anytime soon.

**Comment by clsid2** [comment]
Option for preferred video format has been added.
