### ISSUE TITLE
Get duplicate blu-ray playlist.

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#850]
![image](https://user-images.githubusercontent.com/41434272/104895794-45333780-59b1-11eb-8eaa-78bd1520286a.png)
`00003.mpls` is same as `01003.mpls`, but `01003.mpls` have chapter infos.
The [ISO file](https://mega.nz/file/spwTBADL#BjCxlFuv58EOfDV8O6dDXmQri9qM7jskpuM14EhNRQg) which removed the video file.

**Comment by clsid2** [comment]
It simply parses all playlists. I don't know if there is any information available that the parser can use to ignore certain ones.

**Comment by Aleksoid1978** [comment]
You can see/use parser from MPC-BE.

**Comment by adipose** [comment]
Link is dead.
