### ISSUE TITLE
[Feature Request] display name for current palying Item

### ISSUE THREAD

**Issue by hafedh-trimeche** [clsid2/mpc-hc#853]
Hello,

Would current Item or Favorite name be displayed instead of the path file name, e.g. channel inside m3u file?

Best regards.

**Comment by clsid2** [comment]
Options > Player >title bar > replace file name with title

**Comment by hafedh-trimeche** [comment]
Hello,

Sorry, it is functional only from Playlist not from Favorites!

Best regards.
