### ISSUE TITLE
[request] Show OSD title for audio/sub track on switch

### ISSUE THREAD

**Issue by azev** [clsid2/mpc-hc#858]
When I switch audio/sub track via hotkey it doesn't show in the OSD the track title.
It would be very nice to have it shown in the OSD for 3s when track is changed.
Thanks

**Comment by MadokaAyukawa** [comment]
When I switch with a right click on a subtitle track, it doesn't show in the OSD, but then it shouldn't have to as I just picked a specific track. When I change subtitle tracks with the hotkey, it does show in the OSD for me. I don't have any multi-audio files, but I'd assume audio switching is the same.
