### ISSUE TITLE
Preview isn't rotated

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#860]
Hi,
the preview doesn't follow manual rotation and auto-rotation, sample [here](https://drive.google.com/file/d/1JleI-8v79SgTMYuBgGuCXB2-6q_JTM49/view?usp=sharing).

**Comment by clsid2** [comment]
We use the vanilla EVR renderer for preview. That does not support rotate. It also does not support HDR.

Using another renderer is not an option as I am afraid that could result in lots of stability and performance problems.
