### ISSUE TITLE
Playlist UI doesn't update correctly when deleting a file

### ISSUE THREAD

**Issue by Ferocit** [clsid2/mpc-hc#863]
**Setup**
* Player with attached playlist (ctrl+7) enabled
* Multiple files in playlist
* Delete currently playing file from disk (ctrl+del)

**Expected behavior**
* Entry gets removed from playlist
* Numbers left of entries are shown correctly
* Currently playing indicator (red dot) shows

**Actual behavior**
* Indicator is (often, not always) missing, only playtime is shown in a red font (see MissingIndicator.png)
* Number left of entries doesn't seem to update (see MissingIndicator.png - Number 2 is missing)
![MissingIndicator](https://user-images.githubusercontent.com/3397899/105615043-c7669600-5dcd-11eb-86ad-e8b732c49f87.png)

* UI sometimes gets messy (see MessedUpNumbers.png - The last two numbers seem to overlap!?)
![MessedUpNumbers](https://user-images.githubusercontent.com/3397899/105615045-c7ff2c80-5dcd-11eb-8a07-8d73a41af658.png)

**Comment by adipose** [comment]
Does the same bug occur in Dark Mode?

**Comment by Ferocit** [comment]
Yes, just tested it in Dark Mode. The same bugs is there, too.

**Comment by adipose** [comment]
ctrl+del is a custom shortcut you have for recycling an item?

![image](https://user-images.githubusercontent.com/3324395/110422426-35041400-8054-11eb-961c-93c11a095b1b.png)

**Comment by adipose** [comment]
Couldn't reproduce it.  I did note some weird inconsistencies.  The playlist traps the delete key and processes a delete.  But the main form also wants to process it.  When deleting from the main form, it will continue playing the next item, but when deleting from within the playlist, that doesn't work.

It seems we could just let this key pass back to the main form, but then it wouldn't work as it does today, if the user had changed the delete hotkey...

**Comment by clsid2** [comment]
I am able to reproduce it this way:
Add 5 files to playlist. Play second file. Set focus to video. Press Del to delete file 2.
Contents of playlist is now numbered: 1. File1 / 2. File3 / 3. File4 / 5. File5
So in this case the last entry has wrong index. But funny thing is that once it select that entry it is redrawn with correct index. So probably an off-by-one bug in the drawing code.

If playlist has focus then Del will remove the entry (not the file). It should not process that again in main window. But perhaps we can add Ctrl+Del as shortcut in the playlist window for move to recycle bin.

**Comment by Ferocit** [comment]
> ctrl+del is a custom shortcut you have for recycling an item?
> 
> ![image](https://user-images.githubusercontent.com/3324395/110422426-35041400-8054-11eb-961c-93c11a095b1b.png)

Yes, I've assigned ctrl+del to "Datei löschen" (German for "Delete file", but the ID is the same).

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/989

Pretty sure what's happening is the listctrl is optimized to not redraw items, but just shift them up, when things are added or removed.  However, it doesn't know that we have draw code that includes the sequence of each item, which means all items after the delete need redrawing.
