### ISSUE TITLE
Crashing on right click and close window from taskbar [win 10]

### ISSUE THREAD

**Issue by Arczi008TV** [clsid2/mpc-hc#864]
Im listening something in background, then I quit MPC from taskbar using right click and close - it crash.
And page appear - https://drdump.com/UploadedReport.aspx?DumpID=58880225

![crashh](https://user-images.githubusercontent.com/49120706/105635195-18c06500-5e62-11eb-9764-31230c183f80.png)

**Comment by clsid2** [comment]
Try version 1.9.8.159:
https://github.com/clsid2/mpc-hc/releases
