### ISSUE TITLE
Mouse scroll not working when over controls area unless directly on volume part.

### ISSUE THREAD

**Issue by exuvo** [clsid2/mpc-hc#865]
I have been using old MPC-HC for years on windows and i am pretty sure i could hover the mouse anywhere over the controls in fullscreen (set to appear when mouse is at the bottom) and still be able to adjust volume with the mouse wheel.

I just switched over to linux but all the media players i can find there suck (the best i could find, smplayer, did not even support chapters) so i am running MPC-HC via wine (with dxvk, madvr and xysubfilter). I have only encountered a few problems, this, that the options menu does not refresh as it should when changing category (not really much of a problem as i rarely change them, workaround: re-open options and new category is visible) and madvr sometimes seeking a keyframe too late when going to chapters.

With the latest release from here i am unable to adjust volume with mouse scroll when mouse is over controls unless i have the mouse pointer directly over the volume slider. Same behavior in windowed mode. In window mode it does work on the "File View" row at the top but not on "Seek bar" "controls" or "status" parts at the bottom. Works fine when mouse is over the video part.

This looks very similar to #473 which was reverted. Would it be possible to fix the recursion problem in that patch and re-apply it?

**Comment by clsid2** [comment]
It works fine here in Windows.

I don't use WINE, and I am not interested in fixing bugs that only happen in WINE. The issues are likely bugs in WINE itself. You need to submit bug report to WINE developers.
