### ISSUE TITLE
[request] add subscene subtitles

### ISSUE THREAD

**Issue by 3xploiton3** [clsid2/mpc-hc#867]
in my country (indonesia language) very often contributor upload to subscene.com,

please add feature for subscene sync

i tried this tools, work good,
https://github.com/HandyOrg/HandySub

<summary>

<details>

![image](https://user-images.githubusercontent.com/19517680/106008275-b5486880-60e9-11eb-9682-7b170f0c2234.png)

</details>
</summary>

**Comment by clsid2** [comment]
That website does not have an API for searching and downloading subs.

**Comment by ale5000-git** [comment]
It is unofficial but there is: https://github.com/andy-pham/subscene-api

**Comment by clsid2** [comment]
I am not interested in implementing support for any new subtitle providers. So unless someone submits a patch, nothing is going to happen. Those unofficial APIs are not usable at all by MPC-HC. It must be completely be re-implemented.
