### ISSUE TITLE
[Request] Add option to display current world time in status bar

### ISSUE THREAD

**Issue by ANotThrowawayKonto** [clsid2/mpc-hc#868]
It would be nice if the status bar is able to import current world time from Windows / use internal clock as an option.
This would make checking current time as simple as dragging the mouse on the status bar in full screen compared to minimized/windowed mode and pausing video playback to check current time.

**Comment by clsid2** [comment]
You can press Ctrl+I to show time in the OSD.

Otherwise buy a clock, watch, or phone.

**Comment by ANotThrowawayKonto** [comment]
I tried Ctrl + I, however it only shows the playback time on the OSD.

Is it possible to modify the code to show world time as an option, as for some use cases it will be inconvenient having to reach out for another screen e.g. watching a movie in the dark, etc.? Thank you for the swift reply.

**Comment by clsid2** [comment]
I am not adding any new options or features.
