### ISSUE TITLE
Paused file resumes when clicking a Windows 10 notification

### ISSUE THREAD

**Issue by JakobTischler** [clsid2/mpc-hc#87]
Using MPC-HC 1.8.5 x64 on Win10 Pro x64

When I have an open MPC window with a paused file, clicking _any_ Windows notification (be it clicking it directly, closing it, clicking an action button, just anything) makes MPC resume playback. If I have two MPC windows open, each with a paused file, only _one of them_ gets unpaused. I can't make out any pattern as to which one takes preference over the other. This problem has existed since at least 1.7.13.

Can anyone confirm this, and does anyone have any ideas? TIA.

**Comment by clsid2** [comment]
Options > Player > keys > uncheck "Global media keys"

It is Windows which is sending a play/pause event. Very annoying feature.

**Comment by JakobTischler** [comment]
Oh boy, never would have guessed that's what that meant. Thank you very much for the quick answer.
