### ISSUE TITLE
About OSD Feature

### ISSUE THREAD

**Issue by NightSharp** [clsid2/mpc-hc#873]
I remember one old version of MPC-HC, which has an OSD like this:
When playing any video files, sometime we need jump forward or backward.
And on the top-left corner will show "current time/total time (percentage %)".
Howerver, in recent versions, it only show "current time/total time", which don't contain the "percentage %" part.
I hope thie feature can be back, or just tell me how to set options to enable it.

**Comment by lifegpc** [comment]
Yea. adipose developed it in #341 and removed by clsid2 in 95fd617.

**Comment by clsid2** [comment]
It wasn't working properly. If it ever gets added back as an option, then it needs to show the same time string on both OSD and the statusbar.

**Comment by butterw** [comment]
v1.9.3 had it, it was a cool feature. On seek, it would display: 
02:50 /12:43 [22.29%]

**Comment by NightSharp** [comment]
> v1.9.3 had it, it was a cool feature. On seek, it would display: 02:50 /12:43 [22.29%]

Sorry but I can't find it work.
need some other settings?

**Comment by clsid2** [comment]
Right-click on the time in status bar (in v2.1.4).
