### ISSUE TITLE
"View > On Top > While Playing" not taken in account on start

### ISSUE THREAD

**Issue by XinHong** [clsid2/mpc-hc#877]
**How to reproduce**

- Check that MPC-HC has the option View > On Top > While Playing is selected
- Close MPC-HC
- Open an application, like Firefox
- Open a video file
- Click on the Firefox window
- The MPC-HC window has moved behing the Firefox window

But if you select View > On Top > Default then View > On Top > While Playing when a video is already playing, the MPC-HC window stays On Top.

This bug might be related to https://github.com/clsid2/mpc-hc/issues/846#issue-785525843

MPC-HC version:
---------------

Build information:
    Version:            1.9.8 (6281da8a8)
    Compiler:           MSVC v19.26.28806
    Build date:         Oct 24 2020

LAV Filters:
    LAV Splitter:       0.74.1.64
    LAV Video:          0.74.1.64
    LAV Audio:          0.74.1.64
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 10.0 (build 19042)
    Version:            10.0 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz
    GPU:                Intel(R) Iris(R) Plus Graphics 640 (driver version: 27.20.100.9030)

**Comment by adipose** [comment]
If this was caused by the preview window issue, it can be closed.
