### ISSUE TITLE
settings/prefs file

### ISSUE THREAD

**Issue by art-iszt** [clsid2/mpc-hc#881]
would come in handy if all settings/prefs would be saved/stored somewhere, for instance in a file in AppData, or so ?!

*tia*

**Comment by lifegpc** [comment]
It is stored in Registry by default. You can enable `Store settings in .ini file` in player settings to store it in a ini file which located in the program directory.

**Comment by clsid2** [comment]
Settings are stored here:
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC
It is easy to backup/export registry key with regedit.exe

INI file is for portable use.
