### ISSUE TITLE
How do i fix the brightness or lack there of problem?

### ISSUE THREAD

**Issue by VanishingBlaze** [clsid2/mpc-hc#883]
i noticed 1 of my videos is very dark compared to what it looks like on the web and when i adjust it to look like the web version another video i watch get washed out from the brightness.

**Comment by clsid2** [comment]
If it is a HDR video, then install this video renderer and select in in MPC-HC output options:
https://github.com/Aleksoid1978/VideoRenderer/releases

**Comment by VanishingBlaze** [comment]
i don't think the videos are HDR. just got them from youtube and a media share site, both are 720p

**Comment by clsid2** [comment]
It is possible that something is wrong with the file.
Do you have a link?

**Comment by VanishingBlaze** [comment]
https://www.youtube.com/watch?v=ZPzP4EXuay8 this is 1 of the videos. for example if i have the settings to make dark videos view-able like on the web then the view i just linked the characters face (the blush for example) is whited out a lot

**Comment by clsid2** [comment]
That video plays exactly the same as in the web browser here. Colors are normal.
Tip: put [youtube-dl](http://youtube-dl.org/downloads/latest/youtube-dl.exe) in the MPC-HC folder and you can open Youtube links directly in MPC-HC.

Your download tool might be breaking the file. Update it or find a better one.
