### ISSUE TITLE
Fast Seek & Preview

### ISSUE THREAD

**Issue by vindyvalentine** [clsid2/mpc-hc#885]
Fast seek & preview not showing in the latest build (even previous)
![Untitled](https://user-images.githubusercontent.com/26200511/107466817-ae1c6280-6b9f-11eb-972e-354cb055a99e.png)

**Comment by NanaMizukiAnother7** [comment]
It _works_ for me:

![MPC-HC 1 9 9 PFA](https://user-images.githubusercontent.com/78664512/107469239-f6d21c80-6b9b-11eb-9ac1-fce277e5ef41.png)

Did you reset your settings on Media Player Classic - Home Cinema?

**Comment by ale5000-git** [comment]
@vindyvalentine: It should be enabled in the setting and it work only for local files.

**Comment by clsid2** [comment]
It also only works for files that have keyframe information for fast seeking. So it may for example not work for WMV files.

**Comment by vindyvalentine** [comment]
Okay, i have reset my setting, and yeah it still not work
![image](https://user-images.githubusercontent.com/26200511/107600320-5a248300-6c5e-11eb-8cad-99ae533d42bf.png)

**Comment by vindyvalentine** [comment]
Ah okay, my bad. After reinstall it, it works like a charm
