### ISSUE TITLE
Seek is enabled but it doesn't work in MPC-HC

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#886]
URL: http://www.geekymedia.com/media/UC_Irvine_HFD_2003_high.wmv

Seek is enabled but it doesn't work in MPC-HC.
Works fine in Windows Media Player.

Filters currently loaded:
  - Internal Audio Renderer
  - MPC Video Renderer
  - Audio Switcher
  - LAV Video Decoder (internal)
  - LAV Audio Decoder (internal)
  - LAV Splitter Source (internal)

**Comment by clsid2** [comment]
Seek works fine here with same filters. Both streaming and downloaded.

If you mean seek preview, then that is because keyframes are not exported by the splitter for wmv files.

**Comment by ale5000-git** [comment]
Strange, it now works also for me.
Probably it was a server issue.
