### ISSUE TITLE
Problems with handling private or deleted videos from Youtube playlists

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#887]
So I wanted to load a youtube playlist to mpc-hc. I grab the youtube playlist url and paste it in open file.
You can use this for example:
https://www.youtube.com/playlist?list=PLDC0A896AF5B3728F
![image](https://user-images.githubusercontent.com/26070892/107559189-a7a7de00-6bd3-11eb-9684-7535fe29122d.png)
![image](https://user-images.githubusercontent.com/26070892/107559336-dde55d80-6bd3-11eb-8935-c962c03adee9.png)
![image](https://user-images.githubusercontent.com/26070892/107559429-fc4b5900-6bd3-11eb-8d86-19a96e865425.png)
It give me errors that some videos are deleted, and other are private so I can't acess them
I was thinking originally, that this is not a bug. But wouldn't be nice if the program handled these errors and just delete them from the playlist?

PS: I am not a frequent user of Github, so I didn't know if I should post this on the issues Tab. And a quick message: I was a big user of VLC for the entire of my life, but after weighing the pros and cons, I feel that for my personal usage mpc-hc is so much better than vlc. Congratulations and keep up the good work

**Comment by clsid2** [comment]
I will have a look at this later.

**Comment by clsid2** [comment]
Fixed
