### ISSUE TITLE
File Menu cause Not Responding

### ISSUE THREAD

**Issue by vindyvalentine** [clsid2/mpc-hc#889]
When right click, then hover the mouse to the File section, MPC HC becoming not responding. It happen only the first time doing it on application start. After that not responding, when selection the File section, it was normal again. Any reason why it becoming not responding ? Even when the recent play was nothing (After reinstall them it still happen)

**Comment by clsid2** [comment]
It checks if a disc is present in your CD/DVD/Bluray drive. That normally does not cause any delays, but it some rare cases it can hang the menu for a while.

Solution:
Options > player > disable "open disc" menu
