### ISSUE TITLE
Seemingly random stutter

### ISSUE THREAD

**Issue by BreakPoints** [clsid2/mpc-hc#89]
I recently bought a 1440p 144Hz monitor (moving from 1080p 120Hz) and have been experiencing random short cases of stuttering since. The file resolution doesn't seem to make a difference and it isn't at any particular point in any video file.

I'm running MPC-HC 1.8.6 and my specs are as follows:
Nvidia GTX 980
Intel i7 9700k
32GB of DDR4 RAM @ 3200 MHz
Windows 10 Build 17763.404 (most recent at the time of writing)

Bellow is a screenshot of the Ctrl+J graph during one of these stuttering/freezing episodes.

![MPC Stutter](https://user-images.githubusercontent.com/11966090/55562432-ce4d8180-56eb-11e9-8af4-19a1a924aebd.PNG)

**Comment by clsid2** [comment]
Some of the recent NVIDIA drivers have stuttering issues. Version 418.91 works ok for most people.

Here is an optimized NVIDIA settings profile for MPC-HC:
https://www.sendspace.com/file/ohoudl

**Comment by BreakPoints** [comment]
Thanks for pointing me to the optimised settings, I've applied them and haven't noticed the stuttering yet but I also haven't been watching many videos. Has the bug been reported to Nvidia?

**Comment by clsid2** [comment]
You can report NVIDIA bugs here:
https://forums.geforce.com/default/board/33/

**Comment by BreakPoints** [comment]
So it hasn't. I'll have to create an account and report it at some point then.
