### ISSUE TITLE
Provide option to completely disable windows always on top function

### ISSUE THREAD

**Issue by aliencaocao** [clsid2/mpc-hc#892]
It's very annoying to me when I try to open another window while playing a video and that window gets hidden and I do not even know if it's already opened. A typical case this happens is when I'm setting the script location for Avisynth filter that I use. I cannot find any options so far in the latest v1.9.9 that allows me to disable window always on top feature no matter what case. Currently, the most I can do is choose the "only when playing video" which is still not enough for me. Please consider adding this feature.

**Comment by clsid2** [comment]
Use "Default" setting. Then it is disabled and it should behave like any other window.

**Comment by aliencaocao** [comment]
Default doesnt work in full screen mode, else I wont be asking here

**Comment by clsid2** [comment]
Works for me in fullscreen on Windows 7. I can alt+tab, open Explorer (Ctrl+E) or Start menu without issues.

So either it is a bug in Windows, or you have enabled exclusive fullscreen in the video renderer.

**Comment by ale5000-git** [comment]
I confirm it works also in Windows 10, only when the MPC-HC UI freeze it is strangely kept always on top making Alt+Tab useless.

**Comment by aliencaocao** [comment]
I'm using the default EVR video renderer with D3D full screen disabled and no external filters enabled, and I'm not asking for alt tab function. What I'm referring to is a dialogue box that mpchc opens up. In full screen mode and playing any video, the dialogue box will be opened but hidden. I have to use the task bar window preview to close the opened dialogue box else I have no way of closing it. 
The specific use case I'm dealing with is choosing the script path for an external avisynth filter. You can install it and have a try yourself. I don't think its a windows bug as I can reproduce this in 2 other windows computers.
The filter download link: [https://github.com/CrendKing/avisynth_filter/releases/tag/v0.9.1]
once installed, add it to external filters. Don't need to enable it. Double click on the filter in the list after you added it, and a pop up window will appear. There is a browse button in that window that opens a system file picker for you to pick the script. That file picker is the one that gets blocked.

**Comment by clsid2** [comment]
That file picker dialog is controlled by that filter, not by the player.
