### ISSUE TITLE
Mouse not hidden with Miracast

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#893]
On Windows 10 select to duplicate screen with Miracast on a Samsung TV.
Now open a video in fullscreen.
When the mouse is still then it correctly disappear on PC but it remains visible in the TV.

**Comment by clsid2** [comment]
Probably a bug in Windows.

**Comment by ale5000-git** [comment]
I have submitted a bug report for Windows, I hope they fix it in this life :)
