### ISSUE TITLE
"Save a Copy..." on streamings

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#894]
This open a window but at the end the window disappear immediately so you have no way to see WARNINGS/ERRORS.

Could you please add a "Press any key to continue.." at the end or something similar?

**Comment by clsid2** [comment]
Not possible. It simply starts a run youtube.dl.exe process. That way you can safely close the player without interruption the download. I don't see any command line options to make it pause at the end.

I am not interested in making workarounds for this.

**Comment by clsid2** [comment]
You can try adding `--exec pause` to the command line parameters in advanced options. That works here for pausing after download. I don't know if it also works in case of error. Please test that and I may add it to the default command.

**Comment by ale5000-git** [comment]
What is the default command-line for youtube-dl download if the advanced option isn't specified?

**Comment by clsid2** [comment]
youtube-dl.exe --console-title "URL" -o "FILENAME"

**Comment by ale5000-git** [comment]
`--exec pause` doesn't work in case of errors like `ERROR: requested format not available`.

PS: I have found [this](https://stackoverflow.com/a/30613614):
> CreateProcess is only responsible for spawning / creating the sub-process which is successful, therefore it returns TRUE. It's your code's responsibility to monitor the sub-process and when it ends to get its exit code. Do that by calling [MS.Docs]: GetExitCodeProcess function before closing its handle:
> 
> GetExitCodeProcess(pi.hProcess, &ec);

**Comment by ale5000-git** [comment]
I have also made a feature request on youtube-dl for the pause option: https://github.com/ytdl-org/youtube-dl/issues/28148

**Comment by ale5000-git** [comment]
@clsid2
From command-line I have found two alterantive ways to prevent console from closing (even in case of errors) but they can't be used from MPC-HC options:
1) `youtube-dl ... --exec pause || pause` (the first pause is executed when the script is successful, the second when it fails)
2) `cmd /K youtube-dl ...`

There is a possibility to add something like these in advanced settings of MPC-HC please?

**Comment by clsid2** [comment]
Use one of the many GUIs for youtube-dl if you want more options. I am not going to add all kinds of extra advanced options.
