### ISSUE TITLE
[Request] Remove seek preview when scrubbing (dragging seek)

### ISSUE THREAD

**Issue by BreakPoints** [clsid2/mpc-hc#895]
The seek preview is a great new piece of functionality but when scrubbing through a video file by dragging the seek pip, it creates redundant information that overlaps the main view.

Furthermore when dragging the seek pip and drifting the mouse cursor above or bellow the seek bar, the seek continues to work in the main view but the preview is stuck on the last preview frame from when the mouse was within the seek bar which is no longer valid.

**Comment by clsid2** [comment]
@adipose

**Comment by adipose** [comment]
Seems reasonable to hide when dragging.  It would fix the other issue, but I'm not sure why it's not getting triggered in that case (likely because the scroll messages are sent rather than a mouse pos change).

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/917
