### ISSUE TITLE
Save Thumbnails... on streamings set the wrong file name

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#899]
`Save Thumbnails...` on streamings set the wrong file name (inside the image), see:
![Luna - Baila (Official Video) ft  Kayler (youtube com_watch_v=Gug_00DIkic)_thumbs](https://user-images.githubusercontent.com/15793015/107816132-9b0ebb80-6d74-11eb-831a-4431140e5149.jpg)

**Comment by ale5000-git** [comment]
Instead of File Name I think title and url would be more appropriate.

**Comment by lifegpc** [comment]
I think if video file is a URL, use Title instead of File Name.
If video file is a normal file, add an option to display Title.

**Comment by clsid2** [comment]
It should show URL.
I don't want option to show title instead of filename.

**Comment by lifegpc** [comment]
#902

**Comment by ale5000-git** [comment]
I'm just wondering, it is an image so space is unlimited so why not show both on 2 separate lines (for both local files and streamings)?

**Comment by lifegpc** [comment]
It use ASS subtitle renderer to render that infomation. I think it will break that line automatically.

**Comment by clsid2** [comment]
But does it also move down the rest when a line is broken?
