### ISSUE TITLE
can't open ProRes 4444XQ

### ISSUE THREAD

**Issue by igitlin** [clsid2/mpc-hc#900]
can't open ProRes 4444XQ

**Comment by NanaMizukiAnother7** [comment]
What your ProRes video file do? You should look its video data on MediaInfo.

**Comment by clsid2** [comment]
Can't do anything without a sample file.

**Comment by igitlin** [comment]
sory,
mediainfo:
`Format                                   : MPEG-4
Format profile                           : QuickTime
Codec ID                                 : qt   2005.03 (qt  )
File size                                : 47.4 GiB
Duration                                 : 5 min 15 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 1 292 Mb/s
Encoded date                             : UTC 2021-01-16 20:54:05
Tagged date                              : UTC 2021-01-16 20:54:05
Writing library                          : Apple QuickTime

Video
ID                                       : 1
Format                                   : ProRes
Format version                           : Version 1
Format profile                           : 4444 XQ
HDR format                               : SMPTE ST 2086, HDR10 compatible
Codec ID                                 : ap4x
Duration                                 : 5 min 15 s
Bit rate mode                            : Variable
Bit rate                                 : 1 278 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:4:4
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 6.422
Stream size                              : 46.9 GiB (99%)
Writing library                          : afl0
Language                                 : English
Encoded date                             : UTC 2021-01-16 20:54:05
Tagged date                              : UTC 2021-01-16 20:54:05
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1000 cd/m2
Maximum Frame-Average Light Level        : 400 cd/m2
`
Lav spletter:
`LAV Splitter Source (internal)::Video

Media Type 0:
--------------------------
Video: AP4X 3840x2160 24fps 1336790kbps

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Video {73646976-0000-0010-8000-00AA00389B71}
subtype: Unknown GUID Name {78347061-0000-0010-8000-00AA00389B71}
formattype: FORMAT_VideoInfo {05589F80-C356-11CE-BF01-00AA0055595A}
bFixedSizeSamples: 0
bTemporalCompression: 1
lSampleSize: 1
cbFormat: 88

VIDEOINFOHEADER:
rcSource: (0,0)-(3840,2160)
rcTarget: (0,0)-(3840,2160)
dwBitRate: 1336790188
dwBitErrorRate: 0
AvgTimePerFrame: 416667

BITMAPINFOHEADER:
biSize: 40
biWidth: 3840
biHeight: 2160
biPlanes: 1
biBitCount: 24
biCompression: ap4x
biSizeImage: 24883200
biXPelsPerMeter: 0
biYPelsPerMeter: 0
biClrUsed: 0
biClrImportant: 0

pbFormat:
0000: 00 00 00 00 00 00 00 00 00 0f 00 00 70 08 00 00 ............p...
0010: 00 00 00 00 00 00 00 00 00 0f 00 00 70 08 00 00 ............p...
0020: ac cc ad 4f 00 00 00 00 9b 5b 06 00 00 00 00 00 ¬Ì­O....[......
0030: 28 00 00 00 00 0f 00 00 70 08 00 00 01 00 18 00 (.......p.......
0040: 61 70 34 78 00 b0 7b 01 00 00 00 00 00 00 00 00 ap4x.°{.........
0050: 00 00 00 00 00 00 00 00                         ........`
sample: https://yadi.sk/i/d8kCjFCCx0vRJQ

**Comment by clsid2** [comment]
Install K-Lite Codec Pack. That is able to play this file. It supports a few more mediatypes than vanilla MPC-HC/LAVFilters.

**Comment by igitlin** [comment]
> 
> 
> Install K-Lite Codec Pack. That is able to play this file. It supports a few more mediatypes than vanilla MPC-HC/LAVFilters.

no, thanks, I will not litter the system with codec packs - my computer is used for work and it is important for me that there is no garbage in the form of K-light, which then cannot be removed without reinstalling the system.
MPC-HC normally shows ProRes 422, 422HQ, 4444, only 444XQ does not.
MPC-BE shows 444XQ, but it takes a very long time to open large MOV files - about 0.5-1.5 minutes.

**Comment by clsid2** [comment]
Removing K-Lite does not require a re-install of your system. Complete utter nonsense.

You can submit a request to LAV Filters to add support for FourCC "ap4x".

**Comment by igitlin** [comment]
> Removing K-Lite does not require a re-install of your system. Complete utter nonsense.

I had a sad experience with K-Lite - when I got a bunch of problems in the programs in which I work, a simple uninstall did not help, I had to completely reinstall the system. After that, I never install any codec packs and prefer programs that do not embed their codecs into the system, but store them in their portable folder.

**Comment by clsid2** [comment]
If uninstall did not help, then your problem was likely caused by something else. People always blame all their issues on codecs, while in reality 99% of problems are caused by other factors such as buggy drivers. Sadly, few people make proper bug reports, giving developers the chance to identify the real cause.

K-Lite also has an option to install the codecs only for MPC-HC instead of registering them system-wide.
