### ISSUE TITLE
Change the time location in the preview

### ISSUE THREAD

**Issue by demolitioner** [clsid2/mpc-hc#901]
The preview time is located at the top (1 in the picture). But so the time is not so quickly available to the eyes when searching with the mouse than if it was located at the bottom (2 in the picture). The eyes must be moved up all the time after search to observe time.
I also offer an additional option for displaying a preview (3 in the picture), providing a quickly accessible display of time and reducing the size of the preview.
![preview](https://user-images.githubusercontent.com/68711737/107833680-15573400-6da5-11eb-8525-6e30b1cc66f5.png)

**Comment by clsid2** [comment]
It would be fine with me if position is changed to below the video. I would like to avoid more options.

**Comment by adipose** [comment]
Putting it below isn't hard.  Not sure which is preferred by the average user, but MPC-BE has it above, which is where I left it.
