### ISSUE TITLE
Micro-freezes when OSD is on

### ISSUE THREAD

**Issue by xl743** [clsid2/mpc-hc#903]
It's a long standing bug I'd like to report. If OSD: Display Current Time (Ctrl + I hotkey) is on, there are 2 micro-freezes every second occurring. They are very noticeable on a long panning shots/credit titles or so. They are also seen if chart (Ctrl + J) is on. Please take a look at the screenshot attached:

![MPC-HC](https://user-images.githubusercontent.com/11822541/107837021-d676ad80-6da7-11eb-8590-cc6c714543fe.png)

You can see those spikes, occurring 2 times every second.

I can see this bug on every device I tried it (about a dozen of PCs) regardless of the player configuration, including default configuration.

The only thing tempts me switching to another player.

**Comment by clsid2** [comment]
Does not happen here.

Try setting your refreshrate to 59 Hz (=59.94)

**Comment by xl743** [comment]
This screenshot is made with my laptop, where 60 and 40 Hz are only options available, but the issue occurs with all the devices I tried, including 59.94 monitors.

Forgot to add. The issue disappears with madVR renderer (installed separately). But it persists with EVR*/VMR* renderers.
