### ISSUE TITLE
[Request] Show video and audio codecs on the thumbnail image.

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [clsid2/mpc-hc#904]
I have lots of AVI files and I'm going to take a thumbnail image for these. Thanks.

**Comment by cw2** [comment]
How about something like this (click the image for the original/full size):
![mkv_thumbs](https://user-images.githubusercontent.com/10730406/131641180-3217a9f6-c894-451d-972c-57008a98a81e.png)
I did not want to change the number of lines, so I moved Duration up to make space for the A/V codecs information.

**Comment by ale5000-git** [comment]
I think you can remove Resolution since it is already inside Video.

**Comment by cw2** [comment]
How about this?
![mkv_thumbs2](https://user-images.githubusercontent.com/10730406/131679238-5330c2da-c6d8-46a2-ab3d-d1580b59f033.png)

Note: There appears to be enough room in the bottom area of the Save Thumbnails dialog for possible customization of those four lines, e.g. there could be some kind of replacement strings like

Line 1: `File Name: %FileName%`
Line 2: `File Size: %FileSizeFormatted% (%FileSize%), Duration %DurationHMS%`
Line 3: `Video: %VideoInfo%`
Line 4: `Audio: %AudioInfo%`

**Comment by cw2** [comment]
Hm, I forgot about localization, it would complicate things a little bit...

**Comment by ale5000-git** [comment]
Like this?
```
Line 1: %FileNameOrTitleLabel%: %FileNameOrTitle%
Line 2: %FileSizeLabel%: %FileSizeFormatted% (%FileSize%), %DurationLabel%: %DurationHMS%
Line 3: %VideoInfoLabel%: %VideoInfo%
Line 4: %AudioInfoLabel%: %AudioInfo%
```

PS: Please check also the behaviour on streamings if you look at it.

**Comment by NanaMizukiAnother7** [comment]
> Like this?
> 
> ```
> Line 1: %FileNameOrTitleLabel%: %FileNameOrTitle%
> Line 2: %FileSizeLabel%: %FileSizeFormatted% (%FileSize%), %DurationLabel%: %DurationHMS%
> Line 3: %VideoInfoLabel%: %VideoInfo%
> Line 4: %AudioInfoLabel%: %AudioInfo%
> ```
> 
> PS: Please check also the behaviour on streamings if you look at it.

Really good!

**Comment by NanaMizukiAnother7** [comment]
Close this, clsid2.
