### ISSUE TITLE
'File -> Subtitles -> Load Subtitles' not working when using XySubFilter as the subtitle renderer

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#906]
Bug: 'File -> Subtitles -> Load Subtitles' not working when using XySubFilter as the subtitle renderer

The bug appears when 
1. XySubFilter is added in 'Options -> External Filters' and it is set to Prefer
2. In 'Options -> Playback -> Output', set XySubFilter as Subtitle Renderer
3. Play a video with built-in subtitle track(s) or play any video with the setting 'XySubFilter Settings -> Main -> loading' set to Always load (Only in the both ways can XySubFilter be actually used as the subtitle renderer, or the internal subtitle renderer will be used actually)
4. load a subtitle file using 'File -> Subtitles -> Load Subtitles', then there will be no subtitle loaded successfully

However, a subtitle file can be successfully loaded using  the following method:
1. Click 'XySubFilter Settings -> Main -> open'
2. Choose a subtitle file

This bug does exist in the final version on MPC-HC offcial website (1.7.13)

**Comment by clsid2** [comment]
Not a bug. The internal subtitle functionality only works with the internal subtitle renderer.

There already is another issue with feature request to also support XySubFilter.

If you give the subtitle file same name as the video, then it will be loaded automatically, and you don't need to load it manually at all.
