### ISSUE TITLE
Problems with building / compilation guide is not accurate

### ISSUE THREAD

**Issue by zoidbergthepopularone** [clsid2/mpc-hc#907]
Hi! Since my MPC-HC build environment stopped working (see step 3 below) with version 6.9.9 (but worked fine with 6.9.8), I decided to create a new one from scratch, based on the most current compiler toolchain available and the most recent clone of the repository (there have been issues with submodules being added or their address changed in the past). In doing so, I noticed the following problems:

1) DirectX SDK is no longer available from https://go.microsoft.com/fwlink/?LinkID=71193. I installed a version that I had downloaded before for the older versions of MPC-HC, but that is not an option for a new developer. It would be best if the documentation listed the current location of the SDK.

2) The documentation says to save the mingw package to `C:\msys64\mingw64`, which was, however, already populated by MSYS. The older version of the documentation (and the `build.user.bat` file) suggested `C:\msys64\mingw`, which did not exist.  It would probably be a good idea to specifically mention that either the directory should be deleted first or that it's OK to overwrite the existing files.

3) When trying to build the project (both from the command line using `build.bat x86` and from the GUI using the solution file), I get an error while compiling libass:
```
  YASM: Assembling be_blur.asm
  YASM: Assembling blend_bitmaps.asm
C:\Source\src\yasm.targets(45,5): error MSB3721: Příkaz yasm.exe -X vc -f win32  -D HAVE_CPUNOP=0 -D PREFIX -D WIN32=1 -D ARCH_X86_64=0 -D HAVE_ALIGNED_STACK=0 -D _CRT_SECURE_NO_DEPRECATE -D _CRT_NONSTDC_NO_DEPRECATE -D _CRT_SECURE_NO_WARNINGS -I "libass\libass" -o "C:\Source\bin\obj\Release_Win32\libass\blend_bitmaps.obj" "C:\Source\src\thirdparty\libass\libass\libass\x86\blend_bitmaps.asm" byl ukončen s kódem 1. [C:\Source\src\thirdparty\libass\libass.vcxproj]
```
It seems to be a case of incorrect working directory, because if I run the failing command from any directory other than `src\thirdparty\libass`, I get an errorlevel 1 with error `yasm: FATAL: unable to open include file `x86/x86inc.asm'` while I get a successful compile if I run the command from `src\thirdparty\libass`.

What *did* work for me was to try to build MPC-HC by using `build x86`, when that failed go to the libass directory and `msbuild libass.vcxproj` and then go back and `build x86` again - which may be why you never noticed the problem, because you had already built the necessary part of libass. But it does not work if you start with a clean environment.

4) During build, I got an error that file `src\mpc-hc\res\mpc-hc.exe.manifest` does not exist. I copied the `mpc-hc.exe.manifest.conf` file to that name which allowed me to complete the build, but I suspect this is another problem in the build process.

**Comment by zoidbergthepopularone** [comment]
Problem #3 can also be resolved by copying YASM to a directory which is in the PATH. So either mark the C.7 step from Compilation.md as required or change the D step to read "copy YASM to a directory in PATH".

**Comment by clsid2** [comment]
Instructions have been updated.
