### ISSUE TITLE
Resurrect Standalone Filters build?

### ISSUE THREAD

**Issue by pa3pyx** [clsid2/mpc-hc#912]
Ever since the original repo development stopped and the project was picked up by clsid2, there have been no Standalone Filters builds updates published. However, commit history indicates that there have been multiple updates to the filters since then. Could Standalone Filters again be published as part of the release process? A brief look at the repository seems to indicate that the make files are still there.
The primary use case for this (for me) is adding CD Audio support to other DirectShow-enabled players (whose native CDDA support is either non-existent or substandard -- e.g. Winamp/WACUP) with CDDAReader.ax, or ripping CD audio in plain old GraphEdit in combination with WavDest.ax. :)

**Comment by clsid2** [comment]
I am not interested in spending time on that. There have not been any significant changes to those filters either.

**Comment by pa3pyx** [comment]
@clsid2 What's the current release process/what CI/CD system is used to publish the build artifacts (if any)? Is https://github.com/clsid2/mpc-hc/blob/1cde499f9bf3378661f30e03e2a68b16bdc5576f/docs/Release.md no longer followed? Because it instructs to build the `All` target, which according to https://github.com/clsid2/mpc-hc/blob/1cde499f9bf3378661f30e03e2a68b16bdc5576f/build.bat, does still include the standalone filters build (https://github.com/clsid2/mpc-hc/blob/1cde499f9bf3378661f30e03e2a68b16bdc5576f/build.bat#L170). I can only assume that, since filters are no longer built/published, this target broke at some point and doesn't build anymore. So if I fix that and submit a PR with the fix, then can they be included in releases again?

**Comment by lifegpc** [comment]
Why not go to the [origin repo](https://github.com/Nevcairiel/LAVFilters) of LAV Filters to build?

**Comment by clsid2** [comment]
The release process that I use only involves MPC-HC. And as I have already said, that is not going to change.

There have not been any improvements to ancient filters such as CDDAReader and Wavdest. You can continue to use the existing ones you already have.

**Comment by pa3pyx** [comment]
Perhaps I better use standalone filters from MPC-BE then; apparently, that fork of MPC never switched to LAV Filters, so it appears they not only still release the old-school MPC filters, but still maintain them (even though their changes look to be mostly refactoring as well).
@lifegpc I'd be happy to use LAV Filters for everything, but the problem is they are not quite universal -- the most glaring omissions being CD Audio and DVD/CSS Video source support. While the latter is handled mostly fine by Microsoft's DVD Navigator (qdvd.dll), which both MPC-HC and MPC-BE normally rely on, the former requires a third-party filter to support via DirectShow.
