### ISSUE TITLE
Blank window if I increase size/width/height in Pan&Scan menu.

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#918]
Move Left and Move Up also have this issue. But Move Right and Move Down works fine.
![image](https://user-images.githubusercontent.com/41434272/108142237-58483d00-7100-11eb-9f0b-c284e84d29f6.png)
Seems issue releated to MPC-VR. I test with EVR-CP and madVR, works fine with that renderer.
Filters currently loaded:
  - Internal Audio Renderer
  - MPC Video Renderer
  - Audio Switcher
  - LAV Video Decoder (internal)
  - LAV Audio Decoder (internal)
  - LAV Splitter Source (internal)

![image](https://user-images.githubusercontent.com/41434272/108142420-b2e19900-7100-11eb-9137-9c3b37effb55.png)

**Comment by clsid2** [comment]
That is fixed in MPCVR 0.5.3.1640

**Comment by lifegpc** [comment]
After update MPC-VR's version, works fine now.
