### ISSUE TITLE
Audio not playing with ProRes 16ch audio files

### ISSUE THREAD

**Issue by sarek9** [clsid2/mpc-hc#92]
When opening Apple ProRes files containing 16ch of audio a DirectShow warning is displayed and no audio is rendered. Audio is, to my experience, usually contained in the first two tracks though. These files are surprisingly common when receiving files from someone that has edited them in Final Cut and made a miss in the export. As an FYI, VirtualDub2 plays these fine with audio.

Sample movie attached (audio is just low frequency hum in this file).

[16ch sample.zip](https://github.com/clsid2/mpc-hc/files/3060760/16ch.sample.zip)

**Comment by clsid2** [comment]
Plays OK with the internal audio renderer.
options > playback > output

The DirectShow error means that the default audio renderer doesn't support that specific input.

**Comment by sarek9** [comment]
Yes you're correct, my bad. I forgot I was overriding the graph so it's on my side the problem lies. Sorry for the false report.

Thanks for picking up development of MPC-HC btw, big thanks!
