### ISSUE TITLE
Snapshot Subtitles option doesn't work

### ISSUE THREAD

**Issue by emperor06** [clsid2/mpc-hc#920]
Version: MPC-HC 1.9.9.4 (bf6dee937) Feb 12 2021
When I set the option "Snapshot Subtitles = false" and take a screenshot (default hotkey alt+i), the subtitles are still included on the screenshot. The subtitle is softsub (ass).

**Comment by clsid2** [comment]
Are you using madVR as video renderer? That uses its own settings for taking screenshots.

The option also only works when using the internal subtitle renderer. It doesn't work if you use VSFilter.

**Comment by emperor06** [comment]
Indeed, I'm using madVR. I tested with MPC renderer just in case but I didn't know I had to restart the player (clicking on "apply" is not enough). So that's a madVR issue then.

**Comment by clsid2** [comment]
madvr settings > rendering > screenshots
