### ISSUE TITLE
'On Top' (all) stops functioning whilst the 'Show preview on seek bar' is turned on

### ISSUE THREAD

**Issue by amd5000** [clsid2/mpc-hc#921]
MPC-HC 1.9.9.20 (and ever since the preview on seek bar option was introduced)
Keeping the player 'On Top' apparently stops functioning whenever the 'Show preview on seek bar' tweak is selected and turned on. 'Always', 'While Playing' & 'While Playing Video'... all do not work. These two options just cannot be selected together.

**Comment by adipose** [comment]
Pretty sure this can never work, given that always on top uses wndTopMost, but the preview window is a WS_POPUP, which means the player cannot be topmost.

So, how do we want to handle this?  Just disable preview entirely if wndTopMost is selected?

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/981/files

**Comment by ale5000-git** [comment]
@adipose: Isn't possible to enable always on top while the preview window is hidden and disable it when the preview is displayed (so switching on/off continuously when needed during playback)?

Another idea from [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/fb4a7d5f-c98b-461f-a527-7d5dd4cd03e6/multiple-topmost-windows):
> I have 2 windows with their Topmost property set to True. However, I want one of them to always be on top of the other. Is there some sort of Z-Indexing for separate windows, or another way to solve this problem?
> 
> One of the windows always refers the user to the other user. The problem was the the second window could have been underneath the first window, and since they are both Topmost=true it didn't show. I solved the problem by calling Activate() on the second window ever time the first window referred to it.

**Comment by clsid2** [comment]
wndTopMost is not always strictly highest in z-order, that is wndTop. Maybe that is reason for the other (non-preview related) "on top" issues.
http://www.icodeguru.com/vc&mfc/mfcreference/html/_mfc_cwnd.3a3a.setwindowpos.htm

I was thinking that after hiding preview, the "On top" state of main window could be re-applied similar to how play/pause would affect "On top (while playing)".

**Comment by adipose** [comment]
Are you sure?

https://devblogs.microsoft.com/oldnewthing/20051121-10/?p=33263

My understanding is topmost is like "super top" and even _top cannot go above a topmost window.

However, in theory, the preview window could also be a topmost window, thus solving our problem...

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/981/files

Tried your idea and it seems to work.
