### ISSUE TITLE
Show speed in status bar when clicking on speed up and slow down buttons

### ISSUE THREAD

**Issue by SuperPat45** [clsid2/mpc-hc#922]
Clicking on speed up and slow down buttons does not show the current speed in status bar unlike other zoom and crop functions.

Having set a low speed step, after clicking many times on these buttons it may be difficult to return to the normal speed without knowing this information.

**Comment by clsid2** [comment]
Options > Advanced > ShowFPSinStatusbar

Menu > Play > Playback rate

**Comment by lifegpc** [comment]
Or open statistics panel.
