### ISSUE TITLE
WebVTT font color

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#926]
https://www.w3.org/TR/webvtt1/#default-text-color

Basic tags could be converted into srt/ssa tags:
`<c.yellow>text</c>`  -> `<font color=yellow>text</font>`

But it should still strip more complex ones if they can't be converted:
`<c.yellow.bg_blue>This is yellow text on a blue background</c>`
`<c.yellow.bg_blue.magenta.bg_black>This is magenta text on a black background</c>`
(basically anything that either contains "bg_" or two dots)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/930

Second example is weird.  I guess it's saying that multiple tags strung together ignore the early tags?  Anyway, I supported the first two options.
