### ISSUE TITLE
x265 10bit red color is brown orange

### ISSUE THREAD

**Issue by taipignas** [clsid2/mpc-hc#928]
Video: HVC1 1920x1080 24fps [V: hevc main 10 L4.0, yuv420p10le, 1920x1080 [default]]

pure clear red becomes brownish orange and rest of the video has this dusty tint.
tested on vlc and the colors are good there

**Comment by clsid2** [comment]
For HDR video you need to install [MPCVR](https://github.com/Aleksoid1978/VideoRenderer/releases) or madVR and select that as video renderer in MPC-HC options.
