### ISSUE TITLE
Program crashes when screen sharing on Discord

### ISSUE THREAD

**Issue by Strombilly** [clsid2/mpc-hc#929]
When I first click "share screen" and choose the program as a window, it will only show in the top left of the share whether it's in full screen or not. When trying to play, pause, resize, or do anything to the window while it's sharing, it freezes and crashes. It happens with multiple video files of different extensions, and the same files don't crash when using a different video file viewer.

**Comment by clsid2** [comment]
Discord settings > Voice & Video > disable "Use our latest technology to capture your screen"
