### ISSUE TITLE
black screen when play 2160P HEVC using DXVA2(native)+MadVR

### ISSUE THREAD

**Issue by wsyonline** [clsid2/mpc-hc#93]
hello 
HW:
I7 6820HK(HD530)+16GB+GTX980M+4K screen
SW:

- HPC-HC 1.8.6 

- MADVR v0.92.17
I know 980M does not support decode 4K HEVC movie. so I use HD530 play movie.
If I only use DXVA2(native), The color of the movie is incorrect. cause of the movie has HDR.
So I must use MADVR.
      but when I use MADVR+DXVA2, there is nothing display, just black screen. 
      if I use MADVR+INTEL QUICKSNYC(Hybrid decoding), the color and display are ok. but the CPU and GPU usage rate will reach 100%. 
anyone knows why use MADVR+DXVA2 will display black screen.

**Comment by clsid2** [comment]
You should use DXVA2 Copy-back or D3D11.

The QuickSync decoder does not support HEVC. So you are actually software decoding now.

The black screen issue is a bug in Madvr. It will be fixed in future version.
