### ISSUE TITLE
Tried to view the old english serie of lost railways

### ISSUE THREAD

**Issue by ubronan** [clsid2/mpc-hc#931]
It seems this TVrips are kinda not liked by the drivers AMD has made
I have no idea why these movies make this heavy crashes.
But its also happening with games and other stuff so no clue why it m ake mpc-hc go nuts so much more
The result is the driver died and then seems to load back but it goes kinda faster now that it happened like 40 times in a row
Anyway sometimes the screen stays completely black or as i said recover in the next 2 situations either it ends up that the player screen stays black completely and i have to restart the movie or it recovers and plays the movie untill i close it or pause it.
When  i later try to play it again the same happens over and over again.
I have upload the smallest version of the episode i received from the guy send me, now onto mega.nz
So if you want i can send a share link if you want of course only after someone send me a request

**Comment by clsid2** [comment]
You can try if disabling hardware acceleration helps to avoid the problem.
Options > Internal Filters > Video Decoder > Hardware decoder to use = None

I can't help with driver problems. Use the AMD bug report tool:
https://www.amd.com/en/support/kb/faq/amdbrt
