### ISSUE TITLE
Subtitle-heavy scenes seem to have trouble rendering (need to pause in order to get the subtitles to appear)

### ISSUE THREAD

**Issue by Reonu** [clsid2/mpc-hc#932]
Example clip (issue happens when the phone screen appears)
https://drive.google.com/file/d/12ePG8kLrhan1k69MXonhcNtKGnb0cA7-/view?usp=sharing

The subtitles will not appear (or appear briefly and then dissapear), and the only way to get them to appear and stay there is to pause the video.

Running a ryzen 5800X + 3070 so it's not a lack of processing power.

Let me know if you need any more info

**Comment by clsid2** [comment]
Working fine here.

Do you have a 4k screen? If so, this might help:
Options > Subtitles > Maximum texture resolution > 1920x1080
Subtitles will be a little bit lower quality, but should improve performance a lot.

**Comment by Reonu** [comment]
My screen is 2560x1440. I tried what you said and it's the same.

I recorded a video of the problem happening: https://streamable.com/3t2doy

**Comment by clsid2** [comment]
Try with "Sub pictures to buffer" = 0

**Comment by Reonu** [comment]
That completely fixed it.

Any side effects to expect from this? If not maybe it should be the default? 

Thanks!

**Comment by clsid2** [comment]
No negative side effects. Buffer can only potentially help to even out peak loads a bit. There is a bug that can cause this flickering issue in some cases. It is high on the todo list to investigate and fix this issue.

Weird thing is that some systems suffer more from this problem than others. It doesn't seem performance related. What is the refreshrate of your screen? Maybe it happens more in high refreshrates.

**Comment by Reonu** [comment]
My refresh rate is 144 Hz so that could be it...

**Comment by clsid2** [comment]
Could you temporary set it to 59 or 60Hz and test if the flickering is less severe then? Knowing if it does could help with solving the bug.

**Comment by Reonu** [comment]
Nope, same exact problem at 60 Hz if the buffer thingy is set to 10.

**Comment by MadokaAyukawa** [comment]
I get this with my laptop with integrated Intel GPU and refresh at 60 Hz. Win 10. Setting to 0 does "fix" the issue.

**Comment by clsid2** [comment]
Please test 1.9.9.45 development build. The queue should work better now.

**Comment by MadokaAyukawa** [comment]
Is there a zip version of .45?

**Comment by clsid2** [comment]
Zip has been added.

**Comment by Reonu** [comment]
> 
> 
> Please test 1.9.9.45 development build. The queue should work better now.

Same exact issue, no change at all :(

**Comment by Reonu** [comment]
Disregard the comment I deleted, I accidentaly opened the old build instead of the new one.

Yeah, the new build works much better

**Comment by MadokaAyukawa** [comment]
The new build works well in windowed mode. But in fullscreen mode, the overlay on the phone works with the first line on the bottom of the screen, when it changes, the overlap goes away and the second line is not displayed. This is with the buffer > 0.

**Comment by Reonu** [comment]
> 
> 
> The new build works well in windowed mode. But in fullscreen mode, the overlay one the phone works with the first line on the bottom of the screen, when it changes, the overlap goes away and the second line is not displayed. This is with the buffer > 0.

Yep, this is true. I didn't try fullscreen mode earlier. I just did now and it doesn't work properly. It only looks ok in windowed mode with the new build.

**Comment by clsid2** [comment]
It can still skip a sub if it isn't rendered fast enough.

Does fullscreen work good with buffer = 0 ?

**Comment by Reonu** [comment]
> Does fullscreen work good with buffer = 0 ?

It doesn't glitch out or anything, but it looks laggy, as if it was struggling to render everything. I just checked the stable version and it happens there too with buffer = 0, I just hadn't noticed before!

In windowed mode, there's no lag in either build.

**Comment by MadokaAyukawa** [comment]
Fullscreen renders all lines as expected with buffer = 0. I'm not sure I noticed any lag or not.

**Comment by clsid2** [comment]
Without buffer the video may lag a bit, while with buffering it will skip the subtitle if it is too slow.

Is it good in fullscreen if you reduce the "maximum texture resolution" with buffer > 0?

**Comment by MadokaAyukawa** [comment]
If I set max texture resolution to 900 in fullscreen and buffer > 0, it works fine.  It fails at any resolution > 900.

**Comment by Reonu** [comment]
> 
> 
> Without buffer the video may lag a bit, while with buffering it will skip the subtitle if it is too slow.
> 
> Is it good in fullscreen if you reduce the "maximum texture resolution" with buffer > 0?

Yep reducing the resolution makes it not laggy

**Comment by clsid2** [comment]
I am probably going to disable the buffer by default in next release.

I also have some ideas to dynamically adjust the texture size based on the rendering performance. Hopefully I find some time and motivation to look into that soon.
