### ISSUE TITLE
Request - Allow Added video preview functionality to the seekbar with remote locations

### ISSUE THREAD

**Issue by NaruZosa** [clsid2/mpc-hc#937]
Could you please allow the video preview functionality to be enabled for remote locations, possibly with a whitelist of locations.

This would be useful for instances where a user stores their media on a local NAS, where read times are not an issue even though it is a remote location.

**Comment by clsid2** [comment]
An UNC path does not count as a remote location in this context. The player only considers URLs are remote.

**Comment by NaruZosa** [comment]
Great! Would it be possible to still whitelist particular URLs, such as in the case of a remote NAS or remote server controlled by the user, as in many of these cases bandwidth still shouldn't pose an issue?

**Comment by ale5000-git** [comment]
Have you tried?

If you access NAS in a normal way (via SMB, which use port 445) preview works, like these:
`\\nas-name\nas-folder\video-name.mkv`
`\\nas-ip\nas-folder\video-name.mkv`

Or do you mean access it via FTP?

**Comment by NaruZosa** [comment]
Not sure why, but it didn't work for me previously. I can confirm it now does, not sure what changed.

I'll just put it down to user error.


Thanks for adding the thumbnail functionality, it's great to have :)
