### ISSUE TITLE
Thumbnails no longer present

### ISSUE THREAD

**Issue by Fanatiikon** [clsid2/mpc-hc#938]
It seems that recently i no longer have thumbnails for .mkv files. I've tried reinstalling and downgrading with no luck.
![image](https://user-images.githubusercontent.com/76494177/108995263-7b955e00-76a5-11eb-9edb-ab0c6819c9bd.png)
![image](https://user-images.githubusercontent.com/76494177/108995300-88b24d00-76a5-11eb-8780-23eac67fc01d.png)

**Comment by Fanatiikon** [comment]
Update: It doesnt't seem that it's all .mkv files as some of them work just fine.

**Comment by clsid2** [comment]
The player is not involved at all in the process of creating thumbnails! That is done by Explorer itself.

It looks like you are using the standard thumbnail shell extension from Windows. You should install the [HEVC Media Foundation ](http://codecguide.com/media_foundation_codecs.htm) codec.

Alternatively, you can install [Icaros](https://m.majorgeeks.com/files/details/icaros.html) thumbnail shell extension. That works much better than the standard thumbnailer from Windows and supports more video formats.
