### ISSUE TITLE
ToDo: improvements for subpic texture resolution

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#939]
- ~~Reduce the number of options. The tiny resolutions are obsolete.~~
- ~~Remove the Desktop and Video size options. 4k desktop can give crap performance.~~
- ~~Change default to something more reasonable such as 1920x1200. This is already difficult with complex subs of some Anime videos.~~
- ~~Use a pixel count rather than a fixed resolution. Meaning that if the video surface is larger than the subpic size, use a subpic texture that has same AR as the video surface. Also make this calculation smart so that it gives a nice scale factor for subpic->video, even if that means to use a little smaller texture than maximum.~~
- Measure the time it takes to renderer a subtitle. If this is longer than frame duration, then maybe dynamically adjust the texture size to improve performance?

**Comment by MadokaAyukawa** [comment]
It's sort of related so I'll put it here. 

The Allow Dropping of Subpictures if Queue is Late option is always grayed out for me. It was checked due to some older version (I've been using HC for a long time) and the only way to uncheck it was to edit the .ini file.

**Comment by clsid2** [comment]
It is only enabled when buffer is enabled.

**Comment by MadokaAyukawa** [comment]
Thank you.

**Comment by TinyTrbl** [comment]
> * Remove the Desktop and Video size options. 
> * Change default to something more reasonable such as 1920x1200.

**I do not know** how subtitles depends on resolution, but if possible then leave 1920x1200 resolution as an option, because if you remove "Desktop" option then it will not be possible to select this resolution on "outdated" 16:10 1920x1200px monitors...

**Comment by MadokaAyukawa** [comment]
>     * Remove the Desktop and Video size options. 4k desktop can give crap performance.

It seems as if some .ass tags are rendered as resolution dependent. In the issue mentioned here:

https://github.com/clsid2/mpc-hc/issues/1102

The difference in the blurring effect is due to the texture resolution set at Desktop (default) when viewed in fullscreen and is correctly displayed in fullscreen when the subtitle texture resolution is set to Video.

**Comment by clsid2** [comment]
Please attach the .ass file of that subtitle.
It should probably use PlayResX and PlayResY as maximum for texture resolution?

**Comment by MadokaAyukawa** [comment]
Here is a slightly modified version of that .ass file so the lines appear right away.

[Test.zip](https://github.com/clsid2/mpc-hc/files/6503543/Test.zip)

I believe using PlayResX and Y as the maximum texture resolution should resolve this issue. There are a few .ass files that do not contain the resolution information, but those tend not to have many override tags, if any at all. Any .ass file with more complex typesetting should contain the resolution information. Those that do not could probably use the texture resolution as defined in the options without issues.

Currently changing the texture resolution to Video can sometimes result in slightly blurry .srt subtitles using the Default Style as defined in the options as HC uses a lower texture resolution for lower resolution videos.

**Comment by clsid2** [comment]
After thinking about it, using PlayRes as maximum texture is a bad idea, because for some files it would give similar bad quality issues as the VIDEO setting due to low values.
The blur implementation itself could probably use PlayRes information to scale the blur strength. But that is low priority for me.

**Comment by ale5000-git** [comment]
What about use PlayRes as maximum texture but cap minimum to 1024x768?

**Comment by clsid2** [comment]
I am not going to do that. At least not anytime soon. I am not going into details why, as the code is too complex to explain. But texture size is not controlled by the subtitle parser. It is controlled by the subpic allocator of the video renderer. It also doesn't always use video size, but rather the padded video size (to have same AR as the window). Plus PlayRes may be totally different than the actual video size.

People should just configure a sane size in the options. Size mostly only has effect on performance, as everything is scaled properly. Only exception is blur strength, but that can probably be fixed in a different way.
I already know some people would want to override PlayRes to get better quality subtitles, so that is another reason to not use it.

**Comment by clsid2** [comment]
Implemented some of the improvements in 1.9.11.53
