### ISSUE TITLE
HEVC x265 issue

### ISSUE THREAD

**Issue by RichardLeblanc** [clsid2/mpc-hc#94]
The player freezes at a random point when playing hevc x265 videos, it doesn't happen in older versions like 1.7.14

**Comment by clsid2** [comment]
Provide a link to a file that has this problem. I have no problems with HEVC video. You may need to enable hardware acceleration in the video decoder settings. CPU decoding will give performance problems with high resolution videos.

Also clarify what you mean with 'freeze'. Is it a short hiccup in playback, or does the player become unresponsive?

**Comment by RichardLeblanc** [comment]
The player becomes unresponsive, I have to close the process manually. Tried a few videos/movies and always freezes at a random point and only with x265, as I said no problems with older builds, can't provide links.

My settings:

![Immagine](https://user-images.githubusercontent.com/47771443/56089840-8839b000-5e99-11e9-9fb4-70b7c776696c.jpg)

**Comment by clsid2** [comment]
It works fine for me and millions of others, so without a sample file it is impossible to fix!

What GPU do you have and what is your current driver version? Updating the driver might solve the problem.

**Comment by RichardLeblanc** [comment]
I'll update the GPU drivers, in case it didn't solve the problem I'll stick with an older build, thanks anyway!
