### ISSUE TITLE
Seekbar preview width setting not saving with values below 10 and above 30

### ISSUE THREAD

**Issue by Alpacalord** [clsid2/mpc-hc#941]
View > Options > Tweaks > Preview width
When using the arrows to adjust this setting it is clamped between 10 and 30, but you are able to manually enter a number which you can set beyond these bounds.
Doing so will cause this setting to not be saved.

(Note, a value below 10 doesn't affect its actual size. A value above 30 to a maximum of 40 does affect the size)

**Comment by clsid2** [comment]
Fixed
