### ISSUE TITLE
MPC-HC 1.9.9.45 almost fully hangs Windows 7 when doing a specific thing

### ISSUE THREAD

**Issue by Zero3K** [clsid2/mpc-hc#942]
When I keep going in and out of full-screen with "D3D Fullscreen" checked, it eventually causes the OS to  almost fully hang. I can get the OS to be usable again by pressing Ctrl+Alt+Delete and selecting Log Off.

**Comment by clsid2** [comment]
Then don't do that.

D3D Fullscreen is not an option I recommend using. I am not going to spend time on hunting down weird bugs like this that might actually end up being OS or driver bugs.
