### ISSUE TITLE
Discord rpc support?

### ISSUE THREAD

**Issue by Numerok** [clsid2/mpc-hc#946]
Discord has Rich Presence API, it can display some information like current file name and timestamp

"Display "Now Playing" information in Skype's mood message" is already in mpc-hc, RPC is like this, but better, so why not?

**Comment by clsid2** [comment]
I am not interested in implementing such features.

**Comment by Cikapkamuy** [comment]
That would be a nice feature to have

**Comment by jendorei** [comment]
Why Skype but not Discord? Arguably Discord is more popular than Skype now, it also has APIs for this kind of functionality.

**Comment by clsid2** [comment]
The presence of functionality X that was added long ago by someone else is not a valid argument at all for adding functionality Y. Certainly not since I have already said that I am not going to add it. I don't care about nor use Discord.

**Comment by Cikapkamuy** [comment]
You might not want it but other people do

**Comment by rollingmoai** [comment]
You might be interested in this project: https://github.com/angeloanan/MPC-DiscordRPC. There is also a request to add MPC-HC to PreMiD (https://github.com/PreMiD/Presences/issues/1514)

**Comment by frenesus** [comment]
This is a feature that will make me very happy, none of the others video players have.
