### ISSUE TITLE
15 second "Commercial Break in progress" countdown when opening twitch streams.

### ISSUE THREAD

**Issue by tordenflesk** [clsid2/mpc-hc#947]
See example:
https://i.imgur.com/DWyk91X.png

MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.10 (29a1254b5)
    Compiler:           MSVC v19.26.28806
    Build date:         Feb 25 2021

LAV Filters:
    LAV Splitter:       0.74.1.92
    LAV Video:          0.74.1.92
    LAV Audio:          0.74.1.92
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 6.1 (build 7601, Service Pack 1)
    Version:            6.1 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    GPU1:               NVIDIA GeForce GTX 1060 3GB (driver version: 27.21.14.6172)
    GPU2:               NVIDIA GeForce GTX 1060 3GB (driver version: 27.21.14.6172)

**Comment by clsid2** [comment]
This is not a bug in the player.

The streams extracted by youtube-dl contains this video intro. There is nothing I can do about it.

**Comment by ale5000-git** [comment]
@tordenflesk: You should report it here => https://github.com/ytdl-org/youtube-dl/issues

**Comment by clsid2** [comment]
They won't be able to fix it either.
