### ISSUE TITLE
Capture mouse on seek preview

### ISSUE THREAD

**Issue by k0dek0mmand0** [clsid2/mpc-hc#948]
When using the seek preview feature as a way to quickly scrub through the video while retaining current playing position it gets difficult to keep the mouse cursor moving straight in only horizontal direction. Sooner or later the cursor will miss the narrow seek bar rectangle in the vertical direction and the preview will close, which is super annoying to me.

To improve the UX I suggest adding a (transparent) panel beneath the preview rectangle (z axis) that would be full width of the main window and the height of the preview rectangle plus height of seek bar. This panel could then be the actual source of horizontal mouse movement instead of seek bar, thus reducing flickering whenever mouse cursor leaves the seek bar rectangle.

To close the transparent panel (and the preview itself), one would have to move the mouse outside its area. The panel would only open on hover of seek bar, or course.

Edit: If mouse position/movement can be retrieved directly, the additional panel is unnecessary. Only the conditions for closing the preview could change.

**Comment by clsid2** [comment]
If you use Dark theme, then you can increase the height of the seekbar in the advanced options.

Allowing a small area above seekbar to track movement for preview could be implemented.
