### ISSUE TITLE
Fast seek jumps on wrong keyframe

### ISSUE THREAD

**Issue by mikhaelkh** [clsid2/mpc-hc#949]
23.976fps video, keyframes every 120 frames. Fast seek on nearest keyframe with jump distance 10000ms jumps only 120 frames instead of 240 when video paused on a keyframe. When video is playing, multiple seeks at once forward ~10s each, but backward only ~5s each.

**Comment by clsid2** [comment]
Give an example file.

**Comment by mikhaelkh** [comment]
[sample.zip](https://github.com/clsid2/mpc-hc/files/6055208/sample.zip)

**Comment by clsid2** [comment]
Fixed
