### ISSUE TITLE
Remember Last Window Size vs Auto Zoom

### ISSUE THREAD

**Issue by adigourdi** [clsid2/mpc-hc#95]
In v1.8.5, there's this fix:

> Ignore auto-zoom setting when remember window size is enabled.

I couldn't find an issue discussing it, so I'm writing this.

I don't think this is an issue, and why ignore an option if it's particularly checked in the settings ?!

- I'd love to keep the window size as it was the last time it was open, instead of a small black square in my screen (I hide borders)
- And I'd like to open videos in their original size, to get an idea of the "quality" (720, 1080, ...)

If for someone this is an issue, they can just un-tick the checkbox of the feature they don't want ?

**Comment by clsid2** [comment]
Either you remember window size, or you auto-zoom, not both. You can press Alt+2 to resize to 100% of video size.

**Comment by adigourdi** [comment]
I do use alt+2 to reset zoom

The way I see remember size is in player startup, the player opens with the size of the last video that was played before closing, that's why it's named "Last" size, and not previous size

The same thing as in the "Last" window position, the position where the player was closed, since obviously the window isn't gonna move on it's own when switching videos

PS. sorry for confusing position/size in my original post, I see you got the meaning, I'll edit it

**Comment by clsid2** [comment]
I don't understand what problem you have.

**Comment by adigourdi** [comment]
Revert the "Fix", so it acts as :

- Player opens with last window size (before it was closed)
- Player auto zooms when a video starts

Now with the "Fix", it does :
- Either the player starts with it's original size (too small for no reason, around 240p instead of previous 720p+)
- Or, videos starts not zoomed 100%, and I need to Alt+2 every time a videos starts

If any one want to actually have it act this way, they can uncheck the box in settings,
So why limit it to us who want to keep the original behavior ?!

I'd love to have this reopened, so other users might give their opinion about the matter

Thanks anyway

**Comment by Hrxn** [comment]
Okay, the way I understand it, it's basically this:
- Last window size *and* auto zoom video (to 100%) both at the same time.

So, what happens in effect, if you open a file, it will zoom to 100%, and if you open MPC-HC *without* a file (i.e. just the program itself) it should have last window size?

**Comment by adigourdi** [comment]
Thank you

That's how it's always been, since Win XP days, why change it now and call it a "Fix"

Honestly, I thought this was a regression, and waited for an update, until I came and checked the changelog

**Comment by clsid2** [comment]
I am not changing anything. You should not enable remember window size if you want to watch videos at their original size. That option is for people who always want to watch video at the same size.

If you want to change the default size of the player window (without opened video), then you can do that by selecting a custom Logo image in the options. A larger image will increase the window size.

**Comment by adigourdi** [comment]
If they want to watch their video at the same size, they can just uncheck the Auto Zoom in options

I've always had both checked, and it was fine, and as expected

If you please care to explain, what's the problem that occurred in the original behavior ? before the fix that is

**Comment by clsid2** [comment]
The problem was that many people had the player not behaving as expected due to the auto-zoom interfering with remember window size. It is not intuitive to change two settings to make things work.

I am not changing it. So any further discussion is pointless.

**Comment by adigourdi** [comment]
I'll be happy if you show me where these people are, reading the discussion might make me agree, but until that, you're just being stubborn

As I said, if they have a conflict somehow, ask them to uncheck the auto zoom, by ignoring it for people who actually use it, you're just making a section in options useless for us

> I am not changing it. So any further discussion is pointless.

Rude, and stubborn. Unless you provide a test case that I or someone can replicate
Which you're not obligated it to, so .. meh 😒  I give up

**Comment by clsid2** [comment]
No, it is you who is stubborn and selfish. I have been providing support for MPC-HC for many years. So I do know what I am talking about. You can find several 'bug' reports on this subject on the old bug tracker. And there have been many in other places as well.

**Comment by adigourdi** [comment]
Sorry for the inconvenience
And thanks for the hard work, appreciated

**Comment by Cerlancism** [comment]
Just an opinion and question here, I do prefer the old way where auto zoom overrides the remember last window size 

My reason to enable remember last window size is that a maximised window will stay maximised overrides auto zoom.

Now it seems unable to achieve this behaviour, any work around?

**Comment by adigourdi** [comment]
None that I know of 😕
