### ISSUE TITLE
Adding imgs to to playlist from subfolder

### ISSUE THREAD

**Issue by hirezz** [clsid2/mpc-hc#950]
Not sure if there's an option to do this but haven't found it.
Example below
In folder A there are mp4 files and a subfolder called folder A2 that has img and mp4 files. When I drag folder A into the playlist of mpc-hc it grabs all the mp4 files but none of the imgs in folder A2. 

Is there a way or any work available to have mpc-hc read img files as valid file format to place into the playlist

**Comment by clsid2** [comment]
Options > Player > Formats > Other
Add the image extensions there. Then the player will include the image files as well.

It ignores images by default, because adding such files is generally unwanted.
