### ISSUE TITLE
Toolbar icons are black in dark theme

### ISSUE THREAD

**Issue by 9inpachi** [clsid2/mpc-hc#952]
Hi,

In dark theme, the toolbar icons do not change color. It seems the BMP toolbar isn't colored according to the theme.

I am not sure why the SVG toolbar isn't being used. Changing the scale (to 1.0f) when loading the image loads the SVG correctly and otherwise somehow (not a clue why) fallbacks to the BMP version.

https://github.com/clsid2/mpc-hc/blob/develop/src/mpc-hc/PlayerToolBar.cpp#L111

![image](https://user-images.githubusercontent.com/36920441/109425206-05785a80-7a09-11eb-8fb6-ff3e915b17dd.png)

**Comment by clsid2** [comment]
It looks like you enable the legacy toolbar option in the advanced settings. That doesn't work properly in dark theme.

**Comment by 9inpachi** [comment]
![image](https://user-images.githubusercontent.com/36920441/109425676-3eb1ca00-7a0b-11eb-8333-4fbd26d82754.png)

It's set to false. Tried toggling and reloading but doesn't work.

**Comment by 9inpachi** [comment]
BTW, in my debugging, the `AfxGetAppSettings().bUseLegacyToolbar()` is false too but yields the same result.

```cpp
!AfxGetAppSettings().bUseLegacyToolbar && SUCCEEDED(SVGImage::Load(IDF_SVG_TOOLBAR, origImage, dpiScaling * defaultToolbarScaling))
```

I just don't know why replacing `dpiScaling * defaultToolbarScaling` with `1.0f` or `1.5f` or `2.0f` makes it use the SVG toolbar. And using some value like `1.51111f` falls back to the BMP version.

**Comment by clsid2** [comment]
It must fail somewhere in NSVGimageToCImage().
What is your value of defaultToolbarScaling?

**Comment by 9inpachi** [comment]
It was `1.5` if I remember correctly. I will recheck.

EDIT: Yes, it's `1.5` indeed.

**Comment by 9inpachi** [comment]
> It must fail somewhere in NSVGimageToCImage()

The `SUCCEEDED` returns true though. 

`toolbarImageLoaded || (!AfxGetAppSettings().bUseLegacyToolbar && SUCCEEDED(SVGImage::Load(IDF_SVG_TOOLBAR, origImage, dpiScaling * defaultToolbarScaling)))` gets resolved to `false || (true && true)`

**Comment by 9inpachi** [comment]
Okay, the reason is because I have a custom scale of `105` in my windows display settings. You can most probably reproduce setting that value on your end as well..

**Comment by 9inpachi** [comment]
It seems the SVG load at least on my end is fine for default scale options like `dpiScaling => 1.0f | 1.25f | 1.5f |1.75f | 2.0f` work fine. Using anything in between like `1.1f | 1.2f | 1.72f` doesn't work.

**Comment by clsid2** [comment]
This also works fine me:
```
int targetsize = int(dpiScaling * AfxGetAppSettings().nDefaultToolbarSize);
float svgscale = targetsize / 16.0f;

SVGImage::Load(IDF_SVG_TOOLBAR, origImage, svgscale)
```
Basically making sure the scale is adjusted to match the size of the target bitmap, which is a rounded down integer value.
But the SVG code failing without error is something that should ideally be fixed as well.

**Comment by 9inpachi** [comment]
Good enough.
Thanks for looking into this. :)

> But the SVG code failing without error is something that should ideally be fixed as well.

I am not honestly well versed enough in Cpp to debug that. :(
