### ISSUE TITLE
Taskbar will appear over video in fullscreen and over window even with "On Top" is enabled

### ISSUE THREAD

**Issue by Gorrrg** [clsid2/mpc-hc#955]
When I play a video in fullscreen mode going all the way down to the bottom of the screen with the mouse cursor will make the taskbar appear over the video, sometimes clicking there is needed to make the taskbar appear. This also happens when I want to use the popup seekbar to skip the video. Only when clicking the taskbar button of MPC twice (twice because: minimizing it and maximizing it again) or into the fullscreen video twice (twice because: single left click pause/unpauses it) will this stop from happening. Quite annoying.

Also when I enable "On Top" in MPC (it doesn't matter which mode) and drag the MPC window half way over the taskbar clicking the taskbar will make it go over the MPC window.

```
Build information:
    Version:            1.9.10 (29a1254b5)
    Compiler:           MSVC v19.26.28806
    Build date:         Feb 25 2021

Operating system:
    Name:               Windows NT 10.0 (build 19042)
    Version:            10.0 (64-bit)
```

**Comment by clsid2** [comment]
The seek preview window can currently break "On top".

#921
