### ISSUE TITLE
Question About Fullscreen Mode

### ISSUE THREAD

**Issue by MadokaAyukawa** [clsid2/mpc-hc#956]
I have Launch Files in Fullscreen Mode and Exit Fullscreen at the End of Playback both checked.

If I double click on a file in Windows with MPC-HC not running, it opens in fullscreen mode as expected and exits at the end as expected. 

If I then play another file, by double clicking on a file in Windows, selecting a file from the Quick Open File dialog, or selecting a file from the Favorites or Recent Menus, it will open in windowed mode when I would have expected fullscreen mode.

Also, if I just open MPC-HC itself without opening a file, it will open in fullscreen mode when I would expect windowed mode.

I'm wondering if the last two instances are working as intended?

**Comment by clsid2** [comment]
It can be considered a bug. But this is not a priority for me, as I don't use this functionality myself.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1075

Should fix both issues.
