### ISSUE TITLE
Playlist Parameters - Doubt

### ISSUE THREAD

**Issue by ticao2** [clsid2/mpc-hc#96]
Playlist Parameters - Doubt  
As far as I know, there are **4** possible parameters in a Playlist:  
```
MPCPLAYLIST
1,type,0
1,filename,
1,label,
1,subtitle,
2,type,0
2,filename,
2,label,
2,subtitle,
...
```

Is there any other Parameter?  

In the **type** parameter, in my lists the value is always **0**.  
What is the meaning of the value 0?  
What are the possible values?  

When the Playlist file (**.mpcpl**) is in the **same folder** as the movie file, in the Parameters **filename** and **subtitle**, just put the **filename with the extension**.  
**Aquaman.2018.mkv** and **Aquaman.2018.pt.srt**  

**Otherwise** it is necessary to place the **complete Path**.  
**"G:\Movies\Aquaman (2018)\Aquaman.2018.mkv"** and  
**"G:\Movies\Aquaman (2018)\Aquaman.2018.pt.srt"**   

But, what if I need to determine a Subtitle from another language that is internal to the video file?
Is there a way to do this?  
Maybe just the **language code**? For example **en**, **eng**, **pt** or **por**?

**Comment by clsid2** [comment]
It is not possible to specify selection of embedded tracks in playlist file. But you can specify preferred languages in: options > playback > Default track preference

**Comment by ticao2** [comment]
Thanks for the quick response.
So, as for the parameters, they are just those **4**.

As for the subtitle languages, yes, I have already specified the languages I prefer, in the right order.
But, I have a **.mkv** file that has the wrong caption languages, changed.
Apparently those who converted put the list a language ahead.
They are almost all changed.
I think I'm going to have to edit .mkv

Thank you one more time.

ticao2

**Comment by 5rzmz8odb** [comment]
@clsid2 is it possible to create a .mpcpl to play all media in a folder and subfolders?

It will be efficient to add a parameter like ,folder, \\path to folder 😊

**Comment by clsid2** [comment]
Simply drag&drop a folder onto the player...
