### ISSUE TITLE
Getting DirectX End-User Runtime...June 2010 error opening vid after 1.9.9 (4aa0ed080) on Win10 x64.

### ISSUE THREAD

**Issue by TCCBodhi** [clsid2/mpc-hc#960]
After updating MPC-HC to the 1.9.9 version on a Win10 x64 machine, I get the DirectX error when opening a video. After clicking OK, the video then runs correctly (or seems to). 

I see solutions to this error from the 2010-2015 range, but I don't see anything from after HPC-HC was taken to open-source in 2017. Also, since DirectX is part of Win10, I haven't attempted these solutions.

Is this just a bug that will work it's way out, or do I need to correct in some way to get rid of this error? I'm not a coder, so easy directions would be helpful. Thanks.

**Comment by TCCBodhi** [comment]
I updated to 1.9.10 and issue is resolved. Sorry for the problem reporting.

**Comment by clsid2** [comment]
The required DirectX files are included with MPC-HC.

A clean Windows 10 installation does **not** include all available DirectX components by default.

**Comment by TCCBodhi** [comment]
Thanks for the info, and clarification on my assumptions. All I know is
that it appeared with v1.9.9, and resolved when I moved to 1.9.10. No need
to dig further if this hasn't appeared for others. Cheers.
