### ISSUE TITLE
UI scaling regression

### ISSUE THREAD

**Issue by Ede123** [clsid2/mpc-hc#961]
I noticed that some UI elements scale differently since MPC-HC 1.9.9.

For comparison (note the increased height of the status bar and the oddly sized buttons in the subtitle download dialog):
* MPC-HC 1.9.8 (6281da8a8)<br>![grafik](https://user-images.githubusercontent.com/904570/109579037-7e0a1480-7af8-11eb-859e-1a93b3988899.png)
* MPC-HC 1.9.9 (4aa0ed08a)<br>![grafik](https://user-images.githubusercontent.com/904570/109579281-e527c900-7af8-11eb-90e2-253c152815b2.png)

While the status bar is mostly cosmetic and wasting a few pixels, the subtitle dialog actually is harder to use because of this (It opens like that, with zero rows visible. You can also not reduce the horizontal size further in that case).

**Comment by adipose** [comment]
What dpi were you using?

**Comment by ArcticGems** [comment]
> 
> 
> What dpi were you using?

@Ede123 
Also what scaling/zoom are you using?
