### ISSUE TITLE
Seekbar preview uses fixed aspect ratio

### ISSUE THREAD

**Issue by Ede123** [clsid2/mpc-hc#962]
The seekbar preview seems to use a fixed frame size of 16:9. This results in black bars for other aspects. It would be great if the aspect of the preview frame could be adjusted to match the video aspect automatically (like the player window itself already does).

/cc @adipose

Example:
![grafik](https://user-images.githubusercontent.com/904570/109581087-105fe780-7afc-11eb-8be0-3e681d0a512b.png)

**Comment by lifegpc** [comment]
#959 same issue.

**Comment by Ede123** [comment]
Indeed, sorry for the noise,

Duplicate of #959.
