### ISSUE TITLE
Visual bugs of preview

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#963]
There are strange preview effects on MPC-HC 1.9.10.7 (c5cc102c3).

See:
1) ![1](https://user-images.githubusercontent.com/15793015/109808274-2f0ecd00-7c27-11eb-83fa-98250a0f39f1.png)
2) ![2](https://user-images.githubusercontent.com/15793015/109808709-be1be500-7c27-11eb-9005-6f5a11dabd1d.png)

**Comment by clsid2** [comment]
Doesn't happen here.

**Comment by ale5000-git** [comment]
It happened on Windows 7 by moving the mouse quickly.

**Comment by ale5000-git** [comment]
Sample file: https://www.sendspace.com/file/kl8udq

It happened on Windows 7 by moving the mouse quickly.

Filters currently loaded:
  - Internal Audio Renderer
  - MPC Video Renderer
  - Audio Switcher
  - LAV Video Decoder (internal)
  - LAV Audio Decoder
  - LAV Splitter Source (internal)

-------------------------------------

MPC-HC (Nightly, 64-bit)
------------------------

Build information:
    Version:            1.9.10.7 (c5cc102c3)
    Compiler:           MSVC v19.26.28806
    Build date:         Mar  1 2021

LAV Filters:
    LAV Splitter:       0.74.1.105
    LAV Video:          0.74.1.105
    LAV Audio:          0.74.1.105
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 6.1 (build 7601, Service Pack 1)
    Version:            6.1 (64-bit)

Hardware:
    CPU:                Intel(R) Celeron(R) CPU G540 @ 2.50GHz
    GPU:                AMD Radeon R7 240 (driver version: 27.20.14501.18003)

-------------------------------------

Windows 7 SP1
DirectX 9
Graphics adapter: AMD Radeon R7 240 (1002:6613)
VideoProcessor  : DXVA2 ProgressiveDevice
DeinterlaceTech.: none
Display: SMB2430L 1920x1080 60.000 Hz [Primary] windowed

**Comment by clsid2** [comment]
No issue here with that file.

Does your system have EVR? Maybe it only happens when VMR9 is used by the preview.

**Comment by ale5000-git** [comment]
I have set EVR on main video to test and EVR works:
```
Filters currently loaded:
  - Internal Audio Renderer
  - Enhanced Video Renderer
  - Audio Switcher
  - LAV Video Decoder (internal)
  - LAV Audio Decoder (internal)
  - LAV Splitter Source (internal)
```
DXVA is disabled.

Maybe the problem happens on the combination of ATI video card + Windows 7.
Do you have a system like this to test?

**Comment by clsid2** [comment]
Does it also happen with 1.9.10.0?
The time was moved from top of preview to bottom. It could be related to that change.

**Comment by ale5000-git** [comment]
I can try again on that pc on Monday.

**Comment by ale5000-git** [comment]
1.9.10.0
1) **OK**
2) ISSUE

1.9.10.7
1) ISSUE
2) ISSUE

1.9.10.16
1) ISSUE
2) ISSUE

**Comment by demolitioner** [comment]
It looks like you turned off aero in windows 7, which disables some features of desktop hardware acceleration and can lead to glitches.

**Comment by ale5000-git** [comment]
After some testing the problem can be reproduced by disabling the desktop composition (not just Aero) under visual effects tab inside performance (on Windows 7 can be easily done by the Windows settings).

So the problem 2 can be ignored because it is like before but problem 1 didn't exist before moving the time from top of preview to bottom so it was introduced by the change.

**Comment by adipose** [comment]
Did you try with this commit?  I see clsid2 added some code for redraws.

https://github.com/clsid2/mpc-hc/commit/e829b72272991e8b148294018920481e45f2bd2f

edit: I guess you should try without this commit, since it appears to have been done before the build you tried.

**Comment by ale5000-git** [comment]
I have tried both 1.9.10.7 and 1.9.10.16.

Was 1.9.10.7 before that commit?
If yes, I have tried both before and after.

**Comment by adipose** [comment]
I assume this is VMR9 related.

In a recent patch i made the window match the aspect ratio, thus avoiding the black bar "empty" area.  There's a good chance the opportunity for this glitch to occur is now gone.  That black area is drawn by the renderer in letterbox mode, so if it's glitchy, we probably can't fix it.  But hopefully, latest corrects this.

**Comment by clsid2** [comment]
I agree
