### ISSUE TITLE
Auto zoom

### ISSUE THREAD

**Issue by NBH-cloud** [clsid2/mpc-hc#964]
Hi,

AutoZoom behaviour seems to have changed, or I need to change my settings to have the same behaviour in 1.9.10  (i jumped from an old 1.7 ;-)  )

Playing 3 videos one after each other : 2160p, 1080p & 720p
Autozoom settings : 100% / 90% factor
Screen Resolution : 3440*1440

When playing 4K video, I used to have MPC reduce the video to 90% screen factor  (as it exceed my screen res)
switching to 720p or 1080p, I used to have MPC displaying the video at 100%, and adapting MPC window to fit it.  (720p=>1080p or reverse, always display 100% video and resizing MPC)

After upgrade, with the same settings, MPC now stick to its size (regardless of the video size) and never adapt the MPC windows to display a 100% video  (if possible, otherwise 90% screen res)

I looked in the issues or requests, and every case seems to have been fixed almost a year ago.

What am I missing ?

thanx

**Comment by MadokaAyukawa** [comment]
Try Auto-Fit (Larger Only)

**Comment by clsid2** [comment]
Yes, the auto-fit factor only has effect when you use auto-fit zoom.

**Comment by NBH-cloud** [comment]
thank you for your responses.

So I tried the new setting : Auto-Fit (Larger Only)

it partially worked : from 720p to 1080p, MPC windows resize to fit 1920*1080, but when I switch from a 2160p or 1080p to 720p, the MPC windows doesn't reduce to display 1280*720 à 100%
I need to manually choice ALT+2 - 100% zoom   (which wasn't necessary with MPC 1.7.3)
Same behaviour with Autofit.

Do I need to change one last setting ?
Thanx

**Comment by clsid2** [comment]
A new option would need to be added: 100% + Autofit larger
Current autofit options don't resize to smaller size if the video already fits in existing window.

**Comment by NBH-cloud** [comment]
yes probably, to get back the old behaviour.

obviously, I would gladly test it
