### ISSUE TITLE
Fluent Design

### ISSUE THREAD

**Issue by AAide** [clsid2/mpc-hc#965]
Hello

I can find out what the MPC-HC developers are doing to improve the look and are you going to develop a new interface like Fluent Design? Because the interface dates from the first windows, so a very very old interface that is at least 25 years old.

**Comment by butterw** [comment]
There's a fluent-ui toolbar, which looks quite good in dark mode and as I understand it there are some plans for UI improvements down the line.

- You would be refering to WinXp, not the first windows.
- Many new looks of the day have come and gone over the years. In MPC, C stands for classic.
