### ISSUE TITLE
Misalignment of PGS subtitle in "Save Image" function

### ISSUE THREAD

**Issue by FX8350** [clsid2/mpc-hc#968]
Playing 4K videos on the 2K (actually U-WQHD) monitor ~~using MPC Video Renderer~~ and take screen shots with subtitles by "Save image", the subtitles are misaligned.
![スクリーンショット 2021-03-04 231124](https://user-images.githubusercontent.com/10481430/109976301-f82bda80-7d3e-11eb-90c9-b987c38d20be.png)
![00002 mpls_snapshot_01 33 38 691](https://user-images.githubusercontent.com/10481430/109976327-ff52e880-7d3e-11eb-9129-678d2f36715b.jpg)

**Comment by FX8350** [comment]
This problem also seems to occur with the default video renderer (EVR-CP). 
(Note the unprocessed HDR to SDR).
![00002 mpls_snapshot_01 33 39 637](https://user-images.githubusercontent.com/10481430/112458793-87f20100-8da0-11eb-89d7-971bf546ee63.jpg)
I don't own any 4K and subtitled sources other than UHDBD, so I don't know if this problem is specific to UHDBD .m2ts.

**Comment by clsid2** [comment]
I have been able to reproduce this with PGS subtitle format.

**Comment by clsid2** [comment]
This is difficult to fix.

As a workaround you can use madVR as video renderer. That handles placing subtitles on screenshots by itself.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2623
