### ISSUE TITLE
Seek to previous keyframe behaves counter-intuitively

### ISSUE THREAD

**Issue by LukeRoss00** [clsid2/mpc-hc#97]
I usually use the jump to keyframe function to scrub forward and backward through video files, because it's faster and more responsive than the small/medium/large jumps. At least for me it is, on version 1.8.6.

While seeking to the next keyframe works as intended, i.e., I can press the associated key several times in succession and keep jumping forward, seeking to the previous keyframe only works once if the video is playing, because as soon as I release the button the video resumes playing, and when I press the button again the "previous keyframe" is actually the same keyframe as before.

What I suggest is changing

`rtMax = rtPos - 10000LL;`

in function `CMainFrame::OnPlaySeekKey()` to something like

`rtMax = rtPos - 5000000LL;`

so that if you seek again in, say, half a second you will actually keep going backwards instead of being stuck on the same keyframe.

**Comment by clsid2** [comment]
The normal jumps should also seek to keyframes. At least if "fast seek" is enabled in options>tweaks, and "AllowInaccurateFastSeek" in options>advanced. If not, there may be a bug.

I will think about your suggestion. Probably could do that conditionally based on playback state.

**Comment by LukeRoss00** [comment]
Curiously I had checked that AllowInaccurateFastSeek was set, but I had completely forgotten about Fast seek in Tweaks! Thanks, that did the trick
