### ISSUE TITLE
Color controls unresponsive.

### ISSUE THREAD

**Issue by Malora** [clsid2/mpc-hc#970]
Video is incredibly oversaturated and too bright and I'm unable to use color controls to correct the issue.

**Comment by clsid2** [comment]
For playback of HDR video you need to install a video renderer that supports HDR colors.

For example:
https://github.com/Aleksoid1978/VideoRenderer

Once installed you can select it in the player options.
Options > Playback > Output

**Comment by Malora** [comment]
That didn't have any effect.
