### ISSUE TITLE
Playback will stop when try to play UHDBD mpls on old gen GPU that doesn't support hardware decoding HEVC

### ISSUE THREAD

**Issue by FX8350** [clsid2/mpc-hc#972]
Video file formats such as mp4 and mkv will automatically play with software decoding even if HEVC codec are used on old gen GPU, but try to play UHDBD mpls, it will stop playing.
To play them,Need to unchecking the HEVC hardware decoding from the internal decoder settings.
Of course, if the GPU does not support it, the user should uncheck the box, but I think it would be better if the decoder automatically software-decode HEVC even if it is checked.

**Comment by clsid2** [comment]
That is strange because the decoder should already fallback to software decoding automatically.

Which GPU do you have?
Does it also happen if you open the m2ts file instead of mpls?

**Comment by clsid2** [comment]
Try with latest development build:
https://github.com/clsid2/mpc-hc/releases/tag/1.9.10.16

**Comment by FX8350** [comment]
I have a GeForce 750 Ti (Maxwell 1st Gen). 
And I tried the latest developer build, but mpls still won't play.
When I played m2ts directly instead of mpls, it was automatically software decoded and played fine (like mp4 etc).

**Comment by clsid2** [comment]
Please download DXVAChecker:
https://bluesky-soft.com/en/DXVAChecker.html
(download link is at bottom of page)

Then check if it shows "HEVC_VLD_Main" in the decoder device list. The driver might be offering hybrid acceleration (which is slow). If that is the case, then blacklisting the GPU deviceid might be solution.

**Comment by FX8350** [comment]
Thanks for the help.
I checked DXVA Checker.
It certainly shows "HEVC_VLD_Main".
The device ID shown in the device manager of my 750Ti is as follows
`PCI\VEN_10DE&DEV_1380&SUBSYS_36671458&REV_A2
`
![スクリーンショット 2021-03-14 100931](https://user-images.githubusercontent.com/10481430/111054142-62661d00-84ad-11eb-891b-c8fd4d838b52.png)

**Comment by clsid2** [comment]
@FX8350
Do you know if the UHDBD contains 8-bit HEVC or 10-bit?

@nevcairiel
Could you add an internal device blacklist to prevent using HWA on GPUs with slow partial acceleration? VLC also does this for a few Intel GPUs. If you are interested I could make a list of DeviceIDs.

Any idea why the fallback works when playing .m2ts, but not for .mpls? HEVC not correctly detected as 10-bit in latter case?

**Comment by FX8350** [comment]
All UHDBD I have are 10 bit,MediaInfo says so.

**Comment by Nevcairiel** [comment]
Its possible that the MPLS starts with a short 8-bit HEVC clip which gets detected, some logo or something, and that gets detected instead of the main movie. Can you copy-paste the pin info from LAV Splitter for the video when its failing?

Play -> Filters -> LAV Splitter Source -> Properties -> Pin Info -> [OUT] Video

As for blacklisting, I guess its a thing one could do, but a GPU that can competently decode 8-bit but not 10-bit might still remain.

**Comment by FX8350** [comment]
Here is pin info when its failing.

Note:I have noticed that mpc-hc64.exe has high CPU usage when playback failng.
CPU usage during .m2ts playback with software-decode on my system is about 30-40%, but during .mpls playback failng it goes to about 80-90%.
After a minute or so, it will drop to less than 10%.
```
Filter : LAV Splitter Source (internal) - CLSID : {B98D13E7-55DB-4385-A33D-09FD1BA26338}

- Connected to:

CLSID: {EE30215D-164F-4A92-A4EB-9D4C13390F9F}
Filter: LAV Video Decoder (internal)
Pin: Input

- Connection media type:

Video: HEVC 3840x2160 23.976fps

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Video {73646976-0000-0010-8000-00AA00389B71}
subtype: Unknown GUID Name {43564548-0000-0010-8000-00AA00389B71}
formattype: FORMAT_MPEG2_VIDEO {E06D80E3-DB46-11CF-B4D1-00805F6CBBEA}
bFixedSizeSamples: 0
bTemporalCompression: 1
lSampleSize: 1
cbFormat: 480

VIDEOINFOHEADER:
rcSource: (0,0)-(3840,2160)
rcTarget: (0,0)-(3840,2160)
dwBitRate: 0
dwBitErrorRate: 0
AvgTimePerFrame: 417083

VIDEOINFOHEADER2:
dwInterlaceFlags: 0x00000000
dwCopyProtectFlags: 0x00000000
dwPictAspectRatioX: 16
dwPictAspectRatioY: 9
dwControlFlags: 0x00000000
dwReserved2: 0x00000000

MPEG2VIDEOINFO:
dwStartTimeCode: 0
cbSequenceHeader: 348
dwProfile: 0x00000002
dwLevel: 0x00000099
dwFlags: 0x00000000

BITMAPINFOHEADER:
biSize: 40
biWidth: 3840
biHeight: 2160
biPlanes: 1
biBitCount: 15
biCompression: HEVC
biSizeImage: 15552000
biXPelsPerMeter: 0
biYPelsPerMeter: 0
biClrUsed: 0
biClrImportant: 0

pbFormat:
0000: 00 00 00 00 00 00 00 00 00 0f 00 00 70 08 00 00 ............p...
0010: 00 00 00 00 00 00 00 00 00 0f 00 00 70 08 00 00 ............p...
0020: 00 00 00 00 00 00 00 00 3b 5d 06 00 00 00 00 00 ........;]......
0030: 00 00 00 00 00 00 00 00 10 00 00 00 09 00 00 00 ................
0040: 00 00 00 00 00 00 00 00 28 00 00 00 00 0f 00 00 ........(.......
0050: 70 08 00 00 01 00 0f 00 48 45 56 43 00 4e ed 00 p.......HEVC.Ní.
0060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0070: 00 00 00 00 5c 01 00 00 02 00 00 00 99 00 00 00 ....\..........
0080: 00 00 00 00|00 00 01 40 01 0c 01 ff ff 22 20 00 .......@...ÿÿ" .
0090: 00 03 00 b0 00 00 03 00 00 03 00 99 14 86 03 00 ...°..........
00a0: 00 03 03 e9 00 00 5d c0 e8 00 00 00 01 42 01 01 ...é..]Àè....B..
00b0: 22 20 00 00 03 00 b0 00 00 03 00 00 03 00 99 a0 " ....°....... 
00c0: 01 e0 20 02 1c 4d 8d 14 86 92 42 97 84 3f ff c2 .à ..M.B?ÿÂ
00d0: 1f ff e1 0f ff f0 87 ff f8 43 ff fc 21 ff fe 10 .ÿá.ÿðÿøCÿü!ÿþ.
00e0: ff ff ff ff ff ff ff ff 08 7f ff ff ff ff ff ff ÿÿÿÿÿÿÿÿ.ÿÿÿÿÿÿ
00f0: ff 84 3f ff ff ff ff ff ff ff c2 1f ff ff ff ff ÿ?ÿÿÿÿÿÿÿÂ.ÿÿÿÿ
0100: ff ff ff e1 0f ff ff ff ff ff ff ff f0 87 ff ff ÿÿÿá.ÿÿÿÿÿÿÿðÿÿ
0110: ff ff ff ff ff f8 43 ff ff ff ff ff ff ff fe 10 ÿÿÿÿÿøCÿÿÿÿÿÿÿþ.
0120: ff ff ff ff ff ff ff ff 84 3f ff ff ff ff ff ff ÿÿÿÿÿÿÿÿ?ÿÿÿÿÿÿ
0130: ff e1 0f ff ff ff ff ff ff ff f8 43 ff ff ff ff ÿá.ÿÿÿÿÿÿÿøCÿÿÿÿ
0140: ff ff ff fe 10 ff ff ff ff ff ff ff ff 84 3f ff ÿÿÿþ.ÿÿÿÿÿÿÿÿ?ÿ
0150: ff ff ff ff ff ff e1 0f ff ff ff ff ff ff ff f9 ÿÿÿÿÿÿá.ÿÿÿÿÿÿÿù
0160: 78 0b 50 91 00 9b 65 00 00 03 03 e9 00 00 5d c0 x.P.e....é..]À
0170: f9 1a 08 37 00 00 be 8b 80 00 5f 58 40 00 17 d1 ù..7..¾._X@..Ñ
0180: 70 00 0b eb 0b e7 8f 1e 80 00 00 00 01 44 01 c0 p..ë.ç.....D.À
0190: 2c 93 03 b2 40 00 00 00 01 4e 01 81 01 0f 80 00 ,.²@....N....
01a0: 00 00 01 4e 01 00 0a 80 0a 71 e0 00 02 9c 78 00 ...N....qà..x.
01b0: 00 03 01 03 04 00 03 80 00 00 00 01 4e 01 89 18 ...........N..
01c0: 21 34 9b aa 19 96 08 fc 8a 48 39 08 3d 13 40 42 !4ª..üH9.=.@B
01d0: 00 98 96 80 00 00 03 00 32 90 04 03 69 01 0f 80 .....2..i..

- Enumerated media type 0:

Set as the current media type
```

**Comment by Nevcairiel** [comment]
The pin info is definitely for HEVC 10-bit. Since fallback isn't working I assume you might be using DXVA2-Native?

As far as I can see there should be no reason why MPLS should behave any differently.

**Comment by FX8350** [comment]
Yes, I'm using DXVA2-Native.
I've tried DXVA2 Copy-Back, D3D11, NVIDIA CUVID,that's fallback correctly and playback fine software-decoding.
The default item is alos DXVA2-Native, so I leave it as it is but should not use DXVA2-Native?

**Comment by Nevcairiel** [comment]
The fallback should hopefully be fixed in LAV Filters now

**Comment by clsid2** [comment]
Thanks for fixing.

> As for blacklisting, I guess its a thing one could do, but a GPU that can competently decode 8-bit but not 10-bit might still remain.

My idea would be to use a list of pairs: decoder profile -> VendorID+DeviceID
For example some Intel GPUs can do 8-bit HEVC just fine, but suck with 10-bit. So in that case blacklist HEVC_VLD_Main10 for those devices.

Possibly also add a maximum width/height value as well for extra flexibility. If those values are >0 then disallow HWA if video size exceeds the values.

**Comment by FX8350** [comment]
I disabled all internal filters, registered LAV Filters0.74.1.123-git as an external filter, and tested it.
DXVA2-Native was correctly fallbacked and mpls has playback with software-decoding now.
Thanks for the fix!
