### ISSUE TITLE
Playlists are not in numerical order

### ISSUE THREAD

**Issue by kyudaindo** [clsid2/mpc-hc#973]
If the playlist contains numbers, they will not be in order.
If the file name starts with "1,2,3.... .9,10,11", the playlist would become "1,10,11,2,3....".
Please improve this software so that the playlist is in numerical order "1,2,3....9,10,11".

**Comment by clsid2** [comment]
It does not change the order of items in a playlist file. Are you talking about adding files to playlist from Explorer context menu?

**Comment by clsid2** [comment]
You should change names to 01,02,...,10
Then alphabetical order is same as numerical.
