### ISSUE TITLE
fonts not works with Open URL

### ISSUE THREAD

**Issue by realfinder** [clsid2/mpc-hc#975]
using this sample https://cdn.filesend.jp/private/IzihIGRjyrAfyQ7X1-DvHK4O4p8yyuADYeeFLklkHp6v6VL8InY8CKA_n9P9S72k/test_with_font.mkv

**_edit: this link will last for few days only, so this is a backup one https://www.solidfiles.com/v/P4YdK3LPRMMjy (you can do some trick to get the hotlink from it every time)_**

it show as 
![image](https://user-images.githubusercontent.com/2512153/110248380-cce4fd80-7f81-11eb-8272-f643f17d4d4b.png)

and if we download it and then play it it will be
![image](https://user-images.githubusercontent.com/2512153/110248448-3ebd4700-7f82-11eb-8b11-f77c6aacfd5a.png)
and it work as it should

**Comment by clsid2** [comment]
It works like bottom picture here. Try with latest development build.

**Comment by ale5000-git** [comment]
@clsid2: Strangely I can confirm this weird behaviour with K-Lite Codec Pack 16.0.7 Mega Beta.

**Comment by realfinder** [comment]
the problem still there, work fine in mpc-be

plus, I note the mediainfo is not work too
![image](https://user-images.githubusercontent.com/2512153/151677816-9b973cca-4954-4fe6-8eae-9e10db1b98a7.png)

**Comment by clsid2** [comment]
Font still works fine for me. Resources tab in the properties shows 14 fonts.

MediaInfo only works for local files. I am not going to add support for online streams.

**Comment by realfinder** [comment]
Resources tab show them but as you can see in the image, they not work

**Comment by clsid2** [comment]
It works for me, so there is nothing I can do.

Make sure that you are using the internal filters and internal subtitle renderer.

**Comment by realfinder** [comment]
yes I note that with the 1st link they work as it should!

but with http://s02.solidfilesusercontent.com/ZWFlOGE0ZTViMjAxMDYzNjQ5NGU2ZmE1NjU3MDg3MjI4YjZjZTYxZToxbkR3cEg6T2p3R2lFZmRsVXIyd2lMdDNjX0ZhTGJ1Q01r/P4YdK3LPRMMjy/test_with_font.mkv they not! also [hfs](https://www.rejetto.com/hfs/?f=dl) links don't work (The main reason I did open this issue)

**Comment by clsid2** [comment]
I can reproduce the problem with the solidfiles link.

But since it only occurs with crappy file hosts, I am not not going to spend time trying to fix it. If behavior depends on the web server, then the server might not support certain needed functionality such as random access. Plus this is not a player problem, but rather one with the internal codecs, which are an external project.

Sorry, but I just don't care about this problem.
