### ISSUE TITLE
MPC-HC

### ISSUE THREAD

**Issue by jabadahut27** [clsid2/mpc-hc#976]
I just have a couple questions regarding the player, if you have the time.
1. When you refer to the -Renamed "System Default" video renderer to "Video Mixing Renderer 7". This to prevent people from thinking this ancient renderer is the preferred one. Do you think all movies even "ancient" ones redone in 1080p or even old divx (I am no professional nor programmer) should be watched using EVRCP? 
2. If so then would one assume that just adjusting your tv color display will effect it the same as VMR7/SD?
3.  Can I upload a file to someone, so they can explain to me why it's skipping? Thanks for any help.

**Comment by clsid2** [comment]
Why the hell do you think you need an old renderer to watch old videos. Sorry but these questions are so weird I can't even answer them.

**Comment by jabadahut27** [comment]
Well because the newer renderer makes old movies look too bright.

**Comment by jabadahut27** [comment]
The System Default or your rename makes older movies look right. Why the
hell is it there in the first place if it's so obsolete?

**Comment by clsid2** [comment]
If it is too bright it is the fault of your graphics driver.

This might help:
Menu > View > Renderer Settings > Output range

If something else works better for you then use something else. But problem is not fault of the renderer.
Also, EVRCP has been the default renderer in MPC-HC for many many years. The rename is totally unrelated to the default renderer in the player.

**Comment by jabadahut27** [comment]
Actually I had tried switching the Output Range. It didn't really affect
it. What do those settings mean  anyway? What worked was adjusting my tv
settings using the EVRCP. When I use EVRCP on 2160p files they look good.
Yes I did not think it was the renderer fault. It's just how it worked out
on my tv. Those settings 0-255, 16-235. To me it looks like the first
setting covers the 2nd?
