### ISSUE TITLE
[Feature Request] Hold to Pause

### ISSUE THREAD

**Issue by ivadham** [clsid2/mpc-hc#978]
Play/Pause (ID: 889), Play (ID: 887) and Pause (ID: 888) are OK, but I'm looking for a feature to pause as long as I hold down a key (Z for instance) and play as soon as I release that key.

**Comment by clsid2** [comment]
If your mouse has extra buttons on the side, then you could use those (X1 or X2). Mouse actions have an Down and Up state. You can assign pause to down and play to up.

I am not going to add any new functionality.
