### ISSUE TITLE
Missing subtitle freezes playback

### ISSUE THREAD

**Issue by VasaXter** [clsid2/mpc-hc#979]
I played mkv with "drag on" external subtitles.
I deleted both the video and the subtitles.
I restored from Bin the video, but not the external subtitle.
The internal subtitle was displayed differently now - with MPC preset, not the internal subtitle preset.
Trying to change the subtitle from picked internal to "no subtitle" when playing - OK.
Trying to change the subtitle from picked internal to "no subtitle" when paused - video freezes (MPC controls are fine, just unable to play the video until closed and opened again.

MPC-HC (64-bit)
---------------
Build information:
    Version:            1.9.10 (29a1254b5)
    Compiler:           MSVC v19.26.28806
    Build date:         Feb 25 2021
LAV Filters:
    LAV Splitter:       0.74.1.92
    LAV Video:          0.74.1.92
    LAV Audio:          0.74.1.92
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0
Operating system:
    Name:               Windows NT 10.0 (build 19042)
    Version:            10.0 (64-bit)
Hardware:
    CPU:                Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    GPU1:               NVIDIA GeForce GTX 960 (driver version: 27.21.14.6140)
    GPU2:               NVIDIA GeForce GTX 960 (driver version: 27.21.14.6140)

**Comment by clsid2** [comment]
Weird behavior is to be expected when you remove files. I have better things to do than fix this.

**Comment by VasaXter** [comment]
The same behavior occurs in less obscure situations, EG
When I download few different external subtitles, test them and then delete the unuseful/all of them (deciding to stick with the language in mkv).

**Comment by adipose** [comment]
Probably could validate the file was there when reloading it.  Not sure, I may take a look at some point.

**Comment by clsid2** [comment]
Does this bug still occur with latest version?

**Comment by VasaXter** [comment]
I tried to replicate the behaviour and the bug didn't occured.
