### ISSUE TITLE
Player hangs after pausing for extended periods and attempting to resume

### ISSUE THREAD

**Issue by Rage-X** [clsid2/mpc-hc#982]
Hi,

Thanks for all the work that you've been doing on this. I've encountered two issues so far:

1. Whenever I pause a video in the player, and go and do something else for an extended period - e.g. open a game, play it for 30mins, and close it - attempting to resume the video will result in the player hanging, and I have to close it at the task manager level.

2. When playing older video files with built-in subtitles, there are times when in the middle of the video, expected subtitle lines do not show up, and I have to jump back and forward again for the subtitles to appear.

Wonder if these are known issues? I think these two issues were not present in the older version of MPC-HC. Thank you.

MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.10 (29a1254b5)
    Compiler:           MSVC v19.26.28806
    Build date:         Feb 25 2021

LAV Filters:
    LAV Splitter:       0.74.1.92
    LAV Video:          0.74.1.92
    LAV Audio:          0.74.1.92
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 10.0 (build 19042)
    Version:            10.0 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    GPU1:               NVIDIA GeForce GTX 1070 Ti (driver version: 27.21.14.6089)
    GPU2:               NVIDIA GeForce GTX 1070 Ti (driver version: 27.21.14.6089)
    GPU3:               NVIDIA GeForce GTX 1070 Ti (driver version: 27.21.14.6089)

**Comment by clsid2** [comment]
When player freezes, right-click on it in task manager and choose "create dump". Zip/rar/7zip that file and upload it somewhere for me. For example sendspace.com/dropbox/google drive.

For subtitle issue try this:
Options > Subtitles > Sub pictures to buffer = 0
If you have a high resolution monitor, then it can also help to lower the "Maximum texture resolution" to 1080p.

**Comment by hell-racer** [comment]
I have an issue like the 1-st one - after a leave player paused for a long time (e.g. overnight) and then try to continue - video remains paused, but the audio continues as normal. The player app doesn't hang though, I can close it and then play the video as normal. I have version 2.2.1, Windows 11. Also have this problem in 1.7.13.  Should I open a new issue?

Memory dump:
https://drive.google.com/file/d/1wnD0uw0l4KVs6zqxR5iPbpD0bPp9GUdb/view?usp=drive_link

MPC-HC (64-bit)
---------------

Build information:
    Version:            2.2.1 (30fc3853b)
    Build date:         Apr 10 2024

LAV Filters:
    LAV Splitter:       0.79.2.0
    LAV Video:          0.79.2.0
    LAV Audio:          0.79.2.0
    FFmpeg compiler:    MinGW-w64 GCC 13.2.0

Operating system:
    Name:               Windows 11 (Build 23H2)
    Version:            10.0.22631 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    GPU:                NVIDIA GeForce RTX 3050 (driver version: 31.0.15.3734)
    Monitor:            \\.\DISPLAY1 - Philips 325B1L (31.5 inch Wide LCD MONITOR ) [2560x1440 32-bit 96 DPI] - [Current]

**Comment by clsid2** [comment]
Options > Advanced > ReloadAfterLongPause

**Comment by MD-78** [comment]
I also have these hangs (but only with MPC Video Renderer).
