### ISSUE TITLE
Only 1 GPU detected in the About dialog of MPC-HC

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#984]
Only 1 GPU is detected in the About dialog of MPC-HC.
It is strange because K-Lite Codec Pack detect both video cards.

```
MPC-HC (Nightly, 64-bit)
------------------------

Build information:
    Version:            1.9.10.16 (4769b8447)
    Compiler:           MSVC v19.26.28806
    Build date:         Mar  6 2021

LAV Filters:
    LAV Splitter:       0.74.1.114
    LAV Video:          0.74.1.114
    LAV Audio:          0.74.1.114
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 10.0 (build 19042)
    Version:            10.0 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    GPU:                Intel(R) HD Graphics 520 (driver version: 27.20.100.9077)
```

**Comment by clsid2** [comment]
Not a bug. This is limitation of Direct3D9. It only detect GPU connected to a monitor.

**Comment by ale5000-git** [comment]
@clsid2: Isn't possible to use Direct3D11?
This is a notebook and the two video cards can work concurrently if I'm not wrong.

![lav-settings](https://user-images.githubusercontent.com/15793015/110551111-35281080-8135-11eb-9331-84c0790991c4.png)
