### ISSUE TITLE
Player does not stay on top at all despite choosing "View>On Top>Always" or "View>On Top>While Playing"

### ISSUE THREAD

**Issue by noto10** [clsid2/mpc-hc#986]
Player does not stay on top at all despite choosing "**View>On Top>Always**" or "**View>On Top>While Playing**". This happens regardless whether player was started first or another application. As soon as focus is switched from player either using mouse or keyboard, player will move behind the application in focus.

Probably related to [https://github.com/clsid2/mpc-hc/issues/877#issue-799643581](https://github.com/clsid2/mpc-hc/issues/877#issue-799643581)

**MPC-HC (64-bit)**
---------------

Build information:
    Version:            1.9.10 (29a1254b5)
    Compiler:           MSVC v19.26.28806
    Build date:         Feb 25 2021

LAV Filters:
    LAV Splitter:       0.74.1.92
    LAV Video:          0.74.1.92
    LAV Audio:          0.74.1.92
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 10.0 (build 17763)
    Version:            10.0 (64-bit)

**Comment by Mrakobes666** [comment]
+1

**Comment by ale5000-git** [comment]
Have you tried MPC-HC 1.9.10.26?

**Comment by MadokaAyukawa** [comment]
.26 works correctly for me as I type this behind the HC window.

**Comment by Mrakobes666** [comment]
https://i114.fastpic.ru/big/2021/0316/e3/c28a63d31e1919f505447c61385514e3.png

**Comment by ale5000-git** [comment]
@Mrakobes666: From the screenshot you are using 1.9.10 and NOT 1.9.10.26
