### ISSUE TITLE
Some problems with playing the .mp4 videos

### ISSUE THREAD

**Issue by AndrewTCEC** [clsid2/mpc-hc#988]
My notebook has goth internal (Intel HD Graphics 620) and external videocard (Nvidia Geforce 940MX). For some reason when I try to start an .mp4 video, the player doesn't want to play it unless you "stop" the video and play it right from the start. For a fact, VLC 3.0.12 behaves fine on my notebook.

Any ideas why?

**Comment by clsid2** [comment]
Try disabling hardware acceleration in the video decoder settings. If that solves the problem, then I recommend updating the graphics drivers. This problem is usually fault of the driver.

**Comment by AndrewTCEC** [comment]
Eh, no problem, changed the video renderer (for some reason I had the old rendering on) and everything is fine. You can close the issue.
