### ISSUE TITLE
Window doesn't stay maximized after full-screen

### ISSUE THREAD

**Issue by Kono14** [clsid2/mpc-hc#993]
Steps:
1. maximize the player window --> play next video file --> window stays maximized
2. maximize the player window --> go to full-screen --> play the next video file --> exit full screen --> window is not maximized anymore

I'm not sure, if this is a bug or if my configuration is wrong. Relevant settings that I have:
- remember last window position = enabled
- remember last window size = enabled
- remember last pan&scan = disabled
- Auto-zoom = enabled with "Auto Fit" 100%

**Comment by Felipefpl** [comment]
I had the same problem, the config doesnt matter, also, if you set the window to maximized in the properties on desktop mpc will start maximized but after some time the config wont work again.

**Comment by clsid2** [comment]
"Auto Fit" 100% is not the same as a maximized state.

Disable auto-zoom and maximized state will be remembered correctly.

**Comment by Kono14** [comment]
Thanks for the explanation. I confirm it works as intended when auto-zoom is disbaled.
