### ISSUE TITLE
Jump to second chapter for multi-segment mkv's fails

### ISSUE THREAD

**Issue by hubblec4** [clsid2/mpc-hc#994]
Hi clsid

In version 
> MPC-HC (64-bit)
Build information:
    Version:            1.9.10 (29a1254b5)
    Compiler:           MSVC v19.26.28806
    Build date:         Feb 25 2021
LAV Filters:
    LAV Splitter:       0.74.1.92
    LAV Video:          0.74.1.92
    LAV Audio:          0.74.1.92
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

a jump to the second chapter (using the next chapter/file button), jumps always back to the first chapter.
If the video is behind the second chapter, a jump to the third chapters works, also for all following chapters.
But when a chapter is reached which belongs to a new/next file in the multi-segment chain a jump goes back to the "first" chapter of this file.

This version works:
> MPC-HC (Nightly, 64-bit)
Build information:
    Version:            1.7.10.276 (e15495d0a)
    Compiler:           MSVC v19.00.24215.01
    Build date:         Dec 26 2016 01:12:30
LAV Filters:
    LAV Splitter:       0.69.0.0
    LAV Video:          0.69.0.0
    LAV Audio:          0.69.0.0
    FFmpeg compiler:    MinGW-w64 GCC 6.2.0

it also works in version 1.9.7 stable, but after (include) 1.9.8 no more.

**Comment by hubblec4** [comment]
Samples says more then words.

[Multi-Segment mkv.zip](https://github.com/clsid2/mpc-hc/files/6137173/Multi-Segment.mkv.zip)

**Comment by Deses** [comment]
I also saw this today, and I could reproduce it with your sample files.

Another issue in `Hauptmenü.mp4` is that when going back from chapter 5, it goes back to 3 instead of 4.
And I can't go to the next chapter if I'm currently in chapter 3 or 6... sometimes... there are times where it works but skips chapters.

**Comment by hubblec4** [comment]
This issue occurs also on non-multi-linked mkv's. (mkv's with two editions)
Found while editing new mkv's.

**Comment by clsid2** [comment]
Fixed.

If there is less than 2 seconds between chapters, then it can jump backwards multiple chapters. That is intentional and required to allow jumping backwards smoothly instead of getting stuck. Previously that was 5 seconds.
