### ISSUE TITLE
Malformed screenshot path for some streams

### ISSUE THREAD

**Issue by reallyuniquename** [clsid2/mpc-hc#995]
I've recently encountered a stream with a newline character in its title. It goes directly into screenshot filename and makes resulting path invalid on Windows systems, i.e. file can't be saved without manually altering its name. 

```
youtube-dl -j
{"protocol": "m3u8_native", ..., "vcodec": "avc1.64002A", "title": "Stream title\n", "acodec": "mp4a.40.2"}
```
Probably other special characters should be stripped too.

Unfortunately that stream is no longer available so I don't have a quick way to reproduce this.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2612

I added three control characters that might as well be excluded.  1-31 could be, too, but I don't think that's likely for streams.
