### ISSUE TITLE
10bit encodes are not properly displayed in mpc-hc

### ISSUE THREAD

**Issue by nobananasforyou** [clsid2/mpc-hc#997]
Hello,

I've encountered an issue. 8bit and 16bit encodes display correctly in mpc-hc, however, 10bit encodes do not. I've attached said samples and have also made an image comparison: https://slow.pics/c/HI5ZcFEa 

Samples:
https://www.dropbox.com/s/kjcq56kweuzdpsz/test8.mkv?dl=0
https://www.dropbox.com/s/th7yjvzkj0dq46l/test10.mkv?dl=0
https://www.dropbox.com/s/q2w6u5vm6avlkym/test16.mkv?dl=0

Kind Regards, 
B.

**Comment by clsid2** [comment]
I think your encodes may be wrong. With full range instead of limited range the colors look better. You can see the difference with the "16-235 to 0-255" shader.

**Comment by nobananasforyou** [comment]
It seems there's a discrepancy, considering the output range for 10bit needs to be switched from "0-255" to "16-235", whereas 16bit encode doesn't require it. You can also confirm this issue by doing your own 10bit encode since the one I provided is said to be wrong.

**Comment by clsid2** [comment]
test16.mkv is 8-bit Ut Video
test10.mkv is 10-bit H.264

If you believe there is a bug somewhere, then you need to provide proof your files are correctly encoded.

**Comment by nobananasforyou** [comment]
Okay. Sorry about that. Now both 8bit and 10bit files are encoded with h.264 for clarity purposes. 

Image comparison:
https://slow.pics/c/MKu9Mw3T

Video comparison (H.264):
https://www.dropbox.com/s/99dwgwu7f2iyabb/test8.mkv?dl=0
https://www.dropbox.com/s/th7yjvzkj0dq46l/test10.mkv?dl=0

**Comment by clsid2** [comment]
Here both files decode the same and look like your 10-bit image. Also same in another player.

Your graphics driver might be applying additional image processing in the 8-bit case. If you have Intel or AMD then look in the driver settings and disable stuff like "adaptive brightness" and "fleshtone enhancement".
