### ISSUE TITLE
Playback>Output settings will not save if once access Internal Filters>Audio Renderer settings and didn't check the box

### ISSUE THREAD

**Issue by FX8350** [clsid2/mpc-hc#998]
Open Settings and go to Playback>Output and set the Audio Renderer to Internal Audio Renderer.
At this time, if you go to Internal Filters>Audio Renderer without pressing the Apply button, the "Internal Auidio Rendere Enabled" box will not be checked.
and If you go to another setting without checking that box, the Audio Renderer of Output setting will be lost. (revert to "system default").
To prevent this,I think the "Internal Auidio Rendere Enabled" box should be immediately checked when the audio renderer is set to the Internal Audio renderer in Output, or there should be a warning that "setting will be lost" when user move to another settings without pressing the Apply button. 

`MPC-HC (Nightly, 64-bit)`
`Build information:`
`    Version:            1.9.10.26 (b60774ab4)`
`    Compiler:           MSVC v19.26.28806`
`    Build date:         Mar 13 2021`

**Comment by clsid2** [comment]
Fixed
