### ISSUE TITLE
Video output corrupts after using screen capture

### ISSUE THREAD

**Issue by BubTheBozo** [clsid2/mpc-hc#999]
Whenever I try to capture a clip using Nvidia Shadowplay and then reload the video it causes it to have heavy visual glitches and artifacts.

![unknown](https://user-images.githubusercontent.com/80783586/111360732-681a5900-868d-11eb-9cd2-d5d60b77c7b3.png)

Mediainfo: https://pastebin.com/LJJ2pNmH

MPC-HC (Nightly, 64-bit)
------------------------

Build information:
    Version:            1.9.10.26 (b60774ab4)
    Compiler:           MSVC v19.26.28806
    Build date:         Mar 13 2021

LAV Filters:
    LAV Splitter:       0.74.1.114
    LAV Video:          0.74.1.114
    LAV Audio:          0.74.1.114
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 10.0 (build 19042)
    Version:            10.0 (64-bit)

Hardware:
    CPU:                AMD Ryzen 7 3700X 8-Core Processor
    GPU:                NVIDIA GeForce RTX 2070 (driver version: 27.21.14.6192)

**Comment by clsid2** [comment]
You need to report this kind of problems to NVIDIA.

I can't help you with this.
